### PR TITLE
Remove some class parameters related to Routing

### PR DESCRIPTION
**Pull request by lepiaf**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/21735
| License       | MIT
| Doc PR        | no

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
👍

**Comment by xabbuh** [comment]
I bet there will be users out there who rely on these parameters. At least, we should document this in the upgrade file.

**Comment by Tobion** [comment]
I'm totally in favor of removing this. But are you sure you want to do that BC break in 3.x?

**Comment by fabpot** [comment]
Let's keep that one for 4.0. @lepiaf Can you create a new PR on master (aka 3.3) with just a note in the UPGRADE/CHANGELOG file that those parameters are deprecated and will be removed in 4.0?

**Comment by lepiaf** [comment]
Should I create CHANGELOG-4.0.md file ? It does not exists yet.

**Comment by xabbuh** [comment]
@lepiaf The global changelog files are generated automatically. You can just add a new entry to the changelog file of the Routing component.

**Comment by fabpot** [comment]
Closing in favor of #21824

**Pull request closed without merging**
