### PR TITLE
[HttpKernel] fix handling of nested Error instances

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27613
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
This can happen when the exception controller is registered as a private service and was removed (now that we catch every `Error` instance): https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php#L48-L73

**Review by nicolas-grekas — COMMENTED** [review]
The "if" should be replaced by a ternary operator to select Exception or Error, to allow changing the previous of errors, isn't it?

**Comment by xabbuh** [comment]
Yes, I was under the false impression that the `Error` class doesn't have this property. Fixed now.

**Comment by xabbuh** [comment]
We could also merge this into 4.0 to account for the not so likely case that an `ArgumentCountError` is thrown during resolving the exception controller.

**Comment by nicolas-grekas** [comment]
Even 3.4 actually, but the check needs to be for Exception then, not Error, to account for polyfills.

**Comment by xabbuh** [comment]
indeed, done

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
