### PR TITLE
[FrameworkBundle] Simplify the configuration class

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

Spotted while documenting #58161.

### CODE REVIEW

**Comment by xabbuh** [comment]
This of is not exactly the same as the empty string would become an array with one element.

**Comment by stof** [comment]
@javiereguiluz only `trusted_hosts` and `trusted_headers` are impacted by that remark (as they don't perform a simple wrapping in array. Other changes in the PR are good.

**Comment by xabbuh** [comment]
@stof is right. I was reading the changes in my phone and didn’t realise that there were more changes.

**Comment by javiereguiluz** [comment]
Thanks for the review. I reverted the wrong changes.

**Review by xabbuh — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @javiereguiluz.

**Pull request merged**
