### PR TITLE
[WebProfilerBundle] Fix for CSS attribute at Profiler Translation Page

### PR DESCRIPTION
**Pull request by e-moe**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22107
| License       | MIT
| Doc PR        | none

### CODE REVIEW

**Review by javiereguiluz — COMMENTED** [review]
This was on my TODO list, so thanks for contributing it.

However, I'd like to propose some changes:

1) What if we also add the `nowrap` to `message.domain` (it's ugly to see `messages` split into several lines).

2) I'm worried about applying `nowrap` to `message.translation` because the translation can be incredible long. That's the usual case because apps use keys, so `message.id` is short and `message.translation` is long.

**Comment by e-moe** [comment]
@javiereguiluz , sorry for stealing items from your todo list :)

I do agree with length of `message.translation` and will update this PR. As for `message.domain` - currently it has additional styles like bold and small. I have doubts about visual appearance of this item with one more style applied

**Comment by javiereguiluz** [comment]
Here is the before/after if we add `nowrap` to domain and id but not the message:

before

after

---

It looks better now, right? so maybe we should add the `nowrap` to the translation domain after all.

**Comment by e-moe** [comment]
oh, sorry. got your point. thanks for you review! PR is updated

**Review by javiereguiluz — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Thanks for fixing this bug @e-moe.

**Pull request merged**
