### PR TITLE
[HttpFoundation] Make dependency on Mime component optional

### PR DESCRIPTION
**Pull request by atailouloute**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | 
| License       | MIT
| Doc PR        | 

Make the Mime component dependency optional

/cc @nicolas-grekas

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @atailouloute.

**Comment by GrahamCampbell** [comment]
I think this should be reverted. It breaks laravel/framework's 7.x branch which depends on symfony/http-foundation: ^5.0. When v5.1.0 comes out, it will be broken. I'd argue Laravel was not using symfony/mime implicitly, since it called code in http-foundation. It didn't make use of a non-direct dependency by bypassing http-foundation code. I think Symfony should wait until 6.0 before making this an optional dependency.

**Comment by GrahamCampbell** [comment]
// cc @taylorotwell

**Comment by nicolas-grekas** [comment]
Is Laravel 7 released? I'd suggest explicitly requiring symfony/mime on your side.
This change is planned for Symfony 5.1, which is unreleased also.
Note that this change is not covered by the BC policy. We already did so in the past and will continue to when needed.
Note also that in some specific cases, we decided to postpone the removal of some deps to the next major. This was done only for convenience. Here, I think you have plenty of time to adapt and you should. The change is easy enough to do.

**Comment by GrahamCampbell** [comment]
Laravel 7 will depend on ^5.0, which means once 5.1.0 is tagged, we'd have unexpected breakage.

**Comment by GrahamCampbell** [comment]
What was more concerning is that this change might be wanted in a symfony 4.4 patch release?

https://github.com/symfony/symfony/pull/35807#pullrequestreview-363080072

**Comment by nicolas-grekas** [comment]
Even if you add symfony/mime in your deps explicitly?

**Comment by GrahamCampbell** [comment]
We should be fine once we do that. My objection was to the principal of such changes.

**Comment by chalasr** [comment]
> What was more concerning is that this change might be wanted in a symfony 4.4 patch release?
#35807 (review)
I missed the PR that made made it optional recently, sorry. This is for master.

**Comment by nicolas-grekas** [comment]
> What was more concerning is that this change might be wanted in a symfony 4.4 patch release?

this won't happen, @chaslar must have been mistaken :)

> We should be fine once we do that.

that's the way to go then, this change is desired on our side (to me at least.)

**Comment by GrahamCampbell** [comment]
Ok. :)

**Pull request merged**
