### PR TITLE
[DoctrineBridge] Fix comment for type on Query::setValue (middlewares)

### PR DESCRIPTION
**Pull request by l-vo**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

See #46810 and #46744

### CODE REVIEW

**Review by dmaicher — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Can you please add a test case that would also fail on 6.1?

**Comment by nicolas-grekas** [comment]
OK, I see #46810
Please borrow the test case from there to this PR after #46810 is finished (and we'll then close it)

**Comment by l-vo** [comment]
@nicolas-grekas tests added :)

**Review by dmaicher — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @l-vo.

**Pull request merged**
