### PR TITLE
[HtmlSanitizer] add a method to the HtmlSanitizerConfig class to opt-in to allow all link schemes

### LINKED ISSUE #49030: [Html Sanitizer] There is no way to allow just any link scheme
### Symfony version(s) affected

6.2.2

### Description

Html Sanitizer has hard-coded default collection of protocols allowed in `<a href="url">` in `HtmlSanitizerConfig`:

```
    private ?array $allowedLinkSchemes = ['http', 'https', 'mailto', 'tel'];
```

There is a method `HtmlSanitizerConfig::allowLinkSchemes()` allowing to override it with custom list of allowed protocols. However, there is no way to just allow any protocol: to remove any restrictions from the URL's protocol.

This is already supported by `UrlSanitizer::sanitize()` but there is no way to pass `null` to `$allowedSchemes` which would remove any protocol related restrictions.

https://github.com/symfony/symfony/blob/1f7bc1098f0b03181095d35b11fa48523864e6f2/src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php#L32

https://github.com/symfony/symfony/blob/1f7bc1098f0b03181095d35b11fa48523864e6f2/src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php#L51

### How to reproduce

```php
<?php

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\HtmlSanitizer\HtmlSanitizer;
use Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig;

#[AsCommand(name: 'example')]
class ExampleCommand extends Command
{
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $customConfig = (new HtmlSanitizerConfig)
            ->allowElement('a', '*')
            ->allowLinkSchemes([]) // null would work but it's impossible because of typing; I don't want to hardcode any protocol here
        ;
        $sanitizer = new HtmlSanitizer($customConfig);

        $output =  $sanitizer->sanitize('<a href="news://somedomain.com">some text</a>');

        dd($output);
       // outputs: <a>some text</a>
    }
}

```

### Possible Solutions

- Allow null in `HtmlSanitizerConfig::allowLinkSchemes()` and related fields & getters.
- Reorganize configuration to make it possible in more elegant way, maybe create new `allowAllLinkSchemes()` method.

### Additional Context

This may need to be handled also in framework bundle: currently empty value (null, empty array) of `framework.html_sanitizer.sanitizers.XXXX.allowed_link_schemes` causes `HtmlSanitizerConfig::allowLinkSchemes()` to not be called at all.

https://github.com/symfony/symfony/blob/1f7bc1098f0b03181095d35b11fa48523864e6f2/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L2812

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #49030
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
AFAICT, the XSD is not compatible with this change right now.

**Comment by stof** [comment]
A separate `allow_any_link_scheme` boolean config setting is probably easier to understand than this `null` value triggering a special behavior (that is not safe from an XSS point of view as the `javascript:` scheme allows XSS for instance).

**Comment by xabbuh** [comment]
> that is not safe from an XSS point of view as the `javascript:` scheme allows XSS for instance

Thanks for the hint. I didn't think of that. Now I rather tend to say that we shouldn't provide my suggested solution as a feature.

**Comment by stof** [comment]
I agree about rejecting this feature as it could lead to unsafe configs without people realizing (if they are not aware of the `javascript` scheme for instance). A safe configuration would allow only the schemes it needs.

**Pull request closed without merging**
