### PR TITLE
[Workflow] Removed private Definition::addPlaces

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | "master"
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

There is no need for this method

### CODE REVIEW

**Comment by stof** [comment]
:+1: 
Status: reviewed

**Comment by xabbuh** [comment]
:+1:

**Comment by lyrixx** [comment]
Thanks @Nyholm.

**Comment by Nyholm** [comment]
Thank you for a quick review!

**Pull request merged**
