### PR TITLE
[TwigBridge] Update bootstrap_4_layout.html.twig

### PR DESCRIPTION
**Pull request by Oviglo**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Add 'form-control-range' for range input type.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
(for 4.4)
Can you please have a look at failing tests?

**Comment by Oviglo** [comment]
> (for 4.4)
> Can you please have a look at failing tests?

Yes, the test check if class name contains "form-control" but in Bootstrap doc the range input type need to have "form-control-range" : https://getbootstrap.com/docs/4.5/components/forms/#range-inputs

**Comment by nicolas-grekas** [comment]
> Yes, the test check if class name contains "form-control" but in Bootstrap doc the range input type need to have "form-control-range"

Sure, can you fix the tests please?

**Review by Nyholm — CHANGES_REQUESTED** [review]
Hey. 

Have a look how the current custom forms are implemented. (see the docs: https://symfony.com/doc/current/form/bootstrap4.html#custom-forms)

We should implement this in the same way.

**Comment by fabpot** [comment]
@Oviglo Are you still interested in finishing this PR?

**Comment by nicolas-grekas** [comment]
Closing as this staled.
@Oviglo please submit when you can!

**Pull request closed without merging**
