### PR TITLE
[Intl] JSON config - Croatian dinar doesn't exist

### PR DESCRIPTION
**Pull request by antonioperic**
Q | A
-- | --
Branch? | master
Bug fix? | yes
New feature? | no
BC breaks? | no
Deprecations? | no
Tests pass? | yes
Fixed tickets | -
License | MIT
Doc PR | -

We have only one currency, that is Croatian kuna. Croatian dinnar doesn't exist

### CODE REVIEW

**Comment by fxbt** [comment]
It doesn't exist anymore, but it is still present in the [ISO 4217 standard](https://en.wikipedia.org/wiki/ISO_4217#Historical_currency_codes).

**Comment by antonioperic** [comment]
@fxbt that is also a mistake, but I assume I cannot change that. Dinar was used in Yugoslavia, that country doesn't exist for almost 30 years. Same as currency

**Comment by emirb** [comment]
There are so many currencies defined here that don't exist anymore (i.e. UYP ended in 1975). I assume it's not an issue then, if the intent is to have all ever possible currencies?

**Comment by ro0NL** [comment]
ISO 4217 includes historical currencies: https://en.wikipedia.org/wiki/ISO_4217#Historical_currency_codes

So current JSON is fine IMHO, besides we don't own the data any way :)

**Review by unckleg — CHANGES_REQUESTED** [review]
It's the same Dinar or Kuna, should stay as it is.

**Comment by stof** [comment]
In any case, this data is never edited in Symfony directly. It is extracted from the ICU data, which is the source of truth. Any manual change would be lost the next time we update this from the ICU data.

**Comment by fabpot** [comment]
One change we could make is checking if there is a flag in the upstream data about historical currencies and making sure we do not import them.

**Comment by antonioperic** [comment]
@ro0NL in this case no, that not exist and is not any kind of usage. Croatian Dinnar is historical and not used in any case - not even banking, rates or anything.

**Pull request closed without merging**
