### PR TITLE
[Dotenv] Prefer loading .php files and change dumped file name

### PR DESCRIPTION
**Pull request by jack-worman**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Issues        | n/a
| License       | MIT

Makes `DotEnv::loadEnv()` prefer `.php` files over their respective non-.php version. In the same way I would prefer writing config files in PHP instead of yaml, I would prefer writing .env files in PHP.

To accomplish this I had to change the name of the dumped file because `.env.local.php` and `.env.local` had different priority tiers. Now they have the same priority tier and are consistent with other file names.

Example of new priority tiers with the output of the debug command:
```
Scanned Files (in descending priority)
--------------------------------------

 * ✓ Scenario2/.env.dumped.php
 * ⨯ Scenario2/.env.prod.local.php, ⨯ Scenario2/.env.prod.local
 * ⨯ Scenario2/.env.prod.php, ✓ Scenario2/.env.prod
 * ⨯ Scenario2/.env.local.php, ⨯ Scenario2/.env.local
 * ⨯ Scenario2/.env.php, ✓ Scenario2/.env
 ```

There is some cleanup to do still (.i.e update comments) but I wanted to see if the maintainers would entertain this PR before putting in more work.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This doesn't make sense to me.
Dotenv is a component to deal with standard env files as supported by *nix shells.
If you want to use php for such configs, just do so, you don't need a Symfony component for that.

**Comment by jack-worman** [comment]
> Dotenv is a component to deal with standard env files as supported by *nix shells.

I don't entirely agree with that because there is additional functionality already provided.
If I "just used" arrays, I would not be able to take advantage of functions like `bootEnv()`. And I would lose many integrations within Symfony (debug:dotenv, SymfonyRuntime, etc)

**Comment by nicolas-grekas** [comment]
Still, that's too much complexity, both in terms of added code and choice to make for users.
We prefer building on top of standards.

:-1: on my side with this reasoning sorry.

**Comment by jack-worman** [comment]
> Still, that's too much complexity, both in terms of added code and choice to make for users. We prefer building on top of standards.
> 
> 👎 on my side with this reasoning sorry.

I understand, thanks for your review!

**Pull request closed without merging**
