### PR TITLE
[Form] remove deprecated CSRF options

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
Should be rebased when #16722 is merged up to `master`.

**Comment by fabpot** [comment]
@xabbuh Done

**Comment by xabbuh** [comment]
rebased now that #16722 has been merged, this is ready to be reviewed

**Comment by Tobion** [comment]
:+1: 

Status: Reviewed

**Comment by jakzal** [comment]
:+1: status: reviewed

**Comment by Tobion** [comment]
Could you also remvoe the deprecation from security?

**Comment by xabbuh** [comment]
@Tobion Which deprecation do you mean?

**Comment by Tobion** [comment]
Thank you @xabbuh.

**Comment by Tobion** [comment]
I though the ones in Security/Http added in #16722. But they didnt make it in master apparently.

**Pull request merged**
