### PR TITLE
[Translation] fixed JSON loader on PHP 7 when file is empty

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

For PHP7 compat.

### CODE REVIEW

**Comment by fabpot** [comment]
I confirm that this fixes the PHP7 issue.

**Comment by stof** [comment]
:+1: But should it really be done in 2.5 ? It is not receiving bug fixes anymore since months. this is not a security fix.

Btw, it might be good to fix the existing test failure to bring the  branch back to green.

**Comment by fabpot** [comment]
ahah, 2.6 of course

**Comment by aitboudad** [comment]
:+1:

**Pull request closed without merging**
