### PR TITLE
[String] Transliterate & to and

### PR DESCRIPTION
**Pull request by Warxcell**
| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | kind of
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you please add a test case?

**Comment by Warxcell** [comment]
@nicolas-grekas I think it's also a good idea to be able to add custom behaviour in that slugger (for such replacements). I was thinking about callback. What do you think?

**Comment by nicolas-grekas** [comment]
> be able to add custom behaviour in that slugger

I don't think it's needed: decoration alreadt allows implementing custom behaviors to me.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Warxcell.

**Comment by Warxcell** [comment]
@nicolas-grekas kinda. You have to make your own instance of `UnicodeString`  before `AsciiSlugger`, 
then pass result from `->toString()` to `AsciiSlugger`. Or just use regular `str_*` or `mb_*` functions.


```
    public function slug(string $string, string $separator = '-', string $locale = null): AbstractUnicodeString
    {

        $string = new UnicodeString($string);
        $string->replace('XX', 'YY');
        //  do other stuffs

        return $this->asciiSlugger->slug($string->toString(), $separator, $locale);
    }
```

**Comment by nicolas-grekas** [comment]
yes
or you replace on the return point (`return parent::slug(...)->replace(...);`)
or you reimplement completely
etc

**Comment by Warxcell** [comment]
@nicolas-grekas no, not exactly. on return point everything is now replaced by $separator - it's too late to do anything else on this string anymore.
The other possibility is method to accept either string, either `AbstractUnicodeString`.

**Comment by nicolas-grekas** [comment]
Oh, indeed. The `string` barrier is not an issue to me, it's fine creating the object again inside.

**Pull request merged**
