### PR TITLE
Added .github/CODEOWNERS

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

---

refs https://help.github.com/articles/about-codeowners/

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
I suggested @lyrixx to submit on 2.7 so that we don't have to deal with any merge conflicts on this file. Sensible?

**Comment by nicolas-grekas** [comment]
@csarrazi can we add you to Ldap?
@jderusse to Lock?

**Comment by jderusse** [comment]
Totally :+1:

**Comment by fabpot** [comment]
If we were to do that, I suggest that we do it for everybody in this PR.

**Review by Simperfit — APPROVED** [review]

**Comment by lyrixx** [comment]
> If we were to do that, I suggest that we do it for everybody in this PR.

I'm not sure everyone deal with notifications in the same way. I prefer to let people decide.

**Comment by csarrazi** [comment]
@nicolas-grekas isn't there a requirement to be able to have write access to the repository for that feature?

In any case, sure, but as mentioned numerous times, I can not provide any sort of SLA on response time for tickets or notifications. In the medium term, if someone feels comfortable with this, I would be glad if anyone wished to take over the LDAP component.

**Comment by lyrixx** [comment]
PR Updated

**Comment by sroze** [comment]
I'm definitely happy to be in the Messenger one :)

**Review by sroze — APPROVED** [review]
Thanks

**Review by Tobion — APPROVED** [review]

**Review by csarrazi — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.

**Pull request merged**
