### PR TITLE
Mentioned the deprecation of deep parameters in UPGRADE files

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Branch | 2.8+ |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18058 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by jvasseur** [comment]
I think #18058 is about deprecating the `$deep` parameter of `ParamterBag::get`, not deprecating the `Request::get` method.

**Comment by javiereguiluz** [comment]
@jvasseur yes you are right. But if we explain the deprecation as *"Finding deep items in ParameterBag::get() is deprecated since version 2.8 and will be removed in 3.0."* most people won't understand it. This is in fact a huge BC break for some people because, as @zdenekdrahos said in his issue, upgrading to 3.0 will break their controllers (because they use `$request->get('foo')` instead of `$request->query->get('foo')`).

**Comment by jvasseur** [comment]
@javiereguiluz `$request->get` still exists and isn't deprecated in Symfony 3. what is deprecated is doing something like `$request->query->get('foo[bar]', null, true)` instead of `$request->query->get('foo')['bar']`.

**Comment by iltar** [comment]
This got me really confused because I've seen 0 deprecation notices in 2.8 regarding the get method to fetch request and query parameters. I think @jvasseur is correct about simply that notation being deprecated and removed in 3.0.

**Comment by javiereguiluz** [comment]
@jvasseur I'm really sorry. You were completely right from the beginning. I've updated everything using your nice example. Thanks!

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Comment by javiereguiluz** [comment]
Closing it because this was merged in https://github.com/symfony/symfony/commit/e65eac60c44a21978522728e4dc03ed67c12ae68

**Comment by Aliance** [comment]
Is this okay?

**Comment by sstok** [comment]
@Aliance that's indeed incorrect, good catch.

**Comment by Aliance** [comment]
Make PR for this: https://github.com/symfony/symfony/pull/20448

**Pull request closed without merging**
