### PR TITLE
[2.3][Component/Security] Fixed phpdoc in AnonymousToken constructor for user param

### PR DESCRIPTION
**Pull request by eriwin**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | yes, phpdoc one |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Updated phpdoc of AnonymousToken $user param from string to string|object since an object is allowed to in the parent AbstractToken: https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L91

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you also update the description to describe how the user must be built (like it is done [here](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Core/Authentication/Token/AbstractToken.php#L88-L89) too).

**Comment by eriwin** [comment]
@xabbuh Done. Do you also want me to update this description: https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Security/Core/Authentication/Token/PreAuthenticatedToken.php#L29 and if so in this PR or in a different one?

**Comment by xabbuh** [comment]
@eriwin You can do that in this PR too.

**Comment by fabpot** [comment]
Thank you @eriwin.

**Pull request closed without merging**
