### PR TITLE
[VarDumper] Add changelog entry for DateCaster

### PR DESCRIPTION
**Pull request by maidmaid**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
bof, not worth it IMHO, closing :)

**Comment by maidmaid** [comment]
Ok :), but... why yes in https://github.com/symfony/symfony/pull/23353 and no here? VarDumper is angry against the changelogs?

**Comment by nicolas-grekas** [comment]
my loose arg: the code in vardumper is mostly an internal detail for fancy outputs, to be compared to some class that you might actually use for your own use case in other components.

**Comment by maidmaid** [comment]
Thus, remove this incomplete changelog should be make sence.

**Pull request closed without merging**
