### PR TITLE
[BrowserKit] Fix bug when uri starts with http.

### PR DESCRIPTION
**Pull request by amouhzi**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by GromNaN** [comment]
Can you add a test on [Client::getAbsoluteUri](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/BrowserKit/Tests/ClientTest.php) ?

**Comment by jakzal** [comment]
duplicate of #14734

**Comment by amouhzi** [comment]
Tests added.

**Comment by fabpot** [comment]
Thank you @amouhzi.

**Pull request merged**
