### PR TITLE
[Debug] Fix log level of stacked errors

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
Can you explain what the fix is changing ?

**Comment by nicolas-grekas** [comment]
`self::$stackedErrors` holds errors that should be delayed. When it's time, they should be logged with exactly the same parameters that would have been used at the time they where triggered.
This was not the case for silenced errors and this PR fixes that.

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
any way to add a test?

**Comment by nicolas-grekas** [comment]
Test added

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
