### PR TITLE
[Form] Add context to FormFactory deprecations

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by stof** [comment]
@nicolas-grekas could you check why AppVeyor fails though ?

**Comment by nicolas-grekas** [comment]
@stof see #16813

**Comment by Tobion** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
