### PR TITLE
[Messenger] Fix amqp socket lost

### PR DESCRIPTION
**Pull request by GurvanVgx**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #42825
| License       | MIT
| Doc PR        | N/A

I'm taking the work done from someone else and and adding the remarks mentionned because there is no activity on this PR

PR: https://github.com/symfony/symfony/pull/47574

Network can fail in many ways, sometimes pretty subtle.

To avoid error messages "Library error: a socket error occurred", we detect when heartbeat as expired, and disconnect the chanmel connection, and force a reconnect.

Here a explanation to justify the condition :
https://www.rabbitmq.com/heartbeats.html#:~:text=Heartbeat%20frames%20are%20sent%20about,TCP%20connection%20will%20be%20closed.

### CODE REVIEW

**Comment by GurvanVgx** [comment]
I don't understand why test is failing

**Comment by nicolas-grekas** [comment]
Failures are unrelated I'd say. Can you please add `Miguel Fernandez <mfernandez@nuglif.com>` as co-author?

**Comment by GurvanVgx** [comment]
Done @nicolas-grekas

Thanks for the review :)

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @GurvanVgx.

**Pull request merged**
