### PR TITLE
[Yaml] Leverage array_is_list()

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]
Lovely 😍

**Comment by Nyholm** [comment]
Is this really a bugfix?

Ie, why not target 5.4?

**Comment by nicolas-grekas** [comment]
To save some potential merge conflicts, and benefit from the work on the polyfill I guess.

**Review by stof — APPROVED** [review]
this is consistent with the way we introduced usage of `get_debug_type` where we relied on the polyfill in older branches too.

**Comment by nicolas-grekas** [comment]
> this is consistent with the way we introduced usage of get_debug_type where we relied on the polyfill in older branches too.

ooch, actually we added `get_debug_type()` only on recent branches! That reverses the argument, updating for 5.4... :)

**Pull request merged**
