### PR TITLE
[PropertyInfo] remove conflict with symfony/serializer < 6.4

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by stof** [comment]
is symfony/serializer 6.3 actually compatible with property-info 6.4 ? We might have added this conflict for a reason.

**Comment by nicolas-grekas** [comment]
I think the reason was being overzealous. I tried locally, seems to work. Lets see the CI.

**Comment by stof** [comment]
Well, as you haven't change the dev requirement, the CI will still not try to use older versions.

**Comment by nicolas-grekas** [comment]
That's not the point: the point is to allow Serializer 5.4 to use PropertyInfo 6.4, which does work (verified by the CI).
That's what I mean by being overzealous: the conflict was added in good faith to match what require-dev says, but this is actually too restrictive, and excludes newer versions for no valid reasons for users of older stacks.

**Comment by xabbuh** [comment]
@stof not updating the constraint in `require-dev` was a mistake, #59010 fixed that

**Pull request merged**
