### PR TITLE
[Validator] Edit and add missing translations for Persian (fa)

### LINKED ISSUE #43490: Missing translations for Persian (fa)
Hello,

There are some missing translation for Persian (fa). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.fa.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by BahmanMehrdad**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43490
| License       | MIT

This PR is for edit and add missing translations for Persian (fa)

### CODE REVIEW

**Comment by ErfanBahramali** [comment]
Converting half-space (semi-space) to space is wrong

**Comment by BahmanMehrdad** [comment]
In some browsers (according to people in some cases) half-space (semi-space) is not considered and the words are stuck together. Therefore, it is better to consider this space for use in browsers. But I re-edited and restored semi-spaces.

**Comment by ErfanBahramali** [comment]
> In some browsers (according to people in some cases) half-space (semi-space) is not considered and the words are stuck together. Therefore, it is better to consider this space for use in browsers. But I re-edited and restored semi-spaces.

I had not heard
In which browsers?
They must be very old and obsolete
But in general, as far as I can see, this is not the case

**Review by BahmanMehrdad — COMMENTED** [review]
Final review

**Pull request closed without merging**
