### PR TITLE
[HttpFoundation] Fix FileBag issue with associative arrays

### PR DESCRIPTION
**Pull request by enumag**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |  #24546
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by enumag** [comment]
@szymach Can I ask for your review?

**Review by szymach — APPROVED** [review]
Checks out, thank you :)

**Comment by szymach** [comment]
Hello, any news on whether this will get merged?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @enumag.

**Pull request closed without merging**
