### PR TITLE
[TwigBridge] Fix namespaced classes

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 2.7 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #23072 
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by alOneh** [comment]
I do the same fix, too late... ;)

**Comment by GromNaN** [comment]
The [test needs to be completed](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Twig/Tests/NodeVisitor/TranslationDefaultDomainNodeVisitorTest.php).

**Comment by weaverryan** [comment]
Was this the only file that had an issue? It's the only one that caused issues for me, but I wasn't sure if possibly some bad find/replace caused issues in other files.

And yea... it's not technically needed, but it would be awesome if the test was extended to catch this - it's surprising to see an error like this not caught by a test.

And mostly, thanks for the fast PR :)

**Comment by fabpot** [comment]
Thank you @ogizanagi.

**Comment by ogizanagi** [comment]
> Was this the only file that had an issue? It's the only one that caused issues for me, but I wasn't sure if possibly some bad find/replace caused issues in other files.

@weaverryan : I confirm. I did an inspection for other class not found occurrences in the bridge and the bundle but didn't find anything else.

**Pull request merged**
