### PR TITLE
[DX][Finder] Add a simple way to get the first result of a finder

### PR DESCRIPTION
**Pull request by mcfedr**
| Q | A |
| --- | --- |
| Branch | master |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

I often find myself using the Finder find a single file, and currently not easy to access this one result. I think this would be a useful function.

I am not sure of the implementation, but couldn't see a better option.
I'm not sure why the `rewind` call is needed, but without it I always get a null result.

I'll add some tests if the idea is accepted

### CODE REVIEW

**Comment by iltar** [comment]
I've encountered this case myself somewhere in my codebase. It was resolved by foreaching and fetching the first result and breaking the loop. I think a method like this would help.

**Comment by jakzal** [comment]
Well, if we're adding `first()` shouldn't we also add `last()` for symmetry? :)

Looks like a reasonable thing to have anyway.

**Comment by iltar** [comment]
Maybe for completion we could add the `\Iterator` interface, I was already wondering why it was not there in the `first()` place.

**Comment by mcfedr** [comment]
Maybe `foreach` is a better implementation

    foreach($this as $file) {
        return $file;
    }

**Comment by mcfedr** [comment]
I like that, i'm going to change it. 

Maybe there is some sense in `last` but it seems less helpful, especially as (without lots of work) it will loop though all the matching files, and having a `last` method is a bit suggestive of a more efficient solution.

**Comment by nicolas-grekas** [comment]
Status: needs work

**Comment by nicolas-grekas** [comment]
What is the expected result when the loop is empty (in both first and last)? `null`? Is it correct? (I'm just asking, I didn't about it)

**Comment by mcfedr** [comment]
I think `null` makes complete sense for when nothing matches.

I'm unconvinced by the need for `last()`, `first` is useful because you are searching for just one file,

**Comment by xabbuh** [comment]
`null` looks right to me. Can you add a test case for it (this will make our intention clear for anyone looking at the tests in the future)?

**Comment by fabpot** [comment]
I'm :-1: on this one. The `Finder` class responsibility is "just" a way to configure a filesystem `Iterator`. So adding a `first()` method is out of the scope for this class.

**Comment by mcfedr** [comment]
@fabpot As a user of Finder, its something that helps me find files, not helps me get an iterator that helps me find files. Hence this helper function is useful. Its a function that I find myself writing again and again.

**Comment by fabpot** [comment]
I still think this is the wrong place. If this is really that useful, it should be added on the PHP iterator classes themselves.

**Comment by stof** [comment]
> I still think this is the wrong place. If this is really that useful, it should be added on the PHP iterator classes themselves.

Actually not in Iterator as this is the interface implemented by all iterators and so would force any iterator to reimplement it. It should probably better be ``first_element($iterator)``.

**Pull request closed without merging**
