### PR TITLE
[Form] fetch all known ChoiceType values at once

### LINKED ISSUE #50898: [Form] EntityType in forms generates too many queries
### Symfony version(s) affected

5.4.24

### Description

The EntityType field in forms generates too many queries in the POST action.

If field is multiple and user select about 15/20 options POST method add additional queries in each options.

I know that the EntityType want to check if selected option is in our database.
But why does it work in foreach and send query through each selected options.

In **ORMQueryBuilderLoader.php** there is a method called **getEntitiesByIds**.
But when we see how it works we can see that it works in foreach of our selected options.

When we add additional inserts and selections the database queries are too large.

### How to reproduce

`$builder->add('test', EntityType::class, [
            'label' => 'Label test',
            'class' => YourClass::class,
            'multiple' => true,
            'required' => false,
            'choice_label' => 'name',
            'choice_value' => 'id',
        ]);`

### Possible Solution

Maybe there is the chance to change this foreach to one request with all selected options with IN array.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50898
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
~shouldn't we also keep fetching them at once for expanded choice fields as well ?~

Forget that. The loop above for expanded fields does not call the choice list in that loop.

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
Is there a way to write a test ensuring that a submission of a multiple choice type calls `getChoicesForValues` only once during the processing, to prevent similar regressions ?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by elementaire** [comment]
For record, denied as bug fix for 4.4 #48208, accepted as feature and already merged in 6.3 #48342

**Pull request merged**
