### PR TITLE
Use try-finally where it possible

### PR DESCRIPTION
**Pull request by Koc**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Just a minior refactoring for using PHP 5.5 feature.

### CODE REVIEW

**Comment by Ener-Getick** [comment]
I don't think it will be merged as long as 2.x will be supported as it could create many merge conflicts for almost no gain.

**Comment by ro0NL** [comment]
Good point. Didnt really consider upstream merges on this :) not sure it will be that dramatic, but perhaps should be avoided.

**Comment by nicolas-grekas** [comment]
:+1:, less circumvoluted

**Comment by fabpot** [comment]
Thank you @Koc.

**Pull request merged**
