### PR TITLE
Update css for svg files in web profiler toolbar

### PR DESCRIPTION
**Pull request by yvh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | no
| License       | MIT
| Doc PR        | no

Update css for svg files in web profiler toolbar :
- Fix vertical-align (because some reset css like Bootstrap 4.1.2 add `svg:not(:root) {
    overflow: hidden;
    vertical-align: middle;
}`
- Fix scaling issue in IE9, IE10 and IE11 (I know IE is bad but ... :-) )

### CODE REVIEW

**Comment by ro0NL** [comment]
already fixed by #27941 ?

**Comment by yvh** [comment]
I've added `!important` on the css rule to be sure that's not overridden.
I have also fixed the IE issue.

**Comment by ro0NL** [comment]
Yeah but this PR targets a different selector; `.sf-toolbarreset *`, whereas the merged PR will target `.sf-toolbar-block .sf-toolbar-icon svg` (it's not merged up to master yet). Hence the question if it's still needed.

The IE issue seems valid, not sure :) but that's the scope of this PR then... right?

**Comment by yvh** [comment]
Indeed !

But for me, the css rule already exist in `.sf-toolbarreset *` selector. It's not necessary to duplicate this rule. Just improve it.
So what can I do ? Remove my modification and let rule for IE ?

**Comment by ro0NL** [comment]
well.. `!important` has downsides too :) im fine with the applied patch. Given the baseline issue is fixed, id turn this PR into fixing the IE issue;

- revert the baseline change (it's in 2.8 already)
- does the IE fix apply to 2.8? If so can you switch the target branch to it
- for visual changes a before/after screenshot would be nice :)
- make sure you dont break chrome etc. :P

**Comment by yvh** [comment]
I have closed this PR and created a new one. #27971

**Pull request closed without merging**
