### PR TITLE
[DoctrineBridge][Validator] remove unnecessary null check

### PR DESCRIPTION
**Pull request by scriptibus**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | - 
| License       | MIT
| Doc PR        | - 

Because this is a class constraint validator, the entity parameter cannot be null.

### CODE REVIEW

**Comment by HeahDude** [comment]
This is expected, otherwise this constraint cannot be used with optional values. All validators by design must ignore empty values to allow constraints on optional values. When values are required `NotNull`  (`NotBlank` if string) must be used in addition instead.

**Comment by scriptibus** [comment]
@HeahDude That's correct but only applies to property constraints and not to class constraints.

**Comment by linaori** [comment]
Can you verify that in a yaml or xml configuration this is impossible to be put on a property?

**Comment by HeahDude** [comment]
In theory, nothing prevents the API to be used as:
```php
$validator->validate($nullOrObject, [new UniqueEntity(['fields' => ['name']])]);
```
whatever the method used to resolve the graph, whatever the loader.

**Comment by scriptibus** [comment]
You're right. IMO it is not a good practice to use a class constraint in a way like this, but it is possible and therefore the null check is not unnecessary.

**Pull request closed without merging**
