### PR TITLE
[Serializer] Remove a now useless call to method_exists

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
please do bigger PRs, doing them line by line will take ages otherwise...
rebase needed to see tests green

**Comment by dunglas** [comment]
@nicolas-grekas it's the only one like this for this component ;)

**Comment by fabpot** [comment]
@dunglas There is a big overhead for a PR. So, in this case, this should be about all components, not just one of them.

**Comment by stof** [comment]
I agree with @fabpot and @nicolas-grekas  here. either you work by component, and then you clean *all* deprecations of the component at once, or you work by deprecation type on the whole codebase. But splitting both by component and deprecation type adds lots of review overhead (it only makes you move higher in the stats about the number of PRs opened by each dev, but this is not a worthy goal)

**Comment by nicolas-grekas** [comment]
Thank you @dunglas.

**Pull request merged**
