### PR TITLE
Fix missing compiled field while serializing Route

### PR DESCRIPTION
**Pull request by Nakard**
[Routing][2.4] Fix missing compiled field while serializing Route

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15645 |
| License | MIT |
| Doc PR | none |

### CODE REVIEW

**Comment by stof** [comment]
the 2.4 branch is not maintained anymore: http://symfony.com/roadmap?version=2.4

**Comment by javiereguiluz** [comment]
@Nakard thanks for submitting this fix. As @stof said, the 2.4 branch is no longer maintained. However, I'd like to ask you if you can reproduce this error in the other maintained Symfony branches, which at the moment are 2.3 and 2.7. Thanks!

**Comment by Nakard** [comment]
@javiereguiluz I was investingating the Routing Component because of test failures in [NelmioApiDocBundle](https://travis-ci.org/Nakard/NelmioApiDocBundle).

As you can see on this [travis build](https://travis-ci.org/Nakard/NelmioApiDocBundle/builds/77787370) the only failing version is 2.4, 2.3 and 2.7 works fine.

**Comment by Tobion** [comment]
ref #12329

**Pull request closed without merging**
