### PR TITLE
[Messenger][DX] Do not register a middleware unaware of MiddlewareInterface

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Providing a DX improvement:

**before (error at runtime):**
middleware-before

**after (error at compiler time):**
middleware-after

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Note from afar: every call to reflection at compile time makes compiling the container slower as more files need parsing + loading. We should not take these lightly or we might hurt DX. Maybe ok in this case I don't know, but I just wanted to be sure this is considered.

**Comment by nicolas-grekas** [comment]
(it OK here I suppose since this is a class from src/, which is already parsed for PSR-4 service definition.)

**Review by sroze — APPROVED** [review]
Makes sense to me 👍

**Comment by ogizanagi** [comment]
Perhaps unlikely to happen in this case, but each call to `Definition::getClass()` in a compiler pass acting before `ResolveChildDefinitionsPass` is subject to the same issue as https://github.com/symfony/symfony/issues/27259.

**Comment by yceruto** [comment]
What is the status of this PR after this https://github.com/symfony/symfony/pull/27413#issuecomment-393118841?

**Comment by ogizanagi** [comment]
Ignoring throwing this DX hint when `getClass()` returns `null` for such checks? (there are already some in this very same pass). Not convinced it'll be worth doing more.

**Pull request closed without merging**
