### PR TITLE
[SecurityBundle] use firewall-specific user checkers when manually logging in users

### LINKED ISSUE #57706: [Security] Security::login does not take into account custom user_checker
### Symfony version(s) affected

6.4.3

### Description

We have custom `user_checker` for main firewall and we have automatically called `Security::login` which does not take into account custom`user_checker` and calling `InMemoryUserChecker`

### How to reproduce

security.yaml
```
    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\User\UserChecker
```

after that just call `Security::login()` and UserChecker won't be called.

### Possible Solution

since already fetch `getFirewallConfig` we need to fetch userChecker and fetch it from container.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #57706
| License       | MIT

### CODE REVIEW

**Comment by chalasr** [comment]
Supersedes https://github.com/symfony/symfony/pull/54287 I think.

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @xabbuh.

**Comment by faizanakram99** [comment]
@xabbuh this is a breaking change, earlier user checkers were not called for programmatic logins, now they're.

This has been working like this for a number of years and now the behaviour changed.

**Comment by chalasr** [comment]
@faizanakram99 every bugfix breaks code that adapted itself to work with the bug. Defining a custom user checker implies that it replaces the default one but in this case the custom one was ignored, that is a bug.

**Comment by 94noni** [comment]
just to comment that this properly addresses my original issue, calling the login user checker accordingly, thx @xabbuh and @chalasr 

@faizanakram99 sad to hear that this break yours, can you detail your workflow of "security check" ? perhaps there is something different that may be done to satisfy both worlds

**Comment by faizanakram99** [comment]
@94noni We were relying on the behaviour which was changed here and our tests broke all of sudden after upgrade, took me a while to figure this out. We adjusted it already with the new changes, thanks.

**Pull request merged**
