### PR TITLE
Mention dropping PHP 7.1 support in VarDumper/CHANGELOG

### PR DESCRIPTION
**Pull request by spawnia**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

This is a pure documentation update.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you but I'm closing as this is true for all components - we won't do this for one of them - and we won't either for all of them :)

**Comment by spawnia** [comment]
I found it confusing that it is not there. As somebody who only uses a few Symfony Components here or there, the fact that Symfony 5 does not support PHP 7.1 is not common knowledge. (Is it even true in general?).

**Comment by nicolas-grekas** [comment]
`composer.json` files are here to declare this in all components, aren't you using composer?

**Comment by nicolas-grekas** [comment]
> Is it even true in general?

yes totally

**Comment by spawnia** [comment]
I do use composer.

In my case, someone else on the team added a dependency to `"symfony/var-dumper": "^5.0"` - but our setup is still on PHP 7.1. That meant i had to backtrack the latest version that supports 7.1, the CHANGELOG seemed like the most logical place to look for that information.

That is why i think it would be valuable to mention such changes there. I would be willing to add this to the CHANGELOG of the other components too. If you want to keep the maintenance effort low, maybe some kind at the top of each component's CHANGELOG could help, like:

```
Changes that affect the entire Symfony platform, such as dependency upgrades, are mentioned in [place].
```

**Comment by nicolas-grekas** [comment]
This looks more like a mistake in the prod vs dev process to me.
I think https://github.com/composer/composer/issues/8451 will provide the right solution.
Maintaining this in all components is not worth it to me: too much work (because no end date) and too little value.

**Comment by nicolas-grekas** [comment]
But I suppose we would merge a PR that does so for all components
branch 5.0 please :)

**Comment by IonBazan** [comment]
I think the best way to avoid such problems is to use:
```json
{
    "config": {
        "platform": {
            "php": "7.1.5"
        }
    }
}
```
to mock your current PHP version so that composer won't try to install a package incompatible with it.
https://getcomposer.org/doc/06-config.md#platform

**Comment by fabpot** [comment]
I would not merge a PR adding this in all components. We tend to not document things twice. As already said, the information is already part of the composer.json file.

**Pull request closed without merging**
