### PR TITLE
[WebProfileBundle] Avoid getting right to left style

### PR DESCRIPTION
**Pull request by Arman-Hosseini**
| Q             | A
| ------------- | ---
| Branch?       | >= 3.4 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | N/A   
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
IIRC, I think that the web profiler was compatible with right to left. Isn't the case anymore?

**Comment by Arman-Hosseini** [comment]
Hello @fabpot .
Thanks for reviewing.

It should not follow the right-to-left style because it's not interesting to display it.
It's best to stay with left-to-right.

**Comment by Arman-Hosseini** [comment]
Image

**Comment by derrabus** [comment]
Your screenshot looks like the default page should be fixed as well. 👀

**Review by fabpot — APPROVED** [review]
Got it now!

**Comment by fabpot** [comment]
Thank you @Arman-Hosseini.

**Pull request merged**
