### PR TITLE
Reviewed and Translated zh_CN

### PR DESCRIPTION
**Pull request by ZiYao54**
| Q             | A
| ------------- | ---
| Branch     |5.4
| Bug fix      | no
| New feature?  | no 
| Deprecations? |no 
| Issues        | Fix ##53018
| License       | MIT

Reviewed and add translations of the files below:
- [src/Symfony/Component/Security/Core/Resources/translations/security.zh_CN.xlf](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Core/Resources/translations/security.zh_CN.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.zh_CN.xlf](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Resources/translations/validators.zh_CN.xlf)

### CODE REVIEW

**Comment by ZiYao54** [comment]
I failed the Unit Tests (8.2, high-deps), but I don't really understand why? Can I please get some help...

**Review by nicolas-grekas — APPROVED** [review]
deps=high failures are unrelated to this PR

**Comment by ZiYao54** [comment]
> deps=high failures are unrelated to this PR

Alright! Thank You!

**Comment by nicolas-grekas** [comment]
Thank you @ZiYao54.

**Pull request merged**
