### PR TITLE
fix risky tests

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
@xabbuh is there a way to enforce that new tests should not be risky, to avoid having to do such cleanups in the future ? Can we make PHPUnit exit with a failure code on risky (once all our branches are clean) ?

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
The only option I found so far is `stopOnRisky`, but that does not change the exit code.

**Comment by xabbuh** [comment]
see #22387

**Pull request merged**
