### PR TITLE
enable tests on arm architecture

### LINKED ISSUE #19856: Failed tests on ARM
```diff
There were 2 failures:

1) Symfony\Component\Intl\Tests\NumberFormatter\Verification\NumberFormatterTest::testFormatTypeInt32 with data set #3 (NumberFormatter Object (), -2147483649.0, '2,147,483,647', '->format() TYPE_INT32 formats...range.')
 ->format() TYPE_INT32 formats inconsistently an integer if out of the 32 bit range.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2,147,483,647'
+'0'
/builddir/build/BUILDROOT/php-symfony-2.8.10-1.fc26.noarch/usr/share/php/Symfony/Component/Intl/Tests/NumberFormatter/AbstractNumberFormatterTest.php:184

2) Symfony\Component\Intl\Tests\NumberFormatter\Verification\NumberFormatterTest::testFormatTypeInt32WithCurrencyStyle with data set #3 (NumberFormatter Object (), -2147483649.0, '¤2,147,483,647.00', '->format() TYPE_INT32 formats...range.')
 ->format() TYPE_INT32 formats inconsistently an integer if out of the 32 bit range.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'¤2,147,483,647.00'
+'¤0.00'
/builddir/build/BUILDROOT/php-symfony-2.8.10-1.fc26.noarch/usr/share/php/Symfony/Component/Intl/Tests/NumberFormatter/AbstractNumberFormatterTest.php:207
FAILURES!
Tests: 1227, Assertions: 4883, Failures: 2, Warnings: 58, Skipped: 6.

```

### PR DESCRIPTION
**Pull request by smoench**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  |no 
| Deprecations? |no 
| Tickets       | Fix #19856
| License       | MIT
| Doc PR        | N/A

This draft enables arm64 support to detect possible compatibility issues.

### CODE REVIEW

**Comment by smoench** [comment]
@javiereguiluz @nicolas-grekas I could get the tests partly running but it seems travis ci arm64 virtual machine is very buggy. It randomly hangs and restarts plus there is no tty (probably related to LXC). Services like LDAP and Redis Cluster seems not to work

**Comment by nicolas-grekas** [comment]
Then we have to disable some network services / extensionsif they're not supported.

**Comment by Nyholm** [comment]
Is this needed? Shouldn’t php-src do this? I mean, if php runs on ARM then symfony will, right?

**Comment by smoench** [comment]
> Is this needed? Shouldn’t php-src do this? I mean, if php runs on ARM then symfony will, right?

@Nyholm This should be discussed in #19856 :-)

**Comment by javiereguiluz** [comment]
@Nyholm @smoench PHP source code is tested in ARM architectures: https://github.com/php/php-src/blob/562ceae7bcc3daa3845c2d31e2c3ba6c0c752775/.travis.yml#L76 so we'd only need to check the other dependencies.

**Comment by fabpot** [comment]
Any news here. If we are not able to run tests on Travis for now, let's close and reopen later.

**Comment by stof** [comment]
> Is this needed? Shouldn’t php-src do this? I mean, if php runs on ARM then symfony will, right?

Being tested on ARM does not mean that there is no difference.
php-src is testing on Linux and Windows, but we regularly have to deal with Windows-specific bugs (look at the Process component for instance)

**Pull request closed without merging**
