### PR TITLE
[Console] added a test case

### PR DESCRIPTION
**Pull request by OskarStark**
refs symfony/symfony-docs#5820

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @xabbuh

**Comment by xabbuh** [comment]
@OskarStark Not sure if this is the right test to change. Imho what is more interesting is the actual value the option will have later on.

**Comment by OskarStark** [comment]
You mean, we need a test like:
https://github.com/symfony/symfony/pull/16322/files#diff-dd210f55e046154a0a799b1d87d2ef2dR47

??

**Comment by javiereguiluz** [comment]
@OskarStark I guess @xabbuh means that you have to test that when you pass this option: `-a=bar` the value you get is `=bar` instead of `bar`

**Comment by xabbuh** [comment]
@OskarStark Exactly what @javiereguiluz said (sorry that I missed to reply here).

**Pull request closed without merging**
