### PR TITLE
[Serializer] add missing unit tests related to Encoder

### PR DESCRIPTION
**Pull request by FlorianLB**
Add some missing unit tests on the Serializer component.

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by dunglas** [comment]
:+1:

**Comment by fabpot** [comment]
I've just merged another PR which also added some tests, can you rebase? Thanks.

**Comment by FlorianLB** [comment]
Done.

I tried to merge in a relevant way the 2 versions of `JsonDecodeTest.php`, specially the `json_last_error_msg` part, hope it's fine !

**Comment by fabpot** [comment]
Thank you @FlorianLB.

**Pull request merged**
