### PR TITLE
[FrameworkBundle] Set the kernel.name properly after a cache warmup

### PR DESCRIPTION
**Pull request by jakzal**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16180 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by fabpot** [comment]
This needs to be merged in 2.3, right?

**Comment by jakzal** [comment]
Yes. 

Sorry for the wrong target branch :/

**Comment by fabpot** [comment]
No worries, just want to double-check :)

**Comment by fabpot** [comment]
Thank you @jakzal.

**Pull request closed without merging**
