### PR TITLE
[Validator] Added missing Macedonian translation

### PR DESCRIPTION
**Pull request by thunderer**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

Added missing translation for Macedonian with help from a professional translator. Related to https://github.com/symfony/symfony/issues/53296.

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. Same here, Can you also add 112? It was just added.

**Comment by thunderer** [comment]
@Nyholm sure, let's leave the PR open until it's ready.

**Comment by thunderer** [comment]
@Nyholm added key 112.

**Comment by nicolas-grekas** [comment]
Thank you @thunderer.

**Pull request merged**
