### PR TITLE
[WebProfilerBundle] AJAX links

### PR DESCRIPTION
**Pull request by mykiwi**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

It is considered as a new feature ? If yes, should I make it on 2.7 ?

Add a link on GET requests:
capture d ecran 2015-04-06 a 11 47 33

### CODE REVIEW

**Comment by sstok** [comment]
:+1: and yes its a new feature, but the maintainers should be able to merge to 2.7 without reopening.

**Comment by aitboudad** [comment]
:+1:

**Comment by romqin** [comment]
Could it be in 2.7 beta1 ?
ping @stof @fabpot

**Comment by stof** [comment]
this is a new feature, so it should go in 2.7.

:+1: from me. @fabpot I think we could still include it in 2.7-beta1

**Comment by romqin** [comment]
So should I recreate the PR ? Or you can merge it in 2.7 ?

**Comment by fabpot** [comment]
Thank you @romqin.

**Pull request closed without merging**
