### PR TITLE
[Debug] Scream as LogLevel::DEBUG (but for fatal errors / uncaught exceptions)

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14353 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by lyrixx** [comment]
:+1:

**Comment by stof** [comment]
what does it do exactly ?

**Comment by nicolas-grekas** [comment]
Screaming is a feature that allows logging of @-silenced PHP errors. (e.g. `@unlink($file)`)
In dev mode, screaming is enabled for all PHP error levels.
But in the logs we don't want a silenced PHP warning to come up as LogLevel::WARNING.
We'd prefer having to add `-vv` to app/console to see them

**Comment by stof** [comment]
yeah, looks good to me. :+1: 

Btw, it would be great to fix the deps=low tests

**Comment by xabbuh** [comment]
@stof see #14344

**Pull request merged**
