### PR TITLE
Revert changes I have made earlier and include files for translations in tagalog

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    |no
| Deprecations? | no 
| Tests pass?   | no
| Fixed tickets | none 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by stof** [comment]
Why are you renaming an existing file in this PR ?

**Comment by Simperfit** [comment]
Could you please rebase ?

fabbot.io failure is a false positive.

**Comment by ergiegonzaga** [comment]
Hi sir, how to rebase sir?

**Comment by nicolas-grekas** [comment]
Closing in favor of #26130

**Pull request closed without merging**
