### PR TITLE
[WebProfilerBundle] fix context log pre wrap

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Branch | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by HeahDude** [comment]
On try long context it is impossible to read or scroll the log.

I don't know if it's the best way to handle it though.

Before:
pre_before

After:
pre_after

**Comment by javiereguiluz** [comment]
I'm :+1: for the change. Thanks @HeahDude.

But I have a question: why don't you see the log contents in several lines? This is how I see this:

long_logs

**Comment by HeahDude** [comment]
I guess because it's an with a single key.

**Comment by HeahDude** [comment]
No, in fact I don't know :)

**Comment by HeahDude** [comment]
Ok I think I found it, working on a patch ;)

**Comment by HeahDude** [comment]
I pushed a second commit 209c819 which fix it, now looks like:
after_2

**Comment by javiereguiluz** [comment]
Thanks for working on this. However, I'm not sure about the second commit. The `ValueExporter` class is used in lots of places. This could "break" other things.

**Comment by HeahDude** [comment]
@javiereguiluz sure, I understand.

Still, if this class is meant to ease reading while debugging, it may help to not inline arrays just because they don't have nested arrays, my captures are good example.

Let me know if I should keep it like this, discard or squash this commit. Thanks.

**Comment by HeahDude** [comment]
@fabpot What do you think of 209c819 ? May it "break" things somewhere ?

**Comment by fabpot** [comment]
The ValueExporter class is only used for the profiler, so I think it won't break anything. You can probably browse all the tabs from a profile to confirm that it works well everywhere.

**Comment by HeahDude** [comment]
Thanks, I can confirm. If I'm not wrong my commit only increase readability for inline arrays.

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Pull request closed without merging**
