### PR TITLE
[HttpClient] fix tests

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

make sure that localhost always is resolved to the IPv4 loopback address 127.0.0.1

### CODE REVIEW

**Review by alexandre-daubois — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]

**Comment by GromNaN** [comment]
How is it possible that `localhost` doesn't point to `127.0.0.1` but other tests that make requests to localhost pass correctly?

**Comment by xabbuh** [comment]
Other places where `localhost` is resolved don't use `dns_get_record()`. That's the only difference. `dns_get_record()` returns empty arrays for both `A` and `AAAA` types.

**Comment by nicolas-grekas** [comment]
> dns_get_record() returns empty arrays for both A and AAAA types.

wait, that's a new behavior to me, we shouldn't hide it.

**Comment by nicolas-grekas** [comment]
Replaced by https://github.com/symfony/symfony/pull/58969/files#diff-7daae967be9e83a20ee3a39881b264c72fc830845306041fd24c2954a7777543R92
`gethostbynamel()` returns `127.0.0.1` for localhost, unlike `dns_get_record()`. (I guess `gethostbynamel()` uses more than the local DNS resolver to do its job).
Thanks for digging this.

**Pull request closed without merging**
