### PR TITLE
[FrameworkBundle] update argument value resolver pass tests

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Make sure to have at least one assertion per test.

### CODE REVIEW

**Comment by iltar** [comment]
Ah that's a good check to have :+1:

**Comment by xabbuh** [comment]
Well, I am actually not happy with this particular assertion, but every other assertion that came to my mind made even less sense.

**Comment by iltar** [comment]
Previously the only assertion was that nothing failed, so this is a better assertion than just that. At least you now check if it didn't get added anyway, despite not existing in the first place.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
