### PR TITLE
[WebProfilerBundle] Fix toolbar max-width for long ajax url

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?      | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Before : 
toolbar

After :
toolbar2

### CODE REVIEW

**Comment by ogizanagi** [comment]
I don't have this issue using 3.2. I think it was fixed silently in https://github.com/symfony/symfony/pull/19576.
So it should be fixed in 2.8, and I think it should use the same patch. See https://github.com/symfony/symfony/pull/20715 which is closer IMHO.

**Comment by NicolasPion** [comment]
@ogizanagi i have this issue on 3.2, look the screenshot, the column "xhr"

**Comment by ogizanagi** [comment]
Humpf, indeed. I missed that, sorry. 😕 

On my own side, no matter what length the url is, I cannot reproduce.

**Comment by NicolasPion** [comment]
@ogizanagi I think our font doesn't have the same width

**Comment by NicolasPion** [comment]
> @ogizanagi I think our fonts doesn't have the same width

@ogizanagi This is actually the reason for my issue ! ... forgive this PR ;-)

**Pull request closed without merging**
