### PR TITLE
[DependencyInjection] Fix manual ordering of arguments

### PR DESCRIPTION
**Pull request by GuilhemN**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        | 

I think we expect arguments to be reordered when the keys are numeric so here is the fix :)

ping @nicolas-grekas

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
nope, that's on purpose, to preserve bc

**Comment by GuilhemN** [comment]
ok, updated to a bc layer then

**Comment by nicolas-grekas** [comment]
why should we change something here? what's the benefit?

**Comment by GuilhemN** [comment]
If you want to mix named arguments with manual indexes, you'll currently get something weird:
```php
class Foo {
    public function __construct ($foo, $bar) {}
}
```
```yml
services:
    Foo:
        $bar: 'bar'
        0: 'foo'
```
`@Foo` will be instantiated as `new Foo('bar', 'foo')`... Imo we should either not support mixing named/indexed arguments or consider the indexes.

**Comment by nicolas-grekas** [comment]
are you sure? there is a ksort in ResolveNamedArgumentsPass:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/ResolveNamedArgumentsPass.php#L71

**Comment by GuilhemN** [comment]
Yes I added another test case to illustrate.

**Comment by GuilhemN** [comment]
Closing as discussed ;)

**Pull request closed without merging**
