### PR TITLE
[Translation] Add a hasId method

### PR DESCRIPTION
**Pull request by mbabker**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | https://github.com/symfony/symfony-docs/pull/4404 |

TODO List:
- [x] submit changes to the documentation

This method can be utilized to check if a message ID exists in the message catalogue

### CODE REVIEW

**Comment by aitboudad** [comment]
We can do this with `$translator->loadCatalogue($locale)->has($id, $domain)` and adding another function with no benefits seems wrong to me.
/cc @fabpot

**Comment by mbabker** [comment]
That does indeed work great if you're working within the context of a `Translator` object.  Unfortunately `loadCatalogue()` is a protected method so is unusable as a public API.  Making `loadCatalogue()` public would help in our scenario.

In the context that spawned this idea, we have an application which can be extended in a somewhat CMS like manner and that code (primarily for form fields) may supply a language key specific to its context and if the key does not exist we fall back to a generic key.

**Comment by stof** [comment]
@mbabker the public getter for the catalogue is ``$translator->getCatalogue()``

**Comment by aitboudad** [comment]
sorry it's [getCatalogue](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/Translator.php#L261) and not `loadCatalogue`
```php
$translator->getCatalogue($locale)->has($id, $domain)
```

also another issue here is there is two methods in catalogue, witch one we should use in `hasId`:  [has](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/MessageCatalogue.php#L95) or [defines](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/MessageCatalogue.php#L111) ?

**Comment by mbabker** [comment]
@stof Somehow I've missed that in the dozen or so times I've looked in Translator.  Thanks for that nudge.

@aitboudad I'd prefer `has` as it supports checking in your fallback catalogue as well.

**Comment by fabpot** [comment]
I'm not comfortable with the increasing number of methods added to various Symfony component, especially when there is current alternatives. I'm :-1: for this addition.

**Comment by stof** [comment]
I'm :-1: as well (especially given that this method is not usable by anyone relying on interfaces, in the opposite of the current way, and everyone should depend on the interface).

**Comment by aitboudad** [comment]
@mbabker unfortunately, seems not to have accepted, anyway I would like to thank you for taking time out into this feature

**Pull request closed without merging**
