### PR TITLE
[Form] Fix INT64 cast to float in IntegerType.

### PR DESCRIPTION
**Pull request by ovrflo**
Hello,

This is my fix for #18067. I also added a test for this bug.

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18067 |
| License | MIT |

Thanks !

### CODE REVIEW

**Comment by jakzal** [comment]
@ovrflo this change broke tests on windows, most likely because it's run on 32bit system.

**Comment by ovrflo** [comment]
@jakzal thanks for noticing :)

I added a fix that will make the tests pass. I mean, my last commit will revert to the old behaviour for 32-bit PHP, but that's not really a fix, is it ?

Another way to do it would be to check with strlen for big numbers on 32-bit and decide between INT32 and INT64 (for INT64 it will be casted to float).

// I'm starting to understand why doctrine refuses to cast my BIGINT columns to PHP's int :)

So, what now ?

**Comment by webmozart** [comment]
@nicolas-grekas Do you have any input here?

**Comment by nicolas-grekas** [comment]
Now included in #18179
Thank you @ovrflo

**Pull request closed without merging**
