### PR TITLE
[WebProfilerBundle] Display again the number of occurrences of log messages

### LINKED ISSUE #45183: [Profiler] Logs > Deprecations tab doesn't show how often a single deprecation is triggered
### Symfony version(s) affected

\>=5.4

### Description

Since SF >=5.4, The "Deprecations [n]" tab under Logs menu in the profiler doesn't show how many times a single deprecation is triggered.

I think this is linked to the [redesigned profiler logs](https://symfony.com/blog/new-in-symfony-5-4-redesigned-profiler-logs) feature (#42195)

### How to reproduce

You only need a fresh project with Symfony 5.3 and debug pack, then update to SF 5.4 to compare the results.

### Possible Solution

_No response_

### Additional Context

Symfony profiler in 5.3:

imageedit_7_2591027125
 

Symfony profiler in 5.4:

sf-5 4-profiler

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #45183
| License       | MIT
| Doc PR        | -

It looks like this:

log-occurrences

### CODE REVIEW

**Comment by javiereguiluz** [comment]
As @SVillette pointed out to me via Symfony Slack, the current profiler before this PR already displayed the "log counter":

image (1)

So, the real problem might be that the log counter of LoggerProfiler doesn't work.

@SVillette also mentioned that doing the following change in `LoggerDataCollector::getProcessedLogs()` solve the problem for them:

```php
$logs[] = [
  ...
  'errorCounter' => isset($rawLogData['errorCounter']) ? $rawLogData['errorCounter']->getValue() : 1,
  'errorCount' => $rawLog['errorCount'] ?? 1,  // The line I added to make it worked
  ...
];
```

I need help to know how to move forward with this. Thanks!

**Comment by nicolas-grekas** [comment]
This could qualify as a bug fix IMHO.
About the count, "15" looks like it's correct to me.

**Comment by SVillette** [comment]
Hi @nicolas-grekas, I will clarify a little about what has been done.

The issue is not about global count ("15") but the count per log ("5 times").
Symfony 5.4 added a new method `LoggerDataCollector::getProcessedLogs()` that introduced `errorCounter` when processing a single log, but the template (`Collector/logger.html.twig` at line 241) only display `log.errorCount` which is never defined.

```php
public function getProcessedLogs()
{
...
    $logs[] = [
...
        'errorCounter' => isset($rawLogData['errorCounter']) ? $rawLogData['errorCounter']->getValue() : 1,
    ];
...
    return $this->processedLogs = $logs;
}
```

```twig
{% macro render_log_message(category, log_index, log) %}
...
    {% if log.errorCount is defined and log.errorCount > 1 %}
         <span class="log-num-occurrences">{{ log.errorCount }} times</span>
    {% endif %}
...
{% endmacro %}
```

> " the current profiler before this PR already displayed the "log counter""

To reformulate what @javiereguiluz said, the template was already displaying the right information but the `LoggerDataCollector` does not pass the `errorCount` when getting the processed logs.

From what I debugged `$rawLogData['errorCounter']` is not defined and so `errorCounter` value is always 1. I cannot affirm this is always the case.

So that's why I just modified `errorCounter` by `errorCount` in the `LoggerDataCollector`. In addition, `$rawLogData` does not contain neither `errorCounter` nor `errorCount` so I just used `$rawLog['errorCount']`.

```php
$logs[] = [
    'errorCount' => $rawLog['errorCount'] ?? 1,
];
```

I hope my explanation are clear, I can open a PR if you consider it is a bug fix.

**Comment by SVillette** [comment]
Finally, I want to add that a global search on `errorCounter` only display `LoggerDataCollector::getProcessedLogs()` and `LoggerDataCollector::testCollectFromDeprecationsLog()`. I don't see any other usages.

**Comment by javiereguiluz** [comment]
Closing in favor of a better fix in #45302. Thanks!

**Pull request closed without merging**
