### PR TITLE
Remove direct dependencies on doctrine/common

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Resubmitting #27609 now that Doctrine should be deprecation free.

### CODE REVIEW

**Review by egircys — APPROVED** [review]

**Comment by lyrixx** [comment]
```

Testing src/Symfony/Bridge/Doctrine
...............................................................  63 / 234 ( 26%)
............................................................... 126 / 234 ( 53%)
............................S.................................. 189 / 234 ( 80%)
.............................................                   234 / 234 (100%)
Time: 2.27 seconds, Memory: 26.00MB
OK, but incomplete, skipped, or risky tests!
Tests: 234, Assertions: 484, Skipped: 1.
Remaining deprecation notices (1)
  1x: Doctrine\Common\ClassLoader is deprecated.
    1x in EntityTypeTest::setUp from Symfony\Bridge\Doctrine\Tests\Form\Type
```

**Comment by nicolas-grekas** [comment]
Needs https://github.com/doctrine/doctrine2/pull/7307 to be merged into doctrine/orm 2.7.

**Comment by nicolas-grekas** [comment]
Thank you @Majkl578.

**Comment by fmonts** [comment]
The deprecation warning is still present in Symfony 4.1.4, when will it be fixed?

**Comment by xabbuh** [comment]
@fmonts This is caused by `doctrine/orm` not having a fix released yet for some code that triggers this (see #28119 for more information).

**Comment by stof** [comment]
@fmonts the deprecation is *not* in Symfony at all. It is between doctrine/common and doctrine/orm

**Pull request merged**
