### PR TITLE
Fixed all tests

### PR DESCRIPTION
**Pull request by lyrixx**
| Q | A |
| --- | --- |
| Bug fix? | **YES - ALL** |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | **YES - ALL** |
| Fixed tickets |  |
| License | MIT |

I added it only on the main packages, should I add it also on all component / bridge ?

### CODE REVIEW

**Comment by csarrazi** [comment]
:trollface:

**Comment by stof** [comment]
@lyrixx sorry about your contribution, but my vote is a :-1: (even though the idea of the package is funny, but I already knew about it)

**Comment by jubianchi** [comment]
rofl!

**Comment by Mandragora2** [comment]
+1 j4f ;)

**Comment by stof** [comment]
@jubianchi you need the same package for atoum :smile: (and the question is whether Reflection will be needed to implement it)

**Comment by jubianchi** [comment]
@stof with atoum we won't need to work with reflection, it would just be a custom report ;)

**Pull request closed without merging**
