### PR TITLE
[DI] Fix "almost-circular" dependencies handling

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #19362, #24775
| License       | MIT
| Doc PR        | -

In a situation like the following one, we used to trigger a circular reference exception. But this was a false positive, as the reference is resolvable without hitting the circle. Fixing this exception could be considered as a new feature (because no existing config needs it, since it fails). But for 3.4, this should be considered a bug fix, as reported in #24775: not handling this situation now means creating broken service trees.

``` php
$containerBuilder = new ContainerBuilder();

$container->register('foo', FooCircular::class)->setPublic(true)
   ->addArgument(new Reference('bar'));

$container->register('bar', BarCircular::class)
    ->addMethodCall('addFoobar', array(new Reference('foobar')));

$container->register('foobar', FoobarCircular::class)
    ->addArgument(new Reference('foo'));

$foo = $containerBuilder->get('foo');
```

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
(fabbot failure is false positive)

**Comment by ogizanagi** [comment]
That means `FooCircular` will get in its constructor a `BarCircular` instance not fully configured yet (without `foobar`), right? Isn't it an issue?

**Comment by nicolas-grekas** [comment]
@ogizanagi how that? I don't think that's the case.

**Comment by ogizanagi** [comment]
Just trying to dump `$bar` in `FooCircular`'s constructor:

```php
BarCircular {
  +foobar: null
}
```

but that's actually the only way to solve the circular dependency AFAIU. Or did I miss something?

**Comment by nicolas-grekas** [comment]
@ogizanagi I'm sorry but I'm not able to reproduce your dump. I added type hints on the classes to ensure that `null` is not a possible value of the foobar property, and everything still works.

**Review by ogizanagi — APPROVED** [review]
As discussed together on Slack, this is fine actually 👍

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
