### PR TITLE
remove api tags from code

### PR DESCRIPTION
**Pull request by Tobion**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15977 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by stof** [comment]
:+1: 
status: reviewed

but I think the first step is actually to update the doc, to stop telling users about the distinction

**Comment by xabbuh** [comment]
see symfony/symfony-docs#5735 for the docs changes

**Comment by dunglas** [comment]
:+1:

**Comment by fabpot** [comment]
:+1: I propose that you merge this PR and then merge it to 2.7/2.8/master, doing the needed addons; that would be much more efficient than doing a PR for each branch.

**Comment by Tobion** [comment]
Merged in all branches. All api tags gone.

**Comment by fabpot** [comment]
\o/

**Comment by King2500** [comment]
What was the reason for this?

**Comment by stof** [comment]
@King2500 the explanation is in the issue: https://github.com/symfony/symfony/issues/15977

short version: the ``@api`` tagging has not been maintained at all since 2.3, which means it is now meaningless

**Comment by King2500** [comment]
I understand. 

:+1:

**Pull request merged**
