### PR TITLE
Change Fix to Close in PR template

### LINKED ISSUE #54049: PR template in Issues row should require to be more specific
### Description

PR template for Issues row is as follows:
`| Issues        | Fix #... <!-- prefix each issue number with "Fix #", no need to create an issue if none exists, explain below instead -->`

However not every PR is a **fix** so it might be misleading. I propose to use Fix for bug fixes and Close (or Resolve but Close sounds more familiar imo) for features.

### Example

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Close #54049
| License       | MIT

Currently PR template for `Issues` row is as follows:
`| Issues        | Fix #... <!-- prefix each issue number with "Fix #", no need to create an issue if none exists, explain below instead -->`

However not every PR is a **fix** so `Fix` does not fit here. I know the keyword can be changed by PR author but I can see most PRs have `Fix` so I bet people just leave the default and only paste issue number.
 
Let's move from `Fix` to `Close` as it is generic enough and fits for both, fixes and features.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I'm not sure this is needed: the more text we add, the less people read them. And this has never been an issue in practice.

**Comment by ghost** [comment]
> I'm not sure this is needed: the more text we add, the less people read them. 

OK, so maybe Close instead of Fix? Then the text will stay the same, just one word replacement in two places for this PR.

 > And this has never been an issue in practice.

Yeah, this is not an issue. More like better/clean vocabulary.

**Review by nicolas-grekas — COMMENTED** [review]
I'm fine with this change if that's of any importance, on branch 5.4.
(and I'm fine closing also ;) )

**Comment by ghost** [comment]
> I'm fine with this change if that's of any importance, on branch 5.4. 

Rebased onto 5.4 (don't look at the branch name, my mistake before creating PR).

**Comment by derrabus** [comment]
I'm not convinced we need this change. 🤷🏻‍♂️

**Comment by ghost** [comment]
> I'm not convinced we need this change. 🤷🏻‍♂️

Why? I understand your POV is "People leave Fix for features and it's just fine" but isn't the justification for the change valid? And what does it cost us to merge? Nothing.

**Comment by derrabus** [comment]
> And what does it cost us to merge? Nothing.

What does the change yield? Even less.

It's a nit-pick on an issue template that has served us well for over a decade. This discussion is already more expensive than this change deserves.

**Comment by OskarStark** [comment]
It's more about the action, Github take, it closes the referenced issue. Let's close it.

Thanks for proposing

**Pull request closed without merging**
