### PR TITLE
[Serializer] deserialize as a null when inner object cannot be created and type hint allows null

### PR DESCRIPTION
**Pull request by kbkk**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT

```php
class ObjectConstructorDummy
{
    protected $foo;
    public $bar;
    private $baz;

    public function __construct($foo, $bar, $baz)
    {
        $this->foo = $foo;
        $this->bar = $bar;
        $this->baz = $baz;
    }
}

class DummyWithNullableConstructorObject
{
    private $id;
    private $inner;

    public function __construct($id, ?ObjectConstructorDummy $inner)
    {
        $this->id = $id;
        $this->inner = $inner;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getInner()
    {
        return $this->inner;
    }
}
```

Trying to deserialize to `DummyWithNullableConstructorObject` with the following data currently fails:
```php
[
    'id' => 10,
    'inner' => null
]
```

With this PR `DummyWithNullableConstructorObject ` would be constructed with `null` passed as `$inner` because of the type hint.

### CODE REVIEW

**Review by dunglas — APPROVED** [review]
This can even be merged as a bugfix to me.

**Comment by fabpot** [comment]
Looks like a bug fix to me as well. Which version should it be merged to?

**Review by nicolas-grekas — APPROVED** [review]
OK for 3.4

**Comment by fabpot** [comment]
Thank you @kbkk.

**Pull request closed without merging**
