### PR TITLE
Fixes a typo in the form collector styles

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | none

Ping @javiereguiluz

### CODE REVIEW

**Comment by fabpot** [comment]
Good catch, thanks @romain-pierre.

**Comment by javiereguiluz** [comment]
@romain-pierre have you checked if this "fix" changes the style of that collector? Because maybe a better fix is to remove this entire style. Thanks!

**Comment by romain-pierre** [comment]
Hola @javiereguiluz, you are true, this directive may be removed.

**Comment by romain-pierre** [comment]
A new PR was created in #22104 to suggest complete removal.

**Pull request merged**
