### PR TITLE
Fixed dumpArray when passing an empty array

### PR DESCRIPTION
**Pull request by wouterj**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16266 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nerdstein** [comment]
@WouterJ is there a way to get this applied to the 2.8.* branch?

**Comment by WouterJ** [comment]
@nerdstein when this PR is merged, the code from 2.3 is merged into 2.7 and 2.8 and will be included in the next 2.8 release.

**Comment by fabpot** [comment]
@WouterJ Can you add a test?

**Comment by fabpot** [comment]
:+1:

**Comment by WouterJ** [comment]
Done

**Comment by xabbuh** [comment]
In the past, a change like this was rejected as we do not really know if the PHP array really was supposed to be a sequence or a mapping (see for example #9870). And this would also mean to break applications that rely on the current behaviour.

**Comment by fabpot** [comment]
hmm, @xabbuh is right, closing then.

**Comment by xabbuh** [comment]
Maybe we should introduce dumper options to let people do this (see #17520).

**Pull request closed without merging**
