### PR TITLE
Fixed the form profiler when using long form types

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17415 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Tobion** [comment]
:+1:

**Comment by iltar** [comment]
:+1: this should fix it indeed

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request merged**
