### PR TITLE
[HttpKernel] Fix override bundle config files

### PR DESCRIPTION
**Pull request by tkulka**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

`FileLocator` wasn't looking for the config file in `app/Resources/NameBundle/config` because not have the specified path in the arguments.

### CODE REVIEW

**Comment by iltar** [comment]
I don't want my kernel to automatically load all files in a bundle, what's the use-case for this? Afaik this is done by design.

**Comment by tkulka** [comment]
@iltar I also don't want to load all files in a bundle. Here is another problem. Sorry for the confusion and I'll try to explain. For example:

We use the `name/name-bundle` package in our application. This package is a bundle with `NameBundle` name and bundle have config files:
```
# vendor/name/name-bundle/src/Resource/app/config/foo.yml
foo:
  states:
    - new
    - pending_review
    - accepted

# vendor/name/name-bundle/src/Resource/config/app/bar.yml
bar:
  states:
    - new
    - pending_review
    - accepted

# vendor/name/name-bundle/src/Resource/config/app/config.yml
- { resource: "@NameBundle/Resources/config/app/foo.yml" }
- { resource: "@NameBundle/Resources/config/app/bar.yml" }
```

We import `NameBundle` config file to our application:
```
# app/config/config.yml
- { resource: "@NameBundle/Resources/config/app/config.yml" }
```

Now we want to override whole file `vendor/package/src/NameBundle/Resource/config/app/foo.yml` in app:
```
# app/Resources/NameBundle/config/app/foo.yml
foo:
  states:
    - new
    - accepted
```

Unfortunately it does not work because [FileLocator](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/Kernel.php#L679)  doesn't get the second argument which is app resource path. [Kernel::locateResource](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/Kernel.php#L244) will try to find files to override if the [$dir](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/Kernel.php#L260) parameter contains `Resources`, but $dir is a `null` in this case.

`Kernel::locateResource` may [override](http://symfony.com/doc/current/bundles/override.html):

- `app/Resources/NameBundle/config/routers`
- `app/Resources/NameBundle/views`
- ...

**Comment by tkulka** [comment]
ping @symfony/deciders :)

**Comment by fabpot** [comment]
There is no inheritance mechanism for the config files in a bundle, and we don't want to introduce one. Closing as a won't fix.

**Pull request closed without merging**
