### PR TITLE
[Validator] Fix init of YamlFileLoader::$classes for empty files

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20761
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by stof** [comment]
Would it be possible to write a test covering the actual bug (i.e. checking that ``getMappedClasses`` works) instead of asserting the internal property ? it would be more reliable (the class is free to do what it wants with its private property as long as the public API works fine)

**Comment by nicolas-grekas** [comment]
The property is protected, so it's a "public" side effect, which means the test is good :)

**Comment by nicolas-grekas** [comment]
@stof is this PR ok for you?

**Comment by nicolas-grekas** [comment]
Note that this PR is against 2.7. `getMappedClasses` exists only on 3.2

**Comment by stof** [comment]
:+1: 
Status: reviewed

**Pull request merged**
