### PR TITLE
[Debug] Add symfony_debug_backtrace() and use it when dealing with fatal errors

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

This takes a subset of #12159 that would be great in 2.7, and uses it to gather back traces of fatal errors when possible.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Tests are green for what is related to this PR, ready to merge/vote

**Comment by stof** [comment]
Regarding the C extension, I still don't know what the strategy is to expose it @fabpot. IIRC, you said you would write a blog post about it a long time ago, but I don't remember seeing it. It would be great to know how we deal with them.

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by sstok** [comment]
Will there also be a DDL download at some point?

**Comment by nicolas-grekas** [comment]
Help from someone familiar with building on Windows would be required

**Pull request merged**
