### PR TITLE
[DependencyInjection] definitions are valid objects

### LINKED ISSUE #34480: Service Container Linter and `object` typehint
**Symfony version(s) affected**: 4.4.0

**Description**  
When i execute `lint:container` i get this error:
```
$> symfony console lint:container

In CheckTypeDeclarationsPass.php line 159:

   Invalid definition for service "sylius.translation.translatable_listener.doctrine.orm": argument 2 of 
   "Sylius\Bundle\ResourceBundle\EventListener\ORMTranslatableListener::__construct"
   accepts "object", "Sylius\Component\Core\Translation\TranslatableEntityLocaleAssigner" passed. 
```
Is it correct that service container linter has this behaviour against `object` typehint?

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34480
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by ogizanagi — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
I'm wondering if this should not be deprecated in 5.1. WDYT?

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by nicolas-grekas** [comment]
Deprecating what? This pass is new to 4.4 :)

**Comment by fabpot** [comment]
Deprecating the possibility to pass a definition.

**Pull request merged**
