### PR TITLE
[DependencyInjection] PhpDumper.php: hasReference() shouldn't search references in lazy service.

### PR DESCRIPTION
**Pull request by antanas-arvasevicius**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | yes |
| BC breaks? | no |
| Tests pass? | yes |
| Fixed tickets | #19901 |
| License | MIT |
| Doc PR | N/A |

more info:
https://github.com/symfony/symfony/issues/19901

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Will this also solve https://github.com/doctrine/DoctrineBundle/issues/562?

**Review by lemoinem — CHANGES_REQUESTED** [review]
Hello,

Thank you very much for your contribution... Could you re-insert the complete PR summary at the top of your PR. If a line seems irrelevant for your PR, just put N/A instead of removing it.

I think it would also be a nice touch to add a test for this behavior so we make sure the bug doesn't come back to haunt us later on.

**Comment by lemoinem** [comment]
Status: Needs Work

**Comment by nicolas-grekas** [comment]
@antanas-arvasevicius looking [at your comment here](https://github.com/doctrine/DoctrineBundle/issues/562), I think we can close this PR, isn't it?

**Comment by antanas-arvasevicius** [comment]
Hi, no this PR fixes the issue, I'll add some test cases to this PR and
hope this will be merged into release. But why do you think that this PR
should be closed?

On Oct 3, 2016 6:38 PM, "Nicolas Grekas" <notifications@github.com> wrote:

@antanas-arvasevicius <https://github.com/antanas-arvasevicius> looking at
your comment here <https://github.com/doctrine/DoctrineBundle/issues/562>,
I think we can close this PR, isn't it?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/symfony/symfony/pull/19902#issuecomment-251140747>, or mute
the thread

**Comment by nicolas-grekas** [comment]
> why do you think that this PR should be closed?

Because reading your comment, you say "it's not due lazy->lazy" :)
And also because "lazy" is an optional feature that requires proxy-manager.
Or should this be done conditionally when proxy-manager is used?

**Comment by antanas-arvasevicius** [comment]
Yes, that doctrine bug is not due lazy->lazy. It's due this bug which was
fixed with this PR. It's due a fact that hasReference() also scans lazy
service dependencies to find out circular dependencies, why is that so
because lazy is indirectly referenced and instantiated lazily. And that
Doctrine lazy listeners has worked only by miracle because it used
Configuration as inlined service definition and thats why hasReference
hadn't detected any circular dep.

**Comment by nicolas-grekas** [comment]
So, what about:
>  Or should this be done conditionally when proxy-manager is used?

**Comment by antanas-arvasevicius** [comment]
It would be reasonable to do it conditionally because if proxy-manager
doesn't exists then everything is instantiated eagerly and we need
detection of circular references in this case. If proxy-manager is
available then we need to "skip reference search in lazy service's
arguments". What do you think?

**Comment by nicolas-grekas** [comment]
I agree :)

**Comment by fabpot** [comment]
Anything to be done before merging this one?

**Comment by antanas-arvasevicius** [comment]
On Nov 10, 2016 2:26 AM, "Fabien Potencier" <notifications@github.com>
wrote:

>

> Anything to be done before merging this one?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/symfony/symfony/pull/19902#issuecomment-259566579>, or
mute the thread

**Comment by antanas-arvasevicius** [comment]
Hi, needed to add unit test with DI setup which shows correct behavior (no
circular reference error while injecting argument in lazy service which is
dependent of that service itself) e.g. graph: new A(new B(A)). If B is
marked as lazy we should allow this configuration.

**Comment by stof** [comment]
if B is lazy *and* we can actually make it lazy (if we cannot generate the lazy proxy, it is the same than not being lazy)

**Comment by antanas-arvasevicius** [comment]
Right, but what's the point to allow lazy:true without proxy mngr? Are
there any use cases for that?
Now, if you need a lazy for avoiding circular refs and proxy manager is not
there you'll get circular reference error and not an error which tells you
that you must enable proxy manager for this.

**Comment by fabpot** [comment]
At least for Open-Source bundle, people might tag a service as lazy as an optimization if the end user has the proxy manager and as a noop if it's not installed.

**Comment by antanas-arvasevicius** [comment]
Added unit tests, And also had found out that CheckCircularReferencesPass detects circular references. I've applied patch for that too. Please review.

**Comment by antanas-arvasevicius** [comment]
@fabpot could this be merged now? Or there are any problems?

**Comment by nicolas-grekas** [comment]
rebase needed

**Comment by antanas-arvasevicius** [comment]
Rebase onto what? Haven't thought that bug fix could take so long to be applied... I really do not understand how your bug fix apply policy works, but it sucks. Bye.

**Comment by HeahDude** [comment]
A rebase on the target branch of this PR which is 2.7, since some other commits have changed some files modified in this PR, you need to resolve some conflicts so maintainers are able to merge it automatically. Thank you for contributing.

**Comment by antanas-arvasevicius** [comment]
Thanks for explanation. Now rebased my branch. Is this fix will be available in 2.8 .. 3.1 also?

**Comment by HeahDude** [comment]
Yes it will ;)

**Comment by sstok** [comment]
@antanas-arvasevicius:

Using git remote upstream exists, `git rebase upstream/2.7` and then git push 
See also http://symfony.com/doc/current/contributing/code/patches.html#rework-your-patch

**Comment by HeahDude** [comment]
👍

Status: Reviewed

**Comment by nicolas-grekas** [comment]
:+1: (the $isLazy temp var could be removed)

**Comment by fabpot** [comment]
Thank you @antanas-arvasevicius.

**Comment by gxolin** [comment]
Thank you @antanas-arvasevicius.
@fabpot do you know in which version this fix will be available for 7.2.* ?

**Comment by wouterj** [comment]
@gxolin it's always the next release. So 2.7.22

**Comment by antanas-arvasevicius** [comment]
no prob :)

**Pull request merged**
