### PR TITLE
[DependencyInjection] Add void return type to CompilerPassInterface

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Add void return type to CompilerPassInterface.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
We decided to not add void to our interfaces because this would annoy people for very little benefits.

**Comment by alexander-schranz** [comment]
@nicolas-grekas should we add then `@return mixed`? currently my phpstan always tells me there is no return type defined for my CompilerPasses :) Having @return on the base interface would help here.

**Comment by nicolas-grekas** [comment]
You can add the return type on your side, no need for it to be on the interface.

**Comment by alexander-schranz** [comment]
@nicolas-grekas sure but would make it easier not always have the need to define it there if the interface already defines it ;) But I'm fine with it. Thx for the quick responses!

**Pull request closed without merging**
