### PR TITLE
[EventDispatcher] add method getListenerPriority() to interface

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16198 |
| License | MIT |
| Doc PR | todo |

### CODE REVIEW

**Comment by dupuchba** [comment]
:+1:

**Comment by Tobion** [comment]
:+1: 

Status: Reviewed

**Comment by Tobion** [comment]
Thank you @xabbuh.

**Comment by pfrenssen** [comment]
Is there a possibility to backport this to Symfony 2.8?

**Comment by xabbuh** [comment]
@pfrenssen Adding a method to an interface is a BC break (all implementations of the interface must be changed). That's why we had to make this change in 3.0.

**Comment by pfrenssen** [comment]
Ok that sounds like a good reason. Pity is that BC is already broken, ContainerAwareEventDispatcher is calling this method in 2.8.

**Comment by xabbuh** [comment]
@pfrenssen I do not see where this is happening. But can you please create a new issue if you think that there actually is a bug (always calling a method that is not given by the interface would be indeed a mistake). Best would be if you could come up with a failing test case or code example.

**Comment by donquixote** [comment]
@xabbuh @pfrenssen here, https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php#L102

> backport this to Symfony 2.8

This could be done by adding a separate interface, extending the basic one.
Then either change the constructor signature for TraceableEventDispatcher, or do some instanceof.
Or maybe just method_exists(), without any extra interface?

The question is: Should TraceableEventDispatcher always require a dispatcher with getListenerPriority() ? Or is this called only sometimes? Or could it return a default value, if the method does not exist?

> create a new issue

I leave this to others (e.g. @pfrenssen) For now I am simply having a short visit in this issue queue.

**Comment by xabbuh** [comment]
@pfrenssen @donquixote Thank you for the details given. I checked the code again and proposed a fix in #18388 to provide a meaningful exception in case you call the `getListenerPriority()` method in case the method does not exist in the wrapped dispatcher.

**Comment by pfrenssen** [comment]
I guess this is a good solution if we cannot add the interface for BC reasons. Thanks!

**Pull request merged**
