### PR TITLE
[Form] Using instanceof DateTimeImmutable instead of DateTimeInterface

### PR DESCRIPTION
**Pull request by samsonasik**
refs : 
- http://3v4l.org/8GvgO
- https://github.com/zendframework/zend-validator/pull/25#discussion_r35206888
- http://news.php.net/php.internals/87217 

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Please let me know if I pointed to wrong branch ^^. Thanks ;)

### CODE REVIEW

**Comment by xabbuh** [comment]
What is the advantage of your patch? The `DateTimeImmutable` class also implements the `DateTimeInterface`.

**Comment by samsonasik** [comment]
<code>$dateTime instanceof \DateTimeInterface</code> never works, see http://3v4l.org/8GvgO

**Comment by samsonasik** [comment]
ping @Ocramius you probably have more clear explanation about this ;), thanks ;)

**Comment by unkind** [comment]
> `$dateTime instanceof \DateTimeInterface` never works when implemented by user class

For clarity, `instanceof` does work. The only issue that you can't implement user class with this interface (fortunately). So this patch doesn't affect anything.

**Comment by samsonasik** [comment]
the value about it is that $dateTime will never "directly" implements DateTimeInterface, so I think direct DateTimeImmutable check is ok

Warm regards,

Abdul Malik Ikhsan

Pada 25 Jul 2015, pukul 23.41, unkind <notifications@github.com> menulis:

> $dateTime

**Comment by Nicofuma** [comment]
:-1: There is two different DateTime objects and the interface exists to allow us to not have to bother with this implementation detail
http://news.php.net/php.internals/87218
http://news.php.net/php.internals/87221

**Comment by Ocramius** [comment]
To be honest, after talking with many internal folks, it turns out that the interface was a mistake, and that it is an actual abstract that should not have been exposed to userland.

Therefore, I'd avoid relying on `DateTimeInterface` at all to not aggravate the problem further.

The checks should pretty much be like `$v instanceof DateTime || $v instanceof DateTimeImmutable`.

It is a sad truth and it comes from a messed up internals issue: the ext/date extension does not follow typical PHP OO-typing rules, so avoid coupling to it.

**Comment by xabbuh** [comment]
> Therefore, I'd avoid relying on `DateTimeInterface` at all to not aggravate the problem further.

> The checks should pretty much be like `$v instanceof DateTime || $v instanceof DateTimeImmutable`.

@Ocramius I see your point, though @derickr [also wrote](http://news.php.net/php.internals/87221)

> DateTimeInterface is meant so that 
both DateTime and DateTimeImmutable can be type hinted for, and not 
really for user land.

which I'd interpret as "safe for type-hinting against it, but not for creating custom implementations".

**Comment by Ocramius** [comment]
@xabbuh pretty much nothing about that interface is safe, which is the problem :P

**Comment by xabbuh** [comment]
@Ocramius Then it's a shame to have it in the docs. :(

**Comment by unkind** [comment]
`DateTimeInterface` is broken by its nature, so having issues with internals is luck. The real mistake was mutable `DateTime`, this is *the only reason* why we have this awkward interface. Immutable `DateTime` doesn't need separate interface: it is a *value*, there is no need in multiple implementations. Most of the time when people talk about multiple implementations of this object, they mean something like `Clock` service.

**Comment by nicolas-grekas** [comment]
I understand that DateTimeInterface is broken on the PHP engine. But it is not on HHVM.
I fail to understand how this patch qualifies as bugfix.
What I understand is that you propose to use DateTimeImmutable because, on PHP engine, it is technically equivalent to DateTimeInterface.
But since this is technically equivalent, and since the underlying statement that drives this patch (DateTimeInterface being broken on the PHP engine) is not universal (HHVM, and maybe a next version of PHP), I'd :-1: .
Did I miss something?

**Comment by samsonasik** [comment]
in php manual, the comment for instanceof DateTimeInterface example have removed http://php.net/manual/en/class.datetimeinterface.php , so it indicate that using instanceof DateTimeInterface is not recommended. So I think this change should be ok

**Comment by xabbuh** [comment]
@samsonasik It still states:

> DateTimeInterface is meant so that both DateTime and DateTimeImmutable can be type hinted for.

**Comment by fabpot** [comment]
Wow, that's confusing as hell :) Anyway, `DateTimeImmutable` is only available as of PHP 5.5, so I'm closing this one.

**Pull request closed without merging**
