### PR TITLE
Add PHP nightly to Travis tests

### PR DESCRIPTION
**Pull request by pierredup**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | N/A
| Fixed tickets | 
| License       | MIT
| Doc PR        | N/A

The current Travis tests doesn't run against PHP nightly (I.E PHP 7.2).
This could assist in picking up any regressions or issues with newer versions of PHP.
I'm not sure if there is a specific reason why PHP nightly is not included in Travis (I did a quick search but couldn't find anything)?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
The reason is that we consider that an "allow_failures" job is just one less job available - we're already short on jobs. Another reason is that nobody will ever care about a "red" failing job if it's not enforced.
But if you're trying to make the 7.2 line green, please do! (I might help on VarDumper)

**Comment by fabpot** [comment]
Closing for now. We should first fix compat with 7.2.

**Comment by pierredup** [comment]
@fabpot I started fixing some of the issues I picked up with 7.2, should I create a new PR for that or can we keep this one open for the 7.2 fixes? (The title can then just change to match the purpose of the PR)

**Comment by fabpot** [comment]
@pierredup Sure, having this PR with Travis changes and the fixes for 7.2 would be great! Feel free to reopen when you are ready.

**Pull request closed without merging**
