### PR TITLE
[Workflow] Transtion match types

### PR DESCRIPTION
**Pull request by Padam87**
| Q             | A
| ------------- | ---
| Branch?       |  3.2
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20788
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by lyrixx** [comment]
Hello @Padam87 

Thanks for your work here, but unfortunately, there is not bug to fix. So I have to reject your PR. :/

**Comment by Padam87** [comment]
This is not a bug, it is a new feature

**Comment by lyrixx** [comment]
But in this case, the worflow component will not follow the PetriNet specification.
To fix your issue, you should add new transitions. (transition name are not unique ;) )

**Comment by Padam87** [comment]
Ah, okay, I think that is great. I can still use the same listeners, and works like overloading... nice. Thx :)

**Comment by Padam87** [comment]
I see that the component support it in `getTransitions`, but unfortunately with the yaml mapping only one of the transitions survive.

**Comment by lyrixx** [comment]
Good catch, could you open a new issue for that ?

**Comment by xabbuh** [comment]
For the records, #20794 is the follow-up issue.

**Pull request closed without merging**
