### PR TITLE
[HttpFoundation] Fix and test status codes according to IANA's data

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

This PR updates HTTP status code according to values [standardized by the IANA](https://www.iana.org/assignments/http-status-codes/http-status-codes.xml). It also add a test to check the conformance (we'll also be notified when a code is added, ~~removed~~ or modified).

All credits go to @fcabralpacheco for is work in Zend Diactoros: https://github.com/zendframework/zend-diactoros/pull/234

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Comment by fabpot** [comment]
Thank you @dunglas.

**Comment by fcabralpacheco** [comment]
@dunglas  Firstly I'm happy to see that the PR was more helpful than expected.

Just a suggestion, keep the ".rng" file as a local resource.

The primary purpose of xml validation is to prevent the following code from failing.

The secondary one is to make easier to fix the code if the ".xml" file format changes.
A validation failure will mean a probable format change.
It's easy to just compare two grammars.

Besides this,  I believe the ".rng" file rarely changes, not justifying two more requests ("http-status-codes.rng" and "iana-registry.rng").

**Comment by fcabralpacheco** [comment]
An example of situation that the first purpose try to prevent is the following:

If the format changes and don't return more "records". Just a "record" to "entry" change. PHPUnit will simply skip this test.

**Comment by dunglas** [comment]
Fair. I'll update fix this in a follow up PR.

**Pull request merged**
