### PR TITLE
[Ldap] Ldap username case fix

### LINKED ISSUE #20486: [LDAP] Issue with case-sensitive usernames
When authenticating a user using the LDAP security component, username entered by the user is used to build the `User` instance.

In case of a case-insensitive authentication (which is the default behavior : https://stackoverflow.com/questions/29897684/is-ldap-dn-case-insensitive), the final `User` username can be wrong (for instance, `USERNAME` instead of `UserName`).

To avoid this issue, I'm using the `cn` attribute of the `Ldap\Entry` instead, so I'm getting the well-spelled username. To apply a more generic solution, I think we should store the `$uidKey` as an attribute in the `LdapUserProvider` and use it to retrieve the username using the `Entry` (`$entry->getAttribute($this->uidKey)`).

I can create a pull request if you want.

Thx !

### PR DESCRIPTION
**Pull request by quentinus95**
| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20486
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by quentinus95** [comment]
@csarrazi I have recreated a new PR and deleted the old one because I merged the whole master branch in it inadvertently (I forgot it was based on 3.1)

I have removed the `null` check in `getAttributeValue` method and set a default value for `$uidKey` if `null` given. I also set the password to `null` if the password attribute is `null`.

**Comment by nicolas-grekas** [comment]
Which branch is this fix for? There's a mismatch between the description and the selected base branch (no need to change because we can while merging.)

**Comment by quentinus95** [comment]
This fix is for the 3.1 branch, sorry!

**Comment by nicolas-grekas** [comment]
ping @csarrazi (3.1 is EOLed in two weeks)

**Comment by csarrazi** [comment]
👍 , as I said in the previous PR. I would merge it against 3.1, as we still support it (even though EOL is in 2 weeks).

Should we merge it against 3.1 or rather 3.2 / master?

**Comment by quentinus95** [comment]
Should I care about the failure on AppVeyor as it does not seems related to the changes of this PR ?

**Comment by fabpot** [comment]
Thank you @quentinus95.

**Pull request closed without merging**
