### PR TITLE
[HttpFoundation] AutExpireFlashBag should not clear new flashes

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #9318
| License       | MIT
| Doc PR        | none

I feel like very happy ! :)
But don't worry I'm.

img_2826

### CODE REVIEW

**Comment by sroze** [comment]
Tests? :)

**Comment by Simperfit** [comment]
There are no way to return new, so If I add a test It will be the same as the `all` or the `clear` one.

**Comment by sroze** [comment]
And you've got one now 😉

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
ping @Tobion I guess

**Review by Tobion — APPROVED** [review]
👍  `get()` does not clear the new flashes. So `all()` should not either.

**Comment by fabpot** [comment]
The current behavior is intended. That's not a bug. A flash is something you can get once and only once, no matter if you get it for the current or the next request.

**Comment by sroze** [comment]
@fabpot agreed. The point is: if in your code, you add something before the
"previous" ones are displayed, it should not remove the ones you've just
added.

**Comment by fabpot** [comment]
I should have read the code first. The code is weird indeed, as `all()` does not return the new ones, only the previous ones. So, the fix looks fine.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Simperfit.

**Comment by Simperfit** [comment]
Thanks to @sroze too !

Le mer. 29 nov. 2017 à 02:56, Fabien Potencier <notifications@github.com> a
écrit :

**Pull request merged**
