### PR TITLE
[Mailer] [Sendinblue] refacto sendinblue to brevo

### PR DESCRIPTION
**Pull request by PEtanguy**
WIP: I will make a new bridge altogether.

| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | TODO

Hello,

This PR is aimed at updating the config for the sendinblue mailer.
As you might have seen, Sendinblue has rebranded to [Brevo](https://developers.brevo.com/) and also rewrote their apis.  
This change ensure compatibility with the new endpoints and removes any reference to Sendinblue.

I do not think that this change qualifies as a feature but I also do not believe that it is a bug fix.

Please let me know if that does not fit in 6.3

### CODE REVIEW

**Comment by OskarStark** [comment]
From a code perspective we should introduce this as a new bridge and deprecate the sendinblue bridge. AFAIK we had a bridge which was "renamed" in the past, not sure yet how we did in this case.

@fabpot please leave your 2 cents here, thanks

**Comment by fabpot** [comment]
> From a code perspective we should introduce this as a new bridge and deprecate the sendinblue bridge. AFAIK we had a bridge which was "renamed" in the past, not sure yet how we did in this case.
> 
> @fabpot please leave your 2 cents here, thanks

That's correct.

**Comment by PEtanguy** [comment]
@fabpot @OskarStark that's what I was wondering.

I will have a go at it, thanks.

**Comment by PEtanguy** [comment]
I opened 2 new PRs to add a new notifier and a new mailer

https://github.com/symfony/symfony/pull/50296

**Pull request closed without merging**
