### PR TITLE
[Workflow] Fixed BC break

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27759
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Looking at the breaking commit, this means the parameter will be mandatory in 5.0? Should the deprecation message tell something about it? If not, null is not allowed right now.

https://github.com/symfony/symfony/commit/bd1f2c858385bca965cb6e8d32b1a21085029981#diff-7ced8e5ceace060a06472087086f06eaR49

**Comment by derrabus** [comment]
When not passing a fouth parameter (which used to be valid), the deprecation message is now odd because it tells me not to pass a string (which is not what I did).

**Comment by lyrixx** [comment]
What do you suggest ?

**Review by Nek- — APPROVED** [review]
It fixes #27759 👍 . I only get a deprecation notice.

**Comment by derrabus** [comment]
Would that work?

```php
public function __construct($subject, Marking $marking, Transition $transition, $workflow = null)
{
    // …
    if (null === $workflow) {
        @trigger_error(sprintf('Passing only three parameters to "%s" is deprecated since Symfony 4.1. Pass a %s instance as fourth parameter instead.', __METHOD__, WorkflowInterface::class), E_USER_DEPRECATED);
        $this->workflowName = 'unnamed';
    } elseif (is_string($workflow)) {
        // …
```

**Comment by lyrixx** [comment]
@derrabus :+1: I updated the PR

**Review by derrabus — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.

**Pull request merged**
