### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by jwage**

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi!

your pull request description seems to be incomplete or malformed:

* The `description` shouldn&#039;t be empty. 
* The `type` should be one of: `new feature`, `improvement`, `bug fix`. 

Would you mind to complete the contribution table ? This help us understand how interesting is your contribution.

Thank you!

(note: this is an automated message, but answering it will reach a real human )

**Comment by prestonfakeaccount** [comment]
Hi!

your pull request description seems to be incomplete or malformed:

* The `description` shouldn&#039;t be empty. 
* The `type` should be one of: `new feature`, `improvement`, `bug fix`. 

Would you mind to complete the contribution table ? This help us understand how interesting is your contribution.

Thank you!

(note: this is an automated message, but answering it will reach a real human )

**Comment by prestonfakeaccount** [comment]
Hi!

your pull request description seems to be incomplete or malformed:

* The `description` shouldn&#039;t be empty. 
* The `type` should be one of: `new feature`, `improvement`, `bug fix`. 

Would you mind to complete the contribution table ? This help us understand how interesting is your contribution.

Thank you!

(note: this is an automated message, but answering it will reach a real human )

**Comment by stof** [comment]
@prestonfakeaccount please don't use the Symfony repository to test your bot

**Comment by mickaelandrieu** [comment]
@stof very sorry about it, it was really unexpected :/ It won't happen

**Pull request closed without merging**
