### PR TITLE
moved PHP nightly to PHP 7.0

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
There are more occurrences of "nightly" in the travis file.

**Comment by stof** [comment]
looks good to me. We want to test against 7.0 releases once they are available on Travis

**Comment by stof** [comment]
@nicolas-grekas can you check the issue with the AppVeyor build ?

**Comment by nicolas-grekas** [comment]
@stof the issue is that #15575 is not merged

**Pull request merged**
