### PR TITLE
[Routing] Quick cyclomatic reduce

### PR DESCRIPTION
**Pull request by DocFX**
Just merged `if`.

| Q             | A
| ------------- | ---
| Branch?       |  4.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| License       | MIT

Simply merged `if()`.

### CODE REVIEW

**Comment by stof** [comment]
this does not change the cyclomatic complexity at all. You still have 3 paths in the code. The only thing that changed is the cosmetic.

**Comment by DocFX** [comment]
> 
> 
> this does not change the cyclomatic complexity at all. You still have 3 paths in the code. The only thing that changed is the cosmetic.

2 if => 1 if. CYC = 3 vs 2. You sure it doesn't?

Also, why is appveyor failing from another PR? Oô

**Comment by stof** [comment]
you have 1 `if` with a `&&` in it. That's still 2 conditions. And so that's still a CYC of 3.

Note that the new code is executing exactly the same logic than before, so it is also expected that the CYC does not change (as CYC does not care about the code formatting)

**Comment by fabpot** [comment]
Let's close :)

**Pull request closed without merging**
