### PR TITLE
April Fools' Joke 2018

### PR DESCRIPTION
**Pull request by Majkl578**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no-ish
| Deprecations? | no
| Tests pass?   | no (yet)
| License       | WTFPL
| Doc PR        | TODO

Dear Symfony devs,

I am proposing to **drop Yaml component entirely**, with no direct replacement, possibly pointing users to alternatives: **INI**, TOML, JSON, XML.

I know this is a popular Symfony component, but let's face it, **Yaml is bad** and has no place in 2018.
 * https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html
 * https://hackernoon.com/consistently-bad-parsing-of-yaml-ae23eb3676a1
 * https://dev.mikamai.com/2014/10/06/why-json-sucks-for-user-configuration/
 * https://github.com/markbates/configatron/issues/48

Replacement: Whole Yaml component could be simply replaced by INI:
```php
$config = parse_ini_file('config.ini', true, INI_SCANNER_TYPED);
```
This is a one-liner replacement of whole Yaml component. One line vs. **over 14K LoC**, huge win! :tada: 

Note:
This is **for 5.0 ONLY**, no deprecation in 4.x to avoid noise from users.

### CODE REVIEW

**Comment by curry684** [comment]
So here we have this brilliant framework, that's all about choice, that tries to be as unopinionated about everything as possible because a good framework is really good by *enabling* instead of *disabling*.... and you propose to remove a component because of, well, an opinion.

The Symfony docs have tabs with every configuration related example. You can write huge Symfony applications without ever seeing a single line of YAML. Sure, the skeleton uses it, but you don't need to use it. You can write all your config files in XML or PHP, and Symfony will happily run it. Because it doesn't give a damn about your opinion or anyone else's. Instead it's enabling you to have it and keep it.

So, instead of offering to *disable* functionality because of your opinion, I challenge you to provide a PR integrating proper support for INI and TOML config files, and extending that into the docs. Afterwards, your fellow developers will have more choice, which is always a Good Thing(tm).

Note that I didn't include JSON here. As your third link quite correctly notes JSON is predominantly a machine format, not a user format, and therefore is not a good fit with large configuration files. The article closes with:

> Almost anything is a good alternative, from INI to CSON. The one I like the most tho is YAML.

Man's got a point. It may have flaws, but adding it all together it certainly sucks a lot less than a lot of the alternatives.

**Comment by magnusnordlander** [comment]
I'm very much :-1: on this. 

Even if YAML is bad, there's still a value in a proper YAML implementation in PHP. Had the PR been for removing support for YAML for configuration I would still be 👎, but that's at least a prospect that I could consider.

*If* we wanted to remove, or even deprecate YAML for configuration (which I personally don't), I think 5.x would be too early. Considering that YAML is (I'm guessing) currently the most popular configuration format, we'd basically first have to wean the community off it first.

**Comment by chalasr** [comment]
:-1: no good reason to remove it.

**Comment by Ocramius** [comment]
Good one, @majkl578 😂

**Comment by nuxwin** [comment]
@Majkl578 @Ocramius 

That is a joke right? Why such removal proposal? YAML is not more bad than INI in my eyes. "No place in 2018" Really? While some are implementing new tools using YAML as configuration file format (such as http://netplan.io ) ... Could you clarify a bit?

**Comment by felipsmartins** [comment]
Yes, that's just a joke.

**Comment by bobdenotter** [comment]
I’m a big fan of “convention over configuration”. Let’s remove XML and PHP configuration as well. :+1:

**Comment by gerryvdm** [comment]
Let April 1 2018 be the day the YAML revolution began! ✊🏻

**Comment by nuxwin** [comment]
OH..... 1st april... Or how lose time with useless commit CHUCKLES ;)

**Comment by ro0NL** [comment]
Made my day :D

**Comment by Simperfit** [comment]
We should remove the config’ components aswell and use INI for everything !

**Comment by ro0NL** [comment]
What about a dedicated INI component?

**Comment by dknx01** [comment]
I would like to remove all configuration (annotations, yaml, JSON, xml ...) and also convention over configuration.
The software must just gues (right) what I want and how (and maybe why).

Intension-As-Configuration

**Comment by sstok** [comment]
You broke the build!

Status: Needs work

**Comment by javiereguiluz** [comment]
Note: I've renamed this issue to "April Fools' Joke 2018". The reason is that this kind of "jokes" get out of context quickly and people in the future may be confused when finding this PR via Google's or GitHub's search engines and think that Symfony is going to make this change.

It's the same that happened to Doctrine a few years ago. They published an April Fools' article and today lots of people still think that it's real (because its April Fools' warning message is easy to overview) and it's ranked high in Google: http://www.doctrine-project.org/2017/04/01/announcing-doctrine-4.html

**Comment by alcaeus** [comment]
Renaming it could’ve been done after April 1st, way to spoil the fun here.

**Comment by fabpot** [comment]
Thanks for the joke.

**Pull request closed without merging**
