### PR TITLE
[DI] compilation perf tweak

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | no
| New feature?  | n
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

image

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I'm not sure if it's possible to do it, but it'd be great if PHP could detect this automatically to avoid having to add the `\` explicitly for each function call that we want to optimize. Maybe @nikic could think of a solution for this 🙏  Thanks!

**Comment by jvasseur** [comment]
@javiereguiluz it's not possible because PHP works on a per-file basis when doing optimizations (because the cached OP codes have to stay valid if other files changes), this means PHP can't know if you didn't defined a function with the same name in the current namespace.

I personally think allowing to call root namespace functions without prefixing them with `\` should never have been allowed like it's done for classes (this is preventing things like functions autoloading to append). But it can't be changed now without a massive BC break.

**Comment by theofidry** [comment]
@javiereguiluz an alternative solution is to have use statements:

```php
// No optimisation
is_array($x);

// Optimisation with the FQFN
\is_array($x);

// Optimisation with the use statement:
use function is_array;

is_array($x);
```

There is also a PHP-CS-Fixer rule `native_function_invocation` for the former but not yet for the later. That said there's a config in PhpStorm (Editor > General > Auto Import) where you can configure this

**Comment by iltar** [comment]
Wouldn't it make sense to add the backslash in front of every php function? I'm sure you can get even more performance out of it

**Comment by javiereguiluz** [comment]
@iltar no ... because this optimization only applies to a selected number of PHP functions.

**Comment by theofidry** [comment]
@iltar to me it makes sense if you are using a backlash everywhere e.g. `\Exception` instead of `use Exception; [...] Exception`, but as @javiereguiluz said currrently this is done only to a handful of them because the optimisation doesn't apply to all of them.

I would be for adding a use statement (for functions as well) for all of them, but not everyone may share that opinion :)

**Comment by iltar** [comment]
Any resources on where it's defined for which functions this is and why only for those? I failed finding those.

**Comment by nicolas-grekas** [comment]
@iltar https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048

**Comment by jakzal** [comment]
>> Wouldn't it make sense to add the backslash in front of every php function? I'm sure you can get even more performance out of it

> @iltar no ... because this optimization only applies to a selected number of PHP functions.

Does it do any harm if the backslash is there for every PHP function?

**Comment by nicolas-grekas** [comment]
> Does it do any harm if the backslash is there for every PHP function?

yes: turning PHP into brainf*ck :)

**Comment by nikic** [comment]
While only some functions have a direct opcode implementation, fully qualifying internal function calls is also faster in general. If the function can be resolved statically, PHP will specialize for an internal function call and will specialize for by-value (or by-reference) sending of the function arguments.

**Comment by iltar** [comment]
Maybe a bit off-topic for this PR, but I would love to have an opt-in setting for a completely file to pull all functions and constants out of the global namespace, unless specified otherwise.

**Review by Tobion — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by King2500** [comment]
Why not apply this fix to all occurrences of `is_array`?
https://github.com/symfony/symfony/search?l=PHP&q=is_array&type=&utf8=%E2%9C%93

**Comment by nicolas-grekas** [comment]
@kalessil thanks, but I think we would to that change only when we'll have a bot ensuring this does not diverge.

**Comment by kalessil** [comment]
Ok, poke me if changed your mind =)

**Comment by leofeyer** [comment]
> but I think we would to that change only when we'll have a bot ensuring this cannot diverge

@nicolas-grekas Since FriendsOfPHP/PHP-CS-Fixer#3222 will be merged in version 3 only, I have backported the feature for PHP-CS-Fixer 2:

https://github.com/leofeyer/optimize-native-functions-fixer

**Pull request merged**
