### PR TITLE
[Notifier] Prepare bridges for the upcoming return type change.

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

Preparation for #39549.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
we should do this in all bridges actually

**Comment by derrabus** [comment]
Even if the others aren't affected by the BC break?

**Comment by nicolas-grekas** [comment]
They can be affected by any BC break we might want to do in 5.3+

**Comment by derrabus** [comment]
All right.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @derrabus.

**Comment by derrabus** [comment]
I'll simply discard the changes when merging up, right?

**Comment by stof** [comment]
I already suggested that in the past when dealing with another experimental component (Messenger or Mailer, I don't remember). IMO, dependencies to an experimental component should never be added using the `^` operator, because marking a component as experimental is precisely about not following semver yet in it (which is the requirement for `^` to be safe).

**Comment by nicolas-grekas** [comment]
We did so in 5.1 for notifier, and we lost the practice when preparing 5.2.
Now merged up to 5.3, using `~5.3.0`

**Comment by derrabus** [comment]
I've bumped the conflict rules as well: #39559

**Comment by stof** [comment]
indeed, maybe it was notifier itself in 5.1 then :smile:

**Pull request merged**
