### PR TITLE
[Mailer] Return-Path has higher priority for envelope address than From address

### LINKED ISSUE #41322: Mailer return path is not set correctly
**Symfony version(s) affected**: 4.4.16

**Description**
When we create a email with defined ->returnPath('example@example.com') email is delivered but in email source we can see that return path was replaced by ->from('from@example.com')  We tried to upgrade this component to v5.0.6 and also v5.0.9 both versions are working correctly. WE was using our server DSN and also tried this setting: MAILER_DSN=sendmail://default without change

**How to reproduce**
Just sent a email with setup "returnPath" and returnPath should be in your mailbox replaced with "from"

**Possible Solution**
probably something in suggested versions

### PR DESCRIPTION
**Pull request by tpetry**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41322
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by fabpot** [comment]
This should be on 4.4 instead.

**Comment by tpetry** [comment]
Ok, I'll rebase it onto 4.4 😉

**Comment by tpetry** [comment]
@fabpot Can you re-run the workflows? I missed changing the new base branch information in the Github Pull Request setting.

**Comment by andjsch** [comment]
This is great! I am having the issue with Laravel 9 not setting the Return Path on the sent email correctly. It's always the sender email.

Thanks for the PR!

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @tpetry.

**Pull request merged**
