### PR TITLE
[VarExporter] fix exporting array indexes

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29715
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
From the [documentation](http://php.net/manual/en/language.types.array.php):

> The key is optional. If it is not specified, PHP will use the increment of the largest previously used integer key.

**Comment by simPod** [comment]
Seems that it works 👍

**Review by ogizanagi — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
Using `~4.2@dev` as the version constraint should do the trick. The `master` branch is for the 4.3 release, but the `4.2` branch hasn't been merged into `master` yet.

**Comment by simPod** [comment]
@xabbuh that install the original version with `if (\is_int($k)) {` only. Am I missing something?

`composer require symfony/var-exporter:"~4.2@dev"` ->

```json
        {
            "name": "symfony/var-exporter",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/var-exporter.git",
                "reference": "d89a4ab8d3d8d7ac6487f2252b63b6d865f0cfac"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/var-exporter/zipball/d89a4ab8d3d8d7ac6487f2252b63b6d865f0cfac",
                "reference": "d89a4ab8d3d8d7ac6487f2252b63b6d865f0cfac",
                "shasum": ""
            },
            "require": {
                "php": "^7.1.3"
            },
            "require-dev": {
                "symfony/var-dumper": "^4.1.1"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "4.3-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Symfony\\Component\\VarExporter\\": ""
                },
                "exclude-from-classmap": [
                    "/Tests/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code",
            "homepage": "https://symfony.com",
            "keywords": [
                "clone",
                "construct",
                "export",
                "hydrate",
                "instantiate",
                "serialize"
            ],
            "time": "2018-12-13T12:43:21+00:00"
        }
```

**Comment by ogizanagi** [comment]
@simPod : try `composer req "symfony/var-exporter:~4.2.0@dev"` instead.

**Comment by simPod** [comment]
Works, thanks!

**Pull request merged**
