### PR TITLE
[Console] Update Application.php

### PR DESCRIPTION
**Pull request by aleksandr-shevchenko**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

https://github.com/symfony/symfony/issues/47862#issuecomment-1282195961

### CODE REVIEW

**Comment by xabbuh** [comment]
Should this be merged into the `4.4` branch?

**Comment by aleksandr-shevchenko** [comment]
> Should this be merged into the `4.4` branch?

Do what you think is right.

**Comment by xabbuh** [comment]
Will the error output look differently after this change? If so, can you share before and after screenshots?

**Comment by aleksandr-shevchenko** [comment]
> Will the error output look differently after this change? If so, can you share before and after screenshots?

image

**Review by xabbuh — APPROVED** [review]
LGTM then

**Comment by xabbuh** [comment]
@maxbeckers  what do you think?

**Comment by maxbeckers** [comment]
@xabbuh im also fine with that. 👍

**Comment by nicolas-grekas** [comment]
@aleksandr-shevchenko can you please submit the PR for 4.4? The code is not exactly the same.
Please mind the commit message/PR title also since this is going to be used for the changelog.
Thanks.

**Comment by maxbeckers** [comment]
@nicolas-grekas the difference in 4.4 is from PR #47883 ... so i guess it shoud be rebased to 4.4 and then merged to 4.4?

**Comment by nicolas-grekas** [comment]
yes

**Review by fabpot — APPROVED** [review]

**Review by maxbeckers — APPROVED** [review]

**Comment by fabpot** [comment]
Is anyone willing to submit this change to 4.4?

**Comment by maxbeckers** [comment]
I'd do that, but I guess I only could create a new PR with the change. So @aleksandr-shevchenko should do the rebase.

**Comment by xabbuh** [comment]
I did the rebase and switched the target branch to `4.4`.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @aleksandr-shevchenko.

**Pull request merged**
