### PR TITLE
[Dotenv] Fix phpdoc Dotenv

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by chalasr** [comment]
If you have more similar fixes, please consider gathering them in this PR :)

**Comment by alamirault** [comment]
I searched bad phpdoc for `...$` and found nothing else

**Review by GromNaN — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alamirault.

**Comment by chibsedu** [comment]
DIEU Bénit toute vos philharmonies.

**Pull request merged**
