### PR TITLE
Deprecate accessing environment variables prefixed by SYMFONY__ as parameters

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/20089
| License       | MIT
| Doc PR        | n/a

Replaces #21889

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I don't fully agree with the reasoning presented in https://github.com/symfony/symfony/pull/21889#issuecomment-285974554 but let's be OK for now.
Adding a check like done here in ParameterBag looks wrong to me. ParameterBag does not deal with env vars, why should it be at all now?

**Comment by chalasr** [comment]
Getting parameters automatically created from `SYMFONY__` env vars is what we are deprecating to me. How would you detect that the user is relying on the fact we transform env vars into parameters than doing this check in `ParameterBag::get()`? We could store the env-related params in a prop when setting them from `Kernel::getEnvParameters()` instead of reversing the transformation, but it would still involve to do this check here.

**Comment by nicolas-grekas** [comment]
I don't know yet, but right now, the drawback of this implem (SRP break) is worse than the drawback of the implem in #21889 (a theoretical false positive).

**Comment by chalasr** [comment]
We'll remove this check in 4.0 as well as the practice, IMHO we don't care but of course I would go for any better alternative.

**Pull request closed without merging**
