### PR TITLE
[Debug][ErrorHandler] Do not use the php80 polyfill

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by stof** [comment]
the usage of `get_debug_type` in `FatalThrowableError` also seems to cause issues (see the Goutte issue referencing that ticket)

**Comment by derrabus** [comment]
Out of curiosity: What's the problem with using the polyfill here?

**Review by derrabus — APPROVED** [review]

**Comment by stof** [comment]
@derrabus polyfills rely on autoloading (for the internal class). So this breaks if the polyfill is called inside the autoloading stack (as autoloading the polyfill internal classes will also try to use them then).
For the error handling part, I suspect it is similar (for cases where an error happens during the error handling or during the autoloading of the polyfill internals)

**Review by Tobion — CHANGES_REQUESTED** [review]
Shouldn't this remove the polyfill-php80 dependency from composer.json then?

**Comment by Nyholm** [comment]
I dont see us using any PHP8-only code in the ErrorHandler. I agree with @Tobion 

With that change, Im :+1:

**Comment by nicolas-grekas** [comment]
Polyfill now removed (we were using a few calls to `get_debug_type()`, now removed).

**Comment by Tobion** [comment]
I guess we could revert this in 6.0 as it will require php 8?

**Comment by stof** [comment]
@Tobion yes (but without re-adding the polyfill package)

**Comment by nicolas-grekas** [comment]
I did revert while merging up.

**Pull request merged**
