### PR TITLE
[Serializer] Enabled mapping configuration via attributes

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | TODO

Let's use attributes for the serializer mapping configuration!

```php
class MyEntity
{
    #[Groups(['list', 'detail])]
    #[SerializedName('some-property')]
    public $someProperty;

    #[Ignore]
    public string $secret;
}
```

### CODE REVIEW

**Comment by derrabus** [comment]
I was wondering is we should make the `Groups` attribute variadic. Instead of…
```php
#[Groups(['list', 'detail'])]
```
… we could then write…
```php
#[Groups('list', 'detail')]
```
This would look a bit nicer, but adding additional properties in the future would get messy.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
@derrabus Can you have a look at the failing tests?

**Comment by derrabus** [comment]
I used `::class` in annotations, but Doctrine Annotations 1.0 does not support that. Should be fixed now.

**Comment by fabpot** [comment]
Thank you @derrabus.

**Pull request merged**
