### PR TITLE
[Inflector] Correct the spelling of matracies to matraces

### PR DESCRIPTION
**Pull request by gnito-org**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | [symfony/symfony-docs#... ](https://github.com/symfony/symfony-docs/pull/16266)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This breaks tests. More lines need to be changed apparently.

**Comment by gnito-org** [comment]
The errors all conform to the following pattern:

```
3) Symfony\Component\Inflector\Tests\InflectorTest::testPluralize with data set #73 ('matrix', array('matrices', 'matrixes'))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'matrices'
+    0 => 'matricies'
     1 => 'matrixes'
 )
```
However, the word ``matricies`` does not occur anywhere in the branch where I corrected the spelling. So, from where is the test getting it?

**Comment by nicolas-grekas** [comment]
You might want to take inspiration from eg https://github.com/symfony/symfony/pull/43790 which fixes something similar for another word.

**Comment by gnito-org** [comment]
Unfortunately that does not help. I still do not see from where the test is getting the "matricies" that it's listing in the "Actual" line.

**Comment by gnito-org** [comment]
The more overarching question is, why are the tests also failing on other words (fungus, hero) that have nothing to do with the one word I changed in [src/Symfony/Component/Inflector/Tests/InflectorTest.php](https://github.com/symfony/symfony/pull/44632/commits/f84806fe7cc185c547ef13d5cdb71b4831c0b099#diff-8d55263f5bbcccf4ed5ab12f38d29df79cbf0581082185572abfc00c4f015e36).

Shouldn't those other words cause failures in all CI tests that do not include my word change?

**Pull request closed without merging**
