### PR TITLE
[Yaml] keep trailing newlines when dumping multi-line strings

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/pull/39668#issuecomment-753484545
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by geek-merlin** [comment]
Thanks Christian @xabbuh for working on this! First impression, i have doubts about this and will look deeper into this and make a writeup. My timeframe now is ~1/2h, so either i can do it now, or stay tuned tomorrow.

**Comment by xabbuh** [comment]
@geek-merlin Thank you for your valuable feedback. Please do not hesitate to leave comments if you discover more edge cases that do not work as expected. I'll be happy to look into them.

**Comment by geek-merlin** [comment]
Short story: I had some concerns about edge cases of the foreach loop but on closer look all seems fine.

And now i see that you're coming from the test-first camp, so i'll provide pre-cooked tests in the future.

So i guess for now the trailing-newline issue is settled, and hopefully we can finally use that in Drupal's config dumper.

I guess that we still have some unicode issues with this, so i'm interested in architectural feedback on #39682.

**Pull request merged**
