### PR TITLE
[FrameworkBundle] Adding the extension XML

### PR DESCRIPTION
**Pull request by flug**
| Q             | A
| ------------- | ---
| Branch?       | <3.3
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 

XmlUtils

This pull request is referenced on symfony/skeleton

### CODE REVIEW

**Comment by Pierstoval** [comment]
PR name should be prepended with [FrameworkBundle]

**Comment by flug** [comment]
Oh right, I redid this pull request on FrameworkBundle  https://github.com/symfony/framework-bundle/pull/15

**Comment by Pierstoval** [comment]
Don't make PR on symfony/framework-bundle#15, this is a read-only split of the full-stack repo.

This #22676 PR is good, you just have to rename the PR and add [FrameworkBundle] at the beginning of it so it can be tagged properly and fabbot.io doesn't complain 🙂

**Comment by fabpot** [comment]
Thank you @flug.

**Comment by xabbuh** [comment]
I am not sure about this. We did not explicitly require other PHP standard extensions in the past, did we? And if we were to do this for the FrameworkBundle, we should IMO do the same for the other bundles too.

**Pull request closed without merging**
