### PR TITLE
[VarDumper] Get dump as string with `$dumper->dump(..., true);`

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Branch? | master |
| New feature? | yes |
| Tests pass? | yes |
| License | MIT |

ping @lyrixx @wouterj since you expressed interest in boilerplate reduction around this in the past :)

### CODE REVIEW

**Comment by lyrixx** [comment]
:+1: 
Now the dumper trait can be simplified ?!

**Comment by nicolas-grekas** [comment]
More than already done here?

**Comment by wouterj** [comment]
Looks good!

I also wondered if [these 4 lines of boilerplate code](https://github.com/symfony/symfony/pull/19614/files#diff-1b203840c96e2f4a2f0386788e2765d3R216) can be reduced as well? I've had to use it in a couple places in that PR.

**Comment by nicolas-grekas** [comment]
@wouterj these 4 lines of boilerplate won't be needed anymore with #19768

**Pull request merged**
