### PR TITLE
Update license years (last time)

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | n/a

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Review by dunglas — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by wouterj — APPROVED** [review]
Another approval, in case this is a roulet game where the last remaining core team member that doesn't approve has to do the merge and merge-up of this one 😉

**Review by lyrixx — APPROVED** [review]
Not the last one 😅!

**Comment by derrabus** [comment]
I wonder if this is going to pass. Looks like a close vote.

**Review by fancyweb — APPROVED** [review]
👋🧹

**Comment by alexisLefebvre** [comment]
It looks like that the “Package / Verify” job on the CI needs a year number:

> symfony/doctrine-bridge
>  Verifying new package
>  First line of the license file is wrong. Maybe it is the wrong year?

**Comment by stof** [comment]
`.github/workflows/package-tests.yml` should be updated to change the check being done.

**Comment by stof** [comment]
@fabpot the fix for the CI check is wrong, making the CI red

**Comment by xabbuh** [comment]
@stof IIRC this step is usually only applied when a new license file is added for which the check is correct.

**Pull request merged**
