### PR TITLE
Fix AttributeClassLoaderTestCase

### PR DESCRIPTION
**Pull request by cyraid**
+ Added ->setUp()
  - Removed 'abstract' so it'd be picked up by Tests.
  * Changed getNamespace() to full path Qualified Name.

| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| License       | MIT

This Pull Request should fix *Component/Routing/Tests/Loader/AttributeClassLoaderTestCase* as I'm gonna be including a test with it for an upcoming change regarding Routing I'd like you guys to look at.

Could someone review? Thanks guys. ^_^

### CODE REVIEW

**Comment by cyraid** [comment]
That's odd, it says some failed but the tests in the logs show they did? Hmm.. `86 / 86 (100%)`

**Comment by xabbuh** [comment]
Can you rebase your changes on the `7.0` branch and fix the code style please?

**Comment by cyraid** [comment]
Fix the code style? You mean in setUp()? Mostly not my file I just added setUp() to make it work, and abstract, and changed some strings.

**Comment by xabbuh** [comment]
basically move the import of `TraceableAttributeClassLoader` at the right position as suggested by fabbot

**Comment by cyraid** [comment]
Hmm, I might have to make a new Pull Request for 7.0, I'll close this one and make a new one.

**Pull request closed without merging**
