### PR TITLE
[symfony/symfony] add "provides" for psr/cache-implementation

### PR DESCRIPTION
**Pull request by alcohol**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #19742 |
| License | MIT |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by jakzal** [comment]
👍

**Comment by stof** [comment]
Thank you @alcohol.

**Comment by alcohol** [comment]
I just realized it should be "provide".

**Pull request merged**
