### PR TITLE
[HttpFoundation] removed the ParameterBag::get() deep argument

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by Tobion** [comment]
Tests are failing

**Comment by xabbuh** [comment]
Status: Needs work

**Comment by fabpot** [comment]
Fixed

**Comment by xabbuh** [comment]
The tests with Symfony 2.8 still as the number of arguments of the `get()` method has changed.

**Comment by fabpot** [comment]
#16037 will fix that.

**Pull request merged**
