### PR TITLE
Minor code style fix

### PR DESCRIPTION
**Pull request by codedmonkey**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | 
| License       | MIT
| Doc PR        | 

Fixes indentation in a configuration file

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Should target 6.1 instead (as this is not a bug).

**Comment by codedmonkey** [comment]
Changed, I wasn't sure because it's not a feature either :)

**Comment by fabpot** [comment]
The rule is that old branches can only get bug fixes, nothing else.

**Comment by fabpot** [comment]
Thank you @codedmonkey.

**Pull request merged**
