### PR TITLE
[GHA] Test on PHP 8.2 as experimental and 8.1 as a regular version

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by stof** [comment]
laminas/laminas-code does not support PHP 8.1 yet, so we cannot remove the `php 8.0.99` hack yet.

**Comment by nicolas-grekas** [comment]
Yes, that's what I figured out, we should remove the hack once https://github.com/laminas/laminas-code/pull/86 is merged. Thanks @derrabus for working on that PR btw!

**Comment by derrabus** [comment]
Wow, we are early this time. 😲

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
> we should remove the hack once [laminas/laminas-code#86](https://github.com/laminas/laminas-code/pull/86) is merged.

We would make this a `8.1.99` hack then that is only applied for the PHP 8.2 job.

**Pull request merged**
