### PR TITLE
[DI] Register default env var provided types

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/23888#discussion_r144703581
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

cc @nicolas-grekas

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
That's a BC break.

**Comment by ro0NL** [comment]
Against a BETA release? This is a new 3.4 feat :thinking:

**Comment by nicolas-grekas** [comment]
I would consider it as a bug fix also.

**Review by ogizanagi — APPROVED** [review]

**Comment by ro0NL** [comment]
Right, the bugfix in disguise is calling setProvidedTypes(). Following gettype() names is just something i think we need to choose now and be future proof (or at least is the desired behavior we want).

**Comment by jvasseur** [comment]
I think we should keep the current types,`int` and `bool` were chosen as the "correct" way of representing those types when scalar type hints were added to PHP. They are also the the standard way of using `is_*` function (even if `is_integer` and `is_boolean` exists as aliases).

The problem is `typeof` not returning non-standard type names. But that's not something that should imply changes in Symfony, it's more something that should be fixed in PHP (by deprecating `gettype` and introduction a replacement that return the correct strings).

**Comment by ro0NL** [comment]
Hm good point. We dont respect gettype() returning "double" either.

:+1: for shortnames from me.

**Comment by nicolas-grekas** [comment]
Status: needs work

**Comment by ro0NL** [comment]
Status: needs review

cc @jvasseur

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request merged**
