### PR TITLE
[Form] Add `webkitdirectory` to `FileType`

### PR DESCRIPTION
**Pull request by danielburger1337**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

See https://github.com/symfony/symfony/pull/52493

### CODE REVIEW

**Comment by danielburger1337** [comment]
> You are targeting branch "7.0" but it seems your PR description refers to branch "7.1". 

Branch 7.1 doesnt exit yet. Just ignore it for now?

**Comment by stof** [comment]
This can already be configured through the `attr` option, so I don't think we should add this option. We generally don't add options that just get copied into attr (for instance, we removed the `readonly` option a long time ago due to that).

So -1 from me for now, unless convinced otherwise.

**Comment by danielburger1337** [comment]
Fair point by stof. I don't care either way.

**Comment by nicolas-grekas** [comment]
I was wondering if we could provide a nicer way to support upload of directories. But I never tried so I have no clue :grimacing:

**Comment by xabbuh** [comment]
I agree with @stof. 👎 from me

**Comment by nicolas-grekas** [comment]
Thanks for submitting.

**Pull request closed without merging**
