### PR TITLE
[Form] Fixed empty conversion of Intl types

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20759, #21475
| License       | MIT
| Doc PR        | ~

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]
:+1:

Status: Reviewed

**Comment by geoffrey-brier** [comment]
Many thanks @HeahDude :+1:

**Comment by HeahDude** [comment]
Please wait before merging.

Status: I need to check something

**Comment by yceruto** [comment]
@HeahDude, This solution force `null` for empty string (good), but what if the dev needs to change this behavior through a callable `choice_value` option?

I wondering removing [these](https://github.com/HeahDude/symfony/blob/master/src/Symfony/Component/Form/Extension/Core/Type/CountryType.php#L82-L85) optimization could solves the problem instead of current solution, because `$value` will be `null` always unless you pass a custom `choice_value` option?

**Comment by HeahDude** [comment]
@yceruto I don't really understand what you want to approve here.

Indeed `$value` depends on `choice_value` option. The filtering added in this PR just prevents to handle empty string because there is no such need with countries, locales, etc.

**Comment by nicolas-grekas** [comment]
Status update @HeahDude ?

**Comment by HeahDude** [comment]
I'll be very busy this week, but now I've missed today's releases so I guess there is no rush.

Status: needs extra work in 2.7 :)

**Comment by fabpot** [comment]
@HeahDude  Any news?

**Comment by HeahDude** [comment]
Finally see #21879 with adds the failing tests. Will need a rebase once this other is merged.

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Pull request merged**
