### PR TITLE
[Console] Fix tests

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | N/A   
| License       | MIT
| Doc PR        | N/A

Fix Console tests after https://github.com/symfony/symfony/pull/26439 merge.

### CODE REVIEW

**Comment by noniagriconomie** [comment]
@ogizanagi my PR was done on 2.7 (as it was requested on the original issue by @Simperfit), all test were ok
but at the end it was merged on master :/ 
thank for reviewing tests on this branch

**Comment by ogizanagi** [comment]
@noniagriconomie : Yes, no worries! You did nothing wrong. This indeed happened while changing the branch for merging your PR into master :)

**Review by javiereguiluz — APPROVED** [review]
Thanks Maxime! And @noniagriconomie, don't worry because this is not your fault at all. Changing the merging branch can make this happen, so no worries!

**Review by Simperfit — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thanks @ogizanagi.

**Pull request merged**
