### PR TITLE
[Router] Eliminate extra strtr call in UrlGenerator

### PR DESCRIPTION
**Pull request by ostrolucky**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | possible in obscure edge cases
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | related: https://github.com/symfony/symfony/issues/30751#issuecomment-478260837
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by Tobion** [comment]
It was not put in the `$decodedChars` on purpose: The property can and is overwritten others. So they would miss this security sensitive encoding.

**Comment by ostrolucky** [comment]
I was aware of that, see my BC breaks note and is the reason I target master. Adding new elements to protected array properties is allowed as per your BC promise though. It's role of children to make sure they are futureproff and not just do snapshot of values at the time child class was written.

How is it security related though? Or better, what vulnerability would not encoding this cause?

**Comment by Tobion** [comment]
https://www.owasp.org/index.php/Path_Traversal

**Comment by fabpot** [comment]
Shall we close?

**Comment by nicolas-grekas** [comment]
Closing yes. @ostrolucky we would need a reproducer that would allow profiling the changes. In the linked issue you give some hints, but I don't know if any of them would make a difference without numbers first.

**Comment by ostrolucky** [comment]
Huh guys you are close button trigger happy.

@Tobion but that vulnerability is when you consume such URLs, here we generate them. This code is when having routes like `@Route("/../foo", "foo")`. I don't see how is support of these so important or how is this security related. Could you show example how is this vulnerability in this context?

@nicolas-grekas Reproducer is needed only to see HOW MUCH does the change help. Having one call less, given everything other same MUST be faster.

**Pull request closed without merging**
