### PR TITLE
[DependencyInjection] Add new Autoconfigure attributes

### PR DESCRIPTION
**Pull request by alexndlm**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

New Autoconfigure attributes for more convenient configuration of services.

### CODE REVIEW

**Comment by alexndlm** [comment]
@nicolas-grekas, would you check this PR?

If a general idea is correct and acceptable, I will create tests.

**Comment by nicolas-grekas** [comment]
I'm not sure this is useful at this stage:
- `#[Autowire]` already covers most of what `#[AutoconfigureBind*]` would provide
- `#[Required]` together with `#[Autowire]` already cover what `#[AutoconfigureCall*]` would

We might just need to allow `#[Autowire]` on properties so that we can also use it with `#[Required]`, but that'd be only for completeness.

WDYT?

**Comment by alexndlm** [comment]
With `#[Autowire]`, I can't configure with attributes the following case:
```php
<?php
declare(strict_types=1);

abstract class AbstractFooService
{
    public function __construct(private ProcessorInterface $processor)
    {
    }

    public function process(): void
    {
        $this->processor->process();
    }
}

final class FooService extends AbstractFooService
{
}

final class BarService extends AbstractFooService
{
}

return static function (ContainerConfigurator $containerConfigurator): void {
    $services = $containerConfigurator->services();

    $services->defaults()
        ->autowire()
        ->autoconfigure();

    $services->set(FooService::class)
        ->arg('$processor', 'processor.foo');

    $services->set(BarService::class)
        ->arg('$processor', 'processor.bar');
};
```

**Comment by nicolas-grekas** [comment]
Thanks for the example, that gives a much better idea of the motivation for this proposal!

What about this instead?
```php
#[Autowire(bind: '$processor', service: 'processor.foo')]
final class FooService extends AbstractFooService
{   
}

#[Autowire(bind: '$processor', service: 'processor.bar')]
final class BarService extends AbstractFooService
{
}   
```

The `bind` argument would be required when using the attribute on a class, and forbidden on parameters+properties.

**Comment by alexndlm** [comment]
Looks awesome.

Do you mind allowing `#[TaggedIterator]` and `#[TaggedLocator]` for class and property and adding `call` and `method` params?

The final result will be like this:
```php
#[Autowire(bind: '$processor', service: 'processor.foo')]
#[Autowire(call: 'setProcessor', service: 'processor.foo')]
#[Autowire(property: 'processor', service: 'processor.foo')]
#[TaggedIterator(bind: '$iterator', 'tag.name')]
#[TaggedIterator(call: 'setIterator', 'tag.name')]
#[TaggedIterator(property: 'iterator', 'tag.name')]
#[TaggedLocator(bind: '$locator', 'tag.name')]
#[TaggedLocator(call: 'setLocator', 'tag.name')]
#[TaggedLocator(property: 'locator', 'tag.name')]|
final class FooService
{
    #[Autowire(service: 'processor.foo')]
    public FooProcessor $processor2;

    #[TaggedIterator('tag.name')]
    public iterable $iterator2;

    #[TaggedLocator('tag.name')]
    public ServiceProviderInterface $locator2;

    public function __construct(
        #[Autowire(service: 'processor.foo')]
        private FooProcessor $processor,
        #[TaggedIterator('tag.name')]
        private iterable $iterator,
        #[TaggedLocator('tag.name')]
        private ServiceProviderInterface $locator,
    ) {
    }

    #[Autowire(service: 'processor.foo')]
    public function setProcessor(FooProcessor $processor): void
    {
        ...
    }
    
    #[TaggedIterator('tag.name')]
    public function setIterator(iterable $iterator): void
    {
        ...
    }

    #[TaggedLocator('tag.name')]
    public function setLocator(ServiceProviderInterface $locator): void
    {
        ...
    }
}
```

**Comment by alexndlm** [comment]
@nicolas-grekas, would you please check the proposal above?

If ok, I will close this PR and create three smaller PRs.

**Comment by nicolas-grekas** [comment]
Thanks for the update.

I'm not in favor of the proliferation of attributes. I'm therefor looking to add as little as possible.

As I mentioned, `#[Required]` already covers "call". The use case you have with inheritance can be covered already with `#[Autoconfigure(bind: ...)]`. But it's true that it's not very convenient to define the value of the binding.

I think we can improve all this by adding one attribute, which we might name just `#[Bind]`.

Its signature would be the following:
```
    public function __construct(
        string $name,
        string|array|TaggedIterator|TaggedLocator $value = null,
        string $service = null,
        string $expression = null,
        string $env = null,
        string $param = null,
    )
```

Note that `$value` accepts also `TaggedIterator|TaggedLocator` so that there would be no need to add corresponding dedicated attributes. One would instead use `#[Bind('foo', new TaggedIterator('tag'))]`.

WDYT?

**Comment by kbond** [comment]
> I think we can improve all this by adding one attribute, which we might name just #[Bind].

Love this idea!

**Comment by nicolas-grekas** [comment]
Still up to move this forward @alexndlm 
Feel free to close of course if you don't have time.
Someone else could maybe take over if `#[Bind]` makes sense to them.

**Comment by alexndlm** [comment]
@nicolas-grekas I close this PR and will try to make the new at this week. I hope I could find the time and brain to do this.

**Pull request closed without merging**
