### PR TITLE
Allow 'Name <email@address.com>' pattern in `framework.mailer.envelop.sender` config

### PR DESCRIPTION
**Pull request by maidmaid**
| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | https://github.com/symfony/symfony/pull/33091
| License       | MIT
| Doc PR        | /

```diff
# config/packages/mailer.yaml
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
-            sender: 'email@address.com'
+            sender: 'Name <email@address.com>'
```

### CODE REVIEW

**Comment by fabpot** [comment]
AFAIR, a Sender cannot have a name, so I would not allow it to strip it afterwards.

**Comment by maidmaid** [comment]
With gmail, mails are sent with a sender name :
image

**Comment by fabpot** [comment]
Here, you have a `From` header, not a `Sender` one.

**Comment by fabpot** [comment]
I'm closing as `Sender` is NOT the same as a `From `header. It overrides it.

**Comment by maidmaid** [comment]
So, how can I send emails with something like `My App <no-reply@my-app.com>` ?

**Comment by fabpot** [comment]
You need to use a `From` header. The `Sender` of the envelope is a way to override the `From` header in the dev env for instance (that way, you still have the email without any modification).

**Comment by maidmaid** [comment]
We should be able to set globally the From header like the Sender one. I could work on it if you agree.

**Comment by maidmaid** [comment]
Actually, there is no `Sender` header used by Mailer. The sender of the envelope is used in the `From` header.

https://github.com/symfony/symfony/blob/3987914982e8c7dbec7a85e533b849ece89ac885/src/Symfony/Component/Mailer/Transport/Smtp/SmtpTransport.php#L197

I feel like the `framework.mailer.envelope.sender` is misnamed and should be callled `framework.mailer.envelope.from`.

If I deprecate the `sender` config in favour of `from`, we could re-open this PR.

**Pull request closed without merging**
