### PR TITLE
Normalize "Added" in changelog-5.2

### PR DESCRIPTION
**Pull request by pascalheidmann**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | #32840 
| License       | MIT

Replace uniformly all instances of "add", "added", "Add" with "Added" in `CHANGELOG-5.2.md`

### CODE REVIEW

**Comment by jvasseur** [comment]
Since most lines are using the present, should we normalize it to "add" instead ?

**Comment by wouterj** [comment]
I'm not sure about the benefit of such changes. The CHANGELOG is automatically generated based on the merge commit message. Changing it could lead to all sorts of merge conflicts. As the merge commit message contains the PR title, it's not consistent at all. E.g. most of the lines are about adding a feature, but they don't start with "added".

If this is something the core team wants to spent time on - and I highly doubt if this is important enough - it should probably be contributed to the internal merge tool they're using.

**Comment by nicolas-grekas** [comment]
This file is auto-generated from PR titles.

**Comment by wouterj** [comment]
@nicolas-grekas maybe also close the related issue: https://github.com/symfony/symfony/issues/32840 ?

**Comment by nicolas-grekas** [comment]
The linked issue is about changelog files *in components*.

**Pull request closed without merging**
