### PR TITLE
[DebugBundle] Fix typo licence

### PR DESCRIPTION
**Pull request by BASAKSemih**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  |no
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by OskarStark** [comment]
We have many files with the same wording, besides that I am not really convinced, that this is a wrong wording.

**Comment by BASAKSemih** [comment]
also in my research we never use NONINFRINGEMENT we can NON-INFRINGEMENT or NON INFRINGEMENT

**Comment by fabpot** [comment]
For reference, the license here is like what we have: https://mit-license.org/

**Comment by BASAKSemih** [comment]
@fabpot thank you

**Pull request closed without merging**
