### PR TITLE
[Workflow] Remove `GuardEvent::getContext()` method without replacement

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Follow-up of https://github.com/symfony/symfony/pull/51484

### CODE REVIEW

**Comment by stof** [comment]
The upgrade-7.0 file must also be updated

**Comment by alexandre-daubois** [comment]
Actually, it has been already done last week:

https://github.com/symfony/symfony/blob/d1774f4f159e13dffd2f9a7dddc5fb8861ad882f/UPGRADE-7.0.md?plain=1#L489-L493

**Comment by stof** [comment]
ah OK. so this is something that has been forgotten in https://github.com/symfony/symfony/pull/51493 actually.

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alexandre-daubois.

**Pull request merged**
