### PR TITLE
[Notifier] use a clock to create datetime instances

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
https://github.com/symfony/symfony/pull/54756#discussion_r1591002660 made me think that we should rather use a clock to be able to properly mock the time in tests. If we agree on this approach, I'll update the other Notifier bridges as well.

**Review by OskarStark — APPROVED** [review]
I like it 👍

**Comment by xabbuh** [comment]
I updated all places in the Notifier component where we could use a clock.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
