### PR TITLE
[FrameworkBundle] Add support for `--sort` option for `--force` option with `translation:extract` command

### LINKED ISSUE #49250: Sort flag in `translation:extract` command doesn't seem to work
### Symfony version(s) affected

6.2

### Description

According to the help text
```
You can sort the output with the --sort flag:

  php bin/console translation:extract --dump-messages --sort=asc en AcmeBundle
  php bin/console translation:extract --dump-messages --sort=desc fr
```

However, when execute this command
```
php bin/console translation:extract --force --sort=asc --format=yaml --as-tree=3 en
```
will produce
```yaml
app:
    tagline: __app.tagline
title:
    signin: __title.signin
    signin.subtitle: __title.signin.subtitle
action:
    signin_with_google: __action.signin_with_google
    forgot_password: __action.forgot_password
label:
    email: __label.email
    password: __label.password
button:
    signin: __button.signin
    signup: __button.signup
```
which doesn't seem to be sorted. Similar with XLIFF file
```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
    <file source-language="en" target-language="en" datatype="plaintext" original="file.ext">
        <header>
            <tool tool-id="symfony" tool-name="Symfony" />
        </header>
        <body>
            <trans-unit id="0YNaGh4" resname="app.tagline">
                <source>app.tagline</source>
                <target>__app.tagline</target>
            </trans-unit>
            <trans-unit id="Qpet77t" resname="title.signin">
                <source>title.signin</source>
                <target>__title.signin</target>
            </trans-unit>
            <trans-unit id="mQx524n" resname="title.signin.subtitle">
                <source>title.signin.subtitle</source>
                <target>__title.signin.subtitle</target>
            </trans-unit>
            <trans-unit id="xmxEM1y" resname="action.signin_with_google">
                <source>action.signin_with_google</source>
                <target>__action.signin_with_google</target>
            </trans-unit>
            <trans-unit id="Bn6yTIX" resname="action.forgot_password">
                <source>action.forgot_password</source>
                <target>__action.forgot_password</target>
            </trans-unit>
            <trans-unit id="D2N6_cP" resname="label.email">
                <source>label.email</source>
                <target>__label.email</target>
            </trans-unit>
            <trans-unit id="9pvowqn" resname="label.password">
                <source>label.password</source>
                <target>__label.password</target>
            </trans-unit>
            <trans-unit id="IrKI5AG" resname="button.signin">
                <source>button.signin</source>
                <target>__button.signin</target>
            </trans-unit>
            <trans-unit id="WSGXkGL" resname="button.signup">
                <source>button.signup</source>
                <target>__button.signup</target>
            </trans-unit>
        </body>
    </file>
</xliff>
```

### How to reproduce

Just execute this command in a Symfony project that use `symfony/translation`
```
php bin/console translation:extract --force --sort=asc en
```

### Possible Solution

Output should be sorted by keywords.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mboultoureau**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #49250, #37918
| License       | MIT

### CODE REVIEW

**Comment by mboultoureau** [comment]
In the implementation, I used the `--sort` option also used for `--dump-messages`. However, this option defaults to "asc". So now, even without this option, all files will be sorted. Is this considered a regression?

**Comment by OskarStark** [comment]
As we are in feature freeze period, this must target 7.1 after the branch is created. 👍🏻

**Comment by mboultoureau** [comment]
> As we are in feature freeze period, this must target 7.1 after the branch is created. 👍🏻

I've just rebased the pull request on the 7.1 branch 👍.

**Comment by asispts** [comment]
Probably related to #37918 as well

**Comment by mboultoureau** [comment]
> Probably related to #37918 as well

Good point, I'll add it to the description, thanks!

**Comment by marien-probesys** [comment]
Oops, I didn't see you PR and I did my own (https://github.com/symfony/symfony/pull/52938) :sweat_smile: At least we have two ways to solve the problem, so we can expect it to be solved soon! :)

Just a note on your solution: the translations will be sorted with `asc` by default. It means that the translation files will contain a lot of changes when upgrading to a future version of Symfony… which might be fine, but I wasn't able to know if it was fine from core maintainers (so I kept the original behaviour when `--sort` isn't passed in my solution).

**Comment by mboultoureau** [comment]
> Oops, I didn't see you PR and I did my own (#52938) 😅 At least we have two ways to solve the problem, so we can expect it to be solved soon! :)
> 
> Just a note on your solution: the translations will be sorted with `asc` by default. It means that the translation files will contain a lot of changes when upgrading to a future version of Symfony… which might be fine, but I wasn't able to know if it was fine from core maintainers (so I kept the original behaviour when `--sort` isn't passed in my solution).

Thanks for your comment!
Good point, I asked the question on 28 October and depending on the answer I may or may not modify the pull request

**Comment by nicolas-grekas** [comment]
IIUC, this has been fixed in #58408
closing therefor, thanks for the PR.

**Pull request closed without merging**
