### PR TITLE
[HttpKernel] Clarify deprecations around annotated classes

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Review by wouterj — CHANGES_REQUESTED** [review]
Let's add a before/after code example in the UPGRADE guide, given this will be a common deprecation that people are facing?

**Comment by GromNaN** [comment]
In short, [it's a change of `use`](https://github.com/jolicode/automapper/pull/132/files).

```diff
- use Symfony\Component\HttpKernel\DependencyInjection\Extension;
+ use Symfony\Component\DependencyInjection\Extension\Extension;
```

**Comment by javiereguiluz** [comment]
Luckily the new class is available in 5.4 too (https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/DependencyInjection/Extension/Extension.php) so bundles that support a lot of different Symfony versions can safely switch to the new class and keep the same compatibility. Thanks!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
