### PR TITLE
[DependencyInjection] Fix order of arguments when mixing positional and named ones

### LINKED ISSUE #49118: Bug in named arguments since 5.4.17, not fixed by fix in 5.4.19
### Symfony version(s) affected

5.4.17, 5.4.19

### Description

The fix in named arguments in 5.4.17 triggered issues which 5.4.19 rectified. But seems to have not fixed all cases.

### How to reproduce

```
services:
    _defaults:
        public: true
        bind:
            $a: 'A'

    App\Controller\IndexController:
        arguments:
            $b: 'B'
```
Above service configuration will trigger:

```
In DefinitionErrorExceptionPass.php line 54:
                                                                 
  Invalid constructor argument for service "App\Controller\IndexController": integer expected but found string "b". Check your service definition.  
```

Adding them both to `bind` or both to `arguments` will work (but is undesired).

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49118
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Comment by msteltenpool** [comment]
Tried to see if this would fix the latest builds. The below issue popped up, need to dive a bit deeper to understand and isolate this new issue.

```
Invalid constructor argument 2 for service "[REMOVED]": argument 1 must be defined before. Check your   
  service definition.                                            
```

**Comment by msteltenpool** [comment]
`services.yaml`
```
services:
    # default configuration for services in *this* file
    _defaults:
        public: true
        bind:
            $a: 'A'

    App\Controller\IndexController:
        arguments:
            $b: 'B'
            $c: 'C'
```
`IndexController.php`
```
class IndexController
{
    public function __construct($b, $a, $c)
    {
    }
}
```
Result:
```
!!  In DefinitionErrorExceptionPass.php line 54:
!!                                                                                 
!!    Invalid constructor argument 2 for service "App\Controller\IndexController"  
!!    : argument 1 must be defined before. Check your service definition.    
```

**Comment by nicolas-grekas** [comment]
Thanks for checking. I'd need a reproducer to figure out what I missed. :pray:

**Comment by nicolas-grekas** [comment]
Got it thanks. PR updated.

**Comment by msteltenpool** [comment]
Confirmed. No issues any more on my end. Thanks!

**Pull request merged**
