### PR TITLE
[DependencyInjection] fix handling of empty DI extension configs

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27707
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
This will fix the issue reported in #27707. However, I am not sure if it is really a good idea to process all the `Configuration` classes that we can reach through extensions. It could trigger the same wrong behaviour in other packages too.

**Comment by ro0NL** [comment]
lets skip those extensions / apply array_filter here:

https://github.com/symfony/symfony/blob/5fe78a33d8f225ae142887a3dde0eeb036948e0f/src/Symfony/Component/DependencyInjection/Compiler/ValidateEnvPlaceholdersPass.php#L68-L70

it only validates env placeholders which are not present in empty configs anyway.

**Comment by xabbuh** [comment]
@ro0NL done

**Review by chalasr — APPROVED** [review]
would be even better with a test

**Review by nicolas-grekas — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
