### PR TITLE
Remove usage of empty function when possible

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

In recent code reviews we suggest to use `!$var` instead of `empty($var)`

In order to keep same code style in codebase, I replaced usages of empty when it is possible and typehinted

### CODE REVIEW

**Comment by ro0NL** [comment]
if we want to enforce it by rule, we should update psalm.xml

```
    <forbiddenFunctions>
        <function name="empty"/>
    </forbiddenFunctions>
```

**Review by ostrolucky — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
Can you add the Psalm config as well?

**Comment by alamirault** [comment]
Rule added to `psalm.xml`

**Comment by fabpot** [comment]
Thank you @alamirault.

**Pull request closed without merging**
