### PR TITLE
[WebProfilerBundle] fixed cursor as pointer when hovering over link.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | ~ |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by stof** [comment]
Please also add the ``e.preventDefault()`` in https://github.com/symfony/symfony/blob/f3b6ffc85a338abad7bb846c50a46ea57f996b2c/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base_js.html.twig#L397 before the early return, otherwise this case will make the page scroll to the top.

**Comment by stloyd** [comment]
Maybe better would be replace that `<a>` with `<button>`?

**Comment by stof** [comment]
this would force to add a bunch of CSS to reset the styles (we don't want a huge button here), but it would be more semantic markup indeed.

**Comment by aitboudad** [comment]
switched into `button`

**Comment by fabpot** [comment]
ping @symfony/deciders @javiereguiluz

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @aitboudad.

**Pull request merged**
