### PR TITLE
[Intl] Update ICU data to 60.2

### PR DESCRIPTION
**Pull request by jakzal**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Not much has changed in data we actually use in Symfony.
However, the extension compiled for ICU 60.2 behaves slightly differently in some cases.
This can be observed on one assertion that had to be disabled. There's no point in keeping it since the Symfony implementation does not support the behaviour.

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
Finally, an ICU update which doesn't make thousands of changes 😄  Thanks for taking care of this!

I know you haven't forgotten about #23545 but let's see if we can finish it because it could bring a nice performance improvement. Cheers!

**Comment by jakzal** [comment]
@javiereguiluz yeah, I remember about that one. I did some work on that it already. Stay tuned...

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jakzal.

**Comment by jakzal** [comment]
@fabpot why master?

**Comment by fabpot** [comment]
Because you made the PR on master and I merged it without spotting the mistake :) I will cherry-pick the commit in 2.7.

**Comment by jakzal** [comment]
Thanks!

**Pull request merged**
