### PR TITLE
[Workflow] Removed twig from composer.json (dev section, not used)

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21172
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by stof** [comment]
👍

**Comment by lyrixx** [comment]
Failures seems not related.

**Comment by xabbuh** [comment]
👍

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
