### PR TITLE
[Validator] Added Timezone Constraint Validator

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Q | A |
| --- | --- |
| Bug fix? | [no] |
| New feature? | [yes] |
| BC breaks? | [no] |
| Deprecations? | [no] |
| Tests pass? | [yes] |
| Fixed tickets | [] |
| License | MIT |
| Doc PR | yes (symfony/symfony-docs#3907) |

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@webmozart is it good enough for 2.7?  
we don't need for 3.x release to add - at least - only 1 validation constraint imo ^^

**Comment by xabbuh** [comment]
@mickaelandrieu Rebasing should make that failure go away as it was fixed a while ago. By the way, IIRC merging will become an issue (at least with the tools the mergers use) given that you deleted your Symfony fork.

**Comment by mickaelandrieu** [comment]
@xabbuh yes.

I was a little bored to always rebase my fork: it's been 8 months I maintain "a fork" of Symfony.

Maybe a cherry pick can be more easy than a total rebase ? /c @webmozart

**Comment by fabpot** [comment]
@mickaelandrieu Cherry-picking is not magic and won't solve merge conflicts; so cherry-picking or rebasing involves the same amount of work.... resolving the conflicts.

**Comment by mickaelandrieu** [comment]
@fabpot it's better at this point to make a new PR, I will some more time for rebase than actualy copy this code (only 3 cllasses). What do you think ?

**Pull request closed without merging**
