### PR TITLE
[Form] Used ::class constant

### PR DESCRIPTION
**Pull request by webmozart**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by webmozart** [comment]
This PR replaces various class name strings by the `::class` constants. The remaining occurrences of such strings can be replaced in other PRs.

**Comment by nicolas-grekas** [comment]
we refused such changes because it complicates merges from 2.8 to master for no practical benefit...

**Comment by nicolas-grekas** [comment]
See #16648 that has just been closed

**Comment by webmozart** [comment]
Ah ok.

**Comment by Tobion** [comment]
I thought about adding a `NAME` constant to all form types in 2.3 that have the FQCN.
In 3.0 we can then just change the constant to `const NAME = self::class;`.

Then we could use the `NAME` constant in all code and documentation and in all branches. I guess that would be easier to maintain and more readable.
But it also involves alot of merges.

**Pull request closed without merging**
