### PR TITLE
added PHP 7.1 to Travis

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Duplicates #19971 ;)

**Comment by fabpot** [comment]
Not really, this one has a good commit message, ready to be merged ;)

**Comment by nicolas-grekas** [comment]
Needs https://github.com/krakjoe/apcu/issues/201 on master (and .travis.yml should require apcu 5.1.6 once released of course)

**Comment by nicolas-grekas** [comment]
Closed in favor of #19971

**Pull request closed without merging**
