### PR TITLE
[travis] Enable mongo.so and memcache.so on PHP 7

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Not sure there are available for PHP 7, let's try.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
For 2.3 btw

**Comment by Tobion** [comment]
It's not available from my experience: https://travis-ci.org/doctrine/cache/jobs/84653900#L139

**Comment by nicolas-grekas** [comment]
Same here, closing

**Comment by stof** [comment]
mongo is not available on PHP 7, and it will never be. The MongoDB team is working on a whole new driver for PHP (the extension is named ``mongodb``), which will be the one to use on PHP 7 (however, it is not yet working on PHP 7 AFAIK)

**Pull request closed without merging**
