### PR TITLE
[Debug] display error file contents while debug

### PR DESCRIPTION
**Pull request by believer-ufa**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |

### CODE REVIEW

**Comment by fabpot** [comment]
Isn't it exactly what is displayed when expanding the first stack trace line?

**Comment by believer-ufa** [comment]
@fabpot, yes, its file from first stack trace line)

**Comment by fabpot** [comment]
Then, I don't understand what you are trying to do. Having the information twice does not seem that useful.

**Comment by believer-ufa** [comment]
This pull request add ability to see contents from this file directly on the screen page with an error message. I'm attached screenshots to show how it works)

**Comment by believer-ufa** [comment]
For example, sometimes an error in the template, which was compiled in the additional code (just like in the screenshots). And in such situations it is difficult to see where the error occurred specifically. Output file content helps me personally to understand the essence of the problem.

**Comment by believer-ufa** [comment]
And, without displaying the contents of the file, we can not immediately understand exactly what caused the error. We have to open this file. But in this version, we immediately see the whole situation.

**Comment by fabpot** [comment]
You do have the content of the file already, just click on the file name.

**Comment by believer-ufa** [comment]
Sorry, im using 2.7.* branch of this component in my Laravel 5.1 project. I just see full filename after double click on it. This feature you talking about is impletended in 2.8 or 3.0 branch?

**Comment by fabpot** [comment]
This feature has been available since day 1. And I can see the link from your screenshot (the gray part), so if it does nothing, it probably means that there are some JS errors. Can you have a look? In any case, I'm closing this PR as the feature already exist.

**Pull request closed without merging**
