### PR TITLE
Create an accessible class/id version of the TestContainer service

### PR DESCRIPTION
**Pull request by Pierstoval**
| Q             | A
| ------------- | ---
| Branch?       | 4.1 (but maybe master, not sure)
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Now we can write `$container = static::bootKernel()->getContainer()->get(TestContainer::class);` to get the container by calling the class name instead of the service id.

### CODE REVIEW

**Comment by jvasseur** [comment]
I'm :-1: here, the `TestContainer` class is an implementation detail and you should code around the `Container` class (or the PSR or Symfony `ContainerInterface` interface). This means your code should not be aware of it.

**Comment by Pierstoval** [comment]
We're only talking about code in our functional tests. Sometimes, you have to test services when dealing with a `KernelTestCase`-based test, so I don't see why the `Client` would benefit from this automatic change (remember that `$client->getContainer()` doesn't return the same container as before) and not the parent's test case.

Moreover, as the service is public and not explicitly flagged as "internal", anyone can use it, and in this case, for documentation & refactoring purposes in IDE integrations, I tend to think it's much better to use the FQCN instead of a string name that doesn't reference anything from the original service but a string id.

To me, FQCN as service id is one of the main features of the DIC that appeared in 3.3 and I think all services, could they be public or be injected in our services, should have a FQCN id when there is any chance for it to be injected or retrieved via the DIC.

**Comment by nicolas-grekas** [comment]
Why don't you use static::$container instead?

**Comment by Pierstoval** [comment]
> Why don't you use static::$container instead?

Ok I completely missed this part 😆 

If you still think it's useless to make it a FQCN service id, it can be closed, as `static::$container` is actually enough

**Comment by nicolas-grekas** [comment]
> TestContainer class is an implementation detail

I agree with this also, therefore closing, thanks for proposing anyway!

**Comment by gmponos** [comment]
Hi.. 

I wanted to create a PR that would add into the `client` (of tests) a helper function `getTestContainer`

I was looking for old isssues/PR if it was ever discussed and I discovered the current issue.

So would you be interested into rethinking this statement:

> TestContainer class is an implementation detail

**Why?**

- At the moment I am using `self::$container` but I am only making assumption that the container is initialized.
- As a programmer I have accepted that this is indeed the `test container` and it is not an abstraction detail that I am not aware of. When I call this container I am calling it because I need the private services out of it. So `self::$container` for me is always the test container just with a wrong name.
- Although I should have tested before.. but what is the behavior if you initialize two test clients. Are two containers initialized with different state?
- I need to be aware that the service I am trying to retrieve does not exist because it was not used:

Lets take the following example:

```
... run some tests before
$this->assertCount(static::$container->get('myservice_that_is_removed')->getLogs());
```

**Comment by Pierstoval** [comment]
> Although I should have tested before.. but what is the behavior if you initialize two test clients. Are two containers initialized with different state?

For this specific part, it depends on _how_ you initialize two clients. If it's via `static::createClient()`, you won't be able to initialize two clients ([check here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php#L43)), because the Client is actually a service from the container ([check here](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php#L49)).

For the rest, I'm not qualified to answer, even though I thought adding more types to make sure we have a TestContainer (and static analysis don't fail) was useful too

**Comment by gmponos** [comment]
>If it's via static::createClient(), you won't be able to initialize two clients (check here),
👍 

>and static analysis don't fail

that too.. 👍

**Pull request closed without merging**
