### PR TITLE
[Validator] Add missing translation for Greek (el)

### LINKED ISSUE #53027: Missing translations for Greek (el)
Hello,

There are some missing Greek (el) translations and we are looking for a **native** speaker to help us out. 

Here is a [short example](https://symfony-translations.nyholm.tech/#pr) of what you need to do. There are 4 rules: 

1. You must be a Greek (el) native speaker
2. You must look at the existing translations and follow the same "style" or "tone"
3. You must make your PR to branch 5.4
4. You must use the correct indentation (number of spaces)

These are the files that should be updated: 
- [src/Symfony/Component/Validator/Resources/translations/validators.el.xlf](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Resources/translations/validators.el.xlf)

> [!NOTE]
> If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by Pathpat**
| Q             | A
| ------------- | ---
| Branch?       |5.4 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix #53027  
| License       | MIT

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Great. Thank you very much. 

FYI. 
I saw that you checked out branch 7.1, did your changes and then created a PR to branch 5.4. (that is why the diff was soo large). I rebased your changes on branch 5.4 and now the diff looks good.

**Comment by Nyholm** [comment]
Btw. I added this to google translate and got a "did you mean?"

Is this correct or is it just a bad suggestion?
Screenshot 2023-12-17 at 10 56 57

**Comment by Pathpat** [comment]
Hello,
Is bad suggestion because on word "επιτρεπομενες" need the tone on the "o".The correct word is "επιτρεπόμενες". So if you can change this exactly word the translate will be perfect.And sorry for the confusion it was my first pr.

**Comment by Nyholm** [comment]
Okey. Thank you for confirming. 

> And sorry for the confusion it was my first pr.

No worries. When I did my first contribution to Symfony, I opened an issue saying "here are the missing translations". So you are already doing way better than I did =)

Now we just need to wait for a second maintainer to review this. Hopefully it will be merged within the next 2-3 days. 
Thank you again for your help.

**Comment by fabpot** [comment]
Thank you @Pathpat.

**Pull request merged**
