### PR TITLE
[Form] Make sure to collect child forms created on *_SET_DATA events

### LINKED ISSUE #29291: Rendering of the form panel of the profiler breaks due to data.id being undefined
**Symfony version(s) affected**: 3.4.18

**Description**  
The macro `form_tree_details` and `form_tree_entry` uses `data.id` in a lot of places. Some of them check for it to be defined, but some others don't. And I got a case where it fails:

```
Twig_Error_Runtime:
Neither the property "id" nor one of the methods "id()", "getid()"/"isid()"/"hasid()" or "__call()" exist and have public access in class "Symfony\Component\VarDumper\Cloner\Data".

  at vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/form.html.twig:429
```

**How to reproduce**  
I don't have a standalone reproducer for now.

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #29291
| License       | MIT
| Doc PR        | -

See reproducer provided by @WubbleWobble https://github.com/WubbleWobble/symfony-issue-29291.

### CODE REVIEW

**Comment by stof** [comment]
wouldn't this have a bad side-effect if the call to `setData` happens after creating the form rather than passing the data to the form factory directly ?

**Comment by yceruto** [comment]
@stof in that case `$this->defaultDataSet` is already `true` and `setData()` wouldn't be called again.

**Comment by yceruto** [comment]
I've also checked the case when dynamic child forms are added on `PRE_SUBMIT` event and they are correctly collected thanks to this code:
https://github.com/symfony/symfony/blob/29cabf94c513e7d1df3373d372286a4dc091f049/src/Symfony/Component/Form/Extension/DataCollector/FormDataCollector.php#L151-L155

**Comment by OskarStark** [comment]
Is it possible to add a testcase?

**Review by OskarStark — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Pull request merged**
