### PR TITLE
[FrameworkBundle] Hide server:log command based on deps

### PR DESCRIPTION
**Pull request by sroze**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25025
| License       | MIT
| Doc PR        | ø

Remove the `server:log` command if monolog is not installed.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by ro0NL** [comment]
in fact, the issue looks related to lazy command loading given `ServerLogCommand::isEnabled` is called :thinking: 

looking at `Application::get` we call `add($lazyLoadedCommand)`, but `add()` itself doesnt register if it's a disabled command, yet `get()` happily returns $lazyLoadedCommand anyway. Causing `server:log` also to look available in `bin/console list`.

**Comment by chalasr** [comment]
See #25030

**Comment by sroze** [comment]
I think I prefer your approach @chalasr 👍

**Review by chalasr — APPROVED** [review]
Actually this one stays fine regarding the framework, no need to process a useless definition esp. based on class existence.

**Comment by nicolas-grekas** [comment]
Thank you @sroze.

**Pull request merged**
