### PR TITLE
[String] Fix skip condition for INTL

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/commit/1bbacd5c86e7058f05e27b360091440f1331e26a#r52732121
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
>They don't, I still get the failures from #38957.

We should report the issue to ICU...

**Comment by derrabus** [comment]
> > They don't, I still get the failures from #38957.
> 
> We should report the issue to ICU...

I don't feel like I know enough about unicode to write a proper bug report. 😓

**Comment by nicolas-grekas** [comment]
Reported at https://unicode-org.atlassian.net/browse/CLDR-14861

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @derrabus.

**Pull request merged**
