### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | --
| License       | MIT

### CODE REVIEW

**Review by yceruto — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
For 7.1.

**Comment by fabpot** [comment]
It does not merge cleanly on 7.1.

**Comment by OskarStark** [comment]
I thought it would avoid merge conflicts in the long run if merging up from 5.4 but I can rebase

**Comment by fabpot** [comment]
> I thought it would avoid merge conflicts in the long run if merging up from 5.4 but I can rebase

I want us to be very strict on the "only bug fixes go to lower branches" policy (like for CS changes).

**Comment by OskarStark** [comment]
> I want us to be very strict on the "only bug fixes go to lower branches" policy (like for CS changes).

Allright 👍

**Comment by OskarStark** [comment]
Rebased on `7.1` ✅

**Comment by fabpot** [comment]
Thank you @OskarStark.

**Pull request merged**
