### PR TITLE
[VarDumper] Fixed phpDoc

### PR DESCRIPTION
**Pull request by enomotodev**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

- I added it because nullable was not mentioned in phpdoc

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Review by vudaltsov — APPROVED** [review]

**Review by OskarStark — COMMENTED** [review]
Wait, not sure what’s right here, because you are not allowed to pass null for the second parameter. In this case the typehint needs a leading „?“... 🤔

Friendly ping @nicolas-grekas

**Comment by vudaltsov** [comment]
@OskarStark , it's okay. If you have `null` as a default value that means that the argument is nullable. Otherwise how it might have `null` as a default? See the accepted RFC https://wiki.php.net/rfc/nullable_types#default_values

**Comment by OskarStark** [comment]
I know but how to use null and a custom flag parameter?

**Review by xabbuh — APPROVED** [review]

**Comment by vudaltsov** [comment]
@OskarStark , `new SomeDumper('output', null, 1)`

**Comment by OskarStark** [comment]
Ah sorry, TIL

(?string $foo) allows the same values as (string $foo = null), except only the latter has a default. Thank you!

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @enomotodev.

**Pull request merged**
