### PR TITLE
[HttpFoundation] Added missing HTTP status code

### PR DESCRIPTION
**Pull request by lyrixx**
from RFC: https://github.com/joho/7XX-rfc

### CODE REVIEW

**Comment by hhamon** [comment]
:+1: :)

**Comment by jderusse** [comment]
duplicate of #12286 ?

**Comment by lyrixx** [comment]
Already refused in #12286 ; I missed it.

**Comment by gnugat** [comment]
Yeah, you "[missed it](https://github.com/symfony/symfony/pull/12286#issuecomment-60072292)" :D

> **lyrixx** *commented on 22 Oct 2014*
> You should have opened this PR on 2015/04/01

**Pull request closed without merging**
