### PR TITLE
[FrameworkBundle] Add default translations path option and convention

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | ToDo

Similar to Twig default path, this proposal adds a `default_path` option under `translator` config:
```yaml
framework:
    translator:
        default_path: '%kernel.project_dir%/config/translations'
```
adding this default path to the discovered translations dirs. Thus, overriding bundle translations is possible by using this new convention: `config/translations/<BundleName>/messages.en.xlf`.

Also a new container parameter `%translator.default_path%` is defined by external purpose (similar to https://github.com/symfony/symfony/pull/24840)

Note: The current convention `%kernel.root_dir%/Resources/translations` path has priority over the new one.

TODO:
- [x] Add more tests about the new path
- [x] Update changelog

### CODE REVIEW

**Comment by yceruto** [comment]
Having this in 3.4/4.0 could be awesome but I guess it doesn't qualify, right?

**Comment by yceruto** [comment]
Some opinion about this? I'd like to finish it :)

**Comment by fabpot** [comment]
It does qualify. LGTM.

**Comment by fabpot** [comment]
Wouldn't it be "better" to move them to `config/translations`? Like for serialization and validation configs?

**Comment by yceruto** [comment]
Great! ready :)

**Comment by fabpot** [comment]
Thank you @yceruto.

**Comment by ogizanagi** [comment]
Do we want to reflect this change in the [existing translation recipe](https://github.com/symfony/recipes/blob/master/symfony/translation/3.3/config/packages/translation.yaml#L5) or create a new one for 3.4?

**Comment by fabpot** [comment]
@ogizanagi Let's update the current recipe to point to the "right" directory. Can you submit a PR?

**Comment by ogizanagi** [comment]
Sure. Done in https://github.com/symfony/recipes/pull/249

**Pull request merged**
