### PR TITLE
[Finder] fix wrong method call casing

### PR DESCRIPTION
**Pull request by azjezz**
fix wrong method call casing for [`SplFileInfo::getRealPath()`](https://www.php.net/manual/en/splfileinfo.getrealpath.php)

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

### CODE REVIEW

**Review by ro0NL — APPROVED** [review]
one more at https://github.com/symfony/symfony/blob/ce269367305661ac8d32c9e5cce5f07b8ae7ddf2/src/Symfony/Component/Filesystem/Filesystem.php#L575 (`getPathName`) :angel:

**Comment by azjezz** [comment]
@ro0NL i will open another PR for that, the statement was introduced in 4.3 ( https://github.com/symfony/symfony/commit/59437a4af9790edbc729dc783f3d8f0f6aeefd99 ), this PR targets 3.4 :angel:

**Comment by azjezz** [comment]
#31607

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Good catch, thanks @azjezz.

**Pull request merged**
