### PR TITLE
[DependencyInjection] Handle INI arrays

### LINKED ISSUE #47357: IniFileLoader throws when parsing arrays
### Symfony version(s) affected

3.2.0-current

### Description

Since https://github.com/symfony/symfony/pull/20232/, [IniFileLoader](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/DependencyInjection/Loader/IniFileLoader.php) no longer works correctly with ini files containing arrays:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\DependencyInjection\Loader\IniFileLoader::phpize() must be of the type string, array given, called in vendor/symfony/dependency-injection/Loader/IniFileLoader.php on line 44 and defined in vendor/symfony/dependency-injection/Loader/IniFileLoader.php on line 72

Call Stack:
1. {main}()
2. Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load()
3. Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseImports() vendor/symfony/dependency-injection/Loader/XmlFileLoader.php:59
4. Symfony\Component\DependencyInjection\Loader\FileLoader->import() vendor/symfony/dependency-injection/Loader/XmlFileLoader.php:111
5. Symfony\Component\Config\Loader\FileLoader->import() vendor/symfony/dependency-injection/Loader/FileLoader.php:66
6. Symfony\Component\Config\Loader\FileLoader->doImport() vendor/symfony/config/Loader/FileLoader.php:104
7. Symfony\Component\DependencyInjection\Loader\IniFileLoader->load() vendor/symfony/config/Loader/FileLoader.php:165
8. Symfony\Component\DependencyInjection\Loader\IniFileLoader->phpize() vendor/symfony/dependency-injection/Loader/IniFileLoader.php:44
```

Previously, per the default behaviour of `INI_SCANNER_NORMAL`, the loader would always return values as `string|string[]`. There were some possible value substitutions, eg `"true"` became `"1"`, however the deepest nested values were always a string.

The linked PR added intermediate parsing to convert these values to other scalar types, but incorrectly assumes the only possible input type is `string`. (Since version 4.4, this is by typehinting the private method's parameter, and before that by immediately calling `\rtrim` on the value.) This conversion isn't mentioned at all in the [upgrading notes](https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.2.md) and there's still a [caution in the docs](https://symfony.com/doc/current/components/config/resources.html) suggesting other types aren't supported.

### How to reproduce

Load a config file such as:

```
[parameters]

this.works = true
these.work[] = false
these.fail[] = true
```

Expected values:
```
[
    "this.works" => true,
    "these.work" => [
        false
    ],
    "these.fail" => [
        true
    ]
]
```

Actual behaviour: `TypeError` thrown

### Possible Solution

`IniFileLoader::load` should call `\is_array` on each parameter value, and when true call `IniFileLoader::phpize` for each array element instead of passing the entire array only once.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/47357
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by fabpot** [comment]
Looks like a new feature to me.

**Comment by lpd-au** [comment]
> Looks like a new feature to me.

In what way? It's fixing a regression in 3.2.0.

**Comment by fabpot** [comment]
It's not supported today, so that's a new feature.

**Comment by lpd-au** [comment]
Strange perspective, not throwing a TypeError on valid input is a feature?

**Comment by fabpot** [comment]
> Strange perspective, not throwing a TypeError on valid input is a feature?

But then, everything is a bug fix.
Anyway, we favor stability over everything else in our maintained branches, so we're very strict in what we consider a bug.

**Comment by lpd-au** [comment]
> But then, everything is a bug fix.
> Anyway, we favor stability over everything else in our maintained branches, so we're very strict in what we consider a bug.

I don't understand the point you're trying to make, there's a great scope between fixing a thrown `Error` and adding new functionality. Nonetheless, this should have little to no backwards compatibility impact; if your code was working beforehand, it'll still work now.

**Comment by MatTheCat** [comment]
> It's not supported today, so that's a new feature.

But it was at some point 🤔 I don't know how Symfony handles regressions though ([Wikipedia says regressions are bugs](https://en.wikipedia.org/wiki/Software_regression)).

**Comment by fabpot** [comment]
Symfony 3.2 EOLed was 5 years ago. Nobody reported this since then. So, that's a new feature.
As I said, we have a very strict definition of what is considered a new feature vs a bug.

**Comment by fabpot** [comment]
Thank you @MatTheCat.

**Comment by lpd-au** [comment]
> Symfony 3.2 EOLed was 5 years ago. Nobody reported this since then. So, that's a new feature. As I said, we have a very strict definition of what is considered a new feature vs a bug.

For PHP 7.x, this only became a TypeError in 4.4, before that it was only a PHP warning. Btw, this "nobody" reported it while trying to upgrade a legacy app.

**Pull request merged**
