### PR TITLE
Fix typo in Norwegian translation

### PR DESCRIPTION
**Pull request by tarjei**
| Q             | A
| ------------- | ---
| Branch?       | master for features / 3.4 up to 4.2 for bug fixes 
| Bug fix?      | no
| New feature?  |no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT

Minor translation fix.

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
Google Translate considers both right ... but `påloggingsinformasjonen` gives 13,900 results on Google and `påloggingsinformasjon` gives 588,000 results.

**Comment by tarjei** [comment]
It's a bit like saying "Invalid the credentials." instead of "Invalid credentials." :)

**Review by stof — APPROVED** [review]
I know nothing about Norwegian (as most of the core team) so I will assume this is right.

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @tarjei.

**Pull request merged**
