### PR TITLE
[FrameworkBundle] Initialize translator with the default locale.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13887 |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by aitboudad** [comment]
@stof  allowing `null` value for locale look wrong should we throw an exception in that case or we use `en` as default locale ?

**Comment by Tobion** [comment]
@aitboudad how could the locale be null now? the `default_locale` should validate that it is not null if you mean that.

**Comment by aitboudad** [comment]
I'm not talking about `default_locale` but it looks good idea too.
right now the `Symfony\Component\Translation\Translator` allow set `null` value for the default locale but it shouldn't( [Translator.php#L77](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/Translator.php#L77))  so I think we need to add some check in [setLocale](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/Translator.php#L151) to avoid null value.

**Comment by Tobion** [comment]
The constructor does not allow null value. It says `string`. So I don't see what you mean.

**Comment by aitboudad** [comment]
It says `string` but we can pass `null` value.

```patch
     public function setLocale($locale)
     {
+        if (null === $locale) {
+            throw new \InvalidArgumentException(sprintf('Invalid "%s" locale.', $locale));
+        }
         $this->assertValidLocale($locale);
         $this->locale = $locale;
     }
```

**Comment by Tobion** [comment]
Why would you do that? Wrong values are not supported. What if someone passes an array or an object? You want to catch that as well?

**Comment by aitboudad** [comment]
@Tobion ok seems that it's not necessary :)

**Comment by stof** [comment]
@aitboudad our rule in Symfony is to rely on the phpdoc to describe the signature of the method for scalar types (because PHP 5.x does not have scalar typehints). We don't perform scalar type checks in all methods.

**Comment by Tobion** [comment]
:+1:

**Comment by Tobion** [comment]
Thank you @aitboudad for taking care of this regression.

**Comment by aitboudad** [comment]
@stof :+1:

**Comment by raistlin** [comment]
This change breaks compatibility when used with JMSI18nRoutingBundle.

With this change, all translations are always returned in default locale and the only way to display right translation is to override twig translation extension and get language from request.
On controllers it's also needed to make this change and always set target language to translate.

Please, revert this change on 2.6.x.

**Comment by jakzal** [comment]
@raistlin could you create a new issue please?

**Comment by aitboudad** [comment]
@raistlin not sure if I understand correctly, we only use the default locale instead of null here.

**Comment by raistlin** [comment]
@aitboudad Right, but we use JMSI18nRoutingBundle, and this bundle force us to set framework fallback translation, so I can not set default_locale as null any more, and default translation is set to fallback translation.

I have overridden 'trans' twig extension to fix this problem, but using translator in controllers still don't work properly, I need to set the locale on every trans call, or I will always get translation on default locale instead of locale of the request.

**Comment by aitboudad** [comment]
@raistlin would you mind reproducing the issue in a fork of Symfony Standard edition :) ?

**Comment by aitboudad** [comment]
@raistlin any news ?

**Comment by raistlin** [comment]
@aitboudad I did not have enough free time to setup a broken project, I will create it when I didn't have deadline pressures, sorry.

**Comment by aitboudad** [comment]
@raistlin no worry, FYI I tested with `JMSI18nRoutingBundle` without getting any issues.

**Comment by raistlin** [comment]
mmm could you please post the configuration of your project?

May be I have something messed up with configuration files

**Comment by raistlin** [comment]
Found and fixed.
I had a Translator that override original symfony translator.

**Comment by aitboudad** [comment]
@raistlin great :)

**Pull request merged**
