### PR TITLE
remove not needed PHP version switch

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
What's the reasoning for this change? Shouldn't we do this on 6.3 only?

**Comment by xabbuh** [comment]
We could 🤷‍♂️ But I do not really see a reason to keep dead code in a script that we only use to execute the Symfony test suite.

**Comment by stof** [comment]
the phpunit bridge still supports PHP 7.1.3+, so this is not dead code

**Comment by xabbuh** [comment]
This file is not part of the bridge.

**Comment by stof** [comment]
But this file is also used when running the tests of the bridge IIRC

**Review by nicolas-grekas — COMMENTED** [review]
> This file is not part of the bridge.

got it
and we don't test the bridge on php 7.* anymore on 6.* branches (but we still run it on 7.2, on the 5.4 branch)

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
