### PR TITLE
[Form] fix #15544 when a collection type attribute "required" is false, "prototype" should too

### LINKED ISSUE #15544: [Bug] [Form] 2.7 - Form collection prototype required option
When using the 'collection' form type with the 'required' option set to false, The rendered HTML is different between the form_widget() macro and the prototype. The macro does not output the required field contrary to the prototype field.

Form definition :
```
$formBuilder->add('emails', 'collection', array(
            'type' => 'email',
            'allow_add' => true,
            'required' => false
        ));
```
Twig Template : 
```
{% for emailField in form.emails %}
    {{ form_widget(emailField) }}
{% endfor %}
```
HTML output :
```
<input name="form[emails][1]" id="form_emails_1" type="email">
<input name="form[emails][2]" id="form_emails_2" type="email">
<input name="form[emails][3]" id="form_emails_2" type="email">
```
data-prototype:
```
<input type="email" id="form_emails___name__" 
name="form[emails][__name__]" required="required" class="" />
```
Is that, the expected result ? I would expect the prototype field not to contain 'required' as the form_widget() macro doesn't output the 'required' field

I know the 'option' parameter is supposed to do the job but as the 'required' parameter is supported, the prototype output should match the macro output.
```
'options' => array(
       'required' => false
  )
```

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15544 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Kevinrob** [comment]
Thanks, this PR is a good fix :+1:

**Comment by xabbuh** [comment]
:+1: LGTM

@webmozart Can you please have a look here too? :)

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Pull request closed without merging**
