### PR TITLE
[Form] minor fix tests of Bootstrap layout

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Branch | 2.8+ |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by HeahDude** [comment]
Some residue of #17760 because tests were added in 2.8 only.

**Comment by HeahDude** [comment]
ping __@symfony/mergers__

**Comment by HeahDude** [comment]
@xabbuh same here...

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Pull request merged**
