### PR TITLE
[Security] Add missing Dutch translations

### LINKED ISSUE #41042: Missing translations for Dutch (nl)
Hello,

There are some missing translation for Dutch (nl). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Security/Core/Resources/translations/security.nl.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.nl.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by cwiesenekker**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #41042
| License       | MIT

Sorry screwed up my previous branch while rebasing and amending the author name of the commits.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by cwiesenekker** [comment]
Sorry screwd up https://github.com/symfony/symfony/pull/41070 so new PR.

**Comment by Nyholm** [comment]
Could @wouterj have a second set of eyes on this?

**Comment by cwiesenekker** [comment]
@ro0NL reviewed and approved the previous PR also for Dutch.

**Review by wouterj — APPROVED** [review]
I definitely can confirm it's Dutch in the `<target>` elements :wink:

**Comment by derrabus** [comment]
Thank you @cwiesenekker.

**Pull request merged**
