### PR TITLE
[Form][DoctrineBridge] Optimize EntityType by only loading choices for values restricted by values

### PR DESCRIPTION
**Pull request by guilhermeblanco**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

Optimize EntityType by only loading choices for values in the same way that EntityLoader customization does (if you provide a query_builder).

### CODE REVIEW

**Comment by phansys** [comment]
Recently I had to manage this behavior through form options since I have a lot of choices and performance was seriously degraded with the amount of results.
:+1:

**Comment by fabpot** [comment]
Does it make sense to merge this into 2.3?

**Comment by guilhermeblanco** [comment]
@fabpot Yes. =) Doctrine 2.3 addressed some issues with `findBy` looking for associations as keys, but you cannot use it inside of EntityType, so it's irrelevant.

**Comment by fabpot** [comment]
Thank you @guilhermeblanco.

**Comment by guilhermeblanco** [comment]
@fabpot Why this was not merged into Symfony 2.6?

**Comment by fabpot** [comment]
@guilhermeblanco Sorry about that, I made a mistake when merging. I'm going to merge it manually into 2.3.

**Comment by drmonty** [comment]
This commit introduces an issue with mongodb, see #13961

**Pull request merged**
