### PR TITLE
[appveyor] Run the test suite on PHP 7.1

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Strange failure on a previously (missconfigured) build:
https://ci.appveyor.com/project/fabpot/symfony/build/1.0.21534

**Comment by ChadSikorra** [comment]
FYI, I wrote a Powershell script to automate the install of PHP on AppVeyor (as chocolatey was super buggy/inconsistent for me). I put the script out here:

https://github.com/ChadSikorra/ps-install-php

Example usage here:

https://github.com/ldaptools/ldaptools-bundle/blob/master/appveyor.yml

Feel free to copy the script if you feel like incorporating it. It's not the cleanest Powershell script, but it does the job.

**Comment by nicolas-grekas** [comment]
now green
@ChadSikorra thanks for the link, but installing php on windows for the purpose of testing here is really easy, so we don't need any other script IMHO.

**Comment by ChadSikorra** [comment]
Shouldn't the AppVeyor build essentially mirror the Travis build? I'd think testing such a large code base against the same versions of PHP on Windows as is done on Linux in Travis would be the target?

**Comment by nicolas-grekas** [comment]
Nope, it's not: we use appveyor to test different conditions than on Travis on purpose, in order to exercice the code base in more diverse situations (different extensions loaded, lowest supported version of PHP)

**Comment by stof** [comment]
@ChadSikorra Appveyor is not good at running multiple jobs with different PHP versions in parallel (cache is not keyed by PHP version, invalidating the cache for each job). This is why we restricted ourselves to a single job.
And then, running all tests on all PHP versions twice is not really worth it. Especially when you consider that we have limits on concurrent jobs on each platform, and we don't want to have jobs waiting in the queue for days due to the activity on the repo (in the past, when the build was slower, we used to have to wait for hours to have the CI result during active hours due to this quota).

**Pull request merged**
