### PR TITLE
[travis] Do not exclude legacy tests on 2.7

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

This is to be reverted on 2.8, where legacy tests should be excluded.

### CODE REVIEW

**Comment by Tobion** [comment]
Why should legacy tests be excluded?

**Comment by nicolas-grekas** [comment]
Because on this matrix line, 2.8 is installed with 3.0 deps. Legacy tests are for interfaces that are removed in 3.0.

**Comment by Tobion** [comment]
I think tests should be skipped if they rely on an interface that doesn't exist (because a 3.0 dep is installed). Just not executing all legacy tests will potentially hide alot of problems or wrong dependencies.

**Comment by nicolas-grekas** [comment]
We are talking about one line in the matrix, not all of them. All other lines on 2.8 do run legacy tests.
This line is very specific and only for testing 2.8 with 3.0.

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
