### PR TITLE
[Validator] Added context object method callback to choice validator

### PR DESCRIPTION
**Pull request by Bouwdie**
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Bouwdie** [comment]
Could the build please be restarted? I squashed a commit on the fork branch.

**Comment by jakzal** [comment]
@Bouwdie the build is triggered automatically on push. I restarted it nevertheless.

The failure is legitimate (it's introduced by this PR).

**Comment by Bouwdie** [comment]
@jakzal thx for restarting them anyway! I should have taken the behaviour of is_callable into account. 
https://3v4l.org/j8CBb. The test opened something up that was already occurred if a non-static method was given as callback.

**Comment by Bouwdie** [comment]
@jakzal Everything is working correctly and the build succeeds. Is there anything more i can do to speed the review process?

**Comment by fraghi** [comment]
:+1:

**Comment by bdemes** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @Bouwdie.

**Comment by patrick-mcdougle** [comment]
Documenting this feature here: https://github.com/symfony/symfony-docs/pull/6973

**Comment by Bouwdie** [comment]
@ro0NL Thank you for noticing this pull request :+1:

**Pull request closed without merging**
