### PR TITLE
[DI]  CheckTypeDeclarationsPass now checks if value is type of parameter type 

### PR DESCRIPTION
**Pull request by pfazzi**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #35420 
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you provide a reproducer for the issue? Maybe a test case?
There is already such a check when $value is a Definition.
Which triggers this: what's the type/class of $value in your case and more importantly how does it get there?

**Comment by pfazzi** [comment]
Yes i can, i can anticipate you that error happens when `$value` is not a 'Definition` but instance of `Symfony\Component\ExpressionLanguage\Expression`

**Comment by pfazzi** [comment]
@nicolas-grekas I have just integrated a test case

**Review by nicolas-grekas — APPROVED** [review]
(I pushed some changes on your fork to make the code less error-prone)

**Comment by nicolas-grekas** [comment]
Thank you @pfazzi.

**Pull request merged**
