### PR TITLE
[WebProfilerBundle] Added tabindex="-1" to not interfer with normal UX

### PR DESCRIPTION
**Pull request by drAlberT**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by drAlberT** [comment]
Sorry .. my first PR .. should be ok now (?) :)

**Comment by fabpot** [comment]
:+1: should be merged in 2.3 though.

**Comment by drAlberT** [comment]
:+1:  thanks fabien :)

**Comment by Tobion** [comment]
I'm not sure about this one. If you don't want interference with the toolbar, just close it. With this change, how do you navigate to the toolbar menu without mouse?

**Comment by drAlberT** [comment]
Just implement access key then ..

Debugging should be aside the normal behavior, not something changing it ... it's not quantum mechanic, I'd  like to study my application without interfere, not so much at least ;)

**Comment by Tobion** [comment]
It's about accessability. And there are also developers that need accessability.

**Comment by drAlberT** [comment]
@Tobion I agree .. but having tab to jump here and there without much control is not so accessible too .. so I think the right approach should be to introduce an access key to show/hide the dev bar.

**Comment by fabpot** [comment]
@drAlberT An access key looks like a good idea.

**Comment by fabpot** [comment]
@drAlberT Can you finish this PR?

**Comment by drAlberT** [comment]
What about [D] (Debug) ?  it's not in the already taken standard AC http://www.standardaccesskeys.com/SAK2014/

**Comment by fabpot** [comment]
Fine by me. ping @symfony/deciders

**Comment by drAlberT** [comment]
I leaved the tabindex -1 in order to not interfere and added accesskey="D" in order to keep TB accessible

**Comment by xabbuh** [comment]
Just to make sure: Can I now navigate to the toolbar using the tab key or what am I supposed to use now when I don't want to use the mouse?

**Comment by drAlberT** [comment]
Access key "D" will toggle the bar, then tab should follow the natural order

**Comment by fabpot** [comment]
Thank you @drAlberT.

**Pull request closed without merging**
