### PR TITLE
[Form] silently ignore uninitialized properties when mapping data to forms

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #36492
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by lucasmezencio** [comment]
Please, this PR must be accepted! 🙏

**Review by yceruto — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by lucasmezencio** [comment]
Guys, when is this going to be on `5.1`?

**Comment by xabbuh** [comment]
patch releases are published roughly every four weeks

**Comment by chypriote** [comment]
Hello @xabbuh, am I right in thinking that this PR will allow the code described here to function ? https://github.com/symfony/symfony/issues/36051

Thanks !

**Comment by xabbuh** [comment]
@chypriote yes, it should

**Comment by chypriote** [comment]
Nice, thanks for your work :)

**Pull request merged**
