### PR TITLE
[Validator] add Password constraint

### PR DESCRIPTION
**Pull request by babeuloula**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | /
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Hello,

In order to comply with the recommendations of the CNIL, I propose this little password check.

I did not update the CHANGELOG.md because you're in feature freeze. I will be update and rebase when you release Symfony 6.1 and when you'll create the branch for 6.2.

Thanks.

### CODE REVIEW

**Comment by stof** [comment]
What does this have to do with the GDPR ?

**Comment by babeuloula** [comment]
Sorry CNIL

**Comment by stof** [comment]
Given that https://packagist.org/packages/rollerworks/password-strength-bundle already provides this feature and the NIST explicitly rules [against password complexity requirements](https://pages.nist.gov/800-63-3/sp800-63b.html#appA) (due to them annoying the users while not improving security at all in practice), I vote -1 on adding that in the core.

**Comment by stof** [comment]
@babeuloula please provide a link to that CNIL resource

**Comment by babeuloula** [comment]
@stof You can see the CNIL recommandation here : https://www.cnil.fr/fr/mot-de-passe

This is just a constraint, you can don't use it if you want. And it's fully configurable.

**Comment by derrabus** [comment]
Thank you for your proposal, but I agree with @stof here. If we were to introduce a constraint called `Password`, I'd expect it to be a best practise for Symfony projects to use that constraint. And from my point of view, that is not the case.

That aside, the name `Password` is a bit ambigous. If we added this constraint, the name should reflect that the constraint validates if a given string may be used as password, so it is not confused with the already existing `UserPassword` constraint.

I'd also like to leave this comic here.

**Comment by fabpot** [comment]
Closing as explained.
In any case, you can still use it in your projects.
Thank you for proposing.

**Pull request closed without merging**
