### PR TITLE
[WebProfilerBundle] Add link to last 10 requests in request panel

### PR DESCRIPTION
**Pull request by jameshalsall**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #19506 |
| License | MIT |

last-10

### CODE REVIEW

**Comment by HeahDude** [comment]
This link may be handy but it's just saving one click, just click anywhere get you to it, but mostly I don't like having it in the middle of the request information.

**Comment by HeahDude** [comment]
Maybe it would be better to put it on top and as one part blue link saying something like "Show history"?

**Comment by fabpot** [comment]
I know that we already had some discussion about this topic. ping @javiereguiluz

**Comment by ro0NL** [comment]
What about a global icon in the toolbar (right aligned perhaps).. saves 1 click and hovering :)

history

**Comment by ro0NL** [comment]
@jameshalsall sorry i forgot about this being a PR, thought it was an issue only. Anyway we have 2 versions to choose from now :)

**Comment by javiereguiluz** [comment]
@jameshalsall thanks for proposing this feature. Sadly I need to close it as "won't merge" because of the same reasons that we discussed in #20128, which proposed the exact same feature with a slightly different implementation. Thanks anyway for your work!

**Pull request closed without merging**
