### PR TITLE
[Intl] fixed php7 compatibility

### PR DESCRIPTION
**Pull request by ondrejfuhrer**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22735 
| License       | MIT

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
👍  should be on 2.7 (oldest maintained impacted branch)

**Comment by ondrejfuhrer** [comment]
PR for Symfony 2.7 here https://github.com/symfony/symfony/pull/22748

**Comment by chalasr** [comment]
You could have rebased/retargeted this one, or it would just have been merged on 2.7 instead. 
This can be closed, bug fixes are then applied on all active branches.

**Comment by ondrejfuhrer** [comment]
@chalasr Thanks, I'm actually not sure how I can change the target of the PR, so I chose a way of creating a new PR, easier, faster 😄 But thanks for the input.

**Comment by ondrejfuhrer** [comment]
Closing in favour of #22748

**Comment by chalasr** [comment]
@ondrejfuhrer Here is how you can retarget your PRs https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Pull request closed without merging**
