### PR TITLE
[Finder] Fix gitignore regex build with "**"

### LINKED ISSUE #41223: Symfony/finder no longer handles patterns like **/vendor/**
**Symfony version(s) affected**: 5.2.8

**Description**
The gitignore pattern parsing no longer handles patterns like `**/vendor/**`, which are respected by `.gitignore` and have also been working perfectly fine with the `symfony/finder` component up until now.

**Possible Solution**
Revert and rethink the "fix" that rewrote the gitignore parsing in `symfony/finder` ([this commit](https://github.com/symfony/finder/commit/67b77716f517e3f864759232e1201e7aa2ab0e82)).

**Additional context**
We're using this component via PHP CS Fixer.

### PR DESCRIPTION
**Pull request by mvorisek**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41223
| License       | MIT
| Doc PR        | no

covered with tests, also faster, we do not have to explode the rule at all :)

ping @lindelius @OskarStark

### CODE REVIEW

**Comment by derrabus** [comment]
Thank your for your PR. Two questions:
* Did you target the 5.x branch on purpose? The PR discription says you wanted to target 4.4.
* Can we find a PR title that people would want to read in a ChangeLog? 🙂

**Comment by mvorisek** [comment]
@derrabus base changed, it should be 4.4, title also updated

**Review by OskarStark — APPROVED** [review]

**Comment by lindelius** [comment]
I can confirm that this PR fixes the issue for us, at least. Thanks!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mvorisek.

**Pull request merged**
