### PR TITLE
fix code style

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
Sorry, I realized too late that #39709 wasn't complete. Let's wait here until all the jobs pass.

**Comment by xabbuh** [comment]
This is ready now.

**Comment by wouterj** [comment]
Nice, that's just in time before this draft would be auto closed :smile:

**Review by wouterj — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
