### PR TITLE
Try PHP7 mode on HHVM

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | let's see
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@mofarrell looks like that's not enough, any other idea? Could you give it a try on your side?

**Comment by nicolas-grekas** [comment]
Related to https://github.com/facebook/hhvm/issues/7198

**Comment by photodude** [comment]
@nicolas-grekas you are correct in identifying facebook/hhvm#7198 as the source of the test failure on travis. Unfortunately, until they fix it (or someone contributes a fix) testing HHVM in php-7 mode with an environment that requires composer is currently impossible.

**Comment by photodude** [comment]
I should mention that you could use php 7 with composer locally then run unit tests locally with hhvm. (I'm not sure the details or possibility of running hhvm and php side by side)

**Comment by fabpot** [comment]
Decision has been made now, we are dropping HHVM.

**Pull request closed without merging**
