### PR TITLE
[Translation] DataCollectorTranslator clarifications

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by aitboudad** [comment]
@xabbuh can you do the same for `LoggingTranslator`

**Comment by xabbuh** [comment]
@aitboudad The constructor argument in the `LoggingTranslator` is not type-hinted. So, there's not much to simplify/clarify and I think adding the type hint is not covered by the BC promise. What do you think about this?

**Comment by aitboudad** [comment]
@xabbuh ok let's do it and I think it should be in `2.6`

**Comment by xabbuh** [comment]
@aitboudad see #14356

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
