### PR TITLE
Make sure the UriSigner can be autowired

### PR DESCRIPTION
**Pull request by Toflar**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

I wasn't able to find the correct spot where this is tested. Is it even tested and if so, can you point me as to where to add tests for that? Thanks 😄

### CODE REVIEW

**Review by aschempp — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
We don't have tests for these :)
PR should target master, that's a new feature.

**Comment by Toflar** [comment]
Damn, I was sure it's going to be 3.4 😆 Okay, let me fix that real quick.

**Comment by leofeyer** [comment]
Is this really a new feature? We will not be able to autowire the URI signer in Symfony 4.4 then, will we?

**Comment by Toflar** [comment]
Rebased, target branch fixed, description updated.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Toflar.

**Comment by xabbuh** [comment]
@leofeyer You can still add the alias yourself if you would like to autowire the `UriSigner`, but do not want to wait for Symfony 5.1.

**Pull request merged**
