### PR TITLE
[Security] Move AbstractListener abstract methods to the new FirewallListenerInterface

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | -
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

We added a FirewallListenerInterface in 5.2, let's make it complete to allow for cleaner firewall listener implementations.

### CODE REVIEW

**Comment by wouterj** [comment]
Hmm, I'm not very sure about these changes. But the listener logic is quite complex, so I might completely miss something. What I see:

* The only requirement for firewall listeners is to be callable: https://github.com/symfony/symfony/blob/93d0276d8c003ebbfbb173aa557efc1b826b521d/src/Symfony/Component/Security/Http/Firewall.php#L110-L119
* Only the `AbstractListener` implements this callable functionality using `supports()`/`authenticate()`: https://github.com/symfony/symfony/blob/93d0276d8c003ebbfbb173aa557efc1b826b521d/src/Symfony/Component/Security/Http/Firewall/AbstractListener.php#L24-L29

So, it should be possible to have a class with just an `__invoke()` and `getPriority()` method, right? `AbstractListener` is only relevant when you want your listener to support laziness.

**Comment by chalasr** [comment]
> AbstractListener is only relevant when you want your listener to support laziness.

Actually `supports()` is also relevant for listeners that don't need laziness (yet), as they can opt-in using the special `null` return type for this method.

At the time lazy firewalls were introduced, @nicolas-grekas and I talked about deprecating not extending `AbstractListener` at some point, so that we have a consistent API for firewall listeners (see https://github.com/orgs/symfony/projects/1#card-30499343). 
I'm still a bit annoyed by the fact we need to rely on inheritance instead of a clear contract if we do so.

Meanwhile we are reintroducing an interface which, right now, only covers the priority feature.
This PR takes it as an opportunity to not force extending a base class, making the concept more structured and more flexible. That's worth the hassle to me.

About adding `__invoke()` to the contract, I'm mitigated:  should we just accept `callable|FirewallListenerinterface` for firewall listeners? 
The interface allows you to opt-in into more complex features like priority, laziness and the ability to separate concerns between the guard clause and the actual authentication logic.

Does this make sense?

**Review by nicolas-grekas — APPROVED** [review]
big :+1: on my side
this change *enables* lazy firewalls (but is not ad hoc for them) because it enables a better design, with a better split of the steps of a firewall

**Review by wouterj — APPROVED** [review]
Ah sorry, I originally was looking at this PR as "purely simplifying" instead of moving to more consistency.

If I understand correctly, the contract already is `callable|FirewallListenerInterface` (it needs to be, for BC reasons IIRC). In that case :+1: and we might indeed want to deprecate `callable` in Symfony 5.3 (I don't think it's possible to introduce new deprecations after feature freeze?)

**Comment by nicolas-grekas** [comment]
Thank you @chalasr.

**Pull request merged**
