### PR TITLE
[Console] Helper\TableHelper->addRow optimization

### PR DESCRIPTION
**Pull request by boekkooi**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13322 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by pierrre** [comment]
Why
```php
end($this->rows);
$rowKey = key($this->rows);
reset($this->rows);
```
instead of
```php
$rowKey = count($this->rows) - 1;
```
?

**Comment by boekkooi** [comment]
@pierrre because of the way TableHelper->setRow is implemented.

**Comment by pierrre** [comment]
What are the expected values of `$column` in `setRow()`?
Integer?
An integer lower than `count($this->rows)`?
A string?

**Comment by boekkooi** [comment]
@pierrre setRow allows for that. So to avoid BC breaks it's better not to use `count` and use `end`.

**Comment by pierrre** [comment]
OK I understand.
Thank you.

**Comment by Tobion** [comment]
`TableHelper` is deprecated. It would be more useful to make this PR against `Table` class.

**Comment by boekkooi** [comment]
@Tobion I opened another PR for Table (#13355)

**Comment by Tobion** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @boekkooi.

**Pull request merged**
