### PR TITLE
[2.8] [Form] Add feature choice_label_attr to ChoiceType

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14404 |
| License | MIT |
| Doc PR | ? |
- extend new choice_attr option to labels for radio buttons and
  checkboxes when choice field type is expanded.
- accepts same arguments as choice_attr : string, array, callable and
  null by default

### CODE REVIEW

**Comment by xabbuh** [comment]
Looks like some tests are failing.

Status: Needs Work

**Comment by HeahDude** [comment]
@xabbuh OK tests should be fixed with last commit

**Comment by xabbuh** [comment]
@HeahDude Looks like you need to do some more rebasing (the diff is far too big).

**Comment by stof** [comment]
You are reverting lots of changes done in Symfony 2.8 here. Please fix your PR as it cannot be merged as is (it cannot even be reviewed)

**Comment by HeahDude** [comment]
@xabbuh @stof , sorry my first PR and and it took me some time to understand how to cleanly rebase. Hope it's fine now.

**Comment by jakzal** [comment]
@HeahDude it's still broken. Perhaps it'll be easier if you create a new branch and commit your stuff again.

**Comment by HeahDude** [comment]
Closed. See #15887

**Pull request closed without merging**
