### PR TITLE
[HttpKernel] fix Kernel name when stored in a directory starting with a number

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20489
| License       | MIT
| Doc PR        | -

replaces #20750

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
:+1:

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Review by stof — APPROVED** [review]
👍

**Review by xabbuh — APPROVED** [review]
:+1:

**Comment by lyrixx** [comment]
replace also https://github.com/symfony/symfony/pull/13412#r23002580

anyway :+1:

**Pull request merged**
