### PR TITLE
HTTP Foundation: provide metadata for PhpStorm

### PR DESCRIPTION
**Pull request by Chi-teck**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      |  no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

This metadata can improve developer experience for PhpStorm users by providing extended autocomplete.

phpstorm-meta-example

### CODE REVIEW

**Comment by derrabus** [comment]
I wonder if this is a feature for the PhpStorm Symfony plugin instead. cc @Haehnchen

**Comment by derrabus** [comment]
Another thing we have to keep in mind is that the HTTP method is not limited to those constants. Theoretically, the protocol allows me to extend it by inventing as many methods as I want.

**Comment by Chi-teck** [comment]
> Theoretically, the protocol allows me to extend it by inventing as many methods as I want.

Same applies to MIME types and headers. The patch adds only most common MIME types and headers. This metadata is just for auto-completion. It'll not stop a user from entering arbitrary values.

**Comment by wouterj** [comment]
I'm -1 on including this in core. We always only include generic PHPdocs in core (i.e. PHPdocs understood by at least PHPstan, Psalm and PHPStorm) and refer to the tool-specific plugin for anything that is not generic.

**Comment by welcoMattic** [comment]
I'm -1 on this too for the same reason about staying generic. 
But I agree wuth @derrabus about adding this in PHPStorm Symfony plugin.

**Comment by Haehnchen** [comment]
There is "an external package" for this, which is included by the Symfony Plugin via submodule: example: https://github.com/King2500/symfony-phpstorm-meta/blob/master/Symfony/Component/HttpClient/.phpstorm.meta.php#L171

So every contribution there will be available. Maybe a contribution there would be easier. packages are also available via composer

**Comment by wouterj** [comment]
Thanks for the reference @Haehnchen. I think that concludes this discussion.

Nonetheless, thanks for proposing this @Chi-teck. I suggest you compare your proposal here with what is already available in the repository linked above and contribute the missing bits to that repository instead.

**Comment by Chi-teck** [comment]
@Haehnchen Thank you for pointing out that package. Seems it's the right place to contribute.

> which is included by the Symfony Plugin via submodule:

Why doesn't it enable auto-completion then? I have Symfony plugin enabled almost on every project but never seen auto completion provided by that package.
The auto-completion only appears after I install the `thomas-schulz/symfony-meta` package manually.

**Comment by Haehnchen** [comment]
@Chi-teck indeed, i missed the phpstorm api changes somewhere in the latest versions. thanks for hint; to be fixed with next release.

**Pull request closed without merging**
