### PR TITLE
[4.0][BC Break] Removed BC layers for ControllerResolver::getArguments()

### PR DESCRIPTION
**Pull request by linaori**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ~
| License       | MIT
| Doc PR        | ~

Removes the Backwards Compatibility layer for the `ControllerResolver` that depends on the `ArgumentValueResolver`. ~~There's still 1 bit left in the `HttpKernel`, but I don't quite know how this is solved in the best way:~~

```php
    public function __construct(EventDispatcherInterface $dispatcher, ControllerResolverInterface $resolver, RequestStack $requestStack = null, ArgumentResolverInterface $argumentResolver = null)
    {
        $this->dispatcher = $dispatcher;
        $this->resolver = $resolver;
        $this->requestStack = $requestStack ?: new RequestStack();
        $this->argumentResolver = $argumentResolver;

        if (null === $this->argumentResolver) {
            @trigger_error(sprintf('As of 3.1 an %s is used to resolve arguments. In 4.0 the $argumentResolver becomes the %s if no other is provided instead of using the $resolver argument.', ArgumentResolverInterface::class, ArgumentResolver::class), E_USER_DEPRECATED);
            // fallback in case of deprecations
            $this->argumentResolver = $resolver;
        }
    }
```

~~The 4th argument is now mandatory, but I can't make it mandatory without switching it with the request stack.~~
 - ~~I can make both mandatory~~
 - ~~I can make it `?RequestStack`~~
 - ~~I can switch the arguments~~

~~Each of those area a BC break but for the request stack or the switch, there is no BC layer yet (could be done in 3.4).~~

### CODE REVIEW

**Comment by stof** [comment]
The argument is not meant to become mandatory, but to instantiate an `ArgumentResolver` if none is provided, according to the deprecation message

**Comment by iltar** [comment]
@stof you're right.

**Comment by iltar** [comment]
Minor addition, @nicolas-grekas has added the service resolver, but this one isn't added to the default set.

**Comment by stof** [comment]
@iltar that's expected, as this ServiceResolver requires some wiring, it is not standalone. So using it requires configuring the resolver externally and passing it to the kernel (which is what FrameworkBundle does for instance)

**Comment by iltar** [comment]
@stof fair enough, I see that the dependency is optional as well. I got confused because it's between the other resolvers here: https://github.com/symfony/symfony/tree/master/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver

**Comment by nicolas-grekas** [comment]
fabbot failure looks legit

**Comment by iltar** [comment]
@nicolas-grekas indeed, should be fixed now!

**Comment by nicolas-grekas** [comment]
Thank you @iltar.

**Pull request closed without merging**
