### PR TITLE
[DependencyInjection] Allow enumerated keys as result of defaultIndexMethod

### LINKED ISSUE #44556: Allow TaggedLocator autowiring via enums
### Description

```php
#[TaggedLocator(tag: 'my_tag', defaultIndexMethod: 'myStaticMethod')]
```

works with strings and integers, but not with ``BackedEnum``. A simple change to 

```php
trait PriorityTaggedServiceTrait
{
    public static function getDefault()
    {

        // ....
        if ($default instanceof BackedEnum) {    //  <---
            $default = $default->value;
        }

        if (\is_int($default)) {
            $default = (string) $default;
        }
        // ....
        
    }
}
```

could improve static analysis and autocomplete.

### Example

Tag:

```php
#[AutoconfigureTag(name: 'my_tag')]
interface PartnerInterface
{
    public static function getPartnerId(): MyEnum;   // <- enum instead of string
}
```

Service that gets them works as before:

```php
class PartnerProcessor
{
    public function __construct(
        #[TaggedLocator(tag: 'my_tag', defaultIndexMethod: 'getPartnerId')]
        private ServiceLocator $partners,
    )
    {
    }

    // autocomplete and static analysis is improved here
    public function doSomethingWithPartner(MyEnum $enum): void
    {
        $partner = $this->partners->get($enum->value);
    }
}
```

### PR DESCRIPTION
**Pull request by zmitic**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | Fix #44556
| License       | MIT
| Doc PR        | 

Allows using PHP8.1 enums as a result of getDefaultIndexMethod, as described in #44556.

### CODE REVIEW

**Comment by fractalzombie** [comment]
Good Idea, will wait for it, will be good to see for `defaultPriorityMethod` the same thing, plese add test for `defaultPriorityMethod `.

**Comment by fractalzombie** [comment]
Up this PR!

**Comment by zmitic** [comment]
@fractalzombie 
Hey thanks for update, I totally missed the first comment. Sorry, on it!

**Comment by zmitic** [comment]
@fractalzombie While bots perform checks, can you take a look at PR and give me some hints?

**Comment by fractalzombie** [comment]
> @fractalzombie While bots perform checks, can you take a look at PR and give me some hints? 

Yep, of course

**Comment by fractalzombie** [comment]
> @fractalzombie While bots perform checks, can you take a look at PR and give me some hints? 

You need to fix tests for pho 8.1 with annotation about, that test only for 8.1. I will give you example in 1-2 hours, when will be near laptop.

**Comment by fractalzombie** [comment]
> @fractalzombie While bots perform checks, can you take a look at PR and give me some hints?

You can do it like here https://github.com/symfony/symfony/pull/43386/commits/8c4651a0abfa7dc39109e2f910423d34b078bf13#diff-4440c0daf07aa75a97e4cf9f147391d566ebaa04fe772bdf1c896f92f6292f38R364

**Comment by zmitic** [comment]
@fractalzombie 

Thanks for review. But this is 8.1 specific, won't even work on 8.0. So annotation[ like this](https://github.com/symfony/symfony/pull/44664/files#diff-4440c0daf07aa75a97e4cf9f147391d566ebaa04fe772bdf1c896f92f6292f38R544) should be correct, right?

**Comment by fractalzombie** [comment]
> @fractalzombie 
> 
> 
> 
> Thanks for review. But this is 8.1 specific, won't even work on 8.0. So annotation[ like this](https://github.com/symfony/symfony/pull/44664/files#diff-4440c0daf07aa75a97e4cf9f147391d566ebaa04fe772bdf1c896f92f6292f38R544) should be correct, right?

Yep, this annotation will execute this test on needed php version.

**Comment by zmitic** [comment]
@fractalzombie 

>Yep, this annotation will execute this test on needed php version.

So I did put [correct 8.1 annotation](https://github.com/symfony/symfony/pull/44664/files#diff-4440c0daf07aa75a97e4cf9f147391d566ebaa04fe772bdf1c896f92f6292f38R544-R606), right? These 2 new tests pass and bots don't report problems with them.

Sorry if noobish question.

**Comment by fractalzombie** [comment]
> @fractalzombie 
> 
> 
> 
> >Yep, this annotation will execute this test on needed php version.
> 
> 
> 
> So I did put [correct 8.1 annotation](https://github.com/symfony/symfony/pull/44664/files#diff-4440c0daf07aa75a97e4cf9f147391d566ebaa04fe772bdf1c896f92f6292f38R544-R606), right? These 2 new tests pass and bots don't report problems with them.
> 
> 
> 
> Sorry if noobish question.

I think yes, in my case it works.

**Comment by nicolas-grekas** [comment]
Re-reading this PR, I think I agree with @stof's comment:

> this proposal is using enums as a way to store backing strings that are used to actually index the service locator. This seems like an abuse of enums

Closing therefor. We can reopen but we need more experience with enums before I think. Right now, I'm not convinced they provide much in some use cases that have been proposed to the codebase.

Thanks for the proposal.

**Pull request closed without merging**
