### PR TITLE
[Validator] Add a missing Polish translation

### PR DESCRIPTION
**Pull request by jakzal**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jakzal.

**Comment by jakzal** [comment]
Ah, i sent it to master as the translation doesn't exist in previous branches.

**Comment by fabpot** [comment]
We are always merging into the lower branch (even if the translation does not exist there).

**Comment by jakzal** [comment]
What about the `en` version? Currently it's missing at least one entry (that's why I sent my PR against master).

**Comment by fabpot** [comment]
The files are indeed not always synced (especially for the en version as it is part of the original PR which is always on master). From time to time, we try to re-sync the translations file though.

**Pull request merged**
