### PR TITLE
DX: Update PHP CS Fixer config file

### PR DESCRIPTION
**Pull request by keradus**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | n/a
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

For a good start, updated config for php cs fixer v2.
I would guess that fabbot needs to be updated ;)

### CODE REVIEW

**Comment by SpacePossum** [comment]
:+1:  , but is fabbot.io already updated to 2.0 line?

**Comment by keradus** [comment]
Thats why
> I would guess that fabbot needs to be updated ;)

**Comment by fabpot** [comment]
Upgrading fabbot is a bit challenging as we need to upgrade all repos before migrating (so, we need some coordination). We will try to do that ASAP.

**Comment by keradus** [comment]
what about detecting version of PHP CS Fixer used in configuration (eg via namespace), so fabbot could support both for a while ?

**Comment by fabpot** [comment]
Thank you @keradus.

**Pull request merged**
