### PR TITLE
 add return type hints to EntityFactory

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

see https://github.com/EasyCorp/EasyAdminBundle/actions/runs/6603120076/job/17935909075

### CODE REVIEW

**Comment by wouterj** [comment]
An alternative would be to add the native return type and document the BC break. We've done that for multiple other method implementations as well: #50890 Given `EntityFactory` is a DI factory class, the likelihood of anyone being hit by this BC break seems rather slim.

**Comment by nicolas-grekas** [comment]
I like @wouterj's proposal!

**Comment by derrabus** [comment]
Yes, let's do what @wouterj proposes. If someone complains about the BC break, we could still make the return type conditional using a trait, but I doubt that someone extends this class.

While we're at it, should we make `EntityFactory` final in 7.0? There's really no point in extending it: It only exposes the public methods from `UserProviderFactoryInterface`. If someone wants to extend the functionality of that class, a decorator would be the better way to do that.

**Comment by xabbuh** [comment]
I have added the return types and also marked the class as final.

**Review by nicolas-grekas — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by smnandre** [comment]
Is this the same problem there ? 

> PHP Fatal error:  Declaration of Symfony\WebpackEncoreBundle\CacheWarmer\EntrypointCacheWarmer::doWarmUp($cacheDir, Symfony\Component\Cache\Adapter\ArrayAdapter $arrayAdapter): bool must be compatible with Symfony\Bundle\FrameworkBundle\CacheWarmer\AbstractPhpFileCacheWarmer::doWarmUp(string $cacheDir, Symfony\Component\Cache\Adapter\ArrayAdapter $arrayAdapter, ?string $buildDir = null): bool in /home/runner/work/ux/ux/src/Turbo/vendor/symfony/webpack-encore-bundle/src/CacheWarmer/EntrypointCacheWarmer.php on line 27

https://github.com/symfony/ux/issues/1223

If so, could you explain what are the steps to fix ? (i must admit i'm not yet fluent in "multi-php multi-version multi-bundle" troubles 😅

**Comment by wouterj** [comment]
@smnandre that's a different issue: the first parameter `$cacheDir` must get the `string` type in the WebpackEncoreBundle. Adding types to parameters can be done safely (it's not a BC break), as a child can have a less specific parameter type than its parent).

**Comment by smnandre** [comment]
Thank you @wouterj !

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by derrabus** [comment]
> the first parameter `$cacheDir` must get the `string` type in the WebpackEncoreBundle

Actually, the issue is the new and optional third parameter. But, as @wouterj said, this is a different and unrelated problem. If you don't know how to solve it, please open a new issue or a dicussion.

**Pull request merged**
