### PR TITLE
[Serializer] Fix low-deps tests

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

The tests break because of a missing dependency to `phpstan/phpdoc-parser` in low-deps. I'd suggest to skip them if the dependency is not installed?

### CODE REVIEW

**Comment by wouterj** [comment]
Let's instead add `phpstan/phpdoc-parser` as a dev dependency to Serializer (similar to how it also depends on `phpdocumentor/reflection-docblock`)?

Currently, we only have test coverage by chance as the dep is required by newer versions of `phpdocumentor/reflection-docblock`. That seems fragile to me :)

**Comment by alexandre-daubois** [comment]
Suits me fine! It's better this way. Let me find the good constraint to use 🙂

**Comment by alexandre-daubois** [comment]
I think we should use the same constraint as there is in other packages, namely `^1.0`.

It seems one of the tests is failing even with the new dependency. I'm investigating a bit more on it.

**Comment by alexandre-daubois** [comment]
It seems that the test is failing if `symfony/property-info` is < 7.1. What about bumping the require-dev dependency as I did in the last update of this PR?

**Comment by alexandre-daubois** [comment]
It seems that the test is failing if `symfony/property-info` is < 7.1 and `symfony/type-info` is < 7.2. What about bumping the require-dev dependencies then? It seems they fixed things in the latest versions.

**Comment by xabbuh** [comment]
@alexandre-daubois Do we need to target the `7.1` branch (see https://github.com/symfony/symfony/actions/runs/10947480547/job/30396307514#step:8:9378)?

**Comment by alexandre-daubois** [comment]
Yes you're right! However, there's something that's been updated in `symfony/type-info` 7.2 that fixes this (see the result on 7.1: https://github.com/alexandre-daubois/symfony/actions/runs/10954501971/job/30416559832#step:8:10297).

Maybe @mtarld can see something "obvious" from his point of view about it?

**Comment by alexandre-daubois** [comment]
Closed in favor of #58337

**Pull request closed without merging**
