### PR TITLE
[ExpressionLanguage] Provide the expression in syntax errors

### PR DESCRIPTION
**Pull request by stof**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #19445
| License       | MIT
| Doc PR        | n/a

This finishes the PR #19449.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
fabbot failure - but shouldn't this be done on master instead? a new public method looks like a new feature to me - the DX "fix" looks like DX "improvement" to me.

**Comment by stof** [comment]
well, the new method is quite internal (I should tag it as `@internal` btw)

**Comment by stof** [comment]
Regarding the target, the original PR was on 2.7. But deciding between 2.7 and master can be discussed. The current exceptions when using a wrong expression in a DI configuration are totally impossible to debug (the error message does not contain the expression, and the stack trace does not contain the config file containing the expression as the expression is parsed only later when dumping the compiled container). So I would still be in favor of adding it in 2.7

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Review by dunglas — APPROVED** [review]
👍

**Comment by fabpot** [comment]
Thank you @stof.

**Pull request merged**
