### PR TITLE
[Security] Improve AbstractVoter tests

### PR DESCRIPTION
**Pull request by wouterj**
Applying the improved tests from https://github.com/symfony/symfony/pull/15932 into the oldest possible branch.

Merge conflicts from 2.7 into 2.8 caused by this PR do not need to be done carefully, I'll create a new PR for 2.8 updating the tests as soon as these changes are merged up.

| Q | A |
| --- | --- |
| Fixed tickets | - |
| License | MIT |

### CODE REVIEW

**Comment by weaverryan** [comment]
:+1: all the previous test cases are included.

**Comment by xabbuh** [comment]
:+1: Will this help to fix the failing Security related tests on the `2.8` branch?

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @WouterJ.

**Comment by fabpot** [comment]
@WouterJ Merged and not merged too carefully on 2.8 (so tests do not pass). Can you submit a PR ASAP for the 2.8 branch? Thank you very much for your help.

**Comment by WouterJ** [comment]
Thanks, see https://github.com/symfony/symfony/pull/15961

**Pull request merged**
