### PR TITLE
[Security\Http] Restore laziness of listener iterator

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no (never released)
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Alternative to #28223

Restores laziness that I broke in merge commit https://github.com/symfony/symfony/commit/2dedacbc046ebfce2d9dc40257f8ce94b2562244#diff-31ca8a8ce837591218082b00363149fc

### CODE REVIEW

**Comment by chalasr** [comment]
Thank you @nicolas-grekas.

**Comment by stof** [comment]
Another option would be to provide the access listener separately (as done for the logout listener)

**Comment by nicolas-grekas** [comment]
I've been wondering the same. Would there be any bonus or drawback?

**Comment by stof** [comment]
@nicolas-grekas your code still requires instantiating all listeners, as it still iterates over them twice.

**Comment by stof** [comment]
hmm, no, I'm wrong. The generator yields the listeners as they go (except the AccessListener), it does not build the list first.

**Comment by nicolas-grekas** [comment]
How that? To me the generator keeps laziness. Can you elaborate?

**Pull request merged**
