### PR TITLE
WIP [Validator] Added a BitcoinAddressValidator constraint

### PR DESCRIPTION
**Pull request by gmponos**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | yes/no
| Deprecations? | yes/no 
| Tests pass?   | yes/no
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by gmponos** [comment]
Would you be interested accepting this?

**Comment by fabpot** [comment]
I'm not sure it makes sense to have such a validator in core (at least not now).

**Comment by gmponos** [comment]
> I'm not sure it makes sense to have such a validator in core (at least not now).

What is there to loose? I can understand that if something like that is merged symfony is responsible of maintaining it. That's a point there but because I saw IBAN validator which most probably also needs some maintenance I thought that Validators are not restricted to some basic stuff (like isEmpty or isFalse etc)

**Comment by Simperfit** [comment]
I guess it could be useful, if not in core, in a bundle then.

**Comment by javiereguiluz** [comment]
I'm 👎 because I also think this proposal comes too early. I'd recommend to wait a bit and also to transform this BitcoinAddressValidator into CryptocurrencyValidator to validate (if possible) the formats of the most popular ones (like we do with Banks + Countries in IbanValidator and Credit Cards in CardSchemeValidator).

**Comment by fabpot** [comment]
I agree with @javiereguiluz. Closing for now. Can be part of another package anyway in the meantime.

**Pull request closed without merging**
