### PR TITLE
[Dotenv] Check required dotenvs

### PR DESCRIPTION
**Pull request by pizzaminded**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony#12030

# TODO:
- [x] update documentation
- [x] fix tests

Added new method, which checks there are all environment variables defined in project.
This one may be used e.g. to tell other developer to provide all things needed to run app without any missing-envs-caused malfunctions. 

It is checking only _ENV superglobal as there may be some vars defined in third-party software (like `SetEnv` in Apache)

### CODE REVIEW

**Comment by xabbuh** [comment]
To me it doesn't look like this change really belongs to the Dotenv component. The component is meant to read environment variables from `.env` files. The code added here is about verifying the presence of some environment variables which is not tied to reading `.env` files. Those environment variables could be populated by any other mechanism as well without the Dotenv component being involved.

**Comment by pizzaminded** [comment]
@xabbuh similar features are used e.g in Ruby's gem (https://github.com/bkeepers/dotenv#required-keys) and some PHP libs:
- https://github.com/vlucas/phpdotenv#requiring-variables-to-be-set
- https://github.com/josegonzalez/php-dotenv#require-environment-variables

IMHO Dotenv could be one of the best places for this feature as it is used at the beginning of script, where it is possible to prevent further execution of scripts with invalid config.

**Comment by nicolas-grekas** [comment]
Where do you get the list of required vars from in your use case?
Can't we derivate it from the .env file?
That'd fit well with the way we see it now: this file should list all the env vars that are needed by the app, even with an empty value.

**Comment by pizzaminded** [comment]
@nicolas-grekas I got some environment variables defined in Apache's vhosts config to verify that request came from internal of external networks. For development purposes adding it to ``.env`` would be a good idea, but in testing (i mean UAT, not unit tests etc.)  or production this might be tricky. 

This also can act as an "reminder" for new developers that they need to define missing variables in ``.env`` file.

**Comment by nicolas-grekas** [comment]
> This also can act as an "reminder" for new developers that they need to define missing variables in .env file.

In any case, the list of required vars needs to be put somewhere. The most logical place is the `.env` file to me.

**Comment by nicolas-grekas** [comment]
I'm closing to snapshot the state of the PR and related discussion.
Feel free to submit another PR with the proposed alternative.

**Pull request closed without merging**
