### PR TITLE
[DependencyInjection] top-level anonymous services must be public

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18703 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:, a test case would be great

**Comment by xabbuh** [comment]
The file loader Test case I had to change covers this.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
@nicolas-grekas By the way, in the same test we ensure that anonymous services used in definition arguments are still private.

**Comment by nicolas-grekas** [comment]
Yep, I checked that also before merging :)

**Pull request merged**
