### PR TITLE
[Filesystem] Added a LockHandler

### PR DESCRIPTION
**Pull request by lyrixx**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #9357 , #3586 |
| License | MIT |
| Doc PR | https://github.com/symfony/symfony-docs/pull/3956/files |

Code sample:

``` php
    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $lockHelper = new LockHandler('/tmp/acme/hello.lock');
        if (!$lockHelper->lock()) {
            $output->writeln('The command is already running in another process.');

            return 0;
        }

        $output->writeln(sprintf('Hello <comment>%s</comment>!', $input->getArgument('who')));

        for (;;) {
        }

        $output->writeln(sprintf('bye <comment>%s</comment>!', $input->getArgument('who')));

        $lockHelper->unlock();
    }
```

process-lock

### CODE REVIEW

**Comment by temple** [comment]
Could you please @lyrixx provide an interface for the `LockHandler` class?
It would be useful to enhance this class by using wrappers.. but this means having an interface to implement.

**Comment by temple** [comment]
Are you referring this one, @lyrixx ?
http://symfony.com/blog/new-in-symfony-3-3-lock-component

**Comment by lyrixx** [comment]
yes.

**Comment by temple** [comment]
Thank you very much!

**Pull request merged**
