### PR TITLE
Reduce Cognitive load

### PR DESCRIPTION
**Pull request by NikoGrano**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes  
| Fixed tickets | none
| License       | MIT
| Doc PR        | none

- Reduced cognitive load.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
But that's not the same, you forgot to remove the `null !==` part.
Can you target 4.2 instead?

**Comment by Niko9911** [comment]
yes, I'm aware of this. Sorry, it was late night. I will be going trough this component and reviewing it from point of best practices. Will be posting new PR in a day.

**Comment by xabbuh** [comment]
@Niko9911 IMO there is no need to close here. Just change it to something like this:

```php
$this->mutatorPrefixes = $mutatorPrefixes ?? self::$defaultMutatorPrefixes;
$this->accessorPrefixes = $accessorPrefixes ?? self::$defaultAccessorPrefixes;
$this->arrayMutatorPrefixes = $arrayMutatorPrefixes ?? self::$defaultArrayMutatorPrefixes;
```

**Comment by Niko9911** [comment]
I'm aware of rejecting changes to code-style just fixing stuff what is wrong from logical view. Meaning, just like cases like this. I'm not correct guy to judge where is the brackets but and how many spaces is between...

@xabbuh Gimme time to make new PR. I will be tomorrow working on this. Thank you for your understanding.

**Pull request closed without merging**
