### PR TITLE
[Messenger] Make 'headers' key optional for encoded messages

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #30455 
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
4.2?

**Review by nicolas-grekas — APPROVED** [review]
applies to 4.2, would be legit to have it there to me also.

**Comment by yceruto** [comment]
Rebased to `4.2`

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @yceruto.

**Pull request merged**
