### PR TITLE
[Security] Relax return type on VoterInterface

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | https://github.com/symfony/security-acl/pull/97#issuecomment-913774242
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by wouterj — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
You shall also update `.github/expected-missing-return-types.diff`

**Comment by derrabus** [comment]
> You shall also update `.github/expected-missing-return-types.diff`

I see. 🙈

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @derrabus.

**Comment by nicolas-grekas** [comment]
Linking to symfony/symfony#43021 for history.

**Pull request merged**
