### PR TITLE
[WebProfilerBundle] Display environment variables

### PR DESCRIPTION
**Pull request by sanpii**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

With the new dotenv component it’s usefull to have environment variables in the profiler page.

screen shot 2017-04-12 at 21 02 37-fullpage

### CODE REVIEW

**Comment by iltar** [comment]
What if there are passwords in there?

**Comment by javiereguiluz** [comment]
@iltar although your concern is true, we may display passwords and other sensitive information in other panels. That's why it's suicidal to put the profiler in production or forget to remove app_dev.php  (Symfony Flex will help with this of course).

**Comment by iltar** [comment]
@javiereguiluz We use `app_dev.php` to reproduce issues in production and check the debug/profiler information, removing this is not really an option for us unless an alternative is provided. However, this also means that wherever possible, I would like to avoid displaying sensitive data, regardless of environment. Not sure if the env variables is something that you _want_ to see. They are a replacement of the parameters and I never had the need to display those either.

**Comment by sanpii** [comment]
@iltar How could you distinguish sensitive data?

**Comment by javiereguiluz** [comment]
@iltar I meant it's suicidal to put the profiler in production ... without protecting it. You are already protecting it, so there's no issue for showing a few more sensitive data.

@sanpii you can't. There's no solution to this issue :(

**Comment by wouterj** [comment]
I wonder how usefull this is. Profilers should show *request dependent* data, data that changes per request. Env variables are bound to the server, not the request, isn't it?

**Comment by sanpii** [comment]
> I wonder how usefull this is

It’s usefull when you use the environment variables to configure your application.

http://fabien.potencier.org/symfony4-best-practices.html#environment-variables

**Comment by wouterj** [comment]
> It’s usefull when you use the environment variables to configure your application.

Yeah, but it doesn't change per request. If people find it usefull to get this information, I think a `debug:dotenv` or `debug:env` etc. command fits this data better.

**Comment by sanpii** [comment]
> Yeah, but it doesn't change per request.

It’s possible. You can define a variable from bash command.

> If people find it usefull to get this information, I think a debug:dotenv or debug:env etc. command fits this data better.

It’s a good idea, however environment variables may be different between the command line and the web server.

**Comment by fabpot** [comment]
I think @wouterj is right. The web profiler is about "things" that are related to the current request.

**Comment by javiereguiluz** [comment]
@sanpii don't worry if this proposal is rejected. When using the new Dotenv component (as in Symfony Flex, Symfony 4.0, etc.) those env vars already appear in the profiler thanks to this line: https://github.com/symfony/dotenv/blob/master/Dotenv.php#L76

In this example, the `APP_ENV`, `APP_DEBUG`, etc. are variables defined in the `.env` file:

env_vars_profiler

**Comment by fabpot** [comment]
Good catch @javiereguiluz, then we're all good.

**Comment by sanpii** [comment]
@javiereguiluz I didn’t see, thank you!

**Pull request closed without merging**
