### PR TITLE
Fix #36973: Command description consistency

### LINKED ISSUE #36973: Inconsistent verb mood in command options and descriptions
**Symfony version(s) affected**: dev-master

**Description**  
Built-in Symfony options and commands, such as in the Console and Framework Bundle, use inconsistent mood in option and command descriptions.

**How to reproduce**  
Look at the option and command descriptions in [AssetsInstallCommand.php](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php) and [HelpCommand.php](https://github.com/symfony/console/blob/master/Command/HelpCommand.php), just for example.
```
Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
...
  --symlink             Symlinks the assets instead of copying it
...
Available commands:
  help                  Displays help for a command
...
  assets:install        Installs bundles web assets under a public directory
```
Note that some verbs are in the indicative mood ("Symlink**s**") and some are imperative ("Display").

This is not only grammatically inconsistent, but the inconsistency makes it difficult for downstream projects to choose a consistent standard when implementing commands.

**Possible Solution**  
Reword all command options and descriptions to use a consistent mood, ideally the imperative mood (no trailing "s") since that's more concise, matches the commands themselves, and is in line with what I tend to see for other more traditional frameworks and commands (such as Unix man pages), and [random internet people](https://chris.beams.io/posts/git-commit/#imperative) seem to prefer it. But I don't really care as long as it's consistent.

Bonus points for declaring this along with rationale in a Symfony style guide or documentation.

### PR DESCRIPTION
**Pull request by danepowell**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36973
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/15062

This rewords command descriptions and options to use consistent verb mood.

### CODE REVIEW

**Comment by danepowell** [comment]
I don't think the test failures are due to my changes, but let me know if I'm wrong

**Review by derrabus — APPROVED** [review]

**Comment by chalasr** [comment]
~~45 commands in the diff, I guess we probably have very few commands using imperative.
We use the indicative mood for class/method descriptions in doc blocks. Command descriptions are similar to me, I'd prefer imperative.~~

**Comment by derrabus** [comment]
@chalasr Let's keep the discussion on #36973.

**Review by chalasr — APPROVED** [review]
I changed my mind, most other cli tools do the same.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @danepowell.

**Comment by fabpot** [comment]
I've merged up to 5.x and updated commands and options added in 5.2 and 5.x. We should be all set now.

**Comment by chalasr** [comment]
Tests are plain broken from 4.4 to 5.x due to this change. I'm on it...

**Comment by danepowell** [comment]
Thanks everyone for jumping on this! It might seem minor but little things like this really add up to improve Symfony's UX and reputation. 😄

**Pull request merged**
