### PR TITLE
[Notifier] [CS] [5.x] Replace easy occurrences of ?: with ??

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

https://github.com/symfony/symfony/pull/40729 on 5.x

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you @fancyweb. 

I see that a similar PR was approved and merged. Im happy to merge this to, but could you help me understand the benefit of this change?

**Comment by derrabus** [comment]
> but could you help me understand the benefit of this change?

`??` is more precise than `?:`. With `$foo ?: $bar`, we tell PHP, "Check if `$foo` contains some truthy value and if not, fall back to `$bar` instead". With `$foo ?? $bar`, we explicitly check for `$foo === null` and nothing else.

If possible, we should prefer `??` over `?:` – just as we should prefer `===` over `==`. Less edge cases and the intention of the code is made clearer to the reader.

Moreover, one fine day, when we don't have to support PHP < 7.4 anymore, wen can simplify `$foo = $foo ?? $bar` to `$foo ??= $bar`. 🎉

**Review by OskarStark — APPROVED** [review]
Thanks for the explanation 👍🏻

Shouldn't we first tackle 5.2 branch?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @fancyweb.

**Comment by Nyholm** [comment]
Thank you @derrabus for the explanation. 

Well done @fancyweb

**Comment by fancyweb** [comment]
> Shouldn't we first tackle 5.2 branch?

I started on 4.4 and 5.2 before this one.

BTW, I only searched for `?: new` and `?: $this->createMock` but if we look for every ` ?: ` occurrences, many of them can probably be replaced too. It's just that it's going to be way harder to do and especially to review.

**Pull request merged**
