### PR TITLE
revert #30525 due to performance penalty

### PR DESCRIPTION
**Pull request by bendavies**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets |   
| License       | MIT
| Doc PR        | 

This reverts #30525, because it introduced a large performance penalty.

Here is the effect of that PR when I upgrade my Api Platform project from 4.2.9 to 4.3.1:
https://blackfire.io/profiles/compare/28bfbc61-3649-4896-bd03-7201239134cd/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=Symfony%5CComponent%5CVarExporter%5CInternal%5CExporter%3A%3Aexport%403&callname=main()

The reverted PR targeted master. This should go in 4.3?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Master then is 4.3 now so yes, this should target 4.3. But can we have a deeper analysis so that we better understand what's going on? The reverted PR had merits I suppose.

**Comment by dunglas** [comment]
I'm in favor of reverting in the meantime, this change looks to impact badly most API Platform projects.

**Review by dunglas — APPROVED** [review]

**Comment by bendavies** [comment]
From the profile, it seems the reverted PR caused many many cache lookups and writes.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @bendavies.

**Comment by bastnic** [comment]
THANKS!

FYI, a cache warmup with symfony 4.3 : https://blackfire.io/profiles/d20d4c31-f68c-406a-b691-94dba2422d6b/graph. With both this problem and this one https://github.com/symfony/symfony/pull/32188. 

Yep, 16mn cache warmup... 14 for this one and 1.5 for the new PR.

**Comment by deviantintegral** [comment]
From the original issue I filed at https://github.com/symfony/symfony/issues/29977:

> Is optimizing for the "most properties will need to be extracted case" best?
> Are there commonly used cached backends where rewriting the same cache key like this will cause problems?

Do we have any idea if either one of these cases is what's happened? In our case, it's the opposite, and without the original PR we see additional seconds in latency. It'd be great if we could figure out something that handles both cases.

**Pull request merged**
