### PR TITLE
[Workflow] Fix configuration node reference for "initial_marking"

### PR DESCRIPTION
**Pull request by phansys**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Related to       | #30890
| License       | MIT

### CODE REVIEW

**Comment by OskarStark** [comment]
But initial_places was also a thing and should not be removed from the README, shouldn’t it?

Even this line was not introduced in your references PR #30890 🤔

**Comment by OskarStark** [comment]
friendly ping @lyrixx

**Comment by phansys** [comment]
In the last release from 4.2 branch (v4.1.12), the configuration node is called "initial_place":
https://github.com/symfony/symfony/blob/7b0ca3ab5678232f876a95991b66778f4aaa33e3/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L230
In the first release from 4.3 branch (v4.3.0), the configuration node is called "initial_marketing":
https://github.com/symfony/symfony/blob/0bf8d128ef3c492436ab5f1b7c7b130f9e96aad2/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L236

So, answering your question, I think yes:
>Or do you mean to skip 2 iterations which were both introduced in 4.3 go straight to initial_marking?

The related commit is 1af1bf29ef5f1306dfcaf15970df46146a6dbdc4.

**Review by lyrixx — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @phansys.

**Pull request merged**
