### PR TITLE
[Form] Silence a legacy test.

### PR DESCRIPTION
**Pull request by jakzal**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Is it really a legacy test? Or shouldn’t `bind` be renamed to `submit` instead?

**Comment by jakzal** [comment]
Hm... checking :)

**Comment by jakzal** [comment]
Actually, you're right. It was added as a bug fix for `bind()` (#7789), but the actual behavior is in `submit()`.

**Comment by jakzal** [comment]
I'll just add it to my other PR (#13800).

**Pull request closed without merging**
