### PR TITLE
[Console] Catch also TypeErrors in console app

### PR DESCRIPTION
**Pull request by tomasfejfar**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

If console command throw TypeError it falls through this error handling routine.

### CODE REVIEW

**Comment by ro0NL** [comment]
ref #39798

**Comment by derrabus** [comment]
Test failure is related. Also, can you explain what problem you want to solve? If the command execution raises an error, this should already be caught here:

https://github.com/symfony/symfony/blob/ffb0d2d4245f905c85aacf84a003ebdff6f31a4c/src/Symfony/Component/Console/Application.php#L1023-L1031

**Comment by ro0NL** [comment]
@derrabus it's rethrown in L1045 :)

`testErrorIsRethrownIfNotHandledByConsoleErrorEventWithCatchingEnabled` needs investigation indeed, from what i understood in #39798 errors can already be transformed to exceptions (or the error handler sends them back to console rendering), so we have a conditional issue the least.

**Comment by tomasfejfar** [comment]
@derrabus In our app we have overridden `Application::renderException` to use our internal log component that does things like upload the full stacktrace and bluescreen to s3 for debugging and the rest to papertrail. It seemed like the correct place to handle the exceptions from commands. 

This worked fine so far, but we noticed it drops Error from commands and wanted to fix it. 

Does the above explain my the reasoning sufficiently?

**Comment by derrabus** [comment]
> It seemed like the correct place to handle the exceptions from commands.

The correct place would be a listener on the `console.error` event. That listener should also receive `Error` instances.

**Comment by tomasfejfar** [comment]
But that only work within Symfony application, doesn't it? We use symfony/console in isolation...

**Comment by stof** [comment]
@tomasfejfar using the EventDispatcher component with the console does not require using the FrameworkBundle. It only requires installing the symfony/event-dispatcher component in your project and setting an EventDispatcher instance (that contains your listeners) in the Application object. So that can be done in standalone usage too

**Comment by nicolas-grekas** [comment]
It looks like we're not going to have a consensus on this one.
I'm closing as an alternative way has been provided.

**Pull request closed without merging**
