### PR TITLE
[Yaml] fix parsing multi-line mapping values

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #11109 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by fabpot** [comment]
The question is whether we want to support this. Having a string on multiple lines is already supported via '|' for instance, so do we really need another way? Wouldn't it be good to re-read the spec and write a doc that explicitly list what we do support and what we don't want to support?

**Comment by xabbuh** [comment]
I could also live with not fixing this issue. Though in that case I suggest to provide a more meaningful exception message (something like what I suggested in #11911).

**Comment by xabbuh** [comment]
ping @symfony/deciders Any opinion on this?

**Comment by Tobion** [comment]
If that is according to the yaml spec, we should support it as well. We removed support for other stuff like non-quoted strings starting with `%` to increase compatibility. That wouldn't make sense if the full spec is not supported anyway.

**Comment by fabpot** [comment]
We don't want to support the full YAML spec but a subset of it. So, removing things that were not compatible with the YAML spec was needed but this is different from supporting features that are currently not supported.

**Comment by javiereguiluz** [comment]
👍  because this YAML feature is not that "edgy" and because the implementation is reasonably small and simple.

Status: reviewed

**Comment by fabpot** [comment]
ok, let's do it. But that's a new feature then, which should be done on master. @xabbuh I let you merge this on master (there are some conflicts).

**Comment by smarcet** [comment]
is there is any update of this fix ?
regards

**Pull request closed without merging**
