### PR TITLE
[Process] Add getter for process pipes to be able to work with them

### PR DESCRIPTION
**Pull request by momocode-de**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no (Just a new getter function)
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

This is my situation:

I have the following bash script and I want to execute it with the `Process` component within a PHP script:

```bash
#!/usr/bin/env bash

echo "Insert something:"
read INPUT

echo "-${INPUT}-"
```

In order for the PHP script to stop for the "read" and ask for the user input, I figured out that you have to pass PHP's STDIN to the Process like this:

```php
$process = new Process(['/path/to/my/script.sh'], null, [], \STDIN, null);

$process->start();

foreach ($process as $type => $buffer) {
    echo $buffer;
}

$process->wait();
```

With this the PHP script pauses when the bash script asks for user input. After submitting the input to the command line, the input is written to PHP's STDIN and because I passed \STDIN to the Process, my input is redirected to the bash script and then the bash script prints my input and finishes.

My problem was now to automatically write something to the "read" of the bash script without actually asking the user for the input.

The first important thing is to know when the bash script requires user input. My idea was to look for the text that was printed before the read and once it arrives, I can write something to the input. Something like this:

```php
$process = new Process(['/path/to/my/script.sh'], null, [], \STDIN, null);

$process->start();

foreach ($process as $type => $buffer) {
    $separator = "\r\n";
    $line = strtok($buffer, $separator);
    while ($line !== false) {
        if (mb_strpos($line, 'Insert something:') === 0) {
            // No echo here
            // Write a pre-defined value to the script's input so that the bash script continues and prints this value
        } else {
            echo $buffer;
        }
        $line = strtok($separator);
    }
}

$process->wait();
```

My first approach was to write something to \STDIN like this:

```php
fwrite(\STDIN, 'My pre-defined value' . PHP_EOL);
```

With this the input is printed to the command line, but it is not redirected to the bash script. The bash script does not receive the input and does not continue the execution. Only when I write something to the command line and hit enter, the script continues. But then my own input is printed, not the input the PHP script has written to \STDIN.

So this is where my PR comes in. I have added a getter function for the "processPipes" variable and I can use it like this now:

```php
fwrite($process->getProcessPipes()->pipes[0], 'My pre-defined value' . PHP_EOL);
```

With this my pre-defined value is submitted to the bash script and it directly continues and prints this value.

So this is my final PHP code then:

```php
$process = new Process(['/path/to/my/script.sh'], null, [], \STDIN, null);

$process->start();

foreach ($process as $type => $buffer) {
    $separator = "\r\n";
    $line = strtok($buffer, $separator);
    while ($line !== false) {
        if (mb_strpos($line, 'Insert something:') === 0) {
            // No echo here
            // Write a pre-defined value to the script's input so that the bash script continues and prints this value
            fwrite($process->getProcessPipes()->pipes[0], 'My pre-defined value' . PHP_EOL);
        } else {
            echo $buffer;
        }
        $line = strtok($separator);
    }
}

$process->wait();
```

I have not found any other way to achieve my requirement. That is why I wrote the PR. If there is already a way to do this that I haven't found, please let me know.

I have not written tests or added something to the docs, because it is a simple new getter function. I hope that is fine.

Here are issues that might be solved with it:

https://github.com/symfony/symfony/issues/39482
https://github.com/symfony/symfony/issues/40037 (I have created this a month ago for this use case)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can't you use an `InputStream` instance for that already?

**Comment by momocode-de** [comment]
> Can't you use an `InputStream` instance for that already?

Actually yes, but I forgot to mention that I want to have both cases. For some questions I want that the user types input to command line (for that I need \STDIN as input stream) and for some questions I want to add the input automatically (that's not working with \STDIN).

**Comment by stof** [comment]
Exposing the ProcessPipes is leaking the internal implementation details of the component in an uncontrolled way. That's a bad idea IMO, as any refactoring changing the internals of Process about how we deal with these pipes can then become a BC break (which would basically force to freeze the component).

**Comment by stof** [comment]
> New feature? 	no (Just a new getter function)

this is wrong. this is not just a newer getter function. This is making ProcessPipes part of the public API of the component, and so makes it covered by the BC rules.

**Comment by nicolas-grekas** [comment]
> For some questions I want that the user types input to command line (for that I need \STDIN as input stream) and for some questions I want to add the input automatically (that's not working with \STDIN).

I don't understand why this makes a difference?
You need the STDIN of the surrounding process, not the one of the child process to do that.

I agree with @stof: exposing the pipes is a significant change in the API. We'd better not.

**Comment by momocode-de** [comment]
> I don't understand why this makes a difference?
> You need the STDIN of the surrounding process, not the one of the child process to do that.

This is the code you meant, right?

```
$inputStream = new InputStream();
$process = new Process([$this->script->getPath()], null, [], $inputStream, null);

$process->start();

foreach ($process as $type => $buffer) {
    $separator = "\r\n";
    $line = strtok($buffer, $separator);
    while ($line !== false) {
        if (mb_strpos($line, 'Insert automatically:') === 0) {
            // No echo here
            // Write a pre-defined value to the script's input so that the bash script continues and prints this value
            $inputStream->write('My pre-defined value' . PHP_EOL);
        } else {
            echo $buffer;
        }
        $line = strtok($separator);
    }
}

$process->wait();
```

Let's assume I have this bash script:

```
echo "Insert automatically:"
read AUTO

echo "Insert manually:"
read MANUAL

echo ${AUTO}
echo ${MANUAL}
```

Because I look in my PHP code for `Insert automatically:` and then write the pre-defined value to the input stream, the first question is working fine. But if I come to the second question, for that no input is automatically written, I type something to the command line and hit enter. But then nothing happens. I just come to a new line. That is because I type the text to the STDIN of the surrounding process, but it is not redirected to the child process and thus the child process not continues. And for that I have passed PHP's \STDIN to the child process before, what is not possible anymore, if I use the input stream.

> I agree with @stof: exposing the pipes is a significant change in the API. We'd better not.

Mhh ok, I understand. Do you have any other idea for my requirement?

**Comment by nicolas-grekas** [comment]
> That is because I type the text to the STDIN of the surrounding process, but it is not redirected to the child process

but can't you ready STDIN in your script, and pass it along to the inputstream?

**Comment by momocode-de** [comment]
> but can't you ready STDIN in your script, and pass it along to the inputstream?

How do you mean that? Do you have a code example?

**Comment by fabpot** [comment]
Closing this PR as we won't expose the internals for reasons explained in other comments.

**Pull request closed without merging**
