### PR TITLE
[Translator] fix test for php 7 compatibility

### PR DESCRIPTION
**Pull request by Tobion**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14086 for Translation component |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by dosten** [comment]
:+1:

**Comment by aitboudad** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @Tobion.

**Pull request merged**
