### PR TITLE
[Security] check token in payload instead just request

### PR DESCRIPTION
**Pull request by eltharin**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| License       | MIT

Replace request by getPayload for allow token to ba passed in Json for an API call

### CODE REVIEW

**Comment by xabbuh** [comment]
As this is not a bugfix this PR must target the ’7.2` branch.

**Comment by eltharin** [comment]
If you look the documentation for 7.1 it's written the attribute is alternative to `$submittedToken = $request->getPayload()->get('token');` but it's not really
So It's a bug not a new feature.
https://symfony.com/doc/current/security/csrf.html#generating-and-checking-csrf-tokens-manually

**Comment by xabbuh** [comment]
That’s a bug in the documentation (caused by https://github.com/symfony/symfony-docs/pull/19225) and needs to be fixed there.

**Comment by eltharin** [comment]
no need to fix the fake bug in documentation since the real bug is fixed. One moire time it's not a new feature

**Review by nicolas-grekas — APPROVED** [review]
I understand both pov, strictly speaking this is a feature, but since this class has been introduced in 7.1 #52961 by @yguedidi, it might be fine being a bit more relaxed here, afterall this might just be something we missed. Bonus: that'd make the doc simpler :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @eltharin.

**Pull request merged**
