### PR TITLE
[Messenger] Permit creating queue when an account is provided

### LINKED ISSUE #42208: Messenger Amazon SQS Connection::setup() throws exception when needing to create a queue
**Amazon SQS Messenger version(s) affected**: 5.3

**Description**
An exception is thrown when trying to setup non-existent queues.  The exception is ''The Amazon SQS queue "<queue_name>" does not exists (or you don\'t have permissions on it), and can\'t be created when an account is provided.". It is thrown from [line 276](https://github.com/symfony/amazon-sqs-messenger/blob/31e1ab0d9090ef3dd3ca693470778f51fcd0c79a/Transport/Connection.php#L276) of \Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection.  Looking at the code in that area, if there is an account set you can't create queues....but the reasoning for this isn't clear.

**How to reproduce**
* Configure messenger to use an access and secret key with an sqs url with account number (like https://sqs.us-west-2.amazonaws.com/123457890/?access_key=ACCESS_KEY&secret_key=SECRET_KEY)
* Create a transport using Amazon SQS and configure a queue_name that doesn't yet exist in SQS.
* Run `bin/console messenger:setup`

**Possible Solution**
I believe the thrown exception is unnecessary and can be removed.

**Note** *updated*
It seems like the error is thrown because of an assumption that if we have an account ID, then we must expect that the queue already exists.  However, I don't think that is necessarily true. From what I'm seeing, the queue url is predictable and we can assume it takes the following form: `https://sqs.<region>.amazonaws.com/<account>/<queue_name>`. From that, I don't think it hurts to ask if the queue exists, and if not, create it.  That is basically what the setup function already does.  But, perhaps there is a good reason not to trust that scheme?

### PR DESCRIPTION
**Pull request by nuvolapl**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42208
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by Kocal** [comment]
Hi everyone, what is the state of this PR? 
Should it target 5.4 instead of 6.1? To me it looks like a bug fix and not a new feature. The current behaviour is broken.

I can confirm the provided patch works, a non-existent queue is created when calling `->setup()` if needed.

Friendly ping @fabpot @jderusse @Nyholm 🙏 

Thanks!

**Comment by Nyholm** [comment]
This was part of the original PR by @jderusse. It is not a bug it is a new feature. 

I dont remember why this was added. Jeremy, do you know?

**Comment by chalasr** [comment]
This is for 5.4. It just misses a test case (if possible)

**Comment by Kocal** [comment]
I will create a new PR with @nuvolapl's commit + a new test case.

**Comment by chalasr** [comment]
Sorry Tobias, I missed your comment. If creating the queue on the fly was not expected to work, then it is indeed a new feature.

**Comment by Kocal** [comment]
Then what's the meaning of having an option `auto_setup` (which is `true` by default), if the auto-setup is not allowed?

**Comment by jderusse** [comment]
> This was part of the original PR by @jderusse. It is not a bug it is a new feature.

At this time, the DSN for the queue was `sqs://default/queue_name` OR `sqs://default/owner_id/queue_name`.
When `owner_id` was present, we presumed that it was somebodyelse's queue (like referencing the queue from another account). And, in that case, it was not possible de create the queue.

Since then, things changed:
- first, the `owner_id` could be us, and the presumption is wrong.
- the DSN could be now `https://sqs.eu-west-1.amazonaws.com/owner_id/queue_name`, and presumption is wrong again.

I believe this check should not be ignored because: If the code run with credentials belonging to account `1234`, but queue is `/9876/foo`, the Symfony will create the queue `foo` on account `1234` which is wrong.

This line should be replaced by checking if the ownerId is identical to the currently connected account (see `StsClient::getCallerIdentity`).

**Comment by Nyholm** [comment]
Thank you for the clarification. 

@Kocal do you understand and are happy moving forward in this way?

@chalasr With this new information (for both of us), do you agree on targeting 6.1?

**Comment by Kocal** [comment]
Thanks everyone!

@Nyholm: yeah I'm fine with those explanations, I will try to send a PR ASAP.

**Pull request closed without merging**
