### PR TITLE
[Workflow] Use event constants for subscribed events

### PR DESCRIPTION
**Pull request by 94noni**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

I was checking this feature `audit_trail` and thus this class
Is this code change desired? I've found several code using the event string
Or perhaps using the `Symfony\Component\Workflow\WorkflowEvents::LEAVE` etc ?
thx!

### CODE REVIEW

**Comment by lyrixx** [comment]
Looks like you broke tests
```
1) Symfony\Component\Workflow\Tests\EventListener\AuditTrailListenerTest::testItWorks
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
-Array &0 (
-    0 => 'Leaving "a" for subject of class "Symfony\Component\Workflow\Tests\Subject" in workflow "unnamed".'
-    1 => 'Transition "t1" for subject of class "Symfony\Component\Workflow\Tests\Subject" in workflow "unnamed".'
-    2 => 'Entering "b" for subject of class "Symfony\Component\Workflow\Tests\Subject" in workflow "unnamed".'
-)
+Array &0 ()
```

I never know if this is a BC break or not (cc @nicolas-grekas) but if it's not 👍🏼

**Comment by 94noni** [comment]
@lyrixx thx for the comment

hum yes, I think if we changed it is for the `Symfony\Component\Workflow\WorkflowEvents::LEAVE` constants, not the FQDN
I had in mind [this one](https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching) but perhaps it need to update the caller as well if using the FQCN

**Comment by nicolas-grekas** [comment]
It's a BC break unfortunately yes.

**Comment by 94noni** [comment]
@nicolas-grekas thx for confirming, thus it is either we use the event constants (see force push)
but we can not rely at all on event class on all symfony internal dispatch?

**Comment by 94noni** [comment]
status: needs work
status: needs discuss

**Comment by nicolas-grekas** [comment]
It's not worth the change IMHO. We have enough PRs to review/discuss in the backlog :)

**Comment by 94noni** [comment]
yes I know, I swapped just to see the tests

> but we can not rely at all on event class on all symfony internal dispatch?

may I ask you if you have some hints/time on this just to understand 
thx!

**Pull request closed without merging**
