### PR TITLE
[FrameworkBundle] Remove ControllerTrait::isFormValid()

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/24576#issuecomment-452220557
| License       | MIT
| Doc PR        |

**edit**: During the first draft I made, I did not use the request stack. I finally used it to mimic other shortcut! It was a bad idea. Now there is less code, it's simpler. Love it more

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@weaverryan I'd like to read your opinion about this. In the past you insisted a lot to add the `$form->isSubmitted() && ...` to all the doc examples to be more explicit. I think that's the right decision because code is easier to understand (otherwise newcomers can get lost: *who/when/how was the form submitted !?!?*)

So, my question: are you happy with the proposed shortcut name?

```php
if ($this->isFormValid($form, $request)) { ... }
```

Or would you prefer to keep being explicit about the form submission?

```php
if ($this->isFormSubmittedAndValid($form, $request)) { ... }

if ($this->formIsSubmittedAndValid($form, $request)) { ... }

...
```

Thanks!

**Comment by lyrixx** [comment]
@javiereguiluz we added `isSubmitted()` everywhere in the doc to fix an inconsistency in the Form Component. This is just a hack. Before the inconsistency was raised, almost nobody used `isSubmitted()` and everything were fine. 

So let's keep thing simple here. I really prefer `isFormValid()`. There are no need to explain about `isSubmitted()`

**Comment by javiereguiluz** [comment]
I've seen lots of newcomers have problems understand where or who submits the form. With the current recommended way of working, you can easily see the "is submitted?" check:

```php
public function new(Request $request)
{
    $task = new Task();
    $form = $this->createForm(TaskType::class, $task);

    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        // ...

        return $this->redirectToRoute('task_success');
    }

    return $this->render('task/new.html.twig', [
        'form' => $form->createView(),
    ]);
}
```

If you remove the optional `$form->isSubmitted()` ... the code is harder to understand but newcomers think: *"OK, I guess the form submission will take place in this weird $form->handleRequest($request) call which I don't understand (yet)."*

My fear is that the new shortcut removes any clues about the form being submitted or processed or handled:

```php
public function new(Request $request)
{
    $task = new Task();
    $form = $this->createForm(TaskType::class, $task);

    if ($this->isFormValid($form, $request)) {
        // ...

        return $this->redirectToRoute('task_success');
    }

    return $this->render('task/new.html.twig', [
        'form' => $form->createView(),
    ]);
}
```

But my fears could be exaggerated. That's why I want to know Ryan's opinion about this. Thanks!

**Comment by mbabker** [comment]
If the form being submitted is a condition of it being valid, then I would suggest `isFormValid` is perfectly fine as far as naming goes.

**Comment by weaverryan** [comment]
Sorry @lyrixx, I don't really like this new shortcut, though it looks like Fab does like it, so it's certainly subjective. As Javier mentioned, with:

```php
public function new(Request $request)
{
    $task = new Task();
    $form = $this->createForm(TaskType::class, $task);

    if ($this->isFormValid($form, $request)) {
        // ...

        return $this->redirectToRoute('task_success');
    }

    return $this->render('task/new.html.twig', [
        'form' => $form->createView(),
    ]);
}
```

The flow is very non-obvious. It's very strange to have a method starting with `is` that performs an action (an important action). And I can't really think of anything I love :/. But I'm also not sure the current/old way is a huge problem. 

If anything, I tend to agree with Javier's suggestions: https://github.com/symfony/symfony/pull/29813#issuecomment-452335729 - or `if ($this->submitForm($form, $request) && $form->isValid())`

> **lyrixx** we added isSubmitted() everywhere in the doc to fix an inconsistency in the Form Component. This is just a hack. Before the inconsistency was raised, almost nobody used isSubmitted() and everything were fine.

> Yes, but before we added `isSubmitted()`, there WAS still `handleRequest()`. So you could guess (even though the name isn't great) that this is the line that's probably submitting things. Removing any line that suggests the form being submitted is where things get slippery.

**Comment by lyrixx** [comment]
What should I do? I'm a bit confused here :|

**Comment by javiereguiluz** [comment]
@lyrixx I still like this shortcut ... but I think we need to tweak it a bit to make it better. I don't have a perfect solution for this, though.

As mentioned, controllers handling forms have two very different execution branches ... and this shortcut hides that too much at the moment.

**Comment by nicolas-grekas** [comment]
I think we should remove the method personally.

**Comment by lyrixx** [comment]
> As mentioned, controllers handling forms have two very different execution branches ... and this shortcut hides that too much at the moment.

Are you talking about submitted vs valid ?

**Comment by javiereguiluz** [comment]
@lyrixx no, I was talking about creating/rendering the form vs processing the form. That's why I need the "isSubmitted()" thing ... to say, *"yes! now it's when we are processing the form instead of rendering it"*.

**Comment by chalasr** [comment]
Too much important things are hidden by this shortcut, the name does not reflect what it does. I don't expect a `isValid()` method to throw if the form is submitted, nor I expect it to process submission by itself. +1 for reverting.

**Comment by lyrixx** [comment]
Actually, I just wanted to replace

```php
if ($form->handleRequest($request)->isSubmitted()) && $form->isValid()) {
    # code...
}
```
```php
if ($this->isFormValid($form) {
    # code...
}
```

I guess I have used the following code only once
```php
if ($form->handleRequest($request)->isSubmitted()) {
   #code
}
```

I think I spend more time to make theses PR merged than typing `if ($form->handleRequest($request)->isSubmitted()) && $form->isValid()) {` :joy: 
So Let's revert it :)

**Review by xabbuh — CHANGES_REQUESTED** [review]
@lyrixx Can you change the PR title to better match what we now have here? :)

**Comment by zanbaldwin** [comment]
Changing `array()` syntax to `[]` is probably outside the scope of this pull request.

Also, can someone from the core team clarify which syntax Symfony components now use?
Last I heard the only place the new syntax was being used was in [`symfony/flex`](https://github.com/symfony/flex) and not the components :woman_shrugging:

**Comment by ostrolucky** [comment]
All the concerns raised could be solved by using @javiereguiluz's suggestion `isFormSubmittedAndValid`. Not sure why revert was chosen instead of simple rename.

**Comment by gharlan** [comment]
Maybe just add a `isSubmittedAndValid()` shortcut to form instead of ControllerTrait, and without implicit `handleRequest`?



vs.



I need ~5.8s to type this instead of ~9.3s (with autocompletion in phpstorm). Don't know, if it is worth it. ;)

**Comment by chalasr** [comment]
And have an `isSubmitted...()` throwing an exception if the form is not submitted? Sounds plain wrong to me.

**Comment by ostrolucky** [comment]
No exception, it's not implied anywhere

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
