### PR TITLE
[DependencyInjection] PhpDumper::isFrozen inconsistency

### PR DESCRIPTION
**Pull request by allflame**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

There is a bug (from my prespective) regarding cached container generated by the PhpDumper. ProjectServiceContainer::isFrozen call will be forwarded to the Container::isFrozen method which relies on instance of the parameter bag property. In the cached ProjectServiceContainer parameter bag is undefined afetr intialization hence calls to the isFrozen will result in false unless getParameterBag will be called and then calls to isFrozen will return true onwards.
This can actually break some compatibility, although it's a bug from my prespective from the very beginning

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Looks like a bug to me also, not a bc break.
:+1: on 2.7

**Comment by stof** [comment]
:+1: on 2.7

**Comment by fabpot** [comment]
Thank you @allflame.

**Comment by allflame** [comment]
@fabpot can we get a backmerge to 3*? Or what should I do to get this fix there?

**Comment by nicolas-grekas** [comment]
@allflame it will come to 3.* as part of the regular merges from 2.7

**Pull request closed without merging**
