### PR TITLE
[FrameworkBundle] Use canBeEnabled() instead of canBeUnset() for consistency

### PR DESCRIPTION
**Pull request by GuilhemN**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | https://github.com/symfony/symfony/issues/13703 |
| License | MIT |

I'm not sure if we should consider this as a bug fix or as a new feature.

### CODE REVIEW

**Comment by fabpot** [comment]
:+1:

**Comment by fabpot** [comment]
To keep BC, I would keep the `canBeUnset()` call as well.

**Comment by Ener-Getick** [comment]
@fabpot in case someone uses the FrameworkBundle's ``Configuration`` class and check if keys exist ? 
Otherwise ``canBeEnabled`` threat ``false`` so it should not change anything to the actual configurations.

**Comment by fabpot** [comment]
@Ener-Getick I know that the BC break would be small, but as it does not cost us anything to not break BC, I prefer to.

**Comment by Ener-Getick** [comment]
@fabpot well having both options wouldn't change the ``Configuration`` output.
(``allowFalse`` is checked after ``equivalentValues``, see [here](https://github.com/symfony/config/blob/master/Definition/BaseNode.php#L254-L261)). 
The only thing changing would be that ``ArrayNode::setAllowFalse()`` would be called. Is this what you want ?

**Comment by fabpot** [comment]
ok, fair enough, :+1:

**Comment by fabpot** [comment]
Thank you @Ener-Getick.

**Comment by Ener-Getick** [comment]
You're welcome :-)

And there is a solution to keep ``canBeUnset`` but I don't know if that's not durty...
```php
->arrayNode()
    ->canBeEnabled()
    ->canBeUnset()
    ->threatFalseLike(false)
```

**Pull request closed without merging**
