### PR TITLE
[Process] Provide getPipes() public interface.

### PR DESCRIPTION
**Pull request by boombatower**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

Useful for performing stream operations directly on the pipes.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
But this isn't portable unless I'm wrong: Windows pipes or sigchild enabled php pipes must be handled very differently. This looks like making the abstraction leak and defeating the purpose of the component.
What do you need this pipes for?

**Comment by boombatower** [comment]
@nicolas-grekas Could be, but then not sure what is the correct way to expose the unix pipes.

As the comment in code indicates I need to be able to use `stream_select()` to wait for output from a number of processes in a loop with a timeout. During timeouts there are other things that need to be done (ie processing). This is independent of the idle timeout provided by Process.

Additionally, per the discussion in #19558 I also need direct write access to input pipe to avoid delays. Alternatively, write could be handled by calling isrunning() (which triggers readwrite or pipes) after appendingInputBuffer(), but as described the current interactive input implementation is unclear how to flush the buffer.

**Comment by boombatower** [comment]
As far as portability getPipes() returns the wrapper pipe class which will expose different features on different platforms. As such it's portable, but one would need to check the specific subclass to know if particular features are available.

Having a parameter for the `stream_select()` timeout on `readAndWrite()` could then be used directly which solves my case for a single process, but unfortunately does not help for handling multiple.

**Comment by boombatower** [comment]
To be clear I basically need:

```php
while (true) {
  $r = [$process1->getPipes()[1], $process2->getPipes()[1]];
  stream_select($r, $w, $e, 1, 0);
}
```

Noting the custom timeout.

**Comment by boombatower** [comment]
@nicolas-grekas Also what do you think of exposing processInformation?

For instance if one wants to handle process termination inside a process subclass the only real place is `updateStatus` (which is protected), but calling any message such as `isRunning()` results in an infinite loop since they all call `updateStatus`. The only real way around this is direct access to the variables they read .

```php
updateStatus()
{
  $running = magic();
  parent::updateStatus()
  if (!magic() && $running) {
    // terminated
  }
}
```

Any thoughts?

**Comment by nicolas-grekas** [comment]
So, I'm :-1: on this one: the exposed classes are `@internal`. I understand this provides no solution to the `stream_select`. If you want to make your code take responsibility for this, you could access to the pipes through the private properties (through e.g. a rebound closure).

About your last question, you should be able already to deal with recursivity: just add a property `isRecursiveCall` and don't call the parent on recursive calls. WDYT?

**Comment by boombatower** [comment]
The `Closure::bind()` works, thanks for the suggestion. I have a little over 200 lines of extra sauce to facilitate some extra process workflow in a subclass of Process. In case anyone else wants an example, I ended up with the following:

```php
/**
  * Returns PipesInterface for underlying process.
  *
  * Useful for performing stream operations directly on the pipes. For
  * example performing a stream_select() across multiple processes.
  *
  * Obviously, closing or altering pipes may cause errors.
  *
  * @throws LogicException In case the process is not running
  */
public function getPipes()
{
  static $bind;

  if (!isset($bind)) {
    $getPipes = function()
    {
      if (!$this->isRunning()) {
        throw new LogicException('Process pipes are not available while the process is not running.');
      }

      return $this->processPipes;
    };
    // The scope parameter will need to be updated if this class ends up with
    // another parent in between it and Symfony Process.
    $bind = Closure::bind($getPipes, $this, get_parent_class());
  }

  return $bind();
}
```

The recursive check I implemented as method static, but it functions. Thanks. I prefer these to having a fork/patch against proper Process.

As such I imagine these pull requests can be closed

**Pull request closed without merging**
