### PR TITLE
[PhpUnitBridge] Mark parent class also covered in CoverageListener

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       |
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by lyrixx** [comment]
Actually, I do think this is a bug fix. WDYT?

**Comment by nicolas-grekas** [comment]
OK as a bug fix yes.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
@lyrixx Can you rebase on 3.4?

**Comment by lyrixx** [comment]
Done. Sorry I was AFK

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
