### PR TITLE
Filtering empty uuids in ORMQueryBuilderLoader.

### PR DESCRIPTION
**Pull request by mlazovla**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23808 
| License       | MIT
| Doc PR        | no

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
ping @Tobion @maryo

**Comment by Tobion** [comment]
Seems good enough. But https://github.com/symfony/symfony/issues/23808#issuecomment-321513830 would be the more correct solution.

**Comment by nicolas-grekas** [comment]
@mlazovla what's your stand about that "more correct solution"?

**Comment by mlazovla** [comment]
Maryo's new solution looks more universal than my PR. But I am not sure if it broke some edge case.

**Comment by nicolas-grekas** [comment]
So, should we merge and later on do what @maryo describes? Anyone willing to give it a try?

**Review by javiereguiluz — APPROVED** [review]
This definitely improves our current code and it looks correct. I'm not sure about the other proposed solution [here](https://github.com/symfony/symfony/issues/23808#issuecomment-321513830) and even its author mentions some potential problems with PostgreSQL.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mlazovla.

**Pull request merged**
