### PR TITLE
[HttpFoundation] Fix getClientIp @return docblock

### PR DESCRIPTION
**Pull request by e-moe**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22415
| License       | MIT
| Doc PR        | none

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
👍

**Review by xabbuh — APPROVED** [review]

**Review by sstok — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @e-moe.

**Comment by ossinkine** [comment]
IMO the client IP can not be null in HTTP request. If you mock a request to use it in tests (as @miklcct described in #22415), you should make it correctly.
I suggest to revert this PR.

**Comment by ossinkine** [comment]
Moreover, it is impossible even from the viewpoint of code execution: you'll get a notice `Undefined offset: 0` if `$ipAddresses[0]` is undefined.

**Pull request merged**
