### PR TITLE
[TwigBridge] bootstrap4 file_widget: allow setting label attributes declared in label_attr

### PR DESCRIPTION
**Pull request by AngelFQC**
| Q             | A
| ------------- | ---
| Branch?       | 4.2 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | ...   
| License       | MIT
| Doc PR        | ... 

> Bootstrap provides a way to translate the “Browse” text in HTML with the data-browse attribute which can be added to the custom input label.

https://getbootstrap.com/docs/4.3/components/forms/#translating-or-customizing-the-strings-with-html

But currently the attributes declared in label_attr aren't being added.

Previously I sent this same change to the master branch (PR #31102), but I think I should have sent it to branch 4.2

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks for submitting but #31220 is enough.

**Comment by AngelFQC** [comment]
Ok. Thanks.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
This looks like a new feature to me, right?

**Comment by AngelFQC** [comment]
@fabpot No. Well I think no, because the html attributes defined in a form with `label_attr`currently are not being printed in label html tag... so it a bug :)

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @AngelFQC.

**Comment by xabbuh** [comment]
@fabpot IMO we should have merged this as a bugfix. The `FileType` was the only type where it was not possible to do this.

**Comment by o-alquimista** [comment]
When I pass a translation key as the `data-browse` value, it is not translated.

```
            ->add('avatar', FileType::class, [
                'label' => 'label.avatar',
                'required' => false,
                'label_attr' => [
                    'data-browse' => 'label.select',
                ],
            ])
```

However, `label.avatar` is translating as expected. Why doesn't the same happen to `data-browse`?

**Comment by apfelbox** [comment]
Only [`help`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L304), [`placeholder`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L436), [`title`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L436) and [`label`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L282) are translated by default.

**Pull request merged**
