### PR TITLE
Dirname simplification

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by kalessil** [comment]
Awesome!

**Review by phansys — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by derrabus** [comment]
Can we add the `combine_nested_dirname` rule to the CS Fixer ruleset?

**Comment by fabpot** [comment]
@derrabus done!

**Pull request merged**
