### PR TITLE
[Profiler] Fix code excerpt wrapping

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 3.3 
| Bug fix?      | yesish
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | N/A 
| License       | MIT
| Doc PR        | N/A

|Before|After|
|--|--|
|screenshot 2017-05-30 a 19 09 03|screenshot 2017-05-30 a 19 09 35|

However, I think my own preference for code excerpts would be to never wrap, at the risk of scrolling horizontally. 1024px is enough to read most of the code excerpt without scrolling, and it feels less messy (to me) when a line is too long. WDYT?

### CODE REVIEW

**Comment by yceruto** [comment]
:+1: to never wrap! it feels less messy (to me too)

**Comment by ro0NL** [comment]
Looking at it, i think the line-height really needs a patch as well (part of discussion in #22439, but perhaps we can do it here already). The space between `}` and `throw` intuitively looks like 2 line breaks.

**Comment by ogizanagi** [comment]
Hmmm. I guess we can close this one if we can accept #22439 as a "bug fix".
Or we can merge this one instead, just fixing the code wrapping and keep the nowrap suggestion for 3.4 in #22439, but I guess it'd be better to have something consistent between 3.3 and 3.4 about this...

**Comment by nicolas-grekas** [comment]
I like how github does. Wrapping code is a bad idea I think.

**Comment by ogizanagi** [comment]
Great! So it seems we have a consensus about this currently (at least no opponent right now).

Either I update this PR to always prevent wrapping and allow horizontal scrolling with minimal changes, either we reconsider #22439 to target 3.3 as a bug fix and we close this one.
IMHO, I'd love to see #22439 merged in 3.3, because (despite I didn't checkout it yet), it seems @sustmi did great and it's not DX but UI/UX fixes to me. Also, I clearly think having 2 different UI/UX will only complicate maintenance.

**Comment by nicolas-grekas** [comment]
> prevent wrapping and allow horizontal scrolling with minimal changes

if it's a few css lines+classes, let's do that - it wouldn't prevent considering #22439 afterwards

**Comment by ogizanagi** [comment]
Done.

|Before|After|
|--|--|
|juin-03-2017 10-38-47|juin-03-2017 10-39-04|

(I also slightly updated the line height, so it feels more natural and consistant for every lines. Poke @ro0NL)

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Comment by ro0NL** [comment]
Much better :+1:

**Comment by fabpot** [comment]
Thank you @ogizanagi.

**Pull request merged**
