### PR TITLE
[Mailer] Use idn encoded address otherwise Brevo throws an error

### PR DESCRIPTION
**Pull request by etlam**
| Q             | A
| ------------- | ---
| Branch?       | 6.4 for features
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | 
| License       | MIT

We have to use the encoded email address in case of special character domains like 'kältetechnik-xyz.de' otherwise brevo fails with 400 error.

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please add a testcase? Thank you

**Comment by etlam** [comment]
@OskarStark Tests are added and fix is also contributed to the new Brevo transport.  
I can not reproduce this one failing unit test locally, what am I doing wrong and do I have to fix it?  

As far as I understand the test, it should not fail after doing changes to brevo or sendinblue.

**Comment by OskarStark** [comment]
That's caused by another PR I guess.

cc @StaffNowa

**Comment by StaffNowa** [comment]
> That's caused by another PR I guess.
> 
> cc @StaffNowa

@OskarStark I think it is not the same case as nullable transport.

@etlam as I see your PR it is about brevo API, but why do you edit another API? Is it the same company?

**Comment by OskarStark** [comment]
@etlam you can ignore the failing test case.

> @OskarStark I think it is not the same case as nullable transport.

Yes, but AFAIR you had a PR regarding null transport, and this PR is failing, can you please have a look? Thanks

> @etlam as I see your PR it is about brevo API, but why do you edit another API? Is it the same company?

Yes it is!

**Comment by etlam** [comment]
> @etlam as I see your PR it is about brevo API, but why do you edit another API? Is it the same company?

In 2023 Sendinblue changed its name to Brevo.

**Comment by StaffNowa** [comment]
@OskarStark I am running tests now with https://github.com/symfony/symfony/pull/51830, and we will see if it helps or not )

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @etlam.

**Pull request merged**
