### PR TITLE
[Config] Remove extra sprintf arg

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 5.0 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | N/A 
| License       | MIT
| Doc PR        | N/A

there is only one placeholder here

(code in previous branches is commented out for 5.0)

### CODE REVIEW

**Comment by chalasr** [comment]
Should target 5.0 then, right?

**Comment by ogizanagi** [comment]
Of course, my bad :)

**Review by chalasr — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
> (code in previous branches is commented out for 5.0)

then that's for 4.3!

**Comment by ogizanagi** [comment]
4.3 you get 😄

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @ogizanagi.

**Pull request merged**
