### PR TITLE
[Finder] mark the LazyIterator class as internal

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | https://github.com/symfony/symfony/pull/40040#discussion_r575127254
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by jderusse** [comment]
Thanks for taking care of this. Could you please also take https://github.com/symfony/symfony/pull/40040#discussion_r575127730 into account?

**Comment by ro0NL** [comment]
why not keep support for `Finder::append(new LazyIterator($callable))`?

`appendFromCallable` for 5.x maybe, then it can become internal IMHO

**Comment by stof** [comment]
@ro0NL this can was merged 4 hours ago. so there is no support to keep. `Finder::append(new LazyIterator($callable))` is not supported in any released version of Symfony, because `LazyIterator` does not exist there.

**Comment by ro0NL** [comment]
right, i meant introducing the feature in 4.x as a bonus side effect yes

unless we have other plans for 5.x, or we conclude it's not useful for users at all

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
@jderusse I didn't read your comment before the PR was merged. Feel free to open a PR with your suggestion.

**Pull request merged**
