### PR TITLE
[DependencyInjection] Throw exception when the constructor is private

### PR DESCRIPTION
**Pull request by mikocevar**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Resolves developer confusion as seen here #53651
| License       | MIT

It makes no sense to include a class with a private constructor since it cant be instantiated unless that happens within a static method. Skipping such a class in not in my scope of solutions, since that would leave the developer in the dark, just like it happened in the mentioned issue.

No additional test failed when running phpunit on https://github.com/symfony/dependency-injection. 

Symfony already covers a class with private constructor, but the message only appears when manually registering the class.

I did not write any additional tests either, if that is needed please say so, any suggestions will be appreciated since the tests are advanced.

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
> I did not write any additional tests either, if that is needed please say so

Yes. Always.

**Comment by mikocevar** [comment]
Will work on that in the following days @derrabus

**Comment by mikocevar** [comment]
@derrabus I closed the PR since it looks like I had the wrong base branch. Will make another one when I have everything ready.

**Comment by derrabus** [comment]
Sure, take your time.

**Pull request closed without merging**
