### PR TITLE
[Messenger] Remove deprecated `StopWorkerOnSignalsListener`

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 7.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Followup to #50997.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Looks like this would break 6.4? Can you have a look?

**Comment by HypeMC** [comment]
@nicolas-grekas Done, see #51093

**Comment by derrabus** [comment]
Please rebase. 🙂

**Comment by HypeMC** [comment]
@derrabus Done, fabbot failure is unrelated.

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.

**Pull request merged**
