### PR TITLE
[Config] Throw an exception when using cannotBeEmpty() with numeric or boolean nodes

### PR DESCRIPTION
**Pull request by GuilhemN**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16812 |
| License | MIT |

### CODE REVIEW

**Comment by sstok** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
:+1:, as a bug fix for me

**Comment by Ener-Getick** [comment]
The build failure seems unrelated.

**Comment by Ener-Getick** [comment]
@nicolas-grekas can you ping the people in charge of the ``Config`` component please ?
Would be good if someone else reviews this PR.

**Comment by fabpot** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1: (I think we accidentally just removed the methods instead of throwing the exception as it was planed initially (see https://github.com/symfony/symfony/pull/15285#issuecomment-121687849).

**Comment by stof** [comment]
Thank you @Ener-Getick.

**Pull request merged**
