### PR TITLE
@expectedException expects FQCN

### PR DESCRIPTION
**Pull request by ro0NL**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any |
| License | MIT |
| Doc PR | reference to the documentation PR, if any |

See #20028 

Almost there :)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
It would be nice to have fabbot report these, wdyt? Can you suggest it  on the php-cs-fixer repos?

**Comment by ro0NL** [comment]
Agree.. there's some discussion already though. But ill try to PR a simple fixer for this..

**Comment by ro0NL** [comment]
@nicolas-grekas lets see what happens :)

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request merged**
