### PR TITLE
[2.6] * Happy New Year 2015 *

### PR DESCRIPTION
**Pull request by saro0h**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by romqin** [comment]
IMO, one PR was enough ^^

**Comment by iltar** [comment]
It's easier to press merge for 3 branches than to cherry-pick them afterwards tho. But happy new year!

**Comment by stof** [comment]
@iltar we don't cherry-pick. the 2.3 branch gets merged into newer branch on a regular basis (and so on). This ensures that we never miss a patch which should go in all branches.
So merging different PRs for each branch means having duplicate commits doing the same in the history.

So this PR should be change to update the year only for components which are new in 2.6 (VarDumper and DebugBundle)

**Comment by saro0h** [comment]
Done :)

**Comment by hhamon** [comment]
:+1:

**Pull request merged**
