### PR TITLE
[Form] Made original data of a form and choices accessible in templates

### PR DESCRIPTION
**Pull request by webmozart**
Bug fix: no
Feature addition: yes
Backwards compatibility break: no
Symfony2 tests pass: yes
Fixes the following tickets: #4171
Todo: -

Now you can access the normalized data of a form in the template:

```
form.vars.data
```

You can also access the original data of a choice, for example the entities in an entity type:

```
choice.data
```

### CODE REVIEW

**Comment by trsteel88** [comment]
Is this merged into 2.6?

I can't seem to get the underlying object.

```twig
{% for choice in form.packages %}
    {{ dump(choice.vars.data) }}
{% endfor %}
```

Data just results in a true/false (if the checkbox is ticked or not)

screen shot 2015-04-01 at 9 49 59 am

**Comment by stof** [comment]
@trsteel88 the ChoiceView is used for ``<select>`` element, not for checkbox groups. So this PR is about a different case than yours
An expanded choice type is a compound form with multiple children having each a boolean data.

**Comment by stof** [comment]
and if you want to get the underlying data of the choice type itself, do it on the choice type, not on its checkbox children:

```jinja
{% dump(form.packages.var.data) %}``
```

**Comment by stof** [comment]
and to answer about the version, this was merged into 2.1.0

**Comment by trsteel88** [comment]
Thanks for the info @stof. However, **form.packages.vars.data** only gives me the data of the selected elements.

screen shot 2015-04-02 at 8 04 46 am

I am after the object of each package.

Basically, I want the **Package 1** and **Package 2** object so I can put an image (related to the Package object) next to the checkbox.

**Pull request merged**
