### PR TITLE
[YAML] PHPDoc fixes for inline parser/dumper

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | "master"
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### CODE REVIEW

**Comment by fabpot** [comment]
Is it really just for master? I think most (if not all) applies to 2.7 as well.

**Comment by ro0NL** [comment]
You're right.. havent checked it yet :) just proposed the change first. Ill have a look tonight :+1:

**Comment by ro0NL** [comment]
@fabpot ready.

**Comment by stof** [comment]
👍

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request merged**
