### PR TITLE
[Config] Fix array sort on normalization in edge case

### PR DESCRIPTION
**Pull request by romainneutron**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by romainneutron** [comment]
What solved by this issue:

At the moment, if you define a bundle configuration like this:

```
config:
   anything-with-a-dash-and-no-underscore: value
   anythingelse: othervalue
```

It is resolved like this:
```
["config"]=>
  array(2) {
    ["anythingelse"] => string(10) "othervalue"
    ["anything_with_a_dash_and_no_underscore"] => string(5) "value"
  }
```
instead of
```
["config"]=>
  array(2) {
    ["anything_with_a_dash_and_no_underscore"] => string(5) "value"
    ["anythingelse"] => string(10) "othervalue"
  }
```
This is particularly a problem when defining prioritized rules :)

You can find the details of the issue at https://github.com/nelmio/NelmioSecurityBundle/issues/72

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by tucksaun** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @romainneutron.

**Pull request merged**
