### PR TITLE
[Cache] Revert "minor #47292  make `Redis*Proxy` extend `Redis*`"

### PR DESCRIPTION
**Pull request by chalasr**
This reverts commit ee7809908317b505e455376f3ca488cb46309386, reversing changes made to 0b325376e8acb8114c557e3e3684c0b0d3d9b6e0.

| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Maintaining these proxies turns out to be painful for no benefit. 
Here's the history since they've been added 1 month ago:
- [[Cache] sync Redis6Proxy with upstream](https://github.com/symfony/symfony/commit/05697ca95747b9964e985a1cc19acc6596d8c0d7)
- [[Cache] sync Redis6Proxy with upstream](https://github.com/symfony/symfony/commit/34ff72fabac83c7b41ab55665c164cdc2b231199)
- [[Cache] Sync Redis6Proxy::lPos() return type](https://github.com/symfony/symfony/commit/94ed011378c86228c2fd8598231bae6b285d966c)
- [sync the Redis6Proxy class with latest upstream changes](https://github.com/symfony/symfony/commit/351622406004933931281489956e3615c2907f38)
- [[Cache] sync redis6 proxies with upstream](https://github.com/symfony/symfony/commit/ad83254d50129b447811c0da767c0ba3df0aa205)
- [sync Redis6Proxy with upstream implementation](https://github.com/symfony/symfony/commit/92963b14b25f8d89b331dec52218a6d4a61a883d)
- [Fix redis rests](https://github.com/symfony/symfony/commit/8e2899861de1c3ee09d53f3dc336724d39def5fd)

No bugfix here, only syncing. As usual having something that makes our CI always red is frustrating for contributors as well as core developers, and of course our OSS time is better spent elsewhere. Therefore I propose to revert this change.
I'm sure we will find other ways to leverage the work done on lazy proxies.

### CODE REVIEW

**Comment by jderusse** [comment]
What's about generating (and caching) the class on the fly instead?

**Comment by nicolas-grekas** [comment]
Closing in favor of #47966

> What's about generating (and caching) the class on the fly instead?

That would fail on r/o filesystems / or be dumped in a writable location, but then this becomes too complex.

The proxies are stable, see v5 which doesn't require changes. v6 is just a fast-moving target at the moment.

**Comment by ostrolucky** [comment]
Or use an proxy manager. This is precisely why we started to use it in SncRedisBundle

**Comment by nicolas-grekas** [comment]
@ostrolucky AFAIK this doesn't work in practice because of https://github.com/Ocramius/ProxyManager/issues/162, which affects ext-redis v5 (v6 should fix it but it's not ready yet.)

**Pull request closed without merging**
