### PR TITLE
Fix `!important` in VarDumper stylesheet

### PR DESCRIPTION
**Pull request by mul14**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| License       | MIT

Fix tiny thing.

Before

```css
.hidden {
    display: none; !important
}
```

After

```css
.hidden {
    display: none !important;
}
```

### CODE REVIEW

**Comment by Kocal** [comment]
I guess you have to rebase your PR... :smile:

**Comment by fabpot** [comment]
@mul14 Can you fix this PR?

**Comment by mul14** [comment]
@Kocal this bug introduced in 4.1. The 4.0 or lower doesn't have `htmlDescriptor.css` file

@fabpot It's hard, too many conflicts. I think I will close this PR, then create new PR based on 4.1 branch.

**Comment by mul14** [comment]
New PR #28118

**Pull request closed without merging**
