### PR TITLE
Require security-acl 2.7 for BC

### PR DESCRIPTION
**Pull request by scaytrase**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | BC fix |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15648 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Could you also please remove the acl-related suggestions?
https://github.com/symfony/symfony/pull/15658/files#diff-303420d112ba190b0f9edb9c9806d7b2R43

**Comment by scaytrase** [comment]
Done

**Comment by nicolas-grekas** [comment]
Thanks @scaytrase.

@iltar is there a plan to release security-acl 3.0? If yes, shouldn't we change these ~2.7 in ~2.7|~3.0.0 in this composer.json and in the root one ?

**Comment by nicolas-grekas** [comment]
Hum, looking at the branch alias on security-acl, I'd say yes. @scaytrase can you please to this (use ~2.7|~3.0.0 in the two composer.json files)?

**Comment by scaytrase** [comment]
The first is `Security` component's. The second is global `symfony\symfony` composer.json? Correct?

**Comment by Tobion** [comment]
Since security-acl will have it's own release cycle, as you said yourself, why would you assume 3.0 version is going to be compatible? 3.0 would mean the acl part has a BC break which would not make it compatible.

**Comment by nicolas-grekas** [comment]
these two files yes. I don't assume 3.0 will stay compatible with 2.8. But right now, it is compatible. And tests will tell when and if this becomes false. Which may or may not happen (this is how we did for all components btw).

**Comment by Tobion** [comment]
@nicolas-grekas no tests will not tell us because there is not test in the security core or csrf that uses the acl component of course. Adding 3.0 as allowed dependency is totally random. You could just as well allow 4.0 as well, or anything since we don't know yet what exactly the BC break will be in >=3.0 as it does not exist yet.

**Comment by scaytrase** [comment]
i hope we could use travis to check 3.0.0 compatibility. And to agree  with @tobion - with desync release process 3.0.0 is no really have to be compatible. It could be not released at all.

**Comment by nicolas-grekas** [comment]
That's true, OK for me, let's remove the 3.0

**Comment by iltar** [comment]
I think that for the sake of simplicity, it would be easier to have it follow the same major/minor versions as `symfony/symfony`.

**Comment by scaytrase** [comment]
@nicolas-grekas @iltar So what is the correct version reference? `~2.7` or `~2.7|~3.0.0`?

**Comment by nicolas-grekas** [comment]
~2.7 for me after this discussion :-)

**Comment by iltar** [comment]
I agree with `~2.7`, when 2.8 is released, it can become `~2.8` and should support `~3.0` with forward compatibility: `~2.8|~3.0`.

**Comment by scaytrase** [comment]
I've rolled-back addition of 3.0.0, please re-check.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by Tobion** [comment]
:+1:

**Comment by Tobion** [comment]
Thank you @scaytrase.

**Pull request closed without merging**
