### PR TITLE
[Travis] Do not use legacy mongo ext

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Should make travis green after #24438

### CODE REVIEW

**Comment by chalasr** [comment]
Remaining failure unrelated.

**Comment by nicolas-grekas** [comment]
Fixed in https://github.com/symfony/symfony/pull/24409 by a group legacy annotation.

**Comment by chalasr** [comment]
@nicolas-grekas But the test should not be marked as legacy, the class itself is not deprecated

**Comment by nicolas-grekas** [comment]
Hum indeed... See master where I just removed the group and kept the test class obviously.
The issue with the attached patch is that we should still test with mongo.so in 3.4.
Maybe the legacy group is enough? The class is still tested.

**Comment by stof** [comment]
Well, we don't have an easy way to make it legacy conditionally (only when tests are running with the old extension)

**Comment by chalasr** [comment]
:+1: fine for me as well

**Pull request closed without merging**
