### PR TITLE
[Form] compound forms without children should be considered rendered implicitly

### PR DESCRIPTION
**Pull request by backbone87**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | possibly |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17580 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @backbone87.

**Comment by fabpot** [comment]
Actually I merged too fast. Tests do not pass. Can you check that @backbone87? Thanks.
https://travis-ci.org/symfony/symfony/builds/163762900

**Comment by fabpot** [comment]
reverting for now

**Comment by backbone87** [comment]
@fabpot @webmozart

the failing test cases build their forms out of plain `FormType`s which are compound by default. This fix basically considers every form (sub) tree as rendered that doesnt contain at least one non-compound form type. if not for the CSRF extension adding a non-compound HiddenType, doin `{{ form_widget(myFormView) }}` or `{{ form_row(myFormView) }}` when myFormView is a compound type and has only compound type descendants (and CSRF extension disabled) wouldnt output anything. thats because https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormRenderer.php#L158 checks the rendered flag initially for every non label block to make sure every form widget is not rendered more than once.

i could change the test cases to set the leaf `FormType`s to compound = false, which would ensure all subtree are rendered, but i question the check at https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormRenderer.php#L158 itself

i have commented out the check and the failing test cases are gone, but one other pops up, i will investigate that tomorrow

**Comment by backbone87** [comment]
The following test case is failing, if i remove the check at https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/FormRenderer.php#L158

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Tests/AbstractDivLayoutTest.php#L142

This is because form_rest relies on the check in the FormRenderer. Although form_rest does only output not already rendered child forms, it only makes the check explicitly for children ( https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L319 ) and then starts the default renderering process for unrendered childs , relying on FormRenderer to check for already rendered descendants **within** these childs.

You could completely remove the check at https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L319 and you will get exactly the same result, because form_rest just calls form_row on children, which itself skips already rendered children.

imo the check should be done consistently only in one place. either in the form theme or in the form renderer. however we can only move it to the renderer, because moving it (completely) to the form theme would require modifying them, which could be a hugh break in BC. but i think it would be actually better to do it in the form theme, since this allows you do output form rows/widgets multiple times (for example to populate a JS template fragment).

**Pull request merged**
