### PR TITLE
[Runtime] Fix property must not be accessed before initialization on SymfonyRuntime

### PR DESCRIPTION
**Pull request by l-vo**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Introduced by https://github.com/symfony/symfony/pull/51068, see https://github.com/symfony/symfony/pull/51068#issuecomment-1650330435

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @l-vo.

**Comment by PhilETaylor** [comment]
Awesome - thanks @l-vo, this indeed addresses and fixes the https://github.com/symfony/symfony/pull/51068#issuecomment-1650330435

**Comment by PhilETaylor** [comment]
@nicolas-grekas any chance of pushing this to https://github.com/symfony/runtime/tree/6.4 because at the moment 6.4-dev runtime is broken because of this one

```
Fatal error: Uncaught Error: Typed property Symfony\Component\Runtime\SymfonyRuntime::$input must not be accessed before initialization in /var/www/current/vendor/symfony/runtime/SymfonyRuntime.php:109 Stack trace: #0 /var/www/current/vendor/autoload_runtime.php(16): Symfony\Component\Runtime\SymfonyRuntime->__construct() #1 /var/www/current/public/index.php(13): require_once('...') #2 {main} thrown in /var/www/current/vendor/symfony/runtime/SymfonyRuntime.php on line 109
```

**Comment by nicolas-grekas** [comment]
We have an issue with the splitter, it should be fixed in the very next days if not hours.
Thanks for sponsoring me BTW!

**Comment by PhilETaylor** [comment]
> We have an issue with the splitter, it should be fixed in the very next days if not hours.

ah no worries - sorry to hear that. Absolutely no pressure from me!

> Thanks for sponsoring me BTW!

It's only small amounts but Im sure they add up somehow.

**Comment by derrabus** [comment]
We're having trouble with our subtree splitter at the moment. Bear with us.

**Comment by PhilETaylor** [comment]
> We're having trouble with our subtree splitter at the moment. Bear with us.

Absolutely! There is no pressure from me at all - thanks for letting me know though. I have manually worked around this bug this week, and will continue to all weekend :) no pressure this end, and now I know the reason it was not split. :)

**Comment by fabpot** [comment]
The splitter has now catch up.

**Pull request merged**
