### PR TITLE
Fix BC break after split of ACL from core

### PR DESCRIPTION
**Pull request by wouterj**
Rebased version of https://github.com/symfony/symfony/pull/15520

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
Do we still needs this (given the changes done in 1270e725601e08a228d35c6c91cea61aea958b03)?

**Comment by WouterJ** [comment]
@xabbuh yes, when installing `symfony/symfony`, only the root composer.json is what matters and it does not require the not included Security ACL package.

**Comment by xabbuh** [comment]
indeed :+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @WouterJ.

**Comment by WouterJ** [comment]
Would there be a way to warn package maintainers that they have to add `symfony/security-acl` to the requirements in order to have 3.0 support?

**Comment by dosten** [comment]
@WouterJ maybe we can add symfony/security-acl as a suggested package.

**Pull request merged**
