### PR TITLE
[Debug] Fix false-positive "MicroKernelTrait::loadRoutes()" method is considered internal"

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes (fixing and unreleased issue)
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28549
| License       | MIT
| Doc PR        | -

Introduced in #28411
Just a failing test for now.

### CODE REVIEW

**Comment by GuilhemN** [comment]
I've done the fix in https://github.com/symfony/symfony/compare/master...GuilhemN:debug-int, I did not realize it was there since 3.4...
BTW one of test cases should have detected this issue... If it wasn't broken itself 😅

**Comment by nicolas-grekas** [comment]
@GuilhemN thanks a lot for having a look! Actually I don't agree with your patch, the test was fine and its exactly what was added in #28411. The issue is more nasty: we don't deal with trait correctly. This very check you moved up shouldn't exist at all - and we should never inspect method annotations on traits.
#28553 is now ready with the correct fix, see https://github.com/symfony/symfony/pull/28553/files?w=1

**Comment by GuilhemN** [comment]
Oops sorry, I thought I was the one who introduced it and by mistake 😶 I understand now why you've done this change, I will review https://github.com/symfony/symfony/pull/28553 asap :)

**Review by GuilhemN — COMMENTED** [review]
Reviewed and looks all good to me :+1:

**Comment by nicolas-grekas** [comment]
@GuilhemN thanks for the review. Now merged up to master and green :)

**Pull request merged**
