### PR TITLE
Allow non-breaking symfony/polyfill-php80 updates

### PR DESCRIPTION
**Pull request by andrii-pukhalevych**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | ~
| New feature?  | no
| Deprecations? | no

Please also merge it to new branches

### CODE REVIEW

**Comment by derrabus** [comment]
I don't understand this change. What problem are you trying to solve?

**Comment by andrii-pukhalevych** [comment]
It enables to get last updates for `symfony/polyfill-php80`.
In my project I had `polyfill-php80` version 1.22, but after adding `symfony/css-selector` to project, version was donwgraded to 1.16

**Comment by xabbuh** [comment]
`^1.16` allows the installation of `1.22`. So I do not really see how this would change anything. Please run `composer why-not symfony/polyfill-php80:1.22` after adding the CssSelector component to find out why the package was downgraded.

**Comment by andrii-pukhalevych** [comment]
I though it installed 1.16 for me, but now I see its v1.23.1. So sorry for disturbs, closing this PR

**Pull request closed without merging**
