### PR TITLE
[Asset] PathPackage : use parent getUrl Method instead of duplicating code

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Use parent getUrl method instead of duplicating code.

### CODE REVIEW

**Comment by OskarStark** [comment]
You have a typo in your PR title

**Comment by tiecoders** [comment]
Thanks @OskarStark, i fixed the type.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @tiecoders.

**Comment by tiecoders** [comment]
You are welcome @fabpot, I am very happy to contribute on symfony.

**Pull request merged**
