### PR TITLE
fixxed order of usage

### PR DESCRIPTION
**Pull request by OskarStark**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13537 |
| License | MIT |
| Doc PR | - |

[options] command [arguments]

to

command [options] [arguments]

### CODE REVIEW

**Comment by hugohenrique** [comment]
:-1:

**Comment by OskarStark** [comment]
i don't understand your vorting, can you please explain it to me? @hugohenrique 

thx

**Comment by hugohenrique** [comment]
Hi @OskarStark,
Yes, I did not see the need for re-organization in your commit.
Before sending the commit you come to test if it worked?

**Comment by iltar** [comment]
@hugohenrique I don't see the reason of your downvote either, it's not about something broken, it's about a malformed looking message in the console.

@OskarStark Can you fix the issue op in fabbot.io? If you make a PR, you see a big header telling you to view that page when making a contribution, you forgot that. That would have also made the point clear to @hugohenrique 

To me this change seems like a good one, but I don't know if this was done intentional.

**Comment by OskarStark** [comment]
@iltar you are right, it loks malformed to mee, too. I updated the PR desc.

If there were decisions i dont't know, please let me know.

How can i re-trigger the fabpot.io check?

Oskar

**Comment by kix** [comment]
@OskarStark, you should rebase and squash your commits and then force push them into your fork.

**Comment by iltar** [comment]
@OskarStark Push something to your branch (OskarStark:patch-2). This will trigger the git hook that does the checks. If you follow what @kix suggested, it will happen too.

**Comment by OskarStark** [comment]
thank you guys!

**Comment by OskarStark** [comment]
hmm, something went wrong... :(

i forked symfony new and make a clean "patch-2" branch, shall i close and reopen the PR?

sorry :(

**Comment by sstok** [comment]
Yes you need reopen a new PR.

You don't have to fork the repository as GitHub already does this when doing a fast file editing.
You can just edit the file in the created branch creating multiple commits, the maintainers can squash can squash all the commits into one when merging.

But for future its best to learn how to use Git the correct way as will save allot of hassle :)
http://symfony.com/doc/current/contributing/code/patches.html

**Comment by OskarStark** [comment]
duplicate of #13545

**Pull request closed without merging**
