### PR TITLE
[DX][Routing] Display file which contain deprecated option

### PR DESCRIPTION
**Pull request by Koc**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | waiting |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Tobion** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by aitboudad** [comment]
:+1:

**Comment by Tobion** [comment]
Thank you @Koc.

**Pull request merged**
