### PR TITLE
[Cache] Handle serialization failures for Memcached

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Fixes two issues with serialization + memcached: with the memcached extension, the default serializer is automatically selected as igbinary when possible, native php otherwise. That creates obvious migration/portability issues (ie just installing igbinary wipes out the value of your cache.)

Then, handling unserializing failures (esp. "php_incomplete_class") is a paramount feature of the component. You must be able to deal with migrating you code base without being blocked by some legacy serialized data.

### CODE REVIEW

**Comment by robfrawley** [comment]
Does this make the `php` serializer default now?! Do we really need to force this default for users, especially to an inferior serialization method? If people want portability and the environment's they deploy to differ, they can already explicitly set whatever serializer they want, right?

**Comment by nicolas-grekas** [comment]
So, what would be your stand on #19895?

**Comment by robfrawley** [comment]
Accidentally hit delete when editing my original message; here it is again:

> Does this make the php serializer default now?! Do we really need to force this default for users, especially to an inferior serialization method? If people want portability and the environment's they deploy to differ, they can already explicitly set whatever serializer they want, right?

I think my initial reaction was an uneducated gut-reaction without fully understooding the intention of this PR; if your intention is https://github.com/symfony/symfony/issues/19895#issuecomment-317005709, then I'm 100% in agreeance.

**Comment by nicolas-grekas** [comment]
My goal with this PR is to have a predictable, thus safe, default behavior. :)

**Review by fabpot — APPROVED** [review]
I would merge this as a bug fix in 3.3 instead. Wiping the cache should never be an issue (should probably be done anyway on a new deploy).

**Comment by nicolas-grekas** [comment]
Rebased to target 3.3

**Pull request merged**
