### PR TITLE
Dump & die function

### PR DESCRIPTION
**Pull request by gragio**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by stof** [comment]
New features are *never* added in maintenance branch.

And this feature has already been rejected multiple times in the past.

**Comment by stloyd** [comment]
Looks like duplicate of at least #13657, #17267 & #19096.

**Comment by gragio** [comment]
Why? Is it too simply?

https://laravel.com/docs/5.6/helpers#method-dd

**Comment by curry684** [comment]
https://github.com/symfony/symfony/pull/13657#comment-73878638

**Comment by gragio** [comment]
I think that is it an added value. Otherwise why was this feature requested multiple times?

**Comment by curry684** [comment]
Count all the people shooting down those 4 requests and the lack of support for them from others :wink:

**Comment by gragio** [comment]
@curry684 
I'm sorry, I couldn't imagine that this feature can disturb the workflow of all these people 😉

**Comment by curry684** [comment]
It's code. It has to be maintained. It has to be documented. It's an attack vector. 

*"Code is not done when there's nothing left to add, but when there's nothing left to take away"*

Now convenience functions are in themselves not necessarily wrong, assuming they're covering the 80+% use case (technically it becomes a [facade](https://en.wikipedia.org/wiki/Facade_pattern) then). In this case it most certainly doesn't, I can't remember typing `die` after a `dump` call more than a handful of times in the past years, because there's never a reason to - the dump shows up in the profiler toolbar, or in the template rendered, or on the command line. What's the added value of dying except in the handful of cases where you actively need to avoid subsequent code being executed based on the bug you're fixing?

**Comment by chalasr** [comment]
Still -1 for me.

**Comment by xabbuh** [comment]
👎 for me too. I am closing here as this was already rejected in the past and the core team still isn't convinced about the feature.

**Comment by nicolas-grekas** [comment]
For reference, this is being reconsidered in #26970.

**Pull request closed without merging**
