### PR TITLE
[SecurityBundle] add missing logout_on_user_change options

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
I am just a bit confused that this did not fail earlier.

**Review by chalasr — APPROVED** [review]
Me too 🤔

**Comment by chalasr** [comment]
Good catch, thanks @xabbuh.

**Comment by dunglas** [comment]
This is painful when you when to support both <= 3.4 (where the option doesn't exist at all) and >=3.4 (where it's mandatory to set the option).

**Comment by chalasr** [comment]
@dunglas I know :/ but it's the only way we found to fix an important flaw in 4.0 (see https://github.com/symfony/symfony/pull/23882)

**Comment by dunglas** [comment]
Is it possible to enable this flag in PHP (to do it using feature detection)?

**Comment by dunglas** [comment]
Here is a workaround: https://github.com/api-platform/core/pull/1566/files

**Pull request merged**
