### PR TITLE
Add missing ID_id validators translation

### PR DESCRIPTION
**Pull request by ikhsan017**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes  
| Fixed tickets | #30170
| License       | MIT
| Doc PR        | 

Add the missing translations for the Indonesian ("id") locale

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@ikhsan017 you did it great! Thanks for this contribution!

The only minor thing to change is that the validation messages must end with a dot, like in the original English content. If you can, please update this pull request to add the dots. Thank you!

**Comment by ikhsan017** [comment]
@javiereguiluz Thanks!

Is it good now?

**Review by javiereguiluz — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@ikhsan017 yes! Thanks a lot for your contribution.

**Comment by fabpot** [comment]
Thank you @ikhsan017.

**Pull request merged**
