### PR TITLE
Expression language evaluate traversable

### PR DESCRIPTION
**Pull request by jokersoft**
| Q             | A
| ------------- | ---
| Branch?       | 3.4+
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

ExpressionLanguage currently only evaluates array. If I would like to pass something like collection of "lazy" objects to evaluate - I could not.
This thing allows to significally improve performance by passing a "lazy" Expressions collection in case you have a lot of "heavy" ones.

### CODE REVIEW

**Comment by jokersoft** [comment]
Sorry for mess in history :)

**Comment by stof** [comment]
-1 for that. The top-level list of variables available in the expression is documented as being an array (it is meant to be an associative array btw).

Adding support for Traversable does not make sense IMO. and this does not improve performance for "lazy" expressions, as you have to turn it into an array anyway in the code (you win lazyness only if you are able to *never* use `iterator_to_array` on it).

And passing a Traversable to the evaluation layer is broken anyway (accessing a variable relies on accessing a key in it, not on looping, and that all what `Traversable` guarantees).

I think you misunderstand what `$values` represent in the ExpressionLanguage.

**Comment by jokersoft** [comment]
@stof It CAN have lazyness.
Let us assume, that we need to evaluate expression:
```
$isEvaluated = $this->expressionLanguage->evaluate($this->expression, $lazyVarCollection);
```

And the LazyVarCollection has a DI, where "resolvers" are actually the "lazy" part in that particular case.
```
class LazyVarCollection extends \ArrayObject
{
    private $resolvers = ['Security' => '@app.expression_syntax.var_provider.security']]; //for example
    /**
     * @var ?bool[]
     */
    private $resolvedProperties = [];

    public function __construct(array $resolvers)
    {
        $this->resolvers = $resolvers;
        $this->resolvedProperties = array_combine(
            array_keys($this->resolvers),
            array_fill(0, count($this->resolvers), null)
        );

        parent::__construct($this->resolvedProperties);
    }

    public function offsetGet($index)
    {
        if (null === $this->resolvedProperties[$index] && array_key_exists($index, $this->resolvers)) {
            $this->offsetSet(
                $index,
                $this->resolvers[$index]->resolve()
            );
        }

        return parent::offsetGet($index);
    }

    public function offsetSet($index, $newval)
    {
        $this->resolvedProperties[$index] = true;
        parent::offsetSet($index, $newval);
    }
}
```
Means, 'Security' will only be "resolved" IF called in some expression.

**Comment by jvasseur** [comment]
@jokersoft but you are doing an `iterator_to_array($values)` in `evaluate` meaning all your values will get resolved as soon as `evaluate` is called.

**Comment by jokersoft** [comment]
@jvasseur 
>but it means you get different values when iterating on your collection and when getting items by key, that looks really strange
True, I just gave a little and a bit weird example of usage.
What I intended to transfer by this PR is a possibility to use this specific ```evaluate``` function in a bit different manner.

**Comment by stof** [comment]
> Again, just an example

no, that a requirement of your PR, as the code inside the evaluation is **never** looping over values, and always accessing it by (meaning that it **cannot** support Traversable, and it works in your own case because your object implements ArrayAccess).

**Comment by jokersoft** [comment]
@stof OK, I just wanted to leave more possibilities, but \ArrayAccess also fine for me. PR updated.

**Pull request closed without merging**
