### PR TITLE
[TwigBridge] Update `main.css` email stylesheet to latest foundation-emails release

### LINKED ISSUE #58309: [TwigBridge] Update `main.css` email stylesheet to latest foundation-emails release
### Symfony version(s) affected

5.4.*

### Description

Current email stylesheet ([`main.css`](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Bridge/Twig/Resources/views/Email/zurb_2/main.css)) is outdated. Update `v2.2.1` (released in 2016) to `v2.4.0` (released in 2022) to get latest bug fixes, etc. 

### How to reproduce

N/A. This is a dependency update.

### Possible Solution

Overwrite `main.css` with latest [foundation-emails.css ](https://github.com/foundation/foundation-emails/blob/v2.4.0/dist/foundation-emails.css) distribution.

### Additional Context

Release details for foundation-emails: https://github.com/foundation/foundation-emails/releases

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58309
| License       | MIT

Current email stylesheet ([main.css](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Bridge/Twig/Resources/views/Email/zurb_2/main.css)) is outdated. Update v2.2.1 (released in 2016) to v2.4.0 (released in 2022) to get latest bug fixes, etc.

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
Their changelog only lists bug fixes and a few new features: https://github.com/foundation/foundation-emails/releases/tag/v2.4.0

So, this seems free of BC breaks and could be safe to merge. Thanks!

**Comment by stof** [comment]
hould we merge that in the 5.4 branch or only in 7.2  ?

**Comment by fabpot** [comment]
I'd rather be on the safe side and merge in 7.2.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @phasdev.

**Pull request merged**
