### PR TITLE
[SecurityBundle] Rename init:acl to acl:init

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by fabpot** [comment]
I'd would prefer that we finally move everything related to ACLs into another bundle that can be moved outside of Symfony core. Probably directly into `symfony/security-acl`

**Comment by ro0NL** [comment]
See https://github.com/symfony/acl-bundle/pull/2 :) but thats needs a update anyway,, so perhaps we can this here.

**Comment by iltar** [comment]
I'll simply do the same changes in that bundle so they remain in sync

**Comment by ro0NL** [comment]
:+1: not sure how this goes.. if the commands stay in core till 4.0 i think the rename makes sense. In the acl bundle we can do the rename instantly i guess, without deprecation.

**Comment by iltar** [comment]
@ro0NL I've simply copied your changes to keep them in sync, the deprecation makes sense as we can release a 4.0 variant of that bundle without problems. As long as people use 3.4 and use the ACL (bundle), they should be able to plug and play without BC breaks

**Review by Simperfit — APPROVED** [review]

**Comment by JasonCoal** [comment]
Thanks for sending!   
  
  
  

  
  

  
  
>

**Comment by chalasr** [comment]
Let's deprecate ACL code and rename it in symfony/acl-bundle directly. See #24318

**Comment by ro0NL** [comment]
Favoring #24318 :)

**Pull request closed without merging**
