### PR TITLE
[DEBUG] FlattenException bugfix #30462

### PR DESCRIPTION
**Pull request by error56**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | yes     
| Deprecations? | no 
| Tests pass?   | n/a    
| Fixed tickets | #30462  
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Looks liek a BC break to me.

**Comment by error56** [comment]
@nicolas-grekas Ok, I changed description :D

**Comment by fabpot** [comment]
@error56 As I mentioned in another PR of yours, we don't do such changes on just one file. In any case, that's a BC break and we never merge BC breaks without an upgrade path. Let's close.

**Comment by error56** [comment]
@fabpot thanks for feedback. I fixed bug and I thought that I can create PR with only 1 file.

**Pull request closed without merging**
