### PR TITLE
[Tests] Use `unset()` instead of nullable properties

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | --
| License       | MIT

Follows
* #52374

### CODE REVIEW

**Comment by xabbuh** [comment]
Why do we have the `tearDown()` method at all. I don't see the real value in unsetting the properties (or setting them to `null`).

**Comment by OskarStark** [comment]
I was thinking the same as we always have the `setUp` method run

**Comment by sstok** [comment]
Properly because garbage collection cannot detect that these references are no longer used? Or does PHPUnit handle this transparently?

**Review by stof — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Changes reverted in 714ca9b24c

**Pull request closed without merging**
