### PR TITLE
[Notifier] Register NotificationDataCollector and NotificationLoggerListener service

### LINKED ISSUE #38009: [Notifier] DataCollector for Notifier component not available
**Symfony version(s) affected**: 5.1.4

**Description**  

For me it currently looks the DataCollector for the `notifier` component is not registered?

**How to reproduce**  

```php
$client->enableProfiler();
$client->request('POST', '/api/...');

$profile = $client->getProfile();
$profile->getCollector('notifier'); // there seems not exist any data collector for notifier component?
```

**Possible Solution**  

Not sure for me it seems like the [NotificationLoggerListener](https://github.com/symfony/symfony/blob/v5.1.4/src/Symfony/Component/Notifier/EventListener/NotificationLoggerListener.php) and [NotificationDataCollector](https://github.com/symfony/symfony/blob/v5.1.4/src/Symfony/Component/Notifier/DataCollector/NotificationDataCollector.php) are never registered, not sure how they should be registered.

### PR DESCRIPTION
**Pull request by jschaedl**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #38009  
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by fabpot — APPROVED** [review]
This should be merged in master as this is a new feature. I did not register it as it was not used. But if we have the profiler's integration in 5.2, that makes sense to register it now.

**Comment by fabpot** [comment]
Can you rebase on master?

**Comment by jschaedl** [comment]
> Can you rebase on master?

Done

**Comment by fabpot** [comment]
Thank you @jschaedl.

**Pull request merged**
