### PR TITLE
[Validator] clarify stringable type annotations

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by DavidBadura** [comment]
In our projects psalm complains that the \Stringable class has not been seen. We fixed it by installing the PHP80 polyfill. Shouldn't you add it as a composer require when using it?

**Comment by nicolas-grekas** [comment]
I considered that but that's not a requirement of the code, so it's not needed. If it's a requirement for you because of the tooling you use, this is legit and then you should add the polyfill.

**Comment by DavidBadura** [comment]
Yes, I was also unsure, but you are right. The code doesn't need it. 👍

**Comment by gsdevme** [comment]
Having these methods return `\Stringable` or `string` makes things a little difficult in userland right now though because, in PHP7.1, PHP7.2, PHP7.3, PHP7.4 you cannot type it.. the RFC didn't include a special type and furthermore there isn't anything in the polyfill. 

This seems to force all existing userland code that consumed any of these methods to remove `string` in favour of mixed. Granted this is mostly caused by static analyzers reading docblocks as gospel and the use of strict_types. 

The userland flow basically is 

1. Symfony (Via docblock) said it's returning a string
2. You type string and strict_types=1 (happy because you have a real type)
3. Symfony change to `string|\Stringable` (docblock)
4. Because you can't union type yet, you have to remove your real type and use a docblock of `string|\Stringer` 
5. PHP 8 is released
6. You can revisit that code that update the docblock for a real union type

Is this the migration path for this? the polyfill while it fast-forwards the feature doesnt give the full benefit because we dont have union types :(

**Comment by gsdevme** [comment]
further to my comments, I can see some of this discussion did happen on the RFC 

> A virtual "stringable" type (that would be similar to "iterable)" would,
IMHO, be of a bigger benefit if it is to denote the fact that "a variable
can be transformed to a string".

> As it is presented, Stringable alone seems of very little use as compared to union like "string|Stringable", so using the polyfill in a version of PHP that does not support union does not seem to make sense.

I guess my userland code is living through this scenario right now as described by Patrick ALLAERT 

https://externals.io/message/108539#108545

**Comment by nicolas-grekas** [comment]
> Symfony change to string|\Stringable (docblock)

This has always been `string|object` with a comment telling "stringable object",
which means there is nothing new here, PHP7.* cannot use any native types before PHP8. `stringable` vs `string|Stringable` would also make no difference in this regard since both would be shipped by PHP8. PHP7.* can not use `string|Stringable` to accurately tell this. That's much better than "`string|object` with a comment".

**Comment by gsdevme** [comment]
> This has always been string|object with a comment telling "stringable object",

I'm not totally sure I follow? I don't see `string|object`, its explicitly saying `string` (and string only) are you saying implicitly it was `string|object`? 

Screenshot 2020-05-12 at 14 02 25

In regard to the userland problem steps 1-6, is that the expectation here? I can see some of this discussion bleeds into the RFC but from consumption of this interface, it seems that is the expected thing here. That is to bounce between typing string then no type then php8's union type?

**Comment by nicolas-grekas** [comment]
That specific PR fixes wrong annotations you're right. They should have been using `string|object` in the first place.

See https://github.com/symfony/symfony/pull/31083 for background on this specific issue/PR.

See e.g. https://github.com/symfony/symfony/pull/36056 for what I had in mind.

**Pull request merged**
