### PR TITLE
[WebProfilerBundle] bug #15811 use of twig deprecated sameas test

### PR DESCRIPTION
**Pull request by ctrl-f5**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15811 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by stof** [comment]
:+1: (this usage of the deprecated filter was reintroduced by the new design)

**Comment by javiereguiluz** [comment]
:+1:

**Comment by ctrl-f5** [comment]
The failed tests seem to be unrelated to the PR, what's the procedure here?

**Comment by fabpot** [comment]
Thank you @ctrl-f5.

**Pull request merged**
