### PR TITLE
[Routing] fix trailing slash redirection

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29363
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by jimmycleuren** [comment]
Hm, this does not seem to fix the issue for me.

Btw, what is the easiest/best way to check this ? I manually copy/pasted your changes in my vendor folder now.

**Comment by nicolas-grekas** [comment]
Now that it's merged, you can require `~4.1@dev` I think. Copy/pasting in vendor works also.
About your issue, without a reproducer, I'm can't to anything I'm afraid.
I think you have a route earlier in the list that takes precedence. Is it legit or not? I can't tell without having it :)

**Comment by nicolas-grekas** [comment]
any reproducer?

**Comment by jimmycleuren** [comment]
I've created a demo app to reproduce the issue. If you try to access /user/ or /admin/, you'll get the error while those routes are ok according to debug:router.

https://github.com/jimmycleuren/routing-issue

**Comment by nicolas-grekas** [comment]
@jimmycleuren thanks understood, I'm on it (#29380 fixes it but it still not finished)

**Pull request merged**
