### PR TITLE
Convert switch cases to match expression

### PR DESCRIPTION
**Pull request by tigitz**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | -
| License       | MIT
| Doc PR        | 

Continuation of https://github.com/symfony/symfony/pull/45433 using [rector rule ](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#changeswitchtomatchrector)

@fancyweb friendly ping as you've worked on it previously.

### CODE REVIEW

**Review by wouterj — DISMISSED** [review]
Imho, only the change in `src/Symfony/Component/Serializer/Normalizer/UidNormalizer.php` should be kept.

Changes in existing code increases maintenance (we have to review & merge it, make sure it doesn't break a single thing in a release, fix merge conflicts when upmerging older branches, etc.). As such they must provide value.

For a `match`, this value is the fact that is an expression - unlike `switch`. So imho, we should only change `switch` statements that are used as expression (which is only the one in the Serializer component). This also seems to have been the case with the previous PR introducing most `match` expressions to the code base.

**Comment by tigitz** [comment]
@wouterj I understand your POV, however to me it brings value in code readability but also reliability since match is a strict comparison. But you obviously know better than me if it's worth it as I don't realize the impact of the increased maintenance.

If that's ok with you I'll let other core members confirm your stance and make the appropriate modifications. Thanks.

**Comment by nicolas-grekas** [comment]
Personally I find the code more readable when using match. The change is fine to me.

**Review by chalasr — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @tigitz.

**Pull request merged**
