### PR TITLE
declare types in array_map callbacks

### PR DESCRIPTION
**Pull request by DQNEO**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

This is a continuation of https://github.com/symfony/symfony/pull/26821

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by xabbuh — CHANGES_REQUESTED** [review]
Apparently tests do fail since we removed the `RoleInterface` in Symfony 4.

**Comment by nicolas-grekas** [comment]
These failures perfectly illustrate what I was anticipating inWe must be very careful when doing such changes. In fact, should revert the added Role type hint from #26821?

**Comment by DQNEO** [comment]
OK I'll revert the RoleInterface addition. 
And also make a PR to remove Role from  #26821.

**Comment by nicolas-grekas** [comment]
>  Oh, what is wrong with #26821 ? Role type is not deprecated.

Right, but there is nothing enforcing that a Role object is actually provided here. People could play duck typing, isn't it?

**Comment by DQNEO** [comment]
well, that depends on how strict people think `@return` (like `@return Role[] `  in RoleHierarchyInterface) is.
I regarded `@return` as equivalent to the "return type declaration". 
But as you say, some users may ignore it and could do duck typing.
So I'll eliminate the `Role` declaration.

Sorry for bothering you all and thank you for the feedback!

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Should be merged in master, not 3.4.

**Comment by DQNEO** [comment]
Sure. I've changed the target branch to master.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @DQNEO.

**Pull request merged**
