### PR TITLE
fixed a test that do not pass on a Mac

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Branch? | master (test did not exist before) |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by fabpot** [comment]
Note that this does not change the test at all, just that the order of the arrays to compare are not the same on a Mac, so the assertion fails.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by xabbuh** [comment]
👍

**Comment by nicolas-grekas** [comment]
Thank you @fabpot.

**Pull request merged**
