### PR TITLE
[Form] [DateType] Bugfix placeholder DateType widget single_text

### PR DESCRIPTION
**Pull request by Thorry84**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14860 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by webmozart** [comment]
Hi @Thorry84, thank you for creating this issue! Your change is correct. Nevertheless I wonder what the benefit is for you? When "widget" is "single_text", the placeholder is currently not passed to the view, so the change doesn't seem to make any difference to me.

**Comment by Thorry84** [comment]
Hi @webmozart 

Was this changed in the default form theme? Because I was using the form_div_layout form theme combined with my own templates for design purposes.

Maybe there was a mistake in my template (which I've been using for some years) which caused the Array to string conversion notice. So it seems the placeholder is passed. I've since modified my template to pass an empty string placeholder, which takes care of the notice. But I thought I would create an issue + pull request to fix it at the source so to speak.

**Comment by webmozart** [comment]
I see. Since placeholders are not supported for any other type but choice, I'll close this for now. Once we implement placeholders for these types, we can also do this fix. Thanks! :)

**Comment by Thorry84** [comment]
I think I know where the confusion comes from. When I think of a placeholder I think of the HTML placeholder attribute http://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#the-placeholder-attribute
Some years ago I added a form extension to make it easier to add placeholders to all forms, this extension simply takes the form option "placeholder" and places it into "attr". The default Symfony form theme (form_div_layout.html.twig) already supports doing this very well (it has a special case for title and placeholder to make sure it's translated).

Now placeholder is also a special option for the choice widget to give it's empty selection some kind of title, the name "placeholder" is poorly chosen since it has nothing to do with the HTML placeholder. It is true what you say about the option placeholder only being supported for the choice widget, but using the placeholder in the view seems to be very common since it's included in the default form theme.

IMHO the patch should be applied, even though the code works in the default configuration it seems to break easily and depend on the formtype ignoring the parameter which can change in the future. Also I don't see any downside to applying the patch?

Ofcourse it's your decision, the problem is simply fixed without applying this patch, but it feels like a dirty workaround to me.

Thanks :)

**Pull request closed without merging**
