### PR TITLE
[Routing] fix route loading with wildcard, but dir or file is empty

### PR DESCRIPTION
**Pull request by gseidel**
| Q             | A
| ------------- | ---
| Branch?       |  4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | no ticket i see so far
| License       | MIT

In my route config i have something like:

```yaml
empty_wildcard:
    resource: ../controller/empty_wildcard/*
    prefix: /empty_wildcard
```

But ``empty_wildcard`` is empty or has no route configured.

So i had this error:

``Call to a member function addPrefix() on null``

This PR take care if no route is configured, there will be no error.

### CODE REVIEW

**Comment by Tobion** [comment]
As a bug fix it needs to be opened against 3.4

**Comment by Tobion** [comment]
Also the XmlFileLoader would need the same bug fix.

**Review by nicolas-grekas — APPROVED** [review]
(I made some changes while merging)

**Comment by nicolas-grekas** [comment]
Thank you @gseidel.

**Comment by nicolas-grekas** [comment]
Applied on 3.4 in a54ecb0fae

**Pull request merged**
