### PR TITLE
[FrameworkBundle] Add a controller to send simple HTTP responses

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | todo

This PR adds a new built-in controller, similar to `TemplateController` and `RedirectController`, allowing to send simple HTTP response without having to write a custom controller:

```yaml
# config/routes.yaml
login:
  path: /my-page
  controller: Symfony\Bundle\FrameworkBundle\Controller\SimpleController
  defaults:
    content: 'A simple web page'
```

This is especially useful when dealing with the security system, here is a fully working example of a JSON-based login endpoint:

```yaml
# config/routes.yaml
login:
  path: /login
  methods: POST
  controller: Symfony\Bundle\FrameworkBundle\Controller\SimpleController
  defaults:
    content: '{"status": "success"}'
    _format: json
    private: true
```

```yaml
# config/packages/security.yaml
security:
    firewalls:
        main:
            anonymous: true
            json_login:
                check_path: /login
```

It can also be useful for the following use cases:

* Health check URL for Kubernetes / Nagios / whatever returning a 200 OK and a predefined string
* Secret URL returning a token proving you're the owner of a domain (Google Analytics validation for instance)

### CODE REVIEW

**Comment by HeahDude** [comment]
Wow! I can add this to #30501 <3, WDYT?

**Comment by dunglas** [comment]
@HeahDude while writing the PR description, I was telling myself that the full namespaces where not user friendly! Your PR looks like the missing part, it would be awesome if you add support for this new controller!

**Comment by javiereguiluz** [comment]
Two quick questions:

* Can't you solve this today with a Template controller that renders `templates/security/login_success.json.twig` and contains `{"status": "success"}` ?
* Apart from this JSON login use case, can you imagine any other common use case?

Thanks.

**Comment by dunglas** [comment]
@javiereguiluz 

> Can't you solve this today with a Template controller

It creates a dependency to Twig (not wanted in case of an API), and require the user to create one extra file.

> Apart from this JSON login use case, can you imagine any other common use case?

I think that's a common use case:

* Kubernetes / Nagios / whatever health checks returning a 200 OK and a predefined string
* Secret URL returning a key to validate you're the owner of a domain (Google Analytics validation for instance)

**Comment by javiereguiluz** [comment]
If this is accepted ... I suggest to rename `SimpleController` as `ContentController` ... because this is a controller that returns the given content as its response. Also ... the shortcut would be called `content`, so it'd be consistent.

**Comment by HeahDude** [comment]
What about `RawContentController`?

**Comment by nicolas-grekas** [comment]
another one: `StaticController` )

**Comment by dunglas** [comment]
👍 for StaticController

**Comment by lyrixx** [comment]
For what it worth, I don't really like it because I like when everything is declared in one place. 
With this, there will be some "controllers" in the `routing.yml` and others in `App\Controller\*`

That why I even do this for "security controller": 

```php
/**
 * @Route("/logout", name="logout")
 */
public function logout()
{
    throw new \BadMethodCallException('The security layer should handle this route.');
}
```

**Comment by dunglas** [comment]
@lyrixx your example doesn't work for `json_login`.

**Comment by lyrixx** [comment]
@dunglas This particular example is not really related with your use case. It's just an explanation on why I don't like it.

About your exemple, did you know you can (should?) use route name in the security bundle? instead of `               check_path: /login` you can use `check_path: login`

**Comment by pimolo** [comment]
I'm not convinced about the DX improvement, it doesn't bring much imo, but a new way to do something we can already do easily and quickly, with some PHP code that every newcomer in Symfony can understand.

**Comment by dunglas** [comment]
@lyrixx yes but I've just copied the docs :) Maybe should we update it.

**Comment by ktherage** [comment]
Hi, i've just a question on it. 

Does it is a kind of upgrade of  `FrameworkBundle:Template:template`/`Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction`?

If it is, IMO this controller (`FrameworkBundle:Template:template`/`Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction`) might be renamed to StaticController because they are pretty similar or make it an implementation of the new StaticController.

What do you think about that ?

**Comment by fabpot** [comment]
Not convinced this is that useful.

**Comment by chalasr** [comment]
"

**Comment by chalasr** [comment]
Sorry for the misclick :)
About the described use case, the right way to set a success response on a `json_login` listener remains to create an `AuthenticationSuccessHandlerInterface` implementation and set it as `success_handler`. Although it looks "simpler", I think it would be confusing to document this feature as such, and could lead to people handling more security stuff in controllers which I recommend to avoid as it means going "outside" of the security system, potentially skipping some important security events or (worse) creating security holes more easily.

**Comment by fabpot** [comment]
Let's close.

**Pull request closed without merging**
