### PR TITLE
[DependencyInjection] Enable alias for service_container

### PR DESCRIPTION
**Pull request by hason**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
Is this related to #17910 and #17915?

**Comment by hason** [comment]
@xabbuh No

At present, ``ReplaceAliasByActualDefinitionPass`` class is coupled with [configuration](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Bundle/FrameworkBundle/Resources/config/services.xml#L45) in FrameworkBundle. And that is the problem.

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @hason.

**Pull request merged**
