### PR TITLE
let Travis builds fail when PHP 7 jobs fail

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by Tobion** [comment]
:-1: nightly is not stable yet. why would we depend on it?

**Comment by xabbuh** [comment]
Now, that we are at a point where our tests are passing on PHP 7, I think it's a good idea (especially because it isn't stable yet) for two reasons:

1. We notice very early when our code breaks in case that some PHP behaviour changes intentionally. Hence, we can react fast and adapt the Symfony code to be compatible again (we can decide to allow failures again if we notice that it will take us some time to make the needed changes).

1. If the code breaks because of a regression in PHP itself, we will be able to report them as soon as possible to the PHP devs (and again, we could revert this change again if fixing PHP would take some time).

I believe that we wouldn't notice failures (regardless of the reason for it) really soon if we were suppose to check the build log of passed Travis builds.

**Comment by Tobion** [comment]
If it does fail too often because of unstable php I'm ok with it.

**Comment by nicolas-grekas** [comment]
I also think it's too early to enforce this.

**Comment by nicolas-grekas** [comment]
Hum, we're now 3 days after, the time is has come :)
Rethinking about it, I'd be :+1: for this reason: ZF 2.4 already communicates on being PHP7 compatible. That means the guy from Zend will ensure that they do not break anything anymore.
We need to be able to communicate on 2.7 being PHP7 ready.

**Comment by xabbuh** [comment]
Actually, I was thinking about closing this as we are actually not yet where I thought when opening this PR (see #14086). :)

**Comment by stof** [comment]
@nicolas-grekas you could start debugging the Debug and VarDumper tests on PHP7 then :smile:

**Comment by nicolas-grekas** [comment]
I was just looking at them :)

**Comment by nicolas-grekas** [comment]
@xabbuh can you please rebase? We're almost ready to merge this one!

**Comment by xabbuh** [comment]
Ready to go.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
