### PR TITLE
Fix the expected result of the PhpFileLoaderTest

### PR DESCRIPTION
**Pull request by DanielRuf**
| Q             | A
| ------------- | ---
| Branch?       | master for features
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

The CI is currently failing due to changes in the `PhpFileLoaderTest` assertion.
This PR tries to fix it.

### CODE REVIEW

**Comment by DanielRuf** [comment]
I think we can also migrate to Travis CI for testing on Windows as AppVeyor seems to be still unstable.

**Comment by xabbuh** [comment]
Thank you for proposing. But this was fixed in the meantime merging #29886.

**Comment by DanielRuf** [comment]
Oh ok, thanks for the info.
But do you know why the CI still failed on some jobs?

**Comment by DanielRuf** [comment]
At least master is green now.
https://travis-ci.org/symfony/symfony/builds/479738574?utm_source=github_status&utm_medium=notification

**Pull request closed without merging**
