### PR TITLE
[Filesystem] Added additional check for temporary file existence on cleanup step

### PR DESCRIPTION
**Pull request by gechetspr**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | #39235
| License       | MIT
| Doc PR        | N/A

Added additional file existing check before removing temporary file in `Filesystem::dumpFile()` method.

### CODE REVIEW

**Comment by gechetspr** [comment]
https://github.com/symfony/symfony/issues/39235

**Comment by derrabus** [comment]
Can you please rebase your change on the *lowest maintained* branch the problem occurs on? The linked issue suggests that the problem happens on 5.1, so we should at least fix it on 5.1. If it happens on 4.4 as well, we need to fix it on 4.4.

**Comment by gechetspr** [comment]
I'll reopen a new one, sorry

**Comment by jderusse** [comment]
This should target branch `4.4` as it has been introduced by #39059

**Comment by gechetspr** [comment]
https://github.com/symfony/symfony/pull/39243

**Pull request closed without merging**
