### PR TITLE
[Serializer] AbstractObjectNormalizer: be sure that isAllowedAttribute is called

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Please merge before the release of 3.1 (potential bug fix)

### CODE REVIEW

**Comment by xabbuh** [comment]
@dunglas So this is meant to be merged into the `3.1` branch?

**Comment by dunglas** [comment]
Yes

**Comment by fabpot** [comment]
Merging as I'd like to do RC1 today. A test can/should be added later on.

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request closed without merging**
