### PR TITLE
[Messenger] Add `psr/cache` on Messenger's dependencies

### PR DESCRIPTION
**Pull request by sroze**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #30754 
| License       | MIT
| Doc PR        | ø

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
It it really a mandatory requirement? Or just something you need if you use the related features?
2nd choice means there is not need to do this.

**Comment by fabpot** [comment]
@nicolas-grekas is right.

**Comment by sroze** [comment]
@nicolas-grekas the way we merged #30754 means that it's a technical requirement but it's a good shot actually.

**Comment by nicolas-grekas** [comment]
Not unless you use `StopWorkersCommand`, which you don't have to.
For require-dev if we have tests.

**Comment by sroze** [comment]
Moved to `require-dev`, thanks!

**Review by chalasr — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @sroze.

**Pull request merged**
