### PR TITLE
[VarDumper] Fix PHP7 type-hints compat

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
can you add a test for PHP 7 dumping a parameter with a scalar typehint to prevent regressions ?

**Comment by nicolas-grekas** [comment]
test added

**Comment by Tobion** [comment]
:+1:

**Comment by Tobion** [comment]
Thanks for fixing this bug @nicolas-grekas.

**Pull request merged**
