### PR TITLE
[HttpKernel] Don't cache "not-fresh" state

### LINKED ISSUE #34567: [4.4] Tests slow after updating to 4.4
**Symfony version(s) affected**: 4.4

Somehow our testsuite became extremely slow after updating to 4.4. It's a regular API platform setup, using hautelook fixtures. So DB is reloaded on every test.

In the `var/cache/test` it seems to boot/cache a compiled container container *per testcase*. If i abort after first testcase, and then restart the testsuite it seems to pick up the existing container.

Moreover, the behavior is exposed using:

```
# FAST
rm -rf var/cache/test
bin/phpunit

# SLOW
rm -rf var/cache/test
bin/console c:c -e test
bin/phpunit

# ALSO SLOW
rm -rf var/cache/test
bin/console c:c --no-warmup -e test
bin/phpunit
```

Im not sure where to look for now, hints welcome :) i've updated all recipes etc. so everything is "latest 4.4".

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34567
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by Kocal** [comment]
It fixed the issue, thanks!

**Review by ro0NL — APPROVED** [review]
same :+1:

**Comment by acasademont** [comment]
I'd appreciate 4.4.1 could be tagged as soon as this patch is merged 🙏

**Review by acasademont — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by stof** [comment]
@nicolas-grekas shouldn't we also mark the cache as fresh after we rebuild it ?

**Comment by nicolas-grekas** [comment]
@stof I considered this but thought it was not needed - this would only save one extra freshness check - with little to no perf benefit.

**Pull request merged**
