### PR TITLE
[Messenger] add TransportMessageIdStamp to RedisSender

### PR DESCRIPTION
**Pull request by GaryPEGEOT**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by fabpot** [comment]
That's a new feature :)

**Comment by GaryPEGEOT** [comment]
> That's a new feature :)

Worth a shot :smile: ! I've changed the target branch

**Review by nicolas-grekas — COMMENTED** [review]
LGTM, but there is a failure to fix in the CI

**Comment by GaryPEGEOT** [comment]
@nicolas-grekas fixed!

**Comment by nicolas-grekas** [comment]
Thank you @GaryPEGEOT.

**Pull request merged**
