### PR TITLE
[FrameworkBundle][TwigBundle] add changed debug command names to upgrade file

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Thanks to @timglabisch for noticing this in https://github.com/symfony/symfony/pull/11627#issuecomment-66521130.

### CODE REVIEW

**Comment by aitboudad** [comment]
:+1: would you add [lint commands](#14317) too ?

**Comment by xabbuh** [comment]
@aitboudad done

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
