### PR TITLE
[Fabbot] Add `global_namespace_import` PHPCSFixer rule

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

As suggested in https://github.com/symfony/symfony/pull/47709#discussion_r982428553

### CODE REVIEW

**Comment by stof** [comment]
Isn't this already part of the `@Symfony` or `@Symfony:risky` rulesets ? This is a rule we have since years in the Symfony coding standards.

**Comment by chalasr** [comment]
Nope https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/ruleSets/Symfony.rst. 
Do you think it should? I tend to think it's fine to enable this one only on the core codebase.

**Comment by welcoMattic** [comment]
It mentioned in https://symfony.com/doc/current/contributing/code/standards.html
> Add a use statement for every class that is not part of the global namespace;

But not applied in https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/ruleSets/Symfony.rst?rgh-link-date=2022-10-26T12%3A10%3A34Z

I think we should fix the rule set instead of the core config

**Comment by chalasr** [comment]
Works for me: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6662

**Pull request closed without merging**
