### PR TITLE
[WebProfilerBundle][4.1] Deny messenger >=4.2

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 4.1 only
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #29378
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

makes sense?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
composer will happily install the previous version of the bundle, so I don't think that works.

**Comment by ro0NL** [comment]
> composer will happily install the previous version of the bundle

in that case there's no messenger integration yet, so nothing to break also

im not sure it's worth the extra complexity just to prevent this issue, but it happens for sure.

**Comment by nicolas-grekas** [comment]
This one can create more wtf than doing nothing IMHO. :-1:

**Comment by ro0NL** [comment]
just to solve a broken template, perhaps you're right :}

**Pull request closed without merging**
