### PR TITLE
[Messenger] consumer name parameter

### PR DESCRIPTION
**Pull request by zorn-v**
| Q             | A
| ------------- | ---
| Branch       | master
| Bug fix      | no
| New feature  | yes
| Deprecations | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

It is a part of https://github.com/symfony/symfony/pull/35128 PR. As mentioned here https://github.com/symfony/symfony/issues/35112 there is missing feature in current `messenger:consume` command for implement supervisor via separate bundle.

Also this option may be usefull if you have "ordered queue" that must run messages only in one process. This command prevent run consumer with same name. 
Also project path is considers
```bash
/project/bin/console messenger:consume --name my-consumer &
/project/bin/console messenger:consume --name my-consumer
# Error "consumer 'my-consumer' already running" will show
/another/project/bin/console messenger:consume --name my-consumer
# Consumer will start
```

Lock component is used under the hood

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. 

I see that this PR gives the consumer/process a name. And you cannot start two consumers/processes with the same name.

However, I dont see that this will fix the root issue. 

>  if you have "ordered queue" that must run messages only in one process. 

There is nothing stopping me from doing: 
```
bin/console messenger:consume async --name foo
bin/console messenger:consume async --name bar
```

--------

I also fail to see how this is a blocker for creating a separate bundle to replicate supervisord config.

**Comment by zorn-v** [comment]
> However, I dont see that this will fix the root issue

I mean accidental start via some supervisor.

> I also fail to see how this is a blocker for creating a separate bundle to replicate supervisord config.

1. `messanger:consume` create a lock that will be released on proccess exit
2. Supervisor check that locks and start/restart `messanger:consume` commands

**Comment by Nyholm** [comment]
Hm. 

I dont believe this is a good idea. It brings zero features to Symfony. I also believe that these locks can be implemented in the third party bundle. The bundle can be responsible that you dont accidentally start two processes. 

I appreciate the implementation though. I think you did a good job adding `null === $this->lockFactory` and the tests.

**Comment by zorn-v** [comment]
> The bundle can be responsible that you dont accidentally start two processes.

But it can not determine if proccess die

**Comment by Nyholm** [comment]
That is the job of Supervisord. :/

Im not super happy with replicating the greatness of Supervisord in Symfony. 
You can work around this by using the [Process component](https://symfony.com/doc/current/components/process.html) to ask the system for what process is running.

**Comment by zorn-v** [comment]
> the greatness of Supervisord

`systemd` is better :wink: 

Imagine that you have customer that did not give you access to server. Every new "queue" you may want to add, you also should ask customer to add new entry for new consumer. Is it no reason to hold that configs in app ?

> You can work around 

But I don't want "workaroud" that may not work sometimes.

> to ask the system for what process is running.

As far I know, process component can not do it

**Comment by zorn-v** [comment]
Well, seems I missing very noticeable method - `Process::isRunning` :smile: 
Now I can create a bundle I think.

**Comment by zorn-v** [comment]
https://github.com/zorn-v/messenger-supervisor-bundle

**Comment by zorn-v** [comment]
One more question - is it possible to access framework bundle configuration (I need messenger config) from another bundle ?
I need it for config validation that bus or/and receivers exists in messenger config

**Comment by zorn-v** [comment]
> Well, seems I missed very noticeable method - Process::isRunning

There is one issue with it (as I tell before "that may not work sometimes") - if you kill main supervisor proccess with `SIGKILL`, it can not shut down consumers. And after restart it will start copies of they.
With locks on `messenger:consumer` side there is not issue coz copies just will not started again as locks already exists.

**Comment by Nyholm** [comment]
My opinion is that the PR should stay closed. 

Try using a forum like stackoverflow for help and support.

**Comment by zorn-v** [comment]
I mean reopen for possible merge in future, not for help. 
No means no; I get it.

**Pull request closed without merging**
