### PR TITLE
Introduce dump_die to directly output result

### PR DESCRIPTION
**Pull request by rvanlaak**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR | https://github.com/symfony/symfony-docs/pull/4988 |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This do not save a single keystroke... What about d() + dd()? I'm not sure others would agree though

**Comment by Rvanlaak** [comment]
Some other helpers would be usefull. Was inspired by the Ladybug Helpers

https://github.com/raulfraile/LadybugBundle#helpers

**Comment by fabpot** [comment]
I don't see a big value in adding more "shortcuts"; it makes things more difficult to learn and more confusing IMO.

**Comment by stof** [comment]
I agree with @fabpot here

**Comment by gaaarfild** [comment]
It makes debugging easier and It's a helper. There is no need to learn it. You can only discover it and be happy.

**Comment by ivoba** [comment]
Uh i just wanted to open a PR for this.
I still think its a useful helper and would save me tons of typing "exit;".

Btw the implementation here wont work, it will show the line of the dump call, which is inside of dump_die.

**Comment by nicolas-grekas** [comment]
For reference, this is being reconsidered in #26970.

**Comment by ivoba** [comment]
nice!
in the meantime i wrote https://github.com/ivoba/dump-die-shortcuts
and https://github.com/ivoba/dump-die
Hopefully obsolete soon :)

**Pull request closed without merging**
