### PR TITLE
[HttpClient] fix checking for recent curl consts

### LINKED ISSUE #42061: [HttpClient] CurlHttpClient throws Undefined constant `CURLOPT_PINNEDPUBLICKEY`
**Symfony version(s) affected**: 5.3, 5.4

**Description**
Some CURL constants could be not defined depending on libcurl version. 
Thus private `CurlHttpClient::validateExtraCurlOptions` throws `Undefined constant "CURLOPT_PINNEDPUBLICKEY"` even though user code doesn't use this constant. https://github.com/symfony/symfony/blob/1fc489f1f08ef60b2453ad71de83bec1e3512542/src/Symfony/Component/HttpClient/CurlHttpClient.php#L519 

For example CURLOPT_PINNEDPUBLICKEY requires `libcurl 7.39.0`

**How to reproduce**

You could try `Centos 7` with `remi PHP`. 

```
PHP 8.0.8
cURL support => enabled
cURL Information => 7.29.0
```

```php
$client = new CurlHttpClient();
$response = $client->request('GET', 'https://download.geonames.org/export/dump/alternatenames/RU.zip', [
    'extra' => [
        'curl' => [
            CURLOPT_MAX_RECV_SPEED_LARGE => 1024
        ]
    ]
]);
var_dump(strlen($response->getContent()));
```

**Possible Solution**
Check that constant is `defined(...)` or add polyfill

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42061
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by derrabus — APPROVED** [review]
Wow, this PR fixes compatibility with libcurl versions older than 7.39.0 which was released in 2014! Enterprise Linux ftw. 🙈

**Comment by stof** [comment]
@derrabus quoted from https://www.php.net/manual/en/curl.requirements.php:

> PHP requires libcurl version 7.10.5 or later.

**Comment by stof** [comment]
based on https://github.com/php/php-src/blob/0b5d371a9c2652c9775d807d29658b59a71848e5/ext/curl/sync-constants.php#L15, that doc seems outdated though. the min version seems to be 7.15.5 now. But that's still very old.

Edit: fixed the doc in https://github.com/php/doc-en/pull/1221

**Comment by derrabus** [comment]
Yeah, I know. But still. 🙈

**Pull request merged**
