### PR TITLE
[Console] remove methods that were needed for PHP 5.3

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | 3.0 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by GromNaN** [comment]
👍 This is acceptable because removed methods are flagged as [`@internal`](http://symfony.com/doc/current/contributing/code/bc.html#using-our-classes).

**Comment by Tobion** [comment]
:+1: 

Status: Reviewed

**Comment by javiereguiluz** [comment]
👍

**Comment by Tobion** [comment]
Thank you @xabbuh.

**Pull request merged**
