### PR TITLE
[FrameworkBundle] Remove `#StandWithUkraine`

### PR DESCRIPTION
**Pull request by BafS**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | #52577
| License       | MIT

Without being too political

- Stand with Ukraine got removed from symfony-cli (https://github.com/symfony-cli/symfony-cli/commit/7b1629faea560cc8b0c917872fae3ca62d13f250)
- There is other wars and conflicts in the world, it's not fair to only have this for Ukraine (why not for Palestine?)

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @BafS.

**Comment by webknjaz** [comment]
Hello, as a Ukrainian, I'm very disappointed in such a disregard to human life.
Such a stance is quite immoral and is a known way of rationalizing the normalization of the ruscist terrorism.

So I'll take a liberty of reminding you what's happening now (posts from my today's feed) that people decide that they live in the world where everything "is fine" and calling out murderers is unacceptable (under the pretense of "neutrality" and whataboutism):
- https://www.linkedin.com/posts/roman-sheremeta-14972a50_the-eu-promised-to-send-one-million-artillery-activity-7146196395010527233-GBFd
- https://www.linkedin.com/posts/roksolanadiachuk_yesterday-ukraine-suffered-from-massive-missile-activity-7146942416443383808-Y_SA
- https://www.linkedin.com/posts/kyivindependent_russia-carried-out-a-mass-strike-against-ugcPost-7147876410051784708-LuE7
- https://www.linkedin.com/posts/sda-98123358_war-day-678-consequences-of-ugcPost-7147851799390056449-4RsY
- https://www.linkedin.com/posts/ros-rosenko-74a56298_ukraine-kyiv-kharkiv-ugcPost-7147861106387070976-TeGG
- https://www.linkedin.com/posts/tetyanaderkach_russiaterroriststate-ugcPost-7147923570709504000-uW7b
- https://www.linkedin.com/posts/ukraineua_russias-attacks-against-ukraine-endanger-ugcPost-7147982790515474432-eE5D
- https://www.linkedin.com/posts/roman-sheremeta-14972a50_a-typical-strategy-used-by-russia-for-russification-activity-7143267118204071942-wRKL
- https://www.linkedin.com/posts/marijnmarkus_nato-ukraine-media-activity-7147909229356478464-BQ1C

This what this PR is helping people to ignore more actively at scale.

**Comment by DavertMik** [comment]
Hey, @fabpot I'm sorry that Russian war is still ongoing and we keep dying which may disappoint symfony users. We will try better next time. Or probably we will die in silence as the world turns away from us.

Btw, this is Kyiv today, 10km from my home and about the same distance from the conference venue we have been at PHP fwdays:

image

**Comment by MaxGraey** [comment]
> it's not fair to only have this for Ukraine (why not for Palestine?)

Why not stand with Israel?

It would be much more consistent if you take into account that you are using language and a runtime created by Andi Gutmans and Zeev Suraski, among others.

**Comment by webknjaz** [comment]
> Why not stand with Israel?

Because the author is swiss?

**Comment by Nyholm** [comment]
I had to lock the conversation for a few minutes to be able to write my answer to try to clear things out. Thank your patience. 

--------

There has been many discussions about "Symfony's official stance" in public and private. The Symfony community is both large and international. We don't want any community member (or non-member) any harm and if we could, then we would end all world conflicts right now. 

This banner was created to show support for Ukraine, but it brings up questions like "why don't you also support Israel? Or Palestine?" There is also a long list of other world conflicts Symfony could potentially show support for too. 

The problem is that we, a group of programmers, are not even nearly knowledgeable enough to have an opinion about any war. Two years ago it seamed easy to support Ukraine and at the time I agreed to add banners like this to our website and tools. But now I believe we made a mistake by doing that... That mistake became painfully obvious when the Israel/Palestine war intensified again a few months back. The war in the middle east is way more complex* and there are no clear side to support. It all "depends" and we, a group of programmers, are way outside our knowledge zone to have an opinion. 

This PR does not mean the conflict is over, it does not mean Symfony has stopped their support. It means that Symfony are unable to make a policy for: 
- When to make an official announcement
- When to make a banner
- How to pick sides

Like Fabien wrote two months ago, [Symfony is about community](https://symfony.com/blog/symfony-is-all-about-its-community). Since we don't want to be a judge of "which conflict is worth supporting/mentioning" or "who is the good-guy here", we treat every conflict equally. 

----------

\* I know Ukraine/Russia war is also complex and has been going on for almost 10 years. 

My point I am trying to make is: Having an option about word conflicts/war is too difficult for Symfony. We are good programmers and we should stick to have opinions on programming. 

------

Note that even I don't know much about world conflicts. And I may have expressed myself poorly in this post. I hope you see the point I am trying to make. I have updated this post to express myself better.

**Comment by rkiyanchuk** [comment]
@Nyholm @BafS This action shows that you are hypocrites with no idea of what is dignity and honor.

You stuck a hashtag on your website not in solidarity with the people of Ukraine who suffered from unprovoked russian military aggression, and not because you stand on the side of truth and justice, but just because it was trendy. And now that the hype subsided, when you realized that sticking hashtags and showing solidarity actually comes with some moral obligations, you run like rats to avoid any kind of responsibility, or even merely a non-purely positive attention. Well, there you have it anyway.

Ukraine still suffers from russian aggression and [has been bombed with hundreds of missiles over the holidays](https://www.kyivpost.com/post/26242), but you feel like continuing showing solidarity with Ukraine may be _inconvenient_ **for you**.

This is a disgusting hypocritical act that shows any of your words and stances are worthless. But this is your choice. Just remember this for the time when you and your people may need support and help due to injustice.

**Comment by danylokos** [comment]
Please refrain from ever using the flag of my country as a mere marketing tool. For you, it may have been a fleeting trend, but for us, it represents a real and ongoing struggle for life and liberty.

**Comment by BafS** [comment]
@rkiyanchuk I don't understand how it is linked with dignity and honor. Those are anyway subjective. Saying it was "unprovoked" is also a point of view unfortunately. It may be immoral, unjustifiable but from the side of Russian it's surely not unprovoked. See how NATO expended.

I'm not pro Russia and I strongly dislike their regime but it's funny that we had this StandWithUkraine banner because it's in Europe, for me it's double standards. We didn't have anything with Syrians, Kurds, Yemeni, Armenia-Azerbaijan, Afghanistan, Tigray War, now Israel-Hamas and there is of course more to it.

It's also interesting to see that many people who tell us that Ukraine is invaded are pro Israel, who are invading the Gaza Strip. Double standards.

As Symfony people said, it was a mistake to have it, it creates more tension in the community (just see this thread) and nothing is black and white. Geopolitic is a complex topic and I don't see why an open source project should pick a side and a conflict when there is many ongoing.

**Comment by rkiyanchuk** [comment]
@BafS 
> I don't understand how it is linked with dignity and honor.

This is exactly the problem, together with your inability to reason. Ukraine is not NATO member and did not decide to expand NATO, yet it's the one attacked. So calling NATO expansion a provocation of russia by Ukraine is inadequate. And some calls for “fairness” in this scenario are ridiculous.

And "double standards" is exactly what you demonstrate by first adding the banner for support of Ukraine, and then removing it, even though nothing had changed in the situation – Ukraine still struggles against russian military aggression.

Your stance of not having any stance is basically equivalent to: you see a known rape victim, you first jump into supporting them, but then as soon as you see another case where it's not as clear **to you** that they had been raped, you opt-out and say _"but I didn't support all the other rape victims before, so how it is fair that I support this one? There are many rapes, and we don't know exact circumstances of all of them, so let's not support rape victims!"_.

Such reasoning seems fine only for people with a complete loss of moral compass. It is sad and disgusting to see. Remember, that if less than 100 years ago the majority of people had the same views, you would be living under Nazi dictatorship right now.

So I'm very glad that most people now have a sense of dignity and ability to reason – it's clear from the votes on this PR. Too bad Symfony leaders are not among them.

**Comment by Nyholm** [comment]
There are many opinions and suggestions what Symfony **should not** do. And there is a clear support for "add back this banner". 

Could I ask for some advice or opinions what Symfony **should do** in this conflict, other conflicts and in a future conflict? Ie, if you were to decide a policy for "how Symfony relates and acts on conflicts", how would that policy look like?

**Comment by BafS** [comment]
> This is exactly the problem, together with your inability to reason.

😄 

> you first jump into supporting them, but then as soon as you see another case where it's not as clear to you that they had been raped

It's absolutely unrelated to this discussion. I always supported Ukraine but I never wanted to see this banner for a framework. People read the news and they don't need to have a banner to change their opinion. We are talking about supporting some conflicts and some not. How do you choose your camp? Do we choose Israel or Palestine? Do you care about other conflicts too? It's a never ending topic.

> it's clear from the votes on this PR

The sample is really low and it could have been shared on a pro Ukrainian chat, it's not clear at all.

> Such reasoning seems fine only for people with a complete loss of moral compass.

That's an opinion. If not having a banner to support Ukraine is a "complete loss of moral compass" I don't know what to tell you but it seems ridiculous to me. Why so Ukraine focused really? Why can Ukraine have the monopoly? Because it's white people in Europe? I find it's morally unfair and really sad to not care about other conflicts, there is a lot of horror in the world and creating hierarchies don't help.

Many Symfony devs support you, I do it too but I'm glad that those banners are removed.

**Comment by danylokos** [comment]
Don't add anything to your website/tool if you aren't sincere about it, so you can ditch it when it becomes inconvenient; It's as straightforward as that.

**Comment by DavertMik** [comment]
@BafS best way would be to keep supporting Ukraine in some other way if possible. Sure, the same message for more than a 1.5 years is already a victory. But probably it should be transformed to still make people feel that the war is ongoing. 

So my suggestion would be following:
* Don't compare conflicts. It sounds with whataboutism. A conflict in one part of the world can't justify another conflict in other part of the world. Don't turn people to statistics. Each conflict have each own stories, values and victims. 
* Support the values you belive in. 
* Stand on your values, transform, communicate.

Also, I'm thankful to symfony community and @fabpot fpr having this message for all this time. This was quite a long period and this was an extraordinary move. Thank you all!

**Comment by BafS** [comment]
@DavertMik thanks for your message, that's refreshing to read.

I don't want to compare conflicts, I actually try to do the opposite. I want to mention them because choosing some conflicts mean choosing what you consider important or not and doing so it's playing with fire. In my opinion choosing to offer space to a specific conflict/country is comparing them, you now have a hierarchy of importance.
I don't see how you could solve this properly. Removing the banner seems to be the most logical thing to do.

Symfony didn't have the "black lifes matter" banner and I don't see this being talked at all (https://github.com/search?q=org%3Asymfony+black+lifes+matter&type=code). I'm sure people would have been upset if it was there and then removed and some would argue that Symfony devs are racist. With Ukraine they just opened the Pandora box. In my opinion we should continue to focus on technical knowledge and code instead of arguing about politics in the Symfony context.

**Comment by DavertMik** [comment]
In case of Ukraine there is a timeline where I would remove the banner. This would be at the moment of signed ceasefire. The war this intesivity can't last for ages. The thing is that it already it went for so long no one could predict.

Sure, you cant wait for all world conflicts to be ended or racism to be eliminated. But this exact conflict has a very forseenable ending: Ukraine defends its independence, democracy, joins EU and NATO. As of now we are not there yet so the support is still needed, as unlike russia we depend on public opinion of people from the democratic world. So this actually have a practical meaning to us.

Also I agree that this was extraordinary step taken by Symfony community and thankful to you. I feel that we are 80% on the way to our victory but last 20% are always the hardest.

**Comment by markwatney2016** [comment]
I really hope such political statements will never be forced on us again in the Symfony community. And please also no rainbow flags and things like that. Focus on programming instead. Thanks.

**Pull request merged**
