### PR TITLE
Update security.he.xlf

### LINKED ISSUE #38744: Missing translations for Hebrew (he)
Hello,

There are some missing translation for Hebrew (he). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.he.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.he.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.he.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.he.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.he.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.he.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by ben29**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38744
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Thank you. 

Im happy with this PR

**Review by derrabus — CHANGES_REQUESTED** [review]
Can you please adjust the PR header and use our template?

https://raw.githubusercontent.com/symfony/symfony/4.4/.github/PULL_REQUEST_TEMPLATE.md

**Comment by Nyholm** [comment]
Done

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @ben29.

**Pull request merged**
