### PR TITLE
[Bridge/PhpUnit] Remove trailing "\n" from ClockMock::microtime(false)

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25050
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by sroze** [comment]
That's a BC break.

**Comment by nicolas-grekas** [comment]
Thank you @joky.

**Comment by nicolas-grekas** [comment]
@sroze it's not: the reference is the native microtime, any divergence from it is a bug. That's a mock, it's optional and doesn't run at runtime.

**Comment by joky** [comment]
@nicolas-grekas you're welcome. It's my first contrib. I'll try to do better next time (correct lower branche, correct commit comment, ...)

**Pull request merged**
