### PR TITLE
[PropertyInfo] Make classes final

### PR DESCRIPTION
**Pull request by GuilhemN**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

The classes of the PropertyInfo component do not provide extension points, so imo it's better to make them final in 4.0.

### CODE REVIEW

**Comment by stof** [comment]
👍 for this

**Comment by xabbuh** [comment]
What about documenting this in the upgrade files?

**Comment by GuilhemN** [comment]
@xabbuh looks like it wasn't done the other times we made classes final too, let's do it :)

**Review by xabbuh — COMMENTED** [review]
:+1:

Status: Reviewed

**Comment by dunglas** [comment]
👍

**Review by dunglas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @GuilhemN.

**Pull request closed without merging**
