### PR TITLE
[TwigBundle] removed deprecated ActionsExtension

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

This removes the `{% render %}` tags which was replaced by the `{{ render }}` function in 2.2.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Given that `{% render %}` will no longer work, the PR table should say `BC breaks? yes`, right?

**Comment by fabpot** [comment]
@javiereguiluz fixed

**Comment by Tobion** [comment]
:+1: but it seems like it is missing the deprecation trigger so far. So I guess renderUri should include a trigger_error in branch 2.7

**Comment by fabpot** [comment]
@Tobion You're right, done in #13408

**Pull request merged**
