### PR TITLE
[DI] Fix method autowiring in ResolveDefinitionTemplatesPass

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

cc @nicolas-grekas

### CODE REVIEW

**Comment by dunglas** [comment]
Should we remove https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/ChildDefinition.php#L142-L148?

**Comment by nicolas-grekas** [comment]
@dunglas `s/setAutowired/setAutowiredMethods`

**Comment by dunglas** [comment]
@nicolas-grekas it's not necessary because we do a merge now.

**Comment by dunglas** [comment]
Switched from a merge to a full replacement.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request merged**
