### PR TITLE
Workaround for HHVM serialize problem -  fix #13288

### LINKED ISSUE #13288: Symfony crash on automatic PHP enviroment switching from HHVM to PHP5-FPM.
I have configured two php environments, one running HHVM 3.4 and a fallback PHP5-FPM 5.5 using NGINX 1.7.

NGINX is used as a proxy and automatically switches the enviroments on server errors 50X.

When I force the fallback an error appears, it is fixed by clearing the caches of symfony.

Here is the error message:

```
ContextErrorException in FilesystemLoader.php line 65: Notice: Object of class Symfony\Bundle\FrameworkBundle\Templating\TemplateReference could not be converted to int

    in FilesystemLoader.php line 65
    at ErrorHandler->handleError('8', 'Object of class Symfony\Bundle\FrameworkBundle\Templating\TemplateReference could not be converted to int', '/var/www/symfony/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Templating/Loader/FilesystemLoader.php', '65', array('template' => object(TemplateReference), 'time' => object(TemplateReference), 'storage' => object(FileStorage))) in FilesystemLoader.php line 65
    at FilesystemLoader->isFresh(object(TemplateReference), object(TemplateReference)) in FileResource.php line 49
    at FileResource->isFresh(object(TemplateReference), '1420557707') in FileResource.php line 49
    at FileResource->isFresh('1420557707') in AsseticResource.php line 38
    at AsseticResource->isFresh('1420557707') in bootstrap.php.cache line 2910
    at ConfigCache->isFresh() in classes.php line 1277
    at Router->getMatcher() in classes.php line 1255
    at Router->matchRequest(object(Request)) in classes.php line 1987
    at RouterListener->onKernelRequest(object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))
    at call_user_func(array(object(RouterListener), 'onKernelRequest'), object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher)) in WrappedListener.php line 59
    at WrappedListener->__invoke(object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher))
    at call_user_func(object(WrappedListener), object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher)) in classes.php line 1776
    at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent)) in classes.php line 1709
    at EventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in classes.php line 1870
    at ContainerAwareEventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in TraceableEventDispatcher.php line 112
    at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in bootstrap.php.cache line 2997
    at HttpKernel->handleRaw(object(Request), '1') in bootstrap.php.cache line 2970
    at HttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 3119
    at ContainerAwareHttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 2364
    at Kernel->handle(object(Request)) in app_dev.php line 28
```

### PR DESCRIPTION
**Pull request by gadelkareem**
HHVM serialize/unserialize behave differently than PHP, issue https://github.com/symfony/symfony/issues/13288

### CODE REVIEW

**Comment by fabpot** [comment]
Is the bug reported to HHVM? I'd prefer the same behavior in HHVM and PHP instead of working around it in Symfony.

**Comment by gadelkareem** [comment]
Yes https://github.com/facebook/hhvm/issues/5698 
I agree, I ran into more problems specially using jms_serializer.

**Comment by fabpot** [comment]
So, I propose to close this as any usage of serialize/unserialize could potentially lead to problems with HHVM. ping @symfony/deciders

**Comment by xabbuh** [comment]
If it's an issue with HHVM, it should rather be fixed there than worked around it in Symfony code.

**Pull request closed without merging**
