### PR TITLE
Fix EOL of text files

### PR DESCRIPTION
**Pull request by mvorisek**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes/CS
| New feature?  |no
| Deprecations? | no
| Tickets       | no
| License       | MIT
| Doc PR        | no

### CODE REVIEW

**Comment by mvorisek** [comment]
both fabbot errors seems false positive

**Review by yceruto — APPROVED** [review]

**Review by chalasr — CHANGES_REQUESTED** [review]
Some tests are broken due to your changes. Can you have a look at Travis failures?

**Comment by Nyholm** [comment]
Thank you for the PR. 

Could you help me understand **why** we need this change?

**Comment by fabpot** [comment]
That breaks tests. Fixtures and output from commands shouldn't be "fixed". Closing as I don't think this is something we need to change.

**Comment by mvorisek** [comment]
@fabpot please reopen, I am working on tests fix, these changes are needed to fix CS implified by strict enviroments which have some strict requirements of text files

**Comment by mvorisek** [comment]
@fabpot please reopen, I will fix tests or add flag to `.gitattributes`

**Comment by fabpot** [comment]
I don't think there is anything to fix here.

**Comment by mvorisek** [comment]
Some dev enviroments/IDEs warn if text files has no EOL. This can be enforced by `.gitattributes`. I can fix this, but I would like to do it in this PR.

**Pull request closed without merging**
