### PR TITLE
[Debug] Reset previous exception handler earlier to prevent infinite loop

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #26438
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by Jean85** [comment]
Appveyor build has some unrelated failures, but also it's failing on my regression test: https://ci.appveyor.com/project/fabpot/symfony/build/1.0.34059#L1515

It's not calling back the third party exception handler... strange!

**Comment by nicolas-grekas** [comment]
For some reason I cannot understand, the integration test fails on Windows (but not locally).
I replaced it by a unit test.

**Comment by Jean85** [comment]
It's now failing on both CI :cry:

**Comment by nicolas-grekas** [comment]
@Jean85 for unrelated reasons, keep cool :)

**Pull request merged**
