### PR TITLE
Deprecate onBind in favor of onSubmit

### PR DESCRIPTION
**Pull request by dosten**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
Do we really need to rename the function ?

If we rename things, it might be worth naming the function according to hat it does rather than according to when it is called btw.

**Comment by dosten** [comment]
@stof I think that topic is for another issue, this PR is for keep consistency with all deprecations of `onBind` methods.

**Comment by stof** [comment]
@dosten This discussion needs to happen before the renaming IMO, to avoid renaming twice.

Btw, your BC layer is not working: if someone extends the class and overwrites the ``bind`` method, the child method will not be called anymore when registering the listener.
Renaming event subscriber methods while keeping a BC layer is hard (most BC layers in renamed event subscriber methods are actually not working properly). This is why I'm not in favor of renaming the method when it does not give much value but creates pain for users

**Comment by dosten** [comment]
Yes, you are right. I will close this.

**Pull request closed without merging**
