### PR TITLE
[Cache] skip APCu in chains when the backend is disabled

### LINKED ISSUE #34962: Misleading warning (?) cache.WARNING: Failed to save key "mystringtags" of type integer.
**Symfony version(s) affected**: 4.4.1

**Description**  
I see this warning in the logs:

```
cache.WARNING: Failed to save key "stream.thiemo_sysnat_e9_v4-publish-1573137262tags" of type integer. {"key":"stream.thiemo_sysnat_e9_v4-publish-1573137262\u0000tags\u0000","exception":null}
```

The real problem is probably (?) that I'm trying to invalidateTags where the tag does not exist, but the warning message is not even close to telling me that.

**How to reproduce**  
I'm using both doctrine ORM and doctrine ODM, and re-using the doctrine ORM cache pool to store ODM result cache manually

```yaml
framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapters:
                    - cache.adapter.array
                    - cache.adapter.apcu
                    - cache.adapter.redis
                tags: true
```

At some point I invalidate tags, but it is possible that the tag has not been created
```php
        $this->doctrineResultCachePool->invalidateTags([
            sprintf('%s-%s-%d', $code, $type, null), // latest version
            sprintf('%s-%s-%d', $code, $type, $revision), // specific revision
        ]);
```

That's when this message shows up.

Interestingly enough I get 4 warnings, two for each tag. Perhaps the tag was in redis, but not in this pod?

**Possible Solution**  
Improved warning message that I've tried to invalidate a tag that does not exist.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34962
| License       | MIT
| Doc PR        | -

I think this should do it.

### CODE REVIEW

**Review by Nyholm — COMMENTED** [review]
I believe this is a hack. A useful hack and most likely exactly what you want. But still. 

We don’t do the same thing if the Redis extension (or Redis lib) is missing.

**Comment by nicolas-grekas** [comment]
The difference is that the availability of the redis backend doesn't vary by runtime.
That's the best I can think of. There must be some runtime code that deals with the situation. Configuration only cannot do anything for us here (for redis it can)

**Review by javiereguiluz — APPROVED** [review]

**Review by Nyholm — APPROVED** [review]
@nicolas-grekas: I said Redis extension/lib not backend. 

I get the argument that this is the only difference between CLI/HTTP. If the Redis extension was missing it would be missing on all runtimes. 

:+1:

**Comment by nicolas-grekas** [comment]
> I said Redis extension/lib not backend.

and I wrote "backend" to mean "extension" :D

The alternative would be to make the ApcuAdapter NOT throw any warning when it's not enabled and on the CLI. But as you explained in one of the issues, there should be some reporting when ApcuAdapter is used directly and it doesn't work at all. In a chain, we can relax this rule - that's what this PR proposes.

Thanks for approving :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
