### PR TITLE
Added support for name on the unit node

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25758
| License       | MIT
| Doc PR        | na

See [unit specification](http://docs.oasis-open.org/xliff/xliff-core/v2.0/os/xliff-core-v2.0-os.html#unit) and [name specification](http://docs.oasis-open.org/xliff/xliff-core/v2.0/os/xliff-core-v2.0-os.html#name)

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Nyholm.

**Comment by Nyholm** [comment]
Thank you for merging

**Comment by axi** [comment]
Any specific reason this hasn't been merge in 3.4 ?

**Comment by Nyholm** [comment]
Excellent question. Yes, there is a reason. 

This was a new feature. 3.4 will not include new features, only bug fixes and security fixes. 

Symfony is using version numbers like x.y.z. X is a major change (can break BC). Y is added features. Z is bug fixes. You can read more about Semver here: https://semver.org/

You can also see Symfonys release process here: https://symfony.com/releases

**Comment by axi** [comment]
Thanks for the answer, I was preparing a PR to report it to 3.4 but it won't be accepted if I understand. We should definitly move to 4.4...

**Pull request closed without merging**
