### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Changes? | <li>- [ ] bugfix</li><li>- [ ] feature</li><li>- [ ] deprecation</li>
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

WDYT?

### CODE REVIEW

**Comment by ro0NL** [comment]
also can we make "Branch" an informational thing? I choose it in git(hub) already isnt it ...

**Comment by wouterj** [comment]
I'm not sure about these changes. The HTML-in-markdown looks much less clear that I'm supposed to enter one of the options. Also, Carson bot and our merge tool currently relies on the table, it looks harder to parse a checklist than the current table.

> also can we make "Branch" an informational thing? I choose it in git(hub) already isnt it ...

You must not forget that you are in the top x% of Symfony contributors/GitHub users :wink: . There are many people that are unfamilar with GitHub and it's pull request system.

**Comment by ro0NL** [comment]
not feeling like bikeshedding it, but i'll defend it once :)

The template is pesky IMHO in terms of UX, i prefer checking over editing. In that sense the checkbox conveys the same as "yes/no"

_Filling in_ the branch as part of QA is redundant IMHO.

Tools can adapt.

**Comment by ro0NL** [comment]
actually leaving the question open cannot be conveyed with a checkbox :D

im afraid this is a rabbit hole :)

**Pull request closed without merging**
