### PR TITLE
add uz validators file

### PR DESCRIPTION
**Pull request by shokhaa**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

add uz validators file

### CODE REVIEW

**Comment by shokhaa** [comment]
when will my pull request be accepted?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @shokhaa.

**Comment by fabpot** [comment]
@shokhaa Can you create another PR to translate the 2 other files that need to be taken into account?

./src/Symfony/Component/Form/Resources/translations/validators.uz.xlf
./src/Symfony/Component/Security/Core/Resources/translations/security.uz.xlf
./src/Symfony/Component/Validator/Resources/translations/validators.uz.xlf

Also, you should do the PR on the 4.4 branch.

**Comment by shokhaa** [comment]
@fabpot ok, I'll do them right now too

**Pull request merged**
