### PR TITLE
[FrameworkBundle][Workflow] Add a way to register a guard expression in the configuration

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

---

Many people already asked for this feature so ... here we go :tada: 

---

Usage:
```yml
            transitions:
                journalist_approval:
                    guard: "is_fully_authenticated() and has_role('ROLE_JOURNALIST') or is_granted('POST_EDIT', subject)"
                    from: wait_for_journalist
                    to: approved_by_journalist
                publish:
                    guard: "subject.isPublic()"
                    from: approved_by_journalist
                    to: published
```

### CODE REVIEW

**Comment by stof** [comment]
third option: do as the SecurityListener in FrameworkExtraBundle: allow expressions, but not by using the ExpressionVoter itself, allowing you to expose ``is_granted`` to call the full-featured access decision logic (for instance using ``is_granted('EDIT', subject)`` to vote on the subject rather than just on ``null``)

Pros:
- very flexible
- easy for simple checks (if you also expose the functions available inside the ExpressionVoter language, as done in `@Security`).
- we can expose additional variables in the expression if needed, as we control it (the workflow name, the transition name, etc... depending on what actually makes sense)
- we can add more workflow-specific functions (a way to check whether another place is also marked, not sure whether it makes sense ?)

I see several cons in your option 2:
- not allowing to vote on an object (the one being marked is a candidate here), or enforcing it depending on the implementation (both ways can have issues, as we need to be able to do both of them)
- not flexible at all when wanting to implement more complex checks, as expressions are not available (not sure why you listed this as a Pro. It is not one IMO). And custom voters don't help much here if there is no access to the subject.

**Comment by lyrixx** [comment]
@stof Thanks. That's very cool. I did not think to do that ;) I will do that !

Just to clarify your point about 2/: I said it's more flexible because in the end you write pure PHP. That's why it is the most flexible solution. Thus you have access to the object in the voter (because the listener pass it to the AuthChecker)

**Comment by stof** [comment]
@lyrixx but forcing to pass it is not always the most flexible. I have voters which explicitly vote on ``null`` and abstain when being asked to vote on an object (because a most specific voter is responsible for it). The RoleVoter accepts anything (it ignores the subject entirely) so it does not hurt to pass it in this case, but it is less flexible.

**Comment by lyrixx** [comment]
I pushed the new version ;) Ready for review.

**Comment by iltar** [comment]
More of a semantic, but why 'guard' instead of 'authorization'?

**Comment by lyrixx** [comment]
@iltar usually people use `guard` for this kind of things. More over the event is named `guard`.

refs: 

* https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html
* https://en.wikipedia.org/wiki/Guard_(computer_science)

Thus, here you can block a transition not only with the security but with, for example, the subject itself. So authorization seems too "security related" to me.

**Comment by iltar** [comment]
The expression seems to be used for authorization, hence I was wondering. Guard sounds fine in this cause though.

**Comment by lyrixx** [comment]
I updated the PR description to add another example where we don't use the security. I guess it's better now.

**Comment by nicolas-grekas** [comment]
In routing, this is called "condition", maybe better and more consistent?

**Comment by lyrixx** [comment]
In that case, it will not be consistent with the workflow. to me, `guard` is better.

**Comment by nicolas-grekas** [comment]
Fabbot is red, and deps=low line also

**Comment by lyrixx** [comment]
@nicolas-grekas Rebase + Fixed tests. Now it's green.

@stof Is it what you had in mind ?

**Comment by lyrixx** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Comment by fduch** [comment]
This functionality (and also other extensions) was implemented in https://github.com/GlobalTradingTechnologies/workflow-extensions-bundle long time ago)

See for example [transition blocking feature](https://github.com/GlobalTradingTechnologies/workflow-extensions-bundle)

**Comment by destillat** [comment]
What about adding guard expressions for [workflow.guard](https://github.com/symfony/symfony/blob/d9c38310f65253e6e47f16615ec0feea73ab4927/src/Symfony/Component/Workflow/Workflow.php#L262) and [workflow.id.guard](https://github.com/symfony/symfony/blob/d9c38310f65253e6e47f16615ec0feea73ab4927/src/Symfony/Component/Workflow/Workflow.php#L263) events too?

**Pull request merged**
