### PR TITLE
fix composer install process, resolves #20032

### LINKED ISSUE #20032: Broken tests in master: Could not scan for classes inside "tests/"
It seems like some commit broke at least the master. If I run `./phpunit` it crashes after installing the packages with:
```
                                                                                              
  [RuntimeException]                                                                          
  Could not scan for classes inside "tests/" which does not appear to be a file nor a folder  
                                                                                              
```

I did a bit of digging and the only reference I found was a classmap option in composer.json from the zip file in the `.phpunit` directory. Sadly I was unable to fix it myself as it keeps overwriting everything.

ping @nicolas-grekas

### PR DESCRIPTION
**Pull request by alcohol**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #20032 |
| License | MIT |
| Doc PR | reference to the documentation PR, if any |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

This looks like the right solution to me.

**Comment by alcohol** [comment]
( •\_•)

That's because...

( •\_•)>⌐■-■ 

it is.

(⌐■_■)

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @alcohol.

**Pull request merged**
