### PR TITLE
[DependencyInjection] Fix return of YamlFileLoader::parseDefaults

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no (or very unlikely)
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

I've messed up the return value of parseDefaults under certain conditions in #21342. Here is the fix... Sorry about that.

### CODE REVIEW

**Comment by xabbuh** [comment]
Didn't any tests fail without these changes?

**Comment by dunglas** [comment]
No because it still returns an array behaving like an empty one (because keys of `$content` are usually service ids or class names and doesn't have any signifiant meaning as a service definition).

It's why it's very unlikely to introduce bugs, but still need to be fixed IMO.

**Comment by nicolas-grekas** [comment]
Thank you @dunglas.

**Comment by stof** [comment]
yeah, the case where the bug would be impacting you is when you have a service named ``tags`` or ``autowire`` 😄

**Pull request merged**
