### PR TITLE
Preserve percent-encoding in URLs when performing redirects in the UrlMatcher

### PR DESCRIPTION
**Pull request by mpdude**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

While investigating #25373, I found that when the *dumped* `UrlMatcher` performs redirections due to missing trailing slashes on URLs, it does so using an url*de*coded URL.

This is wrong, as it may lead to wrong interpretations of URLs upon the next request. For example, think of an URL that contains `%23` in the middle of the path info. Upon redirection, this will be turned into `#` with an obvious effect.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you check the failures please?

**Comment by mpdude** [comment]
fabbot complains about fixtures (`src/Symfony/Component/Routing/Tests/Fixtures/dumper/url_matcher{1,2,3}.php`). Won't fix that, as it would also mean having to change the MatcherDumper.

Will habe a look at the Travis failures as well.

**Comment by mpdude** [comment]
Overall, would it be better to apply `rawurlencode` instead of trying to preserve the URL as- is?

**Comment by mpdude** [comment]
@nicolas-grekas green

**Review by Simperfit — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mpdude.

**Comment by fabpot** [comment]
@mpdude Can you have a look at why the tests are broken on 3.4 (https://travis-ci.org/symfony/symfony/jobs/316592496)? Thanks.

**Comment by nicolas-grekas** [comment]
Tests fixed in 3c67741954b164e30f4621026b53e2aa95d8cd7d

**Pull request closed without merging**
