### PR TITLE
Added note about security issues in issue template

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

This could help people if they are not sure if they should submit a public issue or not.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I moved the templates to https://github.com/symfony/.github/tree/main/.github/ISSUE_TEMPLATE while you were creating this PR :D
I also added a note about security issues.
Thanks :)

**Comment by Nyholm** [comment]
Cool cool. Well done.

**Comment by mynameisbogdan** [comment]
I have to ask, what's the policy if the security issue is regarding an experimental feature/component?

**Comment by wouterj** [comment]
@mynameisbogdan the same as with any other code. The `@experimental` flag only indicates that the BC promise does not yet cover that class/component, but it's 100% within the maintenance promise (and consequently the security policies) of all code in the Symfony organisation.

**Comment by mynameisbogdan** [comment]
@wouterj thank you for clearing that for me. 

and sorry about that earlier, I was treating it as a missing feature.

**Pull request closed without merging**
