### PR TITLE
Improve some URLs

### PR DESCRIPTION
**Pull request by Arman-Hosseini**
| Q             | A
| ------------- | ---
| Branch?       | 3.4 
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | N/A   
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
If we do this, we should do it for the whole codebase. There is no point in making it for some random files (except calling for an undefined amount of follow-ups, which we'd better not.)

**Comment by nicolas-grekas** [comment]
@Arman-Hosseini up for screening the whole codebase? We could also improve links to bug reports, e.g. `https://bugs.php.net/78175` instead of `https://bugs.php.net/bug.php?id=78175`

**Comment by Arman-Hosseini** [comment]
Hi @nicolas-grekas .
I'm ready to do that.
Where to start?

**Comment by nicolas-grekas** [comment]
`grep "https*://" src/` + filter the result :)

**Comment by Arman-Hosseini** [comment]
@nicolas-grekas .
Do I have to commit all the results on the branch of patch-10?

**Comment by nicolas-grekas** [comment]
that would make sense, but do what's easiest for you of course

**Comment by Arman-Hosseini** [comment]
I carefully review all the results and correct them as needed.

**Comment by nicolas-grekas** [comment]
@Arman-Hosseini maybe you forget to push the result? We see no changes here :)

**Comment by Arman-Hosseini** [comment]
@nicolas-grekas I am involved in a project and will be pushing it soon.

**Comment by Arman-Hosseini** [comment]
@nicolas-grekas Do the schema links in the xml file also need to be changed?

**Comment by nicolas-grekas** [comment]
No need to patch xsd, this can have unwanted technical consequences.

**Comment by Arman-Hosseini** [comment]
@nicolas-grekas  Can I change long redirect links?
For example: `http://support.microsoft.com/kb/323308 it's` redirected to `https://support.microsoft.com/en-us/help/323308/internet-explorer-file-downloads-over-ssl-do-not-work-with-the-cache-c`

**Comment by Arman-Hosseini** [comment]
@nicolas-grekas Can I remove www from a link? Even for a link that is ultimately loaded with a www address?
For example: I use `https://zend.com/` and finally it's redirected to `https://www.zend.com/`

**Review by oliverquynh — APPROVED** [review]

**Comment by fabpot** [comment]
@Arman-Hosseini I think using the shortest URL possible is always nice (even if the URL is redirected).

**Comment by nicolas-grekas** [comment]
Thank you @Arman-Hosseini.

**Comment by Arman-Hosseini** [comment]
@nicolas-grekas .
This process had not yet been completed.

**Comment by nicolas-grekas** [comment]
I completed it :)
No need for more updates, that's really minor concern and we already have plenty of PRs.
Thanks!

**Pull request merged**
