### PR TITLE
[Validator] Adds some missing validation messages translations for IT

### PR DESCRIPTION
**Pull request by micheleorselli**

### CODE REVIEW

**Comment by xabbuh** [comment]
Note to merger: This must be merged for Symfony 2.7.

**Comment by Tobion** [comment]
The translations in the Security Core need to be updated equally.

**Comment by micheleorselli** [comment]
@Tobion I can also work on those, do you prefer a separate PR?

**Comment by fabpot** [comment]
same PR is better, thanks

**Comment by micheleorselli** [comment]
It seems to me translations in Security Core are up to date since https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/Resources/translations/security.it.xlf contains all the messages defined in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Security/Core/Resources/translations/security.en.xlf or am I missing something?

**Comment by fabpot** [comment]
Thank you @micheleorselli.

**Pull request closed without merging**
