### PR TITLE
[Security] Strengthen comparison of target_url vs login_path

### PR DESCRIPTION
**Pull request by mrzard**
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18862 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by sstok** [comment]
Looks good to me 👍 

Status: Reviewed

**Comment by ro0NL** [comment]
Not sure on this one.. but shouldn't we consider trailing slash normalization since the router, AFAIK, has some issues with it (#18702)

**Comment by cdesign** [comment]
Minor issue, but there is a type in the test name:

`public function testRefererWithoutParametersHasToBeDifferentThatLoginUrl()`

should be:

`public function testRefererWithoutParametersHasToBeDifferentThanLoginUrl()`

**Comment by mrzard** [comment]
@cdesign Thanks! Fixed. Fixed the original test name too. 

@ro0NL Not very sure how to apply that detection as it is kind of "quirk" of the Router, any pointers? I'd be happy to actually code them.

**Comment by ro0NL** [comment]
@mrzard i think it's a problem we cant fix.. as we cant determine the `login_path` route supports both variants yes or no. Currently how i understand it, it only is supported for imported routes.

I foresee some nasty side effects, but im not sure as i havent tested it, i.e. it needs to be reproduced first to properly document what no to do :-)

**Comment by fabpot** [comment]
Thank you @mrzard.

**Pull request merged**
