### PR TITLE
[Security] Fix for TraceableAuthenticator debug when no Auth

### PR DESCRIPTION
**Pull request by PhilETaylor**
| Q             | A
| ------------- | ---
| Branch?       | 6.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix https://github.com/symfony/symfony/pull/51585#issuecomment-1712828991
| License       | MIT

Fixes regression in PR #51585 and adds unit test

image

### CODE REVIEW

**Review by derrabus — APPROVED** [review]
👍🏻 … once fabbot is happy.

**Comment by PhilETaylor** [comment]
> once fabbot is happy.

Sorry missed that - done now.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @PhilETaylor.

**Comment by PhilETaylor** [comment]
Thanks all - hope you have some time off Sunday evening! :)

**Pull request merged**
