### PR TITLE
Changed one console output style to avoid visual issues

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16257 |
| License | MIT |
| Doc PR | - |

Read [this comment](https://github.com/symfony/symfony/issues/16257#issuecomment-149205104) for the rationale behind this change.

### CODE REVIEW

**Comment by Tobion** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by OskarStark** [comment]
:+1:

**Comment by aitboudad** [comment]
selection_003

:+1:

**Comment by stof** [comment]
:+1:

**Comment by Tobion** [comment]
Thank you @javiereguiluz.

**Pull request merged**
