### PR TITLE
[Intl] [Workflow] fixes English grammar typos

### PR DESCRIPTION
**Pull request by hhamon**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | ~
| License       | MIT
| Doc PR        | ~

Also related to #34604

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]

**Comment by stof** [comment]
Please open a PR against the 3.4 branch (oldest supported branch) fixing all occurrences there. Then, we'll need additional PRs for newer branches (4.3 and then 4.4) only for phpdoc which does not exist in older versions (which might mean we don't need the PR at all).

**Comment by hhamon** [comment]
@stof yes I'll open a PR against 3.4 to fix the other occurrences. This class was introduced in Symfony 4.3 so this is the reason why I isolated the patch in this PR.

**Comment by lyrixx** [comment]
And that's why I :+1: the PR

**Review by darielopper — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Good catch, thanks @hhamon.

**Pull request merged**
