### PR TITLE
[Serializer] minor: fix comment

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |
| Doc PR | n/a |

Fix bad copy/paste from the Validator component.

### CODE REVIEW

**Comment by cystbear** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by umpirsky** [comment]
:+1:

**Comment by fabpot** [comment]
Good catch, thanks @dunglas.

**Pull request merged**
