### PR TITLE
[OptionsResolver] replaced some exception messages

### PR DESCRIPTION
**Pull request by issei-m**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

In accordance with renaming of methods.

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by stof** [comment]
Actually, you need to update the tests to match the exception message update

**Comment by issei-m** [comment]
@stof I have updated OptionsResolverTest.

**Comment by fabpot** [comment]
Thank you @issei-m.

**Comment by fabpot** [comment]
I fixed the tests in 48265c9ab28c0c1cab2289c5733d301ddb4c830b

**Pull request closed without merging**
