### PR TITLE
[Form] Cleanup

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

ping @stof, ok for you?

### CODE REVIEW

**Comment by stof** [comment]
@nicolas-grekas many tests for ``$formFactory->createBuilder()`` should be removed, as they are now all testing the same thing (given that the default name is not generated in the method anymore)

**Comment by nicolas-grekas** [comment]
@stof can you point them at me please?

**Comment by stof** [comment]
I would say, all tests of ``createBuilder`` where you added the mocking of ``getBlockPrefix`` here :smile:

**Comment by nicolas-grekas** [comment]
ok :) See #16761 on 2.8, I'll then do the removal while merging 2.8 into master

**Pull request closed without merging**
