### PR TITLE
[Messenger] Add config option 'arguments_delay' for delay queues

### LINKED ISSUE #46254: [Messenger][AMQP] Support for RabbitMQ Quorum Queues in delayed queues
### Description

Hi! 

[Quorum Queues](https://www.rabbitmq.com/quorum-queues.html) were introduced in RabbitMQ 3.8.0.  
Since 3.10.0 it supports `x-message-ttl` which is used by [`Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::createDelayQueue()`](https://github.com/symfony/amqp-messenger/blob/6.1/Transport/Connection.php#L379-L395) - it was basically the missing piece to be able to use quorum queues for delayed queues.

Right now there is no way to configure messenger so it creates delayed queues as quorum.

Quote from the [documentation](https://www.rabbitmq.com/quorum-queues.html#declaring):
>To declare a quorum queue set the x-queue-type queue argument to quorum (the default is classic). This argument must be provided by a client at queue declaration time; it cannot be set or changed using a [policy](https://www.rabbitmq.com/parameters.html#policies). This is because policy definition or applicable policy can be changed dynamically but queue type cannot. It must be specified at the time of declaration.

Apart of the `x-queue-type` it would be great to be able to pass more arguments for delyed queues, like `x-quorum-initial-group-size`. 

### Example

_No response_

### PR DESCRIPTION
**Pull request by fwolfsjaeger**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #46254 & #44186
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

I've added the config option 'arguments_delay' to add arguments to delay queues when they are created in `\Symfony\Component\Messenger\Bridge\Amqp\Transport\Connection::createDelayQueue()`.

I'm not sure if this requires a Doc PR. If so, please just let me know and I'll add one.
Also, it might be necessary to remove certain arguments, but unfortunately I don't know which.

### CODE REVIEW

**Comment by fwolfsjaeger** [comment]
Okay, my changes do not work as expected. For whatever reason messages from delayed quorum queues vanish occasionally.

I'll have to investigate why later.

**Comment by fwolfsjaeger** [comment]
Alright, I've made some changes, it works now. Please let me know if you need a DOC PR or if this should go to 6.3 instead of 6.2.

**Comment by thomasbeaujean** [comment]
Hi @fwolfsjaeger, I add the same issue and went almost with the same strategy as you.

However, if I understand correctly your PR, I have to know in advance the routingKeys (the name of the delay queues, that depends of the name of the original queue and the delays).
And in my use case, it is something that is unknown by the dev team and is handled by the "infra guys".

I thought is was easier to only precise the extra args for the associated delay queues.

That is why I created a PR that achieve the same goal. 
I do not mean to compete your PR.

**Comment by fwolfsjaeger** [comment]
> Hi @fwolfsjaeger, I add the same issue and went almost with the same strategy as you.
> 
> However, if I understand correctly your PR, I have to know in advance the routingKeys (the name of the delay queues, that depends of the name of the original queue and the delays). And in my use case, it is something that is unknown by the dev team and is handled by the "infra guys".
> 
> I thought is was easier to only precise the extra args for the associated delay queues.
> 
> That is why I created a PR that achieve the same goal. I do not mean to compete your PR.

Hey!

You are right, with my PR, you have to know the actual queue name. I have added the config array `arguments_delay` to the queue options. This way it is possible to change settings per queue.

In my case a transport wide setting would be sufficient as well though. I don't know if anybody actually requires this config on queue level. Your PR as based on 6.3 and includes a test case, I'll close mine.

**Pull request closed without merging**
