### PR TITLE
[HttpFoundation] explicit type casting

### PR DESCRIPTION
**Pull request by nommyde**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

Not adding this casting may cause errors in the future.

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you please explain why you think that this change is necessary?

**Comment by nommyde** [comment]
@xabbuh I see that the development of the framework's code is moving towards increased strict typing. If we were to add the directive declare(strict_types=1) to this file now, it would result in an error. I believe that sooner or later these changes will have to be made anyway. Additionally, explicit type casting improves code clarity

**Comment by xabbuh** [comment]
The Symfony code is not going to move to strict types. And if we were, this file is not the only one that had to be updated. So I am against doing it here.

**Comment by wouterj** [comment]
Hi!

We've discussed strict typing before (https://github.com/symfony/symfony/issues/28423) and decided that we aren't going to add it to Symfony's code.

One of the reasons is precisely to avoid explicit type casting. PHP is very good at handling type coercion between strings, ints and doubles. There is no risk involved in using type coercion here instead of explicit casting.
Furthermore, this allows us to potentially change the method signature to also allow ints without having to remove the explicit type casts everywhere on the calling side.

For this reason, and the fact that if we change our opinion we need to do this in bulk throughout the codebase, I'm going to close this PR. 

Thanks for creating a PR, I hope we'll see you back in the future! 🙂

**Pull request closed without merging**
