### PR TITLE
[HttpClient] Add an opportunity to use curl BLOB constants certs

### PR DESCRIPTION
**Pull request by voodooism**
| Q             | A
| ------------- | ---
| Branch?       | 6.3 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? |no
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

It would be good to have an opportunity to pass raw data instead of path in HTTP-client configuration, like so:

```php
$httpClient->scopedClient('client_name')
  ->cafile('raw-data-here, not path')
  ->localCert('raw-data-here, not path')
  ->localPk('raw-data-here, not path');
```

### CODE REVIEW

**Comment by stof** [comment]
I don't think we should have the same option supporting strings being either filesystem paths or file contents. Guessing the expected signature based on whether the file actually exists is quite fragile (and might even be dangerous)

**Comment by voodooism** [comment]
> I don't think we should have the same option supporting strings being either filesystem paths or file contents. Guessing the expected signature based on whether the file actually exists is quite fragile (and might even be dangerous)

Ok, I agree. To be honest, initially, I wanted to introduce new options, but I spent some time thinking about naming and finished with no good idea :)

What do you think about the next naming: `cafileData`/ `cafileRaw`, `localCertData`/`localCertRaw`, `localPkData`/`localPkRaw`? 

Also, I didn't get why the tests failed with the `"Undefined constant "CURLOPT_SSLCERT_BLOB"`. As I see the constant is supported since PHP 8.1.0

**Comment by nicolas-grekas** [comment]
Thanks for the PR.
I'd rather not add options that are specific to some implementation.
Instead, I'd advise using extra.curl options.

**Comment by voodooism** [comment]
> Thanks for the PR. I'd rather not add options that are specific to some implementation. Instead, I'd advise using extra.curl options.

But in that case, we need to do it in every request, if I understand correctly. 
As libcurl supports it,  I think it would be useful to have those options to configure clients in application configs.

**Comment by nicolas-grekas** [comment]
It should be possible to configure default "extra" entries. If that's not possible today, this should be improved.

**Comment by nicolas-grekas** [comment]
It should be possible to configure default "extra" entries. If that's not possible today, this should be improved.

**Comment by voodooism** [comment]
Okay, will do it in a separate PR

**Comment by nicolas-grekas** [comment]
Thanks. Note that you can also configure the default options at the injection point, with eg
`$this->client = $client->withOptions([...])`

**Comment by voodooism** [comment]
> Thanks. Note that you can also configure the default options at the injection point, with eg `$this->client = $client->withOptions([...])`

Yes, it's applicable, but again in that case we need to do it in every class we use those options :(

**Comment by nicolas-grekas** [comment]
Closing in favor of #48797

**Pull request closed without merging**
