### PR TITLE
[Form] form_theme now sets the theme to all children of the specified form

### PR DESCRIPTION
**Pull request by mvrhov**
Bug fix: yes
Feature addition: no
Backwards compatibility break: no
Symfony2 tests pass: yes
Fixes the following tickets: N/A
Todo: -
License of the code: MIT
Documentation PR: N/A

### CODE REVIEW

**Comment by webmozart** [comment]
I don't have enough information to reproduce and fix this problem. Closing.

**Comment by mvrhov** [comment]
@webmozart: Would you please explain what exactly is it missing? You have the fork. The code is documented.

**Comment by webmozart** [comment]
To quote myself:

> I would really appreciate if you could simplify the form and describe exactly 1) what you expect to see and 2) what you actually see. It's really hard to figure that out from a big junk of HTML without any detailed explanation.

I know long explanations can be tedious, but I can't fix something that i don't understand.

**Comment by mvrhov** [comment]
@webmozart: 
IMO there is no need to simplify the html. If you don't notice the difference (after following the instructions inside  `src\Acme\DemoBundle\Resources\views\Welcome\index.html`) it's in the labels in this particular case.

As you are probably aware the default form theme associates a label with each input. 
In 2nd level the form is formated inside a table, so the labels on each input are unnecessary. And the theme removes them for the 2nd level. However due to a bug this seems not to work. The patch fixes that. 

How to achieve this with the demo is written in a comment inside  as I have said before.

**Comment by mvrhov** [comment]
P.S. This really needs to get into the core as this will be impossible to fix in 3.0 as the class parameters are gone. And there is no way for me to ship the workaround in my projects.

**Comment by sstok** [comment]
I think I understand what your problem is, you render the form and then you load an additional the theme into a subform. But as the previous theme (in the parent) is already cached the new one is never loaded.

This seems like an edge case and I'm not sure if its a good idea to support this, theming subforms by loading the theme into the subform looks wrong and edgy.

**Comment by mvrhov** [comment]
Yes, sstok, you understand correctly. I don't think that this is such edge case. Or it is as there would be more reports like this. 
I'd say that changing a subform theme is no different than changing the theme for a couple of inputs.

**Comment by mvrhov** [comment]
@webmozart: Please reconsider this.. sstok described perfectly. aNd this is now impossible to achieve in sf 3

**Comment by mvrhov** [comment]
@webmozart: I really need this in core, because now that 3.0 is out I'm unable to style my forms properly.

**Comment by webmozart** [comment]
@mvrhov Thanks for bringing this up again Miha. If somebody else can reproduce this and write a corresponding test case, I'm happy to merge this.

**Comment by backbone87** [comment]
If i get this correctly, then the cause for this problems lies with a potential missuse of the FormView.

FormViews are stateful (easily spotted by the "isRendered" method), but besides the "rendered" flag, also some caching for the form theme is done in the form view.

But because `form_javascript` and `form_stylesheet` (both from the custom bundle), traverse the whole form view tree to collect the styles and scripts, the form theme gets also processed and cached for each node in the form view tree.

Both functions are called at https://github.com/mvrhov/symfony-standard/blob/testcase_6025/src/Acme/DemoBundle/Resources/views/Welcome/index.html.twig#L15-L16 before the actual form rendering is done at https://github.com/mvrhov/symfony-standard/blob/testcase_6025/src/Acme/DemoBundle/Resources/views/Welcome/index.html.twig#L19-L27 . So the form theme set for the `form` twig-variable at the point of the first tree traversal at https://github.com/mvrhov/symfony-standard/blob/testcase_6025/src/Acme/DemoBundle/Resources/views/Welcome/index.html.twig#L15 is used for each node in the form view tree (and therefore cached in each one).

However at https://github.com/mvrhov/symfony-standard/blob/testcase_6025/src/Acme/DemoBundle/Resources/views/Welcome/index.html.twig#L26 the form theme gets overridden for a single node `form.prices` (a collection form type). But since the entry types were already visited, when `form_javascript` was called at https://github.com/mvrhov/symfony-standard/blob/testcase_6025/src/Acme/DemoBundle/Resources/views/Welcome/index.html.twig#L15 at which time the only form theme set (implicitly via default form theme) was already used and cached for the every descendant of the `form.prices` form view tree node.

@webmozart i hope this helps to get a grasp on the problem. (and i also agree that the presented demo is too complex to be easily scanned for the concrete problem)

**Comment by webmozart** [comment]
Thanks a lot for investigating @backbone87, the issue is much clearer now. Does that mean this could be fixed by moving the `{% form_theme ... %}` statement *before* the custom `form_javascript()` call?

**Comment by backbone87** [comment]
from my understanding: yes

**Comment by webmozart** [comment]
@mvrhov Could you verify please?

**Comment by mvrhov** [comment]
That "won't" work, when your forms are more than 1 level deep. 
What I'm trying to say is that it would be cumbersome/weird to set all the themes up top and not at the place you actually need it.

**Comment by webmozart** [comment]
@mvrhov What about moving the `form_stylesheet()` and `form_javascript()` calls after the form rendering code?

**Comment by backbone87** [comment]
@mvrhov the "where you need it" is *before* you call `form_stylesheet` and/or `form_javascript` because they internally traverse the whole form view tree to collect the styles the scripts. you need "a priori" knowledge about the inner workings of the functions/methods working on form views. thats the problem which i already mentioned:
>  i think subform theming is fine in general. the problem is that form theme "resolution" is done only once for each node not having an explicit theme set in the form view tree and since one doesnt know if, for example, form_start(myForm) already visited the whole form view tree internally, and therefore triggered the form resolution on every node, one must explicitly recursively overwrite the form theme for a node in the form view tree.

even **if** the concrete block to use, doesnt get cached: in your example the collected styles and scripts from your `form_stylesheet` and `form_javascript` calls base on the application of the default form theme to the whole form view tree, which could emit very different styles and scripts compared to (recursively) using another theme for a particular form view **sub**tree. either you must set all form themes within the form view tree before calling any rendering method or you must know what parts of the form view tree the called rendering method is using.

**Comment by mvrhov** [comment]
Putting `form_stylesheet˙ and `form_javascript` before form_end tag seems to work at least in the demo I provided.
I don't work on the project this was a problem initially anymore. So I cannot check there.
I also don't know why they were at the top i might be that that was requirement back then.

**Comment by webmozart** [comment]
Thanks a lot for verifying @mvrhov! :)

**Pull request closed without merging**
