### PR TITLE
[Intl] Update ICU data to 59.1

### PR DESCRIPTION
**Pull request by jakzal**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

The [GMT timezone has been split from the UTC](http://site.icu-project.org/download/59) timezone [in CLDR](http://cldr.unicode.org/index/downloads/cldr-31) (which ICU is based on).

For example, the code blow:
* before ICU 59.1 would return "GMT" in all cases
* with ICU 59.1 it returns "UTC" for the first three ('z', 'zz', 'zzz') 
  and "Coordinated Universal Time" for the last two ('zzzz', 'zzzzz').

```php
foreach (['z', 'zz', 'zzz', 'zzzz', 'zzzzz'] as $pattern) {
    $formatter = new \IntlDateFormatter('en', IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT, new \DateTimeZone('UTC'), IntlDateFormatter::GREGORIAN, $pattern);
    var_dump($formatter->format(new \DateTime('@0')));
}
```

Similarly Form's `DateTimeToLocalizedStringTransformer` is also affected:

```php
$transformer = new DateTimeToLocalizedStringTransformer('UTC', 'UTC', null, \IntlDateFormatter::FULL);
var_dump($transformer->transform(new \DateTime('2010-02-03 04:05:06 UTC')));
// ICU 58.2: '03.02.2010, 04:05:06 GMT'
// ICU 59.1: '03.02.2010, 04:05:06 Koordinierte Weltzeit'
```

Refer to added and modified test cases for more changes. I split this PR in two commits for easier review. First commit updates ICU data (generated files), the second updates code and test cases to be compatible with updated data.

### CODE REVIEW

**Comment by jakzal** [comment]
By the way, this PR is a perfect example of why the tests were used to run against a specific Intl version. ICU data changes way too often and it's hard to maintain tests that would run across versions.

**Comment by jakzal** [comment]
[This is interesting.](https://3v4l.org/sT7ia)

```php
foreach (array('UTC', 'GMT') as $timeZoneId) {
    $tz = new \DateTimeZone($timeZoneId);
    var_dump($timeZoneId.': '.$tz->getName());    
}
```

Output for 5.5.10 - 5.6.30, hhvm-3.10.1 - 3.19.0, 7.0.0 - 7.1.5:
```
string(8) "UTC: UTC"
string(8) "GMT: GMT"
```

Output for 5.3.0 - 5.5.9:

```
string(8) "UTC: UTC"
string(8) "GMT: UTC"
```

**Comment by jakzal** [comment]
This is ready for review.

To make my life easier [I prepared docker images](https://hub.docker.com/r/jakzal/php-intl) with various ICU releases and PHP versions compiled. Might be useful for others too.

Usage is very simple:

```
docker run -it --rm \
  -v (pwd):/symfony -w /symfony \
  jakzal/php-intl:7.1-59.1 \
  ./phpunit /symfony/src/Symfony/Component/Intl/Tests/
```

Where 7.1 is the chosen PHP version and 59.1 is the chosen ICU release.

**Comment by fabpot** [comment]
@jakzal Great for the Docker images! Can you add the URL and usage somewhere in the component itself so that we don't forget that these images exist?

**Comment by jakzal** [comment]
Added the link to docker hub to the Resources section in the readme. As usage is documented on docker hub I didn't want to duplicate it here.

**Comment by fabpot** [comment]
Thank you @jakzal.

**Comment by marcusesa** [comment]
Hi @jakzal. How could I help you? Is the PR ready to merge?

**Comment by marcusesa** [comment]
Is this PR applicable only to version 2.7 or 3.3 too?

**Comment by xabbuh** [comment]
@marcusesa We regularly merge the `2.7` branch up to all maintained branches. So this change will be available in the next patch releases of 2.8 and 3.2 as well as in the upcoming 3.3 release.

**Comment by marcusesa** [comment]
Thank you @xabbuh

**Pull request merged**
