### PR TITLE
[Filesystem] Updated phpdoc on allowed types of content

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/20612#discussion_r92941157
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by chalasr** [comment]
I believe `dumpFile` does not handle streams before 2.8 (see https://github.com/symfony/symfony/pull/16156), maybe this should target it instead of 2.7?

Status: reviewed
👍

**Comment by ro0NL** [comment]
I think were good... this applies to `$content` as a stream resource used with `file_put_contents`.

**Comment by nicolas-grekas** [comment]
Technically, this is right, but this is a contract change. I'm not sure we want to guarantee that it works for anything else but strings.
If we want, then this needs corresponding test cases, and it could target master.

**Comment by nicolas-grekas** [comment]
That could even be considered a BC break if we read things strictly.

**Comment by xabbuh** [comment]
:-1: for me. Making this change means that we have to support the other types too. Thus, moving away from `file_put_contents()` in the future could become harder than necessary.

**Comment by ro0NL** [comment]
Making it a behavior discussion then.. do we allow users to rely on it?

**Pull request closed without merging**
