### PR TITLE
[3.0] [SecurityBundle] Form extension deprecations fixes

### PR DESCRIPTION
**Pull request by TomasVotruba**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

This should make tests passing on master again

Master mirror to #16331

Depends on #16396

### CODE REVIEW

**Comment by xabbuh** [comment]
As far as I see this we just have to wait until branches have been merged up to the `master` branch.

**Comment by TomasVotruba** [comment]
I see. I'd just prefer to send PR against passing branch.

Was about to send some deprecated removal PRs, but failed due to few bugs after margin lower branches.

**Comment by TomasVotruba** [comment]
Any idea why this fails? https://travis-ci.org/symfony/symfony/jobs/88419632#L2514

**Comment by Tobion** [comment]
2.8 was merged into master.

**Comment by TomasVotruba** [comment]
:+1:

**Pull request closed without merging**
