### PR TITLE
[HttpFoundation] Fix formatting session id

### LINKED ISSUE #44546: Session is not being created after upgrade to 5.4.1
### Symfony version(s) affected

5.4.1 or 6.0.1

### Description

After upgrading to version 5.4.1/6.0.1, the session stopped working. As a result of the search, I realized that the problem was with this [https://github.com/symfony/symfony/pull/44437](https://github.com/symfony/symfony/pull/44437), if you roll it back, it became normal.

### How to reproduce

if `framework.session.cookie_secure: auto` is set, then:

- `https `connections will create a session
- `http `connections will not create a session

### Possible Solution

File `src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php` Line 32:

If you replace this:

`$sessionCookieWithId = sprintf('%s%s;', $sessionCookiePrefix, urlencode($sessionId));`

On

`$sessionCookieWithId = sprintf(' %s%s;', $sessionCookiePrefix, urlencode($sessionId));`

That works correctly.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by verng95**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #44546 
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by chalasr** [comment]
Some tests are failing with this change. Can you have a look?

**Comment by verng95** [comment]
> Some tests are failing with this change. Can you have a look?

Hm... locally, the tests did not show an error, I will try to reproduce the problem.

**Comment by fritzmg** [comment]
I can confirm that the fix would work though.

**Comment by verng95** [comment]
> I can confirm that the fix would work though.

Yes, but the tests fail. I can return a pull request.

**Comment by alexislefebvre** [comment]
Maybe the tests were wrong, and they have to be updated.

**Pull request closed without merging**
