### PR TITLE
Update bridge PHPUnit 8.3 -> 8.5

### PR DESCRIPTION
**Pull request by RSalo**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 or 5.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. 

Could you just tell me why you need this?

**Comment by RSalo** [comment]
@Nyholm I have seen that is not the latest version for PHP 7.4 and created PR.

**Comment by Nyholm** [comment]
Is there any features in 8.5 that you need that is not available in 8.3? Is there something major that I’ve missed?

**Comment by RSalo** [comment]
@Nyholm Nope. Nothing special. Just a fresh version. If it will BC fall or fail tests I will close this PR.

**Comment by derrabus** [comment]
I understand that the PHPUnit versions the bridge selects seem a little arbitrary. On the other hand, projects that do not specify a PHPUnit version might break unexpectedly if we changed the defaults in a bugfix release.

Either way, I would recommend not to rely on the defaults of the bridge and to use the `SYMFONY_PHPUNIT_VERSION` env variable to specify the PHPUnit version you want.

**Comment by RSalo** [comment]
@derrabus I can re-create this PR for the 5.x branch. Sooner or later this anyway should be updated to the latest version. Is this path good for solving this issue? Or easily just stay it as it is?

**Comment by nicolas-grekas** [comment]
I think staying as-is is OK. We don't need to bump for the sake of it, especially when new phpunit versions can break existing CIs with new deprecations.

**Comment by Nyholm** [comment]
I agree with Nicolas and Alexander. 

Thank you for making the PR.

**Pull request closed without merging**
