### PR TITLE
[SecurityBundle] Fix CookieClearingLogoutListener DI configuration

### LINKED ISSUE #37282: Service "security.logout.listener.cookie_clearing.web" must implement interface "Symfony\Component\EventDispatcher\EventSubscriberInterface".
**Symfony version(s) affected**: 5.1.1

**Description**  

Adding `delete_cookies` to a firewall throws and error: `Service "security.logout.listener.cookie_clearing.web" must implement interface "Symfony\Component\EventDispatcher\EventSubscriberInterface".`

I believe this is becuase `vendor/symfony/security-http/Logout/CookieClearingLogoutHandler.php` does not implement `EventSubscriberInterface`

**How to reproduce**  

Reproduction: https://github.com/leevigraham/symonfy_delete_cookies_bug

1. Create a new skeleton app with the security component
```
composer create-project symfony/skeleton bug_app
cd bug_app
composer require symfony/security-bundle
```

2. Add delete_cookies to the firewall config

```
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users_in_memory
            logout:
                delete_cookies:
                    jwtSig: { path: null, domain: null }
                    jwtPayload: { path: null, domain: null }

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
```

3. Run `bin/console cache:clear`

**Additional context**  

image

image

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37282 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by wouterj** [comment]
Please do not merge yet, I need to update the test to see if the cookie is deleted. I'm struggling quite hard to achieve that

**Comment by wouterj** [comment]
Test fixed, can be merged :)

**Comment by wouterj** [comment]
Status: Needs review

**Comment by fabpot** [comment]
Thank you @wouterj.

**Pull request merged**
