### PR TITLE
[Validator] ExpressionValidator should use OBJECT_TO_STRING 

### PR DESCRIPTION
**Pull request by Simperfit**
…value in message

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24595 
| License       | MIT
| Doc PR        | Will do.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
For which branch is this PR?

**Comment by Simperfit** [comment]
I think it's for 4.1 since it's a new feature
Le lun. 30 oct. 2017 à 19:36, Nicolas Grekas <notifications@github.com> a
écrit :

**Review by dunglas — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
It looks like a bug to me. The current behavior does not make much sense, it "works" by change. Displaying a generic "object" string is never something one would expect, right?

**Comment by xabbuh** [comment]
fine for me as a bugfix too

**Review by ogizanagi — APPROVED** [review]
Agreed too 👍

**Comment by Simperfit** [comment]
rebased to 2.7

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Simperfit.

**Pull request merged**
