### PR TITLE
[Messenger] Remove the Doctrine middleware configuration from the FrameworkBundle

### PR DESCRIPTION
**Pull request by sroze**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #26647
| License       | MIT
| Doc PR        | ø

As per @fabpot's request, remove the enabling feature of the DoctrineMiddleware from the FramworkBundle.

/cc @Nyholm

### CODE REVIEW

**Comment by Nyholm** [comment]
Im not convinced. It feels like all middlewares should be registered at the same place. Especially if we do #26652. 

I do also imagine we could register middlewares like: 

```yaml
framework:
  messenger:
    middlewares: ~ # default middlewares
    bus_foo:
      type: foo
      routing:
        'App\Bar': ['sender.bar', 'sender.biz']
        'App\Foo': 'sender.foo'
      middlewares:  # bus specific middlewares
        - 'custom_service'
        - validation: true
```

**Comment by fabpot** [comment]
@Nyholm There is a difference between being able to register all middleware services at the same place and hardcoding a specific middleware for Doctrine (third-party libraries won't be able to do that).

**Comment by sroze** [comment]
For the records, a bit of the discussion is happening here as well: https://github.com/symfony/symfony/pull/26647#discussion_r177396484

**Comment by Nyholm** [comment]
>  There is a difference between being able to register all middleware services at the same place and hardcoding a specific middleware for Doctrine (third-party libraries won't be able to do that).

Yes. I know. I just wanted to share this idea with you (everybody). Maybe I should put it on #26652.

**Comment by sroze** [comment]
@fabpot at the end, WDYT about this one? Shall we close it or revert that on the FrameworkBundle (which will require a PR on the DoctrineBundle later)? 🤔

**Comment by fabpot** [comment]
I haven't changed my mind on this one.

**Comment by sroze** [comment]
Fair enough. It's waiting for votes to go ahead then.

**Comment by fabpot** [comment]
@sroze Can you rebase this one so that I can merge it? Thank you.

**Review by fabpot — APPROVED** [review]

**Comment by sroze** [comment]
Rebased. @Nyholm could you send a PR on the DoctrineBundle to port this feature there?

**Comment by fabpot** [comment]
Thank you @sroze.

**Pull request merged**
