### PR TITLE
[Contracts] extract LocaleAwareInterface out of TranslatorInterface

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

While reviewing #28929, I realized we have a design issue in the Translation contract: we missed segregating `setLocale()`/`getLocale()` out of `TranslatorInterface`. E.g. when people type-hint for `TranslatorInterface`, they *should not* be auto-suggested with the `setLocale()` mutator.

Technically, that's a BC break. I think we should do it. The release is close enough in time and that will save us from maintenance issues this will create in the future otherwise.

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
You explained it perfectly: there may be some (little) pain in this BC change ... but it's tiny compared to its benefits.

**Review by ogizanagi — APPROVED** [review]

**Review by stof — APPROVED** [review]
The pain will only be for people having fully migrated away from the old TranslatorInterface. So I'm fine with doing that.

**Review by Tobion — APPROVED** [review]

**Comment by Isengo1989** [comment]
Should be the new Service be autowired by default? I updated my project and switched the setLocale() of the TranslatorInterface with the LocaleAwareInterface but I am getting:

> Cannot autowire argument $locale of "App\Controller\UsersController::test()": it references interface "Symfony\Contracts\Translation\LocaleAwareInterface" but no such service exists.

**Comment by goeckus** [comment]
> Shouldn`t be the new Service be autowired by default? I updated my project and switched the setLocale() of the TranslatorInterface with the LocaleAwareInterface but I am getting:
> 
> > Cannot autowire argument $locale of "App\Controller\UsersController::test()": it references interface "Symfony\Contracts\Translation\LocaleAwareInterface" but no such service exists.
> 
> when using **$locale->setLocale('en');**

Just define the interface in services yaml. I'm not sure if this is the best way, but it will work:

    Symfony\Contracts\Translation\LocaleAwareInterface:
        alias: 'translator.default'

**Comment by gmponos** [comment]
@nicolas-grekas I recently created a new services that I wanted to make it `aware` of the locale.

Let's say my services was `EmailSender`. I tried to have this class implement `LocaleAwareInterface` but since this interface is under `Translation` namespace it does not feel correct to have a service about `emails` implement an `Interface` for translation. Furthermore the locale is not used there to define the translation but to define the receiver.

So I was wondering if this could be improved even further and have the `LocaleAwareInterface` somewhere else.

**Pull request merged**
