### PR TITLE
[travis] update to trusty

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Precise is dying, see https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

### CODE REVIEW

**Comment by lyrixx** [comment]
Maybe It should be done on 3.X only? (because of PHP 5.3)

**Comment by nicolas-grekas** [comment]
Travis is planning to drop precise this winter - so we'll have to do that update anyway.

**Comment by lyrixx** [comment]
:+1:

**Review by fabpot — APPROVED** [review]

**Comment by Tobion** [comment]
It says 

> end support for dist: precise | Sunday, April 1 2018

and 2.7 is supported for bugfixes until May 2018. So I don't see why not keep 5.3 tested until March and be on the safe side.

**Comment by nicolas-grekas** [comment]
In fact, 5.3 is tested, on appveyor now, so were still reasonably safe.

**Comment by nicolas-grekas** [comment]
(oh, and 2.8 still supports 5.3, so we'll hit the issue with it)

**Comment by stof** [comment]
Well, we can keep using Precise for the 5.3 job only for the time where Travis still supports it.

**Pull request merged**
