### PR TITLE
[Translation] restore compatibility with FrameworkBundle 4.2

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #30260
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by yceruto — APPROVED** [review]
Hi @xabbuh, is it planned to move both commands to the Translation component at some point? This kind of incompatibility looks bad from the design point of view IMHO.

**Comment by xabbuh** [comment]
IMO that makes sense and IIRC we already did that for other commands in the past.

**Comment by yceruto** [comment]
Well, I'll take a look at this next week to see what I can do.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
