### PR TITLE
[Routing] add query param if value is different from default

### PR DESCRIPTION
**Pull request by Tobion**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | yes |
| New feature? | yes |
| BC breaks? | most likely not |
| Deprecations? | no |
| Tests pass? | no |
| Fixed tickets | #10940, #18111, #18035 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Tobion** [comment]
I hope this does not break the i18n routing bundle tests contrary to before (see #6814 and https://travis-ci.org/schmittjoh/JMSI18nRoutingBundle/jobs/3229075).
This time only query params are added that are not equal to the default value.

**Comment by fabpot** [comment]
Thank you @Tobion.

**Comment by leofeyer** [comment]
This is a BC break, I'm afraid. If you had not removed lines 296 and 297 of the `UrlGeneratorTest` class, you would have noticed. These are the former assertions:

```php
public function testQueryParamSameAsDefault()
{
    $routes = $this->getRoutes('test', new Route('/test', array('default' => 'value')));
  
    $this->assertSame('/app.php/test', $this->getGenerator($routes)->generate('test', array('default' => 'foo')));
    $this->assertSame('/app.php/test', $this->getGenerator($routes)->generate('test', array('default' => 'value')));
```

We have relied on the first assertion being true in Contao, which is now no longer the case.

**Comment by Tobion** [comment]
What is your use-case for this behavior?

**Comment by leofeyer** [comment]
Our use case is pretty much what is in the first deleted assertion. We want the router to ignore the `_locale` request attribute if there is a default `_locale` route attribute. It worked like a charm up to Symfony 3.0.4 and it does no longer in Symfony 3.0.5, because now the `?_locale=xx` query string is appended.

But actually the use-case should not matter. The changes affect the API in an incompatible way, which the deleted assertions would have shown if not removed. :)

**Comment by leofeyer** [comment]
Also, I'm not implying that ignoring the `_locale` request attribute if there is a default `_locale` route attribute is the right way to solve the problem. It might be not.

Still the router now behaves differently than in Symfony 3.0.4.

**Pull request merged**
