### PR TITLE
Use symfony-*-bridge instead of symfony-bridge for component bridges

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Might help discovering bridges for each component.

### CODE REVIEW

**Comment by stof** [comment]
To me, this kind of discovery is better handled using keywords than using the type (which has a single value).

**Comment by nicolas-grekas** [comment]
Updating the type still makes sense to me: e.g. `symfony-messenger-bridge` is a better type description than `symfony-bridge` to me.

**Comment by GromNaN** [comment]
On packagist there is a filter on tags, not on type. How would you search a package on its type?

https://packagist.org/?query=symfony-bridge does not return symfony packages.

**Comment by nicolas-grekas** [comment]
https://packagist.org/?type=symfony-bridge

**Comment by stof** [comment]
@GromNaN packagist has both a filter by type and by tags (packagist's name for keywords). But the `query` parameter is about searching by name.

**Review by chalasr — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
