### PR TITLE
[Routing] check static routes first in a switch

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Improves performance by moving static routes first when possible. Should benefit PHP 7.2 most, where switch uses a hash table.
Embeds a few fixes for bugs found meanwhile, which I'm going to submit separately for lower branches (see #25962.)

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Can anyone please benchmark this change with a non-trivial set of routes and using PHP 7.2? Thanks!

**Comment by nicolas-grekas** [comment]
The perf improvement is significant: for 400 static + 400 dynamic routes, matching the last static route
- when the 400 static precede the others: 72ms vs 65 ms for 10k routes
- when the routes are interweaved: 775ms vs 65ms

**Comment by derrabus** [comment]
So, this basically changes the order of the routes, doesn't it? Could this be a problem?

**Comment by nicolas-grekas** [comment]
@derrabus not if done wisely, which should be the case here - at least there is some logic to ensure this should not be an issue. Please review :)

**Comment by nicolas-grekas** [comment]
Closing in favor of #26059

**Pull request closed without merging**
