### PR TITLE
[Intl] fix wrong offset timezone PHP 8.1

### PR DESCRIPTION
**Pull request by Lenny4**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/45451
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by nicolas-grekas — COMMENTED** [review]
I pushed some changes, but I cannot reproduce the failure on my local setup.
When I revert the change, the new test case still passes. Can you confirm that's not the case for you?

**Comment by Lenny4** [comment]
@nicolas-grekas 
Which PHP version were you using ?

**Comment by nicolas-grekas** [comment]
With both PHP 8.1 and 7.4

**Comment by nicolas-grekas** [comment]
I ran the test case with 
`./phpunit src/Symfony/Component/Intl/ --group intl-data --filter testGetRawOffsetChangeTimeCountry`

**Comment by Lenny4** [comment]
This is really strange I got the same result as you.

**Comment by ro0NL** [comment]
for me the patch works

```
docker run -it -v "$(pwd):/app" -w /app php:8.1 ./phpunit src/Symfony/Component/Intl/ --group intl-data --filter testGetRawOffsetChangeTimeCountry
```

**Comment by nicolas-grekas** [comment]
@ro0NL the issue is not that tests are red, it's that they are always green, even when using PHP 8.1 BEFORE THE PATCH.

**Review by ro0NL — APPROVED** [review]
PHP 8.1 docker images uses: `"Olson" Timezone Database Version => 2021.5`

and the test is red without this patch :+1:

**Comment by nicolas-grekas** [comment]
Thank you @Lenny4.

**Pull request merged**
