### PR TITLE
[CS] PHPUnit dedicate assert fixer acceptance test

### PR DESCRIPTION
**Pull request by SpacePossum**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | no |
| License | MIT |

The goal of this PR is _not_ to have it merge, but to check with SF community if a new Fixer (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1792) should be added to the set of Symfony fixers (at PHP-CS-Fixer).

### CODE REVIEW

**Comment by javiereguiluz** [comment]
My 2 cents: I love the `assertFileExists()` and `assertFileNotExists()` ... but I don't like the `assertInternalType()`. I wish it was called `assertType()`.

**Comment by fabpot** [comment]
LGTM :+1:

**Comment by SpacePossum** [comment]
nice :)

offtopic:
@javiereguiluz I agree, don't know why they picked that method name. I created a trait with some aliases https://github.com/GeckoPackages/GeckoPHPUnit#scalarasserttrait (not useful for SF, but maybe for a little project of your own ;) )

**Comment by fabpot** [comment]
Thank you @SpacePossum.

**Pull request merged**
