### PR TITLE
[DependencyInjection][Messenger] Add auto-registration for `BatchHandlerInterface`

### PR DESCRIPTION
**Pull request by GaryPEGEOT**
| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Comment by chalasr** [comment]
~For 6.1?~ Nevermind.

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @GaryPEGEOT.

**Comment by oneNevan** [comment]
@GaryPEGEOT hi there!

I know it's been a long time, but i'm curious why this change was introduced?
It is stated as a bug fix, but I there is no reference to an issue this PR fixed, so I cannot to figure it out by myself.

I've created an issue https://github.com/symfony/symfony/issues/59912, but I'm wondering if I'm missing something..

Do you remember why would we need to autoregister services with BatchIndexHandlerInterface with `messenger.message_handler` when all other handlers are supposed to be registered manually with #[AsMessageHandler]? What "bug" did you try to fix by doing so? Or maybe it was like "it's handy, so lets autorigister it"?

Thanks!

**Comment by GaryPEGEOT** [comment]
@oneNevan it was so a class implementing this interface would be auto-configured with the correct tag. I might be wrong, but I think it was before `AsMessageHandler` attribute was created.

**Comment by oneNevan** [comment]
@GaryPEGEOT Yes, you are probably right!

Now I recall we previously had MessageHandlerInterface for regular handlers which was deprecated with introduction AsMessageHandler attribute and removed in symfony 7.0
With [this](https://github.com/oneNevan/symfony/commit/6baa3d282c04b9208ef1c2e3d58a0f1cc02bb7bc#diff-e4f52d5033296421d02e360c8355aa1931bdfb0c12579f4815ea02b724322c0cL650) change autoregistration of BatchHandlerInterface should have been removed too, but it wasn't

Thank you!

**Pull request merged**
