### PR TITLE
[DomCrawler] Added nextUntil and previousUntil sibling navigation functions.

### PR DESCRIPTION
**Pull request by sudhanshuRathore**
| Q             | A
| ------------- | ---
| Branch?       | master for features / 5.0 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| License       | MIT
| Doc PR        | https://github.com/symfony/symfony-docs/pull/13267

Crawler::nextUntil($finalNode) & Crawler::previousUntil($finalNode) returns siblings within the range of current and $finalNode.

### CODE REVIEW

**Comment by fabpot** [comment]
I don't know if this use case is widespread enough to add it to the core. @javiereguiluz What do you think?

**Comment by javiereguiluz** [comment]
I don't remember needing this feature myself ... but my DomCrawler usage is limited (I only use it for my non-complex tests). Maybe people who use this component a lot (e.g. @lyrixx) can comment if they regularly need this. Thanks!

**Comment by lyrixx** [comment]
I don't need this feature ATM, but who know? 
Anyway for now I agree with @fabpot

**Comment by stof** [comment]
btw, the behavior seems weird to me when `$finalNode` is not found in the siblings. The current implementation would return all next siblings (or all previous siblings for `previousUntil`). But we cannot really consider that they are between the current node and the final node.
So even the definition of the API seems unclear to me.

**Comment by fabpot** [comment]
Let's close then. Thanks for proposing.

**Pull request closed without merging**
