### PR TITLE
[WebProfilerBundle] replaces tabs characters by spaces.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by sstok** [comment]
Status: reviewed

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by stof** [comment]
Good catch, thanks @hhamon.

**Comment by lyrixx** [comment]
@hhamon Could you please fix other files too ?

* src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig
* src/Symfony/Bridge/Twig/Resources/views/Form/bootstrap_3_layout.html.twig

Thanks.

**Comment by hhamon** [comment]
Yes sure! Will do in the train ;)

**Comment by lyrixx** [comment]
http://hugo.jmikola.net/

**Pull request merged**
