### PR TITLE
[SecurityBundle] allow auto_wire for SessionAuthenticationStrategy class

### PR DESCRIPTION
**Pull request by xavren**
| Q             | A
| ------------- | ---
| Branch?       | 3.4 up to 4.0 for deprecation fixe 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets |  
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by chalasr** [comment]
What deprecation are you getting?

**Comment by chalasr** [comment]
Ah, I guess the service gets auto registered and corresponding notice triggered. But this can be disabled by setting the `container.autowiring.strict_mode` parameter to `true` (see https://github.com/symfony/symfony-docs/issues/8561). 
This should be rebased on master.

**Comment by xavren** [comment]
I have this deprecated on sf 3.4.2

```
Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "security.authentication.session_strategy" service to "Symfony\Component\Security\Http\Session\SessionAuthenticationStrategyInterface" instead.
Hide context    Hide trace
[▼
  "exception" => SilencedErrorContext {#2472 ▶}
]
{▼
  /srv/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php:304 {▶}
  /srv/www/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php:245 {▶}
}```

**Comment by xavren** [comment]
For information, i create my own LoginManager and i inject $sessionStrategy, but my manager cannot be autowire because of this service

**Review by chalasr — APPROVED** [review]
👍  for 3.4

**Comment by nicolas-grekas** [comment]
Thank you @xavren.

**Pull request merged**
