### PR TITLE
[HttpFoundation] Deprecated considering 201 a redirect status code

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #12347
| License       | MIT
| Doc PR        | -

The question to answer is: *"Is 201 HTTP status code a redirect?"*

* If yes, let's work on this PR.
* If no, let's close this PR and #12347 too.

### CODE REVIEW

**Comment by stof** [comment]
We need an argument to be able to opt-in for the new behavior of the method. Otherwise, the only way to get rid of the notification is to stop using 201.

**Comment by Tobion** [comment]
IMO it should just check if the Location header is present for certain status codes like 201. If the location header is not present, it's not considered a redirect.

**Comment by derrabus** [comment]
`201 Created` definitely is a redirect status despite not being part of the 3xx series. The problem with the `Location` header is that it is optional not only for `201` but also for `301`, `302` etc. The standard only says that you SHOULD provide a `Location` header with the response, not that you have to. So if you take the header into account, you need to do it for all redirection status codes. And I don't think that this would be helpful.

Also, even without a `Location` header a `201` is still a redirect to the effective URL of the request, meaning that if you `PUT` something to `/foo/4711`, a `201` without that header will tell you that you can now `GET /foo/4711` to find your newly created resource.

> The question to answer is: _"Is 201 HTTP status code a redirect?"_

Yes, it is.

**Comment by Tobion** [comment]
A redirection is defined in https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html as

> indicates that further action needs to be taken by the user agent in order to fulfill the request

@derrabus can you quote the spec where it says that 201 falls under this category?

**Comment by Tobion** [comment]
Also where does it say that a 201 without Location is the same as a 201 with the same resource Location header?

**Comment by derrabus** [comment]
@Tobion RFC 2616 is obsolete and has been replaced by RFC 7230 through 7235, so let's work with those documents.

The passage you're quoting does not describe redirection in general, but the 3xx groups of status codes titled "redirection", see [RFC 7231](https://tools.ietf.org/html/rfc7231), section 6.4:

> The 3xx (Redirection) class of status code indicates that further action needs to be taken by the user agent in order to fulfill the request.

As `201` is not a `3xx` status code, that definition does not apply to `201`.

Of course you could argue that if the standard does not include it in the group it labelled "Redirection", it's probably not meant to be a redirect. But in that case, the presence of a `Location` header would be irrelevant.

`201` is somewhat a special case, since it is not included in the "Redirection" group, yet it uses mechanisms of redirects like the `Location` header. So I guess, both interpretations have a valid point. I'd rather support the interpretation that recognizes `201` as a redirect.

From the Symfony point of view, if I create a `RedirectResponse` with a `201` code, the framework would produce a valid HTTP message.

> Also where does it say that a 201 without Location is the same as a 201 with the same resource Location header?

RFC 7231, section 6.3.1:

> The primary resource created by the request is identified by either a Location header field in the response or, if no Location field is received, by the effective request URI.

**Comment by Tobion** [comment]
A 201 with a Location header is just meant as a hint where to find the created resource. That is clearly not a redirect as defined by the standard.

> For 201 (Created) responses, the Location value refers to the primary
   resource created by the request.  For 3xx (Redirection) responses,
   the Location value refers to the preferred target resource for
   automatically redirecting the request.

I don't think the whole `isRedirect` is useful at all. Either you can use `isRedirection` or you can check the `Location` header yourself which is more understandable and does not create this confusion. So I'd be favor of deprecating the whole method.

**Comment by derrabus** [comment]
You have to differ between a redirect and a redirection status code. The first is a concept of a response redirecting the client (typically a browser) to a different resource. The latter is a group of status codes that indicate that further actions have to be taken by the client (which may or may not include a redirect).

There's an intersection like a `302 Found` response for instance that typically comes with a `Location` header or an HTML document with a piece of JavaScript code that refreshes the URL.

On the other hand, there's a `201` which can be seen as a redirect, but which is not a redirection. And there's `304` which is a redirection, but probably not a redirect.

I understand that this causes confusion, especially looking at the docblock of the `Response::isRedirection()` method (yeah, we should at least change that).

> So I'd be favor of deprecating the whole method.

Fine by me, but the logic behind the method is actually being used by Symfony in various places. You'd either have to duplicate that logic or you're changing behavior.

**Comment by javiereguiluz** [comment]
I'm closing because this proposal is too controversial and it looks like there's no consensus about 201 being a redirect. In any case, thanks for the discussion!

**Pull request closed without merging**
