### PR TITLE
[3.0] Added getBlockPrefix to FormTypeInterface

### PR DESCRIPTION
**Pull request by wouterj**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by WouterJ** [comment]
Failures seem unrelated to this PR

**Comment by xabbuh** [comment]
@WouterJ Can you rebase on the latest `master` branch? That should make the test pass.

**Comment by xabbuh** [comment]
:+1: anyway as the failure is not related to these changes

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @WouterJ.

**Comment by webmozart** [comment]
Here's the follow-up: https://github.com/symfony/symfony/pull/16749

**Pull request merged**
