### PR TITLE
Changed private static array-properties to const

### PR DESCRIPTION
**Pull request by simonberger**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

This changes all private static properties (just screened arrays) to private const. I left out those which have write access obviously and also those with `static::` access.

It is a new implementation of #38213. Based on 4.4 this time.
If merging it up creates several conflicts, you could ignore all changes of 4.4 and I create a new branch for 5.1 or 5.2. I'll do this anyway if any new private static arrays are existing there.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Can this change be automated? If not, then I'm likely :-1: 
merging in 5.1 or higher won't reduce merge conflicts - it will increase them actually.

**Comment by simonberger** [comment]
@nicolas-grekas 
> Can this change be automated? If not, then I'm likely 👎

I don't know of any tool providing this as an automation.

> merging in 5.1 or higher won't reduce merge conflicts - it will increase them actually.

What do you exactly mean? Because of merge conflicts I offered to redo all the work on the next branches. I can prepare them already in advance. In a merge you can ignore all conflicts this branch creates. Similar to how fabpot did it with this PR https://github.com/symfony/symfony/pull/39775#issuecomment-757508718

In the previous PR everyone was generally 👍  for the change. As some time has passed and no one of the team did it I repeated the work (It's not that costly; took around 1,5 hours).

**Comment by stof** [comment]
Well, this can probably not be automated, because we cannot forbid using `private static` in the project. We might have valid use cases for it. But this should be a one-time conversion anyway.
Our new code is already using private constant when possible instead of private static arrays.

**Review by nicolas-grekas — APPROVED** [review]
OK, I forgot about this previous discussion.
Let's go.

**Comment by nicolas-grekas** [comment]
Thank you @simonberger.

**Comment by nicolas-grekas** [comment]
Now merged up to 5.x. PR welcome for 5.1+

**Comment by simonberger** [comment]
Looks like you solved all conflicts. Thank you. :)
I'll add a PR later.

**Comment by TomasVotruba** [comment]
> Can this change be automated? If not, then I'm likely -1

It can :)
https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#changereadonlyvariablewithdefaultvaluetoconstantrector

**Pull request merged**
