### PR TITLE
[DomCrawler] prevent deprecation being triggered from assertion

### LINKED ISSUE #35889: DOM Crawler component triggers deprecation error when calling its own method
**Symfony version(s) affected**: 4.4.4

**Description**  

The `Symfony\Component\DomCrawler\Test\Constraint::CrawlerSelectorTextContains::matches` method uses the `Symfony\Component\DomCrawler\Crawler::text()` method in such a way that it triggers a deprecation error.

While not a being a critical bug, I think a component should not trigger its own deprecation errors. It looks like the app using the component is doing something wrong but it is not.

**How to reproduce**  

I am running a WebTestCase that has the following assertion:
```php
$this->assertPageTitleContains('Expected title');
```

The page's `<title>` element has a text content with multiple spaces, like this:
```html
<title>    Site name
    –
    Expected title</title>
```

**Possible Solution**  

The constraint could explicitly pass the optional arguments to the `text()` method.

**Additional context**  

Here is the deprecation error that shows up in the test report of my company's symfony application:

```
  4x: "Symfony\Component\DomCrawler\Crawler::text()" will normalize whitespaces by default in Symfony 5.0, set the second "$normalizeWhitespace" argument to false to retrieve the non-normalized version of the text.
```

The method call:
https://github.com/symfony/dom-crawler/blob/4.4/Test/Constraint/CrawlerSelectorTextContains.php#L48

The deprecation trigger:
https://github.com/symfony/dom-crawler/blob/4.4/Crawler.php#L617-L620

There is probably the same issue with the `CrawlerSelectorTextSame` contraint:
https://github.com/symfony/dom-crawler/blob/4.4/Test/Constraint/CrawlerSelectorTextSame.php#L48

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35889
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by fancyweb — APPROVED** [review]
As pointed in the issue, don't we need to also update https://github.com/symfony/dom-crawler/blob/4.4/Test/Constraint/CrawlerSelectorTextSame.php#L48?

**Comment by xabbuh** [comment]
@fancyweb Indeed, I fixed it.

**Comment by xabbuh** [comment]
@fancyweb Indeed, I fixed it.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by flaushi** [comment]
Maybe we could add a hint to `assertSelectorTextSame` into the error message https://github.com/symfony/symfony/blob/15edfd39d4b3da4d011a6242238c4b2874eb1ace/src/Symfony/Component/DomCrawler/Crawler.php#L619? I think many people had to research this issue

**Comment by xabbuh** [comment]
What issue would that solve?

**Comment by flaushi** [comment]
I can imagine may people using `$crawler->text()` in their tests.

They all have to read through this issue and PR to finally see that there is a new assertion  `assertSelectorTextSame ` they can use to prevent the deprecation error. Kind of "documentation in issue"

**Pull request merged**
