### PR TITLE
[DependencyInjection] Fixed decoration of service for service with parent

### PR DESCRIPTION
**Pull request by hason**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by iltar** [comment]
What issue/bug does this actually fix?

**Comment by jakzal** [comment]
Could you rebase as [tests are failing](https://travis-ci.org/symfony/symfony/jobs/51581926) and they're fixed in 2.6.

Also, please explain more what's being fixed here.

**Comment by hason** [comment]
@itar and @jakzal The explanation is in the tests. Nevertheless I present a real problem:

I want to decorate all haml filters defined by DI tag `mthaml.filter` (a decorator is a front yaml parser). So I define the abstract filter:

```yaml```
front_yaml.haml_filter:
    class: Vendor\Haml\FrontYamlFilter
    arguments:
      - @front_yaml.parser
    abstract: true
```
In a compiler pass I create a new filter from parent service `front_yaml.haml_filter` (see http://symfony.com/doc/current/components/dependency_injection/parentservices.html) and define the decorated service - the original haml filter (see http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services):

```php
foreach ($container->findTaggedServiceIds('mthaml.filter') as $id => $tags) {
    $name = $id.'_front_yaml';
    $filter = new DefinitionDecorator('front_yaml.haml_filter');
    $filter->addArgument(new Reference($name.'.inner'));
    $filter->setDecoratedService($id);
    $filter->setTags(['mthaml.filter' => $tags]);
    $container->setDefinition($name, $filter);
}
````

**Comment by hason** [comment]
ping @symfony/mergers

**Comment by hason** [comment]
ping @fabpot @stof

**Comment by stof** [comment]
The decoratedService overwrite should be handled in the same way than other changeable settings IMO (through ``$definitionDecorator->getChanges()``, not in the special way.

**Comment by hason** [comment]
@stof Updated.

**Comment by nicolas-grekas** [comment]
:+1: for a merged on 2.3

**Comment by fabpot** [comment]
Thank you @hason.

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
