### PR TITLE
CS fixes

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | o 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by keradus** [comment]
Hi @fabpot , thanks for note.
This is bug that we had sadly introduced in last release of 2.12.

If description is a multiple sentences, rule shall not change it.

--------

This is good change:

```diff
-@param string $foo Description of param.
+@param string $foo description of param
```

This is not a good change:

```diff
-@param string $foo Description of param. Multiple sentences.
+@param string $foo description of param. Multiple sentences
```

----

This bug will be fixed in next 2.12 release, see PR to see state of work on that:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4027

**Comment by keradus** [comment]
This PR follows after tool, but it introduces bad changes, that won't happen anymore after fix on PHP CS Fixer side.
I would suggest to not merge it.

**Comment by nicolas-grekas** [comment]
@keradus I've been wondering a lot about the lowercasing of the first letter: it happens only when there is a dot that should be removed at the end. If there is no dot, then the uppercase is preserved. That's a really strange behavior. (personally, I prefer keeping this letter uppercased all the time as I feel it eases reading.)

**Comment by keradus** [comment]
Originally requested rule was to not let the description to be a sentence.
Same as sentence has no trailing dot, it shall not have leading upper case.
Having it mixed up is weird.

**Comment by nicolas-grekas** [comment]
There is at least one inconsistency: if the description doesn't end with a dot, then the uppercase is not turned to lowercase...

**Comment by nicolas-grekas** [comment]
Hum this logic doesn't work in practice to me as it makes things feel very unstable and unintuitive.

I'd prefer something like:
- always upper the first letter
- remove end dot for single sentence descriptions
- enforce end dot for multi sentences ones

Does anyone else agree with this proposal?

**Comment by keradus** [comment]
Having uppercased first letter without having full stop at end of the sentence look wrong from grammar point of view. :(

**Comment by chalasr** [comment]
I agree with @nicolas-grekas here, not having uppercased first letter makes it less readable/structured to me. Even though I understand @keradus point regarding grammar, I don't really like the rule as-is in practice (just feeling)

**Comment by SpacePossum** [comment]
maybe @nicolas-grekas an/or @chalasr can open an issue @ [the fixer project](https://github.com/FriendsOfPHP/PHP-CS-Fixer) with a detailed description of how the SF team would like this rule to act? Than we can work on it :)

**Comment by nicolas-grekas** [comment]
Thanks, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4045

**Pull request closed without merging**
