### PR TITLE
[Workflow] determines places from transitions

### LINKED ISSUE #52378: [Workflow][RFC] Simplify workflow configuration
I have been thinking about this for a while, so it's time to open a RFC!

The workflow definition is redundant. You have to define the places twice:

* in the `places`
* in the `transitions`

Example:

```yaml
framework:
    workflows:
        article:
            places:
                - first
                - last
            transitions:
                go:
                    from: first
                    to: last
```

I think we could simplify it to:

```yaml
framework:
    workflows:
        article:
            transitions:
                go:
                    from: first
                    to: last
```

Indeed, all places could be guessed from the transitions `from`s et `to`s. If a
place is not reached by a transition, it become useless anyway.

## Pros

* Simpler configuration

## Cons

* If one made a typo between the `place` and the `transitions` transition, it's
  not caught anymore

---

WDYT ?

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | Fix #52378
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
What about throwing if at least one place is defined?
The behavior would be:
- if you don't define any place => auto-guessed from transitions
- if you define at least one place => require them all to be listed (allowing some sort of strict mode definitions to be typo-safe)

**Comment by lyrixx** [comment]
The issues comes from the framework bundle. I want people to be able to

* not define dumb places
* define places with some metadata

```yaml
framework:
    workflows:
        blog_publishing:
            metadata:
                title: 'Blog Publishing Workflow'
            places:
                draft:
                    metadata:
                        max_num_of_words: 500

            transitions:
                to_review:
                    from: draft
                    to:   review
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by lyrixx** [comment]
(fixed fabbot, phpunit failures seems not related)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
