### PR TITLE
[Serializer] Add ability to skip uninitialized properties

### PR DESCRIPTION
**Pull request by idsulik**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Add SKIP_UNINITIALIZED_PROPERTIES context property to AbstractObjectNormalizer to skip uninitialized properties when normalizing object.
PHP 7.4 thrown exception when you try go get uninitialized property, the PR add ability to skip those properties when normilizing

p.s. I don't know how to test because of project php version 7.2

### CODE REVIEW

**Comment by BoShurik** [comment]
Similar PR #38900 but as a bug fix

**Comment by idsulik** [comment]
@BoShurik , #38900 - it fixes only property access, but not method access. for example - I have an private uninitialized property and getter for the property

**Comment by BoShurik** [comment]
Property access was fixed in #34791. #38900 fixes exactly what you describe

**Comment by idsulik** [comment]
@BoShurik I'm sorry, you're right , it fixed #38900 but not merged. When it will be merged?

**Comment by BoShurik** [comment]
@idsulik I don't know. Waiting for review

**Comment by idsulik** [comment]
@BoShurik okay, thank you! I think we can close the PR

**Pull request closed without merging**
