### PR TITLE
Cleanup `@return` annotations

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

The goal of this patch is to allow php-cs-fixer to remove these annotations on 6.0 when native return types will be used.

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
🔥

**Review by wouterj — APPROVED** [review]
Nice! I hope you used incredible regex skills to somewhat automate this and didn't have to go over all of them by hand.

(is even this something that we don't want to merge into 4.4?)

**Review by derrabus — APPROVED** [review]
🚀

**Comment by derrabus** [comment]
Thank you Nicolas.

**Pull request merged**
