### PR TITLE
[PropertyAccess] Fix accessing public property on Object

### LINKED ISSUE #37026: Recover support to write properties for non stdClass objects
**Symfony version(s) affected**: 5.1 and lower

**Description**  
When generating entities (e.g. via nelmio/alice) it was long possible to write values into existing properties.
But now it seems like the property accessor does only allows this for instances of stdClass .

Possibly since this change: https://github.com/symfony/property-access/commit/0583535d2cfa597ccd6a8e75f6f3bf5a138a5541

So when a class like

```
class Foo {
}
```

has no property but an object gets a property later on like

```
$o = new Foo();
$o->bla = null;
```

then the PropertyAcessor is no longer able to write into this existing property
and instead throws the NoSuchPropertyException exception with a "Could not determine access type" message.

**Possible Solution**  

Drop the explicit check for stdClass 

```
} elseif (property_exists($object, $property)) {
            $object->$property = $value;
        }
```

see https://github.com/symfony/property-access/blob/0583535d2cfa597ccd6a8e75f6f3bf5a138a5541/PropertyAccessor.php#L509

### LINKED ISSUE #37615: Regression - PropertyAccess no longer works with classes + dynamically added properties
**Symfony version(s) affected**: x.y.z

**Description**  
In version 5.0.10, one could use a `PropertyAssessor` to fetch properties that were dynamically added to a class instance.  In version 5.1.0, this functionality was removed/broken.

**How to reproduce**  

```
class Person  {
    public function __construct(string $name) {
        $this->name = $name;
    }
}

$accessor = PropertyAccess::createPropertyAccessor();

$person = new Person("Joe Consumer");

/* 
  The following works correctly in version 5.0.10.
  In versions 5.1.0 - 5.1.2 it throws an exception: "Can't get a way to read the property "name" in class..." 
*/
$name = $accessor->getValue($person, 'name');  
```

**Possible Solution**  
One solution is to declare the property in the class definition, but this does not solve the issue for dynamically added properties.

Underlying regression is here:

https://github.com/symfony/symfony/blob/367aa1df6caa2c739a58165ead81e7fe50e6599e/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L438

The `Person` class in this example is not an instanceof `\stdClass`.

**Additional context**  

Same issue reported when writing to a class instance:  #37026

### PR DESCRIPTION
**Pull request by kschnekenburger**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37026, fix #37615
| License       | MIT
| Doc PR        | no

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you please add a test case for what Fabien described in https://github.com/symfony/symfony/pull/37622#issuecomment-683392308 to make sure that we do not break those use cases?

**Comment by xabbuh** [comment]
Will this also fix #37615?

**Comment by kschnekenburger** [comment]
> Will this also fix #37615?

@xabbuh Yes it will also fix, i wrote test for that

**Comment by kschnekenburger** [comment]
> Can you please add a test case for what Fabien described in [#37622 (comment)](https://github.com/symfony/symfony/pull/37622#issuecomment-683392308) to make sure that we do not break those use cases?

@xabbuh For that maybe I'm wrong but testGetValueIgnoresMagicGet covers this case no ?

**Comment by xabbuh** [comment]
Not sure, if I don't miss anything, that test was already present at the time #37622 was merged.

**Comment by kschnekenburger** [comment]
> Not sure, if I don't miss anything, that test was already present at the time #37622 was merged.

@xabbuh Ok, i also wrote test for that

**Comment by kschnekenburger** [comment]
Hi, Did you have time to watch ? @xabbuh thx :)

**Comment by nicolas-grekas** [comment]
Thank you @kevcomparadise.

**Pull request merged**
