### PR TITLE
Update contributing docs

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Branch | 2.3 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

I propose adding the branch to the pull request template so that submitters have some hint about the branch selection workflow, and so that we can edit it for mergers.

I'd also like to add a link to the "running tests" doc, which made me rewrite the full contributing file, with links to the sections of the contributing documentation.

### CODE REVIEW

**Comment by fabpot** [comment]
:+1:

**Comment by dunglas** [comment]
:@

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
