### PR TITLE
[FrameworkBundle] templating can be fully disabled

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #19052 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by dosten** [comment]
This cannot be merged into 3.1?

**Comment by xabbuh** [comment]
My mistake, this should of course be merged into 3.1.

**Comment by j0k3r** [comment]
@xabbuh thanks for the fix, it works well :+1:

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request closed without merging**
