### PR TITLE
[HttpFoundation] Remove body-related headers when sending the response, if body is empty

### PR DESCRIPTION
**Pull request by SimonSimCity**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

I've updated the implementation for informational and 204 or 304 responses. They will now, as they have no content, not return headers like `content-type` or `content-length`.

I'm unsure about `content-length` - we could also set it hardcoded to zero ... but I thought, that (because the specs say that it just can't have a response-body) the system should not return anything here.

### CODE REVIEW

**Comment by jeffsrepoaccount** [comment]
I stumbled on what I thought to be a bug, which turns out was the result of this PR.  The use case is that I have an API that is set up to respond with a content-type of `'application/json'` for requests with an `Accept` of `'application/json'`.  Some of the responses' status are 204.

We have a client for this API that ensures the content-type coming back from the API is correct.  Since the status code is 204, this line in our code seemingly does nothing:

    $response->header('Content-Type', $contentType);

Where `$contentType` is determined via the `Accept` header.

I can verify that we were attempting to set it to the correct type, but when inspecting the response coming back it is always `text/html`.  IMHO, Symfony re-setting the content-type to `text/html` for empty responses makes about as much sense in general as someone wanting to set a different content-type for that empty response, so why am I forced to use `text/html` when the response body is empty?  I don't believe the spec mentions this header specifically, only the `Content-length` header. (I may be wrong on this point, if so I apologize)

Sure, I can easily change the status code coming back from 204 to something else like 200 / 201, but I don't want to be forced to do so _if_ 204 happens to make better semantic sense.

**Comment by SimonSimCity** [comment]
Hi, @jeffsrepoaccount

Are you really sure, that this response is sent by Symfony2? This PR here was about removing all content related headers, where `Content-Type` was one of the very first one.

Please check your Webserver, sending the response to the browser. Some of them are adding the content-type if the underlying system (PHP in this case) does not seem to have it set.

For more details, take a look at the code, committed in this PR: https://github.com/symfony/symfony/commit/72e8515327e8f828e4803c4e340aa32eb0c5099f#diff-a8f7745712c744a53020ed9c09bd68bcR273 - See also the test, where I verify, that the header has been removed: https://github.com/symfony/symfony/commit/72e8515327e8f828e4803c4e340aa32eb0c5099f#diff-1

**Comment by jeffsrepoaccount** [comment]
Ok, fair enough, something else is adding back the `Content-type` after this removes it (which is _after_ I set it).  If it doesn't get removed, nothing else has to add it back in, correct?

**Comment by SimonSimCity** [comment]
Right ... but I had the feeling, that having it removed was a good choice, since there is no content.

I researched a bit more and found out, that nginx sets `text/plain` as default http://nginx.org/en/docs/http/ngx_http_core_module.html#default_type and Apache had `none` for pretty much time now http://httpd.apache.org/docs/current/mod/core.html#defaulttype

**Comment by jeffsrepoaccount** [comment]
I think ultimately you're semantically correct, it doesn't make sense in the outside world for empty content to have a type.  However, I don't think the specification disallows it which means those web servers are still operating within their prerogative.

**Comment by jakzal** [comment]
@jeffsrepoaccount @SimonSimCity PHP is adding Content-type back. see #12744

**Pull request closed without merging**
