### PR TITLE
[Form] Deprecate the "choices_as_values" option of ChoiceType

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by craue** [comment]
Is there any way to "feature detect" wether or not this option needs to be set (to `true`)?

**Comment by stof** [comment]
@craue ``method_exists(AbstractType::class, 'getName')``, as this method has been removed in Symfony 3, and setting it is neccessary only in ``~2.7`` to get this behavior.

**Comment by craue** [comment]
@stof, thanks. I wonder why `getName` isn't mentioned in the 3.0.0 changelog. But that's out of scope of this PR.

**Comment by stof** [comment]
@craue because the changelog files are incomplete, as reported already. Latest removals have been forgotten

**Comment by Laurent3170** [comment]
I am using Symfony 3.1.2 and I receive the message:	The "choices_as_values" option is deprecated since version 3.1 and will be removed in 4.0. You should not use it anymore. but I DON'T use "choices_as_values". I just use
"choices" as shown below:
```
    ->add('advertiser', ChoiceType::class, array(
        'label' => 'label.advertiser',
        'disabled' => $disabled,
        'required' => true,
        'expanded' => true,
        'multiple' => false,
        'choices'  => array(
            'label.individual' => 'individual',
            'label.association' => 'association',
            ),
        'label_attr' => array(
            'class' => 'radio-inline'
        )))
```
Stack trace in case it helps
```
ChoiceType::Symfony\Component\Form\Extension\Core\Type\{closure}() (called from OptionsResolver.php at line 885)
    OptionsResolver::offsetGet() (called from OptionsResolver.php at line 716)
    OptionsResolver::resolve() (called from ResolvedFormType.php at line 95)
    ResolvedFormType::createBuilder() (called from ResolvedTypeDataCollectorProxy.php at line 83)
    ResolvedTypeDataCollectorProxy::createBuilder() (called from FormFactory.php at line 85)
    FormFactory::createNamedBuilder() (called from FormBuilder.php at line 106)
    FormBuilder::create() (called from FormBuilder.php at line 269)
    FormBuilder::resolveChildren() (called from FormBuilder.php at line 215)
    FormBuilder::getForm() (called from FormBuilder.php at line 221)
    FormBuilder::getForm() (called from FormFactory.php at line 39)
    FormFactory::create() (called from Controller.php at line 309)
    Controller::createForm() (called from AdController.php at line 144)
    AdController::displayLocaleCreateAdAction()
    call_user_func_array() (called from HttpKernel.php at line 153)
    HttpKernel::handleRaw() (called from HttpKernel.php at line 68)
    HttpKernel::handle() (called from Kernel.php at line 177)
    Kernel::handle() (called from app_dev.php at line 30)
```

**Pull request merged**
