### PR TITLE
[Workflow] improve docblocks

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍 

Status: reviewed

**Comment by xabbuh** [comment]
@lyrixx's changes from #20470 are included too.

**Comment by javiereguiluz** [comment]
👍 to the new changes too. Thanks!

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
