### PR TITLE
[Form] Add vietnamese translation for html5 color validation

### PR DESCRIPTION
**Pull request by jschaedl**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | - 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Could you work on the other missing translations?

**Review by van2412 — APPROVED** [review]

**Comment by jschaedl** [comment]
@fabpot 

> Could you work on the other missing translations?

Yes I probably could do that. But I am not sure which translations you mean. Could you give me a hint, please :-)

**Comment by fabpot** [comment]
nevermind :)

**Comment by fabpot** [comment]
Thank you @jschaedl.

**Pull request merged**
