### PR TITLE
[Twig] added subpath function

### PR DESCRIPTION
**Pull request by Tobion**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #4849, partly #6857 |
| License | MIT |

The new function `subpath` merges the variables of the current route request with the ones you optionally passed to the function. On top of that you can also add the query params (disabled by default).

It will generate a path-relative URL once #3958 gets merged but this PR is not necessarily depending on it. Since the target URL, that inherits some params from the current request, is probably a sub-page in the URL hierarchy (which is why it's called `subpath`), it makes sense to default it to a relative path, which makes the links shorter.

Use cases:
1. Generating the **same route** but changing a few parameters while keeping others of the current request (e.g. typical locale switcher).
2. Generating a **different route** while removing/overriding/adding some parameters on top of the current params. This is very useful when you have hierarchically structured pages, which is very common.
   Example: We are at `/user-slug/article-slug/` (article_show) and want to generate the link to comments of the article (article_comments). At the moment we would have to always repeat the current variables like
   `{{ path('article_comments', {'user': 'user-slug', 'article': 'article-slug'}) }}` and would for example get `/user-slug/article-slug/comments`.
   With `subpath` the advantage is you don't need to specify the variables of the current request again.
   So simply `{{ subpath('article_comments') }}` is enough for the relative URL `comments` in this case. But you can optionally overwrite some request variables with `{{ subpath('article_comments', {'article': 'different-article-slug'} ) }}` which would generate `../different-article-slug/comments` (i.e. same user, but different article).
3. Merging the **query params** can be used for filtering links, e.g. a facetted navigation page that filters items and you want to generate a link to add/overwrite filters based on the current filters. This is also one reason why removing params is needed which can be achieved by passing `null` as value for the unwanted param.
4. Generating a route with the same host params. See #6857.
5. <del>Generating the **same URL**.</del> I really thought much about this use-case. And I came to the conclusion it's not necessary for it to have a specific twig function. Of course you can also generate the same URL with path, url and subpath functions. But with path and url, you need to pass all variables again. And with subpath it will just generate an empty string `''` because that's the relative path for the current URL. So you don't need to call subpath at all. And if you need an absolute path or url, then you can just access the request information directly (`Request::getRequestUri`, i.e. in twig `{{ app.request.requestUri }}`. It's also faster because it doesn't go through the routing url generation at all. So all in all, it's already easy to get the same url. It would also not have much to do with `subpath` but instead it would be more appropriate to expose a new function like `{{ self() }}`. But as I said, it's not really needed and not part of this PR.

### CODE REVIEW

**Comment by WouterJ** [comment]
ping @xabbuh @jakzal @stof @fabpot @Tobion can we please decide on the solutions mentioned in https://github.com/symfony/symfony/pull/3965#issuecomment-50607864 ?

**Comment by xabbuh** [comment]
In my opinion, option four is a step in the right direction. The `app.currentRoute` and `app.currentRouteParams` globals could also be useful outside of creating URLs/paths.

Some things we then still need to solve are:

* removing params
* merging query params

For the first issue, I could imagine that this is something that could be added to Twig itself (like it is done the other way around with the `merge` filter).

For the second issue, I don't have a concrete idea right now. Maybe adding another Twig global or function could be the solution.

**Comment by fabpot** [comment]
It really depends on which use cases we are talking about. From the issue description, I think that only the first one is relevant.

**Comment by fabpot** [comment]
I'm closing this very old PR as there is no activity, and no consensus on what to do.

**Pull request closed without merging**
