### PR TITLE
[Mailer] update the Brevo SMTP host

### LINKED ISSUE #51118: Changes in SMTP relay address
### Description

We use Sendinblue as a mail provider for our Laravel application. Recently, we received an email to change the SMTP Server address:
https://developers.brevo.com/docs/changes-in-smtp-relay-address

As far as I understand we need to use the https://github.com/symfony/brevo-mailer package. However, as far as I can tell, this package is still using the old host address `smtp-relay.sendinblue.com`:
https://github.com/symfony/brevo-mailer/blob/6.4/Transport/BrevoSmtpTransport.php#L26

Do you have plans to update it? If yes, when can we expect this change to be released?

Thank you!

### Example

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #51118
| License       | MIT
| Doc PR        | 

see https://developers.brevo.com/docs/changes-in-smtp-relay-address

### CODE REVIEW

**Comment by xabbuh** [comment]
ping @PEtanguy

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by bastien-wink** [comment]
@xabbuh @nicolas-grekas Could this be also part of lower versions of symfony ? According to the email bellow the current SMTP will be terminated this month.

image

I will get in touch with Brevo to know exactly how long they will support the old hostname.

**Comment by fabpot** [comment]
My answer would be that if a commercial product doesn’t care about making their user lives easier, I don’t see why we should. Anyway, I suppose we would accept a PR doing the needed changes in 6.3.

**Comment by bastien-wink** [comment]
Indeed they don't care about their customers, I've done my best to have a clear answer, all we have is "that might impact the good fonction of your transactional sending".

I created a PR for 6.3 https://github.com/symfony/symfony/pull/51295

For the record :
image

**Comment by stof** [comment]
Given that the new Brevo bridge won't be released until November (as it was merged in 6.4 and not in 6.3), I suggest merging that as a bugfix (and maybe even in the 5.4 LTS instead of having a non-working bridge as LTS)

**Comment by fabpot** [comment]
I've merged the PR in 5.4.

**Comment by stof** [comment]
@fabpot given that the previous host will stop working on August 30th, it would be great also to do a patch release (for 5.4 and 6.3) soon enough to give projects a bit of time to update this bridge before the deadline is reached so that it keeps working.

**Comment by kgonella** [comment]
Hello, do we have a chance that a patch release will be available before August 30th ?

**Comment by fabpot** [comment]
We make releases at the end of each month. So, the next release cycle will happen at the end of August.
But then again, I don't see why we should rush things out on our side because of a commercial company that doesn't care about their customers.

**Comment by derrabus** [comment]
Until we tag a new release, use a dev snapshot:

```JSON
"require": {
    "symfony/sendinblue-mailer": "~6.3.4@dev"
}
```

or switch to the new package:

```JSON
"require": {
    "symfony/brevo-mailer": "^6.4@dev"
}
```

**Comment by stof** [comment]
@derrabus switching to brevo-mailer also requires switching to framework-bundle 6.4.x-dev, otherwise the wiring won't be done.

**Pull request merged**
