### PR TITLE
3.0 Upgrade Guide: Describing how to pass data to a form through options resolver

### PR DESCRIPTION
**Pull request by smithandre**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18662 |
| License | MIT |
| Doc PR |  |

Enhanced the upgrade guide by adding details regarding passing data to a form through the options resolver.

### CODE REVIEW

**Comment by Koc** [comment]
What to do if I should check for `custom_value` inside method `configureOptions`?)

```php
class MyType
{
    private $value;

    publuc function __construct($value)
    {
        $this->value = $value;
    }
  
    public function configureOptions(OptionsResolver $resolver)
    {
        if ($this->value) { ... }
        $resolver->setDefaults(array(
            'custom_value' => null,
        ));
    }
}
```

**Comment by Koc** [comment]
For example how to handle this case http://symfony.com/doc/current/validation/group_service_resolver.html wich explained in documentation? As you see - `groupResolver` passed via constructor of form type and cann't be passed via options array, because we haven't options array when `configureOptions` method called

// cc @webmozart

**Comment by xabbuh** [comment]
@Koc You would register your form type as a service and register the instance you would like to use as the default value. You would then still be able to pass another instance using the option when building the form.

**Comment by fabpot** [comment]
Thank you @smithandre.

**Pull request closed without merging**
