### PR TITLE
[HttpKernel] Dont register env parameter resource

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Think this was forgotten in #22886

Not sure about `EnvParametersResource` in the http-kernel component. Core doesnt use it anymore, so we could deprecate it (and while doing so move it to config component to keep the feature if wanted). Kept as is for now.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by chalasr — APPROVED** [review]
once fabbot happy :) Tend to agree we should deprecate the class

**Comment by ro0NL** [comment]
have some patience :) done.

**Comment by ro0NL** [comment]
Deprecation be done in 3.4, let me know if you want a PR.

**Comment by stof** [comment]
I suggest deprecating EnvParametersResource in 3.4, in favor of env placeholders. The implementation of this resource is tied to the old logic reading magic env variables. It is not a generic resource for env variable usage anyway, so using it in other contexts that HttpKernel would be weird.

**Comment by ro0NL** [comment]
Basically it's a resource to verify freshness of any env var, tied to a prefix. i think it fits config component, but im not sure it be useful to anyone =/

**Comment by nicolas-grekas** [comment]
#24068 is now merged up to master, can you rebase and remove the deprecated class meanwhile please?

**Pull request merged**
