### PR TITLE
[Debug] Fix case sensitivity checks

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18344 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
Looks like deps=high needs some fixing.

regarding this PR, this looks good to me. :+1:

**Comment by alexchip64** [comment]
With this fix, in Windows system, $caseCheck is set to "0", whereas it should be set to "1" (filesystem is NOT case sensitive) as in previous versions.

**Comment by nicolas-grekas** [comment]
@alexchip64 can you detail why it ends up being set to zero in your case?

**Comment by alexchip64** [comment]
Because, in my case, the situation of the checking is as follow:

$file = C:\Users\cipriano\Documents\NetBeansProjects\zoe\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php

$fileTest = C:\USERS\CIPRIANO\DOCUMENTS\NETBEANSPROJECTS\ZOE\VENDOR\SYMFONY\SYMFONY\SRC\SYMFONY\COMPONENT\DEBUG\DEBUGCLASSLOADER.PHP

_but_

realpath($fileTest) = C:\Users\cipriano\DOCUMENTS\NETBEANSPROJECTS\zoe\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php

so the check `realPath($fileTest) === $file` fails.

(please consider that I don't know why **realPath** returns "DOCUMENTS" and "NETBEANSPROJECTS" in capitals, as both directories were created with the names indicated in "$file")

**Comment by nicolas-grekas** [comment]
does it work better if you use strtolower instead of strtoupper?

**Comment by alexchip64** [comment]
I've done it, it but final result does not change:

`$fileTest = 'c:\users\cipriano\documents\netbeansprojects\zoe\vendor\symfony\symfony\src\symfony\component\debug\debugclassloader.php'`

_but_

`realpath($fileTest) = 'C:\Users\cipriano\documents\netbeansprojects\zoe\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php'`

**Comment by nicolas-grekas** [comment]
strange... this means it couldn't work previously and caseCheck ended up being 2, not 1, isn't it?

**Comment by alexchip64** [comment]
Version 2.8.4 does not work in Windows as I indicated in my #18344, because final value is 2 and Symfony hangs.
Previous versions used different way for checking: the result was 1 if PHP_OS contains the string "win" but not the string "darwin".

**Comment by nicolas-grekas** [comment]
@alexchip64 PR updated, can you please check the new patch?

**Comment by alexchip64** [comment]
Nothing changes.

`$test = 'C:\Users\cipriano\Documents\NetBeansProjects\zoe\vendor\symfony\symfony\src\Symfony\Component\Debug\DebugClassLoader.php'`

and

`$file = 'DebugClassLoader.php'`

so the checking:
`elseif (substr($test, -strlen($file)) !== $file)`

returns false

**Comment by nicolas-grekas** [comment]
My bad, it should be `===` instead of `!==`. Fixed.

**Comment by alexchip64** [comment]
Now it is ok. At least it appeas ok for Windows systems.

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
