### PR TITLE
[HttpCache] add option to passthrough HEAD requests to the backend

### PR DESCRIPTION
**Pull request by dmaicher**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/20893
| License       | MIT
| Doc PR        | TODO

This PR introduces a new config option `'head_method_passthrough'` that will change the default behaviour of changing the request method from `HEAD` to `GET` when doing a backend fetch.

### CODE REVIEW

**Comment by fabpot** [comment]
I'm :-1: for this. I don't understand the issue here.

If the client asks for a HEAD request, it will receive a HEAD response. But, we are doing a GET request to the backend so that we can cache the response in the cache. When doing a HEAD request, you will probably be doing a GET request if you receive a 200 from the server.

**Comment by fabpot** [comment]
Also, I forgot to mention 2 things:

 * `HEAD` requests can be served from the cache, so the backend is only called once;
 * Varnish behaves in the exact same way.

**Comment by nicolas-grekas** [comment]
Closing for the reason given by @fabpot

**Comment by mangelsnc** [comment]
Actually, the issue is not solved yet.

The main problem with this is that when you change to `prod` environment, all the routes annotated with `@Method("HEAD")` are not accessible, because before to send it to back, is sent a `GET` instead of a `HEAD` and that route is not configured for this method. 

The only solution is to annotate it as `@Method({"HEAD", "GET"})`.

**Comment by nicolas-grekas** [comment]
@mangelsnc please open an issue then. Your description here is new. If you want it answered, a closed PR is not going to trigger much feedback.

**Pull request closed without merging**
