### PR TITLE
[MimeType] Duplicated MimeType due to PHP Bug

### PR DESCRIPTION
**Pull request by juanmrad**
| Q             | A
| ------------- | ---
| Branch?       | 5.1 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

## Issue:

Currently there is a PHP bug https://bugs.php.net/bug.php?id=77784 that is causing several MimeTypes to be given as duplicated:

```
application/vnd.openxmlformats-officedocument.spreadsheetml.sheetapplication/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```
Instead of:
```
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```

This Patch will fix the Issues by checking if a returned MimeType is duplicated and return appropriate MimeType.

This patch should be reverted if the PHP Bug is ever fixed.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you for telling us about this.
Could you please target branch 3.4 and add a test case also?

**Comment by fabpot** [comment]
Any news? fabbot has also some fixes for you.

**Comment by juanmrad** [comment]
@nicolas-grekas I tried changing the base, but looks like 3.4 does not have that file. I'll be creating some test cases today and apply patches from fabbot as mentioned by @fabpot

**Comment by juanmrad** [comment]
NVM realized it is just on another place. I'll be doing the change in a bit.

**Comment by juanmrad** [comment]
@nicolas-grekas I have encountered 2 issues with my PR and would like to ask for suggestions. 
on PHP 5.6 there is an issue that docx and xml files are actually reported as application/zip as they are not being recognized. 
And looks like TravisCi is not running php 7.4 where this issue is present.

**Comment by nicolas-grekas** [comment]
I'd suggest skipping the test on PHP5 by adding an `@requires PHP 7 annotation on the test case.
PHP 7.4 runs on the deps=low job.

**Comment by juanmrad** [comment]
@nicolas-grekas Done thanks :).

**Comment by nicolas-grekas** [comment]
Thank you @juanmrad.

**Pull request merged**
