### PR TITLE
[HttpFoundation] Fix ianaCodesReasonPhrasesProvider in ResponseTest

### PR DESCRIPTION
**Pull request by simonberger**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Tickets       | #43292
| License       | MIT

This fixes the currently failing tests.

### CODE REVIEW

**Comment by simonberger** [comment]
I don't understand why the 7.4 tests still fail with the same error.

**Comment by fabpot** [comment]
As the status messages should never be used for anything, I think this should be done in 5.4 instead (aka not a bug fix).

**Comment by simonberger** [comment]
The main problem are failing tests (https://github.com/symfony/symfony/pull/43291/checks?check_run_id=3776657076#step:8:4317). 

There would be the need to replace values of the XML https://www.iana.org/assignments/http-status-codes/http-status-codes.xml

**Comment by simonberger** [comment]
Or moving the XML into the project as a test resource and keep an old version for 4.4 to 5.3?

**Comment by nicolas-grekas** [comment]
Good idea

**Comment by simonberger** [comment]
I found the state of the XML of last month (from 2018) and added it to the project.
I'll create another PR for 5.4 (or 6.0?) to update the XML and actual message-texts in the Response class.

**Comment by OskarStark** [comment]
5.4 please

**Comment by simonberger** [comment]
> 5.4 please

It is a bugfix. How should it be fixed on 4.4?

**Review by nicolas-grekas — APPROVED** [review]
4.4 indeed as is

**Review by chalasr — APPROVED** [review]

**Comment by OskarStark** [comment]
As @fabpot mentioned as no bugfix, it should result in 5.4 instead of 6.0.
While it is now considered a bugfix, 4.4 is fine

**Comment by nicolas-grekas** [comment]
@OskarStark: @fabpot's comment was on the initial iteration of this PR, where the reason text was updated. That's not the case anymore and only tests are fixed (by making them used a pinned version of iana's xml).

**Comment by nicolas-grekas** [comment]
Thank you @simonberger.

**Comment by stof** [comment]
@simonberger can you do a second PR targetting 5.4 to update HttpFoundation to use the new IANA reason phrases ?

**Comment by simonberger** [comment]
@stof Already prepared one. I'll create the PR once it is merged up to `5.4` and I can rebase.

**Comment by xabbuh** [comment]
@simonberger done

**Pull request merged**
