### PR TITLE
[TwigBridge] update test for Twig performance optimizations

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | twigphp/Twig#2617
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by fabpot** [comment]
That works only with the next version of Twig, so we need to bump Twig's versions.

**Comment by stof** [comment]
this should be done with a different case, checking both the environment major version and the minor version IMO, instead of forbidding older minor versions strictly.

**Comment by xabbuh** [comment]
I am not sure if it's worth it, but taken that into account doesn't add much complexity. So here we go.

**Review by javiereguiluz — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
