### PR TITLE
Fix ini_get() for boolean values

### PR DESCRIPTION
**Pull request by deguif**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

This follows #29020 for branch 3.4

### CODE REVIEW

**Comment by jvasseur** [comment]
This shouldn't be needed, `ini_get` already returns a normalized value for boolean configs ("" for false and "1" for true).

**Comment by nicolas-grekas** [comment]
ini_set() and ENV-defined ini setting, see https://github.com/composer/composer/pull/7760#issuecomment-434630838

**Comment by deguif** [comment]
To add more details, the issue is encountered when using environment variables to configure some PHP ini directives.

```
#php.ini
[opcache]
opcache.enable_cli = ${PHP_INI_OPCACHE_ENABLE_CLI}
```

`PHP_INI_APC_ENABLE_CLI=true php -r "var_dump(ini_get('apc.enable_cli')); new APCUIterator();"` will enable apcu and outputs:
```
string(4) "true"
``` 

`PHP_INI_APC_ENABLE_CLI=false php -r "var_dump(ini_get('apc.enable_cli')) ; new APCUIterator();"`
will disable apcu and outputs:
 ```
string(5) "false"

Fatal error: APCuIterator::__construct(): APC must be enabled to use APCuIterator in Command line code on line 1
```

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
I'm not sure we want to do this dance for all calls to `ini_get`. Most of those settings should not be set via env vars anyway (or is there another case where we need this?).

**Comment by nicolas-grekas** [comment]
Let's do it IMHO: that prevents us from wondering about which settings are legit changing via env vars. There is no easy reasoning so we will be wrong at some point in the future. There are only a few calls in the code base also...

**Review by xabbuh — APPROVED** [review]

**Pull request merged**
