### PR TITLE
[Validator] Fix DebugCommand

### PR DESCRIPTION
**Pull request by loic425**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please tell what is the bug about you are trying to fix? Thanks

**Comment by loic425** [comment]
> Can you please tell what is the bug about you are trying to fix? Thanks

It crashes when debuging validators in a directory path which contains other files than classes but with namespace (traits, interfaces). I will edit the first post with the error.

**Comment by xabbuh** [comment]
Does it apply to the 4.4 branch too?

**Comment by loic425** [comment]
> Does it apply to the 4.4 branch too?

No this feature was released on 5.2 :)
https://symfony.com/doc/current/validation.html#debugging-the-constraints

**Review by xabbuh — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @loic425.

**Pull request merged**
