### PR TITLE
don't implement custom serialize for Route / CompiledRoute

### PR DESCRIPTION
**Pull request by dawehner**
IMHO there is no real reason to require to have custom serialize() implementations
for Route/CompiledRoute() ... it just slows down the calls a bit.

### CODE REVIEW

**Comment by Tobion** [comment]
Please look at the discussion where this was introduced. We added it for drupal so we can keep BC when we change the internal representation. Removing it now is also a bc break.

**Comment by dawehner** [comment]
I totally remember that discussion, but IMHO this doesn't mean that we should not reavaluate what we did. Having a lot of user code which has to be executed, even we actually don't have to, is partially a bad idea, at least for me.

**Comment by Tobion** [comment]
So you would prefer to break all your serializations if we just rename a __private__ property?

**Comment by dawehner** [comment]
Well, I won't fight that, but this is a problem of every of the millions classes out there.

**Comment by dawehner** [comment]
And yes, the router is special because the route object is serialized more often

**Comment by Tobion** [comment]
As I said, please read the tickets then you would have seen symfony/symfony-docs#4380

**Pull request closed without merging**
