### PR TITLE
[DoctrineBridge] Require doctrine/persistence 2

### PR DESCRIPTION
**Pull request by greg0ire**
| Q             | A
| ------------- | ---
| Branch       | 5.x
| Bug fix      | no
| New feature  | no 
| Deprecations | no 
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

This allows us to remove autoload calls that are necessary for the
persistence 1 backwards-compatibility layer to work.

This is a follow up of #35728

### CODE REVIEW

**Comment by stof** [comment]
As there is no change in the composer.json of the doctrine bridge, you have no guarantee that doctrine/persistence 2 is actually used when using the subtree packages.

**Comment by derrabus** [comment]
Making Persistence 2.0 a requirement would basically render our codebase incompatible with ORM 2.6, correct?

**Comment by stof** [comment]
ORM 2.6 is EOL AFAICT

**Comment by greg0ire** [comment]
I think it would, but I don't think it's a big deal, for reasons pointed out by @stof

**Comment by derrabus** [comment]
Yeah, I think we're good. It's just that the Bridge's composer.json says `"doctrine/orm": "^2.6.3"` and I thought we should've at least talked about that hidden version bump. 😃

**Comment by stof** [comment]
@alcaeus is the ODM 1.3.x still maintained (and supported by a version of the bundle compatible with Symfony 5) ? Because that would also drop support for the ODM 1.3.x

**Comment by stof** [comment]
> It's just that the Bridge's composer.json says `"doctrine/orm": "^2.6.3"` and I thought we should've at least talked about that hidden version bump.

We could update that one to `^2.7.3` to avoid confusion

**Comment by greg0ire** [comment]
Should I bump the ORM constraint globally as well?

**Comment by derrabus** [comment]
@greg0ire Yes, please. The ORM version referenced there can be considered antique by now. 😅

**Comment by alcaeus** [comment]
> @alcaeus is the ODM 1.3.x still maintained (and supported by a version of the bundle compatible with Symfony 5) ? Because that would also drop support for the ODM 1.3.x

It's no longer supported, so we can start the process of dropping support for it.

**Review by stof — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
What about doing it in the 5.2 branch instead?

**Comment by greg0ire** [comment]
@fabpot you're right, done!

**Comment by chalasr** [comment]
Build failure looks unrelated but interesting https://travis-ci.com/github/symfony/symfony/jobs/444188596#L2509
//cc @xabbuh @nicolas-grekas

**Comment by nicolas-grekas** [comment]
fix welcome :)

**Comment by fabpot** [comment]
Thank you @greg0ire.

**Pull request merged**
