### PR TITLE
[CI] Show exit code when job fails

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

This is just a small small PR to show what exit code the job failed with.

### CODE REVIEW

**Comment by derrabus** [comment]
For 5.4?

**Comment by Nyholm** [comment]
Sure. I rebased on 5.4

**Review by stof — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by Nyholm** [comment]
Example how a failure looks like: 
Screenshot 2023-12-19 at 15 07 17

**Review by mtarld — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you Tobias.

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
