### PR TITLE
[Workflow] Delete dead code

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | "no"
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

---

Me (and all reviewers ;) ) totally miss this class. It has never been used and there are no reason to use it anyway. It's just a relic from the designing of the Component. Sorry.

I really don't think it deserves a deprecation as the component is quite new, and it is really some dead code.

### CODE REVIEW

**Comment by keradus** [comment]
Technically, it's a non-internal class available eg on v3.2.4, removing it is BC breaker :/

**Comment by fabpot** [comment]
👍 Not used and not documented.

**Review by nicolas-grekas — APPROVED** [review]
:+1: for the deletion, this is dead code really

**Comment by stof** [comment]
👍 for this too. It is not used, and it was *never* used (usage was removed before merging the PR). So there is no reason for external code to depend on it, assuming they discovered it.

**Pull request merged**
