### PR TITLE
add missing use statement

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | https://github.com/symfony/symfony/commit/996c1ee3cb365eb681790cd75f7ae3a4f89b5473#commitcomment-19292581 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by stof** [comment]
@xabbuh you need to rebase your branch so that it starts from 2.7 too. Otherwise, you are asking us to merge the master branch codebase into 2.7, which won't happen

**Comment by xabbuh** [comment]
@stof already done

**Comment by dunglas** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
