### PR TITLE
[WebProfilerBundle] Fix spelling of curl

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       |
| License       | MIT
| Doc PR        |

the CLU is spelled `curl`
the project is spelled `cURL`

Some references:

* https://curl.se/
* https://github.com/curl/curl
* https://twitter.com/bagder/status/1524674023224922112

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Comment by GromNaN** [comment]
That's `Copy as cURL` in Firefox/Chrome DevTools and the project owner seems to agree with that spelling.
https://daniel.haxx.se/blog/2015/11/23/copy-as-curl/

**Review by GromNaN — APPROVED** [review]
The response on twitter is clear.

> nowadays I mostly use "curl" for that as well.

**Comment by nicolas-grekas** [comment]
> That's Copy as cURL in Firefox/Chrome DevTools and the project owner seems to agree with that spelling.

We should then close this PR, isn't it?

**Comment by stof** [comment]
Based on the answer of the project owner on Twitter, I would say we should merge it.

**Comment by lyrixx** [comment]
> That's Copy as cURL in Firefox/Chrome DevTools and the project owner seems to agree with that spelling.

I wanted to send a PR on chrome too, but... I was too lazy!

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.

**Pull request merged**
