### PR TITLE
[Ldap] remove deprecated features

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
The CHANGELOG file needs an update (same for all the other PR I guess?)

**Comment by xabbuh** [comment]
changelog entries added (and I opened #22802 to actually create one for the component in the `3.2` branch)

**Comment by nicolas-grekas** [comment]
FC layer missing in 3.4?

**Comment by xabbuh** [comment]
see #22813

**Comment by xabbuh** [comment]
Tests are green. Ready to be reviewed.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
