### PR TITLE
CS: remove unneeded parentheses around control statements

### PR DESCRIPTION
**Pull request by keradus**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | ? |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by keradus** [comment]
thanks @xabbuh  ;)

**Comment by Tobion** [comment]
Thank you @keradus.

**Comment by keradus** [comment]
Thank you too @Tobion ;)

**Pull request merged**
