### PR TITLE
removed some Form related deprecation notices

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

This removes a deprecation notice.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by fabpot** [comment]
I've fixed some more thanks to Silex.

**Comment by Tobion** [comment]
:+1: 

Status: Reviewed

**Comment by nicolas-grekas** [comment]
Some tests are failing though

**Comment by stof** [comment]
yeah, tests checking these methods explicitly. they should be updated for the new returned value.

and we should probably write integration tests for these classes (using the FormIntegrationTestCase), to run the extension code from a form factory as this is where deprecations are triggered

**Comment by xabbuh** [comment]
We only enforce version 2.8 or higher of the Form component for tests in the FrameworkBundle. Shouldn't we first check the installed version of the Form component (alternatively we could add a conflict rule, but that doesn't seem to be the best solution to me)?

**Comment by xabbuh** [comment]
see #15721

**Pull request merged**
