### PR TITLE
[HttpFoundation] Add generic interface for `UploadedFile` in order to easily mock this object

### PR DESCRIPTION
**Pull request by chadyred**
Add generic interface for `UploadedFile` in order to easily mock this object to mock it through Unit Test / Spec Test more easily.

| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      |  no
| New feature?  | n
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by derrabus** [comment]
In what case would I prefer a mock over an actual instance? That being said, you can create a mock of the class without an interface, can't you?

**Comment by chadyred** [comment]
Hello,

My case is to simply do a "then" case into my test for "move" function. In fact, it is call into class (classically, an uploader class) with `UploadedFile` inject in first parameter. It seems that `PhpSpec` can't mocked `UploadedFile` and with a real instance, unfortunately, he search the Binary file.

When I create a mock (by simply injecting the typed var):

Screenshot_20210830_092158

The result:

Screenshot_20210830_091936

When I create a real instance :

Screenshot_20210830_092239

The result:

Screenshot_20210830_092252

Using an interface for a unit test purpose could be great.

Thanks ;)

**Comment by ro0NL** [comment]
im not sure how you can test a file upload based on a mock. Why not pass a real `tmpfile()` path?

**Comment by chadyred** [comment]
Sure, something like this:

```php
        $file = tmpfile();
        new UploadedFile(stream_get_meta_data($file)['uri'], 'test.pnh', null, \UPLOAD_ERR_OK, true);
```

In fact, I really just want to check  if method "move" of this object has been called, not dealing with the "how real object works" so my though is about "interface" to handle contract and doing whatever I want with this interface.

Thnks a lot !

**Comment by ro0NL** [comment]
IIUC you could provide an upload error other than `UPLOAD_ERR_OK` which will make move() throwing (for you to assert).

im not sure a representation of `A file uploaded through a form.` needs an interface, i tend to prefer a functional approach for testing. Also, why not disable the original constructor call, how would a mocked interface be different?

**Comment by chadyred** [comment]
An interface allow the choice of using a real object for functional testing purpose, or a mock for unit testing purpose. Also, one does not prevent the other with or without a constructor, tests will always works as expected :)

**Comment by ro0NL** [comment]
Im not sure we need choice :) `$this->createMock(UploadedFile::class)` works just fine isnt it? (phpunit)

**Comment by chadyred** [comment]
Great to know under `PhpUnit` it works but not for `PhpSpec` mocking system, except if we use the minimal dependency artifact in OOP : the interface, this is why it could be interesting to introduce it simply

**Comment by sstok** [comment]
PhpSpec mocks all the arguments you pass to the spec method, and all method calls are not forwarded IIRC. 
It shouldn't provide you with an actual instance, if it does however it might require a Phropecy patch for PHPSpec itself as is done for other special classes.

**Comment by fabpot** [comment]
Let's close as from what I understand from the discussion, there is no need for an interface after all.

**Pull request closed without merging**
