### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by Koc**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | wait travis |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
Do all these changes only apply to the `3.0` branch?

**Comment by Koc** [comment]
Most of them yes, because `Validation` class no more required it tests because of skipping BC layer in 3.0. Will check other.

**Comment by fabpot** [comment]
Just checked and those fixes are only for 3.0.

**Comment by fabpot** [comment]
Thank you @Koc.

**Pull request merged**
