### PR TITLE
[FrameworkBundle] Allowed symlinks when searching for translation, searialization and validation files

### PR DESCRIPTION
**Pull request by tifabien**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

When we have a symlink folder in app/Resources/translations, files inside this symlink are not handled.

### CODE REVIEW

**Comment by xabbuh** [comment]
If we want to allow symlinks here, we should do the same for the validation files. What do you think?

**Comment by tifabien** [comment]
I agree. What about serialization files?

**Comment by tifabien** [comment]
I added the followLinks on both serialization and validation files

**Comment by tifabien** [comment]
@xabbuh Is it OK for you? Note that I don't understand why the travis build is in error for PHP5.3.
Any idea?

**Comment by nicolas-grekas** [comment]
Looks like a new behavior, thus new feature to me. Am I wrong?

**Comment by xabbuh** [comment]
Agreed, to treat this as a new features.

Besides that 👍 from me.

**Comment by tifabien** [comment]
If you consider this as a new feature, do I need to rebase my branch on top of master or 3.2(as it's not released yet)?

**Comment by javiereguiluz** [comment]
New features should now go to `master` because `3.2` entered its "code freeze" period.

**Comment by tifabien** [comment]
OK for me I changed the destination branch.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @tifabien.

**Pull request closed without merging**
