### PR TITLE
[Validator] reject ill-formed strings

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13492 |
| License | MIT |
| Doc PR | - |

ping @Tobion

### CODE REVIEW

**Comment by xabbuh** [comment]
We would need the new message added to the translation file(s).

**Comment by fabpot** [comment]
@nicolas-grekas Can you add some tests?

**Comment by nicolas-grekas** [comment]
Tests and translations added, ci is green

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
