### PR TITLE
[Mailer] Fixed decode exception when sendgrid response is 202

### LINKED ISSUE #42306: SendGrid Mailer stopped working after latest update
**Symfony version(s) affected**: 5.3

**Description**
Sending e-mails via de Sendgrid mailer API transport stopped working after the latest update, I have done some digging in the commits and it seems like the following commit: https://github.com/symfony/sendgrid-mailer/commit/e6f0e4313def1a4def569b38bb06b6f7c422879b breaks sending emails.

The sendgrid API does not return a response body when sending the email has been successful, see documentation [here](https://docs.sendgrid.com/api-reference/mail-send/mail-send#responses). This causes an exception when decoding the response.

**How to reproduce**

Setup the sendgrid mailer per documentation and send an email with a 202 response

**Possible Solution**

Check that the response code before decoding the response.

* If the response code is 202, do nothing
* If the response code is an error code, decode the response and use it in the exceptions for a clear error message

### PR DESCRIPTION
**Pull request by rubanooo**
| Q             | A
| ------------- | ---
| Branch?       | 5.4 for features / 4.4, 5.2 or 5.3 for bug fixes 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #42306 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by derrabus** [comment]
We need to target 4.4, don't we?

**Comment by Nyholm** [comment]
Thank you @rubanooo for fixing this. 

Could you target branch 4.4 instead?

Im happy with the changes.

**Comment by fabpot** [comment]
I'm going to switch this PR to 4.4 while merging.

**Comment by fabpot** [comment]
Thank you @rubanooo.

**Pull request merged**
