### PR TITLE
Test with current HHVM LTS 3.18

### PR DESCRIPTION
**Pull request by photodude**
| Q             | A
| ------------- | ---
| Branch?       | 2.7+
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | no
| Tests pass?   | yes/no
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Test with current HHVM LTS 3.18
add option for testing with HHVM's php 7 mode

### CODE REVIEW

**Comment by photodude** [comment]
Should I redo at the 2.7 branch? (oldest branch testing HHVM-3.15)

**Comment by fabpot** [comment]
@photodude You can "just" change the branch of the PR.

**Comment by photodude** [comment]
@fabpot seems making that branch "switch" introduced several complex conflicts

**Comment by stof** [comment]
@photodude you also need to rebase your branch onto 2.7 (otherwise, it contains all master commits):

```bash
$ git checkout -b patch-1 origin/patch-1
$ git rebase --onto upstream/2.7 upstream/master
$ git push origin patch-1 --force-with-lease
```

**Comment by photodude** [comment]
For the moment I'll just redo with #21901 and note the issue with HHVM-3.18 #21900

**Pull request closed without merging**
