### PR TITLE
[Notifier] Sendinblue bridge missing parameters

### PR DESCRIPTION
**Pull request by drixs6o9**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

As mentioned, this [PR](https://github.com/symfony/symfony/pull/38298) has missing parameters for Sendinblue. I added them  :)

### CODE REVIEW

**Comment by fabpot** [comment]
Can you tell us what these settings are for?

**Comment by drixs6o9** [comment]
> Can you tell us what these settings are for?

According to the Sendinblue documentation : 
**type** - Type of the SMS. Marketing SMS messages are those sent typically with marketing content. Transactional SMS messages are sent to individuals and are triggered in response to some action, such as a sign-up, purchase, etc.
**tag** - Tag of the message
**webUrl** - Webhook to call for each event triggered by the message (delivered etc.)

**Comment by fabpot** [comment]
So, I'm closing this PR as we don't want to support those options specifically for one provider. If we want one of them to be supported, it should be done globally. For the `type`, it should always be configured to "transactional" as this is how we use SMSes in notifier. For `tag`, we already have a generic support for them. Finally, `webURL` is not something supported for now.

**Comment by drixs6o9** [comment]
> So, I'm closing this PR as we don't want to support those options specifically for one provider. If we want one of them to be supported, it should be done globally. For the `type`, it should always be configured to "transactional" as this is how we use SMSes in notifier. For `tag`, we already have a generic support for them. Finally, `webURL` is not something supported for now.

Ok, no problem.
I didn't know that each providers should be had same minimal integration.

**Pull request closed without merging**
