### PR TITLE
Fix CS in changelogs

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

I'm note sure it worth applying this patch on lower versions...

### CODE REVIEW

**Comment by chalasr** [comment]
For 4.4?

**Comment by chalasr** [comment]
> I'm note sure it worth applying this patch on lower versions...

I think it is :)

**Comment by jderusse** [comment]
Closing in favor of #39432

**Comment by jderusse** [comment]
Reopening as upstream have been merged. Remaining fix for 5.3 only

**Pull request closed without merging**
