### PR TITLE
Simplify AbstractVoter

### PR DESCRIPTION
**Pull request by Koc**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no, just simplification |
| BC breaks? | no, because 2.8 is not yet released |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Koc** [comment]
Does anybody know why php7 build fails?

**Comment by xabbuh** [comment]
@Koc Seems to be related to some PHPUnit bug.

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @Koc.

**Comment by TomasVotruba** [comment]
Great job!

**Pull request merged**
