### PR TITLE
[FrameworkBundle] Fix NFS detection on macOs

### LINKED ISSUE #39552: [FrameworkBundle] Second invocation of cache:clear command crashes on macOS
**Symfony version(s) affected**: `5.2.x-dev` (`5.2.1@dev`)

**Description**  

Since #39360 [the code checking if a cache dir is NFS](https://github.com/symfony/symfony/blob/ea68966e914a257c2df551160e02e658b44864cd/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L208-L224) changed a bit with respect to `v5.2.0` and unfortunately this change causes `cache:clear` command to crash on macOS

**How to reproduce**  
```
composer create-project symfony/skeleton:^5.2.1@dev
cd skeleton
php bin/console cache:clear
```
// note that the first invocation of `cache:clear` is done while creating a project

This results in the following error:
```
In CacheClearCommand.php line 220:
  Warning: Invalid argument supplied for foreach()
```

This is because `/proc/mounts` does not exist on macOS which makes `$mounts` variable `false`, while [the line 220](https://github.com/symfony/symfony/blob/ea68966e914a257c2df551160e02e658b44864cd/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L220) expects it to be an array.

**Possible Solution**  

The possible solution might be either checking if the variable is an array before iterating in the line 220 or actually using separate variable to read mounts from file since it could be `false`. 

That said, if the intention there was for NFS to work on macOS then the solution would be different (unknown to me at this point), which stopped me from providing the actual patch without Your feedback.

**Additional context**

I know this refers to an unreleased version, however per Your recommendation (https://github.com/symfony/symfony/pull/39360#issuecomment-745220524) we've upgraded [Ibexa DXP](https://github.com/ezsystems/ezplatform-ee) dev version to use that, so we can test it on v5.2. Right now it's a blocker for our developers using macOS.

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39552
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Does fix the FrameworkBundle test suite on my macbook 👍 
Thanks!

**Review by Nyholm — APPROVED** [review]
I also tried the steps to reproduce the bug defined in #39552, this patch will fix the issue.

**Comment by mnocon** [comment]
If you need another data point: this PR solves the issue on my Mac 👍

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Good catch, thanks Jérémy.

**Comment by alongosz** [comment]
Thanks @jderusse :tada:

**Pull request merged**
