### PR TITLE
[Form] Repeat preferred choices in the main list

### PR DESCRIPTION
**Pull request by Seb33300**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/10271
| License       | MIT
| Doc PR        | 

Repeat preferred choices in the main list so we can easily find them in large lists.

### CODE REVIEW

**Comment by HeahDude** [comment]
This should be a new feature.

**Comment by nicolas-grekas** [comment]
This breaks tests, which means the previous behavior was the expected one.
If this is a new feature, it should be opt-in to not break existing apps, isn't it?

**Comment by jakzal** [comment]
@Seb33300 indeed, being a new feature this should be sent to master. Are you still interested in implementing it?

**Comment by Seb33300** [comment]
Unfortunately, I don't have the time to work on this at this time.
So if someone want to work on it, feel free to do it.

**Comment by jakzal** [comment]
That's fine. Let's close for now.

**Pull request closed without merging**
