### PR TITLE
Fix checkbox bootstrap

### PR DESCRIPTION
**Pull request by gonzaloalonsod**
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Test don't pass. Also, what's the description of the issue fixed here? Any link to an existing ticket?
FYI, bug fixes should be submitted against the lowest branch where the bug exists.

**Comment by fabpot** [comment]
@gonzakpo Any news?

**Comment by gonzakpo** [comment]
I expected to consider the class .checkbox-inline
Bootstrap Checkboxes:
http://www.w3schools.com/bootstrap/bootstrap_forms_inputs.asp

**Comment by fabpot** [comment]
@gonzakpo Not sure I understand the status of this PR. Tests do not pass so something needs to be changed... or should I close it?

**Pull request closed without merging**
