### PR TITLE
check for trait as well as class and interface

### PR DESCRIPTION
**Pull request by tacman**
| Q             | A
| ------------- | ---
| Branch?       | 3.4 or master / 2.7, 2.8, 3.2 or 3.3 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #23178
| License       | MIT

### CODE REVIEW

**Comment by stof** [comment]
this won't help, because the mapping of the trait will not be loaded when asking for the mapping of the class anyway, so it does not fix the issue

**Comment by karser** [comment]
I just checked - it's true. Traits definition in serialization.yml doesn't make sense, e.g:
```
#serialization.yml
Gedmo\Timestampable\Traits\TimestampableEntity:
    attributes:
        createdAt:
            groups: [Default]
```

So workaround is either use annotations in the trait itself or specify groups for each classes that use that trait.
@stof is there an open issue for this bug?

**Comment by dunglas** [comment]
It's possible to test if a class uses a trait using the introspection API (http://php.net/manual/en/reflectionclass.gettraits.php), but I wouldn't go in this direction...

**Comment by nicolas-grekas** [comment]
Yep, :-1: also to me, a trait should be "invisible".

**Pull request closed without merging**
