### PR TITLE
[HttpFoundation] use atomic writes in MockFileSessionStorage

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39167
| License       | MIT
| Doc PR        | -

Instead of #39808

### CODE REVIEW

**Review by jderusse — COMMENTED** [review]
We should also handle concurency in read method: `is_file($filePath) ? file_get_contents($filePath)` given the file could be deleted in the meantime (see https://github.com/symfony/symfony/pull/39167#issuecomment-733531777)

**Comment by nicolas-grekas** [comment]
Unless we have reports that this happens IRL, I think we should fix as little as possible. The linked report is only about non-atomic writes. I'd wait before doing more on this topic.

**Comment by jderusse** [comment]
> Unless we have reports that this happens IRL,

I felt like the linked comment reported by @mpdude were a real case.

**Comment by nicolas-grekas** [comment]
> I felt like the linked comment reported by @mpdude were a real case.

It is, and the message there is about "Notice: unserialize()". That's unrelated to the `is_file()` check you're mentioning for now.

**Comment by mpdude** [comment]
Over [here](https://github.com/symfony/symfony/pull/39167#issuecomment-733531777), I also mentioned that the `unlink()` call may be a source of errors as well, since the file might have been deleted by another process in the meantime.

**Comment by nicolas-grekas** [comment]
OK, thanks for the link. So you have processes that concurrently destroy the session?
That cannot work of course, whatever we do here, there will always be an issue with concurrent requests that read and destroy at the same time.
You should not destroy concurrently to me.

**Comment by nicolas-grekas** [comment]
Now updated to guard against concurrent `unlink()`.

**Comment by mpdude** [comment]
Regarding @jderusse's comment above, the `is_file($filePath) ? file_get_contents($filePath)` concurrency thing could also be addressed with something like 

```php
        set_error_handler(static function () {});
        try {
            $this->data = [];
            $this->data = unserialize(file_get_contents($filePath));
        } finally {
            restore_error_handler();
        }
```

But regardless of that, :+1:  and thanks for the fix!

**Comment by nicolas-grekas** [comment]
> the is_file($filePath) ? file_get_contents($filePath) concurrency thing

code updated

**Comment by solverat** [comment]
@nicolas-grekas i just merged your PR into my largest test-set, and it's still passing! Thank you!

**Review by jderusse — APPROVED** [review]

**Review by solverat — APPROVED** [review]

**Pull request merged**
