### PR TITLE
[3.0] [Security] remove deprecated SrtingUtils class

### PR DESCRIPTION
**Pull request by TomasVotruba**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Tests depends on:

- #16393
- #16392

**Comment by Tobion** [comment]
The `StringUtilsTest` must be removed as well!

**Comment by Tobion** [comment]
Thanks for the PR. I removed the test.

**Comment by TomasVotruba** [comment]
Oh, I forgot to. Will do next time!

Thanks!

**Pull request merged**
