### PR TITLE
Process: Add methods for getting start/end/running time

### PR DESCRIPTION
**Pull request by okdana**
| Q             | A
| ------------- | ---
| Branch?       | 3.4 or master (?)
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | ?

Hope i'm doing this right. The issue template says to submit features against `3.4`, but [Submitting a Patch](https://symfony.com/doc/current/contributing/code/patches.html) says to do it again `master`. I guess it's clean either way, idk.

Anyway. In using `Process`, i found myself wanting to know how long it took (or was taking) for a process to run. Obviously you can just wrap the execution in calls to `microtime()` and calculate it yourself, but it seemed like such an obvious feature to add to `Process` itself. So that's what this does. Specifically, it adds three new methods:

* `getStartTime()` — Returns the process start time (as produced by `microtime(true)` when the process started)

* `getEndTime()` — Returns the process end time (as produced by `microtime(true)` when the process finished)

* `getRunningTime()` — Returns the process running time, either `end - start` if it's finished or `now - start` if it's still running

I wasn't sure how to write the unit tests since the exact timing depends on the environment, but i think what i settled on should be close enough.

No 'Doc PR' right now, but i think i can figure out how to put one together if this is accepted.

Please let me know if you have any concerns/suggestions.

### CODE REVIEW

**Comment by ogizanagi** [comment]
> Hope i'm doing this right. The issue template says to submit features against 3.4, but Submitting a Patch says to do it again master. I guess it's clean either way, idk.

Submitting a new feature usually is on `master` indeed, but we're now in a particular situation, as both 3.4 and 4.0 will be released on November 2017, at the same time (4.0 being the 3.4 branch, with all BC layers removed). So:
- 3.4 <=> new features, last 3.x version.
- `master` <=> 4.0 <=> 3.4 - BC layers.

The github template used for PR should have indicate this to you. In case you missed it:

> - Features and deprecations must be submitted against the 3.4,
  legacy code removals go to the master branch.

Anyway, you did right :)

**Comment by nicolas-grekas** [comment]
Why should we do this is core? This adds complexity to the interface. I'm not sure the use case is broad enough to justify it (vs calling microtime on your side as you explained).
I'm "-0" for this reason.

**Comment by okdana** [comment]
I guess it felt justified to me for the same reason it was justified for `Process` to handle time-outs itself (rather than having the user run `start()` and then check `microtime()` herself).

And it just seems like [a common thing](https://github.com/search?l=PHP&q=symfony+process+microtime&type=Code&utf8=✓) to want to know how long it took for a process to run.

On the other hand, i suppose if having to do the `microtime()` dance themselves was a big issue for people, there would have been requests for this feature before, and i don't see any.

**Comment by nicolas-grekas** [comment]
In fact, the timeout is required for the "run" method, so it's really an internal concern.
Still unconvinced sorry :)

**Comment by okdana** [comment]
np

**Pull request closed without merging**
