### PR TITLE
[Form] Fixed trimming choice values

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24247, #24712
| License       | MIT
| Doc PR        | symfony/symfony-docs#9598

Follows #24712 discussion.

### CODE REVIEW

**Comment by HeahDude** [comment]
Change documented here https://github.com/symfony/symfony-docs/pull/9598.

**Review by nicolas-grekas — APPROVED** [review]
Thanks, just one test case to add and good for me

**Comment by nicolas-grekas** [comment]
Just to reduce the BC breaking potential: what about trying the trimmed value when the non trimmed one doesn't match?

**Comment by HeahDude** [comment]
I've added a test that covers submitting a value with a white space.

I don't think we should have a double check that add some overhead in two different transformers, it would mean we may should care of deprecating that behavior in master, adding even more overhead.

You convinced me that this was a bug fix :), then I'm not in favor of having an ambiguous behavior about a match that should not be expected. It is not even possible to try to submit invalid values using a Form API from Browser Kit when playing in tests.

What about not caring about this :), but taking care of fixing the docs should be enough, WDYT?

**Review by ogizanagi — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Pull request merged**
