### PR TITLE
Release v5.2.0-RC1

### PR DESCRIPTION
**Pull request by fabpot**
**Changelog** (https://github.com/symfony/symfony/compare/v5.2.0-BETA3...v5.2.0-RC1)

 * bug #39004 [Messenger] Fix JSON deserialization of ErrorDetailsStamp and normalization of FlattenException::$statusText (@Jean85)
 * bug #38628 [DoctrineBridge]  indexBy could reference to association columns (@juanmiguelbesada)
 * bug #39021  [DependencyInjection] Optimize circular collection by removing flattening (@jderusse)
 * bug #39031 [Ldap] Fix pagination (@jderusse)
 * bug #39038 [DoctrineBridge]    also reset id readers (@xabbuh)
 * feature #39032 [Validator] Allow load mappings from attributes without doctrine/annotations (@derrabus)
 * feature #39022  [FrameworkBundle] Allow to use attribute-based configuration of routing/serializer without doctrine/annotations (@derrabus)
 * bug #39002 [Validator] Override the default option of the choice constraint (@benji07)
 * bug #39026 [Messenger] Fix DBAL deprecations in PostgreSqlConnection (@chalasr)
 * bug #39025 [DoctrineBridge] Fix DBAL deprecations in middlewares (@derrabus)
 * bug #38991 [Console] Fix ANSI when stdErr is not a tty (@jderusse)
 * bug #38980 [DependencyInjection] Fix circular reference with Factory + Lazy Iterrator (@jderusse)
 * bug #38986 [DoctrineBridge] accept converting Uid-as-strings to db-values (@nicolas-grekas)
 * feature #38850 [Messenger] Do not call getQueueUrl when the url is known in AmazonSqs transport (@jderusse)
 * feature #38940 [Messenger] Improve formatting of exception in failed message (@Jeroen Noten)
 * feature #38954 [HttpFundation][FrameworkBundle] Deprecate the HEADER_X_FORWARDED_ALL constant (@jderusse)
 * bug #38977 [HttpClient] Check status code before decoding content in TraceableResponse (@chalasr)
 * bug #38971 [PhpUnitBridge] fix replaying skipped tests (@nicolas-grekas)
 * bug #38910 [HttpKernel] Fix session initialized several times (@jderusse)
 * bug #38882 [DependencyInjection] Improve performances in CircualReference detection (@jderusse)
 * bug #38950 [Process] Dont test TTY if there is no TTY support (@Nyholm)
 * bug #38921 [PHPUnitBridge] Fixed crash on Windows with PHP 8 (@villfa)
 * feature #38919 [Console] Make error message more verbose (@Nyholm)
 * bug #38869 [SecurityBundle] inject only compatible token storage implementations for usage tracking (@xabbuh)
 * feature #38859 [HttpFoundation] Deprecate not passing a `Closure` together with `FILTER_CALLBACK` to `ParameterBag::filter()` (@nicolas-grekas)
 * bug #38894 [HttpKernel] Remove Symfony 3 compatibility code (@derrabus)
 * bug #38888 remove reflection-docblock from mime requirements (@garak)
 * bug #38895 [PhpUnitBridge] Fix wrong check for exporter in ConstraintTrait (@alcaeus)
 * bug #38879 [Cache] Fixed expiry could be int in ChainAdapter due to race conditions (@phamviet)
 * bug #38867 [FrameworkBundle] Fixing TranslationUpdateCommand failure when using "--no-backup" (@liarco)
 * bug #38856 [Cache] Add missing use statement (@fabpot)

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Anyone else having issues upgrading? Im hitting PHP Memory limits (even when memory_limit=8G) just trying to start the Symfony console `php bin/console` after upgrade ... early days I guess...

**Comment by Jean85** [comment]
No issues here.

**Comment by jderusse** [comment]
> Anyone else having issues upgrading? Im hitting PHP Memory limits (even when memory_limit=8G) just trying to start the Symfony console `php bin/console` after upgrade ... early days I guess...

maybe related to https://github.com/symfony/symfony/issues/39015

can you share your project? or a reproducer?

**Comment by PhilETaylor** [comment]
@jderusse Forked to https://github.com/symfony/symfony/issues/39056 with reproducer.

**Pull request merged**
