### PR TITLE
[DependencyInjection] fix tests

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

#FOSSHackathons #EUFOSSA

### CODE REVIEW

**Review by Simperfit — APPROVED** [review]

**Comment by fabpot** [comment]
@xabbuh There is still one failing test. Can you have a look?

**Comment by xabbuh** [comment]
I am going to check.

**Comment by xabbuh** [comment]
finally green \o/

**Comment by Simperfit** [comment]
great !

**Review by lyrixx — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
