### PR TITLE
[Bridge][Monolog] Add intruction about 'ResetLoggersWorkerSubscriber deprecation' in main UPGRADE-5.4.md

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       |
| License       | MIT
| Doc PR        |

I forgot to edit this file in my previous PR. I'm not sure If it should tho. So feel free to close it if it's not required

### CODE REVIEW

**Comment by chalasr** [comment]
`UPGADE-6.0` also needs an entry about the removal, right?

**Comment by lyrixx** [comment]
I did it in https://github.com/symfony/symfony/pull/43405, is it OK?

**Comment by chalasr** [comment]
The UPGRADE-6.0 entry should be moved here (but not the CHANGELOG one)

**Comment by lyrixx** [comment]
OK, it should be OK now (and the other PR too)

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
