### PR TITLE
Fix #33395 PHP 5.3 compatibility

### LINKED ISSUE #33395: phpunit-bridge 3.4 is incompatible with PHP 5.3 the come back
**phpunit-bridge version(s) affected**: 3.4.31

The following code has been added but is not compatible with the supposed minimal version of PHP 5.3:
```php
self::$isAtLeastPhpUnit83 = class_exists(ErrorHandler::class) && method_exists(ErrorHandler::class, '__invoke');
```

Replace `ErrorHandler::class` with `'PHPUnit\Util\ErrorHandler'`

Please consider adding a Travis-CI build to check the compatibility before tagging version. Maybe just a linting of files to check static syntax compatibility.

If you wish, I could try to add it.

### PR DESCRIPTION
**Pull request by kylekatarnls**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #33395
| License       | MIT

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by michaljusiega** [comment]
The minimum version of SF 3.4 isn't PHP 5.3 or I forgot something?

**Comment by kylekatarnls** [comment]
The minimum compatibility of symfony/phpunit-bridge is PHP 5.3

**Comment by kylekatarnls** [comment]
I used ^3.4 in my Travis-CI test for PHP 5.3 and it suddenly broke with the version 3.4.31.

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @kylekatarnls.

**Comment by kylekatarnls** [comment]
A pleasure to help as it's a pleasure to use Symfony.

**Comment by fmonts** [comment]
Supporting EOL PHP versions should be considered a security vulnerability and fixed IMHO

**Comment by stof** [comment]
@fmonts symfony/phpunit-bridge is about running tests. Allowing other projects supporting these PHP versions to use our uptodate test tool is actually *reducing* our maintenance burden.
And being a test tooling, the argument of PHP 5.3 being unmaintained and so being insecure does not hold (you won't use symfony/phpunit-bridge in production)

**Pull request merged**
