### PR TITLE
[Form] remove deprecated date types options handling

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Looks like failures are related, isn't it?

**Comment by xabbuh** [comment]
see #31780

**Comment by xabbuh** [comment]
I was wrong. All jobs are green now.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
