### PR TITLE
[Dotenv] Add comment to `parse()` method

### PR DESCRIPTION
**Pull request by Elikill58**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| Deprecations? | no
| License       | MIT

Add a way to get parsed values for the given `.env` file. Help to parse env files without needing to change `$_ENV` variables.

### CODE REVIEW

**Comment by sstok** [comment]
FYI: When you use public methods to read the file (with the exception of `parse()`) the ENV variables are already set and overwritten, if you only need the values without setting `$_ENV` it's possible to use `parse()`.

**Comment by Elikill58** [comment]
> FYI: When you use public methods to read the file (with the exception of `parse()`) the ENV variables are already set and overwritten, if you only need the values without setting `$_ENV` it's possible to use `parse()`.

Oh, when checking for this, the doc wasn't saying what were returned. After seeing this, my PR becomes quitely useless and should more be about return content.

**Comment by sstok** [comment]
I checked the source code as that's the only source (no pun 😄 ) of truth.

**Comment by Elikill58** [comment]
So, should I edit doc, close the PR or it's even a good PR?

**Comment by GromNaN** [comment]
You can update the PR to modify the comment on `parse`, to something like "Parses the contents of a .env file and returns the variables it contains as a map."

Your branch can be reset on 6.4

**Review by nicolas-grekas — COMMENTED** [review]
I'd suggest changing L220 instead of adding an annotation.
Or doing nothing :)

**Comment by Elikill58** [comment]
> I'd suggest changing L220 instead of adding an annotation. Or doing nothing :)

`@return` annotation are not made for this?
Also yes, actually it were faster you add a line than I made my PR and ask for reviews xd I prefer to nothing than add a line into a comment while there is an annotation made for this

**Comment by nicolas-grekas** [comment]
Adding the annotation would duplicate the information that's already in the title of the phpdoc. Duplication leads to increased maintenance.

Let's close then.

**Pull request closed without merging**
