### PR TITLE
Fix typo in VarDumper README

### PR DESCRIPTION
**Pull request by WouterSioen**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍 

@WouterSioen very nice catch! Thanks.

**Comment by nicolas-grekas** [comment]
Thank you @WouterSioen.

**Comment by WouterSioen** [comment]
How could I know this had to be PR'ed to 2.7 instead of master?

**Comment by nicolas-grekas** [comment]
Because 2.7 is still maintained, and the patch applies there :)

**Comment by WouterSioen** [comment]
ok, good to know. If I find more stuff, I'll try to PR to the right branch.

**Pull request closed without merging**
