### PR TITLE
[HttpKernel] Remove time-sensitivity from `InlineFragmentRendererTest`

### PR DESCRIPTION
**Pull request by herndlm**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | N/A 
| License       | MIT
| Doc PR        | N/A 

I noticed this test failing in #42823 and this is my attempt to remove the time-sensitivity there.

### CODE REVIEW

**Comment by herndlm** [comment]
Is there a better way to compare ignoring parts? This is the best I could come up with..

**Comment by herndlm** [comment]
Strange, I don't understand why the 7.4 high-deps test would still fail comparing those responses. I tested locally with a sleep to be sure this works 🤔

Update: this must be because of how the high-deps work which I did not fully understand yet.. Would be great if exactly that error is not happening any more after this PR got merged.

Update2: I think I got it now. The high-deps mean in this context that checks are done with my branch as dependency using Symfony 3.4. So even if this PR gets merged, the high-deps CI job for 4.4 PRs might still make problems hmm.
I guess trying to remove time-sensivity by not comparing timestamps, especially if they are floats, does make sense. But I was hoping to fix the 4.4 high-deps failures :/

**Review by nicolas-grekas — APPROVED** [review]
(the failure are false positives when testing 3.4 with patched deps)

**Comment by nicolas-grekas** [comment]
Any idea why these tests fail? Does that follow a recent PR?

**Comment by herndlm** [comment]
> Any idea why these tests fail? Does that follow a recent PR?

no clue unfortunately, I did not further look into it. I just saw that failure in 4.4 PRs and thought "oh, something time-sensitive, let's fix it" :/

**Comment by chalasr** [comment]
Closing in favor of https://github.com/symfony/symfony/pull/43264. Thank you for the PR.

**Pull request closed without merging**
