### PR TITLE
Revert "feature #20973 [DI] Add getter injection (nicolas-grekas)"

### PR DESCRIPTION
**Pull request by nicolas-grekas**
This reverts commit 2183f98f5482096ead88e9d251c6283fca067174, reversing
changes made to b465634a55c2faa0e7e52142adfdd742a3797f54.

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no (master only)
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Let's remove getter injection, we now have enough alternative mechanisms to achieve almost the same results (e.g. `ServiceSubscriberInterface`, see #21708)., and I'm tired being called by names because of it.

The only use case in core is `ControllerTrait`, but this should be gone if #22157 is merged.

### CODE REVIEW

**Comment by iltar** [comment]
> and I'm tired being called by names because of it.

People have no respect it seems.

**Comment by sstok** [comment]
On the bright side we now have much better alternatives 😃 Great work @nicolas-grekas !

**Comment by Koc** [comment]
Thank you for rewerting it. Generating proxy classes for services looks so strange

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
