### PR TITLE
[Form] Updated the source text and translation

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

I noticed that the source text had changed. See the [English version](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Resources/translations/validators.en.xlf)

Ping @magnusnordlander or @vinkla, Is this translation okey?

### CODE REVIEW

**Comment by xabbuh** [comment]
should be merged into the `2.7` branch

**Comment by vinkla** [comment]
Maybe we should remove `in` from the sentence?
```diff
- Försök att skicka in formuläret igen.
+ Försök att skicka formuläret igen.
```

Also, not sure about the token translation. Is `CSRF-symbol` the correct word here?

**Review by nicolas-grekas — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you for the comments and feedback. I've updated the PR and changed the base. 

"CSRF-symbolen" is way wrong. I could only come up with some other translations. 

* "CSRF-token" but that is not really Swedish....
* "CSRF-elementet" (en: element) which is abstract but kind correct
* "CSRF-tecknen" (en: chars) which is more correct but also very confusing.

**Comment by fabpot** [comment]
Thank you @Nyholm.

**Pull request merged**
