### PR TITLE
[TwigBundle] return the correct response code in ExceptionController …

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Bug fix?      | yes
| New feature?  | no
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
Tests are now failing. Can you please explain the reason for this change?

**Comment by ShinDarth** [comment]
This is just an example: in my specific case I was trying to [replace all 403 access denied responses with 404 ones](http://stackoverflow.com/questions/40398236/how-to-replace-all-403-status-codes-with-404-in-symfony), and I used the ``ExceptionController`` class in order to accomplish it.

- **Before this PR change**: the `$code` was passed only to the template, so you got inconsistencies between what the template was saying and what the actual response was.

before

Note that the template is showing **404**, but the actual response is **403**.


- **After this PR change**: both the template and actual response show the same value.

after

**Comment by iltar** [comment]
So what happens if you don't give a status code to your exceptions?

**Comment by ShinDarth** [comment]
@iltar in my specific case, explained above, it defaults to 403.

**Comment by iltar** [comment]
@ShinDarth but that's not the behaviour I'd expect. The default behaviour changing is a BC break

**Comment by fabpot** [comment]
This change is not valid

**Pull request closed without merging**
