### PR TITLE
[Validator] Add missing Russian and Ukrainian translations

### PR DESCRIPTION
**Pull request by Koc**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

~~Some of this translations could be missing in 4.2 also, but [support of Symfony 4.2](https://symfony.com/roadmap/4.2) ends in two weeks, so I think nobody cares about missing translations in it.~~

@peter-gribanov , @vudaltsov , @insidestyles, @stfalcon please, check also provided translations

### CODE REVIEW

**Comment by fabpot** [comment]
All translations are merged into 3.4 (even for translations that are not needed for 3.4).

**Comment by Koc** [comment]
@fabpot  So should I open PR against 4.4 branch to embed translation for #32435 also?

**Comment by fabpot** [comment]
The translation for #32435 should be done in 3.4  as well

**Comment by Koc** [comment]
Rebased on 3.4

**Review by vudaltsov — APPROVED** [review]
I approve the Russian part.

**Comment by fabpot** [comment]
Thank you @Koc.

**Review by peter-gribanov — COMMENTED** [review]
Russian translation is good :+1:

**Pull request merged**
