### PR TITLE
allow to install with symfony 3.1 and newer

### PR DESCRIPTION
**Pull request by dbu**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
-1 for that. All our 2.8.x components only allow 3.0.x of other components rather than the full 3.x series, and we should stay consistent.

You should simply avoid using the deprecated symfony/locale component (for LuneticsLocaleBundle, see my comment in the issue btw)

**Comment by dbu** [comment]
if that is by design, then indeed we should leave as is. the problem is that you simply get a composer update error and no explanation why it did not work, so its not great DX. allowing it to install and then trigger deprecation warnings would be more convenient.

**Comment by stof** [comment]
@dbu ``composer why-not`` can explain you why it won't install.

Regarding deprecation warnings, they were already triggered since the 2.8 release, and projects are expected to migrate to 2.8 first to see deprecations before moving on to 3.0 and 3.1. This is not a new deprecation

**Comment by Tobion** [comment]
I think I know now how it changed in the master branch: https://github.com/symfony/locale/blob/master/composer.json#L20
It was probably changed for all components and only later the locale component got removed from 3.0.

So I think the master branch in https://github.com/symfony/locale should be deleted. Otherwise it can be misused and is out-of-sync with symfony/symfony.

**Comment by stof** [comment]
@fabpot could you remove this branch ?

**Comment by dbu** [comment]
thanks for the clarifications.

**Comment by fabpot** [comment]
The master branch of symfony/locale is now removed.

**Comment by stof** [comment]
@fabpot can you also mark the package as abandonned on Packagist, as it only contains deprecated classes ?

**Comment by Tobion** [comment]
`symfony/icu` should be marked as abandonned as well.

**Comment by fabpot** [comment]
Done for both.

**Pull request closed without merging**
