### PR TITLE
Allow to use all tags with private services

### PR DESCRIPTION
**Pull request by GuilhemN**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | https://github.com/symfony/symfony/pull/18101 |
| License | MIT |

This PR allows to register private event listeners/subscribers, private form extensions and private fragment renderers.

### CODE REVIEW

**Comment by sstok** [comment]
:-1: This looks a really weird hack for something that can be resolved easily.

**Comment by Ener-Getick** [comment]
@sstok The reason of this PR is that it looks strange to me to force users to have public services for an internal reason that might change in the future.
Maybe a better solution would be to make the services public instead.

**Comment by sstok** [comment]
Making them public would indeed be a better solution :+1:

**Comment by Ener-Getick** [comment]
@sstok updated

**Comment by sstok** [comment]
Status: Works for me

**Comment by Ener-Getick** [comment]
@sstok I forgot some changes, they are fixed now.

**Comment by nicolas-grekas** [comment]
I don't get this PR: if one did set a service as private, what a surprise that it becomes public automatically just because it's used somewhere, don't you think?

**Comment by stof** [comment]
I'm also -1 on this, for the reason given by @nicolas-grekas

**Comment by javiereguiluz** [comment]
I'm closing it because two core members voted against it and provided compelling reasons, so we cannot merge it.

@Ener-Getick thanks anyway for submitting this contribution and hopefully next time we'll merge it.

**Comment by Ener-Getick** [comment]
@nicolas-grekas @stof marking a service as private means that it may not be accessible by the Container::get() method but there is no certitude so for me this attribute is mainly here to tell the developer "hey, you have to inject me, you should not fetch me from the container". 
So I don't get your point, for me an user wants his services to be marked as private in his configuration files but it doesn't matter how it is treated internally.

**Comment by jvasseur** [comment]
BTW we already set some service as public in a compiler pass for doctrine listeners : https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php#L124

**Comment by stof** [comment]
@jvasseur and IMO, this is a mistake.

**Pull request closed without merging**
