### PR TITLE
[TraceableAccessDecisionManager] fixed voter enumerations

### PR DESCRIPTION
**Pull request by sarbanha**
Removed the "if" statement that verifies if the ADM is instance of AccessDecisionManager.

This control breaks profiler when it is trying to browse "Security" tab while a custom ADM was developed. The reason is that the "if" statement prevents SecurityDataCollector.php to retrieve the strategy and the list of voters.

Based on my tests this modification doesn't affect the regular functionality of security-core.

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #...
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by chalasr** [comment]
Please rebase your PR against 6.1 https://symfony.com/doc/current/contributing/code/pull_requests.html#rebase-your-pull-request

**Comment by chalasr** [comment]
Overall, the current code is far from being "clean" as it is altering properties of a concrete class via reflection + duck-typing, and this would obviously make it worse. I mean, if we want to make this more flexible, I think we should do it with a proper type-based solution.

**Comment by wouterj** [comment]
> I mean, if we want to make this more flexible, I think we should do it with a proper type-based solution.

Or, at least, check `property_exists` before reflecting them.

**Comment by sarbanha** [comment]
Thanks everyone, in this PR I just modified a single file. Probably the worst thing I did was I made modification through GitHub web. I will pull the code and re-submit the PR

**Comment by derrabus** [comment]
All right, please open a new PR whenever you're ready.

**Pull request closed without merging**
