### PR TITLE
[Form] Add some phpdocs for IDE autocompletion and better SCA

### PR DESCRIPTION
**Pull request by Koc**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

@ogizanagi I've tryed add single phpdoc `@method FormInterface[] getIterator()` to `FormInterface` but it not works correctly in PHPStorm. Have you any ideas?

### CODE REVIEW

**Comment by ogizanagi** [comment]
Sadly I don't. The solution you mentioned would only work if the `FormInterface` was implementing `IteratorAggregate`.

**Comment by ro0NL** [comment]
Maybe deprecate implementing `\Iterator` (i rarely do that nowadays). And favor `\IteratorAggregate` instead.

FormInterface extending from Traversable is a bit weird;

> Abstract base interface that cannot be implemented alone. Instead it must be implemented by either IteratorAggregate or Iterator.

So now form interface is the abstract base interface; i dont see a real need for that.

**Comment by Koc** [comment]
@ro0NL where can I add deprecation notices if form implements `Iterator`? Maybe `Form::add()`,  I can work on it on separate PR.

**Comment by ro0NL** [comment]
I think everywhere right before we rely on $form to be foreached. In that case if it's an \Iterator you should get a deprecation.

**Comment by Koc** [comment]
@ro0NL see https://github.com/symfony/symfony/pull/23634

**Comment by ogizanagi** [comment]
Sorry @Koc , I didn't answer @ro0NL's suggestion. I don't think we should #23634 is needed.
`FormInterface` extends from `\traversable`, it's behavioral. There is no reason we should enforce the implementation to be `\Iterator` or `\IteratorAggregate`. Moreover, it should not just be by reasoning about STA.

**Comment by ro0NL** [comment]
> There is no reason we should enforce the implementation to be \Iterator or \IteratorAggregate. Moreover, it should not just be by reasoning about SCA.

Sorry if i got it going too fast :) though i like the _problem_ it solves; i have no real opinion if this is worth it or so. But thats what a PR is for.. to find out :)

**Review by ogizanagi — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Koc.

**Pull request merged**
