### PR TITLE
add and correct armenian translations

### PR DESCRIPTION
**Pull request by azatyan**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | none |
| License | MIT |
| Doc PR | none |

### CODE REVIEW

**Comment by azatyan** [comment]
Added description.

**Comment by fabpot** [comment]
Are you sure we need to use `:` instead of `.` here?

**Comment by azatyan** [comment]
Yes @fabpot  in armenian language the sentence full stop sign is "։" http://unicode-table.com/en/0589/

**Comment by roubenz** [comment]
+ @azatyan is right.

**Comment by jakzal** [comment]
`src/Symfony/Component/Form/Resources/translations/validators.hy.xlf` also needs to be updated.

**Comment by fabpot** [comment]
Thank you @azatyan.

**Pull request closed without merging**
