### PR TITLE
[Yaml] fix indented line handling in folded blocks

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #9105 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
ping @symfony/deciders

**Comment by fabpot** [comment]
This one needs to be rebased.

**Comment by xabbuh** [comment]
@fabpot rebased here

**Comment by xabbuh** [comment]
failures are not related (see #17071)

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
