### PR TITLE
[DependencyInjection] fix parsing calls of methods named "method"

### LINKED ISSUE #40349: YAML service configuration cannot call a method called "method"
**Symfony version(s) affected**: 5.2.3

**Description**
If a service has a method called ***method***, such as [Zebra_Pagination](https://stefangabos.github.io/Zebra_Pagination/Zebra_Pagination/Zebra_Pagination.html#methodmethod) has, it is not possible to declare calls to such a method in YAML.

**How to reproduce**
```yaml
services:
  Zebra_Pagination:
    class: Zebra_Pagination
    calls:
      - method:
        - url
      - padding:
        - false
```

Note the call syntax is correct because the call to `padding()` alone (and others) succeeds, only the call to `method()` fails because Symfony interprets the configuration differently for a key called `method` for some (legacy?) reason.

The specific error thrown is:
>Invalid service "Zebra_Pagination": method "url()" does not exist.
>dependency-injection\Compiler\AbstractRecursivePass.php (line 186)

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40349
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by Bilge — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you Christian.

**Comment by Bilge** [comment]
How will this be delivered to the 5.x branch?

**Comment by derrabus** [comment]
> How will this be delivered to the 5.x branch?

By utilizing the mystic powers of the `git merge` command. 🧙🏻‍♂️

We periodically merge changes from lower branches up.

**Comment by Bilge** [comment]
Right, but what I mean is, which version will it appear in? A minor or patch version?

**Comment by xabbuh** [comment]
it will be part of the next patch releases of 4.4 and 5.2 as well as 5.3.0 (when it's finally released)

**Pull request merged**
