### PR TITLE
[Messenger] do not listen to signals if the pcntl extension is missing

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
caused by the changes done in #49539, previously we exited early when the `pcntl_signal()` function was missing

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Could the failing integration test be related?
> 1) Symfony\Component\Messenger\Bridge\Amqp\Tests\Transport\AmqpExtIntegrationTest::testItReceivesSignals
> RuntimeException: Expected output never arrived. Got "" instead.

It's not on the latest 6.3 run.

**Comment by xabbuh** [comment]
I am looking into the failure

**Comment by lyrixx** [comment]
There is a competitive PR

https://github.com/symfony/symfony/pull/50787

**Comment by xabbuh** [comment]
@nicolas-grekas tests fixed

@lyrixx This PR fixes an issue when this listener is registered by the FrameworkBundle 5.4, but the pcntl extension is missing. I don't see how this is being fixed by the linked PR.

**Comment by lyrixx** [comment]
ah okay, I confused.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
