### PR TITLE
Don't cap the exit code of commands

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13996 |
| License | MIT |
| Doc PR | - |

I haven't added a test because it would require `setAutoExit(true)`

### CODE REVIEW

**Comment by Tobion** [comment]
:+1: 
Status: Reviewed

**Comment by stof** [comment]
This would mean that an exception code of 256 would return a success exit code 0 when masking it. this looks wrong to me.

**Comment by Tobion** [comment]
Status: Needs Work

**Comment by javiereguiluz** [comment]
@stof in the original discussion, the agreement was: let's do nothing on Symfony side ... and let PHP and the Operating System deal with this. Is that assumption wrong?

**Comment by stof** [comment]
The issue is that PHP lets ``exit(256)`` become a success exit code (use any multiple as well). So changing this would be a BC break by introducing a bug in any project currently unaffected by the PHP edge case.

**Comment by javiereguiluz** [comment]
I'm not sure what to do with this. Revert the changes? Add some special treatment for `256` value? Thanks.

**Comment by Tobion** [comment]
Maybe it's the best to not change it. I mean adding special treatment for 256 and every multiple is just as hacky as capping at 255.

**Comment by javiereguiluz** [comment]
Closing it. I agree with @Tobion.

**Pull request closed without merging**
