### PR TITLE
Catch \Throwable

### PR DESCRIPTION
**Pull request by fprochazka**
| Q | A |
| --- | --- |
| Branch? | 2.7, 2.8, 3.0 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | Yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Related symfony/symfony#18765, symfony/symfony#15949
Depends on symfony/symfony#18812

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by xabbuh** [comment]
👍

**Comment by fabpot** [comment]
Thank you @fprochazka.

**Comment by patrick-mcdougle** [comment]
According to the PHP documentation:
>PHP classes cannot implement the Throwable interface directly, and must instead extend Exception.
Are we sure this change is needed?

**Comment by fprochazka** [comment]
> Are we sure this change is needed? 

Yes it is. Theese cases would normally be handled using finally, but since this branch supports PHP 5.3, it has to be done like this.

> Additionally, what does this do when php < 7?

it is ignored

**Comment by patrick-mcdougle** [comment]
I guess what I mean is that everything would be caught by the above `catch(\Exception)` block since all \Throwable MUST extend \Excpetion.

**Comment by xabbuh** [comment]
@patrick-mcdougle The `Error` class (introduced in PHP 7) implements `Throwable` but does not extend the `Exception` class.

**Comment by patrick-mcdougle** [comment]
Thanks for the explanation @xabbuh !

**Pull request merged**
