### PR TITLE
[DI] Anonymous services support for YamlFileLoader

### PR DESCRIPTION
**Pull request by prgTW**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Example:

``` yaml
services:
    first:
        class: FooClass
        arguments: [ { type: service, class: BazClass } ]
    second:
        class: FooClass
        arguments:
            - type: service
              class: BazClass
            - type: service
              class: BarClass
```

### CODE REVIEW

**Comment by SongoQ** [comment]
:+1:

**Comment by sstok** [comment]
This is a BC break as an argument can also an array, and there is no way to determine if it is in fact an array with the key 'type' or a service definition.

**Comment by prgTW** [comment]
You re right, it's a BC break. IMHO I'm introducing a convention here which is similar to @/@@/@?/@= notation. I wanted to do it as similar as it could be comparing with XML format and thus having steep learning curve

**Comment by iltar** [comment]
I can understand the need for this, but I don't think this current implementation is the correct one.

Can you add some more information about what you're changing and why you're changing it? It will help people to understand the PR a lot better.

**Comment by stof** [comment]
-1 on the current implementation. Such BC break is impossible. It is far too big (imagine the case where you inject an array in your service without knowing its content as it comes from the user config)

**Comment by xabbuh** [comment]
Status: Needs work

**Comment by fabpot** [comment]
Closing as it cannot be merged and I don't see a huge benefit in being able to create anonymous services in userland. For core and bundles, it's recommended to use XML anyway where anonymous services are supported.

**Comment by GuilhemN** [comment]
I opened https://github.com/symfony/symfony/pull/21970 which allows anonymous services in yaml using the `!service` tag.

**Pull request closed without merging**
