### PR TITLE
Fix Lock test suite

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | na
| License       | MIT
| Doc PR        | na

### CODE REVIEW

**Comment by chalasr** [comment]
Still failing :) https://travis-ci.org/symfony/symfony/jobs/516770133#L4050

**Review by chalasr — APPROVED** [review]

**Review by lyrixx — APPROVED** [review]

**Comment by fabpot** [comment]
Tests are still broken apparently.

**Comment by sroze** [comment]
Still failing on `deps=high`:
```
1) Symfony\Component\Lock\Tests\Store\StoreFactoryTest::testCreateStore with data set #7 ('memcached://server.com', 'Symfony\Component\Lock\Store\...dStore')
Error: Class 'Symfony\Component\Cache\Adapter\AbstractAdapter' not found
```

**Comment by jderusse** [comment]
code changed  @approvers: (check if the Adapter exists)

**Comment by fabpot** [comment]
Thank you @jderusse.

**Pull request merged**
