### PR TITLE
[Form] DoctrineType, Add widget property to avoid retrieving the whole ChoiceList

### PR DESCRIPTION
**Pull request by RapotOR**
Todo : 
- add some tests
- Replace queryBuilder by generic EntityLoader

The PR gives a different approach of the PR #1951. Please read the discussion.

The same approach is used for DateType (regarding the widget property).
The entity is retrieved from the the hidden (or another type) field contained in the entitype (which is form and not choice anymore in this case).

How it works?
- If the widget is not `choice`, the `ChoiceList` is not loaded anymore; very useful for a huge table.
- If the `property` is given, a second field is added
- The ID field's type will be the `widget` value (maybe a retriction to hidden or text?) .

The idea is :

```
    $builder->add('city', 'entity', array(
        'class'             => 'Acme\DemoBundle\Entity\City',
        'property'          => 'name',
        'widget'            => 'text',
        'required'          => false
    ));
```

Bug fix: no
Feature addition: yes
Backwards compatibility break: no
Symfony2 tests pass: yes
Fixes the following tickets: #1951, #1946

### CODE REVIEW

**Comment by ahmed-bhs** [comment]
@webmozart @Narretz @RapotOR I'm on a Symfony 2.5 project, what should be the solution to avoid retrieving the whole ChoiceList ?  Cheers!

**Comment by dbrumann** [comment]
I don't mean to be rude, but the last comment is from April 2013 and Symfony 2.5 has not been supported for ages. You should seriously consider upgrading your project to a supported version.

**Comment by ahmed-bhs** [comment]
@dbrumann Thank you for your answer, Nah, no problem, could you please provide me the solution for an upgraded version of symfony?

**Comment by dbrumann** [comment]
You can use a custom query to fetch the entities, see [EntityType Field in the docs](https://symfony.com/doc/4.4/reference/forms/types/entity.html#using-a-custom-query-for-the-entities)

**Comment by derrabus** [comment]
Please consider using our support channels for this! Thank you!

https://symfony.com/support

**Pull request closed without merging**
