### PR TITLE
[Finder] added Finder::extract()

### PR DESCRIPTION
**Pull request by ro0NL**
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | ~ |
| Fixed tickets | #19075 |
| License | MIT |
| Doc PR | ~ |

Should i add tests? :-)

### CODE REVIEW

**Comment by fabpot** [comment]
How is different/better than the existing `filter()` method?

**Comment by ro0NL** [comment]
The (custom) filters is about [accepting](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Finder/Iterator/CustomFilterIterator.php#L51) the elements yes/no. This is more of a `map` function i guess, nevertheless the difference is it yields the current iterator rather than wrapping it (which wouldnt make sense for `map`), ie;

```php
$a = Finder::create()->in(__DIR__)->filter(function ($file) {
    return $file->getSize() > 0;
});
$b = Finder::create()->in(__DIR__)->filter(function ($file) {
    return $file->getOwner() === getmyuid();
});
// vs.
$finder = Finder::create()->in(__DIR__);
$a = $finder->extract(function ($file) {
   return $file->getSize();
});
$b = $finder->extract(function ($file) {
   return $file->getOwner();
});
```

Note this is not necessarily needed for #19075 , because afaik this works [out of the box](https://github.com/symfony/symfony/issues/19075#issuecomment-226926050), although it's not explicitly supported from the `Finder` pov (ie. i havent tested all native filesystem functions for `__toString` support). Maybe the `Finder` should force the to string conversion, just to be sure..

**Comment by fabpot** [comment]
This is IMO out of the scope of the Finder component.

**Comment by ro0NL** [comment]
@fabpot guess i have to agree for the `Finder` class, can be added somewhere in userland anyway.

What about (official) support for the `Finder` in conjunction with the `Filesystem` class? Do we expect it to work in all cases?

**Comment by ro0NL** [comment]
Replaced by #19132

**Pull request closed without merging**
