### PR TITLE
[2.6][FIX]Adding a space between the icon and the error message

### PR DESCRIPTION
**Pull request by ghost**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Adding a space between the icon and the error message

### CODE REVIEW

**Comment by dosten** [comment]
Do you have a screenshot?

**Comment by dosten** [comment]
You need to update `Symfony\Bridge\Twig\Tests\Extension\FormExtensionBootstrap3LayoutTest::testErrors`

**Comment by stof** [comment]
The change looks good, once you fix the tests

**Comment by pborreli** [comment]
:+1: looks the way it should be, but what about people already implementing the wrong way, if they fixed it with css for example.

**Comment by nicolas-grekas** [comment]
Closing in favor of #14557 because this PR has a ghost owner

**Pull request closed without merging**
