### PR TITLE
fix: Response status code from start() of GuardAuthenticator is ignored

### PR DESCRIPTION
**Pull request by ant5**
| Q             | A
| ------------- | ---
| Branch?       | to be confirmed
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29657 
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by fabpot** [comment]
As I said on the other PR, can you add some tests?

**Comment by ant5** [comment]
If you point me to file with GuardAuthenticator tests, may be.

**Comment by nicolas-grekas** [comment]
This is patching `src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php`
so the test case should be added in `src/Symfony/Component/Security/Tests/Http/Firewall/ExceptionListenerTest.php`
Can you please check on which branch the issue exists?
You submitted it against master, but if it exists also in 3.4 or 4.2, we're going to merge it there.
Thanks.

**Comment by ant5** [comment]
The issue exist in 4.2. I don't know about 3.4. I have no installation of symfony 3 and I think that just looking in code is not enough because of different logic.
As for test I'll try to add the case but it takes some time.

**Comment by Simperfit** [comment]
@ant5 I can check for 3.4 and write the test if you want too ;). I will just add a commit to this PR.

**Comment by ant5** [comment]
I'm stuck on trying to get executable phpunit. In src/Symfony/Component/Security/Http there is no phpunit in composer.json. So I don't know how to run tests.

However, it seems that simple test for custom response may look like:

```
diff --git a/src/Symfony/Component/Security/Http/Tests/Firewall/ExceptionListenerTest.php$
index ecbf614a69..515f452c71 100644
--- a/src/Symfony/Component/Security/Http/Tests/Firewall/ExceptionListenerTest.php
+++ b/src/Symfony/Component/Security/Http/Tests/Firewall/ExceptionListenerTest.php
@@ -50,15 +50,16 @@ class ExceptionListenerTest extends TestCase
     {
         $event = $this->createEvent($exception);

-        $response = new Response('Forbidden', 403);
+        // use something other than 403 to test that EntryPoint can return custom respon$
+        $response = new Response('Retry With', 449);

         $listener = $this->createExceptionListener(null, null, null, $this->createEntryP$
         $listener->onKernelException($event);

         $this->assertTrue($event->isAllowingCustomResponseCode());

-        $this->assertEquals('Forbidden', $event->getResponse()->getContent());
-        $this->assertEquals(403, $event->getResponse()->getStatusCode());
+        $this->assertEquals('Retry With', $event->getResponse()->getContent());
+        $this->assertEquals(449, $event->getResponse()->getStatusCode());
         $this->assertSame($exception, $event->getException());
     }

`````

P.S. @Simperfit , of course I grant all rights to everybody to do his best.

**Comment by nicolas-grekas** [comment]
To run the tests, the easiest might be to install deps in at the root of the repository, then run
`./phpunit src/Symfony/Component/Security/Http`

**Comment by nicolas-grekas** [comment]
Friendly ping, anyone to help move forward?

**Comment by Simperfit** [comment]
Going to check ASAP.

**Comment by ant5** [comment]
It seems that issue may be closed. I found that in some minor version change there was a fix and things work without patch proposed for this issue.

**Pull request closed without merging**
