### PR TITLE
Fix PropertyAccessor modifying array in object when array key does no…

### PR DESCRIPTION
**Pull request by pierredup**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16056 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by Tobion** [comment]
:+1:  Looks good. But applying this in 2.7 will be tricky because we cannot just skip the last item as we also support throwing a `NoSuchIndexException` in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/PropertyAccess/PropertyAccessor.php#L234

@pierredup do you have an idea how to best solve it in 2.7?

**Comment by Tobion** [comment]
I think the best is to just move the test within the outer if
```
if ($i + 1 < $propertyPath->getLength()) {
    $objectOrArray[$property] = array();
}
```

**Comment by pierredup** [comment]
@Tobion I've just tested this on the 2.7 branch, and it works by wrapping the assignment in the `if`.
I've updated this PR to use that approach instead, to make the merging into 2.7 a bit easier.
When this is merged then I'll create more tests to check for the `NoSuchIndexException`

**Comment by fabpot** [comment]
Thank you @pierredup.

**Pull request merged**
