### PR TITLE
Add getDefinition() to allow outside access

### PR DESCRIPTION
**Pull request by tacman**
| Q | A |
| --- | --- |
| Branch? | 3.1+ |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | 19938 |
| License | MIT |
| Doc PR | reference to the documentation PR, if any |

### CODE REVIEW

**Comment by jameshalsall** [comment]
This should be targeted at the master branch.

**Review by lemoinem — CHANGES_REQUESTED** [review]
Hello,

Thank you for your contribution.

Could you check the style modifications required by fabbot.io please?

If you could update your PR summary also. Among other things, update so it says target branch master instead of 3.1, and add a # in front of the ticket number so github generates a link which will make it easier to access the issue.

That would help a lot.

**Comment by lemoinem** [comment]
Status: Needs work

**Comment by lyrixx** [comment]
Hello.

Thanks for your contribution.

Unfortunately, I'm going to reject this PR for the same reasons as described in #19938

**Comment by lyrixx** [comment]
For you information, This feature has been added to Symfony.

**Pull request closed without merging**
