### PR TITLE
Use class constant in validators

### PR DESCRIPTION
**Pull request by Koc**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Koc** [comment]
should I replace everywhere string class names with constant?

**Comment by Tobion** [comment]
See #16666, #16648 etc

**Comment by Tobion** [comment]
@symfony/deciders I would propose to accept `::class` usage at places that developers are often facing and that are often used as template for new code. This eliminates alot of those PRs, makes code more readable and better exposes best practices. One of those places is `FormFactoryInterface` as people should use `create($type = FormType::class)` instead of `create($type = 'Symfony\Component\Form\Extension\Core\Type\FormType')` anyway according to our doc. So it would be strange if the Form component doesn't follow it's own best practices. The change proposed here is also one of those cases that should be accepted as it will be used for custom validators.

Those interfaces and classes are not changing often anyway. But we should avoid doing those changes in test files as it's more a pain to merge things and keep things consistent. We add tests often in 2.3 where `::class` cannot be used and thus it would be too painful to change that in 3.0 again and again.

**Comment by fabpot** [comment]
I don't see why it would be a "best practice". The result is exactly the same and as demonstrated by this PR, the gain in terms of readability is very minimal. Being the one who merge branches the most, I'm :-1: for this change.

**Comment by Koc** [comment]
@fabpot find usages support in IDE and ctrl+click are good additions.

**Pull request closed without merging**
