### PR TITLE
[Form] Fix tests to use FQCN

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Fixes an issue while merging 2.7 in upper branches (https://github.com/symfony/symfony/commit/2cf474e2eb65602bdc5ba7ff658767eb81560258#diff-fbbd0dcfdc8319ceb89c18435e590fd2R234)

### CODE REVIEW

**Comment by stof** [comment]
this should be done in 2.8 actually, to avoid getting a deprecation warning there.

But we can change this when merging (by rebasing your commit first)

**Comment by ogizanagi** [comment]
You're right of course. I've rebased and changed the target.

**Comment by HeahDude** [comment]
👍

**Comment by stof** [comment]
👍

**Comment by xabbuh** [comment]
:+1:

Status: Reviewed

**Comment by nicolas-grekas** [comment]
Thank you @ogizanagi.

**Pull request merged**
