### PR TITLE
[Yaml] do not dump extra trailing newlines for multiline blocks

### LINKED ISSUE #38310: Yaml::dump adds erroneous trailing \n (with Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK)
**Symfony version(s) affected**: 3.4.41 (and probably master too)

**Description**  

Yaml::parse(Yaml::dump("a\nb")) === "a\nb\n"

In other words, multiline YML does not roundtrip, it seems to always get a trailing newline.

**How to reproduce**  

```
# In my Drupal/Drush env:
$ drush ev 'print json_encode(\Symfony\Component\Yaml\Yaml::parse(\Symfony\Component\Yaml\Yaml::dump(["a\nb"],2,4, \Symfony\Component\Yaml\Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK))) . "\n";'
["a\nb\n"]
```

**Possible Solution**  

Add such test and fix code.

**Additional context**  

- Raised this already in #25842, but witn "\r\n", and in the heat of the battle, the problem was just hidden by un-multilining "\r\n".
- This is strongly wanted for Drupal config dump [here](https://www.drupal.org/project/drupal/issues/2844452)

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38310
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by jderusse — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by geek-merlin** [comment]
Thanks everyone for caring for and putting time and energy into this! (I'm the person who raised the issue and its predecessor. ;-)

Reviewing the code (unfortunataly i did not catch the unmerged-PR time window), i'm quite sure that this causes regressions:
- Dumper now **always** uses the "|-"=strip block chomping indicator, which means "strip all trailing newlines" (it mixes in indentation like "|4-" but that does not change the reasoning)
- => so the trailing-newlines case should be fixed
- => but all other cases should break
- Consistently with this, it looks to me like now we only have "no trailing newline" tests, but no tests with one or more trailing newlines.

What to do? Yaml spec is a convoluted piece of art. 
According to the [YAML Multiline](https://yaml-multiline.info/) and [tested with this fiddle](https://yaml-online-parser.appspot.com/?yaml=clip+1%3A+%7C%0A++one%0A++two%0Aclip+2%3A+%7C%0A++one%0A++two%0A%0Astrip+1%3A+%7C-%0A++one%0A++two%0Astrip+2%3A+%7C-%0A++one%0A++two%0A%0Akeep+1%3A+%7C%2B%0A++one%0A++two%0Akeep+2%3A+%7C%2B%0A++one%0A++two%0A%0A&type=python), we should be able to get away with something like this (plus tests for 0/1/2 trailing newlines):
```
// Yaml multiline output always needs a trailing newline, 
// so for no trailing newline, tell Yaml to strip it, otherwise to keep them all.
if ("\n" !== $value[-1]) {
  $blockChompingIndicator = '-';
  $value .= "\n";
}
else {
  $blockChompingIndicator = '+';
}
```

Sorry for not having the bandwidth to forge this into a new PR, but HTH.

**Comment by xabbuh** [comment]
@geek-merlin Thank you for coming back to this. I am going to check the current code with the YAML example that you linked.

**Comment by geek-merlin** [comment]
For a radically different multiline alternative see #39682. **It does not help with this bugfix**, but being in the enlightened state of having groked this corner of Yaml, i quickly needed to do a braindump.

**Comment by xabbuh** [comment]
see #39683 for fixing this regression

**Pull request merged**
