### PR TITLE
[Translation][Form] Do not translate placeholder and/or empty_value when translation_domain is false

### PR DESCRIPTION
**Pull request by Restless-ET**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

I've made the fix against branch 2.3, but on branch 2.7 there are a few more places where the fix is needed so if you guys want I can make another PR against branch 2.7. :)

### CODE REVIEW

**Comment by ogizanagi** [comment]
This is a new behavior and not a bug fix, isn't it ?

**Comment by Restless-ET** [comment]
IMO it's a bug fix because I believe that we should not try to execute a translation when the translation_domain was specifically disabled.
Also, unless we add this checking the translator will try to execute a translation using a non-existant (empty name) domain.

**Comment by Tobion** [comment]
`translation_domain => false` is not a supported so far. So this is a new feature. We only supported it for choices - also as a new feature - in #13651. So this is not a bug fix.

**Comment by jvasseur** [comment]
```translation_domain => false``` support was partially added in #15142 to solve the problem of expanded choice widgets.

This should probably be added everywhere for consistency.

But i agree this is a new feature and not a bug fix, the current implementation was just made for internal use (it isn't documented anywhere).

**Comment by Tobion** [comment]
@Restless-ET Please open a new PR against 2.8

**Comment by Restless-ET** [comment]
I was using the (partial-)feature added in #15142 so I though this was supported.

I'll make the PR against 2.8 then. :)

@Tobion You might want to close #16025 as well...

**Pull request closed without merging**
