### PR TITLE
Fixed markdown file

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by fabpot** [comment]
I should probably add a check on fabbot :)

**Comment by lyrixx** [comment]
@fabpot Indeed. My IDE removes quite often trailing space when I open a new PR. At least this check will be awesome. 
The command I used: `fd .md | xargs sed -i 's/^[ \t]*$//;s/[ \t]*$//'`  ([fd](https://github.com/sharkdp/fd))
And for the syntax, I opened all files and checked by hand. My IDE highlight errror

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Comment by nicolas-grekas** [comment]
@lyrixx could you please have a look at tests? It looks like this change broke them.

**Comment by lyrixx** [comment]
I will

**Comment by lyrixx** [comment]
Sorry, for the delay, I was sleeping / commuting :)
I opened a new PR #33160 where I revert changes on fixtures files

**Pull request merged**
