### PR TITLE
CS: recover no_break_comment

### PR DESCRIPTION
**Pull request by keradus**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | n/a, see CIs
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

rule was excluded in #24123, yet without any information about it
it was not excluded in original form of given PR, it's not part of any commitlog nor any comment, title claims to touch only other rules.

this rule shall not be excluded, it's part of PSR and is applied for most places.
I added missing ones.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
It was briefly talked about in https://github.com/symfony/symfony/pull/24182#discussion_r138551329
Looking at the proposed diff, I personally not favorable to merging this.
But I won't spend more time on CS things so I'll let others do however they want :)

**Comment by keradus** [comment]
let us not violate PSR ;)

**Comment by chalasr** [comment]
I don't like it either. 
Do we want to be PSR-2 compliant (it does not appear in the repository tags)? If yes [then it's a must](http://www.php-fig.org/psr/psr-2/#52-switch-case).

**Comment by keradus** [comment]
http://symfony.com/doc/current/contributing/code/standards.html :
> Symfony follows the standards defined in the PSR-0, PSR-1, PSR-2 and PSR-4 documents.

it's not big cost to pay for not violating PSR

**Review by fabpot — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]
okay for me if that's part of PSR-2

**Review by chalasr — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @keradus.

**Pull request merged**
