### PR TITLE
[ExpressionLanguage] Add `is_json()` and `is_xml()` expression functions

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | _NA_
| License       | MIT
| Doc PR        | Todo

The addition of these utils functions can be leveraged like this, for example:

```php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;

#[AsController]
class FooController extends AbstractController
{
    #[Route('/', condition: 'is_json(request.getContent())')]
    public function index(): Response
    {
        // ...
    }
}
```

Or like this:

```php
use Symfony\Component\Validator\Constraints\Expression;

#[Expression(
    expression: "is_json(this.body) and this.type == 'json' or is_xml(this.body) and this.type == 'xml'",
    message: "Body and type of payload mismatch"
)]
class Payload
{
    public string $body;

    public string $type;
}
```

### CODE REVIEW

**Comment by GromNaN** [comment]
I feel like this is a partial solution for a validation need. These functions either do too much (validate when you only want to know if the content seems to be JSON or XML), or not enough (if I want to validate that the JSON is an object?).

Maybe we should look at whether we could use validation in expressions?

**Comment by stof** [comment]
To me, this does not belong in the ExpressionLanguage component.

If you want routing conditions, it might be better to expose some functions in the routing component only, that would operate on the Request object using request matchers.

**Comment by wouterj** [comment]
I agree that this seems out of scope for the ExpressionLanguage component.

For requests, I would say you should never check whether the content is like a format, but always check the `Content-Type` header. We already support this using `#[Route('/', condition: 'request.getContentTypeFormat() == "json")')]`.

For validation, I'm not sure if this is a common enough use-case to add something built-in. You can always use the callback constraint to write this logic in PHP.

So :-1: for me to add this in the component or any expression provider of other components.

**Comment by alexandre-daubois** [comment]
Your comments suits me fine. Thank you for the time spent on the review! 🙏

**Pull request closed without merging**
