### PR TITLE
Add php_unit_dedicate_assert to PHPCS

### PR DESCRIPTION
**Pull request by carusogabriel**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25420 
| License       | MIT
| Doc PR        | -

Forgot to add this in #25420 :sweat_smile:

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This is risky because those methods exist only under PHPUnit 5.x.
But our 5.3/5.4 builds only run 4.8

**Comment by carusogabriel** [comment]
All the methods are available from PHPUnit `4.x` to `6.x` (I take this careful while doing that). I guess I didn't get your ask :disappointed:

**Comment by nicolas-grekas** [comment]
so, `php_unit_dedicate_assert` is safe for that? 
eg `assertNan()` should not be used, `$this->assertTrue(is_nan(...))` should always be used instead.
I just want to ensure this will be the case :)

**Comment by carusogabriel** [comment]
Oh, ok, now I get it. As I understood from PHP-CS-Fixer, [its checks the `PHPUnit` version before](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.8/src/Fixer/PhpUnit/PhpUnitDedicateAssertFixer.php#L84) doing this changes.
Maybe @keradus can help us :relaxed:

**Comment by nicolas-grekas** [comment]
OK cool, can we then target 4.8 explicitly?

**Comment by carusogabriel** [comment]
`4.8` no, but `3.5` yes. I'm running locally to see if we face it any incompatibility.

**Comment by keradus** [comment]
if doesn't check the installed version, as there could not be one installed yet, it checks requested version.

target could be configured for 3.0, 3.5, 5.0 and 5.6 (and newest ever).
as we run tests on phpunit 4.x as well, we need to set target for this fixer for highest compatible, thus 3.5. (@nicolas-grekas , then it will not affects `assertNan` !)
note: phpunit 3.6+ | 4.0+ did not introduce new assertions that could be fixed, that's why there is no target for them.

**Comment by keradus** [comment]
we shall not use one rule only. use full set instead: #25556

**Comment by nicolas-grekas** [comment]
Thank you @carusogabriel.

**Pull request merged**
