### PR TITLE
[2.8] [Form] minor fix some regression in tests with placeholder in AbstractLayout

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by HeahDude** [comment]
Tests are actually failing globally in travis on 2.8, this PR is the fix.

**Comment by HeahDude** [comment]
Some builds still fail but locally tests are green. Am I missing something ? (sorry for the) ping @nicolas-grekas

**Comment by xabbuh** [comment]
:+1:

**Comment by HeahDude** [comment]
@xabbuh forgive me to ask this as I don't understand, what about the failing builds ?

**Comment by xabbuh** [comment]
@HeahDude The failing tests on AppVeyor have been fixed in the meantime (you can trigger a rebuild by push a new commit). The `deps=high` tests can fail when some tests depend on changes in a different component made in this PR.

**Comment by xabbuh** [comment]
ping @symfony/deciders 

Status: Reviewed

**Comment by HeahDude** [comment]
Ok thank you @xabbuh, I was just worried because some tests I fixed here were still failing in some travis build (with php 5.6) while the others were green (green also for my local tests and I am on php 5.6).

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Pull request merged**
