### PR TITLE
[TwigBridge][DependencyInjection] ignore null arguments

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by OskarStark** [comment]
Could you explain why in a small sentence?

**Comment by derrabus** [comment]
> Could you explain why in a small sentence?

The old constructor signature was `(RequestStack $requestStack, RequestContext $requestContext = null)`, so `null` was a valid second argument until #30862. This PR basically restores BC.

**Comment by OskarStark** [comment]
Ah yes I thought it on the linked PR from Valentin 👍🏻
Thanks for the feedback, it makes sense 😊

**Review by OskarStark — APPROVED** [review]

**Review by maxhelias — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
