### PR TITLE
[travis] merge php-nightly and deps=high test-matrix lines

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
Why ? We want to test our high deps on stable PHP versions IMO, not only on nightly.

**Comment by nicolas-grekas** [comment]
Now that we enforce php7 tests to pass, this is the same (for the use case).

Removing one test line makes tests faster, which means faster feedback for PR-authors, and more merges per day (we quite often saturate our travis slots when we merge several PRs a day while other PRs are also submitted/updated.)

**Comment by nicolas-grekas** [comment]
Btw, indirectly related: the php7 tests fail from time to time with a segfault.
I reported this here: https://bugs.php.net/70202

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
