### PR TITLE
CS for AccessDecisionManager

### PR DESCRIPTION
**Pull request by aschempp**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | #34548
| License       | MIT
| Doc PR        | -

As discussed in #34548 with @nicolas-grekas here's a CS change for the `AccessDecisionManager`

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @aschempp.

**Comment by gaetan-petit** [comment]
Hi all,

This PR breaks old code because of the type check added here :
https://github.com/symfony/symfony/commit/b3742ec493c37b597e507b2eeaf12bb5c7fca794#diff-198f07c52bf3eeb62bd14e3a0fb01dd0L93

Some voters in our application were previously returning `true` and not `0`.

No big deal, but was it intended ? @nicolas-grekas @chalasr

**Comment by nicolas-grekas** [comment]
Breaking your code was not intended, but returning true was not supported either...

**Comment by gaetan-petit** [comment]
@nicolas-grekas It's code from 2015, nice excuse to clean it up 😄

**Pull request merged**
