### PR TITLE
Minor tweaks to the welcome page

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/33189#issuecomment-529177310
| License       | MIT
| Doc PR        | -

/cc @fabpot

### CODE REVIEW

**Comment by fabpot** [comment]
It's better, thank you.

Some more comments:

 * On Safari, there is no margin at the bottom

image

 * The path is now correct but it looks like it's not aligned/centered (Safari and Firefox)

image

 * On my screen, the warning about the fact that this page is displayed because there is no controllers yet is not displayed. I'm wondering if we should not move it just after "Your application is now ready and you can start working on it.". And/or perhaps makes the design a bit more compact vertically.

**Comment by yceruto** [comment]
Status: Needs Work

**Comment by javiereguiluz** [comment]
I'm testing this in Safari, Chrome and Firefox. I still cannot make it work with Firefox, but I'll keep trying to fix this:

browser-comparison

**Comment by michaelperrin** [comment]
@javiereguiluz @yceruto First, thanks for this new project page design, it's awesome! Concerning the alignment issues, I could solve them for all browsers quite easily using Flex (not talking about Symfony's one 😄). Is there any reason you didn't use these CSS properties?

Please note that I didn't test it on IE11 (if we really need this...), but that should be doable to make it work anyway if it doesn't already.

**Comment by stof** [comment]
I don't think supporting IE 11 for this page is needed. Hopefully web developers don't use it as their main browser.
We already stopped supporting for the web profiler UI IIRC (keeping IE support for the web debug toolbar, as this one gets injected in the project UI, which may have a need to support IE)

**Comment by michaelperrin** [comment]
Yeah I totally agree as we are targeting developers. I will have a quick look just by curiosity.

**Comment by michaelperrin** [comment]
Here is a quick diff you can apply into the `welcome.html.php` file for cross-browser compatibility (at least Firefox, Chrome and Safari) and cleaner CSS code (no need of the margin-left of 70px):

```diff
code {
-   position: relative;
-   padding: 10px 26px 14px 70px;
+   display: inline-flex;
+   align-items: center;
+   padding: 4px 26px 4px 4px;
}

.check {
-   position: absolute;
-   left: 6px;
-   top: 5px;
+   margin-right: 10px;
+   line-height: 38px;
}
```

**Comment by javiereguiluz** [comment]
@michaelperrin I can't see it correctly with Firefox. Look at how different is the vertical align of the monospaced text.

Firefox:
firefox

Chrome:
chrome

-----

The problem is that both browsers are using different fonts ... because we don't define the font family explicitly, so `'monospace'` is used.

I could solve the problem by setting the font family explicitly. I used the same font stack as Bootstrap's monospace:

```
SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace
```

**Comment by michaelperrin** [comment]
You're right. My CSS flex solution wouldn't help for this. I checked with the Bootstrap's monospace font family and it makes the correctly aligned indeed.

**Comment by fabpot** [comment]
@javiereguiluz Let's use the same font everywhere as done with Bootstrap. I don't see any drawback.

**Comment by javiereguiluz** [comment]
I've committed some changes. I share some screenshots using Firefox, which was the browser where we had some issues ... and now it looks the same as Chrome and Safari:

**Desktop**

desktop

**Smartphone**

smartphone

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @yceruto.

**Comment by yceruto** [comment]
Thank you @javiereguiluz :heart:

**Pull request merged**
