### PR TITLE
[HttpKernel] Add tests for `#[TaggedIterator]` & `#[TaggedLocator]` on controller arguments

### LINKED ISSUE #49083: TaggedLocator/TaggedIterator attributes does not work in  controller argument
### Description

It would be super cool to be able to write such code: 

```
    #[Route('/')]
    public function index(
        #[TaggedLocator('foobar')]
        ContainerInterface $foobar,
    ): JsonResponse
    {
        dd($foo);
```

But it does not work ATM

> Cannot autowire argument $foo of "App\Controller\AController::index()": it references interface "Psr\Container\ContainerInterface" but no such service exists. Available autowiring aliases for this interface are: "$parameterBag".

> **Note**
> It also applies to `TaggedIterator`

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49083
| License       | MIT
| Doc PR        | -

~~I think this doesn't qualify as a bug fix, but an improvement. If I'm wrong please let me know.~~

#49628 fixed the issue, this PR only adds tests now.

### CODE REVIEW

**Review by nicolas-grekas — COMMENTED** [review]
Thanks.
Can you please let me know if `#[Autowire(new TaggedLocator(...))]` (or `#[Autowire(new ServiceLocatorArgument())]` I don't remember) works?

**Comment by HypeMC** [comment]
> Thanks. Can you please let me know if `#[Autowire(new TaggedLocator(...))]` (or `#[Autowire(new ServiceLocatorArgument())]` I don't remember) works?

@nicolas-grekas No, neither work. As far as I can tell, the `#[Autowire]` attribute is not designed to work like that.

**Comment by HypeMC** [comment]
Funny thing, this does seem to work:

```php
#[Autowire([new ServiceLocatorArgument(new TaggedIteratorArgument(...)), new TaggedIteratorArgument(...)])]
```

In this case, the argument is an array with a service locator and an iterator.

**Comment by nicolas-grekas** [comment]
Can you please try #49628? It might have fixed the issue. If not, the PR will still need to be updated to account for the changes in #49628.

**Comment by HypeMC** [comment]
> Can you please try #49628? It might have fixed the issue. If not, the PR will still need to be updated to account for the changes in #49628.

@nicolas-grekas Yep, #49628 fixed the problem. I've removed all my changes except the test cases as this particular functionality isn't covered anywhere.

**Comment by nicolas-grekas** [comment]
Thank you @HypeMC.

**Pull request merged**
