### PR TITLE
return $this  in container aware classes

### PR DESCRIPTION
**Pull request by dawehner**
| Q | A |
| --- | --- |
| Branch? | "master" for new features |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes/no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

For some limited usecases it would be nice to return $this in `->setContainer()`

### CODE REVIEW

**Comment by xabbuh** [comment]
:-1: Changing the interface is a BC break that cannot be done in a minor release.

**Comment by fabpot** [comment]
As it does not bring that much value, I think this can be closed.

**Comment by stof** [comment]
:-1: for me as well. Forcing a fluent interface in ContainerAwareInterface does not bring any value IMO (making any possible interface fluent is harmful), and clearly does not justify a BC break.

Closing as 3 core team members voted against it.

**Comment by dawehner** [comment]
Well, I filed it on master on purpose for symfony but meh, it would have been nice

**Pull request closed without merging**
