### PR TITLE
[Mailer] relax constraints to also run tests with symfony/webhook 6.3

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
alternative solution: change the constraint in `require-dev` to `^6.3|^7.0` (as it's done in the Mailgun, Postmark and Sendgrid bridges)

**Comment by nicolas-grekas** [comment]
if there is a solution that doesn't involve conflict that's better indeed.

**Comment by xabbuh** [comment]
I updated the constraints in the `require-dev` section instead

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
