### PR TITLE
[DependencyInjection] Add custom container configurators

### PR DESCRIPTION
**Pull request by unkind**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | let's see
| Fixed tickets | #25630
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by unkind** [comment]
Is there any reason for `ExtensionInterface`? I'd like to put this stuff into `Extension` instead of `ContainerBuilder`, but I can't extend it due to interface.

**Comment by unkind** [comment]
Any chance to merge it in 4.1? 

It's a challenge to make it without changes in the core so far: `ContainerConfigurator` requires `PhpFileLoader` as dependency (probably, `FileLoader` is enough?). /cc @nicolas-grekas

**Comment by ro0NL** [comment]
What about something like

```php
$c->extension('my_ext', ['primitive' => 'config']);

// vs.

/** @var MyExtConfigurator $myExt */
$myExt = $c->extension('my_ext');
$myExt
   ->fluent('config');
```

**Comment by andersonamuller** [comment]
Or:

```php
$myExt = $c->extension('my_ext')->configure(function (MyExtConfigurator $myExt) {
	return $myExt->foo('bar');
});
```

**Comment by ro0NL** [comment]
Or:

```php
$c->extension(function(MyExtConfigurator $e) {
   $e->fluent('config');
});
```

Where's my cookie?

**Comment by nicolas-grekas** [comment]
I'm not convinced this is the approach we need in core.

The idea I proposed in #25630 doesn't require any code at all, thus any new concept/methods/api:
```php
return function (ContainerConfigurator $c) {
    $myBundle = new MyBundleConfigurator($c);

    $myBundle->setWhatever();
}
```

To me, configuration is the correct place to do "new".

Note that I'd also really like to be able to autocomplete bundle config using fluent configurator.
Unfortunately, this is currently left as "an exercise" to bundle authors (and the exercise is not trivial).
Would be awesome to be able to somehow autogenerate it from config definition!

**Comment by nicolas-grekas** [comment]
@unkind can you check #27065? I think it could fix your issue in a nice way. WDYT? I'm closing this PR as explained above. Thanks for proposing.

**Comment by unkind** [comment]
Sorry for duplicates, it was github lag that night.

**Pull request closed without merging**
