### PR TITLE
Add parseFile method

### PR DESCRIPTION
**Pull request by lostcodder**
| Q             | A
| ------------- | ---
| Branch?       | master / 2.7, 2.8, 3.1 or 3.2 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@lostcodder thanks for contributing to the Symfony project!

I don't know if this proposal will make it, but in case you are not aware of it, I'd like to tell you that the philosophy of Symfony is usually against adding lots of related utility methods. For example, if we have a `parse($string)` method, we usually don't include `parseFile($filePath)` but rely on `parse(file_get_contents($filePath))`.  But maybe this time the proposal is accepted, so let's wait.

Another example is how we generate absolute URLs for assets. We have `asset()` and then we added `absolute_url()` so you can combine them as `absolute_url(asset('...'))` but we don't have for example `asset_absolute()`.

**Comment by lostcodder** [comment]
@javiereguiluz yeah. Thank you! I think you right.

**Comment by ro0NL** [comment]
Also note the feature was already removed previously (since 3.0), this would reintroduce it.

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Yaml/Yaml.php#L52

Not sure we need to do it with a separate method this time.

**Comment by fabpot** [comment]
Closing as it was indeed removed. There is no real benefit in adding a utility method that does not add much value. Moreover, it does not deal with issues like when the file does not exist, ...

**Pull request closed without merging**
