### PR TITLE
[2.7][Asset] Ability to set empty version strategy in packages

### PR DESCRIPTION
**Pull request by ewgRa**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no, but not sure, as for me test was wrong |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14832 |
| License | MIT |
| Doc PR |  |

Comment about '' thing. As you can see in xml test - we can't for attribute set null value. And for xml version '' empty string considered as null value, that affect all others formats and test is changed.

### CODE REVIEW

**Comment by ewgRa** [comment]
Tests fails only on hhvm and seems not related to this PR

**Comment by XWB** [comment]
Can you fix this in 2.7 as well?

**Comment by ewgRa** [comment]
PR Branch was created from 2.7, so this is for 2.7 too.

**Comment by XWB** [comment]
@ewgRa You created the pull request against the symfony:2.8 branch:

image

**Comment by ewgRa** [comment]
Ok, if it important.

Create new PR for 2.7 - #16511

**Comment by XWB** [comment]
Thank you :)

**Pull request closed without merging**
