### PR TITLE
Replace __CLASS__, get_called_class() and get_class($this) by (self|static)::class

### PR DESCRIPTION
**Pull request by Majkl578**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | ?
| Fixed tickets | ~
| License       | MIT
| Doc PR        | ~

* Replace `__CLASS__` with `self::class`
* Replace `get_called_class()` with `static::class`
* Replace `get_class($this)` by `static::class`

### CODE REVIEW

**Comment by Tobion** [comment]
Does not seem worth to me to create so many conflicts due to changes in the deprecation lines.

**Comment by nicolas-grekas** [comment]
I agree with @Tobion 
There is only one way we could merge this, it's if/when fabbot will enforce a normalized version of these.

**Comment by keradus** [comment]
btw, if you want to participate with discussion about this feature request for PHP CS Fixer (which boosts fabbot.io), please visit https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3900 !

**Comment by fabpot** [comment]
So, I'm closing this one and let's wait for PHP-CS-Fixer to implement this so that we can automate/enforce that with fabbot.

**Comment by stof** [comment]
@nicolas-grekas cannot be applied to 2.8, as it supports PHP versions without `::class`

**Comment by nicolas-grekas** [comment]
@stof right! Which means we have to wait for 2.8 to be EOLed before reconsidering this. Fortunately that's going to happen in just a few months.

**Comment by keradus** [comment]
hm...
@nicolas-grekas , can we go crazy? short array syntax is longly awaited ;)

**Comment by nicolas-grekas** [comment]
@keradus that's also for early December :)

**Pull request closed without merging**
