### PR TITLE
add missing description on text representation of command info

### PR DESCRIPTION
**Pull request by cordoval**
| Q | A |
| --- | --- |
| Bug Fix? | y |
| New Feature? | n |
| BC Breaks? | n |
| Deprecations? | n |
| Tests Pass? | - |
| Fixed Tickets | #13943 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by cordoval** [comment]
can't recall if this PR is ok to be send here or to 2.3, or which version, can someone please shed some light? :older_man:

**Comment by Epskampie** [comment]
See [Choose the right branch](http://symfony.com/doc/current/contributing/code/patches.html#choose-the-right-branch) in the contributing guide.

**Comment by cordoval** [comment]
ok cool, i will fix tests first and then relaunch the PR with gush into the right branch, i presume it is 2.3 as usual. Thanks :older_man:

**Comment by cordoval** [comment]
replaced with #13975

**Pull request closed without merging**
