### PR TITLE
Add phpdoc return type to TypedReference::getType

### PR DESCRIPTION
**Pull request by 94noni**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | -
| New feature?  | -
| Deprecations? | -
| License       | MIT

### CODE REVIEW

**Review by stof — CHANGES_REQUESTED** [review]
Adding a PHP return type in a non-private method of a non-final class is a BC break. So this cannot be done in 6.2.

Please add a phpdoc return type instead (which will make DebugClassLoader trigger a deprecation for child classes to make them add the return type before Symfony 7.0).

**Comment by 94noni** [comment]
Got it will do it thx

**Comment by 94noni** [comment]
@stof regarding [your comment](https://github.com/symfony/symfony/pull/47480#pullrequestreview-1095488780)

would it be nice to check all codebase that do not have return typehint neither return phpdoc to add them so that v7 is fully type hinted? at least as much as possible?

thank you

**Comment by fabpot** [comment]
You're right that this should be an initiative that we need to coordinate. Such a PR won't be merged as we can then create hundreds of similar PRs, which won't scale.

**Comment by 94noni** [comment]
@fabpot I agree obviously with this (will close this)

but regarding the main point, do you have in core team member some tools that can lead to find/patch/merge easily such codebase ?

thx

**Pull request closed without merging**
