### PR TITLE
[Serializer] Use autoloader for annotations in tests

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by dunglas** [comment]
The Travis failure seems not related with this PR.

**Comment by fabpot** [comment]
Can you do the same for the Validator component? (in src/Symfony/Component/Validator/Tests/Mapping/Loader/AnnotationLoaderTest.php for instance)

**Comment by dunglas** [comment]
@fabpot sure, I'll open another PR.

**Comment by dunglas** [comment]
@fabpot I cannot find any use of `require` nor `include` in that class.

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request merged**
