### PR TITLE
FileSystem: improved filesystem class with move function

### PR DESCRIPTION
**Pull request by pix-art**
| Q | A |
| --- | --- |
| Branch? | "master" for new features |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by ogizanagi** [comment]
What is the difference with the `Filesystem::rename()` method ?

**Comment by pix-art** [comment]
Hmm, I must have looked over the rename function, I guess there is not much difference but I did overlook it. Maybe rename that function to move? But I guess I can close down this PR.

**Comment by ogizanagi** [comment]
@pix-art: great. Just wanted to be sure there was no more confusion.

Renaming the `Filesystem::rename()` method to `move` would probable not be possible, except by deprecating the `rename` method first and calling the `move` one inside. Then, removing the `rename` method in 4.0.

But actually, the `Filesystem::rename()` method's name makes sense, as expressed in the [copy PHP manual entry](http://php.net/manual/en/function.copy.php) : 
> If you wish to move a file, use the rename() function.

**Comment by pix-art** [comment]
Thanks for the feedback, greatly appreciated :-)

**Pull request closed without merging**
