### PR TITLE
[HttpFoundation] : add support for text/vnd.turbo-stream.html

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

This will allow simplifying Symfony UX Turbo:

* https://github.com/symfony/ux/blob/2.x/src/Turbo/Stream/TurboStreamResponse.php#L25-L26
* https://github.com/symfony/ux/blob/2.x/src/Turbo/Stream/AddTurboStreamFormatSubscriber.php

### CODE REVIEW

**Review by nicolas-grekas — DISMISSED** [review]

**Review by ogizanagi — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by ogizanagi** [comment]
Worth adding a CHANGELOG.md entry?

**Comment by dunglas** [comment]
@ogizanagi yes I think so.

Please wait before merging, this should maybe be merged as a bug fix.

**Comment by nicolas-grekas** [comment]
Looking at https://github.com/symfony/ux/pull/217/files#r782554659, this is not needed actually to me.

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
Putting a preemptive :-1: as I think this is not needed.

**Comment by dunglas** [comment]
Closing in favor of https://github.com/symfony/ux/pull/217

**Pull request closed without merging**
