### PR TITLE
[Form] add Create form - UPGRADE-3.0.md

### PR DESCRIPTION
**Pull request by sad270**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
I think we can better reuse the wording from the `UPGRADE-2.8.md` file:

> Passing type instances to Form::add(), FormBuilder::add() and the FormFactory::create*() methods is not supported anymore. Pass the fully-qualified class name of the type instead.
>
> Before:
>
> ```php
> $form = $this->createForm(new MyType());
> ```
>
> After:
>
> ```php
> $form = $this->createForm(MyType::class);
> ```

**Comment by nicolas-grekas** [comment]
Status: needs work

**Comment by fabpot** [comment]
What's the status of this PR? @xabbuh Can you open a PR with your suggestion instead?

**Comment by xabbuh** [comment]
This was already covered by #17432 (see https://github.com/symfony/symfony/pull/17432/files#diff-0901ceb76939b17cd920bc69aa52d21fR312).

**Pull request closed without merging**
