### PR TITLE
[Console] Fix bug in windows detection

### PR DESCRIPTION
**Pull request by kbond**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16577 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by ewgRa** [comment]
Just a curious.

What is a standard way to check OS in Symfony?

At some places it is check DIRECTORY_SEPARATOR, in another places it is strpos(PHP_OS, "WIN") === 0.

**Comment by xabbuh** [comment]
@ewgRa We always check the value of the `DIRECTORY_SEPARATOR` constant. There shouldn't be any other checks anymore (we unified that some time ago).

**Comment by fabpot** [comment]
Thank you @kbond.

**Pull request closed without merging**
