### PR TITLE
Run tests on hhvm instead of hhvm-nightly

### PR DESCRIPTION
**Pull request by dosten**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14532 |
| License | MIT |

### CODE REVIEW

**Comment by dosten** [comment]
I need to create a PR for each version?

**Comment by stof** [comment]
@dosten no. We will merge 2.3 into newer branches

**Comment by stof** [comment]
:+1:

**Comment by Tobion** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @dosten.

**Pull request merged**
