### PR TITLE
fixed APCu dep version

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17428 |
| License | MIT |

### CODE REVIEW

**Comment by Tobion** [comment]
You forgot https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/ClassLoader/composer.json#L21

**Comment by fabpot** [comment]
@Tobion fixed

**Comment by Tobion** [comment]
Merging. Will also merge it upwards

**Comment by Tobion** [comment]
Thank you @fabpot.

**Comment by nicolas-grekas** [comment]
@Tobion I read in a comment that polyfill-apcu could be removed in master because apc_* is pre-5.5 only, but this forgets about HHVM, which still provides apc_*

**Comment by Tobion** [comment]
Hm but #17524 does not fail on hhvm on apcu?

**Comment by Tobion** [comment]
Ah probably because it's skipped now?

**Comment by nicolas-grekas** [comment]
I guess...

**Comment by stof** [comment]
I suggest opening an issue on HHVM asking them to provide the apcu_* functions too

**Comment by nicolas-grekas** [comment]
Done : https://github.com/facebook/hhvm/issues/6784

**Comment by Tobion** [comment]
So are we ok to just wait on hhvm support and add apcu-polyfill to the suggest section of the ClassLoader in the meantime? I saw that was done for the cache component.

**Pull request merged**
