### PR TITLE
[Console][PhpUnitBridge][VarDumper] Add support for `FORCE_COLOR` environment variable

### PR DESCRIPTION
**Pull request by serious-angel**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        |
| License       | MIT

### CODE REVIEW

**Review by serious-angel — COMMENTED** [review]
I am not sure about `CHANGELOG` file and how breaking it is.
Please suggest any details if possible.

Related: https://github.com/chalk/supports-color/issues/105

**Comment by nicolas-grekas** [comment]
Related also: https://force-color.org/

**Comment by nicolas-grekas** [comment]
BTW, https://no-color.org/ tells that the NO_COLOR env var should not be the empty string, and we don't follow this spec currently. I think we should.

**Comment by alexandre-daubois** [comment]
Hi @artshade, you may have a look at this fix to be sure to update everywhere it is relevant in Symfony: https://github.com/symfony/symfony/pull/57815

**Comment by serious-angel** [comment]
> ...you may have a look at this fix to be sure to update everywhere it is relevant in Symfony: https://github.com/symfony/symfony/pull/57815

This is awesome! Thank you, @alexandre-daubois ! Have you considered the related forced color option?

**Comment by alexandre-daubois** [comment]
You seemed to be well on your way to adding this feature, so I didn't want to impose a PR if you wanted to finish it :)

**Comment by serious-angel** [comment]
> You seemed to be well on your way to adding this feature, so I didn't want to impose a PR if you wanted to finish it :)

Changed the priority of `NO_COLOR` as in the snippet at https://force-color.org, where `NO_COLOR` comes first and only then - `FORCE_COLOR`:

```c
if (no_color != NULL && no_color[0] != '\0')
    color = false;
// ...
if (force_color != NULL && force_color[0] != '\0')
    color = true;
```
[Source](<https://force-color.org>)

Regarding the PR, I am frankly not sure if the current state of the PR is correct considering all the branches and rules.

**Review by derrabus — CHANGES_REQUESTED** [review]
Thank you. Please add a test.

**Comment by nicolas-grekas** [comment]
Thank you @artshade.

**Comment by serious-angel** [comment]
I am sorry for not implementing the test in-time...
Sincere gratitude, @nicolas-grekas, and everyone...

**Let it be colors!** :rainbow: :sparkles:

**Pull request merged**
