### PR TITLE
[Yaml] Match signature of Yaml::parse() with Parser->parse()

### PR DESCRIPTION
**Pull request by remi-blaise**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
@Zzortell Could you please also rebase and add a test for this feature?

**Comment by Zzortell** [comment]
I integrate this commit in #14420 so you can close this one.

**Comment by jakzal** [comment]
@Zzortell These are separate things. I think there should be two PRs.

**Comment by Zzortell** [comment]
Yes, it's what I thought first, but does PR matter ? Because I mean only commits count no ?

**Comment by Zzortell** [comment]
What do you mean when you say rebase ? Because I rebased it when I pushed it

**Comment by xabbuh** [comment]
@Zzortell Never mind, I must have looked at the wrong Travis build. So everything is fine. :+1:

**Comment by Zzortell** [comment]
Travais failed because of errors in Process and Debug components. Nothing to do with this commit.

**Comment by fabpot** [comment]
Thank you @Zzortell.

**Pull request merged**
