### PR TITLE
Fix `$this` calls to static ones when relevant

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by GromNaN — COMMENTED** [review]
All the PHPUnit assertions are static methods called on `$this`. Unless this calls are nested in static methods (data provider, class events), I don't see the point of changing this.

**Comment by alexandre-daubois** [comment]
> All the PHPUnit assertions are static methods called on $this

Unfortunately, this is not exactly true. There are more than 1200 occurrences of `self::assert` in the codebase. I know there's a will to make this consistent, once there's a way to automate the change in the CI (with fabbot for instance). I can't find the discussion again though.

But this is why I didn't make the change on tests. There are just too many and the decision hasn't been fully made. I think however that it's always good thing to be fully accurate on (non) static calls elsewhere in sources, especially since there are only 8 occurrences of "wrong" calls.

**Review by javiereguiluz — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
Works for me, even-though this provides nothing in practice.

I'm :-1: to do this for test cases. That'd be just noise in the git history and overhead for maintainers.

**Comment by nicolas-grekas** [comment]
Thank you @alexandre-daubois.

**Pull request merged**
