### PR TITLE
In README.md of Community Section Changed Twitter to it's new name 𝕏

### LINKED ISSUE #52370: In README.md of Community Section Change Twitter to it's new name 𝕏
### Symfony version(s) affected

-

### Description

Twitter is now known as 𝕏.

In README.md of community section it is still it's old name.

### How to reproduce

1. Go to symfony repository
2. Read community section in README.md 

### Possible Solution

Change the name of Twitter to it's new name

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by BandhiyaHardik**
changed Twitter's name to 𝕏 (Twitter)

| Q             | A
| ------------- | ---
| Branch?       | 6.4 
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #52370
| License       | MIT

### CODE REVIEW

**Comment by derrabus** [comment]
I don't think that this is worth "fixing", tbh. "Twitter" is fine.

**Comment by BandhiyaHardik** [comment]
> I don't think that this is worth "fixing", tbh. "Twitter" is fine.

I am opening this so it reflects it's latest name

**Comment by derrabus** [comment]
Yeah, got it. I think, we can keep the _well known name_ of that service for a little while longer.

That being said, if we decided to go with your proposal: Why do we change the displayed name of the service, but not the URL that we link to?

**Comment by BandhiyaHardik** [comment]
> Yeah, got it. I think, we can keep the _well known name_ of that service for a little while longer.
> 
> That being said, if we decided to go with your proposal: Why do we change the displayed name of the service, but not the URL that we link to?

i will change it and replace it with x

**Comment by welcoMattic** [comment]
As x.com redirects to twitter.com, I think we should stick to twitter unless the redirection will be switched.

:-1: for me

**Pull request closed without merging**
