### PR TITLE
[RFC][Console] Added console style guide helpers

### PR DESCRIPTION
**Pull request by kbond**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | todo |
| Fixed tickets | #12014 |
| License | MIT |
| Doc PR | todo |
### Code

``` php
// Symfony command
protected function execute(InputInterface $input, OutputInterface $output)
{
    $output = new StandardOutputStyle($output);

    $output->title('Lorem Ipsum Dolor Sit Amet');
    $output->text(array(
        'Duis aute irure dolor in reprehenderit in voluptate velit esse',
        'cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat'
    ));
    $output->ln();

    $output->table(array('Name', 'Method', 'Scheme', 'Host', 'Path'), array(
            array('admin_post_new', 'ANY', 'ANY', 'ANY', '/admin/post/new'),
            array('admin_post_show', 'GET', 'ANY', 'ANY', '/admin/post/{id}'),
            array('admin_post_edit', 'ANY', 'ANY', 'ANY', '/admin/post/{id}/edit'),
            array('admin_post_delete', 'DELETE', 'ANY', 'ANY', '/admin/post/{id}'),
        ));

    $output->caution(array(
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
            'foo'
        ));
    $output->section('Consectetur Adipisicing Elit Sed Do Eiusmod');
    $output->listing(array(
        'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod, tempor incididunt ut labore et dolore magna aliqua.',
        'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.',
        'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
    ));

    $customValidator = function ($value) {
        if ($value == 'foo') {
            throw new \Exception('cannot be foo');
        }

        return $value;
    };

    // hidden question
    $output->note($output->askHidden('Hidden question'));

    // choice questions
    $output->note($output->choice('Choice question no default', array('choice1', 'choice2')));
    $output->note($output->choice('Choice question with default', array('choice1', 'choice2'), 'choice1'));

    // confirmation questions
    $output->note($output->confirm('Confirmation with yes default', true) ? 'yes' : 'no');
    $output->note($output->confirm('Confirmation with no default', false) ? 'yes' : 'no');

    // standard questions
    $output->note($output->ask('Question no default'));
    $output->note($output->ask('Question no default and custom validator', null, $customValidator));
    $output->note($output->ask('Question with default', 'default'));
    $output->note($output->ask('Question with default and custom validator', 'default', $customValidator));

    $output->note('Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat.');
    $output->success('Lorem ipsum dolor sit amet, consectetur adipisicing elit');
    $output->error('Duis aute irure dolor in reprehenderit in voluptate velit esse.');
    $output->warning('Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.');
}
```
### Output

```
$ php app/console command

Lorem Ipsum Dolor Sit Amet
==========================

 // Duis aute irure dolor in reprehenderit in voluptate velit esse
 // cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat

 ------------------- -------- -------- ------ ----------------------- 
  Name                Method   Scheme   Host   Path                   
 ------------------- -------- -------- ------ ----------------------- 
  admin_post_new      ANY      ANY      ANY    /admin/post/new        
  admin_post_show     GET      ANY      ANY    /admin/post/{id}       
  admin_post_edit     ANY      ANY      ANY    /admin/post/{id}/edit  
  admin_post_delete   DELETE   ANY      ANY    /admin/post/{id}       
 ------------------- -------- -------- ------ -----------------------

 ! [CAUTION] Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et    
 ! dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris. Lorem ipsum dolor sit amet, 
 ! consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim    
 ! veniam, quis nostrud exercitation ullamco laboris.                                                                   
 !                                                                                                                      
 ! foo                                                                                                                  

Consectetur Adipisicing Elit Sed Do Eiusmod
-------------------------------------------

 * Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod, tempor incididunt ut labore et dolore magna aliqua.

 * Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.

 * Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Hidden question:
 > <f><o><o><enter>

 ! [NOTE] foo

 Choice question no default:
  [0] choice1
  [1] choice2
 > <enter>

 [ERROR] Value "" is invalid                                                                                            

 Choice question no default:
  [0] choice1
  [1] choice2
 > 0<enter>

 ! [NOTE] choice1                                                                                                       

 Choice question with default [choice1]:
  [0] choice1
  [1] choice2
 > 1<enter>

 ! [NOTE] choice2                                                                                                       

 Confirmation with yes default (yes/no) [yes]:
 > <enter>

 ! [NOTE] yes                                                                                                           

 Confirmation with no default (yes/no) [no]:
 > <enter>

 ! [NOTE] no                                                                                                            

 Question no default:
 > <enter>

 [ERROR] A value is required.                                                                                           

 Question no default:
 > foo<enter>

 ! [NOTE] foo                                                                                                           

 Question no default and custom validator:
 > foo<enter>

 [ERROR] cannot be foo                                                                                                  

 Question no default and custom validator:
 > <enter>

 [ERROR] A value is required.                                                                                           

 Question no default and custom validator:
 > foo<enter>

 [ERROR] cannot be foo                                                                                                  

 Question no default and custom validator:
 > bar<enter>

 ! [NOTE] bar                                                                                                           

 Question with default [default]:
 > <enter>

 ! [NOTE] default                                                                                                       

 Question with default and custom validator [default]:
 > <enter>

 ! [NOTE] default                                                                                                       

 ! [NOTE] Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.        
 ! Excepteur sint occaecat cupidatat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu   
 ! fugiat nulla pariatur. Excepteur sint occaecat cupidatat. Duis aute irure dolor in reprehenderit in voluptate velit  
 ! esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat.                                      

 [OK] Lorem ipsum dolor sit amet, consectetur adipisicing elit                                                          

 [ERROR] Duis aute irure dolor in reprehenderit in voluptate velit esse.                                                

 [WARNING] Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.                                     
```
### Screenshots

screen1

screen2

screen3

### CODE REVIEW

**Comment by sstok** [comment]
Whats the status of this?

**Comment by aequasi** [comment]
:( I hope this isnt dead.

**Comment by javiereguiluz** [comment]
@kbond do you think you'll have time to rebase and finish this PR this week? If not, I totally understand, but we're in a hurry because this week ends the development period for Symfony 2.7 and it's our last chance to make it happen for 2.x branch. Thanks.

**Comment by kbond** [comment]
Yes, I can work on this. Should it be rebased to the 2.7 branch then? Do I have to open a new PR?

**Comment by kbond** [comment]
Closed in favor of #14057

**Pull request closed without merging**
