### PR TITLE
fixxed order of usage

### PR DESCRIPTION
**Pull request by OskarStark**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13537 |
| License | MIT |
| Doc PR | - |

`[options] command [arguments]`

to

`command [options] [arguments]`

(i made some issues in this branch before #13538 )

### CODE REVIEW

**Comment by phansys** [comment]
:+1:

**Comment by sstok** [comment]
:+1:

**Comment by cordoval** [comment]
:+1:

**Comment by OskarStark** [comment]
i can't figure out why the CI-build is broken.

any ideas?

seems like ```master```is the problem, not the commit, or?

**Comment by mvhirsch** [comment]
:+1:

**Comment by stof** [comment]
I think this should be considered as a bugfix, and so applied in older branches

**Comment by OskarStark** [comment]
:+1:  i changed the PR header @stof

**Comment by phansys** [comment]
I think it should be applied on top of 2.6, because [these changes](https://github.com/symfony/symfony/commit/28edd30007aee351757260282856fa089d44b6e3) were introduced there: [Choose the right Branch](http://symfony.com/doc/current/contributing/code/patches.html#choose-the-right-branch).

**Comment by OskarStark** [comment]
@stof what do you mean?

@phansys looks like the code was moved there, but not initial written

**Comment by fabpot** [comment]
Thank you @OskarStark.

**Pull request closed without merging**
