### PR TITLE
[DependencyInjection] fix dumped YAML string

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by Tobion** [comment]
Some other calls don't use `dump` as well like `$definition->getFactoryMethod()`. Shouldn't they be wrapped as well?

**Comment by xabbuh** [comment]
If I am not mistaken parameters aren't supported for the other options. Though wrapping all these places doesn't hurt at all. I'll update.

**Comment by Tobion** [comment]
I thought it's about properly wrapping strings in quotation marks so they don't start with invalid `@` etc.

**Comment by xabbuh** [comment]
Exactly, though I think the places were I added this then too usually wouldn't contain forbidden characters anyway. But it shouldn't hurt to have this handling here.

**Comment by Tobion** [comment]
Thank you @xabbuh.

**Pull request merged**
