### PR TITLE
Update validators.hy.xlf

### PR DESCRIPTION
**Pull request by azatyan**
| Q             | A
| ------------- | ---
| Branch?       | 5.x for features / 4.4, 5.1 or 5.2 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by OskarStark** [comment]
Do you need help? Feel free to ping me 👌🏻

**Comment by azatyan** [comment]
> Do you need help? Feel free to ping me 👌🏻

Yes, you can review this translation

**Comment by azatyan** [comment]
> Do you need help? Feel free to ping me 👌🏻

Do you know armenian?

**Comment by OskarStark** [comment]
No 😄 

I meant more if I can help with the open PR's, looks like they all just contain the english version for know

**Comment by azatyan** [comment]
> No 😄
> 
> I meant more if I can help with the open PR's, looks like they all just contain the english version for know

I'm very busy with my Trello team. Sorry can't help just now )

**Comment by OskarStark** [comment]
Shall we close the PR for no and you reopen it any time soon?

**Comment by azatyan** [comment]
> Shall we close the PR for no and you reopen it any time soon?

It's your choice. I'm just a contributor

**Comment by derrabus** [comment]
Closing then. As soon as you have the time to contribute translations, please open a new PR (with actual translations please).

**Pull request closed without merging**
