### PR TITLE
created validator.tl.xlf for Form/Translations

### PR DESCRIPTION
**Pull request by ergiegonzaga**
| Q             | A
| ------------- | ---
| Branch?       | master  / 2.7 up to 4.0 for bug fixes 
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? |no 
| Tests pass?   | no
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by ergiegonzaga** [comment]
Hi sir, how to make a pull request wherein i would only embed one file change or commit,?

**Comment by ergiegonzaga** [comment]
Is there any files left sir I can translate to tagalog sir?

**Comment by nicolas-grekas** [comment]
Thank you @ergiegonzaga.

**Comment by nicolas-grekas** [comment]
There are no other files to translate, thank you again.

**Comment by ergiegonzaga** [comment]
Okay sir, your welcome :)

**Pull request merged**
