### PR TITLE
add missing translation for uuid validator

### PR DESCRIPTION
**Pull request by garak**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | related to #27984
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by ro0NL** [comment]
for `nl` it's

```
Deze waarde is geen geldige UUID waarde.
```

**Comment by apfelbox** [comment]
for `de`:

> Dies ist keine gültige UUID.

**Comment by Cydonia7** [comment]
For `fr`:
`Ceci n'est pas un UUID valide.`

**Comment by javiereguiluz** [comment]
For `es`:

```
Este valor no es un UUID válido.
```

For `eu`:

```
Balio hau ez da onartutako UUID bat.
```

For `ca`:

```
Aquest valor no és un UUID vàlid.
```

**Comment by 1ed** [comment]
en: https://github.com/symfony/symfony/pull/27993
hu: https://github.com/symfony/symfony/pull/27994

**Comment by fabpot** [comment]
Thank you @garak.

**Comment by fabpot** [comment]
Anyone willing to do a PR with the translations given in the comments here?

**Comment by apfelbox** [comment]
@fabpot PR in #27999

**Pull request merged**
