### PR TITLE
[DI] fix edge case in InlineServiceDefinitionsPass

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Looks like this can happen - dunno how
https://stackoverflow.com/questions/53558247/autowire-services-test-yaml-there-is-no-node-with-id-service-a

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Comment by kevin-lot** [comment]
Are there a workarround time to wait for next release ?

**Comment by stof** [comment]
@kevin-lot the normal schedule (i.e. outside security releases) is to have a patch release once per month (generally at the end of the month)

**Comment by RubenKruiswijk** [comment]
Is there a specific reason why this was not merged into v3.4.20 (https://github.com/symfony/symfony/compare/v3.4.19...v3.4.20)?

We experience an issue with doctrine filters (https://packagist.org/packages/gedmo/doctrine-extensions + https://packagist.org/packages/stof/doctrine-extensions-bundle) that cannot be found after this patch.

**Comment by nicolas-grekas** [comment]
About 3.4, this patch doesn't apply there. About any other issue, we're not aware of anything until someone opens an issue ;)

**Pull request merged**
