### PR TITLE
[Routing] AnnotationDirectoryLoader::load() may return null

### LINKED ISSUE #45259: AnnotationDirectoryLoader raises type error for abstract classes
### Symfony version(s) affected

6.0.4

### Description

`AnnotationDirectoryLoader::load()` has a return type `RouteCollection`, but it may return `null` in some situations
https://github.com/symfony/symfony/blob/4a31c2952e5f5ed3c4a374b833cc75d2f793851f/src/Symfony/Component/Routing/Loader/AnnotationDirectoryLoader.php#L28-L31

Because it calls parent::load(), which is `AnnotationFileLoader::load()`, which has return type `?RouteCollection`
https://github.com/symfony/symfony/blob/4a31c2952e5f5ed3c4a374b833cc75d2f793851f/src/Symfony/Component/Routing/Loader/AnnotationFileLoader.php#L45

### How to reproduce

1. have an abstract class that extends `\Symfony\Bundle\FrameworkBundle\Controller\AbstractController` (e.g. `abstract class AdminController extends AbstractController`)
2. have `config/routes/annotations.yaml` similar to:

```yaml
controllers:
    resource: '../../src/**/*Controller.php'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

```
3. upgrade from 5.4.4 to 6.0.4
4. `Symfony\Component\Routing\Loader\AnnotationDirectoryLoader::load(): Return value must be of type Symfony\Component\Routing\RouteCollection, null returned`

### Possible Solution

Change the return type of `AnnotationDirectoryLoader::load()` to `?RouteCollection`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mhujer**
Closes #45259.

| Q             | A
| ------------- | ---
| Branch?       | 6.0 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix  #45259 
| License       | MIT

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Good catch, thanks @mhujer.

**Comment by trsteel88** [comment]
@derrabus any chance of a patch version being tagged? I'm keen to launch a project on Symfony 6.0 and this is holding me up.

**Comment by trsteel88** [comment]
Actually, I've found a temporary workaround:

```
exclude: '../../src/Controller/**/AbstractController.php'
```

**Comment by derrabus** [comment]
We usually do releases by the end of the month. This patch will be part of the 6.0.5 release. Until then, please use the following constraint in your composer.json to get this patch:

```JSON
"require": {
    "symfony/routing": "~6.0.5@dev"
}
```

**Comment by trsteel88** [comment]
No worries. Thanks for the quick response.

**Pull request merged**
