### PR TITLE
[Doctrine][DoctrineBridge] Compatibility with ORM 3 and DBAL 4

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Follows #51947
| License       | MIT

This PR makes the 6.3 branch compatible with Doctrine DBAL 4 and ORM 3. It contains all changes from #51947 which does the same on the 5.4 branch.

Please note that I intentionally did not allow DBAL 4 in the dependencies of the monorepo's composer.json. If I did that, we would lose coverage for DBAL 3 completely which would be very unfortunate.

Right now, we should get the following test matrix:

* same deps: DBAL 3
* low deps: DBAL 2
* high deps DBAL 4

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks for the PR, I used it while merging 5.4 into 6.3 see b691c316f7

**Comment by nicolas-grekas** [comment]
> PHP Fatal error:  Declaration of Symfony\Bridge\Doctrine\Middleware\Debug\Statement::bindValue(string|int $param, mixed $value, Doctrine\DBAL\ParameterType $type): void must be compatible with Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware::bindValue($param, $value, $type = Doctrine\DBAL\ParameterType::STRING) in /home/nicolas/Code/symfony-symfony/src/Symfony/Bridge/Doctrine/Middleware/Debug/Statement.php on line 42


Please note that I pushed 913a317706780c843a7d1d7ed78e2e81a0d4d9e1 to fix such messages. Please double-check I did no mistakes.

**Comment by derrabus** [comment]
> > PHP Fatal error:  Declaration of Symfony\Bridge\Doctrine\Middleware\Debug\Statement::bindValue(string|int $param, mixed $value, Doctrine\DBAL\ParameterType $type): void must be compatible with Doctrine\DBAL\Driver\Middleware\AbstractStatementMiddleware::bindValue($param, $value, $type = Doctrine\DBAL\ParameterType::STRING) in /home/nicolas/Code/symfony-symfony/src/Symfony/Bridge/Doctrine/Middleware/Debug/Statement.php on line 42
> 
> Please note that I pushed [913a317](https://github.com/symfony/symfony/commit/913a317706780c843a7d1d7ed78e2e81a0d4d9e1) to fix such messages. Please double-check I did no mistakes.

That change does not look correct. My PR introduces dedicates `Connection` and `Statement` classes for DBAL 3 and 4. Your error could only occur if the DBAL 4 `Statement` has been loaded with DBAL 3 installed. We should rather investigate why that happens.

**Comment by nicolas-grekas** [comment]
I merged everything up to 7.0 but I'm pretty sure I made mistakes - at least this one. I need your help to double check + fix :pray:

**Comment by derrabus** [comment]
Let's cross fingers for #52022. 🤞🏻

**Pull request closed without merging**
