### PR TITLE
[Console] Fix tests for SymfonyStyle

### PR DESCRIPTION
**Pull request by 1ed**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15909 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
I don't think introducing such lineLength setting in the public API just to fix tests make sense

**Comment by 1ed** [comment]
@stof Yeah, it seemed a little odd to me too. So should I use reflection in the tests to access the private property or do you have something better in mind?

**Comment by stof** [comment]
yeah, using Reflection to force the length might be an option.

**Comment by 1ed** [comment]
Updated to use reflection instead.

**Comment by fabpot** [comment]
Thank you @1ed.

**Pull request merged**
