### PR TITLE
Fix BC break after split of ACL component

### PR DESCRIPTION
**Pull request by wouterj**
Until symfony 3.0, the ACL component should still be included in Symfony to avoid BC breaks.

I don't think we can trigger deprecation errors here to warn people that they have to include an extra require.

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by iltar** [comment]
:+1: this should fix the issue where people depending on `symfony/symfony` do not get it.

**Comment by nicolas-grekas** [comment]
This should not propagate up to master and we should instead tell people to add this dep explicitly in UPGRADING

**Comment by iltar** [comment]
@nicolas-grekas I agree, this should be a `2.8` only fix only. `3.0` is not supposed to have a dependency on the acl/acl-bundle in the core. This is something I missed in https://github.com/symfony/symfony/pull/15013 as I added it to `require-dev` instead of `require` for some reason.

I have made a start on the acl bundle as well. I might have to add this bundle in the same fashion to this `composer.json`: https://github.com/iltar/AclBundle/tree/feature/extract-from-core

**Comment by nicolas-grekas** [comment]
In fact, I worked around this BC break in 1270e725601e08a228d35c6c91cea61aea958b03 (same on me I did it silently :) )
This could be reverted on 2.3 on this PR is merged.

**Pull request closed without merging**
