### PR TITLE
Remove unnecessary retrieval and setting of data

### PR DESCRIPTION
**Pull request by trsteel88**
| Q | A |
| --- | --- |
| Bug fix? | No |
| New feature? | No - optimisation |
| BC breaks? | No |
| Deprecations? | No |
| Tests pass? | Yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | None |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thanks for this contribution. Please update the description of your pull request to include the "checklist table" as explained here: http://symfony.com/doc/current/contributing/code/patches.html#make-a-pull-request  Thanks!

**Comment by Tobion** [comment]
:+1: Should be merged in 2.3
Status: Reviewed

**Comment by xabbuh** [comment]
:+1:

**Comment by Tobion** [comment]
Thank you @trsteel88.

**Comment by trsteel88** [comment]
You're welcome @Tobion. Looks like this should be merged into master as well.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php

**Comment by xabbuh** [comment]
We frequently merge branches into higher branches. So this will be part of master soon.

**Pull request closed without merging**
