### PR TITLE
[Process] -fix when env variable in uppercase

### PR DESCRIPTION
**Pull request by alexndlm**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT

Fix when env var in uppercase.

### CODE REVIEW

**Comment by OskarStark** [comment]
Duplicate of #44538 ?

**Comment by GromNaN** [comment]
Is it possible to add a test to prevent any regression?

**Comment by nicolas-grekas** [comment]
Closing as duplicate yes. Thanks for the PR.
Please continue there.

**Comment by nicolas-grekas** [comment]
See #44538

**Pull request closed without merging**
