### PR TITLE
[FrameworkBundle] do not fail when MercureBundle is not installed

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by chalasr** [comment]
Can we throw this exception somewhere else? It seems nice for DX when one explicitly ask for the mercure transport via dsn.

**Review by derrabus — APPROVED** [review]

**Comment by xabbuh** [comment]
I don't know. Maybe @OskarStark has some ideas.

**Comment by OskarStark** [comment]
Sure, I think we can double check here and throw, after the scheme check:
https://github.com/symfony/symfony/blob/4818b282f75a38a3a2a52f7fed10037afbceae0b/src/Symfony/Component/Notifier/Bridge/Mercure/MercureTransportFactory.php#L44-L48

**Comment by OskarStark** [comment]
cc @mtarld

**Comment by mtarld** [comment]
Agreed, this is much better. So the definition can be removed if not used. :+1:

**Comment by chalasr** [comment]
Follow-up PR welcome for readding this check elsewhere :)

**Comment by chalasr** [comment]
Good catch, thanks @xabbuh.

**Pull request merged**
