### PR TITLE
[DependencyInjection] Add support for autowiring services as closures using attributes

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

When dealing with laziness on the consumer side, a common pattern is to wrap a heavy service in a closure and call it only when needed.

This PR adds attribute `#[AutowireServiceClosure]` for this purpose:

```php
// generate a closure that returns service "foo"
public function __construct(
    #[AutowireServiceClosure('foo')]
    \Closure $foo,
)
```

It also adds support for turning callables into closures with a new `#[AutowireCallable]` attribute:

```php
// generate a closure that calls "foo"::someMethod()
public function __construct(
    #[AutowireCallable(service: 'foo', method: 'someMethod')]
    \Closure $foo,
)
```

Of course, this fully leverages autowiring aliases, so that instead of "foo", you can use `MyInterface::class`.

### CODE REVIEW

**Comment by Neirda24** [comment]
Would this also be supported through yaml auto wiring ?

**Comment by GromNaN** [comment]
Do we really need the verbosity of instancing `new Reference`? I wish the same config could be expressed with simple arguments.

```diff
public function __construct(
-    #[Autowire([new Reference('foo'), 'someMethod'])]
+    #[Autowire(service: 'foo', method: 'someMethod')]
    \Closure $foo, // generates a closure that calls "foo"::someMethod()
)
```

**Comment by derrabus** [comment]
I agree with @GromNaN, using `Reference` here does not feel right.

What also concerns me is that the container has to know the class of the referenced service in order to know if `#[Autowire(service: 'foo')] Closure $foo` should be wired directly or through a service closure. That feels brittle.

I'd be in favor of a solution where we only look at the attribute and the parameter type. That means we need to be explicit about wiring a service closure.

```php
#[Autowire(serviceClosure: 'foo')] // Wires a closure that returns service "foo"
#[Autowire(service: 'foo', method: 'someMethod')] // Wires $container->get('foo')->someMethod(...)
#[Autowire(service: 'foo')] // Wires the service foo. If the parameter type is "Closure",
                            // $container->get('foo')(...) is wired instead.
```

**Comment by nicolas-grekas** [comment]
Thanks for the feedback. PR (and description) updated with two new attributes: `#[AutowireCallable]` and `#[AutowireServiceClosure]`.

**Comment by nicolas-grekas** [comment]
> Would this also be supported through yaml auto wiring ?

@Neirda24 this is already supported, see eg #41176 and #45878 which introduced `!service_closure` and `!closure` YAML tags respectively.

**Review by GromNaN — APPROVED** [review]
This is much more expressive and self-documented.

**Comment by Neirda24** [comment]
> > Would this also be supported through yaml auto wiring ?
> 
> @Neirda24 this is already supported, see eg #41176 and #45878 which introduced `!service_closure` and `!closure` YAML tags respectively.

Missed it ! Thanks 👍

**Comment by nicolas-grekas** [comment]
Merging as this blocks other PRs right now, but feel free to review after merge of course!

**Pull request merged**
