### PR TITLE
[Serializer] Don't overwrite $format variable in DateTimeNormalizer::normalize

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by dunglas** [comment]
👍

**Comment by xabbuh** [comment]
👍

**Comment by fabpot** [comment]
Does it fix a bug? I fail to see how this is important to change; we can probably find such other examples in the codebase.

**Comment by teohhanhui** [comment]
What is the policy? I can resubmit this for master if that's better. Or I
can make it part of #20217 if that's fine.

**Comment by fabpot** [comment]
@teohhanhui I'm not against this change, but this adds a lot of overhead for the core team for no actual benefit (reviewing the change to be sure it's safe, merging the PR, possible conflicts when merging old branches to newer ones, ...). So, I prefer to avoid PRs that don't really solve any issue. Doing this as part of #20217 is indeed an option, but honestly, I don't see the need for this change.

**Comment by teohhanhui** [comment]
Sometimes it's just hard to resist the urge of wanting to fix minor code
quality issues when you accidentally see it when working on something else.

So, just for the record, should minor code quality improvement PRs like
this generally be avoided? If that's the team's decision I shall of course
abide by it.

**Comment by nicolas-grekas** [comment]
The issue is that we have some experience in breaking Symfony by merging apparently minor things... So we learned to be careful...

**Comment by teohhanhui** [comment]
Should I close this?

**Pull request closed without merging**
