### PR TITLE
[Mailer] add Azure and Resend support to the UnsupportedSchemeException

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Review by fabpot — APPROVED** [review]
@OskarStark I'm wondering if we should create a checklist of things we should not forget when adding a new mailer/notifier (and publish it in the docs). WDYT?

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by OskarStark** [comment]
> @OskarStark I'm wondering if we should create a checklist of things we should not forget when adding a new mailer/notifier (and publish it in the docs). WDYT?

Makes sense, if I find some spare time, I will do it.

PS: Another option would be to have dedicated Carsonbot comment with the checklist when a new bridge is added

**Comment by fabpot** [comment]
> > @OskarStark I'm wondering if we should create a checklist of things we should not forget when adding a new mailer/notifier (and publish it in the docs). WDYT?
> 
> Makes sense, if I find some spare time, I will do it.
> 
> PS: Another option would be to have dedicated Carsonbot comment with the checklist when a new bridge is added

Carsonbot would be ideal but probably more complex to do. Starting with a manual list will be easier and bring a lot of value.

**Pull request merged**
