### PR TITLE
[Messenger] Add types to private properties

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by fabpot** [comment]
What about this one? It needs a rebase for sure at least.

**Comment by derrabus** [comment]
I'll do the rebase.

**Comment by derrabus** [comment]
Rebased and updated. PR is ready again.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @derrabus.

**Pull request merged**
