### PR TITLE
Default factory method

### PR DESCRIPTION
**Pull request by hbakhtiyor**

### CODE REVIEW

**Comment by sstok** [comment]
What is the reason behind this change? :)

**Comment by iltar** [comment]
@hbakhtiyor Can you please resolve the following points?
 - You're missing the PR header, please add it
 - You're missing a description why you make this PR
 - You forgot to update the tests

**Comment by xabbuh** [comment]
I fail to see why every service definition should have a factory.

**Comment by stof** [comment]
This is totally wrong. It breaks all service definitions out there (btw, the ``factory`` function does not exist, and it cannot create all services magically).

I'm closing this PR.

**Pull request closed without merging**
