### PR TITLE
removed useless PHPDoc

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]

**Comment by OskarStark** [comment]
there are a lot more, shall I remove them, too?

https://github.com/symfony/symfony/search?o=asc&q=%2A+Constructor.&s=indexed&type=&utf8=%E2%9C%93

**Comment by lyrixx** [comment]
Yes please

**Comment by ogizanagi** [comment]
It should start by targeting the lowest maintained branch (i.e 2.7), not 3.3. :)

**Comment by OskarStark** [comment]
> It should start by targeting the lowest maintained branch (i.e 2.7), not 3.3. :)

can you do this or shall I switch the branch?

**Comment by Simperfit** [comment]
You should do it since it will lead to a rebase

**Comment by OskarStark** [comment]
Refs https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2511

**Comment by OskarStark** [comment]
> It should start by targeting the lowest maintained branch (i.e 2.7), not 3.3. :)

done @ogizanagi

**Review by ogizanagi — APPROVED** [review]

**Comment by ogizanagi** [comment]
@OskarStark: There are still some tests failing.

**Comment by OskarStark** [comment]
> @OskarStark: There are still some tests failing.

*fabbot* is failing, but not related to this PR
*AppVeyor* is green
*travis* failed, due to now output for 10 minutes, I restarted via --force push

**Comment by nicolas-grekas** [comment]
can you still fix fabbot failure please?

**Comment by OskarStark** [comment]
> can you still fix fabbot failure please?

done @nicolas-grekas 👍

**Review by xabbuh — APPROVED** [review]

**Comment by OskarStark** [comment]
Hmm, I don't know why they are failing... 😢

**Review by nicolas-grekas — APPROVED** [review]
travis error is a false positive

**Comment by OskarStark** [comment]
> travis error is a false positive

good to know, thank you @nicolas-grekas

**Review by stof — APPROVED** [review]

**Pull request closed without merging**
