### PR TITLE
Allow autowire of fragment handler

### PR DESCRIPTION
**Pull request by XWB**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Autowiring the fragment handler throws a deprecation notice and won't work anymore in Symfony 4.

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fragment.handler" service to "Symfony\Component\HttpKernel\DependencyInjection\LazyLoadingFragmentHandler" instead.

Note: I'm not entirely sure if we need to do the same for `Symfony\Component\HttpKernel\Fragment\FragmentHandler`?

### CODE REVIEW

**Comment by XWB** [comment]
One of the tests has timed out. Please restart.

**Comment by fabpot** [comment]
We autowire services that are "mainstream" (where there are use cases for using them in user's projects). Can you tell us why you need to inject this service in your app? If it's not something most project's would do, I'd recommend to add the alias in your project instead of Symfony.

**Comment by XWB** [comment]
@fabpot We have several Twig extensions that use the fragment handler to render inline blocks inside editorial articles.

**Comment by nicolas-grekas** [comment]
I also feel like this doesn't belong to core.
Adding this alias in your app's config is still possible, that's what I'd also recommend.

**Pull request closed without merging**
