### PR TITLE
[JsonEncoder] Remove chunk size definition

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | 
| License       | MIT

Remove the `$forceEncodeChunks` boolean. 

This boolean was telling if the encoder should use `json_encode` or should yield as small strings as possible.
It was set to `false` by default and not easily configurable yet.

This configurable behavior has been removed.
Instead, we use `json_encode` directly if **the value that does not contain any object**. Otherwise, it'll be split (see the diff in `src/Symfony/Component/JsonEncoder/Tests/Fixtures/encoder/object_in_object.php`)

IMHO, this will fit most of the use cases, and remove a configuration complicated to understand.

### CODE REVIEW

**Comment by chalasr** [comment]
Build failures look related, could you check?

**Comment by mtarld** [comment]
Indeed, they're here because of the BC break between FrameworkBundle and JsonEncoder (because of the `$forceEncodeChunks` removal in constructors). It should disappear once merged

**Comment by stof** [comment]
This will not disappear once merged. The CI failure are legitimate, because your PR misses the update of service definitions in FrameworkBundle to use the new signature.

**Comment by mtarld** [comment]
It was missing my last update... Should be good then

**Review by chalasr — APPROVED** [review]

**Review by GromNaN — APPROVED** [review]

**Comment by GromNaN** [comment]
Thank you Mathias.

**Pull request merged**
