### PR TITLE
[Mime] Removes deprecated tests

### PR DESCRIPTION
**Pull request by 0x346e3730**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Follow-up from https://github.com/symfony/symfony/pull/41398 to fix CI for 6.0.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Sorry I wasn't clear enough. On legacy tests, calling deprecated code is expected! This PR is for 6.0:)

**Comment by 0x346e3730** [comment]
My bad, I hesitated and went for it as it's late, should be good now :) Not sure why it auto asked for review tho, sorry for the unnecessary pings :(

**Review by Nyholm — APPROVED** [review]
I think this looks good. 

`Address::fromString()` is removed in favour of `Address::create()`. These tests are no longer needed.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by 0x346e3730** [comment]
I just reviewed as I've sent the PR late yesterday, shouldn't I also delete fromStringProvider ?

**Comment by 0x346e3730** [comment]
> 
> 
> I just reviewed as I've sent the PR late yesterday, shouldn't I also delete fromStringProvider ?

It's still used in testCreateWithString, I don't know if renaming the provider is a good idea or not.

**Comment by Nyholm** [comment]
Good observation.

Let's rename it. There is no backwards compatibility issue with files in `/Tests/`

**Comment by nicolas-grekas** [comment]
The rename should happen on 5.3 then!

**Comment by nicolas-grekas** [comment]
Or better: don't rename

**Comment by Nyholm** [comment]
Oh... let's not rename it then =)

Im happy with this PR in its current state.

**Comment by 0x346e3730** [comment]
I'm cool with not renaming it too.

**Comment by Nyholm** [comment]
Awesome. Congratulations to your first contribution!

**Pull request merged**
