### PR TITLE
Update ParameterBag.php

### PR DESCRIPTION
**Pull request by ahmedali5530**
for recursively getting items from arrays

| Q             | A
| ------------- | ---
| Branch?       | 4.4 for features
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no  
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I would discourage using parameters this way.

**Comment by Tobion** [comment]
👎 we had this discussion before

**Comment by fabpot** [comment]
Was removed, so we won't add it back.

**Comment by ahmedali5530** [comment]
> 👎 we had this discussion before

can you share the link of discussion?

**Comment by Tobion** [comment]
you can search the github issues/prs or the file history of ParameterBag

**Comment by xabbuh** [comment]
@ahmedali5530 You can start with #14039 and then read through the linked issues/PRs.

**Pull request closed without merging**
