### PR TITLE
[Translation] [Loco] Simplify namespace

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | ---

Based on https://github.com/symfony/symfony/pull/40945#discussion_r620058173 (@nicolas-grekas )

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]
I'd like to rewrite the LocoProviderTest.php file, because it looks too complex. I simplified the mocking of responses in https://github.com/symfony/symfony/pull/40926/files#diff-b1104914549a3654ba982fdc521e72b9f7eab1021f8bf9896c228431267f6f8f

Would you like to do it here, or we do it in another PR?

**Comment by stof** [comment]
to me, that's a separate PR than changing the namespace (which could be considered ready)

**Comment by Nyholm** [comment]
There are still a few places that needs to be updated. Do a search for `Bridge\Loco\Provider` and you will find at least 3 hits.

**Comment by OskarStark** [comment]
Thanks Tobias 👍 fixed

**Review by welcoMattic — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
