### PR TITLE
[WebProfilerBundle] Added preview iframe for built-in IDE links

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/19973#issuecomment-248358257
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

I was playing with this a few days ago.. and i just finished it. I really like it :)

out

### CODE REVIEW

**Comment by ro0NL** [comment]
Given https://github.com/symfony/symfony/pull/21050#issuecomment-269189842 im not really sure about this. It could be too much, the experience is nice though.

The approach is simple.. but you can do it easily (custom) in your own projects. Code is here to take :+1: 

Closing for now.

**Comment by ogizanagi** [comment]
@ro0NL : Just to mention: I played a little around with the web profiler in a similar way a while ago, in order to make the whole profiler panel displayable in an iframe, which is pretty convenient to introspect what happens on the current page without leaving it/opening a new tab.
But as you said, I'm not sure it worth being in the Symfony core, as it is easily achievable by tweaking your project or making a little browser extension, and the benefits are almost only about saving a <kbd>CTRL</kbd> / <kbd>CMD</kbd>+<kbd>clic</kbd>.

**Comment by ro0NL** [comment]
> the benefits are almost only about saving a CTRL / CMD+clic

And switching tabs/windows, which can be huge in terms of experience / doing it many times each day.

**Comment by ro0NL** [comment]
Btw if we could do 50/50 split screen with the profiler, you'd really make my day.

This code snippet could work for both.. but i dont know how you did it? Was it less "complex".. better?

**Comment by ogizanagi** [comment]
Unfortunately, I think I don't have this snippet anymore. Anyway it was done at the time the 2.7 version was released, so it'll needs some styling tweaks.

But the solution is nothing more or less complex than your, simply exposing the whole profiler in an iframe.
If it makes sense to a majority, I or anyone else could easily replicate it (more advanced features like being able to navigate within very simply (history, backards and forward) would be great too).

**Comment by ro0NL** [comment]
@javiereguiluz WDYT? Does it solve a case? (considering we can do this for the whole profiler).

I understand devs most of the time live with their editor anyway.. so perhaps only this feature brings little value (other then better experience _if_ used, imo.). But to be honest i never considered the whole profiler on this... it blew my mind actually ;-)

I could definitely appreciate such a feature! But we shouldnt do it only because it looks pretty or so.. (but yeah.. marketing-wise that also could be a smart move ;-)).

**Pull request closed without merging**
