### PR TITLE
Add BC break note to UPGRADE-4.2.md

### PR DESCRIPTION
**Pull request by umpirsky**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Added a note about upgrade consequences. See #33473

### CODE REVIEW

**Comment by Taluu** [comment]
Shouldn't this target 4.2 instead of 4.4 ? Kinda missing the point...

**Comment by umpirsky** [comment]
4.4 is the default branch when browsing the repo, it should be visible on https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.2.md. If the change is distributed to all version branches up, then yes, it can go to 4.2.

**Comment by nicolas-grekas** [comment]
4.2 is not maintained anymore, so this should go to 4.3

**Comment by umpirsky** [comment]
Updated. :+1:

**Review by fabpot — APPROVED** [review]

**Pull request merged**
