### PR TITLE
New PHPUnit assertions for the WebTestCase

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | replaces #29990
| License       | MIT
| Doc PR        | n/a

While reviewing #29990, and working on some tests, I realized that we could do better by adding PHPUnit constraint classes in various components that are then used in WebTextCase.

**Before**

```php
<?php

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testSomething()
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/test');

        $this->assertSame(200, $client->getResponse()->getStatusCode());
        $this->assertContains('Hello World', $crawler->filter('h1')->text());
    }
}
```

**After**

```php
<?php

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testSomething()
    {
        $client = static::createClient();
        $client->request('GET', '/test');

        $this->assertResponseIsSuccessful();
        $this->assertSelectorTextContains('h1', 'Hello World');
    }
}
```

### CODE REVIEW

**Comment by fabpot** [comment]
Green and ready!

**Comment by javiereguiluz** [comment]
Minor comment: checking PHPUnit's assertions (https://phpunit.de/manual/6.5/en/appendixes.assertions.html) I saw that they don't define "negative asserts" (NotHas..., NotContains..., etc.) but here we're defining asserts in symmetric pairs: (assertResponseHasCookie() + assertResponseNotHasCookie(), assertInputValueSame() + assertInputValueNotSame(), etc.) Just in case you want to double check if we really want this. Thanks.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
@javiereguiluz If you have a closer look, you will see that PHPUnit defines a Not alternative for **almost all** their assertions.

**Comment by fabpot** [comment]
Thank you @Pierstoval.

**Comment by vudaltsov** [comment]
@fabpot , why it is not suffixed with `Trait` according to Symfony coding standards?
https://symfony.com/doc/current/contributing/code/standards.html#naming-conventions

**Comment by fabpot** [comment]
@vudaltsov Good catch! That's because I got the code from another PR and didn't think about that. Can you submit a PR to rename it properly?

**Comment by vudaltsov** [comment]
@fabpot , done, see https://github.com/symfony/symfony/pull/30842

**Comment by TomasVotruba** [comment]
Just wondering, the Symfony blog post mentions many assertsions that are not there.

E.g. `assertClientCookieValueEquals()`

When you search for this string in whole Symfony code ([here](https://github.com/symfony/symfony/search?q=assertClientCookieValueEquals+is%3Apr&type=Issues)), you see it was in previous PR, but never merged

Blog post should be updated with this PR, not previous one. It's very confusing

**Pull request merged**
