### PR TITLE
[HttpKernel] Fix typo in deprecation message

### PR DESCRIPTION
**Pull request by paullallier**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | not really - typo
| New feature?  | no
| Deprecations? | no
| Issues        | n/a
| License       | MIT

Just a minor typo

### CODE REVIEW

**Comment by derrabus** [comment]
Thank you for your proposal. However, this is not a typo.

**Comment by paullallier** [comment]
Oh, sorry @derrabus.  I assumed it was because the other deprecations in that file mention 8.0 - I guess I don't know how it works!

**Comment by xabbuh** [comment]
@paullallier We only deprecate features in the x.1, x.2, x.3 and x.4 minor releases. The code base of (x+1).0 is the same as the codebase of x.4 except for the deprecated code that is cleaned up. But we never introduce new features or deprecations in a new major release. But since we already know that we want to deprecate this code in the future during the lifetime of Symfony 8 the comment points to the next minor version where this will be possible.

**Comment by paullallier** [comment]
@xabbuh Thank you for clarifying.  I think I'm used to other projects that do the deprecation tidy up only at the (x+1).0 release.

I'm still slightly confused that the methods say they are deprecated at 8.0 though?  How does the class get deprecated at 8.1 if the methods are deprecated at an earlier minor release?  Does the class just remain with the methods inherited from the parent for that minor?

**Comment by xabbuh** [comment]
> I'm still slightly confused that the methods say they are deprecated at 8.0 though? How does the class get deprecated at 8.1 if the methods are deprecated at an earlier minor release? Does the class just remain with the methods inherited from the parent for that minor?

I think you are confusing changes to the class and to the methods. The method are already deprecated and will therefore be removed in 8.0. The class itself is not deprecated yet to make updating for third-party bundles easier IIRC. The (then empty) class will be deprecated in 8.1 and eventually gets removed in 9.0.

**Comment by paullallier** [comment]
I see now.  Thank you very much for taking the time to explain it, @xabbuh.

**Pull request closed without merging**
