### PR TITLE
	 [Security][SecurityBundle] Remove the HTTP digest auth

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | yes
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #24325, #24335 
| License       | MIT
| Doc PR        | N/A

To be merged once #24335 is merged up from 3.4 to master.

### CODE REVIEW

**Comment by chalasr** [comment]
Can we remove the reference in https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Security/Core/Resources/translations?

**Comment by ogizanagi** [comment]
Indeed. I spotted those ones, but forgotten to remove :) Thanks.

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
@fabpot wrong closing? Needs a rebase and good to go.

**Comment by fabpot** [comment]
I didn't see that the commit from 3.4 was there, so it's merged in a weird way, but merged :)

**Pull request closed without merging**
