### PR TITLE
[DependencyInjection][FrameworkBundle] Leverage array_is_list

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Use `array_is_list` instead of `count`+`range`+`array_key`

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
`symfony/polyfill-php81` should be added to the dependencies of FrameworkBundle and the DI component.

**Comment by jderusse** [comment]
ohh... I thought it was introduced in php 8.0

**Comment by derrabus** [comment]
Why did you close the PR? 😶

Adding the polyfill should be fine for both packages.

**Comment by jderusse** [comment]
indeed... 

I can't reopen it (branch delete). followup #44167

**Pull request closed without merging**
