### PR TITLE
[WIP] [Console]  Make creating single command app easier

### PR DESCRIPTION
**Pull request by soxofaan**
This is PR for the discussions started at #9564
intended to make it easier (less boilerplate) to create single command applications

At the moment it is still work in progress, but already started this pull request to keep the discussion going

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #9564 |
| License | MIT |
| Doc PR | n/a |
- [x] fix added but failing tests
- [ ] submit changes to the documentation
- [ ] finish the code

### CODE REVIEW

**Comment by RQuadling** [comment]
What is the status of this? Are we going to see the functionality as part of Symfony/Console?

If not any time soon, is there any chance of making this a package in its own right so that I can just composer require it?

**Comment by TomasVotruba** [comment]
Is this still relevant? 

@soxofaan How do you approach this now?

@rquadling I think you can make own package a put a link here.

**Comment by soxofaan** [comment]
sorry, I lost interest
I'm not doing PHP development anymore 
(and too much bikesheding to be honest)

**Comment by TomasVotruba** [comment]
In wasp numbers of issues can be difficult to solve easily.

So I guess you can close this.

**Comment by rquadling** [comment]
@soxofaan Well what particular shade of green SHOULD it be?

**Comment by rquadling** [comment]
It would be nice to have this as a natively supported feature of Symfony. Maybe as a helper class, supported and maintained within Symfony, rather than as a third party package.

**Comment by TomasVotruba** [comment]
It seems this issue is really stuck for last 2 years. Need to move or close

Could you help @symfony/deciders ?

**Comment by TomasVotruba** [comment]
I just found, there is article about this topic in Symfony docs: [Building a single Command Application](http://symfony.com/doc/current/components/console/single_command_tool.html)

**Comment by fabpot** [comment]
Closing in favor of #16906, which seems better.

**Pull request closed without merging**
