### PR TITLE
[FrameworkBundle] move Routing dep up to make tests pass

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Ping @Tobion

### CODE REVIEW

**Comment by Tobion** [comment]
This is ugly. I think we better rewrite the console descriptor tests to not test against the actual values but instead just the structure, e.g. with preg_match.
So in https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Descriptor/route_1.md instead of `Host Regex: #^localhost$#si` it just tests `Host Regex: .+`

**Comment by nicolas-grekas** [comment]
Hum, that's too much work. I updated the PR and too an other approach: raising composer deps a bit up.

**Comment by Tobion** [comment]
This needs to be done in 2.3 branch.

**Comment by nicolas-grekas** [comment]
Why is 2.3 green then ?

**Comment by Tobion** [comment]
Ah nvm. The descriptors were added later.

**Comment by Tobion** [comment]
:+1:

**Comment by jakzal** [comment]
I [was initially against](https://github.com/symfony/symfony/pull/13738#issuecomment-75026836) raising the for the sake of making these tests pass, as technically the FrameworkBundle can work with previous versions of the Routing component. 

However, now that I look at it, there's probably no use case for using FrameworkBundle without the whole stack and raising these deps doesn't make much harm. It still gives me a feeling we're postponing solving the issue.

So I'm +0.

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
