### PR TITLE
[PropertyInfo] Added Readable/Writable Interface

### PR DESCRIPTION
**Pull request by andrey1s**
…ccessReadableInterface`

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Added `PropertyAccessWritableInterface` and `PropertyAccessReadableInterface`

### CODE REVIEW

**Comment by sroze** [comment]
👋 @andrey1s. Could you explain the use-case you have for this? What value does it bring?

**Comment by andrey1s** [comment]
@sroze this allows you to use them separately in your libraries, for example
 ```php
    public function __construct(PropertyAccessWritableInterface $writable)
    {
        $writable->isWritable()
    }
```

**Comment by sroze** [comment]
I get the hypothetical usage but what is the actual use case that made you
send this pull-request?

**Comment by andrey1s** [comment]
@sroze 
what actual application do you expect, interfaces not yet implemented?
in fact, I cannot use it because the interfaces are not yet implemented in the component.

**Comment by Simperfit** [comment]
It is something you will use or it's juste because you find it better to separe them ?

**Comment by fabpot** [comment]
@andrey1s Can you tell us more about the use case you envision for this? We ask the question as we are not adding new features without "valid" use cases.

**Comment by andrey1s** [comment]
use `PropertyAccessReadableInterface` to get object properties that can be `Normalize` for Serilaize and `PropertyAccessWritableInterface` for `Denormalize`
```php
<?php

namespace App;

use Symfony\Component\PropertyInfo\PropertyListExtractorInterface;
use Symfony\Component\PropertyInfo\ PropertyAccessReadableInterface;
use Symfony\Component\Serializer\Normalizer\ContextAwareNormalizerInterface;

class MyNormalizer implements ContextAwareNormalizerInterface
{
    /**
     * @var PropertyAccessReadableInterface
     */
    private $accessReadable;

    /**
     * @var PropertyListExtractorInterface
     */
    private $propertyList;

    public function __construct(PropertyAccessReadableInterface $accessReadable, PropertyListExtractorInterface $propertyList)
    {
        $this->accessReadable = $accessReadable;
        $this->propertyList = $propertyList;
    }

    /**
     * @inheritDoc
     */
    public function normalize($object, $format = null, array $context = array())
    {
        $className = \get_class($object);
        $properties = $this->propertyList->getProperties($className);
        foreach ($properties as $property) {
            if ($this->accessReadable->isReadable($className, $property, $context)) {
                //own logic
            }
        }
    }
    /**
     * @inheritDoc
     */
    public function supportsNormalization($data, $format = null, array $context = array())
    {
        //own logic
    }
}
```

**Comment by stof** [comment]
And why can't you use the existing interface for that ?

**Comment by fabpot** [comment]
Closing as there is no more activity.

**Pull request closed without merging**
