### PR TITLE
[HttpFoundation][File] uses mother class methods instead of plain function

### PR DESCRIPTION
**Pull request by ghost**
Since inheriting from the spl class it seems beeter to use the mother class method for that checking

### CODE REVIEW

**Comment by fabpot** [comment]
What is the benefit of this change?

**Comment by stof** [comment]
This is broken. ``$this->isFile()`` does not take any argument, and it cannot be used here given we haven't finished instantiating the SplFileInfo.
And running tests tells you it does not work.

**Comment by Pherserk** [comment]
sorry

**Comment by Pherserk** [comment]
no benefits and serious syntax errors really sorry. just a PR raptus.

**Pull request closed without merging**
