### PR TITLE
[String] Fixed Quorum plural, and Quora singular in EnglishInflector

### PR DESCRIPTION
**Pull request by Dean151**
| Q             | A
| ------------- | ---
| Branch?       | 6.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Issues        | None
| License       | MIT

When asking English Inflector the plural of Quorum, we get Quora instead of expected Quorums.
Also added the relevant test coverage for it.

**Rationale**:
ApiPlatform removed their "legacy inflector" and started using Symfony/String inflector instead. Quorum was inflected to Quorums with Api Platform legacy inflection. Therefore, the migration to Symfony inflection introduce breaking changes (with possible workarounds)

**Problem**:
After discussion on Slack, it turns out that Quora could be a valid plural, as explained on Wiktionary: https://en.wiktionary.org/wiki/quorum#Noun
Therefore:
> quorum (plural [quorums](https://en.wiktionary.org/wiki/quorums#English) or [quora](https://en.wiktionary.org/wiki/quora#English))
> The plural [quora](https://en.wiktionary.org/wiki/quora#English) is sometimes objected to on the grounds that it is not grammatically correct: in Latin quorum is a plural pronoun, not a singular noun.

@xabbuh suggest that native speakers define which one is the most widely used to decide if this change is a good idea, or not. Debate is open :)

**Proposed solution**:
- Singular of Quora should return Quorum (Quora currently returned)
- Plural of Quorum should return both Quora & Quorums ; in an order to be defined depending on the most used one.

### CODE REVIEW

**Comment by Dean151** [comment]
Added rationale, and problem section in description.
We need to discuss which, from Quorums or Quora should be inflected by Symfony String.

**Comment by Dean151** [comment]
ChatGPT "knowledge" about this matter:

```
It seems there might be some confusion, as "Quorums" generally refers to a concept rather than a platform. Here’s a detailed comparison:

### Quora
**Description:** Quora is a question-and-answer platform where users can ask questions, provide answers, and engage in discussions on a variety of topics. It is a social media website that focuses on knowledge sharing.

**Key Features:**
- User-generated questions and answers.
- Upvoting and downvoting system to prioritize content.
- Personalized feeds based on user interests.
- Spaces (communities) for focused discussions.
- User profiles showcasing expertise and activity.

**Usage Scenarios:**
- Seeking expert opinions or crowdsourced answers.
- Sharing knowledge or expertise on various subjects.
- Networking with professionals and like-minded individuals.
- Exploring diverse viewpoints and discussions.

**Most Widely Used For:**
- Knowledge sharing.
- Q&A interactions.
- Community engagement on specific topics.

### Quorums
**Description:** "Quorums" typically refers to the minimum number of members required to be present at a meeting to make the proceedings of that meeting valid. This term is commonly used in the context of organizational, legislative, or governance meetings.

**Key Features:**
- Ensures legitimacy and representativeness of meetings.
- Defined by bylaws or regulations of an organization.
- Critical in decision-making processes within organizations or legislative bodies.

**Usage Scenarios:**
- Organizational meetings (e.g., board meetings, general assemblies).
- Legislative sessions (e.g., parliament, councils).
- Any formal gathering requiring a minimum attendance for decisions to be binding.

**Most Widely Used For:**
- Ensuring valid and representative decision-making in organizations.
- Compliance with governance rules and regulations.

### In Summary:
- **Quora** is a widely used platform for online Q&A and community discussions, suitable for individual knowledge sharing and crowdsourced information.
- **Quorums** is a concept used in organizational and legislative contexts to ensure that meetings and decisions are legitimate and representative.

**When to Use Each:**
- **Quora:** When seeking information, sharing knowledge, or engaging in discussions on a wide range of topics with a global online community.
- **Quorums:** When organizing or participating in formal meetings within an organization or legislative body to ensure decisions are valid and representative.

Quora, as a web platform, is much more widely used by the general public for knowledge sharing and community interaction. Quorums, being a procedural concept, is essential in specific formal and organizational contexts to ensure proper governance and decision-making.
```

**Comment by stof** [comment]
As both plurals are valid, I suggest that the EnglishInflector return both, which will be better for use cases able to deal with multiple candidates (like code trying to find the corresponding method in a class for instance, to support methods defined with any valid plural).
The question of the most common plural form still need to be answered to decide which form should be the first one in the array.

**Comment by Dean151** [comment]
Added quora to be singularized to quorum.
Added back quora in the plural list. Order not yet final 
@stof @xabbuh

**Review by fabpot — COMMENTED** [review]
I would keep quorums first to keep as this is what we return today.

**Comment by Dean151** [comment]
> I would keep quorums first to keep as this is what we return today.

@fabpot 
To be 100% transparent, "quorums" inflection was the behavior of ApiPlatform legacy inflector.
Symfony currently inflect "quorum" to "quora".
In a pure backward compatibility consideration, I'll put back quora to be the first return if that's okay for you.

For the reverse, quora plural is not inflected back to quorum. This is a new behavior that will be some kind of bugfix.

**Comment by fabpot** [comment]
Oops, you're right, quora first for Symfony BC.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Dean151.

**Pull request merged**
