### PR TITLE
[DependencyInjection] Add coverage for all invalid arguments in exportParameters

### PR DESCRIPTION
**Pull request by JhonnyL**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by javiereguiluz** [comment]
👍

**Comment by xabbuh** [comment]
Ah well, maybe we should split this PR: Merge everything but the ExpressionLanguage case in 2.3 and add the ExpressionLanguage test in 2.7.

**Comment by JhonnyL** [comment]
@xabbuh Should I split it into two different commits?

**Comment by xabbuh** [comment]
@JhonnyL That would be good.

**Comment by fabpot** [comment]
@JhonnyL Can you submit 2 PRs? One on 2.3 and one on 2.7?

**Comment by JhonnyL** [comment]
@fabpot I have created https://github.com/symfony/symfony/pull/18499 and https://github.com/symfony/symfony/pull/18500. Closing this one.

**Pull request closed without merging**
