### PR TITLE
[Ldap] Make LdapUserProvider::refreshUser() actually reload the user entry

### PR DESCRIPTION
**Pull request by Mathieudewet**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | 
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I'm sorry but I miss the point of this PR: why would an LDAP user provider have to know anything about a Doctrine ORM?

**Comment by Simperfit** [comment]
I don't think that's a right fix either :/

**Comment by chalasr** [comment]
LGTM now that the doctrine-related code has been reverted, deauthentication should be triggered if the user has changed on the ldap server.
Related https://github.com/symfony/symfony/issues/18401#issuecomment-221761554 from @csarrazi

> The refreshUser method actually only refreshes the user from the session, without checking whether he has changed or not. This could change at a later time, but know that when re-authenticating (during the refresh user phase), the password can not be compared, as it is not available anymore.

**Comment by chalasr** [comment]
@Mathieudewet Can you add a test and a note in the Ldap component's CHANGELOG file?

**Comment by csarrazi** [comment]
Note that this will break for session-based mechanisms. Stateless authentication modes (Basic / Digest) will be able to work, as the user never has to be refreshed, but any other authentication mode might break, if you are using the authenticated user credentials in order to fetch the user information (bind w/ authenticated user vs bind w/ search user). The only way this can work is with a search user.

👎 on this.

**Comment by chalasr** [comment]
Thank you for reviewing @csarrazi.
Closing as explained.

**Pull request closed without merging**
