### PR TITLE
[TwigBridge] Update main.css email stylesheet to latest foundation-emails release

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix 58309
| License       | MIT

Current email stylesheet ([main.css](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Bridge/Twig/Resources/views/Email/zurb_2/main.css)) is outdated. Update v2.2.1 (released in 2016) to v2.4.0 (released in 2022) to get latest bug fixes, etc.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Something is wrong with the history of this PR.
Can you please do something about it?
Note that PRs should not contain any merge commits. Please use `git rebase` instead.

**Comment by stof** [comment]
this PR tries to merge the whole history of Symfony 7.2 into the 5.4 branch...

**Comment by ghost** [comment]
Sorry, my mistake. Here's what I think happened: I forked the Symfony repo and switched to the 5.4 branch where I made the bugfix. Then I used GitHub's `Sync Fork` feature to keep my bugfix branch in sync; this is what created the merge commits.
I mistakenly thought `Sync Fork` would sync the 5.4 branch but looks like it pulled in all the changes from the 7.2 branch.

I'll close this PR and create a new one with just the updated CSS file.

**Comment by ghost** [comment]
OK, here's the updated PR: https://github.com/symfony/symfony/pull/58448

**Pull request closed without merging**
