### PR TITLE
[Routing][Serializer] Add annotation -> attribute aliases

### LINKED ISSUE #51381: [RFC] Consistently use the word "attribute" in all symbols
### Description

Doctrine Annotations have served us well, but PHP attributes are the future.

Our strategy for Symfony 6 was to support Doctrine Annotations and PHP attributes as two ways of annotating pieces of configuration to code. In Symfony 7, attributes will be the only supported way. However, we still use the word "annotation" in the codebase in an abstract sense (PHP attributes are a form of annotation). This might be confusing, so we might consider using the work "attribute" everywhere consistently.

I've opened this issue to collect all occurrences of the term and to discuss the possible impact on downstream projects.

- [x] The `serializer` integration of FrameworkBundle exposes a configuration option `enable_annotations`. Rename to `enable_attributes`.
- [x] The `validation` integration of FrameworkBundle exposes a configuration option `enable_annotations`. Rename to `enable_attributes`.
- [x] The Routing and Serializer components organize their attribute classes in a namespace called `Annotation`. Rename that namespace to `Attribute`.
- [x] When loading routes from attributes, the loader type is `annotation` although `attribute` is already an alias for that. Make `attribute` the only possible type.
- [x] Serializer uses a class named `AnnotationLoader` to load metadata from attributes. Rename to `AttributeLoader`.
- [x] Validation uses a class named `AnnotationLoader` to load metadata from attributes. Rename to `AttributeLoader`.
- [x] Routing contains classes `AnnotationClassLoader` and `AnnotationDirectoryLoader` for loading routes from attributes. Rename to `AttributeClassLoader` and `AttributeDirectoryLoader`.

If you find more TODOs, please drop a comment.

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #51381 
| License       | MIT

### CODE REVIEW

**Comment by GromNaN** [comment]
This is going to conflict with PR on #51920.

**Comment by nicolas-grekas** [comment]
There are some related failure to check ;)

**Comment by wouterj** [comment]
Fixed lots of typos. I believe the high deps tests are fixed when this is up merged into 7.0, all other failure seem unrelated.

**Review by derrabus — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @wouterj.

**Pull request merged**
