### PR TITLE
[HttpFoundation] Fix memory limit problems in BinaryFileResponse

### LINKED ISSUE #48692: Send partial content is not possible with BinaryFileResponse with memory_limit less than filesize
### Symfony version(s) affected

6.1.7

### Description

Hello. I got OutOfMemroy in BinaryFileResponse in stream_copy_to_stream function.
I try to send partial content with Accept-Range bytes but it doesn't work. 
I have memory_limit 256M in php.ini and i have file with size >= 512Mb. When i try to send response
```php
return new BinaryFileResponse('path_to_mp4_video_fil_greater_memory_limit');
```
I got 
```
Fatal error: Allowed memory size of X bytes exhausted (tried to allocate X bytes) in /var/www/html/vendor/symfony/http-foundation/BinaryFileResponse.php on line 323
```
What i expect?
I expect that response will use Range headers and will read file by chunkSize. And i see it in source code
```php
// symfony/vendor/symfony/http-foundation/BinaryFileResponse.php
elseif ($request->headers->has('Range') && $request->isMethod('GET')) {
            // Process the range headers.
            if (!$request->headers->has('If-Range') || $this->hasValidIfRangeHeader($request->headers->get('If-Range'))) {
                $range = $request->headers->get('Range');

                if (str_starts_with($range, 'bytes=')) {....
```
I tried to manually set `Content-Type` to `video/mp4` and manually set `Accept-Range` like this 
```php
$r = new BinaryFileResponse($file->filePath);
$r->headers->set('content-type', 'video/mp4');
$r->headers->set('accept-ranges', 'bytes');
// i expected that BinaryFileReponse has own logic to create Content-Range headers and Accept-Ranges based on current memory_limit or something else, but it doesn't 
return $r;
```

 but not works for me.

I did't know there is bug or not, but look's like buggy/unexpected behavior. It could use check for memory limit to switch "Range mode" if filesize >= memory_limit. And i think that HTTP-header response to Range header in BinaryFileResponse now incorrect, because it doesn't return `Content-Range` to "bytes=0-"

```
curl -v -H "Range: bytes=0-"
```
no `Content-Range` returned

### How to reproduce

First.
```
bin/console make:controller
```
Second create/get mp4 file with size > php memory_limit and put it to any not public directory.
Then in controller 

```php
return new BinaryFileResponse('path_to_mp4_video_fil_greater_memory_limit');
```

### Possible Solution

I create own custom class for this case

```php
class StreamedFileResponse extends Response
{
    private ?Request $request;

    private ?int $start;
    private ?int $end;
    private ?int $chunkSize;

    public function prepare(Request $request): static
    {
        $this->request = $request;
        parent::prepare($request);

        $this->headers->set('Accept-Ranges', 'bytes');
        $this->headers->set('Content-Type', 'video/mp4'); //<!-- FIX TODO:
        $this->setStatusCode(206);

        $fileSize = filesize($this->content);
        $this->headers->set('Content-Length', $fileSize);
        $start = 0;
        $end   = $fileSize - 1;

        if($this->request->headers->has('Range'))
        {
            $range = $this->request->headers->get('Range');
            if (str_starts_with($range, 'bytes='))
            {
                $rangeExp       = array_filter(explode('bytes=', $range));
                [$start, $end]  = explode('-', implode('', $rangeExp));

                $start          = (int) $start;
                $end            = (int) $end;
                if($start > $end || empty($end))
                {
                    $end = $fileSize - 1;
                }
            }

            $this->headers->set('Content-Range', "bytes {$start}-{$end}/{$fileSize}");
        }

        $this->start = $start;
        $this->end   = $end;
        $this->chunkSize = $this->start - $this->end <= 0 ? 1024 : $this->start - $this->end;

        return $this;
    }

    /**
     * Sends content for the current web response.
     *
     * @return $this
     */
    public function sendContent(): static
    {
        $fd = fopen($this->content, 'r');
        // move to begining
        fseek($fd, $this->start);

        while(!feof($fd))
        {
            $content = fread($fd, $this->chunkSize);
            echo $content;
            flush();
        }
        fclose($fd);

        return $this;
    }
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by glady**
see #48692

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #48692
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks for the PR. Can you please add a test case?

**Comment by glady** [comment]
I tried to have a look on a reproduction and a test case. I can add a test, that chunks are used with my changes, but I **failed** in reproducing hitting memory_limit.

I analyzed, why it happened in our application and found that there were two levels of output buffering. Closing both/all (instead of just one) did work **well for us**.

So my findings are:
* without output_buffering active (ob_get_level() === 0), the download works with -1 (as it is implemented)
* with one level of output_buffering active (ob_get_level() === 1), the download fails with -1 and works when I do stream_copy_to_stream in chunks (this PR), but I not fully understand why.
* with two levels of output_buffering, my patch does not work too.

So my PR is not valid for all cases, as developer I would have expected either closing all output buffers internally via
```
            while (ob_get_level()) {
                ob_end_clean();
            }
```
 or just throw an exception, if there is any output buffer active. For me it would help to see this dependency somehow, when using BinaryFileResponse. Its just not visible, that the file fully is loaded to memory instead of sent until you hit a file that does not fit in your memory limit.

**Comment by glady** [comment]
I thought about this some days now. Closing all output-buffers (via while) is possible in our specific case, so we need not to wait for this PR, but indeed especially for end-to-end functional tests it would be nice to be able to keep at least one buffer open in order to be able to check the content of the binary file response. In the test case, it will not exceed the memory limit. To change the code from -1 to $filesize would support this. In this case we would be able to close our one "known" buffer that catches all for some other reasons, but still would allow to put any code around it with separate handling like a test that checks a buffer afterwards.

I will check, if I can add testcases in order to demonstrate this.

**Comment by nicolas-grekas** [comment]
Thank you @glady.

**Pull request merged**
