### PR TITLE
[Process] use __METHOD__ where applicable

### PR DESCRIPTION
**Pull request by annesosensio**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by romainneutron** [comment]
Definitely :+1: 
Thank you very much @annesosensio !

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @annesosensio.

**Comment by nicolas-grekas** [comment]
:+1:

**Pull request closed without merging**
