### PR TITLE
[Messenger] Added check if json_encode succeeded

### PR DESCRIPTION
**Pull request by toooni**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

When trying to add a message to redis transport which can not be encoded with `json_encode` there is now a `TransportException` containing the `json_last_error_msg` as the message.
I had an issue where I tried to send an email through messenger by symfony mailer which contains a pdf attachment. Instead of an error while sending i got an error `Encoded envelope should have at least a "body"` which happened because the encoded message was `false`.

This is not exactly a bugfix, but IMO also not a feature worth being mentioned in the changelog so I am not sure I've filled out the Q/A correctly.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
for 4.4
can you please send another PR for 4.3, where the code is a bit different?

**Comment by toooni** [comment]
@nicolas-grekas 👍https://github.com/symfony/symfony/pull/35150 is targeted to 4.3

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Should we do the same for decoding?

**Comment by toooni** [comment]
@chalasr I am not sure. I don't think there is much to gain when doing the same for decoding.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @toooni.

**Comment by toooni** [comment]
@fabpot @nicolas-grekas Thank you very much. Can I direct you to the issue which led me to this PR? https://github.com/symfony/symfony/pull/33920#issuecomment-569516989

Right now the messenger aims to serialize the data in a readable format. This leads to issues with some transports (like redis, doctrine and probably SQS) because of the character encoding when having binary content. This is a problem especially if the mailer is used with an attachment (binary) through messenger.

I've fixed the issue by creating a `SafeSerializer` which encodes the data with base64 but I'd like to hear an opinion to what would be the best way to resolve this issue so I can try to create a proper PR.

**Pull request merged**
