### PR TITLE
[Security/Core] Fix wrong roles comparison

### LINKED ISSUE #35941: [security-core] Wrong roles comparison in hasUserChanged method
**Symfony version(s) affected**: 4.4 / 5.0

**Description**  

It seems there is mistake here :

https://github.com/symfony/security-core/blob/6251c8e432640106e6f2f045ac3b365f1af36d44/Authentication/Token/AbstractToken.php#L326

**How to reproduce**  

When simulating authentication, roles passed to UsernamePasswordToken have to be identical to user roles retrieve by user_provider. It doesn't make any sense. The fourth parameter of UsernamePasswordToken is useless in this case.

```
private function logIn()
    {
        $session = self::$container->get('session');

        $firewallName = 'secure_area';
        // if you don't define multiple connected firewalls, the context defaults to the firewall name
        // See https://symfony.com/doc/current/reference/configuration/security.html#firewall-context
        $firewallContext = 'secured_area';

        // you may need to use a different token class depending on your application.
        // for example, when using Guard authentication you must instantiate PostAuthenticationGuardToken
        $token = new UsernamePasswordToken('admin', null, $firewallName, ['ROLE_ADMIN']);
        $session->set('_security_'.$firewallContext, serialize($token));
        $session->save();

        $cookie = new Cookie($session->getName(), $session->getId());
        $this->client->getCookieJar()->set($cookie);
    }
```

**Possible Solution**
  
It should be :
```
if (\count($userRoles) !== \count($this->user->getRoles()) || \count($userRoles) !== \count(array_intersect($userRoles, $this->user->getRoles()))) {
```

instead of 
```
if (\count($userRoles) !== \count($this->getRoleNames()) || \count($userRoles) !== \count(array_intersect($userRoles, $this->getRoleNames()))) {
```

### PR DESCRIPTION
**Pull request by thlbaut**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #35941 
| License       | MIT

Fix wrong roles comparison.

### CODE REVIEW

**Comment by ajgarlag** [comment]
I've opened https://github.com/thlbaut/symfony/pull/1 to PR author branch with an small change to reproduce the bug, and to prevent a future regression.

**Comment by nicolas-grekas** [comment]
This would deserve more tests I suppose (note the I don't know if this is correct.)

**Review by chalasr — APPROVED** [review]
The added test looks good enough.

**Review by wouterj — APPROVED** [review]
Agreed with Robin, the tweaked test covers the BC regression introduced in 4.4

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @thlbaut.

**Pull request merged**
