### PR TITLE
[Form] Removed duplicated conditions

### PR DESCRIPTION
**Pull request by pamil**
Extracted common code fragment to private method.

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by pamil** [comment]
Don't know why it fails on PHP 5.6, it's not connected with this PR.

**Comment by stof** [comment]
This adds lots of method calls during the creation of a Form instance. And given that a form involves many Form instances, this makes things even worse.

I would like to see a profiling of the impact of this change on a page usign a big form.

**Comment by stof** [comment]
status: needs work

**Comment by pamil** [comment]
@stof Here you are :)

I used XDebug Profiler to check whether this refactoring affects efficiency so much. The form I was rendering is a massive one from Sylius - Product (Dashboard > Products > Edit). It seems like there is no measurable impact.

screenshot from 2015-08-05 21 22 52
screenshot from 2015-08-05 21 22 47

**Comment by pamil** [comment]
Status: Needs Review

**Comment by stof** [comment]
I suggest you to use https://blackfire.io, which allows to comparing profiles before and after easily

@webmozart IIRC, you had a repo containing some huge forms somewhere

**Comment by stof** [comment]
and btw, you are hightling the call in ``addEventSubscriber`` here in the call stack, but this is not the only place where it is used.

**Comment by pamil** [comment]
I may take a look at blackfire, just give me a moment :) 

Yeah, I know, it was looking for the biggest comparable part. Overall, there was ~4k calls to new method. Other calls are the same, we can assume that if these 730 calls does not make a difference, then another ~3.3k does not too, can't we?

Anyway, let's get back to code, the refactored one is a lot clearer. Adding a new method instead of pasting it 22 more times in the code is the obvious choice. If we were looking only at performance, we would pass form config as an array, by reference.

**Comment by stof** [comment]
@pamil comparing only some calls is not a right solution, and assuming that it will not have perf impact is precisely the opposite of profiling to have data about this subject.

Btw, regarding your solution about passing an array by reference, I highly doubt this would improve performance. References are forcing to copy the whole array regularly, using much more memory so it might actually degrade performance (and it would also allow to introduce many bugs by allowing other code to mess with internals)

**Comment by nicolas-grekas** [comment]
If the overhead is measurable, then I'd suggest to factor out the exception message in a private static property. This will fix the current inconsistency of messages in the FormConfigBuilder.

**Comment by pamil** [comment]
@stof Haven't got much time to run that blackfire.io, I may do that today.

Passing this config as an array is, of course, dumb idea, I used it to visualize that strong push towards performance isn't always the best choice :) 

Regarding your reply on array refrences, references in PHP does **not** force to copy whole array, it does exactly the opposite. PHP uses copy-on-change policy, which means, that if you change value of variable inside your function, it will be copied. If you do not, it won't.

```php
function foo(array $array) {
  return $array['qunatity'] + 5;
}

function bar(array $array) {
  $array['quantity'] += 5;

  return $array;
}

function baz (array &$array) {
  $array['quantity'] += 5;

  return $array;
}
```

Array for functions `foo` and `baz` won't be copied, because `foo` doesn't change its value and `baz` operates on reference (and has side effect too). Array for function `bar` will be copied, because its value does change.

Anyway, references in PHP are quite a weird thing compared to other programming languages.

@nicolas-grekas It's a good idea, I'll try blackfire and see what to do.

**Comment by nicolas-grekas** [comment]
@pamil about references, see http://schlueters.de/blog/index.php?url=archives/125-Do-not-use-PHP-references.html&serendipity[cview]=linear
It's a bit more complicated than what you just said as e.g. `count($array)` would triggers a copy.

**Comment by stof** [comment]
you can also read http://jpauli.github.io/2014/06/27/references-mismatch.html

**Comment by pamil** [comment]
Thanks! I was blind, PHP will never stop amazing me :)

**Comment by fabpot** [comment]
Closing as their no gain in that PR and no more feedback.

**Pull request closed without merging**
