### PR TITLE
Translator component has default domain for null implemented

### PR DESCRIPTION
**Pull request by Tobion**
no need to have default translation domain logic in 3 different places

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | hopefully |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by aitboudad** [comment]
:+1:

**Comment by fabpot** [comment]
:+1:

**Comment by Tobion** [comment]
Should be merged into 2.3 without problems.

**Comment by xabbuh** [comment]
Form type tests [are failing now](https://travis-ci.org/symfony/symfony/jobs/55686898#L2035).

**Comment by Tobion** [comment]
Thanks, fixed

**Comment by fabpot** [comment]
Thank you @Tobion.

**Pull request closed without merging**
