### PR TITLE
[FrameworkBundle] Fix for placeholder/title rendering.

### PR DESCRIPTION
**Pull request by relo-san**
Small fix for rendering placeholder on widgets in php templates.

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | no |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by fabpot** [comment]
Good catch @relo-san Can you add a test to avoid regressions?

**Comment by relo-san** [comment]
Yes. I will add test on this weekend.

**Comment by fabpot** [comment]
@relo-san Any news?

**Comment by fabpot** [comment]
@relo-san Can you finish this PR?

**Comment by fabpot** [comment]
fixed in #13647

**Pull request closed without merging**
