### PR TITLE
add callback to BinaryFileResponse

### PR DESCRIPTION
**Pull request by ricventu**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | yes  
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Added a callback to BinaryFileResponse, called after send of the content

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
This PR contains commits from the master branch. Please rebase against 4.4.

**Comment by ricventu** [comment]
rebased against 4.4

**Comment by lyrixx** [comment]
Hello, what is your use case?

**Comment by ricventu** [comment]
Hello,
after send the content of file I need to do some stuff instead of delete it, without the support of queue jobs or something else

**Comment by lyrixx** [comment]
Why don't you register a listener on `kernel.terminate` ?

**Comment by ricventu** [comment]
I will try it.  Thanks for your suggestion

**Comment by fabpot** [comment]
I agree with @lyrixx, let's close.

**Pull request closed without merging**
