### PR TITLE
[Form] repeat preferred choices in list of all choices

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10271
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by Seb33300** [comment]
See https://github.com/symfony/symfony/pull/23690

**Comment by xabbuh** [comment]
@Seb33300 I have now cherry-picked your commit from #23690 and updated the tests. Thank you for the initial work on it.

**Comment by xabbuh** [comment]
`deps=high` jobs will pass once the changes are in `master`

**Comment by Seb33300** [comment]
Maybe I misunderstood but if I didn't fixed the test on my previous PR it's because regarding the comments I thought we had to introduce this as a new optional feature (with a new option).

But maybe I am wrong

**Review by nicolas-grekas — APPROVED** [review]

**Comment by xabbuh** [comment]
@Seb33300 I think we should revisit the decision made back then. This only improves the rendering. Adding an extra option for this seems to be unneeded complexity.

**Comment by nicolas-grekas** [comment]
Back then the PR was not completed, so we didn't make any decision :)

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
