### PR TITLE
Changed private static properties to private const

### PR DESCRIPTION
**Pull request by simonberger**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

This PR changes all private static properties with read-only usage to private const.

### CODE REVIEW

**Comment by stof** [comment]
changing this only in master will make maintenance harder (we will get potential conflicts on all these places for each merge-up), while this provides little benefit.

As this applies only to private stuff, this can be changed at any time without any BC impact. So if we decide to apply such change on existing code, I would suggest doing that in the oldest supported branch, so that all maintained branches have that and don't conflict when merging up later. But given `private const` requires PHP 7.1, such change cannot be applied to the 3.4 branch. So using that strategy would require waiting for 3.4 to reach end of bug fix support, i.e. waiting until end of November 2020.

**Comment by simonberger** [comment]
@stof 
I would understand such a decision.
I just like this change to happen. Static const-like usage always reminds me of old code.

Whenever you decide to release this.
I like to not stop after changing private static but also protected and public static usage of the same way, This obviously would mean deprecating the old property and and having both for the rest of the 5.x releases.

Please let me also know if this is something you like to do.

**Comment by derrabus** [comment]
I agree that this would be a reasonable code modernization. If we do it, the patch should be applied to the 4.4 branch **after** the final bugfix release of the 3.4 branch.

**Comment by simonberger** [comment]
Ready for review now.
But I'll close it in a few days if its the decision to wait. No need to look at the code right now.

**Comment by simonberger** [comment]
An example which public static properties to potentially change is:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L147

The backward compatibility is rather easy as it is possible to assign the value of the new const to the static property.

I admit changing this with the necessary deprecation means a lot of documentation for this rather small change and is maybe not reasonable. On the other hand it is the only way to get rid of it with the clean upgrade strategy Symfony has.

**Comment by stof** [comment]
> I admit changing this with the necessary deprecation means a lot of documentation for this rather small change and is maybe not reasonable.

it even involves replacing the public property with a magic one. Otherwise, we have no way to trigger deprecations when using it.

**Comment by simonberger** [comment]
Yes, if there is a requirement of a thrown message this is necessary. But that's not a much higher complexity.
From your doubts for this PR; As the public static code changes can only be done in the master this probably would be the biggest impact for the development.

**Comment by ro0NL** [comment]
@stof soft-deprecating public static props would work, isnt it? AFAIK we cant even overload static props in php ..., so my proposal would be

````php
/** @deprecated use class::X instead */
public static $x = self::X;
public const X = ...;
```

**Comment by stof** [comment]
@ro0NL we cannot warn for such deprecation, so it might not be enough for projects to migrate.

And indeed, for static props, the trick of the magic property won't work.

**Comment by nicolas-grekas** [comment]
I think this might be worth doing in 4.4 immediately. I don't think 3.4 will evolute that much around those lines in the next 3 months.

**Comment by ro0NL** [comment]
> it might not be enough for projects to migrate

we could try :)

**Comment by simonberger** [comment]
If you accept it for 4.4 at this point I'll redo it on this branch. Let me know if this has been decided.

Regarding public/protected deprecation:
If showing the deprecation in the code and having the upgrade notes is enough, it is easily done.
[There are several request for static magic functions](https://bugs.php.net/bug.php?id=45002) but nothing seem to happen.

**Comment by simonberger** [comment]
@stof @xabbuh @dunglas Do you want those changes for 4.4 
now 👍  
or later 👎 
?
I'll close the MR this week but re-create it for 4.4 if no one comments/votes to do this later.

**Comment by stof** [comment]
if @nicolas-grekas is OK with doing it now in 4.4 rather than waiting, this is fine with me. He is the one doing the merge-up regularly, not me, so I will accept it if he thinks that the 2 months delay is not necessary.

**Comment by fabpot** [comment]
Let’s wait the end of 3.4 first.

**Pull request closed without merging**
