### PR TITLE
fix request scheme

### PR DESCRIPTION
**Pull request by wanglilong2013**
| Q      | A            |
| ------ | ------       |
| Branch       | master |
| Bug fix      | no     |
| New feature  | no    |
| BC breaks    | no     |
| Deprecations | no     |
| Tests pass   | yes    |
| Fixed tickets|        |
| License      | MIT    |
| Doc PR       |        |

Fix request scheme

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you explain what issue this change is going to fix?

**Comment by wanglilong2013** [comment]
> Can you explain what issue this change is going to fix?

I think request scheme should be judged with "REQUEST_SCHEME" not "HTTPS",but some times we enable the HTTPS but not use.

**Comment by wanglilong2013** [comment]
> Can you explain what issue this change is going to fix?

I think request scheme should be judged with "REQUEST_SCHEME" not "HTTPS",but some times we enable the HTTPS but not use.

**Comment by wanglilong2013** [comment]
> Can you explain what issue this change is going to fix?

I think request scheme should be judged with "REQUEST_SCHEME" not "HTTPS",but some times we enable the HTTPS but not use.

**Comment by wanglilong2013** [comment]
> Can you explain what issue this change is going to fix?

I think request scheme should be judged with "REQUEST_SCHEME" not "HTTPS",but some times we enable the HTTPS but not use.

**Comment by wanglilong2013** [comment]
> Can you explain what issue this change is going to fix?

I think request scheme should be judged with "REQUEST_SCHEME" not "HTTPS",but some times we enable the HTTPS but not use.

**Comment by ro0NL** [comment]
shouldnt the isSecure() fallback remain at least.. https://stackoverflow.com/questions/18008135/is-serverrequest-scheme-reliable

**Comment by nicolas-grekas** [comment]
Sorry, this change is wrong. Deciding the scheme is more complex and already implemented in the "isSecure" method.

**Pull request closed without merging**
