### PR TITLE
[DoctrineBridge] Fix bug when indexBy is meta key in PropertyInfo\DoctrineExtractor

### PR DESCRIPTION
**Pull request by insekticid**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #25834 
| License       | MIT

@dunglas could you check it?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@insekticid would you mnd adding a test case please?

Status: needs work

**Review by dunglas — APPROVED** [review]
When a test will be added.

**Comment by fabpot** [comment]
@insekticid Can you work on adding a test case for your bug fix? That's something we need to avoid future regression. Or do you need help?

**Comment by nicolas-grekas** [comment]
Status: needs work
(missing test case)

**Comment by insekticid** [comment]
I need some time to go back to this issue and write some tests

**Comment by insekticid** [comment]
added tests

**Comment by Simperfit** [comment]
Travis failure is unrelated.

Status: Needs Review

**Review by Simperfit — APPROVED** [review]
LGTM

**Review by dunglas — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Isn't it something that also needs to be fixed in 2.8?

**Comment by nicolas-grekas** [comment]
Thank you @insekticid.

**Pull request merged**
