### PR TITLE
Add symfony/translation to the dev dependencies of symfony/security

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

Fixes https://travis-ci.com/github/symfony/symfony/jobs/423605540#L6749

### CODE REVIEW

**Comment by Nyholm** [comment]
The original PR #38939 only added it in SecurityCore, not the Security package. 

What I fail to understand is why the CI didn't fail in #38939?

**Comment by stof** [comment]
@Nyholm it actually failed: https://travis-ci.com/github/symfony/symfony/jobs/423540387#L7036

**Comment by Nyholm** [comment]
It did! Good. 

But the foldable output was not helping..

**Comment by derrabus** [comment]
Oh wow, yes, why was a failed run folded? 😱

**Review by Nyholm — APPROVED** [review]
Im happy with this PR.

**Comment by stof** [comment]
> Oh wow, yes, why was a failed run folded?

@nicolas-grekas any idea here ?

**Pull request merged**
