### PR TITLE
[DependencyInjection] fix ambiguous services schema

### PR DESCRIPTION
**Pull request by backbone87**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? |  |
| Fixed tickets | #17460 #2122 |
| License | MIT |

### CODE REVIEW

**Comment by backbone87** [comment]
ref https://github.com/symfony/symfony/issues/2122

**Comment by javiereguiluz** [comment]
This issue seems very important. Could anyone who uses XML config verify it? Thanks! After all, people use XML because it validates the config ... so we must ensure that the validation is correct.

**Comment by xabbuh** [comment]
Best imo would be to have additional tests that ensure that an XML file that wasn't valid before now is parsed properly.

**Comment by stof** [comment]
@backbone87 can you add such a test ?

**Comment by backbone87** [comment]
if the XmlFileLoader is validating the loaded xml, then the schema should be covered by its test cases already?

**Comment by backbone87** [comment]
actually all the XmlFileLoader should fail without this ticket resolved, because the schema is invalid and therefore the xml cant be validated. i am not that familar with the validation behavior of libxml

**Comment by backbone87** [comment]
ok i have played around with the test cases of the XmlFileLoader and it seems like libxml doesnt care about unique particle attribution and therefore "succeeds" validating the services.xml files.
in general i have noticed some wacky applications of the whole validation, but i will open another issue for it.

in general the existing testcases cover that this PR is working as intented.

**Comment by xabbuh** [comment]
@backbone87 The thing is, if we cannot find an example that would fail without this change, there is no need to do it. So what I meant is that we need to find a failing example and have to add it on top of the already existing ones.

**Comment by backbone87** [comment]
@xabbuh it cant fail, because libxml doesnt seem to care about the problem in the XSD, but every other standards conforming tool reports this XSD as invalid without the fix

**Comment by backbone87** [comment]
i mean we could add a XSD linting test to the test suite, but that needs to use another XML tool than the ones bundled with PHP. every decent XSD editor lints automatically, so idk if its worth the hassle.

**Comment by backbone87** [comment]
whats missing here? any opinions on the latest comments?

**Comment by xabbuh** [comment]
The change itself looks good to me. :+1: 

But yeah I think we should use some external validation tool if that doesn't work properly with PHP.

**Comment by fabpot** [comment]
Thank you @backbone87.

**Pull request merged**
