### PR TITLE
[DI] Fix dumping some complex service graphs

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28296 (and its duplicates #28355 & #28362 ~+ possibly #28304~)
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by skalpa** [comment]
Works for me. Thank you 👍

**Comment by FabienSalles** [comment]
It fixed it on my side too.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by XWB** [comment]
I'm now getting other errors:

```php
(1/1) ErrorExceptionNotice: Undefined variable: f
--
in srcDevDebugProjectContainer.php line 1786
```

```php
(2/2) Twig_Error_Syntax
Unknown "abbr_class" filter.
```

**Pull request merged**
