### PR TITLE
[3.0][Security] Remove deprecated features

### PR DESCRIPTION
**Pull request by wouterj**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
You need to update the VoterFixture class to implement ``supports`` (or to get rid of the class). Otherwise the testsuite is broken.

**Comment by WouterJ** [comment]
@stof fixed by https://github.com/symfony/symfony/pull/15932 (wrong tests made it into the 2.8 branch)

**Comment by fabpot** [comment]
@WouterJ Can you finish this PR?

**Comment by WouterJ** [comment]
@fabpot done. I've also removed `AbstractVoter#isGranted()` now

**Comment by fabpot** [comment]
hmm, I've not checked, but I'm pretty sure they are some tests that need to be updated, no?

**Comment by WouterJ** [comment]
Indeed, found some other tests and removed them as well

**Comment by fabpot** [comment]
@WouterJ Looks like `property-access` is not in the `composer.json` (it's not even in 2.8 apparently)

**Comment by WouterJ** [comment]
@fabpot that's a bug introduced in https://github.com/symfony/symfony/pull/16007 and fixed in https://github.com/symfony/symfony/pull/16030 and not related to this PR, neither can I relate the other build failures to this PR.

**Comment by fabpot** [comment]
Thank you @WouterJ.

**Pull request merged**
