### PR TITLE
Extract the profiler to a new component

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | not use how to handle documentation |

This pull request extracts the HTTP profiler from the HttpKernel component to a new dedicated component: HttpProfiler. This is the first step towards splitting the HttpKernel component into reusable sub-components (see #9406 for more information about this strategy).

### CODE REVIEW

**Comment by barryvdh** [comment]
Is the point of this PR also to make the WebProfiler more of a stand-alone tool, usable by other frameworks that use the HttpFoundation (or even other request objects)? Cause that would be nice :)

**Comment by barryvdh** [comment]
> @fabpot  Any references to a multi-purpose profiler in PHP or other languages?

These 2 are both multi-purpose that do pretty much the same, run some collectors on the request, store the result and output it somewhere:
https://github.com/itsgoingd/clockwork
https://github.com/maximebf/php-debugbar


(And [Z-ray](https://github.com/zend-server-extensions), but that's not really PHP but in the Zend server)

**Comment by mickaelandrieu** [comment]
@fabpot do you have a "functional" roadmap on what do we need to do to finish this pull request ?
I want to help :)

**Comment by jelte** [comment]
I mostly agree with @webmozart , but I think the "ApplicationRun" is a bit over engineering.
as I see DataCollectors more as Observers of the application which subscribe to specific events and Collect the data based on those events being triggered. This method is already being used by current DataCollectors such as RequestDataCollector ( to collect the controllers ).
The issue I see with the ApplicationRun is that again you create something that is passed along to the DataCollectors which some or even most won't use.

I've been going through the DataCollectors and a lot of them never use the Request, Response or even Exception. ( you can check my experimentation at https://github.com/jelte/symfony/pull/1/files ) 
Having this dependency makes it impossible to reuse them for other data collection. 

Making DataCollectors not strictly dependant on them would allows for some reuse when creating other Profilers, such as a ConsoleProfile.

The DataCollector could then also be reused in other places and make the profiler and debug bar reusable in other projects.

What I basically did is make DataCollectors that require the Request dependant on the RequestStack and those that require the Response listen for the KernelEvent::RESPONSE. 

I think even the Profile::collect method can lose its arguments. By injecting the RequestStack the profile could get the required info from the RequestStack->getMasterRequest(). But I haven't played around with this yet.

**Comment by DavidBadura** [comment]
It would be awesome if the Web Profiler would be a stand-alone tool :-)

**Pull request closed without merging**
