### PR TITLE
[WebProfilerBundle] Add main template in twig toolbar

### PR DESCRIPTION
**Pull request by alOneh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Before :
web profiler twig toolbar before

After:
web profiler twig toolbar after

### CODE REVIEW

**Comment by stof** [comment]
What is the main template in case a page uses multiple calls to "$twig->render()`` ?

**Comment by alOneh** [comment]
The main template should be the first template call in a page

**Comment by iltar** [comment]
I don't think you can reliably resolve this unless you use `@Template()` as this is a reliable source for actions but `$this->render()` isn't. To be honest it's more useful to check which action is executed and manually check which template was called.

**Comment by javiereguiluz** [comment]
@alOneh I like this contribution and I think it can be really useful! However, as pointed by @iltar and @stof, I'm afraid this is one of those features that "can't" be implemented in Symfony because of its flexibility. There are a lot of advanced cases where you can't decide which is the main template. And even if you show the first template, that may be not enough.

**Pull request closed without merging**
