### PR TITLE
[2.7] Fix license headers

### PR DESCRIPTION
**Pull request by 1ed**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by derrabus** [comment]
:+1: 

Status: Reviewed

**Comment by stof** [comment]
This PR should contain only the files not fixed already in the 2.3 branch though (same for PRs against 2.8 and master), as we merge branches together.

**Comment by 1ed** [comment]
@stof that's the case here I think. I fixed 2.3 than I merged the fixed branch into 2.7 and fixed 2.7 as well and cherry-picked the fix commit so these are the fixes for 2.7 without my merge commit of 2.3, and the same for 2.8 but merged the fixed 2.7 branch.

**Comment by stof** [comment]
Thank you @1ed.

**Pull request merged**
