### PR TITLE
[Console] Added support for the ability to define the full_name template parameter

### PR DESCRIPTION
**Pull request by kvncrw**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18524 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by stof** [comment]
This does not correspond to the discussion on the issue.

Status: needs work

**Comment by kcrawley** [comment]
Status: needs review

**Comment by kcrawley** [comment]
hello?

**Comment by xabbuh** [comment]
Not sure if `$fullNamePrefix` is the best term to use here. What about something like `$executorScript`?

**Comment by ro0NL** [comment]
I think calling it `$prefix` would be just fine.. as it's consistent with the terminology of the `Process` component. 

Also.. what about using the `Application` class as extension point? i.e. `Application::setPrefix()`. Imho, this is a lot more DX friendly then setting the same command _prefix_ on each instance registered in the application.

`Command` can have a `setPrefix` on its own or just resolve from `Command::$application->getPrefix()` (which defaults to `PHP_SELF`). In case command classes get a `setPrefix` it could be set by the application when registerering and/or running commands (does it need to be in sync?).

My2cents :-)

**Comment by kcrawley** [comment]
`$prefix` would be perfectly fine.

My only reservations in regards to moving the getter/setter for prefix is the precedence that has been set by the getter/setter for `$name` that is already in place.

**Comment by fabpot** [comment]
As this is an edge case, changing `$_SERVER['PHP_SELF']` seems good enough to me.

**Pull request closed without merging**
