### PR TITLE
Fix author for class CachePoolClearerCacheWarmer

### PR DESCRIPTION
**Pull request by guilliamxavier**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/pull/35109#discussion_r363985644
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Closing as staled, we can reopen if the change is confirmed.

**Comment by teohhanhui** [comment]
I can confirm I wrote the original class.

Sorry for the lack of response, I have stopped doing Symfony / API Platform, and moved on to Rust.

**Comment by bastnic** [comment]
I can confirm @teohhanhui confirmation ;).

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @guilliamxavier.

**Pull request merged**
