### PR TITLE
removed usage of the deprecated EsiListener class in core

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
@fabpot Was there a special reason to keep the `EsiListener` class itself?

**Comment by fabpot** [comment]
Just for BC. It will be removed in 3.0.

**Comment by xabbuh** [comment]
Sure, you're right. I missed that this was opened against the `2.7` branch. Sorry for the noise.

**Pull request merged**
