### PR TITLE
Don't reference symfony/security

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by Simperfit — APPROVED** [review]

**Review by Tobion — APPROVED** [review]

**Comment by HeahDude** [comment]
Really nice move, but I guess this really needs a doc PR.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by HeahDude** [comment]
@ro0NL if the point is to stop to require `symfony/security`, we don't just need to do it internally in Symfony packages, but also to tell people to do so.

**Comment by stof** [comment]
@HeahDude that's the plan. But the first step was to remove internal references before launching such communication.

**Pull request merged**
