### PR TITLE
Leverage non-capturing catches

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
Is there any support in PHP CS Fixer that we can enable? That's we are doing in such situations to avoid having new occurrences in future PRs.

**Comment by fancyweb** [comment]
I don't think so because some static code analysis is needed to detect those cases.

New occurrences will probably happen because of old habits but that's ok I guess. We can just try to do our best in reviews and clean them once in a while.

**Comment by fabpot** [comment]
Thank you @fancyweb.

**Comment by apfelbox** [comment]
Maybe static analysis can detect these cases as unused variables. So it might at least show up in the CI.

**Pull request merged**
