### PR TITLE
[FrameworkBundle][Console] JsonDescriptor: Respect original output

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

I'm suggesting this one, because I recently pushed some changes to the descriptors, and of course, I'm not editing expected output fixtures by hand, but by dumping the real output to fixture files. But it's tiring to get false positive diffs when reviewing it. Descriptor tests already are painful enough 😅 

This PR respects the way elements are actually output. If it's ok to you, I'll submit some other PRs to upper branches, because there are more issues regarding this (items order for instance).

If it causes too much troubles getting this in sync with upper branches, let's close this and never talk about it anymore 😄

### CODE REVIEW

**Comment by stof** [comment]
AFAIK, the pretty-printing of empty arrays depends on the PHP version

**Comment by ogizanagi** [comment]
I tried myself with both PHP 5.6, 7.0 and 7.1.

**Comment by ogizanagi** [comment]
A quick test on https://3v4l.org/uLA1g seems to confirm there is no difference regarding empty arrays between PHP versions. :)

**Comment by nicolas-grekas** [comment]
merged up to master, cleaned. thanks @ogizanagi

**Pull request merged**
