### PR TITLE
[PropertyAccess] minor: constants as internal and removed unused var

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by Tobion** [comment]
:+1: Should be merged into 2.3

Status: Reviewed

**Comment by Tobion** [comment]
Hm actually `$guessedAdders` is used in 2.3, but not in 2.7?

**Comment by dunglas** [comment]
Yes because someone changed this behavior in 2.7 (before the optim).

**Comment by Tobion** [comment]
So which branch is this for?

**Comment by dunglas** [comment]
2.7

**Comment by Tobion** [comment]
But those constants have been added in 2.3

**Comment by dunglas** [comment]
@Tobion Removed the unused variable check has it is not applicable to 2.3 and already fixed in #16698. So must be merged in 2.3 now.

ping @symfony/deciders

**Comment by Tobion** [comment]
Thanks, but please use the right branch next time. It didn't apply cleanly.

**Comment by dunglas** [comment]
@Tobion thanks for the merge but I was just waiting for another :+1: to respect the core team rules. I would have done the merge by myself.

**Pull request closed without merging**
