### PR TITLE
Mutate remaining data providers to static ones

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

Non-static data providers are deprecated.

### CODE REVIEW

**Comment by alexandre-daubois** [comment]
Just saw @derrabus had the same idea in #58323 😄 

This one targets 5.4

**Comment by derrabus** [comment]
Yeah, I don't think we need to do this on 5.4. We likely won't ever run those tests with PHPUnit 11.

My current strategy is: Fix incompatibilities on 7.2 and if the patch applies cleanly on 6.4, backport it there.

**Review by derrabus — APPROVED** [review]

**Comment by alexandre-daubois** [comment]
Noted for the next ones. Thanks!

**Comment by derrabus** [comment]
Thank you @alexandre-daubois.

**Pull request merged**
