### PR TITLE
[Yaml] properly handle empty lines

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by stof** [comment]
no test added to cover it ?

**Comment by nicolas-grekas** [comment]
This PR was fixing failures, so it's already tested :)

**Comment by xabbuh** [comment]
Exactly, see https://travis-ci.org/github/symfony/symfony/jobs/683008149#L10058 for example.

**Pull request merged**
