### PR TITLE
Fix PHP8.2 str_split function returns empty arrays for empty strings

### LINKED ISSUE #49213: PHP8.2 str_split function returns empty arrays for empty strings
### Symfony version(s) affected

6.2.6

### Description

In PHP 8.2, the str_split function will returns empty arrays for empty strings.
See: https://php.watch/versions/8.2/str_split-empty-string-empty-array

### How to reproduce

No steps to replicate

### Possible Solution

We can use mb_str_split() instead

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by HuongNV13**
| Q             | A
| ------------- | ---
| Branch?       |  6.2 for bug fixes
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49213
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by xabbuh** [comment]
Switching to `mb_str_split()` would mean to change the behaviour on PHP < 8.2. I don't think that's the right solution.

**Comment by MatTheCat** [comment]
> This change can be a breaking change for applications that relied on this erroneous behavior in the implementations in older PHP versions.

Did you check if it was the case (in which case I think your PR will need tests) or did you just replace every occurrence?

The right solution may be to do nothing at all.

**Review by derrabus — CHANGES_REQUESTED** [review]
I agree with @xabbuh, we should not switch to `mb_str_split()`. Possible fix:

```php
str_split($someExpression) ?: ['']
```

**Comment by derrabus** [comment]
Also, if this really fixes a problem on PHP 8.2, we should target the 5.4 branch. Did you actually encounter an issue here or did you just change every occurrence of `str_split()`? I doubt that this change of behavior is a general problem for us, so we might not need to "fix" every call.

**Comment by stof** [comment]
Replacing `str_split` with `mb_strsplit` is not good. This changes from splitting bytes to splitting UTF-8 codepoints (assuming that the encoding used is UTF-8).

So a big -1 for this PR as it. It is much more likely to create bugs than to fix them.

**Comment by derrabus** [comment]
Let's close the PR then: We agree that it's not the right course of action and are not even sure it fixes a problem. Let's continue the discussion on #49213.

**Pull request closed without merging**
