### PR TITLE
[VarDumper] Add dd function, dump and die

### PR DESCRIPTION
**Pull request by Mrkisha**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

Laravel already has this functionality on top of `VarDumper`. Why not just make it available out of the box?

This is my first ever `PR`, any guidance and patient is appreciated.

### CODE REVIEW

**Comment by chalasr** [comment]
@Mrkisha There is no commit from you here, it is expected? 
You are apparently proposing to merge some commits from 2.7 into master, I guess it's a mistake.

If your description is no more than a proposal yet, you should open an issue instead.
Otherwise, you need to fork this repository and propose the changes from your fork in a specific branch.

See http://symfony.com/doc/current/contributing/code/patches.html

**Comment by WouterJ** [comment]
Welcome @Mrkisha! :)

Unfortunately, this feature was requested before (#13657) and rejected, because the core team doesn't see any benefit in these type of shortcuts.

As this is your first contribution, let's give me some tips to make your next contributions even more awesome:

 * Before creating a patch, first use the search functionality on the issue tracker and PR list to see if the feature is requested before. You can also first create an issue to get the opinion, which saves you the time of implementing a rejected feature.
 * New features are always created on master, not on 2.7. It seems like you edited the 2.7 branch directly. Please refer to the [Submitting a Patch](http://symfony.com/doc/current/contributing/code/patches.html) guide for more information and a step-by-step guide into contribution. (for instance, it's common to create a new branch per PR, so you can submit multiple PRs at the same time)

**Comment by Mrkisha** [comment]
Thank you. I appreciate.

**Comment by nicolas-grekas** [comment]
For reference, this is being reconsidered in #26970.

**Pull request closed without merging**
