### PR TITLE
[FrameworkBundle] Only run Notifier bridge test in fullstack suites

### PR DESCRIPTION
**Pull request by wouterj**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | n/a

This fixes the build failures when a new bridge is merged and the subtree split is not yet configured.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Does this mean we can remove all notifier bridges from the require-dev of the bundle?
Can you please give it a try?

**Review by nicolas-grekas — APPROVED** [review]
:tada:

**Comment by wouterj** [comment]
Turns out we can :smiley:

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @wouterj.

**Pull request merged**
