### PR TITLE
[FrameworkBundle] Fixed form type extensions priority ordering

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20332
| License       | MIT
| Doc PR        | ~

I've kind of insisted in https://github.com/symfony/symfony/pull/19790 to use the trait, but maybe a few line of codes of PHP won't kill the warmup and I hope will fix the BC break so we can can keep this needed feature before 4.0 next year.

@francoispluchino Could you please confirm whether or not this patch fixes your issue?

### CODE REVIEW

**Comment by HeahDude** [comment]
Tests have confirmed it "Php7 uses non stable sorting algos, on the contrary to php5" :(

**Comment by HeahDude** [comment]
@francoispluchino your version looks more stable https://github.com/symfony/symfony/pull/20993/commits/241684a105efe7901570c73bbd796cf17cbb0c72 ;) 🎉

**Comment by francoispluchino** [comment]
@HeahDude For this reason, I have proposed the PR #20995.

**Comment by HeahDude** [comment]
Closing in favor of #20995.

**Pull request closed without merging**
