### PR TITLE
[String] add $lastGlue argument to join() methods

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

An idea that came when reviewing https://github.com/symfony/symfony-docs/pull/12440

### CODE REVIEW

**Comment by ro0NL** [comment]
unicode defines a start/middle/end part: https://github.com/unicode-org/icu/blob/fd123bf023882f07bfacf51c39111be2f946d8f8/icu4c/source/data/locales/en.txt#L2008-L2019

this was on my list to investigate :) not sure it fits String component, as i was already skeptical about `$glue->join($strings)` for an API.

ultimately i want to format list values in ICU translation files, but the spec format is missing still :( https://github.com/tc39/proposal-intl-list-format

**Review by yceruto — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
@ro0NL I'm not trying to solve the 100% of the problem but the most common that we've all been using again and again. TC39 is another level of complexity (same reasoning about `title(true)`: it's not linguistically universal, yet it's common enough to deserve being supported out of the box.)

**Review by ro0NL — APPROVED** [review]
anyway, i think this feature is fine for non-localized stuff either way :+1:

**Review by OskarStark — APPROVED** [review]

**Review by gharlan — APPROVED** [review]

**Comment by gharlan** [comment]
What do you think about making the method static, like in Java: https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.CharSequence...-

For me, it is a kind of named special constructor for a string (and not a method for doing something with the glue string).
`$str = UnicodeString::join($array, $glue, $lastGlue);`

**Comment by nicolas-grekas** [comment]
I think it would make the method harder to discover.

**Review by javiereguiluz — APPROVED** [review]

**Comment by stof** [comment]
I'm not even sure this should belong to a String component, as it is more about dealing with arrays...

**Comment by nicolas-grekas** [comment]
@stof Python has it. That's a serious enough precedent to me.

**Pull request merged**
