### PR TITLE
[WebProfilerBundle] Disable the search toggle button on result page

### PR DESCRIPTION
**Pull request by hason**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I don't understand the reasoning of this change. Please explain a bit. Thanks!

**Comment by hason** [comment]
I think that toggle search form is on result/search page unnecessary. The search form should always be visible.

**Comment by fabpot** [comment]
I'm not sure this is worth it.

**Comment by hason** [comment]
Before:
The search form is hidden. I think that this functionality is unnecessary and confusing.

before

After:

after

**Comment by fabpot** [comment]
Indeed, I did not understand it that way. Can you open a new PR for that as I does not seem to be able to reopen this one. Thanks.

**Comment by javiereguiluz** [comment]
The search form is not hidden for me.

**Comment by javiereguiluz** [comment]
This is how it works for me:

profiler_search_form

**Pull request closed without merging**
