### PR TITLE
[securityBundle] Compare roles strictly when computing inherited roles

### PR DESCRIPTION
**Pull request by ghost**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15377 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
Could you please add a failing test case to avoid future regressions of this fix?

**Comment by bokonet** [comment]
@xabbuh: i tried to reproduce this failure in two other symfony projects with the same user/userRole structure unsuccessfully. The error occured only in one project, and we dont know why. I can not find any different configurations between the projects. I realy dont understand this error!
Sorry, i dont know how to add a failing test case...

**Comment by bokonet** [comment]
We looked into it again and discovered that this "nesting level to deep" error is in some way related to the count of doctrin entity-realtions. We removed a oneToMany relation and the error was gone. So it should be better to compare php objects strict, to avoid comparing every attribute and value of the first object with the second.

**Comment by stof** [comment]
I think this happens when you have an uninitialized Doctrine proxy as one of your roles, as this object will then have a reference to the entity manager, which itself keeps the proxy in its identity map, leading to an infinite loop when comparing the 2 big object graphs

**Comment by fabpot** [comment]
Thank you @bokonet.

**Pull request merged**
