### PR TITLE
Use PSR-4 everywhere instead of PSR-0

### PR DESCRIPTION
**Pull request by Seldaek**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #11189 |
| License | MIT |

Includes and replaces #11199

### CODE REVIEW

**Comment by stof** [comment]
@fabpot ping

I would vote for switching to PSR-4 at least for all subtree repos, to stop relying on the deprecated ``target-dir`` feature

**Comment by jrobeson** [comment]
yes please. Let's get this in 2.7 if possible

**Comment by Tobion** [comment]
@symfony/deciders please vote so it's not being delayed further

**Comment by Tobion** [comment]
Actually I guess it's already accepted as stof, seldaek and me already voted +1

**Comment by jakzal** [comment]
:+1:

**Comment by lsmith77** [comment]
+1 from me as well ..

**Comment by cordoval** [comment]
needs a rebase though :+1:

**Comment by Tobion** [comment]
Rebased in #14323

**Comment by Tobion** [comment]
merged

**Comment by derrabus** [comment]
:tada:

**Pull request closed without merging**
