### PR TITLE
[WebProfilerBundle] Remove loading status from AJAX toolbar after error

### PR DESCRIPTION
**Pull request by kucharovic**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by iltar** [comment]
:+1: I forgot to report this but I noticed it never stopped.

**Comment by xabbuh** [comment]
:+1: Should be merged into `2.8`, right?

Status: Reviewed

**Comment by iltar** [comment]
@xabbuh correct

**Comment by kucharovic** [comment]
@xabbuh yes, my bad.

**Comment by fabpot** [comment]
Thank you @kucharovic.

**Pull request closed without merging**
