### PR TITLE
[FrameworkBundle] add forward compatibility layer for FrameworkBundle

### PR DESCRIPTION
**Pull request by hhamon**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ~
| License       | MIT
| Doc PR        | ~

### CODE REVIEW

**Comment by hhamon** [comment]
This PR also depends on #22773.

**Comment by stof** [comment]
@hhamon technically, the dependency is the opposite one. The removal is the one depending on this one

**Comment by nicolas-grekas** [comment]
I guess a rebase is need to make tests green

**Comment by nicolas-grekas** [comment]
Thank you @hhamon.

**Pull request merged**
