### PR TITLE
[Intl] Backport #28070

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

This is a backport of #28070 for the Intl component, to ensure consistent data generation as much as possible across branches. I bumped into it after refactoring in https://github.com/symfony/symfony/pull/31337#issuecomment-488250475, which also targets 3.4

this should avoid some merge conflicts / inconsistencies.

### CODE REVIEW

**Comment by ro0NL** [comment]
Alternatively i can do a new PR for 4.2, after #31337, as the generated data is not really used by the translator component in 3.4 :confused:

**Comment by ro0NL** [comment]
I also remember i discussed with @nicolas-grekas to backport #28833 as well, AFAIK then we'll generate 100% the same data between 3.4 and 4.2 (we should check)

If so, we dont need to re-generate data per branch. One less trap, on more BC break...

**Review by nicolas-grekas — APPROVED** [review]
Dealing with this in the same days as translations.

**Comment by ro0NL** [comment]
> If so, we dont need to re-generate data per branch

actually this is a required step anyway, as we added timezones in master. So for each ICU update we need to remember  it :)

**Comment by ro0NL** [comment]
Discussed with @fabpot to close here and forget about it. Let's avoid the backporting/BC break hassle.

Given the re-generation is required per branch (sorry :P) we should rely on the process instead.

**Pull request closed without merging**
