### PR TITLE
[Mime] Fix EmailHeaderSame to make use of decoded value

### LINKED ISSUE #35062: [FrameworkBundle/Mime] Assert email (header) subject which contains non-ascii characters
**Symfony version(s) affected**: 4.4 and 5.0

**Description**  
When using the `assertEmailHeaderSame()` function on the `subject` header when it contains non-ascii characters results in a false assertion as the value is decoded.
Introduced in 4.4 with the FrameworkBundle see `\Symfony\Bundle\FrameworkBundle\Test\MailerAssertionsTrait` (and [blogpost](https://symfony.com/blog/new-in-symfony-4-4-phpunit-assertions-for-email-messages)).

**How to reproduce**  

```php
$mailer->send(
    (new Email())
        ->to('fabien@symfony.com')
        ->from('fabien@symfony.com')
        ->subject('Foó')
);
        
...

static::assertEmailHeaderSame($email, 'subject', 'Foó');
```

Currently results in:
```php
Failed asserting that the Email has header "subject" with value "Foó" (value is =?utf-8?Q?Fo=C3=B3?=).
```

**Possible Solution**  
**1)** Change the `\Symfony\Component\Mime\Test\Constraint\EmailHeaderSame::matches` function to use `getValue()` on the `HeaderInterface` instead of the `getBodyAsString()`. 
_Can't estimate the implications of that change._
**2)** Change the function `assertEmailHeaderSame` in `\Symfony\Bundle\FrameworkBundle\Test\MailerAssertionsTrait` to 
```php
public static function assertEmailHeaderSame(RawMessage $email, string $headerName, string $expectedValue, string $message = '', bool $rawValue = false): void
```
And pass the `$rawValue` to the constructor of the `\Symfony\Component\Mime\Test\Constraint\EmailHeaderSame` and in the `matches` function use
```php
$header = $message->getHeaders()->get($this->headerName);

if ($this->rawValue() {
    return $this->expectedValue === $header->getValue();
}

return $this->expectedValue === $header->getBodyAsString();
```
**3)** Introduce a `EmailSubjectSame` constraint in the Mime component which is a simplified version of the `\Symfony\Component\Mime\Test\Constraint\EmailHeaderSame` constraint (not having to have the `$headerName` passed through). In the `\Symfony\Bundle\FrameworkBundle\Test\MailerAssertionsTrait` add a `assertEmailSubjectSame` fucntion, specifically using the `EmailSubjectSame` constraint. 
_This solution is also reasonable as the 'subject' is a bit of a specific header within the email, also given this scenario._

I would like give it a go in fixing, what would be the most desirable solution?

### PR DESCRIPTION
**Pull request by evertharmeling**
Fixes #35062

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  |no
| Deprecations? | no
| Tickets       | Fix #35062
| License       | MIT

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by evertharmeling** [comment]
Do I need to take a look at the failed test? 

Looks like the hinted `\Symfony\Component\Mime\Header\HeaderInterface` (in `\Symfony\Component\Mime\Header\Headers`) does not have the `getValue` function. 

But in the implementation the `$header` will be of type `\Symfony\Component\Mime\Header\UnstructuredHeader` which does...

**Comment by nicolas-grekas** [comment]
Yes please, tests you be green (at least the ones related to this change)

**Comment by evertharmeling** [comment]
Test fixed, current fails are not PR related (Redis related)

**Comment by nicolas-grekas** [comment]
Thank you @evertharmeling.

**Pull request merged**
