### PR TITLE
[Security] ensure some empty classes cannot be instantiated

### PR DESCRIPTION
**Pull request by issei-m**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | maybe |
| New feature? | no |
| BC breaks? | potencially, but almost not |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Even if it is unlikelly to be used, this is a bc break.
So should be deprecated and throw an exception in 4.0 imo.

**Comment by iltar** [comment]
I agree with @Ener-Getick here. It will be very unlikely to be called, however I have noticed myself I sometimes spam my ctrl+space too fast and end up annotating this class instead of the security annotation when importing. If people don't realize this mistake, it will end up breaking their application.

**Comment by fabpot** [comment]
There is no BC break, the class is empty. If someone creates an instance, it's not covered by our BC break policy.

**Comment by iltar** [comment]
@fabpot considering having no constructor is like having an empty public constructor: `public function __construct() {}`, so it would be a BC break but only if you consider this

**Comment by fabpot** [comment]
Let's be pragmatic :)

**Comment by issei-m** [comment]
@Ener-Getick @iltar @fabpot Thank you guys for reviewing and giving an opinion me.
I agree with @fabpot. It's substantially not a BC break.

btw,

> end up annotating this class instead of the security annotation when importing. If people don't realize this mistake

We don't need concern about this because [instantiation of an annotation](https://github.com/doctrine/annotations/blob/2e1b1f7597e2f647e99e96e747fcae9718ac817b/lib/Doctrine/Common/Annotations/DocParser.php#L793-L797) is involved after check whether the class annotates the @Annotation,
if not, `AnnotationException` [will be thrown](https://github.com/doctrine/annotations/blob/2e1b1f7597e2f647e99e96e747fcae9718ac817b/lib/Doctrine/Common/Annotations/DocParser.php#L727).

**Comment by issei-m** [comment]
if this change is correct, can I change [SecurityEvents](https://github.com/symfony/symfony/blob/ace9a2210173fb8da0cee6936ffbd28428465020/src/Symfony/Component/Security/Http/SecurityEvents.php) and [AuthenticationEvents](https://github.com/symfony/symfony/blob/af4ca4f48b1aca08991f30ef7b4cdb58002c369e/src/Symfony/Component/Security/Core/AuthenticationEvents.php)?
If so, I will work on here.

Or rather I should find and apply this change to entirely PJ? 😲

**Comment by nicolas-grekas** [comment]
Is there any technical/UX benefit doing this change? We're basically saying this is not a BC break because nobody is instantiating it. So why should we care? Is there any IDE related benefit I'm missing? Some other one?

**Comment by issei-m** [comment]
@nicolas-grekas Actually, I'm not sure what benefit this change has. But Symfony has lots of the classes which has a private constructor such as [IpUtils], [ProcessUtils], [FormUtil], etc...
So this change intents to keep a consistency with these classes.

Although this change only applies to Security package, we might be better to apply to entire PJ. If so, I will do that.

[IpUtils]: https://github.com/symfony/symfony/blob/3067bdb8d9b34fb1a8450bd20275ba566c657aef/src/Symfony/Component/HttpFoundation/IpUtils.php
[ProcessUtils]: https://github.com/symfony/symfony/blob/f31e783fd4a44fe7959aa62a1c4e1d2af9aef2bb/src/Symfony/Component/Process/ProcessUtils.phphttps://github.com/symfony/symfony/blob/3067bdb8d9b34fb1a8450bd20275ba566c657aef/src/Symfony/Component/HttpFoundation/IpUtils.php
[FormUtil]: https://github.com/symfony/symfony/blob/83c15db887fd1f614716ea2de5853ac84054d604/src/Symfony/Component/Form/Util/FormUtil.php

**Comment by fabpot** [comment]
Let's close this one as it does not bring anything really useful and it is controversial.

**Pull request closed without merging**
