### PR TITLE
improve BrowserKit test coverage p1

### PR DESCRIPTION
**Pull request by eventhorizonpl**
Hi,

This PR improves BrowserKit test coverage.

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by stof** [comment]
shouldn't this be merged into older branches to cover it in all relevant versions ?

**Comment by fabpot** [comment]
2.3 is still maintained.

**Comment by stof** [comment]
IMO, it makes sense to add tests in 2.3

**Comment by eventhorizonpl** [comment]
Ok, I'll rebase it against 2.3

**Comment by eventhorizonpl** [comment]
Here is a new PR https://github.com/symfony/symfony/pull/17069

**Pull request closed without merging**
