### PR TITLE
[VarExporter] Drop support for partially initialized lazy object

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

Sidekick of #52568

### CODE REVIEW

**Comment by derrabus** [comment]
⚠️ This PR will break DoctrineBundle which has already been made compatible with Symfony 7.

**Comment by nicolas-grekas** [comment]
Ah, I forgot about this one. As I wrote on another PR, ORMv3 makes `LazyServiceEntityRepository` useless, we should deprecate and drop it.

**Comment by derrabus** [comment]
> ORMv3 makes `LazyServiceEntityRepository` useless

Yes, but we still need a solution for ORM 2 which will stay around for a while.

> we should deprecate and drop it.

`LazyServiceEntityRepository` is marked as internal, so we can drop that class without deprecation. If we find a way to keep the laziness of `ServiceEntityRepository` for ORM 2, I'm fine with the late removal of this feature. I won't have time to work on that though. 😕

**Comment by back-2-95** [comment]
So how to overcome this? My SF7 project I now need to keep `symfony/var-exporter` at `7.0.0-BETA1`.
Or is there some release coming which would fix this?

**Comment by stof** [comment]
There is an in-progress PR for DoctrineBundle.

**Comment by stof** [comment]
Actually, the PR is even merged. So if you use the dev version of DoctrineBundle, it should be OK.

**Comment by back-2-95** [comment]
2.11-dev or 2.12-dev ?

**Comment by nicolas-grekas** [comment]
Here is the PR: https://github.com/doctrine/DoctrineBundle/pull/1727

**Comment by stof** [comment]
2.11-dev for now. The change has not yet reached 2.12-dev as the merge-up between branches has not yet been done after the merge of that PR.

**Comment by back-2-95** [comment]
Ok, I required 2.11-dev for Doctrine Bundle and it worked. Now all my Symfony packages are RC1. Thanks for quick responses.

**Comment by derrabus** [comment]
I've released DoctrineBundle 2.11.1 that includes the fix.

**Pull request merged**
