### PR TITLE
[ExpressionLanguage] Fixed expressions cache key generation

### PR DESCRIPTION
**Pull request by inso**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Reworked version of #15537 

Difference with original PR:
- sort $names array to ensure its order does not affect caching, added test for it
- minor tweaks for cache key format
- used `foreach` instead of `array_map`

P.S. I'm not proficient with tests so not sure if tests are correct.

### CODE REVIEW

**Comment by sstok** [comment]
LGTM.

**Comment by inso** [comment]
ping @symfony/deciders

**Comment by Tobion** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @inso.

**Pull request closed without merging**
