### PR TITLE
[Contracts] add .gitattributes - exclude tests

### PR DESCRIPTION
**Pull request by iamvar**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I don't think this change is needed, because one is not supposed to use this package. You should reference individual contracts packages instead.

**Comment by iamvar** [comment]
Should we move tests in individual packages, then?

**Comment by nicolas-grekas** [comment]
What issue are you trying to solve?

**Comment by iamvar** [comment]
> What issue are you trying to solve?

With .gitattributes - it is obvious - reduce archive, exclude useless files for production...

Regarding folders structure - I just want to understand what is the repositories division strategy.
For example, Bridges, Components, etc have tests inside the final repository
e.g. https://github.com/symfony/symfony/tree/5.4/src/Symfony/Component/Notifier/Bridge/AllMySms

Should Contracts follow the same principles or they use another strategy?

**Comment by nicolas-grekas** [comment]
Contracts have their own layout yes.
About the size reduction, see my previous comment: use standalone contracts instead.

**Pull request closed without merging**
