### PR TITLE
[Translation] keep old array structure of resourcesFiles to avoid BC.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | #13897 |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by aitboudad** [comment]
related to https://github.com/liip/LiipTranslationBundle/pull/36

**Comment by stof** [comment]
does this allow to preserve the performance improvement or no ?

**Comment by aitboudad** [comment]
yes, as we don't load them in prod env.

**Comment by fabpot** [comment]
Thank you @aitboudad.

**Pull request merged**
