### PR TITLE
[DependencyInjection] fix the sorting by priority

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18482 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
This should make the test suite for `master` green again.

**Comment by xabbuh** [comment]
Ah, we need to update the required version of the DependencyInjection component too.

**Comment by xabbuh** [comment]
@symfony/deciders tests are passing

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
