### PR TITLE
[Filesystem] Issue 14066: makeRelativePath does not work correctly for root paths

### PR DESCRIPTION
**Pull request by jaytaph**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14066 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
@jaytaph Looks like something went wrong and you need to rebase onto the `2.7` branch.

**Comment by xabbuh** [comment]
Btw. would something like this also affect users on Windows?

**Comment by fabpot** [comment]
@jaytaph Can you rebase this PR?

**Comment by fabpot** [comment]
@jaytaph Can you rebase this PR as right now it includes a lot of noise? Thanks.

**Comment by fabpot** [comment]
see #16226

**Pull request closed without merging**
