### PR TITLE
[VarDumper][CliDumper][WIP] Add a way to export the HTML dump of the dumped var to view it in the browser

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Hello everyone !

When you dump a large object in a Console command for example, it is really hard to find what you are looking for because the dump can be thousands of lines long. As I'm often facing this problem, I decided to try to do something about it. 

My idea is to dump the var using the `HtmlDumper` in the `CliDumper`, export the result to an html file, and provide the link to this file to the user so he can open it in the browser, and use all the functionality (open and close nodes / search).

I just made this real quick to see if the idea is interesting enough for other people, this is why there is no tests nor configuration yet.

I think this option could be in three states : 
* disabled (default) : not enabled (current behaviour)
* only : only display link to the html dump and don't display the normal dump in the terminal
* both : display the normal dump and the link at the end

Also I was wondering two things : 
* Should this feature be directly implemented in the `VarDumper` component, or would it be better to do it with an extended `CliDumper` in the `FrameworkBundle` ?
* If it stays in the `VarDumper` component, where the configuration should be ? In the `FrameworkBundle` I guess ?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
The way this is implemented cannot be merged as it breaks e.g. SRP.
There could another totally different way to achieve something like this:
you could make the server:log listen to some port in HTTP, and dump the logs there in Html.

**Comment by fancyweb** [comment]
Hello @nicolas-grekas, I understand your concern. Your suggestion of how to implement it is great but I don't see how I can make it without breaking SRP too.

I will still need to use the `HtmlDumper` in the `CliDumper` to get the html output. The `CliDumper` will have to know where to send the html output (host + port) so there is still a need of configuration in the `CliDumper`. The sending of the html output has to be done in the `CliDumper` as well.

Maybe I did not understand your idea very well.

Also, shouldn't it be a new command that does this job ? I don't see what it has to do with logs. AFAIK, dumps are not in logs at all. And it would be way better to be able to use it only with the `VarDumper` component.

**Comment by yceruto** [comment]
I've needed this before too, for which I made my own `HtmlVarDumper` class to achieve it without having to lose the current one. it's quite easy to achieve through the `output` argument:

```php
// ...

class HtmlVarDumper
{
    public static $defaultOutput = 'output.html';

    private static $handler;

    public static function dump($var, $output = null)
    {
        if (null === self::$handler) {
            $cloner = new VarCloner();
            $dumper = new HtmlDumper(self::$defaultOutput);
            self::$handler = function ($var, $output = null) use ($cloner, $dumper) {
                $dumper->dump($cloner->cloneVar($var), $output);
            };
        }

        return call_user_func(self::$handler, $var, $output);
    }
}

function dump2html($var)
{
    foreach (func_get_args() as $var) {
        // dump using default output
        HtmlVarDumper::dump($var);
    }
}

/*** CLI MODE ***/

// dump all to output.html (by default)
dump2html($doctrine);
dump2html($em, $router);

// dump to custom output
HtmlVarDumper::dump($container, 'container.html');
```

**Comment by nicolas-grekas** [comment]
clearly as explained the implementation cannot be merged.
the comment from @yceruto can give some hints on how to move forward on the end goal.
Closing for now.

**Comment by fancyweb** [comment]
No problem on closing this indeed.

I actually made a very small bundle to fulfil my need (https://github.com/fancyweb/html-cli-dumper-bundle). I'm promoting it for future people that might end up on this PR.

**Comment by ogizanagi** [comment]
See #23831

**Pull request closed without merging**
