### PR TITLE
[Serializer] fix AbstractObjectNormalizer

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Fixes #46680

### CODE REVIEW

**Comment by chalasr** [comment]
Duplicate of #46842 :)

**Comment by chalasr** [comment]
Thank you @nicolas-grekas.

**Comment by nicolas-grekas** [comment]
Looks like this is still red when running cross-deps...

**Comment by chalasr** [comment]
Are you sure? 6.2 seems green

**Comment by nicolas-grekas** [comment]
Oh :thinking: 
Then we might have an issue with the CI, which doesn't use local packages anymore for PRs.

**Pull request merged**
