### PR TITLE
Remove invalid CSS white-space value

### PR DESCRIPTION
**Pull request by Mx-Glitter**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@Triiistan thanks for this fix. However, in addition to removing the wrong value, I'd like to replace it by the right property/value:

```css
word-break: break-all;
```

Thanks!

**Comment by Triiistan** [comment]
@javiereguiluz I've tested it and here are my results:
- Without `word-break: break-all;` (current situation)
without break-all
- With `word-break: break-all;`
with break-all

I feel like cutting inside words removes readability, what do you think?

**Comment by javiereguiluz** [comment]
@Triiistan the screenshots show an edge-case (the second line of the second log contains just a letter and it's weird). But in most cases, you see big gaps (like the second line of your first screenshot) because class namespaces are very long and browsers don't want to break them.

But honestly I don't have strong opinions for either side. The both have pros and cons.

**Comment by Triiistan** [comment]
Where it really changes things for example is on SQL query logs for example which can often spans on multiple lines. Cutting between words looks difficult to read IMHO, but I'm ok for doing that change if you don't feel the same way :smiley:

**Comment by fabpot** [comment]
Thank you @Triiistan.

**Pull request merged**
