### PR TITLE
[FrameworkBundle] Register the DataUriNormalizer

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | todo |

### CODE REVIEW

**Comment by xabbuh** [comment]
@dunglas Did we already make a decision on how to ensure the proper Serializer component version?

**Comment by dunglas** [comment]
IIRC, no. The easiest way is to register it in the extension with a call to class_exist. What do you think?

**Comment by dunglas** [comment]
ping @symfony/deciders

**Comment by weaverryan** [comment]
:+1: 

*Maybe* it should be configurable... but I can't think of when you would *not* want it (except for really optimizing for performance to not include this instantiated object) and we could add that later.

**Comment by mcfedr** [comment]
This is similar situation to https://github.com/symfony/symfony/pull/17603 where I have put a composer `conflicts` to make sure it has the correct version of the serializer component. 
My question would be, is there any reason for someone using version 3.0 of the component to want to upgrade the framework bundle but keep the old serializer component?

**Comment by dunglas** [comment]
@mcfedr Probably. The basic use case is a dependency requiring an old version of the component.

**Comment by dunglas** [comment]
@weaverryan for optimizations like that, a compiler pass can be used to remove unnecessary normalizers.

**Comment by mcfedr** [comment]
Most people would likely have a `^3.0.0` or similar dependancy.. Basically I'm not really fighting for either option being better, but I would be maybe more inclined to use the `conflict` to avoid having to introduce work arounds for old versions, which tend to make the code less clear.

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request closed without merging**
