### PR TITLE
[Console] remove readline support

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15583 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by OskarStark** [comment]
@xabbuh are there no tests, which have to be removed too?

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
@OskarStark no, see #15382

**Comment by OskarStark** [comment]
ah, thank you @xabbuh

**Pull request merged**
