### PR TITLE
[Configuration] improve description for ignoreExtraKeys on ArrayNodeDefinition

### PR DESCRIPTION
**Pull request by cordoval**
| Q | A |
| --- | --- |
| Bug Fix? | y |
| New Feature? | n |
| BC Breaks? | n |
| Deprecations? | n |
| Tests Pass? | y |
| Fixed Tickets | #13957 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by cordoval** [comment]
anyone on why travis is failing in that way "Pull request or branch commit hash has changed, aborting!" ?

**Comment by xabbuh** [comment]
@cordoval Since #14047 Travis builds are stopped for a PR when there are more recent commits pushed to it. Actually, only the build status of the last pushed commit is of interest.

**Comment by xabbuh** [comment]
Just curious: Did you push another commit which you removed again later?

**Comment by cordoval** [comment]
I did not @xabbuh

**Comment by fabpot** [comment]
Thank you @cordoval.

**Pull request merged**
