### PR TITLE
Add missing Albanian translations for Security and Validator components

### LINKED ISSUE #54548: Missing translations for Albanian (sq)
Hello,

There are some translation work needed for Albanian (sq) and we are looking for a **native** speaker to help us out. 

Here is a [short example](https://symfony-translations.nyholm.tech/#pr) of what you need to do. There are 4 rules: 

1. You must be a Albanian (sq) native speaker
2. You must look at the existing translations and follow the same "style" or "tone"
3. You must make your PR to branch 5.4
4. You must use the correct indentation (number of spaces)

These are the files that should be updated: 
- [src/Symfony/Component/Security/Core/Resources/translations/security.sq.xlf](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Core/Resources/translations/security.sq.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.sq.xlf](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Resources/translations/validators.sq.xlf)

<details>
<summary>Show related strings</summary>

#### src/Symfony/Component/Security/Core/Resources/translations/security.sq.xlf

| Id | English | Translation | Status |
| -- | -- | -- | -- |
| 20 | Too many failed login attempts, please try again in %minutes% minutes. | Shumë përpjekje të pasuksesshme për t'u identifikuar, ju lutemi provoni përsëri pas %minutes% minutash. | Needs review |

#### src/Symfony/Component/Validator/Resources/translations/validators.sq.xlf

| Id | English | Translation | Status |
| -- | -- | -- | -- |
| 113 | This URL is missing a top-level domain. | Kësaj URL i mungon një domain i nivelit të lartë. | Needs review |

</details>

> [!NOTE]
> If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by RiniMisini12**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54548 
| License       | MIT

Added missing Albanian translations, in
src/Symfony/Component/Security/Core/Resources/translations/security.sq.xlf and src/Symfony/Component/Validator/Resources/translations/validators.sq.xlf
files respectively.

### CODE REVIEW

**Comment by wouterj** [comment]
Thank you for the contribution!

Let's do a friendly ping to @llupa, another Albanian contributor, for a quick double-check of the new translations.

**Comment by nicolas-grekas** [comment]
Thank you @RiniMisini12.

**Comment by RiniMisini12** [comment]
Thank you as well✌️

**Comment by llupa** [comment]
@wouterj I flew back home a couple of hours too late! 

I am leaving this comment as a note to myself. The translation overall are ok but they have some minor grammar issues. Për Rinin, shumë faleminderit për kontributin!

- The first translation was in infinitive, reflexive, accusative  (për t'u indentifikuar) and was transformed in active voice accusative, but part of the infinitive remains (për të). If kept in active voice this case needs the ablative and the infinitive dropped completely.
- The second translation does not use compound sentences and *It* as a pronoun has been dropped completely. Needs to be added.
- Week validation messages are OK. But I am still mulling over whether using the ablative feels more natural sounding in Albanian.

**Pull request merged**
