### PR TITLE
Set server parameters without deleting defaults

### PR DESCRIPTION
**Pull request by aistis-**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no (?)
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12189 
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
@aistis- Can you please add a test to prevent future regressions?

**Comment by nicolas-grekas** [comment]
That's a new behavior, so it has the potential to break existing app that rely on the current behavior, isn't it?

**Comment by aistis-** [comment]
@nicolas-grekas It may affect someone's tests suite.

**Comment by nicolas-grekas** [comment]
The behavior change is a no go, but what about adding a new `$replace = true` argument on the method to allow one to opt-in the new behavior?

**Comment by nicolas-grekas** [comment]
ping @aistis-

**Comment by aistis-** [comment]
@nicolas-grekas it is a good suggestion for the parameter, even I do not like behavior control via parameters.

Sorry, I have not find any time yet for adding the tests :disappointed:

**Comment by aistis-** [comment]
@nicolas-grekas It still counts kinda a bug, because it is not possible to use `test.client.parameters` as it will never be used when creating a test client in tests.

Could you put bug label back and something like "easy pick"?

**Comment by fabpot** [comment]
Closing as this is not finished. Feel free to reopen when you have time. Thanks.

**Pull request closed without merging**
