### PR TITLE
[Cache] Fixed tests.. again

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  |no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

Hm.. Im sorry for the many PRs. 

I failed to fix this in #38709.

### CODE REVIEW

**Comment by derrabus** [comment]
Shall we also add `symfony/filesystem` to `require-dev` of `symfony/cache`? 🤔

**Comment by Nyholm** [comment]
symfony/cache has a dev dependency on symfony/config. So symfony/filesystem is already added. But sure. It is better to be explicit

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you Tobias.

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
