### PR TITLE
fixed obsolete getMock() usage

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Let's do it.

### CODE REVIEW

**Comment by hugohenrique** [comment]
Why not? ```$this->createMock```

**Comment by xabbuh** [comment]
@hugohenrique `createMock()` is only available in PHPUnit >= 5.4, but we need older versions to run the testsuite with PHP < 5.6.

**Comment by fabpot** [comment]
And to be honest, I prefer to use the same way everywhere.

**Comment by stof** [comment]
hurray for it. We will be able to upgrade simple-phpunit to use a more recent version of PHPUnit 5.x then

**Comment by nicolas-grekas** [comment]
The same PR needs to be submitted against 2.8 now, then etc up to master :)

**Comment by fabpot** [comment]
I've of course done that already

**Pull request merged**
