### PR TITLE
Updating the Request.php

### PR DESCRIPTION
**Pull request by sof1105**
Changing "#^(%[[:xdigit:]]{2}|.){{$len}}#" By "#^(%[[:xdigit:]]{2}|.){{".$len."}}#"

### CODE REVIEW

**Comment by stof** [comment]
What is the use case ?

**Comment by stof** [comment]
Btw, the 2.4 branch is not maintained anymore

**Comment by sstok** [comment]
Not sure whats happening here, `{5}` indicates it expects 5 characters not `{5}` literal but its doubled.

**Comment by jakzal** [comment]
The internal pair of `{}` is for variable expansion, so the two expressions are not equivalent - `#^(%[[:xdigit:]]{2}|.){5}#` vs `#^(%[[:xdigit:]]{2}|.){{5}}#`.

Closing as this change is wrong. Feel free to reopen with explanation on what you're trying to do and code that passes tests.

**Pull request closed without merging**
