### PR TITLE
removed dots at the end of @param and @return

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

For phpdocs, we only add dots for sentences like description, but not for @param and @return for instance. This PR fixes this issue.

This should probably be added to PHP-CS-Fixer as well (/cc @phansys @keradus).

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
See failures :)

**Comment by fabpot** [comment]
tests fixed

**Comment by keradus** [comment]
@fabpot 
Feel free to specify the requirements in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2020 (exactly https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2020/files#diff-4e353d9e86349c0daec425c628ad5688R32 ), eg do we want to keep `?` at the end or not (I would keep them, as during removal the sentence should be adjusted as well)

**Comment by GrahamCampbell** [comment]
@keradus PHP-CS-Fixer is removing them from other annotations like the deprecation one too. I don't think that is desired?

**Pull request merged**
