### PR TITLE
Optimize perf by replacing call_user_func with dynamic variables

### PR DESCRIPTION
**Pull request by ostrolucky**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

This provides similar boost as in https://github.com/symfony/symfony/pull/29245, but on more places and without complexity increase. Check eg. https://github.com/fab2s/call_user_func for proof 

Fabpot failure unrelated

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
AFAIK, these functions have no overheard when they're called with a `\`. That's because they're resolved at compile time. Would you mind verifying please?

**Comment by ostrolucky** [comment]
I did verify

**Comment by nicolas-grekas** [comment]
Verified here also, measurable perf gain confirmed.
Actually, we wondered about this change before and concluded we cannot do it because of PHP5.5 support: `call_user_func($a)` accepts more callables than `$a()` in PHP5.5. see https://3v4l.org/NGGth
Then, merging this into master is technically possible, but would open for years of merge conflicts we'll have to deal with weekly. I'd better not.

**Comment by nicolas-grekas** [comment]
What we could do is wonder case by case when such a change is safe doing for 5.5 (ie no `foo::bar` style can possibly be used) and merge them on 3.4.

**Comment by ostrolucky** [comment]
How do you solve these conflicts? Intellij knows how to resolve such simple conflicts automatically.
peek 2018-11-25 10-39

I don't think there are much cases when we can safely assume `foo::bar` is not used

**Comment by ostrolucky** [comment]
You can even configure it to do this automatically every time without asking ;)

**Comment by nicolas-grekas** [comment]
Closing as explained, thanks for submitting.

**Comment by ostrolucky** [comment]
What makes you think this will cause conflicts on weekly basis? Those lines are rarely changed. I really don't see how are changes like https://github.com/symfony/symfony/pull/29245 preferable over this one. Performance gain is very similar but lot of places benefit from it instead of one, it has 0 complexity penalty nor change of behavior and very easy to solve conflicts. Lastly, if you are so worried about merge conflicts that are solvable automatically, you should fix your merge tool.

**Comment by nicolas-grekas** [comment]
Then let's merge this in 4.1? 55 files modified, that's a lot of potential future conflicts I fear.

**Comment by nicolas-grekas** [comment]
Yes please rebase. We'll handle the 4.2-only sites either while merging or in another PR (eg you can keep this one for reference)

**Comment by ostrolucky** [comment]
rebased, only fabpot failures not cause by my changes

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ostrolucky.

**Pull request merged**
