### PR TITLE
[WebProfilerBundle] Re add missing link to the controller

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes (because it was on 3.2 but not in 3.3)
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

---

screenshot at 2017-07-26 10-54-16

### CODE REVIEW

**Comment by javiereguiluz** [comment]
It's nice to have this feature back ... but I'm afraid it looks very ugly.

What if we use a style similar to the sub-requests?

subrequests

We could display the controller only in the Request tab, like this:

controller

**Comment by lyrixx** [comment]
Oh you find it ugly :( My bad I was proud of my work :D 

Actually, my first attempt was what you proposed. And I found it ugly; jajaja.

Note: I moved the link on top of the tab name because the controller is related to the request / response et / etc. and not only the request.

**Comment by javiereguiluz** [comment]
What if we display the controller like this:

controller-1

And reduce the font-size of sub-requests controllers to 18px to display a better hierarchy:

controller-2

**Comment by lyrixx** [comment]
image

WDYT? As you can see, I did not had to change the CSS, And I'm quite happy to not add special rules for this.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
