### PR TITLE
[VarDumper] Add darsyn/ip caster

### PR DESCRIPTION
**Pull request by plandolt**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR | n/a

Created a caster for darsyn/ip IP class to get human readable information.

### Before
image

### After
image

### CODE REVIEW

**Comment by scuben** [comment]
Anyone any idea why PHP 7.2 test on travis fails?

**Comment by stof** [comment]
you need to add a dev requirement in the root composer.json too, otherwise the dependency will be missing when running tests in the fullstack repo (which is what happens on some CI jobs)

**Comment by ste93cry** [comment]
Although I see this as a valuable feature, why users should be forced to install a dependency that probably they don't need?

**Comment by scuben** [comment]
@ste93cry they are only required in `require-dev`.

**Comment by ste93cry** [comment]
Indeed, but this does not change the fact that users will download an unneeded dependency. If I don't need the dependency obviously I don't need the caster as well. There is nothing wrong in having a caster for this, as I said above I like that more and more types are supported by the `VarDumper` component but all things that depends on third-party libraries imho should be optional

**Comment by ogizanagi** [comment]
@ste93cry : dev-dependencies used by a package aren't required at all in a project using this package. [`require-dev`](https://getcomposer.org/doc/04-schema.md#require-dev) is a [root-only field](https://getcomposer.org/doc/04-schema.md#root-package).

The third-party library is required from `symfony/var-dumper` side in order to write and run tests about this feature. This won't make it a dependency at all in your project. It's still optional.

**Comment by ste93cry** [comment]
>dev-dependencies used by a package aren't required at all in a project using this package. [`require-dev`](https://getcomposer.org/doc/04-schema.md#require-dev) is a [root-only](https://getcomposer.org/doc/04-schema.md#root-package) field.

Oh, I didn't remember this. Then it's fine, sorry for raising a non-issue. By the way, I would still prefer to have this feature in the library/bundle that provides the library the caster is acting on, but this is just my opinion

**Comment by nicolas-grekas** [comment]
Too bad the IP class [is deprecated](https://github.com/darsyn/ip/blob/develop/src/IP.php#L7) in the develop branch. BTW, the deprecation notice should really be silenced on that line, and it's strange to deprecate something on a future major-version branch btw. Ping @zanbaldwin

About the caster, I'd suggest some improvements:
- the $ip and $version properties should be displayed as existing: caster should tell the reader what the actual internal structure is.
- when displaying the $ip property, I would suggest to use a ConstStub to display either a short or a long IP depending on the IP version
- then, for all other virtual props, what abut nesting them in a "details" array? (with keys version+long+short removed of course)
- what about also compacting zeros to `:` in v6 IPs?

There is one remaining thing: this caster changes the state of the object by initializing the $version property. Could that be fixed?

**Comment by zanbaldwin** [comment]
Hi! Just dropping by to say that I've seen this and will get back to you soon (probably the weekend), I'm a little bogged down with work in the new year.

/cc @nicolas-grekas: will silence the deprecation notice, got any advice for the library?

**Comment by scuben** [comment]
I'll update the PR when I get a change to get back to OSS. Like @zanbaldwin there is much work in the new year.

@zanbaldwin I think you should create a new minor version with all the deprecations mentioning the removal in the next major.

**Comment by nicolas-grekas** [comment]
Status: needs work

**Comment by nicolas-grekas** [comment]
I'm closing here because the `IP` class is deprecated.
Don't hesitate to resubmit when darsyn/ip will have clarified the situation (as currently, it doesn't make sense, as explained above.)
Thank you for the PR anyway.

**Pull request closed without merging**
