### PR TITLE
[String] improve slugger's portability accross implementations of iconv()

### LINKED ISSUE #36880: slug() crop string
**Symfony version(s) affected**: 5.0.*

**Description**  
slug() crop string after some symbols if `ICONV_IMPL === 'glibc'`

**How to reproduce**  
```
public function __construct(SluggerInterface $slugger) {
    $slug = $slugger->slug('Отель Отель')->lower(); // 'Ote'
    $slug = $slugger->slug('ль Отель')->lower(); // ''
    $slug = $slugger->slug('Рь Отель')->lower(); // ''
}
```

**Possible Solution**  
`AbstractUnicodeString.php`
```
} elseif (ICONV_IMPL === 'glibc') {
    $s = iconv('UTF-8', 'ASCII//TRANSLIT', $s);
} else {
```
change to
```
} elseif (ICONV_IMPL === 'glibc') {
    $s = iconv('UTF-8', 'ASCII//IGNORE//TRANSLIT', $s);
} else {
```

**Additional context**

### LINKED ISSUE #38060: Exception "Symfony\Component\String\UnicodeString" requires a translit-able iconv implementation...
**Symfony version(s) affected**: 5.1.5

**Description**  
With **Windows 8** and **PHP 7.4**, an exception is thrown: 

Here the phpinfo if needed : https://gist.github.com/Surfoo/293c14052c882c08bfab1368af38a3e7
```
Exception "Symfony\Component\String\UnicodeString" requires a translit-able iconv implementation, try installing "gnu-libiconv" if you're using Alpine Linux.
```
Exception

**How to reproduce**

In a controller : 

     dd((string) $this->slugger->slug('🐎 test unicode character'));

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36880, fix #38060
| License       | MIT
| Doc PR        | -

Ping @Surfoo @edguar, can you please confirm that this fixes your issues?

### CODE REVIEW

**Comment by kdambekalns** [comment]
I'd love to help, but none of the linked issues are known to me… 🤷‍♂️

**Comment by nicolas-grekas** [comment]
Oups sorry @kdambekalns , bad ping.

@edguar could you please have a look?

**Comment by Surfoo** [comment]
Hello  @nicolas-grekas,

Works for me, thank you!

Just for my curiosity, why don't you have some unit tests on a matrix of differents environments?

**Comment by nicolas-grekas** [comment]
Having a matrix of possible iconv implementations looks impossible to me. That's a zoo I know nothing about...

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
