### PR TITLE
[VarDumper] Fixed HtmlDumper with long string

### PR DESCRIPTION
**Pull request by alOneh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
Can you post a screenshot before and after ?

**Comment by alOneh** [comment]
Before :
before fix

After :
after fix

**Comment by stof** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @alOneh.

**Pull request merged**
