### PR TITLE
[PropertyInfo] Extract nullable and collection key type for Doctrine associations

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by teohhanhui** [comment]
Test failures are unrelated.

**Comment by dunglas** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @teohhanhui.

**Pull request merged**
