### PR TITLE
[Security] backported phpdoc from Guard component.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by hhamon** [comment]
This PR fixes https://github.com/symfony/symfony/pull/16910

**Comment by derrabus** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
:+1:

**Comment by dunglas** [comment]
:+1:

**Comment by hhamon** [comment]
Someone to merge this PR please ;)

**Comment by Tobion** [comment]
Thanks @hhamon.

**Pull request merged**
