### PR TITLE
[Workflow] Trigger `entered` event for subject entering in the Workflow for the first time

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28319
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
please submit a doc PR if applicable

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.

**Comment by lstrojny** [comment]
I think this should be considered a BC break since it changes the signature of `Workflow\Event::getTransition()` from `getTransition(): Transition` to `getTransition(): Transition|null`?

**Comment by lyrixx** [comment]
There was not typehint nor PHPDoc on this method, so I guess this was not a BC break.
More over, this has been merged 2 year ago and you are the first one to report that, so I guess this is fine.

**Comment by lstrojny** [comment]
The argument that a lack of PHPDoc makes it not a BC break doesn’t sound convincing to me as one wouldn't realistically expect users to assume `getTransition(): mixed` before Symfony 4.3. And yes, it’s probably too late anyway to do anything about it. I don't know what the practice it but adding it to the 4.3 upgrade guide might be a good idea.

**Comment by xabbuh** [comment]
I think adding this to the upgrade file is a good idea as changing this again is too late. @lstrojny Would you like to send a PR changing the `UPGRADE-4.3.md file (on the `4.4` branch)?

**Pull request merged**
