### PR TITLE
[Security] [Core] Harden StringUtils against mb.func_overload

### PR DESCRIPTION
**Pull request by sarciszewski**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

See also #13983

### CODE REVIEW

**Comment by sarciszewski** [comment]
http://fabbot.io/patch/symfony/symfony/13984/e09d0269bc744bc682ca05c5c928edc088ce7991/cs.diff

**Comment by cordoval** [comment]
weird CS is failing, are you still inserting white spaces? you can also use php-cs-fixer to get rid of those there in that class

**Comment by sarciszewski** [comment]
I'm not using a local editor, I'm using my web browser on github.com

**Comment by cordoval** [comment]
can you send a PR from the cli then?

**Comment by sarciszewski** [comment]
Maybe later.

**Comment by nicolas-grekas** [comment]
I saw two issues with this approach, so I opened #14024 as an alternative proposal.
The issues are: the majority with mbstring enabled will take the slow code path, and the implementation of mb_strlen iterates through the string to get its result, which is exactly what this function tries to avoid (leaking length time).

**Comment by stof** [comment]
I suggest using @nicolas-grekas's implementation

**Comment by sarciszewski** [comment]
Conversely, I suggest asking @ircmaxell before doing anything weird. He's
the one who taught me about mbstring.func_overload

**Comment by ircmaxell** [comment]
@nicolas-grekas it's impossible to avoid leaking length information, no matter how hard you try (thanks to things like CPU caches). So rejecting a fix because it leaks length information is a bit of an issue.

Additionally, when using the `8-bit` charset to `mb_strlen`, it won't "iterate through the string". In fact, it takes the short path of [setting the length to the binary length](http://lxr.php.net/xref/PHP_TRUNK/ext/mbstring/libmbfl/mbfl/mbfilter.c#811) due to [using `MBFL_ENCTYPE_SBCS` (single byte character set)](http://lxr.php.net/xref/PHP_TRUNK/ext/mbstring/libmbfl/mbfl/mbfilter_8bit.c#43). 

Therefore, the entire reason for the alternative PR is incorrect. I'd strongly suggest avoiding #14024

**Comment by sarciszewski** [comment]
I think fabbot is broken. Also, the service hook to Travis too? It didn't update the previous whitespace commit.

**Comment by nicolas-grekas** [comment]
I though there was some kind of charset validation like iconv does, but you proved me wrong. Thanks for the info+src link @ircmaxell. Then your other comments remain about casting+concatenating but you also says we shouldn't care too much as leaking is unavoidable. Does it apply here or do you think we should do better here?

**Comment by ircmaxell** [comment]
@nicolas-grekas I'm drafting a patch to fix it (which will also supersede this patch) mainly to clean up the comparison function.

**Comment by sarciszewski** [comment]
:+1: looks great to me

**Comment by Tobion** [comment]
That mb.func_overload is not used is a requirement for symfony. So there is no point it harden it against it, esp. if just done in one place.

**Comment by ircmaxell** [comment]
@Tobion in security sensitive contexts, it's important. 

Especially seeing as `mb.func_overload` is not checked for component usages, having the hardening is quite important.

**Comment by sarciszewski** [comment]
> So there is no point it harden it against it, esp. if just done in one place.

I disagree strongly, to the point that it's taking a phenomenal amount of restraint to maintain a modicum of politeness.

There is no point hardening a configuration error that can cause this function to misbehave in a possibly security affecting way, in a framework where you don't know how people will configure their environment or how this component will be used?

**Comment by fabpot** [comment]
Closing in favor of #14024, which includes these changes (it's much easier for everyone to work on one PR).

**Comment by sarciszewski** [comment]
Yes, choose the worst of three PRs to work with. Perfectly logical. *ragequit*

**Comment by fabpot** [comment]
@sarciszewski Sorry about this. I thought the third PR was really just about getting the changes from your PR and #14028, and then adding on top of it, but I read too fast (just by looking at the commit list.) I apologize for the mistake and I'm reopening this PR.

I'm no security expert and I trust you and @ircmaxell on those matters, so I will let you let me know which one(s) should be merged.

**Comment by sarciszewski** [comment]
Okay, I can see how that mistake could be made. My vote is for #14028 above even my own PR. (This one can remain closed.)

**Pull request closed without merging**
