### PR TITLE
Disable platform checks

### LINKED ISSUE #38803: AppVeyor build broken on 4.4
**Symfony version(s) affected**: 4.4-dev

**Description**  
Our AppVeyor build is currently broken. Each test suite fails with the following error:

```
Composer detected issues in your platform:
Your Composer dependencies require the following PHP extensions to be installed: mbstring
```

The reason for that is a failed platform check enforced by Composer 2. That check for `ext-mbstring` is installed because PHPUnit explicitly asks for the extension:

https://github.com/sebastianbergmann/phpunit/blob/e936ac1a54a49d1636f05e6c8871f73a79b877f6/composer.json#L28

Of course, we could just enable the extension. But I believe, `ext-mbstring` among other extensions is missing here on purpose because we want to test Symfony with minimal extensions enabled.

**How to reproduce**  
https://ci.appveyor.com/project/fabpot/symfony/builds/35947101

**Possible Solution**  
* Enable `ext-mbstring` anyway.
* Find a way to get around the platform check (e.g. same hack as #38707).

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38803
| License       | MIT
| Doc PR        | -

Let's see

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by jderusse** [comment]
Didn't worked on 7.1? https://travis-ci.org/github/symfony/symfony/jobs/738950105

**Comment by stof** [comment]
weird that this happens only for one specific sub-test. Could it be that this one does special things for its composer usage and does not use that config file ?

**Comment by jderusse** [comment]
Other version are compiled with mbstring (see `php -i` output for php 7.4 for instance)

**Comment by jderusse** [comment]
same for 7.2 on branch 5.x https://travis-ci.org/github/symfony/symfony/builds/738951096

**Comment by jderusse** [comment]
fixed by https://github.com/symfony/symfony/commit/255f1e3478caf9b8e8dfb843e448074bce594949

**Pull request merged**
