### PR TITLE
[Messenger/Amqp] Allow setting option "login" in DSN

### LINKED ISSUE #37618: [Messenger] "login" falsely reported as invalid option
**Symfony version(s) affected**: 5.1

**Description**  
Since #34925
> User Deprecated: Since symfony/messenger 5.1: Invalid option(s) "login" passed to the AMQP Messenger transport. Passing invalid options is deprecated.

But login is a valid option that being used by `\AMQPConnection::__construct`, see also https://github.com/symfony/symfony/blob/8a7c776b92c92ef6867fdd6a1682171c17f76de1/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L191

### PR DESCRIPTION
**Pull request by W0rma**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #37618
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Thank you

**Comment by chalasr** [comment]
Should we document it in https://github.com/symfony/symfony/blob/8f12f968f53e978d98333e5198a83b3d6f374e05/src/Symfony/Component/Messenger/Bridge/Amqp/Transport/Connection.php#L122?

**Comment by W0rma** [comment]
> Should we document it in https://github.com/symfony/symfony/blob/8f12f968f53e978d98333e5198a83b3d6f374e05/src/Symfony/Component> 

@chalasr Makes sense - thank you for the hint. Done.

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @W0rma.

**Pull request merged**
