### PR TITLE
[Config] Remap XML before normalization

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes (should add one for regression though)
| Fixed tickets | https://github.com/symfony/symfony/pull/21051#discussion_r93830053
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

You never seem to get the remapped value with things like `beforeNormalization()` etc.

Meaning you never get the normalized form which makes deprecating for instance really hard ;-)

### CODE REVIEW

**Comment by ro0NL** [comment]
Added failing test that proves we get a de-normalized form in normalization closures.

This PR _fixes_ XML remapping, but setting the key attrribute actually still happens in `PrototypedArrayNode::normalizeValue` (ie. post normalization).

I think moving the normalization closures from `normalizeValue` to `preNormalize` could also work.. and is perhaps the easier approach. Then again.. from an extension pov you'd probably expect this value already in `preNormalize`.

**Comment by ro0NL** [comment]
If we agree with behavior change in master i propose to go with;

- normalize
  - preNormalize
    - normlize keys
    - remap XML attributes
    - assign key attribute
  - replace equivalent values
  - run normalization closures (user normalization starts here)
  - normalizeValue (ie. post normalization)
    - normalize childs
    - check extra keys (actually validation?)

Knowing this, we could even consider normalizing childs in pre-normalization. But im not sure :confused:

**Comment by nicolas-grekas** [comment]
Just a confirmation: is this PR for master or for a lower branch?

**Comment by ro0NL** [comment]
Depends on SF's policy on behavioral changes :)

I think we should do the master+changelog approach on this. I already imagine people relying on certain keys.. or not expecting certain ones for that matter (to make things work perhaps).

**Comment by xabbuh** [comment]
How would you write code then that has to support different Symfony versions?

**Comment by ro0NL** [comment]
Maybe adding `afterNormalization` is the better approach.. im not sure where where pre stops, and post begins.

Imo. XML remapping and key normalization are kinda at the same level.. but maybe im wrong? I can understand _before normalization_ actually runs before `treatFalseLike` etc. However practically you need a point where you just know `$v['enabled']` is set/normalized. Hence `afterNormalization` could work.

**Comment by stof** [comment]
this PR is a BC break, and then the name ``beforeNormalization`` does not make sense anymore, as it happens after.

Btw, if you need to know whether whether the feature is enabled or no, it probably means you need to run your logic after the merging of different files too (as it can be enabled in a different file). So use ``->validate()`` instead of ``beforeNormalization``.

**Comment by ro0NL** [comment]
i believe my issue was one where i got a different value depending on the format (YAML gives plural, XML singular) which i didnt really expected

:+1: for `validate`.. that is practically `afterNormalization` already

**Comment by ro0NL** [comment]
Closing for now :) not sure anymmore what to do here. I believe moving things to `validate()` is the right approach.

**Pull request closed without merging**
