### PR TITLE
[Routing] Add `Requirement::POSITIVE_INT` for common ids and pagination

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #45528
| License       | MIT
| Doc PR        | ~

I targeted 6.1 because it's not yet released, should I rebase onto 6.2?

ping @fancyweb :)

### CODE REVIEW

**Review by derrabus — APPROVED** [review]
This PR improves a feature that is added in 6.1. I think merging it to 6.1 is fine.

**Review by chalasr — APPROVED** [review]
Works for me on 6.1

**Review by fancyweb — APPROVED** [review]

**Comment by fabpot** [comment]
That's unfortunately too late, that will be for 6.2.
There are many other such requirements we could add (and this one is not critical for the feature to be useful).

**Review by OskarStark — APPROVED** [review]

**Comment by HeahDude** [comment]
Alright then, rebased and added the proper note in the CHANGELOG.

**Comment by nicolas-grekas** [comment]
Thank you @HeahDude.

**Pull request merged**
