### PR TITLE
Unpack nested array instead of using temp var

### PR DESCRIPTION
**Pull request by dosten**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

Since php 5.5 we can [unpack nested arrays with `list()`](http://php.net/manual/en/control-structures.foreach.php#control-structures.foreach.list) to avoid temp vars.

### CODE REVIEW

**Comment by jakzal** [comment]
Status: Reviewed

**Comment by nicolas-grekas** [comment]
@dosten Did you check if there are other occurrences of this in the code?

**Comment by dosten** [comment]
@nicolas-grekas Done! but the failing tests in PHP7 seems to be not related.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by jakzal** [comment]
:+1:

**Comment by dosten** [comment]
Thanks for run the test suite again :)

**Comment by fabpot** [comment]
Thank you @dosten.

**Pull request closed without merging**
