### PR TITLE
[Validator][Choice] Fix callback option if not array or iterable returned

### LINKED ISSUE #58610: [Validator] Fix choice callback option if not array or iterable returned
### Symfony version(s) affected

5.4.x

### Description

When using the Choice validator `callback` option : If the method provided in the callback does not return an array or iterable, it causes the following PHP error:
```
TypeError: in_array(): Argument #2 ($haystack) must be of type array
```

### How to reproduce

```php
<?php

use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Validation;

class Entity
{
    public function callbackMethod()
    {
        return null;
    }
}

$validator = Validation::createValidator();
$entity = new Entity();
$violations = $validator->validate($entity, [
    new Choice(['callback' => [$entity, 'callbackMethod']]),
]);
// should throw a TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given
```

### Possible Solution

Ideally, the Choice Validator should handle such cases more gracefully ? With an exception ?

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by symfonyaml**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58610
| License       | MIT

### Issue
When using the Choice validator `callback` option, and the callback method provided does not return an array or iterable, it causes a PHP error.
See all details and how to reproduce it in the issue https://github.com/symfony/symfony/issues/58610

### Solution
In this PR
 - Add some checks if the callback method provided returns an array or iterable
 - Add tests for exception and iterable

### CODE REVIEW

**Comment by stof** [comment]
should we mention the name of the callable in the error message, to make it easier to debug ?

**Comment by symfonyaml** [comment]
@stof Thank you for your review. That's a good idea, I will add that the callable in the error message.

**Comment by symfonyaml** [comment]
I applied [this from the doc](https://symfony.com/doc/current/contributing/code/pull_requests.html#rebase-your-pull-request) 
but still wrong rebase ....... I create another PR.

**Comment by symfonyaml** [comment]
@stof  new PR https://github.com/symfony/symfony/pull/58615 , sorry .....

**Comment by stof** [comment]
@symfonyaml looks like you rebase on top of the latest 7.2 branch instead of the latest 5.4 branch (as your PR targets 5.4)

**Pull request closed without merging**
