### PR TITLE
[HttpFoundation] Revert getClientIp @return docblock

### PR DESCRIPTION
**Pull request by ossinkine**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

This PR reverts https://github.com/symfony/symfony/pull/22418, see the comment https://github.com/symfony/symfony/pull/22418#issuecomment-513256687

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I just trying running this and it returned `null`, with no "underfined" notivce:
```php
$r = new Request();

var_dump($r->getClientIp());
```

**Comment by ossinkine** [comment]
I think the docblock contains a type that must be, but not one that can be.
There is a lot of not null fields in Request class which will be null after `new Request()`.

**Comment by ostrolucky** [comment]
No, docblock must specify type it returns

**Comment by ossinkine** [comment]
But now it is not so, we must be consistent. If we want the docblock to contain what the method returns, we need to add `|null` to other fields and check that the field is not null when we call the getter, but we don’t do that, it is a huge number of redundant checks.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ossinkine.

**Pull request merged**
