### PR TITLE
[Mailer] conflict with Mime 4.4

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Will it work?
Already released tags will happilly install Mime 4.4.
This should be on mime 4.4 instead, isn't it?

**Comment by xabbuh** [comment]
This change at least will help people who use something like `4.3.*` for `symfony/mailer` once a stable tag is done for the Mime component 4.4.

In general, we need to be careful not to use the caret or tilde operator when defining requirements for experimental components.

**Comment by nicolas-grekas** [comment]
Sorry, this doesn't work to me: when 4.4 will be released Composer will be allowed to stick to 4.3.3 for mailer and install mime 4.4.0, and this will explode :)

**Comment by stof** [comment]
Well, at least, this will solve it for upcoming releases.

if we want to fix it for every release, we would have to also update mime 4.4 to add a conflict rule with mailer 4.3.
The proper fix would be to change our policy regarding constraint targetting experimental packages: we should not use the caret operator for these constraint, as it is the semver operator and the key thing about experimental packages is that they don't follow semver yet. We already faced similar issues in the past with messenger IIRC.

**Comment by nicolas-grekas** [comment]
conflict rules added to mime 4.4

**Pull request closed without merging**
