### PR TITLE
[Routing] allow URLs to be generated that include the default param

### LINKED ISSUE #5180: [Routing] UrlGenerator doesn't allow generating URL with default param
When you have a route like `/index.{_format}` with _format defaults to html, one cannot generate `/index.html` because params that equal the default value are ignored, so it would instead generate `/index`. But sometimes it's nessecary to have the other URL, e.g. due to caching strategies or semantic reasons (URI identifier vs. resource location).

### PR DESCRIPTION
**Pull request by Tobion**
BC break: yes (even if no test needed to be changed, so the old behavior was probably not even intended as no test for it existed)
Fixes #5180

This can be achieved by explicitly passing the parameter. Previously it just ignored the parameter that equals the default value. You can still omit optional variables by not passing it at all or passing null as param value.

Example:
Given the route `new Route('/index.{_format}', array('_format' => 'html'));`
Previously generating this route with params `array('_format' => 'html')` resulted in `/index` which means one could not generate `/index.html` at all. This has been changed. You can of course still generate just `/index` by passing array('_format' => null) or not passing the param at all.

I'm certain this is the best solution to the problem even if it slightly breaks bc. But IMO this is how it is supposed to work. Because when I pass a parameter explicitly, I want it to be included in the URL.

### CODE REVIEW

**Comment by WouterJ** [comment]
Let's summarize the above discussion and make a decision (and finish this PR):

The Problem
===

Assume a route `/index.{_format}` with `_format` set to `html` as default value. Now, when rendering a template:

Code | Result
--- | ---
`path(..., { format: 'html' })` | `/index`
`path(..., { format: 'json' })` | `/index.json`

There should be a way to get `/index.html`, there isn't one at the moment.

The Solutions
===

 1. *(current implementation)* Generate `/index.html` when `{ format: 'html' }` is passed and only generate `/index` when `{ format: null }` is passed

     * If you use `{ format: format }` (which is common), the only way to get `/index` would be: `{ format: format === 'html' ? null : format }`
     * The application might end up linking to both `/index` and `/index.html`, meaning 2 URLs serving the same content
 1. *([refs](https://github.com/symfony/symfony/pull/5410#issuecomment-15056743))* Add a special parameter `_with_defaults` to determine if default values should be included in the path

     * Parameters don't seem to be the correct way
     * Inconsistent with relative/absolute URLs for instance
     * BC break, as you can no longer use `_with_defaults` as route placeholder

 1. *([refs](https://github.com/symfony/symfony/pull/5410#issuecomment-21038878))* Have a special character in the parameter name to determine if it should be included or not (like `/index.{!_locale}` or `/index.{_locale!}`).

**Comment by fabpot** [comment]
I tend to prefer option 3 as it's the only proposal that makes the choice in the definition of the route where it belongs; that also avoids any possibility to generate both forms (and I really dislike option 2)

**Comment by javiereguiluz** [comment]
We could change the `!` character by `?` to make it consistent with other parts of Symfony (optional Assetic filters, optional services dependencies, etc.):  `/index.{?_format}`

**Comment by WouterJ** [comment]
Btw, I agree with @fabpot :)

@javiereguiluz the character indentifies that the parameter is *not* optional (parameters with a default value are optional by default). So I think `!` seems like a nice choice, however it can be mixed up with `not` as noticed by @lyrixx.

**Comment by Tobion** [comment]
The use-case for me was exactly to be able to generate BOTH forms of URIs as detailed in the original ticket. So option 3 would not solve that problem at all. And option 3 would not be useful at all since I can simply remove the default value if I want to generate a URI with the param (you don't want to have matching without the param but generating with it).

**Comment by fabpot** [comment]
I don't understand why one would want to generate different URLs for the same resource, it looks like a bad use case.

**Comment by Tobion** [comment]
For example you want to match `/index` but then redirect to `/index.html`. For redirecting you need to generate this route with the format (otherwise you will end up in an endless loop).

This is common practice for example in the semantic web where `/index` is the real-world resource and `/index.html` would then be the page about this resource where a semantic client gets redirected via HTTP See Other.

There are currently workarounds like using two routes or changing the default value of the format to something that does not correspond to an existing format.

**Comment by javiereguiluz** [comment]
> For example you want to match /index but then redirect to /index.html

I'm just asking: if you want to redirect ALL URLs to their `.html` counterparts, shouldn't you do that at proxy or web server level?

**Comment by SofHad** [comment]
:+1:

**Comment by Tobion** [comment]
Closing as there is no consensus.

**Pull request closed without merging**
