### PR TITLE
[HttpClient]  debug test failures

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
do we have failures? which ones?

**Comment by xabbuh** [comment]
It doesn’t seem to happen always, but I was looking into https://github.com/symfony/symfony/actions/runs/8600287905/job/23564944376#step:7:8934.

**Comment by nicolas-grekas** [comment]
Ah OK. You can ignore this one: it happens when checking out 4.4 and loading it with more recent deps. A fix would involve patching the tests on 4.4.

**Comment by xabbuh** [comment]
That explains why I was not able to reproduce it. 😄

**Pull request closed without merging**
