### PR TITLE
[HttpFoundation] Request->getRequestFormat should only rely on the request attributes

### PR DESCRIPTION
**Pull request by pvandommelen**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | possibly |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #8966 |
| License | MIT |
| Doc PR |  |

Added test case and fix for #8966. Is this functionality relied on somewhere?

### CODE REVIEW

**Comment by fabpot** [comment]
I'm going to merge this one on master for Symfony 3.0.

**Comment by fabpot** [comment]
ping @symfony/deciders

**Comment by weaverryan** [comment]
@fabpot so this would just need to be a documented BC break for 3.0? Or will we do more work to try to trigger deprecation warnings?

Anyways, I agree with the change. The trick is not breaking existing apps and giving an upgrade path - and that part doesn't seem to be here yet.

**Comment by fabpot** [comment]
I think documenting that this should be avoided in pre-2.8 is enough. People using the feature the wrong can easily fix their code as this is probably almost always a mis-configuration. Triggering a deprecation notice is also possible but then any end user will be able to trigger it which is probably not a good idea.

**Comment by Tobion** [comment]
:+1: 

The preview error route also has a `_format` placeholder, so it is still possible to test errors in different formats: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/Resources/config/routing/errors.xml#L7

**Comment by fabpot** [comment]
Thank you @pvandommelen.

**Pull request closed without merging**
