### PR TITLE
[ExpressionLanguage] lint should return bool

### PR DESCRIPTION
**Pull request by decima**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | i don't really know
| New feature?  | yes and no 
| Deprecations? | yes?
| License       | MIT

I don't know how to qualify this : [Documentation](https://symfony.com/doc/current/components/expression_language.html#parsing-and-linting-expressions) says lint should return boolean, but when you check the code, it's a void value, so should I update doc first, and then add it to a new branch as a new feature? 

Depending on the point of view, if the documentation is the source of truth, this means it's a bug fix. But if the code is the source of truth, then, this is a new Features which introduces breaking changes :thinking: 

And It seems like some non-related tests in this component don't work?

### CODE REVIEW

**Comment by xabbuh** [comment]
This indeed looks like a mistake in the documentation. The method is supposed to throw  an exception in case of a syntax error. Would you like to send a PR to fix the documentation?

**Comment by decima** [comment]
> This indeed looks like a mistake in the documentation. The method is supposed to throw an exception in case of a syntax error. Would you like to send a PR to fix the documentation?

Idk, I think it's weird that a method which validates an expression does't return anything. By logic, I would make it return a bool.

I bypassed my issue by doing
```
try {
    return $this->expressionLanguage->evaluate($condition, $args);
} catch (Exception) {
    return false;
}
```

I made my change on the docs repo [#20351](https://github.com/symfony/symfony-docs/pull/20351)

**Comment by MrYamous** [comment]
Taking a look on it after seeing the PR doc, considering author comment from original [code PR](https://github.com/symfony/symfony/pull/35849/files#r404024581) the void return is on purpose then this is pretty like a doc mistake

**Comment by derrabus** [comment]
I'm going to close this PR. The proposed change break backwards compatibility, so merging it is out of the question. I think, we agree that this is an issue of the documentation, so let's continue the discussion on symfony/symfony-docs#20351.

**Pull request closed without merging**
