### PR TITLE
[Form] Remove deprecated setDefaultOptions and OptionsResolverInterface

### PR DESCRIPTION
**Pull request by peterrehm**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | symfony/symfony-docs#4786 |
| Related | #12891 |

### CODE REVIEW

**Comment by peterrehm** [comment]
Rebased, good for review.

**Comment by peterrehm** [comment]
Also removed the OptionsResolverInterface and it's usages.

**Comment by peterrehm** [comment]
@stof Can you have a look at those changes? Tests are failing, but looks unrelated...

**Comment by peterrehm** [comment]
Anyone up for a review?

**Comment by Tobion** [comment]
Looks ok :+1:

**Comment by fabpot** [comment]
Thank you @peterrehm.

**Pull request merged**
