### PR TITLE
[Process] fix locking of pipe files on Windows

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28655
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@SailorMax patch updated, can you try the new one please?

**Comment by nicolas-grekas** [comment]
Thanks, can you try again please? It should be good now (at least appveyor is green.)

**Comment by SailorMax** [comment]
Yes, latest patch work as expected in my case.
Thank you!

**Comment by SailorMax** [comment]
But after work temp files remain in the temp-directory. Is it feature? :)

**Comment by SailorMax** [comment]
For me - not a problem :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
