### PR TITLE
[From] minor fix tests added by #17798 for bootstrap theme

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Branch | 2.7+ |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by HeahDude** [comment]
Tests are globally failing because of a conflict with tests added in #17798 and patch from #17600

**Comment by HeahDude** [comment]
ping __@symfony/mergers__

**Comment by javiereguiluz** [comment]
:+1:

But some test still fail, probably because of what @xabbuh explained here: https://github.com/symfony/symfony/pull/17568#issuecomment-190585004

**Comment by HeahDude** [comment]
Yes, I still don't understand the reason, but it makes TwigBridge difficult to debug.

**Comment by xabbuh** [comment]
The `deps=low` test should not fail.

Status: Needs work

**Comment by HeahDude** [comment]
Ok I keep investigating then.

**Comment by HeahDude** [comment]
@xabbuh, It's not the first PR where I notice this, travis builds for php 5.6 and php 7 run the tests without taking into account the PR commits.

I don't see what I can do...

???

**Pull request merged**
