### PR TITLE
[WIP] Use ::class keyword when possible

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | n/a  
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by xabbuh** [comment]
I was thinking about this as well. Can we update fabbot to enforce the usage of the class constant?

**Comment by fabpot** [comment]
@xabbuh That's probably the job of PHP CS Fixer, and it's not trivial, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2918 for reference

**Comment by derrabus** [comment]
Merging this up is going to be a huge one-time PITA, but I think we'll have a nicer codebase afterwards.

**Comment by fabpot** [comment]
I will merge this one up. My strategy with such a PR is always the following: merge everything up, then merge the PR, merge up again and ignore all conflicts. Start again the work on branch n + 1, rinse and repeat.

**Pull request merged**
