### PR TITLE
[VarDumper] Fixed search bar

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Continuation of #28854, replaces #29176

initial:

image

ctrl f:

image

scroll:

image

tested in chrome+ff

cc @ogizanagi 

ref https://caniuse.com/#feat=css-sticky

### CODE REVIEW

**Comment by ro0NL** [comment]
made sure the first result wont be hidden under the search bar:

image


i think this nails it :)

**Review by ogizanagi — APPROVED** [review]
Thanks for working on this ❤️

**Comment by fabpot** [comment]
Shouldn't we merge this one on an older branch?

**Comment by Koc** [comment]
Is it possible to disable this search bar in all?

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @ro0NL.

**Pull request merged**
