### PR TITLE
[SecurityBundle] Made collection of user provider unique when injecting them to the RemberMeService

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 2.7 
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by lyrixx** [comment]
Fabbot is wrong.
Tests are green ;)

**Comment by lyrixx** [comment]
> When can the collection be non-unique?

If you have many authentication provider in a firewall that use the same user provider

> Can we add a test covering this?

yes, I guess ;)

**Comment by lyrixx** [comment]
I wanted to add tests, but for now, there are no tests on this class. IMHO, we can merge this one as this.

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
