### PR TITLE
[Security] PreAuthenticatedAuthenticationProvider::authenticate(): don't load user via userProvider if the user was already supplied in the token

### LINKED ISSUE #43374: [Security] Potential error in PreauthenticatedAuthenticationProvider::authenticate()
**Symfony version(s) affected**: 4.4

**Description**
PreauthenticatedAuthenticationProvider::authenticate() causes an error when passed a token with a user object (as opposed to a username string).

The error happens here:
 https://github.com/symfony/symfony/blob/a4498006357b8ed9cac9d35ec038e303d95ec2d7/src/Symfony/Component/Security/Core/Authentication/Provider/PreAuthenticatedAuthenticationProvider.php#L57

It happens because there is no check performed to see if `$user` is an object already, and user providers expect a string argument to `loadUserByUsername()` (`UserProviderInterface` is annotated with `@param string`).

**How to reproduce**
Pass a token with an already resolved user object to `PreauthenticatedAuthenticationProvider::authenticate()`.

**Possible Solution**
I would put line 57 in an `if` condition which tests whether or not `!$user instanceof UserInterface` or `\is_string($user)`.

### PR DESCRIPTION
**Pull request by rimas-kudelis**
Fixes #43374

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #43374
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
Could anyone review this please?

**Comment by xabbuh** [comment]
Can you please add a test case that would fail without this patch?

**Comment by wouterj** [comment]
A token at this stage should never have a `UserInterface` object - just a string. How did you end up with this situation?

**Comment by rimas-kudelis** [comment]
> A token at this stage should never have a `UserInterface` object - just a string. How did you end up with this situation?

It could be that I'm doing something not quite expected, but a similar check already exists in other providers.

Example: [`DaoAuthenticationProvider`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php) extends [`UserAuthenticationProvider`](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php), whose `authenticate()` method [calls](https://github.com/symfony/symfony/blob/186e83a25f637689c4d2d266fcacd9258ec28eb1/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php#L66) its child's `retrieveUser()` method, which in `DaoAuthenticationProvider` [already spots the logic which I'm adding here](https://github.com/symfony/symfony/blob/186e83a25f637689c4d2d266fcacd9258ec28eb1/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php#L79).

**Comment by chalasr** [comment]
We will need more details on your usage to justify this change. 
Having a user object in the storage should not happen at this stage, really.

**Comment by rimas-kudelis** [comment]
I think I found what exactly causes my issue: our application has [security.always_authenticate_before_granting](https://symfony.com/doc/current/reference/configuration/security.html#always-authenticate-before-granting) set to `true`, which means that each call to `Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface::isGranted()` triggers a reauthentication, and `PreAuthenticatedAuthenticationProvider`, which is triggered for `PreAuthenticatedToken`, fails in such case.



Long story below:

> We will need more details on your usage to justify this change. Having a user object in the storage should not happen at this stage, really.

Actually, I tried not having the user object there, but it would also fail.
What we have is the following scenario: a listener implementing deprecated `Symfony\Component\Security\Http\Firewall\ListenerInterface`, which authenticates a user by a JSON request (either via username and password or a social login JWT token).

Upon successful authentication, it:
1. creates a token (either a `UsernamePasswordToken`, or a `PreAuthenticatedToken`), with the username as plain text,
2. calls `Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface::authenticate()` with that token, which returns an authenticated token of the same type, but with the user object attached instead of the username.
3. calls `Symfony\Component\Security\Http\Session\SessionAuthenticationStrategyInterface::onAuthentication()` with the request and the authenticated token as arguments.
4. calls `Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface::setToken()` with the new token as argument.
5. dispatches an `Symfony\Component\Security\Http\Event\InteractiveLoginEvent`initialized with the request and the authenticated token as arguments. And this is where the problem manifests: in case of `UsernamePasswordToken`, all works fine, all event listeners are executed, and the request gets procesesd successfully. However, in case of `PreAuthenticatedToken`, an exception is thrown when executing one of the event listeners, because `Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface::isGranted()` is called and it triggers reauthentication as explained above.

**Comment by rimas-kudelis** [comment]
@chalasr does my previous comment make the change easier to evaluate?

**Comment by rimas-kudelis** [comment]
@chalasr @xabbuh @wouterj  ping?

**Comment by wouterj** [comment]
It should only reauthenticate if the current token is not yet authenticated: https://github.com/symfony/symfony/blob/2381e0d301ccec6323d78572b13198bd1f9937fc/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php#L52-L54

This means you `PreAuthenticatedToken` is not "pre-authenticated", which indicates that you don't instantiate it with any roles: thttps://github.com/symfony/symfony/blob/2381e0d301ccec6323d78572b13198bd1f9937fc/src/Symfony/Component/Security/Core/Authorization/AuthorizationChecker.php#L52-L54 Fixing that should fix this error.

Given 4.4 is currently very deep in the LTS maintenance time, and this behavior (always authenticate) is deprecated in the current up to date Symfony versions (5.3+), I'm going to close this bug fix. I hope you understand :) If you have any questions, please feel free to comment here.

**Pull request closed without merging**
