### PR TITLE
move abstract test classes to Test namespace

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
That doesn't make sense. We added . gitattributes because ppl did not way to get the tests in the zip, yet we're still adding them back? 

That's going to cause a lot of troubles in the long run, because we won't be able to know ahead of time when a test should be added to Tests or Test. Process wise, we have no CI to back that up.

I'm seriously in favor of reverting the PR that added those files. We could replace them by some logic in flex instead.

**Comment by Nyholm** [comment]
Thank you for the PR. 

@xabbuh could you elaborate *why* this is needed?

**Comment by fabpot** [comment]
Maybe adding the `.gitattributes` in 3.4 was not the right move. We could do it only in 4.4 instead?

**Comment by xabbuh** [comment]
@Nyholm In some bundles/bridges we rely on classes from the `Tests` namespace of different components. Now, with the changes done in #33579 these classes are not there anymore in our `deps=low`/`deps=high` build jobs.

@fabpot Not sure that really helps here. We would have the exact same problem there again I guess.

Another solution could be to install from source instead (see #33637).

**Pull request closed without merging**
