### PR TITLE
[FrameworkBundle] remove getProjectDir method from MicroKernelTrait

### LINKED ISSUE #36719: New getProjectDir in MicroKernelTrait is too opinionated
**Symfony version(s) affected**: 5.1.0

With changes introduced in commit a68980738798233d257fa46875f32827f4537254, is always supposed that Kernel is simply in `src` directory.
This breaks applications where Kernel is put elsewhere (that, by the way, would work fine with the base definition of `getProjectDir` in the base kernel class).

I suggest to revert such change and to remove `getProjectDir` from MicroKernelTrait

### PR DESCRIPTION
**Pull request by garak**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36719
| License       | MIT
| Doc PR        | not needed

Remove method added in trait, to be able to use same method in base kernel class.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Please fix the changelog also.

**Comment by garak** [comment]
> Please fix the changelog also.

I thought changelogs were autogenerated...

**Comment by nicolas-grekas** [comment]
Only the main changelog is. We maintain them per components.
Check the commit you linked in the issue:
https://github.com/symfony/symfony/commit/a68980738798233d257fa46875f32827f4537254

**Comment by garak** [comment]
> Only the main changelog is. We maintain them per components.

Ah, I see.
Changelog updated!

**Review by nicolas-grekas — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @garak.

**Pull request merged**
