### PR TITLE
[Mailer][Notifier] added missing gitattributes and gitignore

### PR DESCRIPTION
**Pull request by iamvar**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

just added missing .gitattributes and .gitignore to be consistent with other components

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Cool, thank you. 

It looks like the first bridge was missing these and then people just copied that bridge as a template =)

**Comment by StaffNowa** [comment]
My bridges PR the same will have this issue

**Review by derrabus — APPROVED** [review]
Can you please check if we need to fix any of those bridges on the 4.4/5.2 branches already?

**Comment by iamvar** [comment]
> Can you please check if we need to fix any of those bridges on the 4.4/5.2 branches already?

in 4.4 there is no Mailer/Bridge/Mailjet and Notification component, so nothing in there

in 5.2 it is applicable for all existing there bridges
src/Symfony/Component/Mailer/Bridge/Mailjet/.gitattributes
src/Symfony/Component/Mailer/Bridge/Mailjet/.gitignore
src/Symfony/Component/Notifier/Bridge/Discord/.gitignore
src/Symfony/Component/Notifier/Bridge/Esendex/.gitattributes
src/Symfony/Component/Notifier/Bridge/Esendex/.gitignore
src/Symfony/Component/Notifier/Bridge/Firebase/.gitignore
src/Symfony/Component/Notifier/Bridge/FreeMobile/.gitignore
src/Symfony/Component/Notifier/Bridge/GoogleChat/.gitignore
src/Symfony/Component/Notifier/Bridge/Infobip/.gitignore
src/Symfony/Component/Notifier/Bridge/LinkedIn/.gitattributes
src/Symfony/Component/Notifier/Bridge/LinkedIn/.gitignore
src/Symfony/Component/Notifier/Bridge/Mattermost/.gitignore
src/Symfony/Component/Notifier/Bridge/Mobyt/.gitignore
src/Symfony/Component/Notifier/Bridge/Nexmo/.gitignore
src/Symfony/Component/Notifier/Bridge/OvhCloud/.gitignore
src/Symfony/Component/Notifier/Bridge/RocketChat/.gitignore
src/Symfony/Component/Notifier/Bridge/Sendinblue/.gitignore
src/Symfony/Component/Notifier/Bridge/Sinch/.gitignore
src/Symfony/Component/Notifier/Bridge/Slack/.gitignore
src/Symfony/Component/Notifier/Bridge/Smsapi/.gitignore
src/Symfony/Component/Notifier/Bridge/Telegram/.gitignore
src/Symfony/Component/Notifier/Bridge/Twilio/.gitignore
src/Symfony/Component/Notifier/Bridge/Zulip/.gitignore

Should I create merge request for 5.2?

**Comment by derrabus** [comment]
> Should I create merge request for 5.2?

Yes, please!

**Comment by iamvar** [comment]
> > Should I create merge request for 5.2?
> 
> Yes, please!

https://github.com/symfony/symfony/pull/40703

**Review by OskarStark — APPROVED** [review]

**Comment by Nyholm** [comment]
I've merged some of these in 5.2. Let's wait (a day or two) until someone core team member merge 5.2 into 5.x. After that we should rebase this PR.

**Comment by derrabus** [comment]
> merge 5.2 into 5.x.

✅

**Comment by OskarStark** [comment]
I merged this PR in https://github.com/symfony/symfony/commit/712100924d9dc875b536b8c25f88b6a2d9d40169

Thank you 👍

**Pull request merged**
