### PR TITLE
Streamlined Exception type between ArrayInput and ArgvInput

### PR DESCRIPTION
**Pull request by peterrehm**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18617 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by OskarStark** [comment]
Can we really merge this in `2.8` ?
This looks like a BC break to me, because `InvalidOptionException` **does not** extend `RuntimeException`

**Comment by fabpot** [comment]
It's definitely a BC break that cannot be merged.

**Comment by peterrehm** [comment]
@fabpot So discarding this PR?

**Comment by OskarStark** [comment]
> @fabpot So discarding this PR?

i would say if you can handle BC then 2.8 could be the target branch, otherwise it needs to be resubmitted against master.

Do you have a real use case where this would help, i don't get the benefit of this PR right now, which is important to introduce a BC break IMO

**Comment by peterrehm** [comment]
@OskarStark See the linked Ticket. It is just inconsistent.

**Comment by OskarStark** [comment]
Thanks for pointing this out, to be honest I have no idea how to handle it

**Comment by peterrehm** [comment]
I only see 2 options

1) Introduce the BC break and target 4.0

2) InvalidOptionException could extend RuntimeException

**Comment by OskarStark** [comment]
> 2) InvalidOptionException could extend RuntimeException

oh i thought this wasn't possible, but if it is, then it is easy to stay BC!

**Comment by peterrehm** [comment]
Okay, in fact this is not possible as InvalidOptionException extends `\InvalidArgumentException`

**Comment by OskarStark** [comment]
> Okay, in fact this is not possible as InvalidOptionException extends \InvalidArgumentException 

That was the result of my research, too

**Comment by stof** [comment]
> 1) Introduce the BC break and target 4.0

And this means that the PR cannot be merged, because development of 4.0 has not started yet (the master branch is 3.2, not 4.0, and we won't start the 4.0 now as maintaining 2 development branches for 2 years would be a nightmare)

**Comment by peterrehm** [comment]
@stof Or do you see any other possibility?

**Comment by nicolas-grekas** [comment]
there are no possibilities to fix this, we have to live with that

**Comment by peterrehm** [comment]
@nicolas-grekas Can you close the related issue then as well?

**Pull request closed without merging**
