### PR TITLE
[WebProfilerBUndle] Improve toolbars ajax requests status visibility

### PR DESCRIPTION
**Pull request by javihgil**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

This PR improves the ajax requests status visibility in Profiler's toolsbar. Shows which requests are still loading, and which ones are succeded or error.

### CODE REVIEW

**Comment by theofidry** [comment]
@javihgil any chance you could append a screenshot?

**Comment by fabpot** [comment]
Indeed, a screenshot would help understand the changes.

**Comment by xabbuh** [comment]
@javihgil Any news here? :)

**Comment by fabpot** [comment]
Anyone willing to apply these changes and paste screenshots here? That would be helpful. Without screenshots, we would close this PR.

By the way, that would be a new feature, so should be merged in master.

**Comment by javihgil** [comment]
I'm sorry, I don't know why, but I did not receive notifications about this conversation...

Here they are some captures and aditional explanations:

When you have an error in any number of request you get this:

ajax0

and if you hover on the button:

ajax1

With this update you would see as shown:

ajax2

In the capture it's not perceived, but the top "GET" element is blinking, the same style as the one shown in toolbar main button when an ajax request is in progress.

Recently I've realized that something similar feature was added in 3.x versions: there is a new table column with http status code and it's colorized depending on response error status. So, I leave you the decision of merging this PR, if you think this can be useful, I think so.

Thanks.

**Comment by fabpot** [comment]
Indeed, we have done similar changes recently. I will let @javiereguiluz see if we can close this PR or if we want to adapt what we did on this very same topic.

**Comment by fabpot** [comment]
I'm closing it as we added the status in master. Thanks.

**Pull request closed without merging**
