### PR TITLE
[Form] fix lowest deps tests

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
I am not really sure what causes the difference here though. /cc @ro0NL

**Comment by ro0NL** [comment]
the `%s/%` trick is for linux vs windows (the file path exceeded the table length on windows).

i missed the failing test from the original PR: https://travis-ci.org/symfony/symfony/jobs/510860372#L5020 ..., not sure what happened.

It passed before, maybe related after the last change: https://github.com/symfony/symfony/pull/30666/files#diff-4d7446f0cdc9d06df82e038e443e1dbcL184 (removing VarDumper fallback in the component and bumping the deps)

**Review by ro0NL — APPROVED** [review]
reproduced. But im still investigating why the table is longer on deps=high. Both high/low use the same version of console+var-dumper now

:thinking:

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by ro0NL** [comment]
i think it's related to

```
`file: "./Tests/Console/Descriptor/AbstractDescriptorTest.php"` 
// vs.
`file: "./src/Symfony/Component/Form/Tests/Console/Descriptor/AbstractDescriptorTest.php"
```

depending on where phpunit is invoked. locally i ran from the repository root, so the table was longer due this filename.

Maybe travis was failing all along :) dunno.

**Pull request merged**
