### PR TITLE
[Security] Expose Previous Exceptions in ChainUserProvider

### PR DESCRIPTION
**Pull request by patrick-mcdougle**
| Q | A |
| --- | --- |
| Branch? | not sure |
| Bug fix? | maybe? |
| New feature? | maybe? |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #20181 |
| License | MIT |
| Doc PR | N/A |

To the maintainer, I don't know if this is a feature of a bugfix, so I don't know what branch it should be merged into. I had to break our style guide rule of calling exceptions $e because there are two possibilities.

### CODE REVIEW

**Comment by xabbuh** [comment]
I am not sure if we really need to make a change in that direction. But if we want to do that, we should not only pass the last exception, but all the exceptions that have been thrown by the chained providers.

**Comment by ro0NL** [comment]
Why _exactly_ do we need the stack of all previous exceptions.. i can only imagine `getProviders` (the failed providers) being useful.

**Comment by patrick-mcdougle** [comment]
@xabbuh Not sure how to do that. I don't really want to create another exception type (because then you have to deal with how to log it appropriately). I wanted to overload the previous exception, but you can only set that in the constructor, or by using reflection.

**Comment by fabpot** [comment]
Having the last exception as a parent sounds weird to me. Logging calls to `loadUserByUsername ()` that failed is perhaps a better idea. But then, it should probably be the responsibility of the user providers.

**Pull request closed without merging**
