### PR TITLE
[WebProfilerBundle] Add HTTP return code in the Ajax request list table

### PR DESCRIPTION
**Pull request by kucharovic**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17518 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@kucharovic I just tested your pull request and it works perfect! Thanks for working on this.

ajax_status_before

However, to make errors stand out more prominently, what do you think of using the `sf-toolbar-status` CSS classes that we use elsewhere in the toolbar. This way we could show the HTTP status like this:

ajax_status_after

If you like the idea, the code would be something like this:

```js
var statusCodeCell = document.createElement('td');
var statusCode = document.createElement('span');
if (request.statusCode > 299) {
    statusCode.setAttribute('class', 'sf-toolbar-status sf-toolbar-status-red');
} else {
    statusCode.setAttribute('class', 'sf-toolbar-status');
}
statusCode.textContent = request.statusCode || '-';
statusCodeCell.appendChild(statusCode);
row.appendChild(statusCodeCell);
```

**Comment by kucharovic** [comment]
@javiereguiluz it looks better. Are you sure, that [redirects](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection) should be red?

**Comment by javiereguiluz** [comment]
@kucharovic I trusted [this comment](https://github.com/symfony/symfony/issues/17518#issuecomment-174899043) from @Jean85 who said that in Ajax there are no redirections. We probably need more comments about this or some verification.

**Comment by stloyd** [comment]
IMO it should be:
```js
if (request.statusCode < 300) {
    statusCode.setAttribute('class', 'sf-toolbar-status sf-toolbar-status-green');
} elseif (request.statusCode < 400) {
    statusCode.setAttribute('class', 'sf-toolbar-status sf-toolbar-status-yellow');
} else {
    statusCode.setAttribute('class', 'sf-toolbar-status sf-toolbar-status-red');
}

**Comment by javiereguiluz** [comment]
@kucharovic anyway, to be completely safe, we could change `if (request.statusCode > 299)` by `if (request.statusCode > 399)` and this will always work no matter what.

**Comment by kucharovic** [comment]
@javiereguiluz [he's right](https://www.w3.org/TR/XMLHttpRequest/#the-send()-method). A XMLHttpRequest should either get the resource or be told why not.

**Comment by stloyd** [comment]
Hmmm, then maybe:
```js
if (request.statusCode < 400) {
    statusCode.setAttribute('class', 'sf-toolbar-status sf-toolbar-status-green');
} else if (request.statusCode < 500) {
    statusCode.setAttribute('class', 'sf-toolbar-status sf-toolbar-status-yellow');
} else {
    statusCode.setAttribute('class', 'sf-toolbar-status sf-toolbar-status-red');
}

**Comment by javiereguiluz** [comment]
@stloyd I like your proposal ... except for the last comment. Showing 4xx errors in yellow is inconsistent with the current toolbar. 4xx and 5xx are treated as errors and showed in red.

**Comment by Jean85** [comment]
Yeah, I posted that comment because I stumbled on it.. I had an issue in my code, since I was trying to catch redirects with `jQuery.ajax()` and I was getting always 200, didn't understand why :D

I agree with @javiereguiluz , consistency with the rest of the toolbar is better.

**Comment by fabpot** [comment]
:+1:

**Comment by stof** [comment]
should we really put the 2xx in green or keep it in gray instead ? I think putting colors only on errors make them stand out more than if everything is colored

**Comment by javiereguiluz** [comment]
For comparison:

### Color on Errors

ajax_status_after

### Color on Everything

ajax_status_after_colors

**Comment by fabpot** [comment]
+1 for gray instead of green

**Comment by maidmaid** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @kucharovic.

**Pull request closed without merging**
