### PR TITLE
[FrameworkBundle] Revert " Deprecate making `cache.app` adapter taggable"

### PR DESCRIPTION
**Pull request by keulinho**
This reverts commit eed5b284618ec95eedbc376fb140b8fc24619372.

| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Issues        | Fix https://github.com/symfony/symfony/issues/58790
| License       | MIT

As discussed in former PR the deprecation was wrong, and trying to solve the deprecation will lead in errors.
Refer to https://github.com/symfony/symfony/pull/58830 for detailed analysis. 

[according to the creator](https://github.com/symfony/symfony/pull/58830#issuecomment-2470332473) of the original issue the behaviour that is making problems is actually covered by tests, so I'm not sure how to proceed, but the deprecation is clearly wrong and should not make it to 7.2!

### CODE REVIEW

**Comment by alexandre-daubois** [comment]
Sorry I'm only catching up the conversation right now. About what you said in the other PR:

> Ok i'm really questioning what was the original goal here

It's quite well explained [in the original issue](https://github.com/symfony/symfony/issues/54339): the idea is that if `cache.app.taggable` already exists, it will simplify things for the developer to inform of the existence of the taggable cache so that the dev can use it directly, rather than redefining it by hand when the framework offers it. But also, as you mentioned, there's something wrong anyway with the "double taggable cache".

However, I may have underestimated the impact, and judging by the number of thumbs up from the PR, there was a very real use case that was broken by the deprecation! I guess the deprecation could indeed be reverted, and a new issue explaining the original problem you pointed may be opened.

**Comment by keulinho** [comment]
Hey thanks for chiming in 👍 

the "problem" is that was deprecated where cases like these:
```yaml
       cache.object:
         default_lifetime: 172800
         adapter: cache.app
         tags: cache.tags
```

But those cases won't make the cache.app adapter/pool taggable, but create a new pool that will be taggable and use cache.app under the hood.

Also it is not supported to use cache.app.taggable in that case as an adapter as https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Cache/DependencyInjection/CachePoolPass.php#L114 expects that the adapter accepts namespace and default lifetime as constructor arguments and that is not the case for the `cache.app.taggable` service, leading to errors

**Comment by keulinho** [comment]
Unit test fails seem unrelated to change, any idea what I need to do to fix?

**Comment by alexandre-daubois** [comment]
> Unit test fails seem unrelated to change, any idea what I need to do to fix?

You can ignore them here, these are transient tests that fail from time to time 👍

**Comment by nicolas-grekas** [comment]
Good catch, this didn't deprecate what was intended to be. Can you figure out how we could deprecate the behavior we wanted to deprecate?

**Comment by nicolas-grekas** [comment]
Thank you @keulinho.

**Comment by nicolas-grekas** [comment]
I reopened #54339 to keep track of this. Help wanted.

**Comment by alexandre-daubois** [comment]
@javiereguiluz the entry may be removed from the blogpost: [Deprecate Making cache.app Taggable](https://symfony.com/blog/new-in-symfony-7-2-deprecations#deprecate-making-cache-app-taggable) 🙂

**Comment by javiereguiluz** [comment]
@alexandre-daubois I just updated the blog post to remove that. Thanks!

**Pull request merged**
