### PR TITLE
[DI] fix lazy factory code generation

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #36547
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by stof** [comment]
@nicolas-grekas can we have tests covering the dumping of lazy services to avoid such issues in the future ?

**Comment by stof** [comment]
@nicolas-grekas or having such tests in the proxy-manager bridge

**Comment by nicolas-grekas** [comment]
Not sure how to test this specific behavior from the bridge... The bridge is not part if it actually, it works the same with the different modes (5.0, as_file=0/1, etc) A true regression test would require testing the integration from the DI component.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
