### PR TITLE
[VarDumper] Fix dump comparison on large arrays

### PR DESCRIPTION
**Pull request by romainneutron**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |

### CODE REVIEW

**Comment by fabpot** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @romainneutron.

**Comment by ogizanagi** [comment]
Shouldn't this be fixed in the [`VarDumperTestCase `](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/VarDumper/Test/VarDumperTestCase.php#L36) class, too ?

**Comment by nicolas-grekas** [comment]
@ogizanagi it could, although the TestCase should be deprecated in master in favor of the trait.
PR welcomed btw

**Comment by xabbuh** [comment]
The `VarDumperTestCase` class was already removed in 3.0. ;)

**Pull request merged**
