### PR TITLE
[Routing] make generated UrlMatcher code use the local $context function variable instead of the instance reference.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | maybe |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

I don't really know if this change is a BC break as it concerns generated code... But people using the component itself (ie: Drupal, Silex, etc.) might be concerned by this change.

### CODE REVIEW

**Comment by hhamon** [comment]
It's legit that fabbot.io screams for this PR.

**Comment by Tobion** [comment]
What is the advantage of changing this?

**Comment by Tobion** [comment]
The local variable is only created for the expression language matching and should not be used for anythign else.

**Comment by nicolas-grekas** [comment]
There is a minor perf gain in doing so. Any downside?

**Comment by Tobion** [comment]
Where does the performance gain come from?

**Comment by nicolas-grekas** [comment]
It's a bit faster to access local vars than props.

**Comment by Tobion** [comment]
What would make more sense to me is to only create the local variables when expressions are used at all.

**Comment by fabpot** [comment]
Closing as this makes merging 2.3 into 2.7 potentially more complex for no real benefit in terms of performance.

**Pull request closed without merging**
