### PR TITLE
[Workflow] Added parameter type hinting where possible.

### PR DESCRIPTION
**Pull request by fre5h**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Related to #32223
| License       | MIT
| Doc PR        | no

According to #32223 were added type hintings in most classes, but not in all possible. I tried to add more type hintings. Most of my changes look reasonable, but I am not sure in every.

If you find, that in some class/method type hintings are not welcome, then notice it and I will remove it.
If you find, that all my changes are senseless, then just close this pull request :)

### CODE REVIEW

**Review by ro0NL — COMMENTED** [review]
i thought we did do return types automatically ... https://github.com/symfony/symfony/pull/33236 or why did we miss those initially?

**Comment by lyrixx** [comment]
> why did we miss those initially?

I don't think so.

Thanks @fre5h  for your PR but Most of your change break the BC promise

**Comment by lyrixx** [comment]
About the `:void` on private method (the only changes that does not break BC), it does not bring anything useful.

I'm sorry, But I'm gonna close your PR because It cannot be merged.

**Comment by ro0NL** [comment]
@lyrixx so we missed those because they break BC :) i see.

**Pull request closed without merging**
