### PR TITLE
[DX] Minor improvement for the translation:debug output

### PR DESCRIPTION
**Pull request by nicolasdewez**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13874 |

### CODE REVIEW

**Comment by aitboudad** [comment]
:+1: but the target branch should be `2.8`

\cc @javiereguiluz

**Comment by javiereguiluz** [comment]
:+1: I like it. Thanks @nicolasdewez

**Comment by nicolasdewez** [comment]
@aitboudad : must do i make something ? (it's my first PR for symfony)

**Comment by aitboudad** [comment]
@nicolasdewez no it's ok I'll merge into `2.8` but for the next time try to choose the right Branch :)

* `2.3`  fixing a bug.
* `2.8`  adding a new feature which is backward compatible;
* `master`, adding a new and backward incompatible feature.

see http://symfony.com/doc/2.7/contributing/code/patches.html#choose-the-right-branch

**Comment by fabpot** [comment]
Thank you @nicolasdewez.

**Pull request closed without merging**
