### PR TITLE
[Ldap] Add types to private properties

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
fabbot has a catch :) (will you backport some changes to 5.4 after merge or do you prefer to create the PR for 5.4 before?)

**Comment by derrabus** [comment]
I'll do the backports once the integration tests are green. I don't have an LDAP setup, so I'm abusing GHA at the moment. 🙈

**Comment by derrabus** [comment]
Backports: #42931

**Comment by nicolas-grekas** [comment]
Thank you @derrabus.

**Pull request merged**
