### PR TITLE
WIP #25825: Add a failing test to demonstrate bug introduced in #24987.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes (failing tests only for now)
| New feature?  | no
| BC breaks?    | demonstrates BC breaks already committed
| Deprecations? | tbd
| Tests pass?   | no (this is the purpose of this PR for now)
| Fixed tickets | #25825, #24987 (aiming to fix this - not yet fixed)
| License       | MIT
| Doc PR        | n/a

This PR adds some failing tests to demonstrate the problem introduced by the above-referenced PR.

The main issue introduced is demonstrated by test `[B]`. `hasParameterOption('-s')` returns the wrong result because it confuses the characters in the value of the `-e` flag for additional options.

Proposed resolution:

Back out #24987

Impact:

Symfony Console will once again have the limitation that one cannot use `cli.php -fh` to set the `-f` flag AND get help via the `-h` flag, because `hasParameterOption` / `getParameterOption` only work with short parameters that appear by themselves (e.g. `cli.php -f -h`). This limitation is necessary because `hasParameterOption()` has no access to the input definition.

In the tests below, backing out #24987 would have the following effect:

- `[A]`: Control test: `getOptions()` / `getOption()` will continue to work as always.
- `[B]`: Fixed
- `[C]` and `[D]`: Will fail. Fixed by #24987, but introduces a worse problem
- `[E]`, `[F]` and `[G]`: Not supported.

Remaining work:

The function `getParameterOption` still does not work correctly for short options with values. This bug was pre-existing, prior to #24987, and was not affected by that PR. See the comment on failing test `[I]`.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@greg-1-anderson the fix should be submitted against branch 2.7, isn't it? Would you like to submit one?

**Comment by greg-1-anderson** [comment]
@nicolas-grekas The bug was committed to many versions of Symfony. If 2.7 is where I should start, I'll be happy to make a PR there to fix this.

**Comment by nicolas-grekas** [comment]
Yes, that's how we manage this: we first merge in the lowest branch, then we merge that branch up to master.

**Comment by greg-1-anderson** [comment]
Work continues in #25893

**Pull request closed without merging**
