### PR TITLE
[VarDumper] word-break: break-all for long string dumps

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | "master"
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

Before

image

After

image

### CODE REVIEW

**Comment by ogizanagi** [comment]
Could you ensure it won't bring any regression with popular css frameworks rules like Bootstrap? I'm mentioning this because of [this fix](https://github.com/symfony/symfony/pull/16183) I've provided some time ago and this: https://github.com/symfony/symfony/pull/16183#r41654623.

**Comment by ro0NL** [comment]
Hm, current master applies a `200px` width already; https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/toolbar.css.twig#L378

Before

image

After

image

Chrome 54.0

**Comment by fabpot** [comment]
👍

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request merged**
