### PR TITLE
[HttpFoundation] Add Request::HEADER_X_FORWARDED_AWS_ELB const

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes (a missing part of a 3.3 feat.)
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

See https://github.com/symfony/symfony-docs/issues/7045

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can we ignore fabbot report here? Alignement is desired to me...

**Review by xabbuh — APPROVED** [review]
If we prefer to use the binary format, I am in favour of keep the alignment to ease readability.

**Comment by javiereguiluz** [comment]
I don't think we should keep the alignment. If we apply some code formatting syntax, we should apply it always and without exceptions. Otherwise this will cause problems when running the php-cs-fixer in the entire codebase, which is done from time to time.

**Comment by nicolas-grekas** [comment]
ok, fabbot green

**Comment by nicolas-grekas** [comment]
Just renamed the const to be even more explicit: `Request::HEADER_X_FORWARDED_AWS_ELB`

**Comment by weaverryan** [comment]
👍 This will help the docs - it's already complex enough :)

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
