### PR TITLE
[Filesystem] Fix Filesystem::remove() on Windows

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | #57375, #57346
| License       | MIT

Let's experiment with @smnandre's theory.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
appveyor still failing after this PR, your guess didn't work this time @smnandre :)

**Comment by smnandre** [comment]
Well could we use the old « dot » thing on Windows ? On my PR it seems to work well (and i’m not sure if the alpha order is the cause or the dot dot thing .. but i’m sure this change is the root of the problem — or at least what exposes it)

**Comment by nicolas-grekas** [comment]
I really really doubt that changing for a dot would fix anything. We should look for something else.

**Comment by xabbuh** [comment]
~If we find a proper solution for this, could it be that such a fix will also fix #50326?~ (the `FilesystemCommonTrait` doesn't use the Filesystem component)

**Comment by smnandre** [comment]
Maybe something there: https://github.com/rectorphp/rector-src/pull/5514

> using null arg to keep file permission: 
> ```diff
> - $this->filesystem->dumpFile($filePath, $newContent);
> + FileSystem::write($filePath, $newContent, null);
>  ```

**Pull request merged**
