### PR TITLE
[Validator] Update Spanish translation for Range validator  

### PR DESCRIPTION
**Pull request by plozmun**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no    
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | Part of #31503
| License       | MIT
| Doc PR        |  -

### CODE REVIEW

**Review by phansys — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Comment by javiereguiluz** [comment]
Both are correct. I'm going to look for which one is more commonly used. Please wait a bit before merging. Thanks.

**Review by javiereguiluz — APPROVED** [review]
The official authority that regulates the Spanish language [just confirmed via Twitter](https://twitter.com/RAEinforma/status/1151066402528382976) that the change proposed in this pull request is more correct. Thanks!

**Comment by fabpot** [comment]
Thank you @plozmun.

**Pull request merged**
