### PR TITLE
[Translation] make intl+icu format seamless by handling it in MessageCatalogue

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29136
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by gharlan — APPROVED** [review]
It fixes my issue (tested profiler and command `debug:translation`)
Thanks @nicolas-grekas!

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Now with tests. PR ready.

**Comment by stof** [comment]
@nicolas-grekas wouldn't `transChoice` now also go look in the Intl-ICU domain, but without switching to the Intl formatter ?

**Comment by nicolas-grekas** [comment]
It could, but that'd mean make a new feature accessible via a deprecated API. I'd prefer not allowing it. OK for you?

**Comment by nicolas-grekas** [comment]
OH, GOT IT.
Yes. I wouldn't care :)
New format with deprecated transChoice => not supported :)

**Comment by nicolas-grekas** [comment]
GRR. OK, fixed. Good catch @stof :)

**Review by stof — APPROVED** [review]

**Pull request merged**
