### PR TITLE
[Routing] Fix the retrieval of the default value for variadic arguments in the annotation loader

### PR DESCRIPTION
**Pull request by stof**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13690 |
| License | MIT |
| Doc PR | n/a |

This takes the test submitted in #13690 and implements the fix for this bug

### CODE REVIEW

**Comment by stof** [comment]
Actually, I'm wondering whether we need more changes to support variadic arguments properly in case values are passed.
However, in any case, this is a valid change.

**Comment by Tobion** [comment]
:+1:

**Comment by Tobion** [comment]
Thanks Christophe.

**Comment by wdalmut** [comment]
@Tobion do you know when this will be merged into 2.7 branch?

**Pull request merged**
