### PR TITLE
[DOMCrawler] Bug fixed

### PR DESCRIPTION
**Pull request by Imangazaliev**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### CODE REVIEW

**Comment by iltar** [comment]
A bug fix usually goes into the lowest possible maintained branch, can this go into 2.7?

**Comment by ro0NL** [comment]
@Imangazaliev you should also rebase your commit on the 2.7 branch in git and (force) push your branch from there.

And perhaps add a luttle test? :angel:

**Comment by stof** [comment]
As you created your PR from your master branch directly, rebasing it elsewhere will mess yo your fork though. this is why using feature branches is better.

And btw, when opening the PR, it is good to explain what the bug being fixed is instead of saying ``bug fixed``

**Comment by fabpot** [comment]
Good catch, thanks @Imangazaliev.

**Comment by fabpot** [comment]
@ro0NL We can't add a test as both syntaxes are valid :)

**Comment by jakzal** [comment]
Closing as it was merged already.

**Pull request closed without merging**
