### PR TITLE
[Validators] Add translations for Slovak #43735

### LINKED ISSUE #43735: Missing translations for Slovak (sk)
Hello,

There are some missing translation for Slovak (sk). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Validator/Resources/translations/validators.sk.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.sk.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by bhavin-nakrani**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #43735 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by fabpot** [comment]
Is Slovak your native language or have you used Google translate (or a similar tool)?

**Comment by bhavin-nakrani** [comment]
> Is Slovak your native language or have you used Google translate (or a similar tool)?

I have used Google translator.

**Comment by fabpot** [comment]
Let's close then. We don't want automated translations.

**Comment by ostrolucky** [comment]
Hey, my native language is slovak and these translations are spot on.

**Comment by fancyweb** [comment]
Thanks @ostrolucky, I guess we can reopen and merge it then.

**Comment by fabpot** [comment]
Thank you @bhavin-nakrani.

**Pull request merged**
