### PR TITLE
Remove unnecessary condition;

### PR DESCRIPTION
**Pull request by 243083df**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | ---
| License       | MIT
| Doc PR        | ---

### CODE REVIEW

**Review by sroze — APPROVED** [review]
True, as the `setResponse` method on the event as the typehint.

**Comment by nicolas-grekas** [comment]
Where is this enforced? I only see a docblock, which is not really an enforced contract :)

**Comment by sroze** [comment]
[Here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Event/GetResponseEvent.php#L49) ?

**Comment by nicolas-grekas** [comment]
But what if the setter is not called? ;)

**Comment by sroze** [comment]
Then `hasResponse` is false ;-)

**Review by nicolas-grekas — APPROVED** [review]
For 2.7

**Comment by sroze** [comment]
@243083df could you rebase and retarget the PR on 2.7?

**Review by chalasr — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @243083df.

**Comment by chalasr** [comment]
PR wasn't rebased to 2.7, should be backported.

**Comment by fabpot** [comment]
@chalasr Sorry about forgetting to switch to 2.7 for the merge. I don't think that we need to backport this. This is minor anyway. Not worth it. I would even say that it should not go to 2.7 as it does not fix any bugs.

**Pull request merged**
