### PR TITLE
[Cache] harden LockRegistry tests, consider PHP files only

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

see https://github.com/symfony/symfony/actions/runs/5761767836/job/15641917703#step:8:2977

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
let's update the .github/expected file instead, it's a sign that it's out of sync ;)

**Comment by xabbuh** [comment]
I am not sure which file you want to update, but the difference here I guess is coming from backup files being created in the pipeline. Locally the test already passes without the changes.

**Review by nicolas-grekas — APPROVED** [review]
I mean `.github/expected-missing-return-types.diff` on 6.4: the .orig files are created by the `patch` command when adding return types in the CI. Not sure why this issue pops up recently.

Anyway, :+1: for this change!

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
