### PR TITLE
[WebDebugToolbar] Adding options to WebDebugToolbar

### PR DESCRIPTION
**Pull request by loconox**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | no |
| License | MIT |
| Doc PR |  |

When the machine is very slow or when there are lot of sub requests, the WDT may not be able to show up after 5 tries every 500ms.
I'm suggesting to add some options to configure how many tries before the script stop trying to load the bar and even to configure the delay between each tries.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Instead of defining configuration values, I think it would be better to apply some reasonable values (3 retries, 5 sec. ?) and show an error message when the toolbar doesn't load. I remember that there was an old issue or pull request about this.

**Comment by loconox** [comment]
My point is that a reasonnable value may not have sens on some situations. In particular, between php5 and php7, the load may be much faster. Or dev on a very slow computer with xdebug and php5, the page may take several seconds to load.

**Comment by loconox** [comment]
I didn't look into the code in detail but I wanted to note that the behavior of the WDT seems different between the version <=2.7 and 2.8.
With 2.7 the bar may show up correctly but an memory error may be raised on the detailed page. Whereas with 2.8, the bar doesn't load without any php error but a 404.

**Comment by fabpot** [comment]
See #15670 for the prior discussion on this topic. A good solution is mentioned there but nobody implemented yet.

**Pull request closed without merging**
