### PR TITLE
[FrameworkBundle] Fix bad interface hint in AbstractController

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

As spotted by @stof

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by xabbuh** [comment]
Does it really make a difference? We have aliases for both interfaces pointing to the same service, don't we?

**Comment by chalasr** [comment]
I think it's sane to have the type that is closer to the injected implementation in the class itself.

**Comment by fabpot** [comment]
Instead of changing the interface, I would instead change the implementation to respect the current interface.

**Comment by nicolas-grekas** [comment]
done

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
But tests are broken.

**Review by xabbuh — APPROVED** [review]

**Comment by Tobion** [comment]
> Instead of changing the interface, I would instead change the implementation to respect the current interface.

Esp. since the FrameworkBundle EngineInterface will be deprecated #21035

**Review by Tobion — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
