### PR TITLE
[HttpFundation] Add an `XmlResponse` object.

### PR DESCRIPTION
**Pull request by Aerendir**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | Not created
| Fixed tickets | #24187 
| License       | MIT
| Doc PR        | not created

This is a first attempt to create an `XmlResponse` object.

### CODE REVIEW

**Comment by weaverryan** [comment]
Yo @Aerendir!

This seems simple enough! But... so simple, that I'm not sure it's worth it. This basically only sets the `Content-Type` header for you (which is valuable, but pretty minor) and runs your XML through `XmlEncoder`. But, shouldn't the user go through the `Serializer` class instead of the `XmlEncoder` directly? That's my main concern... in which case, this class is doing a bit too much (`JsonResponse` uses the native `json_encode()`, so it can "get away with it" a bit more).

I have a few other comments, but I don't want to trouble you with doing them until/unless we want to move forward :).

Cheers!

**Comment by fabpot** [comment]
I agree with @weaverryan. I'm 👎 for adding such a class in the core.

**Comment by javiereguiluz** [comment]
I'm closing this proposal because of the downvotes from Core Team members. @Aerendir I'm really sorry because this was going to be your first contribution to Symfony ... but I'm sure there will be more opportunities to contribute. Thanks a lot for supporting Symfony!

**Comment by Aerendir** [comment]
@Javiereguiluz, no problem, it will be for the next time! ☺️

**Pull request closed without merging**
