### PR TITLE
[Form] Be able to whitelist selected fields in a form

### PR DESCRIPTION
**Pull request by pascalwacker**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27660
| License       | MIT
| Doc PR        | -

As described in feature request https://github.com/symfony/symfony/issues/27660 I'd like to be able to whitelist selected fields in a form instead of either allow all or none. One use case for this could be the Google reCAPTCHA.

From the feature request:
**Description**  
Currently the Form component in Symfony has the option to allow additional fields by setting `allow_extra_fields` to true (http://symfony.com/doc/current/reference/forms/types/form.html#allow-extra-fields).
As of today, you can only specify a boolean either true or false. I'd propose to, besides having just booleans, also allow passing an array of strings as value. This would work as a mixture of both options, by allowing all fields, whose names are specified in that array, but still forbid all others. This would give devs a finer granularity in what should be allowed in forms and what not.

**Example**  
Currently we can only set a form to accept all or none additional fields. Ex. `$this->createFormBuilder(null, ['allow_extra_fields' => true])`, With this proposal, we could pass something like `$this->createFormBuilder(null, ['allow_extra_fields' => ['foo', 'bar']])`. The form would then accept fields with the name `foo` and `bar` but still reject others, like `baz`.

**Usage**
Only allowing specific additional fields in a form, for example: `g-recaptcha-response` which is used by [reCAPTCHA](https://developers.google.com/recaptcha/docs/verify) but still don't allow arbitrary form inputs to be added

### CODE REVIEW

**Comment by pascalwacker** [comment]
Somehow this part doesn't seem "perfect" to me yet:
```
foreach ($form->getExtraData() as $key => $val) {
    if (!in_array($key, $allowedExtraFields)) {
        $invalidExtraData[$key] = $val;
    }
}
```

Is there a better way to test for this? AFAIK PHP doesn't offer a way to check if one array contains another, or is there one? If so, it could be done with simply checking if the `array_keys` are contained within the allowed array.

**Comment by jakzal** [comment]
If you already know which additional fields to allow you could just add them to the form, or am I missing something?

**Comment by pascalwacker** [comment]
@jakzal for me the use case was with the reCAPTCHA. To achieve this, I could have added a new form element to twig and then use that.

Another use case could be, if you have to modify a form in the frontend with JS, adding optional fields. In that case, you don't know all the fields beforehand but might still like to use the PHP validation with a whitelist of allowed fields.

**Comment by xabbuh** [comment]
> Another use case could be, if you have to modify a form in the frontend with JS, adding optional fields. In that case, you don't know all the fields beforehand but might still like to use the PHP validation with a whitelist of allowed fields.

But even then you can still add the fields to your form type and just abstain from rendering them in the HTML. That said I am not convinced we should make this change in the component.

**Comment by xabbuh** [comment]
@ogizanagi @HeahDude What do you think about it?

**Comment by xabbuh** [comment]
I am closing here as several core team members are not convinced of this idea.

**Pull request closed without merging**
