### PR TITLE
[Security] Add missing Request typehint in HttpUtils::generateUri()

### PR DESCRIPTION
**Pull request by chalasr**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by dunglas** [comment]
This is a BC break and it's not permitted by [our BC promise](http://symfony.com/doc/current/contributing/code/bc.html):

> Add type hint to an argument	No

**Comment by chalasr** [comment]
Even if it could cause errors if the argument passed is not of the good type?
If it is, should I change the type of the phpdoc param to mixed?
Thank's

**Comment by dunglas** [comment]
You must keep it as it is currently. The PHPDoc is accurate. The typehint can added in Symfony 4 (branch not open yet) but not in 2 and 3 because it will break user classes overriding this method.

**Comment by chalasr** [comment]
Thank's for the explanation @dunglas

**Pull request closed without merging**
