### PR TITLE
Revert "bug #30423 [Security] Rework firewall's access denied rule (dimabory)"

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? |no
| Tests pass?   | yes
| Fixed tickets | #31136 
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by curry684** [comment]
So idea is to push this to 3.4 and 4.2 but not master right? Or should we just delay the real fix until 5.0 is branched?

**Comment by fabpot** [comment]
I'm fine with having it in master/4.3.

**Comment by curry684** [comment]
Yes so we agree the revert should only be in 3.4 and 4.2, and the fix stays in master/4.3 indeed  😄

**Comment by fabpot** [comment]
We will need a new PR for master though.

**Comment by dimabory** [comment]
> We will need a new PR for master though.

@fabpot Should I take over this as an author of #30423?

**Comment by curry684** [comment]
You could just resubmit the same PR with the upgrade and changelog notes that will be needed now.

**Comment by chalasr** [comment]
@dimabory PR welcome with UPGRADE + CHANGELOG entries

**Comment by dimabory** [comment]
@curry684, @chalasr Actually, the discussion can be moved to #30423 (someone is still commenting there)

**Comment by nicolas-grekas** [comment]
Thank you @chalasr 
PR welcome on master now.

**Pull request merged**
