### PR TITLE
[Form] keep the context when validating forms

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25542
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
The context is modified by the nested validator calls for the form children. I am actually not sure if this solution is the best or if we should rather clone the current context before validating the nested data.

If someone is able to write a test case for this, that will be really appreciated. I failed miserably.

**Comment by xabbuh** [comment]
Status: Needs Review

**Comment by nicolas-grekas** [comment]
Could you add a test case please?

**Review by nicolas-grekas — APPROVED** [review]
(I missed the test change :) )

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
