### PR TITLE
[TwigBridge] Amend `MoneyType` twig to include a space

### PR DESCRIPTION
**Pull request by mogilvie**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | 
| Deprecations? | 
| Tickets       | 
| License       | MIT
| Doc PR        | 

Fix for MoneyType not rendering classes in Bootstrap 4&5.

### CODE REVIEW

**Comment by mogilvie** [comment]
Failing on:
```
Unsilenced deprecation notices (1)

  1x: Legacy nullable type detected, please update your code as
         you are using nullable types in a docblock. support will be removed in v2.0.0
    1x in ObjectNormalizerTest::testDoesntHaveIssuesWithUnionConstTypes from Symfony\Component\Serializer\Tests\Normalizer
```

**Comment by stof** [comment]
As this is a bugfix, it should probably not target the 6.3 branch

**Comment by mogilvie** [comment]
They failing test looks like something with the ObjectNormalizer @dunglas. I won't even pretend to understand where the 'legacy nullable' type is.

**Comment by mogilvie** [comment]
Argh, fecked that up. I'm checking out for tonight. My apologies to everyone.

**Comment by javiereguiluz** [comment]
I haven't looked into the details of this ... but Bootstrap classes for money uses the `input-group-text` CSS class See https://getbootstrap.com/docs/5.2/forms/input-group/#multiple-addons

So, the existing code (`<div class="input-group{{ group_class|default('') }}">`) could be correct if `group_class` is `-text` ... and the new code (`<div class="input-group {{ group_class|default('') }}">`) only would be correct if `group_class` is `input-group-text`

**Comment by mogilvie** [comment]
> I haven't looked into the details of this ... but Bootstrap classes for money uses the `input-group-text` CSS class See https://getbootstrap.com/docs/5.2/forms/input-group/#multiple-addons
> 
> So, the existing code (`<div class="input-group{{ group_class|default('') }}">`) could be correct if `group_class` is `-text` ... and the new code (`<div class="input-group {{ group_class|default('') }}">`) only would be correct if `group_class` is `input-group-text`

The inner span is input-group-text. The outer div wrapper is class input-group. The issue is the outer div.
image

**Comment by javiereguiluz** [comment]
Mark, thanks for the additional insights!

**Review by javiereguiluz — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mogilvie.

**Pull request merged**
