### PR TITLE
[Form] Added missing Lithuanian translations

### PR DESCRIPTION
**Pull request by rmikalkenas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #38750 
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by Nyholm — COMMENTED** [review]
Thank you. 

Please help me with one thing, 

The word "tinkamą", does that mean "valid" or "appropriate"? Is the word "galioja" any better here?  
(I obviously don't know anything this, so feel free to tell me how much I am wrong)

**Comment by rmikalkenas** [comment]
> Thank you.
> 
> Please help me with one thing,
> 
> The word "tinkamą", does that mean "valid" or "appropriate"? Is the word "galioja" any better here?
> (I obviously don't know anything this, so feel free to tell me how much I am wrong)

"Galioja" would be better when talking about expiration date.
Valid and appropriate basically both means "tinkamą".

Which translation are you concerned about?

**Comment by Nyholm** [comment]
When I was using google translate (which are wrong time to time), most translations said "choose an **appropriate** file", etc. 

I just wanted to confirm that Google translate was wrong and that you just didnt make a misstake. 

Im happy with this. Thank you 👍

**Review by Nyholm — APPROVED** [review]

**Comment by rmikalkenas** [comment]
> When I was using google translate (which are wrong time to time), most translations said "choose an **appropriate** file", etc.
> 
> I just wanted to confirm that Google translate was wrong and that you just didnt make a misstake.
> 
> Im happy with this. Thank you 👍

Even though Im not a lithuanian language teacher, but for me "tinkamą" sounds and means better in this exact sentence 😅

**Comment by derrabus** [comment]
Thank you @rmikalkenas.

**Pull request merged**
