### PR TITLE
[Messenger] fix test to be compatible with DBAL 4.2

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

see doctrine/dbal#6504

### CODE REVIEW

**Review by alexandre-daubois — APPROVED** [review]

**Comment by derrabus** [comment]
We need to fix this on 5.4.

**Comment by xabbuh** [comment]
If I didn’t miss anything, we didn’t allow DBAL 4 in older versions.

**Comment by xabbuh** [comment]
see https://github.com/symfony/symfony/blob/0bd6136ce71ba0120e769879a6719897f1cc6cfb/composer.json#L136

**Comment by stof** [comment]
is there a way to rewrite this test to avoid using an internal class of DBAL, for which no BC is guaranteed at all ?

**Comment by derrabus** [comment]
> If I didn’t miss anything, we didn’t allow DBAL 4 in older versions.

We do actually. The high-deps tests should cover DBAL 4.

**Comment by xabbuh** [comment]
test updated and rebased on 5.4

**Review by derrabus — APPROVED** [review]

**Pull request merged**
