### PR TITLE
[PhpUnitBridge] hide stack trace of expected deprecation failures

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
this will have an effect only when using ``simple-phpunit``, not when registering the listener explicitly to be used for normal phpunit runs.

couldn't this be handled by the listener constructor instead ?

**Comment by xabbuh** [comment]
For our use cases that will work. But since the blacklist is only evaluated once I wanted to add the listener class as soon as possible. Do you think it's safe to always do that in the listener's constructor?

**Comment by stof** [comment]
Well, when using the simple-phpunit runner, it would still work (as the constructor is invoked before the line you added).
For usage through the config file, I don't know. It depends when the instantiation takes place. You would need to try it. See Swiftmailer for a project using the bridge through normal PHPUnit usage and registering the listener in the config file for instance.

**Comment by xabbuh** [comment]
I can confirm that moving the modification of the blacklist to the listener's constructor still leads to the expected effect.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
