### PR TITLE
[WebProfilerBundle] Fix regexp

### PR DESCRIPTION
**Pull request by mykiwi**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #12122 |
| License | MIT |
| Doc PR |  |

Old PR #12124

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@romqin thanks a lot for fixing this annoying issue!

**Comment by aitboudad** [comment]
:+1: indeed I wonder how to make it work with absolute URL ?

**Comment by romqin** [comment]
@aitboudad what if I add this :
```patch
+ var path = url.substr({{ app.request.basePath|length }});
- if (url.substr(0, 1) === '/' && !url.match(new RegExp({{ excluded_ajax_paths|json_encode|raw }}))) {
+ if (path.substr(0, 1) === '/' && !path.match(new RegExp({{ excluded_ajax_paths|json_encode|raw }}))) {
```

**Comment by aitboudad** [comment]
@romqin 
```patch
- var path = url.substr({{ app.request.basePath|length }});
+ var path = url.replace('{{ app.request.schemeAndHttpHost }}', '');

**Comment by romqin** [comment]
Or this, but maybe it's overkill :
```js
var path = url;
if (url.substr(0, 1) === '/') {
    if (0 === url.indexOf('{{ app.request.getBasePath }}')) {
        path = url.substr({{ app.request.basePath|length }});
    }
}
else if (0 === url.indexOf('{{ app.request.getSchemeAndHttpHost() ~ app.request.getBasePath }}')) {
    path = url.substr({{ (app.request.getSchemeAndHttpHost() ~ app.request.basePath)|length }});
}

if (!path.match(new RegExp({{ excluded_ajax_paths|json_encode|raw }}))) {
```

**Comment by aitboudad** [comment]
look good but I'd prefer to use ```replace``` instead of ```substr``` to simplify code :)
```js
var path = (url.substr(0, 1) === '/') ? url.replace('{{ app.request.basePath }}', ''):url.replace('{{ app.request.schemeAndHttpHost ~ app.request.basePath }}', '');
if (path.substr(0, 1) === '/' && !path.match(new RegExp({{ excluded_ajax_paths|json_encode|raw }}))) {
```

**Comment by florianbelhomme** [comment]
:+1:

**Comment by stof** [comment]
@aitboudad the issue with ``replace`` is that it will not only replace at the beginning of the string

**Comment by aitboudad** [comment]
@stof no it will replace only the first occurrence.

**Comment by stof** [comment]
@aitboudad but what if the path is not found at the beginning, but is found later in the string ?

**Comment by aitboudad** [comment]
@stof got it 

```patch
-  ? url.replace('{{ app.request.basePath }}', '')
-  : url.replace('{{ app.request.schemeAndHttpHost ~ app.request.basePath }}', '');
+  ? url.replace(/^({{ app.request.basePath|e('js') }})/, '')
+  : url.replace(/^({{ (app.request.schemeAndHttpHost ~ app.request.basePath)|e('js') }})/, '');
```

is that ok ?

**Comment by stof** [comment]
@aitboudad no. you need to escape the path for a usage into a regex (especially given that ``/`` is the delimiter, and it appears in the path)

**Comment by romqin** [comment]
So, should I use [my previous code](https://github.com/symfony/symfony/pull/14217#issuecomment-89789488) ?

**Comment by stof** [comment]
@romqin this looks like the right solution (except the escaping needed to output the value as a JS string)

**Comment by romqin** [comment]
Like this ?
```js
var path = url;
if (url.substr(0, 1) === '/') {
    if (0 === url.indexOf('{{ app.request.getBasePath|e('js') }}')) {
        path = url.substr({{ app.request.basePath|length }});
    }
}
else if (0 === url.indexOf('{{ (app.request.getSchemeAndHttpHost() ~ app.request.getBasePath)|e('js') }}')) {
    path = url.substr({{ (app.request.getSchemeAndHttpHost() ~ app.request.basePath)|length }});
}

if (!path.match(new RegExp({{ excluded_ajax_paths|json_encode|raw }}))) {
```

**Comment by aitboudad** [comment]
@romqin now it work for all url, you need check ```path.substr(0, 1) === '/'``` also

```js
if (path.substr(0, 1) === '/' && !path.match(new RegExp({{ excluded_ajax_paths|json_encode|raw }}))) {
```

**Comment by romqin** [comment]
Would be great to have this fix in 2.7 beta1  
ping @stof @fabpot @aitboudad @javiereguiluz

**Comment by fabpot** [comment]
Thank you @romqin.

**Comment by drmonty** [comment]
@fabpot this PR broke Silex-WebProfiler ~2.0@dev, see silexphp/Silex-WebProfiler#64

**Comment by stof** [comment]
We should not use the ``app`` global in the profiler template

**Pull request closed without merging**
