### PR TITLE
Add COMPOSER_BIN environment variable for PHPUnit Bridge

### LINKED ISSUE #34796: PHPUnit Bridge fails in CI environment
**Symfony version(s) affected**: 4.4.1

**Description**  
When trying to install phpunit bridge in Scrutinizer CI it tries to guess the path for composer. For some strange reason `$COMPOSER` gets evaluated to:

```
'/home/scrutinizer/.phpenv/versions/7.3.0/bin/php' '/usr/bin/composer'
```
When you run this via the command line or via the simple-phpunit.php script it displays:
```
php /usr/bin/composer.phar $@
```
It then fails to create the `$PHPUNIT_VERSION_DIR` directory and thus everything else fails.

**How to reproduce**  
Run `./bin/phpunit install` inside Scrutinizer CI

**Possible Solution**  
Check for `COMPOSER_BIN` environment variable and use that ahead of trying to work out the path.

**Additional context**  
```
php /usr/bin/composer.phar $@
PHP Warning:  chdir(): No such file or directory (errno 2) in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 127

Warning: chdir(): No such file or directory (errno 2) in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 127

php /usr/bin/composer.phar $@

php /usr/bin/composer.phar $@

php /usr/bin/composer.phar $@

php /usr/bin/composer.phar $@
PHP Warning:  file_get_contents(./src/Framework/TestCase.php): failed to open stream: No such file or directory in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 156

Warning: file_get_contents(./src/Framework/TestCase.php): failed to open stream: No such file or directory in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 156
PHP Warning:  file_put_contents(./src/Framework/TestCase.php): failed to open stream: No such file or directory in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 161

Warning: file_put_contents(./src/Framework/TestCase.php): failed to open stream: No such file or directory in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 161
PHP Warning:  file_get_contents(./src/Framework/Assert.php): failed to open stream: No such file or directory in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 164

Warning: file_get_contents(./src/Framework/Assert.php): failed to open stream: No such file or directory in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 164
PHP Warning:  file_put_contents(./src/Framework/Assert.php): failed to open stream: No such file or directory in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 166

Warning: file_put_contents(./src/Framework/Assert.php): failed to open stream: No such file or directory in /home/scrutinizer/build/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php on line 166
```

### PR DESCRIPTION
**Pull request by NoodlesNZ**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #34796
| License       | MIT
| Doc PR        | 

I came across a weird edge case when PHPUnit Bridge tries to get the composer binary path inside Scrutinizer CI (see attached ticket). To work around this edge case I added an environment variable for the composer binary path.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I think there might be a better way, based on `phpenv which composer`.
We should add this command to the list of ways to autodiscover composer.
Could you give it a try?

**Comment by NoodlesNZ** [comment]
I'm not sure it works. When I run that command on Scrutinizer I get:
```
scrutinizer@container-10:~$ phpenv which composer
rbenv: composer: command not found
```

But when I run `which` it gives me:
```
scrutinizer@container-10:~$ which composer
/usr/bin/composer
```

**Comment by nicolas-grekas** [comment]
Replaced by #35219, which should solve the issue also. Thank you @NoodlesNZ!

**Comment by NoodlesNZ** [comment]
Thanks @nicolas-grekas, a much more eloquent solution. I tested the patch on Scrutinizer and it works as expected.

**Pull request closed without merging**
