### PR TITLE
[Asset] ability to set assets_version_strategy as service

### PR DESCRIPTION
**Pull request by ewgRa**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

While I working on #14832 I realize that all this problems and hidden magic can be avoided, if we will have ability to set asset version strategy as service.

This PR implementation of this idea.

Now it is possible to do something like this:

```
framework:
    assets:
        version_strategy: assets.custom_version_strategy
        base_urls: http://cdn.example.com
        packages:
            foo:
                base_urls: ["https://example.com"]
                version_strategy: assets.custom_version_strategy        
```

There is can be some conflicts with #16511, I will fix it, depends on which one PR will be merged first (or not merged) :)

### CODE REVIEW

**Comment by ewgRa** [comment]
Test fail seems not related to this PR

**Comment by ewgRa** [comment]
ping @fabpot, what do you think? I think it is great feature

**Comment by fabpot** [comment]
As this is a new feature, it should be done on master instead.  @ewgRa Can you rebase and submit a new PR? Thanks.

**Comment by ewgRa** [comment]
Closed in favor #17532

**Pull request closed without merging**
