### PR TITLE
[2.7] [DoctrineBridge] [Form] fix choice_value in EntityType

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17693, #17271, #13964 |
| License | MIT |
| Doc PR | symfony/symfony-docs#6260 |

### CODE REVIEW

**Comment by HeahDude** [comment]
Before :
```
Time: 10.1 seconds, Memory: 65.50Mb

There was 1 failure:

1) Symfony\Bridge\Doctrine\Tests\Form\Type\EntityTypeTest::testOverrideChoicesValues
Field should be synchronized.
Failed asserting that false is true.

/Users/Heah/Sites/dev/symfony/src/Symfony/Bridge/Doctrine/Tests/Form/Type/EntityTypeTest.php:761

FAILURES!
Tests: 431, Assertions: 625, Failures: 1, Skipped: 11.

Legacy deprecation notices (212)
KO ./src/Symfony/Bridge/Doctrine
```

After :

```
Time: 8.92 seconds, Memory: 65.25Mb

OK, but incomplete, skipped, or risky tests!
Tests: 431, Assertions: 627, Skipped: 11.

Legacy deprecation notices (212)
OK ./src/Symfony/Bridge/Doctrine
```

**Comment by nicolas-grekas** [comment]
Please revert the indentation changes...

**Comment by HeahDude** [comment]
@nicolas-grekas oupssss

**Comment by HeahDude** [comment]
Done
Status: Needs Review

**Comment by webmozart** [comment]
Thanks for that PR! Looks good to me.

Status: reviewed

**Comment by HeahDude** [comment]
thanks @webmozart, just added #13964 as fixed though.

**Comment by HeahDude** [comment]
@fabpot @webmozart. Tests in 2.8 need renaming `entity` to `Symfony\Bridge\Doctrine\Form\Type\EntityType`, should I make a PR on 2.8 to update only this once 2.7 is merged in 2.8 or do another version of this one right now for the greater branches ?

**Comment by webmozart** [comment]
@HeahDude I would create a separate PR and rebase this one once that is merged.

**Comment by HeahDude** [comment]
Updated description with link to the doc PR and tests are ready for 2.8 with #17699.

ping @symfony/deciders

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Comment by HeahDude** [comment]
thanks @fabpot, don't forget to ping me in #17699 for the rebase, when this one gets merged in 2.8 :)

**Pull request merged**
