### PR TITLE
[DependencyInjection] Don't try to load YamlFileLoader if it's not actually needed

### LINKED ISSUE #41169: symfony/dependency-injection has a hard dependency on symfony/config under PHP 8
**Symfony version(s) affected**: 5.3.0-beta3

**Description**
symfony/dependency-injection now appears to have a hard dependency on symfony/config when running under PHP 8.

**How to reproduce**
```
$ composer init
...
$ composer require symfony/dependency-injection:^5.3@beta
...
$ cat test.php 
<?php

require 'vendor/autoload.php';

new Symfony\Component\DependencyInjection\Compiler\PassConfig();

$ php8.0 test.php
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Config\Loader\FileLoader" not found in vendor/symfony/dependency-injection/Loader/FileLoader.php:32
```

This is because `PassConfig::__construct()` calls `new RegisterAutoconfigureAttributesPass()`, where the constructor instantiates `YamlFileLoader` via reflection - and `YamlFileLoader` is a subclass of `Symfony\Component\Config\Loader\FileLoader`. 

Cross-posting this from Drupal core, where we are working on upgrading to the latest release of Symfony in https://www.drupal.org/project/drupal/issues/3161889#comment-14098238 - we use the DI component including ContainerBuilder and PassConfig, but don't use the Config component.

**Possible Solution**
Move `YamlFileLoader::parseDefinition()` to a trait or helper class? This would also avoid the use of reflection in RegisterAutoconfigureAttributesPass to use a private method on YamlFileLoader.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41169
| License       | MIT
| Doc PR        | -

This PR enables using DI without Config when autoconfiguration is not used.
(When autoconfiguration is used, the dependency on Config is still there.)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
(false positives from psalm)

**Review by derrabus — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Comment by longwave** [comment]
:+1: this solves the dependency issue for Drupal

**Comment by derrabus** [comment]
@nicolas-grekas The Travis failures look related.

**Comment by nicolas-grekas** [comment]
Thanks for the ping @derrabus, should be fixed now.

**Comment by derrabus** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
