### PR TITLE
[HttpClient] don't break BC badly

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Follows #31831, replaces #31842, as I'd prefer not sticking to a specific minor version - that'd be bad for transitivity of deps IMHO.

/cc @xabbuh @fabpot

### CODE REVIEW

**Comment by xabbuh** [comment]
The issue I see here is that consumers of the interface now cannot rely on the method being present which makes it more or less useless.

**Comment by stof** [comment]
I think I actually prefer https://github.com/symfony/symfony/pull/31842. We should not use the caret operator when depending on an experimental package, as this experimental package does not guarantee BC yet (and so relying on the semver BC rules is a wrong assumption).

**Comment by fabpot** [comment]
What about considering #31850 instead?

**Comment by nicolas-grekas** [comment]
Closing in favor of #31850

**Pull request closed without merging**
