### PR TITLE
[Form] Add "range" type #11979

### PR DESCRIPTION
**Pull request by crevillo**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | 11979 |
| License | MIT |

Here's my approach to https://github.com/symfony/symfony/issues/11979

It allows to use range field type with symfony

### CODE REVIEW

**Comment by stof** [comment]
2 things are missing here:

- tests (for the form type, and for its rendering)
- the PHP form theme update (which would have been catched by the rendering tests if they were there)

**Comment by crevillo** [comment]
Ok. I will try to do them during the next hours and will ping you about.

**Comment by stof** [comment]
@crevillo ping

**Comment by crevillo** [comment]
Haven't found time. Feel free to take over

**Comment by webmozart** [comment]
This was added in #12067. Thanks for creating the PR @crevillo!

**Pull request closed without merging**
