### PR TITLE
[Lock] downgrade log.info to log.debug

### LINKED ISSUE #37710: [Lock] downgrade log.info to log.debug
**Description**  
the Lock class log to info level, but it's not a useful information to store in my production logs.
see:
https://github.com/symfony/lock/blob/8ecfa4943d835cc3803e4d6f9696c81c43fbae90/Lock.php#L81
https://github.com/symfony/lock/blob/8ecfa4943d835cc3803e4d6f9696c81c43fbae90/Lock.php#L138

I think that this type of log should be downgraded to debug instead of info
Currently i configure this class with NullLogger but it's not ideal because i can lost usefull logs like:
https://github.com/symfony/lock/blob/8ecfa4943d835cc3803e4d6f9696c81c43fbae90/Lock.php#L141

### PR DESCRIPTION
**Pull request by rvitaliy**
| Q             | A
| ------------- | ---
| Branch?       | master for features / 3.4, 4.4 or 5.1 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #37710
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

we changed log behavior see issue for more details

### CODE REVIEW

**Review by jderusse — APPROVED** [review]
I wonder if we shouldn't also downgrade the notice `Failed to acquire the "{resource}" lock. Someone else already acquired the lock.` to info

**Comment by fabpot** [comment]
I agree with @jderusse 
Can you also rebase as there is a conflict?

**Review by nicolas-grekas — APPROVED** [review]
For 4.4, isn't it?

**Comment by fabpot** [comment]
Thank you @rvitaliy.

**Pull request merged**
