### PR TITLE
add translation for afrikaans

### LINKED ISSUE #45123: Missing translations for Afrikaans (af)
Hello,

There are some translation work needed for Afrikaans (af) and we are looking for a **native** speaker to help us out. 

Here is a [short example](https://symfony-translations.nyholm.tech/#pr) of what you need to do. There are 4 rules: 

1. You must be a Afrikaans (af) native speaker
2. You must look at the existing translations and follow the same "style" or "tone"
3. You must make your PR to branch 6.4
4. You must use the correct indentation (number of spaces)

These are the files that should be updated: 
- [src/Symfony/Component/Validator/Resources/translations/validators.af.xlf](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Validator/Resources/translations/validators.af.xlf)

<details>
<summary>Show related strings</summary>

#### src/Symfony/Component/Validator/Resources/translations/validators.af.xlf

| Id | English | Translation | Status |
| -- | -- | -- | -- |
| 37 | This is not a valid IP address. | Hierdie waarde is nie 'n geldige IP-adres nie. | Needs review |
| 51 | No temporary folder was configured in php.ini. | Geen tydelike gids is in php.ini opgestel nie, of die opgestelde gids bestaan nie. | Needs review |
| 59 | This is not a valid International Bank Account Number (IBAN). | Hierdie waarde is nie 'n geldige Internasionale Bankrekeningnommer (IBAN) nie. | Needs review |
| 81 | This is not a valid Business Identifier Code (BIC). | Hierdie waarde is nie 'n geldige Besigheid Identifiseerder Kode (BIC) nie. | Needs review |
| 83 | This is not a valid UUID. | Hierdie waarde is nie 'n geldige UUID nie. | Needs review |
| 93 | This password has been leaked in a data breach, it must not be used. Please use another password. | Hierdie wagwoord is in 'n data-oortreding uitgelek, dit mag nie gebruik word nie. Gebruik asseblief 'n ander wagwoord. | Needs review |
| 104 | The filename is too long. It should have {{ filename_max_length }} character or less.\|The filename is too long. It should have {{ filename_max_length }} characters or less. | Die lêernaam is te lank. Dit moet {{ filename_max_length }} karakter of minder hê.\|Die lêernaam is te lank. Dit moet {{ filename_max_length }} karakters of minder hê. | Needs review |
| 105 | The password strength is too low. Please use a stronger password. | Die wagwoordsterkte is te laag. Gebruik asseblief 'n sterker wagwoord. | Needs review |
| 106 | This value contains characters that are not allowed by the current restriction-level. | Hierdie waarde bevat karakters wat nie toegelaat word deur die huidige beperkingsvlak nie. | Needs review |
| 107 | Using invisible characters is not allowed. | Die gebruik van onsigbare karakters word nie toegelaat nie. | Needs review |
| 108 | Mixing numbers from different scripts is not allowed. | Die meng van nommers van verskillende skrifte word nie toegelaat nie. | Needs review |
| 109 | Using hidden overlay characters is not allowed. | Die gebruik van verborge oorvleuelende karakters word nie toegelaat nie. | Needs review |
| 110 | The extension of the file is invalid ({{ extension }}). Allowed extensions are {{ extensions }}. | Die uitbreiding van die lêer is ongeldig ({{ extension }}). Toegelate uitbreidings is {{ extensions }}. | Needs review |
| 111 | The detected character encoding is invalid ({{ detected }}). Allowed encodings are {{ encodings }}. | Die opgespoorde karakterkodering is ongeldig ({{ detected }}). Toegelate koderings is {{ encodings }}. | Needs review |
| 112 | This value is not a valid MAC address. | Hierdie waarde is nie 'n geldige MAC-adres nie. | Needs review |
| 113 | This URL is missing a top-level domain. | Die URL mis 'n topvlakdomein. | Needs review |
| 114 | This value is too short. It should contain at least one word.\|This value is too short. It should contain at least {{ min }} words. | Hierdie waarde is te kort. Dit moet ten minste een woord bevat.\|Hierdie waarde is te kort. Dit moet ten minste {{ min }} woorde bevat. | Needs review |
| 115 | This value is too long. It should contain one word.\|This value is too long. It should contain {{ max }} words or less. | Hierdie waarde is te lank. Dit moet een woord bevat.,Hierdie waarde is te lank. Dit moet {{ max }} woorde of minder bevat. | Needs review |
| 116 | This value does not represent a valid week in the ISO 8601 format. | Hierdie waarde stel nie 'n geldige week in die ISO 8601-formaat voor nie. | Needs review |
| 117 | This value is not a valid week. | Hierdie waarde is nie 'n geldige week nie. | Needs review |
| 118 | This value should not be before week "{{ min }}". | Hierdie waarde mag nie voor week "{{ min }}" wees nie. | Needs review |
| 119 | This value should not be after week "{{ max }}". | Hierdie waarde mag nie na week "{{ max }}" kom nie. | Needs review |
| 121 | This value is not a valid Twig template. | Hierdie waarde is nie 'n geldige Twig-sjabloon nie. | Needs review |
| 122 | This file is not a valid video. | Hierdie lêer is nie 'n geldige video nie. | Needs review |
| 123 | The size of the video could not be detected. | Die grootte van die video kon nie bepaal word nie. | Needs review |
| 124 | The video width is too big ({{ width }}px). Allowed maximum width is {{ max_width }}px. | Die videowydte is te groot ({{ width }}px). Toegelate maksimum wydte is {{ max_width }}px. | Needs review |
| 125 | The video width is too small ({{ width }}px). Minimum width expected is {{ min_width }}px. | Die videobreedte is te klein ({{ width }}px). Minimum verwagte breedte is {{ min_width }}px. | Needs review |
| 126 | The video height is too big ({{ height }}px). Allowed maximum height is {{ max_height }}px. | Die videohoogte is te groot ({{ height }}px). Toegelate maksimum hoogte is {{ max_height }}px. | Needs review |
| 127 | The video height is too small ({{ height }}px). Minimum height expected is {{ min_height }}px. | Die videohoogte is te klein ({{ height }}px). Minimum hoogte verwag is {{ min_height }}px. | Needs review |
| 128 | The video has too few pixels ({{ pixels }} pixels). Minimum amount expected is {{ min_pixels }} pixels. | Die video het te min pixels ({{ pixels }}). Minimum hoeveelheid verwag is {{ min_pixels }}. | Needs review |
| 129 | The video has too many pixels ({{ pixels }} pixels). Maximum amount expected is {{ max_pixels }} pixels. | Die video het te veel pixels ({{ pixels }}). Maksimum verwagte hoeveelheid is {{ max_pixels }}. | Needs review |
| 130 | The video ratio is too big ({{ ratio }}). Allowed maximum ratio is {{ max_ratio }}. | Die videoratio is te groot ({{ ratio }}). Toegelate maksimum ratio is {{ max_ratio }}. | Needs review |
| 131 | The video ratio is too small ({{ ratio }}). Minimum ratio expected is {{ min_ratio }}. | Die videoratio is te klein ({{ ratio }}). Minimum verwagte ratio is {{ min_ratio }}. | Needs review |
| 132 | The video is square ({{ width }}x{{ height }}px). Square videos are not allowed. | Die video is vierkantig ({{ width }}x{{ height }}px). Vierkantige video's word nie toegelaat nie. | Needs review |
| 133 | The video is landscape oriented ({{ width }}x{{ height }}px). Landscape oriented videos are not allowed. | Die video is landskap georiënteer ({{ width }}x{{ height }} px). Landskapvideo's word nie toegelaat nie. | Needs review |
| 134 | The video is portrait oriented ({{ width }}x{{ height }}px). Portrait oriented videos are not allowed. | Die video is portretgeoriënteerd ({{ width }}x{{ height }}px). Portretgeoriënteerde video's word nie toegelaat nie. | Needs review |
| 135 | The video file is corrupted. | Die videolêer is korrup. | Needs review |
| 136 | The video contains multiple streams. Only one stream is allowed. | Die video bevat veelvuldige strome. Slegs een stroom word toegelaat. | Needs review |
| 137 | Unsupported video codec "{{ codec }}". | Nie-ondersteunde videokodek "{{ codec }}". | Needs review |
| 138 | Unsupported video container "{{ container }}". | Nie-ondersteunde videohouer "{{ container }}". | Needs review |
| 139 | The image file is corrupted. | Die beeldlêer is beskadig. | Needs review |
| 140 | The image has too few pixels ({{ pixels }} pixels). Minimum amount expected is {{ min_pixels }} pixels. | Die beeld het te min pixels ({{ pixels }}). Minimum hoeveelheid verwag is {{ min_pixels }}. | Needs review |
| 141 | The image has too many pixels ({{ pixels }} pixels). Maximum amount expected is {{ max_pixels }} pixels. | Die beeld het te veel pixels ({{ pixels }}). Maksimum verwagte aantal is {{ max_pixels }}. | Needs review |
| 142 | This filename does not match the expected charset. | Hierdie lêernaam stem nie ooreen met die verwagte karakterstel nie. | Needs review |

</details>

> [!NOTE]
> If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by lacatoire**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45123
| License       | MIT

### CODE REVIEW

**Comment by stof** [comment]
@lacpandore the fabbot checks are meant to prevent English typos. I would not trust it for translations. In such cases, it is often best to ignore its suggestion than applying it.

**Comment by lacatoire** [comment]
> @lacpandore the fabbot checks are meant to prevent English typos. I would not trust it for translations. In such cases, it is often best to ignore its suggestion than applying it.

ok i've checked on another tools, it seems fabbot was wrong, i've removed it's suggestion

**Comment by fabpot** [comment]
@lacpandore You didn't answer my question on another issue. We won't accept PRs if these translations are done via a tool like Google translate or Deepl. Please, confirm that you are indeed fluent in all the languages for which you're opening PRs.

**Comment by lacatoire** [comment]
Hi @fabpot i'm not. I just tried !

**Comment by fabpot** [comment]
Ok, I'm closing these PRs then.

**Pull request closed without merging**
