### PR TITLE
[Security] fix check for empty usernames

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15237 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by WouterJ** [comment]
Can you also fix some other occurences of empty + username? As there are more https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=if+%28empty%28%24username%29%29

**Comment by WouterJ** [comment]
Status: Needs Work

**Comment by xabbuh** [comment]
@WouterJ done

**Comment by WouterJ** [comment]
Perfect!

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
