### PR TITLE
[TwigBundle] Normalize path of template to support Windows

### PR DESCRIPTION
**Pull request by yethee**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14764 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by Tobion** [comment]
Why is that needed? What fails? What is the error?

**Comment by yethee** [comment]
Windows uses backslash as a directory separator, so the reference to a template may be incorrect. For example, `@app/foo\bar.html.twig` instead of `@app/foo/bar.html.twig`.

**Comment by Tobion** [comment]
When accesing files via php, you can use both forms of slashes. It works either way. Also twig normalizes the path anyway. So again, what error are you facing?

**Comment by yethee** [comment]
You are right. I check again, twig really used cache file which it has been generated by not normalized path. Won't fix.

**Pull request closed without merging**
