### PR TITLE
remove conflict with phpunit/phpunit < 5.4.3

### PR DESCRIPTION
**Pull request by alexislefebvre**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #...
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

[PHPUnit 5.4.3](https://packagist.org/packages/phpunit/phpunit#5.4.3) requires PHP `^5.6` or `^7.0`. Therefore it can't be installed alongside Symfony 6.2 which require PHP `>=PHP 8.1`. So we can remove it from the `conflict` conf.

### CODE REVIEW

**Comment by stof** [comment]
See my comment on https://github.com/symfony/symfony/pull/47487#issuecomment-1236631961

This conflict rule still makes sense.

**Comment by alexisLefebvre** [comment]
@stof Thanks for the feedback.

Can we keep the conflict rule and change it to `"phpunit/phpunit": "<5.2.8"`?

It looks like it was changed in [5.2.8](https://packagist.org/packages/phpunit/phpunit#5.2.8), see [5.2.7](https://packagist.org/packages/phpunit/phpunit#5.2.7) that has no boundary.

**Comment by nicolas-grekas** [comment]
> older PHPUnit version (matched by that conflict rule) don't have the PHP upper bound. So without that conflict rule, it could install phpunit 5.0.9 for instance.

Do we need to care about this? I'm not sure it's on us to fix, nor that this is likely to happen in practice.

**Comment by stof** [comment]
@nicolas-grekas I'm quite sure we added those conflict rules because our optional PHPUnit integrations have a minimum supported version for PHPUnit. So I would not remove the conflict rule, and I would not lower it either (because the *current* value of the conflict rule probably has a meaning, even though versions between 5.2.8 and 5.4.3 would be forbidden by the PHP requirement anyway).

**Comment by nicolas-grekas** [comment]
Fine by me, thanks for proposing, and for the reminders @stof.
Closing therefor.

**Pull request closed without merging**
