### PR TITLE
[HttpFoundation] Add test for non-string request attribute matching

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | related #16529 |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by fabpot** [comment]
Indeed, attribute values should only be scalars.

**Comment by teohhanhui** [comment]
@fabpot
> attribute values should only be scalars

But `_controller` can be a callable, that's how I ran into this bug...

**Comment by teohhanhui** [comment]
Seems to be explicitly supported:

https://github.com/symfony/http-kernel/blob/2.3/Controller/ControllerResolver.php#L67-L70

**Comment by xabbuh** [comment]
@fabpot I think @teohhanhui is right here. THe API doc also doesn't put any restrictions on it: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ParameterBag.php#L97

**Comment by teohhanhui** [comment]
What ParameterBag can store is not the question here. The question is what should be expected in Request `attributes`? Can it accept non-scalars? I think the answer is yes.

**Comment by xabbuh** [comment]
Well, `$attributes` is a `ParameterBag` instance.

**Comment by teohhanhui** [comment]
Additional semantics could be applied here, but it might be hard to enforce in code or to articulate in phpdoc...

**Comment by fabpot** [comment]
Philosophically, attributes should be scalars. Put another way, even if Symfony internals puts non-scalar in there, this is its responsibility. As a end user, you should not do that... or at least, this is not officially supported.

**Comment by fabpot** [comment]
Closing this as it's better if the discussion only happens on one place. Leaving the ticket opened for now.

**Pull request closed without merging**
