### PR TITLE
[WIP] [FrameworkBundle] Add debug:autoconfigure command

### PR DESCRIPTION
**Pull request by atailouloute**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | #26295
| License       | MIT
| Doc PR        | TODO

This will be the continuation of the work started in PR #31183

### CODE REVIEW

**Comment by maxhelias** [comment]
Is it testable as is?

**Comment by atailouloute** [comment]
> Is it testable as is?

@maxhelias It is, but it's not complete yet, I will push a new update ASAP

**Comment by nicolas-grekas** [comment]
rebase needed
ready otherwise?

**Comment by YaFou** [comment]
Any news about this pull request?

**Comment by atailouloute** [comment]
Anyone wants to continue on this? I will not have enough time to finish it, but I can help if someone is motivated

**Comment by fabpot** [comment]
As there is a linked issue, I'm closing here in the meantime. Thanks for the quick feedback.

**Pull request closed without merging**
