### PR TITLE
[2.3][CS][Twig] String literals with single quotes

### PR DESCRIPTION
**Pull request by SpacePossum**
| Q | A |
| --- | --- |
| Bug fix? | [no] |
| New feature? | [no] |
| BC breaks? | [no] |
| Deprecations? | no] |
| Tests pass? | [yes] |
| License | MIT |

### CODE REVIEW

**Comment by SpacePossum** [comment]
Failing tests are not related:
`No releases available for package "pecl.php.net/memcached"
install failed
The command "if [[ "$TRAVIS_PHP_VERSION" != *"nightly" ]]; then pecl install -f memcached-2.1.0; fi;" failed and exited with 1 during .`

**Comment by aitboudad** [comment]
In twig there is no preference of using single or double quotes and it's not a part of Twig CS.

**Comment by WouterJ** [comment]
Hmm, why would we want something like this? Consistency? Or did you find errors with the double quote usage in Twig?

**Comment by SpacePossum** [comment]
For consistency mostly, readability secondly.

These are now being changed in PHP although not part of the Symfony coding standard (http://symfony.com/doc/current/contributing/code/standards.html) and not in PSR (as far as I can find).
I admit; in PHP there is small speed gain which is not the case in Twig.

**Comment by fabpot** [comment]
Closing now

**Pull request closed without merging**
