### PR TITLE
[Finder] Only use GLOB_BRACE when available

### PR DESCRIPTION
**Pull request by dosten**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14502 |
| License | MIT |

### CODE REVIEW

**Comment by dosten** [comment]
The failing tests seems to be unrelated.

**Comment by stof** [comment]
it would be better to avoid defining the constant if it is unsupported. It could break other tools checking the support for the feature by detecting the constant (we stopped redefining constants for ``ENT_SUBSTITUTE`` for this reason for instance, even though we may still have a few places using this pattern for other constants)

**Comment by dosten** [comment]
@webbird proposed this solution:
`defined('GLOB_BRACE') ? GLOB_BRACE | GLOB_ONLYDIR : GLOB_ONLYDIR` this is better?

**Comment by dosten** [comment]
btw, we override JSON_PRETTY_PRINT, this needs to be replaced in 2.6, 2.7 and 2.8? Ex:
- `Symfony/Bridge/Twig/Command/LintCommand`
- `Symfony/Bundle/FrameworkBundle/Command/YamlLintCommand`
- `Symfony/Bundle/FrameworkBundle/Console/Descriptor/JsonDescriptor`
- `Symfony/Component/Translation/Dumper/JsonFileDumper`

**Comment by dosten** [comment]
@stof i have updated the PR.

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @dosten.

**Pull request closed without merging**
