### PR TITLE
[Debug] Fix bad registration of exception handler, leading to mem leak

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 27
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25965
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by alcaeus** [comment]
@nicolas-grekas I applied your commit on 3.4.4 in my projects and it fixes the problems I've been having since moving to 3.4.4 :+1:

**Comment by derrabus** [comment]
With your patch applied, the leak seems to be gone.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by gmponos** [comment]
Any chance this could be tagged ASAP since it consumes a lot of resources?

**Comment by florian25686** [comment]
I ran into this issue today and couldn't find the bugfix in the tag 3.4.4. Is there any update plan for the tags?

**Comment by derrabus** [comment]
@florian25686 The bugfix will go into 3.4.5.

**Pull request merged**
