### PR TITLE
[Intl] Add a special locale to strip emojis easily with `EmojiTransliterator`

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

I'd like to add a special locale `strip` to the emoji transliterator to easily remove all emojis from a string. It would only work with valid input/emojis.

Removing emojis from a string is not easy. Regexes are complicated and most of the time not up-to-date with the latest Unicode versions. I thought we could leverage the new transliterator :smile:

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]
I like it

**Comment by javiereguiluz** [comment]
I like this feature (and I've needed it myself more than once ... I agree with what you said about regexes).

What I don't like is "hacking" this feature as a special non-real locale. This is a convention that developers must learn, so it makes it a bit more difficult. I wonder if we could add a `removeEmojis()` method in `String` component or any other method somewhere. Thanks.

**Review by nicolas-grekas — APPROVED** [review]
LGTM.

This is not really a locale but a transliteration rule. This belongs to the EmojiTransliterator to me.
(the patch demonstrates it quite strongly: there is no new code here, just a new map.)

**Comment by ro0NL** [comment]
i'd still be in favor of String integration, `u($s)->stripEmoji()->toString()`

**Comment by nicolas-grekas** [comment]
> i'd still be in favor of String integration, u($s)->stripEmoji()->toString()

That'd be :-1: on my side. I don't see why this specific translit rule would deserve such an important place.

**Comment by ro0NL** [comment]
i assumed our removeEmoji() removed emoji, but in fact it transliterates them to codes :facepalm:  (based on https://github.com/aaronpk/emoji-detector-php)

nevertheless i still think controlling the emoji at String level is nice to have

**Comment by nicolas-grekas** [comment]
Thank you @fancyweb.

**Pull request merged**
