### PR TITLE
[DoctrineBridge][EventDispatcher] Add LazyEventManager and LazyEventDispatcher

### PR DESCRIPTION
**Pull request by enumag**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

My application does not use the full symfony framework, just some parts. Among them the DoctrineBridge and EventDispatcher. I'd like to have the subscribers loaded lazily which symfony can do but the classes require a Container from Symfony\DependencyInjection - which I don't use. I'm using a different DI container, namely [nette/di](https://github.com/nette/di).

The logic of ContainerAwareEventManager/Dispatcher is not really dependent on symfony/dependency-injection. In fact the container is only used once in the whole class. Therefore I'd like to split the classes like this so that I don't have to copy the lazy-loading logic when using a different DI container.

### CODE REVIEW

**Comment by enumag** [comment]
I've refactored it a little bit. The LazyEventManager/Dispatcher is no longer abstract with a method to be implemented. Instead it accepts a callable resolver. The ContainerAwareEventManager/Dispatcher simply wrap the container into a closure.

It is cleaner this way in my opinion but I can revert it if necessary.

**Review by lemoinem — CHANGES_REQUESTED** [review]
I like this version better too... I don't think anything in the docs need updating...

However, splitting the tests for `ContainerAwareEventManager`as you did for the code. And use them as a basis to write tests for the `ContainerAware/LazyEventManager` too?

Status: Needs work

**Comment by lemoinem** [comment]
Status: Needs Work

**Comment by enumag** [comment]
@lemoinem Done, please review.

Status: Needs Review

**Comment by lemoinem** [comment]
@enumag Could you rename the Lazy* Tests to mention LazyListener instead of Services?

Status: Needs work

**Comment by enumag** [comment]
@lemoinem There is nothing lazy about the listener, just the evm/evd is lazy. So I'll just rename `$service` to `$listener`.

**Comment by lemoinem** [comment]
Yes, but it is lazyily loaded. My point is, tests for the lazy evm/evd do not deal with services but lazily built/loaded listeners, so I think the test names should reflect that.

**Comment by enumag** [comment]
@lemoinem Like this?

Status: Needs Review

**Comment by lemoinem** [comment]
PS: Same goes for the code in the Lazy evm/evd. It is still referring to services at several points. If you think it'd help, I could go through the code and try to add a line comment to each of them.

**Comment by lemoinem** [comment]
Yes, I noticed this afterward. Since the Lazy evm/evd only takes a closure to lazily load the listeners, I don't think it should refer to services at all... What do you think?

**Comment by enumag** [comment]
@lemoinem I agree but since there is "service" in the method names I can't change it because of BC.

**Comment by lemoinem** [comment]
Why not introduce new methods in the new class and keep (depreciate?) the current methods in the current class? The other way around would be to introduce an interface similar to [PSR11's ContainerInterface](https://github.com/container-interop/fig-standards/blob/master/proposed/container.md#21-psrcontainercontainerinterface) within the component and make Symfony's ContainerInterface extend it... But I'm not sure it would still solve your problem...

**Comment by enumag** [comment]
I don't think introducing new methods is a good idea. I mean even in my case I'll still use DI container with services, just a different implementation.

PSR11 unfortunately isn't acccepted yet and creating something similar doesn't have a chance to be merged.

**Comment by lemoinem** [comment]
OK, Then I guess keeping the current code will be good enough... Thanks.
Status: Reviewed

**Comment by enumag** [comment]
Anything else?

**Comment by enumag** [comment]
@fabpot What do you think about this one?

**Comment by enumag** [comment]
ping @fabpot

**Comment by fabpot** [comment]
We are in a code freeze, so any new feature will be consider after the release of 3.2.

**Comment by enumag** [comment]
@fabpot There is a separate 3.2 branch now. I'm guessing that fulfills the requirement?

**Comment by stof** [comment]
I'm quite -1 for adding the integration between nette/di and doctrine/common in our doctrine bridge. Our bridges are meant to provide integration between Symfony and external libraries, not between 2 libraries outside Symfony.

If you want to have a shared LazyEventManager somewhere, you should submit it to doctrine/common, not to Symfony.

**Comment by enumag** [comment]
@stof That's a good point! Yeah I should try and push it to doctrine/common. Here are some questions for you:

- Can I use the implementation and tests from Symfony? What should I do with the copyright? If I can use the existing Symfony code as a base I'll gladly create such pull request to doctrine/common.
- What do you think about the LazyEventDispatcher?

**Comment by enumag** [comment]
ping @stof @fabpot

**Comment by nicolas-grekas** [comment]
For the LazyEventDispatcher, WDYT of #20875 instead?

**Comment by nicolas-grekas** [comment]
Since we're going to deprecate ContainerAwareEventDispatcher, I think this PR will be obsoleted by either #20953 or #20875.

**Comment by fabpot** [comment]
Closing as we are working on a more generic way to solve this problem as mentioned by @nicolas-grekas

**Comment by enumag** [comment]
@fabpot @stof The LazyEventManager is still needed. I understand why you don't want it in Symfony though. Can I use the ContainerAwareEventManager implementation and tests as a base for a pull request to doctrine/common? What should I do with the copyright?

**Comment by sstok** [comment]
@enumag Make sure to keep the author's intact and you can propose this to the Doctrine project 👍  both are MIT licensed, so this shouldn't be a problem.

Make sure to link this pull request so they can decide if this acceptable.

**Comment by enumag** [comment]
@sstok Thanks, I'll look into it when I have some time.

**Pull request closed without merging**
