### PR TITLE
[Messenger] Add AvailableAtStamp to delay messages until fixed DateTime

### PR DESCRIPTION
**Pull request by delolmo**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

An AvailableAtStamp and an AvailableAtStampMiddleware have been added to allow posponing a message to a fixed date and time. Internally, the middleware calculates the difference in milliseconds between the desired date and the current date and adds a DelayStamp to the envelope.

### CODE REVIEW

**Comment by delolmo** [comment]
I have given more thought to this PR and I would like two things to be discussed.

1) Calculating the amount of seconds between two dates is apparently easy, but if we are dealing with a timezone with a daylight saving time period, a +/- 1 hour difference will appear if the availableAt DateTime changes between daylight saving period and non-daylight saving period. I am no expert managing date and time functions, but could this be a solution to the problem (basically, comparing dates in UTC timezone)?

```php
            $availableAt = new DateTime(
                $availableAtStamp
                    ->getAvailableAt()
                    ->format('Y-m-d H:i:s'),
                $timezone
            );

            $now = new DateTime(
                (new DateTime())
                    ->format('Y-m-d H:i:s'),
                $timezone
            );

            $delay = $availableAt->getTimestamp() - $now->getTimestamp();
```

2) If an AvailableAtStamp is included, the default Serializer created by the Serializer Transport will now fail when trying to denormalize the DateTime object. The `Symfony\Component\Serializer\Normalizer\DateTimeNormalizer` should be added in the `public static function create(): self` method of the Serializer Transport, especially if this stamp is provided as a core function in the Messenger component. Would this be fine?

**Comment by fabpot** [comment]
What's the status here?

It looks like there is an unrelated commit.

**Comment by ogizanagi** [comment]
Can't we add a `DelayStamp::to(\DateTime $datetime)` helper instead of a new stamp+middleware?

**Comment by maxhelias** [comment]
> Can't we add a `DelayStamp::to(\DateTime $datetime): DelayStamp` helper instead of a new stamp+middleware?

@ogizanagi I agree, it could be a really good idea

**Comment by fabpot** [comment]
I like @ogizanagi idea.

**Comment by weaverryan** [comment]
> Can't we add a DelayStamp::to(\DateTime $datetime): DelayStamp helper instead of a new stamp+middleware?

I was thinking the same! Maybe `DelayStamp::delayUntil()`?

**Comment by fabpot** [comment]
We've just moved away from `master` as the main branch to use `5.x` instead. Unfortunately, I cannot reopen the PR and change the target branch to `5.x`. Can you open a new PR referencing this one to not loose the discussion? Thank you for your understanding and for your help.

**Comment by Aerendir** [comment]
As linked by @maxhelias , I've just proposed the exact same thing in https://github.com/symfony/symfony/issues/38459 (sorry for the duplication)...

~Please, read my issue as there are some useful inspiration, I think...~
Please, read also this comment, because it has some details that maybe of inspiration: https://github.com/symfony/symfony/issues/38463#issue-716656714

**Comment by Aerendir** [comment]
I've send a new PR: https://github.com/symfony/symfony/pull/38480

**Pull request closed without merging**
