### PR TITLE
[DependencyInjection] properly fix tests on PHP 5

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
Nothing to worry about. :) Just by reading the code I also don't see where the test would be skipped on PHP 5.5. But we seem to miss something as the test apparently passes right now. :)

**Comment by przemyslaw-bogusz** [comment]
As I understand this PR was about fixing tests due to the fact, that Symfony 3.4 can run on PHP 5, which means that tests from branch 3.4 should take into account, that return type declarations were introduced in PHP 7.

I thought that was why the test failed, as it hinted at `:` from the return type declaration.
https://github.com/symfony/symfony/blob/db6784bb095de2c6ef0ab424efd5b06e71e3feef/src/Symfony/Component/DependencyInjection/Tests/Fixtures/FactoryDummy.php#L16-L18

But now, since suddenly the Travis CI test passes, I'm confused.

**Comment by xabbuh** [comment]
@przemyslaw-bogusz looks reasonable to me, could you do the PR?

**Comment by przemyslaw-bogusz** [comment]
@xabbuh I will do the PR

**Comment by przemyslaw-bogusz** [comment]
@xabbuh Could you please enlighten with one more thing? Since the problem resolves around using return type declarations in PHP 5 test environment, for the CI test to fail, it's enough that **FactoryReturnTypePassTest** has a `use Symfony\Component\DependencyInjection\Tests\Fixtures\FactoryDummy;`, which loads a class with a syntax error. Why Travis CI tests with PHP 5 for other PRs pass? Does it mean that not all PHPUnit tests are run on each PR?

**Pull request merged**
