### PR TITLE
Added missing Uzbek translations

### LINKED ISSUE #51962: Missing translations for Uzbek (uz)
Hello,

There are some missing translation for Uzbek (uz). These should be added in branch 5.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Validator/Resources/translations/validators.uz.xlf](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Resources/translations/validators.uz.xlf)

> [!NOTE]
> If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by asrorbekh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #51962
| License       | MIT

Added missing translations (translation units 104-109) and fixed some translations in previous units.

### CODE REVIEW

**Comment by lyrixx** [comment]
@asrorbekh hello. 

Thanks for your first contribution 🎉 

But it looks like you based your patch on the wrong branch. Could you check it please?

If you need help, just tell me, and I could clean the git history with only this commit https://github.com/symfony/symfony/pull/52168/commits/b0eef79c38a1787052f2f157bab05b43be2b3e62 (BTW, `true` and `false` seems suspicious on this commit)

**Comment by asrorbekh** [comment]
> @asrorbekh hello.
> 
> Thanks for your first contribution 🎉
> 
> But it looks like you based your patch on the wrong branch. Could you check it please?
> 
> If you need help, just tell me, and I could clean the git history with only this commit [b0eef79](https://github.com/symfony/symfony/commit/b0eef79c38a1787052f2f157bab05b43be2b3e62) (BTW, `true` and `false` seems suspicious on this commit)

Yes @lyrixx bro. I merged 6.4 to contribute-patch by mistake so sorry. How can i update it 5.4 to current patch or should i start over by merging 5.4 to my own patch? The true and false are technical words releated to programming, that's why i changed it  to make it understanable for developers!

**Comment by lyrixx** [comment]
I have the current setup
```
>…regoire/dev/github.com/lyrixx/symfony(sanitizer-no-limit) git remote -v
origin  git@github.com:lyrixx/symfony.git (fetch)
origin  git@github.com:lyrixx/symfony.git (push)
upstream        git@github.com:symfony/symfony (fetch)
upstream        git@github.com:symfony/symfony (push)
```

so when I need to fix my history, I usually do that:

1. copy the SHA I want to keep b0eef79c38a1787052f2f157bab05b43be2b3e62
2. `git reset --hard upstream/5.4`
3. git cherry-pick b0eef79c38a1787052f2f157bab05b43be2b3e62
4. git push -f

**Comment by asrorbekh** [comment]
> I have the current setup
> 
> ```
> >…regoire/dev/github.com/lyrixx/symfony(sanitizer-no-limit) git remote -v
> origin  git@github.com:lyrixx/symfony.git (fetch)
> origin  git@github.com:lyrixx/symfony.git (push)
> upstream        git@github.com:symfony/symfony (fetch)
> upstream        git@github.com:symfony/symfony (push)
> ```
> 
> so when I need to fix my history, I usually do that:
> 
> 1. copy the SHA I want to keep [b0eef79](https://github.com/symfony/symfony/commit/b0eef79c38a1787052f2f157bab05b43be2b3e62)
> 2. `git reset --hard upstream/5.4`
> 3. git cherry-pick [b0eef79](https://github.com/symfony/symfony/commit/b0eef79c38a1787052f2f157bab05b43be2b3e62)
> 4. git push -f

I apologize for the confusion. I mistakenly merged the wrong branch into the old branch. To rectify this, I have opened a new pull request with the correct changes in https://github.com/symfony/symfony/pull/52175

Thank you for your understanding.

**Pull request closed without merging**
