### PR TITLE
[Console] Constant STDOUT might be undefined

### LINKED ISSUE #34341: [Console] Use of undefined constant STDOUT
**Symfony version(s) affected**: 4.3.7

**Description**  
The latest update of Symfony Console 4.3.7 errors when calling an artisan command from a controller in Laravel with the following error message "ErrorException
Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP)".

See attached image.
Screenshot_2019-11-12 🧨 Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version

**How to reproduce**  
Windows Server 2016
IIS 10
PHP 7.3.11
Laravel 6.X
Laravel 5.8
Run an artisan command in Laravel from a controller.

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34341
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by nicolas-grekas — COMMENTED** [review]
fopen('php://stdout', 'w')?

**Comment by derrabus** [comment]
> fopen('php://stdout', 'w')?

Would be overkill here. The constant is defined by the CLI SAPI. Thus, if the constant is not there, we're not on CLI, thus we're not on a terminal with VT100 support.

We already have a similar check in PhpUnitBridge:

https://github.com/symfony/symfony/blob/fb4065ac95f08ca26ee605936e537ba2cd4a6bb7/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L355-L357

**Comment by nicolas-grekas** [comment]
I'm not sure I agree. If the check targets the sapi, let's make it crystal clear. Checks for color support all use php://stdout. STDOUT is not used anywhere else in the codebase as far as I checked. I think we should check what we want to check in a portable way, using php://stdout Sorry my previous comment was too laconic.

**Comment by derrabus** [comment]
> STDOUT is not used anywhere else in the codebase as far as I checked.

Well yes, the method I've linked in my previous comment uses the constant to check for color support as well.

https://github.com/symfony/symfony/blob/fb4065ac95f08ca26ee605936e537ba2cd4a6bb7/src/Symfony/Bridge/PhpUnit/DeprecationErrorHandler.php#L353-L383

Also, I wouldn't want to change the way stdout is accessed without a Windows machine to test on. 😕

**Comment by nicolas-grekas** [comment]
That's the bridge, it's not a piece of reusability, it's a tool :)
No worries about php://stdout, it does the very same job.

**Comment by derrabus** [comment]
All right, here you go.

@lazosweb Can you please test again? Sorry for the hassle. 😃

**Comment by lazosweb** [comment]
@derrabus . All good. No issue. That will work too.

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Should be merged after #34346 and rebased on 3.4.

**Comment by derrabus** [comment]
> Should be merged after #34346 and rebased on 3.4.

@chalasr Feel free to squash my change into your PR. I don't think, we need to backport a buggy solution first. 😉

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @derrabus

**Pull request merged**
