### PR TITLE
[Form] fix tests added by #16886

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Branch | 2.7+ |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16886 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by HeahDude** [comment]
Feel free to close this one in favor of an alternative by @boite if any.

**Comment by boite** [comment]
Thanks @HeahDude I'll look these over and make sure they agree with some recent changes to the placeholder normalizer.

**Comment by HeahDude** [comment]
Yes I've already changed some assertions to take that into account ;)

**Comment by boite** [comment]
:+1: Good work @HeahDude. 

What was your reason for removing the final three tests in the single, expanded, required section?

Status: Reviewed

**Comment by HeahDude** [comment]
@boite Because when `ChoiceType` expanded and required never has a placeholder.

see https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php#L356

**Comment by HeahDude** [comment]
Note to merger : only 2.x branches.

**Comment by boite** [comment]
I suppose that if that code is unlikely to change then there's no harm in having removed the tests.

**Comment by boite** [comment]
Branches 2.7 and 2.8 only.

**Comment by HeahDude** [comment]
yes, this precision was in the description ;)

**Comment by webmozart** [comment]
Thanks for this PR @HeahDude :) What about the failing tests in the PHP 7 build?

**Comment by HeahDude** [comment]
@webmozart I know I still miss to understand.

It's like the PHP 7 build of travis does not take into account commits of #17568 and #17973.

Any lead ?

**Comment by fabpot** [comment]
@HeahDude That's because the tests use the form component from v2.7.10, which does not include the two PRs you mention.

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Comment by HeahDude** [comment]
Thanks @fabpot for your explanation :)

**Pull request merged**
