### PR TITLE
Use DI exceptions in components compiler passes

### PR DESCRIPTION
**Pull request by chalasr**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| License | MIT |

### CODE REVIEW

**Comment by sstok** [comment]
LGTM 👍

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by chalasr** [comment]
Rebased after #19842

**Comment by fabpot** [comment]
This one is for master

**Comment by chalasr** [comment]
Messed up git (0 commit => closed)
See #19875

**Pull request closed without merging**
