### PR TITLE
Subarray of sequential array must be inline in Yaml

### PR DESCRIPTION
**Pull request by JJarrie**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no    
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Hello,

As I investigated [this issue](https://github.com/symfony/maker-bundle/issues/396), I noticed this rule which seems to me implicit to avoid generation like

```yaml
foo:
    -
        bar: baz
        qux: quux
```

Instead of

```yaml
foo:
    - { bar: baz, qux: quux }
```

Here is the most surgicals changes to obtain the expected result without breaking the existing output.

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you explain why you think that the mapping should be dumped inline?

**Comment by JJarrie** [comment]
I think that the mapping should be dumped inline when it is into array for most reasons :

1/ Readibility : the generation exemple I have post is not really an exemple of good organization of code, particularly for a configuration. At least the carriage is too much.

2/ Documentation: I haven't look for a while into documentation an example who give the multiline syntax.

3/ Seem Symfony's standard : In the whole project, except few files into tests, the inline syntax is used.

4/ Usage: With this update, this is quick and easy to fix the linked issue and enhance the Authenticator Make, I think few others Maker will generate configuration's files with this syntax.

This is my opinion, sorry if I'm on the wrong way.

**Comment by fabpot** [comment]
Not sure I agree with the changes, but as this is not a bug fix, it should target 4.4. /cc @xabbuh

**Review by nicolas-grekas — APPROVED** [review]
makes sense to me

**Comment by xabbuh** [comment]
I am mixed here. I could imagine other users complaining about this change if they like the previous behaviour especially since you could get the output desired by this PR by changing the inline argument, right?

**Comment by stof** [comment]
If the values in the subarray are more complex (nested arrays), the readability argument would precisely reject your change. So I'm also mixed here.

**Comment by fabpot** [comment]
Let's close as 3 core team members are not convinced that the changes are worth it.

**Pull request closed without merging**
