### PR TITLE
Minor cleanups and improvements

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Is it for 2.7 or master?

**Comment by nicolas-grekas** [comment]
2.7 to me, these are only private things

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
