### PR TITLE
Add Estonian (et) translations

### LINKED ISSUE #38738: Missing translations for Estonian (et)
Hello,

There are some missing translation for Estonian (et). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.et.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.et.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.et.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.et.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.et.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.et.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by hluup**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38738
| License       | MIT
| Doc PR        | N/A

Added new translations and made few small updates to couple of existing ones.

### CODE REVIEW

**Comment by hluup** [comment]
Closing as requested.

**Comment by wouterj** [comment]
Hi @hluup. Thanks for this contribution. I think it's OK to leave this open, but without the draft status.
It's already great to have some messages translated already, you don't have to do all of them in a single PR.

**Comment by Nyholm** [comment]
Awesome! 
Thank you @hluup for working on this.

**Comment by hluup** [comment]
Everything should be translated now.

**Review by javiereguiluz — APPROVED** [review]
👍  Validated with Google Translate

Thanks Hendrik!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @hluup.

**Pull request merged**
