### PR TITLE
Create security.lv.xlf to translate security messages to Latvian.

### PR DESCRIPTION
**Pull request by Rikijs**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #19919 |
| License | MIT |
| Doc PR | reference to the documentation PR, if any |

Security component messages translation to Latvian.

### CODE REVIEW

**Comment by fabpot** [comment]
Something went wrong when you submitted this PR. Can you submit a PR on Symfony 2.7 with all translations, even those not related to 2.7? That makes merging much easier and that's what we are doing for other translations. Thank you.

**Comment by Rikijs** [comment]
Can You please clarify what you mean by "...with all translations, even those not related to 2.7?"
Do You mean all translations of security component's messages in Symfony 3.1?
(Excuse me if I am doing something wrong I just started use GIT.)

**Comment by fabpot** [comment]
Indeed, I mean messages introduced in later versions and not useful in 2.7. Also, there are several files that need to be translated, not just the security one.

**Comment by Rikijs** [comment]
I searched for translatable files and I found several locations:
- [1] Symfony\src\Symfony\Component\Validator\Resources\translations
- [2] Symfony\src\Symfony\Component\Security\Resources\translations
- [3] Symfony\src\Symfony\Component\Security\Core\Resources\translations
- [4] Symfony\src\Symfony\Component\Form\Resources\translations

Latvian translation is missing in [1], [2] and [3].
[2] location is actually deprecated

**Comment by fabpot** [comment]
@Rikijs You're right. Can you provide translations for everything and for the 2.7 branch? I'm closing this one in the meantime as it is borked now.

**Pull request closed without merging**
