### PR TITLE
[Serializer] Refactoring of metadata

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no (the metadata system will be introduced in 2.7) |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |
- Add an interface for `ClassMetadata` and `ClassMetadataFactory`
- Add a new `AttributeMetadata` and the corresponding interface to ease add of future features (e.g. type support for deserialization) and to allow custom metadata implementations (e.g. description of an attribute for an hypermedia normalizer - my use case)
- Add tests for news features
- Add new tests for exsiting features

### CODE REVIEW

**Comment by dunglas** [comment]
The Travis error isn't related with this PR.

**Comment by dunglas** [comment]
Rebased.

**Comment by dunglas** [comment]
ping @symfony/deciders

**Comment by dunglas** [comment]
ping @symfony/deciders

**Comment by lsmith77** [comment]
i wonder if the handling for different formats could be made more generic, ie. into a component of its own. @schmittjoh also created a lib for this once upon a time.

**Comment by dunglas** [comment]
@lsmith77 the two way have their advantages. Here having a single `AttributeMetadata` gathering data both from properties and accessor methods make sense IMO: they match the structure of the serialized document and allows to keep the code clean and simple.

However, maybe some formats loaders related code from Serializer, Validator, Routing and Config can be merged (but not especially metadata). cc @webmozart @Tobion @fabpot @stof.

**Comment by fabpot** [comment]
The loaders for the DIC and the Routing for instance share code (to be found in Config). I don't know if it would be worth it to go further down this road. Anyway, I think that's something that should be discussed independently of this PR.

**Comment by lsmith77** [comment]
yeah .. its certainly beyond the scope of this PR

**Comment by lsmith77** [comment]
BTW for the record I am talking about https://github.com/schmittjoh/metadata

**Comment by dunglas** [comment]
@lsmith77 can I merge this PR or do you think this issue is blocking?

**Comment by lsmith77** [comment]
no. this was more a forward thinking point i made

**Comment by lsmith77** [comment]
so merge :)

**Pull request merged**
