### PR TITLE
[FWBundle] Remove error_renderer.serializer if the Serializer isn't available

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

(Should help for https://github.com/hautelook/AliceBundle/pull/485).

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by yceruto** [comment]
We already have TwigErrorRenderer into TwigBridge, what about move the `SerializerErrorRenderer` + definition to the Serializer component instead?

**Comment by dunglas** [comment]
Good idea @yceruto, done

**Review by ogizanagi — APPROVED** [review]

**Comment by yceruto** [comment]
Could we move the `SerializerErrorRenderer` class too? or it's too late :( ?

**Comment by yceruto** [comment]
I was wondering if we could make these error renderers `@experimental` or `@internal` ... ?

**Comment by nicolas-grekas** [comment]
> I was wondering if we could make these error renderers `@experimental` or `@internal` ... ?

internal: no, api platform uses it
experimental: no, that's 4.4

> Could we move the SerializerErrorRenderer class too? or it's too late :( ?

I think we still can, wdyt @dunglas ?

**Comment by nicolas-grekas** [comment]
Thank you @dunglas.

**Comment by dunglas** [comment]
Yes we can, even if it's technically a BC break.

**Pull request merged**
