### PR TITLE
[HttpFoundation] update changelog

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20569
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by fabpot** [comment]
Question about those CHANGELOG: are they worth it?

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by lyrixx** [comment]
> Question about those CHANGELOG: are they worth it?

For what it worth: I never used them.

**Comment by xabbuh** [comment]
> Question about those CHANGELOG: are they worth it?

Not sure, but people complained about missing entries in the past. I think we should at least be consistent (either add all new features or completely remove the changelogs).

**Comment by juuuuuu** [comment]
> Question about those CHANGELOG: are they worth it?

_Auto-generated_ CHANGELOG are useless. It's hard to read and to extract useful information from it.

**Comment by romainneutron** [comment]
@fabpot it would be nice. When I do a `composer up` and use a new version, I'm usually looking for this CHANGELOG to read BC break, changes and new features. 
I agree with @juuuuuu, auto-generated one are useless. However, well documented ones are priceless when upgrading packages regularly

**Comment by ro0NL** [comment]
@xabbuh nice one. Perhaps it's worth clarifying this is about `Symfony\Component\HttpFoundation\Cookie`.. as we have 2 ;-) (`Symfony\Component\BrowserKit\Cookie`).

If we add `Symfony\Component\BrowserKit\Cookie::fromString` we're good as well :+1:

**Comment by xabbuh** [comment]
@ro0NL But this is the changelog of the HttpFoundation component. :)

**Comment by ro0NL** [comment]
You're right.. my bad :)

**Pull request merged**
