### PR TITLE
Simplified the template for pull requests

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

We don't need this information because we use Travis CI and AppVeyor.

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
It was done on purpose. The goal is for people to run as least part of the tests before submitting changes. :-1:

**Comment by javiereguiluz** [comment]
OK. It makes sense as an incentive to run tests. Closing it.

**Comment by Tobion** [comment]
The same is true for `BC breaks?` question. It usually cannot be true (only once every two years basically). But it makes people think about whether their PR may break BC.

**Pull request closed without merging**
