### PR TITLE
[FrameworkBundle] Fix Form conflict rule

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Fixes https://travis-ci.org/symfony/symfony/jobs/270430600#L2628.
/cc @ogizanagi @yceruto

### CODE REVIEW

**Comment by ogizanagi** [comment]
The conflict rule is not needed, dev-dependencies are installed for testing the FrameworkBundle, and the min version already is set to `^3.4`.
I think the issue comes from the fact packagist is only seeing 0898e9f01e1dedc70fb4f77b594227619d7e1711 [as last commit on `symfony/form:master`](https://packagist.org/packages/symfony/form#dev-master), hence the command is not available yet.
But 3.4 has properly been merged on master though: https://github.com/symfony/form/commits/master

**Comment by nicolas-grekas** [comment]
see #086e457eebba77d45bd0e69fbf215f629a943cdb
would be great to fix master now :)

**Comment by chalasr** [comment]
@nicolas-grekas nice catch. I'll look at master tomorrow if @yceruto can't before

**Comment by ogizanagi** [comment]
Re-opening this one, as the conflict rule looks legit to me though: We don't do a `class_exists` check on `DebugCommand` which is only available as of `symfony/form` 3.3. So Using FrameworkBundle 3.4+ with `symfony/form` 3.3 will raise a:

> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DebugCommand" from namespace "Symfony\Component\Form\Command".

We can tweak the FrameworkExtension, but I think we're already used to bump the min-version by adding a conflict rule in such cases in the FrameworkBundle.

**Comment by chalasr** [comment]
Agree (my own PR but it was not intended for that).

**Review by xabbuh — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @chalasr.

**Pull request merged**
