### PR TITLE
Remove root v3 CHANGELOG and UPGRADE files

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.0
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Just curious why?

**Comment by nicolas-grekas** [comment]
Because the v4 code base doesn't need instructions about v3.
See 3.0, we did the same then.

**Comment by TomasVotruba** [comment]
I see. I though whole instructions would be removed.

Is there any link to the one past version? I didn't know there where any 2.x upgrades. There are usually all or none in the repo.

**Comment by nicolas-grekas** [comment]
Like https://github.com/symfony/symfony/tree/3.0?

**Comment by TomasVotruba** [comment]
Yep, it should be in v4 Readme, so people always find way to upgrades. Most of them will look for these files while v4 would be on master by default

**Pull request merged**
