### PR TITLE
[Security] Login: Only use referer URL if it differs from default login_path

### PR DESCRIPTION
**Pull request by keichinger**
| Q             | A
| ------------- | ---
| Branch?       | 3.4 
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | yes
| Deprecations? |no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

This PR fixes a strange behaviour by the `use_referer` logic inside the `DefaultAuthenticationSuccessHandler` inside the security component.

When `use_referer` is enabled in your `security.yml` for a given `firewall` like so:

```yaml
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path:          login
                check_path:          login_check
                default_target_path: admin
                username_parameter:  "login[username]"
                password_parameter:  "login[password]"
                csrf_parameter:      "login[_token]"
                csrf_token_id:       authenticate
                remember_me:         true
                use_referer:         true
```

And then follow the given workflow:

- Visit `/admin/login/`
- Enter credentials
- Get redirected to `/admin/login/` again with no message or whatsoever

But now if you follow the regular/normal workflow:

- Visit `/admin/`
- Get redirected to `/admin/login`
- Enter credentials
- Get redirected to `/admin/` and enjoy your website

The cause for this behaviour was the introduction of `parse_url` to `$targetUrl` in `DefaultAuthenticationSuccessHandler`'s `determineTargetUrl` in https://github.com/symfony/symfony/commit/ac9d75a09ef7ebd7776bc610f8799f92562dfd83#diff-a654f85d03c2e834cb8701bec08e2a4fR125. The code itself was testing a relative path against an absolute URL (e.g. `/admin/login/` vs. `http://domain.com/admin/login/`).

### CODE REVIEW

**Comment by apfelbox** [comment]
The problem with the referrer redirection is that if you somehow land on the login screen after a **succesful**  login, you (and the user) have no way to know whether the login succeeded as the login page is normally excluded from the firewall.

So big 👍  as we were just bitten by this bug where the client suddenly wasn't able to login anymore. This is especially painful, if the client sets a bookmark on the login page.

**Comment by apfelbox** [comment]
Build errors are unrelated.

**Comment by wcluijt** [comment]
Related to https://github.com/symfony/symfony/pull/23061

**Comment by fabpot** [comment]
Fix in 19026 is wrong. So, instead, I've submitted #23580, which fixed the issue in 2.7 as a bug fix. When merged up to master, that would fix the issue in 3.3 as well. Closing in favor of #23580.

**Comment by cH40z-Lord** [comment]
Thank you :)

**Pull request closed without merging**
