### PR TITLE
[PhpUnitBridge] bump "php" to 7.1+ and "phpunit" to 7.5+

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Now that we don't maintain any branch with PHP < 7.1, we can drop support for older PHP and phpunit versions from the bridge \o/

### CODE REVIEW

**Comment by derrabus** [comment]
I'd really love to do that, but the bridge is also used by projects outside of the Symfony org. Those projects would be locked in on 5.2 then.

**Comment by nicolas-grekas** [comment]
Yes, but we never promised anything past our LTS versions. Having the bridge out of sync is a pain. We need to make our lives simpler from time to time, this is now :)

**Review by ogizanagi — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Review by chalasr — APPROVED** [review]
🍾

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
