### PR TITLE
Remove Serializable implementations

### LINKED ISSUE #41094: Phase out Serializable
**Description**
Due to its broken behavior, PHP is phasing out the `Serializable` interface currently.

See:
* https://wiki.php.net/rfc/custom_object_serialization
* https://wiki.php.net/rfc/phase_out_serializable

The replacement are the magic methods `__serialize()` and `__unserialize()` that have been introduced with PHP 7.4. As long as our implementations of `Serializable` also implement those methods, PHP 8.1 won't throw deprecation notices at us. As far as I can tell, we're safe here.

For Symfony 6, we decided to not provide support for PHP 7 anymore. This also means that we don't need `Serializable` as a BC layer for PHP 7.3 and below anymore. Because of that, I'd like to propose to remove that interface from all Symfony classes in 6.0.

Affected by this change:

* Mime: `RawMessage` (the implementation of the interface is finalized and flagged `@internal`)
* Routing: `CompiledRoute` and `Route` both implement the interface with `@internal` and `final`.
* Security Core:
    * `TokenInterface` extends `Serializable` but also requires `__serialize()` and `__unserialize()` to be implemented.
    * `AbstractToken` provides an implementation that is again `@internal` and `final`.
    * `NullToken` implements `Serializable` *without* `@internal` and `final`.

Question now is: Do we need any additional deprecation layer for 5.4 or would it be okay to simply unannounce the interface and remove the implementations?

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41094
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
> SwitchUserToken has no unserializer

test failure look related

**Comment by derrabus** [comment]
It is indeed.

The failing test checks if a `SwitchUserToken` that has been serialized with Symfony 4.4 and PHP 7.2 (I think) can still be unserialized. This does not work anymore because on PHP 7.2, the `Serializable` interface is used and if we remove that interface, PHP does not know how to unserialize the data. The test will fail again if we remove the deprecated `User` class because the serialized fixture uses it.

I think, the gap is too large here. I would not expect that I can jump from Symfony 4.4 and PHP 7.2 to Symfony 6.0 and PHP 8.0 directly and resume old sessions.

I would regenerate the fixture with `InMemoryUser` on Symfony 5.3 and PHP 8 and update the test accordingly. Would that be okay?

**Comment by derrabus** [comment]
🤔 Let's get that deprecated user out of that fixture first. #41385

**Comment by derrabus** [comment]
Now that the deprecated fixture is out of the way, I could regenerate the fixture on PHP 8. This way, an app could still jump from Symfony 4.4 to 6.0 directly, if PHP is not upgraded at the same time. I'm going to document this is the upgrade notes.

**Comment by nicolas-grekas** [comment]
> Route has no unserializer

one more :)

**Comment by derrabus** [comment]
> one more :)

Fixed. I regenerated the fixture with Symfony 4.4 and PHP 8:

```php
$newFixture = serialize(unserialize($oldFixture));
```

What is the use-case for serializing routes? I'd like to write an upgrade note here as well.

**Comment by nicolas-grekas** [comment]
I think Drupal stores the routes in the DB.

**Comment by derrabus** [comment]
Oh, I see. In that case, Drupal needs to provide a way to migrate database tables storing serialized routes after a PHP upgrade (if that does not happen already), ideally before they release a version with Symfony 6 support. Is there someone we can contact about that?

**Comment by nicolas-grekas** [comment]
As discussed in https://github.com/symfony/symfony/issues/41094#issuecomment-847242634, we should keep the interface on implementations (not on interfaces), but they should be final and internal, and only unserialize() should have an implementation: serialize() should throw a BadMethodCall instead

**Comment by nicolas-grekas** [comment]
Thank you @derrabus.

**Comment by derrabus** [comment]
Thank you for resuming my work. 🙂

**Pull request merged**
