### PR TITLE
[Console] added possibility to choose right answers for a ConfirmationQuestion

### PR DESCRIPTION
**Pull request by AlexDpy**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

With this pull request, the ConfirmationQuestion can accept one (or many) answer(s) like 'o', 'oui' (in french) or 'si' (in spanish) or anything else, it's up to you !
Default value is still 'y' (yes)

### CODE REVIEW

**Comment by AlexDpy** [comment]
@symfony/deciders All is ok ?

**Comment by fabpot** [comment]
Looks like a duplicate of #11129 (@WouterJ)

**Comment by fabpot** [comment]
Closing as a duplicate of #11129

**Comment by fabpot** [comment]
@AlexDpy Thank you for you pull request, sorry that there was another one created not too long ago.

**Comment by AlexDpy** [comment]
Thank you for merging the other one and sorry for this duplicate

**Pull request closed without merging**
