### PR TITLE
[TwigBridge] account for the short array syntax in Twig

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
see also twigphp/Twig#2796

**Comment by fabpot** [comment]
I would only change the generated code as changing the PHP code should be done globally.

**Comment by xabbuh** [comment]
I thought the reasoning was in fact to do this step by step (see #29811)?

**Comment by fabpot** [comment]
For new code, yes, but not for existing code (to avoid too many issues when merging up).

**Review by javiereguiluz — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Pull request merged**
