### PR TITLE
[Cache] PDO-based cache pool table autocreation does not work

### PR DESCRIPTION
**Pull request by errogaht**
look at https://github.com/symfony/symfony/issues/29898
I believe that it is not good fix... But pgsq table not foutd throwed right there, in execute(). Dont know about another DB drivers, and i dont know will execute() again work or not, please if some one know more about PDO than me, check it!

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29898 
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Hi @errogaht thanks for the PR, it looks good to me.
Could you please rebase+retarget branch 4.2?
You'll also need to fix the short array syntax we're using now.

**Comment by nicolas-grekas** [comment]
Thank you @errogaht.

**Comment by nicolas-grekas** [comment]
Actually, some db engine (eg sqlite) check table existency at prepare time, as spotted by the CI. I'm adding back the remove code.

**Comment by errogaht** [comment]
@nicolas-grekas fixed, please check https://github.com/symfony/symfony/pull/30005

**Pull request merged**
