### PR TITLE
TemplateReference::__set_state for var_export support

### PR DESCRIPTION
**Pull request by vudaltsov**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by fabpot** [comment]
Can you tell us a bit more about this change? Why is it useful? Which problem does it solve?

**Comment by vudaltsov** [comment]
Sure. This is useful for example when passing template reference as a route default in loader. Since routing cache serializes everything by var_export, TemplateReference throws an exception.

**Comment by fabpot** [comment]
Instead of passing a template reference, you should pass the template name instead (or cast the reference to a string).

**Comment by vudaltsov** [comment]
Ok, I agree. Thank you!

**Pull request closed without merging**
