### PR TITLE
[VarDumper] Improve dump of AMQP* Object

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

---

The release of https://github.com/pdezwart/php-amqp/ 1.7.0alpha1
changed internally the handling of AMQP* object. So now when dumping
using var_dump(), many information are available. So many information
are displayed twice. This commit fixes this issue and keeps displaying basic
information for older versions of the lib.

Reference:

* https://pecl.php.net/package-info.php?package=amqp&version=1.7.0alpha1
* https://github.com/pdezwart/php-amqp/commit/314afbc (and next commits)

---

screenshot4

screenshot5

### CODE REVIEW

**Comment by stof** [comment]
shouldn't we rather avoid all the useless info instead of overwriting the existing ones ?

**Comment by lyrixx** [comment]
> shouldn't we rather avoid all the useless info instead of overwriting the existing ones ?

The things is: it's hard to know when property X or property Y has been added in the extension. So If we want to avoid overwriting, we should check for each property if it has been defined before.

WDYT?

**Comment by stof** [comment]
Well, you are switching the prefix globally anyway, which implies that they all changed together.

**Comment by lyrixx** [comment]
Indeed. But anyway `$array  += []` does not overwrite the initial value. So IMHO, it's not an issue. I just specifically, overwrite some properties, to enchance the display.

But just to be sure I understand, you propose something like that:

```php

        // Recent version of the extension already expose internal properties
        if (isset($a["\x00AMQPConnection\x00login"])) {
            $a += [
                Caster::PREFIX_VIRTUAL.'isConnected' => $c->isConnected(),
            ];

            return $a;
        }

        $prefix = Caster::PREFIX_VIRTUAL;

        // BC layer in the amqp lib
        if (method_exists($c, 'getReadTimeout')) {
            $timeout = $c->getReadTimeout();
        } else {
            $timeout = $c->getTimeout();
        }

        $a += array(
            $prefix.'isConnected' => $c->isConnected(),
            $prefix.'login' => $c->getLogin(),
            $prefix.'password' => $c->getPassword(),
            $prefix.'host' => $c->getHost(),
            $prefix.'vhost' => $c->getVhost(),
            $prefix.'port' => $c->getPort(),
            $prefix.'read_timeout' => $timeout,
        );

        return $a;
```

**Comment by lyrixx** [comment]
@stof I updated my PR according to your comments.

**Comment by stof** [comment]
👍 

Btw, don't we need to update some tests ?

**Comment by lyrixx** [comment]
> Btw, don't we need to update some tests ?

This part is not tested... :/

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.

**Pull request merged**
