### PR TITLE
[Inflector] Support pluralization in the inflector

### PR DESCRIPTION
**Pull request by mbabker**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | not yet
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | Not Yet

At present the inflector only supports singularizing plural words, this PR adds the capability to pluralize singular words.

### CODE REVIEW

**Comment by ostrolucky** [comment]
Have you read readme of this component? 
> This component is currently marked as internal. Do not use it in your own code.

I don't see this patch utilized in other components, so why adding unused feature into internal component?

**Comment by mbabker** [comment]
In combination with https://github.com/symfony/symfony/issues/26903 this allows us in Joomla to drop our inflector (which is in essence stable but unmaintained because we just don't have the resources to keep up with it) for something which is better maintained.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mbabker.

**Comment by jewome62** [comment]
After rebase on master, Test suite on Inflector failed : 
Exemple : https://travis-ci.org/symfony/symfony/builds/514143324?utm_source=github_status&utm_medium=notification

**Pull request merged**
