### PR TITLE
[PropertyInfo] Add hassers for accessors prefixes

### PR DESCRIPTION
**Pull request by sebdec**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | None
| License       | MIT
| Doc PR        | -

In the component PropertyInfo
In the class ReflectionExtractor Add hassers in the accessors prefixes

Because I think it's common to have readable properties with method like this: 
hasChildren()

### CODE REVIEW

**Comment by sebdec** [comment]
maybe it can be defined as a bug fix

**Comment by jakzal** [comment]
Would be nice to have it. It's a new feature though.

**Review by fabpot — APPROVED** [review]
for master

**Comment by fabpot** [comment]
Thank you @sebdec.

**Pull request closed without merging**
