### PR TITLE
[Process] Do feat test before enabling TTY mode

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20565
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by mayeco** [comment]
@fabpot this is happening in master

**Comment by xabbuh** [comment]
@mayeco We always merge bugfix in the lowest affected, maintained branch. From there we merge up branches regularly. So each bugfix will end up in master eventually.

**Comment by mayeco** [comment]
@xabbuh Thank you!

**Pull request merged**
