### PR TITLE
[Mailer] fixed destination override by envelope in amazon api transport

### LINKED ISSUE #35037: [Mailer] AWS SES API Transport not always using envelope
**Symfony version(s) affected**: 4.4/5.0

**Description**

The AWS SES API transport implementation for Mailer is not using the recipients set on the envelope in all cases. If an email has attachments the envelope is entirely ignored and the message send in its raw form. In every other case "to" destination is set from the envelope but cc and bcc is still read from the email headers.

**How to reproduce**

Configure the Mailer with AWS API transport (ses+api://AWS_ACCESS_KEY_ID: AWS_SECRET_ACCESS_KEY@default), override the recipients via EnvelopeListener according to the sf docs and send an email with attachment (envelope ignored) or a cc/bcc (to gets rewritten but cc/bcc is still delivered).

**Possible Solution**

Use the AWS SES SendRawEmail endpoint in any case and set the API parameter `Destinations` to override an emails recipient in case the envelop recipient are different from the emails header recipients.

**Additional context**

For us this is kind of critical because we use redirection in a staging environment where the customer is expecting all emails to be redirected while testing his software. We are currently using our own AWS Mailer transport based on the AWS SDK and implemented the mentioned fix and redirects are done reliable. I would be happy to provide a PR with an implementation for the Symfony provided transport.

### PR DESCRIPTION
**Pull request by cfoehrdes**
| Q             | A
| ------------- | ---
| Branch?       | 4.4/5.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #35037
| License       | MIT
| Doc PR        | -

Fixes recipients not being replaced if an email has an attachment and recipients have been set on the envelope. Also ensures recipients from envelope are used as message destination if they differ from the email header recipients. The comparison of the header and envelope recipients ensure the destination is only overridden if required, otherwise the cc/bcc classification would be lost. It is not necessary to have a condition and switching between `SendMail` and `SendRawMail` AWS API endpoints.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you please add a test case?

**Comment by cfoehrdes** [comment]
@nicolas-grekas I could not find any other transport mocking the API they are calling. I wrote a test for normal submission and an envelope example. Happy to hear some feedback.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
I've just read your last comment on the issue and that made me re-read this PR. The difference between the API and HTTP transports is the following (true for all transports): API should use the API abstraction of the transport (the transport is responsible for generating the email as a string). For the HTTPS transport, Symfony is responsible for generating the email as a string.

**Comment by cfoehrdes** [comment]
@fabpot thank you for the clarification. I tried understanding the existing transports and did more local testing. I have a couple of questions to have my PR aligning to the concept:

* I use the `SendRawEmail` API endpoint from AWS (symfony is creating the email string). Should I move everything I did to the HTTPS version of the transport?
This would also fix the issue that the AWS HTTP transport is not using the envelope at all.
* The current AWS API transport is overriding the TO destination using the envelope recipients but still setting original CC/BCC recipients on the api call. (see https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesApiTransport.php#L104-L109)
If you redirect using an `EnvelopeListener` the CC/BCC will still receive an email. Is this intended behaviour or can we change this?
* The current AWS API transport is ignoring the envelope when sending emails with attachments and symfony is creating the email string (see https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Mailer/Bridge/Amazon/Transport/SesApiTransport.php#L90)
Using attachments can not be done when AWS creates the email string. Should we leave the switch from `SendEmail` to `SendRawEmail` in this case but ensure the envelope recipients are set?

**Comment by fabpot** [comment]
I'm wondering it #35992 makes this PR not needed anymore.

**Comment by fabpot** [comment]
Closing as the code changed here is deprecated is favor of new classes.

**Pull request closed without merging**
