### PR TITLE
[Security] Fixed missing badges argument for method authenticateUser

### LINKED ISSUE #40719: Wrong method definition in `UserAuthenticatorInterface` for the new Authenticator-based Security
**Symfony version(s) affected**: 5.2

**Description**
In a feature that was added in the latest release, we have a difference between interface method definition and its implementation. Because of that we lost some data and can not use the feature as expected.

Take a look at the `UserAuthenticatorInterface`. Here we have `authenticateUser` method with 3 parameters.

```php
namespace Symfony\Component\Security\Http\Authentication;

/**
 * @author Wouter de Jong <wouter@wouterj.nl>
 *
 * @experimental in 5.2
 */
interface UserAuthenticatorInterface
{
    /**
     * Convenience method to programmatically login a user and return a
     * Response *if any* for success.
     */
    public function authenticateUser(UserInterface $user, AuthenticatorInterface $authenticator, Request $request): ?Response;
}
```

 This interface has been implemented by two classes: `AuthenticatorManager` and `UserAuthenticator`.

```php
namespace Symfony\Bundle\SecurityBundle\Security;

/**
 * A decorator that delegates all method calls to the authenticator
 * manager of the current firewall.
 *
 * @author Wouter de Jong <wouter@wouterj.nl>
 *
 * @final
 * @experimental in 5.2
 */
class UserAuthenticator implements UserAuthenticatorInterface
{
     public function authenticateUser(UserInterface $user, AuthenticatorInterface $authenticator, Request $request): ?Response
    {
        return $this->getUserAuthenticator()->authenticateUser($user, $authenticator, $request);
    }
}
```

```php
namespace Symfony\Component\Security\Http\Authentication;

/**
 * @author Wouter de Jong <wouter@wouterj.nl>
 * @author Ryan Weaver <ryan@symfonycasts.com>
 * @author Amaury Leroux de Lens <amaury@lerouxdelens.com>
 *
 * @experimental in 5.2
 */
class AuthenticatorManager implements AuthenticatorManagerInterface, UserAuthenticatorInterface
{
     /**
     * @param BadgeInterface[] $badges Optionally, pass some Passport badges to use for the manual login
     */
    public function authenticateUser(UserInterface $user, AuthenticatorInterface $authenticator, Request $request, array $badges = []): ?Response
    {
        // create an authenticated token for the User
        $token = $authenticator->createAuthenticatedToken($passport = new SelfValidatingPassport(new UserBadge($user->getUsername(), function () use ($user) { return $user; }), $badges), $this->firewallName);

        // announce the authenticated token
        $token = $this->eventDispatcher->dispatch(new AuthenticationTokenCreatedEvent($token))->getAuthenticatedToken();

        // authenticate this in the system
        return $this->handleAuthenticationSuccess($token, $passport, $request, $authenticator);
    }
}
```

In the class `AuthenticatorManager`, for this method we have 4 parameters: `UserInterface $user, AuthenticatorInterface $authenticator, Request $request, array $badges = []`. It's ok for PHP, but not for feature purposes. We can not pass the array of `BadgeInterface`'s, because we lost them in the `UserAuthenticator` class. Here we catch only 3 parameters and pass them to the manager.

**Possible Solution**
Can you please add an array of `BadgeInterface` to the `UserAuthenticatorInterface` and make it possible to pass them?

### PR DESCRIPTION
**Pull request by alexandre-daubois**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #40719 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
Adding the parameter in the interface is a BC break. The fact that the interface is experimental allows us to do that in 5.x for the 5.3 release, but I don't think it allows BC breaks in patch releases.

**Comment by alexandre-daubois** [comment]
> Adding the parameter in the interface is a BC break. The fact that the interface is experimental allows us to do that in 5.x for the 5.3 release, but I don't think it allows BC breaks in patch releases.

Thank you very much for your explanation. I added the BC break line in `UPGRADE-5.3.md`.

**Review by chalasr — APPROVED** [review]

**Comment by wouterj** [comment]
Thank you @alexandre-daubois! Congratulations with your first pull request :)

**Comment by wouterj** [comment]
I'm sorry, something went wrong during the merge and the merge commit is now lost. The commit is in the 5.x branch though: https://github.com/symfony/symfony/commit/7888f8930d20d30d696c61ece51487559f50b30e

I'll do my best to get the merge commit back, but for now, I'll have to give this PR a "closed" status (but it *is* merged).

**Comment by stof** [comment]
@wouterj have you merged that with the gh tool ? The commit also appears to have been merged as a fast forward rather than a  merge commit, meaning that the changelog tooling won't find it either.

**Comment by wouterj** [comment]
@stof yes, I did. But I had to rebase my local 5.x branch as it changed between me merging this PR and trying to push 5.x, which caused the merge commit to be removed (see my thread on Slack).

**Comment by stof** [comment]
@wouterj in such case, you should restart the gh merge instead

**Pull request closed without merging**
