### PR TITLE
[HttpFoundation] Typo on deprecation package name

### PR DESCRIPTION
**Pull request by andersonamuller**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by jderusse — COMMENTED** [review]
Good catch.

There is a second occurrence in the test

**Review by derrabus — APPROVED** [review]

**Review by derrabus — CHANGES_REQUESTED** [review]
I was too fast with my aproval. As @jderusse said, we have to fix the corresponding test as well. 😓

**Review by xabbuh — DISMISSED** [review]

**Review by stof — DISMISSED** [review]

**Comment by andersonamuller** [comment]
Please, fell free to fix the tests and push to my branch, won't look into this until Monday.
Have a good weekend you all.

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Good catch, thanks @andersonamuller.

**Pull request merged**
