### PR TITLE
New extensions were released supporting PHP 7.3

### PR DESCRIPTION
**Pull request by tvlooy**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | see travis
| License       | MIT

Requested in #30030

### CODE REVIEW

**Comment by tvlooy** [comment]
zookeeper still segfaults. I do see a fixed segfault in master (that will become 0.7.0) we will need to re-test when this release is out
last release from amqp didn't look ok, I'm investigating what is wrong ...

**Comment by tvlooy** [comment]
@nicolas-grekas amqp is fixed!

zookeeper still segfaults. I do see a fixed 7.3 segfault in master (that will become 0.7.0) we will need to re-test when this release is out to see if this is the same. If not I'll track down the test, isolate and report upstream

**Comment by tvlooy** [comment]
tests should pass by the way. 7.0 failed on adding the ppa

**Comment by nicolas-grekas** [comment]
Thank you @tvlooy.

**Pull request merged**
