### PR TITLE
[SecurityBundle] Remove unused memory users’ `name` attribute from the XSD

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | N/A
| License       | MIT

The related config has been deprecated in #40403 and removed in #41613.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @MatTheCat.

**Comment by xabbuh** [comment]
Shouldn’t we do this change on 7.2 only? This change now risks that someone receives errors on the next patch release if their XML config still makes use of the now removed attribute.

**Comment by nicolas-grekas** [comment]
@xabbuh right, see cdb8354a152b5c8299ab2bb66933922b644920a9

**Comment by MatTheCat** [comment]
@xabbuh @nicolas-grekas using `name` would have made the config crash after https://github.com/symfony/symfony/pull/41613 so no one could be using it.

**Pull request merged**
