### PR TITLE
[FrameworkBundle] Make Controller helpers final

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

I propose to make all ControllerTrait methods final so we can add type hints.
I also propose to add ControllerTrait::has/get so that AbstractController also has the methods.
This will help move from Controller to AbstractController.

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by ossinkine** [comment]
@nicolas-grekas Could you please explain what is the sense of making this methods final?

**Comment by nicolas-grekas** [comment]
@ossinkine see PR description. Why would you need to extend them?

**Comment by ossinkine** [comment]
@nicolas-grekas PR description just says you propose to make them final but does not say why.
For example, I want to override `render` method in abstract controller to transparently set default parameters or set custom header to response:
```php
abstract class MyController extends Controller
{
    public function render($view, array $parameters = [], Response $response = null)
    {
        $parameters = array_merge(['foo' => 'bar'], $parameters);

        return parent::render($view, $parameters, $response);
    }
}
```
So children controllers continue to use `render` method.

By the same logic, other methods can be overridden

**Comment by nicolas-grekas** [comment]
@ossinkine after #24722, the method will have a new signature (type-hints, as stated in the above description), so that if your code extends the methods, it will break. That's why.

**Comment by ossinkine** [comment]
@nicolas-grekas I understand the new signature breaks BC and I've have to fix my code. But why I can't override the methods in future when my method signature is fixed?
I will need to create one more method like `renderWithDefaultParameters`, right?

**Comment by TeLiXj** [comment]
I'm surprised after try 3.4 beta 2 and discover this like ossinkine. 
IMHO add type-hints in the future couldn't be a reason to mark this method as final. In the next version we can fix our signature to adapt to parent type-hints.

**Pull request merged**
