### PR TITLE
[Form] fix parameter type declaration and make fabbot happy

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This will make fabbot green and Travis red :)

**Comment by xabbuh** [comment]
The Form component tests are green now. AppVeyor failure doesn't look related.

**Review by yceruto — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
Sweet :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
