### PR TITLE
[Messenger] Add forward compatibily with php-amqp v2

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       |
| License       | MIT
| Doc PR        |

see https://github.com/php-amqp/php-amqp/issues/424#issuecomment-1656692661

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
:monkey:

**Review by maxbeckers — APPROVED** [review]

**Comment by fabpot** [comment]
I'm not sure this qualifies as a bug fix.
In any case, I suppose we would need to run tests for both v1 and v2?

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Comment by Danielss89** [comment]
This actually need to be done to the nack() method too, not only ack().
Is there a reason why this is only in 5.x branch and not 6.x branch? If not, i can do a PR for 6.x
It currently breaks with version 2 of php-amqp, so would be good to get patched rather quick.

Sorry, i see it actually is in 6.4!

**Comment by maxbeckers** [comment]
@Danielss89 i guess the nack() was forgotten in this fix, you can provide a pr for that. And this will be merged to all the newer versions at the latest with the next release.

**Comment by Danielss89** [comment]
Ok great! Which branch should i target?

**Comment by stof** [comment]
@Danielss89 please target 5.4, as done for this PR.

**Pull request merged**
