### PR TITLE
[ExpressionLanguage] add contains operator

### PR DESCRIPTION
**Pull request by xavren**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16153 |
| License | MIT |

### CODE REVIEW

**Comment by fabpot** [comment]
I would prefer to add this support on the existing `in` test like in Twig.

**Comment by stof** [comment]
@fabpot this could make things more complex for the compiled version, as we cannot hide the logic inside a dedicated function as Twig does: it would not be available in the context running the compiled code.

**Comment by fabpot** [comment]
To be clear, I would not add support for this (and by the way, your argument is why I did not implement it back then), but *if* we were to add support for it, I don't think it would make sense to add another keyword.

**Comment by xavren** [comment]
Ok so if i try a type verification for the in operator, will it be accepted?

**Comment by fabpot** [comment]
I don't think it is worth it. Or do you have a strong use case?

**Comment by xavren** [comment]
ExpressionLanguage is used in a lot of context and there is only preg_match that can be used to test this.
My goal is to use it like the routing component does, but exposed directly to web user and it is more natural to write string contains string rather than contains(string, string)

The performance on strings will be better too but i'll understand if this is not enough

**Pull request closed without merging**
