### PR TITLE
Remove experimental notice from components

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

@fabpot:
> Nothing can be marked as experimental in 4.4.
>
> https://github.com/symfony/symfony/pull/32277

### CODE REVIEW

**Comment by teohhanhui** [comment]
Hmm... It seems like the same message is in a few other components as well.

**Comment by nicolas-grekas** [comment]
@teohhanhui can you please remove them all in this PR?

**Comment by teohhanhui** [comment]
Done.

**Review by Tobion — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @teohhanhui.

**Pull request merged**
