### PR TITLE
[CS] Enforces null type hint on last position in phpDocs

### PR DESCRIPTION
**Pull request by carusogabriel**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | -   
| License       | MIT
| Doc PR        | - 

As a majority in our codebase, the `null` typehint usually comes in the last position in phpDocs.

### CODE REVIEW

**Review by ro0NL — APPROVED** [review]
can/does php-cs-fixer cover it?

**Review by javiereguiluz — APPROVED** [review]
Maybe this is rejected because of the "merge conflicts" ... but I wish this is merged because it's great for consistency. Thanks Gabriel.

**Review by nicolas-grekas — APPROVED** [review]
(would be great to have php-cs-fixer do it for us)

**Comment by nicolas-grekas** [comment]
Thank you @carusogabriel.

**Comment by TomasVotruba** [comment]
@ro0NL No need to. [`NullTypeHintOnLastPositionSniff`](https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Sniffs/TypeHints/NullTypeHintOnLastPositionSniff.php) can

```yaml
services:
    SlevomatCodingStandard\Sniffs\TypeHints\NullTypeHintOnLastPositionSniff: ~
```


```
vendor/bin/ecs check src/Symfony --fix
```

**Comment by jvasseur** [comment]
php-cs-fixer can do it with the `phpdoc_types_order` fixer.

**Comment by carusogabriel** [comment]
@jvasseur Thanks for that. Gonna open a PR adding that to all current active branches.

**Pull request merged**
