### PR TITLE
Added {{ value }} message placeholder to UniqueEntityValidator

### PR DESCRIPTION
**Pull request by jperovic**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15268 |
| License | MIT |
| Doc PR | - |

Apologize if I missed something. This is my first contribution to a large scale project.

### CODE REVIEW

**Comment by jperovic** [comment]
Just wanted to ask quick question here, to which I didn't find any answer in CONTRIBUTING document.

When I run "phpunit" command, it works until it gets stuck with `QuestionHelperTest::testAskChoice` test. I did a little bit of research and it seems that it gets stuck due to `interactive` argument being set to `true` in `InputStream` instance. After that, code hits this infinite `while` loop (`$attempts` is `NULL`):

```php
# Symfony\Component\Console\Helper\QuestionHelper::validateAttempts()
while (null === $attempts || $attempts--) {
            if (null !== $error) {
                $this->writeError($output, $error);
            }

            try {
                return call_user_func($question->getValidator(), $interviewer());
            } catch (\Exception $error) {
            }
        }
``` 

Is this known limitation? I have `Centos 6.5` and `PHP 5.6`...

**Comment by jakzal** [comment]
@jperovic that's a bug. I'm looking into this.

**Comment by jperovic** [comment]
@jakzal Cool, thanks :)

**Comment by Minishlink** [comment]
Hello, thanks for this ! :+1: 

Just a quick note: UniqueEntityValidator can have several fields. As such, one should be able to refer to all these fields in the validation message eg. "The combination of {{ field1 }} and {{ field2 }} should be unique.".

Also, see #15201. You both address the same issue.

**Comment by fabpot** [comment]
Status: needswork

**Comment by fabpot** [comment]
@jakzal Are you still looking at this bug?

**Comment by jakzal** [comment]
@fabpot I fixed it in #15280. Looks like I forgot to update this ticket (which is actually not related to the issue with tests).

**Comment by fabpot** [comment]
Thank you @jperovic.

**Pull request closed without merging**
