### PR TITLE
[FrameworkBundle] Check non-null type for numeric type

### PR DESCRIPTION
**Pull request by Arman-Hosseini**
$maxAge and $sharedAge can both be zero

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you add a test case please?

**Comment by nicolas-grekas** [comment]
Friendly ping @Arman-Hosseini

**Comment by Arman-Hosseini** [comment]
Sorry. I was busy. I'll definitely do it by the weekend @nicolas-grekas

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Arman-Hosseini.

**Pull request merged**
