### PR TITLE
Changed roundCurrency method to be public

### PR DESCRIPTION
**Pull request by votemike**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

This allows a developer to fetch the rounded amount of the currency without the symbol

### CODE REVIEW

**Comment by OskarStark** [comment]
Do we need to add this method here on top of the class?

https://github.com/symfony/symfony/pull/18827/files#diff-2a5ae15ec68c5d666ce08a09d75690efR25

**Comment by votemike** [comment]
@OskarStark I guess I should. It also appears that the methods are ordered in the file by visibility. Should I move the method its self?

**Comment by OskarStark** [comment]
> @OskarStark I guess I should. It also appears that the methods are ordered in the file by visibility. Should I move the method its self?

i would say yes, but i can be wrong

**Comment by stof** [comment]
-1 for that. This method is not available in the NumberFormatter API, so it should not appear in the API of the stub implementation

**Comment by votemike** [comment]
@stof Are you saying -1 for the Pull Request or for OskarStark's suggestion?
If it's for the PR, can you suggest a better way to get a rounded number without the currency symbol.

**Comment by stof** [comment]
@votemike for the PR. The class used here is the stub implementation of the ext-intl NumberFormatter. Making support things not supported in ext-intl is a no-go (it would mean that enabling the extension to get better performance and support for all locales would drop some features)

**Pull request closed without merging**
