### PR TITLE
[FrameworkBundle] drop hard dependency on the Stopwatch component

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | related to symfony/flex#14
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
does TwigBundle works fine for the Stopwatch extension if the service is not always available anymore ?

**Comment by xabbuh** [comment]
Good question, I did not check what's happing if the `debug.stopwatch` service is not present as it would already be ignored then. So if that was not working properly, it would already have to be fixed in older branches IMO.

**Comment by stof** [comment]
@xabbuh well, currently, the debug.stopwatch service is always present. So we clearly need to check the impact of this change

**Comment by fabpot** [comment]
@stof all usage in Symfony uses `on-invalid=null`, so we're good here.

**Review by fabpot — APPROVED** [review]
As the stopwatch service is only available in the dev env, this looks good to me. We cannot break production inadvertently.

**Comment by stof** [comment]
> As the stopwatch service is only available in the dev env, this looks good to me. We cannot break production inadvertently.

@fabpot that's not true. This service was defined in `debug_prod.xml`, and so loaded in all environments

**Comment by stof** [comment]
However, it won't change anything for fullstack users

**Comment by fabpot** [comment]
@stof indeed, I thought I remembered it being defined in `debug.xml` Anyway, you're right about not being a problem for people using the full-stack. That's why I was also able to remove many other deps in 3.2.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
FYI, I have checked the code of the classes where `null` could be injected instead of the `debug.stopwatch` service and all of them properly deal with `null` being passed.

**Pull request merged**
