### PR TITLE
[Routing] make host matching case-insensitive

### PR DESCRIPTION
**Pull request by Tobion**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #9072 |
| License | MIT |
| Doc PR |  |

Ignore case in host which means:
- When generating URLs we leave the case in the host as specified.
- When matching we always return lower-cased versions of parameters (because of https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Routing/RequestContext.php#L190 ) in the host. This is also what browers do. They lowercase the host before sending the request, i.e. WWW.eXample.org is sent as www.example.org. But when using curl for example it sends the host as-is. So the HttpFoundation Request class can actually have a non-lowercased host because it doesn't have this normalization.

### CODE REVIEW

**Comment by Tobion** [comment]
fabbot.io failure is false positive because the CS error is in a fixture that we cannot change.

**Comment by Tobion** [comment]
ping @symfony/deciders when this is merged I'll try to rebase and finish #10254

**Comment by fabpot** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @Tobion.

**Pull request merged**
