### PR TITLE
[Dotenv] Add support for overriding existing envs

### PR DESCRIPTION
**Pull request by voronkovich**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23723
| License       | MIT

Every time I changed my `.env` file I need to restart the WebServerBundle's server, because the Dotenv component doesn't override the existing environment variables. This PR adds a dedicated method to overload the environment variables.
Having an ability to overload the`.env` file, we could solve the issue like this:
```php
// public/index.php
if (getenv('APP_DEBUG') && file_exists(__DIR__.'/../.env')) {
    (new Dotenv())->overload(__DIR__.'/../.env');
} elseif (!getenv('APP_ENV')) {
    (new Dotenv())->load(__DIR__.'/../.env');
}

```

### CODE REVIEW

**Comment by Taluu** [comment]
It if it is in a `.env`, the DotEnv overwrites only if the var doesn't exist. When you do a `putenv` (and manipulate `$_ENV`, `$_SERVER` variables), it affects only the running process, and does not modify it on the global for all the runs.

So basically, this means that the problem is elsewhere. I'm 👎 for this patch in particular.

**Comment by chalasr** [comment]
Other libraries address this with a dedicated method, that is better IMHO. See 
https://github.com/vlucas/phpdotenv/blob/master/src/Dotenv.php
https://github.com/bkeepers/dotenv/blob/master/lib/dotenv.rb#L30

**Comment by voronkovich** [comment]
@chalasr, thanks for the links! I've added the dedicated method as you suggested!

**Comment by fabpot** [comment]
While I agree that the references bug should be fixed, I'm :-1: for adding such a method which I consciously decided to not add when I design the library.

**Comment by chalasr** [comment]
@fabpot The first approach was a flag set through the constructor. Personally I think we don't need such state hence suggesting a new method (a new arg for the `load()`  method would do the job as well).
Refreshing env vars for each request cannot be done using DotEnv if we don't want it to be able to overload (or clean up) already defined env vars.

**Comment by chalasr** [comment]
Can't we close this one in favor of #23799?

**Comment by nicolas-grekas** [comment]
yes, same purpose

**Pull request closed without merging**
