### PR TITLE
fix: twig deprecation with ??

### PR DESCRIPTION
**Pull request by 94noni**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no 
| New feature?  | no
| Deprecations? | yes
| Issues        |  local profiler
| License       | MIT

hello, I've found this: question should we update all occurences of symfony twig files if any another files ?
(opening raw PR just to get some hint)

Capture d’écran 2024-11-19 à 11 01 02

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Actually, this is already part of bb3e10191fd84affffd16236f8d6b7f4fa343cc4

**Comment by derrabus** [comment]
> Actually, this is already part of [bb3e101](https://github.com/symfony/symfony/commit/bb3e10191fd84affffd16236f8d6b7f4fa343cc4)

But that commit was merged to 7.2. I think, we need to fix this on the lower branches as well. This PR targeted 6.4.

**Comment by 94noni** [comment]
oki thx for commenting I got it
edit: and yes indeed, I was targeting sf64 as I am in the process of upgrading an app from v5 to v6 and found this in the profiler

**Comment by fabpot** [comment]
> > Actually, this is already part of [bb3e101](https://github.com/symfony/symfony/commit/bb3e10191fd84affffd16236f8d6b7f4fa343cc4)
> 
> But that commit was merged to 7.2. I think, we need to fix this on the lower branches as well. This PR targeted 6.4.

I've done the change in all maintained branches, bb3e10191fd84affffd16236f8d6b7f4fa343cc4 is part of 6.4 as well (see https://github.com/symfony/symfony/commits/6.4/).

**Pull request closed without merging**
