### PR TITLE
[PhpUnitBridge] Exclude from baseline generation deprecations triggered in legacy test

### LINKED ISSUE #46710: [PhpUnitBridge] Baseline generation includes deprecations triggered in legacy tests
### Symfony version(s) affected

6.1.0, but earlier for sure

### Description

Baseline generation includes deprecations triggered in legacy tests, which IMHO

1) is irrelevant, because by design deprecations in that context are ignored since they're explicitly expected to occur
2) are confusing if included in the baseline file, since they're not really to be addressed by developers

### How to reproduce

Create a baseline file for a test class that has at least a test marked `legacy` and deprecations are triggered as part of that test execution.

### Possible Solution

Do not include in deprecation baseline file the Deprecation objects that have `::isLegacy()` true.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mondrake**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #46710  
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @mondrake.

**Comment by mondrake** [comment]
Thanks @nicolas-grekas! 

However I think we need to adjust some tests that are now failing - how do you usually do that? Revert and fix, new PR, or? Sorry I come from Drupal world, not yet accustomed to Symfony's etiquette.

**Comment by mondrake** [comment]
Tests will be fixed in #46719 .

**Comment by wouterj** [comment]
To answer your questions about the "normal process" of failing tests: Normally, we don't merge PRs that cause test failures, but sometimes we missed that a PR introduced new failing tests (I think that's what happened here).

Due to third party changes or other changes when upmerging older versions into newer branches, our branches often have a few failing tests. If you feel like it, we always welcome people submitting a PR to fix failing tests :) Otherwise, a core team member takes care of it (as the branches have to be green before releasing a new version at the end of the month).

**Comment by mondrake** [comment]
Thanks @wouterj - I see fixes are already under way, so I'll just pause here.

**Pull request merged**
