### PR TITLE
[DoctrineBridge] drop binary variants of UID types

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #39112
| License       | MIT
| Doc PR        | -

#39112 made me realize that when the DB engine doesn't have a native UUID/GUID type, there's no benefit to representing ULIDs as UUIDs.

This PR proposes to use the native GUID type for both UUIDs and ULIDs only when the DB engine provides such a type, and to use `BINARY(16)` when the DB engine doesn't have a native GUID type.

This leaves us in a situation where, whether the DB engine supports GUID natively or not, UUID and ULID are always stored in the most compact format.

This makes the "binary" variants useless.

MySQL 8 has [functions](https://mysqlserverteam.com/mysql-8-0-uuid-support/) to deal with binary GUID, and so does [SQLite](https://sqlite.org/src/file/ext/misc/uuid.c).

### CODE REVIEW

**Comment by derrabus** [comment]
Is it possible to change your mind on this? Storing a UUID as string on MySQL seems to be inferior to storing it in `BINARY(16)`. That's not only about storage, but also about index size.

MySQL ships with functions like `UUID_TO_BIN()` and `BIN_TO_UUID()`, dedicated to the binary storage of UUIDs. `BINARY(16)` is MySQL's poor man's version of a native UUID type. https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid-to-bin

And you know, if the project is already running on MySQL, "use Postgres" is not really a viable option.

**Comment by nicolas-grekas** [comment]
Instead of defaulting to a varchar, we could default to binary when a DB storage doesn't have a native GUID type.
But I don't think providing a choice to users for this is really needed. Eg if MySQL has functions to represent `BINARY(16)` as uuids, then we should definitely use `BINARY(16)` when the type is declared as `uuid` or `ulid`.

**Comment by nicolas-grekas** [comment]
@derrabus updated to my last proposal.

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by sylfabre** [comment]
@nicolas-grekas @javiereguiluz This conflicts with this article which needs to be updated

https://symfony.com/blog/new-in-symfony-5-2-doctrine-types-for-uuid-and-ulid

**Pull request merged**
