### PR TITLE
FIXED NON EXISTING TYPE DECLARATION

### PR DESCRIPTION
**Pull request by edwinhageman**
| Q             | A
| ------------- | ---
| Branch?       | 3.1, 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20765
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### CODE REVIEW

**Comment by HeahDude** [comment]
Nice catch! Should be merged in 3.1.
👍

Status: Reviewed

**Comment by stof** [comment]
👍

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Good catch, thanks @edwinhageman.

**Pull request closed without merging**
