### PR TITLE
[HttpFoundation] Fix BC break introduced by #17642

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Branch | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17642 |
| License | MIT |
| Doc PR | n/a |

@taylorotwell can you confirm it fixes the issue with Laravel?

### CODE REVIEW

**Comment by fabpot** [comment]
LGTM

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
Wait, you also need to update the UPGRADE and  Controller.php that where modified in #17642 isn't it?

**Comment by dunglas** [comment]
@nicolas-grekas, I don't think so. `Controller.php` only use the constructor and it's signature hasn't been modified and `CHANGELOG` files are still accurate.

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request closed without merging**
