### PR TITLE
[Console][DI] Fail gracefully

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/flex/issues/212, #25280
| License       | MIT
| Doc PR        | -

I already experienced this issue a few times without spending time digging it:
sometimes, you call `cache:clear`, and the command quits without any output, and with 255 status code.

The reason is the `@include` in `Kernel`, which makes everything silent, especially fatal errors (thanks PHP...)
So if the to-be-removed container is broken for some fatal reason, the failure is really bad.

To fix that, here are two measures:
- use `include_once` instead of `require_once` in the dumped container: that's OK there to actually not immediately load the file, any hard failure will happen later anyway, and any soft failure will allow the `cache:clear` command to complete (like when you remove a package)
- register `Application::renderException()` as the main PHP exception handler, via `Debug::ErrorHandler` when it's available

End result when it fails:
image

instead of a blank output.

### CODE REVIEW

**Comment by theofidry** [comment]
@nicolas-grekas so you would still get a silent hard failure if you do `c:c --env prod`?

**Comment by nicolas-grekas** [comment]
Not since 10 minutes. When did you read the code ? :)

**Comment by theofidry** [comment]
I didn't, but I have trouble following :P

**Comment by weaverryan** [comment]
Fwiw, I believe a user on Twitter hit the same issue - when removing Twig https://twitter.com/neelion333/status/936623941937795072 - looks very easy to reproduce

**Comment by weaverryan** [comment]
I think this bug might be quite critical. I think I'm even able to hit it through the web interface. While upgrading a project from 3.3 to 3.4, I did the following:

1) Added the `container.autowiring.strict_mode: true` parameter.
2) Refreshed to rebuild the container
3) Removed this parameter
4) Refreshed to this error:

screen shot 2017-12-01 at 10 40 10 pm

@nicolas-grekas Do you think it's related? Do you need me to try to create a repeater (the above was done on our big KnpU Symfony 3 tutorial project).

**Comment by nicolas-grekas** [comment]
@weaverryan looks like the same yes.

I improved the behavior by replacing the nasty `@`-silencing by a specific `E_WARNING` silencing. The container-loading file is also now resilient to a broken container folder, by using include+return in case of failure. Also handled by Kernel.

PR is ready. Dunno how to test it as the behavior is triggered by edge case fatal errors...

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by weaverryan** [comment]
I do not appear to be able to trigger the fatal error anymore. I think you may have gotten it!

**Comment by k00ni** [comment]
I experienced this bug today. It occurs in certain controller actions and not when using the cache commands via terminal. But these actions call indirectly `cache->clear()` which seem to interfere with symfony internals?

> FatalErrorException Compile Error: Container Failed opening required [...]getRouting_LoaderService.php' (include_path='.:/usr/local/lib/php') in srcDevDebugProjectContainer.php (line 295)

I was able to "fix" that for now, by **removing the WebProfilerBundle** resp. **ProfilerPack**:

* "symfony/profiler-pack": "^1.0"
* "symfony/phpunit-bridge": "^4.0.6"

Afterwards i cleared the cache using `rm -rf var/cache/*` and it seems to work.

**Comment by nicolas-grekas** [comment]
What are you calling in your controller?

**Comment by k00ni** [comment]
Here is part of the code:

```php
$env = /* .. */;
$cache = new FilesystemCache('', 0, __DIR__.'/../../var/cache/'.$env);

// do some mysql operations

$cache->clear();
```
I am expected the cache, because you mentioned it at the beginning. But i am not sure.

**Comment by k00ni** [comment]
Ok, i changed `$cache->clear()` to a solution which directly removes entries, which my app created. I re-enabled the WebProfilerBundle and tried the mentioned controller actions. And it worked. I assume, that calling `$cache->clear()` in a controller was the problem?

**Comment by nicolas-grekas** [comment]
I suppose. FilesystemCache is not made for clearing the full Symfony cache AFAIK.

**Pull request merged**
