### PR TITLE
[Serializer] Revert "Fix object normalizer when properties has the same name as their accessor" - it was a BC Break

### LINKED ISSUE #54488: [Serializer] BC break on isers following #54148
### Symfony version(s) affected

6.4.6

### Description

The following PR fixes a bug, but changes how isers are serialized: https://github.com/symfony/symfony/pull/54148/files

- In 6.4.4, a property named `$isSomething` is serialized `something`

- In 6.4.6, that property is now serialized: `isSomething`

Even though previous behaviour was a bug, it is there since years and needs the right migration on our codebase. I'd advise that such a backward compatibility break could be updated on the next major upgrade.

### How to reproduce

```php
    private bool $isAdmin = false;

    public function isAdmin(): bool
    {
        return $this->isAdmin;
    }

    public function setIsAdmin(bool $isAdmin): self
    {
        $this->isAdmin = $isAdmin;

        return $this;
    }
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by NeilPeyssard**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54488
| License       | MIT

Revert changes from this PR https://github.com/symfony/symfony/pull/54148 (BC Break).

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
PR welcome to make this change on 7.x (smoothly if possible i.e. with deprecation).

**Comment by nicolas-grekas** [comment]
Thank you @NeilPeyssard.

**Comment by nvdbeek** [comment]
@nicolas-grekas when are you creating a new tag for this 'misbehavior'? We cannot update our 6.4.x cause of this.

**Comment by nicolas-grekas** [comment]
We tag at the end of the month, so one week max.

**Pull request merged**
