### PR TITLE
[PropertyInfo] added handling of nullable types in PhpDoc

### PR DESCRIPTION
**Pull request by oxan**
While not specified in PSR-5, PhpDocumentor does support parsing nullable types in the PHP 7.1 syntax (i.e. `?string`), and returns those in a `Nullable` wrapper type. We currently don't handle this and neither throw an error, which results in all kind of weird breakage when this syntax is used (e.g. "class string|int not found").

Correctly parse this syntax into a nullable type.

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by oxan** [comment]
Okay, so the tests fail because `phpdocumentor/typeresolver` only parses nullable types from v0.3.0 onwards, and we require v0.2.1+. Should I bump the dependency or make the tests conditional?

**Comment by nicolas-grekas** [comment]
Given 0.3 supports 5.5, which is the minimum version of Symfony 3.4, I think it's fine bumping.

**Review by dunglas — APPROVED** [review]

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
bump pending :)

**Comment by oxan** [comment]
@nicolas-grekas I fixed the dependency (& tests are working now) :)

**Review by fabpot — APPROVED** [review]

**Review by dunglas — APPROVED** [review]
Nice one, thanks!

**Comment by fabpot** [comment]
Thank you @oxan.

**Pull request merged**
