### PR TITLE
fix form tests for master

### PR DESCRIPTION
**Pull request by EVODelavega**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17089 |
| License | MIT |
| Doc PR | N/A |

Proposed fix for failing form component tests

### CODE REVIEW

**Comment by Tobion** [comment]
The legacy test should be removed in 3.0 and not a removed functionality reintroduced.

**Comment by stof** [comment]
These options were not even part of this form type

**Comment by EVODelavega** [comment]
@stof So basically, the form components' tests need to be reworked. Also: `CollectionType::buildForm` does work under the assumption that there is an option called `options` for that form type:

```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if ($options['allow_add'] && $options['prototype']) {
            $prototypeOptions = array_replace(array(
                'label' => $options['prototype_name'].'label__',
            ), $options['options']);

            if (null !== $options['prototype_data']) {
                $prototypeOptions['data'] = $options['prototype_data'];
            }

            $prototype = $builder->create($options['prototype_name'], $options['entry_type'], $prototypeOptions);
            $builder->setAttribute('prototype', $prototype->getForm());
        }

        $resizeListener = new ResizeFormListener(
            $options['entry_type'],
            $options['entry_options'],
            $options['allow_add'],
            $options['allow_delete'],
            $options['delete_empty']
        );

        $builder->addEventSubscriber($resizeListener);
    }
```

With the changes in this PR, running `./phpunit src/Symfony/Component/Form` passes all tests. Removing the changes makes them fail again

**Comment by stof** [comment]
For the collection type, not for the inner type.

**Comment by nicolas-grekas** [comment]
This has been already fixed isn't it?

**Comment by dupuchba** [comment]
@nicolas-grekas , to complete @stof statement => https://github.com/symfony/symfony/commit/4c7c5ff489ea868daf36e77a87ab379577d2782f

**Comment by fabpot** [comment]
What's the status of this PR?

**Comment by Tobion** [comment]
Fixed with https://github.com/symfony/symfony/commit/bd686cd1eecad01e38794bf4ee65566e24f844b9

**Pull request closed without merging**
