### PR TITLE
[Form][TwigBridge] Add help_html

### PR DESCRIPTION
**Pull request by mpiot**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | no
| License       | MIT
| Doc PR        | symfony/symfony-docs#10978

Sometimes, when we use the form `help` option, we want to display it as HTML (add bold, italic, a span with a specific class, ...). For security reasons, we escape the `help` content.

In this PR, I've added an `help_html` option, seted to false per default. When it set on true, the `help` content is no longer escaped.

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thanks @mpiot, could you please rebase to fix the conflicts? They must be related to the move to short arrays.

**Review by nicolas-grekas — APPROVED** [review]
(I just rebased for you)

**Comment by nicolas-grekas** [comment]
Thank you @mpiot.

**Comment by mpiot** [comment]
Thanks a lot :-) I was thinking about doing this tonight, it's faster like this :D

**Comment by scuben** [comment]
I wonder if we should also add a boolean option `label_html` with a similar functionality like the newly `help_html`? Would it be appreciated if one would create a PR for that? An old issue (https://github.com/symfony/symfony/issues/8733) suggested that but was closed due to lack of traction.

**Comment by mpiot** [comment]
@scuben I can do that, (I've hesitate to do that when I've done this PR), but is it really usefull ?
In which case we need to implement HTML in a label ? Often the label is stilized by it class and we don't really need to use HTML tags.

**Comment by scuben** [comment]
@mpiot I just had a use case to add a TOS link to the label of a checkbox and would have loved this feature 👍

**Comment by mpiot** [comment]
@scuben Okay, I see, then it should be implement in CheckboxType, RadioType, and ChoiceType only ?

**Comment by scuben** [comment]
I would implement it in any type which would reduce complexity as you know you can relay on that it's available in any label.

**Comment by mpiot** [comment]
It's comprehensive, then it's easier to implement too. I start it, when I've some times :-)

**Comment by xabbuh** [comment]
I think it would be better to discuss this in a new issue before investing time in something that might not be merged. Pesonally, I don't see this as a common use case and would rather suggest to use a custom form theme for cases when you really need this instead.

**Comment by mpiot** [comment]
Okay, then @scuben, can you create an Issue ? You can refer it and ping me, if there are a real interest from users, I'll do it.

For the moment, I've must do that one times, and I've used a custom form theme thath extends which theme I use, with a custom type.

**Pull request merged**
