### PR TITLE
[Workflow][Registry] Added a new 'all' method (Symfony 3.4)

### PR DESCRIPTION
**Pull request by alexpozzi**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Same as [26656](https://github.com/symfony/symfony/pull/26656) but for the 3.4 version.

### CODE REVIEW

**Comment by iltar** [comment]
@alexpozzi the way Symfony handles versions, means new feature only get merged in new feature releases (next one is 4.1). That means this feature won't be back-ported (or added) to 3.4. It looks like your other PR is (almost) ready to be merged though, so you should be able to use this feature in about 2~3 months with 4.1.

**Comment by alexpozzi** [comment]
Ok, no problem.
I submitted it because reading [this document](https://symfony.com/doc/current/contributing/code/maintenance.html) I thought it was going to be an accepted change.

Thanks!

**Comment by iltar** [comment]
If it would considered a bug fix, this branch would've been correct and it could be merged upwards (3.4 to master), so only 1 PR would be required to reduce overhead for the contribution

**Comment by alexpozzi** [comment]
Ah I misread! Sorry for that!

**Pull request closed without merging**
