### PR TITLE
[3.4] Deprecations regarding use of service locators/getter injection

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

In order to don't do it twice, this includes the deprecations for #21625. 
Targets 3.4 (or more if the experimental period for service locators/getter injection is prolonged).

### CODE REVIEW

**Comment by ogizanagi** [comment]
> Targets 3.4 (or more if the experimental period for service locators/getter injection is prolonged).

I doubt it will be more anyway, as 3.4 is the last release for Symfony 3. 
Can experimental features stay experimental in a new major release?

**Comment by chalasr** [comment]
@ogizanagi Given "experimental" doesn't fit with semver and considering the following statement:

> The core team can decide to extend the experimental period for another minor version on a case by case basis.

I would say yes.

**Comment by nicolas-grekas** [comment]
This is going to be a nightmare to track to me... Except for the UPGRADE notes, I'd prefer to have the code side  be implemented right into the PR introducing the new proposed way of things so that the test suite can spot any missing upgrade of the code base.

**Comment by nicolas-grekas** [comment]
ping @fabpot

**Pull request closed without merging**
