### PR TITLE
[FrameworkBundle] add `cache.adapter.filesystem_tag_aware` pre-configured adapter

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | n/a
| License       | MIT
| Doc PR        | todo

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Why? I mean: we already have `tags: true`, which is using the generic `TagAwareAdapter`, which should do just fine, isn't it?

**Comment by kbond** [comment]
It is my understanding that `FilesystemTagAwareAdapter` is better optimized than using `tags: true` and `FilesystemAdapter`.

**Comment by nicolas-grekas** [comment]
Not really actually. It just has different performance characteristics that should be reviewed and benchmarked (sorry that's a bit vague I don't remember the details at the moment)

**Comment by kbond** [comment]
I see, well what I was trying to do is make `cache.app` taggable (I know there is a `cache.app.taggable` but I wanted `cache.app` taggable directly).

Maybe just a documentation issue but I couldn't figure out how to do this without a hefty custom abstract service.

**Comment by nicolas-grekas** [comment]
Type hint `TagAwareCacheInterface` and get `cache.app.taggable` for free?

**Comment by kbond** [comment]
Closing as there isn't a clear performance benefit.

**Pull request closed without merging**
