### PR TITLE
[Console] add ClassName on help output

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #26034 
| License       | MIT
| Doc PR        | todo if pr validated

I'm adding the class name output to the help command in order to be able to know what class it is, and can be helpful to debug or to add feature.

### CODE REVIEW

**Comment by chalasr** [comment]
Not fond of this, commands output should be as clean as HTTP responses in production to me (i.e. free of debug info) and finding a command class by looking for its name in a codebase is trivial most of the time. Let's see what others think

**Comment by ogizanagi** [comment]
I tend to agree with @chalasr too

**Comment by Simperfit** [comment]
Maybe we can add a paremeter to not have it by default ?

**Comment by jvasseur** [comment]
I'm 👎 for adding this in the help command the console component component is used to build a lot of console applications and getting the class name when trying to get informations on how to use a command is more polluting the output than providing an useful information.

**Comment by Simperfit** [comment]
We can add a new command to get debug information of a command, but what will be in ?

**Comment by nicolas-grekas** [comment]
in very-verbose mode ?

**Comment by fabpot** [comment]
I agree with other commenters here. Finding the class is really easy. Closing.

**Pull request closed without merging**
