### PR TITLE
[Validator] Standardizing validation messages

### PR DESCRIPTION
**Pull request by toniperic**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ~
| License       | MIT
| Doc PR        | ~

Currently, almost all of the validation messages follow the same format, which I personally like.  
Some of the examples are:

> This value should be of type {{ type }}.
> This value is too long. It should have {{ limit }} characters or less.
> This collection should contain only unique elements.
> This is not a valid International Bank Account Number (IBAN).

Basically, the format is: reference the subject ("this value", "this collection", "the file"...) and then explain what the actual problem is.

There are two exceptions that I'm seeing:

1. **addressing the client only in some places**. In the majority of messages, they have been constructed in such a way that no single individual is being addressed, whereas some of them do.  
This PR fixes this in a way so that the messages which have been addressing anyone no longer do. Examples:
    - _"The value **you** selected is not a valid choice."_ is now _"The selected value is not a valid choice."_
    - _"**You** must select at most {{ limit }} choices."_ is now _"At most {{ limit }} choices must be selected."_
    - _"This password has been leaked in a data breach, it must not be used. **Please use** another password."_ is now _"This password has been leaked in a data breach. A different password must be used."_
2. **avoiding being consistent with aforementioned format**.  
This PR fixes that in a way that so that the messages conform to the same format as most of the others (referencing the subject and then stating the problem). Examples:
    - _"Invalid card number."_ is now _"This is an invalid card number."_
    - _"Unsupported card type or invalid card number."_ is now _"This is an unsupported card type or invalid card number."_

Also, as an added bonus, since I'm Croatian, I've done the translations for Croatian language in the very same PR + fixed some of the messages that didn't account for Croatian pluralization rules (or have, but implemented incorrectly).

All comments and feedback are appreciated.

Have a nice day!

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I understand what you propose, but I fear this might be a too large BC break: this would invalidate any existing alternative translations. I don't know how/if we can do this.

**Comment by toniperic** [comment]
Thanks for the feedback @nicolas-grekas.

What I'm seeing that could be done to avoid BC issues is:
create new translation entries, where source of each entry is actually the one being changed through this MR (that is making breaking changes), while keeping whatever the current translations are for those entries.

That way, translations on all languages are kept as-is – so they're conveying pretty much the same understandable message – but from then on developers might provide more precise translations at any point to be in sync with the standard.

I've tried to illustrate this using a simple example which can be seen [in this gist](https://gist.github.com/toniperic/e6e7ab82b498c12a53ce0497a8c1f7be).

Also, messages that are not in sync with the standard could be deprecated and removed at some point in the future, where breaking changes are allowed and clearly communicated.

What do you think?

**Comment by fabpot** [comment]
I like this pull request. Having consistent error messages sounds like a nice goal. 👍 for me

**Comment by nicolas-grekas** [comment]
@fabpot which forward path do you recommend? Should we go with identifiers instead of messages as source?

**Comment by ro0NL** [comment]
we should leverage #30931 imho, and get this right in one version :)

**Comment by fabpot** [comment]
Would it make sense to try to translate all the new messages during SymfonyCon Amsterdam where we have a lot of different countries/languages represented? If we can have enough people, that could work.

**Comment by nicolas-grekas** [comment]
Thank you for proposing. The proposed messages are marginally better, but the effort to migrate to using is not worth the effort.

**Pull request closed without merging**
