### PR TITLE
[Console] Show commands list when we run bin/console [namespace]

### PR DESCRIPTION
**Pull request by maidmaid**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/27473
| License       | MIT
| Doc PR        | /

before:
Screenshot from 2019-04-07 13-24-34

after:
Screenshot from 2019-04-07 13-25-17

#EUFOSSA

### CODE REVIEW

**Comment by sstok** [comment]
Should the status code be 0? technically it's still a failure 🤔

**Comment by curry684** [comment]
Given the wording of the original request this is now to be expected functionality, that would make it a success call.

**Comment by maidmaid** [comment]
With a big red output, yes, but with a nice commands list output, we can consider it as the normal output, so the code should be 0 IMO.

**Comment by OskarStark** [comment]
If you are executing bin/console list namespace it should be 0, but if you are executing bin/console namespace it should end up executing a command (at least I would expect that) and it should be 1.

**Comment by maidmaid** [comment]
0 vs 1, wdyt @nicolas-grekas ?

**Comment by fabpot** [comment]
I'm 👎 on such a change.

**Comment by curry684** [comment]
I'm tempted to go with fabpot here - there is a `list namespace` command for this purpose, and what we're doing here now boils down to replacing a correct error (it's an invalid command you're running) with a fake command's output.

**Comment by nicolas-grekas** [comment]
I'm friendly to this - the red bg is too much currently IMHO )

**Comment by maidmaid** [comment]
Just a note : this PR does not replace the red warning when we run a real misspelled/ambiguous command. It works only when a full/abbreviated namespace is matched. It's really convenient.

**Comment by maidmaid** [comment]
Following the @Nyholm's advice, I'd like to know your opinion @weaverryan :)

**Comment by fabpot** [comment]
As explained by @curry684, we already have a command to list commands under a namespace. When the command does not exist, we must have an error. Just to be clear, I won't change my mind here :)

**Comment by chalasr** [comment]
Closing, thanks for the proposal.

**Comment by Nyholm** [comment]
Thank you for the proposal and for the feedback.

**Pull request closed without merging**
