### PR TITLE
[Validator] Add Japanese translation

### PR DESCRIPTION
**Pull request by issei-m**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
Thank you @issei-m.

*どうもありがとう*

**Comment by issei-m** [comment]
@javiereguiluz 👍

**Comment by fabpot** [comment]
Thank you @issei-m.

**Comment by fabpot** [comment]
I've merged it on 2.7 (to ease maintenance, we always merge translations on the lowest branch even if the translation was not used on that version).

**Pull request closed without merging**
