### PR TITLE
[Serializer] Denormalize with typehinting.

### PR DESCRIPTION
**Pull request by mihai-stancu**
[2.7][Serializer] Feature using the type hinted class from the setter (or construct) parameter to denormalize values before calling the setter.

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | none |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by mihai-stancu** [comment]
Example:

```
class Invoice {
    /** @var Customer */
    protected $customer;

    public function setCustomer(Customer $customer)
    {
        $this->customer = $customer;
    }
}

$invoiceArray = array(
    'customer' => array(/* field data  of a customer */)
);
$invoiceObj = $normalizer->denormalize(invoiceArray, Invoice::class, null);
```

In the above example the denormalizer will crash because iti will attempt to call `->setCustomer($invoiceArray['customer'])` which is an array, not an object of type `Customer`.

This PR will try to denormalize `$invoiceArray['customer']` before passing it as a parameter.

**Comment by xabbuh** [comment]
@mihai-stancu Can you add a test that would have failed without your changes?

**Comment by dunglas** [comment]
It's a complex topic:
- what about collections (if a mutator must must take in parameter an array of object)
- type metadata can come from various sources (typehints, Doctrine ORM mappings, PHPDoc...)
- type extraction should use the metadata system to improve performance (don't extract the type for every request)
- all normalizers should support that feature

During the development of [API Platform](https://github.com/dunglas/api-platform) I've created a component able to extract informations form various sources (and extensible). It also support collections: https://github.com/dunglas/php-property-info

Then I've integrated it with the Symfony Serializer:
- https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/Loader/AttributesLoader.php
- https://github.com/dunglas/DunglasApiBundle/blob/master/JsonLd/Serializer/ItemNormalizer.php#L139-L163

Dealing with types is indeed a common need and JMSSerializer and DunglasApiBundle have that capability. In fact any advanced serializer will have that need.

Instead of that patch, what do you @symfony/deciders think of integrating my component (or moving it under the Symfony umbrella if it's necessary) and backporting the integration code from DunglasApiBundle directly to the Serializer component?

**Comment by fabpot** [comment]
@dunglas I've just had a look at the library, and that makes a lot of sense. One of my question is if it is useful as is for a large number of use cases? The answer would help defining how to proceed next.

**Comment by mihai-stancu** [comment]
@xabbuh sure, can-do.

**Comment by mihai-stancu** [comment]
@dunglas JMSSerializer and your bundle bring many more features to the table (as well as complexity). My patch is indeed geared towards smaller simpler use cases.

**Comment by mihai-stancu** [comment]
@xabbuh test added.

**Comment by mihai-stancu** [comment]
@xabbuh, @dunglas -- any opinions on the PR so far?

**Comment by dunglas** [comment]
IMO we must decide first if we want an advanced type guessing system such as https://github.com/dunglas/php-property-info or not in the core cc @fabpot

**Comment by sroze** [comment]
It makes a lot of sense to have a the current `php-property-info` library as a Symfony component IMO. This is an "abstraction" layer of class or property reflection that would simply a lot processes like serialization, and remove this logic of the Serializer which shouldn't have this responsibility.

**Comment by fabpot** [comment]
FYI, I've sent an email to @dunglas to confirm that I'm fine with integrating the library into Symfony as a new component.

**Comment by lsmith77** [comment]
great!

**Comment by dupuchba** [comment]
great news

**Comment by mihai-stancu** [comment]
Awesome!

**Comment by mihai-stancu** [comment]
I'll reopen this PR against symfony:2.8 instead.

**Pull request closed without merging**
