### PR TITLE
[HttpFoundation] MongoDbSessionHandler::read() now checks for valid session age

### PR DESCRIPTION
**Pull request by bzikarsky**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | no |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

As discussed with @jmikola: 
- It's a bugfix - expired sessions should never be read
- Therefore should be merged into 2.3 LTS
- TODO: Modify the behavior to match the PDO adapter
- TODO: Add a precise description of the behavior to the manual

-- old description below --

This patch can be seen as either bugfix or feature, though it's probably more on the feature-side. 

Currently a session will be returned by `read()` even if it's already older than `gc_maxlifetime`. If `gc_maxlifetime` is used for timing out sessions and a low gc-ratio is in place there is a high chance the session stays alive for a longer time than wanted. The manual describes the current limitations of `gc_maxlifetime` correctly at http://symfony.com/doc/current/components/http_foundation/session_configuration.html#session-lifetime.

But since the modification timestamp is stored in MongoDB anway, we can actually use it to only return "valid" session-data as does the [PdoSessionHandler](https://github.com/symfony/HttpFoundation/blob/2.7/Session/Storage/Handler/PdoSessionHandler.php#L518)

### CODE REVIEW

**Comment by fabpot** [comment]
What's the status of this PR?

**Comment by bzikarsky** [comment]
It's idle. I was waiting on feedback for the proposed manual changes - especially regarding the "Sessions older than gc_maxlifetime are never read"-stance - and then forgot about it. 

If the general direction of this PR and the proposed documentation-changes is approved, I 'll prepare a PR on documentation and check behaviour of the other session-handlers.

**Comment by jmikola** [comment]
@fabpot, @bzikarsky: I concur that this is just waiting on a documentation PR. I concur with the documentation todo items in [this comment](https://github.com/symfony/symfony/pull/12516#issuecomment-65028144). The generic topics about "timed out" sessions being read and session lifetimes being updated on each request can appear within [Session Configuration](http://symfony.com/doc/current/components/http_foundation/session_configuration.html).

Personally, I'm not sure why [Session Cookie Lifetime](http://symfony.com/doc/current/components/http_foundation/session_configuration.html#session-cookie-lifetime) and [Session Lifetime](http://symfony.com/doc/current/components/http_foundation/session_configuration.html#session-lifetime) are split ([Configuring Garbage Collection](http://symfony.com/doc/current/components/http_foundation/session_configuration.html#configuring-garbage-collection) appears between them). Both sections talk about session cookies. I do think that [Session Lifetime](http://symfony.com/doc/current/components/http_foundation/session_configuration.html#session-lifetime) is the better place to discuss the topics relevant to this PR.

As for documenting suggested MongoDB indexes, that does belong on a new page, which should be linked to from [Custom Save Handlers](http://symfony.com/doc/current/components/http_foundation/session_configuration.html#custom-save-handlers).

**Comment by fabpot** [comment]
I'm going to merge it as is then.

@bzikarsky Can you submit a PR for the docs?

**Comment by fabpot** [comment]
I've just noticed that this is a bug fix that needs to be merged in 2.3. Can you submit a PR for that branch?

**Comment by bzikarsky** [comment]
I'll close this in favour for the new PR (based on 2.3) - https://github.com/symfony/symfony/pull/13911

**Pull request closed without merging**
