### PR TITLE
[AssetMapper] ignore missing directory in `isVendor()`

### LINKED ISSUE #58858: [AssetMapper] `MappedAssetFactory->isVendor()` return `true` when the directory is missing
### Symfony version(s) affected

6.4

### Description

`MappedAssetFactory->isVendor()` return `true` when the directory is missing, which leads to unexpected behaviours.

For some reason, `str_starts_with('/app/assets/javascript/site_chart.js', null)` returns `true`, so AssetMapper thinks that one file is in the `vendor/` directory when it is not.

3v4l: https://3v4l.org/iZfv4

### How to reproduce

Try to use https://github.com/sensiolabs/minify-bundle while the directory `assets/vendor` doesn't exist: https://github.com/sensiolabs/minify-bundle/issues/17#issuecomment-2474070767

### Possible Solution

Refactor `isVendor()` to handle this case.

### Additional Context

I don't know yet if `assets/vendor/` should or must be created by some automation (`bin/console assets:install`, `bin/console asset-map:compile`, or Symfony's recipes?) , but `assets/vendor/` is added to `.gitignore` by the recipes: https://github.com/symfony/recipes/blob/21ffab22d3d8641e626b52bbabc435b690dde218/symfony/asset-mapper/6.4/manifest.json#L10 so it looks like it's possible to miss this directory.

### PR DESCRIPTION
**Pull request by alexislefebvre**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58858
| License       | MIT

~~I don't know how to add tests yet, because this method is private.~~

### CODE REVIEW

**Comment by smnandre** [comment]
Arf sorry.... i did not see it :( 

https://github.com/symfony/symfony/pull/58880

**Review by chalasr — APPROVED** [review]

**Comment by alexisLefebvre** [comment]
> Arf sorry.... i did not see it :(
> 
> #58880

Your PR relies on a simple mock, while my PR changes `$this->createFactory(…);`. Your test looks cleaner, should we use it in this current PR instead of changing `createFactory()`?

**Comment by smnandre** [comment]
> > Arf sorry.... i did not see it :(
> > #58880
> 
> Your PR relies on a simple mock, while my PR changes `$this->createFactory(…);`. Your test looks cleaner, should we use it in this current PR instead of changing `createFactory()`?

No idea  🤷  

But if you want to take anything from my closed PR you can of course :)

**Comment by alexisLefebvre** [comment]
> No idea 🤷
> 
> But if you want to take anything from my closed PR you can of course :)

Thanks for the feedback, let's see the opinions of the reviewers. :slightly_smiling_face:

**Comment by nicolas-grekas** [comment]
Thank you @alexislefebvre.

**Comment by nicolas-grekas** [comment]
Less mocks FTW

**Pull request merged**
