### PR TITLE
Fix HttpCache test

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | https://github.com/symfony/symfony/pull/22043#discussion_r107864054
| License       | MIT
| Doc PR        | n/a

will make appveyor green.

### CODE REVIEW

**Comment by chalasr** [comment]
The refactoring made in #22043 is not the cause, reverting it makes this test keep failing on windows.

**Comment by mheki** [comment]
Wouldn't be better to fix the error on Windows or create alternative test which won't break there, instead of skipping the test?

**Comment by chalasr** [comment]
Status: needs work

**Comment by chalasr** [comment]
Spent some hours at trying to debug it and I can't find the bottleneck, so keep skipping on windows as it runs fine on other platforms.

**Comment by chalasr** [comment]
Status: needs review

**Comment by fabpot** [comment]
Thank you @chalasr.

**Pull request merged**
