### PR TITLE
Add element to ghost in Exception

### PR DESCRIPTION
**Pull request by przemyslaw-bogusz**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Let's make love (& good code) not war. Sorry for not submitting it at least yesterday, but hopefully you will accept it, and we will be able to merge today. This will allow us to add different addons on other special ocasions.

zrzut ekranu 2019-02-14 o 09 53 42

On personal side, I dedicate it, with lots of kisses, to my wife Martha.

If you like it, just ❤️

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @przemyslaw-bogusz.

**Comment by przemyslaw-bogusz** [comment]
Thank you @fabpot. I will make a birthday ghost to celebrate Symfony's anniversary. Please tell me, on which day it should appear - October 18, or October 22?

**Comment by javiereguiluz** [comment]
Just sharing my opinion about this proposal: even if the idea is cute ... I wouldn't have merged this for several reasons, mainly:

* This code is super critical, because it deals with exceptions. It cannot fail, ever. The more code and features we add, the higher probability of failure.
* Symfony is a universal application. It's for every person, every country and every culture. Sadly there is not a single event shared universally by all people on Earth. Did you know that, [according to Wikipedia](https://en.wikipedia.org/wiki/Valentine%27s_Day#Celebration_and_status_worldwide), Valentine's Day is banned in countries like Iran and Saudi Arabia? Did you know that in some countries, such as Israel, it's celebrated on a different day? I'm afraid that people will suggest to add another ornaments, such as for Christmas ... which again, is not a universal festivity.

I'd agree with what you said in your last comment: showing something different on Symfony's birthday (which is considered to be: October 18th 2005 at 16:27:36). That's a truly universal and non-controversial event. But I wouldn't display any other event, so I'd remove the one merged in this PR. Thanks.

**Comment by nicolas-grekas** [comment]
To me, pretending to be universal shouldn't mean removing all the fun. Instead of removing, can't we add all "Valentine's" days?

**Comment by przemyslaw-bogusz** [comment]
@javiereguiluz I would just like to underline that I had no intensions of hurting anybody's beliefs or feelings. 

Althougth I take my job as a developer very seriously, I wanted to add a little fun and human touch to a great tool, which I - like most of us here - use almost every day. I thougth, that it would be nice, if hardcoding developer noticed something special about the exception message on a few selected occasions. I started with this one, because I believe it to be a universal message - I mean love in general, not just Valentine's Day.

As to the code itself, I don't believe that these few additional lines complicate it in a way, which would increase a chance of failure. Nevertheless, I am always open to any suggestions from an experienced developer and Symfony contributor like you. I have prepared a new addon to celebrate Symfony's anniversaries, and I am looking forward to your comments (#30326).

**Pull request merged**
