### PR TITLE
removed obsolete images (since 2.2)

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | yes-ish (those files are not used since 2.2) |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by fabpot** [comment]
Added a second commit that removes a sync script that is not used anymore (since the redesign of the web profiler).

**Comment by xabbuh** [comment]
What about adding this change to the upgrade file? Someone might reference them for whatever reason in their own code.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
@xabbuh good idea, I've just added the change to the CHANGELOG file (same in #19997 between).

**Comment by xabbuh** [comment]
@fabpot I think we should document these changes in `UPGRADE-3.2.md` too (but we can continue the discussion in #20014).

**Pull request merged**
