### PR TITLE
[5.0] set return type declartion to `self` instead of `object` when the type is `$this`

### PR DESCRIPTION
**Pull request by azjezz**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no  
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #32179
| License       | MIT

please see : https://github.com/symfony/symfony/pull/31996#discussion_r294063966

### CODE REVIEW

**Comment by azjezz** [comment]
cc @Tobion

**Comment by derrabus** [comment]
For the record: I‘m not 100% against this, but I‘m unsure, if this is a wise move as long as we need to support php version below 7.4. Using `self` as return type makes overriding those methods awkward. And moving such a method into parent class while maintaining BC is nearly impossible.

**Comment by nicolas-grekas** [comment]
Thank you @azjezz for opening.
I've the same opinion as @derrabus: we need a consistent policy for methods that return `static` or `$this`. It cannot be `self` to me, because as soon as inheritance is involved, you cannot move the signatures around easily anymore, as you need constant care to replace self by the corresponding FQDN, and vice-versa.
Technically, `object` will prevent us from returning `null` by mistake. `self` won't provide anything on top. Or: if you do the kind of mistakes that makes a difference between object and self here, your code is seriously doomed and you'll notice the first time you'll run it.

I'm for rejecting this PR and consistently using `object` in this situation.

**Comment by Tobion** [comment]
Closing then. phpstorm makes use of the `@return $this` anyway. So it does not matter much to me.

**Pull request closed without merging**
