### PR TITLE
Add tests for translated error messages of json authentication

### PR DESCRIPTION
**Pull request by malteschlueter**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | #33168
| License       | MIT
| Doc PR        | -

In PR #38037 i added the translator to the json authenticator but there are some tests missing. I added some now.

### CODE REVIEW

**Review by wouterj — APPROVED** [review]

**Comment by fabpot** [comment]
Tests for the low requirements must be fixed.

**Comment by wouterj** [comment]
Oh sorry, missed that test failure. For your information, this means that you should add a dev dependency on `symfony/translation` in the Http and Core security `composer.json` files.

**Comment by malteschlueter** [comment]
> Oh sorry, missed that test failure. For your information, this means that you should add a dev dependency on `symfony/translation` in the Http and Core security `composer.json` files.

Thanks for the tip.

I understand why to add it to the Http Security but why should i added it also to Core Security? I didn't changed anything in this "area".

**Comment by wouterj** [comment]
> I understand why to add it to the Http Security but why should i added it also to Core Security? I didn't changed anything in this "area".

My mistake (in my mind, all authentication listeners lived in Core, but most of them actually live in Http).

:+1: the remaining test failure is not caused by this PR

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @malteschlueter.

**Pull request merged**
