### PR TITLE
Add multiple badges into README

### PR DESCRIPTION
**Pull request by matks**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

This PR adds multiple badges into the README. Direct badge sources are Travis, and GitHub, and other badges are provided by http://shields.io/ and rely on data sources provided by GitHub, Appveyor and Packagist

Badges are really beautiful 🤩 but also can provide useful informations for people quickly browsing GitHub repositories. They provide popularity and usage KPI and links to the CI tools.

Other possible useful badges I could add in the PR (just tell me):
- link to the Symfony slack
- link to Symfony documentation
- link to Symfony website
But these would be static badges, not indicating a status / number, just clickable items.

You can see how it would look like by clicking on this link: https://github.com/symfony/symfony/blob/21a6fc51c0e8c412d5c46e341ce6d7f433ce66a4/README.md

### CODE REVIEW

**Comment by matks** [comment]
OK Appveyor tells me the build broke
```
OK src\Symfony/Bundle/SecurityBundle
PHPUnit 8.3.5 by Sebastian Bergmann and contributors.
Testing src\Symfony/Bundle/FrameworkBundle
...............E...............................................  63 / 900 (  7%)
............................................................... 126 / 900 ( 14%)
............................................................... 189 / 900 ( 21%)
............................................................... 252 / 900 ( 28%)
............................................................... 315 / 900 ( 35%)
............................................................... 378 / 900 ( 42%)
............................................................... 441 / 900 ( 49%)
............................................................... 504 / 900 ( 56%)
.....................SS........................................ 567 / 900 ( 63%)
............................................................... 630 / 900 ( 70%)
............................................................... 693 / 900 ( 77%)
................................................SS............. 756 / 900 ( 84%)
.............................................S................. 819 / 900 ( 91%)
............................................................... 882 / 900 ( 98%)
..................                                              900 / 900 (100%)
Time: 3.23 minutes, Memory: 158.00 MB
There was 1 error:
1) Symfony\Bundle\FrameworkBundle\Tests\Command\CacheClearCommand\CacheClearCommandTest::testCacheIsFreshAfterCacheClearedWithWarmup
Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "C:\projects\symfony\src\Symfony\Bundle\FrameworkBundle\Tests\Command\CacheClearCommand\Fixture/test": rmdir(C:\projects\symfony\src\Symfony\Bundle\FrameworkBundle\Tests\Command\CacheClearCommand\Fixture/test): Directory not empty
C:\projects\symfony\src\Symfony\Component\Filesystem\Filesystem.php:176
C:\projects\symfony\src\Symfony\Bundle\FrameworkBundle\Tests\Command\CacheClearCommand\CacheClearCommandTest.php:40
ERRORS!
Tests: 900, Assertions: 2549, Errors: 1, Skipped: 5.
KO src\Symfony/Bundle/FrameworkBundle
php phpunit src\Symfony\Component\HttpClient || SET X=!errorlevel!
#!/usr/bin/env php
```

Did I break the build with a change in the README 😁 ?

Is that some changes on Windows ? 🤔

**Comment by wouterj** [comment]
Please note that Symfony has already rejected badges multiple times in the past:

https://github.com/symfony/symfony/pull/8308#issuecomment-19685414
https://github.com/symfony/symfony/pull/21744#issuecomment-282238857

**Comment by fabpot** [comment]
Thanks for proposing. Closing as it has been rejected multiple times already.

**Comment by matks** [comment]
No worries, I understand 😊 thanks for fast answer !

**Comment by matks** [comment]
(on a sidenote, the issue in Ci might be worth looking at, I doubt changing the README was a valid reason for CI to complain)

**Pull request closed without merging**
