### PR TITLE
Add an auto_alias compiler pass

### PR DESCRIPTION
**Pull request by dawehner**
Discussion see https://github.com/symfony/symfony/issues/11460

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | [#11460] |
| License | MIT |
| Doc PR | symfony/symfony-docs#4992 |

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @dawehner.

**Comment by WouterJ** [comment]
Am I correct that this pass is not registered anywhere by default?

**Comment by xabbuh** [comment]
@WouterJ Yes, seems like this was missed.

**Comment by jean-pasqualini** [comment]
@wouterj @xabbuh @nicolas-grekas @fabpot 
Why do we keep this feature if it is not wired?

**Comment by xabbuh** [comment]
@jean-pasqualini The best is to open a new issue so this doesn't get lost again.

**Pull request closed without merging**
