### PR TITLE
[TwigBundle] Allow to exclude files and directories on cache warmup

### LINKED ISSUE #34142: [TwigBundle] TemplateCacheWarmer processes non-template files
**Symfony version(s) affected**: >= 2.8.0
(not sure exactly, probably as soon as the [`TemplateCacheWarmer` was introduced](https://github.com/symfony/symfony/commit/bd3701b30ff7675b2fd2bdeb4b4199760398d70b#diff-046da8074005c4646f865b4e68fcd36a))

**Description**  
The template cache warmer loads (lexes, compiles, ...) all files the default template iterator is listing. This may include images and other non-templates inside `/templates`, `/app/Resources/views`, any bundles resource paths and so on.

https://github.com/symfony/symfony/blob/60a4d8dc7ae91b55770102ff32a92c7b50717e49/src/Symfony/Bundle/TwigBundle/CacheWarmer/TemplateCacheWarmer.php#L47-L54

This can consume quite a lot of memory (and processing time). In fact for large files this fails completely. If you want to try this yourself do the following:

1. create a large dummy file inside your default template path (800MB in this example):
 `dd if=/dev/zero of=file.txt count=1024 bs=781250`
2. warm the cache: `bin/console cache:warm`
3. wait...

```bash
In Compiler.php line 129: Error:
Field width 3200000000 is too long
```

In my opinion it's wrong to include random files in the cache warming process. One could argue that putting those files inside the template/views folders is a bad practice to begin with but Symfony does so [as well](https://github.com/symfony/symfony/tree/4.4/src/Symfony/Bundle/TwigBundle/Resources/views/images) and it allows to include assets like so: `{{ include('@Twig/images/symfony-logo.svg') }}`. 

**Conclusion**
In theory every file **could** be a twig template that's content needs to be parsed but it **should** imo have a `.twig` file extension in this case. Like `mylogo.svg.twig` or `template.html5.twig`. (&larr; these files potentially aren't valid svgs or html5 documents and you'd probably have setup your IDE to enable Twig language support based on the file extension anyway)

**Possible Solution**  
Add a callback filter iterator or a condition inside the `TemplateCacheWarmer` that strips all files without a `.twig` extension before calling `$twig->load($template)`.

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #34142
| License       | MIT
| Doc PR        | -

So you can put any file/directory (not related to Twig's templates) in `templates/` dir and configure which files/directories can or cannot be warmed up, increasing the performance on 'cache:clear' (sometimes impossible).

Example of configurations:
```
twig:
    # include all *.twig files only
    cache_pattern_files: '*.twig'
    cache_pattern_files: '/\.twig$/' # same as above

    # include multiple files/extensions
    cache_pattern_files: ['*.twig', '*.svg'] # can be done in one regex too
    
    # exclude all *.png files only
    cache_pattern_files: '/.*(?<!\.png)$/'

    # exclude directory paths
    cache_exclude_paths: ['node_modules', '...'] # 'bundles' will always be excluded
```

**Backward Compatibility**

Unaffected! By default all files for all Twig's paths will be warmed up as well as the `'bundles'` directory will be excluded even if it's not added to the `cache_exclude_paths` option by the user.

It's up to you to decide the structure of your template directories and which files/dirs should or shouldn't be cached.

Replacement of https://github.com/symfony/symfony/pull/34321
Also related to https://github.com/symfony/symfony/issues/28282

wdyt?

### CODE REVIEW

**Comment by yceruto** [comment]
Note that I'm using `cache_pattern_files` option for both purposes (include/exclude), but we could separate it into two options `cache_include_files` and `cache_exclude_files` if you think it's more clear, calling to `$finder->names()` and `$finder->notNames()` methods respectively.

**Comment by fabpot** [comment]
I'm always very skeptical when we add new settings and when they are global.

The `templates/` directory is, well, for templates only. If people store something else, that's their responsibility, not ours. I'm :-1: for anything that allow people to store everything under the `templates` directory.

**Comment by m-vo** [comment]
But what's with things like this?
https://github.com/symfony/symfony/blob/4045a134df3cfd2356b0b5a9fae7e91ec16d5f7d/src/Symfony/Bundle/TwigBundle/Resources/views/layout.html.twig#L17

In a bare Symfony 4 installation with only twig installed I already get 28 templates and 64 'other' files including php templates and images.

<details>
  <summary>Details: list of loaded templates during cache warmup</summary>

```bash
"base.html.twig"
"@Framework/FormTable/hidden_row.html.php"
"@Framework/FormTable/button_row.html.php"
"@Framework/FormTable/form_widget_compound.html.php"
"@Framework/FormTable/form_row.html.php"
"@Framework/Form/form_rows.html.php"
"@Framework/Form/color_widget.html.php"
"@Framework/Form/integer_widget.html.php"
"@Framework/Form/form_widget_simple.html.php"
"@Framework/Form/button_widget.html.php"
"@Framework/Form/repeated_row.html.php"
"@Framework/Form/button_attributes.html.php"
"@Framework/Form/hidden_widget.html.php"
"@Framework/Form/money_widget.html.php"
"@Framework/Form/form_start.html.php"
"@Framework/Form/datetime_widget.html.php"
"@Framework/Form/form_rest.html.php"
"@Framework/Form/reset_widget.html.php"
"@Framework/Form/form_errors.html.php"
"@Framework/Form/form_enctype.html.php"
"@Framework/Form/form.html.php"
"@Framework/Form/form_end.html.php"
"@Framework/Form/widget_container_attributes.html.php"
"@Framework/Form/search_widget.html.php"
"@Framework/Form/widget_attributes.html.php"
"@Framework/Form/choice_attributes.html.php"
"@Framework/Form/hidden_row.html.php"
"@Framework/Form/email_widget.html.php"
"@Framework/Form/choice_widget_options.html.php"
"@Framework/Form/checkbox_widget.html.php"
"@Framework/Form/choice_widget.html.php"
"@Framework/Form/range_widget.html.php"
"@Framework/Form/attributes.html.php"
"@Framework/Form/url_widget.html.php"
"@Framework/Form/button_row.html.php"
"@Framework/Form/form_widget.html.php"
"@Framework/Form/textarea_widget.html.php"
"@Framework/Form/radio_widget.html.php"
"@Framework/Form/tel_widget.html.php"
"@Framework/Form/choice_options.html.php"
"@Framework/Form/collection_widget.html.php"
"@Framework/Form/form_help.html.php"
"@Framework/Form/choice_widget_expanded.html.php"
"@Framework/Form/button_label.html.php"
"@Framework/Form/submit_widget.html.php"
"@Framework/Form/date_widget.html.php"
"@Framework/Form/number_widget.html.php"
"@Framework/Form/form_label.html.php"
"@Framework/Form/percent_widget.html.php"
"@Framework/Form/container_attributes.html.php"
"@Framework/Form/choice_widget_collapsed.html.php"
"@Framework/Form/time_widget.html.php"
"@Framework/Form/form_widget_compound.html.php"
"@Framework/Form/form_row.html.php"
"@Framework/Form/password_widget.html.php"
"@Twig/base_js.html.twig"
"@Twig/Exception/exception_full.html.twig"
"@Twig/Exception/exception.css.twig"
"@Twig/Exception/error.html.twig"
"@Twig/Exception/traces_text.html.twig"
"@Twig/Exception/error.js.twig"
"@Twig/Exception/error.txt.twig"
"@Twig/Exception/exception.html.twig"
"@Twig/Exception/trace.txt.twig"
"@Twig/Exception/traces.html.twig"
"@Twig/Exception/exception.json.twig"
"@Twig/Exception/trace.html.twig"
"@Twig/Exception/exception.atom.twig"
"@Twig/Exception/traces.txt.twig"
"@Twig/Exception/exception.rdf.twig"
"@Twig/Exception/exception.js.twig"
"@Twig/Exception/exception.txt.twig"
"@Twig/Exception/error.css.twig"
"@Twig/Exception/exception.xml.twig"
"@Twig/Exception/error.atom.twig"
"@Twig/Exception/traces.xml.twig"
"@Twig/Exception/error.json.twig"
"@Twig/Exception/logs.html.twig"
"@Twig/Exception/error.rdf.twig"
"@Twig/Exception/error.xml.twig"
"@Twig/exception.css.twig"
"@Twig/layout.html.twig"
"@Twig/images/icon-minus-square.svg"
"@Twig/images/favicon.png.base64"
"@Twig/images/icon-plus-square.svg"
"@Twig/images/symfony-ghost.svg"
"@Twig/images/icon-book.svg"
"@Twig/images/chevron-right.svg"
"@Twig/images/icon-plus-square-o.svg"
"@Twig/images/icon-minus-square-o.svg"
"@Twig/images/icon-support.svg"
"@Twig/images/symfony-logo.svg"
```
</details>

In this case filtering for `.twig` would work but that's not guaranteed as long as doing otherwise is explicitly allowed/not deprecated. (also see https://github.com/symfony/symfony/issues/34142#issuecomment-546907328)

**Comment by yceruto** [comment]
Fair enough :+1:

**Comment by stof** [comment]
@m-vo in this case, this file **is** a template (`include` includes templates)

**Comment by m-vo** [comment]
You mean a template without any placeholders? That's an asset imho and that should not need to be parsed.

**Pull request closed without merging**
