### PR TITLE
Replace array|\Traversable by iterable

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Replace `array|\Traversable` by `iterable`, favoring pure API (or less mixed at least :)) and be clear whenever phpdoc is replaced.

https://secure.php.net/manual/en/language.types.iterable.php

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
is for 2.7

**Comment by ro0NL** [comment]
> Iterable is a pseudo-type introduced in PHP 7.1. 

Technically `iterable` is meaningless in 2.7 (php5.3), but im not sure you're being pragmatic? :)

**Comment by nicolas-grekas** [comment]
docblocks have no PHP version constraints

**Comment by ro0NL** [comment]
Done. `Symfony\Component\Cache\Traits\AbstractTrait::doFetch` left for 3.3

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request merged**
