### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by wnunezc**
Update composer.json

Replace of ^ with > suggested by composer standar doc:

https://getcomposer.org/doc/articles/versions.md#version-range

https://getcomposer.org/doc/articles/versions.md#hyphenated-version-range-

For the current version of the framework it doesn't make sense to use the semantic version.

| Q             | A
| ------------- | ---
| Branch?       | 6.4 for features 
| Bug fix?      | no
| New feature?  |no 
| Deprecations? | no 
| Tickets       | [ticket](https://github.com/symfony/symfony/issues/51422)
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by wnunezc** [comment]
lots of unrelated errors in unit test...

**Comment by nicolas-grekas** [comment]
Sorry this is wrong, see https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by wnunezc** [comment]
> Sorry this is wrong, see https://getcomposer.org/doc/articles/versions.md#caret-version-range-

you are implemente carret or up version instead?
https://getcomposer.org/doc/articles/versions.md#summary

**Comment by nicolas-grekas** [comment]
Caret is the semantics we want yes. I'm closing because there is nothing to fix here, we know caret works since years. Please use support channels if you need more help to understand why.

**Pull request closed without merging**
