### PR TITLE
[BrowserKit][DomCrawler] Relax return types needed for Symfony Panther

### PR DESCRIPTION
**Pull request by jordisala1991**
| Q             | A
| ------------- | ---
| Branch?       | 6.0 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Part of #43021, https://github.com/symfony/panther/pull/509 
| License       | MIT
| Doc PR        | N/A 

To make Symfony Panther compatible with Symfony 6 those types need to be
removed. Symfony Panther overrides those classes and it is compatible
with PHP 7.

Previous conversations:

https://github.com/symfony/panther/pull/509 (in this PR I am showing those changes applied as patches on composer directly)
https://github.com/symfony/symfony/issues/43021#issuecomment-955764741

### CODE REVIEW

**Comment by jordisala1991** [comment]
I might need some help to understand why this fails: https://github.com/symfony/symfony/runs/4175506921?check_suite_focus=true

**Comment by nicolas-grekas** [comment]
I proposed to bump panther to v2 instead, see  symfony/panther#509

**Comment by weaverryan** [comment]
I’m hearing a slight preference to make a v2 of this bundle. That would be my vote as well so we can move things forward. 

As far as a 1.x branch? We could decide on that later, but there is little harm to create one.

**Comment by jordisala1991** [comment]
Closing since it won't be needed.

**Pull request closed without merging**
