### PR TITLE
April Fools' Joke 2018

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | highly probable
| Deprecations? | guess yess
| Tests pass?   | work in progress
| Fixed tickets | 
| License       | MIT
| Doc PR        | todo

This PR fixes an old typo in the name of the project.

### CODE REVIEW

**Comment by Simperfit** [comment]
is Symphony a software to make music ?

**Comment by jeremyFreeAgent** [comment]
I can now apply to the jobs the recruiters sent me about that Symphony, thanks!

**Comment by rugabarbo** [comment]
There are so many joksters today: #26729 

laugh

**Comment by javiereguiluz** [comment]
Note: I've renamed this PR to indicate that it's an April Fools joke.

**Pull request closed without merging**
