### PR TITLE
bug #20653 [WebProfilerBundle] Profiler includes ghost panels

### PR DESCRIPTION
**Pull request by jzawadzki**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Fixed tickets | #20653 
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

Status: Reviewed

**Comment by patrick-mcdougle** [comment]
2.7?

**Comment by jzawadzki** [comment]
@patrick-mcdougle - I based PR on the branch which have the change that caused this bug, but bug itself is visible only in new profiler so it should be at least 2.8

**Comment by javiereguiluz** [comment]
👍 

I have tested this in the application and it solved the problem. Thanks @jzawadzki!

**Comment by fabpot** [comment]
Thank you @jzawadzki.

**Pull request merged**
