### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Adding a link to help framework users that happen to end up here.
See also https://github.com/symfony/symfony-docs/issues/14476

| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by ro0NL** [comment]
if anything, i suggest a `Framework Integration` link under `Resources. That's something we could add per component, without cluttering too much.

in the end components are independent, and shouldnt have any framework knowledge IMHO, however i appreciate a bit of cross linking

**Comment by fabpot** [comment]
The goal of the README is to document how to use it outside of the framework. I don't think we need to add anything here.

**Comment by ThomasLandauer** [comment]
> The goal of the README is to document how to use it outside of the framework

Yeah, sure, you know that. But the user doesn't!

**Comment by fabpot** [comment]
There is only one entry point for docs: symfony.com/doc. Nobody is really supposed to read these README files.

**Comment by ThomasLandauer** [comment]
> Nobody is really supposed to read these README files.

Well, open https://symfony.com/components/Stopwatch and click on the "Documentation" link (right sidebar). The link URL is https://symfony.com/doc/current/components/stopwatch.html but guess where it's being redirected to? Right to this README here ;-)

The general problem with components' docs is that you change your strategy too often, and don't make that obvious to the user. Let me show you:
* https://symfony.com/doc/4.4/components/index.html looks like a *complete* list of components. But Stopwatch is missing. Why?
* On the other hand, if you look at https://symfony.com/components/Stopwatch there's *zero* information for framework users. Why?

That's why I suggested some general changes at https://github.com/symfony/symfony-docs/issues/14476#issuecomment-716529048

**Pull request closed without merging**
