### PR TITLE
[Translation] drop MessageSelector support in the Translator

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
The failure seems to be related to a commit hash that was not propagated from the subtree split of the Translation component to packagist.org.

**Comment by fabpot** [comment]
I've updated Packagist, is it better now?

**Comment by xabbuh** [comment]
finally, Travis CI got that change too

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by flip111** [comment]
This breaks stuff in Silex

https://github.com/silexphp/Silex-Providers/blob/1a9753e0bd7ef1efe619a1ea7ac13d003ebf50f2/TranslationServiceProvider.php#L38

**Comment by xabbuh** [comment]
@flip111 not sure what you mean, this PR is precisely tagged as a BC break because we removed things that were deprecated before

**Comment by flip111** [comment]
Yes that's fine, i'm just making a comment as cross-reference ...

**Comment by xabbuh** [comment]
Please abstain from doing so. This just causes unnecessary noise for everyone having subscribed to the Symfony repository.

**Pull request merged**
