### PR TITLE
[Intl] Update the ICU data to 65.1

### LINKED ISSUE #33548: [Intl] ICU 65 release
ICU 65 RC was just released (https://github.com/unicode-org/icu/releases/tag/release-65-rc)

> ICU 65 updates to CLDR 36 locale data with many additions and corrections

Based on the previous releases, i think we can expect a stable release this month or so. We might test the impact already though ...

> Please test this release candidate on your platforms and report bugs and regressions by Tuesday, 2019-sep-24.

I figure https://github.com/jakzal/docker-symfony-intl also needs a patch first. cc @jakzal 

Created this reference ticket for now.

### PR DESCRIPTION
**Pull request by jakzal**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33548
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by jakzal** [comment]
Status: needs work

Some `intl-data` tests are failing.

**Comment by ro0NL** [comment]
thanks :) (we should not forget to re-compile per branch)

**Comment by jakzal** [comment]
status: needs review

All tests are passing now.

image

**Comment by jakzal** [comment]
Unfortunately, there **will** be lots of conflicts when merging this to 4.3. I'm fine to resolve them.

**Comment by nicolas-grekas** [comment]
Thank you @jakzal 
I merged this PR in 3.4 then 4.3 but I ignored all conflicts.
PR welcome on 4.3 now.

**Comment by jakzal** [comment]
On it! :)

**Pull request merged**
