### PR TITLE
Use hirak/prestissimo ^0.2

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
We should wait for a new release that includes hirak/prestissimo#88 to not get the error we get right now on AppVeyor.

**Comment by nicolas-grekas** [comment]
@xabbuh version raised to dev-master

**Comment by keradus** [comment]
@nicolas-grekas 

`hirak/prestissimo` is there with `0.3.1`, maybe it's time when we could reconsider using it ?

**Comment by nicolas-grekas** [comment]
@keradus feel free to open a PR :)

**Comment by keradus** [comment]
Here you go @nicolas-grekas : #20230 ;)

**Pull request closed without merging**
