### PR TITLE
[DependencyInjection] fix PHP 8 compatibility

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
According to the failing test `gettype()` now returns `bool` instead of `boolean` as it was in 8.0.0 and before.

**Review by jderusse — APPROVED** [review]

**Review by derrabus — APPROVED** [review]
🤔

**Comment by wouterj** [comment]
According to https://3v4l.org/Lf7H1 , `gettype()` always returns `boolean`. Looking at https://wiki.php.net/rfc/get_debug_type , it seems like the `bool` return value is coming from `get_debug_type()`. We're using `get_debug_type()` (or it's polyfill) since 5.1 (ref daf1c6605eb3571e2176c46281acba36b37cf536).

In my understanding, this means that we should test for `boolean` in the 4.4 branch, and `bool` in 5.1+ branch. This also explains why the build passes on 4.4, but doesn't on 5.1.

**Comment by xabbuh** [comment]
Thanks for checking Wouter. That explains it perfectly.

**Comment by derrabus** [comment]
Should we use `get_debug_type()` on 4.4 as well to make our lives easier? 🤔

**Comment by wouterj** [comment]
I'm also wondering why 5.1+ only failed on PHP 8 and not on PHP 7.4 or lower. As it's using `get_debug_type()`, PHP 8 should use the functionality of PHP, and PHP <=7.4 should use [the polyfill](https://github.com/symfony/polyfill/blob/main/src/Php80/Php80.php) which is using `bool` as well.

**Pull request merged**
