### PR TITLE
[Config] Only using filemtime to check file freshness

### PR DESCRIPTION
**Pull request by dmifedorenko**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25999
| License       | MIT

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
I'm ok for merging this in 3.4: this is not a bug fix, but a DX fix. Let 2.7/2.8 in peace now, with real fixes only. OK for you?

**Comment by sroze** [comment]
Looks good 👍

**Comment by Tobion** [comment]
While I agree it makes sense to do this with one call, there will be alot of people reporting the silenced errors again. See https://github.com/twigphp/Twig/pull/1866 and related tickets.

**Comment by nicolas-grekas** [comment]
@Tobion I wondered the same - but this should happen only in dev, when the cache is rebuilt. Not sure it's a real issue. Would you consider this a no-go?

**Comment by dmifedorenko** [comment]
@Tobion https://github.com/twigphp/Twig/pull/1866 is very strange issue. We use "@" before filemtime to mute all error, and it work in default php's error handler. If custom error handlers dont check error level of error and rice error event even code called with "@" this is problem of error handler, not framework components code.

I search for regexp @[^\s]+\( on framework's source code and found more then 500 calls with muted errors. So Symfony has tons of calls with @, shall we rewrite them all according to https://github.com/twigphp/Twig/pull/1866?

image

**Comment by Tobion** [comment]
@dmifedorenko symfonys debug error handler logs all silenced errors. The other silenced operator usages usually never happen, they are just silenced as a safe guard against the PHP warnings generated. But this change here will likely trigger these silenced errors alot. This is what happened in the referenced twig tickket. And when it happens alot, people will complain. And they will not know, that this is intended and does not need a fix.

@nicolas-grekas If we accept these silenced errors we probably need a way to tell people that this is an acceptable warning. Like explaining that in the web profiler in the silenced errors tab.

**Comment by dmifedorenko** [comment]
> symfonys debug error handler logs all silenced errors

Why so?

**Comment by nicolas-grekas** [comment]
I just tried: the notice is invisible in practice, so there is no issue at all. I suppose the reason why it is invisible is because it is thrown pre compile time, at a moment where things are not bootstrapped enough.

So let's do that change on my side.

**Comment by nicolas-grekas** [comment]
Thank you @dmifedorenko.

**Pull request merged**
