### PR TITLE
Update es.php

### PR DESCRIPTION
**Pull request by Gonzalo1987**
| Q             | A
| ------------- | ---
| Branch?    |   5.4 and forward 
| Bug fix?  |    yes
| New feature?  | no 
| Deprecations?  | no 
| Issues        | 
| License       | MIT

Minor fix on the Ivory Coast translation to 'es'

### CODE REVIEW

**Comment by ro0NL** [comment]
it's upstream data ;) it should be commented on-top in the artifact files.

for reference, it's related to `es` vs `es_419` locales. Im not sure the fix is correct.

https://github.com/unicode-org/icu/blob/a7c7d8f214926ef23d2b54500ab77d95e5ea0068/icu4c/source/data/region/es.txt#L81

https://github.com/unicode-org/icu/blob/a7c7d8f214926ef23d2b54500ab77d95e5ea0068/icu4c/source/data/region/es_419.txt#L23

**Comment by ro0NL** [comment]
the parent locales are also dealt with:

https://github.com/symfony/symfony/blob/5bdf2f0aca06f1e91b633d75e66e06b31bb4205d/src/Symfony/Component/Translation/Resources/data/parents.json#L98

but perhaps the issue is related to #31348

**Comment by stof** [comment]
those files must not be edited manually. They are generated from the upstream data and any manual change would be lost on the next run of the command.

**Comment by gonzalo1987** [comment]
Thank you very much! I'll try to PR in the upstream so.

**Pull request closed without merging**
