### PR TITLE
[Contracts] closure to arrow functions

### PR DESCRIPTION
**Pull request by ibrahimBougaoua**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License      | MIT

Refactor some closure to arrow functions

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Works for me, but please mind the CS (see fabbot job)

**Comment by OskarStark** [comment]
@nicolas-grekas I fixed the CS

**Review by OskarStark — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you Ibrahim and congratulations on your first contribution to the Symfony codebase :tada:

**Comment by ibrahimBougaoua** [comment]
> Thank you Ibrahim and congratulations on your first contribution to the Symfony codebase 🎉

Thanks,  It is my pleasure.

**Pull request merged**
