### PR TITLE
[Form] Applying bug #18935 fix (done only on symfony/form)

### PR DESCRIPTION
**Pull request by Ghriim**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes (only for the behavior)
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | symfony/form #11493
| License       | MIT
| Doc PR        | see https://github.com/symfony/form/commit/8502f30310c3bc0294d4c3e98f271c83bf89a210)

### CODE REVIEW

**Comment by HeahDude** [comment]
This is a duplicate of https://github.com/symfony/symfony/pull/18935 which has been reverted.

Sadly we cannot afford this bc break, prepopulating data in a form does not belong to the scope of its validation if it is not submitted.

Btw, calling `$form->isValid()` without calling `$form->isSubmitted()` first has been deprecated in 3.2, so this can be more consistant.

**Comment by Ghriim** [comment]
I've discover this bug fix from this ticket https://github.com/symfony/symfony/issues/11493
Is their any work around for PATCH context if the fix on ViolationMapper is finally reverted ?

**Comment by HeahDude** [comment]
@Ghriim `$this->get('validator')->validate($form->getData())` should be enough to avoid persisting wrong data ;), but you'll have to handle errors yourself though.

**Comment by xabbuh** [comment]
Can you confirm that the changes proposed in #30265 will fix this issue?

**Pull request closed without merging**
