### PR TITLE
[Translator][fallback catalogues] fixed circular reference.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | ~ |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by kimausloos** [comment]
This fixes issue #15522

**Comment by aitboudad** [comment]
@symfony/deciders can someone review please :)

**Comment by stof** [comment]
what happens if you defined ``array('fr', 'en')`` as fallback locales and you load either fr or en as fallback locales. what would be the fallbacks for each of them ?

**Comment by aitboudad** [comment]
@stof 
fr -> en as fallback
en -> fr as fallback

**Comment by stof** [comment]
well, this looks weird to me though, as the fr fallback of en will be different from the fr catalogue used anywhere else. But it is indeed one of the possible implementations. the other one could be to consider that ``en`` does not fallback to anything here, as it is itself the last fallback locale.

Anyway it is a different topic (and a behavior change, so not for 2.3), so it should be discussed separately.

:+1: for this
status: reviewed

**Comment by fabpot** [comment]
Thank you @aitboudad.

**Comment by c960657** [comment]
I believe this caused a regression: #17596

**Pull request merged**
