### PR TITLE
[WebServerBundle] Mark ServerCommand as internal

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/22758#discussion_r117748941
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by fabpot** [comment]
Closing in favor of #22871

**Comment by Koc** [comment]
Looks like something wrong with travis or packagist or network. Have similar problems with builds

**Comment by nicolas-grekas** [comment]
https://twitter.com/packagist/status/866952618349920257

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
