### PR TITLE
[Validator] Missing translations for Brazilian Portuguese (pt_BR)

### LINKED ISSUE #41812: Missing translations for Brazilian Portuguese (pt_BR)
Hello,

There are some missing translation for Brazilian Portuguese (pt_BR). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Validator/Resources/translations/validators.pt_BR.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.pt_BR.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by rezendus**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Fixed tickets       | #41812 
| License       | MIT

[Validator] Missing translations for Brazilian Portuguese (pt_BR)

### CODE REVIEW

**Comment by rezendus** [comment]
@anararo could you please review it :)

**Review by AnaRaro — APPROVED** [review]
Looks good! 👍

**Review by cenoura — APPROVED** [review]
Thank you for contributing, @rezehnde 

LGTM

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @rezehnde.

**Pull request merged**
