### PR TITLE
[Form] Button icon

### PR DESCRIPTION
**Pull request by girayk**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #...
| License       | MIT

**Icon attr for Form Buttons
usage:**
```
->add('submit', SubmitType::class, array(
 'icon' => "fa fa-home"
))

 ->add('submit', ButtonType::class, array(
 'icon' => array(
   'name' =>  'fa fa-home',
   'align' =>  'right',
   'space' =>  3
 ),
))

 ->add('submit', ButtonType::class, array(
 'icon' => array(
   'name' =>  'fa fa-2x fa-home',
   'space' =>  0
 ),
 'label' => false
))
```

### CODE REVIEW

**Comment by girayk** [comment]
@lyrixx I used font awesome on the example, there is no any specific implementations.
can use with any web-fonts

**Comment by lyrixx** [comment]
That's my point sorry. It's really tight to web-font implementation.
For exemple, it will not work with SVG sprites / image

**Comment by girayk** [comment]
yes it's only for font icons, icons are using i or span elements,
IMHO SVG sprite can be another feature.

**Comment by ro0NL** [comment]
maybe `"icon" => new HtmlIcon('class', $otherStuff)` vs. `new Icon('☺')` vs. `new SvgIcon('file.svg')`

but this can be a custom extension/theme as well :confused: not sure it belongs to core.

**Comment by girayk** [comment]
@ro0NL your link is similar to what I did but icon_before, icon_after are not logical variable names for symfony structure for my opinion, instead, "icon" is more memorable.
also, new classes are sounds logical but I have no idea, where to create this classes,
I think I need someone to tell me, what I have to do 😕

**Comment by fabpot** [comment]
I tend to agree with @ro0NL that this probably does not belong to core but more suited for a custom theme.

**Comment by drspct** [comment]
The solution with label_html and label is completely sufficient, but unfortunately, the UX icons are not rendered.
example: `...->add('submit', SubmitType::class, ['label_html' => true, 'label' => '<twig:ux:icon name="fa:sign-in" /> Log in'])`

**Comment by OskarStark** [comment]
Please open a new issue, thanks

**Pull request closed without merging**
