### PR TITLE
[Translation] Fixes typo in comment

### PR DESCRIPTION
**Pull request by jschaedl**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? |no 
| Tests pass?   | yes    
| Fixed tickets | -   
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
What's the lowest branch where the typo exists?

**Comment by jschaedl** [comment]
> What's the lowest branch where the typo exists?

It's `2.8`: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Translation/Util/ArrayConverter.php

**Comment by jschaedl** [comment]
@nicolas-grekas Should this fix go into 3.4 then?

**Comment by jschaedl** [comment]
https://github.com/symfony/symfony/pull/31343

**Pull request closed without merging**
