### PR TITLE
Use Symfony "dark-mode"-responsive logo in README

### LINKED ISSUE #53105: [DX] Symfony logo in dark mode
I find the white square around the logo a bit rought, and would like to suggest a little modification that would improve the look of all the README pages

* on github.com
* in your IDE (phpstorm there)

And the good news is ... there is only one file to update :) 

## What it could render

dark-mode

### Github.com

| Before | After |
| - | - |
| before-readme | after-readme |

### phpstorm

| Before | After |
| - | - |
| before-phpstorm | after-phpstorm |

## How can it be done

The good news is that you would just have to update the logo file which is linked in all those README : 

```md
<p align="center"><a href="https://symfony.com" target="_blank">
    <img src="https://symfony.com/logos/symfony_black_02.svg">
</a></p>
```

By adding a couple of lines of CSS in the SVG, the logo can be modified depending on the user dark/light mode

Let's use a simplified SVG code for the Symfony logo 

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 288 122">
  <path id="circle" d="..."/>
  <path id="sf" fill="#fff" d="..."/>
  <path id="symfony" d="..."/>
</svg>
```

### Solution 1 : Filter Invert

If you want to get a quick win, you can simply invert the image via the invert filter

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 288 122">
  <style>
    @media (prefers-color-scheme: dark) { 
      path { filter: invert(1) }
    }
  </style>
  <path id="circle" d="..."/>
  <path id="sf" fill="#fff" d="..."/>
  <path id="symfony" d="..."/>
</svg>
```

### Solution 2 : Manual override

Personnaly, i'd rather write things explicetly, so you could do it like that too (or in a dozen of other ways i guess... 😅 )

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 288 122">
  <style>
    @media (prefers-color-scheme: dark) { 
      path { fill: #fff; }
      #sf { fill: #000; }
    }
  </style>
  <path id="circle" d="..."/>
  <path id="sf" fill="#fff" d="..."/>
  <path id="symfony" d="..."/>
</svg>
```

--- 

What do you think ?

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #53105 
| License       | MIT

Following #53105 @javiereguiluz [uploaded](https://github.com/symfony/symfony/issues/53105#issuecomment-1915193582) a Symfony "dynamic" logo, featuring a color scheme that adapts to user preferences. 

This enhancement allows the README's logo to appear sharper and cleaner in dark mode (on Github.com, in PHPStorm, ...)

```diff
<svg>
    <style>
+        @media (prefers-color-scheme: dark) {
+            .symfony-logo-circle, .symfony-logo-letter { fill: #fff; }
+            .symfony-logo-circle-letters { fill: #000; }
        }
    </style>
    <!-- SVG code -->
</svg>
```
| Before | After |
| - | - |
| before_dark | after_dark |

( Thank you again @javiereguiluz )

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @smnandre.

**Comment by antonkomarev** [comment]
In the official mobile app. Android with dark mode interface.

**Comment by smnandre** [comment]
@antonkomarev could you try on the 5.4 branch just to be sure ?

**Comment by derrabus** [comment]
On my iPhone:

#### GitHub app

image

#### Safari

image

Both screenshots show the 5.4 branch, but it's the same on 7.1.

**Comment by smnandre** [comment]
> Both screenshots show the 5.4 branch, but it's the same on 7.1.

Just to be complete, could you show how it renders in light mode ?

**Comment by derrabus** [comment]
Certainly!

image

image

**Pull request merged**
