### PR TITLE
Fix code examples in PHPDoc

### PR DESCRIPTION
**Pull request by maidmaid**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

This PR properly indents the code examples in PHPDoc for a clean render.

### CODE REVIEW

**Comment by maidmaid** [comment]
Annex question: many ways are currently used to make a code examples in PHPDoc, namely 4 spaces of indentation, `<code>` tag and markdown syntaxe. Would it be interesting to standardise that or not at all ?

**Comment by fabpot** [comment]
I would standardize to using 4 space indentation (which is Markdown right?).

**Comment by maidmaid** [comment]
Markdown is different from 4 spaces indentation. An example here :

https://github.com/symfony/symfony/blob/6c539e1408769e3de8766d238b11770c95e016a5/src/Symfony/Component/OptionsResolver/OptionsResolver.php#L413-L417

Do I standardize it in this PR ?

**Comment by fabpot** [comment]
That's not Markdown, but something added by Github. Anyway, 4 spaces indentations seems the best to me. If you can do it in this PR, that would be wonderful. I think that we also need to update the docs regarding our CS.

**Comment by maidmaid** [comment]
Done : 4 spaces indentation used everywhere now.

> I think that we also need to update the docs regarding our CS.

Btw, a new php cs fixer rule could be interesting here.

**Review by fabpot — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by maidmaid** [comment]
@keradus Some of the code examples were like normal text description and it broke the PHPDoc render.

**Comment by keradus** [comment]
Still, docs only, nothing that is not working for Sf users in their project and now will be fixed for them.
label was automatically assigned only as there was a keyword in PR title ;)

nothing to focus on, just saying

**Review by nicolas-grekas — APPROVED** [review]

**Pull request merged**
