### PR TITLE
[Mime] Added MimeType for "msg"

### PR DESCRIPTION
**Pull request by libertjeremy**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
Although this is not in the lists that we use to generate the list of MIME types ... I've looked up and it seems like a commonly enough used extension + MIME type.

So, I think we should add it (and, according to https://github.com/symfony/symfony/blob/ddee23f2f856b1da568e0e7786be8c401e294082/src/Symfony/Component/Mime/Resources/bin/update_mime_types.php#L65, the script we use to update the MIME types from time to time won't delete this entry added manually).

**Review by maxhelias — APPROVED** [review]

**Comment by fabpot** [comment]
Can you point us to an official source for that association?

**Comment by javiereguiluz** [comment]
Here's a reliable source about this: https://www.loc.gov/preservation/digital/formats/fdd/fdd000379.shtml

**Comment by fabpot** [comment]
I'm not very comfortable with this PR as `.msg` seems very generic. Why isn't it in the official list we get from Apache?

**Comment by javiereguiluz** [comment]
Yes, this is tricky. For what is worth, here's some Apache source code using this MIME type: https://github.com/search?q=org%3Aapache+application%2Fvnd.ms-outlook&type=Code

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Merging to master as a new feature.

**Comment by fabpot** [comment]
Thank you @libertjeremy.

**Pull request merged**
