### PR TITLE
fix Validator dependencies for tests

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
I'm really not convinced that this is the right way to fix the tests. The problem is 5aa44eec3d9b87e8017549f5b228b0a2a8b3e3d6 which removed the handling of the 2.4 validation API from the `AbstractConstraintValidatorTest` class.

**Comment by fabpot** [comment]
I'm not comfortable as this is really just about making the tests pass and not something that is required in real-life.

What do you think about this @nicolas-grekas?

**Comment by xabbuh** [comment]
I see to alternative solutions to make the tests pass again:

* revert the changes from 5aa44eec3d9b87e8017549f5b228b0a2a8b3e3d6 for the `AbstractConstraintValidatorTest`
* copy the state the test class had before that commit into the affected components

What do you think about that?

**Comment by stof** [comment]
the issue with your commit is that the code of the 2.4 API level is still there, so people instantiating it directly will still be using it (Silex 1.2.0 for instance), but you removed all testing against this API level.

**Comment by xabbuh** [comment]
@stof Which solution do you suggest?

**Comment by stof** [comment]
@xabbuh the tests for the 2.4 API level should be re-added in the testsuite (we are keeping the tests for our other BC layers too)

**Comment by fabpot** [comment]
see #13511

**Pull request closed without merging**
