### PR TITLE
Revert "[Command] fix emojis messing up the line width"

### LINKED ISSUE #40634: [console] Table grid offset bug
**Symfony version(s) affected**: 5.2.6

**Description**
Seems like console table has offset issue with latest Symfony;

symfony/console 5.2.5:
image

symfony/console 5.2.6:
image

It seems like to be related to custom styles inside table.

I created simple example repository to demonstrate this bug - https://github.com/tarlepp/symfony-console-bug

### PR DESCRIPTION
**Pull request by Nyholm**
This reverts commit 36b36dcecc8223b8f3d02c6c463a9a2dbf48ff90.

| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | 
| Tickets       | Fix #40634, fix #40635
| License       | MIT
| Doc PR        | 

PR #40524 cause a few regressions. There is a confusion between string "length" and string "width". This is sorted out in #40695. 

I suggest reapply this commit on 5.x instead.

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
This patch was a step in the right direction. Merging it on 5.x won't make it less a regression for the referenced issue, unless we also fix the issue with width vs length, which then would be a bugfix, thus on 5.2 too. :)

What I mean is that I'm fine reverting, but the new patch would still be a fix, thus for 5.2 as of today.

**Comment by Nyholm** [comment]
See this as an alternative approach: https://github.com/symfony/symfony/pull/40698

**Comment by chalasr** [comment]
Closing in favor of #40698.

**Comment by Nyholm** [comment]
Thank you

**Pull request closed without merging**
