### PR TITLE
[Security] Don't log AccessDecisionManager decision when decide is called from inside a voter

### PR DESCRIPTION
**Pull request by l-vo**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Since version 3.0, `AccessDecisionManager::decide` can be called from inside a voter. When doing so, the result of `decide` from inside
the voter is displayed in the profiler at the same place as the results of the decisions called via `isGranted`. From my point of view, it's confusing.

Let's imagine we call `isGranted` once in a controller action. If one of the implicated voters calls `AccessDecisionManager::decide`, we'll have two decision results in the profiler. But only the last result is the decision for `isGranted`. The first result is only a part of this decision, with no more importance than any one of the implicated voters.

This PR allows to not display decision results which are called from inside a voter.

### CODE REVIEW

**Comment by iltar** [comment]
> The first result is only a part of this decision, with no more importance than any one of the implicated voters.

If I understand this correctly, that means it will not show 3 but 2 results?

**Comment by l-vo** [comment]
It will not show 2 but 1 result :)

Considering a voter:
```php
class DummyVoter extends Voter
{
    private $adm;

    public function __construct(AccessDecisionManagerInterface $adm)
    {
        $this->adm = $adm;
    }

    protected function supports($attribute, $subject)
    {
        return $attribute == 'myattr';
    }

    protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        return $this->adm->decide($token, ['ROLE_USER']) /* && Some other stuff */;
    }
}
```

And a controller action:
```php
class DefaultController extends Controller
{
     //...
    public function indexAction()
    {
        if ($this->isGranted('yes')) {
            // Some stuff
        }

        return new Response();
    }
    // ...
}
```
At this time, the profiler shows:
capture d ecran 2018-10-15 a 12 50 29

The first line with `ROLE_USER` is actually a part of the decision displayed in the second line. So my PR propose to modify this behavior for displaying instead:
capture d ecran 2018-10-15 a 12 51 27

**Comment by iltar** [comment]
I don't like this, it's effectively hiding an important part of the authorization process. Perhaps it would be more valuable to show it as a tree view, but it should _definitely_ stay visible.

**Comment by l-vo** [comment]
IMHO It's not always an important part of the authorization process. My voter could be:
```php
class DummyVoter extends Voter
{
    private $adm;

    public function __construct(AccessDecisionManagerInterface $adm)
    {
        $this->adm = $adm;
    }

    protected function supports($attribute, $subject)
    {
        return $attribute == 'myattr';
    }

    protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        $cond2 = true;
        $cond3 = false;
        $cond4 = true;

        return ($this->adm->decide($token, ['ROLE_USER']) || $cond2) && ($cond3 || $cond4);
    }
}
```
With this display:
capture d ecran 2018-10-15 a 13 22 02

The line 1 shows `denied` but finally the voter returns `granted` (and the ADM finally returns `granted` too). Why is it more important to display the result of `$this->adm->decide($token, ['ROLE_USER'])` than those of `$cond2`, `$cond3`, `$cond4` ?

**Comment by iltar** [comment]
If you can show that (A) is a part of the voting process of (B), that's fine. Imo this is already symptom of voters using voters, which to be sounds like a wrong design.

**Comment by nicolas-grekas** [comment]
@iltar your recommendation is then to reject this PR? @l-vo any comment before that happen?

**Comment by xabbuh** [comment]
Is this still a thing given the improvements made in 4.2?

**Comment by iltar** [comment]
I haven't tried the latest Symfony versions, so I can't comment on that part. @nicolas-grekas not necessarily reject, I just like to point out that this might obfuscate important information

**Comment by l-vo** [comment]
@xabbuh it's still relevant today, the changes of the profiler handle the case where decision manager is called inside a voter.
@iltar related to your previous comment, I can't show that a decision is a part of a voter result. With the improvements done in 4.2, it might lead to a too complex UI.
@nicolas-grekas I understand @iltar point of view even if mine is different. If you think this change is not relevant, you can close the PR :)

**Comment by xabbuh** [comment]
Rereading the description I am 👎 here. This section of the profiler is called "access decision log". Not displaying all decisions being made here is too confusing from my point of view.

**Comment by chalasr** [comment]
Closing as explained, thank you for submitting @l-vo.

**Pull request closed without merging**
