### PR TITLE
[Monolog Bridge] Fixed accessing static property as non static.

### LINKED ISSUE #34505: [Monolog Bridge] ErrorException: Accessing static property $sendHeaders as non static
**Symfony version(s) affected**: 4.4
The problem started after updating SF4.3 to 4.4 but I'm not really sure why earlier versions would not be affected. I am running php 7.3.11.

**Description**  
When using the ``ChromePHPHandler`` the following error may occur:

> Notice: Accessing static property Symfony\Bridge\Monolog\Handler\ChromePhpHandler::$sendHeaders as non static in ChromePhpHandler.php line 62

To replicate add the following to the monolog configuration: 
```yaml
monolog:
    handlers:
        chromephp:
            type: chromephp
            level: debug
```

I think we can replace the `$this->sendHeaders` on lines 44 and 62 with `self::$sendHeaders` without any problem since the ``sendHeaders`` property is static in both version 1.25.1 and 2.x of monolog. 

PR is on its way.

### PR DESCRIPTION
**Pull request by Sander-Toonen**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  |  no
| Deprecations? | no
| Tickets       | Fix #34505
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by fancyweb — APPROVED** [review]

**Review by xabbuh — CHANGES_REQUESTED** [review]
The commit that changed the property to `static` (Seldaek/monolog@e0d18f454be4b149e528ade4a6852cf2493f4302) was first released in Monolog 1.4.0. I think we should bump the requirement for `monolog/monolog` in `composer.json` accordingly.

**Comment by Sander-Toonen** [comment]
Isn't the requirement for `symfony/monolog-bridge` already ^1.25.1 and therefore greater than 1.4.0?

**Review by xabbuh — APPROVED** [review]
Sorry, that was my mistake. I misread `1.4.0` as 1.40`.

**Review by xabbuh — APPROVED** [review]
Sorry, that was my mistake. I misread `1.4.0` as 1.40`.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
So, this one should be merged in 3.4, right?

**Comment by fabpot** [comment]
Thank you @Sander-Toonen.

**Pull request merged**
