### PR TITLE
[Intl] Fix intl tests for PHP < 5.5.10

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Should fix tests in upper branches (see https://github.com/symfony/symfony/pull/22760).

### CODE REVIEW

**Comment by ogizanagi** [comment]
Everything is green. Ready.

**Comment by jakzal** [comment]
How did you manage to make these tests fail? For me, they're either passing or are skipped on PHP < 5.5. Travis doesn't report failures either.

Anyway, I'm against adding PHP version checks to test against different values. Especially that this is caused by a (fixed) PHP bug. It only make tests harder to maintain and read. I'd rather skip some tests for older PHP versions as we'll be phasing them out eventually.

👎

**Comment by ogizanagi** [comment]
> How did you manage to make these tests fail? For me, they're either passing or are skipped on PHP < 5.5. Travis doesn't report failures either.

Just give a look to recent builds on AppVeyor on PR targeting >= 3.2 branches as it require php <= 5.5.9 (and AppVeyor Php version used is 5.5.9, which indeed contain the bug)...

So yes, we can skip them entirely instead.

**Comment by jakzal** [comment]
I see you already noticed what [I was doing](https://github.com/symfony/symfony/pull/22767/files) and updated your PR accordingly. We only need one PR for 2.7.

**Comment by ogizanagi** [comment]
You're right. I closed #22760.

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
It used to work, and we support 5.5.9 as lowest version - I don't get this change.

**Comment by ogizanagi** [comment]
We do support 5.5.9 as lowest version, but the test is not meant to cover a buggy behavior which has been fixed since. Hence excluding php 5.5.9.

@jakzal explained everything by giving some examples in https://github.com/symfony/symfony/pull/22627 description and https://github.com/symfony/symfony/pull/22627#issuecomment-300431128. But trying to shorten it: 
Everything was working fine previously, because php used to convert GMT to UTC implicitly (the forehead mentioned bug), while before ICU 59.1 using UTC would output "GMT". 
With ICU 59.1, it'll output "UTC".

Hence, @jakzal rightly pointed me out this was identified as a bug and we shouldn't cover it, so we excluded the buggy version for those test cases.

**Comment by fabpot** [comment]
Thank you @ogizanagi.

**Pull request merged**
