### PR TITLE
Add a donation section in the README with a Bitcoin address 

### PR DESCRIPTION
**Pull request by JeremieSamson**
| Q             | A
| ------------- | ---
| Branch?       | master  
| Bug fix?      | no
| New feature?  |no 
| Deprecations? | no 
| Tickets       | N/A 
| License       | MIT
| Doc PR        | N/A 

Hello there, 

As a crypto fan, I would love to see a Bitcoin address inside the readme to support the SF project. 
I didn't know how to suggest this, so I just added this line here. Didn't see neither another PR talking about donation.

And of course the bitcoin address has to be created by the team to get the private keys (Not your keys not your coins).

### CODE REVIEW

**Comment by patrickbussmann** [comment]
Haha nice 😅
Maybe some other ideas, too - like contributing.

Or link to Blog: https://symfony.com/blog/donate

**Comment by lyrixx** [comment]
For the record: https://symfony.com/sponsor

**Comment by lyrixx** [comment]
There a not bitcoin account for Symfony AFAIK, and there are way to sponsor.

So I'm 👎🏼 for this PR

But thanks for trying to help!

**Comment by JeremieSamson** [comment]
> There aren't bitcoin account for Symfony AFAIK. But there are way to sponsor.
> 
> So I'm 👎🏼 for this PR
> 
> But thanks for trying to help!

The main purpose here is to help SF to have a new way to get some donations. 
And no there is not any bitcoin address so far, if this PR is accepted, I assume they will edit the `xxxxx` by the address they will create ;)

**Comment by JeremieSamson** [comment]
> There aren't bitcoin account for Symfony AFAIK. But there are way to sponsor.
> 
> So I'm 👎🏼 for this PR
> 
> But thanks for trying to help!

Also yes @lyrixx sponsoring is a thing, but here it's giving all crypto people an easier way.

**Comment by nicolas-grekas** [comment]
I can provide an address :)

https://github.com/symfony/.github/blob/master/FUNDING.yml could be a better place to add this.
I'm closing because the readme is not the right place, bitcoin should not be listed in a separate place than other options.

**Pull request closed without merging**
