### PR TITLE
Fix potential access to undefined index

### PR DESCRIPTION
**Pull request by Seldaek**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Fixes @tobion's comment in https://github.com/symfony/symfony/pull/14563/files#r39705270

### CODE REVIEW

**Comment by Tobion** [comment]
The whole `withPriorities` logic is very fragile as this parameter is not part of the interface.
But all descriptors are typehinted against the interface but rely on the fact the the `withPriorities` is understood. Otherwise the descriptors will fail. So what is the plan for 3.0? Add the paramter to the interface? Or maybe its better to create a dedicated method for that. Currently the return structure depends on the paramters which is usually really bad.

But something needs to be added for #11742

**Comment by fabpot** [comment]
Thank you @Seldaek.

**Comment by fabpot** [comment]
We still have 2 months to fix what @Tobion describes as the original PR as merged in 2.8. I will try to propose something later today.

**Comment by fabpot** [comment]
see #16198

**Pull request merged**
