### PR TITLE
[Serializer] Minor code cleanup in XmlEncoder

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7 
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by javiereguiluz** [comment]
In the past we rejected changes like this in other components because they usually introduce bugs. Old branches should only include bug fixes, not code refactorings. But maybe we can do an exception this time?

**Comment by dunglas** [comment]
If we do it in master, it will be harder to merge.

**Comment by nicolas-grekas** [comment]
then let's just close it...

**Comment by nicolas-grekas** [comment]
http://fabien.potencier.org/about-symfony-stability-over-features.html

**Comment by javiereguiluz** [comment]
Related to Fabien's blog post, he wrote this article that explains when these pull requests are acceptable: https://symfony.com/doc/current/contributing/code/maintenance.html

> Coding standard and refactoring: Coding standard fixes or code refactoring are not recommended but can be accepted for consistency with the existing code base, if they are not too invasive, and if merging them on master would not lead to complex branch merging;

I wrongly thought that all refactorings were rejected. I'm sorry! So maybe we should merge this PR after all?

**Comment by dunglas** [comment]
No problem @javiereguiluz :) Your call @fabpot, close it or merge it, it's not a big deal to me.

**Comment by fabpot** [comment]
Ok, let's close it then.

**Pull request closed without merging**
