### PR TITLE
[Form] don't add the inputmode attribute on fields whose type is the same

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/pull/34986
| License       | MIT

These is no need to add the `inputmode` attribute on fields whose `type` is the same.

From https://html.spec.whatwg.org/multipage/interaction.html#attr-inputmode
> When inputmode is unspecified (or is in a state not supported by the user agent), the user agent should determine the default virtual keyboard to be shown. Contextual information such as the input type or pattern attributes should be used to determine which type of virtual keyboard should be presented to the user.

From https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
> **tel**
> Inputs that *require* a telephone number should typically use `<input type="tel">` instead.

> **search**
> Inputs that *require* a search query should typically use `<input type="search">` instead.

> **email**
> Inputs that *require* email addresses should typically use `<input type="email">` instead.

As such there is no point in adding `inputmode` for those types.

Symfony’s `UrlType` uses `inputmode` **only** when the `type` has to be `text` because the `default_protocol` option is set.

### CODE REVIEW

**Comment by fre5h** [comment]
I rechecked it on iOS mobile browsers. Works well. I mean only `type` without `inputmode`. I'm not sure that it is really a bug, that `inputmode` was added. Because `inputmode` attribute is still a part of HTML standard, it is not deprecated, it does not perform any negative side effects of form rendering.

**Comment by MatTheCat** [comment]
Indeed it’s not a bug, nor a feature. It basically added code for nothing so I believe it is okay to remove it.

**Review by nicolas-grekas — APPROVED** [review]
(for 5.1)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @MatTheCat.

**Pull request merged**
