### PR TITLE
[WebProfilerBundle] fixed undefined buttons variable.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | #13974, #13636 |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by dosten** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @aitboudad.

**Pull request merged**
