### PR TITLE
[FrameworkBundle] Support autowiring for TranslationInterface

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
This seems to not working:

```
Unable to autowire argument of type "Symfony\Component\Translation\TranslatorInterface" for the service "twig.ssl_certificate_extension".
```

My service definition:

```yaml
    twig.ssl_certificate_extension:
        class: AppBundle\Twig\SslCertificateExtension
        autowire: true
        tags:
            - { name: twig.extension }
```

My service class:

```php
class SslCertificateExtension extends \Twig_Extension
{
    /**
     * @var TranslatorInterface
     */
    private $translator;

    /**
     * @param TranslatorInterface $translator
     */
    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }
// [...]
```

**Comment by stof** [comment]
This may be because this service is replaced by another one when enabling the translator

**Comment by Soullivaneuh** [comment]
@stof indeed:

```bash
$ ./docker-console app/console container:debug | grep translator
  translator                                                                       Symfony\Component\Translation\DataCollectorTranslator                                           
  translator.default                                                               Symfony\Bundle\FrameworkBundle\Translation\Translator                                           
  translator_listener                                                              Symfony\Component\HttpKernel\EventListener\TranslatorListener                                   
```

**Comment by Soullivaneuh** [comment]
Works like a charm now! :green_heart:

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request closed without merging**
