### PR TITLE
[Validator] Added missing galician (gl) translations

### PR DESCRIPTION
**Pull request by rubenrua**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @rubenrua.

**Comment by stloyd** [comment]
@fabpot I guess you forgot to close this PR ;)

**Comment by xabbuh** [comment]
Does it make sense to have all of these translations in Symfony 2.3 (73 to 79 have been added in later versions).

**Comment by fabpot** [comment]
A while ago, we decided to not bother contributors anymore with several PRs that add the right translations in the right versions. As it does not hurt to have more translations than needed, we thought it would ease everyone work.

**Comment by xabbuh** [comment]
Thanks for the clarification.

**Pull request closed without merging**
