### PR TITLE
Missing ctype extension as requirement

### PR DESCRIPTION
**Pull request by analogic**
PHP Fatal error:  Call to undefined function Symfony\Component\Yaml\ctype_digit() in .../vendor/symfony/yaml/Inline.php on line 494

### CODE REVIEW

**Comment by mvrhov** [comment]
Beginning with PHP 4.2.0 these functions are enabled by default. For older versions you have to configure and compile PHP with --enable-ctype . You can disable ctype support with --disable-ctype . 

Some Linux distribution package guys being smart again?

**Comment by analogic** [comment]
Ha, you are right. PHP ctype package for alpine linux (like busybox - mainly used for smallest docker containers) must be explicitly installed. Close this if you think its not necessary...

**Comment by Tobion** [comment]
We already have ctype as requirement: https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/skeleton/app/SymfonyRequirements.php#L470

And this solution would not be enough as it's missing from symfony/symfony then.

**Comment by analogic** [comment]
Just FYI I use yaml as standalone component... but nevermind, i am ok with that...

**Pull request closed without merging**
