### PR TITLE
[Yaml] parse inline serialized PHP objects

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #6498
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by GuilhemN** [comment]
Do we really need this ? It is a deprecated feature and the issue is already fixed by using the syntax with quotes.

**Comment by xabbuh** [comment]
We need to update the code of course to support the "new" tag in 3.4. But since this patch is very small and tackles an isolated part of the parser, I don't see why we don't want to fix the issue.

**Comment by GuilhemN** [comment]
This is invalid yaml and I don't like allowing invalid syntaxes :)
Using `!php\object 0:...:{....}` shouldn't be allowed either imo, it is also invalid yaml and quotes are here exactly to prevent hacks.

**Comment by xabbuh** [comment]
Hm indeed, you are right. :)

**Pull request closed without merging**
