### PR TITLE
[Cache] CacheItem with tag is never a hit after expired

### LINKED ISSUE #36458: [Cache] CacheItem with tag is never a hit after expired once
**Symfony version(s) affected**: 4.4.0 -> 4.4.7

**Description**  

If a CacheItem with a Tag is expired once and be rewritten with a new expiredAfter it is never again a hit.

**How to reproduce**  

https://github.com/symfony/symfony/pull/36457

**Possible Solution**  

Can sadly not provide a solution as I'm not sure where the error is.

**Additional context**  

Without tags it works as expected.

Also when using the older `TagAwareAdapter(` instead of the optimized `FilesystemTagAwareAdapter` it works as expected so it need to be in the `TagAwareTraitAdapters` as the following tests are effected:

```
1) Symfony\Component\Cache\Tests\Adapter\FilesystemTagAwareAdapterTest::testRefreshAfterExpires

Failed asserting that false is true.

/home/travis/build/symfony/symfony/src/Symfony/Component/Cache/Tests/Traits/TagAwareTestTrait.php:194

2) Symfony\Component\Cache\Tests\Adapter\PredisTagAwareClusterAdapterTest::testRefreshAfterExpires

Failed asserting that true is false.

/home/travis/build/symfony/symfony/src/Symfony/Component/Cache/Tests/Traits/TagAwareTestTrait.php:183

3) Symfony\Component\Cache\Tests\Adapter\RedisTagAwareAdapterTest::testRefreshAfterExpires

Failed asserting that true is false.

/home/travis/build/symfony/symfony/src/Symfony/Component/Cache/Tests/Traits/TagAwareTestTrait.php:183

4) Symfony\Component\Cache\Tests\Adapter\RedisTagAwareClusterAdapterTest::testRefreshAfterExpires

Failed asserting that true is false.

/home/travis/build/symfony/symfony/src/Symfony/Component/Cache/Tests/Traits/TagAwareTestTrait.php:183
```

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes/no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #36458
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

It seems like a tag cacheItem is never a hit again. Not sure how fix this but the cache component is really hard to debug 🙈 .

It need to be somewhere generally as all TagAware caches are effected:

```
1) Symfony\Component\Cache\Tests\Adapter\FilesystemTagAwareAdapterTest::testRefreshAfterExpires

Failed asserting that false is true.

/home/travis/build/symfony/symfony/src/Symfony/Component/Cache/Tests/Traits/TagAwareTestTrait.php:194

2) Symfony\Component\Cache\Tests\Adapter\PredisTagAwareClusterAdapterTest::testRefreshAfterExpires

Failed asserting that true is false.

/home/travis/build/symfony/symfony/src/Symfony/Component/Cache/Tests/Traits/TagAwareTestTrait.php:183

3) Symfony\Component\Cache\Tests\Adapter\RedisTagAwareAdapterTest::testRefreshAfterExpires

Failed asserting that true is false.

/home/travis/build/symfony/symfony/src/Symfony/Component/Cache/Tests/Traits/TagAwareTestTrait.php:183

4) Symfony\Component\Cache\Tests\Adapter\RedisTagAwareClusterAdapterTest::testRefreshAfterExpires

Failed asserting that true is false.

/home/travis/build/symfony/symfony/src/Symfony/Component/Cache/Tests/Traits/TagAwareTestTrait.php:183
```

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Did you try with 3.4?

**Comment by alexander-schranz** [comment]
@nicolas-grekas the bug only appears with the classes which extend from `AbstractTagAwareAdapter` like FilesystemTagAwareAdapter which do not exist in 3.4 only in 4.3 . The `new TagAwareAdapter(new FileSystemAdapter));` which exist before does not contain this bug.

**Comment by nicolas-grekas** [comment]
I pushed the fix on your fork. Redis adapters don't have the bug. The transient failures related to them are due to expirations being time-sensitive.
FilesystemTagAwareAdapter is the one that needed a fix.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@nicolas-grekas looks good. Thank you for having a look at this 👍. Travis error seems to have nothing todo with the changes in this PR.

**Comment by nicolas-grekas** [comment]
Thank you @alexander-schranz.

**Pull request merged**
