### PR TITLE
[PropertyInfo] fix support for phpstan/phpdoc-parser 2

### LINKED ISSUE #58796: PropertyInfo PhpStanExtractor is incompatible with version 2.0 of phpstan/phpdoc-parser
### Symfony version(s) affected

5.4, 6.4, 7.2

### Description

A new version of PHPStan's parser has been released (2.0.0).

Installation with 2.0.0 causes issues with the following code:
https://github.com/symfony/symfony/blob/3ee749073358a2e096193994176dc054806b62f1/src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php#L82

Because `ConstExprParser` now has required constructor arguments.

Since this is an optional dependency, how are we going to handle it?

### How to reproduce

In my case it was any project using `symfony/serializer-pack`. Since this also installed the `phpstan/phpdoc-parser` with any version, I received 2.0.0.

### Possible Solution

_No response_

### Additional Context

_No response_

### LINKED ISSUE #58798: Missing language codes
### Symfony version(s) affected

5.4.46, 6.4.14, 7.1.7, 7.2.0-BETA2

### Description

Symfony was recently updated to include locale information from ICU 75.1, which is a great improvement.

Unfortunately, this version of the ICU data still does not include information for many languages, particularly African ones (including the official languages of a number of African countries). The result is that projects that depend on Symfony cannot be localised into these languages. (See [here](https://github.com/simplesamlphp/simplesamlphp/issues/2305) for an example.)

The newer 76.1 release of the ICU data includes several more African languages, including the specific ones I'm interested in (being a number of South Africa's official languages).

### How to reproduce

Setting a language locale to `st`, `st_ZA`, or `st_LS` uses the default fallback or results in an error, despite being a valid language (Southern Sotho/Sesotho) and having been included in the ISO 639-1 language codes for over a decade.

### Possible Solution

Updating the locale information to ICU 76.1 (based on CLDR 46) will add support for more languages.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #58796
| License       | MIT

### CODE REVIEW

**Review by alexandre-daubois — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you Christian.

**Comment by bnf** [comment]
Hey, can you estimate when this fix is going to be released?

https://github.com/phpDocumentor/ReflectionDocBlock/releases/tag/5.6.0 was released today which added support for `phpstan/phpdoc-parser` v2 in https://github.com/phpDocumentor/ReflectionDocBlock/pull/388
That means a lot of instances start updating to `phpstan/phpdoc-parser` v2 now, and run into conflicts with `symfony/type-info` 7.1.6


In TYPO3, where `symfony/property-info` (pulls in `symfony/type-info`) and `phpdocumentor/reflection-docblock` are both used, there is now an implicit conflict, because `symfony/type-info` 7.1.6 does not declare an explicit dependency to `phpstan/phpdoc-parser` 1.x – it only defines a conflict to <1.0 and a require-dev dependency. Is that on purpose or a mistake?

Also see:  https://forge.typo3.org/issues/105582

**Comment by derrabus** [comment]
> Hey, can you estimate when this fix is going to be released?

We do monthly releases, so this change will be released by the end of the month.

**Comment by bnf** [comment]
Thanks for the answer.
Can you elaborate on this aspect:

> symfony/type-info 7.1.6 does not declare an explicit dependency to phpstan/phpdoc-parser 1.x – it only defines a conflict to <1.0 and a require-dev dependency. Is that on purpose or a mistake?

**Comment by stof** [comment]
We don't declare an explicit dependency because this is an *optional* dependency of the component. You could totally configure the type-info component without enabling support for parsing phpdoc (relying only on native types) if you don't need the more precise types supported only in phpdoc (which is what FrameworkBundle does if the dependency is not available, btw).

**Comment by bnf** [comment]
Sorry for discussing in here.
I'm just wondering if we were wrong (and should release a fix ourselves) or not:

https://symfony.com/doc/current/components/property_info.html#phpdocextractor states that 
> This extractor depends on the [phpdocumentor/reflection-docblock](https://packagist.org/packages/phpdocumentor/reflection-docblock) library.

We're using `PhpDocExtractor` from `symfony/property-info` in https://github.com/TYPO3/typo3/blob/04fb1190b9d/typo3/sysext/extbase/Classes/Reflection/ClassSchema.php#L113 and therefore require your optional dependency in https://github.com/TYPO3/typo3/blob/04fb1190b9d/typo3/sysext/extbase/composer.json#L23

We'not using `PhpStanExtract` (which is documented to require `phpstan/phpdoc-parser`) and therefore do not define a `phpstan/phpdoc-parser` dependency.

Therefore `phpstan/phpdoc-parser` was pulled in implicitly by `phpdocumentor/reflection-docblock`.

Also we do not require `symfony/type-info` directly.

Since https://github.com/phpDocumentor/ReflectionDocBlock/releases/tag/5.6.0 was released today and now pulls in `phpstan/phpdoc-parser` 2.x, effectively all users of `symfony/property-info`:`PhpDocExtractor` run into this issue.

The problem I see is:

- `symfony/property-info`:`PhpDocExtractor` implicitly pulls in `phpstan/phpdoc-parser` and can not be used without
- users could pin `phpstan/phpdoc-parser` to 1.x, without actually using it, which is only "ok" to be done until november release and mean they define a dependency they are not supposed to define.

We'll now ask our community to apply a hotfix like the following do force a downgrade without specifying an unneeded dependency:

```
composer require phpstan/phpdoc-parser:^1
composer remove --no-update phpstan/phpdoc-parser
```

…but we already received complains for composer-updates in the meantime.
Any chance to fix this earlier ?

**Comment by stof** [comment]
FrameworkBundle does not check which requirements you put in your vendor folder. It checks what is installed in the vendor folder.

> We'll now ask our community to apply a hotfix like the following do force a downgrade without specifying an unneeded dependency

you can also ask them to run `composer update phpstan/phpdoc-parser --with "phpstan/phpdoc-parser:^1"` if you want to run a resolution using a constraint forcing phpdoc-parser 1.x without putting it in the composer.json

**Comment by bnf** [comment]
Thanks a lot. That oneline is much better.

I'm still sure that this conflict is wrong:

https://github.com/symfony/type-info/blob/51535dde21c7abf65c9d000a30bb15f6478195e6/composer.json#L36-L37

```
    "conflict": {
        "phpstan/phpdoc-parser": "<1.0",
```


It should have been:

```
    "conflict": {
        "phpstan/phpdoc-parser": "<1.0 || >=2.0",
```

…and now that v2 compatibility has been assured it should of course be:

```
    "conflict": {
        "phpstan/phpdoc-parser": "<1.0 || >=3.0",
```

**Comment by bnf** [comment]
That is why I'm asking for a hotfix release.

It seems everyone is affected who installs or updates `symfony/property-info` from now on until december, as https://github.com/symfony/symfony/issues/58841 shows.

CC @jaapio (whom I do not see as responsible – we just talked via direct messages – but revealed this with his https://github.com/phpDocumentor/ReflectionDocBlock/releases/tag/5.6.0 update today). Maybe he can share his take on this situation.

**Comment by IT-Cru** [comment]
Also in api-platform/core project they run in issues from new phpstan/phpdoc-parser release.

See: https://github.com/api-platform/core/pull/6789

As workaround projects could add following to their own composer.json file:

```javascript
    "conflict": {
        ...,
        "phpstan/phpdoc-parser": "<1.0 || >=2.0"
    }
```

**Comment by jaapio** [comment]
There is not much I can do. 

The version constraint seems to be missing as the package is not compatible with the new version of phpstan/phpdoc-parser. We might want to prevent this in the future.  

For now the only reasonable fix would be a hotfix release from Symfony. Even reverting the changes on my side would not solve anything as it would block symfony 's upgrade path. And composer would still be able to resolve a set containing the V2 version of the docblock parser. 

To be fair, the actual origin of issues are the devs who just randomly update all their packages without reviewing what they actually do. We as maintainers cannot prevent all stupidity. But we can try to prevent it. It would at least reduce the number of emails and issues reported to us.

**Pull request merged**
