### PR TITLE
[Form] cs fixes in date types

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Branch? | 2.3+ |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | n/a |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by HeahDude** [comment]
Apply the same cache handling as in `TimeZoneType`, it may be more useful in 2.7+ as there is an `array_flip` after getting the choices.

Actually b2c9ad5 will have some minor conflicts in 2.7 because of `array_flip` and `choices_as_values`.

I've got a version of this PR targeting 2.7, should I send it ?

There will also be a conflict with 6ce6e8c but very minor (just need to remove the block).

**Comment by fabpot** [comment]
As this is not a bug fix, it should be done in master.

**Comment by HeahDude** [comment]
Alright, I've got a bigger plan for master after that done :)

**Comment by HeahDude** [comment]
@fabpot But we may keep the cs fix of d1f0ffa for 2.3, right ?

**Comment by fabpot** [comment]
Sure, removed the other commits and this one would be ready to be merged

**Comment by HeahDude** [comment]
Done :)

**Comment by javiereguiluz** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @HeahDude.

**Pull request merged**
