### PR TITLE
[2.8][WebProfilerBundle] Drop dead code

### PR DESCRIPTION
**Pull request by romainneutron**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| License       | MIT

As you can read in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/WebProfilerBundle/DependencyInjection/Configuration.php#L40-L46 the `position` can only be `top` or `bottom`. I don't see any reference anywhere to a `normal` position.
The removed tests are always true.

### CODE REVIEW

**Comment by stof** [comment]
Yeah, ``normal`` was used by the profiler itself in the old design: https://github.com/symfony/symfony/commit/56b6d537d6f803e3b497292c14f16fdfd1514126

**Review by stof — APPROVED** [review]
👍

**Review by javiereguiluz — APPROVED** [review]
👍

**Review by xabbuh — APPROVED** [review]
👍

**Comment by nicolas-grekas** [comment]
Thank you @romainneutron.

**Pull request merged**
