### PR TITLE
[2.3] [Bridge] [Doctrine] made session table columns configurable through cons...

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by Tobion** [comment]
What is the state here? It must be done in 2.7 and it must also make the schema configurable. In it's current form it's not mergeable. @hhamon are you going to make the changes? Or rather close the PR?

**Comment by hhamon** [comment]
@Tobion I can make the changes in the coming days and submit against 2.7 branch.

**Comment by Tobion** [comment]
But what's the actual advantage of that? I don't really see it. As a session user you don't care how the table looks like.

**Comment by fabpot** [comment]
Should be done in 2.8 or closed. ping @hhamon

**Comment by hhamon** [comment]
Will do ;)

**Comment by hhamon** [comment]
Closing in favor of #14710.

**Pull request closed without merging**
