### PR TITLE
[Console] ProgressBar displays incorrectly after clear, add reset

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | will add.

### CODE REVIEW

**Comment by fabpot** [comment]
Not sure I understand this PR. Why not fix `clear` instead?

**Comment by Simperfit** [comment]
There are two PRs, one that fix clears, one that add reset.

The one fixing clears is still in WIP because I didn't found the right way to do it ATM.

**Comment by chalasr** [comment]
I suggest to close this one if no use case for `reset()`, and continue to try fixing `clear()` in #24834.

**Comment by fabpot** [comment]
Makes sense.

**Pull request closed without merging**
