### PR TITLE
[2.8] [Bridge] [Doctrine] made session table columns configurable through constructor method.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by hhamon** [comment]
This PR replaces https://github.com/symfony/symfony/pull/13136

**Comment by hhamon** [comment]
ping @Tobion @stof is it ok now?

**Comment by fabpot** [comment]
Why would you want to make them configurable? What's the use case?

**Comment by Tobion** [comment]
I don't think we should do this. Then we also have the problem that people can use reserved words which would need to be "escaped". See #11131

**Comment by Tobion** [comment]
Also implementation wise, it would be better to accept a `Doctrine\DBAL\Schema\Schema` or `Doctrine\DBAL\Schema\Schema\Table` as argument for `DbalSessionHandler`. That would be cleaner and one only needs to configure the names in one place and not in two classes.

**Comment by fabpot** [comment]
@hhamon Closing as I agree with @Tobion.

**Pull request closed without merging**
