### PR TITLE
Fix # 34866 - base path discovery with autoindex

### PR DESCRIPTION
**Pull request by mvorisek**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/34866
| License       | MIT
| Doc PR        | Fix # 34866 - base path discovery with autoindex

### CODE REVIEW

**Comment by mvorisek** [comment]
Please review and merge, projects like https://github.com/PrestaShop/PrestaShop/issues/16631 are waiting for this to be fixed asap. Thanks.

**Comment by nicolas-grekas** [comment]
The current logic exists for years and has been proved workable. I think the PrestaShop conf should be fixed instead. Note that hardcoding "index.php" in the code is totally random - the front controller can be anything from the webserver pov. It used to be `app.php` quite recently.

:-1:

**Comment by mvorisek** [comment]
@nicolas-grekas I understant your point of view, but how? For me, it seems like a clear bug in the Symfony code, as is does strip autoindex if the request root matches the web server root. And by definition the server/CGI variables does not have to match the request root. This is not a PrestaShop issue, it affects all users.

I have fixed the code as a fallback, so under normal circumstances the path is well resolved. But if not, i.e. path resolves so empty (which is never valid - as every path have to start normally with `/`), it applies this extra logic, so no existing working code is affected by this patch.

Can you please advise how to fix this? Would a fallback to strip any 1 level filename be ok? Only filenames ending with `.php`?

**Comment by nicolas-grekas** [comment]
I think there is nothing to fix: several thousand persons manage to run their app behind web servers since years. What is needed is proper configuration on the webserver's side. When the configuration is not correct, I admit one can hit "underdefined behavior" on Symfony's side. Then, the config needs to be fixed.

**Comment by mvorisek** [comment]
@nicolas-grekas This issue is presented when some URL subdir/subpath is routed to some directory - why do you think that this is improper configuration? For example, this is very common in enviroments where every user has some unique path like `/~<username>/` which can not be actually configured differently.

**Comment by fabpot** [comment]
What Nicolas says is that you should probably configure that in your web server setup instead of changing Symfony itself. I agree with him.

**Comment by mvorisek** [comment]
@fabpot But server can not be configure "like Symfony wants it" as the parent directory of root path DOES NOT have to match the subpath in the URL.

Webserver example which currently fails with Symfony:
serve URL: `/~user/*` from (root directory) `/home/user`
rewrite `*` to `/home/user/index.php`

and the following request will fail to resolve properly:
URL:  `/~user/test/x/y` 
as currently Symfony has issue to resolve physical path that does not match URL (`.../user/` vs. `/~user/`) when used with autoindex.

See the issue report for full description and analysis.

Do you understand the issue? Can you advise how to configure the webserver for this very simple and common example?

**Comment by nicolas-grekas** [comment]
I'd suggest adding a few lines of PHP code in your front controller to adapt things as desired if you want.

**Comment by mvorisek** [comment]
> 
> 
> I'd suggest adding a few lines of PHP code in your front controller to adapt things as desired if you want.

Yes, you can patch every code which is served from some URL subpath and the target directory is set as a root. Patch the code for specific use case to modify the $_SERVER vars.

So there is an issue which can be fixed with "autoindex fallback" - see PR, it does not affect any working current configuration and you do not want to fix this quote common scenarion in Symfony directly?

**Comment by nicolas-grekas** [comment]
Actually, this doesn't look quite common to me. From my experience, this is the first report of this kind in years. Which is also part of the reasons why we have this opinion I suppose.

**Comment by mvorisek** [comment]
@nicolas-grekas 

User's directories/URL subpaths are very common it should be fixed.

This issue was probably not reported as this issue is presented only when autoindex is used + parent directory of the root path does not match the URL (i.e. route of URL `/x/y` to root directory `/home/x/y` works, but `/home/not_x/y` does not work).

Do you have anything against safe fix of a real issue? Or can you advise how to fix it without manual patching each website without any portability?

**Comment by mvorisek** [comment]
@nicolas-grekas Please reopen, in other words, is it ok, if the current base path (and all functions like routing which depend on it) does not work with paths like `/~username/`?

**Comment by mvorisek** [comment]
@nicolas-grekas Please reopen, in other words, is it ok, if the current base path (and all functions like routing which depend on it) does not work with paths like `/~username/`?

This PR is safe as it is implmented as a fallback/last resolution. If there is an extra feedback that needs to be implemented, please tell, I will do my best to integrate it into this PR.

**Pull request closed without merging**
