### PR TITLE
[Workflow] Re-add InvalidTokenConfigurationException for BC

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Reverts the BC breaking part of #39671

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]

**Comment by lyrixx** [comment]
Should we add a notice ? an entry in the changelog to not forget to remove it in 6.0 ?

**Comment by stof** [comment]
shouldn't the class be deprecated though ?

**Comment by chalasr** [comment]
Yes, on 5.x. This targets 5.2

**Comment by chalasr** [comment]
See #40202 for the deprecation

**Pull request merged**
