### PR TITLE
[Translation] improve extendability of metrics

### PR DESCRIPTION
**Pull request by rvanlaak**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | https://github.com/php-translation/symfony-bundle/issues/295
| License       | MIT
| Doc PR        | 

For https://github.com/php-translation/symfony-bundle/issues/295 the organization would like to make better use of the extendability of the bundle's Twig templates.

This PR wraps the metrics in a block in order to add metrics. 

RfC: Another future enhancement would have to do with the extendability of the table, but the plan of approach for that (as it's rendered by a macro) has not been decided yet.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
No objections on my side.

**Comment by fabpot** [comment]
I've no objection either, but that block and the structure can be changed anytime as we won't guarantuee any stability in the generated HTML. Is it worth it?

**Comment by rvanlaak** [comment]
One of the remaining questions we have is on [the extendability of the table that shows the translations](https://github.com/symfony/symfony/blob/d8eafcf0b2cc3c4f02d91233f1748154ba956ef6/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/translation.html.twig#L167-L206), as that is rendered using a macro. As modifying macro behavior through extending is more complex, what would be the preferred way to make existing table code reusable as well?

**Comment by fabpot** [comment]
But at this point, wouldn't it be easier/better to create a new panel?

**Comment by fabpot** [comment]
@rvanlaak What's your point of view about my last comment?

**Comment by rvanlaak** [comment]
The issue is that the translation bundle's panel is outdated because it is overwriting instead of extending the existing panel. The goal would be to find a future proof solution for that.

Would be best to get a shared point of view from `php-translation`'s organization perspective. That is why it would be great if @bocharsky-bw could give his opinion as well, given that he opened the issue.

Still; the extendability of the macro that renders the table is not resolved yet, so this PR is not mergeable yet.

**Comment by bocharsky-bw** [comment]
Hm, probably a new panel for PHP-Translation's bundle is overkill because it only adds actions (buttons) to the existent data. Though I don't see a simple way how to make that macro extendable :/
As an alternative solution, I think we can modify rendered macro's content with JS, this way we won't need to override the macro at all.

**Review by ro0NL — APPROVED** [review]
> that block and the structure can be changed anytime as we won't guarantuee any stability in the generated HTML

I suggest to copy the template and maintain/keep it in sync yourself. Then either use it for the existing panel, or create a new panel and disable the existing one. That's safest and most flexible for you.

**Comment by fabpot** [comment]
Can you paste a screenshot of the panel before/after the changes you want to make?

**Comment by bocharsky-bw** [comment]
I made it in the source issue: https://github.com/php-translation/symfony-bundle/issues/295 . Let me duplicate it here:

Screen Shot 2019-03-28 at 18 16 31

Screen Shot 2019-03-28 at 18 17 46

**Comment by fabpot** [comment]
What about a block after the last `<td>` that would be empty by default? That would allow to override it and get the current context.

**Comment by rvanlaak** [comment]
As in, a block inside of a macro? Was not aware that was possible. Could not really find documentation about it, could you point me in the right direction?

If possible, that would solve the problem with the extendability of the table. 

```twig
{# base template #}
{% macro render_table(messages) %}
    <table data-filters>
        <thead>
            <tr>
				{% block table_headers %}
	                <th data-filter="locale">Locale</th>
	                <th data-filter="domain">Domain</th>
	                <th>Times used</th>
	                <th>Message ID</th>
	                <th>Message Preview</th>
				{% endblock %}
            </tr>
			...
{% endmacro %}
```


```twig
{# extending template #}
{% macro render_table(messages) %}
    {% block table_headers %}
	    {{ parent() }}
        <td>Actions</td>
	{% endblock %}
{% endmacro %}
```

**Comment by fabpot** [comment]
@rvanlaak Forget my last comment. I did not remember that the table was in a macro.

**Comment by curry684** [comment]
Given that you want to intervene at multiple points, including table rows, I'd argue the point that you should just make a new panel. As outlined you're now getting yourself into maintenance hell as Symfony itself does not guarantee stability of the templates - so at any time you may need to support up to 4 different versions of this template (LTS, oldstable, stable and next). The support burden on your end would be easier if you just replaced the existing template as a whole.

One way or another, this isn't going to work with how macros work now in Twig.

**Comment by fabpot** [comment]
Let's close.

**Pull request closed without merging**
