### PR TITLE
[String] fix "is too large" ValueError on PHP 8

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by stof** [comment]
What is this number here ?

**Comment by nicolas-grekas** [comment]
It's `INT32_MAX`, as hardcoded in php-src.

**Comment by stof** [comment]
Do they expose such a constant, when their APIs use that as max ?

**Comment by nicolas-grekas** [comment]
Nope, it's an internal macro...

**Pull request merged**
