### PR TITLE
Fixed the Bootstrap form theme for inlined checkbox/radio

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14704 |
| License | MIT |
| Doc PR | - |

@qferr provided the solution for this bug. I only verified it and created the PR.

@aderuwe @JHGitty @tjaadvd all of you took part in the original discussion. Could you please verify if this change fixes your issues? Thanks.

### CODE REVIEW

**Comment by tjaadvd** [comment]
I can confirm that this fixes the issue!

**Comment by javiereguiluz** [comment]
@tjaadvd great! Thanks for confirming.

**Comment by xabbuh** [comment]
:+1:

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request merged**
