### PR TITLE
[ErrorHandler] Make assert() silent when assert.quiet_eval=1

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Working around https://bugs.php.net/75769
/cc @nikic FYI :)

### CODE REVIEW

**Comment by nikic** [comment]
Please don't. `assert.quiet_eval` is meaningless for non-string asserts and removed in PHP 8.

**Comment by nicolas-grekas** [comment]
It would be really useful to make it work in PHP8! The use case is the following: turn assert() "on" in prod, but in a silenced mode only. Instead of disrupting execution, this would trigger warnings with error_reporting() set to zero. Then, userland error handlers would catch those and log them, allowing to debug issues with assert() on prod systems. I don't know the plan for PHP8, but please don't make assert() always throw!

**Comment by nikic** [comment]
@nicolas-grekas I think you are mixing up `assert.exception`/`assert.warning` with `assert.quiet_eval`. `quiet_eval` only affects errors generated during evaluation of the assert itself, it does not affect how an assertion failure is reported.

You may also want to look into `ASSERT_CALLBACK`, which is probably a more convenient way to add custom assert handling than to listen for warnings in an error handler.

**Comment by nicolas-grekas** [comment]
OK, I'll give it a 2nd look, thanks for the feedback. In any chance, do you have any hints about the plans for PHP 8 on this topic?

**Comment by nikic** [comment]
@nicolas-grekas Don't think there are any plans in that area (yet...) There was only some talk of making `assert.exception=1` the default (instead of `assert.warning=1`).

**Comment by nicolas-grekas** [comment]
Alternative proposal in #35645

**Pull request closed without merging**
