### PR TITLE
[FrameworkBundle] Removed kernel.debug from the cache pool namespace seed

### PR DESCRIPTION
**Pull request by Sander-Toonen**
| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/20780
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
The arguments presented in #20780 are sensible to me
:+1:

**Comment by Sander-Toonen** [comment]
Ok, I'll create a similar pr for the DotrineCacheBundle then.

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @Sander-Toonen.

**Pull request merged**
