### PR TITLE
[FrameworkBundle] avoid calls of deprecated addPool() method

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by chalasr** [comment]
Good catch, it makes sense. Is it normal that the build still fails with high deps, until this is released or at least merged on 3.2+?

**Comment by xabbuh** [comment]
@chalasr No it shouldn't fail. That's what I actually wanted to look into first when I noticed these deprecations, but I first need to set up Redis locally. Maybe I have some time to investigate this tonight.

**Comment by nicolas-grekas** [comment]
:-1: : deprecating in 3.2 must not require changing anything in 3.1

**Comment by xabbuh** [comment]
@nicolas-grekas How exactly do you want to avoid that if you want the FrameworkBundle in 3.1 be compatible with all 3.x releases of the Cache component?

**Comment by chalasr** [comment]
@xabbuh The `Psr6CacheClearer` is in the HttpKernel component, though it would make sense to have it in the Cache imho. 
About the deprecation, calling `addPool()` method works with all 3.x releases of HttpKernel so I don't really understand the need for this, I'm surely missing something.

**Comment by xabbuh** [comment]
@chalasr But it will be deprecated starting with Symfony 3.3: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/CacheClearer/Psr6CacheClearer.php#L30

**Comment by chalasr** [comment]
@xabbuh Of course it's about the warning, nevermind.

**Comment by nicolas-grekas** [comment]
The warning is legitimate, there is nothing to fix here, that's how things work.

**Pull request closed without merging**
