### PR TITLE
[BrowserKit] ignore invalid cookies expires date format

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15656
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
This looks weird to me. The issue says to ignore the cookie, not to ignore only its date

**Comment by xabbuh** [comment]
Not sure what you mean. The issue description contains this quote from the RFC:

> If the attribute-value failed to parse as a cookie date, ignore the cookie-av.

Maybe I misinterpret that part, but IIUC `cookie-av` means cookie argument value, but the entire cookie.

**Comment by stof** [comment]
ah sorry, I misread it

**Review by javiereguiluz — CHANGES_REQUESTED** [review]
I guess we should also update the constructor of this class, where you can find:

```php
if (null !== $expires) {
    $timestampAsDateTime = \DateTime::createFromFormat('U', $expires);
    if (false === $timestampAsDateTime) {
        throw new \UnexpectedValueException(sprintf('The cookie expiration time "%s" is not valid.', $expires));
    }

    $this->expires = $timestampAsDateTime->format('U');
}
```

**Comment by xabbuh** [comment]
@javiereguiluz I don't think so. Let me quote myself from https://github.com/symfony/symfony/issues/15656#issuecomment-276069832:

> Actually, after thinking of this again I do not think that we need to change the constructor. It is documented that the expected value must be a string containing the expires timestamp.

The constructor will be used by some code that already had to parse the `Set-Cookie` header. So this part should be responsible to deal with invalid values instead of magically treating them as anything else.

**Comment by javiereguiluz** [comment]
@xabbuh you are right! I missed your comment.

---

👍 

Status: reviewed

**Review by javiereguiluz — APPROVED** [review]
@xabbuh you are right! I missed your comment.

---

👍 

Status: reviewed

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
