### PR TITLE
[PropertyInfo] Fix resolution of partially docblock covered constructors

### LINKED ISSUE #46383: [PropertyInfo] Detection of primitive types is broken for classes with docblocks
### Symfony version(s) affected

6.1.0

### Description

PropertyInfo incorrectly detects collection type for types not documented in docblock since 6.1 version. Deserialization then fails with error
```
In ArrayDenormalizer.php line 40:
                                                                     
  [Symfony\Component\Serializer\Exception\InvalidArgumentException]  
  Data expected to be an array, int given.                                                                        
```

This is because before, ConstructorExtractor has been called, but now this is no longer the case. Now, PhpstanExtractor is called, which resolves types documented in phpdoc only. I've checked a bit why is this the case and looks like on 6.0, this line is triggered https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Component/PropertyInfo/Extractor/PhpStanExtractor.php#L78, while on 6.1 it isn't. But looks like real issue is that PhpStanExtractor is not returning null in `getDocBlockFromProperty` for such (non-documented) properties.

### How to reproduce

deserialize
```json
{"id": 1, "variations": []}
```
into
```php
namespace Haushalt\Bl\DomainBundle\Domain\Product\Entity;

final class Product
{
    /**
     * @param \stdClass[]   $variations
     */
    public function __construct(
        public int $id,
        public array $variations,
    ) {
    }

    public function getId(): int
    {
        return $this->id;
    }
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ostrolucky**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46383
| License       | MIT
| Doc PR        | -

This fixes a regression in 6.1

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by ostrolucky** [comment]
@fabpot @nicolas-grekas can this be looked at before releasing stable version? This is a huge 6.1 regression IMO.

**Comment by fabpot** [comment]
Thank you @ostrolucky.

**Comment by ostrolucky** [comment]
Going to answer my comment. This guard
```php
if (self::MUTATOR === $source && !$this->filterDocBlockParams($phpDocNode, $property)) {
    return null;
}
```

can indeed now be removed, as now you added more generic solution

**Comment by ostrolucky** [comment]
Going to answer my comment. This guard
```php
if (self::MUTATOR === $source && !$this->filterDocBlockParams($phpDocNode, $property)) {
    return null;
}
```

can indeed now be removed, as now you added more generic solution

**Pull request merged**
