### PR TITLE
Allow to define custom status texts for exceptions

### PR DESCRIPTION
**Pull request by bit0rez**
| Q | A |
| --- | --- |
| Branch | 3.0 |
| Bug fix | no |
| New feature | yes |
| BC breaks | no |
| Deprecations | no |
| Tests pass | yes |
| License | MIT |

Set specific status text for extended status code.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This would need a unit test. But AFAIK, the status text is non normative in HTTP and thus should not be used nor relied upon. AFAIK also, we rejected such things in the past because of this. Please  argument your use case.

**Comment by fabpot** [comment]
@nicolas-grekas is right. What's your use case?

**Comment by bit0rez** [comment]
Our team is implementing RESTful API and SDK for our service and we have to use status codes, that differs from those described in HTTP specification, because specification is not considing our situations. HTTP is extensible and we can use status codes, that differs from specification. But we want to set the status text. It's will helping in debugging API and SDK in future, and, AFAIK, it's not a violation of specification. So, why not?

P.S.: Sorry for my bad english.

**Comment by fabpot** [comment]
We've rejected the same kind of changes in the past for the main Response status code, so I think we cannot accept this change for the same reasons.

**Pull request closed without merging**
