### PR TITLE
[TwigBridge] Use label_format option for checkbox and radio labels

### PR DESCRIPTION
**Pull request by enumag**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: Is this the only place where we need to make this change?

Status: Reviewed

**Comment by enumag** [comment]
Not sure I'll take a look at the other files.

**Comment by enumag** [comment]
@xabbuh Turns out we should do the same in the twig template for foundation 5. However since it is not present in 2.7 I can't include the change in this PR. Should I open a second one?

**Comment by xabbuh** [comment]
@enumag Would be great if you were able to do that. :+1:

**Comment by enumag** [comment]
@xabbuh No problem. https://github.com/symfony/symfony/pull/17382

**Comment by Tobion** [comment]
Ref #12050 for the original PR.

:+1:

**Comment by enumag** [comment]
@Tobion You mean to prefix the commit message with "bug #12050" or something else?

**Comment by Tobion** [comment]
No that was just for anyone reviewing the code

**Comment by fabpot** [comment]
Thank you @enumag.

**Pull request merged**
