### PR TITLE
Make the simple exception pages match the new style

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22631
| License       | MIT
| Doc PR        | -

If you create an application with Symfony Flex and don't install the TwigBundle explicitly, you see the exception pages like this:

before

This PR updates that page to match the style of the rest of exceptions:

after

For comparison, this is how the full exception page looks:

full-exception

---

Should I add the small black top header with the Symfony logo too?

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Comment by xabbuh** [comment]
> Should I add the small black top header with the Symfony logo too?

If that's not too much work, I'd say yes. :)

**Comment by deflock** [comment]
Black header with logo may confuse when Debug is used as standalone component.
Will this be merged until 3.3 release?

**Comment by fabpot** [comment]
@javiereguiluz Last call for 3.3 :)

**Comment by javiereguiluz** [comment]
If we don't want to add the black header ... this should be finished. @deflock has a good point about not adding that header. I'm divided about that.

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
