### PR TITLE
[PasswordHasher] Drop UserPasswordHasherInterface & implementation

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | todo

This PR removes the `UserPasswordHasherInterface` (formerly UserPasswordEncoderInterface) in favor of the password hasher factory. 

Motivations:
- Its API is very similar to the `PasswordHasherInterface` one, but tight coupled to the UserInterface. Such code "duplication" at the abstraction level is confusing
- It hides the `PasswordHasherInterface`, making it almost internal while it's actually central and good enough to be used (if you need to write a custom password hasher, it's the one you have to implement anyway)
- It was especially useful to avoid the need for calling both `$user->getPassword()` and `$user->getSalt()` in userland, while only `getPassword()` is needed nowadays.
- It's almost unused in core (only one usage in security-guard)

Before:
```php
public function someController(UserPasswordHasherInterface $passwordHasher) 
{
    $passwordHasher->hashPassword($user, 'plain-password');
}
```

After:
```php
public function someController(PasswordHasherFactoryInterface $passwordHasherFactory) 
{
    $passwordHasherFactory->getPasswordHasher($user)->hash('plain-password');
}
```

again: core already uses the "after" way almost exclusively.
also, this will help proceeding to the next step: removing `getPassword()` from `UserInterface`

### CODE REVIEW

**Comment by stof** [comment]
The higher-level API `UserPasswordEncoder` was added as part of the DX initiative a few years ago. /cc @weaverryan @javiereguiluz as you were the one responsible for it.

**Comment by javiereguiluz** [comment]
First of all, thanks to Robin and others for your efforts to improve Symfony security. Your work is much appreciated!

-----

I don't know if we should keep or remove the UserPasswordEncoder. I'll leave that decision to others. However, I don't like much the new proposal. The reason is that the code looks "cumbersome" *(I must use a factory to build something, when I just want to hash a password)* and it looks "too internal" *(I need to know the internals to know which methods to call)*.

I'd like the code to be as close as possible to what I want to do --> *"As a user, I want to hash the user password"*.

If you look at the current code, the needed code is almost a direct translation of the English text:

```php
public function someController(UserPasswordHasherInterface $passwordHasher) 
{
    // "I want to ...  hash ... the user ... password"
    $passwordHasher->hashPassword($user, 'plain-password');
}
```

This is how it looks the PR proposal:

```php
public function someController(PasswordHasherFactoryInterface $passwordHasherFactory) 
{
    $passwordHasherFactory->getPasswordHasher($user)->hash('plain-password');
}
```

And, for your consideration, here's a new proposal that hides all the internal stuff:

```php
public function someController(PasswordHasherInterface $passwordHasher) 
{
    $passwordHasher->hash($user, 'plain-password');
}
```

Thanks!

**Comment by chalasr** [comment]
Thanks for the explanation @javiereguiluz.
I think this is not worth the DX loss, and it's not required for the real upcoming improvements.
Closing here :)

**Comment by derrabus** [comment]
For the record, I also use `UserPasswordEncoder` quite frequently in applications and love how it hides the complexity of juggling different hashing algorithms from a piece of code that just needs to hash a password for a given user. Let's keep it. ❤️

**Pull request closed without merging**
