### PR TITLE
[Validator] Ensure a group is set on a constraint (fix BC break)

### LINKED ISSUE #44846: [Validator]BC break between 5.3.10 and 5.3.11 with custom Constraint and constructor promotion
### Symfony version(s) affected

5.3.11

### Description

```php
<?php

namespace App\Validator;

use Symfony\Component\Validator\Constraint;

#[\Attribute(\Attribute::TARGET_CLASS)]
class Foobar extends Constraint
{
    public function __construct(
        public bool $something,
    ) {
    }

    public function getTargets()
    {
        return self::CLASS_CONSTRAINT;
    }
}
```

* With SF 5.3.10, the following code works property
* With SF 5.3.11, it fails
  *  error:
  ``` >…home/gregoire/dev/tmp/custom-validator(master) php reproducer.php 
  TypeError {#83
    #message: "in_array(): Argument #2 ($haystack) must be of type array, null given"
    #code: 0
    #file: "./vendor/symfony/validator/Constraint.php"
    #line: 238
    trace: {
      ./vendor/symfony/validator/Constraint.php:238 { …}
      ./vendor/symfony/validator/Mapping/ClassMetadata.php:222 { …}
      ./vendor/symfony/validator/Mapping/Loader/AnnotationLoader.php:52 { …}
      ./vendor/symfony/validator/Mapping/Loader/LoaderChain.php:54 { …}
      ./vendor/symfony/validator/Mapping/Factory/LazyLoadingMetadataFactory.php:101 { …}
      ./vendor/symfony/validator/Validator/RecursiveContextualValidator.php:306 { …}
      ./vendor/symfony/validator/Validator/RecursiveContextualValidator.php:138 { …}
      ./vendor/symfony/validator/Validator/RecursiveValidator.php:93 { …}
      ./vendor/symfony/validator/Validator/TraceableValidator.php:66 { …}
      ./reproducer.php:18 {
        › $v = $k->getContainer()->get('validator');
        › $error = $v->validate(new Dto());
        › 
      }
    }
  }
  ```
  * to make it work, I have to call the parent constructor

### How to reproduce

I made a full reproducer here: https://github.com/lyrixx/test/commits/custom-validator

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44846
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Are you calling the constructor? Because if not, that's the issue. The property is supposed to be lazily initialized (that's why it's unset in the constructor)

**Comment by lyrixx** [comment]
> Are you calling the constructor?

No I don't. It used to work in previous version of symfony. And nothing force us to call the constructor (like it can be done in Command class). So to me it's a BC break and this PR solves this issue

**Comment by nicolas-grekas** [comment]
This change is going to break Composite constraints, see https://github.com/symfony/symfony/blob/4274a1f04707948dd0826ee37e1821154f4597af/src/Symfony/Component/Validator/Constraints/Composite.php#L82-L96

I understand this worked before because the property was undeclared. But to adapt to PHP 8.2, we have to declare all properties.
Using a typed property would work, but I'm not sure we can do so since we'll consider that adding the type is a BC break...

Any other idea?

**Comment by nicolas-grekas** [comment]
Instead, can't we check that the property is null, meaning it need to be unset and __get again before being usable?

**Comment by stof** [comment]
Also, I suggest trigger a deprecation saying that the parent constructor must be called.

**Comment by lyrixx** [comment]
> Also, I suggest trigger a deprecation saying that the parent constructor must be called.

how would you do that? with a check in all public method?

**Comment by nicolas-grekas** [comment]
What about #44854 instead?
Given that this happens at compilation, I think a LogicException is fine IMHO.

**Comment by ogizanagi** [comment]
Superseded by #44854

**Pull request closed without merging**
