### PR TITLE
[Console] Add class names as additional Helpers alias by default

### LINKED ISSUE #41310: [Console] Use class names as canonical name for Helpers by default
```diff
--- a/vendor/symfony/console/Helper/FormatterHelper.php
+++ b/vendor/symfony/console/Helper/FormatterHelper.php
 class FormatterHelper extends Helper
 {
     // [...]
     
     /**
      * {@inheritdoc}
      */
     public function getName()
     {
-        return 'formatter';
+        return self::class;
     }
 }

--- a/MyCommand.php
+++ b/MyCommand.php
 use Symfony\Component\Console\Command\Command;
+use Symfony\Component\Console\Helper\FormatterHelper;

 class MyCommand extends Command
 {
     // [...]
     
     protected function execute(InputInterface $input, OutputInterface $output)
     {
-        $formatter = $this->getHelper('formatter');
+        $formatter = $this->getHelper(FormatterHelper::class);
     }
 }
```

## Why

1. Less typing thanks to IDE autocompletion, immediate understanding and reference on the actual helper in use
2. To ease static analysis tools, which could infer the `$formatter` type to be the Helper name without additional maps to be maintained (or dynamically gathered by an additional `getName()` call or other calls to HelperSet)
3. To ease further `$formatter` IDE autocompletion without additional plugins

### PR DESCRIPTION
**Pull request by Slamdunk**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #41310
| License       | MIT
| Doc PR        | symfony/symfony-docs#... # Ok, soon

### CODE REVIEW

**Comment by stof** [comment]
Helpers are actually an extension point. For instance, by registering my own `formatter` helper with a child class of the FormatterHelper, I can change the formatting. If we automatically take the class name as the registration name, this won't work as the override won't be registered as `FormatterHelper::class`

**Comment by Slamdunk** [comment]
The result you describe is indeed good to me, as it encourages a better SOLID programming.

How do both the user and the IDE know the `formatter` API? There must be a type.
Without any interface, there is no obligation on the child class to be any similar to the parent one. Sure PHP 8 moved the signature incompatibilities from a `Warning` to a `Fatal error`, but that's not enough from an OOP perspective to be unaware of the type you are using.
Introducing interfaces would be cumbersome and useless for console helpers.
With this addition, if you like to extend an Helper class it also invites you to change all the references where you get that Helper so everyone (the users, SA tools and IDEs) know they are dealing with a possible different API.

**Comment by stof** [comment]
@Slamdunk then it is not an extension point anymore if you have to edit the third-party code to make it use your custom formatter.

**Comment by Slamdunk** [comment]
Mmm, I see indeed many external libraries already use the string notation.

So I guess that, if ever https://github.com/symfony/symfony/issues/41310 is going to be considered valuable, it should be implemented with `self::class` (no `static` then).

As for this PR, is looking for the top parent non-abstract class a good workaround to you, for `5.x`?

**Comment by stof** [comment]
> Without any interface, there is no obligation on the child class to be any similar to the parent one. Sure PHP 8 moved the signature incompatibilities from a `Warning` to a `Fatal error`, but that's not enough from an OOP perspective to be unaware of the type you are using.
> Introducing interfaces would be cumbersome and useless for console helpers.

Well, notice how I said that the custom helper extends the original one ? That would mean that the formatter still pass any typehint expecting the original helper.

**Pull request closed without merging**
