### PR TITLE
Add Missing Serbian (Lat & Cyrl) & Bosnian translation

### LINKED ISSUE #38728: Missing translations for Bosnian (bs)
Hello,

There are some missing translation for Bosnian (bs). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.bs.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.bs.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.bs.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.bs.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### LINKED ISSUE #38760: Missing translations for Serbian (sr_Cyrl)
Hello,

There are some missing translation for Serbian (sr_Cyrl). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.sr_Cyrl.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.sr_Cyrl.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.sr_Cyrl.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.sr_Cyrl.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### LINKED ISSUE #38761: Missing translations for Serbian (sr_Latn)
Hello,

There are some missing translation for Serbian (sr_Latn). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.sr_Latn.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.sr_Latn.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.sr_Latn.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.sr_Latn.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by tambait**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Tickets       | Fix #38760, fix #38761, fix #38728
| Deprecations? | no 
| License       | MIT

### CODE REVIEW

**Comment by Nyholm** [comment]
Let me know when you are ready for a review

**Comment by Nyholm** [comment]
Btw, you (usually) dont need to squash the commits. That is taken care of when we merge.

**Comment by tambait** [comment]
> Let me know when you are ready for a review

Should be ready for the review now. I put both Security & Form validator missing translations into this PR.

**Review by Nyholm — APPROVED** [review]
Excellent. Thank you. 

You translated 3 languages all at once. That is impressive. =)

👍

**Comment by tambait** [comment]
> You translated 3 languages all at once. That is impressive. =)

Serbian (Latin & Cyrillic script ), Bosnian (bs), Croatian (hr) and Montenegrian are four variants of one polycentric Serbo-Croatian language (sh) so they all differ slightly :)

**Comment by derrabus** [comment]
Thank you @tambait.

**Pull request merged**
