### PR TITLE
[PropertyInfo] Support Doctrine custom mapping type in DoctrineExtractor

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

Also use Doctrine\DBAL\Types\Type class constants

### CODE REVIEW

**Comment by teohhanhui** [comment]
@dunglas

**Comment by teohhanhui** [comment]
Uhh, wrong branch...

**Comment by dunglas** [comment]
:+1:

Status: Reviewed

ping @salahm

**Comment by fabpot** [comment]
Thank you @teohhanhui.

**Pull request closed without merging**
