### PR TITLE
[Routing] Add a 'has' method to the RouteCollection

### PR DESCRIPTION
**Pull request by voronkovich**
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

This method is usefull when you want just to check whether a route exists:

``` php
if ($router->getRouteCollection()->has('some_route')) {
    // ...
}
```

### CODE REVIEW

**Comment by HeahDude** [comment]
Maybe you should add a `testHas()` here: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Tests/RouteCollectionTest.php#L217)

**Comment by WouterJ** [comment]
Not 100% related to this PR, but *never* use `Router#getRouteCollection()`. This method will rebuilt all routing cache, meaning your application rebuilds routing cache each request and it'll be very slow: https://github.com/symfony/symfony/issues/7368

**Comment by voronkovich** [comment]
@WouterJ, thanks for the heads up! So, there is no way to check whether a route exists at runtime...

**Comment by WouterJ** [comment]
@voronkovich yeah, catching the exception is knowing whether the route exists or not:

```php
use Symfony\Component\Routing\Exception\RouteNotFoundException;

try {
    dump($router->generate('some_route'));
} catch (RouteNotFoundException $e) {
    dump('Oh noes, route "some_route" doesn't exists!');
}
```

**Comment by fabpot** [comment]
Closing as as @WouterJ mentioned, the route collection is an implementation detail that you should never use directly.

**Comment by WouterJ** [comment]
@fabpot do you know the reason why `getRouteCollection()` is part of the RouterInterface? (seems like you added it without any future references in https://github.com/symfony/symfony/commit/1467bdb86837e132891dd1b5605248a736cca5fe ) To me, it seems like this one should not be part of any interface and marked as `@internal` on the `Router` class (it's only used on the debug commands and web profiler)

**Comment by fabpot** [comment]
@WouterJ That's very old :) I think this can be deprecated.

**Comment by stof** [comment]
@WouterJ the getRouteCollection was necessary for the old implementation of the router cache warming.

**Pull request closed without merging**
