### PR TITLE
[HttpCache] add option to passthrough HEAD requests to the backend

### PR DESCRIPTION
**Pull request by pictaile**
| Q             | A
| ------------- | ---
| Branch?       | master for features / 3.4 up to 4.2 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| BC breaks?    | no     
| Deprecations? | yes/no 
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by dmaicher** [comment]
@pictaile this was rejected in https://github.com/symfony/symfony/pull/20998#issuecomment-268772830

**Comment by fabpot** [comment]
@pictaile Can you explain the reasons why you need this change?

**Comment by pictaile** [comment]
As @mangelsnc [wrote]( https://github.com/symfony/symfony/issues/20893#issuecomment-267906659). There is pattern when `HEAD` check resource if resource exist system redirect to `GET` we can take resource. I think there must be a way change `HEAD` and `GET` in the Route.

example:

```
/**
     * @Route("/document/{id}", methods={"HEAD"}, requirements={"id"="\d+"})
     * @return Response
     */
    public function headAction(string $id): Response
    {
        return new Response('', Response::HTTP_NOT_FOUND);
    }
```

Second reason is covered in [Clean Code](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882).  There is concept "Least surprise". 
For me Least surprise is separate method GET and HEAD. Y think if i can write `methods={"GET"}` , `methods={"POST"}` that I can write `methods={"HEAD"}` (it surprise for me that I can't write this). 

I know from [RFC7231](https://tools.ietf.org/html/rfc7231#section-4.3.2) 

> The HEAD method is identical to GET

However, there are **different** HTTP methods.

I propose create method HEAD, because we will get lot of questions about it.

**Comment by pictaile** [comment]
Have you any ideas?

**Comment by fabpot** [comment]
Implementing RFC7231 is following the concept of "least surprise". So, I'm going to close for the same reasons as mentioned in #20998.

**Pull request closed without merging**
