### PR TITLE
[Security] Adding a GuardAuthenticatorHandler alias

### PR DESCRIPTION
**Pull request by weaverryan**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | kinda
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | This feature is not currently documented

The `security.authentication.guard_handler` service *is* actually meant to be available for users to use. Specifically, the `authenticateUserAndHandleSuccess()` method is useful to auto-login the user after, for example, registration, but maintain all the behavior of a normal login (success behavior, trigger the login event).

So, it should have an autowiring alias.

### CODE REVIEW

**Comment by Simperfit** [comment]
It seems that the file loader can't load the file anymore, could you please check why ?

**Comment by weaverryan** [comment]
@Simperfit yea, I borked it :). Let's try that again

**Review by nicolas-grekas — APPROVED** [review]
3.4?

**Comment by weaverryan** [comment]
Yea, it could be considered a bug fix: it really *should* be usable by the end-user. When the service became private in 4.0, that made it not easily usable. So, I think 3.4 makes sense (we could do 3.3... but I don't want to make a policy of back-porting all aliases to 3.3: we just need to make sure they exist on 3.4 so people can upgrade)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @weaverryan.

**Pull request closed without merging**
