### PR TITLE
[Mime][Security] Fix missing sprintf and add tests

### PR DESCRIPTION
**Pull request by alamirault**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |  

https://github.com/symfony/symfony/pull/44808 fix one missing sprintf. This PR fix other cases and add tests.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
(for 5.3)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Can you rebase on 5.3 an create another PR for the exception that did not exist back then?

**Comment by alamirault** [comment]
This PR is now only for AccessListener (6.0).

https://github.com/symfony/symfony/pull/44824 for DkimSigner (5.3)

Is it ok ? did I misunderstand ?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alamirault.

**Pull request merged**
