### PR TITLE
Fix Psalm errors

### PR DESCRIPTION
**Pull request by danepowell**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | Not sure what you call a CI fix 🤷 
| New feature?  | no 
| Deprecations? | no 
| License       | MIT

Psalm runs frequently fail, such as https://github.com/symfony/symfony/pull/48981

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by derrabus — APPROVED** [review]
Do we need to backport this change to 5.4?

**Comment by danepowell** [comment]
The [Symfony 5.4 version of MigratingSessionHandler](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/MigratingSessionHandler.php) does not use intersection types, so it does not suffer from this problem. No backport needed unless you run CI on a branch other than 5.4 or 6.3.

**Comment by stof** [comment]
Given that Psalm v5 has support for intersection type, it would be better to migrate to psalm v5 in our CI.

**Comment by danepowell** [comment]
> Given that Psalm v5 has support for intersection type, it would be better to migrate to psalm v5 in our CI

We're [already using Psalm v5](https://packagist.org/packages/psalm/phar), what makes you think that we aren't? See the `@see` link, I'm pretty sure this is an upstream bug in Psalm, not a general lack of support for intersection types.

**Comment by wouterj** [comment]
Psalm does support intersection types, so this patch seems too generic to me. https://psalm.dev/r/1daf678918

The referenced bug talks about using *build-in* types in intersection types, which seems to be broken: https://psalm.dev/r/bea279b49e

**Comment by stof** [comment]
> what makes you think that we aren't?

What made me think that we aren't is the comment in the code saying "remove this when Psalm implements intersection types", while Psalm v5 has implemented them.

**Comment by danepowell** [comment]
Ah I see what you mean, I'll update the comment to indicate that this is a Psalm bug and not a lack of support.

**Comment by danepowell** [comment]
@wouterj are you saying you want to see a new Psalm bug opened?

**Comment by danepowell** [comment]
Let me know what you want on this, it would really help contributors (and maintainers, I imagine!) to have all tests passing.

**Comment by wouterj** [comment]
Sorry, I misread the changes (I thought it was doing a global find&replace instead of a local one in the file). Let's go :+1: 

(the Psalm bug you referenced is good enough, the maintainers are already on the case it seems and it is about the same issue)

**Comment by fabpot** [comment]
Thank you @danepowell.

**Pull request merged**
