### PR TITLE
Php cs fixer

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | no |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by ro0NL** [comment]
This reflects the entire codebase right? :open_mouth:

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by Oliboy50** [comment]
`Tests pass? 	yes` ?

**Comment by Tobion** [comment]
:+1:

**Pull request merged**
