### PR TITLE
Release v2.7.6

### LINKED ISSUE #15118: [Filesystem] mirroring a symlink copies absolute file path
When using mirror(), I would expect that relative symlinks stay relative after they are copied, but instead they are converted to absolute references to the source directory.

For instance, given this symlink in the source directory:
```/source/bin/behat -> ../vendor/behat/behat```
(implicitly ```/source/bin/behat -> /source/vendor/behat/behat```)

After mirroring that directory, the expected result is:
```/target/bin/behat -> ../vendor/behat/behat```
(implicitly ```/target/bin/behat -> /target/vendor/behat/behat```)

But the actual result is:
```/target/bin/behat -> /source/vendor/behat/behat```

This was originally fixed in #9866, and then regressed in a8b8d33e942566fb858e78d35aa843d7fe77cb11

### PR DESCRIPTION
**Pull request by fabpot**
Changes since last release: https://github.com/symfony/symfony/compare/v2.7.5...88db7c0

**Changelog**
- bug #16338 [VarDumper] Fix anonymous class dumping (@nicolas-grekas)
- bug #16288 [Process] Inherit env vars by default in PhpProcess (@nicolas-grekas)
- bug #16302 [DoctrineBridge] Fix required guess of boolean fields (@enumag)
- bug #16298 Changed one console output style to avoid visual issues (@javiereguiluz)
- bug #16291 [VarDumper] Fix return type and anonymous classes dumping (@nicolas-grekas)
- bug #16177 [HttpFoundation] Fixes /0 subnet handling in IpUtils (@ultrafez)
- bug #16262 [TwigBundle] Fix Twig cache is not properly warmed (@tucksaun)
- bug #16259 [Validator] Allow an empty path in a URL with only a fragment or a query (@jakzal)
- bug #16226 [filesystem] makeRelativePath does not work correctly from root (@jaytaph, @fabpot)
- bug #16108 [Security] #15764. Use SessionAuthenticationStrategy on RememberMe login (@s12v)
- bug #16196 [Console] Fix progress bar formatting when max is set on start() and some other edge cases (@vsychov, @fabpot)
- bug #16183 [VarDumper] Fix wordwrap with Bootstrap (@ogizanagi)
- bug #16182 [Process] Workaround buggy PHP warning (@cbj4074)
- bug #16095 [Console] Add additional ways to detect OS400 platform (@johnkary)
- bug #15793 [Yaml] Allow tabs before comments at the end of a line (@superdav42)
- bug #16152 Fix URL validator failure with empty string (@fabpot, @bocharsky-bw)
- bug #15121 fixed #15118 [Filesystem] mirroring a symlink copies absolute file path (@danepowell)
- bug #15161 avoid duplicated path with addPrefix (@remicollet)
- bug #16146 [Security] sync translations and add a test for it (@xabbuh)
- bug #16133 compatibility with Security component split (@xabbuh)
- bug #16123 Command list ordering fix (@spdionis, @fabpot)
- bug #14842 [Security][bugfix] "Remember me" cookie cleared on logout with custom "secure"/"httponly" config options  (@MacDada)
- bug #13627 [Security] InMemoryUserProvider now concerns whether user's password is changed when refreshing (@issei-m)
- bug #16090 Fix PropertyAccessor modifying array in object when array key does no… (@pierredup)
- bug #16092 [Process] Throw exception if tempnam returns false (@pierredup)
- bug #16111 Throw exception if tempnam returns false in ProcessPipes (@pierredup)
- bug #16087 Fixing typo in variable name (@yceruto)
- bug #16053 [Console] use PHP_OS instead of php_uname('s') (@xabbuh)
- Merge branch '2.3' into 2.7
- bug #15860 [Yaml] Fix improper comments removal (@ogizanagi)
- bug #16050 [TwigBundle] fix useless and failing test (@Tobion)
- bug #16028 [DomCrawler] always pass base href to subcrawlers (@xabbuh)
- bug #15482 [Yaml] Improve newline handling in folded scalar blocks (@teohhanhui)
- bug #15976 [Console] do not make the getHelp() method smart (@xabbuh)
- bug #15799 [HttpFoundation] NativeSessionStorage `regenerate` method wrongly sets storage as started (@iambrosi)
- bug #15446 [Twig][Bridge] force space between widget and label in checkbox_radio_label (@MatTheCat)
- bug #15533 [Console] Fix input validation when required arguments are missing (@jakzal)
- bug #15915 Detect Mintty for color support on Windows (@stof)
- bug #15906 Forbid serializing a Crawler (@stof)
- bug #15682 [Form] Added exception when setAutoInitialize() is called when locked (@jaytaph)
- bug #15776 [TwigBridge] fix with_minutes option in time widget (@arduanov)
- bug #15846 [FrameworkBundle] Advanced search templates of bundles (@yethee)
- bug #15895 [Security] Allow user providers to be defined in many files (@lyrixx)

### CODE REVIEW

**Comment by sstok** [comment]
What the, is there a special reason for doing a release like this? :) with `@name` you will ping everyone who has contributed.

**Comment by WouterJ** [comment]
Yeah, I was also wondering if you couldn't add something like `\@xxx` instead of `@xxx` for the PR descriptions, to avoid pinging everyone.

**Comment by bocharsky-bw** [comment]
I like this kind of release. BTW, releases not so frequent.

**Comment by nicolas-grekas** [comment]
Its worth noticing people who contributed to some release IMHO, e.g. both to thank them again implicitly, and to tell them they can upgrade and use the fix they where waiting for.

**Comment by MacDada** [comment]
> I like this kind of release. BTW, releases not so frequent.

> Its worth noticing people who contributed to some release IMHO […] to tell them they can upgrade and use the fix they where waiting for.

:+1: I made PRs because I need them in my projects, good to know I can upgrade :)

**Comment by spdionis** [comment]
:+1: to notifications when a pr gets into a release.

**Pull request merged**
