### PR TITLE
Support for resources directory

### PR DESCRIPTION
**Pull request by enleur**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

We should support resources directory according to https://github.com/php-pds/skeleton#resources

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
We never decided to follow php-pds/skeleton, so I'm not sure this makes sense.

**Comment by enleur** [comment]
In our project we have bunch of static resources like xml/json templates, wsdl data, e.g. Now it lives in app/Resources/ together with twig templates. Where it supposed to be in the Symfony Flex directory structure?

**Comment by nicolas-grekas** [comment]
in `src/Resources` AFAIK

**Comment by enleur** [comment]
should I change path in the PR?

**Comment by ro0NL** [comment]
`src/Resources` equals `%kernel.root_dir%/Resources` in flex :) due root_dir usage and the kernel living in `src/` by default.

However adding `%kernel.project_dir%` makes sense i guess. So you could use custom dirs like `etc/my-resource`.

**Pull request closed without merging**
