### PR TITLE
[Console] Do not check for "stty" using "exec" if that function is disabled

### PR DESCRIPTION
**Pull request by mvorisek**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | no
| License       | MIT
| Doc PR        | no

fixes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5030

### CODE REVIEW

**Comment by mvorisek** [comment]
Please verify AppVeyor tests and if ok, please merge asap.

**Comment by nicolas-grekas** [comment]
Is this really enough? other parts of the component use shell_exec, and I'd suspect exec and shell_exec to be disabled at the same time.

I'm not sure it makes much sense also to run console commands without exec: if you can run a Symfony command, it means you can run any command, isn't it?

**Comment by mvorisek** [comment]
> I'm not sure it makes much sense also to run console commands without exec: if you can run a Symfony command, it means you can run any command, isn't it?

Some users have these functions disabled for cli (like for web where it is very usual). Console library should not throw if exec is not available - because `stty` can not be called anyway then.

Example of usecase: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5030

CS fixer and any library that does not need to start another process does not need `exec` or similar functions.

> Is this really enough? other parts of the component use shell_exec, and I'd suspect exec and shell_exec to be disabled at the same time.

Yes, only this one.

**Review by nicolas-grekas — APPROVED** [review]
I checked the source: all calls to `shell_exec()` in Console have an `hasSttyAvailable()` check before, that's why it's fine to check only for `exec`.

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mvorisek.

**Pull request merged**
