### PR TITLE
[Process] don't populate internal buffer if user closure is supplied

### PR DESCRIPTION
**Pull request by avindra**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17390 |
| License | MIT |
| Doc PR | N/A |

Requesting a pull to main repo instead of readonly mirror.

### CODE REVIEW

**Comment by avindra** [comment]
Is there a way to re-run fabbot.io?

**Comment by xabbuh** [comment]
@avindra fabbot.io should be triggered again when you add commits or change the existing one (meaning you have to do a forced push afterwards).

**Comment by avindra** [comment]
Just tweaked some README grammar, and did a force push, now seeing : 

```
AppVeyor was unable to build non-mergeable pull request
```

:frowning:

**Comment by Ener-Getick** [comment]
@avindra you must rebase your PR on ``master`` or recreate it if ``master`` is not the branch you wanted to target.

**Comment by avindra** [comment]
Done. Please review, thank you.

**Comment by romainneutron** [comment]
Closed in favor of https://github.com/symfony/symfony/pull/17427 and https://github.com/symfony/symfony/pull/17423

**Pull request closed without merging**
