### PR TITLE
[WIP] [2.8] [Form] fix FQCN in tests added by #17760

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | not yet |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | - |
- [x] Update tests from #17760
- [x] Wait for #17760 to be merged in 2.8

### CODE REVIEW

**Comment by HeahDude** [comment]
Before :

```
Time: 10.5 seconds, Memory: 122.00Mb

There were 2 failures:

1) Symfony\Component\Form\Tests\Extension\Core\Type\ChoiceTypeTest::testChoiceListWithBooleanAsValues
Failed asserting that two strings are identical.

/Users/Heah/Sites/dev/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php:140

2) Symfony\Component\Form\Tests\Extension\Core\Type\ChoiceTypeTest::testPlaceholderWithBooleanChoices
Placeholder should be set
Failed asserting that false is true.

/Users/Heah/Sites/dev/symfony/src/Symfony/Component/Form/Tests/Extension/Core/Type/ChoiceTypeTest.php:240

FAILURES!
Tests: 3195, Assertions: 7009, Failures: 2, Skipped: 221, Incomplete: 11.

Legacy deprecation notices (220)
KO ./src/Symfony/Component/Form
```

After :

```
Time: 10.51 seconds, Memory: 122.00Mb

OK, but incomplete, skipped, or risky tests!
Tests: 3195, Assertions: 7013, Skipped: 221, Incomplete: 11.

Legacy deprecation notices (220)
OK ./src/Symfony/Component/Form
```

**Comment by xabbuh** [comment]
Isn't this the same as #17760?

**Comment by HeahDude** [comment]
@xabbuh indeed. But as for #17694 tests in 2.8 need FQCN or they will fail.
Once #17760 is merged, this PR will fix them.

**Comment by iltar** [comment]
What if someone uses `null`?

**Comment by HeahDude** [comment]
@iltar it returns an empty string as expected. But it was the same for false which caused these bugs.

**Comment by HeahDude** [comment]
Status : Needs Work

**Comment by fabpot** [comment]
#17760 has been merged.

**Comment by fabpot** [comment]
Is this one still needed?

**Comment by HeahDude** [comment]
No let's close.

**Comment by HeahDude** [comment]
But it would be more consistent with other tests. I missed the ping this should have been merged before #17886 :(

Will there be some conflicts ? I let you decide to close then.

**Comment by HeahDude** [comment]
I've rebased, it's up to you.

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Pull request merged**
