### PR TITLE
[WebProfilerBundle] Replaced raster PNG icons with vector SVG icons

### PR DESCRIPTION
**Pull request by sgrodzicki**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Cool! Can you please add a screenshot?

**Comment by sgrodzicki** [comment]
Before:

raster

After:

vector

**Comment by stof** [comment]
:+1: 

Can you also send PRs to SwiftmailerBundle and DoctrineBundle to update their profiler panels ?

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
Can you please squash your commits in one?

**Comment by sgrodzicki** [comment]
@stof I haven't recreated any third-party icons yet, so I suggest these changes should proceed independently.

**Comment by sgrodzicki** [comment]
@nicolas-grekas done.

**Comment by stof** [comment]
@sgrodzicki of course they will be done independently as they are in different repos anyway. But it would be great if you can work on them to have a consistent design.

**Comment by sgrodzicki** [comment]
@stof sure. Give me a couple of days.

**Comment by nicolas-grekas** [comment]
@sgrodzicki please check #13463 : I took your commit but replaced data-uri svg by inline svg. I also removed the xlink @Tobion identified. Are you willing to svg-ize the remaining images? I ask just to know if you want us to wait for them or not. Feel free to `reset --hard` to the commit in #13463 in this PR. I've no pb with giving you back the commit for this PR.

**Comment by sgrodzicki** [comment]
@Tobion my intend was to replace all icons not all graphics.

@nicolas-grekas have you seen the result with the `svg` tag? It renders quite different and that's why I've used the `img` + base64 way.

What's left to get this merged?

**Comment by Tobion** [comment]
Which graphic is not an icon in symfony? I think they all qualify as vector icons.

**Comment by sgrodzicki** [comment]
Any obstacles before merging?

**Comment by nicolas-grekas** [comment]
@sgrodzicki can you please have a look at #13463 again? I fixed the issue with positioning. It was just a matter of adding the width+height attributes and a few CSS rules. There are more PNG in the source code. Are you willing to make SVG icons for them also?

**Comment by sgrodzicki** [comment]
I've currently a case-sensitive filesystem and therefore unable to run Adobe Illustrator. I suggest we merge the current work and add those missing images (which are in different places) later. Cool?

**Comment by nicolas-grekas** [comment]
Thank you @sgrodzicki this is now merged (see #13463)

**Pull request closed without merging**
