### PR TITLE
[HttpKernel] Generic templates for `ControllerArgumentsEvent`,`ControllerEvent` and `ExceptionEvent`

### PR DESCRIPTION
**Pull request by fractalzombie**
Added generic templates in `ControllerArgumentsEvent`,`ControllerEvent` and `ExceptionEvent`.

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

[HttpKernel] Added generic templates in `ControllerArgumentsEvent`,`ControllerEvent` and `ExceptionEvent` for IDE IntelliSense support.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I'm not sure I see the point of these here. Can you explain why that is useful?

**Comment by fractalzombie** [comment]
> I'm not sure I see the point of these here. Can you explain why that is useful?

Yep, in some cases i want to see ExceptionEvent::getThrowable without phpdoc on variable. In this case i add php doc, but it's can be solved if i add it to interface.

If you think it's not useful - we can close PR.

Снимок экрана 2021-12-18 в 19 55 25

**Comment by derrabus** [comment]
In this case, the generics really don't make sense imho. A listener on one of those events cannot assume a certain type for the controller or throwable, it actually _has_ to check the type. And static analyzers should understand guard clauses with type checks.

**Comment by fractalzombie** [comment]
> In this case, the generics really don't make sense imho. A listener on one of those events cannot assume a certain type for the controller or throwable, it actually _has_ to check the type. And static analyzers should understand guard clauses with type checks.

ok

**Pull request closed without merging**
