### PR TITLE
[Workflow] fixed $context not available on GuardEvent

### PR DESCRIPTION
**Pull request by maikelohcfg**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no 
| Tickets       | 
| License       | MIT

For Workflow component, the $context should be available for all events as described on official doc, but GuardEvent don't receive the $context when is instantiated, the context is useful in many ways,  so grant access to it on GuardEvent allow developers to get custom payload on workflow guard event listeners

### CODE REVIEW

**Comment by Nyholm** [comment]
Hey. Thank you for this PR. 

Could you please give me a link to where in the docs it says that `$context` should be part of the Guard event. Im not sure if this is a bug fix or a new feature or a bug in the docs. 
A quick search on the merged issues says that we never intended to add `$context` on guard events (which means it is a new feature)

**Comment by maikelohcfg** [comment]
Hello @Nyholm 

check on https://symfony.com/doc/current/workflow.html#using-events

In Symfony 5.2, the context is accessible in all events:
`
// $context must be an array
$context = ['context_key' => 'context_value'];
$workflow->apply($subject, $transitionName, $context);

// in an event listener
$context = $event->getContext(); // returns ['context']
`
based on this, I don't see my pull request as a new feature.

I think it is useful to have an instance of `$context` on GuardEvent so developers can pass custom payload if needed to subscribers of GuardEvent.

Have a nice day

**Review by derrabus — CHANGES_REQUESTED** [review]
Adding an additional parameter to all those methods is a breaking change and has to come with a proper deprecation layer. There's no way we can do this in a bugfix release.

**Comment by xabbuh** [comment]
In the PR that introduced this feature guard events were not changed on purpose: https://github.com/symfony/symfony/pull/37539#issuecomment-656176051

This looks like something that needs to be changed in the documentation instead.

**Comment by maikelohcfg** [comment]
> Adding an additional parameter to all those methods is a breaking change and has to come with a proper deprecation layer. There's no way we can do this in a bugfix release.

I agree with you if this changes become has a breaking change, but it is backward compatibility because it is optional just for the case if needed, so I don't see the need to deprecated anything.

**Comment by maikelohcfg** [comment]
Hello @xabbuh 

> In the PR that introduced this feature guard events were not changed on purpose: [#37539 (comment)](https://github.com/symfony/symfony/pull/37539#issuecomment-656176051)
> 
> This looks like something that needs to be changed in the documentation instead.

After read the thread you suggest, I see your point, but let me talk about my use case and why I see the need to have access to context on GuardEvent.

I am working on some chatbots where the conversation state is handled by Workflow with  `state_machine`, manage the transitions between states must be validated based con incoming message, so here it comes the GuardEvent which validate and allow the transition between states, but it requires the incoming message is data as payload to do its job. 

The `$context` is useful in so many ways to all events of the workflow if the developer require it.

I hope you see my point, otherwise I am open to discuss better approach to implement this use case.

Have a nice day

**Comment by derrabus** [comment]
> it is backward compatibility because it is optional

No, it isn't. For example, if I had a custom implementation of `WorkflowInterface` in my app, that implementation won't have your new optional parameter. If we merged your PR as is, my code would break next time I upgrade the workflow component.

See https://3v4l.org/3uko6

> I don't see the need to deprecated anything.

Yes, we would need to deprecate implementations of `WorkflowInterface` without the new optional parameter. We cannot do this is a bugfix release.

Your use-case might be valid, but this change is by our definition a new feature. I'm moving this to the 6.1 milestone which is our next feature release.

**Comment by Nyholm** [comment]
Awesome. Now it is correctly labeled as a new feature in 6.1. 

May I ask @lyrixx to elaborate on [this comment](https://github.com/symfony/symfony/pull/37539#issuecomment-656176051) where you say you are agains guard events having context?

**Comment by maikelohcfg** [comment]
Hi @derrabus 

You have all the right, I have done the requested changes.

Thanks for your support

**Comment by maikelohcfg** [comment]
Hi @lyrixx I would like to listen your opinion too about why not `$context` on GuardEvent. 

Thanks in advance

**Review by derrabus — CHANGES_REQUESTED** [review]
> I have done the requested changes.

Well, no. You have added a new method to an interface which is also a breaking change. Also, the original problem is still there for all other methods of the interface.

But let's first discuss this feature first. I'm certain someone will help you building the deprecation layer once we've come to a decision about this feature.

**Comment by lyrixx** [comment]
> Hi @lyrixx I would like to listen your opinion too about why not `$context` on GuardEvent.

Hello,

I always refused to add the context to the apply method because the context (must) contains only "contextual" content (date, user, for example)

To me, the decision to accept of deny a transition should only occurs against the subject that pass into the workflow.

If you want to vote on somethings else, it should be on the subject. BTW, this value does't have to be persisted.

**Comment by maikelohcfg** [comment]
Thanks, @lyrixx, for your reply 

I understand your argument, it makes sense from your point of view, but the end developer using workflow must have the choice to decide what is needed as contextual based on his needs.

Workflow is an excellent component, but in my opinion must be consistent with the docs about the context is available to all events, not a few of them only, because it makes confuse use it.

Take this only has a constructive opinion, I am open to contribute and help to improve this component.

**Comment by lyrixx** [comment]
> , but in my opinion must be consistent with the docs about the context is available to all events, not a few of them only, because it makes confuse use it.

Sure, the doc must be fixed :) Would you mind to submit a PR? That would be lovely. Thanks

**Comment by maikelohcfg** [comment]
Already done

**Pull request closed without merging**
