### PR TITLE
[3.0] Removed unneeded polyfill

### PR DESCRIPTION
**Pull request by GrahamCampbell**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

Surely we don't need these on 3.x?

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I also need to sort this out in all the other composer.json files, which was hard to do from the GitHub web interface, so I'll pull this down to my machine in a bit and sort that.

**Comment by GrahamCampbell** [comment]
Actually, now that I've pulled it down, I see that stuff has already been dealt with, and it's just the main composer.json file that needs updating. ;)

**Comment by xabbuh** [comment]
:+1:

**Comment by Tobion** [comment]
Thank you @GrahamCampbell.

**Comment by GrahamCampbell** [comment]
:)

**Pull request merged**
