### PR TITLE
[HttpFoundation] Fix some typo in the Request doc

### PR DESCRIPTION
**Pull request by alOneh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by dunglas** [comment]
:+1:

**Comment by romqin** [comment]
:+1:

**Comment by funkymed** [comment]
:+1:

**Comment by ogizanagi** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @alOneh.

**Pull request merged**
