### PR TITLE
[DI] Ignore missing tree root nodes on validate

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | technically yes
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #27450
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
LGTM, with a test case would be even better :)

**Review by nicolas-grekas — APPROVED** [review]

**Review by xabbuh — CHANGES_REQUESTED** [review]
The conflict rule for the DependencyInjection component must now be updated:

```
"symfony/config": "<4.1.1"
```

**Comment by ro0NL** [comment]
nice catch. Done

status: needs review

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request merged**
