### PR TITLE
Fix: Article

### PR DESCRIPTION
**Pull request by localheinz**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

This pull request

* [x] fixes usages of the indefinite article `a` where `an` should be used instead

### CODE REVIEW

**Review by wouterj — APPROVED** [review]
Personally, I pronounce this as "cliff", which would indicate "a" instead of "an".

However, looking [at the XLIFF spec](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html), they use "an XLIFF document" (except from 1 occasion, I guess that's a typo). So :+1:

**Comment by localheinz** [comment]
@wouterj 

There are more cases which I have adjusted as well.

**Comment by localheinz** [comment]
Issues reported by `fabbot.io` appear to be unrelated.

**Review by chalasr — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
Thank you Andreas.

**Comment by localheinz** [comment]
Thank you, @chalasr and @xabbuh!

**Pull request merged**
