### PR TITLE
[DI] deprecate the strict attribute

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/20938#discussion_r92660355
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
My concerns are here: https://github.com/symfony/symfony/pull/20938#discussion_r92873633
So if you considered them but still think this should be the way to go, I'm OK.
(which means I'm +0 :) )

**Comment by nicolas-grekas** [comment]
:+1:
if bundles need to support SF 2 & 4 and are bothered about this "strict" attribute, they can very well have two different xml files.

**Comment by stof** [comment]
if they need to support both 2.x and 4.x, they cannot rely on the ``strict=false`` feature anyway (as it is always string in Symfony 3+), and so they can omit the attribute even in 2.x (as the default behavior of 2.x is the one we kept).

👍 about this.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
