### PR TITLE
[CS] Use combined assignment operators when possible

### PR DESCRIPTION
**Pull request by carusogabriel**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | -   
| License       | MIT
| Doc PR        | - 

Less opcodes for us :smile:

### CODE REVIEW

**Review by ro0NL — APPROVED** [review]

**Comment by javiereguiluz** [comment]
@carusogabriel you are involved in the core PHP development, so I'd like to ask you something about this.

In my opinion, in most of the proposed changes the original code is more readable and easier to understand. For example:

```php
$file = $file.'.'.$this->getFileExtension();
$file .= '.'.$this->getFileExtension();
```

The first line is easier to understand for me because I just need to read it to know what it does. The second line has some "complication" and you need to "compile it" in your head to understand it.

So, here's my question related to what you said (*"less opcodes for us"*). Doesn't PHP (or OPCache) do this optimization when compiling the code? If it doesn't ... shouldn't do it? It's a trivial optimization for a machine ... and that would allow us to keep using the "more readable for humans" code.

Thanks!

**Comment by carusogabriel** [comment]
> The first line is easier to understand for me because I just need to read it to know what it does. The second line has some "complication" and you need to "compile it" in your head to understand it.

@javiereguiluz Yeah, I agree with you. Even for trivial cases, e.g. https://3v4l.org/TCEJg, we need some time to understand sometime what is going on if we are not familiar with the operator.

> So, here's my question related to what you said ("less opcodes for us"). Doesn't PHP (or OPCache) do this optimization when compiling the code? If it doesn't ... shouldn't do it? It's a trivial optimization for a machine ... and that would allow us to keep using the "more readable for humans" code.

My answer, unfortunately, is **I don't know**. OPCache is one of the parts of the PHP Internals that I haven't have the change to look up yet, but, I'm gonna take this question to those how knows, as, yes, the following refactor https://3v4l.org/gABQl/vld#output vs. https://3v4l.org/fdLjt/vld#output generates less opcodes, but isn't more readable.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @carusogabriel.

**Comment by TomasVotruba** [comment]
@carusogabriel Did you automate it some way? :)

**Comment by carusogabriel** [comment]
@TomasVotruba Yeap, using https://github.com/slevomat/coding-standard, specific the rule `SlevomatCodingStandard.Operators.RequireCombinedAssignmentOperator`.

**Pull request merged**
