### PR TITLE
[FrameworkBundle][Security] Remove useless mocks

### PR DESCRIPTION
**Pull request by GuilhemN**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Removes mocks causing issues in https://github.com/symfony/symfony/pull/19734.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:
Status: reviewed

**Comment by fabpot** [comment]
Thank you @Ener-Getick.

**Comment by Ener-Getick** [comment]
@fabpot Thanks to you !

BTW shouldn't your tool merging PRs use a more generic reference such as `symfony/symfony#19736` ?
Because [references are broken in commits title of sub repositories](https://github.com/symfony/security/commit/66a4782ddd0539e1b4f2ae2b4058a04af5d21aab).

**Comment by fabpot** [comment]
That's a good remark. But I'm afraid that adding symfony/symfony in front would make the message way less readable :(

**Comment by Ener-Getick** [comment]
@fabpot if i'm not wrong github is smart enough to hide it when that's not necessary (in the main repo).

**Comment by fabpot** [comment]
probably, but I was more talking about git in general, like when doing git log, ...

**Comment by Ener-Getick** [comment]
That's a good argument :/ 
maybe you could update references in splitter to make them longer only in sub repos ? Otherwise that's still just a small detail, convenient but it shouldn't make other things harder of course.

**Pull request merged**
