### PR TITLE
[HttpKernel][Console?] Fix script exit code when throwing Error

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/issues/20775
| License       | MIT
| Doc PR        | N/A

I'm not sure that's the proper way to fix it, but I don't have any better idea 😕

### CODE REVIEW

**Comment by ogizanagi** [comment]
Is there anything else we could do here?
This related issue seems pretty critical to me.

**Comment by fabpot** [comment]
Closing as I've tested and it has been fixed since then.

**Comment by Jean85** [comment]
Maybe this should be reopened, since @fabpot reopened the issue?

**Comment by chalasr** [comment]
I confirm this is still relevant, the bug exists only using the full-stack framework.

**Comment by ogizanagi** [comment]
Reopened in #22134

**Pull request closed without merging**
