### PR TITLE
[Clock] Add get/setMicroseconds()

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | -
| License       | MIT

Polyfilling https://github.com/php/php-src/pull/12557

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
One question here: how confident are we that the new PHP method won't be changed between now and the PHP 8.4 feature freeze in a way that would break our child method ? Symfony 7.1 will be released 6 months before PHP 8.4.
If we are not 100% confident, we should delay that to Symfony 7.2 to avoid making it impossible to make the component compatible with PHP 8.4 without BC break.

**Comment by nicolas-grekas** [comment]
The only thing that could change is the return type of the native methods, which we already set (they're tentative-return-types in the engine for now). I'm 99.9% confident this is going to be compatible with 8.4 :)

**Comment by OskarStark** [comment]
Just in case would it be possible to mark the methods experimental?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by marc-mabe** [comment]
FYI https://github.com/php/php-src/pull/13486 Not sure it it goes through

**Pull request merged**
