### PR TITLE
[VarDumper] Add controller & project dir to HTML output

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | yes (fix callable controller support)
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | N/A   
| License       | MIT
| Doc PR        | N/A

Promise made, here is the missing controller info in HTML output (and additionally the project dir).

screenshot 2018-04-08 a 19 19 30
screenshot 2018-04-08 a 19 19 19

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Just wondering: how will this behave when the controller is not a string? Eg a closure?

**Comment by ogizanagi** [comment]
Hmm, good catch, that'll be an issue (it won't even be unserialized properly). This needs to be fixed in the `RequestContextProvider`. An option could be cloning and dumping it. But not sure it is worth it.

Status: Needs work.

**Comment by ogizanagi** [comment]
Thanks for the hint, but I'm not sure how to leverage it directly? Anyway, what would you think of this?

### HTML

|Collapse by default|Expanded|
|--|--|
|screenshot 2018-04-10 a 19 18 11|screenshot 2018-04-10 a 19 29 55|

### CLI

screenshot 2018-04-10 a 19 19 01

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @ogizanagi.

**Pull request merged**
