### PR TITLE
Fix constraint validator alias being required

### PR DESCRIPTION
**Pull request by Mx-Glitter**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16805 |
| License | MIT |
| Doc PR | symfony/symfony-docs#6055 |

This is my first contribution, so everything might not be in perfect order.

Follow-up of #16841 on the right branch.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@Triiistan could you please rebase to trigger tests again?

**Comment by Triiistan** [comment]
@nicolas-grekas Done

**Comment by Triiistan** [comment]
Fixed a typo + rebased again

**Comment by fabpot** [comment]
Shouldn't this be merged into older branches? It can be seen as a bug fix as having to repeat the class under the alias item seems useless.

**Comment by fabpot** [comment]
:+1:

**Comment by Triiistan** [comment]
I did that because the current behavior is [already documented](https://symfony.com/doc/current/cookbook/validation/custom_constraint.html#constraint-validators-with-dependencies), so I supposed this was a new feature. But I agree with you that it looks like a bug fix.

**Comment by fabpot** [comment]
It's indeed documented as being required, so making that optional is not really a problem IMHO.

**Comment by javiereguiluz** [comment]
This contribution looks finished. Do Symfony mergers want @Triiistan to create a new pull request against 2.3 .... or can you merge this into older branches? Thanks!

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @Triiistan.

**Pull request closed without merging**
