### PR TITLE
[Debug][ErrorHandler] improved deprecation notices for methods new args and return type

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | ~
| License       | MIT
| Doc PR        | ~

~I don't know if this should be considered a bug fix or a feature.~

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Fine for 4.4 I'd say

**Review by yceruto — APPROVED** [review]

**Comment by HeahDude** [comment]
I've changed the target.

**Comment by HeahDude** [comment]
I've fixed the tests in the `Debug` component too though.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @HeahDude.

**Pull request merged**
