### PR TITLE
[Dotenv] Run test in a separate process to have clean global state

### PR DESCRIPTION
**Pull request by rmikalkenas**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #...
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

A fix to comment: https://github.com/symfony/symfony/pull/46502#issuecomment-1190736778
cc @chalasr

### CODE REVIEW

**Comment by chalasr** [comment]
Thanks for looking at it!
Sadly this patch does not seem to fix the issue, see https://github.com/symfony/symfony/runs/7449393160?check_suite_focus=true#step:8:3691

**Comment by rmikalkenas** [comment]
@chalasr unfortunately I'm not able to reproduce such behavior...

Test is failing on low-deps test case. Locally I run:
- `composer update --no-progress --ansi --prefer-lowest --prefer-stable`
- `./phpunit src/Symfony/Component/Dotenv` ends with all greens

Could you help here? Maybe I'm doing something wrong

**Comment by stof** [comment]
@rmikalkenas installing the lowest deps of the fullstack repo or the lowest deps of the component does not produce the same result.

**Comment by chalasr** [comment]
Here is what is needed to reproduce the low-deps check locally assuming you are at the root directory of the symfony/symfony project:
```
cd src/Symfony/Component/Dotenv/
composer update --prefer-lowest --prefer-stable
../../../../phpunit
```

**Comment by rmikalkenas** [comment]
@stof @chalasr thanks for the guidance, everything should be fine now. The rest failing tests have nothing to do with my changes

**Review by chalasr — APPROVED** [review]
Thanks a lot

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @rmikalkenas.

**Pull request merged**
