### PR TITLE
 	[VarDumper] Ctrl+click toggles-all and fix IE8 support

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #12757, #12612 |
| License | MIT |
| Doc PR | - |

I choose Ctrl+click instead of the initial Alt+click because after testing both on Windows and Ubuntu, Alt+click is bound by the Browser/OS for other things. Ctrl+click is OK.

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by taylankasap** [comment]
Ctrl+click opens context menu in OS X hence not expanding

**Comment by nicolas-grekas** [comment]
Try cmd+click

**Comment by nicolas-grekas** [comment]
If it works, please open a PR for tweaking the doc

**Pull request merged**
