### PR TITLE
Improved Bootstrap form theme for hidden fields

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16925 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by satanasdiabolo** [comment]
The widget `choice_widget_collapsed` also need to be modified to remove the `form-control` class.
Maybe I was unclear about this in my comment on the ticket.

**Comment by javiereguiluz** [comment]
@satanasdiabolo I've removed the `form-control` class from `<select>` elements too, as Bootstrap does. But beware that this change can severely change the look of your application. This is what happened to one of my applications:

#### Before
select_before

#### After
select_after

**Comment by michaelPf85** [comment]
@javiereguiluz You shouldn't remove it from the select. In the issue I gave the list of "input" types that were intended to be used with the "form-control" class but I forgot to cite "select" and "textarea" as they seemed "off topic", I might have been wrong.

```less
// Common form controls
//
// Shared size and type resets for form controls. Apply `.form-control` to any
// of the following form controls:
//
// select
// textarea
// input[type="text"]
// input[type="password"]
// input[type="datetime"]
// input[type="datetime-local"]
// input[type="date"]
// input[type="month"]
// input[type="time"]
// input[type="week"]
// input[type="number"]
// input[type="email"]
// input[type="url"]
// input[type="search"]
// input[type="tel"]
// input[type="color"]

.form-control {
```

**Comment by javiereguiluz** [comment]
@michaelPf85 thanks. I've reverted the last change.

**Comment by javiereguiluz** [comment]
I don't understand the failed tests. They refer to the `vendor/` dir inside the Twig Bridge:

```
/home/travis/build/symfony/symfony/src/Symfony/Bridge/Twig/vendor/symfony/form/Tests/AbstractLayoutTest.php:84
/home/travis/build/symfony/symfony/src/Symfony/Bridge/Twig/vendor/symfony/form/Tests/AbstractLayoutTest.php:106
/home/travis/build/symfony/symfony/src/Symfony/Bridge/Twig/vendor/symfony/form/Tests/AbstractBootstrap3LayoutTest.php:697
```

Can we ignore these fails or should we do something else? Thanks!

**Comment by HeahDude** [comment]
It's weird, tests are failing because of `value` and `class` attributes which contain `&amp;` instead of `&`, but this should not be related to your changes.

**Comment by HeahDude** [comment]
It seems like 02b06e5 is not committed in those failing tests, see [this line](https://travis-ci.org/symfony/symfony/jobs/108056570#L2303) `[@class="form-control"]` is still there.

**Comment by fabpot** [comment]
@javiereguiluz Can you finish this one and fix the tests?

**Comment by HeahDude** [comment]
I've got the same problem in my tests of #17609, could something go wrong with travis ?

**Comment by xabbuh** [comment]
Looks like you need to bump requirements of the Form component in the TwigBridge or make it flexible enough to provide output that satisfied all versions.

**Comment by javiereguiluz** [comment]
@xabbuh thanks for the hint. Do you have any proposal for the new requirements to use? Thanks!

**Comment by xabbuh** [comment]
@javiereguiluz I think changing the version constraint from `~2.7,>=2.7.8` to `~2.7,>=2.7.10` should make the low dependency tests pass.

**Comment by javiereguiluz** [comment]
@xabbuh thank you! I've changed it. Let's see if tests go green again.

**Comment by xabbuh** [comment]
@javiereguiluz sorry, I forgot about 2.8, please try `~2.7.10|~2.8.3`

**Comment by fabpot** [comment]
Tests are still red.

**Comment by xabbuh** [comment]
@fabpot This failure is expected as the subtree split of the Form component doesn't know anything about the updated tests here (only the `deps=high` tests for the TwigBridge are failing).

:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
