### PR TITLE
declare type for arguments of anonymous functions for v2.7

### PR DESCRIPTION
**Pull request by DQNEO**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Declare type for array_map

### CODE REVIEW

**Comment by fabpot** [comment]
@DQNEO Can you check if there are other anonymous functions that could use some type hints as well?

**Comment by DQNEO** [comment]
For this component,  that's all.
For the entire repository. There are more and you can see them here https://github.com/DQNEO/symfony/pull/1

> Can you check if there are other anonymous functions that could use some type hints as well?

Sure, I'll do.
Should I make one PR which contains all the similar modifications or  make separated PRs per component?

**Comment by nicolas-grekas** [comment]
One PR for all components please.

**Comment by nicolas-grekas** [comment]
There is a risk factor here to break BC. This can suddendly forbid duck typing.
For this reason, I'm not sure we should do this.

**Comment by stof** [comment]
In this case, we control the array of parameters (as it comes from `$refl->getParameters()`). So the only risk would be if PHP starts returning something else in this API (in which case, knowing early that the code is broken is good, as it would break anyway)

**Comment by nicolas-grekas** [comment]
> In this case, we control the array of parameters

yes: this must be thought case by case, with a risk of mistake if we're not extra careful, that's what I meant

**Comment by DQNEO** [comment]
I've done for most of  anonymous functions in which I thought we could declare types.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
for merging in master

**Pull request merged**
