### PR TITLE
Add application/json to accepted for change charset.

### PR DESCRIPTION
**Pull request by joshuan**
Add application/json to accepted for change charset. May be any formats need add charset? xml?

### CODE REVIEW

**Comment by Tobion** [comment]
What's the use case? JSON can only be encoded in unicode.

**Comment by joshuan** [comment]
Correctly. But JsonResponse set
```
$this->headers->set('Content-Type', 'application/json');
```
And to browser not send encoding:
```
HTTP/1.1 200 OK
Server: nginx/1.1.19
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
```
Not all browsers and servers are set utf-8 by default.

**Comment by Tobion** [comment]
I wonder why this is done exclusively for `text/*` media types. This is just a random selection. What about `application/xml`, `application/xhtml+xml`, `image/svg+xml` etc...

**Comment by jakzal** [comment]
We've discussed this recently in #13410, and the conclusion was it's not needed since, as @Tobion also mentioned here, json only supports unicode.

**Comment by Tobion** [comment]
But unicode can also be UTF-16. UTF-32. So it's not only UTF-8 as stof said.

**Comment by mvrhov** [comment]
The PHP implementation expects json to be valid utf-8. IMO in practice the utf16 or utf32 are scarce.

**Comment by ksimka** [comment]
> What's the use case?

@Tobion, how about debugging an api with cyrillic responses? Without a proper charset browser will show a kind of mess.

**Comment by fabpot** [comment]
ping @symfony/deciders What do we decide here? Close? Merge? Or add the charset for more types?

**Comment by nicolas-grekas** [comment]
My pov is that we could always add charset=utf-8 when sending application/json, but allowing something else would be strange. PHP does only UTF-8 and no other flavor of unicode.

**Comment by derrabus** [comment]
@nicolas-grekas Symfony should be agnostic about the JSON implementation used. It's not hard to write an alternative JSON encoder that emits UTF-16. Hard-coding the charset to UTF-8 because we have a certain implementation in mind, doesn't feel right to me.

**Comment by derrabus** [comment]
`application/json` should not need a `charset` parameter. UTF-8 is the widely accepted default and if I used a UTF-16 or UTF-32 encoding, I'd probably indicate this with a BOM. But I would agree that an application should be able to add this parameter to the header since there's nothing wrong about doing that. If I'm not mistaken (I haven't tested it), this is currently possible by setting the header directly with the parameter.

```php
$response->headers->set('Content-Type`, 'application/json; charset=UTF-8');
```

My problem with this PR is that it switches the default behavior: If the content type is inferred from the request (`_format` attribute) or set by Symfony's `JsonResponse` class, the charset parameter will always be added. The external behavior of my API will change with this PR.

Client code or tests that rely on the `Content-Type` header to be `application/json` and that choke on a new `charset` parameter, might not be written well. By as an API provider, I cannot always check every API consumer when introducing a change.

Furthermore, when merging this PR, there won't be a way back to the old behavior. Even if I set the `Content-Type` header myself to `application/json` without a `charset` parameter, that piece of code will always add that parameter, if it's not present yet.

:-1:

**Comment by weaverryan** [comment]
The behavior change (from a BC-break perspective) seems like a problem - @derrabus pointed out a use-case of someone currently string-checking against the Content-Type header, which would break if this changed automatically. For that reason alone, I have to vote :-1:. There is some oddness (with `text/` only getting the automatic behavior), and to change that, we'd need to think of some way that has an upgrade path.

**Pull request closed without merging**
