### PR TITLE
VarDumper/Caster/Redis Refactor

### PR DESCRIPTION
**Pull request by 243083df**
Delete $connected variable, case it boolean anyway.

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Sorry but we don't do this kind of refactor: the code is working as expected, and changing the code style means creating future merge conflicts (since we will merge 3.4 into 4.0 into master for the next 3 years.)

**Comment by 243083df** [comment]
@nicolas-grekas Okay, so i removed array refactor, and keep unnecessary variable removement

**Comment by nicolas-grekas** [comment]
I don't think this provide much value: in fact, if the method were to return something else than a `bool`, the current code will make it visible - while hardcoding false/true just hides it. The new code makes more assumptions, thus is not better IMHO.

**Comment by fabpot** [comment]
I agree with @nicolas-grekas here. Let's close it. Thanks for your pull request.

**Comment by 243083df** [comment]
@nicolas-grekas @fabpot 
Method return only true or false
Method: https://github.com/phpredis/phpredis/blob/develop/redis.c#L3136
True: https://github.com/phpredis/phpredis/blob/develop/redis.c#L3140
False: https://github.com/phpredis/phpredis/blob/develop/redis.c#L3142

**Pull request closed without merging**
