### PR TITLE
[Console] Use UTF-8 triangle for question prompt

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes/no    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Now inspired by #26698, this updates the prompt icon :) Havent looked at tests/windows yet... but i find it very pretty :}

Before

image

After

image

Move forward?

ref https://www.utf8icons.com/character/9205/black-medium-right-pointing-triangle

### CODE REVIEW

**Review by ostrolucky — CHANGES_REQUESTED** [review]
Tested, doesn't work on windows. Use these https://github.com/sindresorhus/figures

**Comment by Simperfit** [comment]
@ro0NL did you test it on mac ? doesn't seem to work on mine neither

**Comment by rugabarbo** [comment]
It displays as a square (Mac OS X).

**Comment by ro0NL** [comment]
Sorry.. nix-developer here :) Anyway i just got aware of #11326 also.. which seems competing and is a different approach overall.

In general something like `Console\Figure::render('⏵', '>');` would be nice.

Status: needs work

**Comment by javiereguiluz** [comment]
@ro0NL this one should work on macOS: https://www.utf8icons.com/character/9656/black-right-pointing-small-triangle

**Comment by ro0NL** [comment]
Ok. lets see, if we can ship this little enhancement before #11326 that's nice i guess.

**Comment by ostrolucky** [comment]
Works on windows as well

selection_002

**Comment by ro0NL** [comment]
Last triangle on my side:
image

Proposed chevron on my side:
image

Hence i those a smaller triangle ;-)  but im willing to settle, no problem.

**Comment by ostrolucky** [comment]
I like ❯ most, even on your screenshot. But it does not work on windows. We could really use Figure helper

**Comment by nicolas-grekas** [comment]
lets keep it as is, `>` is really fine, and prevents from adding code for dealing with non-UTF-8 consoles.

**Comment by fabpot** [comment]
I think @nicolas-grekas is right. After all, that's not like it's much better and could introduce some bugs on some platforms. For that reason, I'm going to revert #26698, so that we get more time to evaluate the impacts and have only one PR that does all the changes.

**Comment by ro0NL** [comment]
Fair. I see the hassle it brings.. 

What amazes me is this concept of "partial UTF" support accros platforms, totally defeating UTF :D

**Pull request closed without merging**
