### PR TITLE
Update dependencies in the main component

### PR DESCRIPTION
**Pull request by DavidPrevot**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | 

The doctrine/collections and psr/simple-cache dependencies have already been demoted to require-dev in the relevant components.

BTW, I wonder if symfony/mailer (and symfony/*-mailer bridges) should be provided in the main composer.json too.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks, good catch.
For mailer I think it would make sense to list it.
For the bridges I think we prefer keeping them separate.

**Comment by nicolas-grekas** [comment]
Thinking twice, bridges should be in the replace section too, so that flex can apply its extra.symfony.require constraints on them!

**Comment by DavidPrevot** [comment]
Updated according to @nicolas-grekas advice, thanks.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @DavidPrevot.

**Pull request merged**
