### PR TITLE
[SecurityBundle] Add missing deprecation notice for form_login.intention

### PR DESCRIPTION
**Pull request by ro0NL**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | #19664, #19661, #19652 |
| License | MIT |
| Doc PR | - |

By the grace of @chalasr 

ping @fabpot

### CODE REVIEW

**Comment by chalasr** [comment]
Manually checked out and it fixed it 👍

**Comment by ro0NL** [comment]
I dont know wtf is going on.. (github? fabpot?).. but #19662 was removed.. now it's back. Anyway.. for reference :-)

**Comment by chalasr** [comment]
I thought the owner has been banned and the related issues/PRs too...

**Comment by ro0NL** [comment]
Me too, but in case of no censor; :+1:

**Comment by nicolas-grekas** [comment]
:+1: for 2.8 since this is not really a new deprecation but rather a bc-break fix.
Code is exactly the same on MainConfiguration, we just forgot to add it here also by the time.

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request closed without merging**
