### PR TITLE
[Finder] Partially revert #17134 to fix a regression

### PR DESCRIPTION
**Pull request by jakzal**
| Q | A |
| --- | --- |
| Branch | 2.3 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18013 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by jakzal** [comment]
I will not include a test case unless anyone thinks it's absolutely necessary or has a better idea than the test case below. It is rather fragile. It would also double test execution time for the finder component on travis.

```php
namespace Symfony\Component\Finder\Tests\Iterator;

use Symfony\Component\Finder\Iterator\DepthRangeFilterIterator;
use Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator;
class DepthRangeFilterIteratorTest extends RealIteratorTestCase
{
    // ...

    public function testFtp()
    {
        $inner = new \RecursiveIteratorIterator(new RecursiveDirectoryIterator('ftp://speedtest.tele2.net/', \RecursiveDirectoryIterator::SKIP_DOTS), \RecursiveIteratorIterator::SELF_FIRST);

        $iterator = new DepthRangeFilterIterator($inner, 0, 0);

        $files = iterator_to_array($iterator);

        $this->assertArrayHasKey('ftp://speedtest.tele2.net/1000GB.zip', $files);
        $this->assertArrayHasKey('ftp://speedtest.tele2.net/100GB.zip', $files);
        $this->assertArrayHasKey('ftp://speedtest.tele2.net/10GB.zip', $files);
        $this->assertArrayHasKey('ftp://speedtest.tele2.net/1GB.zip', $files);
    }
}
```

**Comment by fabpot** [comment]
@jakzal I think a small comment above the code to explain the reason why we have such a code would probably help any future regressions and should be enough.

**Comment by jakzal** [comment]
Comment added.

**Comment by fabpot** [comment]
Thank you @jakzal.

**Pull request merged**
