### PR TITLE
[Serializer] Fix DataUriNormalizer's regex

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #20225 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by dunglas** [comment]
Travis error not related.

**Comment by dunglas** [comment]
I've updated the regex to be as close as possible of the ABNF syntax: https://tools.ietf.org/html/rfc6838#section-4.2

**Comment by dunglas** [comment]
ping @symfony/deciders

**Comment by xabbuh** [comment]
👍 LGTM

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request closed without merging**
