### PR TITLE
[Yaml] quote all dumped unicode spaces

### LINKED ISSUE #39767: Yaml dumper unquotes string when using an ideographic space
**Symfony version(s) affected**: 5.2.1

**Description**  

When the Yaml dumper encounters an [ideographic space](https://www.fileformat.info/info/unicode/char/3000/index.htm), the whole string becomes unquoted.

**How to reproduce**  

Here's a unit test to go in `src/Symfony/Component/Yaml/Tests/DumperTest.php`.

```php
public function testDumpIdeographicSpaces()
{
    $this->assertSame("{ alone: '　', within_string: 'a　b', regular_space: 'a b' }", $this->dumper->dump([
        'alone' => '　',
        'within_string' => 'a　b',
        'regular_space' => 'a b',
    ]));
}
```

```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'{ alone: '　', within_string: 'a　b', regular_space: 'a b' }'
+'{ alone: 　, within_string: a　b, regular_space: 'a b' }'
```

Thanks!

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39767
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
Technically, this change is not needed, but it hopefully makes the dumped YAML a bit more readable and avoids confusion.

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by jasonvarga** [comment]
Thank you very much for fixing the issue, but I do want to comment out how you've said "this change is not needed".

When we go to parse that dumped unquoted yaml string, it would break.

For instance, if the dumped ideographic string was there without quotes like this:

```yaml
foo: 　
```

Then we'd see an exception like this:

```
Unable to parse at line 20 (near "foo: 　").
```

It appears to only throw that exception if the only thing there is the ideological space (and optionally other whitespace). If there's a regular character in there, it works fine. (Here there's `bar` then the unicode space)

```yaml
foo: bar　
```

I don't know if this warrants a bug report, but I thought it was at least worth mentioning. Thanks again for the quick fix!

**Comment by xabbuh** [comment]
Thanks for the feedback. This indeed looks like a bug in the parser to me. I am going to look into it.

**Comment by xabbuh** [comment]
@jasonvarga Can you confirm that #39787 fixes this as well?

**Comment by jasonvarga** [comment]
Seems good!

**Pull request merged**
