### PR TITLE
[PhpUnit Bridge] Fixes a non-initialized variable

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | to be updated
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT

If you are ok with this, I will rebase on the best branch.

### CODE REVIEW

**Comment by lyrixx** [comment]
What does it fix ? Because now, you will execute many time `file_exists` with no real value.
Did I miss something ?

**Review by lyrixx — APPROVED** [review]
OK, now it's better :+1:

**Comment by romain-pierre** [comment]
Your too quick for me lol, just the time to see the error by myself and re-push ;-)

**Comment by nicolas-grekas** [comment]
Thank you @romain-pierre.

**Pull request merged**
