### PR TITLE
Leverage first-class callable syntax on array methods using string syntax callback

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | -
| Tickets       | -
| License       | MIT
| Doc PR        | -

Follow-up to https://github.com/symfony/symfony/pull/47672

### CODE REVIEW

**Comment by stof** [comment]
Is this an automated change ? If yes, is it performed by php-cs-fixer or another tool ? If it is performed by php-cs-fixer, we should configure it so that fabbot enforces new code to respect that as well.

**Comment by nicolas-grekas** [comment]
Isn't this a bit slower? It requires creating a closure while it didn't before.

**Comment by fancyweb** [comment]
I automated the change with a custom Rector rule.

It's probably a little bit slower but wasn't it already the case in https://github.com/symfony/symfony/pull/47672?

**Comment by nicolas-grekas** [comment]
#47672 is only about tests and non critical code path :shrug: 
I don't think we should switch if the perf degrades, because then, this is not just about a syntax change, but one with real technical implications.

**Comment by fancyweb** [comment]
Closing because I can clearly see a small perf diff on my computer so let's not change anything.

**Pull request closed without merging**
