### PR TITLE
[HttpFoundation] Set meta refresh time to 0 in RedirectResponse content

### PR DESCRIPTION
**Pull request by jnvsor**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23524
| License       | MIT

Set meta refresh time to 0 in RedirectResponse content

### CODE REVIEW

**Comment by ro0NL** [comment]
So is it a bugfix (2.7) or a new feature (3.4)? 2.7 seems fine or do you have legacy projects running onn 3.4? ;-)

**Comment by fabpot** [comment]
I don't think this is worth it. What does it solve?

**Comment by jnvsor** [comment]
It removes the second-long white page with redirect notice if headers have already been sent. I'm not sure whether that's a bug or a feature, but it's an improvement either way I think.

**Comment by javiereguiluz** [comment]
In theory, using `1` is a bug if we want to redirect immediately. MDN for example [mentions this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections):

> The content attribute starts with a number indicating how many seconds the browser should wait before redirecting to the given URL. Always set it to 0, for better accessibility.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jnvsor.

**Pull request closed without merging**
