### PR TITLE
Don't throw fatal errors for unused env vars

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23520
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:-1:
that's too simplistic and ignores the fact that this will also shallow unsupported uses of env vars, which would hurt DX is a much worse way.

**Comment by javiereguiluz** [comment]
I don't understand this part -> *"this will also shallow unsupported uses of env vars"*. Can you please elaborate? You can take for example the Symfony Demo app as an example. Thanks!

**Comment by nicolas-grekas** [comment]
You cannot use `%env(SOME_DEFINED_ENV)%` in all places in the your configuration.
If you do, you get this friendly exception that tells you no, not here.

**Comment by javiereguiluz** [comment]
It looks like we're talking about different things:

1) I suffer this error when I don't use in a config file an env var defined in my `.env`
2) You say that this error checks if you use an env var in the wrong place.

I agree with you about 2) ... but, what would be the solution to remove 1) while maintaining 2)?

**Comment by nicolas-grekas** [comment]
You may think these are different things, but it's the exact same thing in the code right now.

> what would be the solution to remove 1) while maintaining 2)

that's the hard question nobody can answer yet

**Pull request closed without merging**
