### PR TITLE
Update LICENSE year... forever

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes| Fixed tickets | #... 
| License       | MIT
| Doc PR        | n/a

By using the same trick than Facebook: https://github.com/facebook/react/blob/master/LICENSE

### CODE REVIEW

**Comment by wouterj** [comment]
I don't even think adding an end is needed. IIRC, if only one year is mentioned, `-present` is implicit (as it tells you when the copyright started). The end year is only needed if there is an end to the copyright.

**Review by javiereguiluz — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @dunglas.

**Comment by fabpot** [comment]
That PR looks wrong to me. Reverting it now.

**Comment by nicolas-grekas** [comment]
Really? Would be so great to end this yearly game... :)

**Comment by dunglas** [comment]
@fabpot for my curiosity, can you give more insight?

**Comment by dunglas** [comment]
A quick search on GitHub across popular MIT projects: https://github.com/search?utf8=%E2%9C%93&q=stars%3A%3E10000+license%3Amit&type=Repositories

* Bootstrap: -year (outdated)

* Airbnb's Javascript: only includes the first release year
* Angular 1: -year (outdated)

**Pull request merged**
