### PR TITLE
[FrameworkBundle] Container parameters in Route#condition

### PR DESCRIPTION
**Pull request by nikita2206**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | no |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Adds ability to use parameters in route conditions like you can use them in container definitions:

``` php
contact:
    path:     /contact
    defaults: { _controller: AcmeDemoBundle:Main:contact }
    condition: "request.headers.get('User-Agent') matches '%allowed_user_agents%'"
```

As you could see replacement of the placeholder happens before ExpressionLanguage will tokenize and compile the expression so it looks kinda ad-hoc and primitive. This means a BC break for us, because some of conditions out there that had percentage symbol might be invalid now, f.e.: `10%var_name%2`\- without the patch this will be currently compiled to `10 % $var_name % 2`, with the patch it will try to replace `%var_name%` with a parameter. The same goes for percentage symbols inside string literals. 

This PR is a different implementation of #12869 which is I think is too overcomplicated for this feature.

### CODE REVIEW

**Comment by fabpot** [comment]
@nikita2206 Ass FrameworkBundle now relies on the `setCondition` to exists in the Router, you must upgrade the `symfony/routing` dependency in the `composer.json` file of the framework bundle (to 2.5 instead of 2.2).

**Comment by nikita2206** [comment]
@fabpot done (not sure why 2.5 though, PR is aimed at 2.7)

**Comment by fabpot** [comment]
@nikita2206 That's because we test the compatibility of each component/bundle with different other versions (low and high).

**Comment by fabpot** [comment]
Not sure why Travis did not trigger.

**Comment by fabpot** [comment]
Thank you @nikita2206.

**Pull request closed without merging**
