### PR TITLE
Add support for HTTP status code 418 back

### PR DESCRIPTION
**Pull request by dawehner**
See https://gist.github.com/anonymous/a863d7b493c4b09733ec what this results into

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | 16584 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by Tobion** [comment]
Ref. #15796

**Comment by dawehner** [comment]
So yeah #15796 was kind of a BC break indeed, I mean it broke at least some tests

**Comment by fabpot** [comment]
Thank you @dawehner.

**Comment by JHGitty** [comment]
@dawehner @fabpot 
What's about HTTP code 306? It was removed too.
https://github.com/dupuchba/symfony/commit/322656988acb9eb8e06e4fed7339789a5e2abc20#diff-a8f7745712c744a53020ed9c09bd68bcL84

And is the change of the text of some HTTP codes not a BC break?

**Comment by dawehner** [comment]
Sure, why not ...

```

And is the change of the text of some HTTP codes not a BC break?
```
Well, the HTTP standard says that you should not take care about it. IMHO
though having a broken interaction with apache is way more important than
strict BC here.

**Pull request merged**
