### PR TITLE
[Messenger] Messenger: avoid DELETE statement flood when using Doctrine+MySQL backend

### PR DESCRIPTION
**Pull request by giosh94mhz**
| Q             | A
| ------------- | ---
| Branch       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### The issue

I found an issue with the  Doctrine bridge of Messenger when using MySQL. In version 4.4 (commit 12271a44cfe0b4ea7fdcbfc20a1ebf588aa54410 ) the MySQL removal of acknowledged/rejected was implemented by updating the queued message ID with a fake date (i.e. 9999-12-31) and then removing the messages later.

The problem is that this DELETE statement is done every time a connection is checked for job, which usually happens every seconds (in my case, even multiple time per seconds since I use multiple consumers and queues).

Since I use MySQL binary logging and replica, a quick count of recent logged queries highlighted the issue (it's a quick `cat binlog | sort | uniq -c | sort -n`):

```
     30 UPDATE my_job SET delivered_at = 'NNNN-NN-NN NN:NN:NN' WHERE id = 'NNNNNNN'
   3621 DELETE FROM my_job WHERE delivered_at = 'NNNN-NN-NN NN:NN:NN'
```

As you can see, for only 30 messages handles, there were 3600 (1 hour) DELETE statements.

### The fix

I've added a private variable to track if an update has been made, as so if a DELETE  is required. This effectively stops the flood.

I kept the default to `false` to reduce this value to minimum, and after verifying that all invalid records are not queried thanks to `createAvailableMessagesQueryBuilder`.

### Unit tests

There's no regression on actual tests, but I haven't found a specific test to update for this. I'm not sure how this could be implemented, so if needed I waiting for hints!

### CODE REVIEW

**Comment by fabpot** [comment]
As this is a new feature, this should target 7.1.

**Comment by giosh94mhz** [comment]
Thank you for your reply, @fabpot . I don't understand why you see this as a feature, maybe my explanation is a bit confusing.

I try to explain it with an example. Suppose you have a consumer running and today you only sent a single message to it. The current implementation, will send 86400 DELETE statement to MySQL, while only 1 DELETE statement is expected after the job is handled.

My change only ignores the 85399 useless DELETE, while keeping the only rightful DELETE that is right after the condition  `if ($this->doMysqlCleanup && ...)`.

This is important especially in cluster replication, where the fix is not only a connection optimization. With replication, all statements are also written to the binary log and auditing log (wasting I/O) and transferred on all replica nodes (wasting network). Galera cluster likely have similar issues (bottleneck on the primary node for DELETE)

In my use case I have 3 consumer and 2 backup nodes, that's account for 320k useless DELETEs while 100-200 per day are expected.

**Comment by nicolas-grekas** [comment]
The number of DELETE is big, but it's not higher than the number of SELECT, so the DB can handle the load without much issues, isn't it? If confirmed, I'd also consider this as an optimization, not a bugfix.

**Comment by giosh94mhz** [comment]
> The number of DELETE is big, but it's not higher than the number of SELECT, so the DB can handle the load without much issues, isn't it?

The database is handling the DELETEs without much issues, and yes for many LAMP-like server out there there won't be much difference. The fact that no one noticed this before, it's a clear hint for this fact.

>  If confirmed, I'd also consider this as an optimization, not a bugfix.

I don't want to appear selfish, but I'm not totally comfortable in calling this only a performance issue. A select is just READ LOCK + data fetch, while a DELETE it's at the very least a WRITE LOCK + data fetch, but for anyone using any form of mysql backup/cluster, also a Audit/Log write and multiple data transfer. The patch is not "optimizing" some query, but it's trimming away a huge amount of unjustified query, that was in the top 10 query of all servers.

If you don't feel safe in applying this to branch 5.4 I do understand, just wanted to explain this issue well.

PS: thank you for all your hard work with Symfony!

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @giosh94mhz.

**Comment by Double-Ramzi** [comment]
Hello,
Given that the get() method should only be invoked once (when the --limit=1 option is used), and considering that the $doMysqlCleanup variable is initialized to false, messages are not being deleted.

Would it be possible to initialize this variable to true to ensure deletion occurs at startup in this specific case?

Best regards,

**Comment by giosh94mhz** [comment]
> Hello, Given that the get() method should only be invoked once (when the --limit=1 option is used), and considering that the $doMysqlCleanup variable is initialized to false, messages are not being deleted.

@Double-Ramzi The default value is `false` because the Transport is used for both sending and receiving the messages. Sending may happen for each page visited while the receiving only happens con the dequeues; therefore,  if you change to `true` you get a lot of useless DELETE, not as much as the poller task but a lot more nonetheless (in my example above you get 60 instead of 30, but definitely not 3621).

Maybe adding something on `__destruct` or `reset` is more appropriate?

**Comment by gilles-g** [comment]
Hi @giosh94mhz,

I just upgraded my project from Symfony 6.4 to 7.2, and I’m now facing the same issue as @Double-Ramzi.

I have some workers configured with limit=1, and since the update, my messages are never deleted.

This seems like a regression—what do you think, @fabpot?

**Comment by xabbuh** [comment]
Please open a new issue with as many details as possible. Comments on merged PRs are likely to get lost.

**Pull request merged**
