### PR TITLE
[Cache] Fixing typo...

### PR DESCRIPTION
**Pull request by ThomasLandauer**
...for consistency with other components :-)

### CODE REVIEW

**Comment by jderusse** [comment]
Could you please merge your 2 identical PR together?

You also should respect the original PR template and edit the description.

**Comment by OskarStark** [comment]
I like consistency but personally I would prefer `component` over `Component` 🤔

**Comment by ThomasLandauer** [comment]
@OskarStark As you say. Will you merge it if I change the others to lowercase?

> symfony/asset                               v5.2.1             Symfony Asset Component
symfony/browser-kit                         v4.4.18            Symfony BrowserKit Component
symfony/config                              v4.4.18            Symfony Config Component
symfony/console                             v4.4.18            Symfony Console Component
symfony/css-selector                        v5.1.10            Symfony CssSelector Component
symfony/debug                               v4.4.18            Symfony Debug Component
symfony/dependency-injection                v4.4.18            Symfony DependencyInjection Component
symfony/dom-crawler                         v5.1.10            Symfony DomCrawler Component
symfony/error-handler                       v4.4.18            Symfony ErrorHandler Component
symfony/event-dispatcher                    v4.4.18            Symfony EventDispatcher Component
symfony/expression-language                 v5.1.10            Symfony ExpressionLanguage Component
symfony/filesystem                          v5.1.10            Symfony Filesystem Component
symfony/finder                              v5.1.10            Symfony Finder Component
symfony/form                                v4.4.18            Symfony Form Component
symfony/http-foundation                     v5.2.1             Symfony HttpFoundation Component
symfony/http-kernel                         v4.4.18            Symfony HttpKernel Component
symfony/inflector                           v4.4.18            Symfony Inflector Component
symfony/mailer                              v5.1.10            Symfony Mailer Component
symfony/options-resolver                    v5.2.1             Symfony OptionsResolver Component
symfony/process                             v5.1.10            Symfony Process Component
symfony/routing                             v4.4.18            Symfony Routing Component
symfony/security-core                       v4.4.18            Symfony Security Component - Core Library
symfony/security-csrf                       v4.4.18            Symfony Security Component - CSRF Library
symfony/security-guard                      v4.4.18            Symfony Security Component - Guard
symfony/security-http                       v4.4.18            Symfony Security Component - HTTP Integration
symfony/stopwatch                           v5.2.1             Symfony Stopwatch Component
symfony/translation                         v4.4.18            Symfony Translation Component
symfony/validator                           v5.2.1             Symfony Validator Component
symfony/yaml                                v5.2.1             Symfony Yaml Component

vs.

> symfony/http-client                         v5.1.10            Symfony HttpClient component
symfony/string                              v5.2.1             Symfony String component
symfony/uid                                 v5.2.1             Symfony Uid component

**Comment by OskarStark** [comment]
I am not the merger 😊 but yes, @jderusse WDYT?

**Comment by fabpot** [comment]
I would use Component

**Comment by ThomasLandauer** [comment]
Closing in favor of https://github.com/symfony/symfony/pull/39768

**Pull request closed without merging**
