### PR TITLE
[PropertyInfo] Fix some namespaces in tests

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1: 

Status: reviewed

**Comment by xabbuh** [comment]
:+1:

**Comment by dunglas** [comment]
ping @symfony/deciders

**Comment by Tobion** [comment]
Thank you @dunglas.

**Pull request merged**
