### PR TITLE
[UID] Rename NullUuid to NilUuid

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

As per https://tools.ietf.org/html/rfc4122#section-4.1.7

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👎  I disagree with this. We use PHP ... so `null` is natural and `nil` is alien to us.

The fact that the RFC uses that terminology is not enough reason for me. The RFC also uses "node" instead of "mac address" ... and we don't comply with the RFC and keep calling it "mac address".

**Comment by ro0NL** [comment]
> The fact that the RFC uses that terminology is not enough reason for me.

for me it was actually + the fact you get a slightly more relevant search result

Agree it's minor.. and if both are considerable equal im fine with "wont fix"

**Comment by nicolas-grekas** [comment]
This is worth considering as this is what the RFC uses, thanks for raising the point. I'm also thinking our community is not used to "nil" so it could create confusion where "null" wouldn't. Dunno if others agree?

**Comment by ro0NL** [comment]
See also https://english.stackexchange.com/questions/61363/are-nil-and-null-interchangeable, esp.:

> Nil means zero or nought
> Null means nothing or empty

**Comment by wouterj** [comment]
I agree with @ro0NL here. The `null` we as PHP developers know is not a zero or an empty string, it's the non-existence of a value. So the null in `NullUuid` does not relate to the null we know in PHP. 

In Symfony's Notifier component, such a class is called `NoRecipient` (and not `NullRecipient`). 

I think it makes sense to follow the RFC here 👍 

_(Yet, if I'm completely honest, we use [the `Null` prefix in many other classes](https://user-images.githubusercontent.com/749025/76692020-06c24300-6651-11ea-9d2a-7f764d0f437b.png))_

**Review by nicolas-grekas — APPROVED** [review]
> Nil means zero or nought
> Null means nothing or empty

that's quite convincing I agree.
Good to me.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request merged**
