### PR TITLE
Updated copyright year

### PR DESCRIPTION
**Pull request by jeroenvisser101**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Happy new year to you all! I updated the copyright years in all license
files.

PS. #17239 (and the many others) only cover the main LICENSE file, but this one is more thorough. I might have missed some, but I couldn't find any other occurrences of '2015'

### CODE REVIEW

**Comment by dosten** [comment]
:+1: and happy new year! :)

**Comment by 1ed** [comment]
I think this should be created for 2.3 first and then any other maintained branches that have new LICENSE files which are not in the previous maintained branches to ease merging branches.

**Comment by jeroenvisser101** [comment]
Makes sense, should I create a new PR and base it on `2.3` branch?

**Comment by 1ed** [comment]
Yes please, and for 2.7, 2.8, 3.0 and master if required. You can wait for merging branches here or do it yourself and cherry-pick the fix commit for the different branches to create PRs only containing the change required for that branch only (https://github.com/symfony/symfony/pull/15917#issuecomment-143433731). I'm not sure how to handle 2.6 though, it can have new security releases until end of January.

**Comment by Ener-Getick** [comment]
:+1:
@1ed ``2.6`` is not maintained anymore for bug fixes so this shouldn't be included in it.

**Comment by Tobion** [comment]
We need a PR against 2.3. I'll do the rest when merging.

**Comment by jeroenvisser101** [comment]
Okay, will do!

**Comment by dosten** [comment]
see #17244

**Comment by jeroenvisser101** [comment]
@dosten nice, thanks!

**Pull request closed without merging**
