### PR TITLE
[Messenger] Move MiddlewareTestCase in Test ns

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes (AppVeyor failure unrelated)    
| Fixed tickets | N/A   
| License       | MIT
| Doc PR        | N/A

Just a quick suggestion after #28943 being merged. Wouldn't it make sense to move this in `Test` namespace to be used by anyone wanting to unit test their middleware?

### CODE REVIEW

**Review by ro0NL — APPROVED** [review]

**Review by sroze — APPROVED** [review]
Yep, sounds reasonable to me.

**Review by chalasr — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by ro0NL** [comment]
should we actually use it? #28999

**Comment by ogizanagi** [comment]
@ro0NL : Done and added `MiddlewareTestCase::getThrowingStackMock()`. 
Thanks for pointing this out

**Comment by fabpot** [comment]
Thank you @ogizanagi.

**Pull request merged**
