### PR TITLE
[Cache] Cached files rely on umask

### PR DESCRIPTION
**Pull request by 4rthem**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21929
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Review by javiereguiluz — APPROVED** [review]
👍 

@4rthem thanks for reporting this issue in the first place and then for providing a solution for it!

**Review by xabbuh — APPROVED** [review]
:+1:

**Review by chalasr — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @4rthem.

**Pull request merged**
