### PR TITLE
[Cache] fix compatibility with Redis Relay 0.8.1

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
see https://github.com/cachewerk/relay/compare/v0.8.0...v0.8.1

**Comment by nicolas-grekas** [comment]
So the 0.8.0 builds contain the code from 0.7.0?
Doesn't this mean we should compare against 0.8.0 instead when doing the version-compare?

**Comment by nicolas-grekas** [comment]
(I'm confused by the diff which doesn't contain anything about the new json methods).

**Comment by xabbuh** [comment]
> (I'm confused by the diff which doesn't contain anything about the new json methods).

That's covered by the [release notes](https://github.com/cachewerk/relay/releases/tag/v0.8.1) I guess:

> Added experimental support `JSON` commands

**Comment by xabbuh** [comment]
> So the 0.8.0 builds contain the code from 0.7.0?

That's how I read the changes.

> Doesn't this mean we should compare against 0.8.0 instead when doing the version-compare?

I don't think so as that means we would generate incompatible proxy code with 0.8.0.

**Pull request merged**
