### PR TITLE
[Console] fix resetting the COLUMN environment variable

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
This should make tests pass for the `4.2` branch. I have no idea why tests on `3.4` don't fail though.

**Comment by xabbuh** [comment]
ping @greg0ire

**Review by michaelcullum — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by greg0ire** [comment]
Oh right, I forgot to use `=== false` here… thanks for fixing it. `3.4` test didn't fail because there are fewer of them and they were fairly independent already. There might be issues when merging this into master (`COLUMNS` not initialized before running the test), and IIRC adding `putenv(COLUMNS=90)` in the failing test will fix things.

**Pull request merged**
