### PR TITLE
[Form] Suggest symfony/intl instead of requiring it

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24966 
| License       | MIT

### CODE REVIEW

**Comment by stof** [comment]
it is not only for polyfilling. This component provides extra features too, which are necessary for some form types (LanguageType, LocaleType, CountryType and CurrencyType)

**Comment by MatTheCat** [comment]
These aren't extra features as intl provides ways to get these lists.

**Comment by stof** [comment]
@MatTheCat no it does not. PHP provides the class to parse the ICU resource bundle, but it does not ship with the raw ICU data.

**Comment by MatTheCat** [comment]
Isn't icu a dependency of the intl extension? Seems weird to me we could have the classes without any data.

**Comment by stof** [comment]
@MatTheCat the icu C lib is indeed a dependency of the intl extension. But the intl extension does not expose the whole data to PHP userland.

**Comment by MatTheCat** [comment]
I'm pretty sure we can get all data the form types need from intl:

```php
<?php

$languages = array_reduce(\ResourceBundle::getLocales(''), function (array $languages, string $locale) {
    $language = \Locale::getPrimaryLanguage($locale);

    if (!isset($languages[$language])) {
        $languages[$language] = \Locale::getDisplayLanguage($locale);
    }

    return $languages;
}, []);

$locales = array_reduce(\ResourceBundle::getLocales(''), function (array $locales, string $locale) {
    $locales[$locale] = \Locale::getDisplayName($locale);

    return $locales;
}, []);

$countries = array_reduce(\ResourceBundle::getLocales(''), function (array $countries, string $locale) {
    $country = \Locale::getRegion($locale);

    if (!isset($countries[$country])) {
        $countries[$country] = \Locale::getDisplayRegion($locale);
    }

    return $countries;
}, []);

$currencies = array_reduce(\ResourceBundle::getLocales(''), function (array $codes, string $locale) {
    $code = \NumberFormatter::create($locale, \NumberFormatter::CURRENCY)->getTextAttribute(\NumberFormatter::CURRENCY_CODE);

    if (!isset($codes[$code])) {
        $codes[$code] = $code;
}

    return $codes;
}, []);
```

Maybe there are better ways but it doesn't seem like symfony/intl is mandatory if intl extension is present.

**Comment by mvrhov** [comment]
The problem with using data from intl  s that the intl that's shipped by os is usually old.
e.g When you use the LTS version of OS and you do upgrade of OS when there is no more updates, that means that the data in ICU is 5years old and mostly useless.

**Comment by MatTheCat** [comment]
Oh okay. Couldn't Symfony provide ICU data usable by both symfony/intl and the intl extension?

**Pull request closed without merging**
