### PR TITLE
[Finder] add missing return type declaration

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

should make builds green again

### CODE REVIEW

**Comment by xabbuh** [comment]
spotted by the `DebugClassLoader` as Nicolas enabled it again in the pipeline 🎉

**Comment by derrabus** [comment]
This class is neither flagged final nor internal, so this change is technically a BC break. 🤔

**Comment by nicolas-grekas** [comment]
It's been added in https://github.com/symfony/symfony/pull/40040

**Comment by xabbuh** [comment]
see also #40163

**Pull request merged**
