### PR TITLE
[PropertyAccess] unify and fix doc

### PR DESCRIPTION
**Pull request by Tobion**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by fabpot** [comment]
The exception message changes should be done on the 2.7 branch (this is not a bug fix).

**Comment by Tobion** [comment]
Why that? This will make merging and mainting branches even harder.

**Comment by fabpot** [comment]
Because we don't change things that do not fix bugs in older branches. What if someone relies on the message? It is acceptable to break that in minor versions but not in a patch version.

**Comment by Tobion** [comment]
The exception message has never been part of our bc promise. And we changed messages alot in the past. Just a few examples from the last days: #13431 (by yourself) and #13509

**Comment by Tobion** [comment]
And seriously, whoever relies on specific exception messages from symfony has code smell.

**Comment by fabpot** [comment]
Fair enough... even if I think it's not a good thing to do non-bug-fixes in "old" branches.

**Comment by fabpot** [comment]
Thank you @Tobion.

**Pull request merged**
