### PR TITLE
#32853 Check if $this->parameters is array.

### PR DESCRIPTION
**Pull request by ABGEO**
| Q             | A
| ------------- | ---
| Branch?     | 4.3
| Bug fix?      | yes
| New feature?  | no
| Tests pass?   | yes 
| Fixed tickets | #32853
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Would it work if we initializer the property to the empty array when it is declared instead?
The fix should target branch 3.4 btw, thanks.

**Comment by ABGEO07** [comment]
> Would it work if we initializer the property to the empty array when it is declared instead?
> The fix should target branch 3.4 btw, thanks.

Yes, it will. If the array is empty, it will return false.

**Comment by nicolas-grekas** [comment]
Great, can you update the patch then please?

**Comment by ABGEO07** [comment]
What do you mean by updating the patch? :)

**Comment by nicolas-grekas** [comment]
I mean: change the patch to initialize the property, and revert the current changes.

**Comment by ABGEO07** [comment]
@nicolas-grekas Done and it works.

**Comment by nicolas-grekas** [comment]
Thank you @ABGEO07.

**Pull request merged**
