### PR TITLE
Additional addons for the ghost

### PR DESCRIPTION
**Pull request by przemyslaw-bogusz**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

Following #30236 I've prepared two additional addons for the ghost.

The first one will display a plus on February 29, to indicate it's a leap year.
ghost-plus

The second one will display a gift on October 18, to indicate it's Symfony's birthday.
ghost-gift

I would just like to point out that the addons are purely for fun, to amuse every hardcoding Symfony developer and offer a chance to smile on these few selected occasions.

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Review by javiereguiluz — CHANGES_REQUESTED** [review]
I'd like to ask to change the `GHOST_PLUS` symbol.

Do you know the [Red Cross organization](https://en.wikipedia.org/wiki/International_Red_Cross_and_Red_Crescent_Movement)? Its symbol is the same you are proposing here for the "plus symbol". However, this symbol is so offensive to hundreds of millions of people in the world, that they changed it and use another one in lots of countries.

**Comment by mars501** [comment]
I think this "political correctness" thing is really getting out of hand. I mean it's a PLUS sign. A PLUS sign.
Do you know that there is a religion that worships ghosts and it's really offensive to them that you portrait the ghost like you do on the exception page. We should remove it.

**Comment by fabpot** [comment]
I also think that the plus sign is ok.

**Review by nicolas-grekas — APPROVED** [review]
That's a really nice idea, I'm :+1: with the symbols. Absolute generic universality doesn't exist, let's not try to pretend we can achieve it. This is fun and that's an important part of why we like working on Symfony together - fun.

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @przemyslaw-bogusz.

**Pull request merged**
