### PR TITLE
[DomCrawler] UriResolver support path with columns

### PR DESCRIPTION
**Pull request by vdauchy**
| Q             | A
| ------------- | ---
| Branch?       | 6.3 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix UriResolver bad handling of column in path
| License       | MIT

Resolving links on pages using weird pagination like: ```https://localhost/domain/search/page:5``` fails due to `:` making 

```
var_dump(parse_url('/page:1', \PHP_URL_SCHEME));
```

Return `false` (and not null as expected in the code).

This simply ensure the absolute URL is returned only if the SCHEME is found (ie a string is returned by `parse_url`).

### CODE REVIEW

**Comment by derrabus** [comment]
Is 5.4 not affected by this bug?

**Comment by vdauchy** [comment]
@derrabus From https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/DomCrawler/UriResolver.php I think the but does exist in 5.4.

Shall I re-do the a PR targeting 5.4 branch then the patch will be automatically applied upstream ?

**Comment by derrabus** [comment]
Yes, please target 5.4 then. No need to "re-do" the PR, just rebase this one and change the target.

**Comment by vdauchy** [comment]
Moved to https://github.com/symfony/symfony/pull/52579

**Pull request closed without merging**
