### PR TITLE
moved AppVariable to the bridge

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by stof** [comment]
shouldn't you keep the a class in the bundle extending the new one for BC ?

**Comment by fabpot** [comment]
The class was introduced in 2.7.

**Comment by stof** [comment]
then why do we have a method in it which is deprecated since 2.7 ?

**Comment by fabpot** [comment]
For compatibility with the GlobalVariables class it replaces.

**Pull request merged**
