### PR TITLE
[DependencyInjection] Single typed argument can be applied on multiple parameters

### PR DESCRIPTION
**Pull request by sroze**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ø
| License       | MIT
| Doc PR        | ø

I'm @nicolas-grekas' test writer today. This makes the argument resolution working when injecting the same type multiple times (sub-set of PR #24978)

### CODE REVIEW

**Review by Simperfit — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
thank you so much @sroze 
would be great to have another test tat ensures that the named arg wins when doing something like
`$definition->setArguments(array(CaseSensitiveClass::class => new Reference('foo'), '$class1' => ...);`

**Comment by nicolas-grekas** [comment]
do you think you coud also include the patch on PassConfig on # #24978, and add a test in ContainerBuilderTest that ensures that named arguments win over bindings?

**Comment by sroze** [comment]
@nicolas-grekas good point, I've added the test proving the named vs the typed. But I think the priority of the passes should be in another PR, will issue another tomorrow.

**Comment by sroze** [comment]
@nicolas-grekas actually needed this new test fixture class so added the test here as well. It turns out that we don't need the pass order change.

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
