### PR TITLE
use filter_var to validate email addresses

### PR DESCRIPTION
**Pull request by havvg**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by jakzal** [comment]
Here's why we migrated away from `filter_var()` : #1581

**Comment by havvg** [comment]
Well, tl;dr :) I scanned some comments, e.g. the very last one by @stof, but those are statements, without actual data or verification (and I don't have either, but the tests).

Nevertheless the regex is wrong for the test cases added, but `filter_var` is valid in addition to the already given ones.

If that's not going back into Symfony (didn't know, it was there in the first place), I'm fine with it and find another solution :)

**Comment by ro0NL** [comment]
#18177 has 13 upvotes, but is closed due lack of activity. Ie we keep creating new tickets this way :confused:

**Comment by fabpot** [comment]
We made a decision here a long time ago and we won't change it now (mainly for BC reasons): we have a very simple regex and if you need a "better one", you can use `Egulias\EmailValidator\EmailValidator` via the strict option.

**Pull request closed without merging**
