### PR TITLE
[HttpFoundation] Add missing Response::getStatusText() method.

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Proposed as new feature but would be nice to have it as "bug fix" in 2.3 for the http bridge.

### CODE REVIEW

**Comment by Tobion** [comment]
https://github.com/symfony/symfony/pull/14421#issuecomment-94525976 ;)

**Comment by dunglas** [comment]
I've not seen this one :) But we have the valid use case now: 
- https://github.com/symfony/psr-http-message-bridge/pull/1/files#diff-7e5b3956b6ae2a5924719b9d4eecb8cdR151
- https://github.com/php-fig/http-message/blob/master/src/ResponseInterface.php#L52

What do you think @fabpot?

**Comment by dunglas** [comment]
https://github.com/symfony/psr-http-message-bridge/pull/1#discussion_r31118811

**Comment by fabpot** [comment]
I'm strongly against this change because the status text has no meaning in the HTTP spec. And PSR is flawed here. I mentioned my concerns but people disagreed. That's life.

**Comment by shakaran** [comment]
@fabpot for me has meaning since I check the status code in unit test, but also I would like check the status text received since you have some fake request made for bots or you can inject some text responses in status text

**Pull request closed without merging**
