### PR TITLE
Added "psr/log" to composer.json

### PR DESCRIPTION
**Pull request by zomberg**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13888 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by stof** [comment]
:+1: It is indeed a mandatory dependency for the error handler

**Comment by fabpot** [comment]
I don't see how this is mandatory.

**Comment by zomberg** [comment]
Psr\Log\LoggerInterface using in https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Debug/ErrorHandler.php

**Comment by fabpot** [comment]
I can see where it's used but that's not a requirement for using the ErrorHandling class.

**Comment by stof** [comment]
hmm indeed. The usage of the LogLevel constants in a way making the psr/log library mandatory is only in 2.6+

**Pull request closed without merging**
