### PR TITLE
Add .gitattributes to .gitattributes

### PR DESCRIPTION
**Pull request by reedy**
| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

While .gitattributes is great and removes extra files, unless we also exclude it, we add a new file to many clones which is just as annoying :)

### CODE REVIEW

**Comment by fabpot** [comment]
I think I prefer to keep it. That way people can see what they are missing and anyway, it does not matter to keep this file.

**Comment by reedy** [comment]
> I think I prefer to keep it. That way people can see what they are missing and anyway, it does not matter to keep this file.

Technically, it doesn't "matter" to keep most of the files .gitattributes excludes. But that isn't the reason we exclude them...

**Comment by stof** [comment]
Well, excluding Tests removes half of the size of the archive. That makes a big difference in the download (and disk size, which matters for people building Docker archives for instance). Excluding .gitattributes would save only a few bytes.

**Comment by fabpot** [comment]
I think we need to move. We've spent too much time on that topic. It's not worth it.

**Pull request closed without merging**
