### PR TITLE
[Translation] Reverse fallback locales

### LINKED ISSUE #42480: Translation fallback order error
### Discussed in https://github.com/symfony/symfony/discussions/42479

<div type='discussions-op-text'>

<sup>Originally posted by **mboeck001** August 11, 2021</sup>
Hi!

There seems to be a bug in Symfony\Component\Translation computing the fallbacks in method computeFallbackLocales. Perhapes someone can confirm or correct me?

- We use a valid ICU language selector e.g de_AT_VIENNA and we have a message file for de, de_AT and de_AT_VIENNA containing a valid translation
- locale is de_AT_VIENNA
- the lookup ID is missing in de_AT_VIENNA, so fallback is triggered
- the fallback is computed in the order first de, then de_AT, what is imo wrong, it has to be de_AT followed by de corresponding to ICU usage

I would just change the array_unshift to a normal append operation

Did I miss something? This seams to be since a long time ...

changed line arround line 441  of Translator.php to:

            if (null !== $locale) {
                // m.boeck: wrong order in fallback - bug in symfony
                $locales[] = $locale;
            }

removing the array_unshift operation. For me it works.

Thats also in the 4.x branch.

Martin</div>

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #42480 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 
<!--

### CODE REVIEW

**Comment by mboeck001** [comment]
Hi! There seems to be another problem with this fix, if there are manual or default fallbacks. I changed the routine at my place to this to fix it - the logic is to first take all computed fallbacks, and afterwards all fix coded fallbacks ...

`    protected function computeFallbackLocales($locale)
    {
        if (null === $this->parentLocales) {
            $this->parentLocales = json_decode(file_get_contents(__DIR__.'/Resources/data/parents.json'), true);
        }

        $locales = [];
        // m.boeck: Fallback bug
        $localesManual = [];
        foreach ($this->fallbackLocales as $fallback) {
            if ($fallback === $locale) {
                continue;
            }

            // m.boeck: Fallback bug
            $localesManual[] = $fallback;
        }

        while ($locale) {
            $parent = $this->parentLocales[$locale] ?? null;

            if ($parent) {
                $locale = 'root' !== $parent ? $parent : null;
            } elseif (\function_exists('locale_parse')) {
                $localeSubTags = locale_parse($locale);
                $locale = null;
                if (1 < \count($localeSubTags)) {
                    array_pop($localeSubTags);
                    $locale = locale_compose($localeSubTags) ?: null;
                }
            } elseif ($i = strrpos($locale, '_') ?: strrpos($locale, '-')) {
                $locale = substr($locale, 0, $i);
            } else {
                $locale = null;
            }

            if (null !== $locale) {
                // m.boeck: wrong order in fallback - bug in symfony
                $locales[] = $locale;
            }
        }

        // m.boeck: fallback bug
        return array_unique(array_merge($locales, $localesManual));
    }`

For testing there should be a testcase for manual set fallbacks ...

**Comment by ro0NL** [comment]
status: needs work

**Comment by ro0NL** [comment]
LGTM. Remaing failure seems random.

Status: needs review

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @ro0NL.

**Pull request merged**
