### PR TITLE
[Messenger] Fix new AMQP Transport test with Envelope & fix contract

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 4.1 
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | https://travis-ci.org/symfony/symfony/jobs/377246434#L3685-L3686, https://ci.appveyor.com/project/fabpot/symfony/build/1.0.36261#L297   
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by sroze — APPROVED** [review]
I was about to send that one hehe. Thanks!

**Comment by yceruto** [comment]
Me too :) Could we have a test case this?

**Comment by ogizanagi** [comment]
@yceruto : It's already covered (see failing tests in the description :) ).
We missed it because of the component activity and not systematically rebasing PRs after a merge, hence not re-triggering a fresh build.

**Comment by sroze** [comment]
Thank you @ogizanagi.

**Pull request merged**
