### PR TITLE
Phpunit bridge replace

### PR DESCRIPTION
**Pull request by Taluu**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes ? |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

Before I migrated to Sf 2.7+ (actually it was to 2.8), I had the dependency to `symfony/phpunit-bridge` in my `require-dev` dependencies in my composer file. Then, trying to use the brand new optimization from @nicolas-grekas in composer/composer#5174, I had some problem with conflicting classes name, because both `symfony/symfony` AND `symfony/phpunit-bridge` (which I actually forgot to remove while migrating to 2.8...) declared their classes.

So, saying that `symfony/symfony` also replaces `symfony/phpunit-bridge` is a logical step so that the package is not "installed" twice.

### CODE REVIEW

**Comment by Taluu** [comment]
wrong target, closing

**Comment by stof** [comment]
@Taluu even with a different target, this is wrong. The issue with conflicting class names has already been solved. ``symfony/symfony`` was not meant to make the phpunit bridge autoloadable (because this would make the code more complex due to some requirements of the bridge). We only have this mistake in some patch releases, but the next ones will be fixed

**Comment by Taluu** [comment]
Maybe but the phpunit-bridge *is* installed on symfony 2.7+, even though it is loaded only on `dev` dependencies. The fact that it does "conflict" with `symfony/phpunit-bridge` is still relevant, even though there is no autoload triggered with it (like with the different polyfills)

**Comment by stof** [comment]
@Taluu if the classes are not autoloadable (which is the mistake we did in the latest patch release), there is nothing replacing the bridge (as installing the full package won't allow using the bridge).
And as the mistake has already been reverted, your PR actually breaks the usage of the bridge with Symfony.

**Comment by Taluu** [comment]
Fair enough

**Pull request closed without merging**
