### PR TITLE
[HttpKernel] add `kernel.runtime_environment` = `%env(default:kernel.environment:APP_RUNTIME_ENV)%` parameter

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Instead of #37584 

This PR adds a new `kernel.runtime_environment` parameter, which creates a convention to use the `APP_RUNTIME_ENV` env var to define the name of the runtime environment where the app is deployed.

When this env var is not set, the parameter defaults to `kernel.environment`.

This is especially useful for defining the location of the vault for secrets: an app can be deployed in "prod" mode, but still not be deployed on the real prod deployment target. When this happens, one might not use real prod secrets but instead, use a vault with creds for staging.

This parameter enables this use case.

### CODE REVIEW

**Comment by Koc** [comment]
Why not `kernel.runtime_environment` to be consistent in parameters naming?

**Comment by nicolas-grekas** [comment]
> Why not kernel.runtime_environment to be consistent in parameters naming?

Because it's shorter and equally descriptive to me.

**Review by jderusse — APPROVED** [review]
another advantage: developers can use `APP_RUNTIME_ENV=prod ./bin/console secret:set` to define secret in "prod" environment without needing to build and boot a "prod" containers. It avoid booting tools like "newrelic", "sentry", ...

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
