### PR TITLE
[Validator] Added a missing translation

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Comment by xabbuh** [comment]
This translation was also already present in the `4.2` branch. There it read like this:

> Este valor debería ser un múltiplo de {{ compared_value }}.

What would be the more precise translation?

**Comment by javiereguiluz** [comment]
@xabbuh good catch. Both are correct but I'm looking into which one is the most correct. I'll come back here when I have a response.

**Comment by xabbuh** [comment]
Thank you, the one from this PR currently is the version in all branches to be consistent.

**Comment by javiereguiluz** [comment]
[I've asked via Twitter](https://twitter.com/RAEinforma/status/1096333684477739009) to the legal authority that regulates the Spanish language and they told me that both are equally correct.

Let's keep using the new translation of this PR because:

* Google gives 342K results for this translation and 236K results for the previous one.
* [Wikipedia page](https://es.wikipedia.org/wiki/M%C3%BAltiplo) uses both, but this one more often.
* [The only example](https://dle.rae.es/?id=Q4kjZjE) in the official Spanish dictionary shows this one.

**Pull request merged**
