### PR TITLE
[FrameworkBundle] Add conflict with `WebProfilerBundle` < 6.4

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | #52210
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Works for me, but can you think of any other way that wouldn't involve a conflict?

**Comment by HeahDude** [comment]
The only other way I can think of would be to disallow FWB 6.4 by adding the conflict in WPB 5.4.

**Comment by smnandre** [comment]
If the problem happen only with 2 datacollectors, would it be possible to add a specific conflict ?

FMB 6.4 has a conflict with worflow < 6.4, but allow console 5.4.. so i guess there won't be a problem with the new worflow profiler

What if we add a conflict on console < 6.4 on FMB ?

**Review by nicolas-grekas — APPROVED** [review]
On closer look, this is fine to me :rocket:

**Comment by nicolas-grekas** [comment]
Thank you @HeahDude.

**Comment by chalasr** [comment]
@smnandre That wouldn’t have been enough to fix the issue at hand as the missing template is both located in and rendered by WPB. See the failing build which does run with Console v6.4-dev

**Comment by smnandre** [comment]
@nicolas-grekas @chalasr 

 I "fixed" it in another way..... by declaring the collector separately

--> Changes: https://github.com/symfony/symfony/compare/6.4...smnandre:symfony:fix/console-profiler 
--> Runs: https://github.com/smnandre/symfony/actions/runs/6599172839/job/17927922180 

But..... is it only because this one was merged ? (even if i restored the conflict as it was before ?)   😨

**Comment by nicolas-grekas** [comment]
Send the PR! :)

**Pull request merged**
