### PR TITLE
[Translation][fallback] add missing resources in parent catalogues.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20420
| License       | MIT
| Doc PR        | ~

### CODE REVIEW

**Comment by xabbuh** [comment]
👍

**Comment by msheakoski** [comment]
@aitboudad thank you for fixing this. I noticed that the patch is on the 2.7 branch, but I was actually experiencing the issue on 3.1.6 when submitting the bug.

**Comment by xabbuh** [comment]
@msheakoski We always merge bugfixes into the oldest maintained branch and merge everything up to master from there on a regular basis.

**Comment by msheakoski** [comment]
@xabbuh Ahh, got it! 👍 I was not familiar with the process.

**Comment by fabpot** [comment]
Thank you @aitboudad.

**Pull request merged**
