### PR TITLE
[3.0][FrameworkBundle] Fixed Shell logo

### PR DESCRIPTION
**Pull request by francisbesset**
This PR fix #12565.

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: Nice. Thanks @francisbesset.

Somewhat related to this: there was a discussion a time ago about removing this shell in Symfony3 because "nobody" uses it. Should we really remove it?

**Comment by francisbesset** [comment]
@javiereguiluz The soul of Symfony is based on this ASCII logo.

**Comment by javiereguiluz** [comment]
In that case, I'd prefer to update the ASCII logo by something much more beautiful. Here it is an example of a beautiful ASCII console logo which also provides useful information about the system:

archey - mac - console

**Comment by Tobion** [comment]
Also the `Symfony2` term has been replaced by just `Symfony`. So I guess `Symfony3` as name won't happen.

**Comment by francisbesset** [comment]
@Tobion rights! Logo fixed.

**Comment by francisbesset** [comment]
@Tobion The PR must be merged in 2.3 branch.

**Comment by francisbesset** [comment]
Closed in favor of #13776

**Pull request closed without merging**
