### PR TITLE
[Workflow] Move ValidateWorkflowsPass to the Workflow component

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Continues #21284

### CODE REVIEW

**Comment by chalasr** [comment]
Rebased, this is ready.

**Review by xabbuh — CHANGES_REQUESTED** [review]
`symfony/dependency-injection` must now be added to the `require-dev` section of the Workflow component's  `composer.json` file.

**Comment by chalasr** [comment]
@xabbuh the rebase went wrong, fixed now.

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @chalasr.

**Pull request merged**
