### PR TITLE
fix type hint for salt in PasswordEncoderInterface

### PR DESCRIPTION
**Pull request by garak**
See issue #31812

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #31812
| License       | MIT
| Doc PR        | none

Pretty self-explanatory

### CODE REVIEW

**Review by chalasr — APPROVED** [review]

**Comment by xabbuh** [comment]
The `mergePasswordAndSalt()` method in the `BasePasswordEncoder` class could be updated as well.

**Review by xabbuh — APPROVED** [review]

**Review by Tobion — APPROVED** [review]
Null is also used https://github.com/symfony/symfony/blob/061f622a6147ba0758d5ec941ab8475ad848df55/src/Symfony/Bundle/SecurityBundle/Command/UserPasswordEncoderCommand.php#L132

But in general I think we should deprecate the salt argument completely as it's not best practice anymore. E.g. php also deprecated it in https://www.php.net/manual/en/function.password-hash.php

**Comment by nicolas-grekas** [comment]
> we should deprecate the salt argument completely as it's not best practice anymore

100% the only issue is figuring out a smooth way to upgrade. I think we'll be able to do it in 5.1 once we provide a way to migrate passwords to new hash algos. Would that make sense?

**Comment by nicolas-grekas** [comment]
Thank you @garak.

**Pull request merged**
