### PR TITLE
[PhpUnitBridge] Fix test fixture filename

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | no
| License       | MIT
| Doc PR        | -

Fixes PHPUnit warning `Test case class not matching filename is deprecated`. I checked that the filename being different than the class name is not "required" for the test.

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Im happy to make this target 4.4. 

I let others decide if we should add it to 3.4 or not.

**Review by derrabus — APPROVED** [review]
for 4.4

**Comment by chalasr** [comment]
This won't break anything. 3.4 looks good to me.

**Review by chalasr — APPROVED** [review]

**Comment by derrabus** [comment]
> 3.4 looks good to me.

Probably, but @fabpot has to approve then.

**Review by fabpot — APPROVED** [review]
Let's merge into 3.4.

**Comment by fabpot** [comment]
Thank you @fancyweb.

**Pull request merged**
