### PR TITLE
Don't mind me, just using the build system to investigate a transient build issue on Appveyor

### PR DESCRIPTION
**Pull request by greg0ire**
This one, in case you're interested: https://ci.appveyor.com/project/fabpot/symfony/builds/21320382#L1210

### CODE REVIEW

**Comment by greg0ire** [comment]
Related: https://ci.appveyor.com/project/fabpot/symfony/builds/21331665#L1202 ?

**Comment by greg0ire** [comment]
Come on! Now it fails with a different error message:
```
Symfony\Component\Process\Exception\ProcessTimedOutException: The process "c:\php\php.exe "C:\projects\symfony\src\Symfony\Component\Process\Tests/KillableProcessWithOutput.php"" exceeded the timeout of 60 seconds.
C:\projects\symfony\src\Symfony\Component\Process\Process.php:1242
C:\projects\symfony\src\Symfony\Component\Process\Process.php:455
C:\projects\symfony\src\Symfony\Component\Process\Tests\ProcessTest.php:146
ERRORS!
```

https://ci.appveyor.com/project/fabpot/symfony/builds/21343243#L1203

I have seen it in another failing build that does not have my changes…

**Comment by greg0ire** [comment]
Third failure that can happen, apparently: the process is not even running (so, fails to start?)

**Comment by greg0ire** [comment]
:astonished:  Things are getting even weirder:
```
1) Symfony\Component\Process\Tests\ProcessTest::testWaitUntilSpecificOutput
Failed asserting that 'Second iteration output\n
One more iteration output\n
' starts with "First iteration output
Second iteration output
One more".
C:\projects\symfony\src\Symfony\Component\Process\Tests\ProcessTest.php:149
```

Now I am getting output in disorder :thinking: 

https://ci.appveyor.com/project/fabpot/symfony/builds/21344789#L1190

**Comment by nicolas-grekas** [comment]
Could this be related to workarounds implemented in `WindowsPipes`?
I fear they're still needed in PHP 7.1 era...

**Comment by greg0ire** [comment]
I'll try to look into it later, but I'm really not that well-versed on Windows' idiosyncrasies… @romainneutron , maybe you can help?

**Comment by Mx-Glitter** [comment]
@greg0ire It might be completely unrelated, are you also investigating this kind of failure: https://ci.appveyor.com/project/fabpot/symfony/builds/21322425?

**Comment by greg0ire** [comment]
It is indeed completely unrelated, but I think me might need to create a github project here: https://github.com/symfony/symfony/projects or a label or something to track transient builds issues, because there seems to be a lot of them. I saw 2 others on AppVeyor when trying to investigate this one.

**Comment by nicolas-grekas** [comment]
Let's create a meta issue for now, like #15617 in its time.

**Comment by greg0ire** [comment]
Let's use #29760 for this

**Pull request closed without merging**
