### PR TITLE
chore: PHP CS Fixer fixes

### PR DESCRIPTION
**Pull request by keradus**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix CS 
| License       | MIT

### CODE REVIEW

**Comment by OskarStark** [comment]
Do we need to upgrade fabbot?

**Comment by keradus** [comment]
I explicitly applied subset of rules, as it's still over 100+ files to fix and I find it easier to review and apply step by step, and I do steps as rules and not as files. That's why fabbot can see some potential more changes, that I didn't apply, as they are coming from rules I was not applying in this PR.

**Comment by keradus** [comment]
To answer if it's beneficial to update fabbot, I encourage to start mentioning version of Fixer in fabbot report (cc @fabpot).
Without that version, I cannot tell if it's important to upgrade the version right away or if it can wait.

**Comment by fabpot** [comment]
FYI, it was v3.64.0, and I've just upgraded it to v3.65.0.

**Comment by fabpot** [comment]
As Symfony 7.2 has been released now, this PR should target 7.3.

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @keradus.

**Pull request merged**
