### PR TITLE
[ErrorHandler][DebugClassLoader] Add mixed and static return types support

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Is it something that needs to be merged in an older branch instead?

**Comment by fancyweb** [comment]
I considered this a new feature. I don't remember your policy for supporting new PHP versions features.

**Comment by fabpot** [comment]
Right now, we add support for newest PHP versions in the lowest maintained version, that's why I'm asking.

**Comment by fancyweb** [comment]
I need to rebase on 4.4 then, do you agree?

**Comment by fabpot** [comment]
Yes, please.

**Comment by fabpot** [comment]
Thank you @fancyweb.

**Pull request merged**
