### PR TITLE
Add clearScreen to Console

### PR DESCRIPTION
**Pull request by alexbowers**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Resubmitted because of losing original branch.

Resubmit of #23318

### CODE REVIEW

**Comment by alexbowers** [comment]
I don't know why this broke the  tests. 

Can the tests be re-ran please?

**Comment by alexbowers** [comment]
Interesting. The fabbot patch fixed it all. :|

**Review by keradus — CHANGES_REQUESTED** [review]
:-1: I know it's hard, but we need automated tests.

**Comment by ostrolucky** [comment]
I don't think this will be needed if https://github.com/symfony/symfony/pull/24363 gets merged

**Comment by alexbowers** [comment]
These have different use cases.

My PR would perform an effective "Cmd + R" or "clear" command.

Useful for clearing all output from the screen. 

That PR seems to have a use case similar to when you run npm install or similar where you get a progress output where it replaces existing output.

I think them both being in Symfony is beneficial.

**Comment by ostrolucky** [comment]
This isn't CTRL+R/clear variation. Your patch erases whole terminal history. Can you provide use case for this? I don't think this is acceptable for application to do.

**Comment by nicolas-grekas** [comment]
Moving to 4.1 as the discussion is still on going and we're in feat freeze.

**Comment by alexbowers** [comment]
If the linked PR can do what I wanted this to do, im happy for this to be closed in favour of that one.

**Comment by nicolas-grekas** [comment]
To not let this stay forever here, I'm voting :-1: here: this belongs to a set of features that the Console component does handle (console screen management).

**Comment by theofidry** [comment]
@alexbowers I think the linked PR covers your cases and more :)

**Comment by alexbowers** [comment]
I agree, happy for this to be closed.

**Pull request closed without merging**
