### PR TITLE
[FrameworkBundle] Fix logic in workflow:dump between workflow name and workflow id

### LINKED ISSUE #43938: [Workflow] Command workflow:dump not working
### Symfony version(s) affected

5.4

### Description

I tryed to dump a workflow in Symfony 5.4 and kept getting the Message 

`No service found for "workflow.xyz" nor "state_machine.xyr".`

I tryed to reproduce it in Symfony 5.3 and found that it is working, but got the following warning:

`User Deprecated: Since symfony/framework-bundle 5.3: Accessing the "workflow.xyz" service directly from the container is deprecated, use dependency injection instead.`

### How to reproduce

Create a Workflow in Symfony 5.4 and try to dump it:
https://github.com/ch2877/symfony_issue_43938

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by 94noni**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/43938
| License       | MIT

As described in https://github.com/symfony/symfony/issues/43938#issuecomment-961804981
the command need a workflow name as argument, but the array contains workflows ids (prefix `workflow|state_machine`)

### CODE REVIEW

**Review by StaffNowa — APPROVED** [review]
Thanks for fix ;)

**Comment by noniagriconomie** [comment]
@StaffNowa really my bad maybe wrong explanation on your PR!
conflicts between the workflow name pass as argument and the workflows ids passed in constructor :)

**Review by lyrixx — APPROVED** [review]
LGTM

**Comment by fabpot** [comment]
Thank you @94noni.

**Pull request merged**
