### PR TITLE
[DoctrineBridge][Form] Run tests with doctrine/collections 2

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

~~Blocked by doctrine/collections#353~~

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
It'd be great fixing the "Remaining indirect deprecation" before merging.

**Comment by derrabus** [comment]
I thought I had done that. I'll check again.

**Comment by derrabus** [comment]
PR is ready. The remaining failures look unrelated to me.

**Review by xabbuh — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @derrabus.

**Pull request merged**
