### PR TITLE
[travis] Test on PHP 7.1

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Tests pass? | let's see |
| License | MIT |

PHP 7.1 RC2 has been released today.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Needs https://bugs.php.net/73113

**Comment by fezfez** [comment]
https://bugs.php.net/73113 is fix

**Comment by nicolas-grekas** [comment]
Waiting for Travis to update to RC3

**Comment by nicolas-grekas** [comment]
Needs https://github.com/krakjoe/apcu/issues/201 on master

**Pull request merged**
