### PR TITLE
[Intl] Update ICU data to 62.1

### PR DESCRIPTION
**Pull request by jakzal**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

It's this time of the year again to update ICU data. http://site.icu-project.org/download/62

Not many actual changes this time. Few new scripts added and some metadata for the VEF currency.

### CODE REVIEW

**Comment by stof** [comment]
New scripts added in `en` but not in any other locales ? Do we have a bug in our importer, or are they shipping en-only data in the ICU release now ?

**Comment by jakzal** [comment]
@stof indeed only `en` locale seems to be updated in ICU. Example: http://source.icu-project.org/repos/icu/tags/release-62-1/icu4c/source/data/lang/pl.txt

**Comment by stof** [comment]
Too bad that the ICU data were not sent to translators before the release...

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jakzal.

**Pull request merged**
