### PR TITLE
Fix the server variables in the router_*.php files

### PR DESCRIPTION
**Pull request by leofeyer**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | none |
| License | MIT |

The built-in web server automatically rewrites everything to the `app_dev.php` script, but it does not adjust the server variables accordingly.

Here is the output of `print_r($_SERVER)` on Apache with mod_rewrite enabled (relevant lines only):

```
Array
(
    [REQUEST_URI] => /text-elements.html
    [SCRIPT_NAME] => /app_dev.php
    [PHP_SELF] => /app_dev.php
)
```

And here is the output of the exact same script on the built-in server:

```
Array
(
    [REQUEST_URI] => /text-elements.html
    [SCRIPT_NAME] => /text-elements.html
    [PHP_SELF] => /text-elements.html
)
```

And here is the return value of Symfony's `Request::getScriptName()` method:

``` php
// Apache: http://localhost/text-elements.html
echo $this->container->get('request_stack')->getCurrentRequest()->getScriptName(); // /app_dev.php

// Built-in web server: http://127.0.0.1:8000/text-elements.html
echo $this->container->get('request_stack')->getCurrentRequest()->getScriptName(); // /text-elements.html
```

This PR fixes the two server variables in the `router_dev.php` script.

### CODE REVIEW

**Comment by fabpot** [comment]
I think you also need to do the same changes in `router_prod.php`.

**Comment by bytehead** [comment]
> I think you also need to do the same changes in router_prod.php.

Yes, the behaviour is also wrong in prod environment.

**Comment by leofeyer** [comment]
You are right. I have updated the PR.

**Comment by TomasVotruba** [comment]
What needs to be done here?

**Comment by xabbuh** [comment]
Isn't this something to be fixed in PHP?

**Comment by leofeyer** [comment]
Certainly not. Adjusting the environment variables is done by the rewrite module of your web server. Just look at the existing code:

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_prod.php#L34

`$_SERVER['SCRIPT_FILENAME']` is already being adjusted; but since the script is in fact rewriting the URL, `$_SERVER['SCRIPT_NAME']` and `$_SERVER['PHP_SELF']` have to be adjusted accordingly, too.

**Comment by OskarStark** [comment]
You should change (because of the prod file) the headline of this PR

**Comment by fabpot** [comment]
Thank you @leofeyer.

**Comment by OskarStark** [comment]
:+1:

**Comment by bytehead** [comment]
:+1:

**Pull request closed without merging**
