### PR TITLE
[Serializer] Ensure that groups are strings

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by paradajozsef** [comment]
:+1: 

One more thing to note. If such a yml is provided to the loader:

```yml
Acme\MyObj:
    attributes:
        foo:
            groups: 'group1'
```

```Invalid argument supplied for foreach()``` warning raises, because it is [not ensured here](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Serializer/Mapping/Loader/YamlFileLoader.php#L76).

If you think this should be in another PR, than sorry. :)

**Comment by dunglas** [comment]
Good catch @paradajozsef, I've added a separate commit in this PR.

**Comment by paradajozsef** [comment]
:+1:

**Comment by Ener-Getick** [comment]
This is more a bug fix than a new feature ;-)

:+1: debugging is easier with this kind of check :smile:

**Comment by xabbuh** [comment]
We should include the name of the file and probably some other related information (class name, property or something like that) to make it easier to spot the place where the configuration is wrong.

**Comment by fabpot** [comment]
I agree with @xabbuh

**Comment by dunglas** [comment]
Status: Need Review

@xabbuh @fabpot done

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request closed without merging**
