### PR TITLE
[MonologBridge] access processors only when they exist

### LINKED ISSUE #34520: [MonologBridge] ServerLogHandler is incompatible with Monolog 2.0
Because Monolog removes the protected attribute `$processors` in `AbstractHandler`

```
  - Updating monolog/monolog (1.25.2 => 2.0.1): Loading from cache                          
  - Updating symfony/monolog-bridge (v4.4.0 => v5.0.0): Loading from cache                  
```

```
In ServerLogHandler.php line 106:                                            
                                                                                            
  [ErrorException]                                                                          
  Notice: Undefined property: Symfony\Bridge\Monolog\Handler\ServerLogHandler::$processors  
```

I don't have time to dig right now, but can check it later next week.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34520
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by jderusse** [comment]
Shouldn't we use the `ProcessableHandlerTrait` (https://github.com/Seldaek/monolog/commit/902c0c86944c0457317523e164c10a4f45c9f52e#diff-d1d031ebe96084844fb53eb650bc404eR24) or extends the `AbstractProcessingHandler` instead?

**Comment by xabbuh** [comment]
That's not available in Monolog 1, is it?

**Comment by jderusse** [comment]
`AbstractProcessingHandler` does. 

Or we can add a compatibility layer (like we usually do)
```
if (trait_exists(ProcessableHandlerTrait::class)) {
  class ServerLogHandler {
    use AbstractProcessingHandler;
    use ServerLogHandlerTrait;
  }
} else {
  class ServerLogHandler {
    use ServerLogHandlerTrait;
  }
}
trait ServerLogHandlerTrait {
}
```

**Comment by xabbuh** [comment]
closing in favour of #34697

**Pull request closed without merging**
