### PR TITLE
Updated the style of the translation commands

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

@ogizanagi did a great job updating the styles of these commands. This is just a bit of tweaking here and there:

(Left = old; Right = new)

comparison_1

comparison_2

comparison_3

comparison_4

comparison_5

### CODE REVIEW

**Comment by fabpot** [comment]
Can you reference the original PR?

**Comment by javiereguiluz** [comment]
The original PR which was merged is #14595

**Comment by fabpot** [comment]
:+1:

**Comment by ogizanagi** [comment]
:+1:

**Comment by fabpot** [comment]
Needs the new output method before merging

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
