### PR TITLE
[Mime] Attaching '.oft' extension to 'application/vnd.ms-outlook'

### PR DESCRIPTION
**Pull request by ktherage**
| Q             | A
| ------------- | ---
| Branch?       | 5.4/5.3
| Bug fix?      | potentially
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

Microsoft outlook uses two extensions for the mime type "application/vnd.ms-outlook", '.msg' was existing but not '.oft'.

### CODE REVIEW

**Review by mcneely — APPROVED** [review]
Confirmed that this is the proper mimetype for oft.

**Comment by fabpot** [comment]
Can you instead submit that upstream? https://gitlab.freedesktop.org/xdg/shared-mime-info/-/raw/master/data/freedesktop.org.xml.in?inline=false

**Comment by fabpot** [comment]
Closing as this should be submitted upstream instead.

**Comment by ktherage** [comment]
FYI : Merge Request created (https://gitlab.freedesktop.org/xdg/shared-mime-info/-/merge_requests/145)

**Comment by fabpot** [comment]
Great, thank you!

**Comment by ktherage** [comment]
@mcneely, sorry for disturbing, but in the Merge Request I've opened as requested by @fabpot, the `.oft` extension is nowhere to be found in Microsoft's documentation. I also didn't found it on my side.

Do you got a link that prooves that this extension is OK for that MIME Type ?

**Pull request closed without merging**
