### PR TITLE
[DI] Register PSR4 prototypes definitions

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23497 
| License       | MIT
| Doc PR        | todo

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Would that be usable with the default config, or will child definitions conflict?
A functional test ensuring this works would be great :)

**Review by nicolas-grekas — COMMENTED** [review]
This makes one able to inherit from one specific prototype service and specialize it manually.
But the inheritance is limited by the fact that all attributes in `_defaults` and all tags must be repeated since they are not inherited.
This means the interest of inheriting from a prototype is restricted to all the other possible attributes (setters, etc.)
If this is enough value, then implementation looks good to me. If not, it is worth it? Then should we seek for another syntax? That's the questions in my head right now :)

**Comment by chalasr** [comment]
Writing the integration test made me feel it's not worth it, the code in the fixed ticket would be as verbose as if it was using the current possible alternatives. More limitations and edge cases to cover than added value. 
I think `parent` is still useful for distributed stuff but should now be very rare in userland, and is surely not the right way to improve the situation.

If no better solution (I have no) then we can close here

**Comment by nicolas-grekas** [comment]
OK, closing, same feeling. We can still reconsider if a better idea comes up of course. Thanks for trying.

**Pull request closed without merging**
