### PR TITLE
[WebProfilerBundle] Add an HTML comment to specify the Symfony toolbar on the body tag

### PR DESCRIPTION
**Pull request by Arman-Hosseini**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by ro0NL** [comment]
what does it solve?

**Comment by fancyweb** [comment]
I think that `sfwdt` and `sf-toolbar` are already clear hints.

**Comment by Arman-Hosseini** [comment]
> what does it solve?

When the user sees the html source - will find that it belongs to Symfony toolbar. 
Yes it is funny but it can be effective.

**Comment by ro0NL** [comment]
i still dont see what problem it solves :) usually you inspect elements from the UI/console perspective.

id argue looking at raw HTML is a common thing, unless you know what you're looking for already.

i.e. #31514 described a much more real life problem.

**Comment by fabpot** [comment]
I'm also not convinced that this is needed (in any case, that could not go in 3.4). Let's close.

**Pull request closed without merging**
