### PR TITLE
[Console] Fix tests on Windows

### PR DESCRIPTION
**Pull request by mhujer**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14975 |
| License | MIT |
| Doc PR | none |

### CODE REVIEW

**Comment by mhujer** [comment]
fabbot.io: Suggests changes in code which is not changed in this PR - should I apply them?
travis: fails because of some composer fails (unrelated to this PR - I will rebase it once the erros are fixed, so the tests will be ran on Travis)

**Comment by mhujer** [comment]
Travis failures seem unrelated to changes in this PR

**Comment by xabbuh** [comment]
:+1: looks good

**Comment by fabpot** [comment]
Thank you @mhujer.

**Pull request closed without merging**
