### PR TITLE
[Security] add missing plural translation messages

### LINKED ISSUE #54914: Missing translation in TooManyLoginAttemptsAuthenticationException
### Symfony version(s) affected

6.4.6

### Description

The class `TooManyLoginAttemptsAuthenticationException` return a message based on the value of `threshold` class member. if this value is bigger than 1, there are a plural mark. unfortunaly, there is no translation of this message with the plural mark so the message is always in english

### How to reproduce

1. Setup a login with rate limiter and enable the translation of the app.
2. Access to the login page with a language that is not English (tested in french but the problem should be there with other languages)
3. try many invalid login attempts to trigger an error from the rate limiter
4. If the time in minutes is greater than 1, the message is in english even if the rest of the page is in another language

### Possible Solution

add a `<trans-unit>` in files that are in `symfony/security-core/Resources/translations`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54914
| License       | MIT

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
The CI is supposed to detect when a translation is missing from a file and to suggest running the sync-translations.php script to invite doing so to update the PR. Can you please check why this didn't run?

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
This makes me realize that this handling of plural translations is wrong. Plurals are way more complex as we know. We should instead use a translation key that will allow the translator to select the most appropriate plural.
Up to have a look?

**Comment by nicolas-grekas** [comment]
I figured out the code does already define the "%count%" parameter so that we can use plural forms in the translation. I used GPT to add a 2nd commit here that leverages that.

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by xabbuh** [comment]
Thanks Nicolas! 😊

**Pull request merged**
