### PR TITLE
[DependencyInjection] [WIP] Disallow using an existing class name as id for a service that declares the "class" option

### PR DESCRIPTION
**Pull request by phansys**
|Q            |A  |
|---          |---|
|Branch       |4.2|
|Bug fix?     |no |
|New feature? |no |
|BC breaks?   |no |
|Deprecations?|no |
|Tests pass?  |yes|
|Fixed tickets|n/a|
|License      |MIT|
|Doc PR       |n/a|

This PR should be taken as a RFC by now.

**TODO**:
- [ ] Validate the changes with other collaborators;
- [ ] Check if this must trigger a `E_USER_DEPRECATED` notice in the last stable branch in order to avoid BC breaks; moving the exception for the next major release;
- [ ] Implement the same checks for other loaders;
- [ ] Add tests;

### CODE REVIEW

**Comment by jvasseur** [comment]
I'm :-1: for doing this, at least not in this form.

One thing that I often do in projects is declare a service with an interface FQCN as it's id and a class that implements that interface as class.

**Comment by nicolas-grekas** [comment]
:-1: to me too: that'd be an "arbitrary" limitation.

**Comment by phansys** [comment]
Thank you for the feedback.
I understand your concerns, and by now I'm not able to give more precision about what change originated the issue I'll describe in this comment.
Recently, I was upgrading a project from 3.4 to 4.2, and some autowired services stopped to work as they were.

```yaml
services:
    App\Foo:
        class: App\BazInterface
        factory: ['App\Qux', factory]
        lazy: true

    App\Bar:
        class: App\BazInterface
        factory: ['App\Qux', factory]
        lazy: true
```
```php
namespace App;

class Foo implements BazInterface, OtherInterface
{
}

class Bar implements BazInterface
{
}

class MyClass
{
    public function(Foo $baz)
    {
        var_dump($baz instanceof OtherInterface); // prints `false`
        // `$baz` here is a proxy based on the definition of `App\Bar`, where the expected implementation should be based on the definition of `App\Bar`
    }
}
```
If I make these services not lazy or if I remove their "class" option, the issue is gone.

I'll try to investigate with more time which is the change that triggers this issue.

**Comment by nicolas-grekas** [comment]
Closing as explained. Feel free to open an issue if you think you found a bug (for now, this looks like a support request, but I may miss something of course)

**Pull request closed without merging**
