### PR TITLE
Specific encoding for DOMNode nodes.

### PR DESCRIPTION
**Pull request by fgm**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17004 |
| License | MIT |
| Doc PR | not applicable |

Supersedes #17005.

### CODE REVIEW

**Comment by stof** [comment]
Can you add a test covering this to prevent regression (i.e. a test triggering some code sending a DOMNode to this method) ?

**Comment by FGM** [comment]
Well, I did add the test, but to make it a real unit test, I had to make it really ugly because everything is private in this class. There should be a better way.

Also, I wonder what these appveyor crashes are, as they seem totally unrelated (checking a timeout).

**Comment by nicolas-grekas** [comment]
Is there no way to trigger the modified behavior with the public interface? Then this is dead code?

**Comment by stof** [comment]
I agree with @nicolas-grekas. this should be tested through the public API, with a code path reaching this code. If it cannot be reached, there is no reason to change the code order, it should simply be removed

**Comment by FGM** [comment]
Actually it is written that way to be a unit test in the strictest sense, touching only the function under test. Since you prefer involving the public API to reach that function, I'll change the test accordingly. It will just be less pure.

**Comment by fabpot** [comment]
@FGM Can you update the test to only use the public API?

**Comment by fabpot** [comment]
@FGM Any news? Can you update the test to only use the public API?

**Comment by fabpot** [comment]
Closing now. The best would probably be to remove the dead code.

**Pull request closed without merging**
