### PR TITLE
update from Postgres 10 to 16

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
see https://github.com/symfony/symfony/actions/runs/10419496931/job/28858239102#step:16:76

**Comment by derrabus** [comment]
Shall we bump even further? Postgres 12 will reach its EOL later this year. The current stable branch is 16.

ref: https://www.postgresql.org/support/versioning/

**Comment by OskarStark** [comment]
Oh, I updated the PR title and didn't recognize you are still playing with the version number, sorry

**Comment by nicolas-grekas** [comment]
The failure is likely related; my guess: localhost is resolved to ::1, but the server listens to 127.0.0.1?

**Comment by xabbuh** [comment]
build fixed, everything green with Postgres 16

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
