### PR TITLE
[WebProfilerBundle] Make admin button consistent with others

### PR DESCRIPTION
**Pull request by stloyd**
| Q | A |
| --- | --- |
| Bug fix? | yes(?) |
| New feature? | no |
| License | MIT |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:-1: from me. This feature is displayed as a link on purpose. It's a common practice to do that for this kind of secondary utilities in backend designs. Buttons are reserved for important things, and in my opinion this feature is not.

**Comment by stof** [comment]
Wait, purging is a GET request ? This should be changed to a POST request IMO

**Comment by fabpot** [comment]
I would even remove the feature from the web interface altogether. I've never used it myself and I'm pretty nobody uses it.

**Comment by javiereguiluz** [comment]
I like the idea of removing this feature. Do other Symfony deciders agree on this?

**Comment by weaverryan** [comment]
:+1: for removing the feature. If you want to purge, you can do that by emptying whatever your storage is (and for most people, just clearing the cache).

**Comment by stof** [comment]
I agree about the removal. I never purge it through the UI.

**Comment by xabbuh** [comment]
:+1: for removing the feature

**Comment by sstok** [comment]
I have actually used this (trying to debug a redirect loop and needing the first request) :) but I'm OK with removing this :+1: .

**Pull request closed without merging**
