### PR TITLE
[Security] Remove dependency on security-core from security-csrf

### PR DESCRIPTION
**Pull request by enumag**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | possibly |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15872 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by Tobion** [comment]
This cannot be done in 2.8 as it's a BC break and also doesn't make sense in 2.8 as one of the main classes still depends on `Symfony\Component\Security\Core\Util\SecureRandomInterface`. But I'm :+1: to make this change in 3.0 as there is deprecated SecureRandomInterface is removed anyway.

**Comment by enumag** [comment]
That's fine by me. If you want me to create new PR against the 3.0 branch let me know.

The change in the exception might cause BC break if somebody was catching it using the parent exception or ExceptionInterface from Securty/Core. Not sure how bad it is to make this change but it would be sad to have a dependency only because of an exception.

**Comment by enumag** [comment]
@Tobion Actually I think the dependency in UriSafeTokenGenerator is not relevant. If the interface doesn't exist, the UriSafeTokenGenerator should still work fine.

**Comment by fabpot** [comment]
Closing as we don't break BC in stable versions and we can't add new classes/exceptions.

**Comment by enumag** [comment]
@fabpot Would it be possible to do this for 4.0?

**Comment by chalasr** [comment]
@enumag It is for 3.4 (next minor release), could you rebase and update the PR target branch accordingly?

There is no more BC break, reopening.

**Comment by Tobion** [comment]
@chalasr why is there no bc break anymore? The exception hierarchy will still be changed in a BC break way.

**Comment by Hikariii** [comment]
I also think this is in line with the Symfony flex `compose all things` way of thinking. Even if it breaks a BC exception chain, I can imagine that being acceptable for a 4.* release.

**Comment by ostrolucky** [comment]
It's still a bc break, so this interface hierarchy change can't be done in `4.*`. What can be done in 4.* though is ease the migration. I suggest to not copy these classes over here, just deprecate RuntimeException in security component. In 5 just remove it and stop extending it here. RuntimeException from security is used nowhere else and doesn't bring any value here.

steps left to do here:
- revert current changes in this PR
- deprecate `\Symfony\Component\Security\Core\Exception\RuntimeException`
- update upgrade.rst

status: needs work

**Comment by chalasr** [comment]
@ostrolucky deprecating would not help here, RuntimeException especially. Triggering a notice when the exception is caught is not possible, and would not be enough anyway as one might catch `ExceptionInterface` instead.

After all I think it's not worth it, re-closing, sorry for the noise.

**Pull request closed without merging**
