### PR TITLE
Improves readability by using the null coalescing operator

### PR DESCRIPTION
**Pull request by michaelKaefer**
Replaces an isset() comparison

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by derrabus** [comment]
We have the same piece of code in the 3.4 branch where we cannot use the null coalescing operator. This PR would make merges between the branches a bit harder. Other than that the change looks good to me, but it should be applied to the 4.2 branch.

**Comment by nicolas-grekas** [comment]
> We have the same piece of code in the 3.4 branch where we cannot use the null coalescing operator. This PR would make merges between the branches a bit harder.

this is correct, and the reason why we don't do such changes,
thanks for submitting.

**Comment by michaelKaefer** [comment]
@derrabus Thank you for this info! Would you mind explaining this to me in more detail? 

1. Can I open a new PR to the 4.2 branch or must I wait until support for 3.4 ends? 
2. Why the 4.2 branch?

Thank you.

**Comment by nicolas-grekas** [comment]
1. we need to wait until 3.4 ends
2. see https://symfony.com/roadmap

**Pull request closed without merging**
