### PR TITLE
Exclude Bridge\PhpUnit from composer.json by default

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18381, #18272 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by OskarStark** [comment]
Is this already merged in 2.8 @nicolas-grekas ?

I'm using:
```
symfony/symfony                          v2.8.4             The Symfony PHP framework
....
symfony/phpunit-bridge                   v2.8.4             Symfony PHPUnit Bridge
```

and still get this error!

**Comment by xabbuh** [comment]
@OskarStark You will need to wait for the next patch release.

**Comment by OskarStark** [comment]
Thanks for the feedback @xabbuh i will! 👍

**Pull request merged**
