### PR TITLE
[Debug] split tests for deprecated interfaces

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Splitting tests for deprecated interfaces in "Legacy" prefixed test classes/methods should be done for every component.
Let's start by this simple one. To anyone: help welcomed for the other components.

### CODE REVIEW

**Comment by hhamon** [comment]
Why against 2.6 branch instead of 2.7?

**Comment by nicolas-grekas** [comment]
Because this is where the deprecation has been introduced. The split could (and should) have been done at that time.

**Comment by hhamon** [comment]
Ok I see ;)

**Comment by saro0h** [comment]
:+1:

**Comment by stof** [comment]
this needs a rebase

**Comment by stof** [comment]
Otherwise, :+1:

**Comment by nicolas-grekas** [comment]
Rebased. Having worked a bit more on the subject, I reverted the split but prefixed the methods testing deprecated interface with `testLegacy*`, and made it start by `$this->iniSet('error_reporting', -1 & ~E_USER_DEPRECATED);`

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
