### PR TITLE
[FrameworkBundle] don't register some AssetMapper services without configured HTTP clients

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | see https://github.com/symfony/symfony/pull/57073#discussion_r1611731245
| License       | MIT

### CODE REVIEW

**Comment by ruudk** [comment]
I'm not sure if this is the way to do it to be honest.

If I understand it correctly, when `http_client` is disabled, those services no longer register. That means that those functionality will not work anymore.

While with my PR, I did not inject the default http_client but instead, let the service class in question create it's own HttpClient.

I think this PR will actually break things for people that have http_client disabled.

**Comment by ruudk** [comment]
Another solution is to do the following:

If the `http_client` service exists, use and inject that. Otherwise, create a new HttpClient service and inject it inline. 

The AssetMapper component already [requires HttpClient](https://github.com/symfony/symfony/blob/bed9c3660c0106049622eead422fcb3921f8dd21/src/Symfony/Component/AssetMapper/composer.json#L23). But on the Framework level, there is no guarantee that the `http_client` is registered (because it was disabled).

**Comment by xabbuh** [comment]
> I think this PR will actually break things for people that have http_client disabled.

Not sure about that, those service have already been unusable before as you pointed out in your PR. So this doesn't change here.

**Comment by ruudk** [comment]
That's right, it was already broken indeed.

Solving it like this would be the way to go if you ask me: https://github.com/symfony/symfony/pull/57219#issuecomment-2136745936

Instead of removing the functionality that produced an error, it would solve the functionality, without needing addition work for the user.

**Comment by smnandre** [comment]
> If the http_client service exists, use and inject that. Otherwise, create a new HttpClient service and inject it inline.

@xabbuh what do you about this ? 

I can create a PR in this direction if you want 

(as asset-mapper does require http-client as direct dependency, it would allow to fix things for everyone.... or am i beeing naive here ?)

**Pull request closed without merging**
