### PR TITLE
[Routing] support for array values in route defaults

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

As pointed out in symfony/symfony-docs#4017, the `XmlFileLoader` was not capable of defining array default values.
- [x] array values
- [x] integer values
- [x] float values
- [x] boolean

### CODE REVIEW

**Comment by fabpot** [comment]
Re-reading this old PR, I still thing that defaults should only be strings or null. When parsing a path, you can only get back strings anyway, so allowing defaults to be something else seems wrong to me. I'm in favor of deprecating the possibility to use any other kind of value.

**Comment by Tobion** [comment]
One point of routing is that you can change URIs without chaning the code to parse/generate them. Since array params can be used for query strings, at one point it would also make sense to allow arrays in the path. For example, URI templates standard supports that by expanding arrays to comma-separated values.
So removing non-string defaults would be a step in the wrong direction IMO.

**Comment by Tobion** [comment]
Also with the introduction of scalar type hints, what if a controller parameter is typehinted to `int` for example? I guess this will be cast implicitly at the moment. But with strict types, it would cause an error. So in theory either the router itself could cast params (for example based on the requirement) or the code that calls the controller. So then route params would need to be non-strings as well.

**Comment by fabpot** [comment]
ok, you're right. Let's finish this one then.

**Comment by stof** [comment]
@Tobion strict types are irrelevant here, because the strict mode for arguments is determined by the calling code, not by the file declaring the controller, and the Kernel class (which is calling the controller) is not in strict mode

**Comment by Tobion** [comment]
@stof I know. But who says Symfony 4 will not add scalar type hints in certain places and maybe strict types?

**Comment by xabbuh** [comment]
rebased here, if I don't miss anything all comments made so far have already been addressed

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by Tobion** [comment]
Maybe we should rename `boolean` and `integer` elements to `bool` and `int` elements as the short names are now more standard considering scalar typehints etc.

**Pull request merged**
