### PR TITLE
Fix missing deprecation notice for `type`

### PR DESCRIPTION
**Pull request by wouterj**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Replaces https://github.com/symfony/symfony/pull/16231

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Cool, many thanks!
You may have to raise a few lowest versions in composer.json files isn't it?

**Comment by WouterJ** [comment]
Afaics, all dependencies are correct. Something seems wrong in the way we set type instead of entry_type (entry_type will get the incorrect value). I'm not sure why occurs in HHVM and PHP 5.3 and 7...

**Comment by stof** [comment]
@WouterJ this is because the type normalizer is broken. It misses the return statement, meaning it always return ``null`` for the option

**Comment by stof** [comment]
and the reason why only these jobs are broken is clear:

- 5.4 and 5.5 are not running tests for PRs to make builds faster
- 5.6 is running deps=high, which does not run legacy tests, and the issue is in a legacy test

**Comment by WouterJ** [comment]
Thanks @stof for the explanation.

Tests pass now (appveyor failure seems to be unrelated).

**Comment by fabpot** [comment]
Thank you @WouterJ.

**Pull request merged**
