### PR TITLE
[FrameworkBundle] Add default mapping path for validator component in bundle-less app

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | ToDo

Same approach of https://github.com/symfony/symfony/pull/24833

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
For 3.4?

**Comment by yceruto** [comment]
@nicolas-grekas I guess yes, same opinion of @dunglas https://github.com/symfony/symfony/pull/24833#pullrequestreview-74588324

Rebased to 3.4

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @yceruto.

**Comment by strawburrypokki** [comment]
Hello, quick question.  
I've noticed that the default path for validation metadata file is in `$projectDir.'/config/validator'` directory (eg. `/home/sf_project/config/validator/`).

Is it deliberate? What about Sf3 directory structure and the `app/config` directory (eg. `/home/sf_project/app/config/validator`)?

**Pull request merged**
