### PR TITLE
[Tests] Remove annotation of excpectedException Batch #1

### PR DESCRIPTION
**Pull request by gmponos**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Tests pass?   | yes  
| License       | MIT

According to PHPUnit [latest release](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-7.5.md) annotations of `expected*` are deprecated and will be removed. 

I guess this is done because the annotation was misused. By not using the annotation you can make sure where the exception is thrown.

This PR is premature but it will be better to have it now and start writing new PRs in this way rather than keep submitting new features with the old way and pay it later with more places to change and also it promotes a "correct" way of testing exceptions.

At the current PR only `expectedException \InvalidArgumentException` are fixed.. 

Let me know if you agree on doing it partially each time.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
PHPUnit 4.8 was required because of branch 2.8 which supported PHP 5.3
Now that the minimum PHP version of 3.4 is PHP 5.5, we can bump the minimum phpunit version we use I suppose.

**Comment by gmponos** [comment]
> Now that the minimum PHP version of 3.4 is PHP 5.5, we can bump the minimum phpunit version we use I suppose.

Ah!... ok.. I'll see if I can do that on another PR and if this is possible I will reopen this...

**Comment by gmponos** [comment]
First of all.. what's up with this https://github.com/symfony/phpunit-bridge/blob/master/composer.json#L19 ?

Secondly the place that I must bump the min phpunit version is inside [here](https://github.com/symfony/phpunit-bridge/blob/master/bin/simple-phpunit)?

**Comment by nicolas-grekas** [comment]
> PHPUnit 5 requires PHP 5.6+

looks like this means we cannot bump :(

**Comment by gmponos** [comment]
So this means that we have to wait for symfony v5 in order to proceed with changes like this? not even in 4?

OMG! 😛

**Comment by nicolas-grekas** [comment]
Correct, stability first :)

**Pull request closed without merging**
