### PR TITLE
Remove unused constant

### PR DESCRIPTION
**Pull request by medinae**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Just a micro clean-up PR, to assimilate the Symfony PR process.
Hope the next one will be more useful 🤔

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Congrats :)
Since this patch also applies to branch 2.7, it should be submitted again branch 2.7.

**Comment by medinae** [comment]
Target branch switched to 2.7

**Comment by chalasr** [comment]
Can you rebase your branch against 2.7 to make tests green?

**Comment by medinae** [comment]
@chalasr Done.

**Comment by chalasr** [comment]
Thank you for this first contribution @medinae.

**Pull request merged**
