### PR TITLE
[Security] Added option to return true in the method isRememberMeRequested

### PR DESCRIPTION
**Pull request by WhiteEagle88**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #21807 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by fabpot** [comment]
When can it be a boolean and not a string? The value comes from the request, so it's always a string, right?

**Comment by xabbuh** [comment]
The linked issue is talking about sub-requests. I guess the value is written manually into the request's attributes (which are checked first in `Request::get()`) before performing the sub-request.

@fabpot I remember from another issue that you didn't want to support anything else than strings inside the request's attribute (I guess the context was about filling defaults through the routing config). However, the `ParameterBag` is stating that the parameter values can be of any type. So for me this looks like we should merge it as a bugfix.

**Comment by Nek-** [comment]
@WhiteEagle88 thanks for contributing 🤗 . Could you target 2.7 instead of 3.2 ?

**Comment by dmytroboiko** [comment]
@Nek- Thanks. No problem

**Comment by WhiteEagle88** [comment]
I create new PR for this https://github.com/symfony/symfony/pull/22015

**Pull request closed without merging**
