### PR TITLE
[profiler][request toolbar] Removed route name from the toolbar

### PR DESCRIPTION
**Pull request by jbgomond**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14744 |
| License | MIT |
| Doc PR |  |

The action block takes nearly 1/3 of the bar width which is not good.
The controller + action names are useful but the route name less important.

Before
capture_before

After
capture_after

The route name is shown by hovering the action block
capture_tooltip

### CODE REVIEW

**Comment by fabpot** [comment]
:+1:

**Comment by romqin** [comment]
:+1:

**Comment by Tobion** [comment]
:+1:

**Comment by tadcka** [comment]
:+1:

**Comment by aitboudad** [comment]
:+1: we can remove `Controller` and `Action` word too ? see bellow how it's look
selection_014

**Comment by fabpot** [comment]
I'm against removing the Controller and Action suffixes as they are not required, just conventions people can follow.

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @MJBGO.

**Pull request merged**
