### PR TITLE
[Validator] add Indonesian translation

### PR DESCRIPTION
**Pull request by IndraGunawan**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | -
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Business Identifier Code (BIC) is not translate to Bahasa Indonesia because i cant found the formal translation.
i found http://www.bi.go.id/id/peraturan/sistem-pembayaran/Documents/se_173115.pdf page:24 Bank Identifier Code (BIC) is still in English.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍

**Comment by fabpot** [comment]
Thank you @IndraGunawan.

**Comment by IndraGunawan** [comment]
i saw that trans-unit 81 does not exists in branch 2.7

**Comment by fabpot** [comment]
@IndraGunawan Don't worry, we are merging all translations in the oldest branch to make it easier to manage them.

**Pull request closed without merging**
