### PR TITLE
[Console] Fix wrong exceptions thrown

### PR DESCRIPTION
**Pull request by JhonnyL**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by fabpot** [comment]
Isn't it for 2.8 instead?

**Comment by JhonnyL** [comment]
@fabpot Closing in favor of #18645

**Comment by OskarStark** [comment]
@JhonnyL i think it was just a question of @fabpot, because in this case he could merge this to the correct target branch automatically. You don't need to close and reopen another PR for symfony code in the future ;-)

**Comment by JhonnyL** [comment]
@OskarStark Good to know, thanks :)

**Pull request closed without merging**
