### PR TITLE
[FrameworkBundle] do not allow symfony/json-encoder 7.4 yet

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

The component is experimental. Claiming to be compatible with 7.4 could lead to having to change a stable 7.3 release of the FrameworkBundle if the JsonEncoder component introduced BC breaks in 7.4.

### CODE REVIEW

**Review by chalasr — APPROVED** [review]
Well done remembering of this 👍 ref https://github.com/symfony/symfony/pull/57630#issuecomment-2422346760

**Comment by stof** [comment]
Doing that only in a dev requirement does not fully solve the issue though, as it applies only to our CI.

**Review by mtarld — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Review by alexandre-daubois — APPROVED** [review]
Ah yes indeed, thanks!

**Comment by xabbuh** [comment]
@stof conflict rule added

**Review by alexandre-daubois — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
