### PR TITLE
synchronize 2.7 and 3.0 upgrade files

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16667 |
| License | MIT |
| Doc PR |  |

This is a first step into solving #16667 by checking also the entries from the `UPGRADE-2.7.md` file.

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1: Status: reviewed

**Comment by WouterJ** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
It would be useful to do the same for the `2.4`, `2.5`, and `2.6` upgrade files on this branch to, but we can do that in a separate PR if someone else wants to do it or if I do not find the time for it soon.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
