### PR TITLE
[Mailer] Be able to create a stream without TLS

### PR DESCRIPTION
**Pull request by aslangery**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | --
| License       | MIT

It was not possible to create a stream without TLS

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please add a test case? Thanks

**Comment by OskarStark** [comment]
Why not using `àWhy don't you using `smtps` as scheme instead? Can you explain?

**Comment by aslangery** [comment]
> Why not using `àWhy don't you using `smtps` as scheme instead? Can you explain?

Our client has an incorrectly configured mail server. On swiftmailer this did not cause problems, but when switching to symfonymailer the connection stopped working

**Comment by OskarStark** [comment]
I am not sure we want to work around wrong configured mail servers 🤔 

cc @fabpot

**Comment by aslangery** [comment]
> I am not sure we want to work around wrong configured mail servers 🤔
> 
> cc @fabpot

This isn't really a mistake. On servers you can configure an arbitrary port for smtp. Even 465, although it is the default for smtps

**Comment by nicolas-grekas** [comment]
This might break existing client that forgot to add the final "s" to their scheme so I'm not sure I would do it this way.
Instead, we could add a `tls` option - maybe by tweaking #53621
Closing for this reason, let's continue on the linked PR.

**Pull request closed without merging**
