### PR TITLE
[WIP] [Serializer] Allow deserializing `union` types properly

### LINKED ISSUE #45818: [Serializer] Deserializing Union types fails on first subtype deserialization fail
### Symfony version(s) affected

6.0.6

### Description

Deserializing Union types fails on first subtype deserialization fail.

My usecase:
I would like to create a field in a json object where the client can set `null`, `false` or a valid date time value, in order to differentiate between 3 states: deleted, unchanged, updated (to the datetime value).

### How to reproduce

`symfony/serializer` needed.

```PHP
class Test
{
    public null|bool|\DateTime $changed = false;
}

class ServiceWithAutoWiring {
    public function __construct(SerializerInterface $serializer)
    {
        $format = [DateTimeNormalizer::FORMAT_KEY => \DateTimeInterface::ISO8601];
        $a = $serializer->deserialize('{ "changed": null }',                        Test::class, 'json', $format); // OK
        $b = $serializer->deserialize('{ "changed": "2022-03-22T16:15:05+0000" }',  Test::class, 'json', $format); // OK
        $c = $serializer->deserialize('{ "changed": false }',                       Test::class, 'json', $format); // Fails with exception

    }
}
```

### Possible Solution

I think the proper solution would be to try to deserialize all the possible types from the union type, and if all fail, only then trait it as the deserialization failed. 

### Additional Context

I tried to reverse the order of the array returning from `\Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor::extractFromReflectionType` and it seems to solve the problem. (Which is a workaround, and not a proper fix)
This makes the `boolean` type checked before the `DateTime` and returns before the validation can fail on the parsing of date time.
That is why I think checking all possible outcomes before aborting deserialization would help.

A picture from the current values of the returning array (Not with the workaround):
image

### PR DESCRIPTION
**Pull request by T-bond**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #45818
| License       | MIT
| Doc PR        | -

I tried to implement the proper fix, that I mentioned in my issue.

### CODE REVIEW

**Comment by T-bond** [comment]
Self review done. All checks passed. PR was developed with TDD.
I have been using Symfony for 2 weeks only, so I hope I haven't missed anything.
This PR solves my problem mentioned in the issue.

Anyways, thanks for this great software!

Status: Reviewed

**Review by T-bond — COMMENTED** [review]
Self review done. All checks passed. PR was developed with TDD.
I have been using Symfony for 2 weeks only, so I hope I haven't missed anything.
This PR solves my problem mentioned in the issue.

Anyways, thanks for this great software!

Status: Reviewed

**Comment by nicolas-grekas** [comment]
I'm not sure about the patch. It'd make more sense to me to go with the following one.
Note that the issue exists on branch 5.4 so it's where it should be fixed.

<details>

```diff
--- a/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
+++ b/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php
@@ -479,14 +479,14 @@ abstract class AbstractObjectNormalizer extends AbstractNormalizer
                         } elseif ('true' === $data || '1' === $data) {
                             $data = true;
                         } else {
-                            throw NotNormalizableValueException::createForUnexpectedDataType(sprintf('The type of the "%s" attribute for class "%s" must be bool ("%s" given).', $attribute, $currentClass, $data), $data, [Type::BUILTIN_TYPE_BOOL], $context['deserialization_path'] ?? null);
+                            continue 2;
                         }
                         break;
                     case Type::BUILTIN_TYPE_INT:
                         if (ctype_digit($data) || '-' === $data[0] && ctype_digit(substr($data, 1))) {
                             $data = (int) $data;
                         } else {
-                            throw NotNormalizableValueException::createForUnexpectedDataType(sprintf('The type of the "%s" attribute for class "%s" must be int ("%s" given).', $attribute, $currentClass, $data), $data, [Type::BUILTIN_TYPE_INT], $context['deserialization_path'] ?? null);
+                            continue 2;
                         }
                         break;
                     case Type::BUILTIN_TYPE_FLOAT:
@@ -494,11 +494,11 @@ abstract class AbstractObjectNormalizer extends AbstractNormalizer
                             return (float) $data;
                         }
 
-                        return match ($data) {
-                            'NaN' => \NAN,
-                            'INF' => \INF,
-                            '-INF' => -\INF,
-                            default => throw NotNormalizableValueException::createForUnexpectedDataType(sprintf('The type of the "%s" attribute for class "%s" must be float ("%s" given).', $attribute, $currentClass, $data), $data, [Type::BUILTIN_TYPE_FLOAT], $context['deserialization_path'] ?? null),
+                        switch ($data) {
+                            case 'NaN': return \NAN;
+                            case 'INF': return \INF;
+                            case '-INF': return -\INF;
+                            default: continue 3;
                         };
                 }
             }
```

</details.

**Comment by T-bond** [comment]
> I'm not sure about the patch. It'd make more sense to me to go with the following one. 

I think this will not solve the problem, as the exception is thrown from the DateTime normalizer, which tries denormalize `false`. Also, this would change the current specialised message, if the type is not an union one.

Anyways, if you say, that this is the way to go forward, I will do it this way, and only apply the try-catch block to the other denormalizations, where the exception is thrown from somewhere else.

> Note that the issue exists on branch 5.4 so it's where it should be fixed.

Yeah, I forgot that you can use union types with docblock before php 8. I will rewrite to patch for the 5.4 branch, when we could determine the correct solution.

**Comment by nicolas-grekas** [comment]
> I think this will not solve the problem, as the exception is thrown from the DateTime normalizer

Hum indeed, then the issue should be fixed on 4.4, since apparently we don't handle union types there either.
Let's go with your approach.

Can you please rebase+retarget for 4.4?

**Pull request closed without merging**
