### PR TITLE
[HttpKernel] Embed the original exception as previous to bounced exceptions

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14073 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Should be merged on 2.3!

**Comment by stof** [comment]
Closure::bind does not work on 5.3

**Comment by iltar** [comment]
@stof Fair enough

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
