### PR TITLE
CS: Pre incrementation/decrementation should be used if possible

### PR DESCRIPTION
**Pull request by gharlan**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Fixes provided by new fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1113

If this pr is merged I would change the level of the fixer to `symfony`.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
NB, preincrementation is about 30% faster in most cases, and this pull is only changing those cases where the behaviour of the code is unchanged to using preincrementation.

:+1: from me. :)

**Comment by trq** [comment]
$i += $i is faster still if we really want to get into micro optimisations.

**Comment by gharlan** [comment]
@trq for me it is more important to standardize code style.

why is the build failing on PHP 5.3.3?

**Comment by stof** [comment]
@GrahamCampbell when you enable OPCache optimizations, it already optimizes the pre/post incrementation automatically AFAIK

**Comment by GrahamCampbell** [comment]
> when you enable OPCache optimizations, it already optimizes the pre/post incrementation automatically AFAIK

Nice. :)

**Comment by nicolas-grekas** [comment]
I think I'd be :-1: on this one. It's not a hard stand, but I also see no added value here (the perf is not relevant), and I see downsides (readability and making merges harder)

**Comment by keradus** [comment]
It is always good to write it same way in whole project.
:+1: for standarization

**Comment by GrahamCampbell** [comment]
@keradus What if we were to standardise postincrementation?

**Comment by keradus** [comment]
Only `++$i` or only `$i++` is fine with me.
But first one is faster - and not all envs has Zend's OPCache

**Comment by fabpot** [comment]
Thank you @gharlan.

**Comment by razbakov** [comment]
@gharlan 

Can you please also update documentation ([example](http://symfony.com/doc/current/components/expression_language/syntax.html#calling-methods)) and write an explicit rule in coding standards that pre-increment, pre-decrement is forced? Because `Place unary operators (!, --, ...) adjacent to the affected variable` doesn't define it.

**Comment by keradus** [comment]
wow, commenting a 2015 PR...

is you wish to, just send a PR for docs yourself, that would be the best you could do.

if not, there is always: http://symfony.com/doc/current/contributing/code/standards.html
> Imitate the existing Symfony code

**Pull request merged**
