### PR TITLE
[PropertyAccess] Add french singular for words like typologies > typologie

### PR DESCRIPTION
**Pull request by CaporalDead**
Hi,

We just encountered a problem while using 'by_reference' attribute as false in a form which caused a `NoSuchPropertyException` because the StringUtil class in PropertyAccess doesn't handle correctly the case when for example you have "Typologies" (plural) that should be translated into "Typologie" and not "Typology".

I just add this case and a test case which covered the word "typologies" and it seems that it doesn't break other test cases.

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13723 |
| License | MIT |
| Doc PR | [PropertyAccess] Add french singular for words like typologies > typologie |

### CODE REVIEW

**Comment by xabbuh** [comment]
I'm not sure if the `StringUtils` class was designed to work well with other languages than English. Or is "typologie" a French word that is frequently used in English and I am not aware of this fact?

**Comment by jrobeson** [comment]
it would be typology  -> typologies in english

**Comment by WouterJ** [comment]
I'm -1 when this is adding support for other languages than French. Supporting plain English pluralization/singularization is already hard enough, adding support for even more languages makes it impossible.

Anyway, thank you for taking the time to fill in a bug report and create a PR (including PR template)!

**Comment by javiereguiluz** [comment]
@WouterJ what do you think about removing this "pluralization black-magic" even for English. What's the problem of writing some methods using bad English grammar in exchange of having zero problems, zero magic and a nice performance bump?

**Comment by WouterJ** [comment]
There is no magic, just plain english rules.

**Comment by javiereguiluz** [comment]
@WouterJ anything related to languages created by humans is magic, because they are as irregular as they can get. By the way, the "magic pluralizator" used by Symfony (and used too by other frameworks) may be lacking some irregular plurals found on this list: http://en.wikipedia.org/wiki/English_plurals#Irregular_plurals

**Comment by fabpot** [comment]
Closing as we only support English here. Actually, I think that using French (or any other language) in method names is a big mistake as it makes reading the code really strange and messy.

@javiereguiluz I agree with you and I was against adding such a thing in Symfony, but well, we need to support it now.

**Comment by webda2l** [comment]
Remove this difficult magic in 3.0 will be appreciate.

**Comment by WouterJ** [comment]
@webda2l and then not support pluralization? I'm afraid that'll break too much code...

**Comment by stof** [comment]
@WouterJ the issue is that using ``addMembers`` and ``removeMembers`` to add or remove a single member (if we don't singularize the property name) would mean that the PropertyAccess component forces you to define methods with broken names for adders and removers. This is the reason why we have this logic in place

**Comment by webda2l** [comment]
Yes recurrent debate https://github.com/symfony/symfony/issues/9205 https://github.com/symfony/symfony/issues/5013

When magic doesn't work well, and PRs likes https://github.com/symfony/symfony/pull/13618 and https://github.com/symfony/symfony/pull/13714 are needed, facts that broken names for adders/removers are less important in my mind...

Or maybe find alternative to add/remove naming that broke less name, plus/minus? ...
Or if someone know better alternative with other frameworks.

**Comment by CaporalDead** [comment]
Thanks for replying, still I think that there should be a way to tell to doctrine to use another translator. 

@fabpot I understand the fact that it should handle everything or nothing or a way to tell to symfony to use a specific getter/setter maybe. Using english can be very usefull sometimes but when you work with a french customer that have specific words related to his business, translate them can be confusing for your team or for him.

We'll stick with our fork for the moment until 2.7 is released.

Thanks all.

**Comment by WouterJ** [comment]
I think we should add support like proposed in this PR (but then reverted before merging): https://github.com/symfony/symfony/issues/5013

**Pull request closed without merging**
