### PR TITLE
 check empty_data in choices of ChoiceType

### PR DESCRIPTION
**Pull request by peter-gribanov**
| Q             | A
| ------------- | ---
| Branch?       | bug fixes 
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #25896
| License       | MIT

If `empty_data` is callable, search it in choices. May be it is not a really callable data.

I don't exclude the probability of violation of BC.

### CODE REVIEW

**Comment by Simperfit** [comment]
If it's a BC break then you should deprecate the behaviour for 4.1 and then do it for 5.0.

**Comment by xabbuh** [comment]
As written in the referenced ticket you could deprecate the ability for a string to be handled as a callable (you can take a look at the `3.4` branch were we followed this approach for another option). However, the behaviour must not be changed here as that would be a BC break (in your own code you can use an anonymous function which just returns the string as a workaround).

**Comment by xabbuh** [comment]
We know that Symfony 5.0 will be released in November 2019. And if we deprecate something in 4.1 to 4.4, we also know that we will remove this feature in 5.0.

I think we are talking about different things when talking about the deprecation. I do not want to deprecate the ability to use a callable entirely. What we should deprecate IMO is the possibility to pass a callable as a string as this can be ambiguous as you said. So in the future, if you want to make use of a callable, you would need to use an anonymous function.

**Comment by peter-gribanov** [comment]
@xabbuh apparently i did not understand you.
You propose to mark use of handlers as a scalar value as deprecate, but to leave it possible to use anonymous function?

**Comment by xabbuh** [comment]
Exactly, you may want to take a look at #18020 where we did something similar in the past.

**Pull request closed without merging**
