### PR TITLE
[Translation] Fix message key handling for the Localise provider

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Branch?       | 5.3 and above
| Bug fix?      | yes
| New feature?  |no 
| Deprecations? |no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | -

Fixed non-recursively merging existing keys and created. Now created keys totally removed by usual merge.
Handled situation when no keys are created in localise service.

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you for the bugfix, can you please add a testcase to avoid further regressions?

cc @welcoMattic

**Review by welcoMattic — APPROVED** [review]
It miss tests, but for me it looks good

**Review by MikeDevresse — APPROVED** [review]

**Comment by xepozz** [comment]
Done

**Comment by OskarStark** [comment]
@welcoMattic can you please review/test again? Thanks

**Comment by derrabus** [comment]
Since the PR title will appear in the ChangeLog of the next release: Can we please find a better one? The current title does not tell me what aspect of the provider needs fixing.

**Comment by xepozz** [comment]
How can I help you? 
I really need this fix. Can we speed up please?

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xepozz.

**Pull request closed without merging**
