### PR TITLE
[Filesystem] Ensure correct paths in FileSystemTest

### PR DESCRIPTION
**Pull request by IchHabRecht**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by Tobion** [comment]
Please follow contribution guidelines: http://symfony.com/doc/current/contributing/code/patches.html

**Comment by Tobion** [comment]
Closing as it does not fix anything. Those tests are passing anyway as you can see on appveyor.

**Comment by IchHabRecht** [comment]
Sorry for wasting your time. Thought on improving your code by cleaning it up. If you're not interested, it's fine with me. But those tests only pass by the kindness of filesystems as you definitely creating wrong paths with double slashes.

**Comment by Tobion** [comment]
I didn't see any double slashes. It's helpful to actually add a description to your PR. Otherwise reviewers have to guess based on the code what and why you are doing this.

**Comment by xabbuh** [comment]
What do you mean with double slashes?

**Comment by IchHabRecht** [comment]
Most of the paths in the variables are already absolute ons with trailing slashes. But while contacting them with static ones, other hardcorded forward slashes were used. This leads to double slashes in the paths. Will provide a new pull request and have a look at the mentioned guide for commit message.

**Comment by xabbuh** [comment]
Oh okay, I think understand what you mean. Though I suggest to only remove useless slashes but keep them everywhere else (PHP on Windows should handle forward slashes quite well IIRC).

**Comment by IchHabRecht** [comment]
I copied the commit table and added the component to the commit message according to the guidelines. Can anyone help and tell me, why the test is still failing?

**Comment by jakzal** [comment]
@IchHabRecht the "commit table" should be put into the PR's description, not the commit

**Comment by IchHabRecht** [comment]
Yeah! Thanks for that hint!

**Comment by xabbuh** [comment]
Can you please revert the `/` with `DIRECTORY_SEPARATOR` replacements though?

Status: Needs work

**Comment by IchHabRecht** [comment]
Hi xabbuh. Don't get your point. I converted all hard-coded slashes with DIRECTORY_SEPARATOR already?!

**Comment by jakzal** [comment]
@IchHabRecht that's the change that should be reverted. There's only few cases that DIRECTORY_SEPARATOR is really needed. Otherwise PHP handles '/' perfectly fine, even on windows. We simply use '/' in Symfony.

**Comment by fabpot** [comment]
Indeed, we try to avoid using `DIRECTORY_SEPARATOR` when it's not strictly needed as the code is much easier to read when using just `/` everywhere.

**Comment by nicolas-grekas** [comment]
Closing: Windows (and Linux) is perfectly fine with forward and doubled slashes here. Adding DIRECTORY_SEPARATOR complicates reading.

**Pull request closed without merging**
