### PR TITLE
[Validator] property constraints can be added in child classes

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21538, #21567
| License       | MIT
| Doc PR        | 

This reverts the changes done in #21053 (and applies the test written by @angelk in #21538). I think trying to "fix" #15950 with the changes from #21053 was a mistake. Child classes should be able to refine validation constraints (I basically agree with @ro0NL's reasoning in https://github.com/symfony/symfony/issues/21567#issuecomment-278729990.

### CODE REVIEW

**Comment by fabpot** [comment]
Looks like tests are broken.

**Comment by xabbuh** [comment]
tests fixed

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by ro0NL** [comment]
@xabbuh this reopens #15950 right?

**Comment by xabbuh** [comment]
@ro0NL Indeed, thanks for the reminder.

**Pull request merged**
