### PR TITLE
[PropertyInfo] added property list extractor by priority

### PR DESCRIPTION
**Pull request by andrey1s**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

### CODE REVIEW

**Comment by dunglas** [comment]
Can you give more information about your use case?

**Comment by andrey1s** [comment]
I expect to get all the properties, but I can only get by priority extractor. Now I can define `MergeExtractor` (this PR in plans) and get properties all extractors.

**Comment by dunglas** [comment]
What's the difference with the native behavior of the `PropertyExtractor` class? https://github.com/symfony/symfony/blob/master/src/Symfony/Component/PropertyInfo/PropertyInfoExtractor.php#L97

**Comment by andrey1s** [comment]
can't use multiple sources, only the first successful. how about merge data from multiple sources?

**Comment by fabpot** [comment]
Closing as there is no more activity here. @andrey1s  Feel to reopen if you want to finish it.

**Pull request closed without merging**
