### PR TITLE
[Routing][Serializer] Add possible missing imports of NamedArgumentConstructor

### PR DESCRIPTION
**Pull request by michaljusiega**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | ~
| License       | MIT
| Doc PR        | 

Hi.
This PR fixes possible missing imports of NamedArgumentConstructor (etc. added in https://github.com/symfony/symfony/pull/40266).

The main reason for this pull request and apply this changes is error caused by JMSSerializer as below:

```
Luxmed\Intranet\Exceptions\JMSSerializerException : [Semantical Error] The annotation "@NamedArgumentConstructor" in class Symfony\Component\Routing\Annotation\Route was never imported. Did you maybe forget to add a "use" statement for this annotation?
 /var/www/intranet/src/Service/JMSSerializerService.php:136
 /var/www/intranet/tests/DTO/SearchAnnotationDTOTest.php:197
 
 Caused by
 Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@NamedArgumentConstructor" in class Symfony\Component\Routing\Annotation\Route was never imported. Did you maybe forget to add a "use" statement for this annotation?
 
 /var/www/intranet/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:39
 /var/www/intranet/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:803
 /var/www/intranet/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:719
 /var/www/intranet/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:376
 /var/www/intranet/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php:146
 /var/www/intranet/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php:64
 /var/www/intranet/vendor/jms/serializer/src/Metadata/Driver/AnnotationDriver.php:92
 /var/www/intranet/vendor/jms/metadata/src/Driver/DriverChain.php:32
 /var/www/intranet/vendor/jms/serializer/src/Metadata/Driver/TypedPropertiesDriver.php:63
 /var/www/intranet/vendor/jms/metadata/src/MetadataFactory.php:111
 /var/www/intranet/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php:218
 /var/www/intranet/vendor/jms/serializer/src/JsonSerializationVisitor.php:137
 /var/www/intranet/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php:260
 /var/www/intranet/vendor/jms/serializer/src/Serializer.php:252
 /var/www/intranet/vendor/jms/serializer/src/Serializer.php:163
 /var/www/intranet/src/Service/JMSSerializerService.php:134
 /var/www/intranet/tests/DTO/SearchAnnotationDTOTest.php:197
```

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
We don't need to import core annotations. The current code is correct.

**Comment by michaljusiega** [comment]
> 
> 
> We don't need to import core annotations. The current code is correct.

So what should I do to avoid this issue ? :)

**Comment by derrabus** [comment]
What version of Doctrine Annotations do you use? Can you maybe create a reproducer so I can analyze the problem?

**Comment by michaljusiega** [comment]
```
composer show
...
doctrine/annotations                 1.13.1    Docblock Annotations Parser
...
```

I will try to create testcase / reproducer after my work :)

**Comment by michaljusiega** [comment]
@derrabus I added test case for `Route` annotation.

**Comment by michaljusiega** [comment]
@derrabus - friendly ping ;)

**Comment by derrabus** [comment]
Sorry, I‘m on vacation at the moment and did not have time to investigate further. I hope that I can get back to you by the end of the week.

**Comment by derrabus** [comment]
Sorry for the delay. I don't really understand why you (or JMS serializer) would want to parse the annotations on an annotation class. That being said, importing that annotation should not be necessary because it's not necessary for the other core annotations.

See doctrine/annotations#419

**Review by derrabus — CHANGES_REQUESTED** [review]
Sorry for the delay. I don't really understand why you (or JMS serializer) would want to parse the annotations on an annotation class. That being said, importing that annotation should not be necessary because it's not necessary for the other core annotations.

See doctrine/annotations#419

**Comment by derrabus** [comment]
Closing in favor of doctrine/annotations#419.

**Comment by michaljusiega** [comment]
Thank you @derrabus

**Pull request closed without merging**
