### PR TITLE
[Process] Stopped Autoruns when shelling on windows

### PR DESCRIPTION
**Pull request by rquadling**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? |  |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Stop autoruns when shelling on Windows.

Original PR was on https://github.com/symfony/Process/pull/9#issuecomment-140721398.

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by Tobion** [comment]
:+1: 
Status: Reviewed

**Comment by rquadling** [comment]
OOI, it was suggested to make this PR against the 2.3 branch. Should it be for an earlier release? Fixing the first branch with the issue?

**Comment by rquadling** [comment]
And if it is merged into 2.3, how does it get into the rest of the branches?

**Comment by stof** [comment]
@rquadling we merge 2.3 into 2.7 (and then 2.7 into 2.8 and 2.8 into master) on a regular basis (approximately once a week, and we ensure it is done before any release)

**Comment by stof** [comment]
however, this change should apply cleanly on the 2.3 branch, so you don't need to recreate the PR. Our merging tool will be able to rebase the PR on top of the 2.3 branch instead.

**Comment by Tobion** [comment]
Thank you @rquadling.

**Pull request merged**
