### PR TITLE
[Translation] Fix coding standard in CsvFileLoader

### PR DESCRIPTION
**Pull request by tifabien**
| Q | A |
| --- | --- |
| Branch | 2.8 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@tifabien thanks for this improvement. It's true that it's recommended to put  `public` methods first.

The problem for us is that this change has to be merged in all the higher branches (3.0 and master in this case). This causes conflicts when merging and it's very time-consuming for our maintainers. That's why these changes are routinely rejected ... but let's wait to see what happens with your proposal. Thanks!

**Comment by tifabien** [comment]
Hi @javiereguiluz !
I fully understand all these merge conflicts problems for these kind of modifications.

If this change is rejected for 2.8 branch, would it be better if we put this change in master branch?

**Comment by fabpot** [comment]
Doing it in master would lead to the same problem unfortunately. Closing it now.

**Comment by tifabien** [comment]
Ok Understood :) 
Thanks !

**Pull request closed without merging**
