### PR TITLE
[Translation] [FrameworkBundle] Translation: Optimized loading (lazy loading) of domains

### PR DESCRIPTION
**Pull request by pulzarraider**
Bug fix: no
Feature addition: yes
Backwards compatibility break: no
Symfony2 tests pass: yes (tests updated)
Fixes the following tickets: -

Website can have hundreds of messages in each domain. Some domains (and their translations) are not used during different requests (for example "admin" domain and their messages will not be used on public pages, "validation" domain will not be used until validating some entities/processing forms). This PR changes the way how messages are cached. Instead of storing all domains in one file (catalogue.en.php), domains are saved separately (/en/messages.php, /en/validators.php, etc.) and they are processing and loaded into memory only when they are required (to translate some text). This will optimize memory usage.

### CODE REVIEW

**Comment by stof** [comment]
ping again @pulzarraider

**Comment by pulzarraider** [comment]
I will continue working on this PR next week.

**Comment by Rvanlaak** [comment]
A configurable threshold for merging smaller domains together would be great.

**Comment by JHGitty** [comment]
ping @pulzarraider

**Comment by nicolas-grekas** [comment]
@aitboudad what do you think of this one?

**Comment by nicolas-grekas** [comment]
OK you're on it, I just read the linked PR :)

**Comment by fabpot** [comment]
Closing

**Pull request closed without merging**
