### PR TITLE
[HttpKernel] Set configurable hidden parameters request in profiler

### PR DESCRIPTION
**Pull request by goabonga**
[HttpKernel] Set configurable hidden parameters request in profiler

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #12981 |
| License | MIT |

to complete the pull request #12981.

### CODE REVIEW

**Comment by Nek-** [comment]
:+1: this really need its own documentation page.

**Comment by javiereguiluz** [comment]
While redesigning the profiler, I stumbled upon this "feature" and I thought: does it really make sense to hide these params?

  * 99.99% of the times you use the profiler in your own computer while developing the app. You are probably the only one looking at your computer and besides, you are probably using a fake password (for a fixtures user).
  * In the ultra-rare ocasion when you use the profiler in production to hunt a hard-to-debug problem, you may actually want to see all the parameters (imagine that the problem occurs precisely in one of the masked parameters).

But I guess this opinion is not very popular in the community.

**Comment by goabonga** [comment]
@javiereguiluz  yeah ... but that's not rare for me (and some bots) to visit some website who expose app_dev.php page in prod, and passwords.

**Comment by fabpot** [comment]
I agree with @javiereguiluz here. The profiler should never be enabled in production. If someone has access to it, he can gather a lot of useful and sensitive information besides the passwords. We should not make people think it's safe with such features.

**Comment by Nek-** [comment]
@fabpot @javiereguiluz 

Why not testing the fact with a bot that check Sf websites (something like 100 sf websites) each 5 seconds to see if the app_dev.php file is available and if the password is in logs ? I'm pretty sure the result will convince you...

**Comment by fabpot** [comment]
I'm not saying that this does not happen. I'm just saying that we should focus on educating people to not do that as even with your proposal, those apps are at risk. There are some **major** security issues with the profiler when deployed in production that we **cannot** fix as the purpose of the profiler is to help debug applications. So, just removing passwords is just a tiny bandaid on a much larger problem.

**Comment by fabpot** [comment]
By the way, are you sure that people who deploy the profiler in production or there dev frontend controller in prod will configure the hidden parameters? I bet they won't.

**Comment by Nek-** [comment]
@fabpot at least not removing the hidding of password makes sense. IMO this new feature is not so useful as it's not configurable. But maybe if you add a new config inside the framework bundle people are going to be more careful on what they do.

Btw I totally agree with the fact of "educate" people on security issues is more important. But I think it's important to provide more security features than necessary in a *normal* usage.

There is another solution, maybe you'll like it more: hidding the request inside the logs of the profiler.

I insist on this point because many websites were vulnerable on this problem (before the patch in 2.6) and many are still vulnerable because they changed the default config of the security component.

**Comment by iltar** [comment]
I already stated a while ago this should be configurable in my opinion, whether the intention is to not be exposed or not. Either the whole masking should go or it should be configurable if you ask me.

**Comment by sstok** [comment]
If you are exposing the profiler in production you'd properly have a bigger problem then showing the password in a profiler. Assuming you have configured the database access credentials with ENV you can simple get these with `_profiler/phpinfo`.

**Comment by fabpot** [comment]
Closing as making such a feature configurable does not help. I even tend to agree with @iltar that even masking _password should be removed. Exposing the web profiler in production is really opening so many security holes that trying to fix them is a lost battle.

**Comment by goabonga** [comment]
@fabpot .... ok thats so cool, to let me keep an eye on your !

**Pull request closed without merging**
