### PR TITLE
make test case classes compatible with PHPUnit 10+

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by GromNaN — COMMENTED** [review]
Is it necessary to add stubs to the bridge to resolve the missing class errors reported by psalm?

**Comment by xabbuh** [comment]
I think we can ignore them.

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
Currently we install PHPUnit 9.6 in our Psalm CI job. We might as well just bump that version.

**Review by OskarStark — APPROVED** [review]
👏

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
