### PR TITLE
[HttpKernel] Unit test incorrect behavior of ResponseCacheStrategy

### PR DESCRIPTION
**Pull request by aschempp**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | #26532
| License       | MIT
| Doc PR        | ~

This PR only contains failing unit tests to show the incorrect behavior of `ResponseCacheStrategy`. I'm sure we can come up with plenty more ideas for tests, but let me know if this approach makes sense.

It is not meant to be merged as-is. The branch is to be merged into #26532 to show the refactoring fixes these issues. 

#SymfonyConHackday2018

/cc @stof @nicolas-grekas @dbu

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
(please rebase+retarget 3.4 if that's where this should be merged.)

**Comment by nicolas-grekas** [comment]
If this is not intended to be merged, we should close then, isn't it?

**Comment by dbu** [comment]
@aschempp i suggest you close this merge request and add the tests in #26532 - from the fixing merge request, you can still reference the closed merge request which should show the failing tests on travis-ci

**Comment by aschempp** [comment]
Fine with me. The tests are already added in #26532

**Pull request closed without merging**
