### PR TITLE
[PropertyAccess] Fix dynamic property accessing.

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Fix a bug regarding dynamic properties access introduced by #16294.

### CODE REVIEW

**Comment by stof** [comment]
please add a test covering this

**Comment by dunglas** [comment]
@stof some tests exist in 2.7 (it's how I've found I've broke things). I'll backport them ASAP but I've opened this PR right now because 2.3 is currently buggy.

**Comment by stof** [comment]
well, this PR is the one where backporting makes sense, as the backport is adding the test preventing this regression

**Comment by dunglas** [comment]
Test added

**Comment by dunglas** [comment]
AppVeyor failures look unrelated.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request merged**
