### PR TITLE
[FrameworkBundle] Prevent an error when the console component isn't installed

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21246
| License       | MIT
| Doc PR        |n/a

Finish #19443. Alternative to #21246.

### CODE REVIEW

**Comment by stof** [comment]
you need to add the conflict rule too. Otherwise, we could end up in a case where we have framework-bundle 3.3 with console 2.2, where a BC break would happen: existing console commands would not be registered anymore

**Comment by dunglas** [comment]
@stof the conflict is already present: https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/composer.json#L60

**Comment by dunglas** [comment]
(AppVeyor error unrelated, Travis should become green after the merge)

**Comment by stof** [comment]
then 👍

**Comment by xabbuh** [comment]
👍

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request merged**
