### PR TITLE
[Security] Do not save the target path in the session for a stateless firewall

### PR DESCRIPTION
**Pull request by lyrixx**
| Q | A |
| --- | --- |
| Bug fix? | partially |
| New feature? | partially |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | - |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Note: I think this PR can be merged into 2.3 because it's like a bug fix

### CODE REVIEW

**Comment by jderusse** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
:+1: for 2.3?

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
I'm not sure about this one, the target URL is only store when there is an existing session, in which case the app is already not stateless anymore.

**Comment by lyrixx** [comment]
Yes and no:

* The session listener is [configured globally](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/EventListener/SessionListener.php#L36-L40t) for an application ([and not for a subpath](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L81-L84))
* The session listener will "just" test if there is a [session object in the DIC](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/EventListener/SessionListener.php#L36-L40). If so it injects [the session object in the request](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/EventListener/SessionListener.php#L25-L38).

So at this point, an application may not have used the session yet
So you can still have a session empty and so a stateless application.

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request closed without merging**
