### PR TITLE
[Yaml] Deprecate using the object and const tag without a value

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | https://github.com/symfony/symfony/pull/35332#discussion_r366757204
| License       | MIT
| Doc PR        | -

WIP because it needs 3.4 merged up into master + https://github.com/symfony/symfony/pull/35332.

### CODE REVIEW

**Comment by OskarStark** [comment]
Do we really deprecate it in 3.4 AND 4.3,4.4?

**Comment by fancyweb** [comment]
@OskarStark We deprecate it on master (5.1). We can't deprecate anything on lower versions. What I meant is that I pushed some code here on master that is already on 3.4 (because 3.4 is not yet fully merged into master). This code is unrelated.

**Comment by OskarStark** [comment]
> @OskarStark We deprecate it on master (5.1). We can't deprecate anything on lower versions. What I meant is that I pushed some code here on master that is already on 3.4 (because 3.4 is not yet fully merged into master). This code is unrelated.

Thanks for the clarification 👍

**Comment by fancyweb** [comment]
This one is now ready for review 😃

**Review by fabpot — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @fancyweb.

**Pull request merged**
