### PR TITLE
DX: replace @link with @see annotation

### PR DESCRIPTION
**Pull request by keradus**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | n/a
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Just to standardise.

```console
λ grep -r "* @see " src | wc -l
    360

λ grep -r "* @link " src | wc -l
     12
```

### CODE REVIEW

**Review by linaori — APPROVED** [review]
Did you check if 2.8, 3.1 or 3.2 have added any new `@link`s? I don't think so but would be nice to verify.

Status: reviewed

**Comment by keradus** [comment]
Nope. As with all other CS fixes, it should be applied to lowest supported branch and then, after having it marge to successors, could be rerun on following branches.

**Comment by fabpot** [comment]
Thank you @keradus.

**Comment by fabpot** [comment]
hmm, I've merged this one but not sure it was a good idea. @link is used a lot inside some phpdocs.

**Pull request merged**
