### PR TITLE
[TwigBundle] fixed template root path

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | see #20285
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍 

Status: reviewed

**Comment by iltar** [comment]
This is not fool proof though, what about an approach such as here?
https://github.com/hostnet/path-composer-plugin-lib

**Comment by fabpot** [comment]
@iltar Can you explain in which circumstances it would not work?

**Comment by iltar** [comment]
If I understand this PR correctly, it will traverse down until it find a `composer.json` (based on the kernel root). What if my composer.json is in (e.g.) `%kernel.root_dir%/.composer` or my kernel is shared between repositories and installed globally? Edge, case would be a weird situation but not impossible, possible not probable. With `--working-dir`, you can have composer in any location of your system, it doesn't have to be in your repository.

There are just some cases that make this a bit difficult to ensure this would work.

**Comment by nicolas-grekas** [comment]
I suggest using the common prefix between the vendor dir and the kernel.root_dir, as done in 
https://github.com/symfony/symfony/blob/b376d92320aa12778a35c04437e1cf16fbf31450/src/Symfony/Bundle/WebProfilerBundle/DependencyInjection/WebProfilerExtension.php#L56-L66

**Comment by fabpot** [comment]
@nicolas-grekas I prefer my strategy. Storing the `composer.json` (which should be in your repository) elsewhere than the root directory is I think not something we need to support (and a nightmare for anyone doing this). But the `vendor` directory can be anywhere (there is even a configuration for that in `composer.json`: `vendor-dir`). As the `vendor` should not be in your repo, and because this is just a read-only artifact, I can easily see people storing that somewhere else.

@iltar I don't want to support the edge cases you mention, they are non standard and I don't see why it would be a good idea in the first place. Supporting bad practices is not a goal.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by Tobion** [comment]
👍

**Comment by pounard** [comment]
This causes problems as soon as you are a bit paranoid with open_basedir or deliver a project without the composer.json file: #22149

**Pull request merged**
