### PR TITLE
[Routing] Changed Route vars to protected

### PR DESCRIPTION
**Pull request by ragboyjr**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | none |
| License | MIT |
| Doc PR | N/A |

Updated all of the route variables to be protected in order to allow useful extension of Route class. This is related to silexphp/silex#149. We'd need this merged in before we can properly extend and update the Route class.

Also, I'm not 100% sure 2.8 is the best branch for this, but I know silex (recently) uses a min version of 2.8 for Symfony

Signed-off-by: RJ Garcia rj@bighead.net

### CODE REVIEW

**Comment by Ener-Getick** [comment]
Features are merged in ``master``.

**Comment by ragboyjr** [comment]
@Ener-Getick Well, I'm not even sure it's a feature. I just put yes because I didn't want to say no for all of them.

**Comment by Ener-Getick** [comment]
And I think it would be better to add an optional parameter ``$trim`` to ``setPath`` instead as changing the visibility of this properties means a lot of BC to support then.

**Comment by ragboyjr** [comment]
Interesting about the BC support, I didn't consider that. Could you explain why making them protected affects the BC?

Ok, I can change to master, however, if this merge isn't on 2.8, then it wouldn't work to well for silex. My goal for this PR is to fix this issue in silex. So if we could come up with a way to do that, that'd be great.

**Comment by GromNaN** [comment]
@Ener-Getick There is [no BC break](http://symfony.com/doc/current/contributing/code/bc.html) at changing from private to protected.
But this change looks like monkey patching and is a broken solution for the issue. It open a hole for hacking into the Route class.

**Comment by stof** [comment]
> @Ener-Getick There is no BC break at changing from private to protected.

but it then forces us to maintain BC on any protected property, which is a much bigger maintenance task (BC on protected stuff is the harder stuff btw).

So for sure, this will not be accepted in 2.8 or 3.0. And it cannot be accepted in master without a valid use case for which the core team thinks that inheritance is the right way to handle it (hint: most of the time, it is not the case)

**Comment by Ener-Getick** [comment]
@GromNaN I didn't mean a BC break, I meant we won't be able to remove this parameters or change their name for example.
Anyway, I don't think that's the solution for the initial issue.

**Comment by stof** [comment]
to be clear, I'm putting a :-1: vote on this PR in its current state

**Comment by ragboyjr** [comment]
Ah, ok @Ener-Getick I understand what you are saying. Adding a parameter would be a better solution. However, that *would* be a feature, but I guess that feature *could* be merged in 2.8 right?

**Comment by Ener-Getick** [comment]
@ragboyjr old branches only accept bug fixes

**Comment by ragboyjr** [comment]
True True, it'd have to be a patch for it to be in 2.8...

**Comment by ragboyjr** [comment]
Let me close this and try again.

**Pull request closed without merging**
