### PR TITLE
[HttpClient][FrameworkBundle] Allow to configure Http Client transport

### PR DESCRIPTION
**Pull request by Koc**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Provide new configuration node `transport` with possible values: `auto`, `curl`, `native`, `mock`. Would be useful in test env to replace all http clients with mock implementation.

Tests in progress.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Can you hint us more about how this is useful? Providing a mock won't really help out of the box so some pieces are missing, how do you do this? (the answer should be useful for the doc too.)

#30661 will have some interaction with this I suppose.

**Comment by Koc** [comment]
I plan to merge configuration as the 1st step and after merging it make mocking http client mutable and implement resettable interface, create some assertion trait.

**Comment by Nyholm** [comment]
Im on the fence with this PR. 

Using the HttpClient in non-test, then it generally does not matter if I get the NativeClient or the CurlClient. (In the rare instances it actually matters, I define the service myself.)

Whenever I write tests with the HttpClient, I just define a service in my test environment. It is easier since I've got more control how I actually mock things. 

So Im not sure this will actually be an improvement.

**Comment by fabpot** [comment]
Closing as this PR is stale and two core team members are not convinced. Thanks for proposing.

**Pull request closed without merging**
