### PR TITLE
[2.7][Form] Added choice_label_attr option to choice type

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14404 |
| License | MIT |
| Doc PR | ? |
- extend new choice_attr option to labels for radio buttons and
  checkboxes when choice field type is expanded.
- accepts same arguments as choice_attr : string, array, callable and
  null by default

### CODE REVIEW

**Comment by Tobion** [comment]
BC break: yes since it changes an interface

**Comment by HeahDude** [comment]
OK, I thought it was already done by 03efce1b568379eac21d880e427090e43035f505 concerning 2.7

**Comment by webmozart** [comment]
The reason this breaks an interface is that we can only merge this into 2.8, since 2.7 is already feature frozen.

Is this really needed? Can you explain your use case?

**Comment by HeahDude** [comment]
@webmozart Thanks for your reply.

I don't know if it's "really" needed since it should be discussed IMO.
I originally used a trick while testing great form's change you've made, on 2.7 on a project of mine (4156b24ef4a12bbd55fa98947ed83d2609cadc7a).

as Tobion suggested in #14404, this pull request is a proper way to settle it.

Concerning  use case, I had a form with many option types on a project (no bootstrap theming), and with for custom css class I had to put some conditions in twig files while fetching `form` in loops to handle fields by group (another way is to do it is to override form blocks).

A fiew `label_attr` options in the `form builder` did the job and save a lot of times.
It seems to be a natural way for me to use it aside `choice_attr` with fine theming for choice options as the form builder is almost inescapable.

What do you think ? Again thanks for your time.

**Comment by webmozart** [comment]
Ok. Could you please rebase this on 2.8 and rename all `$label_attr` variables to `$labelAttr`? The current naming violates Symfony's naming conventions.

**Comment by HeahDude** [comment]
@webmozart Sorry just got your message. It should be done by the end of the week.

**Comment by jakzal** [comment]
ping @HeahDude :)

**Comment by HeahDude** [comment]
Closing in favor of #15447

**Pull request closed without merging**
