### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by dosten**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |

Happy new year! :tada:

### CODE REVIEW

**Comment by dosten** [comment]
ping @Tobion

**Comment by mvrhov** [comment]
Why don't we remove the year from the copyright. Updating this every year is annoying, and makes unnecessary changes into all files.

**Comment by jrobeson** [comment]
because copyrights expire. however, if a file hasn't even been updated, then the copyright probably shouldn't be touched.

**Comment by dosten** [comment]
@mvrhov maybe this can help http://programmers.stackexchange.com/a/210491

**Comment by hhamon** [comment]
This should be done against `2.7` and `2.8` branches I guess.

**Comment by dosten** [comment]
@hhamon see https://github.com/symfony/symfony/pull/17240#issuecomment-168316353

**Comment by fabpot** [comment]
Thank you @dosten.

**Pull request merged**
