### PR TITLE
[Routing] Fix "config-file-relative" annotation loader resources

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | slight behavior change
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

By using the locator in its `supports()` method, the `AnnotationDirectoryLoader` breaks config-relative annotation resources. The workaround is to fallback on `kernel.root_dir`-relative paths, as done in https://github.com/symfony/recipes/blob/master/doctrine/annotations/1.0/config/routes/annotations.yaml
But as you can see, this is rather WTF: extra knowledge is required to know what to type there. All the other loader look relatively to the config file first.

This is a bug, but since this is a slight behavior change, I think it's best to merge it on 3.4.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/recipes/pull/272 for a corresponding recipe (verified locally.)

**Comment by nicolas-grekas** [comment]
Note that it would be great to deprecate using the loader at all in `supports()`, but 3.4 is now closed for deprecations, so should/could happen on master only.

**Review by dunglas — APPROVED** [review]

**Comment by sroze** [comment]
Can you add some tests for that?

**Comment by fabpot** [comment]
This one makes is difficult (read impossible) to have a config that works on 3.3 and 3.4/4.0 (cf. the changed recipe).

**Comment by nicolas-grekas** [comment]
The current config that works will continue to work. I'm now rebasing on 3.3 as bug fix, so that Flex+3.3 can get the good DX config.

**Comment by nicolas-grekas** [comment]
rebased on 3.3

**Review by fabpot — APPROVED** [review]

**Comment by sroze** [comment]
And we even have tests now 👍

**Comment by nicolas-grekas** [comment]
Thank you @sroze.

**Pull request merged**
