### PR TITLE
[Serializer] Pass the serializer context to PropertyTypeExtractorInterface

### PR DESCRIPTION
**Pull request by dunglas**
…rface

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #25807 
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
didn't we merge something similar as bug fix recently?

**Comment by nicolas-grekas** [comment]
In #26043 actually

**Comment by dunglas** [comment]
It's not the same. In this one the idea is to give access to the serializer context in the PropertyInfo component.

**Comment by nicolas-grekas** [comment]
Ok :) what about adding a test case?

**Comment by dunglas** [comment]
bof 😋 (i'll add it)

**Comment by GuilhemN** [comment]
If we don't have an actual use case, i'd rather not do this since it makes caching much harder (values of circular reference fields are dynamic, aren't they?). I think it was already rejected in the past because of this.

**Comment by dunglas** [comment]
Indeed it's bad in term of cache.

**Pull request closed without merging**
