### PR TITLE
Move licenses according to new best practices

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | n/a |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by Tobion** [comment]
:+1:

**Comment by stof** [comment]
:+1: 

This should also be done in the 2.7 branch for DebugBundle

**Comment by xabbuh** [comment]
:+1:

**Comment by xabbuh** [comment]
Thank you @dunglas.

**Pull request merged**
