### PR TITLE
Optimize production build by ignoring dev files

### PR DESCRIPTION
**Pull request by kylekatarnls**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

This will rid production package of not needed dev files (tests and repo settings files). If you're OK, I could apply this everywhere (main repo and sub-repos), it would make Symfony installation faster and would save place on servers.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
We rejected this in the past. This is a deployment issue. Instead, you can have a script clean those files you don't need.

:-1:

**Comment by kylekatarnls** [comment]
> Would be great if someone could take the time to mark tests classes internal though.

It won't prevent users to include tests classes, calling tests classes is an obvious misuse, if you consider this as a BC, then any white-space added in a README is a BC.

The right way to do is to exclude all those files on next major (5). Deprecation warnings (@internal) would be a nice adding but it would be useful for only 0,01% of users, really not mandatory in my opinion.

**Comment by linaori** [comment]
I'm still in favor of removing those files from the dist, it clutters my search results most of the time.

**Comment by maxhelias** [comment]
@nicolas-grekas I'm don't know if it's possible but could not we do something similar on the Flex side ?
Like blocking the download of some file / folder or delete these items after with an option ?

**Comment by nicolas-grekas** [comment]
A composer plugin/command could look at e.g `exclude-from-classmap` for each package in vendor and delete matching files. I don't know if it's a good idea or not, someone that cares would need to investigate.

**Comment by kylekatarnls** [comment]
I'm not in favor of a delete option/command, it resolves only the half of the problem. You save disk space but you're still downloading useless resources (wasting time, bandwidth, disk write access). By default, when installing your dependencies, you should download only needed files to **use** the library, not the one only needed to develop it, that's why the `export-ignore` feature exists.

I understand the temptation of working around the problem, but nothing will really replace the `.gitattributes` file. Right now, each test file added in the project make the install longer, it should be "free" to add test files or any dev-only files, it's too bad having to refrain yourself from adding stuff in tests directory because it will make the production package bigger and slower to download.

**Comment by nicolas-grekas** [comment]
Closing as explained. See linked issues for details, arguments are the same.

**Pull request closed without merging**
