### PR TITLE
Enable Dependabot for getting updates for actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
| Q             | A
| ------------- | ---
| Branch?       | 5.4 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 

Enable dependabot https://dependabot.com

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
Screen Shot 2021-10-02 at 1 13 37 PM

This has to be enabled in the repository setting.

**Comment by naveensrinivasan** [comment]
Enabling dependabot security updates flags certain issues. This will help the security posture of the project.

**Comment by derrabus** [comment]
Why do we need this?

**Comment by naveensrinivasan** [comment]
related to #43294 and here are some dependencies that could potentially require to be updated.
Screen Shot 2021-10-02 at 1 21 49 PM

**Review by derrabus — CHANGES_REQUESTED** [review]
No, sorry. Blocking libraries with known vulnerabilities is just not our responsibility.

**Comment by naveensrinivasan** [comment]
> No, sorry. Blocking libraries with known vulnerabilities is just not our responsibility.

What changes are you looking for?

**Comment by derrabus** [comment]
> What changes are you looking for?

None, I don't think we should pursue integrating Dependabot.

**Comment by stof** [comment]
@naveensrinivasan the dependabot alerts for the composer ecosystem are fine when you have a lock file committed (so for projects). But for libraries that only contain a composer.json file, they are weird, as they complain when any vulnerable versions is in the range, not when vulnerable versions are actually required to be used, which does not match the way composer will select versions in projects using them.

**Comment by wouterj** [comment]
Hi! I'm afraid I have to close this PR as well.

As @derrabus and @stof said, not permitting releases with security vulnerabilities is not the task of `composer.json` files in projects like the Symfony framework. Applications should do this themselves, with a lock file and security checking (e.g. dependabot, or the `symfony check:security` command provided by Symfony).

**Pull request closed without merging**
