### PR TITLE
[Validator] remove return type declaration from __sleep()

### LINKED ISSUE #34478: [Validator] Breaking change caused by return types upgrade from 4.3 to 4.4
**Symfony version(s) affected**: 4.4.0

**Description**  
Upgrading from 4.3 to 4.4 today causing cache clearing and the bundle  : sonata admin bundle to throw errors.

From the commit "Add return types to internal|final|private methods" 32116184d7c62639d7351c49c160927935e5ba99

Return type was forced even on magic methods which can cause breaking changes on third party libraries overriding them without specifying the return type

**How to reproduce**  
To reproduce the bug simply create a new Constraint class overriding one of the method where the return type was forced in 4.4, this class will work in 4.3 but not when upgrading in 4.4

`
class MyConstraint extends Constraint
{
public function __sleep(){ ...}
}
`

**Possible Solution**  
Maybe don't force return types on 4.4 version to keep retro compatibility
and do those breaking changes in 5 ?

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34478
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by dmaicher — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by ureimers** [comment]
Hi,
thanks for the quick fix. But it seems to be in the 4.4 branch (https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Constraint.php) but not in the 4.4 tag (https://github.com/symfony/symfony/blob/v4.4.0/src/Symfony/Component/Validator/Constraint.php). So `composer update` currently doesn't load it (as it's versioning is based on tags and not on branches, when not explicitly using the dev-* prefix).
Could you update/move the 4.4 tag as well please?

Thanks in advance and best regards,

Ulf

**Comment by xabbuh** [comment]
This will be part of the next patch (once published it will be 4.4.1). If you need it right now, you can require `^4.4@dev`.

**Comment by ureimers** [comment]
Ah, I see. I got it wrong, indeed this should be part of the next patch and not silently be merged into v4.4.

We reverted back to 4.3 for the moment as there's no operational need to switch to 4.4.

Thank you

**Pull request merged**
