### PR TITLE
[FrameworkBundle][HttpKernel] the finder is required to discover bundle commands

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17038 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by dunglas** [comment]
:+1:

**Comment by xabbuh** [comment]
The failure on PHP 7 looks weird to me (Composer isn't able to find a matching package for `symfony/finder`).

**Comment by nicolas-grekas** [comment]
The composer failure is related to a bug in composer when mixed package repositories are used (when deps=low/high, we build a local packages.json file to be able to test cross components PR)

**Comment by nicolas-grekas** [comment]
@xabbuh you need to remove the finder component from require-dev, that's the issue!

**Comment by xabbuh** [comment]
@nicolas-grekas oh good catch, thanks, the builds should pass now

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by nicolas-grekas** [comment]
Closed via e69491c

**Pull request closed without merging**
