### PR TITLE
[DependencyInjection] Add auto aliasing for subscribedServices

### PR DESCRIPTION
**Pull request by nyroDev**
Implemented only for services requested with no key, this is useful to avoid multiple line for the same services and it's aliases

| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no    
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

When using ServiceSubscriberInterface with aliased services, if you want your services to be available as an alias or with it's fully qualified name, you have to add multiple line.

This PR aims to avoid that by automatically adding needed service name using the following rules: 
- If the service is an alias, add only the aliased service
- If the service is parent service, add all of its aliases, if any.

This PR will only do it for indexes with no key.  
When devs specifically indicates local alias and original service ID, I think they know what they're doing and we do not have to add others alias for them.

 BEFORE : 
```php
public static function getSubscribedServices()
{
    return [
        'some.service' => 'stdClass',
        'stdClass' => 'stdClass',
    ];
}
```

 AFTER : 
```php
public static function getSubscribedServices()
{
    return [
        'some.service',
    ];
}
```
OR: 
```php
public static function getSubscribedServices()
{
    return [
        'stdCladd',
    ];
}
```

Note that the first code will still work as excpted.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I'm sorry but I'm pretty sure this we should avoid doing this at all costs. The reason is that this makes global state leak into what is currently local state. Having some ids that come from nowhere (from the pic of the declaring side) introduced back the drawbacks of service locators that service subscribers carefully avoid.

:-1: sorry

**Comment by nyroDev** [comment]
@nicolas-grekas If I understand you correctly, the idea for the controller that implement the `ServiceSubscriberInterface` :  
1. In `getSubscribedServices`, use only simple alias (like router, session, ...) that should be used with the `get` function
2. This controller could use full class names in action method to get others services.

If so, there is 2 differents names for the same service and we could end up with a code like that:

```php
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class FrontController extends AbstractController
{
    public function test(SessionInterface $session)
    {
        $sessionFromGet = $this->get('session');

        // $sessionFromGet may be wrapped, but is the same as $session

        // But this is not working, service not found
        $this->get(SessionInterface::class);
    }
}
```

Isn't it weird for dev to that the full ame work in one place (method arg) and not another (get call)?

**Comment by nicolas-grekas** [comment]
The core logic is: if you didn't declare you need it, you can't get it.
What you declare it what `getSubscribedServices` returns.
That's all.

**Comment by nicolas-grekas** [comment]
Values on the right side must be PHP types - that would conflict with the requirement.
But it is possible to declare two keys for the same type:
```
'session' => SessionInterface::class,
SessionInterface::class => SessionInterface::class,
```

**Comment by nyroDev** [comment]
That's exactly what I ended up with and what I want to avoid.
If have many aliases and I want to make them all available for backward compatibility or something like that, I have to maintain the alias list here.

Which is annoying, because the alias hierarchy is well known by the containerBuilder.
And I have no way to get it in the `getSubscribedServices` function to build this hierarchy

The syntax might be:
```php
[
'@'.SessionInterface::class, // add aliases
'?@'.SessionInterface::class, // add aliases, optionnal dependency
'session'=>'@'.SessionInterface::class, // add session alias, and add other aliases
'session'=>'?@'.SessionInterface::class, // add session alias, and add other aliases, optionnal dependency
]
```

@ stands for alias, not sure if it's really good because of it's meaning elsewhere.

**Comment by nicolas-grekas** [comment]
That conflicts with the core requirement: service subscribers declare their dependencies and don't get anything else in return. Breaking this is a really really bad idea.

**Comment by nyroDev** [comment]
Ok, you're a core team member, you know what's best for it.

**Pull request closed without merging**
