### PR TITLE
[Cache] add constructor docblocks for clarity

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23503
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
OK, although not very useful to me, why not.

**Comment by fabpot** [comment]
During the last few years, we've tried to not add unneeded phpdocs. We also learned that maintaining this information requires a lot of effort. Some added phpdocs seem useless to me.

**Comment by xabbuh** [comment]
In general I do agree with you. But it looks like some users do have problems to infer the right type to pass from the code that we currently have (see the linked issue). And since we don't add any further information besides the type information it's IMO not very likely that this gets outdated soon.

By the way, these places are also good candidates for scalar type hints in Symfony 4.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
