### PR TITLE
[Form] make tests compatible with Symfony 2.8 and 3.0

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by paradajozsef** [comment]
@xabbuh Thank you!! (you were faster than me with this PR) :) It was my mistake. The test I created here: #17406 was only compatible with 2.7, but was merged to 2.8 and 3.0 too. Next time I have to check test in newer versions also. Sorry for that! (Also interesting, that the AppVeyor build was successful when there was a failing test. I create an issue for that.)

:+1: 

Status: Reviewed

**Comment by xabbuh** [comment]
@paradajozsef There was nothing wrong with your pull request. Referencing form types by their qualified class names does only work since Symfony 2.8 so we exactly had to do what you did in your PR. :)

**Comment by paradajozsef** [comment]
@xabbuh  I see. Thanks for the reply! :)

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
