### PR TITLE
[Yaml] treat trailing backslashes in multi-line strings

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24408
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by faheemhameed** [comment]
This works great. Thanks!! Will this be merged to "symfony/symfony": "3.3.3" so that I can pull the new version easily? or how can I do it. I am quite a newbie here.

**Comment by javiereguiluz** [comment]
@faheemhameed if accepted, this will be merged in 3.3 branch and it will be available in the next stable version released for Symfony 3.3. If you need this solution as soon as possible, you could even use a forked version of this component in your composer.json or even, copy+paste this change in the specific file inside vendor/ (this las "solution" only recommended in case of real urgency!).

**Review by javiereguiluz — APPROVED** [review]

**Review by Simperfit — APPROVED** [review]

**Comment by faheemhameed** [comment]
@javiereguiluz Thanks for the guide. I have tried to create a fork and tried to update my composer.json using vcs repo based on a note I found in the getcomposer.org website. But it was not successful. I have decided to wait for the update as the issue is not a pressing one for me. 

Many thanks.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
