### PR TITLE
Simplify markdown for PR template

### PR DESCRIPTION
**Pull request by Pierstoval**
I know it's all about rendering in the issue, but actually putting `[` in markdown can create some issues.

Here, having raw informations looks better IMO and does not cause any rendering issue when not used. And double-click-selection does not force to remove the brackets manually.

What do you think?

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: I was going to propose this change myself. The brackets are really annoying to me.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by iltar** [comment]
:+1: I've often facepalm when people copy-paste the table and leave them in place, seeing [yes] and [no] everywhere.

**Comment by xabbuh** [comment]
Thank you @Pierstoval.

**Pull request merged**
