### PR TITLE
[Validator] remove an unreachable code branch

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

This property is a string or null but can never be `false`.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]
For 6.4?

**Comment by nicolas-grekas** [comment]
Can you please check the history of this line? Could this be linked to a feature we broke at some point?

**Comment by fabpot** [comment]
6.4 for sure

**Comment by xabbuh** [comment]
I switched the base branch to `6.4`.

**Review by yceruto — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
