### PR TITLE
[Intl] Update ICU data to 58.1

### PR DESCRIPTION
**Pull request by jakzal**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

ICU 58.1 was recently released: http://site.icu-project.org/download/58

> This is the first release of ICU after the project joined the Unicode® Consortium. The license changed to the Unicode license (which is similar to the ICU 1.8.1-57 license).

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Could you please rebase on latest 2.7 to be sure that this is fine even after #20551?

**Comment by jakzal** [comment]
Status: Needs work

**Comment by fabpot** [comment]
@jakzal  Is this one ok to merge?

**Comment by ro0NL** [comment]
ICU 58.2 is out ;-)

**Comment by jakzal** [comment]
I'm working on another PR that will improve tests. Once it's done I'll update this PR to 58.2 ;)

**Comment by stof** [comment]
@jakzal what is the state of this PR ?

**Comment by jakzal** [comment]
@stof I'll update it this week (not before Wednesday though)

**Comment by jakzal** [comment]
Replaced by https://github.com/symfony/symfony/pull/21790

**Pull request closed without merging**
