### PR TITLE
[AssetMapper] use the filesystem component to avoid side cases into MappedAssetFactory

### PR DESCRIPTION
**Pull request by chadyred**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

Hello,

To avoid side cases fixed into the filesystem component

Thanks

### CODE REVIEW

**Comment by smnandre** [comment]
Beeing curious, what is the bug you're mentioning this PR fixes ?

**Comment by chadyred** [comment]
I am a noob, I used an older version, without the fix, and I don't have the assets/vendor folder, so I discover the bug....which doesn't exist...because their is the check "&&  vendorDir".... but I saw that after the PR was created ^^'  I edited many time the description...I take a look at the FileSystem component and it seems to do all this kind of stuff...

**Comment by smnandre** [comment]
So, not sure, does this PR solves a bug?

**Comment by chadyred** [comment]
Not at all, I close

**Pull request closed without merging**
