### PR TITLE
[HttpFoundation] missing namespace for RedisProxy

### PR DESCRIPTION
**Pull request by bonfante**
I think the intention was to check if is instance of \Symfony\Component\Cache\Traits\RedisProxy

| Q             | A
| ------------- | ---
| Branch?       | 4.1 (becareful when merging)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no   
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Coincidentally I spotted this also yesterday :)
The namespace should be moved to a "use" statement.
And we should double check that all methods we use on the object exist on the peoxy.
I think at least"del()" is missing.

**Comment by nicolas-grekas** [comment]
Another option is to just remove the check for it. Wouldn't break anything since it never worked. Note that RedisProxy exists because the Redis class used to be incompatible with autogenerated lazy proxies. That's not the case anymore since phpredis 4.

**Comment by Bonfante** [comment]
@nicolas-grekas 
I spotted this when testing [GAE](https://cloud.google.com/appengine/ ) with  [memorystore](https://cloud.google.com/memorystore/).

the `__call` should do trick for `del()` right?
https://github.com/symfony/symfony/blob/44b2f97dcd2ba10857dd545e424ad4f48c9dbea1/src/Symfony/Component/Cache/Traits/RedisProxy.php#L31

**Review by nicolas-grekas — APPROVED** [review]
> the __call should do trick for del() right?

correct!
to be merged on 4.1

**Comment by Bonfante** [comment]
Nice, my first commit on symfony  :smile:

**Pull request merged**
