### PR TITLE
[Serializer] Add missing conflict for property-info<3.1

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/21293#discussion_r96254245
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by dunglas** [comment]
See https://github.com/symfony/symfony/pull/19649#r75210080

**Comment by dunglas** [comment]
But I'm 👍 anyway because it will simplify our CI.

**Comment by xabbuh** [comment]
👍

**Comment by nicolas-grekas** [comment]
Thank you @chalasr.

**Pull request merged**
