### PR TITLE
[BrowserKit] Use a regex to guess if a URI is absolute or not.

### PR DESCRIPTION
**Pull request by dosten**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14732 |
| License | MIT |

### CODE REVIEW

**Comment by jakzal** [comment]
You'll need to add a test :)

**Comment by Tobion** [comment]
Using parse_url would be better IMO

**Comment by dosten** [comment]
@Tobion If i use `parse_url` the code should be:

```php
if (in_array(parse_url($uri, PHP_URL_SCHEME), array('http', 'https'))) {
    return $uri;
}
```

@jakzal How can i test a protected method? via Reflection?

**Comment by dosten** [comment]
Another option https://github.com/symfony/asset/blob/2.7/Package.php#L68-L71

**Comment by jakzal** [comment]
> @jakzal How can i test a protected method? via Reflection?

You don't. You should test its behaviour through a public method.

**Comment by fabpot** [comment]
Closing in favor of #14785 (it has tests).

**Pull request closed without merging**
