### PR TITLE
[Translation] XLIFF 2.0 read support

### PR DESCRIPTION
**Pull request by xphere**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #11853 |
| License | MIT |
- added XLIFF v2.0 support in `XliffFileLoader`.
- detects XLIFF version automatically from `version` or `xmlns` attributes.
- throw exception if XLIFF version does not exist.

Matches XLIFF 1.2 support, except that notes are not loaded now.
This is because they're not tied to a single translation (segment) anymore, but to a group of them (unit) or a whole file.

### CODE REVIEW

**Comment by stof** [comment]
I don't like the current architecture using version classes:

- these classes are named Version, but they are not versions at all. They are extractors
- I don't think it is worth introducing new classes for that. We could simply have ``extractXliff1`` and ``extractXliff2`` in the XliffFileLoader

And can you rebase your work on top of the current 2.7 branch ? It conflicts with the current codebase (which also means that tests will not run when updating your branch with new changes if conflicts are not fixed)

**Comment by stof** [comment]
@xphere it is a good idea to comment when you update the PR, because we are not notified when new commits are added in a PR. Otherwise, there is a high chance that we won't review the PR again, just because we don't know there is a need for that.

**Comment by stof** [comment]
and can you rework your implementation based on my previous review ?

**Comment by xphere** [comment]
@stof sure, sorry, I did rebase on 2.7 branch, but still need to relocate versions into extractor methods. Will do as soon as I've some spare time.

**Comment by aitboudad** [comment]
@xphere any progress :smile: ?

**Comment by aitboudad** [comment]
@xphere interested in updating this PR?  If not I could try work on it.

**Comment by aitboudad** [comment]
closed in favor of #15717

**Pull request closed without merging**
