### PR TITLE
Fix permission for executable class file

### PR DESCRIPTION
**Pull request by DavidPrevot**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| License       | MIT

### CODE REVIEW

**Comment by GromNaN** [comment]
It would be nice to have a job that assert that no `.php` file is executable. 

```bash
#!/bin/bash

# Find executable PHP files
files=$(find . -name "*.php" -type f -perm /u+x,g+x,o+x)

# Check if any executable files were found
if [ -n "$files" ]; then
    echo "Executable PHP files found:"
    echo "$files"
    exit 1
else
    echo "No executable PHP files found."
    exit 0
fi

```

**Comment by GromNaN** [comment]
You can fix the permission for all this files on branch 6.2.
```
src/Symfony/Component/HttpClient/Tests/DataCollector/HttpClientDataCollectorTest.php
src/Symfony/Component/HttpClient/Tests/NoPrivateNetworkHttpClientTest.php
src/Symfony/Component/HttpClient/Tests/TraceableHttpClientTest.php
src/Symfony/Component/HttpClient/Tests/DependencyInjection/HttpClientPassTest.php
src/Symfony/Component/Messenger/Tests/Fixtures/MyOwnException.php
src/Symfony/Component/Messenger/Event/WorkerRateLimitedEvent.php
src/Symfony/Component/DependencyInjection/Tests/Fixtures/IntTagClass.php
src/Symfony/Component/DependencyInjection/Tests/Fixtures/AutoconfiguredService1.php
src/Symfony/Component/DependencyInjection/Tests/Fixtures/AutoconfiguredService2.php
src/Symfony/Component/Process/Tests/ErrorProcessInitiator.php
```

**Comment by nicolas-grekas** [comment]
Thank you @DavidPrevot.

**Comment by nicolas-grekas** [comment]
Cherry-picked on 5.4 as c587137a12

**Pull request merged**
