### PR TITLE
[HttpKernel] [WebProfilerBundle] Added an icon in profile search results if something has been dumped

### PR DESCRIPTION
**Pull request by ahazebroucq**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | None
| License       | MIT
| Doc PR        | TODO

This is a proposal for a small feature : in the profiler search result, display a small icon next to the token link if something has been dump in this profiler token. This is particularly useful if browsing an app creates multiple profiles (via automatic AJAX calls for instance), and we want to quickly find which profile has debug info dumped in it : 

image

As this is my first Symfony contribution, I'm not quite sure about the process, or even if this is an acceptable change. I also appreciate any feedback !

TODO
- [ ] update CHANGELOG file(s ?) I'm not sure about which files should be updated.
- [ ] doc PR. Here also, I'm not sure if a doc PR is needed, as this is a non-interactive feature (it juste displays an icon). Should I update some sreenshots somewhere to reflect this change ?

### CODE REVIEW

**Comment by yceruto** [comment]
I think the TODO items are not necessary for this little feature.

Please check the **fabbot.io** failures, thanks!

**Comment by ahazebroucq** [comment]
Thank you @yceruto, I've applied the fabbot patch. Is there anything else I should do now, or should I wait for review ?

**Comment by fabpot** [comment]
I'm not convinced yet that this is something we want to do. I can see many more icons coming: one when an email was sent, one when a message was dispatched in the bus, ... Not sure we want to go down this road to be honest.

**Comment by ahazebroucq** [comment]
Thank you @fabpot for your input. It's a fair point, and if this proposal is not merged in the end, I might try to rework it as a 3rd party bundle.

I've seen that the milestone has changed and "next" is now selected for this PR. Should I rebase to master ? What are the next steps anyway ? Should I wait for a code review ? Failing tests seem to be unrelated.

**Comment by fabpot** [comment]
Reviewing this PR again, I still think that we should not do it. Thanks for proposing.

**Pull request closed without merging**
