### PR TITLE
Remove extra space after full stop.

### PR DESCRIPTION
**Pull request by kevinirlen**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

Simply removes an extra space in the comment section.

### CODE REVIEW

**Comment by ghost** [comment]
it doesn't matter

**Comment by kevinirlen** [comment]
@javaDeveloperKid thank you for your response. 

But I strongly believe that every little things contributes to the Symfony project :)

**Comment by ghost** [comment]
This space was 14 years old. Finder component was downloaded 682M times. Nobody had problem with this space. For me PRs like this look like racking up PRs just for a sake of having a PR merged.
I've filtered your pull requests on symfony/symfony repository and none brings any value.

**Comment by antonkomarev** [comment]
@javaDeveloperKid0it this PR brings consistency. No need to offend for such things. Anybody can propose any changes he wants.

**Comment by xabbuh** [comment]
Please everybody calm down stay polite. We as the core team value every contribution. If we decide that someone is wasting our time, we will tell that person in a kindly manner to focus on other things instead. Thank you all!

On a side note: IIRC I started contributing to Symfony by fixing a typo.

**Pull request merged**
