### PR TITLE
[Routing] added a suggestion to add the HttpFoundation component.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by hhamon** [comment]
As the `RequestContext` object can be initialized with a Symfony `Request` instance, it seems legit to have a suggestion for the HttpFoundation component as well in the `composer.json` file.

**Comment by fabpot** [comment]
Honestly, and that's not the first time I'm mentioning this, I don't understand how those suggestions are useful for anyone. So, I'm -0 on this one.

**Comment by HeahDude** [comment]
I think it could be useful, for example when working with a standalone symfony component, looking at his `composer.json` you can know what other library needs to be installed in order to use some dedicated functionality. Everybody might not start with a full stack framework.
The fact that it is needed in `require-dev` only says "it can work with this library and it's tested" but not what is the benefit of it.
:+1:

**Comment by hhamon** [comment]
Maybe @nicolas-grekas and @stof have provide their opinion on Composer suggestions.

**Comment by fabpot** [comment]
Thank you @hhamon.

**Pull request merged**
