### PR TITLE
[EventDispatcher] Add Debug\WrappingListenerInterface

### PR DESCRIPTION
**Pull request by hason**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Main goal of this PR is to provide a debug tool, that correct identify wrapped hooks/events from legacy system (e.g. wordpress, ...).

### CODE REVIEW

**Comment by xabbuh** [comment]
Currently, I fail to see the use case. Can you give an example on where and how you would use this?

**Comment by nicolas-grekas** [comment]
@hason a rebase is needed. Can you also please give us a few more words about it, as @xabbuh asked for? Thanks.

**Comment by nicolas-grekas** [comment]
ping @hason 

status: needs work

**Comment by fabpot** [comment]
Closing as there is no more activity.

**Pull request closed without merging**
