### PR TITLE
remove reflection-docblock from mime requirements

### LINKED ISSUE #38886: symfony/mime requires phpdocumentor/reflection-docblock but doesn't use it
**Symfony version(s) affected**: 5.2

**Description**  

In [1a5636c](https://github.com/symfony/mime/commit/1a5636cbf45cbf1d9c1c9b3716f680340b0a826b) a dependency has been introduced, even if mime library doesn't use directly phpdocumentor library.

**Possible Solution**  

Remove phpdocumentor/reflection-docblock from dependencies of symfony/mime

### PR DESCRIPTION
**Pull request by garak**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38886
| License       | MIT
| Doc PR        | not needed

See related issue

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
The dependency is used by the tests introduced with #37847. We need to keep it, but `require-dev` is probably the better place for it.

**Comment by derrabus** [comment]
While we're at it: `symfony/property-access`, `symfony/property-info` and `symfony/serializer` should also not be mandatory dependencies of the Mime component.

**Comment by derrabus** [comment]
Sorry, I should have been more precise here. The three packages I mentioned need to be dev dependencies as well. Sorry for the confusion.

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @garak.

**Pull request merged**
