### PR TITLE
[Form] Fix BC break introduced in #14403

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by HeahDude** [comment]
ref https://github.com/symfony/symfony/pull/14403/files/f0dfd2faaba4eb7848d3e1b8a7add7da302d8cae#r57138850

**Comment by HeahDude** [comment]
Note to merger: to revert in 3.0

**Comment by HeahDude** [comment]
Tests are failing.

Status: Needs work

**Comment by xabbuh** [comment]
Why is the order of the attributes important? Imo you should not rely on it.

**Comment by HeahDude** [comment]
@xabbuh we don't have the choice IMHO.

The component themes needs to print the value independently from `attr` so they can be overridden with:
```twig
{% set read_only = true %}
{{ block 'parent_block' }}
```

**Comment by HeahDude** [comment]
Fixed.

Status: Needs Review

**Comment by mnapoli** [comment]
:+1: however I think the tests need to be reverted too to ensure that we are fixing the problem (see https://github.com/symfony/symfony/pull/14403#discussion_r57133978)

**Comment by HeahDude** [comment]
@mnapoli Thanks for the review, the tests are already reverted (otherwise they would fail).

Failures are unrelated.

**Comment by xabbuh** [comment]
You will now need to update the lowest version of the Form component required by the FrameworkBundle to `^2.8.4`.

**Comment by HeahDude** [comment]
@xabbuh so it should be done in a second commit since this one is supposed to be reverted in 3.0, right ?

**Comment by xabbuh** [comment]
Not necessarily if I don't misunderstand you. We need to revert all the changes here in the `3.0` branch, don't we?

**Comment by HeahDude** [comment]
Yes we do.

**Comment by HeahDude** [comment]
Thanks @xabbuh tests are all green now (excepted appveyor being unusually long).

**Comment by HeahDude** [comment]
It seems appveyor has bugged, why does it still try to install icu v51 ?

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by HeahDude** [comment]
@xabbuh Do I need to upgrade the `composer.json` of `TwigBridge` too ?

**Comment by xabbuh** [comment]
@HeahDude Usually you would have to do that. But this time that's not necessary as this was apparently done in another pull request before: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Twig/composer.json#L25

**Comment by HeahDude** [comment]
@xabbuh Thanks for your leading :)

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Comment by mnapoli** [comment]
Thanks @HeahDude for the fix!

**Comment by HeahDude** [comment]
@mnapoli Thanks for reporting this issue :)

**Pull request merged**
