### PR TITLE
Allow to set SameSite config to 'none'

### LINKED ISSUE #33926: SameSite cookie option could not be set to "none"
**Symfony version(s) affected**: 4.3.*

**Description**  
The PR #31475 allows to set the samesite cookie flag to "none", but it is not allowed in the `framework.session.cookie_samesite` or `remember_me.samesite` config.

**How to reproduce**  

```yaml
# framework.yml
framework:
    session:
        cookie_samesite: 'none'

# or packages/security.yml
security:
    firewalls:
        main:
            remember_me:
              samesite: 'none'
```

**Additional context**  

```
The value "none" is not allowed for path "framework.session.cookie_samesite".
Permissible values: null, "lax", "strict"
```

### PR DESCRIPTION
**Pull request by ihmels**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33926
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by javiereguiluz — APPROVED** [review]
A nice first contribution to Symfony. Thanks Yannick!

**Comment by nicolas-grekas** [comment]
Thank you @ihmels.

**Comment by NielsCorneille** [comment]
It is still missing on the documentation https://symfony.com/doc/current/reference/configuration/framework.html#cookie-samesite

**Comment by chalasr** [comment]
@NielsCorneille Please consider opening an issue/PR on https://github.com/symfony/symfony-docs

**Pull request merged**
