### PR TITLE
[Translation] deprecate the backup feature

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | https://github.com/symfony/symfony/pull/16912#issuecomment-165753061 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@xabbuh @aitboudad what if we remove this backup feature altogether for the Translation component? My feel is that we're trying to do "too much" here. In Symfony we do more "dangerous" things (e.g. the SensioGeneratorBundle) without providing a backup feature.

**Comment by fabpot** [comment]
I agree with @javiereguiluz

**Comment by aitboudad** [comment]
I agree too.

**Comment by stof** [comment]
I agree too. I'm always disabling this backup, as git already gives me a way to get the old file if something goes wrong, and backup files only lead to mistakes in such cases

**Comment by xabbuh** [comment]
I am not too familiar with the Translation component internals. But if you all agree on this, I will revert the new interface and instead deprecate the `setBackup()` method. What do you think about that?

**Comment by aitboudad** [comment]
@xabbuh I think so and deprecate backup for the `translation:update` command too.

**Comment by fabpot** [comment]
:+1: for deprecation

**Comment by xabbuh** [comment]
I added deprecation trigger for the backup feature. I couldn't deprecate the `--no-backup` option of the command nor the `disableBackup()` method of the `TranslationWriter` class as people will need to use them to prepare for the 4.0 upgrade. Though we have to deprecate them in 4.1.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
