### PR TITLE
[HttpClient] Add PSR-18 to HttplugClient since HTTPlug is deprecated

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Relates to https://github.com/php-http/httplug/pull/171

### CODE REVIEW

**Comment by derrabus** [comment]
Does this change do anything? We should already implement through `Http\Client\HttpClient`.

**Comment by nicolas-grekas** [comment]
You should be right, but I still prefer adding this code now since it's going to stay in v7

**Review by stof — APPROVED** [review]

**Comment by derrabus** [comment]
So the plan is to not implement the HTTPlug interface anymore in v7? Does the name `HttplugClient` still make sense then or should we rather add a `PsrClient` as a replacement?

**Comment by stof** [comment]
@derrabus not the *sync* interface, as it is deprecated in favor of the PSR-18 one (the sync Httplug interface is already an empty one extending the PSR-18 one). the client will still implement the async interface (and the PSR-18 one).

**Comment by stof** [comment]
and we *already* have a Psr18Client that implements only the PSR interfaces

**Comment by derrabus** [comment]
Ah, got it, thanks.

**Review by derrabus — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
