### PR TITLE
[Workflow] Remove constraints on transition/place name + Updated Dumper

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

(ping @Plopix : I changed a bit the puml dumper)

### CODE REVIEW

**Comment by Plopix** [comment]
@lyrixx I have just checked and I think your .puml result is not syntactically valid.

```puml
state "a" <<initial>> 
state "b"
"a" --> "b": "t1"
```
=> That is not valid, you have a `Syntax Error`
Instead PlantUML as this concept of *aliases*

```puml
state "a" as a<<initial>> 
state "b" as b
a --> b: "t1"
```

Let me push the valid test fixtures for you to update the dumper accordingly :)

**Comment by Plopix** [comment]
Oh no there is better, just add `allow_mixing` in the header everywhere (plus see my comment in the code)

**Comment by lyrixx** [comment]
Thanks @Plopix for the review.

I have testes in real life with really strange char and my code works.
My test was base on this workflow:
```
        weird:
            type: workflow
            supports: stdClass # Just a hack
            places:
                - "a'"
                - 'é!'
                - 'b\"(\"'
            transitions:
                -
                    name: '{}'
                    from: "a'"
                    to: 'é!'
```

And as it's already a workflow, the `allow_mixing` was already present.
If I remove the `"` in the pum dump, then it's broken.

Here is the dump
```
@startuml
allow_mixing
title weird
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam state {
    BackgroundColor<<initial>> #87b741
    BackgroundColor<<marked>> #3887C6
    BorderColor #3887C6
    BorderColor<<marked>> Black
    FontColor<<marked>> White
}
skinparam agent {
    BackgroundColor #ffffff
    BorderColor #3887C6
}
state "a'" <<initial>>
state "é!"
state "b\(\"
agent "{}"
"a'" --> "{}"
"{}" --> "é!"
@enduml

**But** You are right about the "state_machine dumper". We should always add `allow_mixing`.
I have updated the PR.

**Comment by lyrixx** [comment]
Not really related question: Do you really use the `nofooter` option  of the dumper? (right now, there are not way to use it without writing / editing some code) I no-one use it, I would like to remove it (less code === less bug)

**Comment by Plopix** [comment]
Yes indeed the `allow_mixing` is enough and was present in the workflow dump. I just picked one file randomly in your PR that is how I saw that syntax error and testing a workflow I saw it was working then I figured the `allow_mixing`.

Ok to remove _nofooter_  I agree with the less code less bug. (having the footer was prob too fancy)

> We should always add `allow_mixing`. I have updated the PR.

I don't see the changes but I could have a look when done!
thx!

**Comment by lyrixx** [comment]
> I don't see the changes but I could have a look when done!

Indeed, I forgot to push ;) It's not pushed

**Pull request merged**
