### PR TITLE
[Translation][Profiler]added the number of times a translation has been used.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | #14183 |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: It looks OK to me. Thanks @aitboudad

**Comment by xabbuh** [comment]
This will not change the number for "Defined messages" above the table, right? Does it make sense to update this value as well?

**Comment by xabbuh** [comment]
I also think not having an extra column but just an additional line if the message is used more than once as in the last proposal in #14183 looks nicer.

**Comment by aitboudad** [comment]
@xabbuh fixed.

selection_022

**Comment by aitboudad** [comment]
@fabpot can I merge ? :)

**Comment by xabbuh** [comment]
@aitboudad The number of defined messages (the headline above the table) is still unchanged?

**Comment by aitboudad** [comment]
@xabbuh I updated the number of defined messages.

**Comment by fabpot** [comment]
:+1:

**Pull request merged**
