### PR TITLE
[DoctrineBridge] Fixed bc layer after #18069

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | BC break |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by HeahDude** [comment]
I've got that weird feeling after https://github.com/symfony/symfony/pull/18069 got merged, it's now clear:

while addressing @xabbuh's comment about someone calling `parent::onBind()`, I add the condition `__CLASS__ === get_class($this)` to fix the triggering of the deprecation, but I guess that also breaks the call because the logic now in `onSubmit()` is not excecuted.

This PR adds another flag to fix this BC break.

Sorry for this confusion.

**Comment by HeahDude** [comment]
Any thought on this BC break ?

**Comment by xabbuh** [comment]
I think a test for this would be good.

**Comment by HeahDude** [comment]
Thanks @xabbuh I've added a failing test which revealed another issue, we have to keep the event in `onBind()` definition or it ends with a PHP error...
I also added the missing `Listener` suffix to the test class name.

Note that the patch works as expected, tests are green now :)

**Comment by fabpot** [comment]
Thank you @HeahDude.

**Pull request merged**
