### PR TITLE
[Form] Fix error when rendering a DateIntervalType form with exactly 0 weeks

### LINKED ISSUE #27378: [Form] DateIntervalType: Unable to transform value for property path "[weeks]": Expected a string.
**Symfony version(s) affected**: 3.2 and later

**Description**  
When using the DateIntervalType form type with the integer widget and using weeks rather than days, the following exception is thrown when rendering an interval containing exactly 0 weeks:

    Unable to transform value for property path "[weeks]": Expected a string.
   
The exception is thrown in `\Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer`, line 142.

The problem is that `\Symfony\Component\Form\Extension\Core\DataTransformer\DateIntervalToArrayTransformer` initialises the value for the `weeks` part of the interval to integer `0`. If `days` is available, this will be updated to a numeric string, but if not it remains at integer `0`.

    if (in_array('weeks', $this->fields, true)) {
        $result['weeks'] = 0;
        if (isset($result['days']) && (int) $result['days'] >= 7) {
            $result['weeks'] = (string) floor($result['days'] / 7);
            $result['days'] = (string) ($result['days'] % 7);
        }
    }

Ultimately this integer reaches `NumberToLocalizedStringTransformer`, where on line 141 a type check occurs:

    if (!is_string($value)) {
        throw new TransformationFailedException('Expected a string.');
    }

**How to reproduce**  
Create a form with the following `DateIntervalType` child:

    $builder->add('interval', DateIntervalType::class, [
        'widget'     => 'integer',
        'with_weeks' => true,
        'with_days'  => false,
    ]);

Set the form's data to `new \DateInteval('PY1M1W0')`. Render the form to produce the error.

**Possible Solution**  
Change the default value for `weeks` to `'0'`. PR incoming shortly.

### PR DESCRIPTION
**Pull request by krixon**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27378
| License       | MIT

Fixes the issue described in #27378

### CODE REVIEW

**Comment by krixon** [comment]
BTW, the above test failures also occur on the 3.2 branch on which these changes are based.

**Comment by nicolas-grekas** [comment]
Note that 3.2 is not maintained anymore so that this should be merged on 3.4 (or 2.8 if the issue exists there. Does it?)

**Comment by nicolas-grekas** [comment]
(please check tests and CS failures also)

**Comment by krixon** [comment]
> Note that 3.2 is not maintained anymore so that this should be merged on 3.4 (or 2.8 if the issue exists there. Does it?)

Thanks, I've rebased onto 3.4 and updated the PR target accordingly. The problem does not exist in 2.8.

> please check tests and CS failures also

I am still seeing some test failures locally, however I see the same failures on the 3.4 branch itself - they are unrelated to my changes. I've included details of these errors below. I am also not sure why AppVeyor thinks it can't build this branch - could you advise on how to proceed please?

    1) Symfony\Component\Ldap\Tests\AdapterTest::testLdapQuery
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/AdapterTest.php:40
    
    2) Symfony\Component\Ldap\Tests\AdapterTest::testLdapQueryIterator
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/AdapterTest.php:60
    
    3) Symfony\Component\Ldap\Tests\AdapterTest::testLdapQueryScopeBase
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/AdapterTest.php:86
    
    4) Symfony\Component\Ldap\Tests\AdapterTest::testLdapQueryScopeOneLevel
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/AdapterTest.php:102
    
    5) Symfony\Component\Ldap\Tests\LdapManagerTest::testLdapAddAndRemove
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php:31
    
    6) Symfony\Component\Ldap\Tests\LdapManagerTest::testLdapAddInvalidEntry
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php:31
    
    7) Symfony\Component\Ldap\Tests\LdapManagerTest::testLdapUpdate
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php:31
    
    8) Symfony\Component\Ldap\Tests\LdapManagerTest::testLdapUnboundAdd
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php:31
    
    9) Symfony\Component\Ldap\Tests\LdapManagerTest::testLdapUnboundRemove
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php:31
    
    10) Symfony\Component\Ldap\Tests\LdapManagerTest::testLdapUnboundUpdate
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php:31
    
    11) Symfony\Component\Ldap\Tests\LdapManagerTest::testLdapRename
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php:31
    
    12) Symfony\Component\Ldap\Tests\LdapManagerTest::testLdapRenameWithoutRemovingOldRdn
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/Adapter/ExtLdap/LdapManagerTest.php:31
    
    13) Symfony\Component\Ldap\Tests\LdapClientTest::testLdapClientFunctional
    Symfony\Component\Ldap\Exception\ConnectionException: Can't contact LDAP server
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Adapter/ExtLdap/Connection.php:54
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Ldap.php:38
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/LdapClient.php:39
    /home/karl/code/krixon/symfony/src/Symfony/Component/Ldap/Tests/LdapClientTest.php:165
    
    --
    
    There were 4 failures:
    
    1) Symfony\Component\DependencyInjection\Tests\ContainerBuilderTest::testNoClassFromNsSeparatorId
    Failed asserting that exception message 'The definition for "\foo" has no class attribute, and appears to reference a class or interface in the global namespace. Leaving out the "class" attribute is only allowed for namespaced classes. Please specify the class attribute explicitly to get rid of this error.' contains 'The definition for "\foo" has no class.'.
    
    2) Symfony\Component\HttpFoundation\Tests\JsonResponseTest::testConstructorWithSimpleTypes
    Failed asserting that two strings are identical.
    --- Expected
    +++ Actual
    @@ @@
    -'0.1'
    +'0.10000000000000001'
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/HttpFoundation/Tests/JsonResponseTest.php:46
    
    3) Symfony\Component\HttpFoundation\Tests\JsonResponseTest::testStaticCreateWithSimpleTypes
    Failed asserting that two strings are identical.
    --- Expected
    +++ Actual
    @@ @@
    -'0.1'
    +'0.10000000000000001'
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/HttpFoundation/Tests/JsonResponseTest.php:134
    
    4) Symfony\Component\HttpFoundation\Tests\ResponseFunctionalTest::testCookie with data set #0 ('cookie_max_age')
    Failed asserting that string matches format description.
    --- Expected
    +++ Actual
    @@ @@
     
    -Warning: Expiry date cannot have a year greater than 9999 in %scookie_max_age.php on line 10
    +Fatal error: Uncaught Error: Class 'PHPUnit\Util\ErrorHandler' not found in /home/karl/code/krixon/symfony/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:290
    +Stack trace:
    +#0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler::Symfony\Bridge\PhpUnit\{closure}(2, 'Expiry date can...', '/home/karl.rixo...', 10, Array)
    +#1 /home/karl/code/krixon/symfony/src/Symfony/Component/HttpFoundation/Tests/Fixtures/response-functional/cookie_max_age.php(10): setcookie('foo2', 'bar', 253402310800, '/')
    +#2 {main}
    +  thrown in /home/karl/code/krixon/symfony/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php on line 290
    @@ @@
    -    [3] => Set-Cookie: foo=bar; expires=Sat, 01-Jan-10000 02:46:40 GMT; Max-Age=%d; path=/
    +    [3] => Set-Cookie: foo=bar; expires=Sat, 01-Jan-10000 02:46:40 GMT; Max-Age=251872986908; path=/
    
    /home/karl/code/krixon/symfony/src/Symfony/Component/HttpFoundation/Tests/ResponseFunctionalTest.php:49

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @krixon.

**Pull request merged**
