### PR TITLE
Remove "branch-alias", populate "version"

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by jvasseur** [comment]
I'm not sure if it's a good thing to add the version key to the `composer.json` because packagist will try to read them and IIRC ignore tags if the version key doesn't match the tag meaning we will have to maintain the key when doing releases.

**Comment by stof** [comment]
I agree with @jvasseur. there is only drawbacks when specifying `version` explicitly in VCS repositories.

**Comment by nicolas-grekas** [comment]
The version is required for two reasons:
- in the CI, to know which version is checked out 
- when doing composer up, to not have to populate COMPOSER_ROOT_VERSION (auto-guessing does not work here)

**Comment by stof** [comment]
But it is required to *not* have it in subtree splits for things to work fine (otherwise, you have to remove them before each tag). So I'd rather find a better solution for the CI setup

**Comment by nicolas-grekas** [comment]
Packagist should be patched instead IMHO.
See https://github.com/composer/packagist/issues/1125

**Comment by stof** [comment]
See my answer there. That's not related to Packagist but to Composer itself (Packagist uses Composer's VcsRepository to get the metadata)

**Pull request merged**
