### PR TITLE
[PropertyAccessor] A little refactor

### PR DESCRIPTION
**Pull request by aivus**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |
- Remove obsolete code
- Remove excessive actions
- Fix phpdoc & comments

### CODE REVIEW

**Comment by sstok** [comment]
LGTM.

**Comment by aivus** [comment]
Status: Needs Review

**Comment by dunglas** [comment]
:+1:

**Comment by Tobion** [comment]
@dunglas which branch is this supposed to go in?

**Comment by dunglas** [comment]
2.7 AFAIK. PHPdoc should be updated in 2.3 too.

**Comment by dunglas** [comment]
Status: Reviewed

**Comment by Tobion** [comment]
Thank you @aivus.

**Pull request closed without merging**
