### PR TITLE
[FrameworkBundle] add conflict for non-compatible TwigBridge version

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #27713
| License       | MIT
| Doc PR        | 

The argument was dropped in #27454.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
There have been similar reports on other deps recently. I feel like we will not be able to catch up with all combinations of versions and we should instead tell people how to update. Many did update only framework-bundle, which is wrong. Doing `composer update "symfony/*"` fixes the issue for everyone.

I'd be :-1: here to not create a precedent.

**Comment by chalasr** [comment]
Tend to agree with @xabbuh. Recommending to update `symfony/*` is a thing, having invalid version constraints between components is another. You taught me it @nicolas-grekas: symfony components/bundles are used in the wild, we can't assume that everyone hear and apply our recommendations, here perhaps because of their own technical constraints leading them to try updating a component and not another.
I think we should keep up improving our cross-package test coverage and maintain proper conflict rules when possible.

**Comment by nicolas-grekas** [comment]
But framework-bundle doesn't know about twig-bridge.
All the other conflicts are legit because they target lower level package that framework-bundle is built on.
twig-bridge is just foreign to it.

**Comment by xabbuh** [comment]
but [it does](https://github.com/symfony/symfony/blob/8c1e29995418e4eeed417c66ccf62e7bdd92711d/src/Symfony/Bundle/FrameworkBundle/Resources/config/security_csrf.xml#L25)

**Comment by nicolas-grekas** [comment]
that's not obvious reading the composer.json file ;)
you were suggesting adding a test case, possible?

**Review by nicolas-grekas — APPROVED** [review]
(test welcome later when you have some time :) )

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
