### PR TITLE
[TwigBundle] Deprecate `base_template_class` option

### PR DESCRIPTION
**Pull request by Steveb-p**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | yes 
| Issues        | 
| License       | MIT

According to https://github.com/twigphp/Twig/blob/3.x/CHANGELOG#L222, `base_template_class` option has been removed from Twig 3.0.

Symfony still allows to pass this configuration option via https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bundle/TwigBundle/DependencyInjection/Configuration.php#L132, but there is of course no effect.

I think it would be good to deprecate it and prepare it's removal in 8.x? Since Symfony 7.x requires Twig 3.x.

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
The deprecation should be documented in `UPRADE-7.1.md` and in the changelog file of TwigBundle though.

**Comment by Steveb-p** [comment]
> The deprecation should be documented in `UPRADE-7.1.md` and in the changelog file of TwigBundle though.

I will follow up with this shortly :sweat_smile: I just need to check how they are usually done :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Steveb-p.

**Comment by derrabus** [comment]
The tests needed a little adjustment: #54810

**Pull request merged**
