### PR TITLE
[DependencyInjection] Fix named args support in ChildDefinition

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Following @Tobion's review of #21383.

### CODE REVIEW

**Comment by xabbuh** [comment]
I would also update the exception message. "$index must be an integer." is not really right anymore.

**Comment by dunglas** [comment]
@xabbuh updated, `ChildDefinition` now delegates the common behavior to the parent class.

**Comment by xabbuh** [comment]
@dunglas I meant the one in `replaceArgument()`: https://github.com/dunglas/symfony/blob/9245400aa0a3467d89565ecdda8bd1d5315bbe21/src/Symfony/Component/DependencyInjection/ChildDefinition.php#L102

**Comment by dunglas** [comment]
@xabbuh updated

**Comment by Tobion** [comment]
The exception message in `Definition::replaceArgument` 

> The index "%d" is not in the range [0, %d]

is also not correct anymore in case an argument exists as a string. Then you can't actually access the argument with the given range.

**Comment by yukoff** [comment]
The #22979 seems related to this. With PR applied locally I'm instead of [previous error](22979#issue-232427699) I'm now getting
```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "redis_host". Did you mean this: "doctrine.orm.cache.redis_host"? in D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php:100
Stack trace:
#0 D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag.php(56): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('redis_host')
#1 D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php(217): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('redis_host')
#2 D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php(187): Symfony\Component\DependencyInjection\Par in D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ParameterBag\ParameterBag.php on line 100
```

**Comment by yukoff** [comment]
Seems false alarm, I'll remove confusing comment to avoid indexing and leading others to wrong place ;)

**Comment by yukoff** [comment]
Despite [my false alarm](22979#issuecomment-305289124) in #22979 ;) still doesn't work with PR applied locally:
```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Invalid key "collaboration" found in arguments of method "__construct()" for service "sulu_admin.js_config_pool": only integer or $named arguments are allowed. in D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\ResolveNamedArgumentsPass.php:47
Stack trace:
#0 D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass.php(57): Symfony\Component\DependencyInjection\Compiler\ResolveNamedArgumentsPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), false)
#1 D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\ResolveNamedArgumentsPass.php(30): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#2 D:\sandbox\vendor\symfony\sym in D:\sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\ResolveNamedArgumentsPass.php on line 47
```

Service description is quite trivial
```xml
        <service id="sulu_admin.js_config_pool" class="%sulu_admin.js_config_pool.class%"/>
```

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Comment by nicolas-grekas** [comment]
@yukoff named args must start with a `$`

**Comment by yukoff** [comment]
My previous comment is not actual as of sulu/sulu#3379

@nicolas-grekas not quite sure I got to where you're referencing... ;)

**Comment by nicolas-grekas** [comment]
I'm referencing the error message you pasted just above: it looks legit to me.

**Comment by yukoff** [comment]
Oh... Anyway it seems not actual any more, thanks!

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request closed without merging**
