### PR TITLE
[FrameworkBundle] Removed deprecated code paths

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by Tobion** [comment]
`validator_api_version` still there

**Comment by dosten** [comment]
You should fix the error in `Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper`

**Comment by nicolas-grekas** [comment]
@Tobion yes, to be removed in an other PR

**Comment by nicolas-grekas** [comment]
@dosten which error??

**Comment by dosten** [comment]
@nicolas-grekas Hmm.. It's weird, a few hours ago the cause of the failing job on Travis was the use of the SCOPE_CONTAINER constant in the `Symfony/Bridge/ProxyManager/LazyProxy/PhpDumper/ProxyDumper` class, but now seems to be ok.

:+1:

**Comment by nicolas-grekas** [comment]
Status: needs work
I need to figure out what's wrong with the test.
It may be related to the per-component testing system.

**Comment by nicolas-grekas** [comment]
Failure inspected, will be fixed once #15694 is merged.
Status: needs review

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
