### PR TITLE
[travis] Auto-conf deps=high matrix line

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

This generalize what we did for testing while working on major version:
- on master, the deps=high line checks out the last "number" branch for testing
- legacy tests are skipped when the last X.Y series is tested with master (X+1).0

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Travis config is ready. Once merge on 3.0, I'll cherry-pick the PR on 2.3 (doing it this way reduces conflicts)

**Comment by nicolas-grekas** [comment]
@stof , willing to review this one?

**Comment by jakzal** [comment]
@nicolas-grekas `.travis.yml` is really complex. It's not a subject of this PR, but what do you think of extracting most of its logic to a bash script?

**Comment by nicolas-grekas** [comment]
PR rebased
@jakzal I'm convinced it would  really help... Here, everything is in just one place, just read the file to understand how travis runs tests (even if it's complex I agree)...

**Comment by nicolas-grekas** [comment]
Status: needs work
Testing 2.8 should skip legacy tests, this is not the case currently

**Comment by nicolas-grekas** [comment]
Green on 3.0, now testing on 2.3: #16974

**Pull request closed without merging**
