### PR TITLE
[WebProfilerBundle] Remove maximum width for web profiler content view

### PR DESCRIPTION
**Pull request by hason**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? |  |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
A big :-1: from me :)

The line length has a tipping point at which readability decreases dramatically. A line with 50 characters is more readable that one with 10 characters ... but a line with 200 characters is MUCH LESS readable that the 50 characters line.

In the print world, the limit was set around 50 - 75 characters per line. In the electronic world, the limit can be up to 100 characters ([Wikipedia source](https://en.wikipedia.org/wiki/Line_length)).

In the current profiler, even with the max-width limitation, we are already over that limit. In the "events" panel, when the application doesn't define the `framework.ide` option, we show lines of more than 150 characters:

event-dispatcher

**Comment by stof** [comment]
there are some cases where we could benefit from the full width though. The timeline can be wide without loosing readability (the wider it is, the more details we can see)

**Comment by javiereguiluz** [comment]
@stof I agree with you ... but only for the performance panel that you mentioned. I'm thinking about some changes that I'll propose soon.

In any case, even for the call graph, using the full width is not always that convenient when using a high resolution (the following screenshot was taken at 2,560x1,440):

profiler-full-width

**Comment by stof** [comment]
@javiereguiluz depends how many small events you have (a request doing a bunch of DBAL queries for instance)

**Comment by fabpot** [comment]
Closing then

**Comment by hason** [comment]
@javiereguiluz The max width solves a problem that doesn't even exist. Not every developer has the browser maximized. But if I maximize the browser or hide debug inspector, I want to use the entire space (e.g. DBAL queries, timeline). Recommendations on the length of the line is meaningful for longer texts - paragraphs. And last but not least, the most of [admin templates](http://themeforest.net/search?utf8=%E2%9C%93&term=&view=list&sort=&date=&category=site-templates%2Fadmin-templates&price_min=&price_max=&sales=&rating_min=4) don't have the restriction for maximum width.

**Comment by Green-Cat** [comment]
:+1:

**Pull request closed without merging**
