### PR TITLE
Ticket 9175

### PR DESCRIPTION
**Pull request by seferov**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #9175 |
| License | MIT |
| Doc PR | n/a |

[Form] $data argument is removed. The default data can be set via the "data" option instead.

### CODE REVIEW

**Comment by stof** [comment]
This must be documented as a BC break in both the UPGRADE-3.0.md file at the root of the repo and in the CHANGELOG.md of the Form component

**Comment by seferov** [comment]
outdated

**Comment by dosten** [comment]
@seferov can you restore the `ticket_9175` branch? so i can work on this

**Comment by seferov** [comment]
@dosten the branch was restored

**Comment by dosten** [comment]
@seferov Thank you

**Pull request closed without merging**
