### PR TITLE
Bosnian translation

### PR DESCRIPTION
**Pull request by WaiSkats**
| Q             | A
| ------------- | ---
| Branch?       |  4.4 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no 
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Thank you.
This looks great. 

I saw that the PR included many other commits and not just yours. I think you started working on the 5.4 branch and then made a PR to branch 4.4. 

I checked out branch 4.4 and `cherry picked` your commit and forced pushed it to your `bosnian-translation` branch. Everything looks good now.

**Comment by WaiSkats** [comment]
Is there anything else that I need to do?

**Comment by Nyholm** [comment]
No. We are all done here. Just waiting for a second review.

**Comment by fabpot** [comment]
Thank you @WaiSkats.

**Pull request merged**
