### PR TITLE
[Serializer] fix typo in AbstractNormalizerContextBuilder::withDefaultContructorArguments()

### LINKED ISSUE #54616: [Serializer] Typo in name of AbstractNormalizerContextBuilder::withDefaultContructorArguments() method
### Symfony version(s) affected

6.4

### Description

In the name of `\Symfony\Component\Serializer\Context\Normalizer\AbstractNormalizerContextBuilder::withDefaultContructorArguments()`, `Contructor` (no `s`) is used instead of `Constructor`.

(Same issue for the parameter name)

### How to reproduce

Read method signature of

https://github.com/symfony/symfony/blob/05a8fcc9a9932a2dc36c846c844b4b96b210b4ca/src/Symfony/Component/Serializer/Context/Normalizer/AbstractNormalizerContextBuilder.php#L115

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | Closes #54616 
| License       | MIT

This is not a bug in the meaning of a bug so no need to fix this on 6.4. However a deprecation is needed.

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by chalasr** [comment]
Good catch, thanks @javaDeveloperKid.

**Comment by chalasr** [comment]
Good catch, thanks @javaDeveloperKid.

**Comment by nicolas-grekas** [comment]
What about adding the method on 6.4 (without any deprecation yet?) so that ppl can start writing without typo right away?

**Comment by ghost** [comment]
No contraindications from my side. Do you need another PR or will you cherry pick the new method on your own?

**Comment by nicolas-grekas** [comment]
A new PR please

**Pull request merged**
