### PR TITLE
Added seeing to avoid sooing...

### PR DESCRIPTION
**Pull request by srinikumar11**
Added seeing to avoid sooing...

### CODE REVIEW

**Comment by Tobion** [comment]
`seeing` is a verb. Plural/singular of verbs makes no sense to me. What is the point of this?

**Comment by ksrinivasancomo** [comment]
Exception below:

Neither the property "customerSightseeing" nor one of the methods "addCustomerSightsooing()"/"removeCustomerSightsooing()", "setCustomerSightseeing()", "customerSightseeing()", "__set()" or "__call()" exist and have public access in class "AppBundle\Entity\Customer".

**Comment by ksrinivasancomo** [comment]
Please see the exception below:

Neither the property "customerSightseeing" nor one of the methods
"addCustomerSightsooing()"/"removeCustomerSightsooing()",
"setCustomerSightseeing()", "customerSightseeing()", "__set()" or
"__call()" exist and have public access in class
"AppBundle\Entity\Customer".

On Tue, Oct 20, 2015 at 7:32 PM, Tobias Schultze <notifications@github.com>
wrote:

> seeing is a verb. Plural/singular of verbs makes no sense to me. What is
> the point of this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/symfony/symfony/pull/16297#issuecomment-149577039>.
>



-- 
Kind Regards,
*Srinivasan Kumar*
Symfony 2 Developer
MOBILE:         +91 99625 19459
SKYPE:          srinivasankumar11
HANGOUTS:  srinikumar11

**Comment by stof** [comment]
@ksrinivasancomo please also show your object definition for these properties

**Comment by ksrinivasancomo** [comment]
What you mean?

On Wed, Oct 21, 2015 at 5:27 PM, Christophe Coevoet <
notifications@github.com> wrote:

> @ksrinivasancomo <https://github.com/ksrinivasancomo> please also show
> your object definition for these properties
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/symfony/symfony/pull/16297#issuecomment-149867598>.
>



-- 
Kind Regards,
*Srinivasan Kumar*
Symfony 2 Developer
MOBILE:         +91 99625 19459
SKYPE:          srinivasankumar11
HANGOUTS:  srinikumar11

**Comment by stof** [comment]
you AppBundle\Entity\Customer class (at least the relevant parts)

**Comment by fabpot** [comment]
Closing as there is no feedback. @ksrinivasancomo Feel free to reopen with more details as asked by @stof

**Pull request closed without merging**
