### PR TITLE
[Console] added support for nosql database

### PR DESCRIPTION
**Pull request by potsky**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by jakzal** [comment]
This PR doesn't seem right. First commit comes from another PR.

What is that you're fixing here exactly? A bit more context would be helpful.

**Comment by potsky** [comment]
Hi !

I just want to add this commit : [Console] added support for nosql database

I have followed your contribution documentation which tells to merge master in my branch before sending a pull request of my branch to avoid merge  collision.

When merging, I don't know why this commit has been merged with mine. Moreover, this commit is 4 days old and I have cloned the full repository this morning !

**Comment by jakzal** [comment]
You'll probably need to do a rebase. 

Before doing so, could you give us a bit more context on what problem you're actually trying to fix? Might be worth adding a test case too.

**Comment by potsky** [comment]
I have rebased master on my branch of course. I have fully followed this documentation : <http://symfony.com/doc/current/contributing/code/patches.html>

The Console Table class lets display Database entries on a terminal console. But it assumes that database values are strings or implements the method toString(). But with NoSQL database like MongoDB for example, database values can be arrays too.

So before managing values as strings, if a value is an array, we need to convert this array to a string. If not done, it throws an error on the strstr function which is not applied on a string.

**Comment by stof** [comment]
I agree with @fabpot that it is not the responsibility of the Table object to convert data to display (especially given you only support converting arrays, not other values, and the current array conversion is not really pretty).

**Pull request closed without merging**
