### PR TITLE
Update DateValidator.php

### PR DESCRIPTION
**Pull request by mrsnowin**
With this change DateValidator can be extended and PATTERN checkDate changed for another date format.

### CODE REVIEW

**Comment by xabbuh** [comment]
I do not understand this change. The `checkDate()` method is not related to the pattern being applied to the input string.

**Comment by Tobion** [comment]
Also `checkDate` is marked as `@internal` so should not be overwritten anyway. :-1:

**Comment by mrsnowin** [comment]
@xabbuh 
yyyy-mm-dd (original)
const PATTERN = '/^(\d{4})-(\d{2})-(\d{2})$/';
public static function checkDate($year, $month, $day)

dd.mm.yyyy (my)
const PATTERN = '/^(\d{2}).(\d{2}).(\d{4})$/';
public static function checkDate($day, $month, $year)

Different pattern - different order in income params of checkDate function. Original DateValidator always calls own checkDate, not extended. Changing self to $this will salve this problem.

@Tobion 
I want to extend Constraints\Date and Constraints\DateValidator to use in my validation. Don't want to add additional date format changing to whole project. Why i cant extend checkDate()?

**Comment by xabbuh** [comment]
Imo the right approach for your use case would be to introduce a `format` option like it was proposed for the DateTime constraint in #17553.

**Comment by mrsnowin** [comment]
@xabbuh so, datetime validator with format option will solve my problem :)

**Comment by jakzal** [comment]
Ok, let's close this one then.

**Pull request closed without merging**
