### PR TITLE
[Form] Add `csrf_token_lazy` option

### PR DESCRIPTION
**Pull request by tugrul**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes 
| Deprecations? | no 
| Issues        | #40270 , #13464  
| License       | MIT

### Description
This pull request introduces `csrf_token_lazy`, a new form option in Symfony. This option allows for deferred CSRF token generation until form submission, aiding in performance optimization and mitigating conflicts with caching mechanisms.

### Motivation
The necessity for this option arises from the default behavior of Symfony's CSRF protection mechanism, which initiates sessions for token generation. However, in scenarios where caching is employed, this behavior can lead to cache misses or bypasses, impacting application performance adversely. By introducing `csrf_token_lazy`, developers gain the ability to generate tokens only when necessary, thus avoiding unnecessary session starts during form rendering.

### Functionality
With `csrf_token_lazy` enabled, token generation occurs exclusively during form submission. This ensures that sessions are not initiated unnecessarily during form rendering, thereby maintaining security while optimizing performance, particularly in environments sensitive to caching concerns.

### Usage
Developers can enable `csrf_token_lazy` in form configurations:
```php
public function formAction(Request $request, CsrfTokenManagerInterface $csrfTokenManager): Response {

    $lazy = !$request->hasPreviousSession();

    if ($lazy && $request->isMethod('POST')
        && $request->isXmlHttpRequest()
        && $request->request->has('token')) {
        $response = new Response($csrfTokenManager->getToken('lazy_form_token')->getValue());
        $response->headers->set('Content-Type', 'text/plain');
        return $response;
    }
    
    $form = $this->createFormBuilder($formData, [
        'csrf_token_id' => 'lazy_form_token', 
        'csrf_token_lazy' => $lazy,
        'block_prefix' => ''
    ])->add('field_name')->getForm();
    
    return $this->render('form.html.twig', ['form' => $form->createView()]);
}
```

```javascript
const field = document.getElementById('field_name');
const token = document.getElementById('_token');

field.addEventListener('change', () => {
    if(token.value === '') {
        fetch('/form', {
            method: 'POST', body: 'token',
            credentials: 'same-origin',
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
                'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8'
            }
        }).then(response => response.text()).then(tokenVal=> token.value = tokenVal);
    }
});
```

### CODE REVIEW

**Comment by chalasr** [comment]
Thanks for the PR.
Related : https://github.com/symfony/symfony/issues/40270 https://github.com/symfony/symfony/issues/13464
I think lazy CSRF-token generation is desired. The logic behind the proposed option seems to be missing from the diff though.

**Comment by tugrul** [comment]
@chalasr I've decided against implementing an internal controller action for AJAX requests. It's important to note that there's no missing code, as the CSRF token will still be validated by Symfony's FormTypeCsrfExtension in all cases. This mechanism ensures that token validation fails when the token field is an empty string on the form, thereby maintaining security standards.

Instead, I suggest providing guidance for developers to determine whether to handle token generation internally or independently. This approach preserves flexibility while mitigating potential risks associated with token handling.

I'm open to alternative suggestions regarding the implementation of lazy CSRF-token generation. If you have any ideas on how to address potential risks while maintaining flexibility, I'd love to hear them.

Edit: Indeed, achieving lazy CSRF-token generation can be approached in various ways. For developers who prefer not to rely on JavaScript and AJAX requests, an alternative method could involve utilizing form submissions to initiate the required form. For instance, a "show form" button could trigger a form submission to start the required form with the CSRF token initialized.

This provides developers with flexibility in choosing the method that best suits their preferences and project requirements.

```php
public function buildForm(FormBuilderInterface $builder, array $options): void
{
     if($options['csrf_token_lazy']) {
         $builder->add('show_form', SubmitType::class);
         return;
     }

     $builder->add('field_name', TextType::class)->add('submit', SubmitType:class);
}
```

**Comment by nicolas-grekas** [comment]
I'm failing to see where the lazyness happens? Where do we generate the token now?
I feel like the expectations behind the term "lazy" are undefined at the moment.
Anything that uses the session has to disable the cache, so that I don't see how CSRF tokens stored in the session can be compatible with anything lazy. The use case in #40270 is very specific, I'm not sure that's what you're trying to solve.

To me, the only way to be compatible with caching is using the double-submit strategy, with JavaScript to generate the second submit...

Let me close because this is incomplete and this stalled.

**Comment by tugrul** [comment]
I wrote the below token manager due to lack of this option that I provided in this pull request. 

Framework should not force me to write weird stuff.

```php
<?php

namespace App\Service;

use Symfony\Component\Security\Csrf\CsrfToken;
use Symfony\Component\Security\Csrf\CsrfTokenManager;

class CsrfLazyTokenManager extends CsrfTokenManager
{
    protected bool $lazy = false;

    public function isLazy(): bool
    {
        return $this->lazy;
    }

    public function setLazy(bool $lazy): CsrfLazyTokenManager
    {
        $this->lazy = $lazy;

        return $this;
    }

    public function getToken(string $tokenId): CsrfToken
    {
        if ($this->isLazy()) {
            return new CsrfToken($tokenId, '');
        }

        return parent::getToken($tokenId);
    }
}
```

This is my request handler.
```php
#[Route('/contact', name: 'contact')]
    public function indexAction(Request $request): Response
    {
        $user = $this->getUser();
        $csrfTokenLazy = !$request->hasPreviousSession();

        if ($csrfTokenLazy && $request->isMethod('POST')
            && $request->isXmlHttpRequest()
            && $request->request->has('token')) {
            $response = new Response($this->csrfTokenManager->getToken('lazy_form_token')->getValue());
            $response->headers->set('Content-Type', 'text/plain');
            return $response;
        }

        $contact = new Contact();
        $contact->setUser($user);

        $this->csrfTokenManager->setLazy($csrfTokenLazy);

        $form = $this->createForm(ContactFormType::class, $contact, [
            'csrf_token_manager' => $this->csrfTokenManager,
            'csrf_token_lazy' => $csrfTokenLazy,
            'csrf_token_id' => 'lazy_form_token',
            'attr' => ['id' => 'contact-form'],
            'action' => $this->generateUrl('contact')
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($contact);
            $this->entityManager->flush();
            return $this->saveFormAndRedirect($contact);
        }

        return $this->render('contact/index.html.twig', [
            'form' => $form->createView()
        ]);
    }
```

**Comment by nicolas-grekas** [comment]
OK, so you do an AJAX request to get the token. Honestly, if you rely on JS to prevent CSRF requests, you'd better use the double submit strategy.

**Comment by tugrul** [comment]
> OK, so you do an AJAX request to get the token. Honestly, if you rely on JS to prevent CSRF requests, you'd better use the double submit strategy.

Problem is not style of handing CSRF request. Problem is always start session when page have a form. This sends a session cookie and breaks working behavior of frontend cache proxies like Varnish.

This is acceptable approach for static content pages that cacheable like blog posts / article pages with comment forms.

Actual working behavior is not affected for users who have sessions. CSRF token request is only required on first touch of a user.

**Pull request closed without merging**
