### PR TITLE
[Serializer] fix parent class of AbstractNormalizer

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | https://github.com/symfony/symfony/pull/17545#discussion_r58012336 |
| License | MIT |
| Doc PR |  |

We must maintain the parent class to not break BC.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1: (but fabbot has a valid point)

**Comment by dunglas** [comment]
👍

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by fabpot** [comment]
fabbot fixed in 8e67eab

**Comment by xabbuh** [comment]
Thank you @fabpot.

**Pull request merged**
