### PR TITLE
[Config] [ConfigBuilder] Set FQCN as properties type instead of class name

### LINKED ISSUE #40921: [Config] Missing namespace in generated config classes constructor
**Symfony version(s) affected**: 5.3.0-BETA1

**Description**
When a config class is generated, config classes in their constructor are missing their namespace. This is because in https://github.com/symfony/symfony/blob/abeb8e4ca9adfcc1494df22af9fd9a1c0181b532/src/Symfony/Component/Config/Builder/ConfigBuilderGenerator.php#L374 `getType` does not include it.

**How to reproduce**
See https://github.com/symfony/symfony/issues/40921#issuecomment-825781643

In my `cache.php` config file

```php
$config->cache(['pools' => [[
    'adapters' => 'my.dedicated.cache',
]]]);
```

calls `Symfony\Config\Framework\CacheConfig` constructor, which contains

```php
if (isset($value["pools"])) {
    $this->pools = array_map(function($v) { return new PoolConfig($v); }, $value["pools"]);;
    unset($value["pools"]);
}
```

`PoolConfig` is in the `Symfony\Config\Framework\Cache` namespace so it results in

> Attempted to load class "PoolConfig" from namespace "Symfony\Config\Framework".
> Did you forget a "use" statement for another namespace?

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #40921
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by Nyholm** [comment]
Oh, yes. The constructors!
I missed that. Thank you.

Could you add a small tests for this too? Have a look at `AddToList.php`, `AddToList.config.php`, `AddToList.output.php` and add something similar (but simpler) to that. I can help out if you need me to.

**Comment by MatTheCat** [comment]
Well thank **you** for the ConfigBuilder 😁

Could I just replace https://github.com/symfony/symfony/blob/63496dfdc665067bc13375ed4674d8095e39f657/src/Symfony/Component/Config/Tests/Builder/Fixtures/AddToList.config.php#L10-L13 by

```php
$config->messenger([
    'routing' => [
        'Foo\\Message' => [
            'senders' => ['workqueue'],
        ],
        'Foo\\DoubleMessage' => [
            'senders' => ['sync', 'workqueue'],
        ],
    ]
]);
```
?

**Comment by Nyholm** [comment]
Sure, but dont replace anything. Just add a third message. 

```
$config->messenger([
    'routing' => [
        'Foo\\MyArrayMessage' => [
            'senders' => ['workqueue'],
        ],
    ]
]);
 $config->messenger() 
     ->routing('Foo\\Message')->senders(['workqueue']); 
 $config->messenger() 
     ->routing('Foo\\DoubleMessage')->senders(['sync', 'workqueue']); 
```

**Comment by MatTheCat** [comment]
Done :ok_hand: 

Travis failure seems unrelated.

**Review by Nyholm — APPROVED** [review]
Great. Thank you

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks for fixing this bug Mathieu.

**Pull request merged**
