### PR TITLE
without this change allways the legacy code get called

### PR DESCRIPTION
**Pull request by dominikzogg**
[Form] [Validator] prevent that always the legacy validator logic get called

| Q | A |
| --- | --- |
| Bug fix? | [yes] |
| New feature? | [no] |
| BC breaks? | [no] |
| Deprecations? | [no] |
| Tests pass? | [yes] |
| Fixed tickets | [] |
| License | MIT |
| Doc PR | [] |

### CODE REVIEW

**Comment by dominikzogg** [comment]
i use silexphp with symfony 2.7 components, and at the moment, i get deprecation messages, cause the validator implement both interfaces, which means the deprecated logic get called even with a new validator instance

**Comment by dominikzogg** [comment]
@webmozart did i understand this wrong, or does this not cause any problems within fullstack?

**Comment by xabbuh** [comment]
The change looks correct to me.

@dominikzogg Can you also add a test for this to avoid future regressions?

**Comment by fabpot** [comment]
:+1: 

A test would indeed be great.

**Comment by dominikzogg** [comment]
@xabbuh @fabpot can't test it, cause $this->never() get ignored

```{.php}
// #14891: loadTypeGuesser should not call getMetadataFactory
$validator->expects($this->never())->method('getMetadataFactory');
```

**Comment by fabpot** [comment]
Thank you @dominikzogg.

**Comment by dominikzogg** [comment]
@fabpot  thank you for merge, does this get into 2.7 and 2.7 as well?

**Comment by fabpot** [comment]
We always merge in the oldest and still maintained branch, then merge everything back into newest ones.

**Comment by dominikzogg** [comment]
than you for the declaration

**Pull request closed without merging**
