### PR TITLE
[Console] Remove restriction for choices to be strings

### LINKED ISSUE #34789: Console choice forces answers as strings
**Symfony version(s) affected**: 4.3

**Description**  
When using `choice`, selected answers are forced into strings, preventing us from using complex values such as a class with a custom `__toString`. This is a problem, as I need the ability to present the user with a list of display strings to choose from, but need the ID associated with that display string in order to do anything useful. 

**How to reproduce**  
```php
class UserRoleOption
{

    public $id;
    public $name;

    public function __construct($id, $name)
    {
        $this->id = $id;
        $this->name = $name;
    }

    public function __toString()
    {
        return $this->name;
    }
}

foreach ($rolesQuery as $role) {
    $roles[] = new UserRoleOption($role->id, $role->name);
}

var_dump($this->choice('Select roles to assign', $roles));
```

**Possible Solution**  
Remove the cast to string on this line: https://github.com/symfony/console/blob/master/Question/ChoiceQuestion.php#L172

### PR DESCRIPTION
**Pull request by LordZardeck**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #34789
| License       | MIT

When using choice, selected answers are forced into strings, preventing us from using complex values such as a class with a custom __toString. This is a problem, as I need the ability to present the user with a list of display strings to choose from, but need the ID associated with that display string in order to do anything useful.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Would be worth a test case, can you please add one?

**Comment by nicolas-grekas** [comment]
Friendly ping @LordZardeck

**Comment by Nyholm** [comment]
I like this. 
Thank you. 

Could you add a small test case so this can be merged?

**Comment by YaFou** [comment]
What is the pull request status? Do you need help?

**Comment by fabpot** [comment]
Anyone willing to take over this PR to finish it? @YaFou perhaps?

**Comment by YaFou** [comment]
I'm in vacation but I will finish it later @fabpot. Do I need to open a new pull request?

**Comment by fabpot** [comment]
You can push directly on this PR.

**Comment by YaFou** [comment]
@fabpot @Nyholm I opened a pull request LordZardeck/symfony#1 to add a test case for this feature.

**Comment by fabpot** [comment]
I've tried to understand why we have the `string` cast in the first place. It was added in #14648 as a bug fix. @ogizanagi Can you review and comment on this one as you were the one who wrote the code?

**Comment by ogizanagi** [comment]
I'm fine for removing this cast.

I think the original fix intended to make selecting choices indexed by keys consistent by always returning strings (it never meant to do it for selecting choices sequentially indexed). But the true "issue" is `array_search` returning an int even for an array like `array_search('foo', ['0' => 'foo', 'foo' => 'bar']) // returns 0 instead of '0'`.

A proper fix would have been either:
- to only cast to string for assoc choices
- or to properly account for the type of the keys

**Comment by fabpot** [comment]
Thanks @ogizanagi. That's clearer to me now. @LordZardeck I think we need to add some test cases to cover the situation explained by @ogizanagi to be sure we don't break anything.

**Comment by ogizanagi** [comment]
> I think we need to add some test cases to cover the situation explained by @ogizanagi to be sure we don't break anything.

These test cases already exists and [are failing now](https://travis-ci.org/github/symfony/symfony/jobs/620244915#L4266-L4281), in `QuestionHelperTest::testChoiceFromChoicelistWithMixedKeys`.

Fixing the code to only cast in the case of assoc choices should solve everything here (we should not forget to get https://github.com/LordZardeck/symfony/pull/1 merged as well in here)

**Comment by fabpot** [comment]
@ogizanagi Would you like to take over?

**Comment by ogizanagi** [comment]
Sure, I'll update the PR this week

**Comment by ogizanagi** [comment]
@fabpot : Done. But I'm wondering if this should not be merged as a bug fix into 3.4 since the cast was only meant for keys, not for values (int choices values were casted as well). Support for stringable objects just is a consequence of this fix. Let me know, I'll rebase.

**Review by fabpot — APPROVED** [review]
Looks like a new feature to me. Master is fine :)

**Comment by fabpot** [comment]
Thank you @LordZardeck.

**Pull request merged**
