### PR TITLE
[ExpressionLanguage] fixed a BC break

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | fixes a BC break :) |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | see https://github.com/symfony/symfony/pull/19060#r79791581 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by fabpot** [comment]
ping @nicolas-grekas @lyrixx

**Comment by nicolas-grekas** [comment]
For reference, this was done to ease with dumping AST. With NameNode, `$foo->foo()` is dumped as is.
With this change, it will be dumped as `$foo->"foo"()`.
But BC is of paramount importance, so :+1: 
Maybe adjust `Node::dump()` to deal with this case thought?

**Comment by fabpot** [comment]
@nicolas-grekas Indeed, tweaking `dump()` to take care of that would be ideal. Can you prepare a patch?

**Comment by nicolas-grekas** [comment]
Would it be OK to add a new node type that extends `ConstantNode`, to be used in this case? Because unescaping strings while dumping has some code smell to me.

**Comment by fabpot** [comment]
Not sure :)

**Pull request merged**
