### PR TITLE
[HttpFoundation] add Early Hints to Reponse to fix test

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | not needed

This line seems to be needed in order to fix the tests, maybe it has been forgot in merge ?

### CODE REVIEW

**Comment by Simperfit** [comment]
Travis seems broken.. :(

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
The test uses IANA HTTP codes as data provider, and phpdoc says it should be complete. 
Should this be considered as a bugfix on 2.7?

**Comment by dunglas** [comment]
Should be merged in 2.7, indeed. 👍

**Comment by Simperfit** [comment]
PR Rebased

**Review by ogizanagi — APPROVED** [review]

**Comment by ogizanagi** [comment]
You should re-trigger a travis build by amending your commit.

**Comment by Simperfit** [comment]
done @ogizanagi

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Simperfit.

**Pull request merged**
