### PR TITLE
Added missing "__call" to TraceableNormalizer

### PR DESCRIPTION
**Pull request by danielburger1337**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       |  symfony/maker-bundle#1252 
| License       | MIT
| Doc PR        | none

Added missing `__call` method to the new TraceableNormalizer.
This method was forgotten and breaks custom normalizers that have public methods outside of the NormalizerInterface.

This approach is already being used for TreaceableAuthenticator, TraceableEventDispatcher, LoggingTranslator etc...

### CODE REVIEW

**Comment by chalasr** [comment]
Thanks for the PR. Please rebase against 6.1 (https://symfony.com/doc/current/contributing/code/pull_requests.html#rebase-your-pull-request)

**Comment by chalasr** [comment]
Can you please do the same on https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Serializer/Debug/TraceableSerializer.php?

**Comment by danielburger1337** [comment]
> Can you please do the same on https://github.com/symfony/symfony/blob/6.1/src/Symfony/Component/Serializer/Debug/TraceableSerializer.php?

Working on it

**Comment by danielburger1337** [comment]
Not gonna lie, I don't know how to fix this. I get tons of merge conflicts. I submitted a new PR.

**Pull request closed without merging**
