### PR TITLE
[Security] Added getRoles method

### PR DESCRIPTION
**Pull request by FroggDev**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | /

Added method getRoles which return an array with all available roles defined roleHierarchy in security configuration file (in roleHierachy section)

### CODE REVIEW

**Comment by FroggDev** [comment]
To be able to get all available roles from security config files.

For example i am working on a command which can add/remove role to an user https://github.com/FroggDev/Symfony_TestProject/blob/master/src/Command/UserManagerComplex.php with the method geRoles i can get all role dynamicaly available in security config file. It could be used to in an admin tool to manage user role with a dynamic list based on security config file (in muy todo list)

**Comment by xabbuh** [comment]
I am not convinced this use case is common enough to be part of the core. Having such a method could be confusing as this does not guarantee to cover all roles (you could still use other roles that are not part of the hierarchy).

**Comment by javiereguiluz** [comment]
Don't you really think that it's needed to get all roles in a simple way without having to deal with the role hierarchy complexity? (There are a lot of questions about role hierarchy on StackOverflow: https://stackoverflow.com/search?q=symfony+role+hierarchy).

In any case, I haven't looked into this pull request in detail. If we add a method, it must return all roles, those asigned directly and those via a role hierarchy.

**Comment by xabbuh** [comment]
> In any case, I haven't looked into this pull request in detail. If we add a method, it must return all roles, those asigned directly and those via a role hierarchy.

This PR is not about the roles that are assigned to a particular users, but about retrieving the roles that exist in an application. And that's the hard part as there is no registry for all the roles that can be used.

**Comment by javiereguiluz** [comment]
The I understood this wrong. I'm sorry. As you know, I'm obsessed about including a simple method that returns all roles assigned to a user (resolving the role hierarchy automatically if one it's used).

**Comment by MatthieuMota** [comment]
I think this PR also needs [this one](26639). We sometimes need to recover all the roles defined in the application without worrying about the hierarchy. The question is, should the method be in the RoleHierarchy service?

**Comment by chalasr** [comment]
I'm -1 for the reason given by @xabbuh.

**Comment by FroggDev** [comment]
To answer at @xabbuh & @chalasr 
The goal of the method is to get all roles defined in roleHierachy not from all application

**Comment by fabpot** [comment]
Closing as two core team members voted against this addition. Thanks for proposing.

**Pull request closed without merging**
