### PR TITLE
[Serializer] Add deprecation missing from UPGRADE files

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no, simply mention one in upgrade files
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by javiereguiluz** [comment]
👍

**Comment by ogizanagi** [comment]
Thanks for the changes @javiereguiluz 😃

**Comment by stof** [comment]
👍

**Comment by dunglas** [comment]
👍

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @ogizanagi.

**Pull request merged**
