### PR TITLE
[WIP][Form] Allow to configure selectable locale and countries

### LINKED ISSUE #11847: [Form] add "locales" option to LocaleType
It would be nice to have an option named for instance `allowed_locales`, that when set, would cause the widget to display only locales that appear in it, and would throw an exception if one of them can't be found in `Intl::getLocaleBundle()->getLocaleNames()` keys. If this is something that you think would be useful, I can write the code and make a PR.

### PR DESCRIPTION
**Pull request by sstok**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #11847
| License       | MIT
| Doc PR        | "to do"

This fixes #11847, and I added support for countries as well. It should be possible to update the other types also, but languages is more tricky because `en` could mean many different specific locales (this needs some thought if accepted).

### CODE REVIEW

**Comment by yceruto** [comment]
I think it's already supported in user land:
```php
$supportedCountries = ['FR', 'ES', 'CU'];
$builder->add('country', CountryType::class, [
    'choice_loader' => new IntlCallbackChoiceLoader(function () use ($supportedCountries) {
        return array_intersect(array_flip(Intl::getRegionBundle()->getCountryNames()), $supportedCountries);
    }),
])
```
Although I'm not opposed to adding a shortcut for Intl form types.

**Comment by ro0NL** [comment]
vs.

```php
$builder->add('country', CountryType::class, [
    'choice_filter' => function ($countryName) use ($supportedCountries) {
        return in_array($countryName, $supportedCountries, true);
    }),
])
```

just saying :)

**Comment by yceruto** [comment]
See https://github.com/symfony/symfony/issues/14072 and https://github.com/symfony/symfony/pull/18334

**Comment by ro0NL** [comment]
Right, cool :) so i'm not the only one. The feature would be priceless, @sstok WDYT?

**Comment by yceruto** [comment]
That (`choice_filter`) option would be especially useful for child types that need to filter the choices list built in the parent type, without having to duplicate the logic of the `choice_loader`, right?

**Comment by ro0NL** [comment]
Yes or pre-defined choice loaders like Intl. The main advantage is you dont have to (re)define a new choice loader basically. Thus knowing about the labels, etc. In your last example it could just as well be a `ChoiceType` directly (or at least you dont really rely on `CountryType` anymore).

**Comment by yceruto** [comment]
> In your last example it could just as well be a ChoiceType directly (or at least you dont really rely on CountryType anymore).

Yeah, true :)

**Comment by sstok** [comment]
I took a deep dive into the Choice loading system, and almost drowned! 

The way the choices are loaded does not allow for filtering after their list is created, the loader provides a list and only modifying the loader (which is not always possible) would make it possible to filter the choices before the ChoiseList is created.

There is no other option (no pun) but use custom options for each types. But allowing a Closure for a custom filtering (like `$k[0, 2] === 'EN'`) would a good feature, in practice this allows an array of accepted choices and closure to filter the choices (for more advanced use cases).

**Comment by ro0NL** [comment]
> There is no other option (no pun) but use custom options for each types.

Isnt it possible to add a `FilterChoiceList` and a decorating choice loader. If the choice_filter option is passed we decorate the choice loader (or use the callback choice loader) and return a `FilterChoiceList` instead (which also decorates).

**Comment by yceruto** [comment]
@sstok today I can investigate about this, do you mind if I make an alternative proposal?

**Comment by sstok** [comment]
@yceruto Feel free to do 😄 this thing is driving me crazy.

**Comment by yceruto** [comment]
See alternative with `choice_filter` https://github.com/symfony/symfony/pull/28607

**Comment by xabbuh** [comment]
Thank you for your engagement in this @sstok! 👍 Do you agree to close here in favour of #28624?

**Comment by sstok** [comment]
Whoops, a bit late :) yes I agree this can be closed in favor of #28624

**Pull request closed without merging**
