### PR TITLE
[DI] fix reporting bindings on overriden services as unused

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #28326
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by GuilhemN** [comment]
I'm afraid this won't work in most cases: we deep copy bindings in the loaders (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php#L523). So instead we need to store bindings id and check against this list in the pass.

**Comment by nicolas-grekas** [comment]
@GuilhemN thanks for the review! Updated.

**Review by GuilhemN — APPROVED** [review]
Nice improvement :+1: thank you!

**Comment by przemyslaw-bogusz** [comment]
If I am not mistaken, this fix has created a new problem in **ResolveBindingsPass.**

The newly added puts all bindings that are set within a file into the usedBindings array. Before that, usedBindings array was empty as set in the property's declaration.
https://github.com/symfony/symfony/blob/1d3ce9ba87af9ef6594583109aaf418185473526/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php#L37
This means that aftewards, when **processValue** is called, the unusedBindings array remains empty, because the following condition is not met.
https://github.com/symfony/symfony/blob/1d3ce9ba87af9ef6594583109aaf418185473526/src/Symfony/Component/DependencyInjection/Compiler/ResolveBindingsPass.php#L84-L86
As a result, **InvalidArgumentException** (informing about an unused binding) is not thrown, even if a binding is actually not used. I have come upon this, because I was just about to make a PR solving https://github.com/symfony/symfony/issues/27828, but after I fetched the symfony code to make sure it is up to date my fix stopped working. I believe I can find a new solution, solving both problems.

**Comment by nicolas-grekas** [comment]
The current code prefers a false negative to the previous false positive. 
Being more accurate could mean resolving bindings in the loaders, where there is full context about them.
Or maybe you have another idea. I'd be happy to review it!

**Pull request merged**
