### PR TITLE
[Serializer] Add DateTimeZoneNormalizer into Dependency Injection

### PR DESCRIPTION
**Pull request by jewome62**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | none
| License       | MIT
| Doc PR        | none

https://github.com/symfony/symfony/pull/30915
I have forgot to add new Normalizer into DI 🤭

#SymfonyHackday

### CODE REVIEW

**Comment by jewome62** [comment]
Appveyor CI fail is not related to this PR

**Comment by nicolas-grekas** [comment]
Shouldn't this target 4.4?

**Comment by xabbuh** [comment]
If we treat this as a bugfix, it must be merged into the `4.3` branch where the `DateTimeZoneNormalizer` was added.

**Review by nicolas-grekas — APPROVED** [review]
4.3 LGTM

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jewome62.

**Pull request merged**
