### PR TITLE
[Lock] Remove deprecated classes in Lock

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | /
| License       | MIT
| Doc PR        | /

Remove deprecated paths in `Lock` component

### CODE REVIEW

**Comment by StaffNowa** [comment]
@carsonbot you need to get upgrade 😆

**Review by derrabus — APPROVED** [review]

**Review by chalasr — CHANGES_REQUESTED** [review]
We need a CHANGELOG entry for removals :)

**Review by derrabus — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
(rebase needed)

**Comment by jderusse** [comment]
rebased

**Comment by nicolas-grekas** [comment]
WDYT of the failures?

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.

**Pull request merged**
