### PR TITLE
PHPUnit Bridge: Rollback to traditional array syntax.

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #30039
| License       | MIT
| Doc PR        | N/A

I've used PHP CS Fixer to convert all short array expressions back to the traditional syntax understood by php 5.3. Unfortunately, I don't have a local php 5.3 setup anymore, so I hope I've caught all occurrences.

### CODE REVIEW

**Comment by derrabus** [comment]
I strongly disagree with fabbot.io's assessment. 😅

**Comment by stof** [comment]
We would need to find a way to handle PHPunit Bridge with a separate config than the generic code.

Maybe this bridge should actually be maintained in its separate repo directly:

- it has a separate PHP version support
- it is **not** replaced by the `symfony/symfony` package, so a composer install will *always* use the standalone repo anyway. The code in `symfony/symfony` is here only for maintainers
- the testsuite of `symfony/symfony` does not rely on the bridge version it contains, but on the latest one anyway (which is one of the reason for the 2 previous points)

@nicolas-grekas what do you think ?

**Comment by derrabus** [comment]
The fact that PHPUnit bridge is not automatically tested against PHP 5.3 is indeed a problem. In order to avoid regressions like the one fixed here, we would need to add a dedicated php 5.3 build to Travis' matrix that only runs the PHPUnit bridge tests.

**Review by nicolas-grekas — APPROVED** [review]
@stof why not. I think the PRs that patch the bridge on master are used to run the CI, so that we can spot when a change in the bridge would make our CI red. That's the only thing that could prevent doing a separate repo.

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @derrabus

**Pull request merged**
