### PR TITLE
[HttpFoundation] fix session tracking counter

### PR DESCRIPTION
**Pull request by dmaicher**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

As just discussed with @nicolas-grekas I found this issue today while upgrading my app to 3.4.12. Somehow its not possible anymore to set caching headers correctly since this commit: https://github.com/symfony/symfony/commit/146e01cb4442fbcb3b05dd8ae2569d9894374044#diff-5350dc763df30ada9d00563c115f6652

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks @dmaicher, I pushed the fix here also.

PR ready. The session tracker was too eager.

**Review by dunglas — APPROVED** [review]
We can confirm it fixes the API Platform test suite.

**Comment by teohhanhui** [comment]
Unfortunately the tests added in this PR are still failing...

**Comment by nicolas-grekas** [comment]
Thank you @dmaicher.

**Pull request merged**
