### PR TITLE
[Messenger] Add message ID logs

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

so we can find related logs in prod by message ID

part of debugging https://github.com/symfony/symfony/issues/53642#issuecomment-1929030220

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
(For 7.1, that's an improvement, right)

**Comment by nicolas-grekas** [comment]
Thank you @ro0NL.

**Comment by ro0NL** [comment]
ideally 6.4, but OK :')

**Comment by ro0NL** [comment]
@fabpot @nicolas-grekas can we please consider backport to 6.4, we need message ID in logs really.

**Pull request merged**
