### PR TITLE
[TwigBridge] require the needed symfony/contracts package

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #29086
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Shouldn't this be added to the bundle instead? The bridge doesn't force using the TranslationExtension - the bundle does. WDYT?

**Comment by xabbuh** [comment]
My reasoning would be that the extension was usable without installing any other package before and would now also break other potential consumers of it that do not use the bundle.

**Comment by nicolas-grekas** [comment]
> My reasoning would be that the extension was usable without installing any other package

symfony/translation was required, isn't it? and this one links to symfony/contracts in 4.2

**Comment by xabbuh** [comment]
we used `strtr()` as a fallback: https://github.com/symfony/symfony/blob/4.1/src/Symfony/Bridge/Twig/Extension/TranslationExtension.php#L94

**Comment by ro0NL** [comment]
yes, twig bridge suggests: `"symfony/translation": "For using the TranslationExtension"`.

IIUC the issues is we *dont* have `symfony/translation` and it fallbacks to the contract implementation.. but that's still a soft-dependency :thinking:

**Review by nicolas-grekas — APPROVED** [review]
understood, thanks

**Review by ogizanagi — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request merged**
