### PR TITLE
[HttpClient] prevent installation of contracts 1.2

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Hey, no :) Why?

**Comment by xabbuh** [comment]
In 4.3 we do not implement the `cancel()` method added in #31831 (see the currently failing tests).

**Comment by xabbuh** [comment]
https://travis-ci.org/symfony/symfony/jobs/541145074#L4102

**Comment by nicolas-grekas** [comment]
Or we could remove the method from the interface and turn it into an `@method` annotation.
(+ skip in HttpClientTestCase)
WDYT?

**Comment by xabbuh** [comment]
closing in favour of #31850

**Pull request closed without merging**
