### PR TITLE
[Cache] Add Union Types

### PR DESCRIPTION
**Pull request by ValentineBoineau**
| Q             | A
| ------------- | ---
| Branch?       |  6.0
| Bug fix?      |  no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

Extracted from #41424

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This PR collides with #41290 from @derrabus, I fear we might prefer closing it in favor of #41290, since return types must be added at the same time as arguments because of the PSR dependency...

**Comment by derrabus** [comment]
We can finish this PR first and I'll happily rebase mine afterwards.

**Comment by nicolas-grekas** [comment]
Can we? Because we support psr/cache v1, we cannot update argument types...

**Comment by derrabus** [comment]
#41290 was about adding return types. For now, I'd skip the argument types coming from PSR Cache because that is a bit more complicated. For instance, the integration test suite we're using does not handle them well yet.

So, let's make this PR about adding parameter types to all methods except the psr/cache implementations and iterate further afterwards.

**Pull request closed without merging**
