### PR TITLE
[String] Add `trimSuffix()` and `trimPrefix()` methods

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Inspired by golang's string API.

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by javiereguiluz** [comment]
But aren't these very similar (the same?) as the existing methods `after()` and `beforeLast()` ?

**Comment by nicolas-grekas** [comment]
They're not the same: the needle passed to after/before can be found anywhere in the string, not only at the start/end.

**Comment by javiereguiluz** [comment]
Ah, that's indeed different. Thanks for the info!

**Pull request merged**
