### PR TITLE
[Finder] Apply PathFilterIterator only to directory root if path provided as non-regex

### PR DESCRIPTION
**Pull request by erickskrauch**
https://github.com/symfony/symfony/issues/28158

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | yes     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #28158   
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
We never merge BC breaks sorry. Is there any other way around that wouldn't involve a BC break?

**Comment by erickskrauch** [comment]
Hmm... I can suggest implementing `Finder::useStrictPaths(bool $strict)` method, that will toggle applying `path` and `notPath` to the root directory. I shouldn't involve BC.

**Comment by mnapoli** [comment]
Continuing the discussion here by hope of merging this :) (see https://github.com/symfony/symfony/issues/28158#issuecomment-429961971)

Is it really considered a break if the behavior it's fixing is broken? By "broken" I mean it's not respecting the original contract which is:

> Directories passed as argument must be relative to the ones defined with the in() method.

(https://api.symfony.com/4.1/Symfony/Component/Finder/Finder.html#method_exclude)

This issue is becoming problematic in Bref (https://github.com/mnapoli/bref/issues/51) so I'm really hoping we can find a solution :)

**Comment by taylorotwell** [comment]
Agree this would be very nice to have.

**Comment by Simperfit** [comment]
@erickskrauch do you want to do it or do you want me to help you ?

**Comment by erickskrauch** [comment]
@Simperfit you mean update my PR and resolve conflicts?

**Comment by mnapoli** [comment]
@Simperfit not sure I understand, is this a green light to merge this once conflicts are fixed?

**Comment by nicolas-grekas** [comment]
I'm closing because this breaks BC and this staled.

**Comment by erickskrauch** [comment]
@nicolas-grekas, I'm still in touch if it is a condition of removing the "stale" label :)

**Comment by nicolas-grekas** [comment]
Great thanks. Let's keep this PR closed and try a new one that doesn't break BC. Note that I'd prefer not adding a `Finder::useStrictPaths()` method as I don't think its intend will be obvious to anyone. We'd need another idea. Maybe just using a regexp works as I asked on the issue (let's continue on the issue btw).

**Pull request closed without merging**
