### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by j4nr6n**
I've changed my GitHub username

| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

I randomly searched my name on GitHub and the number of times it shows up in results for `vendor/symfony/symfony/CONTRIBUTORS.md` is astonishing. :smile:

### CODE REVIEW

**Comment by ro0NL** [comment]
https://github.com/symfony/symfony/issues/18644 - join the club 😞

**Comment by nicolas-grekas** [comment]
This file is autogenerated, see @ro0NL's link for some more details about it.

**Comment by j4nr6n** [comment]
Thanks @nicolas-grekas

**Comment by fabpot** [comment]
Clarified that the username are Connect and not Github ones in #40134

**Pull request closed without merging**
