### PR TITLE
[Lock] Fix return typehint

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | NA
| License       | MIT
| Doc PR        | NA

Return typehint added in https://github.com/symfony/symfony/pull/31996

ping @dFayet

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by oliverquynh — APPROVED** [review]

**Comment by dFayet** [comment]
@jderusse For my culture, how to you get a `return null`?

**Comment by jderusse** [comment]
@dFayet You shouldn't. That's why I removed the `?`

**Comment by dFayet** [comment]
I misread your commit  😅 ... have a nice day :-)

**Review by dFayet — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.

**Pull request merged**
