### PR TITLE
Minor iconv() fixes

### PR DESCRIPTION
**Pull request by julienfalque**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I'm +0 here: iconv is a mandatory requirement of Symfony since 2.8 anyway.

**Comment by fabpot** [comment]
I'm closing this one then. Why would we want to add those safe guards if iconv is anyway a requirement?

**Comment by julienfalque** [comment]
> iconv is a mandatory requirement of Symfony since 2.8

Is it? I couldn't find it in `VarDumper`'s `composer.json`, am I missing something?

Anyway, as far as I understand, the component only requires `iconv` when dealing with non-UTF-8 strings, so most applications don't need it at all, right? If so, `iconv` could be a suggested package instead of a mandatory one. We could also split current tests in two: one part with UTF-8 strings only, and another one with some non-UTF-8 strings and a `@requires extension iconv` annotation. WDYT?

**Comment by julienfalque** [comment]
Ping @nicolas-grekas

**Comment by SpacePossum** [comment]
ping @nicolas-grekas 
`var-dumper` does _not_ require 'iconv'
https://github.com/symfony/var-dumper/blob/2.8/composer.json

relying on that SF requires it makes it less re-usable (outside of a SF context, like Silex for example)

**Comment by nicolas-grekas** [comment]
We don't ​want to add iconv as a requirement, because that would forbid the use of polyfils.
See https://github.com/symfony/polyfill/pull/54 for some background and links on the topic.

**Comment by SpacePossum** [comment]
that makes sense, but shouldn't the `symfony/polyfill-iconv` be set on in the `composer.json` of the `var-dumper` than?

**Comment by nicolas-grekas** [comment]
We don't want that neither because the that polyfill ​is so big we want people to opt in using it...
You should do that on your side if you want to.

**Comment by SpacePossum** [comment]
alright, I won't ask for a `suggest` entry in `composer.json` either ;)
thanks for getting back on this :+1:

**Comment by julienfalque** [comment]
Thanks for your answers @nicolas-grekas.

I think my suggestion above (https://github.com/symfony/symfony/pull/20927#issuecomment-269287387) is still relevant though, at least for the composer.json `suggest` part. WDYT?

**Comment by nicolas-grekas** [comment]
@julienfalque what about putting the ext-iconv requirement in `require-dev`? That would replace the `@requires` annotations. Why not for the suggest if you think it's worth.
PR welcomed.

**Comment by keradus** [comment]
>  what about putting the ext-iconv requirement in require-dev

but you just said, there is no need for `ext-iconv`, one could use polyfill.

>  That would replace the @requires annotations. 

I agree that `@requires` annotation for extension is wrong, when one could rely on polyfill.

------------------------------

It's a "have extension or polyfill for it" problem. Composer is not supporting such syntax. Still, one of them is required for this package, without any of them it won't work.
Thus, in requirement, there should be one that is easier to install. And that would be polyfill. One that is better yet harder to install may be in suggest section. And even if one would install extension, yes, the polyfill would still be installed, but it won't be used. It's better to download a little more deps than have unworking code, as we forgot to clarify requirements.

**Comment by nicolas-grekas** [comment]
require-dev is about what is required to *test* something. So still makes sense to me.

**Comment by julienfalque** [comment]
The extension is not only required for tests as `AbstractDumper::utf8Encode()` uses it as well. For that reason I would rather add both `ext-iconv` and `symfony/polyfill-iconv` as suggested dependencies.

**Comment by keradus** [comment]
would `AbstractDumper::utf8Encode` somehow works (eg raising some special exception, but not just crash on not found method/class) ? if not, then one of dep should be mentioned in non-dev, non-suggested deps

**Comment by nicolas-grekas** [comment]
@keradus see previous comments and answers. We could throw an exception thought.

**Comment by keradus** [comment]
yep, but we don't. that's what i'm saying. if you would raise special exception like `install polyfill / extension`, then it's fine. but now (current master), it's just a crash.

**Comment by julienfalque** [comment]
Note that the changes in this PR already introduced such exception (but the message did not mention missing dependency) :p

**Pull request closed without merging**
