### PR TITLE
[WebProfilerBundle] Made profiler changes for WCAG 2.0 AA compliance

### PR DESCRIPTION
**Pull request by spreston**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

[WebProfilerBundle] Modified green icon colors for min contrast of 4.5
[WebProfilerBundle] Added skipnavs and skipnav click events
[WebProfilerBundle] Added hidden-accessible text
[WebProfilerBundle] Added tab indexes to make elements focusable
[WebProfilerBundle] Added href to make a tags focusable

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@spreston thanks for proposing these changes. Before analyzing the proposed color change, I'd like to ask you if the green shade is the only color you propose to change or if you also want to change the red and yellow colors. Thanks.

**Comment by stof** [comment]
this should either go in 2.3 (if we consider it as a bugfix) or in 2.8. But 2.7 is the wrong target in all cases

**Comment by stof** [comment]
and this is only about the toolbar, not about the profiler itself, right ?

**Comment by spreston** [comment]
Correct. This only targets the toolbar itself. I can move these to 2.3 if that's more appropriate. The green shade is the only one that needed to change. 

The proposed color has a contrast of 4.59 (4.5 minimum) based on analysis at http://snook.ca/technical/colour_contrast/colour.html#fg=5E8014,bg=FFFFFF
If it would be better, I can create a bug ticket for the color change and allow someone else to investigate other colors and only commit the text/keyboard accessibility/skipnav changes.

**Comment by javiereguiluz** [comment]
@spreston thanks for the info. I've tested the tool that you linked and the results are:

color_contrast

So it appears that the color complies the WCAG 2.0 AA requirements both for large and small font sizes. Maybe I'm missing something here :confused:

**Comment by spreston** [comment]
That was the new color that I committed. The original is: http://snook.ca/technical/colour_contrast/colour.html#fg=759E1A,bg=FFFFFF

Which shows a contrast of 3.15 which doesn't comply with 508 (minimum 3.5) or WCAG 2.0 AA.

**Comment by javiereguiluz** [comment]
@spreston THAT was what I was missing :)  Thanks!

**Comment by fabpot** [comment]
@spreston Can you submit a PR on 2.3 for the color changes. Everything else should probably be done on 2.8. Thanks.

**Comment by spreston** [comment]
Will do. I'm a little swamped at the moment, so I'll have to work on it
over the coming week.

-- 
bcg
*.*
Steve Preston
Lead Developer
943 Glenwood Station Lane, Suite 301
Charlottesville, VA 22901
Cell: 606-571-4940
Office: 636-BCG-TRNS <636-224-8768> (636-224-8768) <636-224-8768>
Facebook <https://www.facebook.com/bcgtrans> | Twitter
<https://twitter.com/boydcatongrant> | LinkedIn
<https://www.linkedin.com/company/bcg-transportation-inc-?trk=company_logo>
 | bcgtrans <http://www.bcgtrans.com/>

**Pull request closed without merging**
