### PR TITLE
[RFC] [Workflow]  WIP Create MarkingHistoryStore to allow logging of an entity's states in the entity record #28265

### PR DESCRIPTION
**Pull request by ChangePlaces**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes (changelog not updated)
| BC breaks?    | no   
| Deprecations? | no
| Tests pass?   | todo
| Fixed tickets | #28253
| License       | MIT
| Doc PR        | todo

see #28253

This adds the feature for entities with workflows to keep a log of its previous states along with a timestamp.

### CODE REVIEW

**Comment by Padam87** [comment]
IMO this is a bit too specific functionality, and the implementation is very opinionated.

Maybe create a bundle instead?

I use this in my projects:

```php
class WorkflowLogListener implements EventSubscriberInterface
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return [
            'workflow.completed' => 'completed',
        ];
    }

    public function completed(Event $event)
    {
        $subject = $event->getSubject();

        $log = new WorkflowLog();
        $log
            ->setSubjectClass(get_class($subject))
            ->setSubjectId($subject->getId())
            ->setWorkflow($event->getWorkflowName())
            ->setTransition($event->getTransition()->getName())
            ->setFroms($event->getTransition()->getFroms())
            ->setTos($event->getTransition()->getTos())
        ;

        $this->em->persist($log);
        $this->em->flush();
    }
}
```

**Comment by Padam87** [comment]
Not sure why that is a problem. Create a repository, add a method to select based on the entity(class and id), use that in the controller to fetch results.

**Comment by ChangePlaces** [comment]
or put three extra lines in your workflow config

**Comment by noniagriconomie** [comment]
Hi, generaly a workflow state is binded to a status of an entity
I do something like this on most of my workflow entities when i want to track status change on specific

```php
    // the setStatus is called by our implementation of MarkingStoreInterface
    public function setStatus(int $status): self
    {
        $this->status = $status;
        $this->statusLogRecords->add(new MyEntityLog($this));

        return $this;
    }
```

And the `MyEntityLog` have properties like the status (taken from $this), a Gedmo Timestampable (on create) and Blameable (on create), the target entity etc

This PR https://github.com/symfony/symfony/pull/29146 will also allow to re add some comment to this log if oyu need documentation or context :)

**Comment by lyrixx** [comment]
I totally agree with @noniagriconomie 
This is also the solution in mentioned in https://github.com/symfony/symfony/issues/28253#issuecomment-438484545 

I'm really sorry to close your first PR on Symfony, but I can not merge this PR because we are several to prefer the solution proposed by @noniagriconomie 

Anyway, Thanks for your work.

**Pull request closed without merging**
