### PR TITLE
Lock ternary_to_null_coalescing in PHPCS

### PR DESCRIPTION
**Pull request by carusogabriel**
| Q             | A
| ------------- | ---
| Branch?       | 2.7 (be careful when merging)
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25416 
| License       | MIT
| Doc PR        | -

To avoid other developers PR like #25416 :sweat_smile:

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1: for 2.7

**Comment by carusogabriel** [comment]
@nicolas-grekas Gonna change it!

**Comment by keradus** [comment]
this rule is not part of current ruleset, thus there is no need to disable it.
if you want to explicitly disable it to say to other devs it cannot be enabled, then make comment explaining that.

**Comment by keradus** [comment]
(btw, `PHPCS` is different tool than you are touching here)

**Comment by nicolas-grekas** [comment]
Closing in favor of #25556

**Pull request closed without merging**
