### PR TITLE
[DependencyInjection] Use strict comparison operator in XmlFileLoader

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by fabpot** [comment]
What's the point? Or is it the only occurrences left in Symfony that could be converted? I doubt it.

**Comment by dunglas** [comment]
Consistency (`===` is used everywhere else in this file) and score to static analysis tools (using `==` is considered a bad practice by such tools).
Sure they are other occurrences in the codebase. I just found this one by working on this class and "fixed" it.

**Comment by Tobion** [comment]
:+1: we use === as best practice in symfony.

**Comment by stof** [comment]
:+1: Our coding standards are indeed saying to use strict comparison everywhere, unless the type coercion is actually needed to implement the logic (and most of the time, we refactor the logic to avoid it anyway because of weird edge cases of the type juggling)

**Comment by fabpot** [comment]
My point was that it's a lot of work for everyone for a very small benefit. Doing that on the whole code base would be useful though. Anyway, it must be done in 2.3 instead.

**Comment by fabpot** [comment]
Closing as it does not apply cleanly on 2.3 Feel free to reopen on 2.3.

**Pull request closed without merging**
