### PR TITLE
HttpFoundation - uncomment test assertion

### PR DESCRIPTION
**Pull request by keradus**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by Tobion** [comment]
This test seems wrong according to

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

> When this status code is returned for a byte-range request, the response SHOULD include a Content-Range entity-header field specifying the current length of the selected resource (see section 14.16). This response MUST NOT use the multipart/byteranges content- type.

**Comment by keradus** [comment]
So since assertion works the implementation does not follow RFC ?

**Comment by fabpot** [comment]
@keradus Indeed. Can you work on a fix?

**Comment by keradus** [comment]
Sorry @fabpot, I didn't get that deep into RFC.

**Pull request closed without merging**
