### PR TITLE
[PropertyAccess] add more information to NoSuchPropertyException Message

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | no
| Fixed tickets | #24742
| License       | MIT
| Doc PR        | 

Add more context to NoSuchPropertyException as discussed in the issue.

### CODE REVIEW

**Comment by Simperfit** [comment]
fabbot failure is a false positive.

**Comment by Koc** [comment]
Why not cover this change with test using `expectsException`?

**Comment by Simperfit** [comment]
Because I did not find an easy way to do it. But I can look into it to add
one

**Review by dunglas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Simperfit.

**Pull request merged**
