### PR TITLE
[PropertyInfo] Remove useless return statement

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by Tobion** [comment]
Ref. #17201

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Removing useless code is IMO always a good idea.

**Comment by nicolas-grekas** [comment]
Thank you @dunglas.

**Pull request merged**
