### PR TITLE
[FrameworkBundle] fix writes to static $kernel property

### LINKED ISSUE #47186: KerneltestCase: Discrepancy between `self::$kernel` and `static::$kernel`
### Symfony version(s) affected

4.4.39

### Description

I just updated an ancient Symfony 4.4 app and noticed that in release 4.4.39 out unit tests break due to https://github.com/symfony/framework-bundle/commit/cd5273725d4dc32190566051df536e68ceb60be9

After debugging I noticed that this happens because `bootKernel` assigns the new kernel to `self::$kernel`, but a few lines down, the container is read from `static::$kernel`, which in my case is a different class (i.e. my test class extending `KernelTestcase`):

https://github.com/symfony/framework-bundle/blob/3cbca8f6b93681102cab0fe0e3c23d16e4d0ded3/Test/KernelTestCase.php#L80-L83

### How to reproduce
```php
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class MyTest extends WebTestCase
{
    protected static $kernel;

    public function testUserlist()
    {
        static::createClient();
   }
}
```

### Possible Solution

change all occurences to either `self` or `static`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #47186
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by flack** [comment]
I tested this patch against my 4.4 app, and it fixes the issue mentioned in #47186

**Review by derrabus — APPROVED** [review]

**Comment by flack** [comment]
Pleas note that the problem also exists in newer Symfony versions, e.g.:

https://github.com/symfony/symfony/blob/d4042468b11d43f67827f8bee75d3f33fc3170b9/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L74-L77

Should I open a separate ticket for forward ports?

**Comment by xabbuh** [comment]
As I do not understood how this change here is related to forward ports it seems indeed to be better to open a new issue that describes what you have in mind. :)

**Comment by flack** [comment]
Sorry, I'm not sure is forward ports is actually a word, I meant it as the opposite of backports (because this is how you do in Symfony, right? You merge to the lowest branch and then you port forwards from there).

What I meant to say was the confusion between `self::$kernel` and `static::$kernel` also exists in newer branches, including 6.2. So the reproduction code in #47186 (or something similar) would also produce an error on these newer branches

**Comment by xabbuh** [comment]
Oh,  I completely misunderstood your previous comment then. :) I was thinking in terms of forwarded ports when using an HTTP proxy. 😄 I have now merged everything up into the `6.2` branch.

**Comment by flack** [comment]
Awesome, thanks!

**Pull request merged**
