### PR TITLE
[Notifier] Use abstract test cases in 5.x

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | ---
| License       | MIT
| Doc PR        | ---

Same as #39736, but for `5.x`

cc @derrabus

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
I did not merge your changes from #39736 into 5.x because I didn't know how to resolve merge conflicts.

Could you please update this PR to include the relevant changes that should be borrowed from 5.2?

**Comment by OskarStark** [comment]
Sure 👍

**Comment by OskarStark** [comment]
Looks ok now, don't know why two bridges have:
```
Fatal error: Uncaught Error: Class 'Symfony\Component\Notifier\Tests\TransportFactoryTestCase' not found in /home/travis/build/symfony/symfony/src/Symfony/Component/Notifier/Bridge/Discord/Tests/DiscordTransportFactoryTest.php:18
```

```
Fatal error: Uncaught Error: Class 'Symfony\Component\Notifier\Tests\TransportFactoryTestCase' not found in /home/travis/build/symfony/symfony/src/Symfony/Component/Notifier/Bridge/Esendex/Tests/EsendexTransportFactoryTest.php:18
```

but not the other 🤔 

cc @derrabus @nicolas-grekas

**Comment by derrabus** [comment]
Didn't we want to move those abstract test classes out of the Tests folder anyway on 5.x?

**Comment by OskarStark** [comment]
Let's do it a little bit later because IIRC some open PRs for new bridges use it like this, and I want to get them merged before, otherwise it's a never ending story for them to get in 😑

**Comment by derrabus** [comment]
Those failures look like composer hickups to me: Composer could not fetch from git so it fell back to fetching the ZIP. I've rebased the PR to verify my hypothesis.

**Comment by derrabus** [comment]
Thank you Oskar.

**Comment by OskarStark** [comment]
Thanks for the feedback ✌🏻

**Pull request merged**
