### PR TITLE
[Console] Escape command usage

### PR DESCRIPTION
**Pull request by sroze**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24225
| License       | MIT
| Doc PR        | ø

Escape the console usage to prevent arguments named `info` or similar to be formatted.

### CODE REVIEW

**Comment by ro0NL** [comment]
What about markdown formatter? should we use htmlspecialchars there?

**Comment by sroze** [comment]
@ro0NL I'm not sure we should change anything on the Markdown usage for now, I don't see any issue with such arguments.

**Comment by ro0NL** [comment]
AFAIK markdown will render it as HTML tags;

```
<argument>       # shown as HTML; thus not visible
`<argument>`     # shown as code
&lt;argument&gt; # shown text
```

If we already quote using backticks we're good :)

**Review by ro0NL — APPROVED** [review]
I think we should patch 2.7 instead.

**Comment by sroze** [comment]
ping @nicolas-grekas

**Review by nicolas-grekas — APPROVED** [review]

**Comment by chalasr** [comment]
I also think this should be merged as a bugfix in 2.7. @sroze Can you retarget and rebase?

**Comment by sroze** [comment]
Good point. @chalasr rebased and changed target 👍

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @sroze.

**Pull request merged**
