### PR TITLE
[TwigBundle] 'Content-Type' response header match the requested format when generating error pages

### PR DESCRIPTION
**Pull request by damienflament**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no related issue found
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes/no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

The _Content-Type_ response header needs to match the format of the generated response content.

This is obviously useful when an exception is thrown during an XMLHttpRequest handling using JSON content. Currently, the browser (Firefox Developer Edition) handles well the response content and show it as a JSON object. Maybe by looking the request content type or just by recognizing the response content type while parsing it. But the response type is shown as _html_. This PR fix it.

By using the _Request::getMimeType()_ method, we take care of the additional format added by the developer.

### CODE REVIEW

**Comment by damienflament** [comment]
There is a test failure because I pass the exception status code to the created Response object instead of the default 200 HTTP status code. But returning a 200 HTTP status code seems unsuitable when showing an error.

**Comment by fabpot** [comment]
@damienflament Can you rebase this pull request?

**Comment by damienflament** [comment]
' i8 messages ' u>{, 'y Le 6 juil. 2017 08:fffddd' ' ' fff' ' fiofrr552 flament flament , Fabie5, n Potencier - flament g<notifih' 73gcations@github.com> a écrit :n@damienflament Can you/6^7hi rebase this ☆¿¤¤¡¿+uu request?\]' u >messages 6>6

—8 XxxxxxxxxxP5£$55$565@ @ @ @ flament 


  
  




@ gmail messages@ gmail messages messages messages messages wwpw7u77aW

**Comment by nicolas-grekas** [comment]
Fixed in #23052

**Pull request closed without merging**
