### PR TITLE
[HttpKernel] Deprecate single-colon notation for controllers

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Tickets       | -
| License       | MIT
| Doc PR        | todo

### CODE REVIEW

**Comment by chalasr** [comment]
Ready

**Review by fabpot — APPROVED** [review]

**Review by nicolas-grekas — COMMENTED** [review]
missing CHANGELOG entry :)

**Comment by chalasr** [comment]
CHANGELOG updated

**Comment by nicolas-grekas** [comment]
Thank you @chalasr.

**Pull request merged**
