### PR TITLE
[DependencyInjection] register alias after defining the class

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
renaming is hard :)
:+1:

**Comment by xabbuh** [comment]
Maybe we should add the process to the docs. :D

**Review by Jean85 — CHANGES_REQUESTED** [review]
Why not use my latest approach? https://github.com/symfony/symfony/pull/21088/commits/1e29773436b7025b9bd00e8a85c93fddac4abcc3

In this way, the file that is getting deprecated will contain the `class_alias`, and will be deleted altogether in next major, without touching the new class

**Comment by nicolas-grekas** [comment]
Because 1e29773 doesn't work: the alias mit be defined alongside the aliased class so that instanceof checks work as expected.

**Comment by Jean85** [comment]
But @nicolas-grekas the change does work! See the build status in my PR #21088 from which I extracted the prev. commit.

If you look at 41f995e92e3d7d0227b6fe009737cf5ea27b9449 I've added new assertion to the test to see that the `instanceof` works for both class definitions, the old (deprecated) and the new; it should work since the autoloader will attempt to load the old definition, finding the old file, which contains the `class_alias`, hence making it work.

**Comment by nicolas-grekas** [comment]
It works because you already loaded everything.
The broken scenario is:
load TraceableAccessDecisionManager
check an instance of it against DebugAccessDecisionManager

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by Jean85** [comment]
@nicolas-grekas nope. As you can see, I've added your case too here: 78c8e0894491b6405776a924871fff5eef4ca29e
And the build is green: https://travis-ci.org/symfony/symfony/builds/187649329

**Pull request merged**
