### PR TITLE
[FrameworkBundle][Validator] Remove deprecated ConstraintValidatorFactory

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | yes
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #22905
| License       | MIT
| Doc PR        | N/A

Follows #22905

### CODE REVIEW

**Comment by chalasr** [comment]
I thought we would fully avoid storing instances from the container (i.e. remove the `$validators` property). Is there much interest to keep it? We did remove a similar one from the ServiceLocator class in https://github.com/symfony/symfony/pull/22029

**Comment by ogizanagi** [comment]
I think keeping this internal cache is cheap and still worth it, but no strong opinion on this.

I think #22029 was motivated by the fact the memoization was useless when used with the symfony DI container and prevents from using properly non-shared services.
This one can be used with any PSR-11 implementation, which may or may not cache instances (unless it's specified as required by the PSR?) and we also create instances on the fly.

BTW, this makes me think this implementation can be moved to the `Validator` component instead of keeping it in the `FrameworkBundle`, as anyone should be able to use this `ContainerConstraintValidatorFactory` without using the framework bundle.

**Comment by chalasr** [comment]
> and we also create instances on the fly.

fair enough to me!

**Comment by ogizanagi** [comment]
See https://github.com/symfony/symfony/pull/22905 about moving the class in the component (and keep only one deprecation rather than the current three in 3.3)

**Comment by ogizanagi** [comment]
On hold (waiting for 3.3 branch to be merged in upper branches to get #22905).

**Comment by chalasr** [comment]
This can be closed

**Comment by ogizanagi** [comment]
@chalasr : Not exactly, as the changelog is still missing an update. That's why I kept this opened in case it was not entirely done during the merge. Anyway, see https://github.com/symfony/symfony/pull/22926 then :)

**Pull request closed without merging**
