### PR TITLE
[Notifier] [FakeSms] Add missing LICENSE and .gitattributes file

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no 
| Deprecations? |  no 
| Tickets       |  | License       | MIT
| Doc PR        | 

cc @nicolas-grekas

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Didn't you want to add these files to #40647? I don't understand why this PR?

**Comment by OskarStark** [comment]
> Didn't you want to add these files to #40647? I don't understand why this PR?

Sure, I added them in the new PR and spotted they were missing in this bridge too 😄

**Review by nicolas-grekas — COMMENTED** [review]
Indeed

**Comment by nicolas-grekas** [comment]
Thank you @OskarStark.

**Pull request merged**
