### PR TITLE
Fix type in collect() method comment

### PR DESCRIPTION
**Pull request by vladapopster**
| Q | A |
| --- | --- |
| Branch | 2.3 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | https://github.com/symfony/symfony/issues/18088 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by vladapopster** [comment]
Retest.

**Comment by javiereguiluz** [comment]
@vladapopster thanks for this contribution! You did it great .. .except for one minor issue. You removed the `Branch` row in the table that you must fill in for pull requests.

Maybe the human reviewers may not notice this error ... but Symfony uses a robot called "fabbot" which always notices this kind of things. This is why in your pull request, you can see an error message in the list of checks:

fabbot_error

To fix it, you just need to readd the `Branch` row and add the appropriate value. These are the rules:

  * If it's a new feature, select "master"
  * If it's a bug, select the oldest (but maintained) Symfony branch which suffers that error.

In this case it's a bug and the oldest maintained branch who suffers the issue is 2.3, so you need to put 2.3 as the value of the Branch row in the table. Thanks!

**Comment by vladapopster** [comment]
@javiereguiluz Thanks for the tip. I have added `Branch` to description, so should be fine now, just to find a way to restart build.
P.S i used example from [this] (http://symfony.com/doc/current/contributing/code/patches.html#make-a-pull-request) docs page, where `Branch` is not included in a table.

**Comment by javiereguiluz** [comment]
@vladapopster thank you! And thanks too for pointing to an error in our contributing guide. I've just created an issue in the Symfony Docs repository (https://github.com/symfony/symfony-docs/issues/6357) to not forget about this error and fix it soon. Thanks!

**Comment by javiereguiluz** [comment]
About restarting the build ... I can do that for Travis ... but I can't do that for fabbot (I'm sorry!)

**Comment by javiereguiluz** [comment]
A note to you from Symfony maintainers:

Thank you for making this contribution to Symfony. As you know, we prepared some simple issues so you could submit real pull requests fixing real issues. However, as there are more people than issues, we'll need to close some repeated pull requests without merging them.

We are not sure about the criteria we'll use to close repeated pull requests (first one wins? randomly selected one wins?). So maybe your pull request is closed without merging it. But please, don't feel bad about that. You did great and you actually contributed to Symfony :tada: If this pull request doesn't get merged, there will be more opportunities to send new pull requests.

Thank you for being part of the (big and awesome) Symfony Community!

**Pull request closed without merging**
