### PR TITLE
[Security] improved phpdoc.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

The doc was changed in 2.8 when introducing the new Guard system but I think we should backport this new improved phpdoc block in the 2.3 branch.

### CODE REVIEW

**Comment by hhamon** [comment]
@nicolas-grekas appveyor failed but I just changed a phpdoc comment.

**Comment by hhamon** [comment]
Ping @stof @weaverryan @nicolas-grekas @xabbuh for review.

**Comment by weaverryan** [comment]
Obviously, :+1: on the small change. And yes, I think it makes sense to backport this to the 2.3 branch too. @hhamon I'm not sure this will apply very cleanly to the 2.3 branch: it might be better to make a PR against the 2.3 branch with ALL of the changes there (my changes + your fix).

And see you in a few hours ;)

**Comment by stof** [comment]
this makes sense to backport it indeed

**Comment by hhamon** [comment]
Good! I'm gonna close this PR and reopen it against 2.3 branch this evening ;)

@weaverryan see you later ^^

**Comment by hhamon** [comment]
See https://github.com/symfony/symfony/pull/16936

**Pull request closed without merging**
