### PR TITLE
[ClassLoader] Deprecate Apc/WinCache/Xcache class loaders

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

See https://github.com/composer/composer/pull/5559

### CODE REVIEW

**Comment by stof** [comment]
should we also deprecate WinCacheClassLoader and XcacheClassLoader providing similar wrappers with other storages ?

Btw, if we deprecate these caching loaders, and we deprecate the ClassCollectionLoader, the component will only contain the basic PSR-0, PSR-4 and classmap loaders, which are all useless when using composer. So we may want to deprecate the whole component instead.

**Comment by nicolas-grekas** [comment]
@stof I added WinCache and Xcache to this PR. I agree with you about deprecating the component, should be done in another PR (esp. HttpKernel\Client is using the component right now, it needs some work to be freed from it).

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by Koc** [comment]
@stof there is also debug class loader that suggests how to deal with class not found errors

**Comment by stof** [comment]
@Koc no. DebugClassLoader is in the Debug component, not in the ClassLoader component

**Pull request merged**
