### PR TITLE
[FrameworkBundle][Routing] Minor improvement - No `array_merge` in loop

### PR DESCRIPTION
**Pull request by simonberger**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License | MIT

A tiny (here) performance improvement in moving an array_merge out of a foreach.
Added tests  for those lines which were missing.

I started to move more array_merge(_*) calls out of loops where it makes sense. In some cases the impact could be more relevant than in this small loop. I see this as a test. 

Should i add further changes as a combined, single or component based pull request and is 5.4 the correct target?

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by fabpot** [comment]
Do you have any numbers to share to back up the performance improvement?

**Comment by simonberger** [comment]
@fabpot Good point. I just heard up to this point it is slower and can require a lot of memory.
I created a quick script. Let me know in case I did a mistake somewhere. The numbers show a much more dramatic difference than I had expected.

```php
<?php
$arr = [];

$startTime = microtime(true);
for ($i = 0; $i < 20000; ++$i) {
    $arr = array_merge($arr, ['a'.$i, 'b'.$i]);
}
$endTime = microtime(true);

echo "array_merge in loop took: " . number_format($endTime - $startTime, 3) . " Seconds \n";

$arr = [];

$startTime = microtime(true);
for ($i = 0; $i < 20000; ++$i) {
    $arr[] = ['a'.$i, 'b'.$i];
}
$arr = array_merge([], ...$arr);
$endTime = microtime(true);

echo "array_merge out of loop took: " . number_format($endTime - $startTime, 3) . "Seconds \n";
```

```
array_merge in loop took: 3.017 Seconds 
array_merge out of loop took: 0.008 Seconds 
```

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
I can see the perf boost on many iterations, but here, we are talking about a few schemes and/or a few methods. So, maybe it's not worth it after all.

**Comment by simonberger** [comment]
Yes I agree there won't be a any notable difference here. We have 1 to a maximum of three iterations, but it also won't have any negative impact and there are a few analyzers out there marking an array_merge in a loop as an error.

I already changed places which should have a real impact.

**Comment by fabpot** [comment]
Thank you @simonberger.

**Pull request merged**
