### PR TITLE
[HttpClient] Let curl handle Content-Length headers

### LINKED ISSUE #45709: Post with redirected response in HttpClient 5.4.5 throws a 408 error (worked properly on HttpClient 5.4.3)
### Symfony version(s) affected

5.4.5

### Description

When an HttpClient post request is made, and the response returns a redirection, a 408 error is thrown by HttpClient.
This works properly until 5.4.3 version but not in version 5.4.5

### How to reproduce

// $url is a vble like http://my.domain1:8000
// $headers[] = 'Content-Type: application/x-www-form-urlencoded';
// $params is an array form
$client->request('POST', $url, ['headers' => $headers, 'body' => $params]);

Error given: 
HTTP/1.1 408 Request Timeout returned for "..." . (Symfony\Component\HttpClient\Exception\ClientException)

Note the post will be made to an http scheme and redirected to another url, with a different subdomain (http scheme as well), but that is not the issue because works properly in 5.4.3

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #45709
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by xabbuh** [comment]
What about the `NativeHttpClient`?

**Comment by nicolas-grekas** [comment]
It already handles the situation.

**Comment by nicolas-grekas** [comment]
https://github.com/symfony/symfony/blob/2f27b39add8c8cdf7c70f2acfe8c9905eb56dfcc/src/Symfony/Component/HttpClient/NativeHttpClient.php#L384

**Comment by xabbuh** [comment]
From the little tests that I did that line is not enough and the patch as I did it in #45799 was needed too.

**Comment by nicolas-grekas** [comment]
Strange. Can you send a failing test case? Because the one I added here was fine with Native but hanging with Curl.

**Pull request merged**
