### PR TITLE
[Mime][HttpFoundation] Added mime type audio/x-hx-aac-adts

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Replaces #31464

### CODE REVIEW

**Comment by fabpot** [comment]
Shouldn't we contribute that change upstream? Because it will be lost next time we sync with the Apache list.

**Comment by nicolas-grekas** [comment]
I agree, @ifaridjalilov here are the two files we use a a source
https://github.com/minad/mimemagic/blob/master/script/freedesktop.org.xml
and
https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
Could you submit this update there please?

**Comment by nicolas-grekas** [comment]
@fabpot I just ran the `update_mime_types.php` and the additions were not removed, so this is safe.

**Comment by nicolas-grekas** [comment]
Thank you @ifaridjalilov.

**Pull request merged**
