### PR TITLE
[Console] Output Formatter Decorator

### PR DESCRIPTION
**Pull request by secondtruth**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | none |
| License | MIT |
| Doc PR | none |

OutputFormatter uses the Decorator to apply Styles to text

### CODE REVIEW

**Comment by secondtruth** [comment]
@stof Reverted the BC break. I hope my solution is okay.

**Comment by stof** [comment]
I don't really see the benefit of this refactoring. Can you describe the reasons for it ?

**Comment by secondtruth** [comment]
The current `OutputFormatter` is too specific. This means it is intended only for real consoles and this makes it harder to implement Formatters for other types of consoles (like 'web consoles').

My solution is a bit cleaner because the interface is generic. It avoids unclean solutions like this:

https://github.com/CoreSphere/ConsoleBundle/blob/master/Formatter/HtmlOutputFormatterDecorator.php

**Comment by stof** [comment]
@secondtruth my preference to provide a web rendering of the console is to use https://github.com/sensiolabs/ansi-to-html. the advantage of this solution is that it does not require any change to the console application being called.

**Pull request closed without merging**
