### PR TITLE
Added an alias for FlashBagInterface in config

### PR DESCRIPTION
**Pull request by tifabien**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]
for 3.4 as a new feature to me

**Comment by fabpot** [comment]
Somewhat related: #11279 and co

**Comment by chalasr** [comment]
Regarding #11279, would it make sense to make this service available in AbstractController?

**Comment by nicolas-grekas** [comment]
@chalasr in practice a `Session` instance is always provided. With this alias ppl could at least type hint a controller/action argument. Isn't it enough?

**Comment by chalasr** [comment]
Indeed!

**Review by chalasr — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]
as a feature in 3.4

**Comment by tifabien** [comment]
Do I need to rebase my branch on top of 3.4 or is it not necessary?

**Comment by nicolas-grekas** [comment]
Thank you @tifabien.

**Pull request closed without merging**
