### PR TITLE
[Intl] Switch from json to php resources

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #23545
| License       | MIT
| Doc PR        | -

take over #34214

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
In `PhpBundleReader`, I think we should remove the `file_exists()` check and keep only the `is_file()` one, for perf.

:+1: otherwise

**Comment by ro0NL** [comment]
do we fancy cleaning up other readers/writers while at it? e.g.TextBundleWriter only receives cs fixes as of 2014 :}

**Comment by jderusse** [comment]
RFR
Version bumped to 69.1,
Optimization suggested by @nicolas-grekas applied
tested fixed

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.

**Comment by bastnic** [comment]
FYI, on symfony demo app:
 
image

**Pull request merged**
