### PR TITLE
[Translation] [Crowdin] Use synchronous HTTP requests when reading the Crowdin API

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Hi!

We are migrating to Crowdin and we faced `429 Too Many Requests issues` when pull translations, because we have a lot of locales and domains in our application, and [Crowdin limits 20 parallel requests per account](https://developer.crowdin.com/api/v2/#section/Introduction/Rate-Limits). 

image

This is like #44416, but for Crowdin :)

Thanks.

### CODE REVIEW

**Comment by stof** [comment]
If the limit is 20 concurrent requests and not 1, we don't need to use synchronous requests. We only need to limit concurrency to 20.

**Comment by nicolas-grekas** [comment]
Can you try forcing HTTP/1.1? Because the default is to open max 6 connections the remote hosts. If we hit the 20 limit, it means we're using HTTP/2. If that works, then the fix could be just to force the `http_version` in the constructor:
`$this->client = $client->withOoptions(['http_version' => '1.1']);`

**Comment by Kocal** [comment]
Thanks for your suggestions, putting a limit of 6 or 20 concurrent requests won't really work in our case, since we pull translations locally, in our CI, and when deploying our app in review apps / staging / production.

Putting a limit of 1 would be ideal for us, this way we can be sure that we won't hit the Crowdin's concurrent requests limit across envs.

**Comment by stof** [comment]
Maybe the provider should also wrap the client into a RetryableHttpClient

**Comment by nicolas-grekas** [comment]
> putting a limit of 6

Can you still give it a try? 3x6 = 18 so that might work.

**Comment by nicolas-grekas** [comment]
Closing as we're likely not going with this approach. Please let us know if force http 1.1 is enough in practice.

**Comment by Kocal** [comment]
Yeah I gonna try to force HTTP 1.1, or playing with max host connections option ASAP

**Pull request closed without merging**
