### PR TITLE
Redesigned the exception pages

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20620
| License       | MIT
| Doc PR        | -

Here are some before/after screenshots:

| Before | After
| --- | ---
| exception-before-1 | exception-after-1

| Before | After
| --- | ---
| exception-before-2 | exception-after-2

| Before | After
| --- | ---
| exception-before-3 | exception-after-3

---

And here is the new design in action because everything is very dynamic and you can click anywhere to reveal/collapse things:

exception-in-action

### CODE REVIEW

**Comment by Tobion** [comment]
Nice work! Looking at the screenshots, I saw that the plain text stack traces do not include function parameters anymore. E.g. it only says `call_user_func_array` without the parameters (as in  the html stack traces). Is this on purpose? Looks like valuable info is lost there.

**Comment by stof** [comment]
@Tobion good catch, I missed this change.

I think that the plain-text version should keep the args, otherwise copy/pasting the plaintext trace in a bug report will give only partial info

**Comment by javiereguiluz** [comment]
@Tobion @stof yes, that's done on purpose. The main reason is that I wanted to have the same stack traces as the rest of the industry (from Java to Node.js). @stof made me change it a bit to display the (ugly) full namespace of the classes. But I don't think adding the args is necessary there. Java, Node.js, etc. don't do that and we already show that information in the first panel, which is where a developer should always look for info (the stack trace is to just share some info about the exception with other colleagues or publicly).

Another reason is that arguments can contain highly sensitive information. In the Symfony repo we regularly ask users to share the stack traces. We don't want them to share critical information. That's why we also remove your local project directory in the file paths (the first panel shows the absolute file paths when you put your mouse over the file paths, but the stack traces only shows paths relative to the project root directory).

**Comment by mvrhov** [comment]
@javiereguiluz: Please take a look on how tracy/tracy does it. We've replaced the default exceptions with that via TracyBundle in all of our projects. The exceptions are a lot more detailed and having having dumps deduped in production in the log directory is invaluable.

**Comment by wouterj** [comment]
Very nice job @javiereguiluz! Some little notes:

 * Looking at [a previously proposed PR](https://github.com/symfony/symfony/pull/15792) to improve the exception page, can we maybe use the var-dumper for the arguments in the detailed trace? This would be more awesome than just having `object(Post)`.
 * Can we use the var-dumper colors in the code example, to make all colorscheme's consistent throughout exception page - profiler page - dump output?
 * The top sections of the page look way to dense compared to the below sections. This ratio doesn't seem to be 100% correct. Can we maybe add some vertical whitespace at the top? (e.g. the red box with the exception message in it).
 * Not sure about this one, but the second exception seems more hidden than in the original design (at first, I couldn't find the second exception at all). This is a bit of a problem, as the second exception is often more usefull than the first one (e.g. with Twig or file loader exceptions).
 * You probably are already aware of this, but the basic exception page that's triggered when a fatal error occurs also need to be updated: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Debug/ExceptionHandler.php#L203-L393

**Comment by King2500** [comment]
In the sense of DX I suggest the visible source snippet should be the first user land code, not from vendor/* libraries. What do you think?

**Comment by javiereguiluz** [comment]
(I haven't replied to most of your comments yet ... but I'm reading them with keen interest, so please keep adding comments and proposing changes. Thanks!)

**Comment by robfrawley** [comment]
@javiereguiluz 

First off: amazing work. Love the direction. Think this should absolutely be the basis for whatever eventually makes it into `master`. I'll be adding some more comments (re: the code itself) but as for the design:


- The top section needs some additional vertical space. The first row (black) is fine, but the two below it should have more verticle space.
- Second row order (with left chevron) seems "off" to me, would prefer the items were reverse with right chevron.
- Syntax highlighting has too much red: there is enough red elsewhere and that makes it overpowering. Can we use a colorful syntax highlighting?
- *Very strongly* think the stack trace should remain intact (include parameters). The information provided there can be very important to understand context and provide a valuable resolution. Someone posting sensitive information should be their own responsibility.
- On "Exceptions" tab, the InvalidArgumentException doesn't have the message under it as Twig_Error_Loader does; what happens if there are more than two exceptions with the sub-text (the exception message)?

**Comment by robfrawley** [comment]
As @mvrhov mentioned, [nette/tracy](https://tracy.nette.org/) does a really nice job; it is definitely worth taking a look at their [live](https://nette.github.io/tracy/tracy-exception.html) [examples](https://nette.github.io/tracy/tracy-error.html) to glean some inspiration for this Symfony exception page re-design/re-write. I love the simplicity, yet the power, of the call stack functionality.

**Comment by sstok** [comment]
I think it would be useful to include the Environment, HTTP request, HTTP response as this could be related to the failure.

Concerning the parameters, is it possible add a JavaScript toggle to hide/show them?

**Comment by gaetan-petit** [comment]
The red header is a bit too much.
My suggestion: just keep the red line mentioning the error and the HTTP code status.
Go back to grey for the error message and ghost.

**Comment by sstok** [comment]
@gaetan-petit I'm having mixed feelings on that, the exception only happens when something is wrong and red indicates danger giving you a direct indication something is wrong, so only the upper bar would a bit small.

But when you use a dark UI or can't bare bright colors I can imagine this would be to much.
*I have actually spend 10 years daily on a website where the main color was red and white. So I'm used to bright colors* 😄

**Comment by robfrawley** [comment]
@gaetan-petit I actually like the move away from dull grays, on both the redesigned debug toolbar and profiler pages, as well as this new exception redesign.

**Comment by stof** [comment]
@javiereguiluz what is the status of this PR ? Are you continuing the work ?

**Comment by javiereguiluz** [comment]
Yes, I'm continuing the work ... but I'm taking a break here to think about your comments and proposals.

**Comment by fabpot** [comment]
Any news? Do we want this to be ready for 3.3?

**Comment by javiereguiluz** [comment]
I'll have this ready for Symfony 3.3 (we're still 7 weeks away from the "feature freeze"). I want to make some of the changes proposed by reviewers.

**Comment by fabpot** [comment]
Last call for 3.3.

**Comment by javiereguiluz** [comment]
OK, I've updated this PR to make it mergeable.

---

I've made these changes as requested by reviewers:

* Fixed all errors spotted by @stof (thanks for the review!)
* Moved icons/images to individual image files
* Added some vertical white space to the main exception message
* Reversed the order of the chained exceptions: "Parent > Child 1 > Child 2" instead of "Child 2 < Child 1 < Parent"
* Reduce the font size when the main exception message is long
* Instead of always expanding the first code snippet, now the first code snippet that belongs to the application is expanded
* Included again all the function/method arguments in the text-based trace

I've decided to ignore these suggestions:

* "Too much red" *(I think it has the appropriate amount of red for an exception page ... but I can be wrong, and we'll see that when people actually use this page and give more feedback)*
* "Use VarDumper for arguments" *(This behavior is very different from the existing exception page, and I'm afraid of the performance penalty that could introduce hundreds of calls to VarDumper. I'd recommend to try to make this change in Symfony 3.4)*

**Comment by robfrawley** [comment]
@javiereguiluz Looks like this will be a great change. Can't wait for its inclusion!

**Comment by javiereguiluz** [comment]
The failing tests on AppVeyor are unrelated. Please tell me if I can do anything else to make this mergeable for 3.3. Thanks!

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Comment by sstok** [comment]
It seems something is broken 😭 cleared, cache bootstrap file, assets. No dice.
In Firefox it's broken, but it works in chrome 🤔

schermafbeelding 2017-04-06 om 16 55 24

**Pull request closed without merging**
