### PR TITLE
[Validator] Preserve original timezone on formatted dates with the IntlDateFormatter

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/33434/files#r320128185
| License       | MIT
| Doc PR        | -

Thank you @ro0NL for finding this 😄

### CODE REVIEW

**Comment by yceruto** [comment]
Could we a test case for this? thanks!

**Comment by fancyweb** [comment]
Tests are in https://github.com/symfony/symfony/pull/33434. Because I had a wrong branch target there, I opened this one targeting 3.4. But actually both target 3.4.

**Comment by yceruto** [comment]
what about move them to here?

**Comment by fancyweb** [comment]
I'm just gonna cherry-pick in the other branch.

**Pull request closed without merging**
