### PR TITLE
[SecurityBundle] Made 2 service aliases private

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

We missed making them private :(
Is it too late to fix that?

### CODE REVIEW

**Comment by Hanmac** [comment]
i don't like it to make `security.authorization_checker` private.
i have many bundles in my projects (like Sonata, or Sensio) which does use this service for the isGranted check. what else should be used for that?

**Comment by nicolas-grekas** [comment]
@Hanmac this is making 
Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface
and
Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface
private,
it doesn't change anything when using security.authorization_checker

**Review by chalasr — APPROVED** [review]

**Comment by stof** [comment]
I'm 👍 for this, as we never documented these aliases (they are there for autowiring purpose only)

**Review by xabbuh — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
