### PR TITLE
Tgalog translations for security and validation messages.

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | no
| Fixed tickets | none 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@ergiegonzaga thanks for contributing this translation! However, there are some issues that we need to fix: instead of creating a new translation for Tagalog, you modified the translation for Arabic. This is how we can fix it:

1) Copy the `src/Symfony/Component/Security/Core/Resources/translations/security.en.xlf` file into a new file called `src/Symfony/Component/Security/Core/Resources/translations/security.tl.xlf` (`tl` is the code for the Tagalog language.
2) Make the translation in the new `security.tl.xlf` file ... you must keep the original English contents in `<source> ... </source>` and you must write your translations in the `<target> ... </target>` nodes.
3) Do the same for `validators` translation: copy `src/Symfony/Component/Validator/Resources/translations/validators.en.xlf` into a new file called `src/Symfony/Component/Validator/Resources/translations/validators.tl.xlf`, keep the `<source> ... </source>` contents unchanged and add your translations in `<target> ... </target>`.
4) Revert the changes you made in the `src/Symfony/Component/Security/Core/Resources/translations/security.ar.xlf` and `src/Symfony/Component/Validator/Resources/translations/validators.af.xlf` files.

Thank you!

**Comment by stof** [comment]
On a side note, you should generally not use your `master` branch to open pull requests. This will cause your master branch to be out of sync with the upstream one, making it harder for you on your next contribution.

**Comment by ergiegonzaga** [comment]
okay sir, how do i revert the changes I made in the
src/Symfony/Component/Security/Core/Resources/translations/security.ar.xlf
and src/Symfony/Component/Validator/Resources/translations/validators.af.xlf
 files.

**Comment by stof** [comment]
@ergiegonzaga the simpler solution is to start a new PR using a feature branch created from the Symfony master (so starting clean).

**Comment by javiereguiluz** [comment]
The easiest way to revert is to:

1) Copy these contents -> https://raw.githubusercontent.com/symfony/symfony/master/src/Symfony/Component/Security/Core/Resources/translations/security.ar.xlf and paste them into `src/Symfony/Component/Security/Core/Resources/translations/security.ar.xlf`
2) Copy these contents -> https://raw.githubusercontent.com/symfony/symfony/master/src/Symfony/Component/Validator/Resources/translations/validators.af.xlf into `src/Symfony/Component/Validator/Resources/translations/validators.af.xlf`
3) Commit those changes and push them.

**Comment by ergiegonzaga** [comment]
Okay sir i am already doing it now.

**Comment by ergiegonzaga** [comment]
hi sir, I already submitted a new pull request, please take a look at it.

**Comment by xabbuh** [comment]
closing in favour of #26114

**Comment by ergiegonzaga** [comment]
I also included in that pull request the reverted files that I have made
earlier sir..

**Pull request closed without merging**
