### PR TITLE
[HttpKernel] Fix missing psr/cache dev requirement

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes, tests are broken
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Because #20810 added a test for the `Psr6CacheClearer` that mocks methods of the `CacheItemPoolInterface`. It should fix the travis build on master and deps=low

### CODE REVIEW

**Comment by ogizanagi** [comment]
Good catch 👍 

To me should solve the failing test, but let's see.

**Comment by ogizanagi** [comment]
🎉 

Status: Reviewed

**Comment by xabbuh** [comment]
:+1:

Status: Reviewed

**Comment by nicolas-grekas** [comment]
Thank you @chalasr.

**Pull request merged**
