### PR TITLE
[Form] Add "range" type #11979

### PR DESCRIPTION
**Pull request by Kryniol**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #11979 |
| License | MIT |

I've taken over https://github.com/symfony/symfony/pull/12693, added tests for rendering and building the form field and fixed some parts. The linked PR could be probably closed if this one is OK. This is my first PR to the Symfony2 repo so please let me know if anything is missing.

### CODE REVIEW

**Comment by jaytaph** [comment]
Maybe  [ValidatorTypeGuesser](https://github.com/symfony/symfony/blob/7c026bb33e8ca96b285402f7fe7ae27a04a74ea9/src/Symfony/Component/Form/Extension/Validator/ValidatorTypeGuesser.php#L153)  should also return this range type when the range contraint is found.

**Comment by Kryniol** [comment]
@jaytaph I'm not sure, this would certainly be a BC breaker...

**Comment by jaytaph** [comment]
@Kryniol yes, you are right. But it would make more sense to have it guessed to range whenever there is a range constraint.. Maybe this could be postponed to 3.0 (if it's still a good idea)

**Comment by Kryniol** [comment]
I think it's really nice feature for 3.0. I could take care of that after this PR is done, for now I'm struggling with Travis.

**Comment by lucascherifi** [comment]
+1

**Comment by webmozart** [comment]
This was added in #12067. Thanks for the PR @Kryniol!

**Pull request closed without merging**
