### PR TITLE
[DoctrineBridge] forward-compatibility with field mappings in Doctrine ORM 4

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

see doctrine/orm#11211

### CODE REVIEW

**Comment by fabpot** [comment]
Do we need to do it on 5.4?

**Comment by derrabus** [comment]
> Do we need to do it on 5.4?

Yes.

**Comment by xabbuh** [comment]
rebased on 5.4

**Review by derrabus — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
