### PR TITLE
Fix generated HTML code for file syntax highlighting

### PR DESCRIPTION
**Pull request by michaelperrin**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | 
| License       | MIT
| Doc PR        | N/A

I realized that the syntax highlighting made of the code triggering an error is not HTML valid, as there are some extra closing `</span>` tags. If you look at the generated HTML code of this error shown in Symfony's profiler (I would appreciate if you don't make fun of my division by zero to trigger purposely an error 😅):

ghost

You will see the invalid extra `</span>` tags (shown in red here):

span

I tried to figure out why this code was written, in the `fixCodeMarkup` method. It leads to this commit of @fabpot : https://github.com/symfony/symfony/commit/eb7cbb77ec9ff4ca8143679ed66c0c9b94e08413#diff-bf4b3d6db506c41af5fa9306031e0a61R194

The commit message refers to an issue that was on the old Trac issue tracker (issue 9044) used back in the symfony 1 era. Which is fun actually, but doesn't help much on why this method was written, and I could not figure out any case when some missing `</span>` closing tags need to be added.

I supposed it was needed though, and just kept the purpose of the function and fixed it.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Would it be possible to add a test case?

**Comment by michaelperrin** [comment]
@nicolas-grekas Do you mean a unit test or something to see the issue now?

In the second case:

1. Create a traditional web application Symfony project
2. Create a controller and add a route in it to trigger an error (throw an exception, make a division by zero, etc.).
3. Access to the page that triggers the error. The error in the code is shown by Symfony.
4. View the source of the page (not using the debugger, but just plain page source).
5. You will see some extra `</span>` ending tags in the code inside the `class-code` CSS element.

**Comment by nicolas-grekas** [comment]
A unit test yes, if possible.

**Comment by michaelperrin** [comment]
I am closing this issue because after further tests, there was no easy (or non-dirty) way to fix the HTML syntax error due to the way `highlight_file` PHP function generates HTML and the way we try to split lines of codes.
An extra `</span>` doesn't heart to much here, and it's been there since the very beginning of Symfony 2 (preview releases).

**Pull request closed without merging**
