### PR TITLE
swiftmailer bridge is gone

### PR DESCRIPTION
**Pull request by bendavies**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT

Swiftmailer bridge appears to be gone.
Bit confused as to which branch this should be submitted against.

### CODE REVIEW

**Review by dunglas — APPROVED** [review]
Good catch, it will be removed in 4.0.

**Comment by sstok** [comment]
It seems to be gone since 3.0?

**Comment by dunglas** [comment]
@sstok indeed, this should be merged in 3.0.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @bendavies.

**Comment by fabpot** [comment]
merged by mistake on master, cherry-picked on 3.2.

**Pull request merged**
