### PR TITLE
change accessibility for getStepWidth to public

### PR DESCRIPTION
**Pull request by tflori**
| Q             | A
| ------------- | ---
| Branch?       | 3.0
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

In line 573 the method is used from outside (a closure that gets any object of class `ProgressBar` or a subclass of it). So the method has to be public. It's magic that it is working and not good coding style.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Closures have scope. The one calling getStepWidth has the same scope than the object, so that calling private methods there is perfectly legal. Not a bug.

**Comment by tflori** [comment]
extend the progressbar don't overwrite anything and it will fail. it is a public access. the other way around this bug is to call `$this->getStepWidth()` but every other method called in these closures is public and then  not the bar from parameter is used...

**Comment by stof** [comment]
please give a reproducing case.

**Comment by tflori** [comment]
```php
<?php

use Symfony\Component\Console;

class MyProgressBar extends Console\Helper\ProgressBar
{
}

$progressBar = new MyProgressBar(new Console\Output\ConsoleOutput(), 10);
for ($i = 0; $i < 10; $i++) {
  $progressBar->advance();
}
```

**Comment by stof** [comment]
hmm, maybe PHP < 7 had a bug with closure scoping there. This looks weird. `self::initPlaceholderFormatters` should always be calling the static method in the scope of the ProgressBar, not of MyProgressBar.

**Comment by stof** [comment]
in any case, this PR cannot be merged in the 3.0 branch, which is unmaintained since a long time: http://symfony.com/roadmap?version=3.0#checker

**Comment by stof** [comment]
well, lowest maintained version

**Comment by tflori** [comment]
no will have to close and create a new one...

**Pull request closed without merging**
