### PR TITLE
Do not throw away indices from Var Exporter

### PR DESCRIPTION
**Pull request by simPod**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

The Var Exporter component was throwing away array indices, eg. when exporting array `[1=>1, 2=>2]`, it exported `[1 => 1, 2]`. This fixes this faulty behaviour, however, it preserves indices everywhere. That is IMHO the correct way as there's no safe way to detect whether array indices are explicit or just implicit.

### CODE REVIEW

**Review by OskarStark — COMMENTED** [review]
Unlike the improvement of the provideExport() method but my feelings about keeping all indices are 👎 Indeed your case looks wrong, but couldn’t we preserve the old behavior and fix your bug too?

**Comment by nicolas-grekas** [comment]
Hi, thanks for the PR, but that's not a bug. Not displayed indices are increasing numbers from the last explicit indice. That matches how PHP indices work.

**Comment by simPod** [comment]
How do you propose to solve it then? Scanning the whole array and checking whether indices are sequence or not doesn't sound very performance sensitive to me. Especially for larger arrays.

**Comment by nicolas-grekas** [comment]
I propose to close as this output is expected.

**Comment by simPod** [comment]
For array `[100 => true, 101 => true]` is not expected output `[100 => true, true]`

**Comment by nicolas-grekas** [comment]
To me it is, and the code matches :)
See https://3v4l.org/CXXvn

**Comment by simPod** [comment]
Got it. I'll show you my use case:

Consider this array:

```php
[
    20 => true,
    21 => true,
    5 => true,
    3 => true,
    80 => true,
    81 => true,
    82 => true,
    120 => true,
    150 => true,
    1 => true,
    9 => true,
    10 => true,
    60 => true,
    61 => true,
    62 => true,
    8 => true,
    50 => true,
    51 => true,
    100 => true,
]
```

Current version of VarExporter produces this:

```
[
    20 => true,
    true,
    5 => true,
    3 => true,
    80 => true,
    true,
    true,
    120 => true,
    150 => true,
    1 => true,
    9 => true,
    true,
    60 => true,
    true,
    true,
    8 => true,
    50 => true,
    true,
    100 => true,
]
```

And that gives:

```php
[
  20 => true,
  21 => true,
  5 => true,
  3 => true,
  80 => true,
  81 => true,
  82 => true,
  120 => true,
  150 => true,
  1 => true,
  9 => true,
  151 => true,
  60 => true,
  152 => true,
  153 => true,
  8 => true,
  50 => true,
  154 => true,
  100 => true,
]
```

You can see it's not the same array as the origin

```diff
[
     20 => true,
     21 => true,
     5 => true,
     3 => true,
     80 => true,
     81 => true,
     82 => true,
     120 => true,
     150 => true,
     1 => true,
     9 => true,
-    10 => true,
+    151 => true,
     60 => true,
-    61 => true,
-    62 => true,
+    152 => true,
+    153 => true,
     8 => true,
     50 => true,
-    51 => true,
+    154 => true,
     100 => true,
 ];
```

**Comment by xabbuh** [comment]
Happy new year everyone! 🎉 IMO we only need to improve the dump to take into account whether or not the currently exported index is greater than the greatest one (see #29741 for my suggestion to fix this).

**Pull request closed without merging**
