### PR TITLE
[TwigBridge][Worklow] Added a new workflow_has_place function

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20781
| License       | MIT
| Doc PR        | 

--- 

This PR follow up #20781 

I also increased the Coverage of the WorkflowExtension and finally I added an extra commit that is not related to clean-up 2 unused properties

### CODE REVIEW

**Comment by stof** [comment]
what about ``workflow_has_marked_place`` ? ``workflow_has_place`` looks like it asks whether the workflow has this place, which is not what the function does

**Comment by lyrixx** [comment]
@stof I totally agree with you. I have updated the code.

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Comment by lyrixx** [comment]
and thank you @Padam87 ;)

**Pull request merged**
