### PR TITLE
[Validator] Add missing translations for Ukrainian (uk)

### LINKED ISSUE #38769: Missing translations for Ukrainian (uk)
Hello,

There are some missing translation for Ukrainian (uk). These should be added in branch 3.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.uk.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Form/Resources/translations/validators.uk.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Core/Resources/translations/security.uk.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.uk.xlf](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Validator/Resources/translations/validators.uk.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by Comrade42**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38769
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
@Comrade42 Thank you so much for these PR!

You are great!

Could I bother @kefzce with this last PR too?

**Comment by kefzce** [comment]
> @Comrade42 Thank you so much for these PR!
> 
> You are great!
> 
> Could I bother @kefzce with this last PR too?

Seems good, thank you @Comrade42 for your work!

**Comment by Nyholm** [comment]
Awesome. 

Thank you both!

:+1:

**Comment by nicolas-grekas** [comment]
Thank you @Comrade42.

**Pull request merged**
