### PR TITLE
[2.7] [WIP] Fix for #14583

### LINKED ISSUE #14583: [form] error when submitting empty value in for using model choice list
I think that's happening only on propel + postgres after @webmozart removed empty/null checks from ChoiceToValueTransformer in https://github.com/symfony/symfony/commit/1d89922782922fe3bcacb09f91e8c3c992d29d3f

ModelChoiceList->getChoicesForValues allows to create Propel query with empty string values which are not accepted, so I'm getting:
```
Unable to execute SELECT statement [SELECT (...) FROM twilio_number WHERE twilio_number.id IN (:p1)] [wrapped: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""]
```

the code below (for propel bridge) seems to do the trick, but I'm not sure if I can create PR for the Propel1Bridge repository. Will appreciate any help.

```
class ModelChoiceList extends ObjectChoiceList

    public function getChoicesForValues(array $values)
    {
        if (empty($values) || empty($first = reset($values))) {
            return array();
        }
```

### PR DESCRIPTION
**Pull request by phansys**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14583 |
| License | MIT |
| Doc PR |  |

Fixes #14583.
I'm not sure if this is the right fix, so I need someone to share thoughts about this.

**TODO**
- [ ] Add tests

### CODE REVIEW

**Comment by xabbuh** [comment]
At least, this [is breaking](https://travis-ci.org/symfony/symfony/jobs/62244241#L1739) the fix from #14465.

**Comment by phansys** [comment]
You're right @xabbuh, I didn't notice this issue in my test suite.
I'll will update the PR when I have some better idea.

Thank you.

**Comment by benji07** [comment]
any news ?

**Comment by phansys** [comment]
I'm sorry @benji07, I'm very busy these days, but I'll try to work on it this weekend. BTW, if you have some idea, feel free to share your thoughts.

**Comment by phansys** [comment]
I just updated the PR. Can somenone else experiencing this issue test if this fix works? /cc @benji07, @mbartok
BTW, I don't know if this is the right place for this fix, so any help would be much appreciated. 
ping @webmozart

**Comment by weaverryan** [comment]
I think we need to hear what @webmozart thinks - I also can't tell if this is the right way/place to fix this, or if it should be done in the Propel bridge like you mentioned in #14583. @webmozart if you can offer some insight, @phansys or someone else can probably push this the rest of the way.

**Comment by phansys** [comment]
Thank you @weaverryan.
I think its nothing to do with Propel (at least not in an isolated way), since I have this issue with Doctrine 2.5 + PostgreSQL 9.3.

**Comment by benji07** [comment]
@webmozart @fabpot so Symfony 2.7 was release this weekend, and we can't create an entity choice with an empty value.

**Comment by webmozart** [comment]
Sorry, I didn't see this issue until now. Will look into it.

**Comment by phansys** [comment]
Thank you @webmozart.

**Comment by webmozart** [comment]
Hi @phansys, thanks again for this PR! I think the right solution for the problem is #14950. The same should also be done for the Propel bundle. Do you want to work on that?

I'll close this issue as any further work should go to a new PR.

**Comment by phansys** [comment]
Thank you @webmozart. It would be nice to have #14950 merged ASAP. BTW, about the Propel bundle, I would prefer to delegate the task to somebody who know and have worked with Propel since I never used it.

**Comment by guilhermecvmnsj** [comment]
@webmozart your solution doesn't work when using 'uuids'. @phansys solution resolves this problem.
```
with params ["1", "9359da6d-55ff-4da0-8e82-e3b318ecd633", ""]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for uuid: ""
```

**Comment by podhy** [comment]
Any news with this pull request? Because PR #14950 doesnt resolve problem with UUIDs.

Using symfony 2.8

**Comment by jakzal** [comment]
@podhy @guilhermecvmnsj instead of commenting on closed pull requests, please open a new issue if you think there's an unresolved bug. Don't forget to provide steps to reproduce your problem.

**Comment by javiereguiluz** [comment]
@jakzal maybe we could improve our "GitHub bot" to lock conversations automatically some time after the issue has been closed or the PR has been merged (say 6 months).

**Pull request closed without merging**
