### PR TITLE
[Mailer][Notifier] Simplify transport service registration + sorting

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | -
| License       | MIT

### CODE REVIEW

**Comment by OskarStark** [comment]
Are you ok with this PR @nicolas-grekas ?
If yes I will check `mailer_transports.php` too

**Comment by nicolas-grekas** [comment]
Looks fine to me (but don't miss running tests)

**Review by alamirault — APPROVED** [review]

**Comment by OskarStark** [comment]
> but don't miss running tests

Done ✅

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @OskarStark.

**Pull request merged**
