### PR TITLE
[Translator] changed the visibility of the locale from protected to private.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Fixed tickets | ~ |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by aitboudad** [comment]
Reduce visibility for a protected property is allowed http://symfony.com/doc/current/contributing/code/bc.html#changing-classes

**Comment by stof** [comment]
@aitboudad no it is not. The Translator is tagged as ``@api`` (if you are not sure about which category the class is, use the ``API`` column of the table. This is the column being fully BC)

**Comment by aitboudad** [comment]
I see it now so, I'll make the change in `3.0`.

**Comment by aitboudad** [comment]
see #14693

**Pull request closed without merging**
