### PR TITLE
[Messenger] Disable the SchemaAssetsFilter when setup the transport

### PR DESCRIPTION
**Pull request by vincenttouzet**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #31623 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by chalasr** [comment]
Tests seem broken

**Comment by vincenttouzet** [comment]
> Tests seem broken

Yes I'm on it :wink:

**Comment by vincenttouzet** [comment]
Well the fix is uglier than I thought :thinking: 

As of Doctrine 2.9 the method to configure the assets filter has changed : https://github.com/doctrine/dbal/commit/111e42dfb43d1ea0853a449c254df20df2cced37

doctrine-dbal 2.9 introduce the new methods `getSchemaAssetsFilter` / `setSchemaAssetsFilter`. Before it was `getFilterSchemaAssetsExpression` / `getFilterSchemaAssetsExpression`

So I need to try if the method exists before

**Comment by weaverryan** [comment]
Quick work - thanks! Yea, that got ugly :). I can't think of another way either - can anyone else? If not, I think we need this - without it, it's an even uglier situation for the user.

**Review by fabpot — APPROVED** [review]
Let's merge as is for 4.3. We will have time to tweak it if possible in 4.4.

**Comment by fabpot** [comment]
Thank you @vincenttouzet.

**Pull request merged**
