### PR TITLE
[FrameworkBundle] Add support custom config/bundles.php for environment

### PR DESCRIPTION
**Pull request by atotskii**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| License       | MIT

This PR adds support custom `config/bundles.php` for environment.

For example, we don't want to use a some bundle on the specific environment:
Use **Twig** and **Nelmio** packages (build /api/doc) for _dev_ and _test_ only, without _prod_.

Now, we are forced to move packages from _required-dev_ section to _required_ for successful build application after `composer install` with `--no-dev` flag.

After this PR merged we will be able create `config/bundles_prod.php` and remove extra bundles.

### CODE REVIEW

**Comment by yceruto** [comment]
Can you explain the difference between this approach and the current one?

👇 
```php
// config/bundles.php
return [
    // ...
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['dev' => true, 'test' => true],
];
```

**Comment by atotskii** [comment]
> Can you explain the difference between this approach and the current one?
> 
> 👇
> 
> ```
> // config/bundles.php
> return [
>     // ...
>     Symfony\Bundle\TwigBundle\TwigBundle::class => ['dev' => true, 'test' => true],
> ];
> ```

If package placed in **required-dev** section of `composer.json`, then after `composer install --no-dev` we will get an error
> Attempted to load class "XX" from namespace "YY"

Because there will be no package in the `vendor/`

For example, result after `composer install --no-dev`

image

**Comment by GromNaN** [comment]
This is because commands are run in `dev` env by default. But if you want to skip dev-dependencies, you need to swich to `prod` environment.

```
APP_ENV=prod composer install --no-dev
```

I don't see how your change would fix the issue.

**Comment by atotskii** [comment]
> ```
> APP_ENV=prod composer install --no-dev
> ``` 
APP_ENV=prod won't help, because there will be no package in `vendor/` dir and undefined class will be used in `bundles.php`

> I don't see how your change would fix the issue.

I will create `bundles_prod.php` without lines with bundles from **required-dev** section and will be happy)

**Comment by atotskii** [comment]
@GromNaN my bad, APP_ENV=prod fixed, i will close PR, thank you!

**Comment by GromNaN** [comment]
> undefined class will be used in `bundles.php`

Note that the `\My\Class\Name::class` is compiled by PHP as the string `'My\Class\Name'`. The class is not autoloaded, it doesn't need to exist to reference its name with this syntax.

**Pull request closed without merging**
