### PR TITLE
[DI] Fix dumping Doctrine-like service graphs (bis)

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #30091, #29637
| License       | MIT
| Doc PR        | -

Dumping the container while accounting for circular references is hard :)

### CODE REVIEW

**Comment by ro0NL** [comment]
> the required service reference graph is too crazy

well, thank you :} 

conceptually it evolves around using PSR4 prototyped + autowired services, where EM service is bound with a private alias pointing to the actual doctrine EM service. Cool huh :sweat_smile: 

bind: https://github.com/msgphp/msgphp/blob/61f5678b2ab764fb94bd912e6eceab5f3546a8b3/src/UserBundle/Resources/config/doctrine.php#L27
load: https://github.com/msgphp/msgphp/blob/61f5678b2ab764fb94bd912e6eceab5f3546a8b3/src/UserBundle/Resources/config/doctrine.php#L36
alias: https://github.com/msgphp/msgphp/blob/61f5678b2ab764fb94bd912e6eceab5f3546a8b3/src/Domain/Infra/DependencyInjection/BundleHelper.php#L138

Im not sure it's related to the scope where services are registered, in my case from an extension config file, but the alias is registered during bundle booting.

Ill try to replicate it in a minimal DI definition :+1: renamed the repo meanwhile.

Confirmed the patch works. Thanks :100:

**Comment by nicolas-grekas** [comment]
Status: needs work
I'll try to fix #29637 here also, it's related somehow, and not fixed yet.

**Comment by nicolas-grekas** [comment]
:tada:
I've been chasing this for more than one year [almost day-to-day](https://github.com/symfony/symfony/pull/28060).
This PR is now green and fixes all the reproducers provided in linked issues + the test cases from @weaverryan (thank you dude!)

**Comment by nicolas-grekas** [comment]
Thank you @weaverryan.

**Pull request merged**
