### PR TITLE
[WebProfilerBundle] Compact search grid

### PR DESCRIPTION
**Pull request by maidmaid**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

1 row == 1 line, grid more compact, time more readable.

| Before | After |
| --- | --- |
| screenshot from 2017-06-23 15-32-32 | screenshot from 2017-06-23 15-32-58 |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@maidmaid your proposal is beautiful and I like it a lot ... but we can't use it. We thought about this when we redesigned this. The problem is that in real world the URLs will never be `http://dev:8000/`  This is a more realistic example:

profiler-urls

Given that URLs are usually long, we deliberately put the time in 2 lines because long URLs are going to force a two-line anyway and this way the time is more readable.

-----

This reminded me of this:

apple-watchos-ui

The interfaces on Apple press images look gorgeous ... but in real world nobody has handosme friends photographed by professionals with 4-letter names.

**Comment by iltar** [comment]
What about other things we can do to minimize the noise here?
 - I'm never really looking for the fragment requests, maybe the query string can be truncated of those
 - What if the URL is the last column and uses all available whitespace? Won't get worse on smaller screens but gets better on bigger screens.
 - What if instead of the current date, something like "today" is shown? We only really care about the time.
 - Perhaps `127.0.01` can be replaced by an icon? Just sprouting ideas, but in development (99% of the profiler use-cases), this will be most likely localhost?
 - If all the hosts are the same (which is I guess the common case), perhaps the table header could say `URL on http://localhost.com) and have the host stripped from the url columns.

**Comment by javiereguiluz** [comment]
@iltar I like some of your proposals. However, let's keep in mind that the profiler is mostly used when things go wrong or there are issues. So even if most of the info wouldn't be displayed when things go right, we need to display them here to assist our users as much as possible.

> I'm never really looking for the fragment requests, maybe the query string can be truncated of those (with button to show?)

Not possible. We can't alter anything in the original URLs because some people may need it.

> What if the URL is the last column and uses all available whitespace? Won't get worse on smaller screens but gets better on bigger screens.

That's an idea worth trying!

> What if instead of the current date, something like "today" is shown? We only really care about the time.

Not possible, because some people will need complete precision, up to the second.

> Perhaps 127.0.01 can be replaced by an icon? Just sprouting ideas, but in development (99% of the profiler use-cases), this will be most likely localhost?

Not sure if possible, because in some edge cases you may need that too.

> If all the hosts are the same (which is I guess the common case), perhaps the table header could say `URL on http://localhost.com) and have the host stripped from the url columns.

Not sure, because it breaks the URLs in two part (common header + each row) ... and the domain is not that long. The usual problem is the other part of the URL.

**Comment by sstok** [comment]
Can't you force the URL to wrap (using CSS)?

**Comment by javiereguiluz** [comment]
@sstok we already do that:

wrapping-urls

**Comment by iltar** [comment]
> >Perhaps 127.0.01 can be replaced by an icon? Just sprouting ideas, but in development (99% of the profiler use-cases), this will be most likely localhost?
>Not sure if possible, because in some edge cases you may need that too.

@javiereguiluz I meant as in `today 17:50:12`, or even leave the today out if it's today.

**Comment by maidmaid** [comment]
What about use 100% of width of content area, like [the dashboard of Bootstrap 4 alpha](https://v4-alpha.getbootstrap.com/examples/dashboard/)? Actually ``max-width: 1300px`` is used.

screenshot from 2017-06-26 16-31-42

**Comment by fabpot** [comment]
@javiereguiluz I let you make a decision on this one and see how to move this PR forward.

**Comment by maidmaid** [comment]
What about my last comment @javiereguiluz? Many others panels than search panel would render better with 100% width. A lot of data are displayed on two lines because there is not enough width.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't merge". Some final comments:

@iltar we cannot remove or hide or make compact any of the information of this page. The profiler is a bit special because it's mostly used in "distress situations". Something is wrong in your app and you use the profiler to help you figure out what it is. So all useful information must be provided at once.

@maidmaid using ultra-long line lengths may look like a solution but it's actually worse. Instead of increasing readability, long line lengths decrease it. That's why long lines are almost never used in offline or online designs, even with simple contents like this one:

google

**Pull request closed without merging**
