### PR TITLE
Async Aws use Raw field for Api SES requests

### LINKED ISSUE #45168: [Mailer/AWS] Custom headers aren't transmitted
### Symfony version(s) affected

5.4.2

### Description

When trying to send a custom header towards AWS using the AsyncAws implementation custom headers aren't included.
This seems to be due to the usage of the `Simple` message format that doesn't seem to allow for custom headers:
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html

Upon printing the Api request the headers are nowhere to be found either. 

### How to reproduce

Add a header to the mail via:
`$message->getHeaders()->addTextHeader('x-test', 'test'));`
and send it using the `ses+api` DSN

### Possible Solution

There seems to be a `Raw` message format you can send that allows for custom headers so the package should probably use that.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by KDederichs**
…ort)

| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #45168 
| License       | MIT

Copy over the getRequest code from SesHttpAsyncAwsTransport since that used the desired Raw field and thus includes custom headers.

### CODE REVIEW

**Comment by KDederichs** [comment]
Not quite sure what's up with the Psalm, cause it would have had the same complaints with the code in `SesHttpAsyncAwsTransport` :)

**Review by jderusse — COMMENTED** [review]
Symfony AsyncAws's bridge provides the `api` and `http` transport.

IUn your PR, you basically copy/paste the logic of the `http` transport in the `api` transport.

The `api` transport relies on the AWS's interface that does not allow such customization.

If you need a low level access an manipulate email's headers, I suggest using the `http` transport instead.

**Comment by KDederichs** [comment]
Why wouldn't it support that? alas that very code just executes just fine when you copy it over (tested it locally, email was sent and did include the headers)

**Comment by jderusse** [comment]
I've no strong opinion aboutdroping the `api` transport or making the `http` transport as default (and documentation that the API transport does not cover such cases).

But dupplicating the `http` transport's code inside the `api` transport  does not make sense IMHO.

**Comment by KDederichs** [comment]
I'm not 100% sure why they are split up in the first quest tbh (maybe someone can enlighten me on that).

Cause digging a bit deeper they both end up in the same request function (https://github.com/async-aws/ses/blob/73c71526012129f53d5ae277a2e83da2f842bd75/src/Input/SendEmailRequest.php#L208)
anyways so it does make little sense that one of the implementation offers an incomplete set of functionality.
So I don't really care if we end up merging them instead if there's no real reason to split them but they definitely both support the full AWS feature set.

**Comment by KDederichs** [comment]
maybe another option would be to just switch out the simple part with raw? That probably makes more sense and has the desired effect of custom headers as well

**Comment by stof** [comment]
Well, the current implementation matches the distinction between `http` transport and `api` transport in all bridges:

- the `http` transport uses HTTP requests (to an API endpoint) to send a message built entirely in the mailer component (using the mime component for most of the work actually). This is often called a `raw` endpoint
- the `api` transport uses the sending API of the provider. This often has a few limitations about the kind of mime email that can be sent (which depend on the provider), but it unlocks the usage of provider-provided features (automatic DKIM signing, automatic creation of a text alternative, automatic tracking of opens and clicks, etc...) that are generally disabled (at least for some of them) when using their `raw` endpoint.

That's why bridges have 2 different transport, allowing to choose the one with the right tradeoffs.

Changing the SesApiAsyncAwsTransport to become a duplicate of the SesHttpAsyncAwsTransport by using the `Raw` endpoint (which is implemented as passing a different option in SES rather than as a separate API endpoint, but the idea is still the same as they provide 2 different behaviors on that endpoint) would break that disctinction.

**Comment by KDederichs** [comment]
So using raw actually overwrites the things you set outside of it? (Meaning the changes I pushed a few minutes ago effectively would be the same as replacing it outright?)

As I understand https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html you can use Raw in combination with the other parameters, but you are responsible for proper message formatting.

Bit of a bummer tbh if that's not the case.

If it actually does that then there's no way of archiving custom headers with ses+api (which should be then at least mentioned in the docs somewhere)

**Comment by KDederichs** [comment]
Quick update, I did ask the AWS support regarding headers and that's what came back:
```

Hello,

Hope you are well.

Thank you for contacting AWS Premium Support. My name is Samreen and I will be assisting you on this case today.

From your correspondence, I understand that you have a few queries with regards to sending custom email headers using SES. 
I have tried to address your queries as follows, please do let me know if I may have misunderstood any of them:

1) Is there a way to pass custom user defined headers using the Simple content parameter?
No, custom headers cannot be sent using the simple email from SES.
>> https://docs.aws.amazon.com/cli/latest/reference/ses/send-email.html

However, you can customize the message headers when using the SendRawEmail operation.

2) If not what's the behaviour when switching Simple with Raw? Do the headers/parameters defined in the Raw message overwrite the settings set by the api call like Destination, ReplyToAddresses etc. or do the ones defined by the api parameters preference?

In general, if SES is setting the parameters and if the same ones are set as custom headers, then the ones defined by SES API call take precedence. 
For example, if you set Date as a header in the raw message, it will be overwritten by the value provided by SES.

>> https://docs.aws.amazon.com/ses/latest/dg/header-fields.html

```

**Comment by fabpot** [comment]
What's the status here? Shall we close?

**Pull request closed without merging**
