### PR TITLE
Add #[\SensitiveParameter] to $sessionId

### PR DESCRIPTION
**Pull request by mfb**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Follow-up to #48274 and #46183

### CODE REVIEW

**Review by GromNaN — APPROVED** [review]
Very good idea, session ids are indeed sensitive data as stated by owasp: https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html

**Comment by mfb** [comment]
The suggested code style fix at https://fabbot.io/patch/symfony/symfony/49016/32c9f28bebe3573431644838db625ef941f5405b/cs.diff looks wrong - I don't think I should remove a blank line just because I added an attribute to the function arguments.  I _could_ not add it in those places, given this is just an abstract class, but seemed helpful for developers to have it there too.

**Comment by stof** [comment]
Those blank line removals indeed look like a bug in php-cs-fixer (maybe a fixer is not handling attributes on parameters properly)

**Review by javiereguiluz — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @mfb.

**Pull request merged**
