### PR TITLE
[DependencyInjection] force enabling the external XML entity loaders

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18876 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Do we have the same issue in XliffFileLoader.php and XmlUtils.php?

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by sstok** [comment]
@nicolas-grekas It seems so, https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/Loader/schema/dic/xliff-core/xliff-core-1.2-strict.xsd#L33

I wonder if this will not load the external resources of the to be validated XML document, which would break the security system that was introduced 😨 can this be checked somehow?

**Comment by nicolas-grekas** [comment]
Reverted because this look suspicious and need more thought.
@xabbuh now that 2.3 is EOLed, could you please reopen this on 2.7 so that the discussion can continue?

**Comment by xabbuh** [comment]
@sstok @nicolas-grekas see #18915

**Pull request merged**
