### PR TITLE
Fix: Slim composer-config.json

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Follows https://github.com/symfony/symfony/pull/41330#issuecomment-845101425

> @OskarStark dunno, let me know and please send a PR :)

Lets see

cc @nicolas-grekas

### CODE REVIEW

**Comment by OskarStark** [comment]
Looks like it cannot be removed, but maybe the component related parts ... 🤔

**Review by derrabus — APPROVED** [review]

**Review by derrabus — CHANGES_REQUESTED** [review]
Looks like the low-deps build still needs the settings you've removed. 😢

**Comment by OskarStark** [comment]
Maybe because 5.3 isn't released yet?

**Comment by wouterj** [comment]
Because we're using classes from the `Tests` directory in other components (which is excluded from the dist). You can see all used classes in the error messages in either deps Travis log.

Maybe some of them can be replaced with classes in `Test` (if we already replaced them). But I guess most of them should stay in `Tests` (as we don't want to cover them with the BC promise).

**Comment by derrabus** [comment]
> Maybe some of them can be replaced with classes in `Test` (if we already replaced them).

That's what we should do, yes. I'd like to get rid of that hack.

> But I guess most of them should stay in `Tests` (as we don't want to cover them with the BC promise).

If we don't want to include them in the BC promise, we could as well flag them as `@internal`.

**Comment by OskarStark** [comment]
Not checked but IIRC we didn't depend on classes in Tests for the notifier stuff in 5.3 but as this is not released it would use 5.2 which could have dependencies on Tests.

If I am correct this should be green when 5.3 is released

**Comment by nicolas-grekas** [comment]
The CI is independent from releasing

**Comment by nicolas-grekas** [comment]
I personally think that we have enough topics to care about and that this one is not worth our time :)

**Comment by wouterj** [comment]
> Not checked but IIRC we didn't depend on classes in Tests for the notifier stuff in 5.3 but as this is not released it would use 5.2 which could have dependencies on Tests.

Just for completeness (I agree with @nicolas-grekas about this being somewhat irrelevant to fix), both `FakeChat` and `FakeSms` depend on `Tests`: https://github.com/symfony/symfony/blob/03489a49ecca7499e43a0c8052232c33cf623ae3/src/Symfony/Component/Notifier/Bridge/FakeChat/Tests/FakeChatEmailTransportTest.php#L21-L22

**Comment by OskarStark** [comment]
Indeed, just thought about the AbstractTestCase's 👍🏻

**Pull request closed without merging**
