### PR TITLE
Display Ajax requests from newest to oldest in the toolbar

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16831 |
| License | MIT |
| Doc PR | - |
### Before

ajax_before
### After

ajax_after

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by javiereguiluz** [comment]
Failing tests seem unrelated:

```
1) Symfony\Component\Form\Tests\Extension\Core\Type\ChoiceTypeTest::testCustomChoiceTypeDoesNotInheritChoiceLabels
Symfony\Component\Form\Exception\InvalidArgumentException: Could not load type "choice"

2) Symfony\Component\Process\Tests\ProcessTest::testGetEmptyIncrementalOutput
Failed asserting that two strings are identical.
```

**Comment by paradajozsef** [comment]
The first failing test has been fixed since then. I don't know about the second one.

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
