### PR TITLE
[2.7] adds legacy tests for deprecated configuration keys.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by hhamon** [comment]
Not WIP anymore but trying to figure out why the tests suite segfaults on 5.3.3.

**Comment by fabpot** [comment]
@hhamon Have you tried to relaunch the tests on Travis? Sometimes, it segfaults for no obvious reasons.

**Comment by stof** [comment]
just forget about 5.3.3 by rebasing the branch, given the min version has just been bumped to 5.3.9 :smile:

**Comment by hhamon** [comment]
Yep! Looks like the rebase did the trick :D

**Comment by hhamon** [comment]
Everything is green and ready for review by @symfony/deciders ;)

**Comment by stof** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @hhamon.

**Comment by stof** [comment]
@hhamon it would also be good to update the configuration files of functional tests in FrameworkBundle and SecurityBundle to stop using the deprecated config keys but migrating them to the new keys instead (I suggest doing it in a separate PR though, as this one is now mergeable given the 2 votes above)

**Comment by hhamon** [comment]
@stof Good catch! I'm on it ;)

**Comment by stof** [comment]
@hhamon I just looked at Travis: https://travis-ci.org/symfony/symfony/jobs/46451129#L1758

**Comment by hhamon** [comment]
See https://github.com/symfony/symfony/pull/13349

**Pull request merged**
