### PR TITLE
[VarDumper] Add Caster::PATTERN_PRIVATE to help builing key

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       |
| License       | MIT
| Doc PR        | not needed I guess

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by welcoMattic — APPROVED** [review]

**Comment by welcoMattic** [comment]
Thank you @lyrixx.

**Comment by stof** [comment]
should it be a constant containing a sprintf pattern or a static method taking the class name ?

With the sprintf pattern, I fear devs will do mistakes by trying to use the constant only, as other constants.

**Comment by lyrixx** [comment]
I prefer the static method too. But I asked to @nicolas-grekas on slack and he told me to do that. 

Anyway I'm up to add a method!

**Comment by nicolas-grekas** [comment]
I'm not in favor of adding a method for this. My preference is that ppl know the pattern and use strings directly. I'm fine with adding a constants if that helps. But a method is the beginning of an API, and I don't think we should add an API for concatenating these strings.

**Comment by stof** [comment]
To me, this constant does not help because it does not remove the need to know the pattern to understand how to use it.

**Comment by nicolas-grekas** [comment]
It does help, eg to use `::class`, see https://github.com/symfony/symfony/pull/49853/files#diff-9c91e53d35c9528f121b8d7d6ab2ea343249ac120b56282eea81076645189c89R295

**Pull request merged**
