### PR TITLE
Use fully qualified name for is_numeric()

### PR DESCRIPTION
**Pull request by BenMorel**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by fabpot** [comment]
We are adding `\` only when PHP is able to optimize the call. That's not the case here.

**Comment by BenMorel** [comment]
@fabpot Do you mean when PHP can convert the function to an opcode?

In this case, `\is_callable()` is not justified either: https://3v4l.org/cmAVF/vld#output

Please let me know if I missed something!

**Comment by nicolas-grekas** [comment]
@BenMorel see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-332784692 for is_callable (and the rest)

**Comment by BenMorel** [comment]
@nicolas-grekas Thanks for the pointer! I thought I could trust good old opcodes...

**Pull request closed without merging**
