### PR TITLE
Allow --verbose option to accept values

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #10487 |
| License | MIT |
| Doc PR | - |

The special `--verbose` option was defined as this:

``` php
new InputOption('--verbose', '-v|vv|vvv', InputOption::VALUE_NONE, ...),
```

This is wrong, because `--verbose` option must accept integer values (`--verbose=1`, `--verbose=2`, etc.) which are equivalent to the short options (`-v`, `-vv`, etc.):

``` php
new InputOption('--verbose', '-v|vv|vvv', InputOption::VALUE_OPTIONAL, ...),
```

In our test suite we already test values for this option:

``` php
$tester->run(array('command' => 'list', '--verbose' => 2));
```

But we didn't test them in the following way, which is now supported after this fix:

``` php
$input = new ArgvInput(array('cli.php', '--verbose=2'));
$application->run($input, $output);
```

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by stof** [comment]
this is a BC break. It breaks the usage of ``app/console container:debug --verbose twig`` as ``twig`` is now considered as being the option value instead of the argument.
This change was already merged in the past and reverted because of that

**Comment by fabpot** [comment]
I have not tested this patch but I"m pretty sure it won't work in all situation. The verbose option is handled in a very special way and we had to make some ugly hacks to make it work well. This probably breaks with this change.

**Comment by javiereguiluz** [comment]
Your concerns look reasonable. Let's close this PR and let's close #10487 as "won't fix". Thanks!

**Pull request closed without merging**
