### PR TITLE
Update EngineInterface.php

### PR DESCRIPTION
**Pull request by johnnypeck**
Grammer in doc comment.

### CODE REVIEW

**Comment by jakzal** [comment]
Why did you close?

**Comment by johnnypeck** [comment]
@jakzal For some reason I thought I hadn't followed the contributing guidelines as my fork is way out of date. I'll reopen. Thanks for the push ;-)

**Comment by jakzal** [comment]
@johnnypeck here's the contribution guide that should help you: http://symfony.com/doc/current/contributing/code/patches.html 

Please update PR's description and include [the checklist table](http://symfony.com/doc/current/contributing/code/patches.html#make-a-pull-request).

**Comment by fabpot** [comment]
Thank you @johnnypeck.

**Pull request closed without merging**
