### PR TITLE
[6.2] [Yaml] Dumper fix and refactor

### LINKED ISSUE #46725: [Yaml] Dumper: TaggedValue at top level fails unless inline.
### Symfony version(s) affected

6.1.0

### Description

The Dumper::dump() method does not allow `TaggedValue` in the top level, unless it is in "inline" mode.
EDIT: The parser seems alright.

We should either fix it, or more explicitly enforce a contract where this is not allowed.

### Dumper inline -> ok

```php

    public function testDumpingTaggedValueTopLevelScalar()
    {
        $data = new TaggedValue('user', 'jane');

        $yaml = $this->dumper->dump($data);

        $expected = '!user jane';
        $this->assertSame($expected, $yaml);
    }

    public function testDumpingTaggedValueTopLevelAssocInline()
    {
        $data = new TaggedValue('user', ['name' => 'jane']);

        $yaml = $this->dumper->dump($data);

        $expected = '!user { name: jane }';
        $this->assertSame($expected, $yaml);
    }
```

### Dumper not inline -> broken
```php
    public function testDumpingTaggedValueTopLevelAssoc()
    {
        $data = new TaggedValue('user', ['name' => 'jane']);

        $this->expectException(\TypeError::class);
        $this->expectExceptionMessage('Symfony\Component\Yaml\Inline::isHash(): Argument #1 ($value) must be of type ArrayObject|stdClass|array, Symfony\Component\Yaml\Tag\TaggedValue given');

        $this->dumper->dump($data, 2);
    }
```

### Parser works fine

EDIT: I previously thought this was broken, but now found that it works correctly.

```php

    public function testTaggedValueTopLevelScalar() {
        $yml = '!user barbara';
        $data = $this->parser->parse($yml, Yaml::PARSE_CUSTOM_TAGS);
        $expected = new TaggedValue('user', 'barbara');
        $this->assertEquals($expected, $data);
    }

    public function testTaggedValueTopLevelAssocInline() {
        $yml = '!user { name: barbara }';

        #$yml = '!user {name: barbara}';
        $data = $this->parser->parse($yml, Yaml::PARSE_CUSTOM_TAGS);
        $expected = new TaggedValue('user', ['name' => 'barbara']);
        $this->assertEquals($expected, $data);
    }

    public function testTaggedValueTopLevelAssoc() {
        $yml = <<<'YAML'
!user
name: barbara
YAML;

        $data = $this->parser->parse($yml, Yaml::PARSE_CUSTOM_TAGS);
        $expected = new TaggedValue('user', ['name' => 'barbara']);
        $this->assertEquals($expected, $data);
    }

    public function testTaggedValueTopLevelList() {
        $yml = <<<'YAML'
!users
- barbara
YAML;

        $data = $this->parser->parse($yml, Yaml::PARSE_CUSTOM_TAGS);
        $expected = new TaggedValue('users', ['barbara']);
        $this->assertEquals($expected, $data);
    }
```

### Possible Solution

I'd say fix it.

### PR DESCRIPTION
**Pull request by donquixote**
| Q             | A
| ------------- | ---
| Branch?       | 6.2 or 6.1 TBD
| Bug fix?      | yes
| New feature?  | no, unless you count increased tests and dumping more values
| Deprecations? | no
| Tickets       | Fix #46725, #46718, #46728 partly
| License       | MIT
| Doc PR        | -

Check individual commits when reviewing!
The idea is that every commit should have a passing test.

### CODE REVIEW

**Comment by donquixote** [comment]
Btw we could do evern more refactoring, but I want to preserve BC even for those who extend the Dumper class.

E.g. we could have the main `->dump()` method be called only for the top level, and then use a different `->dumpRecursive()` method. But this would break extending classes.

I also would like to have an option to save a line break for map inside sequence as requested in #15782. But better do this in a follow-up.

**Comment by donquixote** [comment]
Fails seem unrelated.

**Comment by xabbuh** [comment]
Can you send the extension of the existing tests as a separate PR against the `4.4` branch please?

**Comment by donquixote** [comment]
https://github.com/symfony/symfony/pull/46739

**Comment by nicolas-grekas** [comment]
https://github.com/symfony/symfony/pull/46739 is now merged up to 6.2. Can you please rebase this PR?
Note that it'd be great to fix those `@todo` before merging, on 4.4 also.

Status: needs work.

**Comment by donquixote** [comment]
@nicolas-grekas 
Thanks!
What is a good base to rebase on?
We want to merge this into all branches later, right?

**Comment by donquixote** [comment]
If I rebase on 4.4, do we want to support PHP 7.1?
The composer.json says so.
With 7.1 we cannot even use composer2 :)
But maybe this is exactly the point, to support legacy projects.

I am not sure if we actually do want to go for 4.4, so I make that a separate PR and we can choose.

**Comment by fabpot** [comment]
Any reactorting must be done in 6.2.

**Comment by xabbuh** [comment]
I fail to see the added benefit these changes bring, thus 👎 from my side on these changes

**Pull request closed without merging**
