### PR TITLE
Unify URL generator reference type + make linking in php templates consistent with twig

### PR DESCRIPTION
**Pull request by Tobion**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | #14672 |
| License | MIT |
| Doc PR | TODO |

Please see ticket.
Please merge #16277 first. I will then rebase this to make tests pass.

### CODE REVIEW

**Comment by Tobion** [comment]
Please merge #16277 first, I will then rebase this PR which will make tests pass.

**Comment by fabpot** [comment]
:+1:

**Comment by Tobion** [comment]
Rebased

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @Tobion.

**Comment by xabbuh** [comment]
see symfony/symfony-docs#5813 and symfony/symfony-docs#5814 for the documentation update

**Pull request merged**
