### PR TITLE
[Yaml] require space after colon after mapping key

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #19436 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Should trigger a deprecation instead (thus on master?)

**Comment by fabpot** [comment]
Why would you want to trigger a deprecation on a bug?

**Comment by nicolas-grekas** [comment]
Because I'm sure some people out there have invalid Yaml file that are accepted by our parser, and we're going to break their app. This is a BC break to me, don't you think?

**Comment by fabpot** [comment]
Fair enough, seeing that we also have tests that exhibit this wrong behavior, let's deprecate this on master first.

**Comment by nicolas-grekas** [comment]
And I propose to go one step farther and add a flag so that people can opt in for more the exception instead of the deprecation. I'm anticipating a need for this in blackfire where we'll want to disallow invalid yaml (because we want parsing parity with a strict go yaml parser).

**Comment by xabbuh** [comment]
closing in favour of #19504

**Pull request closed without merging**
