### PR TITLE
[DependencyInjection] Added tests to cover the possibility of having scalars as services

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #32411 
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Review by fabpot — CHANGES_REQUESTED** [review]
~~Some tests would be nice as well :)~~ Wrong PR sorry

**Comment by nicolas-grekas** [comment]
Can you add a test case that involves a dumped container please?

**Comment by derrabus** [comment]
Done.

**Comment by derrabus** [comment]
Status: Needs Review

**Comment by derrabus** [comment]
Travis failures are unrelated.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @derrabus.

**Pull request merged**
