### PR TITLE
[PhpUnitBridge] Enforce @-silencing of deprecation notices according to new policy

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | symfony/symfony-docs#5413 |

### CODE REVIEW

**Comment by stof** [comment]
This may be an issue for deprecations triggered in other libraries than Symfony though, if they don't use the new silencing pattern

**Comment by nicolas-grekas** [comment]
Yes and no: if the deprecations where is place before the bridge was released, then these libs already have a way to make their user handle them. If the deprecations where added by take inspiration from Symfony, then this is a recent move and I'd advocate we need to push them one step forward.
It tool us several month to create the current deprecation policy and I now really like it. This bridge should help spread the word :)

**Comment by stof** [comment]
Well, pushing to the new way is indeed a good idea. :+1: 

You should also update http://symfony.com/doc/current/contributing/code/conventions.html#deprecations with the new convention btw

**Comment by nicolas-grekas** [comment]
Doc PR is symfony/symfony-docs#5413

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
