### PR TITLE
restrict and increase version of reflection-docblock

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
| Q             | A
| ------------- | ---
| Branch?       | 3.1, 3.2, 3.3, master
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

I think we should have same behavior on 2.8 and 3.0 but there `phpdocumentor/reflection` is required and i whanted to avoid conflicts.

### Reason:

The version 3.2.0 of phpdocumentor/reflection-docblock is really broken. All Annotations lide `@api`, means without any bracket, leads to errors like `Uninitialized string offset: 0`. We in the CMF do not require that bundle directly, but symfony does and so we get braking builds.

### CODE REVIEW

**Comment by xabbuh** [comment]
We should probably then add such an annotation in the test fixtures and switch back to conflicting entirely with 3.2 (like it was done in #23549) as long as the issue isn't fully fixed.

**Comment by ElectricMaxxx** [comment]
I currently also do not trust the `conflict` section in composer. I tryed it on `symfony-cmf/routing-auto-bundle` and it does not restrict. I did exactly get the broken version. So i would go back to the restriction in `require` section?
What about the failing test on the CI? I does not seem to be related to my change.
What about the bundles/components? Should they get same too?

**Comment by xabbuh** [comment]
@ElectricMaxxx I would first switch the target branch to 3.3 (3.1 and 3.2 are not supported anymore) and rebase accordingly. That will probably help making tests pass.

**Comment by ElectricMaxxx** [comment]
My Rebase wasn't fine, so i will retry later.

**Comment by ElectricMaxxx** [comment]
CLOSED in favor of: https://github.com/symfony/symfony/pull/23848

**Pull request closed without merging**
