### PR TITLE
Allow component build failures until we can make them successful

### PR DESCRIPTION
**Pull request by jakzal**
| Q | A |
| --- | --- |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:-1: we'd better fix the issues than closing our eyes

**Comment by jakzal** [comment]
Well, no one has got the fix yet. I'd say we're closing our eyes now. PRs are merged with builds failing, 'cause no one seems to look at them.

I think full tests are more important in this case, and until we sort out the approach to testing components in separation it's better to disable them.

**Comment by fabpot** [comment]
I do have a look at the build problems, but there are not always trivial to fix.

**Comment by stof** [comment]
The issue is that depending of what the PR does, this build might be forced to fail (for a PR affecting multiple components as subtrees won't have the patch of the PR yet)

**Comment by Tobion** [comment]
Exactly. So even if we fix the current issues, there will still be PRs that fail anyway for components. So this change might be a good idea.

**Pull request closed without merging**
