### PR TITLE
[DI] fix ContainerBuilder on PHP8

### LINKED ISSUE #38089: Uncaught Error: Unknown named parameter
**Symfony version(s) affected** 4.2.8 (https://github.com/phpmyadmin/phpmyadmin/blob/64f6b5c43522be49facbd95bee9197e811284c91/composer.json#L55)

**Description**  
```
[11-Aug-2020 10:14:15 America/New_York] PHP Fatal error:  Uncaught Error: Unknown named parameter $create_add_field in D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php:1144
Stack trace:
#0 D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php(1144): ReflectionClass->newInstanceArgs(Array)
#1 D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php(618): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'PhpMyAdmin\\Cont...')
#2 D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php(558): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('PhpMyAdmin\\Cont...', 1)
#3 D:\phpMyAdmin\tbl_structure.php(67): Symfony\Component\DependencyInjection\ContainerBuilder->get('PhpMyAdmin\\Cont...')
#4 {main}
  thrown in D:\phpMyAdmin\vendor\symfony\dependency-injection\ContainerBuilder.php on line 1144
```

**How to reproduce**  
PHP 8.0 beta 1 (https://github.com/phpmyadmin/phpmyadmin/issues/16301)

Upstream bug: https://github.com/phpmyadmin/phpmyadmin/issues/16301

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38089
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by kanlukasz** [comment]
Is it possible that this patch will be in Ubuntu 20 - apt package `php-symfony-dependency-injection` ?
Many of us have problems with phpmyadmin apt because of this problem:
- https://github.com/phpmyadmin/phpmyadmin/issues/17187
- https://github.com/phpmyadmin/phpmyadmin/issues/16968
- https://github.com/symfony/symfony/issues/38089

**Comment by derrabus** [comment]
Report this to Debian/Ubuntu, please. We're not involved in their packaging process.

**Comment by kanlukasz** [comment]
For others who are also looking for it:
https://bugs.launchpad.net/ubuntu/+source/symfony/+bug/1932552

**Pull request merged**
