### PR TITLE
[HttpFoundation] Use directly `has` object method into `get` object method

### PR DESCRIPTION
**Pull request by chadyred**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

Use directly has object method into get object method

### CODE REVIEW

**Comment by stof** [comment]
But why doing more method calls to do the same result ?

**Comment by chadyred** [comment]
IMO it is to deal more with encapsulation, which include the fact to interact with data members of this object like `parameters` through a dedicated method, for example here : `has`.

**Review by javiereguiluz — APPROVED** [review]
@stof it's true that this means calling more methods ... and it could hurt performance very slightly (unless PHP's OPCache is smart enough to inline the `has()` method logic)...

... however, this looks more future-proof to me. Current code duplicates the `has()` method logic, so if we ever change the `has()` method internals (e.g. to deal with lowercase/camelCase, dot namespacing, filtering of underscores/dashes, etc.) we'd need to remember to also change this.

But I agree it's debatable.

**Comment by ro0NL** [comment]
DX only increases when doing `parent::has($key) && myLogic($key)`, other cases need to patch get() either way

eg. lowercasing/normalizing keys should still be kept in sync in get() as well

i tend to be :+1:, given we assume inheritance based design

**Comment by stof** [comment]
Well, inheritance-based design does not benefit from this either (and even suffer from it): the reading in the array only supports the direct key access.
If a child class has some special logic in `has` to support different keys, it also need to override `get` to apply that special logic.

The current check in `get` is the one corresponding to the read done in the `then` case to avoid notices.

So that's a -1 for me.

**Comment by ro0NL** [comment]
i agree you can break get() by implementing has() poorly, but that's a contract violation already IMHO

my point is, if you do `has { return true; }` you need to override get() either way, to implement it as such

if you do `has { return parent::has($key) && myLogic($key) }` you can now spare out overriding get()

note ideally i think we should aim for final InputBag+ParameterBag VOs.

**Comment by stof** [comment]
@ro0NL if you want to support the case of `has` overridden with  `return parent::has($key) && myLogic($key)`, then the `get` method should look like `\array_key_exists($key, $this->parameters) && $this->has($key)`. Doing only the `has` check makes the code fragile as we don't know what this method does when it is overridden.

**Comment by stof** [comment]
btw, doing such check might also break child classes overriding `has` and `get` while passing modified values to the parent method, so it is quite risky.

**Comment by fabpot** [comment]
Closing for the reasons explained by @stof.

**Pull request closed without merging**
