### PR TITLE
[Validator] GH-50526: Reverting ExecutionContextInterface void return types in favor of docblock annotations.

### LINKED ISSUE #50526: [Validator] Return types change on ExecutionContextInterface break BC
### Symfony version(s) affected

6.3.0

### Description

Hello,

I noticed that in 6.3.0 version of the Validator, the ExecutionContextInterface got it's public method signatures updated to add  a return type: https://github.com/symfony/validator/commit/c2801bcde41f42c0fbaa9c64b4ad1e82f7199ad5.

This breaks any implementation of the ExecutionContextInterface. AFAIK, minors should not make changes to public APIs no? 

Thanks!

### How to reproduce

No real steps.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by upchuk**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #50526
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
To make the CI pass, you need to regenerate the `.github/expected-missing-return-types.diff` file (instructions for that are at the top of the file) so that the CI does not complain about not using native types on those methods.

**Comment by upchuk** [comment]
@stof I'm trying but I am getting an error ` Uncaught Error: Failed opening required '/var/www/html/.github/../.phpunit/phpunit/vendor/autoload.php'`, when i run `SYMFONY_PATCH_TYPE_DECLARATIONS='force=2&php=8.1' php .github/patch-types.php`.

The phpunit folder is not there, should it be?

**Comment by stof** [comment]
@upchuk run `./phpunit install` first

**Comment by upchuk** [comment]
@stof thanks. Did that but now I get
```
[05-Jun-2023 06:52:32 UTC] PHP Fatal error:  Uncaught RuntimeException: Case mismatch between loaded and declared class names: "Doctrine\DBAL\Platforms\MySqlPlatform" vs "Doctrine\DBAL\Platforms\MySQLPlatform". in /var/www/html/src/Symfony/Component/ErrorHandler/DebugClassLoader.php:331
```

I think you can just go ahead and make the fix yourself, it's much faster :D

**Comment by nicolas-grekas** [comment]
Thank you @upchuk.

**Pull request merged**
