### PR TITLE
[TwigBridge] Foundation 6 form layout integration

### PR DESCRIPTION
**Pull request by phan7om**
| Q | A |
| --- | --- |
| Branch? | "master" for new features |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| License | MIT |
| Doc PR | http://symfony.com/doc/current/cookbook/form/form_customization.html#what-are-form-themes |

This feature inspired by Foundation 5 template. Improvements are based on http://foundation.zurb.com/sites/docs/abide.html

### CODE REVIEW

**Comment by dunglas** [comment]
Integrating Foundation in core was already refused: https://github.com/symfony/symfony/pull/12587

Maybe should you create a community bundle for that and maybe can we mention it in the Symfony doc.

**Comment by dunglas** [comment]
My bad, it was accepted. So why not the new version.

**Comment by Rattler3** [comment]
@phan7om As foundation is mobile first, should the classes be "small-12" rather than "large-12"?

**Comment by phan7om** [comment]
@Rattler3 for the only one class it's doesn't matter large-12 or small-12. it's the same.
Many classes needed when you organize the look of page in small or large screen properly.
It this case large-12 or small-12 mean full horizontal row of content

**Comment by fabpot** [comment]
What's the status of this PR?

**Comment by fabpot** [comment]
Closing as there is no more feedback. Feel free to reopen.

**Pull request closed without merging**
