### PR TITLE
[Messenger] Templated email messages fails when sending async (thru messenger transport)

### LINKED ISSUE #39190: Templated email messages fails when sending async
**Symfony version(s) affected**: 5.x

**Description**  
When sending a `TemplatedEmail`  asynchronously,  an exception is thrown : `Symfony\Component\Mime\Exception\LogicException: A message must have a text or an HTML part or attachments.`.

The rendering of the templated is not done, as it's deferred to the actual email sending, but when the messenger's message is created it fails: 

```
1) Symfony\Bundle\FrameworkBundle\Tests\Functional\MailerTest::testSendingQueuedMessage
Symfony\Component\Mime\Exception\LogicException: A message must have a text or an HTML part or attachments.

/symfony/src/Symfony/Component/Mime/Email.php:405
/symfony/src/Symfony/Component/Mailer/SentMessage.php:33
/symfony/src/Symfony/Component/Mailer/Transport/AbstractTransport.php:67
/symfony/src/Symfony/Component/Mailer/Mailer.php:42
/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Functional/MailerTest.php:132

``` 

**How to reproduce**  
With a the following test, or by sending async templated messages as documented here: https://symfony.com/doc/current/mailer.html#sending-messages-async

```

class MailerTest extends AbstractWebTestCase
{
    public function testSendingQueuedMessage()
    {
        self::bootKernel(['test_case' => 'Mailer']);

        $testTransport = new class() extends AbstractTransport {
            public function __toString(): string
            {
                return 'dummy://local';
            }

            protected function doSend(SentMessage $message): void
            {
            }
        };

        $mailer = new Mailer($testTransport);

            $message = (new TemplatedEmail())
            ->subject('Test subject')
            ->from('from@example.org')
            ->to('to@example.org')
            ->htmlTemplate('template.html.twig')
        ;

        $mailer->send($message);
    }
}
```

### PR DESCRIPTION
**Pull request by ronnylt**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | yes
| New feature?  | no
| Tickets       | Fix https://github.com/symfony/symfony/issues/39190
| License       | MIT

### CODE REVIEW

**Comment by ronnylt** [comment]
What is the intended behaviour when queueing template messages, doing the rendering before enqueuing the message for async sending, OR just before actually sending the message to the mailer transport?

In other words, is rendering intended to be done before dispatching to the messenger's bus?

I think this clarification is important for a fix.

**Comment by jderusse** [comment]
One benefit of rendering the template BEFORE queuing, is: the extensions have access to the request context.
- can render absolute links with scheme and domain
- have access to the logged user

When switching to async, you have to provide the needed context (ie. `framework.router.default_uri`, or passing context in the `render` method).

Rendering template is fast. I'm not sure adding such complexity and bugs worth it.

**Comment by ronnylt** [comment]
@jderusse +1 on rendering before queuing, this also allows to have a minimalist worker application that only takes care of sending ready-to-send emails.

The proposed fix removes the cloning of the message before sending it to the `EventDispatcherInterface`. This way the message that is transformed by body renderers, etc... is the same that is actually enqueued. 

Not sure if the cloning is needed or if removing this can have any other side-effects. 

Any ideas? Thanks.

**Comment by ronnylt** [comment]
Hi! Can anyone provide any updates or guidance on how to proceed? 

Thanks!

**Comment by mburtscher** [comment]
Really looking forward to this fix! The change actually revert's @fabpot's intention to not use the same variable name as changed in commit 829566cdea90a0be0231a15a229df2166868fce0. The actual bug was introduced later in commit fc4be4822a75e1f2697a260d6ba16ea8bfdfbe1f with removing the second event dispatched.

**Comment by perebusquets** [comment]
Also looking forward to implement this fix, any idea on when can we expect this to be fixed?

**Comment by fabpot** [comment]
Closing as this fix is not valid.
See #47052 and #47049 for more explanations.

**Pull request closed without merging**
