### PR TITLE
[DependencyInjection] Move `array_merge` calls out of loops

### PR DESCRIPTION
**Pull request by simonberger**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License | MIT

See https://github.com/symfony/symfony/pull/43268#issuecomment-932056954 for a small performance benchmark.

### CODE REVIEW

**Comment by fabpot** [comment]
If you have other such changes, can you do them all in this PR?

**Comment by simonberger** [comment]
Yes I could. I was not sure how reviewers prefer to receive it and for that reason asked in the last PR.
The changes are relatively clear but yet need a good review, which is harder to find a volunteer for when coming in a bigger amount and in different components.

Those changes are all in this component and I split it up from the rest. I happily close this and push all together once I am finished.

**Comment by fabpot** [comment]
We prefer to group similar changes in one PR.

**Comment by ging-dev** [comment]
Hey @simonberger, if I'm not mistaken, these two give the same result
```php
array_merge([], ...$arr);
array_merge(...$arr);
```

**Comment by stof** [comment]
@ging-dev no. This is not the same if `$arr` is an empty array. `array_merge` requires at least 1 argument.

**Comment by nicolas-grekas** [comment]
>array_merge requires at least 1 argument

until PHP 7.4 :)

https://3v4l.org/e9FnW

**Comment by stof** [comment]
oh, I was not aware of that change

**Pull request closed without merging**
