### PR TITLE
[DependencyInjection][3.0] Add initialized to container interface

### PR DESCRIPTION
**Pull request by znerol**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15346 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by WouterJ** [comment]
This is a BC break, isn't it? As people typehinting for the new interface will have to update their code for Symfony 3.0

**Comment by OskarStark** [comment]
Yes, it is a BC, everyone who hast implemented ```ContainerInterface```before, has to add the new method ```initialize()``` to his code

**Comment by hhamon** [comment]
Why not make a separate optional interface?

**Comment by OskarStark** [comment]
@hhamon thats, what it was before...or i don't understand what you mean

**Comment by fabpot** [comment]
@hhamon #15336

**Comment by hhamon** [comment]
@fabpot thanks for the link, I didn't know there was a discussion about it.

**Comment by fabpot** [comment]
:+1:

**Comment by znerol** [comment]
Last commit resolves merge conflicts due to the recent introduction of `ResettableContainerInterface`.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @znerol.

**Comment by stof** [comment]
@fabpot should ResettableContainerInterface stay a separate interface in 3.0 or no ?

**Comment by fabpot** [comment]
@stof I think it should not.

**Pull request merged**
