### PR TITLE
[Console] A better progress bar

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #9573, #9574, #10187, #9951, related to #9788 |
| License | MIT |
| Doc PR | symfony/symfony-docs#3626 |

TODO:
- [x] add some docs

See what this PR allows you to do easily:

cwzpvk
## New ProgressBar class

First, this PR deprecates `ProgressHelper` in favor of `ProgressBar`. The main difference is that the new `ProgressBar` class represents a single progress bar, which allows for more than one bar to be displayed at a time:

``` php
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Output\ConsoleOutput;

$output = new ConsoleOutput();

$bar1 = new ProgressBar($output, 10);
$bar2 = new ProgressBar($output, 20);
$bar2->setProgressCharacter('#');
$bar1->start();
print "\n";
$bar2->start();

for ($i = 1; $i <= 20; $i++) {
    // up one line
    $output->write("\033[1A");
    usleep(100000);
    if ($i <= 10) {
        $bar1->advance();
    }
    print "\n";
    $bar2->advance();
}
```

And here is how it looks like when run:

progress-bars
## Format Placeholders

This pull request refactors the way placeholders in the progress bar are managed. It is now possible to add new placeholders or replace existing ones:

``` php
// set a new placeholder
ProgressBar::setPlaceholderFormatterDefinition('remaining_steps', function (ProgressBar $bar) {
    return $bar->getMaxSteps() - $bar->getStep();
});

// change the behavior of an existing placeholder
ProgressBar::setPlaceholderFormatterDefinition('max', function (ProgressBar $bar) {
    return $bar->getMaxSteps() ?: '~';
});
```

Several new built-in placeholders have also been added:
- `%remaining%`: Display the remaining time
- `%estimated%`: Display the estimated time of the whole "task"
- `%memory%`: Display the memory usage
## Formats

Formats can also be added (or built-in ones modified):

``` php
ProgressBar::setFormatDefinition('simple', '%current%');

$bar->setFormat('simple');
// is equivalent to
$bar->setFormat('%current%');
```

Built-in formats are:
- `quiet`
- `normal`
- `verbose`
- `quiet_nomax`
- `normal_nomax`
- `verbose_nomax`
## Format Messages

You can also set arbitrary messages that depends on the progression in the progress bar:

``` php
$bar = new ProgressBar($output, 10);
$bar->setFormat("%message% %current%/%max% [%bar%]");

$bar->setMessage('started');
$bar->start();

$bar->setMessage('advancing');
$bar->advance();

$bar->setMessage('finish');
$bar->finish();
```

You are not limited to a single message (`message` being just the default one):

``` php
$bar = new ProgressBar($output, 10);
$bar->setFormat("%message% %current%/%max% [%bar%] %end%");

$bar->setMessage('started');
$bar->setMessage('', 'end');
$bar->start();

$bar->setMessage('advancing');
$bar->advance();

$bar->setMessage('finish');
$bar->setMessage('ended...', 'end');
$bar->finish();
```
## Multiline Formats

A progress bar can now span more than one line:

``` php
$bar->setFormat("%current%/%max% [%bar%]\n%message%");
```
## Flexible Format Definitions

The hardcoded formatting for some placeholders (like `%percent%` or `%elapsed%`) have been removed in favor of a `sprintf`-like format:

``` php
$bar->setFormat("%current%/%max% [%bar%] %percent:3s%");
```

Notice the `%percent:3s%` placeholder. Here, `%3s` is going to be used when rendering the placeholder.
## ANSI colors and Emojis

The new progress bar output can now contain ANSI colors and.or Emojis (see the small video at the top of this PR).

### CODE REVIEW

**Comment by ruudk** [comment]
Is the configuration/setup for the styling in the animated GIF available somewhere?

**Comment by samsamm777** [comment]
@ruudk +1

**Comment by RoySchoep** [comment]
@ruudk +1

**Comment by obstschale** [comment]
For the people, who are also looking for the nice progress bar from the GIF above like I was. It is defined in this test [ProgressBarTest.php](https://github.com/symfony/Console/blob/master/Tests/Helper/ProgressBarTest.php#L654)

**Pull request merged**
