### PR TITLE
[Intl] Update the ICU data to 68.1

### PR DESCRIPTION
**Pull request by jakzal**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Ideally, this should be merged after #39370.

### CODE REVIEW

**Comment by jderusse** [comment]
Thank you @jakzal for working on this.

What is the plan for converting json to php? #23545

**Comment by fabpot** [comment]
#39370 has been merged now, would you like to rebase this one?

**Review by derrabus — APPROVED** [review]

**Comment by jakzal** [comment]
@jderusse I think it's time to get back to that idea :)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @jakzal.

**Pull request merged**
