### PR TITLE
Added people - person singularization

### PR DESCRIPTION
**Pull request by Keeo**
| Q | A |
| --- | --- |
| Branch? | 3.0, this 'bug' is present even in older versions |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Proper singularization for people into person. This change does not affect singularization of persons.

### CODE REVIEW

**Comment by dunglas** [comment]
Status: reviewed

👍 

Fabbot error is a false positive.
A PR should also be opened on older version of this class (in the PropertyInfo component).

**Comment by Keeo** [comment]
Will do in few hours

**Comment by Keeo** [comment]
Here it is for v2.8 - [#18839]

**Comment by fabpot** [comment]
Thank you @Keeo.

**Pull request merged**
