### PR TITLE
do not declare the PSR-7 bridge to be replaced by symfony/symfony

### LINKED ISSUE #51192: `symfony/psr-http-message-bridge` version conflict
### Symfony version(s) affected

6.3

### Description

With https://github.com/symfony/symfony/pull/51100, `symfony/psr-http-message-bridge` was moved into this repo.

What is the update strategy for packages that required this package before?

### How to reproduce

When installing the [Sentry Symfony SDK](https://github.com/getsentry/sentry-symfony), we now run into issues resolving composer dependencies

```
  Problem 1
    - Root composer.json requires sentry/sentry-symfony ^4.9 -> satisfiable by sentry/sentry-symfony[4.9.0, 4.9.1, 4.9.2].
    - sentry/sentry-symfony[4.9.0, ..., 4.9.2] require symfony/psr-http-message-bridge ^1.2||^2.0 -> found symfony/psr-http-message-bridge[v1.2.0, v1.3.0, v2.0.0, ..., v2.3.1] but these were not loaded, likely because it conflicts with another require.
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #51192
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
we should figure out a proper fix before the stable release

**Comment by derrabus** [comment]
> we should figure out a proper fix before the stable release

Indeed, otherwise projects requiring `symfony/symfony` and `symfony/psr-http-message-bridge` will run into interesting problems.

**Review by derrabus — APPROVED** [review]
👍🏻 as a temporary fix

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Comment by artyuum** [comment]
I think this might be related. https://github.com/symfony/symfony-docs/issues/19018

**Pull request merged**
