### PR TITLE
Removed spaces before semicolon

### PR DESCRIPTION
**Pull request by dereckson**
'lorem ; ipsum' → 'lorem; ipsum'

| Q | A |
| --- | --- |
| Fixed tickets | #17242 |
| License | MIT |

### CODE REVIEW

**Comment by sstok** [comment]
:+1:

**Comment by Tobion** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @dereckson.

**Pull request merged**
