### PR TITLE
[TypeInfo] Prevent creation of composite with only same types

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | 7.3
| Bug fix?      | no
| New feature?  | no
| Deprecations? | yes
| Issues        | 
| License       | MIT

Prevent creation of composite with only same types, such as `Type::union(Type::string(), Type::string())`.
This was possible before, and created an inconsistent union type.

I didn't treat that as a bug fix because it'll cause BC breaks. But this can be discussed.

### CODE REVIEW

**Comment by stof** [comment]
As this is a BC break, it needs to trigger a deprecation instead of an error. The component is not experimental anymore, so BC breaks are not allowed in minor versions.

**Comment by mtarld** [comment]
You're totally right, updated, thanks :slightly_smiling_face:

**Comment by GromNaN** [comment]
> I didn't treat that as a bug fix because it'll cause BC breaks. But this can be discussed.

Why is it a bug?

**Comment by mtarld** [comment]
`Type::union(Type::string(), Type::string())` is returning `UnionType` with a single `BuiltinType<string>` inside. Therefore, it represents a union of only one type, which is not logical to me.

**Comment by GromNaN** [comment]
> which is not logical to me

It is not logical to me either, but in practice it's not wrong.

Why would you want to add a constraint? It forces the calling code to check that there are no duplicate types.

To be sure that you get an actual union or intersection type, you can check the number of embedded types.

```php
$type = Type::union(Type::string(), Type::string())
if (count($type->getTypes()) === 1) {
    $type = $type->getTypes()[0];
}
```

If the return type of `Type::union()` was more permissive, we could return the single type directly in that situation.

**Comment by mtarld** [comment]
Yes, and this is what I have done to overcome that.

To me, such constraint will have ensured that a union/intersection type is a composite type.
But I agree that it forces the user to do check to avoid an exception, and that's why it has to be combined with an update of `Type::union` and `Type::intersection`.

Unfortunately, the only backward compatible change I can see so far is:
- 7.3: deprecate `Type::union` and `Type::intersection` in favor of `Type::unionBis`, `Type::intersectionBis` (with the right signature)
- 8.1: deprecate `Type::unionBis`, `Type::intersectionBis` in favor of  `Type::union` and `Type::intersection` (with the updated signature)
- 9.0: remove `Type::unionBis`, `Type::intersectionBis`

This leads us to November 2027 :sweat_smile:, but maybe you have a better idea? Or maybe it just doesn't worth it?

**Review by chalasr — COMMENTED** [review]
Not sure we want to forbid representing valid types even though they don't make sense as TypeInfo is not about linting but providing information?

**Comment by mtarld** [comment]
But even to PHP, `string|string` is not a valid type. IE the following code won't work:
```php
class Foo
{
  public function bar(): string|string
  {
    return 'baz';
  }
}
```

**Comment by chalasr** [comment]
Fair, I thought it was after reading the discussion. Makes sense as a feature then.

**Comment by mtarld** [comment]
After a second thought, this PR with the `TypeFactoryTrait` update will force the user to check that the returned type is effectively a `UnionType` (which is the common use case), instead of checking that the union contains several types (which is not the common use case).

So I don't think it's worth it.

**Pull request closed without merging**
