### PR TITLE
[HttpFoundation] fix expected argument type docblock

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Fixed tickets |  |
| License | MIT |

### CODE REVIEW

**Comment by xabbuh** [comment]
Actually, we should probably change the type for the other `get*()` methods too. What do you think?

**Comment by Tobion** [comment]
Yes getDigits, getAlnum and getAlpha must be changed to string.

**Comment by xabbuh** [comment]
Updated those three methods as well.

**Comment by Tobion** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
