### PR TITLE
[EventDispatcher] Added the sorted priority information on phpdoc of the getListeners method

### PR DESCRIPTION
**Pull request by dupuchba**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | no |
| License | MIT |

Added the sorting by descending priority information on the `EventDisparcherInterface`

### CODE REVIEW

**Comment by xabbuh** [comment]
I don't feel that this information should be added to the interface, but to the actual implementation in the `EventDispatcher` class instead. Adding this information to the interface adds a new requirement to fullfil for third-party implementation of the interface which should be considered a BC break.

**Comment by dupuchba** [comment]
Ok @xabbuh I didn't thought about that :-).
Let me add The information to the `EventDispatcher` instead.

**Comment by dupuchba** [comment]
@xabbuh done, tell me if you have other observations :-).

**Comment by stof** [comment]
@xabbuh this is already a requirement today actually. The code already relies on listeners being sorted (the TraceableeventDispatcher would dispatch in the wrong order in case the inner dispatcher does not return them sorted for instance). So it is already a requirement of the interface

**Comment by dupuchba** [comment]
@stof ok, I was not sure about it so It has to go on the interface.

**Comment by dupuchba** [comment]
@stof @xabbuh done

**Comment by xabbuh** [comment]
@stof The it must indeed be added to the interface itself.

Sorry for the confusion @dupuchba.

**Comment by dupuchba** [comment]
@xabbuh no problem, your feedback was still valuable.

**Comment by dupuchba** [comment]
@xabbuh is it ok to merge ?(ping @stof )

**Comment by jakzal** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @dupuchba.

**Pull request merged**
