### PR TITLE
Fix return type in isAllowedProperty method on ReflectionExtractor class

### LINKED ISSUE #41103: Method isAllowedProperty on ReflectionExtractor class can return int type
**Symfony version(s) affected**: 5.2.4

**Description**
Method `isAllowedProperty` on `ReflectionExtractor` class should returns  `bool` type, but returns `int`: 
Screenshot 2021-05-04 at 10 01 24

It occurred in in Sylius

### PR DESCRIPTION
**Pull request by Tomanhez**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41103
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
We don't use `boolval()` in this codebase. Please apply the fix suggested by fabbot.

Can you also please add a failing test for your issue?

**Comment by derrabus** [comment]
You opened a bugfix for 5.2, but you have created a PR for the 5.x branch. Can you please rebase and retarget your PR?

**Comment by Tomanhez** [comment]
@derrabus I changed `boolval` for `(bool)` but with additional brackets and its work properly.

**Review by derrabus — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @Tomanhez.

**Pull request merged**
