### PR TITLE
[Finder] Deprecate FilterIterator

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | yes 
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/22820#pullrequestreview-39351934
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
That's for 3.4

**Comment by ogizanagi** [comment]
Oops, indeed. Rebased & re-targeted.

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Comment by nicolas-grekas** [comment]
The corresponding test case should be marked as legacy

**Comment by nicolas-grekas** [comment]
Thank you @ogizanagi.

**Pull request merged**
