### PR TITLE
Added asset PackageJsonVersionStrategy

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| Branch?       | master for features
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | symfony/symfony-docs#10431

In some cases where its not possible to implement a manifest file for asset versions you can use the version number from your package.json and increase this version number always when you build your assets e.g.:

```json
{
    "version": "1.2.3",
    "scripts": {
        "build": "npm run build:assets && npm run version:patch",
        "build:assets": "...",
        "version:patch": "npm version patch --git-tag-version false"
    }
}
```

### CODE REVIEW

**Comment by fabpot** [comment]
@weaverryan Can you have a look at this pull request please?

**Comment by weaverryan** [comment]
This is really nice - great docs & tests included, and it's certainly a valid use-case. However, I'm not convinced it's a common enough use-case that we should support. You can already set the `version_strategy` to a service and the logic itself - the `PackageJsonVersionStrategy` is only about 50 lines long. When we added the JSON manifest strategy, that was a special situation because it hooked directly up with new tooling (Encore) that was part of the official tooling for Symfony.

So, as nice as this is (and I really hope to see more PR's from you), it's a 👎 from me

**Comment by fabpot** [comment]
Thanks @weaverryan for the review. I'm going to close then. Thank you @alexander-schranz for proposing.

**Comment by alexander-schranz** [comment]
@weaverryan Thank you to have a look at it and I'm understanding your decision if you don't want to support it.

To support such strategies it would be great to rename the `json_manifest_path` to `version_file_path` or something similiar which can be used to be accessed by every strategy? But not sure how to handle this without breaking the exist interfaces.

**Comment by weaverryan** [comment]
Hmm, if you *do* create a custom strategy like your’s, you won’t have access to json_manifest_path - that’s an internal thing to FrameworkBundle. If you wanted to create a 3rd party bundle with your feature, you’d need to add some new config options for your bundle. Basically, whatever we name it json_manifest_path is meant only for that *one* exact feature.

**Pull request closed without merging**
