### PR TITLE
[2.6][EventDispatcher] make listeners removable from an executed listener

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13972 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by aitboudad** [comment]
:+1:

**Comment by dupuchba** [comment]
@xabbuh I don't understand what you are trying to do and the uses cases. Can you explain it to me ?

**Comment by xabbuh** [comment]
@dupuchba The use case is to be able to remove a listener from of one of the event listeners while an event us dispatched. Previously, this was not possible because during the dispatch all listeners are wrapped by the `TraceableEventDispatcher` with a `WrappedListener` while the code was looking for an unwrapped one (see the example in #13972).

**Comment by dupuchba** [comment]
ok :+1:

**Comment by aitboudad** [comment]
@xabbuh for the performance reason I suggest to store object hash instead in `wrappedListeners`

**Comment by xabbuh** [comment]
@aitboudad The issue is that a listener is not necessarily an object.

**Comment by stof** [comment]
@aitboudad I don't see how this would increase performance anyway. The listener itself will already be in memory anyway inside the WrapperListener

**Comment by xabbuh** [comment]
@stof It would speed up the lookup in `removeListener()`, but I don't think that it's that important anyway (dispatching an event already requires to touch each listener).

**Comment by stof** [comment]
@xabbuh how would it be faster than the ``===`` check ?

**Comment by xabbuh** [comment]
@stof We wouldn't have to iterate the saved listeners, but access `$this->wrappedListeners[$eventName][$listener]` instead.

**Comment by stof** [comment]
@xabbuh anyway, this is a no-go. Listeners are callable, not objects

**Comment by xabbuh** [comment]
@stof Sure, that's why I did it this way.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
