### PR TITLE
[VarExporter] Bugfix/workaround jit issue

### PR DESCRIPTION
**Pull request by verfriemelt-dot-org**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fixes/Workaround for #54053
| License       | MIT

I managed to fix the erratically behavior with this patch, but i have no idea how one would test this.
It seems tracing jit has some issues with the ternary operator.

Let me know what you think, i have no idea how to work with that properly :)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thanks for this! Did you report the issue to php-src? It should be fixed there ideally, and VarExporter could be showcased as the reproducer for them.

**Comment by nicolas-grekas** [comment]
I'm now seeing https://github.com/php/php-src/issues/13508 so I have my answer :)

**Comment by verfriemelt-dot-org** [comment]
i did :)
maybe i am to tired after figuring all this out, but i really do not understand how i broke the test in the pipeline here? :thinking:

**Comment by nicolas-grekas** [comment]
Thank you @verfriemelt-dot-org

**Comment by k0d3r1s** [comment]
@nicolas-grekas any ETA on next 6.4 minor release with this fix?

**Comment by nicolas-grekas** [comment]
We do releases at the end of each months (and we're at the end of one, so shouldn't be long.)

**Pull request merged**
