### PR TITLE
allow Twig 4

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Review by GromNaN — APPROVED** [review]
It should work once https://github.com/symfony/symfony/issues/52987 is fixed.

**Comment by derrabus** [comment]
Why don't we target 6.4?

**Comment by xabbuh** [comment]
> Why don't we target 6.4?

I considered this change as a new feature. If we chose 6.4 as the target, then why not 5.4?

**Comment by fabpot** [comment]
Twig 4.x will probably never be released as is; this is "just" a branch that allows me to work on the next version that should be part of Symfony (7.1 hopefully). So, allowing it only on 7.1 for now works for me until we have a solid migration plan.

**Comment by derrabus** [comment]
> I considered this change as a new feature.

We usually don't consider supporting new versions of 3rd party libraries as a new feature, but what @fabpot says makes sense to me. If Twig 4.x is a transitional branch that will eventually become symfony/twig 7.1, we should limit this change to the 7.1.x branch.

**Review by chalasr — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
