### PR TITLE
[Asset] ChooseBaseUrl should return an offset

### PR DESCRIPTION
**Pull request by bburnichon**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Enforce chooseBaseUrl to return an integer offset to the baseUrls member.

### CODE REVIEW

**Comment by xabbuh** [comment]
Returning an int doesn't respect the description of what the message is supposed to do:

> This method should always return the same base URL for a given path.

**Comment by bburnichon** [comment]
Ah, I missed this. It should be
> This method should always return the same base URL offset for a given path.

**Comment by dosten** [comment]
I don't know if "offset" is the best word, IMO "index" is better.

**Comment by bburnichon** [comment]
I don't mind changing "offset" into "index". @xabbuh WDYT? Should I make change and squash commits?

**Comment by fabpot** [comment]
index sounds better

**Comment by bburnichon** [comment]
@xabbuh @fabpot Changed 'offset' to 'index'.

**Comment by fabpot** [comment]
Thank you @bburnichon.

**Pull request merged**
