### PR TITLE
[Form] Fixed GroupSequence with "constraints" option

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22373
| License       | MIT
| Doc PR        | ~

### CODE REVIEW

**Comment by HeahDude** [comment]
For a lighter diff, https://github.com/symfony/symfony/pull/23722/files?w=1.

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
ping @symfony/deciders

**Comment by xabbuh** [comment]
@HeahDude Can you rebase to trigger a Travis CI build?

**Review by ogizanagi — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by ogizanagi** [comment]
Thank you @HeahDude.

**Pull request merged**
