### PR TITLE
[Intl] bump icu 67.1

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

mainly some new locales+scripts (see 3a3a9ba)

### CODE REVIEW

**Comment by stof** [comment]
@ro0NL is the `Version` field necessary in all these JSON files ? Diffs for upgrades would be much more readable if we were not updating a version in all files, where it is often the only change.

**Comment by ro0NL** [comment]
@stof agree and done. We dont use this data, nor is it accessible by users.

**Comment by stof** [comment]
and even for contributors, this number is confusing as this version is not the ICU version either

**Review by stof — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @ro0NL.

**Pull request merged**
