### PR TITLE
[CS] Remove useless else statements. (2.3)

### PR DESCRIPTION
**Pull request by SpacePossum**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

This PR is to see if a new fixer @ PHP-CS-Fixer should be added to the set of default fixers of Symfony.
The fixer removes `else`-case when those are overcomplete.

For ref:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1773

### CODE REVIEW

**Comment by xabbuh** [comment]
There are some `elseif` that also are not needed.

**Comment by SpacePossum** [comment]
Indeed :+1:. However fixers have only one task. So for the `elfeif` cases a new one has to be made.

**Comment by fabpot** [comment]
While I agree with the concept, I won't merge this into 2.3, that would lead to too many headaches when merging to other branches.

**Comment by SpacePossum** [comment]
Thank you for your thoughts :)

We can continue in a couple of ways:
- do the fixing on 3.0 / master only; however this won't make merging easier I think
- do the fixing on all release branches and master (in separate PR's); should be easy using the tool, however I'm not sure if this won't cause other merge headaches in the future
- leave the code base as is and add the fixer to the SF set; this will stop new useless `else` statements to be added, however if one would touch any of the files in this PR fabbot.io would suggest to change the file causing DX to decline
- leave the code base as is and don't add the fixer to the SF set

Food for thought :)

I go for the last option ATM, if you want me to proceed otherwise please let me know.

**Comment by javiereguiluz** [comment]
@SpacePossum Symfony 2.3 support will end in 103 days (except for security issues). So maybe then we can merge this into 2.7 upwards.

**Comment by fabpot** [comment]
Merging it in 2.7 would lead to the exact same problems; it's not worth it.

**Comment by SpacePossum** [comment]
Thanks @javiereguiluz for the insight. I agree with @fabpot here, it might not be worth it. Thanks again, now I know on what level to put the fixer :)

**Pull request closed without merging**
