### PR TITLE
[String] Fix string to snake case conversion

### PR DESCRIPTION
**Pull request by Kolyunya**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | ?
| New feature?  | ?
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 
| Breaking change | ‼️🚨‼️

Hi guys!

It seems to me that snake-case converter could be enhanced a bit.
Concretely, I believe that letters should be separated from numbers. What do you think?

Before: `symfony5isGreat` → `symfony5is_great`.
After: `symfony5isGreat` → `symfony_5_is_great`.

Notice that if you would decide to merge this, this is a breaking change.

### CODE REVIEW

**Comment by OskarStark** [comment]
I would rather go with:

symfony5_is_great

**Comment by Seb33300** [comment]
@Kolyunya I think the case is wrong in your example.

It should be: 
`symfony5IsGreat` → `symfony5_is_great`.

**Comment by Kolyunya** [comment]
@Seb33300 my idea was that sequences of letters should be separated from sequences of numbers disregarding the capitalization of letters. So the example I provided is indeed intentional: `symfony5isGreat` → `symfony_5_is_great`.

@OskarStark please let me know if this is the final decision regarding the patch, I will update the tests and the production code accordingly.

Although, I believe that 
1. We should be separating parts of the string that are not semantically coherent. The separation should work word-wise. `Symfony 5` are two words and they don't seem to be a single coherent lexical unit.
2. In natural writing numbers never stick to the preceding letters. Example:

image

**Comment by OskarStark** [comment]
I agree, your example makes sense, but this sounds more like a bugfix to me, also I cannot see a BC break here.

**Comment by OskarStark** [comment]
@nicolas-grekas WDYT?

**Comment by fabpot** [comment]
I don't think this is worth it as this is a BC break.

**Comment by javiereguiluz** [comment]
Thanks for this proposal. I also think that we shouldn't do this change. In addition to the BC break, there are many legit cases (think of commercial product names, brands, etc.) where splitting by the numbers would be wrong.

**Pull request closed without merging**
