### PR TITLE
[VarDumper] display the signature of callables

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/bobthecow/psysh/issues/218
| License       | MIT
| Doc PR        | -

E.g.

capture d ecran de 2018-06-29 12-08-13

or

image

### CODE REVIEW

**Review by ogizanagi — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by bobthecow** [comment]
I love that you dug up a three year old issue and fixed it :)

**Comment by stof** [comment]
@nicolas-grekas isn't this missing the handling of by-ref parameters and of variadic parameters when building the signature ?

**Comment by stof** [comment]
Answering my own question: this is already handled by `castFunctionAbstract`

**Pull request merged**
