### PR TITLE
[ProxyManagerBridge] Drop the bridge

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 7.0
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

As planned in https://github.com/symfony/symfony/pull/48484

### CODE REVIEW

**Review by derrabus — APPROVED** [review]
🔥

**Review by stof — CHANGES_REQUESTED** [review]
this misses the removal of `replace` in the root composer.json

**Comment by stof** [comment]
Btw, `Verify Packages` currently does not catch this mistake in the CI.

**Comment by nicolas-grekas** [comment]
> this misses the removal of replace in the root composer.json

fixed!

**Review by stof — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
