### PR TITLE
[Form] EntityType - Query Builder with closure that returns null

### PR DESCRIPTION
**Pull request by raziel057**
| Q | A |
| --- | --- |
| Branch? | "master" - I don't know if it must be pushed in other branches |
| Bug fix? | yes - Fix regression see https://github.com/symfony/symfony/issues/17352 |
| New feature? | no - Reintroduced a lost feature |
| BC breaks? | yes - For releases after commit eb08baa (2 Aug 2015) see https://github.com/symfony/symfony/issues/17352#issuecomment-244333823 |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17352 |
| License | MIT |
| Doc PR | Blog Post http://symfony.com/blog/new-in-symfony-2-8-form-improvements#allowed-to-return-null-for-query-builder |

### CODE REVIEW

**Comment by HeahDude** [comment]
This is working, but not logical to me. The normalizer should not be used to change the type of an option, only its value. also we should remain consistent: returning `null` from the callable should trigger the same behavior as assigning it: loading all entities.

Maybe another way would be to simply allow to assign/return `false`.

**Comment by raziel057** [comment]
@HeahDude I understand your opinion and I'm must say I'm also not very convinced by this feature because of the inconsistency between returning ``null`` from the callable and by assigning it.

Anyway I think it's not a good solution to allow ``false`` because the common usage for this feature is to allow to return QueryBuilder or null from a doctrine repository. Returning ``false`` in this context seems bad for me because this method must be also called from other services in which it would be weird to check if we have a QueryBuilder or ``false`` rather than ``null``.

```php
$event->getForm()->add('events', EntityType::class, [
    'class' => 'AppBundle:Event',
    'property' => 'title',
    'query_builder' => function(EntityRepository $er) {
        return $er->getEventQueryBuilder();
    }
]));

// ...

public function getEventQueryBuilder()
{
    if ( ... some condition ... ) {
        return null;
    }

    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select(...)->...;
}
```

So maybe the best is to used the more verbose way (with the need to inject the entityManager):

```php
$qb = $this->entityManager->getRepository('AppBundle:Event')->getEventQueryBuilder();

$events = ($qb !== null) ? $qb->getQuery()->getResult() : array();

$event->getForm()->add('events', EntityType::class, array(
	'class' => 'AppBundle:Event',
	'property' => 'title',
	'choices' => $events,
));
```

**Comment by HeahDude** [comment]
Hey @raziel057, I still don't really like this implementation. Could you please provide a case where this is really needed?
Because looking at the original example again (see http://symfony.com/blog/new-in-symfony-2-8-form-improvements#allowed-to-return-null-for-query-builder), this can be handled already pretty easily.

The original use case:
```php
// in a form listener:
$event->getForm()->add('events', 'Symfony\Component\Form\Extension\Core\Type\EntityType', [
    'class' => 'AppBundle:Event',
    'property' => 'title',
    'query_builder' => function(EntityRepository $er) {
        return $er->getEventQueryBuilder();
    }
]));

// ...

// in a repository:
public function getEventQueryBuilder()
{
    if ( ... some condition ... ) {
        return null;
    }

    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select(...)->...;
}
```
A possible way of how this can be solved already:
```php
// in the form listener
$event->getForm()->add('events', 'Symfony\Component\Form\Extension\Core\Type\EntityType', [
    'class' => 'AppBundle:Event',
    'property' => 'title',
    'query_builder' => function(EntityRepository $er) {
        return $er->getEventQueryBuilder();
    },
    // just add this option
    'choice_loader' => function (Options $options, $defaultLoader) {
        // we're getting here lazily the resolved option from above, and the resolved loader
        return $options['query_builder'] ? $defaultLoader : null;
    }
]));
```
I've not tested it for real but this should work, by overriding the loader definition depending on the resolved query builder, the ChoiceType will use the empty choices array if the loader is null.

If so, I'm not sure this PR should be merged after all, unless there are practical use cases that cannot live without it. Consider also https://github.com/symfony/symfony/issues/17352#issuecomment-244313095.

Btw, returning `null` from a repository method that should return a query builder looks weird to me, especially to configure the EntityType.

What could be done and better for performances, is to move this logic in a specific type:
```php
// in the form listener
$event->getForm()->add('events', 'AppBundle\Form\Type\EventsType', [
    'some_dynamic_thing' => $thing,
]);

// in the type
class EventsType extends AbstractType
{
    private $repository;

    public function __construct(EventRepository $repository)
    {
        $this->repository = $repository;
    }

    public function getParent()
    {
        return ChoiceType::class;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            - >setDefaults([
                'choices' => function (Options $options) {
                    return $this->getChoices($options['some_dynamic_thing']);
                },
                'choice_value' => 'id',
                'choice_label' => 'title',
                'some_dynamic_thing' => null,
            ])
        ;
    }

    /**
     * @return Event[]
     *
     */
    public function getChoices($thing = null)
    {
        if ($thing) {
            return array();
        }

        return $this->repository->getEvents($thing);
    }
```

This is really simple to do and to reuse. To go even further in lazy loading choices, there is the `ChoiceLoaderInterface`, but this require to implements three methods, one to return a loaded choice list object (even constructed with an empty array) and two to handle the choices to values transformations, all can use the `choice_value` option.

Given the reasons above, I'm 👎 about this for now.
_______
In any case the milestone should be 3.x IMHO.

**Comment by raziel057** [comment]
@HeahDude as said in a previous comment, I understand your point concerning the inconsistency between returning null from the callable and by assigning it. Anyway sometimes it can be necessary to return a Query Builder or null from method of repositories to have a consistency between different context of call.

For example, you need to get a list of events by if your user have don't have rights or if an element is in a bad state you may want to return null to have an empty array. In that case you don't need to execute the query.

I know we can live without this feature that just aim to ease the basic writing of entity fields that can be empty on specific cases. I let you decide what is the best.

**Comment by HeahDude** [comment]
I understand your point. The thing is that `query_builder` option is meant to customize it or let the default one be executed so this looks like a hack to me.

This situation should be rare enough to rely on overriding the loader option instead, the simplest way being to set `choices` option to an empty array (because it's set to `null` by DoctrineType to allow this flexibility).
The others being to override it lazily depending the query builder like in my example above or like the comment I linked, the most complicated way is by implementing the specific interface (which should not be that complicated).

IMHO it should be enough to handle this consistently. But I'm waiting to hear what others think :)

**Comment by robfrawley** [comment]
Why was the behavior of [null resulting in an empty list](http://symfony.com/blog/new-in-symfony-2-8-form-improvements#allowed-to-return-null-for-query-builder) outright removed after it was promoted on the blog?

**Comment by fabpot** [comment]
What's the status of this PR? How do we move forward?

**Comment by raziel057** [comment]
I think we can live without it by providing "choices" rather than using the "query_builder" property.

**Comment by nicolas-grekas** [comment]
@raziel057 ok to close then?

**Comment by raziel057** [comment]
Yes

**Pull request closed without merging**
