### PR TITLE
[Validator] UuidValidator must accept a Uuid constraint.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by hhamon** [comment]
At first sight it may look like a BC break but the `UuidValidator` class already has several methods arguments that are typehinted on the `Uuid` constraint concrete class in their signatures.

**Comment by ro0NL** [comment]
Im not sure.. some validators do it, others dont. There are also not much validators that typehint against constraints (ie the job is alwasy done directy  in `validate()`).

Currently we can give an any constraint providing the same options (which is nice i guess... but only works if we depend on options, not constraints) for most validators. This should be consistent imo.

Undefined option calls failing is a different story :)

**Comment by hhamon** [comment]
If you look at the `validateLoose` and `validateStrict` methods, they already typehint against the `Uuid` constraint concrete type. It was already forced by design.

**Comment by ro0NL** [comment]
From a class scope the type check is good (ie. better than violating typehints), from a package scope i would just stick with `private function validateLoose($value, Constraint $constraint)`. However currently its in between.. so lets see :)

**Comment by fabpot** [comment]
Do we have any other class with such a check? If not, I propose to close this PR as it does not really add any value.

**Comment by ro0NL** [comment]
This one added a lot: https://github.com/symfony/symfony/commit/df56c23d8f1fc94f46853018df84a2c3c3ba2613

**Comment by hhamon** [comment]
@fabpot every other concrete validator classes does that! For instance `LengthValidator::validate` method checks the received constraint is an instance of the `Length` constraint.

**Comment by fabpot** [comment]
Thank you @hhamon.

**Pull request merged**
