### PR TITLE
[DoctrineBridge] no-op RegisterUidTypePass if DBAL types aren't loaded

### LINKED ISSUE #39400: [Doctrine Bridge] RegisterUidTypePass relies on non-existent parameter "doctrine.dbal.connection_factory.types"
**Symfony version affected**: 5.2.0

**Description**
While updating a bundle I noticed that running tests with Symfony 5.2 raised this error.

**How to reproduce**
If `dbal` is not explicitly enabled by config, DoctrineBundle's `DoctrineExtension` won't [set `doctrine.dbal.connection_factory.types`](https://github.com/doctrine/DoctrineBundle/blob/2.2.2/DependencyInjection/DoctrineExtension.php#L117). `RegisterUidTypePass` [tries to access it anyway](https://github.com/symfony/symfony/blob/v5.2.0/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterUidTypePass.php#L31).

**Additional context**
[installed dependencies](https://travis-ci.org/github/craue/CraueFormFlowBundle/jobs/748517984#L451)
[error log](https://travis-ci.org/github/craue/CraueFormFlowBundle/jobs/748517984#L538)

### PR DESCRIPTION
**Pull request by craue**
| Q             | A
| ------------- | ---
| Branch?       | 5.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #39400
| License       | MIT

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Comment by derrabus** [comment]
Can we add a test for this please?

**Comment by craue** [comment]
@derrabus, how?

**Comment by jderusse** [comment]
> @derrabus, how?

```php
<?php

namespace Symfony\Bridge\Doctrine\Tests\DependencyInjection\CompilerPass;

use PHPUnit\Framework\TestCase;
use Symfony\Bridge\Doctrine\DependencyInjection\CompilerPass\RegisterUidTypePass;
use Symfony\Bridge\Doctrine\Types\UlidType;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class RegisterUidTypePassTest extends TestCase
{
    public function testRegistered()
    {
        $container = new ContainerBuilder();
        $container->setParameter('doctrine.dbal.connection_factory.types', ['foo' => 'bar']);
        (new RegisterUidTypePass())->process($container);

        $expected = [
            'foo' => 'bar',
            'uuid' => ['class' => UuidType::class],
            'ulid' => ['class' => UlidType::class],
        ];
        $this->assertSame($expected, $container->getParameter('doctrine.dbal.connection_factory.types'));
    }

    public function testRegisteredDontFail()
    {
        $container = new ContainerBuilder();
        (new RegisterUidTypePass())->process($container);

        $this->expectNotToPerformAssertions();
    }
}
```

**Comment by craue** [comment]
@jderusse, I see, thanks. Do you want to add it directly?

**Comment by jderusse** [comment]
> @jderusse, I see, thanks. Do you want to add it directly?

Yes please, add this class in you PR. This should cover the Pass

**Comment by craue** [comment]
@jderusse, what I wanted to know is either if you want to add this commit on your own or if you want me to add it. 😏 I just did now.

**Review by jderusse — APPROVED** [review]

**Review by derrabus — APPROVED** [review]
Great test, @craue! 😉

**Comment by derrabus** [comment]
Thank you @craue.

**Pull request merged**
