### PR TITLE
[Translation] Add support for constants in yaml translation files

### PR DESCRIPTION
**Pull request by webmastard**
| Q             | A
| ------------- | ---
| Branch?       | 3.4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | no
| Fixed tickets | #25496 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
I am 👎 here. To me this is not a bug fix. By the way, we merged something like this with #25295 as a new feature for Symfony 4.1.

**Comment by chalasr** [comment]
Same as @xabbuh

**Comment by webmastard** [comment]
Sorry, I have not seen #25295 before.
I think it's a bug because we can use constants in yaml file since 3.2 but we can't use it in translation files.

**Comment by chalasr** [comment]
It never worked, it's just unsupported. Not a bug but a missing feature really, which we would have preferred to add when introducing the constant, sadly nobody thought about it before.

**Comment by fabpot** [comment]
Closing for the reasons explained by @xabbuh and @chalasr

**Pull request closed without merging**
