### PR TITLE
[DI] don't use array_map to resolve services

### PR DESCRIPTION
**Pull request by hadriengem**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16314 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by Tobion** [comment]
Thank you @hadriengem.

**Pull request merged**
