### PR TITLE
Added LB translation for #26327 (Errors sign for people that do not see colors)

### PR DESCRIPTION
**Pull request by mweimerskirch**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | n/a
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #26327
| License       | MIT

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]

**Comment by ostrolucky** [comment]
Shouldn't target be 2.7?

**Comment by mweimerskirch** [comment]
@ostrolucky No, this is related to #26327 which was only merged with 3.4 and 4.0

**Comment by fabpot** [comment]
@ostrolucky is correct. We are always merging translation on the lowest branch to ease our life.

**Comment by fabpot** [comment]
Thank you @mweimerskirch.

**Pull request merged**
