### PR TITLE
[Console] Added three state long option

### PR DESCRIPTION
**Pull request by ocke**
[Console] Added three state long option

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #11572 |
| License | MIT |
| Doc PR |  |

A three state long option, instead of the current 2 state version:
- Not setting the longoption will make the default set to false, just like a standard longoption.
- Setting the longoption without a value will set it to it's default
- Setting the longoption with a value will set it to that value.

Let's say --dev

```
php tool.php
array(1) {
  'dev' =>
  bool(false)
}
php tool.php --dev
array(1) {
  'dev' =>
  'the default value'
}
php tool.php --dev=test
array(1) {
  'dev' =>
  'test'
}
```

A couple of notes:
- I assume you guys agree that it's not a good idea to break current functionality. Therefor VALUE_OPTIONAL will stay how it is and I added a new constant: VALUE_OPTIONULL.
- All the tests still work!
- We need to come up with a better name.
- I'll need to write new test for the new config option (VALUE_OPTIONULL).

### CODE REVIEW

**Comment by OndraM** [comment]
Personally, I prefer solution from this PR: https://github.com/symfony/symfony/pull/12773. It could be used for the same use-case, but it has minimal impact on other code. The only disadvantage is that it may not be as straightforward as using dedicated option type.

**Comment by ocke** [comment]
I leave it up to you guys to decide what's best. I think my solution works great, the tests show it works, but it obviously involves more code changes. It's there for you guys to use, or not.

**Comment by wtfred** [comment]
Hi guys, looking forward for this to be merged, i just start using Console and ran directly into this problem :s

**Comment by OskarStark** [comment]
any news here?

The PR: #12769 is closed

**Comment by fabpot** [comment]
Closing as #12773 make it work without having to add another configuration setting.

**Pull request closed without merging**
