### PR TITLE
[BUG-Fix] issue#29187 Duplication of form_errors field

### PR DESCRIPTION
**Pull request by jawadmjn**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes/no 
| Tests pass?   | yes    
| Fixed tickets | #29187 
| License       | MIT

Releated to [issue](https://github.com/symfony/symfony/issues/29187)

### CODE REVIEW

**Comment by ro0NL** [comment]
Im not sure it's the right fix, as you basically revert https://github.com/symfony/symfony/pull/24435 now

**Comment by xabbuh** [comment]
In #29207 I propose a slightly different way to fix this issue.

**Comment by jawadmjn** [comment]
@ro0NL Actually it is not a revert of #24435, Because in #24435 happening so many other things also.

I just fix the thing what I need as per describe in the issue [29187](https://github.com/symfony/symfony/issues/29187#issuecomment-437897107)

Because in the end, we do not want to destroy our layout when errors are appearing in formField.

**Comment by xabbuh** [comment]
Thank you for your work on this. But the right "fix" to clarify the behaviour in the documentation.

**Comment by jawadmjn** [comment]
@nicolas-grekas  @xabbuh Hi and thanks for the feedback, but I really did not get it that how can we go with a solution when our LayOut is broken?  As mentioned [Here](https://github.com/symfony/symfony/issues/29187#issuecomment-437897107)

**Comment by xabbuh** [comment]
@jawadmjn You can still overwrite the `form_label` block to customise how and when errors are rendered.

**Pull request closed without merging**
