### PR TITLE
container:debug CLI output improvements for excluded services

### PR DESCRIPTION
**Pull request by apfelbox**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes (not sure)
| Deprecations? | no
| Tickets       | —
| License       | MIT
| Doc PR        | —

Normally I test whether the exclusion rules from the service container of my bundles work correctly by just using the `debug:container` command and looking whether my excluded services occur in the last.
However, due to the latest changes in https://github.com/symfony/symfony/pull/46279 all services (excluded or not) are always in this list.

You need to open the definition to see if it was excluded:

CleanShot 2022-12-12 at 11 01 08

This PR proposes two things:

1. add a more prominent warning to the service definition details screen that the service is excluded

CleanShot 2022-12-12 at 11 01 52
(wording tbd)

2. mark the services as excluded in the list (right now by graying them out):

CleanShot 2022-12-12 at 11 02 44

If this looks like something you want to include, I will add the "graying out" part to the table view as well.
wdyt?

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Good catch. I'd suggest being more aggressive and just not list those services, and do it on 6.2. WDYT?

**Comment by apfelbox** [comment]
@nicolas-grekas I think your proposal would make even more sense: no point in showing the service details for a class that is not, well, a service. 😄  Will update my PR for that 👍

**Comment by apfelbox** [comment]
@nicolas-grekas so I updated the implementation: now based on 6.2 and I just excluded the services from the choice list.

However a probably better implementation would be to add a `ContainerBuilder::getNonExcludedServiceIds()` (naming tbd) and just use that? This way it would also more or less directly work in the table view of this command.

And if we go that route, should I just look up every definition in this call and check or is there a smarter way?

**Review by nicolas-grekas — APPROVED** [review]
LGTM as is, no need for more APIs.

**Comment by nicolas-grekas** [comment]
Thank you @apfelbox.

**Comment by apfelbox** [comment]
@nicolas-grekas the drawback of not adding a new API is that the call without a filter

```bash
php bin/console debug:container
```

will still list them. This call doesn't go through this method, but instead through the descriptors (and they call `$builder->getServiceIds()` directly).

Should we ignore that?

**Pull request merged**
