### PR TITLE
Add russian plural rule to PluralizationRules

### PR DESCRIPTION
**Pull request by cv21**
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by sstok** [comment]
The returns statement is the same as for other locales, any reason why this is needed?
The switch case will continue (even after matching) until it hits a `break` - http://php.net/manual/en/control-structures.switch.php

**Comment by cv21** [comment]
@sstok 
> The returns statement is the same as for other locales, any reason why this is needed?

Is the same as for other locales? No.
Any reason why this is needed? Russian plural expression not works out of the box.

>The switch case will continue (even after matching) until it hits a break

In this case reasonably use just `return`.

**Comment by javiereguiluz** [comment]
@cv21 I have the same doubts as @sstok. I'm looking at the line you added (`return (($number % 10 ...`) and I can't see any difference with the previously existing line.

**Comment by cv21** [comment]
@javiereguiluz 
> and I can't see any difference with the previously existing line

It's just translation for russian language. When when I am on 'ru' locale, I want to have right pluralization rule. Now I have no pluralization rule for russian locale.

Please, show me previously existing line, that have no difference.

**Comment by javiereguiluz** [comment]
@cv21 yes, let me explain in detail:

This is the existing code:

before

And this is the new code you propose:

after

You propose to add the line 147 ... but that line is exactly the same as the line 151 ... which is exactly the same that was applied to Russian language in the previous code. So I'm not saying that your code is wrong, but it looks unnecessary because your code does what we already do.

Anyway, I'm pinging @bocharsky-bw because he speaks both Russian and Ukrainian and maybe he can help us see something that we don't see. Thanks!

**Comment by cv21** [comment]
@javiereguiluz 
> So I'm not saying that your code is wrong

Yeah, it's look not pretty, but it works properly. Under the current architecture of PluralizationRules it the single decision. Maybe, you can suggest other?

**Comment by cv21** [comment]
@javiereguiluz @sstok Russian an Ukrainian have same [plural rules](http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html), but it not same locales. We can make new feature for using one statement for multiple locales, or we can write code such as in my pull-request.

**Comment by dosten** [comment]
@cv12 can you explain why your code works properly? I do not understand what changes

**Comment by cv21** [comment]
@sstok @javiereguiluz @dosten Sorry, it's ok. Thank you!

**Pull request closed without merging**
