### PR TITLE
[Console] Separate formatter for stdout/stderr

### PR DESCRIPTION
**Pull request by alcohol**
[Console]

When piping output from a console command through `| more` for example, stderr is still considered to have color support although stdout does not. When stdout and stderr share the same formatter, this results in color codes being output while this is not desired behaviour.

E.g.

``` php
# stdout.php
<?php
require_once 'vendor/autoload.php';
$out = new Symfony\Component\Console\Output\ConsoleOutput();
$out->writeln('<info>OK</info>');
```

without patch

``` bash
$ php stdout.php | more
ESC[32mOKESC[39m

$ php stdout.php 2>/dev/null | more
OK
```

with patch

``` bash
$ php stdout.php | more
OK
```

The cleanest solution I could think of, was simply cloning the given formatter rather than sharing the same instance.

Partial credit goes to @Seldaek as well for discovering and debugging this unexpected behaviour with me.

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by Seldaek** [comment]
:+1:

**Comment by giosh94mhz** [comment]
for reference: :-1: see https://github.com/symfony/symfony/pull/13449#issuecomment-73912321

**Comment by alcohol** [comment]
While I can understand the concern for non-BC in the case of not "clone-able" Formatters, I think the case of actually running into such a scenario is so highly unlikely that it's negligible.

**Comment by giosh94mhz** [comment]
I agree with you that it's a remote scenario, but still is a BC since put more restriction on the constructor; also cloning a DI instance smells to me. 

So, I don't say this PR should not be merged, but probably is not a good idea to merge it in `2.3`. `2.7` it's almost here and may be a perfect opportunity. :)

**Comment by alcohol** [comment]
@fabpot @xabbuh @Tobion do any of you have any feedback on this PR?

**Comment by xabbuh** [comment]
The fix looks good, but I would prefer if we added an extra `$errorFormatter` argument to the constructor which defaults to `null`. The user would then be able to pass their own formatter for stderr and therefore being able to reference it from the outside (like they can do for stdout). Cloning can be the default behaviour then when the formatter for stderr is omitted.

**Comment by alcohol** [comment]
@xabbuh one additional question then, should calls to `setDecorated`, `setFormatter` and `setVerbosity` still also proxy to stderr when called on a stdout wrapper?

**Comment by xabbuh** [comment]
@alcohol Maybe we should check in if both formatters are the same and only in this case change the stderr related stuff too.

**Pull request closed without merging**
