### PR TITLE
added missing deprecation notice when using the form_enctype function

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @fabpot.

**Comment by xabbuh** [comment]
@fabpot Will this work now and don't lead to issues like #12824?

**Comment by fabpot** [comment]
@xabbuh Shame on me :(

**Comment by fabpot** [comment]
see 9c32972

**Comment by xabbuh** [comment]
:+1:

**Pull request merged**
