### PR TITLE
[Inflector] Remove the component

### PR DESCRIPTION
**Pull request by fancyweb**
| Q             | A
| ------------- | ---
| Branch?       | 6.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Ref https://github.com/symfony/symfony/pull/35092

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by Nyholm** [comment]
This may need some special configuration of the subtree split. 

I'll leave this to be merged by @fabpot

**Comment by nicolas-grekas** [comment]
Please rebase to restart tests :pray:

**Comment by fancyweb** [comment]
@nicolas-grekas The CI is green

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @fancyweb.

**Pull request merged**
