### PR TITLE
[DependencyInjection] Add `#[AutowireClassMap]` to inject a class map into a service

### PR DESCRIPTION
**Pull request by HypeMC**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | -
| License       | MIT

The idea behind this PR is to provide a mechanism that allows easy injection of a class map of classes that are not services, and therefore are not registered in the container, as a service argument.

```php
namespace App;

class MyService
{
    public function __construct(private array $classMap) {}
}
```

```yaml
App\:
    resource: '../src/'
    exclude:
        - '../src/DependencyInjection/'
        - '../src/Entity/'
        - '../src/NotInDIC/'
        - '../src/Kernel.php'

App\MyService:
    arguments:
        - !class_map
            namespace: App\NotInDIC
            path: '%kernel.project_dir%/src/NotInDIC'
```

```xml
<service id="App\MyService">
    <argument type="class_map"
              namespace="App\NotInDIC"
              path="%kernel.project_dir%/src/NotInDIC" />
</service>
```

```php
$services->set(MyService::class)
    ->args([
        class_map('App\NotInDIC', '%kernel.project_dir%/src/NotInDIC'),
    ])
;
```

```php
public function __construct(
    #[AutowireClassMap('App\NotInDIC', '%kernel.project_dir%/src/NotInDIC')]
    private array $classMap,
) {}
```

```php
class SomePass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $container->register(MyService::class)
            ->addArgument(
                new ClassMapArgument(
                    'App\NotInDIC',
                    '%kernel.project_dir%/src/NotInDIC',
                ),
            )
        ;
    }
}
```

Optionally, the classes can be filtered to include only those that implement or extend a specific interface or class, or have a specific PHP attribute.

```php
namespace App\NotInDIC;

#[SomeAttribute]
class SomeClass implements SomeInterface
{
}
```

```php
public function __construct(
    #[AutowireClassMap(
        namespace: 'App\NotInDIC',
        path: '%kernel.project_dir%/src/NotInDIC',
        instanceOf: SomeInterface::class,
        withAttribute: SomeAttribute::class,
    )]
    private array $classMap,
) {}
```

By default, the class map is a list with numeric incrementing keys, but can optionally be configured to use the value of a static method, property, or constant name as the index key.

```php
class SomeClass
{
    public static $key = 'someKey';
}
```

```php
public function __construct(
    #[AutowireClassMap(
        namespace: 'App\NotInDIC',
        path: '%kernel.project_dir%/src/NotInDIC',
        indexBy: 'key',
    )]
    private array $classMap,
) {}
```

In case there are multiple elements with the same name, the method has the highest precedence, followed by the property, and then the constant. I also thought about having a separate syntax for each, but it seemed unnecessary, e.g.:

```php
#[AutowireClassMap(
    indexBy: 'key()', // method
    indexBy: '$key',  // property
    indexBy: 'key',   // constant
)]
```

Another way to index the class map is with the `#[WithKey]` attribute. This attribute takes precedence over the `indexBy` option.

```php
#[WithKey('someKey')]
class SomeClass
{
}
```

### CODE REVIEW

**Comment by derrabus** [comment]
What do I do with such a class map?

**Comment by alexandre-daubois** [comment]
I agree with Alexander, I'm not sure why you would inject a class not present in the container? Generally, when a class is not present in the container (likely entities, DTOs, VOs, etc.), you want to instantiate it yourself. What if one of the class in the map requires arguments to be instated ?

Maybe you have a very specific use-case in mind. If so, it would be nice (even for the doc team) to add an example where you actually do something with the class-map you declare. Here, in the examples, I can only see snippets where you declare the map but not use it?

The idea looks interesting to me! I just would like to understand the use case behind such feature 🙂

**Comment by HypeMC** [comment]
@derrabus @alexandre-daubois Hi guys, thanks for the feedback. You're right, I did forget to give you a "why." This is a feature I've needed more than a few times over the years, usually for dynamically "connecting" a string or class to another class. Here are two examples:

1. A few years ago, I was working with a JSON:API and [neomerx/json-api](https://github.com/neomerx/json-api). My company was developing a bundle, and one thing we wanted was to easily map schemas to actual objects. At the time, we had to do this manually, so we created a compiler pass to scan certain directories for schema classes and automatically register them to the object defined in a static method:
   ```php
   class PostSchema extends BaseSchema
   {
       public static function getMappedClassname()
       {
           return Post::class;
       }
   }
   ```

2. A recent use case involves dynamically mapping JSON responses to objects using Symfony's serializer. The provider has a live stream endpoint that streams differently structured JSON messages for various events. Even though the serializer has features like the `#[DiscriminatorMap]` attribute, we still need to manually maintain the map. It would be great to automatically build this map.

**Comment by nicolas-grekas** [comment]
This relates to #57536 
As is, I'm not convinced this would be common need enough, nor good practice actually.
Using FQCN as identifiers looks like something that lacks of flexibility - something we know how to solve in the DI component with tags and service ids (that don't have to be FQCN)

**Comment by nicolas-grekas** [comment]
Let me close as explained.

**Pull request closed without merging**
