### PR TITLE
[TwigBundle] Avoid line overflow with long arguments in exception page

### PR DESCRIPTION
**Pull request by nzldvd90**
| Q             | A
| ------------- | ---
| Branch?       | 3.4 or master 
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
For 3.4, that's where all changes (but deprecated code removal) should go.

**Comment by nicolas-grekas** [comment]
Or 3.3 if it's a bug fix btw!

**Comment by fabpot** [comment]
@nzldvd90 Can you paste a before/after screenshot? That would help a lot. Thanks.

**Comment by fabpot** [comment]
Closing as there is no feedback. Feel free to reopen with screenshots.

**Pull request closed without merging**
