### PR TITLE
improve exception message if symfony/security-csrf is missing

### LINKED ISSUE #37452: Confusing error when CSRF protection is not enabled
**Description**  
If your application doesn't have CSRF protection enabled, you'll see this error message when using forms that use CSRF:

https://github.com/symfony/symfony/blob/1b5430bc9f7385a687c02607a3f8e11bcbce66e7/src/Symfony/Component/Form/FormRenderer.php#L62

This error message may be technically precise ... but it's not very useful because it doesn't explain how to solve the problem. The real solution is that you must set the `framework.csrf_protection` config option to `true` or `null`. So, should we update this error message? Or does this error happen in several different circumstances and we can't update it? Thanks!

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #37452
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]

**Comment by wouterj** [comment]
In the issue, @javiereguiluz says "The real solution is that you must set the `framework.csrf_protection` config option to `true` or `null`". This PR changed it to "install `symfony/security-csrf`". Can we confirm that installing will always fix it, or do we need to add the config option to the message?

**Comment by xabbuh** [comment]
The option is enabled by default as soon as the `symfony/security-csrf` package is enabled. So I am not sure if it's worth adding the option too.

**Comment by javiereguiluz** [comment]
I agree with Christian ... installing the missing package is probably enough to solve this issue (I can't test it myself now). Thanks!

**Review by wouterj — APPROVED** [review]
Alrighty, :+1:

**Review by derrabus — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you for the PR and the reviews

**Pull request merged**
