### PR TITLE
[Form] Allow to extend multiple types in a type extension

### PR DESCRIPTION
**Pull request by egeloen**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #9507 |
| License | MIT |
| Doc PR | - |

The use case of this PR is to allow to extend all form types with a single type extension. Since the button type does not extend the form one, there is no root type which can be extended.

As pointed in the referenced ticket, I'm not sure what can be done/happened if a type extension extends two types where the first is a child of the second. The problem can become much more complex if we extend more than 2 types...

For the test part, I don't see where I can put them. Someone can give me the good direction?

### CODE REVIEW

**Comment by czenker** [comment]
@webmozart I personally prefer being able just having one FormTypeExtension and applying it to multiple FormTypes. Having dozens of trivial FormTypeExtensions seems overly verbose to me.


Allowing a form extension to be applied to multiple form types in SF Framework (!) could be added easily right now without any BC break:

I'd say having some configuration like 

    form.extension.common:
        class: CommonExtension
        tags:
            - { name: form.type_extension, alias: form }
            - { name: form.type_extension, alias: button }
            - { name: form.type_extension, alias: reset }
            - { name: form.type_extension, alias: submit }

is way more readable and easier to understand.

To enable this feature only a few lines would need to be changed in FormPass:

    foreach ($container->findTaggedServiceIds('form.type_extension') as $serviceId => $tags) {
      foreach ($tags as $tag) {
        $alias = isset($tag['alias']) ? $tag['alias'] : $serviceId;
        $typeExtensions[$alias][] = $serviceId;
      }
    }

At the moment only the first tag is evaluated.

**Comment by stof** [comment]
@czenker introducing a mismatch between the FormTypeExtensionInterface and the way the lazy extensions are applied is not an acceptable option.

**Comment by Misiur** [comment]
Hey, anybody still working on this?

**Comment by egeloen** [comment]
@Misiur If you want to finish it your welcome!

**Comment by webmozart** [comment]
Thanks for the PR @egeloen! I'm closing this for the reasons explained in #9507.

**Pull request closed without merging**
