### PR TITLE
[Lock] Expose SharedLockInterface from factory

### LINKED ISSUE #44680: [Lock] Update factory contract
### Description

LockFactory returns SharedLocksInterface's 

https://github.com/symfony/symfony/blob/98e0fa4e0d0fe306ab875f06bad97f2c472db4af/src/Symfony/Component/Lock/LockFactory.php#L44-L47

https://github.com/symfony/symfony/blob/98e0fa4e0d0fe306ab875f06bad97f2c472db4af/src/Symfony/Component/Lock/LockFactory.php#L56-L62

https://github.com/symfony/symfony/blob/98e0fa4e0d0fe306ab875f06bad97f2c472db4af/src/Symfony/Component/Lock/Lock.php#L28

Should we update the return types?

Also `acquireRead()` may forward to `acquire()`

https://github.com/symfony/symfony/blob/98e0fa4e0d0fe306ab875f06bad97f2c472db4af/src/Symfony/Component/Lock/Lock.php#L136-L144

which raises questions about this contract in the first place ... :) perhaps an `@method` on `LockInterface` is possible still?

### Example

_No response_

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #44680
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Review by jderusse — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
We need green CI before merging.

**Comment by fancyweb** [comment]
I'm not sure `.github/expected-missing-return-types.diff` was regenerated properly since the additions are at the end but the file is supposed to be organized alphabetically.

**Comment by ro0NL** [comment]
yes, I appended it manually. But CI is green-ish :smiling_imp: 

please let @carsonbot make that commit, or ship a docker based one-liner :) as it was very painful for me ro run those commands on a bare composer/php8.1 container.

**Comment by nicolas-grekas** [comment]
`sudo update-alternatives --set php /usr/bin/php8.1` with ondrej's ppa makes it trivial on Ubuntu, you might want to improve your setup ;)

I fixed the patch.

Thank you @ro0NL

**Comment by ro0NL** [comment]
@nicolas-grekas thx. We are improving our setup yes, that is moving away from global software on the host, to containerized apps ;)

**Pull request merged**
