### PR TITLE
[Process] Dont use getenv(), it returns arrays and can introduce subtle breaks accros PHP versions

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #25511
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by chr-hertel** [comment]
thanks @nicolas-grekas! fixes the issue in our project, just tested it 👍

**Comment by wppd** [comment]
this problem also occurs in 3.4

**Comment by nicolas-grekas** [comment]
@wppd 3.3 will be merged into 3.4 if not already the case, so all upper branches will get the fix before next release.

**Comment by n-sviridenko** [comment]
The fix is not merged yet. Is there any workaround applicable?

**Comment by xabbuh** [comment]
@n-sviridenko In the meantime it seems to have been merged up to `master`.

**Pull request merged**
