### PR TITLE
[Console] Fix console output with closed stdout

### PR DESCRIPTION
**Pull request by jakzal**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15180 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by fabpot** [comment]
Any way we can test this?

**Comment by jakzal** [comment]
To be honest I don't know how to test this other than manually.

**Comment by fabpot** [comment]
Thank you @jakzal.

**Pull request merged**
