### PR TITLE
As suggested add twig file extension

### PR DESCRIPTION
**Pull request by cybernet**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | N/A
| Fixed tickets | #31045 

- Allow twig template files to be uploaded

### CODE REVIEW

**Comment by OskarStark** [comment]
You have a typo in the commit message and PR title

**Comment by cybernet** [comment]
> 
> 
> You have a typo in the commit message and PR title

unfortunately i can't change the commit message :cry:

**Comment by nicolas-grekas** [comment]
I'm not sure this makes sense - `application/twig` doesn't exist, and more importantly, Twig files are templates of any kind of text contents: html, plain text, markdown, etc

**Comment by Simperfit** [comment]
Same for me, I don't see why we should be using "application/twig" as it doesn't exist. I think it can lead to bad practices and maybe could lead to security issues in the app/website IMHO.

**Comment by ro0NL** [comment]
i was curious if it could be submitted "officially" ...  https://www.iana.org/form/media-types

> I'm not sure this makes sense - `application/twig` doesn't exist, and more importantly, Twig files are templates of any kind of text contents: html, plain text, markdown, etc

twig+html is not valid text/html IIUC, i tend to believe twig could expose it's file contents, i.e. `text/twig+html` :man_shrugging:

**Comment by cybernet** [comment]
than, maybe it should be recognised as a MimeType, officially...

**Comment by fabpot** [comment]
Closing as per https://github.com/symfony/symfony/issues/31045#issuecomment-483401249

**Pull request closed without merging**
