### PR TITLE
[OptionsResolver] added test for allowed values and types that default to null

### PR DESCRIPTION
**Pull request by Tobion**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | no |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Added test to keep logic as experienced in #12809

### CODE REVIEW

**Comment by stof** [comment]
The case experienced in #12809 is not specifically about ``null``. It is about the default value being allowed or no (``null`` just happens to be the default value in HWIOAuthBundle).

you will get the same BC break in 2.6 for any not allowed default value because of the bugfix (which was precisely about default values not being validated)

**Comment by Tobion** [comment]
True, then it's even more important not to revert that. The tests I added here show exactly that both invalid values with setDefault() as well as with resolve() throw an exception.

**Comment by stof** [comment]
but this is already tested (with the test using ``42`` as default value, that you edited in your PR

**Comment by Tobion** [comment]
Yes but there has been no test where the invalid value is passed to `resolve`

**Comment by Tobion** [comment]
ping

**Comment by Tobion** [comment]
@stof you ok with the PR?

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @Tobion.

**Pull request merged**
