### PR TITLE
Fix git diff marker

### PR DESCRIPTION
**Pull request by shyim**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | #..
| License       | MIT
| Doc PR        | 

There are some git diff marker :)

### CODE REVIEW

**Comment by xabbuh** [comment]
Good catch. 👍 Can you also remove the accidentally added `setTrustedHeaderName()` and `getTrustedHeaderName()` methods and rebase on the `4.2` branch?

**Comment by shyim** [comment]
Fixed :)

**Review by xabbuh — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @shyim.

**Comment by xabbuh** [comment]
Congratulations for you first contribution @shyim!

**Comment by shyim** [comment]
It should be the second one :thinking: 
https://github.com/symfony/symfony/pull/28820 :sweat_smile: but ty :blush:

**Pull request merged**
