### PR TITLE
Fix currently broken tests

### PR DESCRIPTION
**Pull request by mpdude**
Glitch from 8f723385139f485a5850b05de58d8794cf8f7423

### CODE REVIEW

**Comment by mpdude** [comment]
Maybe I'm wrong here - can one rely on the first argument being the command? 

If so, \Symfony\Component\Console\Tester\CommandTester::execute does not seem to guarantee this.

**Comment by WouterJ** [comment]
I think this is going to be fixed by https://github.com/symfony/symfony/pull/14197 already

**Comment by mpdude** [comment]
Not sure if #14197 does the right thing (tm)?

**Comment by aitboudad** [comment]
@mpdude FYI $input->getArgument('command') return the cmd name and doesn't allow to know if the user uses the alias or name to execute this command

**Comment by mpdude** [comment]
So, trying to fix it by making sure the `CommandTester` adds the command name as first argument.

**Comment by fabpot** [comment]
:+1:

**Comment by mpdude** [comment]
If the first argument has such a special meaning and can (always?) be expected to contain the (unparsed?) command name, maybe that would be worth a doc note somewhere? (DocBlock?)

**Comment by aitboudad** [comment]
now it's ok :+1:

**Comment by mpdude** [comment]
Please merge so folks with open PRs can rebase and get their tests green again :-)

**Comment by xabbuh** [comment]
:+1:

**Comment by mpdude** [comment]
Can anyone see why some of the Travis builds still fail as before?

**Comment by fabpot** [comment]
Thank you @mpdude.

**Pull request closed without merging**
