### PR TITLE
Added new Forwarded header support for Request::getClientIps

### PR DESCRIPTION
**Pull request by tony-co**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #11073 |
| License | MIT |
| Doc PR | no |

### CODE REVIEW

**Comment by fabpot** [comment]
@tony-co Can you add the test case asked by @Seldaek ?

**Comment by tony-co** [comment]
@Seldaek A few weeks ago, Fabien merged a [fix to strip the port](https://github.com/symfony/symfony/pull/13114).
I rebased and updated the tests to include cases with IPv4/IPv6 with ports.

**Comment by Seldaek** [comment]
Looks good to me I think :)

**Comment by fabpot** [comment]
Thank you @tony-co.

**Pull request closed without merging**
