### PR TITLE
[Form] Fix FormDataCollector

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20698
| License       | MIT
| Doc PR        | -

Alternative to #20707

### CODE REVIEW

**Comment by stof** [comment]
Can you add test covering the bug to prevent regressions ?

**Comment by nicolas-grekas** [comment]
No, I can't... This code is a maze...

**Comment by stof** [comment]
Well, you said you add a reproducer. Couldn't it be used as a test ?

**Comment by nicolas-grekas** [comment]
It's a functional test with master + sub request + profiler enabled. ie. a heavy stack...

**Comment by Padam87** [comment]
I can confirm that the patch works.

**Comment by Padam87** [comment]
I've added a failing test, which is fixed by this patch

**Comment by stof** [comment]
👍

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
