### PR TITLE
[Workflow][FrameworkBundle] Allow workflow's guard works without security

### PR DESCRIPTION
**Pull request by tienvx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | N.A.
| License       | MIT
| Doc PR        | symfony/symfony-docs#13565

### CODE REVIEW

**Comment by tienvx** [comment]
I can not add test case for the case symfony/security-core is not installed, because I don't know how to delete the `Symfony\Component\Security\Core\Security` class

**Comment by lyrixx** [comment]
Hello.

Thanks for your contribution, but I failed to see what is your use case. do you want to add `guard` expression, but without using the security? If so, I fail to see what can be in the guard expression.

Then, what will happen if one use `is_granted()` is the expresson when they does not have the security installed?

**Comment by javiereguiluz** [comment]
@lyrixx maybe @tienvx wants some *mechanism* to disable security temporarily for some scenarios? (not for production) Something like using a `NullLogger` to not null anything even if the app believes that it's logging messages.

**Comment by tienvx** [comment]
@lyrixx For example, I want to define a workflow that has a transition:
```
transitions:
    removeFromCart:
        guard: "subject.cartHasProducts()"
```

This workflow is not related to Symfony's Security component at all. And the app does not require any Symfony's Security related component or bundle to run. But since I defined `guard`, Framework Bundle required to install `symfony/security-core` and `symfony/security-bundle` in order to compile this workflow.

This is the reason for me to create this MR

**Comment by lyrixx** [comment]
Then, what will happen if one use is_granted() is the expresson when they does not have the security installed?

**Comment by tienvx** [comment]
Before, there will be an exception:
```
Cannot guard workflows as the Security component is not installed. Try running "composer require symfony/security-core".
```
After, I guess there will be an exception `SyntaxError` from Expression Language component. I am not sure about this case yet, I didn't test it.

There something we can do about it:
* Keep that exception, I think it's even better that the security exception above
* Check all guard expression, if there are some expression required Security component, throw exception to require it

What do you think?

**Comment by tienvx** [comment]
I can confirm that the `SyntaxError` exception throw from ExpressionLanguage component:
```
The function "is_granted" does not exist around position 1 for expression `is_granted("ROLE_ADMIN") and subject.isTrue()`.
```

I added 4 test cases to cover all of these cases too:
* Use `is_granted` with Security Bundle
* Use `is_granted` without Security Bundle
* Not using `is_granted` with Security Bundle
* Not using `is_granted` without Security Bundle

I updated the MR, so that no code is removed. The exception `Cannot guard workflows as the Security component is not installed. Try running "composer require symfony/security-core".` is still there in case guard is used but `symfony/security-core` is not installed

**Comment by tienvx** [comment]
I have a question: do we usually run test cases for each bundle/component alone (clone the repository for that bundle/component and run test cases)? I re-used the class `Symfony\Component\Workflow\Tests\Subject` in Framework Bundle's test cases. If it's not good, I will clone the class instead.

**Comment by lyrixx** [comment]
I don't really like the new current DX... Could we do something better instead ?

**Comment by tienvx** [comment]
I updated the code, change the exception from:
```
The function "is_granted" does not exist around position 1 for expression `is_granted("ROLE_ADMIN") and subject.isTrue()`.
```
to
```
Cannot validate guard expression as the SecurityBundle is not registered in your application. Try running "composer require symfony/security-bundle".
```

**Comment by tienvx** [comment]
I have no idea how to fix the error on Travis:
```
class "Symfony\Component\Workflow\EventListener\NoSecurityGuardListener" does not exist.
```

**Comment by nicolas-grekas** [comment]
The current approach looks fragile to me: having two code paths that are supposed to do the same but adapt to different dependencies is calling for bug. One day or another (maybe today already), one code path will diverge from the other.

If we believe both code paths behave the same, we should instead settle on only one of them - the one that has the best potential. It could be the new one only - I don't know.

But as is, I'm :-1: personnaly.

**Comment by tienvx** [comment]
Okay I will rewrite the code. Can I update this pull request, or I need to close it and open new one?

**Comment by fabpot** [comment]
If the approach is totally different, let's open a new one and close this one to avoid polluting the discussion for the new approach.

**Comment by lyrixx** [comment]
I'm going to close this pull request because the design is not correct. I'm sorry.

IMHO the best ways to solve that:

* parse the expression during the container build (if possible - I did not test it)
* Only check dependencies at runtime

**Comment by tienvx** [comment]
I created new merge request here. Please take a look https://github.com/symfony/symfony/pull/36577

**Pull request closed without merging**
