### PR TITLE
[Serializer] Fix deserialization of object with private constructor

### PR DESCRIPTION
**Pull request by l3l0**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by l3l0** [comment]
Ok I just noticed that 2.7 has in composer "php: >=5.3.9" and this patch will not work on php 5.3.
Should I open PR for master then? Maybe I should to find a way to make it work on php 5.3 as well...

**Comment by nicolas-grekas** [comment]
It could be seen as a new feature, and be submitted on master yes.

**Comment by xabbuh** [comment]
To me this is a new feature. So :+1: for doing this on master.

**Comment by Ener-Getick** [comment]
This looks risky to me.
Wouldn't it be safer to allow to define a custom factory for each object ?

**Comment by l3l0** [comment]
@Ener-Getick Can you elaborate?

**Comment by Ener-Getick** [comment]
@l3l0 the object's constructor may be necessary and a static method is often here to instantiate the object, so instead we could introduce a new annotation/metadata to choose which method to use to instantiate the object:
```php
class Foo
{
    private __constructor() {
        // some instantiation
    }

    /**
     * @Constructor
     */
    public static function create()
    {
        return new self();
    }
}
```

**Comment by l3l0** [comment]
@Ener-Getick right but arguments pass to constructor do not have to reflect internal state of the object - we can pass VO and convert them to basic types in constructor. IMHO at last for PropertyNormalizer constructor should not be called. For now I will create new PR to master we can discuss later that new PR

**Pull request closed without merging**
