### PR TITLE
[Workflow] Added generic template in Event and his inheritors

### PR DESCRIPTION
**Pull request by fractalzombie**
Added generic template for `Event` in Workflow Component

| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

Added generic template for `Event`, `Event::$subject` and `Event::getSubject()` for PHPStorm support.

### CODE REVIEW

**Comment by fractalzombie** [comment]
It's already reviewed, something strange was broken my fork. https://github.com/symfony/symfony/pull/44622

**Comment by derrabus** [comment]
To get rid of the error on the `GuardEvent`, you need to add the `@param` annotation to its constructor.

```php
        /**
         * {@inheritdoc}
         *
         * @param TSubject $subject
         */
        public function __construct(object $subject, Marking $marking, Transition $transition = null, WorkflowInterface $workflow = null, array $context = [])
```

**Comment by fractalzombie** [comment]
> To get rid of the error on the `GuardEvent`, you need to add the `@param` annotation to its constructor.
> 
> ```
>         /**
>          * {@inheritdoc}
>          *
>          * @param TSubject $subject
>          */
>         public function __construct(object $subject, Marking $marking, Transition $transition = null, WorkflowInterface $workflow = null, array $context = [])
> ```

Thanks, resolved!

**Review by derrabus — APPROVED** [review]

**Review by nicolas-grekas — CHANGES_REQUESTED** [review]
The failure is legit.
Please don't forget to patch the `.github/expected-missing-return-types.diff` file as done eg in #44695 (see the file for how)
Note that since DebugClassLoader is not able to understand the `@template` annotations (yet), I added a hack in 1dad23b9d1e56cface704b30cd27fe287c6648fe
We're going to need something similar here (or to patch DebugClassLoader before merging.)

**Comment by fractalzombie** [comment]
> The failure is legit.
> Please don't forget to patch the `.github/expected-missing-return-types.diff` file as done eg in #44695 (see the file for how)
> Note that since DebugClassLoader is not able to understand the `@template` annotations (yet), I added a hack in [1dad23b](https://github.com/symfony/symfony/commit/1dad23b9d1e56cface704b30cd27fe287c6648fe)
> We're going to need something similar here (or to patch DebugClassLoader before merging.)

Good idea, i will check how i can do it in this case.

**Comment by fractalzombie** [comment]
> The failure is legit.
> 
> Please don't forget to patch the `.github/expected-missing-return-types.diff` file as done eg in #44695 (see the file for how)
> 
> Note that since DebugClassLoader is not able to understand the `@template` annotations (yet), I added a hack in 1dad23b9d1e56cface704b30cd27fe287c6648fe
> 
> We're going to need something similar here (or to patch DebugClassLoader before merging.)

Can't find solution for your suggestion. I close PR.

**Pull request closed without merging**
