### PR TITLE
[Validator] Add german translation for Range validator

### PR DESCRIPTION
**Pull request by PReimers**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

German translation for #32435

### CODE REVIEW

**Comment by Lctrs** [comment]
Should target `3.4`.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @PReimers.

**Comment by PReimers** [comment]
@Lctrs, @fabpot the related PR #32435 is targeting 4.4.

Why should this translation target 3.4?

**Comment by fabpot** [comment]
@PReimers We merge all translations back in 3.4 to ease maintenance on our side.

**Comment by PReimers** [comment]
@fabpot Thanks for the explanation. Didn't know this. 👍

**Pull request merged**
