### PR TITLE
Use short array syntax

### PR DESCRIPTION
**Pull request by ostrolucky**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Symfony is one of last projects using traditional array syntax. After dropping support for 2.8, this is best opportunity to switch to short syntax usage. If we do it later, there would be even more places where it will be needed to change and even more conflicts.

This patch is not just running php-cs-fixer. This is a subset of hunk changes which are conflict free!

Great care was taken to:
- Make this commit **mergeable  to master, 4.1 and 4.2 without conflicts** (removed changes which cause conflicts)
- Make sure there are no syntax errors (php lint)
- Make sure phpunit passes (manually skipped dumped fixtures)

### CODE REVIEW

**Comment by ostrolucky** [comment]
I will rebase it after approval, before merge, since it's prone to conflicts when you merge some branches meanwhile.

**Comment by fancyweb** [comment]
If this is accepted, the https://symfony.com/doc/current/contributing/code/standards.html page must reflect our new policy.

**Comment by ostrolucky** [comment]
Sure, but not immediately. Similar work in upper branches need to be done before rule can be replaced, which I volunteer to do as well. This PR is first step.

**Comment by gmponos** [comment]
@ostrolucky recently I discovered this https://github.com/symfony/phpunit-bridge/blob/master/composer.json#L19

so I guess you must have a look to all components about the version they support.

**Comment by ostrolucky** [comment]
yeah that's a good point. We can exclude this for phpunit bridge

**Comment by nicolas-grekas** [comment]
PHP 5.3 support was required to test Symfony 2.8.
I think we can bump the bridge to 5.5 in Symfony 4.3.

**Comment by nicolas-grekas** [comment]
I'm :+1: for the change, but this will make almost all pending PRs conflict (see how many its already has).
I think the only way to do it is to have a merger do it using php-cs-fixer:
- first merge all branches up to master
- then run php-cs-fixer on 3.4
- merge 3.4 into 4.1 and revert all changes while doing so
- run php-cs-fixer on 4.1
- etc up to master

To save us some hassle, I'd wait for 4.1 to be EOLed personally before doing so.

Meanwhile, what about enabling the short array syntax in fabbot right now, to help rebased/new PRs be ready? @fabpot wdyt?

**Comment by ostrolucky** [comment]
You can do it that way for all php-cs-fixer rules, or at least those affecting single line only. I thought it's not being done that way for some reason?

Also, it's not so simple, as you need to take special care for things like fixtures of dumped containers.

> see how many its already has

Yes, I though this will be merged quicker. You can't let PR like this sit around for 20 days. It was 0 conflicts in beginning all the way up to master.

**Comment by ostrolucky** [comment]
Superseded by https://github.com/symfony/symfony/pull/29903

**Pull request closed without merging**
