### PR TITLE
[Validator] Fix typos in EL translation

### PR DESCRIPTION
**Pull request by simplegr**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| License       | MIT

Fixing some typos

### CODE REVIEW

**Comment by derrabus** [comment]
> Bug fixes must be submitted against the lowest maintained branch where they apply (see https://symfony.com/releases)

Can you please rebase your PR onto the 4.4 branch?

**Comment by simplegr** [comment]
> > Bug fixes must be submitted against the lowest maintained branch where they apply (see https://symfony.com/releases)
> 
> Can you please rebase your PR onto the 4.4 branch?

Sorry my mistake. I did a PR for 4.4 branch. Should I delete this one?

**Comment by Nyholm** [comment]
There is no need to close this PR. You can just edit the PR target branch and do a rebase if needed.

**Comment by derrabus** [comment]
Oh, I didn't see that there is already #41712. We can close this one, yes.

**Pull request closed without merging**
