### PR TITLE
[HtmlSanitizer] Add support for sanitizing unlimited length of HTML document

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       |
| License       | MIT

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
What about `withMaxInputLength(PHP_INT_MAX)`? Isn't this risky practice?

**Comment by lyrixx** [comment]
> What about `withMaxInputLength(PHP_INT_MAX)`? Isn't this risky practice?

I did that in my app (still on 6.3 😅) But If feels more natural to disable the feature completely if you don't want it.

**Review by tgalopin — APPROVED** [review]
Given that there is a default at 20 000, I think anyone choosing to change it probably had a a look at why it exists and therefore understands at least a bit the consequences. I'm fine disabling it completely IMO

**Comment by stof** [comment]
@tgalopin there is no phpdoc at all in `HtmlSanitizerConfig` that would explain the reason to have a limit though.

**Comment by nicolas-grekas** [comment]
Thank you @lyrixx.

**Pull request merged**
