### PR TITLE
[RateLimiter] add Limit::ensureAccepted() which throws RateLimitExceededException if not accepted

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Ref https://github.com/symfony/symfony/issues/38241#issuecomment-695212027
| License       | MIT
| Doc PR        | todo

Example:

```php
try {
    $limit = $limiter->consume()->ensureAccepted();
} catch (RateLimitExceededException $e) {
    $limit = $e->getLimit();
}
```

### CODE REVIEW

**Comment by wouterj** [comment]
I've been thinking about this one a bit during the past weeks (this is one of 2 major design choices in the RateLimiter component that doesn't yet feel completely grounded at the perfect solution).

I think there are 2 different use-cases for a generic rate limiter that is provided by the component:
A) Check the rate with the intention to *drop* the overflowing requests
B) Check the rate with the intention to *wait* till the request can be processed

I would say that this exception is very useful in cases like (A), but a bit difficult in cases like (B).

The `TokenBucketLimiter` already has these 2 cases in its interface - as it can reserve tokens in the future: `consume()` for (A) and `reserve()` for (B). Maybe we should reintroduce `reserve()` in the `LimiterInterface` and somehow create such reservation feature for the window algorithms (although we can't guarantee that they have a valid hit at the `retryAt` date).

**Comment by kbond** [comment]
@wouterj and I discussed this PR in slack and came to the conclusion that adding `Limit::ensureAccepted()` which throws a `RateLimitExceededException` (if not accepted) is the preferred and simplest solution.

**Review by wouterj — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @kbond.

**Pull request merged**
