### PR TITLE
[PhpUnitBridge] Fixed fatal error in CoverageListener when something goes wrong in Test::setUpBeforeClass

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by lyrixx** [comment]
Hmm, I tried to add a test but it's not really possible.

**Comment by xabbuh** [comment]
When can it happen that this method does not exist?

**Comment by lyrixx** [comment]
Ah yes I removed the test. but it is still in the PR title and commit message ;)
Tried to throw an exception in the `setUpBeforeClass` and you will see.
(Note I did not dig in PHPUnit to find the root cause. I'm not sure I want to :D )

**Comment by xabbuh** [comment]
Could it be related to `$test` being an instance of `TestSuite` but not `TestCase`?

**Comment by lyrixx** [comment]
I don't know. What do you have in mind ?

**Comment by xabbuh** [comment]
We could then use `instanceof` instead.

**Comment by lyrixx** [comment]
I was pretty sure you are going to say that.
using instanceof will be a bit boring because we manage many PHPUnit version (pear convention vs namespace :/)

**Comment by xabbuh** [comment]
There is an alias for the namespaced class in PHPUnit 4.8 and 5.x. :)

**Comment by lyrixx** [comment]
@xabbuh  It should be ok

**Review by xabbuh — APPROVED** [review]

**Review by Simperfit — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
