### PR TITLE
Psr16Adapter fails to cache any item if a namespace is used

### PR DESCRIPTION
**Pull request by moufmouf**
| Q             | A
| ------------- | ---
| Branch?       |3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

The Psr16Adapter extends AdapterTestCase.
When adding a namespace, the AdapterTestCase adds ":" after the namespace:

https://github.com/symfony/symfony/blob/v4.3.1/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php#L37

The namespace is prepended to the cache key.
But in PSR-16, the ":" is a forbidden character.

As a result, the cache key is invalid and cache is not persisted. If you use Psr16Adapter + a namespace, the cache simply does not work.

The first commit of this PR starts with an additional test and no fix (to showcase the problem).

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Wow, thanks for spotting. The bug exists on 3.4, in `SimpleCacheAdapter`.
The fix is wrong: the currently attached patch changes `AbstractAdapter` which is used by all adapters.
Only `Psr16Adapter`/`SimpleCacheAdapter` is affected, so that's where the fix should go.
It also doesn't work when versioning is enabled since versioning adds another `:`.
Instead, we could maybe make the `:` an `@internal` `NS_SEPARATOR` const (because PHP5.5 on 3.4 doesn't allow protected consts) that we reference in AbstractAdapter using `static::NS_SEPARATOR`?

**Comment by stof** [comment]
Why would we need to use different separators per implementation, rather than using a separator accepted by all ?

**Comment by nicolas-grekas** [comment]
Two reasons, on a very different scale:
- changing the separator means invalidating all existing caches, better not when it's not needed
- using a separator that is forbidden makes it 100% sure that no collision is possible, that's desired.

**Comment by moufmouf** [comment]
Ok, opened a new PR #32025  that targets Symfony 3.4.

Shall I close this one or continue working on it too?

**Comment by nicolas-grekas** [comment]
Nope, no need, thanks.

**Pull request closed without merging**
