### PR TITLE
[DoctrineBridge] add missing deprecation in MergeDoctrineCollectionListener

### PR DESCRIPTION
**Pull request by HeahDude**
| Q | A |
| --- | --- |
| Branch | 2.3+ |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by HeahDude** [comment]
Don't know if it is need now, but it seems to have been forgotten.

If so, it will need a patch for 3.0 to remove the deprecation.

**Comment by HeahDude** [comment]
Maybe related to #17154. Ping @webmozart

**Comment by HeahDude** [comment]
Of courses not because the right method is still called...

**Comment by xabbuh** [comment]
If we wanted to make this change, we should imo do that in 3.1.

**Comment by webmozart** [comment]
@xabbuh :+1:

**Comment by HeahDude** [comment]
So if I rebase on master I don't have to close this one, right ? Or do you want me to send another PR ?

**Comment by HeahDude** [comment]
see #18069.

**Pull request closed without merging**
