### PR TITLE
[WebProfilerBundle] Make the IP address in the profiler header clickable

### PR DESCRIPTION
**Pull request by jameshalsall**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by fabpot** [comment]
I know that we already had some discussion about this topic. ping @javiereguiluz

**Comment by xabbuh** [comment]
What is the actual use case for this change?

**Comment by jameshalsall** [comment]
This is to make it easier to jump to results for the current IP, which brings it inline with the behaviour of clicking on the URL.

**Comment by xabbuh** [comment]
Let's answer two questions: How common is it that you have profiles with different IP addresses which would justify a need for this feature? And would it be confusing for all other users that the IP address is clickable?

**Comment by jameshalsall** [comment]
1. Quite, if you're viewing the debug profiler in a non-local environment which a lot of people seem to do
2. I'm not sure it would be confusing given that it's styled exactly the same as the URL in the same part of the profiler.

**Comment by javiereguiluz** [comment]
👍 I like this proposal because it changes nothing for most users and it improves the productivity of those using this.

@jameshalsall I'd like to have a minor change before merge: let's make the new link look like the previous text. In line 494 of profiler.css.twig, please update the selector to this:

```css
#summary dl.metadata,
#summary dl.metadata a {    /*  <-- add this line  */
    margin: 5px 0 0;
    color: rgba(255, 255, 255, 0.75);
}
```

**Comment by jameshalsall** [comment]
This has now been updated.

**Review by nicolas-grekas — APPROVED** [review]
:+1:

**Comment by fabpot** [comment]
Thank you @jameshalsall.

**Pull request merged**
