### PR TITLE
[Console] Fixed fatal error when the command is not defined

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/18140/files#r107871406
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by fabpot** [comment]
@lyrixx Can you add a tests to avoid regressions?

**Comment by wouterj** [comment]
I think we should also trigger this event when CommandNotFound exceptions are thrown. What about allowing `null` for the `command` in `ConsoleErrorEvent`?

**Comment by chalasr** [comment]
+1 for having the event fired on command not found. As there is currently no working case where the command is null I think it's safe to make it nullable in this specific event.

**Comment by fabpot** [comment]
Thank you @lyrixx.

**Pull request merged**
