### PR TITLE
[travis] session.gc_probability=0 to fix transient tests on hhvm

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15617 |
| License | MIT |
| Doc PR | - |

Should fix tests failing with:
`ps_files_cleanup_dir: opendir(/var/lib/hhvm/sessions) failed: Permission denied (13)`

### CODE REVIEW

**Comment by Tobion** [comment]
So saving and fetching session files works on HHVM, but GC doesn't? Or why does GC fail?

**Comment by nicolas-grekas** [comment]
I really don't know... Yet, builds fail transiently with this error...

**Comment by Tobion** [comment]
Could be https://www.leaseweb.com/labs/2012/08/ps_files_cleanup_dir-permission-denied/ or https://github.com/facebook/hhvm/issues/6302

Anyway, it doesn't hurt to set gc probability to 0 for tests. So :+1:

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
