### PR TITLE
[Ldap] [Doc] Update README.md

### PR DESCRIPTION
**Pull request by csarrazi**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | yes (doc fix) |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18387 |
| License | MIT |
| Doc PR |  |

Fixes a typo from #18387

### CODE REVIEW

**Comment by xabbuh** [comment]
I think we should better remove the link for the moment as the documentation isn't available yet.

**Comment by csarrazi** [comment]
Well, the doc PR is in progress, as mentioned [here](https://github.com/symfony/symfony-docs/pull/6402)

**Comment by javiereguiluz** [comment]
@xabbuh the first version of the doc will be available very soon, so I think we could merge this fix.

**Comment by fabpot** [comment]
Thank you @csarrazi.

**Pull request merged**
