### PR TITLE
[DependencyInjection] replace alias in factories

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17864 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
Tests are failing.

**Comment by xabbuh** [comment]
Tests have been fixed by #17859.

Status: Needs Review

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by nicokaag** [comment]
@fabpot Branch 2.8 requires this fix as well. (Also see #17910 )

**Pull request merged**
