### PR TITLE
Fixed form data collector

### PR DESCRIPTION
**Pull request by Padam87**
| Q             | A
| ------------- | ---
| Branch?       |  3.2
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #20698
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by Tobion** [comment]
Would be nice to provide a test case.

**Comment by Padam87** [comment]
After spending some time trying to write tests, I'm more baffled than before :) This should work, and the tests I wrote confirm that. Both mocked and real tests passed.

Yet on a real, actual form, the children properties are not getting replaced, almost like if the references weren't working.

The only remaining clue I have is the form being created via a **subrequest**. If it is created in the main request, everything is okay.

**Comment by nicolas-grekas** [comment]
I checked out the patch and have a reproducer so I'm going to try to understand a bit better how this fails now :)

**Comment by Padam87** [comment]
Closing in favor of  #20762

**Pull request closed without merging**
