### PR TITLE
[Validator] Use the new interface in the README

### PR DESCRIPTION
**Pull request by GuilhemN**
| Q | A |
| --- | --- |
| Fixed tickets | #17064 |
| License | MIT |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by jakzal** [comment]
:+1: status: reviewed

**Comment by Ener-Getick** [comment]
Needs to be on a new line @jakzal ;-)
Status: Reviewed

**Comment by Tobion** [comment]
Thank you @Ener-Getick.

**Pull request merged**
