### PR TITLE
[Workflow] mark ClassInstanceSupportStrategy as internal

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | none

We are marking ClassInstanceSupportStrategy as internal since we want to introduce a new interface for the workflow component in 4.1 see #24751

### CODE REVIEW

**Comment by xabbuh** [comment]
I don't think that this makes sense. If we mark it as internal, the class is not meant to be used by others. But people will have to use it if they wire their workflow setup manually.

**Comment by Simperfit** [comment]
I guess we will mark it as internal for 3.4 to 4.1, when we will change it in 4.1 we will remove the `@internal`. That's what I was thinking

**Comment by nicolas-grekas** [comment]
That'd be cheating with the bc promise, not helping devs :) Why not do a proper bc layer in #24751?

**Comment by Simperfit** [comment]
@nicolas-grekas So we need to deprecate this class to and to create a new one if I understand correctly ?

**Pull request closed without merging**
