### PR TITLE
[Serializer] add a local cache to CacheClassMetadataFactory

### PR DESCRIPTION
**Pull request by bendavies**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | #28272
| License       | MIT
| Doc PR        | 

ping @dunglas 

This PR improves the performance of the Serializer in certain benchmarks,
https://www.goetas.com/blog/whats-new-in-jmsserializer-v20/ (https://github.com/goetas/ivory-serializer-benchmark) to be specific.

FYI, https://github.com/egeloen/ivory-serializer-benchmark/pull/11 was also applied to obtain the results below.

Before PR:
```
bin/benchmark --vertical-complexity 60  --horizontal-complexity 60  --iteration 3
Ivory\Tests\Serializer\Benchmark\IvoryBenchmark | 0.89570792516073
Ivory\Tests\Serializer\Benchmark\SymfonyObjectNormalizerBenchmark | 3.3825397491455
Ivory\Tests\Serializer\Benchmark\SymfonyGetSetNormalizerBenchmark | 0.879989306132
Ivory\Tests\Serializer\Benchmark\JmsBenchmark | 0.68816534678141
Ivory\Tests\Serializer\Benchmark\JmsMinimalBenchmark | 0.49477465947469
```

After PR:
```
bin/benchmark --vertical-complexity 60  --horizontal-complexity 60  --iteration 3
Ivory\Tests\Serializer\Benchmark\IvoryBenchmark | 0.90302999814351
Ivory\Tests\Serializer\Benchmark\SymfonyObjectNormalizerBenchmark | 0.92719697952271
Ivory\Tests\Serializer\Benchmark\SymfonyGetSetNormalizerBenchmark | 0.42902104059855
Ivory\Tests\Serializer\Benchmark\JmsBenchmark | 0.66095995903015
Ivory\Tests\Serializer\Benchmark\JmsMinimalBenchmark | 0.48206241925557
```

The improvement of the Symfony Object and GetSet normalizer benchmarks is significant. 

Testing the change was a bit annoying, as you can see. Any better ideas?

### CODE REVIEW

**Comment by bendavies** [comment]
Can anyone see why 5.5 fails?

**Comment by ostrolucky** [comment]
Seems bad idea to decorate psr caches with local caches. Memory leaks, lost control over caches in user space.

**Review by dunglas — APPROVED** [review]

**Comment by bendavies** [comment]
reverted test change

**Comment by goetas** [comment]
Can this implement the kernels resettable interface to avoid memory leaks?

**Comment by bendavies** [comment]
@nicolas-grekas 
> Then I did a composer update, checking out the latest master
head of 3.4 or 4.x?

**Comment by nicolas-grekas** [comment]
Master

**Comment by bendavies** [comment]
thanks, have reproduced that performance decrease between 3.4 and master.

**Comment by goetas** [comment]
So which commit caused the speed slowdown?

**Comment by bendavies** [comment]
Haven't looked yet as I've been on vacation!

**Comment by fabpot** [comment]
@bendavies What's the status of this PR?

**Comment by bendavies** [comment]
@fabian performance decrease in symfony 4 needs investigating. i haven't had time yet, but plan to.

**Comment by fabpot** [comment]
ok, thanks for the heads-up.

**Comment by nicolas-grekas** [comment]
@sroze @dunglas to the rescue maybe?

**Comment by bendavies** [comment]
`Symfony\Component\Serializer\MappingClassDiscriminatorFromClassMetadata` (added in symfony4) is not cached, but calls to `Symfony\Component\Serializer\Mapping\Factory\CacheClassMetadataFactory::getMetadataFor` which is cached, but results in many cache lookups, which are slow.

https://blackfire.io/profiles/compare/890441d8-bfb6-430b-a56f-a96fe137cd9f/graph

So the local cache in this PR fixes the issue, reducing the cache lookups.

Optimally, we could:

1. add a caching (CacheItemPoolInterface + local) `ClassDiscriminatorResolverInterface`, decorating `MappingClassDiscriminatorFromClassMetadata`?
2. add local caches to `CacheClassMetadataFactory` (this PR)

**Comment by dunglas** [comment]
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L114 looks faulty too. This method is called for every attributes, but could be called only one time per object. WYT @sroze.

**Comment by bendavies** [comment]
@dunglas good spot

**Comment by bendavies** [comment]
@nicolas-grekas  @dunglas feedback on my last comment?
I'll fix the issue dunglas found.

**Comment by nicolas-grekas** [comment]
I'd be happy to have a new bench once the patch is applied to see if the perf issue remains after :)

**Comment by fbourigault** [comment]
I did some profiling. All where run using the following command: `blackfire run bin/benchmark --iteration 10 --horizontal-complexity 4 --vertical-complexity 4`.

First I did a profile to see which of arrayAdapter or apcuAdapter is the best:
https://blackfire.io/profiles/compare/6f937d24-47a9-4a47-912c-1541149beb83/graph
It looks like that arrayAdapter is worse. That's why further profiling are done using the apcuAdapter.

Symfony 3.4 vs this PR:
https://blackfire.io/profiles/compare/b24b6c9b-3652-4e59-9463-2ab035fc1c5a/graph
As we can see, this PR does not help at all to increase serializer speed.

master vs this PR rebased:
https://blackfire.io/profiles/compare/e9a70e1f-3594-45fd-9a4c-62919df8a85a/graph
This help a lot, but mostly on the path of `getAttributeValue` which can be improved according to https://github.com/symfony/symfony/pull/28457#issuecomment-428541041.

IMHO, we should work on reducing the `ClassMetadataFactoryInterface::getMetadataFor` calls to get better perfs.

**Comment by nicolas-grekas** [comment]
I closed by mistake, but was going to ask if #28889 does solve this now?
I'll reopen if not, please advise :)

**Comment by bendavies** [comment]
indeed #28889 fixes the root cause.

**Pull request closed without merging**
