### PR TITLE
[FrameworkBundle] Secrets import env file

### PR DESCRIPTION
**Pull request by raphael-geffroy**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Issues        | no
| License       | MIT

This PR aims to allow importing all secrets present in an env file into the vault.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Isn't what secrets:import-from-local does already?

**Comment by raphael-geffroy** [comment]
I didn't manage to make the import-from-local command work, maybe I didn't understand how to use it properly and my PR is pointless.

**Comment by raphael-geffroy** [comment]
It iterates through the vault but my vault is empty it's the one I want to fill.
image

**Comment by raphael-geffroy** [comment]
Plus : I wanted to pass the file as a param so I could import the .env.local and not all the .env (which is frequently versioned and not secret).

**Comment by nicolas-grekas** [comment]
I'd be fine adding the file as an argument to import-from-local. But please try to understand the command first, it doesn't make sense to add another command when we already have one that does the job (and could be improved possibly of course)

**Comment by nicolas-grekas** [comment]
Let me close for now. Keep us posted of course.

**Pull request closed without merging**
