### PR TITLE
[DependencyInjection] fixed PhpDumper + as_files + new lines in string arguments/properties/etc of Definitions

### LINKED ISSUE #24470: [DI] 3.4 Service definitions with line breaks in arguments/properties dumped incorrectly when as_files option used
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.x

Assume we have a service with multi-line string used as value for property:

```yaml
    some_service_id:
        class: stdClass
        properties:
            test1: 1
            test2: >
                Text (
                    Inner Text
                )
            test3: 321
```

This is how this definition dumped to php code when `PhpDumper` used with `as_files` option (default):

```php
<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'some_service_id' shared service.

$this->services['some_service_id'] = $instance = new \stdClass();

$instance->test1 = 1;
$instance->test2 = 'Text (
r Text


$instance->test3 = 321;

return $instance;
```

This file contains incorrect `test2` property, and incorrect syntax.

### PR DESCRIPTION
**Pull request by Strate**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #24470
| License       | MIT
| Doc PR        | no

Handle the case, when exporting string contains new line, which cause
incorrect php code together with `as_files` option

fixes #24470

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
If I remove your change in PhpDumper, I get this change in the fixtures file:
```diff
-return $this->services['foo'] = new \Foo('string with' . "\n" . 'new line');
+return $this->services['foo'] = new \Foo('string with
+');
```

The code without you change is thus perfectly fine.
This means the bug description (generating invalid PHP code?) is not proved yet.
We'd need a test case that actually generates invalid code, then a fix for it.
Possible? Otherwise, this means this fixes nothing in fact...

**Comment by nicolas-grekas** [comment]
OH got it :) "new line" is missing when the patch is not applied!
This bug exists in 2.7 I thing also, and not specific to as_files (see "explode" in "wrapServiceConditionals").

**Comment by Strate** [comment]
@nicolas-grekas yes. Generated code become invalid if test case changed from `"string with\nnew line"`
to `"string with\nnl"` - if length of after-\n part is less than 8, then generated code is invalid. I can add test case for that too.

**Comment by nicolas-grekas** [comment]
Can you submit the fix on 2.7?

**Comment by Strate** [comment]
@nicolas-grekas I've made separate PR#24532
Unfortunatelly no tests, becasuse I don't know which case should be tested.

**Comment by xabbuh** [comment]
Isn't this fixed by #24532?

**Comment by Strate** [comment]
@xabbuh this was created firstly, and this targets to 3.4

**Comment by xabbuh** [comment]
Lower branches are merged up regularly. So the other fix will land in 3.4 eventually.

**Comment by Strate** [comment]
But here is more unit test, target to as_files dumper option

**Comment by chalasr** [comment]
The test added on 2.7 seems enough seems good enough, the value of `as_files` does not matter regarding the fixed bug in fact. This has been merged up to master by Nicolas already.
Closing this one.

**Pull request closed without merging**
