### PR TITLE
[HttpKernel] MapQueryString/MapRequestPayload skips validation when empty request is sent

### LINKED ISSUE #54617: MapQueryString/MapRequestPayload skips validation when empty request is sent.
### Symfony version(s) affected

6.4.6

### Description

It seems to be impossible to validate request properly when sent empty. For both query string and request payload mapper will return `null` and skip validation. Using default value makes callable being called with object which may be invalid.

### How to reproduce

```php
final class ApiDTO
{
    #[Assert\NotBlank]
    public string $foo = '';
}
```

```php
class FooController extends AbstractController
{
    #[Route("/foo", methods: ["GET"])]
    public function __invoke(#[MapQueryString(validationFailedStatusCode: 400)] ApiDTO $dto = new ApiDTO()): JsonResponse {
        dd($dto);
    }
}
```

```
expected behavior
GET /foo?foo= -> 400

validation skipped
GET /foo -> ApiDTO {
    +foo: ""
}
```

### Possible Solution

Possible solution would be to make mapper method return default value if defined instead of returning `null`

```php
// symfony/http-kernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php:162
private function mapQueryString(Request $request, string $type, MapQueryString $attribute): ?object
{
    if (!$data = $request->query->all()) {
        return $attribute->metadata->hasDefaultValue() ? $attribute->metadata->getDefaultValue() : null;
    }

    return $this->serializer->denormalize($data, $type, null, $attribute->serializationContext + self::CONTEXT_DENORMALIZE);
}

// symfony/http-kernel/Controller/ArgumentResolver/RequestPayloadValueResolver.php:185
if ('' === $data = $request->getContent()) {
    return $attribute->metadata->hasDefaultValue() ? $attribute->metadata->getDefaultValue() : null;
}
```

```
GET /foo?foo= -> 400
GET /foo -> 400
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by unixslayer**
| Q             | A
| ------------- | ---
| Branch?       | 7.2 
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54617  
| License       | MIT

### CODE REVIEW

**Comment by unixslayer** [comment]
the same fix was introduced for 6.4 in #57206

**Comment by derrabus** [comment]
Closing as duplicate of #57206.

**Comment by unixslayer** [comment]
@derrabus any chance for #57206 to be reviewed?

**Comment by derrabus** [comment]
I left a comment on the bug report.

**Pull request closed without merging**
