### PR TITLE
[WIP] Fix #18188

### LINKED ISSUE #18188: [DI] Autowiring causes a fatal error for optional services
I use Symfony components and bundles without forms. Autowiring causes the fatal error for [``twig.form.engine``](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml#L124) service from TwigBundle:

```PHP Fatal error:  Class 'Symfony\Component\Form\AbstractRendererEngine' not found in ...```

We should replace [``ReflectionClass``](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L265) with [phpdocumentor/reflection](https://packagist.org/packages/phpdocumentor/reflection) or another library for static reflection.

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18188 |
| License | MIT |
| Doc PR | n/a |

I try to add a test (and a fix) for #18188 but I'm not able to reproduce the problem.
@hason can you explain or add a commit on my PR how to reproduce?

### CODE REVIEW

**Comment by hason** [comment]
@dunglas I prepared a test https://github.com/hason/symfony/commit/5f9e1779960c1037f80340143e75af68e41a8521

**Comment by Ener-Getick** [comment]
I got it, the parent of the class can't be loaded so php throws a fatal error (not a ``\ReflectionException``).
This seems to be an issue hard to fix... and maybe should be fixed in twig bundle instead.

**Comment by nicolas-grekas** [comment]
Should be implemented using similar logic than in ReflectionCaster:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Caster/ReflectionCaster.php#L218-L234

**Comment by nicolas-grekas** [comment]
Closing in favor of #18600

**Pull request closed without merging**
