### PR TITLE
Update DefaultChoiceListFactory.php

### PR DESCRIPTION
**Pull request by fantoine**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |

With Symfony 2.6 I had some choice types with `choices` defined to something similar to

```
'choices' => [
   1 => <an object>,
   2 => <an other object>,
   ...
]
```

But when upgrading to Symfony 2.7 I got an "Illegal offset" error on the DefaultChoiceListFactory because it tries to use the value as an array key, while it should make sure to convert it to string.

This fix removes the BC change in my use cases.

### CODE REVIEW

**Comment by webmozart** [comment]
Hi @fantoine, thank you for submitting that PR! Could you please add a test so that we don't break this functionality again?

**Comment by fantoine** [comment]
Well, it seems this PR is not fully workable.

It works in my use cases because my objects have a __toString method, while on current tests, objects are stdClass which are not castable to string.

Is there any convention in Symfony to handle this kind of problem?
 - Should I create specific tests for objects which can be converted to strings?
 - Should I test if the value can be converted to a string before casting it?
 - ...?

**Comment by fantoine** [comment]
I found an other workaround to solve my issue by explicitly specifying the label and value in the object and in the ChoiceType configuration : 
```
'choices'           => [
   1 => <an object>,
   2 => <an other object>,
   ...
],
'choices_as_values' => true,
'choice_label'      => 'getLabel',
'choice_value'      => 'getId',
```

Without specifying `choice_value` it doesn't work, since the list factory doesn't use the `choices` array keys.

So, is my pull request still interesting?

**Comment by stof** [comment]
@fantoine if ``choices_as_values`` is set to false (which is the default for BC reasons), the values in the ``choices`` array are labels (i.e. behavior in Symfony 2.6 and older).

Were you doing something special in Symfony 2.6 to handle such choices ?

**Comment by fantoine** [comment]
These choices are used for static models which contains an id, a label and other specific informations.

In Symfony 2.6 I used a model transformer to swap between id and static object. The label was implicit thanks to __toString method and the value was the array keys.

I forgot to mention on my previous message that I also had to remove the model transformer which becomes useless.

Maybe it was a wrong way to specify such choices...?

**Comment by stof** [comment]
Well, at least, it was not a supported way, which is why you have to change a bit your configuration for it to work.

However, I think that the casting should indeed be applied as castable objects where indeed valid labels in 2.6

**Comment by stof** [comment]
a test ensuring that castable objects keep working would be a good idea though

**Comment by fantoine** [comment]
OK, I'll work on it.

**Comment by fabpot** [comment]
@fantoine Do you have time to finish this one?

**Comment by fantoine** [comment]
@fabpot I was kinda busy lately, but I'll try to finish to add tests next week.

**Comment by jakzal** [comment]
@fantoine looks like this branch no longer contains your changes.

**Comment by fabpot** [comment]
Closing as this PR is now empty (commits are gone or empty).

**Pull request closed without merging**
