### PR TITLE
Removed deprecations in VarDumper component

### PR DESCRIPTION
**Pull request by dosten**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
There is an other deprecation now in Caster\ReflectionCaster, can you amend it to this PR please?

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
Thank you @dosten.

**Pull request merged**
