### PR TITLE
Fix deprecation triggering test deduction

### PR DESCRIPTION
**Pull request by alexpott**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

This PR is just testing some additions https://github.com/symfony/symfony/pull/24597 - I want to see if the travis run is successful.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@alexpott #24597 now merged, what should we do with this PR?
(yes, it's hard to test the test system, I usually check out locally to simulate the target bridge)

**Comment by nicolas-grekas** [comment]
@alexpott, looks like you were right :) Can you please rebase this PR on latest 3.3?

**Review by xabbuh — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @alexpott.

**Comment by nicolas-grekas** [comment]
For some reasons, the hhvm, 5.6 and 5.5 builds are failing, even after this has been merged up to master.

**Comment by alexpott** [comment]
@nicolas-grekas Fixed in https://github.com/symfony/symfony/pull/24681

**Pull request merged**
