### PR TITLE
[Form] add missing Czech validators translation

### PR DESCRIPTION
**Pull request by mhujer**
| Q             | A
| ------------- | ---
| Branch?       | 5.1
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| License       | MIT

### CODE REVIEW

**Comment by mhujer** [comment]
@xabbuh This validator was added recently https://github.com/symfony/symfony/pull/36302 so I guess it won't be backported to 3.4, right? I rebased the branch 5.1 and changed to PR to target it.

**Comment by xabbuh** [comment]
@mhujer It's right that we don't backport new features, but for translations we try to minimise the effort needed for contributions and merge all translations into the oldest still maintained branch (`3.4` right now).

**Review by javiereguiluz — APPROVED** [review]
Thanks! Verified with Google Translate 👍

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @mhujer.

**Pull request merged**
