### PR TITLE
[2.7] Remove some unused variables, properties and methods

### PR DESCRIPTION
**Pull request by tgalopin**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | kind of
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT

Analyzing symfony/symfony using https://insight.sensiolabs.com, I found several chunks of dead code. This PR removes them in the 2.7 branch.

fabbot failure is unrelated.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by sroze** [comment]
Nice :-)

**Review by chalasr — APPROVED** [review]

**Comment by stof** [comment]
setters turned into no-ops here should be deprecated in master if they were not already in previous releases.

**Comment by tgalopin** [comment]
@stof Thanks, I planned to do that indeed.

**Comment by tgalopin** [comment]
Tests are green.

**Comment by nicolas-grekas** [comment]
Thank you @tgalopin.

**Pull request merged**
