### PR TITLE
[FrameworkBundle] Allow IDE path mappings for built-in protocols

### PR DESCRIPTION
**Pull request by ro0NL**
| Q | A |
| --- | --- |
| Branch? | "master" |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any |
| License | MIT |
| Doc PR | reference to the documentation PR, if any |

Before/After:

``` diff
#config.yml
framework:
-   ide: "phpstorm://open?file=file://%%f&line=%%l&/src/>/dest/"
+   ide: "phpstorm&/src/>/dest/"
```

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
given that the ide shortcuts shouldn't exist imho, I don't think we should do this: ide shortcuts are non standard, and the ide config is best done outside of the Symfony app, using the xdebug.file_link_format ini setting. This is a dev env related setting, not a Symfony-app one.

**Comment by ro0NL** [comment]
@nicolas-grekas you're probably right.. however we _do have_ the `framework.ide` setting allowing to override any global setting. Besides, it allows for _project specific_ path mappings.. is that a feature we support? 

Do you ideally want to drop the framework.ide setting entirely or just the built-in shortcuts?

**Comment by nicolas-grekas** [comment]
The shortcuts

**Comment by ro0NL** [comment]
I guess it will be very opinionated though, to remove them. If shortcuts are kept.. should this have a chance? As it makes more sense then.. (at least i expected it to work).

**Comment by nicolas-grekas** [comment]
Is this something you actually need for your own use? If not, let's close it.

**Comment by ro0NL** [comment]
Already set the xdebug setting ;-)

**Pull request closed without merging**
