### PR TITLE
Add missing translations for Belarusian

### LINKED ISSUE #38727: Missing translations for Belarusian (be)
Hello,

There are some missing translation for Belarusian (be). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Form/Resources/translations/validators.be.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Resources/translations/validators.be.xlf)
- [src/Symfony/Component/Security/Core/Resources/translations/security.be.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.be.xlf)
- [src/Symfony/Component/Validator/Resources/translations/validators.be.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.be.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by OxanaKozlova**
| Q             | A
| ------------- | ---
| Branch?       | 4.4 
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #38727 
| License       | MIT
| Doc PR        | N/A 

Add translations for Belarusian

### CODE REVIEW

**Comment by Nyholm** [comment]
Awesome. Thank you @OxanaKozlova. 

@belangela, it seams like @OxanaKozlova have made this fix. Could you review this pull request to see if the translations makes sense for you?

**Review by Nyholm — APPROVED** [review]
I reviewed this with Google Translate. It all looks good. 

Let's wait for a native speaker to review this too.

**Comment by VladimirBerezkin** [comment]
@Nyholm hi! I'm a native speaker. All looks good.

**Comment by Nyholm** [comment]
Awesome. Thank you. Then let's merge this =)

**Review by derrabus — APPROVED** [review]
@OxanaKozlova Can you squash your three commits into one? I would do it myself, but I'm not allowed to push to your fork.

**Comment by Nyholm** [comment]
Alternatively, one could allow maintainers to push to the fork by selecting this option in the sidebar. 

Screenshot 2021-03-03 at 10 00 22

**Comment by derrabus** [comment]
Thank you @OxanaKozlova.

**Pull request merged**
