### PR TITLE
[travis] test with php nightly

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Apparently, xdebug is not available and our setup fails before running the tests for PHP nightly. The travis file should be fixed before we can merge this one.

**Comment by stof** [comment]
XDebug is indeed not available on PHP 7 currently (it does not support PHP 7 yet).

The code removing the xdebug.ini config should check for ``nightly`` too

**Comment by nicolas-grekas** [comment]
Updated

**Comment by stof** [comment]
next steps (but probably in separate PRs though): debugging the issues on PHP 7 to know whether they are legitimate changes due to BC breaks in PHP 7 (the failure in the parsing of hexadecimal strings in Yaml is because of https://wiki.php.net/rfc/remove_hex_support_in_numeric_strings for instance) or whether they are highlighting bugs in PHP 7 (which should be reported to the PHP team).

Having the testsuite output for PHP 7 is great though.

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
