### PR TITLE
[Translation][Form][choice] Placeholder shouldn't be translated when empty

### PR DESCRIPTION
**Pull request by Restless-ET**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |
- [x] fix the tests

Without this I keep on getting the "missing messages" for an empty string at the Translation Profiler (like shown below) for every non-required `choice` Field Type.
missing_message

PS - I'm aware that the [Translation profiler](http://symfony.com/blog/new-in-symfony-2-7-translation-profiler) is only available for SF 2.7+ but since the `placeholder` option is available for SF 2.6+ I'm creating this PR against branch 2.6

### CODE REVIEW

**Comment by Restless-ET** [comment]
@webmozart I believe it's all ok now, but could you please take a look?

Regards,

**Comment by webmozart** [comment]
Thanks for working on this @Restless-ET. Looks good! :) Could you please rebase this onto 2.3 and open a new PR for the 2.3 branch? We need to fix this in the earliest supported version.

**Comment by Tobion** [comment]
Closing for #15048

**Comment by xabbuh** [comment]
@Tobion The Bootstrap form theme is not part of Symfony 2.3. So we need this PR to at least update that test class.

**Comment by Tobion** [comment]
@xabbuh such things must be done when merging. The naming is different in this branch anyway (placeholder instead of empty_value). So you need to resolve conflicts.

**Comment by Tobion** [comment]
There is no point in having PRs for the same thing.

**Comment by xabbuh** [comment]
@Tobion Will the merge take care of updating a test file that is (on a first glance) totally unrelated to the things fixed by the first PR? I understand that you will have to deal with the conflicts when merging branches. But I thought this PR should be kept for the 2.6 specific changes and could simply be rebased when the `2.3` branch has been merged up.

**Comment by Restless-ET** [comment]
@Tobion @xabbuh 
What exactly should I do here? Wait for the other PR to be merged and then updated this one?

**Comment by Tobion** [comment]
Fixed as part of the merge.

**Pull request closed without merging**
