### PR TITLE
[Translator] Remove deprecated feature

### PR DESCRIPTION
**Pull request by maidmaid**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

### CODE REVIEW

**Comment by chalasr** [comment]
I suggest to review this one after https://github.com/symfony/symfony/pull/23667.

**Comment by maidmaid** [comment]
Ok, but #23667 does not seem to affect the ``TranslationWriter``.

**Review by chalasr — APPROVED** [review]
#23667 BC layers removed during merge.

**Comment by nicolas-grekas** [comment]
Thank you @maidmaid.

**Pull request merged**
