### PR TITLE
[Bridge] [Doctrine] refactored EntityUserProvider class.

### PR DESCRIPTION
**Pull request by hhamon**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by hhamon** [comment]
Anyone from the core team to review please?

**Comment by javiereguiluz** [comment]
:+1: this should be safe to merge because the behavior hasn't change at all. Thanks Hugo!

**Comment by hhamon** [comment]
Thanks @javiereguiluz!

I've just rebased on top of 2.3 branch.

**Comment by HeahDude** [comment]
Looks like a nice catch! :+1:

**Comment by fabpot** [comment]
I don't understand the goal of this PR. If it is just about moving the `if` part, I don't see the value but I can see that it's going to be a pain to merge to other branches if code has been modified there.

**Comment by hhamon** [comment]
I have just removed the "else" statement to make the code more readable. It seems the class is the same from a version to another.

**Comment by xabbuh** [comment]
I am not sure if it's worth to make this change given that it increases the risk to break during merging branches.

**Comment by stof** [comment]
Closing this for the reasons given by @xabbuh and @fabpot (and we discussed it in person with @hhamon today)

**Pull request closed without merging**
