### PR TITLE
[Validator] add domain test for windows check dns

### PR DESCRIPTION
**Pull request by beebop1032**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Bug fix compatibility windows RFC on Email validation
RFC windows check host gmailcom as gmailcom.com so its ok but is not..

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Looks like this broke some test.

**Review by fabpot — COMMENTED** [review]
The file mode change must be reverted.

**Review by beebop1032 — COMMENTED** [review]
@fabpot sure. I will look at how to improve this request.

**Comment by fabpot** [comment]
The file mode still needs to be reverted. Also, I'm not sure I understand the bug. Can you give us an example were your fix would be needed?

**Comment by beebop1032** [comment]
The problem is related to this note in checkdnsrr php doc  : 

http://php.net/manual/fr/function.checkdnsrr.php#119969

I attach a screenshot of results that are different depending on the server

The majority problem for me is that email@gmailcom returns true (actually it tests gmailcom.com).

checkdns

**Comment by beebop1032** [comment]
@nicolas-grekas The appveyor tests are broken but I don't think it's me?

**Comment by beebop1032** [comment]
Do you need more information @fabpot ?

**Comment by beebop1032** [comment]
Hi. When are you gonna look? Thanks a lot !

**Comment by xabbuh** [comment]
> The problem is related to this note in checkdnsrr php doc :
>
> http://php.net/manual/fr/function.checkdnsrr.php#119969

Reading the comment in the docs wouldn't a better fix be to append a dot to the hostname when calling `checkdnsrr()`?

**Comment by fabpot** [comment]
Suggestion from @xabbuh sounds good, but I don't think it will work on Linux. We should try.

**Comment by fabpot** [comment]
I'm still :-1: for this change. Email validation is complex (see the various PRs on this topic) and opinionated. And I would not recommend anyone to use these options anyway, so I propose to instead deprecate checkMX and checkHost and remove them in 5.0.

**Pull request closed without merging**
