### PR TITLE
[DependencyInjection] Removal of service definition with alias dont leave orphan aliases

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #25060 
| License       | MIT
| Doc PR        | will add.

I'm adding a new method in order to tell to remove the alias to the services.

This is one of the implementation, the other could be to search all class with an alias and remove them.

img_2664

### CODE REVIEW

**Review by nicolas-grekas — COMMENTED** [review]
Et really not sure we want to add this. Ppl doing config have the responsibility to make it correct.

**Comment by Simperfit** [comment]
Let's discuss this if we really want to commit to this feature ;).

**Comment by theofidry** [comment]
So if you have:

```yaml
services:
  App\Foo: {}

  foo: '@App\Foo'
```

- If somewhere something is using `@App\Foo` once then you'll have `App\Foo` inlined and  `foo` left as an orphan which doesn't look ideal, we could remove the orphan
- If somewhere something is using `@foo` once then you'll have `foo`, resolved into `App\Foo` inlined and both `App\Foo` and `foo` removed
- If somewhere you are using `@App\Foo` and somewhere else `@foo`, then nothing is inlined

Does the above sounds correct or there is some caveat/things not implemented that way yet?

**Comment by nicolas-grekas** [comment]
IMHO we don't want to provide this, see https://github.com/symfony/symfony/issues/25060#issuecomment-345961812

**Comment by theofidry** [comment]
Oh wait I though that was caused by the Symfony optimisation (automatically in-lining services when possible), not you manually removing a service definition :)

In that case yeah it doesn't make much sense to support it, it's too rare of a case IMO and would break too often

**Comment by Simperfit** [comment]
I guess we will not be supporting it :p

**Pull request closed without merging**
