### PR TITLE
Fixed a minor XML issue in a translation file

### PR DESCRIPTION
**Pull request by javiereguiluz**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17893 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: 

Status: Reviewed

**Comment by stof** [comment]
:+1: for this fix

@javiereguiluz it may be worth adding unit tests in the different components containing translation to assert the validaty of these files, to avoid such mistakes in the future (catching them on CI).

**Comment by javiereguiluz** [comment]
@stof good idea! I'm going to try to create a pull request for that. Thanks!

**Comment by nicolas-grekas** [comment]
Thank you @javiereguiluz.

**Pull request merged**
