### PR TITLE
[TwigBridge] forward compatibility with Yaml 3.1

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by stof** [comment]
:+1: 

We may even want to apply this in older branches

**Comment by xabbuh** [comment]
Indeed, I missed that the requirement is only in `require-dev` (in older versions test won't be executed with 3.1). But this should apply cleanly on older branches.

**Comment by nicolas-grekas** [comment]
Why backporting to older branches ? Their composer.json make them not compatible with 3.1, so this would always evaluate to false, isn't it?

**Comment by xabbuh** [comment]
@nicolas-grekas I do not see what would prevent someone to use the TwigBridge in Symfony 2.3 together with the Yaml component from 3.1. Do I miss something?

**Comment by nicolas-grekas** [comment]
Nevermind, I didn't understand you above statement about the req being in `require-dev` :)

**Comment by xabbuh** [comment]
oh okay :)

**Comment by nicolas-grekas** [comment]
Thank you @xabbuh.

**Pull request closed without merging**
