### PR TITLE
[Messenger] Re-introduce wrapped message configuration (with fix)

### PR DESCRIPTION
**Pull request by sroze**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #26945
| License       | MIT
| Doc PR        | ø

The pull request was merged before beta1, but because it introduced a bug, it has been reverted. This adds back the merged PR but pushes a fix for the found bug.

### CODE REVIEW

**Review by ogizanagi — APPROVED** [review]

**Comment by kbond** [comment]
What exactly was the bug?

**Comment by ogizanagi** [comment]
The original envelope was not properly passed along the whole middleware stack when calling `$next($message)`, so items were vanished in between.
This fixes it and also allows altering the message and the envelope items through middlewares.

**Comment by ogizanagi** [comment]
I've pushed another commit to https://github.com/sroze/symfony/pull/6 for the TraceableBus which misses a small update.

**Comment by sroze** [comment]
Merging as we found and fixed the bug that was almost to bug in beta1.

**Comment by sroze** [comment]
Thank you @ogizanagi.

**Pull request merged**
