### PR TITLE
[bugfix] [Console] Set `Input::$interactive` to `false` when command is executed with `--quiet` as verbosity level

### LINKED ISSUE #19899: [RFC] Should console `--quiet` option set mode `interactive=false`?
I have a command where I'm using the console this way:
```php
if ($input->isInteractive() && !$this->io->confirm('Provide confirmation', false)) {
    // some stuff...
}
```
But when I execute the command with `--quiet`, the output is obviously not displayed but the process still waits for the user's response.
For this reason, I think the `--quiet` option (`OutputInterface::VERBOSITY_QUIET`) should set `Input::$interactive` as `false`.
>OutputInterface::VERBOSITY_QUIET	Do not output any messages	-q or --quiet

Ref: http://symfony.com/doc/current/console/verbosity.html

If I don't misunderstood the intended behavior, I think it could be labeled as a bug.

### PR DESCRIPTION
**Pull request by phansys**
| Q | A |
| --- | --- |
| Branch | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #19899 |
| License | MIT |
| Doc PR | n/a |

Closes #19899.

### CODE REVIEW

**Comment by fabpot** [comment]
I don't understand why quiet and interactive would be tied. I made this decoupling consciously back then. It looks more flexible. So, I'm 👎 for this change.

**Comment by phansys** [comment]
I understand your concern about the responsibilities, but the fact I'm exposing here is that isn't possible to interact with a command when it is executed in quiet mode, given the command isn't able to prompt for any input or provide any kind of response to the user. For this reason, I think a method called `isInteractive()` must return `false` when the command isn't allowed to interact with the user at all.

**Comment by fabpot** [comment]
Ah, understood now. Indeed, if even the questions are not displayed, that does not really make sense to have an interactive quiet command :)

**Comment by fabpot** [comment]
Thank you @phansys.

**Pull request merged**
