### PR TITLE
[Form] Fix declaration of legacy tests

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Ping @webmozart for info
#14214 makes this easier

**Comment by webmozart** [comment]
@nicolas-grekas We usually follow rule of waiting for two +1 from the core team before merging PRs. Was this rule changed?

**Comment by nicolas-grekas** [comment]
You're right, this rule is still valid and I apologize for breaking it yesterday. My excuse is having a few hours free for fixing these red tests everywhere. I could wait for the voting process, but this would have taken weeks instead of hours. If you look at the patch I produced, they are all small tweaks here and here.

I really hope we won't break tests that much again. Now that everything is green and as I said in an other PR, I'm fine with overwriting my patches. Provided tests remain green of course :)

**Comment by webmozart** [comment]
I now how painful the waiting can be :) but usually you can reduce the waiting to a day or two by poking the deciders via GitHub and/or GTalk.

Nevertheless, I get a lot of deprecation notices in the Form component since this change. Any idea?

**Comment by webmozart** [comment]
PS When running PHPUnit, that is.

**Comment by nicolas-grekas** [comment]
That's on 2.6 but not on 2.7 isn't it?
I'd say this summary from the PhpUnit bridge has not changed recently, even if I tweaked it in #14214 but I may be wrong.

On 2.6 and 2.3, you can silence the deprecations with:
`SYMFONY_DEPRECATIONS_HELPER=weak phpunit`

On 2.7 this is not required.

**Comment by webmozart** [comment]
No, on 2.7. Hangouts?

**Pull request merged**
