### PR TITLE
Allow PHP ^7.2.5

### LINKED ISSUE #34442: [symfony/contracts] Why hard dependency to php 7.2.9?
**Symfony version(s) affected**: v3.4.35

**Description**  
I can't install symfony/contracts on a SUSE SLES 12 (SP4) system since it only has php 7.2.**5**. symfony/contracts requires 7.2.**9**.

**Possible Solution**  
Set the dependency to `^7.2` insteadt of `^7.2.9`.

**Additional context**  
If a pull reuqest is needed, just tell me.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #34442
| License       | MIT
| Doc PR        | -

Let's what the CI says.

Will need tagging all contracts as v2.0.1 after merge.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Looks good to me (appveyor failure is unrelated - existed before)

**Comment by derrabus** [comment]
Out of curiosity: Do you know why `7.2.9` was originally picked as minimal requirement?

**Review by derrabus — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
I think it's the version Debian ships

**Review by lyrixx — APPROVED** [review]
72 `composer.json`, hoho

**Review by darielopper — APPROVED** [review]

**Comment by k00ni** [comment]
Why was the min PHP-version lowered to `7.2.5` and not `7.2`?

**Comment by nicolas-grekas** [comment]
.0 versions are always buggy and we don't want to test with them and workaround these early bugs.

**Comment by Defcon0** [comment]
mhm, seems to not being accepted?

**Comment by Matts** [comment]
Note:
7.2.5 -> Security fix
7.2.8 -> Security fix

https://www.php.net/ChangeLog-7.php#PHP_7_2

Maybe a good idea to note somewhere that, although Symfony supports 7.2.5, it is advised to always update to latest patch?

**Comment by Defcon0** [comment]
Could be, but SUSE Linux (up to 15) only has php 7.2.5. This is a major show stopper.

**Comment by nicolas-grekas** [comment]
Distributions backport security fixes, that's why ppl pay for them. It's not our job to safeguard ppl from themselves :)

**Comment by stof** [comment]
tests are failing for the Cache PdoAdapter and the Lock PdoStore. Not sure whether this is related to the new PHP version or whether they were already broken on Windows.

**Comment by nicolas-grekas** [comment]
@stof not related to this PR, I noticed these failures before, reported in #34444

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by Defcon0** [comment]
Will this trickle down to the repo

https://github.com/symfony/contracts/blob/master/composer.json

?

**Comment by chalasr** [comment]
@Defcon0 yes, see PR description :)

Should be applied to symfony/*skeleton also

**Comment by Defcon0** [comment]
@nicolas-grekas Could you please tag the contracts bundle to 2.0.1? We need the fix quite urgently ;-) Thanks!

**Comment by GrahamCampbell** [comment]
Any news on the 2.0.1 contracts tag?

**Comment by derrabus** [comment]
> Any news on the 2.0.1 contracts tag?

The core team is probably busy with SymfonyCon right now. Please have a little patience. You can require `^2@dev` in the meantime, if the missing tag really blocks you.

**Pull request merged**
