### PR TITLE
[DI] Fix by-type args injection

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Three fixes:
- arguments should have higher priority than bindings
- `$named` arguments should have higher priority than `By\TypeHint` arguments
- doubled same-type should work, not only the first should be wired

@sroze I might need your help for adding tests, would be awesome!

### CODE REVIEW

**Comment by sroze** [comment]
@nicolas-grekas can you give me a PHP class example that showcases what you try to solve? I can't reproduce the last issue 🤔

**Comment by stof** [comment]
@nicolas-grekas do we still need the pass order change.

**Comment by keradus** [comment]
any test showing the fix would be nice as well ;)

**Comment by nicolas-grekas** [comment]
Tests have been added as part of #24991

**Pull request closed without merging**
