### PR TITLE
[DependencyInjection] Fixed missing tests

### PR DESCRIPTION
**Pull request by dosten**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Follow up of #11422 and #14446

### CODE REVIEW

**Comment by dosten** [comment]
ping @stof @xabbuh

**Comment by xabbuh** [comment]
:+1: Thanks for taking care of this @dosten!

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
Thank you @dosten.

**Pull request merged**
