### PR TITLE
[Ldap] Add forward compatibility layer

### PR DESCRIPTION
**Pull request by csarrazi**
| Q | A |
| --- | --- |
| Branch | master |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

This PR adds forward-compatibility for the use of the Ldap component within the Security component. Indeed, currently, if one uses the `Symfony\Component\Ldap\LdapClient` class and upgrades to the `master` branch of `symfony/symfony`, the Security component will break as the class does not implement `LdapInterface`.

This PR fixes this.

This means that from now on, the `master` branch of the Ldap component should be compatible with all versions of the Security component. The 2.8/3.0 Security component should be compatible with all versions of the Ldap component, and the 3.1 Security component should be compatible with versions 3.1 onwards of the Ldap component.

### CODE REVIEW

**Comment by csarrazi** [comment]
It seems that the tests fail for an unrelated reason.

**Comment by fabpot** [comment]
Don't you also have to update some dep versions in some composer.json files?

**Comment by csarrazi** [comment]
This will be done in the 3.0 and 2.8 branches.

**Comment by nicolas-grekas** [comment]
@csarrazi can you open the sibling PR you're thinking about please?

**Comment by csarrazi** [comment]
Sure. Will do later today.

**Comment by csarrazi** [comment]
Rebased PR

**Comment by csarrazi** [comment]
AppVeyor builds fail because of an issue in the Console component (unrelated to this PR).

Related PR #18201 should be merged afterward, to release the version requirement on the `3.0` branch.

**Comment by nicolas-grekas** [comment]
Thank you @csarrazi.

**Pull request merged**
