### PR TITLE
Make HttpCache behaves more like a real reverse proxy

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #6982, #7000 |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by leofeyer** [comment]
@fabpot Shouldn't you be adding the port number [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php#L455) if it is not 80 or 443?

```
Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Accept-Encoding: gzip, deflate
Accept-Language: de,en;q=0.9
Connection: Keep-Alive
Device-Stock-Ua: Mozilla/5.0 (Linux; Android 4.4.2; BLOOM Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36
Forwarded: for="10.10.10.10:34161"
Host: www.example.com"
User-Agent: Opera/9.80 (Android; Opera Mini/18.0.2254/37.8814; U; de) Presto/2.12.423 Version/12.16
X-Forwarded-For: 10.10.10.10
X-Operamini-Features: httpping, advanced, pingback, routing, file_system, camera, touch, viewport, folding, download
X-Operamini-Phone: Android #
X-Operamini-Phone-Ua: Mozilla/5.0 (Linux; Android 4.4.2; BLOOM Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36"
```

As you see, the `Forwarded` header has the port number (`10.10.10.10:34161`) whereas the `X-Forwarded-For` header does not. This will lead to a `ConflictingHeadersException`.

**Comment by xabbuh** [comment]
@leofeyer Please open a new issue if you think that you found a bug.

**Comment by leofeyer** [comment]
Will do as soon as I know for sure that it is a bug. 😄

**Comment by MAXakaWIZARD** [comment]
@leofeyer There's `normalizeAndFilterClientIps` call here, which removes port numbers from all IPs: https://github.com/symfony/http-foundation/blob/2.8/Request.php#L830

**Pull request closed without merging**
