### PR TITLE
[travis] Run real php subprocesses on hhvm for Process component tests

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Branch | 2.3 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Let's see if this speeds up hhvm test matrix line.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
And the answer is... YES, by one minute!

**Comment by javiereguiluz** [comment]
Great! Thanks for your continuous effort towards optimizing tests. This is much appreciated by lots of us!

**Comment by ProPheT777** [comment]
@nicolas-grekas there is a failed test and marked as pass : https://travis-ci.org/symfony/symfony/jobs/116377636#L4679

**Comment by nicolas-grekas** [comment]
@ProPheT777 this is hhvm behavior, nothing related to this PR, and no failure but only garbage output.

**Comment by ProPheT777** [comment]
Ok great, that was just in case! Thank you

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
