### PR TITLE
[DependencyInjection] ContainerInterface: unused exception dropped

### PR DESCRIPTION
**Pull request by TomasVotruba**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |

Ref https://github.com/symfony/symfony/pull/14599

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by aitboudad** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @TomasVotruba.

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
