### PR TITLE
[HttpKernel] [FrameworkBundle] [Console] - Added interface to register commands instead of depending on Bundle class

### PR DESCRIPTION
**Pull request by yvoyer**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |
- [ ] submit changes to the documentation

This feature introduce a new interface to trigger the registration of commands on Bundles that do not extends `Symfony\Component\HttpKernel\Bundle\Bundle`.

Using this PR, Bundles can now implement `Symfony\Component\HttpKernel\Bundle\BundleInterface` and `Symfony\Component\Console\CommandRegistryInterface` to enable commands to be registered by the FrameworkBundle's Application class.

### CODE REVIEW

**Comment by GromNaN** [comment]
To summarize, we have 3 components where the interface can be:
- The `Console` component. It seems the more logical place since this interface is related to the console commands and only use the `Console\Application` class. But by implementing this interface, the `Bundle` class get a hard dependency to this component.
- The `FrameworkBundle`.
- The `HttpKernel` component. Since this interface describe an "optional" feature, it is available for any project that uses this component (Bundles, Silex, ...) without the hard dependency to the Console. Unfortunately, this interface cannot be used in a project that uses only the Console.

What if we created 2 identical interfaces in `Console` and `HttpKernel?

**Comment by yvoyer** [comment]
What is the current stage in regards to the split of the console component? 
Any suggestion to fix the dependency problem?
Do you want to keep this issue open for later?

**Comment by fabpot** [comment]
Re-reading this PR's code and I'm wondering what kind of new usages it allows. Do you really have classes that implements the Bundle interface without extending the Bundle class?

The current mechanism is anyway tied to FrameworkBundle, so I don't think that this interface would help in any way Silex or Cilex.

**Comment by yvoyer** [comment]
@fabpot My use case for this PR was that I wanted to define a bundle class using the `BundleInterface` only, and register my command (located someplace else than the default folder). When I did, I found out that registering commands was not working, and it was relying on the `Bundle` implementation. But since my commands were located someplace else than the `Bundle\MyBundle\Command` folder, it would not work.

Using the `CommandRegistryInterface` interface, it would detach the dependency to the implementation of `Bundle` and instead rely on an interface.

IMO, defining an interface and assuming that everyone will use the `Bundle` implementation breaks the goal of interfaces. If we want our users to only use the `Bundle`, make it explicit, and remove the `BundleInterface` interface, since it do not add any value.

```php
// Would not register commands out of the box. I would need to extends Bundle for them to be registered
class MyCustomBundle implements BundleInterface 
{
    ...
}

// Would add the possibility to add commands, while depending on the interface instead of Bundle. 
class MyOtherBundle implements BundleInterface, CommandRegistryInterface
{
   ...
}
```

You are right that its not adding any features, its more about design and dependency.

**Comment by fabpot** [comment]
Closing this one as I don't want to add the Console as a dep to HttpKernel but also because it does not seem to be a common use case.

**Pull request closed without merging**
