### PR TITLE
[TwigBridge] Bootstrap Layout - Fix the label of checkbox cannot be empty

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #13803 |
| License | MIT |

### CODE REVIEW

**Comment by fabpot** [comment]
@ogizanagi Can you test it before we merge?

**Comment by ogizanagi** [comment]
@fabpot : Sure, I will. 
Maybe @qferr could test it too regarding its own case.

**Comment by ogizanagi** [comment]
@fabpot : I confirm through my own tests that everything should work as expected. You could have a look at [test_pr_13806](https://github.com/ogizanagi/sf2SE_demos/tree/test_pr_13806) in order to test it easily.

**Comment by qferr** [comment]
It works !

Thank you @ogizanagi .

**Comment by fabpot** [comment]
Thank you @ogizanagi.

**Pull request merged**
