### PR TITLE
[Config] Fixes the valid placeholder types for variable node

### PR DESCRIPTION
**Pull request by ghost**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | we will see...    
| Fixed tickets | #26894
| License       | MIT

This is a proposition, still in discussion.

### CODE REVIEW

**Comment by xabbuh** [comment]
@ro0NL Can you have a look here?

**Comment by ro0NL** [comment]
Hm, @romain-pierre you are using an env-var for a variable node type right?

I think we can say it allows all types (including array AFAIK). So maybe the better fix is

```diff
-if (array_diff($knownTypes, $validTypes))
+if ($validTypes && array_diff($knownTypes, $validTypes))
```

Could you try that?

**Comment by romain-pierre** [comment]
Absolutely, the use case is the SncRedis configuration ([see](https://github.com/snc/SncRedisBundle/blob/2.1.0/DependencyInjection/Configuration/Configuration.php#L105)) that allows env placeholder. The resulting error is:

> Invalid type for path "snc_redis.clients.default.dsns.0". Expected one of "", but got "string".

For your suggestion, why not, it's an other approach, if you consider that non scalar type are also allowed. So, we could consider that in the case of VariableNode use, this is the responsibility of the user to check the type, and not the one of the Config componement? If your are agree with that, I can change my PR by this way.

**Comment by ro0NL** [comment]
> if you consider that non scalar types are also allowed

That's already possible no? I can pass any value to a variable node type...

**Comment by romain-pierre** [comment]
Yeah you probably right, but I never see this case for now.

The last question I have: there is no confusion/bug risk to *disable* the check when no type are allowed? It's hard to admit that `if [string] is in []` is true.

**Comment by ro0NL** [comment]
> there is no confusion/bug risk to disable the check when no type are allowed?

We should add test for variable nodes yes, see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Tests/Compiler/ValidateEnvPlaceholdersPassTest.php#L227

**Comment by ro0NL** [comment]
> there is no confusion/bug risk to disable the check when no type are allowed?

The feature is new in 4.1, custom node types are not really affected yet. So yes, safe move IMHO.

Empty array means all types are valid (accepting _no_ types is nonsense :))

**Comment by romain-pierre** [comment]
You convinced me (to avoid BC break). But if *accepting no types is nonsense* it should throw an exception IMHO, in a perfect world.

I will update this PR with your proposition.

**Review by ro0NL — APPROVED** [review]
extra test would be nice :)

**Comment by romain-pierre** [comment]
If you are ready to wait a little bit, I'm in to write some tests about this fix (in an other PR?), it could be a good training for me.

**Comment by ro0NL** [comment]
Same PR i'd say. Let me know if you need help :)

In general add a new node here https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Tests/Compiler/ValidateEnvPlaceholdersPassTest.php#L227 and then a new test like `testEnvForvariableNode` or so :+1:

**Comment by nicolas-grekas** [comment]
@romain-pierre in this very PR please, to reduce the overhead.

**Review by ro0NL — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @romain-pierre.

**Comment by fabpot** [comment]
Thank you @romain-pierre.

**Pull request merged**
