### PR TITLE
[Routing] Fix AnnotationDirectionLoaderTest

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | master
| Tests pass? | yes

This directory contains more annotated classes on master, one being read twice (perhaps a bug?)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @chalasr.

**Comment by nicolas-grekas** [comment]
Can you still investigate a bit the double?

**Comment by chalasr** [comment]
@nicolas-grekas will do. My knowledge regarding annotations is quite limited, let's try to change that.

**Comment by chalasr** [comment]
In `AnnotationClassLoader::load()`, there're two places triggering `AnnotationReader::getClassAnnotation()` to be called: [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php#L116) and [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php#L130). 
In the latter, the call is the last condition of an `if` statement. This call is never reached for other classes because they are invokable (satisfying the check before reaching the method call), the fact `BazClass` is not invokable justifies this extra call. At the end of `AnnotationDirectoryClassLoader::load()`, the double doesn't exist, only this method call occurs twice for the same class. Voilà :)

**Pull request merged**
