### PR TITLE
[Fragment] Move configuration to PHP

### PR DESCRIPTION
**Pull request by idetox**
| Q             | A
| ------------- | ---
| Branch?       | master 
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no 
| Tickets       | Ref #37186 
| License       | MIT

### CODE REVIEW

**Review by javiereguiluz — APPROVED** [review]
This looks correct to me!

I only have two minor questions:

(1) Should we standardize the order of PHP calls? In the original XML file, the tag was added before the args, so in PHP is the same:

```php
->tag('kernel.event_subscriber')
->args([
    service('uri_signer'),
    param('fragment.path'),
])
```

But maybe we should put args first always?

```php
->args([
    service('uri_signer'),
    param('fragment.path'),
])
->tag('kernel.event_subscriber')
```

(2) We should probably inline some `args()` calls because their service list is short enough:

```php
// Before
->args([
    service('uri_signer'),
    param('fragment.path'),
])

// After
->args([service('uri_signer'), param('fragment.path')])
```

**Review by massamba00 — APPROVED** [review]

**Comment by Tobion** [comment]
tags are added after the args (and calls) in the other PRs. So I think this should be changed for consistency here.

**Comment by idetox** [comment]
So order is 
```php
->args()
->tag()
->call()
```
Right ?

**Review by Tobion — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Comment by idetox** [comment]
If someone can help, i don't know how to fix the test 😢

**Comment by yceruto** [comment]
@idetox don't worry about it, it's a random failure. I've re-run the jobs to see if it happens now.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Can you squash your commits please?

**Comment by Tobion** [comment]
Thank you @idetox.

**Pull request merged**
