### PR TITLE
[2.6] Static Code Analysis for Components

### PR DESCRIPTION
**Pull request by kalessil**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Static Code Analysis with Php Inspections (EA Extended):
    - finished random api migration
    - for -> foreach transformation

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@kalessil FYI, 2.6 is not maintained anymore, can you please check if your patch merges cleanly on 2.7, or open a new PR on 2.7?

**Comment by nicolas-grekas** [comment]
The issue with this patch is that it will for sure create many merge conflicts.
As with other patches of this kind, can you please start with one PR on 2.3?
Some part of the current patch apply on 2.3, and therefore must be merged there before anything else.

**Comment by kalessil** [comment]
Status update: in progress

**Comment by fabpot** [comment]
Closing as 2.6 is not maintained anymore. @kalessil Feel free to reopen new ones on 2.3 and 2.7. Thanks.

**Pull request closed without merging**
