### PR TITLE
[Serializer] #17881 preg quote camel case to snake case name converter

### PR DESCRIPTION
**Pull request by Aerendir**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17881 |
| License | MIT |
| Doc PR | N/A |

[Serializer] `preg_quote` `$propertyName` in `denormalize()` method.

This will ensure that the characters that need to be quoted, are. (Ex.: ":" if the decoded string is an `XML` file.
- [ ] gather feedback for my changes

I need some guidance: why are there commits from other pull requests? I've never contributed to a so big project. Some help will be appreciated to make me able to contribute more. Thank you.

### CODE REVIEW

**Comment by iltar** [comment]
I think something went wrong with your pull request, you have a bunch of commits in there that are not yours.

**Comment by dunglas** [comment]
Try `git checkout 2.7 && git pull && git checkout -b quote_camel_case && git cherry-pick 2c59596a8afa5ebb95b0a64355a13cc0a1f8e0a6` then push to this branch.

**Comment by fabpot** [comment]
I don't understand this change. The third parameter of `preg_replace_callback` is the string used to match the regular expression. Why would you need to quote characters there? Quoting is needed in the regex, not in the string you are applying the regex against.

**Comment by fabpot** [comment]
Closing as I'm pretty sure that this change is wrong (and the history is borked anyway). Feel free to reopen with more details about a failing case. Thanks.

**Pull request closed without merging**
