### PR TITLE
Added missing APCU CacheProvider of doctrine/cache 1.6.x

### PR DESCRIPTION
**Pull request by fncmedia**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | yes |
| License | MIT |
| Doc PR | reference to the documentation PR, if any |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:
Status: reviewed

**Comment by dunglas** [comment]
👍

**Comment by fabpot** [comment]
Thank you @fncmedia.

**Comment by dextervip** [comment]
Is it not going to be supported in 2.8?

**Comment by xabbuh** [comment]
@dextervip No, we never backport features to already released minor versions.

**Comment by dunglas** [comment]
@xabbuh this one is really annoying because it prevents using Symfony 2 on PHP 7 with decent performances because the compatibility layer between APC and APCu has been disabled by default on APCu for PHP 7 and requires to recompile the extension to enable it.

**Comment by dextervip** [comment]
That's my issue. I've upgraded to PHP 7 with sf2.8 but I am unable to use apcu cache now. And I can't upgrade to sf3.x right now. Any workarounds for this?

**Comment by teohhanhui** [comment]
What is this used for, actually?

Because before this I can already do:

```yaml
# app/config/config_prod.yml
doctrine:
    orm:
        metadata_cache_driver: 'apcu'
        result_cache_driver: 'apcu'
        query_cache_driver: 'apcu'
```

**Pull request merged**
