### PR TITLE
[BUG] Delete class 'control-group' in bootstrap 3

### PR DESCRIPTION
**Pull request by Toelath**
| Q | A |
| --- | --- |
| Branch? | 3.0 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18506 |
| License | MIT |
| Doc PR | any |

### CODE REVIEW

**Comment by xabbuh** [comment]
I do think that we can merge this as someone might already rely on the class being present in their own code.

**Comment by fabpot** [comment]
Do we really need to keep BC here? This is a Bootstrap theme and the class does not exist.

**Comment by Toelath** [comment]
This class does not exist in Bootstrap 3. More, this causes problems to display because this is not the default use of framework. The answers are either the deletion of the class in HTML or add CSS to correct buttons display.

**Comment by fabpot** [comment]
👍 for merge

**Comment by fabpot** [comment]
Thank you @Toelath.

**Pull request closed without merging**
