### PR TITLE
Fix TaggedIterator TaggedLocator and Target attributes to target properties, not parameters

### PR DESCRIPTION
**Pull request by simPod**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| License       | MIT

### CODE REVIEW

**Comment by stof** [comment]
Why wouldn't they target parameters ?

**Comment by simPod** [comment]
Hm, good question.

Jetbrains IDE complained about this:

```php
    public function __construct(
        #[TaggedIterator('tag')] private iterable $a
    ) {
    }
```

> Attribute cannot be applied to a property because it does not contain the 'Attribute::TARGET_PROPERTY' flag 

but it is a bug in IDE I guess. Thanks

**Comment by simPod** [comment]
Umm, psalm just told me the same. Who's right? The php documentation on attributes is kind of brief:

```
ERROR: InvalidAttribute - src/File.php:17:11 - This attribute can not be used on a property (see https://psalm.dev/242)
        #[TaggedIterator('tag')] private iterable $a
```

Crosslink https://github.com/vimeo/psalm/issues/6713

**Comment by bazzik** [comment]
@simPod 
Please check comments in [WI-59974](https://youtrack.jetbrains.com/issue/WI-59974) and [WI-59609](https://youtrack.jetbrains.com/issue/WI-59609) (in particular [this comment](https://youtrack.jetbrains.com/issue/WI-59609#focus=Comments-27-4817389.0-0) by Nikita Popov)

**Comment by simPod** [comment]
@bazzik I see, omg this kinda made me laugh, thanks!

@stof I wonder what would the proper solution to the problem be. Do you think this should not be used with property promotion? As @nikic said: "I'm not sure what should be done about this" I think this will have to be somehow resolved on PHP's side first 🤔

**Comment by stof** [comment]
in any case, this PR is totally wrong, as it removes the parameter target, while Symfony will use it only on parameters and not on properties, so it actually breaks the feature entirely

**Comment by bazzik** [comment]
If you want to use it on promoted properties and for Psalm/IDE to be happy you may need to use this kind of declaration instead (which might be wrong due to _"Symfony will use it only on parameters"_ comment above):
```
#[\Attribute(\Attribute::TARGET_PARAMETER | \Attribute::TARGET_PROPERTY)]
```
_(just an idea, have not tested it at all)_

**Comment by simPod** [comment]
@bazzik yup, thought the same but I'm not sure if it's ok to allow it on properties since we could then do

```php
class A {
    #[TaggedIterator('tag')] private iterable $a 
}
```

but symfony would not inject things there (or will it? @stof)

@stof sorry, forgot to convert to draft

**Comment by stof** [comment]
@simPod it won't do anything there (there is no way to inject into private properties anyway).

@nicolas-grekas does this autoconfiguration parameter work on public properties or no ? I don't remember how public properties are handled in the autoconfiguration and autowiring systems. If it does, then adding the property target will be legitimate anyway.

**Comment by nicolas-grekas** [comment]
Thank you but this is a bug in phpstorm/etc. Allowing these attributes on properties is just plain wrong.

**Comment by nicolas-grekas** [comment]
> autoconfiguration parameter work on public properties or no

Honestly I don't remember :)
If this should be made to work, it should come with test cases if you want to have a look @simPod

**Pull request closed without merging**
