### PR TITLE
[Console] Add placeholder for line number in console exception fixtures

### PR DESCRIPTION
**Pull request by pierredup**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Add placeholders for exception line numbers for tests in `ApplicationTest` to make the tests more flexible

### CODE REVIEW

**Comment by pierredup** [comment]
Travis HHVM failure seems unrelated

**Review by chalasr — APPROVED** [review]
I would have just changed `assertStringEqualsFile` to `assertStringMatchesFormatFile()`, replacing the line number by `%d` in fixtures (https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertStringMatchesFormatFile). Feel free to update if you want, fine for me as is. Thanks for taking care

**Comment by pierredup** [comment]
I think `assertStringMatchesFormatFile` is cleaner as it's not necessary to track the exception line anymore. I have implemented the suggested changes

**Comment by chalasr** [comment]
Thank you @pierredup.

**Pull request closed without merging**
