### PR TITLE
[Security] These interface allways send deprecated because of wrong inheritance

### PR DESCRIPTION
**Pull request by xkobal**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #16643 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by dosten** [comment]
Seems related to #16643

**Comment by xkobal** [comment]
Yes this is the same problem, I haven't seen the issue

**Comment by xkobal** [comment]
Broken tests doesn't seems to come from my PR :-/

**Comment by m0ppers** [comment]
I stumbled upon the same issue in #16801 . this pull request is however missing namespace renaming in SimpleFormAuthenticationListener I think (which is needed for #16801). closing my issue now

**Comment by stof** [comment]
The inheritance is done the right way to preserve BC. What should be fixed is that the DebugClassLoader should not trigger a warning for this particular case.

**Comment by stof** [comment]
@nicolas-grekas please check this case for the DebugClassLoader

**Comment by nicolas-grekas** [comment]
Me or anyone else :-)

**Comment by peterrehm** [comment]
I just implemented it in #17320.

**Comment by nicolas-grekas** [comment]
Closing in favor of #17320

**Pull request closed without merging**
