### PR TITLE
[Console] Fix wrong exceptions being thrown

### PR DESCRIPTION
**Pull request by JhonnyL**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | no |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by sstok** [comment]
LGTM :+1:

**Comment by OskarStark** [comment]
LGTM 👍

**Comment by stof** [comment]
:+1:

**Comment by javiereguiluz** [comment]
👍

**Comment by nicolas-grekas** [comment]
Thank you @JhonnyL.

**Pull request merged**
