### PR TITLE
* wrong trans-unit ids

### PR DESCRIPTION
**Pull request by StaffNowa**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| License       | MIT

Just small fix with trans-unit-id. validators.en.xlf (the main)

### CODE REVIEW

**Comment by ro0NL** [comment]
perhaps worth checking in https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Translation/Resources/bin/translation-status.php

**Review by Nyholm — APPROVED** [review]
Thank you. 

Im not sure how this happened.

**Comment by nicolas-grekas** [comment]
Good catch, thanks @StaffNowa.

**Comment by rvanlaak** [comment]
@ro0NL as in, let that command compare and match the source translations with the trans-unit id?

**Comment by ro0NL** [comment]
yes, unless we fixed all locales now :shrug: who knows.

**Comment by rvanlaak** [comment]
Will work on a PR for that. First results: there are over 50 mismatches between id and source.

**Comment by stof** [comment]
I suggest adding a test in the testsuite ensuring the consistency of trans units (but allowing extra ids not present in the `en` file as we merge translation PRs to the oldest maintained branch for easier contributions avoiding to split the PR). this way, the CI would ensure consistency.

**Comment by rvanlaak** [comment]
@ro0NL created PR #42201 with enhancements to the `translation-status` script

**Pull request merged**
