### PR TITLE
Update HtmlDumper.php

### PR DESCRIPTION
**Pull request by zeyad82**
Made the dump search fixed as it's difficult to mange in long page.

| Q             | A
| ------------- | ---
| Branch?       | master for features / 2.8 up to 4.1 for bug fixes 
| Bug fix?      | yes/no
| New feature?  | yes/no 
| BC breaks?    | no     
| Deprecations? | yes/no 
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by ro0NL** [comment]
Also see #28854 where we discussed this. More specifically: https://github.com/symfony/symfony/pull/28854#issuecomment-429605833

**Comment by ro0NL** [comment]
Here's some work to keep the search bar fixed in view, while scrolling. But the JS needs some work still :)

Feel free to take over.. or maybe @ogizanagi can help. Im kinda stuck on this one :) though i got the CSS ok now..

Absolute min width:

image

Variable max width:

image

**Comment by fabpot** [comment]
@zeyad82 Any news?

**Comment by zeyad82** [comment]
@ro0NL  solution seemed more inclusive.

**Pull request closed without merging**
