### PR TITLE
[Form] Deprecate Iterator implementation in forms in favor of IteratorAggregate

### PR DESCRIPTION
**Pull request by Koc**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | https://github.com/symfony/symfony/pull/23633#issuecomment-317244629
| License       | MIT
| Doc PR        | -

New tests will add later

### CODE REVIEW

**Comment by fabpot** [comment]
I don't get this change. Can you explain?

**Comment by ogizanagi** [comment]
This relates to https://github.com/symfony/symfony/pull/23633#issuecomment-317244629.

I don't get why we should do it. #23633 improves static code analysis, which is good to take, but it cannot in any way be an argument for deprecating `\Iterator` implementations of the `FormInterface`. There isn't any real benefit, IMHO it's not worth it.

**Comment by ro0NL** [comment]
It solves `foreach ($form as $child)`, so that IDE's know $child is an instance of FormInterface. As in 4.0 FormInterface::getIterator would have `@return FormInterface[]`.

This is an out-of-the-box alternative to #23633

Agree it may not be worth it... its not like foreaching forms is a common task.

**Comment by Koc** [comment]
Looks like I've implemented @ro0NL suggestion too fast :).

**Pull request closed without merging**
