### PR TITLE
[VarExporter] do not call `unset()` on unknown variables

### LINKED ISSUE #46926: [VarExporter] Warning: Undefined variable `$state`
### Symfony version(s) affected

6.2.0@dev

### Description

On current state of 6.2.0@dev the Varexporter is failing when trying to run doctrine command in our test setup. It try to call unset on a variable which does not exist: https://github.com/symfony/symfony/blob/517530cefc0f6380423c0f839d04151485a76805/src/Symfony/Component/VarExporter/LazyGhostObjectTrait.php#L198.

### How to reproduce

```
git clone git@github.com:sulu/sulu.git
cd sulu
composer config minimum-stability dev
composer update

docker compose up
```

```
DATABASE_URL=mysql://root:ChangeMe@127.0.0.1:3306/sulu_test?serverVersion=8.0 bin/console doctrine:schema:update --dump-sql -vvv
```

Errors with:

```
In LazyGhostObjectTrait.php line 198:

  [ErrorException]
  Warning: Undefined variable $state


Exception trace:
  at /private/tmp/sulu/vendor/symfony/var-exporter/LazyGhostObjectTrait.php:198
 ContainerYpTrYRo\RepositorySchema_3b8f24e->__set() at /private/tmp/sulu/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/RepositorySchema.php:42
```

<details>
<summary>Complete Stack Trace</summary>

```In LazyGhostObjectTrait.php line 198:

  [ErrorException]
  Warning: Undefined variable $state


Exception trace:
  at /private/tmp/sulu/vendor/symfony/var-exporter/LazyGhostObjectTrait.php:198
 ContainerYpTrYRo\RepositorySchema_3b8f24e->__set() at /private/tmp/sulu/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/RepositorySchema.php:42
 Jackalope\Transport\DoctrineDBAL\RepositorySchema->__construct() at /private/tmp/sulu/var/cache/admin/dev/ContainerYpTrYRo/getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaService.php:30
 ContainerYpTrYRo\getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaService::do() at /private/tmp/sulu/var/cache/admin/dev/ContainerYpTrYRo/getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaService.php:22
 ContainerYpTrYRo\getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaService::ContainerYpTrYRo\{closure}() at /private/tmp/sulu/vendor/symfony/var-exporter/Internal/GhostObjectState.php:73
 Symfony\Component\VarExporter\Internal\GhostObjectState->initialize() at /private/tmp/sulu/vendor/symfony/var-exporter/LazyGhostObjectTrait.php:126
 ContainerYpTrYRo\RepositorySchema_3b8f24e->__get() at /private/tmp/sulu/vendor/doctrine/dbal/src/Schema/Schema.php:174
 Doctrine\DBAL\Schema\Schema->getTables() at /private/tmp/sulu/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/RepositorySchema.php:63
 Jackalope\Transport\DoctrineDBAL\RepositorySchema->addToSchema() at /private/tmp/sulu/vendor/doctrine/phpcr-bundle/src/EventListener/JackalopeDoctrineDbalSchemaListener.php:30
 Doctrine\Bundle\PHPCRBundle\EventListener\JackalopeDoctrineDbalSchemaListener->postGenerateSchema() at /private/tmp/sulu/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:66
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /private/tmp/sulu/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:408
 Doctrine\ORM\Tools\SchemaTool->getSchemaFromMetadata() at /private/tmp/sulu/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:938
 Doctrine\ORM\Tools\SchemaTool->getUpdateSchemaSql() at /private/tmp/sulu/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php:79
 Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand->executeSchemaCommand() at /private/tmp/sulu/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:46
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() at /private/tmp/sulu/vendor/doctrine/doctrine-bundle/Command/Proxy/OrmProxyCommand.php:27
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute() at /private/tmp/sulu/vendor/symfony/console/Command/Command.php:308
 Symfony\Component\Console\Command\Command->run() at /private/tmp/sulu/vendor/symfony/console/Application.php:1016
 Symfony\Component\Console\Application->doRunCommand() at /private/tmp/sulu/vendor/symfony/framework-bundle/Console/Application.php:94
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /private/tmp/sulu/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /private/tmp/sulu/vendor/symfony/framework-bundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /private/tmp/sulu/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /private/tmp/sulu/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /private/tmp/sulu/vendor/autoload_runtime.php:29
 require_once() at /private/tmp/sulu/bin/console.php:19
 include() at /private/tmp/sulu/bin/console:4

doctrine:schema:update [--em EM] [--complete] [--dump-sql] [-f|--force]
```

</details>

### Possible Solution

I'm not sure the effect trait `LazyGhostObjectTrait` seems to be unchanged since 9. june, the bug did only appear since this or maybe last week.

### Additional Context

Using `6.1.*@dev` does not have this error.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #46926
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
If this was not caught by the testsuite, it tells me that the testsuite is incomplete. It would be great to add tests covering the broken scenario

**Review by alexander-schranz — APPROVED** [review]
Fixes the issue in sulu. Not sure if the change should also apply to older symfony versions but it did appear in sulu only for with symfony 6.2.

**Comment by xabbuh** [comment]
@alexander-schranz The trait is new and was merged into the `6.2` branch just yesterday.

I am going to look into improving the test suite.

**Comment by alexander-schranz** [comment]
Oh okay. Seems like github did foul me with showing 9. June as last change 🙈 

Bildschirmfoto 2022-07-13 um 12 30 58

Thx for having a look at this!

**Comment by stof** [comment]
@alexander-schranz that's the date of the commit in the PR, not of the merge commit.

**Review by nicolas-grekas — APPROVED** [review]
For the test case, the issue should happen when setting a dynamic property on a lazy variant of stdClass.

**Comment by xabbuh** [comment]
test case added, thanks for the hint Nicolas 👍

**Review by chalasr — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @xabbuh.

**Pull request merged**
