### PR TITLE
[Validator] Fixed grouped composite constraints

### PR DESCRIPTION
**Pull request by HeahDude**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #17675, #25888, #23480
| License       | MIT
| Doc PR        | ~

From Lisbon :). Thanks @stof, @xabbuh for your help to finally fix this old issue.

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
Thanks @HeahDude.

**Comment by backbone87** [comment]
I think this change completely obsoletes the caching. I am not sure, but a constraint that has two grps would now be validated twice, if the both grps are the validation target.

**Comment by xabbuh** [comment]
Most constraints don't extend the `Composite` constraint so are not affected here.

**Comment by backbone87** [comment]
Yes you are right, i was desperately searching for the check for `Composite`s, while its right the line above.

**Comment by conradkdotcom** [comment]
This was a breaking change for us. Our code depended on this bug. The fix should be quick. Nevertheless it is a bit surprising to see this in a patch release.

**Comment by conradkdotcom** [comment]
Thanks for the fix @stof !

Just FYI, this was unfortunately a breaking change for us. Our code depended on this bug. Hopefully the fix should be quick. Nevertheless it is a bit surprising to see this in a patch release.

I think we might have to check every single validation rule that uses collections in our project, because some previously unknown validations might come into action silently, preventing customers from doing things that were previously possible.

**Pull request merged**
