### PR TITLE
[WIP][Messenger][FrameworkBundle] Fix xml configuration of messenger routing

### PR DESCRIPTION
**Pull request by Koc**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Follow up of #31710
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by Koc** [comment]
"feature" and "deprecation" labels added by mistake.

**Comment by nicolas-grekas** [comment]
Tests fail apparently.

**Comment by weaverryan** [comment]
Ping @Koc! Is this one done or almost done? Thx :)

**Comment by Nyholm** [comment]
Friendly ping

**Comment by Koc** [comment]
Fixed by @Nyholm in  #35502 .

BTW, anybody knows, why fixXmlConfig not help in this case?

**Pull request closed without merging**
