### PR TITLE
[EventDispatcher] Simplify RegisterListenerPass

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | n/a

To make it human readable

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Why is that related to the removal of closure proxies?
To me, this is moving the subscriber logic to the pass, which is what I tried to avoid with the current code.

**Comment by chalasr** [comment]
I understand, but the current code is really harder to read to me

**Comment by stof** [comment]
This requires maintaining the implementation of event subscribers twice.
If you actually want to do it, I require you to write tests ensuring that both implementations can never get out of sync. And such tests will be hard to write properly actually (as they need to fail when a new case is added on one side and not on the other, without requiring first to update the synchronization tests, as this would also be forgotten).
Reusing the component implementation of `addSubscriber` was done to avoid the need for such tests.

**Comment by chalasr** [comment]
Let's keep it as is then

**Pull request closed without merging**
