### PR TITLE
debug deprecations

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
see DaveRandom/LibDNS#26

**Comment by fabpot** [comment]
Looks like the package is not maintained anymore. Last change was in 2018.

**Comment by stof** [comment]
Amp uses it as a dependency in their `amphp/dns` package. So if the package is indeed unmaintained (and not just stable), I hope that the Amp team can manage that.

**Comment by kelunik** [comment]
@fabpot I'd call it stable instead, at least for everything we make use of. We'll take care.

**Comment by fabpot** [comment]
@kelunik Thank you for taking care of it, that's much appreciated.

**Comment by kelunik** [comment]
Fixed and released as v2.0.3. 🙂

**Comment by fabpot** [comment]
@kelunik Thank you so much.

**Pull request closed without merging**
