### PR TITLE
[Cache] Mark FilesystemAdapterTrait as internal

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by chalasr** [comment]
👍

Status: reviewed

**Comment by xabbuh** [comment]
Should we document this change in the upgrade file?

**Comment by chalasr** [comment]
@xabbuh the trait has been introduced in 3.2 which is the PR target :)

**Comment by xabbuh** [comment]
Oh indeed, never mind then.

👍

**Pull request merged**
