### PR TITLE
[Form][2.7][ Choice type] fixed groups with empty array.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15634 |
| License | MIT |
| Doc PR | ~ |
- [x] test

### CODE REVIEW

**Comment by velikanov** [comment]
:+1:

**Comment by stof** [comment]
a test should be added first

status: needs work

**Comment by aitboudad** [comment]
@stof done

**Comment by stof** [comment]
:+1: 

Status: reviewed

**Comment by fabpot** [comment]
Thank you @aitboudad.

**Pull request merged**
