### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #31638
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by ro0NL** [comment]
AH :D `Europe/Saratov` is included as of `TZ DB 2017`.

Appveyor runs v2018, and travis v2015. This explains the failures. (cc @mmokhi i figure you're on >=2017 also).

I'll think of way to fix tests, but it's relies very much on environment. Not sure what TZ/version combination to test is best now :/

**Comment by nicolas-grekas** [comment]
But this means the test us not future proof right? As time passes, it will become more and more skipped.

**Comment by ro0NL** [comment]
Eventually yes, im not sure if travis plans TZ updates regularly (looks not :D). For the time being it's sufficient IMHO.

Today, using TZ DB 2019 all timezone IDs  be used with `IntlTimeZone`. So there's no real better fixture.

The weird thing is the expiry date is stilled listed: `https://github.com/unicode-org/icu/blob/c8c3fbca284351ff259dbd7e983ba61f964fd80f/icu4c/source/data/misc/metaZones.txt#L3886-L3892`. Perhaps ICU will update it later in time...

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @ro0NL.

**Pull request merged**
