### PR TITLE
[Debug] Map PHP errors to LogLevel::CRITICAL

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

See https://github.com/Seldaek/monolog#log-levels for reference.

### CODE REVIEW

**Comment by dupuchba** [comment]
From conference to code since yesterday #symfony_live :-).
Can you explain why you changed `LogLevel::ERROR/EMERGENCY` to `LogLevel::CRITICAL` ?
Thx

**Comment by nicolas-grekas** [comment]
Because it fits better the levels definitions IMHO (see the link).

**Comment by GromNaN** [comment]
This is a BC break if someone log only errors with a level > CRITICAL.

**Comment by nicolas-grekas** [comment]
> This is a BC break if someone log only errors with a level > CRITICAL.

Which means nobody :-) Esp. since the feature is new and not documented...

**Pull request closed without merging**
