### PR TITLE
[Form] ignore whitespaces in choicelist optionkeys

### PR DESCRIPTION
**Pull request by hliebe**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24247
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Why 2.8? Shouldn't it be 2.7?

**Comment by hliebe** [comment]
It's a fix for issue https://github.com/symfony/symfony/issues/24247. The reported version is 2.8 so i decided to do it for this version. Before v2.8 ArrayKeyChoiceList was used which is deprecated since v2.8. I could do a patch for 2.7 but i was not really sure.

**Comment by nicolas-grekas** [comment]
@ro0NL any review here, since you commented on the linked issue?

**Comment by ro0NL** [comment]
it's a new feature no? still think we should not implicitly trim choice options =/

**Comment by nicolas-grekas** [comment]
@ro0NL agreed, we should not trim model data.

What bugs me is : why are input *keys* trimmed in the first place? I understand why values are trimmed by default, but keys, it's wrong. Isn't that the root issue?

**Comment by ro0NL** [comment]
>  why are input keys trimmed in the first place?

Que? That's exactly what's not happening right?

```
The name "foo " contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":").
```

(contains a space)

Am i missing a trim call?

DX-wise what could be done is resolve a default `trim=true|false` option for the choice type. If we know options contains spaces we should set trim=false i guess.

**Comment by nicolas-grekas** [comment]
If we need to trim the *model*, it means the *user input* keys has been trimmed before. Why? That's what I mean.

**Comment by ro0NL** [comment]
Ah right.. isnt the selected choice HTML wise the submitted _value_? Thus trimmed depending on trim=true|false.

**Comment by ro0NL** [comment]
So.. setting trim=false by default for choicetype would be sufficient actually?

**Comment by nicolas-grekas** [comment]
@ro0NL looks like so!

**Comment by nicolas-grekas** [comment]
@ro0NL or @hliebe up to do the PR? (setting trim=false on choicetype)

**Comment by nicolas-grekas** [comment]
@HeahDude would be great if you could submit a PR doing so.

**Comment by HeahDude** [comment]
See #26932.

**Pull request closed without merging**
