### PR TITLE
Sync translations across all languages

### PR DESCRIPTION
**Pull request by carsonbot**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

We just added new English translations. This PR make sure to add them to all other languages. 

-------

This PR was automatically generated by the Carsonbot. It ran the following command: 

```bash
php .github/sync-translations.php
```

You can find the workflow [here](https://github.com/symfony-tools/symfony-translation-checker/blob/master/.github/workflows/sync-sf-translations.yml).

### CODE REVIEW

**Comment by Nyholm** [comment]
I added a workflow to carsonbot to open this PR. I see that I have to modify the `.github/sync-translations.php` to allow header notes. 

FYI @nicolas-grekas

**Comment by Nyholm** [comment]
Blocked by https://github.com/symfony/symfony/pull/53853

**Comment by Nyholm** [comment]
Now when https://github.com/symfony/symfony/pull/53853 is merged, this PR will shorty be updated (in 5h). The diff will be a minor indentation fix.

**Comment by 94noni** [comment]
> Hey!
> I see that this is your first PR. That is great! Welcome!

Capture d’écran 2024-02-08 à 09 15 20

**Review by Nyholm — APPROVED** [review]

**Review by yceruto — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you @carsonbot.

**Pull request merged**
