### PR TITLE
[3.0][Form] Removed depracted events PRE_BIND, BIND and POST_BIND

### PR DESCRIPTION
**Pull request by saro0h**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by saro0h** [comment]
Changes have been made.

**Comment by fabpot** [comment]
Can you rebase to re-run the tests?

**Comment by saro0h** [comment]
Done. The tests do not pass because of that: https://travis-ci.org/symfony/symfony/jobs/45787598#L2208

**Comment by fabpot** [comment]
Thank you @saro0h.

**Pull request merged**
