### PR TITLE
[WebProfilerBundle] fix wrong variable for profiler counting ajax requests

### PR DESCRIPTION
**Pull request by nicolaemarin**
| Q             | A
| ------------- | ---
| Branch?       |  2.7 
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #26364 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Symfony WebProfiler base js change variable tbodies to tbody for counting Ajax Requests.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
ping @xkobal @Simperfit for double checking

**Comment by xkobal** [comment]
That was `tbodies` before my fix but after reading another time the code, it seems that `tbody` is the correct object. @Simperfit must have the last word.

**Comment by Simperfit** [comment]
Let me take this time to test this. But I think this is right too.

I'll test it today.

**Comment by n3o77** [comment]
@nicolas-grekas sorry for hijacking this PR. As i'm having trouble with the code affected in this PR it might make sense to coordinate this here before I create a PR.

@Simperfit your code caused some problems for me too. I'm loading a angular2 app which seems to make ajax requests before the `tbodies.rows` is defined ( error below ). I just fixed it with [surrounding your code with an if to check for that](https://github.com/n3o77/symfony/commit/c8c257a2a5624be07e4a76f04656c12e0e160055).

Unfortunately I wasn't able to create a minimum code version to reproduce this. Maybe you have an idea under which circumstances exactly this could be the case.

```
Uncaught TypeError: Cannot read property 'count' of undefined
    at Object.renderAjaxRequests (order_now:267)
    at Sfjs.load.maxTries (order_now:267)
    at order_now:267
    at XMLHttpRequest.xhr.onreadystatechange (order_now:267)
    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (vendor.bundle.js?v=1:5630)
    at ZoneDelegate.invokeTask (vendor.bundle.js?v=1:5063)
    at Zone.runTask (vendor.bundle.js?v=1:4871)
    at ZoneTask.invokeTask [as invoke] (vendor.bundle.js?v=1:5131)
    at invokeTask (vendor.bundle.js?v=1:5871)
    at XMLHttpRequest.globalZoneAwareCallback (vendor.bundle.js?v=1:5883)
```
(order_now is the pagename and references to the profiler code)

**Comment by nicolas-grekas** [comment]
@n3o77 can you test the code in this PR and report if it fixes the issue for you?

**Comment by n3o77** [comment]
@nicolas-grekas yes, fixes the problem for me. Thank you @marinnicolae .

**Review by nicolas-grekas — APPROVED** [review]

**Comment by n3o77** [comment]
Same problem is in v2.8

**Comment by tanasecosminromeo** [comment]
@n3o77 Yep, problem is on v2.8 also - Fix works good. Thank you @marinnicolae

**Comment by nicolas-grekas** [comment]
Thank you @marinnicolae.

**Comment by nicolas-grekas** [comment]
Can anybody please check if the code on 3.4 works as expected?

**Comment by marinnicolae** [comment]
@nicolas-grekas Just tested on v3.4.5 and AjaxRequests does not appear cuz there are not appending in profiler bar. Will try to create a PR with the fix on 3.4 branch soon.

**Comment by nicolas-grekas** [comment]
@marinnicolae please note that branch 3.4 already has some fixes, so might be just fixed already, you'll tell :)

**Pull request closed without merging**
