### PR TITLE
Bump Symfony 5.0 to PHP 7.2

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Not ready yet.

7.2 because it has all we need for the next two years (7.3 doesn't provide anything we absolutely need, and 7.4 is not even released so cannot be considered yet.)

7.2.9 because of https://tracker.debian.org/pkg/php7.2

Needs:
- [x] https://github.com/symfony/security-acl/pull/48
- [x] https://github.com/doctrine/orm/pull/7723
- [x] https://github.com/doctrine/DoctrineBundle/pull/975
- [x] https://github.com/doctrine/DoctrineCacheBundle/pull/158
- [x] https://github.com/symfony/symfony/pull/31657

### CODE REVIEW

**Comment by vudaltsov** [comment]
Why not `7.3`?

**Comment by nicolas-grekas** [comment]
The question is more: why 7.3?
7.2 is better for adoption.

**Comment by ciaranmcnulty** [comment]
Typed private properties would be a good driver for 7.3 I think?

**Comment by nicolas-grekas** [comment]
@ciaranmcnulty don't you talk about 7.4? See https://www.php.net/releases/7_3_0.php

**Comment by jmsche** [comment]
I'd be in favor of PHP 7.3 too as 7.2 active support ends on November, 30 2019, so at the same time Symfony 5.0 will be released.

**Comment by kunicmarko20** [comment]
Since 7.4 will happen at the same time as sf5, it probably too early to make that a minimal?

**Comment by nicolas-grekas** [comment]
7.2 is all we need to start working on Symfony 5.0.

**Comment by ciaranmcnulty** [comment]
@nicolas-grekas you are of course right. I forgot 7.3 had so few compelling features (some nice stuff but nothing that would require it over 7.2)

**Comment by vudaltsov** [comment]
Okay, I agree that as a **minimum** version `7.2` is good.

**Comment by lyrixx** [comment]
I'm for 7.2 too. 7.3 does not bring so much nice features. 7.2 seems better for adoption.

**Comment by Tobion** [comment]
👍 7.2 for now. Ref. #24283
Maybe bump to 7.4 later if released in time. Then we would use the latest PHP version like done with SF 4.

**Review by alcaeus — APPROVED** [review]
7.2 is a good choice for now: it allows strict typing, allows for parameter type widening in implementations (which is necessary during a migration to strict typing) and it has been widely adopted.

7.3 on the other hand lacks clear features that make it stand out, and 7.4 will not be released in time to be considered at all.

**Pull request merged**
