### PR TITLE
[Form] Change datetime to datetime-local for HTML5 datetime input

### PR DESCRIPTION
**Pull request by pierredup**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | Unknown
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #24307
| License       | MIT
| Doc PR        | N/A

Change the input type from datetime to datetime-local for HTML5 date input (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Is browser support good enough?
https://caniuse.com/#search=datetime-local

**Comment by ogizanagi** [comment]
Anyway, isn't it a BC break? JS apps may rely on `type="datetime"`. Not sure it is worth it.

**Comment by stof** [comment]
`type="datetime"` is supported by exactly 0 browser out there, meaning checking the type DOM property gives you `text` due to the type fallback.
And the `datetime` type is removed from the HTML spec.

However, the HTML5_FORMAT constant has the timezone included in the format. So it should be updated for `datetime-local` to remove the timezone part.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by xabbuh** [comment]
Is this enough? I mean is the format in which data is sent by browsers the same as it was meant to with the old `datetime` type?

**Comment by Tobion** [comment]
From my short test, it seems Chrome submits the `datetime-local` without a timezone. So @stof would be right that `\Symfony\Component\Form\Extension\Core\Type\DateTimeType::HTML5_FORMAT` needs to be changed.

**Review by Tobion — CHANGES_REQUESTED** [review]
html5 constant and description

**Comment by pierredup** [comment]
Would it not be considered a BC break to change the value of a constant?

**Comment by simPod** [comment]
What's the status of this? Can I help?

**Comment by nicolas-grekas** [comment]
@pierredup let's do the change as requested by @Tobion /@stof

**Comment by nicolas-grekas** [comment]
@Tobion aren't we ready here?

**Review by Tobion — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @pierredup.

**Pull request merged**
