### PR TITLE
[FrameworkBundle] Allow custom services for validator mapping cache.

### PR DESCRIPTION
**Pull request by jakzal**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #12803 |
| License | MIT |
| Doc PR | - |
#9892 introduced `DoctrineCache`, but it's not really used by the FrameworkBundle. This was overlooked, therefore I think it should go into 2.5.

This PR will let us to configure a service id, instead of a driver name. The only exception is apc, which is converted to `validator.mapping.cache.apc` to keep BC.

Examples:

``` yaml
framework:
    validation:
        cache: apc # converted to validator.mapping.cache.apc
```

``` yaml
framework:
    validation:
        cache: my_custom_cache_service
```

It would be nice to be able to provide a doctrine service id, instead of `CacheInterface` implementation. It could be automatically decorated with `DoctrineCache`:

``` yaml
framework:
    validation:
        cache:
            doctrine: my_doctrine_cache_service # could be provided by DoctrineCacheBundle
```

I'll work on it next.

### CODE REVIEW

**Comment by cmodijk** [comment]
@jakzal Did you ever get to implement the doctrine decorator?

**Comment by jakzal** [comment]
@cmodijk no, but all you have to do in your own project is to register a new caching service:

```xml
        <service id="my_validator_mapping_cache" class="Symfony\Component\Validator\Mapping\Cache\DoctrineCache" public="false">
            <argument type="service">
                <service class="Doctrine\Common\Cache\ApcCache">
                    <call method="setNamespace">
                        <argument>%validator.mapping.cache.prefix%</argument>
                    </call>
                </service>
            </argument>
        </service>
```


and tell validator to use it:

```yaml
framework:
    validation:
        cache: my_validator_mapping_cache
```

**Comment by cmodijk** [comment]
Hmm yeah but it would be nice to directly give a doctrine cache service and that the wrapping is done by Symfony because of the fact that you have the https://github.com/doctrine/DoctrineCacheBundle that generates these service id's for you. Know you need to create your own service just to wrap around the cache. With the possibility to directly inject the doctrine cache service id you don't need anything extra.

**Comment by pwm** [comment]
Hi, is there a way to do this using Redis?

**Comment by jakzal** [comment]
@pwm yes, see the supported drivers here: https://github.com/doctrine/cache/tree/master/lib/Doctrine/Common/Cache

**Pull request merged**
