### PR TITLE
also clean away the NO_AUTO_CACHE_CONTROL_HEADER if we have no session

### PR DESCRIPTION
**Pull request by dbu**
| Q             | A
| ------------- | ---
| Branch?       | 4.1 (feature added in this branch)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

This header is not supposed to ever be exposed to clients of the application, but a hack to transfer information within the symfony application. This bugfix makes it so that we also remove the header when no session is started and thus no decision has to be taken whether to overwrite the caching instructions or not.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Nice. Would it possible to cover this by a test case?

**Comment by dbu** [comment]
good point with the tests. did need to move getting the request up... i think its ok to expand on the existing test and make it do a bit more, rather than create a separate test. okay like this?

**Review by nicolas-grekas — APPROVED** [review]
OK for me, thanks!

**Review by dmaicher — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @dbu.

**Pull request merged**
