### PR TITLE
Release v2.3.42

### PR DESCRIPTION
**Pull request by fabpot**
Changes since last release: https://github.com/symfony/symfony/compare/v2.3.41...7143b29

**Changelog**
- bug #18893 [DependencyInjection] Skip deep reference check for 'service_container' (@RobertMe)
- bug #18812 Catch \Throwable (@fprochazka)
- bug #18821 [Form] Removed UTC specification with timestamp (@francisbesset)
- bug #18861 Fix for #18843 (@inso)
- bug #18907 [Routing] Fix the annotation loader taking a class constant as a beginning of a class name (@jakzal, @nicolas-grekas)
- bug #18864 [Console][DX] Fixed ambiguous error message when using a duplicate option shortcut (@peterrehm)
- bug #18844 [Yaml] fix exception contexts (@xabbuh)
- bug #18840 [Yaml] properly handle unindented collections (@xabbuh)
- bug #18839 People - person singularization (@Keeo)
- bug #18828 [Yaml] chomp newlines only at the end of YAML documents (@xabbuh)
- bug #18635 [Console] Prevent fatal error when calling Command::getHelper without helperSet (@chalasr)
- bug #18761  [Form] Modified iterator_to_array's 2nd parameter to false in ViolationMapper (@issei-m)

### CODE REVIEW

**Comment by aivus** [comment]
It seems #18908 reverted but exists in your list.

**Comment by sstok** [comment]
@aivus It's not a problem, I checked and there are no security problems introduced with the change.

**Comment by aivus** [comment]
@sstok yeah, but this fix doesn't included to release.

**Comment by nicolas-grekas** [comment]
changelog updated in PR description

**Comment by sstok** [comment]
Oh OK 😄

**Pull request merged**
