### PR TITLE
`OptionsResolver` add default options accessors

### PR DESCRIPTION
**Pull request by PululuK**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | N/A 
| License       | MIT
| Doc PR        | N/A 

Add possibility to access de default options definition

### CODE REVIEW

**Comment by ro0NL** [comment]
IIUC `OptionsResolverIntrospector` already allows to access it

**Comment by PululuK** [comment]
> IIUC `OptionsResolverIntrospector` already allows to access it

Doc please ?

**Comment by OskarStark** [comment]
If there is no documentation right now, you can check the PR which introduces this feature. Afterwards a docs contribution would be appreciated 🙌

Thanks

**Comment by PululuK** [comment]
@OskarStark @ro0NL  can you please check ?
https://github.com/symfony/symfony-docs/pull/18571

**Comment by yceruto** [comment]
Closing here as it's a documentation issue instead. Thank you @PululuK!

**Pull request closed without merging**
