### PR TITLE
- add default value to getNode()

### PR DESCRIPTION
**Pull request by alejgr**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | no
| Fixed tickets | #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Review by stof — CHANGES_REQUESTED** [review]
this mixed default is wrong, as it breaks the signature of the method (which must return a DomElement or null.

So what is your use case ?

**Comment by alejgarciarodriguez** [comment]
If I use text() function, and node is null, i got an InvalidArgumentException.
So the way I use this to get a default value it its null (similar to Request/HttpFoundtaion, $request->get()) is:
`$value = ($filter = $record->filter('myfilter'))->count() === 0 ? 'n\a' : $filter->getNode(0)->nodeValue;
`
I am not sure if there is a better way to handle this. What about to add a default parameter in text() function?

**Comment by nicolas-grekas** [comment]
You should use the `??` operator instead: `$this->getNode('foo') ?? $default`;

**Comment by nicolas-grekas** [comment]
Thanks for the PR anyway :)

**Pull request closed without merging**
