### PR TITLE
[Yaml] fix parsing negative octal numbers

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
while working on #34807 I realised that we actually do not correctly parse negative octal numbers

**Comment by stof** [comment]
Based on https://yaml.org/spec/1.2/spec.html#id2805071, I don't think negative octal actually make sense in YAML

**Comment by stof** [comment]
OK, according to https://yaml.org/type/int.html, they do make sense in YAML 1.1 (and this octal without `0o` is the 1.1 octal syntax). I think we need to clarify which YAML spec we follow in the component (I think the current answer is "a mix of 1.1 and 1.2, being compliant with none of the 2 due to the mix")

**Comment by xabbuh** [comment]
In #34813 I am working on a deprecation. Looks like I need to improve that a bit so that in the future we will only support the `0o` prefix.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
