### PR TITLE
[Serializer] Change >=1.7.0 version constraint to >=1.8.0 for package…

### PR DESCRIPTION
**Pull request by ellisgl**
… phpdocumentor/type-resolver, as it now has a stable 1.7.* release.

| Q             | A
| ------------- | ---
| Branch?       | 6.2 for bug fixes 
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

Change >=1.7.0 version constraint to >=1.8.0 for package phpdocumentor/type-resolver, as it now has a stable 1.7.* release. If you don't restrict it 1.7.*, it will try to install the develop branch instead.

Additionally (see https://symfony.com/releases):
 - Always add tests and ensure they pass.
 - Bug fixes must be submitted against the lowest maintained branch where they apply
   (lowest branches are regularly merged to upper ones so they get the fixes too).
 - Features and deprecations must be submitted against the latest branch.
 - For new features, provide some code snippets to help understand usage.
 - Changelog entry should follow https://symfony.com/doc/current/contributing/code/conventions.html#writing-a-changelog-entry
 - Never break backward compatibility (see https://symfony.com/bc).
-->

### CODE REVIEW

**Comment by stof** [comment]
There is no reason to forbid 1.8+. As they follow semver, a 1.8 version is fine to be used as well once available (whether 1.7.x stable releases or 1.8.x-dev is used depends on the minimum-stability you configure).

So -1 from me.

**Comment by ellisgl** [comment]
Going to re do this from scratch, removing the upper restriction all together.

**Comment by ellisgl** [comment]
6.2 branch Has it correct, but 6.2.7 (down to 6.2.5?) have the limitation --- not sure how I can fix that, since it would look like no change happened against 6.2. So is serializer 6.2.0 newer than 6.2.7?

**Comment by stof** [comment]
No. It is just that the 6.2 branch contains the change done in https://github.com/symfony/symfony/pull/49727, which will be part of the 6.2.8 release.

**Pull request closed without merging**
