### PR TITLE
[SECURITY] AbstractAuthenticationListener.php error instead info.

### PR DESCRIPTION
**Pull request by Warxcell**
```
[2018-09-13 20:43:38] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): An exception occurred while executing
 ...
 Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.phone' in 'field list' at
```

Definitely I think this is NOT info, but error.
And since it's info, it's not logged in production because of `fingers_crossed` with `action_level: error` - so to actually see the real error behind `Authentication request could not be processed due to a system problem.` I had to debug on production. Very bad practice IMHO.

| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no I think
| Deprecations? | no
| Tests pass?   | yes 
| Fixed tickets | ...
| License       | MIT

### CODE REVIEW

**Comment by jvasseur** [comment]
This means all failed authentication attempts will now be logged as error which is not right either. We need to differentiate between errors in the authentication process and failed authentication attempts to determine the logging level here.

**Comment by Warxcell** [comment]
@jvasseur thank you for your response.

How do we do that? What are exceptions for non-errors?

**Comment by jvasseur** [comment]
@Warxcell checking if the exception is an instance of `AuthenticationServiceException` could be a good solution yes.

**Comment by Warxcell** [comment]
What I would do is in case of `AuthenticationServiceException` just rethrow error - so it would result in 500 Error on page, like everywhere else.

**Comment by iltar** [comment]
I've done a quick search where this exception is being used.

### `UserAuthenticationProvider`
This is extended by the `LdapBindAuthenticationprovider` and `DaoAuthenticationProvider`. While being an `AuthenticationServiceException`, this would in the future be caught by return types as it specifies `@return UserInterface` on `retrieveUser`.

One small note for this, the `Dao` is something that should be removed in my opinion and the Ldap variant should be re-made in Guard, but that's another issue.

Conclusion: This one should trigger an ERROR level

### `DaoAuthenticationProvider`
Throws it twice, once when the return contract is broken (return is not a `UserInteface`) and once when a generic exception is thrown. Both of them are triggered when something is broken as the generic exception catch is superseded by a catch on `UsernameNotFoundException`.

Conclusion: Both should trigger an ERROR level 

### `DigestAuthenticationListener`
This implementation specifies that it's an ERROR level: _"Digest User provider returned null, which is an interface contract violation"_

Conclusion: This one should trigger an ERROR level
### `UnsupportedUserException`
 - Caught in the `ChainUserProvider`
 - Caught in the `ContextListener`
 - Caught in the `AbstractRememberMeServices`

Conclusion: these are often implemented by the end-user, but we cannot guarantee they are a 500 error. According to the class itself:
> This exception is thrown when an account is reloaded from a provider which doesn't support the passed implementation of UserInterface.

Which I already see being abused here. My suggestion would be to follow the class doc and make it an ERROR as well.


### Final conclusion
This particular exception _should_ in my opinion trigger an ERROR in the logs. However, it should _not_ do this for the `Authentication Failed` log. That means the logging has to be adapted in a way where both can be logged separately. Perhaps this can be done via `getParent()` on the Exception?

**Comment by iltar** [comment]
I can help with a patch (reviewing), but I do not have time myself to do this in-between at the moment

**Comment by Warxcell** [comment]
So what should be done? If it's error log in app channel, if not - log in security channel?

**Comment by Warxcell** [comment]
@iltar how can this be done? sending 2 different loggers with tag `monolog.logger` ?

**Comment by fabpot** [comment]
@linaori Might be a great PR for the upcoming hackaton :)

**Comment by linaori** [comment]
Do we have a label for the hackathon? If not, it might be nice to tag a bunch of issues so we can plow through them.

**Comment by javiereguiluz** [comment]
@linaori yes, we've created a special label for that event:

image

**Comment by curry684** [comment]
@linaori I've just read the entire discussion and your well research arguments, and I'm now thinking why we're not raising the log level to ERROR as a whole as indeed our existing implementations act like that and the class is documented to work like that. I don't see the INFO case any more other than to maintain some kind of fake B/C with existing applications and bundles that somehow count on it being info. 

To be honest, I don't consider that a B/C breakage as the docs were there to indicate it always should have been an error.

**Comment by nicolas-grekas** [comment]
(rebase needed)

**Comment by Fl0ux** [comment]
Something seems to wrong with this commit. Now every failed login attempts are logged as errors.

`[2019-12-05T11:47:47.157808+01:00] security.ERROR: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /home/foulques/PhpstormProjects/MonAvisCitoyenV2/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:68)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): User \"18691mac@yopmail.com\" not found. at /home/foulques/PhpstormProjects/MonAvisCitoyenV2/vendor/symfony/doctrine-bridge/Security/User/EntityUserProvider.php:65)"} []`

... and every time I receive a mail to warn me about this...

**Comment by Warxcell** [comment]
@Fl0ux it's not because of that. As you can see - it's closed, not merged.

**Comment by nicolas-grekas** [comment]
It's merged in https://github.com/symfony/symfony/commit/87a6f0440931846f02a9bb4b17b26a00d76a83d9 actually.
But commenting on a closed PR will likely be ignored as there is no way to track them.

**Comment by Fl0ux** [comment]
Ok, I will create a new bug report in this case.

**Comment by Warxcell** [comment]
@nicolas-grekas but it's slightly different from my PR. I excluded these exceptions. Only system errors

**Pull request closed without merging**
