### PR TITLE
Add "dump to server" function

### PR DESCRIPTION
**Pull request by Chi-teck**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

This PR adds new `dumps` function which can be used to send variables to VarDumper server.

### CODE REVIEW

**Comment by stof** [comment]
-1 for this. `dump` is already sending the dump to the server when the VarDumper is configured properly.
and this function is reconfiguring the component, meaning that any subsequent call to `dump` would then go to the server rather than to the previously configured handler. That's quite bad (it breaks the WebprofilerBundle integration for instance).

So -1 from me.

**Comment by Chi-teck** [comment]
Well, I did not consider that case.
What is the proper way to make use of dumper server when it is used outside Symfony framerwork?

**Comment by stof** [comment]
Well, configure the call to `VarDumper::setHandler()` in some places of your project (in the boostrapping code, so that it is executed before you call `dump`). Symfony is doing it in `DebugBundle::boot` for instance (but only in debug mode, to avoid spending time initializing the VarDumper in prod)

**Comment by stof** [comment]
I still don't see the need to have a helper doing both a custom config of the handler (ignoring any existing config) and dumping. This only makes the API of the component more confusing (people will need to understand the difference between `dump` and `dumps`, and `dump` might also be using the dump server if configured this way)

**Comment by Chi-teck** [comment]
Can we tweak default handler to use Server dumper conditionally by setting some environment variable for instance?

**Comment by Chi-teck** [comment]
I think I figured out an easy way to use ServerDumper on non Symfony projects.
```
<?php

use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\ServerDumper;

/**
 * Dumps information about a variable to a server.
 *
 * @param mixed $var
 *  The variable you want to dump.
 */
function dumps($var)
{
    $cloner = new VarCloner();
    $dumper = new ServerDumper($_SERVER['VAR_DUMPER_SERVER'] ?? '127.0.0.1:9912');
    $dumper->dump($cloner->cloneVar($var));
}
```
Thanks for the feedback.

**Pull request closed without merging**
