### PR TITLE
[MonologBridge] Fix compatibility of ServerLogHandler with Monolog 2

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 5.0
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | #34520
| License       | MIT
| Doc PR        | NA

This is an alternative to #34521 that keep compatibility with "processors" and "formaters".

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
If we can prevent the BC break, it's better, isn't it?

**Comment by jderusse** [comment]
Done

**Review by nicolas-grekas — APPROVED** [review]

**Comment by xabbuh** [comment]
I fail to see how this prevents the BC break when Monolog 2 is installed. In that case we still add the return type declaration.

**Comment by jderusse** [comment]
In Monolog 2, the interfaces `ProcessableHandlerInterface` and `FormattableHandlerInterface have been removed from `AbstractHandler`. 

If you don't ilmplement them, things won't behave as expected

Your PR has a bug, as the method `formatRecord` call `getFormater` which does not exists anymore https://github.com/symfony/symfony/blob/0a2a7fe46d7aaca231a163642e52728e3d384c75/src/Symfony/Bridge/Monolog/Handler/ServerLogHandler.php#L112

the BC break is coming from `Monolog: 2`. if one stays at Monolog 1, there is no PB break
if one moves to 2, we follow `Monolog2` API.

**Review by xabbuh — APPROVED** [review]

**Comment by xabbuh** [comment]
sounds reasonable 👍

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.

**Pull request merged**
