### PR TITLE
[PropertyInfo] Exclude static methods form properties guessing

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | 2.8
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by stof** [comment]
👍

**Comment by fabpot** [comment]
Thank you @dunglas.

**Comment by teohhanhui** [comment]
Again like in api-platform/core#914, I'm curious about the rationale behind this... Since there's no explanation given.

**Comment by dunglas** [comment]
@teohhanhui if you have an entity like the following:

```php
<?php

// src/AppBundle/Entity/Book.php

use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource(attributes={"validation_groups"={Book::class, "validationGroups"}})
 */
class Book
{
    /**
     * Return dynamic validation groups.
     *
     * @param self $book Contains the instance of Book to validate.
     *
     * @return string[]
     */
    public static function getValidationGroups(self $book)
    {
        return ['a'];
    }

    /**
     * @Assert\NotBlank(groups={"a"})
     */
    private $name;

    /**
     * @Assert\NotNull(groups={"b"})
     */
    private $author;

    // ...
}
```

The extractor will include "validationGroups" in the list of properties of the entity `Book`. It's definitely a bug, static methods should be excluded.

**Comment by teohhanhui** [comment]
Static properties / methods could be used for a variety of reasons (I
believe there are valid use cases where properties are represented as
such). I don't see why PropertyInfo should make the decision for the user
to exclude them.

**Pull request merged**
