### PR TITLE
[Translation] trans, add support of domain in $id message

### PR DESCRIPTION
**Pull request by wtorsi**
| Q             | A
| ------------- | ---
| Branch?       | master for features
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | #37743 
| License       | MIT
| Doc PR        | 

Add support of domain in id message while translating

### CODE REVIEW

**Review by YaFou — CHANGES_REQUESTED** [review]
:+1: Can you add a test for this feature?

**Comment by wtorsi** [comment]
@YaFou sure, done

**Review by YaFou — APPROVED** [review]
Good job @wtorsi! And great feature!

**Comment by xabbuh** [comment]
This looks like a BC break to me as it will break most existing translations that contain the `@` character. The only viable BC solution that I see would be to create a decorator which contains this logic and that would be an opt-in feature.

**Comment by YaFou** [comment]
> This looks like a BC break to me as it will break most existing translations that contain the `@` character. The only viable BC solution that I see would be to create a decorator which contains this logic and that would be an opt-in feature.

Good point. A solution may be to add an argument to the `Translator` class which controls this option. Also this feature can be applied in version 6 generally which will be a breaking change.

**Comment by wtorsi** [comment]
Just found that `DataCollectorTranslator` will be broken after this pull request. 
I think It's a good idea, but it needs a little bit more work and considerations

**Comment by ro0NL** [comment]
Shouldnt we prefer the approach in https://github.com/symfony/symfony/pull/37670?

**Comment by wtorsi** [comment]
I prefer the approach of translatable objects in #37670 , but my idea is to encode domain in message ID itself, because in my opinion it is easier to store such ids in database

**Comment by fabpot** [comment]
I'm against this change. First, it's a BC break, then, it looks a bit hacky, it's also yet another way to do something we can already do, and last, it does not work well when you are not using translation strings: `$this->translator->trans('This is a message to translate@messages', $params)`.

Thanks for proposing.

**Pull request closed without merging**
