### PR TITLE
Update HTTP statuses list

### PR DESCRIPTION
**Pull request by dasmfm**
| Q | A |
| --- | --- |
| Branch? | 2.3 |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by OskarStark** [comment]
LGTM 👍 , but i think the merge should be applied to older maintained branches too

**Comment by javiereguiluz** [comment]
The `421` status code is part of HTTP2 standard. Should we include it?

**Comment by OskarStark** [comment]
If we support HTTP2, then yes

**Comment by nicolas-grekas** [comment]
:+1: for 2.3

**Comment by javiereguiluz** [comment]
@nicolas-grekas is it OK to add HTTP2 status codes even if we don't support the HTTP2 protocol?

**Comment by nicolas-grekas** [comment]
But Symfony can already by put behind an HTTP2 server and thus may of use already use it in this context, and we should support it. Maybe a new feature, I don't know what others think. Always hard to know the limit :)

**Comment by stof** [comment]
@javiereguiluz as far as Symfony is concerned, there is no new protocol here. PHP-FPM talks the FastCGI protocol anyway, not the HTTP one.

So I'm also :+1: for adding this (in 3.1)

**Comment by javiereguiluz** [comment]
@stof OK then. Thanks!  I agree with Nico for merging this in 2.3.

**Comment by fabpot** [comment]
Other changes to the HTTP status list have always been merged in 2.3, so I think we should do the same here.

**Comment by stof** [comment]
then OK for 2.3

**Comment by xabbuh** [comment]
:+1:

**Comment by dunglas** [comment]
👍

**Comment by fabpot** [comment]
Thank you @dasmfm.

**Pull request closed without merging**
