### PR TITLE
[Form] Fix regression on Collection type

### PR DESCRIPTION
**Pull request by hason**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

A regression was introduced in #17044.

### CODE REVIEW

**Comment by Tobion** [comment]
:+1: 

Status: Reviewed

**Comment by xabbuh** [comment]
:+1:

**Comment by hhamon** [comment]
I confirm I had the same issue!

**Comment by nicolas-grekas** [comment]
Thank you @hason.

**Pull request merged**
