### PR TITLE
Clear the opcache for the `require` env processor

### PR DESCRIPTION
**Pull request by mpdude**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets |   
| License       | MIT
| Doc PR        | 

I've noticed the `ConfigCache` classes take care of this as well. I guess it could make sense if you have the opcache configured not to validate timestamps (performance gain in production) but need to be able to update files with configuration data at runtime.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
If I understand correctly, this means this file would never be read from the cache?
This an absolute no-go: the way opcache works is "append-only" and "reset once filled".
Merging this basically means the memory of opcache will be emptied periodically.
Or did I miss something?

**Comment by jvasseur** [comment]
I wondered the same thing (about this filling the opcache with invalid entries) so I tested it. In fact it's fine because `opcache_invalidate` only invalidate the cache if the file changed since last read (unless you pas `true` as its argument) so it would not fill your opcache.

But i'm still not sure if it's a good idea to merge this, it is more the responsibility of the process modifying the file to reset the opcache instead of the one reading it.

**Comment by mpdude** [comment]
My assumption was that this only forces opcache validation (timestamp check?) for this particular file?

**Comment by jvasseur** [comment]
@mpdude it does, but invalid entries are not removed from the opcache, they are just marked as invalid and once the opcache is filled with to many invalid entries it trigger a full opcache restart that empty the cache completely.

**Comment by nicolas-grekas** [comment]
This doesn't make much sense to me as this forces a check on 100% of requests. (`ConfigCache` does this on write and on a dev-only code-path).

Note also that disabling `opcache.validate_timestamps` is not a good practice - it doesn'timprove performance, because the checks are done through the realpath-cache, which save the IO part.

:-1: thanks for proposing.

**Comment by mpdude** [comment]
I'm fine with closing this. Yet, I'd like to make sure I fully understand your objections.

First, `opcache_invalidate()` has a misleading name. It does not (necessarily) forcefully invalidate the script, but "the script will only be invalidated if the modification time of the script is newer than the cached opcodes" (https://php.net/opcache_invalidate).

So my assumption was that with this change we're not worse off than otherwise when `opcache.validate_timestamps` is turned on. We just force a timestamp validation for this particular file, even if timestamp validations are turned off in general.

Second, turning off `opcache.validate_timestamps` is a [recommended Symfony performance measure](https://symfony.com/doc/current/performance.html#performance-dont-check-timestamps). 

@nicolas-grekas Are you sure the `realpath_cache` can fully compensate this? Even with a cache in place, not having to check the mtime in the first place should be even better? Would you recommend changing the performance tip?

**Comment by nicolas-grekas** [comment]
Yes I would :)

**Comment by nicolas-grekas** [comment]
Your description is correct. The last implicit objection I have is that there is already a native mechanism here and we'd better not derivate from it as that means added maintainance / increased suprise effect.

**Comment by mpdude** [comment]
Do you have numbers/blog posts/other references I can use when opening a docs PR to change this? I guess people will ask for that... ;-)

**Comment by nicolas-grekas** [comment]
Hmm not really - this entry in the PHP doc is the starting hint: https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.enable-file-override

**Comment by nicolas-grekas** [comment]
Oh, and http://blog.jpauli.tech/2015-03-05-opcache-html/

**Pull request closed without merging**
