### PR TITLE
[HttpKernel] Allow `Kernel::getLogDir()` to return the empty string when there is no log dir

### LINKED ISSUE #44579: [RFC] Make Log dir nullable
### Description

In context of containers - one of best practices is to write logs in stdout and stderr, rather than in files. 
unfortunately - log dir is required - even if not used.

Proposal is to either add new interface like `LoggableKernel` which requires `getLogDir` or make `getLogDir` nullable. In both cases: disable checks on logs dir.

### Example

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #44579
| License       | MIT
| Doc PR        | -

My proposal instead of #45579, for discussion.

### CODE REVIEW

**Comment by OskarStark** [comment]
You reference the same issue in your last sentence in the PR header 🧐

**Comment by OskarStark** [comment]
Did you mean #45579 instead?

**Comment by GromNaN** [comment]
We should be careful of side effects. Empty string means "current directory" (try `realpath('')`) or be the root of the filesystem (`%kernel.log_dir%/prod.log` becomes `/prod.log` and could be created by root user).

If some bundle uses this path to update the files (remove, rotate ...) and the app have an empty log dir, that would lead to weird side effects.

**Comment by derrabus** [comment]
I don't feel comfortable using the empty string as magic value. If there is no log dir, `null` would indicate just that.

**Comment by nicolas-grekas** [comment]
> If there is no log dir, null would indicate just that.

right, but do we have a forward compatible path to achieve that?

**Comment by GromNaN** [comment]
We can update the return type of `getLogDir` to allow `null`. This will not break child classes ([proof](https://3v4l.org/ouXlu)).

This will not have any side effect on projects that currently specify a log dir.

This may break things if a project chose to return `null` and this value is not expected in the code. But this is normal when using a new feature.

The last thing is if a 3rd party bundle uses the log dir, it will have to be fixed.

**Comment by derrabus** [comment]
> This will not break child classes

But it will break callers. 😕

**Comment by GromNaN** [comment]
> > This will not break child classes
> 
> But it will break callers. 😕

Yes, but only when a project decides to opt for this new feature and return `null`.

**Pull request closed without merging**
