### PR TITLE
[Yaml] add support for parsing the !!binary tag

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #8094, #15587, #17599 |
| License | MIT |
| Doc PR | symfony/symfony-docs#6226 |

### CODE REVIEW

**Comment by xabbuh** [comment]
@stof In #17599 you suggested to dump binary strings with the `!!binary` tag. Do you have an idea how we can best detect such strings (dumping with the `!!binary` should still be an opt-in feature though in my opinion).

**Comment by javiereguiluz** [comment]
:+1: nice addition and perfectly tested! Thanks @xabbuh.

Status: reviewed

**Comment by stof** [comment]
@xabbuh PHPUnit looks for control chars to detect binary strings

**Comment by xabbuh** [comment]
@stof Thanks for the tip. I added support for detecting binary data and dumping them as base64 encoded strings (as an opt-in feature).

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
