### PR TITLE
[HttpFoundation] Do not overwrite the Authorization header if it is already set

### PR DESCRIPTION
**Pull request by jakzal**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #17345 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by stloyd** [comment]
This bug AFAIK exists on 2.3+ so it should be merged in lowest branch not highest.

**Comment by jakzal** [comment]
@stloyd yes, it should be merged on 2.3. That's what I based my branch on. I selected the wrong target branch when sending the PR :)

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @jakzal.

**Pull request closed without merging**
