### PR TITLE
Ignore IDE settings and phpunit logs

### PR DESCRIPTION
**Pull request by alexndlm**
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by wouterj** [comment]
As for `.idea`: this is something that must be done in a global gitignore on your system. The gitignore of a project should only ignore files from the project itself.

As for the `phpunit.std*` files: can you please share how these are created by the project? I've never seen them.

**Comment by stof** [comment]
This is not ignoring IDE settings. This only ignores IDEA settings, which is only a specific editor family (the Jetbrains IDEs).
As we don't provide the IDE setup for our contributors (they can use any IDE they want), I see only 2 valid approaches:
- don't ignore IDE settings in the project, letting contributors use a [global ignore rule on their computer](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) (or a local ignore rule on their computer if they don't want it to apply globally) for the IDE they use
- add ignore rules for *all* IDEs out there

Our choice for now is to keep the first option, because the second option is unmaintainable.

**Review by derrabus — CHANGES_REQUESTED** [review]
FTR: -1 for the reasons @wouterj already mentioned.

**Comment by alexndlm** [comment]
@wouterj, got it, thanks.

About `phpunit.std*` - I can't find out why they were created. I have tested different test setups for PhpStorm, maybe because of this.

For now, I close PR, and if I find out exactly why `phpunit.std*` are created, I will come back to this.

**Pull request closed without merging**
