### PR TITLE
Removed templating.helper.assets service configuration

### PR DESCRIPTION
**Pull request by peterrehm**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

Relates to #14940

### CODE REVIEW

**Comment by dosten** [comment]
`Symfony\Bundle\FrameworkBundle\Templating\Helper\AssetsHelper` also can be removed IMO.

**Comment by dosten** [comment]
We really want to remove this helper? I think that the only thing we need to do here is remove the BC layer.

**Comment by dosten** [comment]
Why we need to delete the service? Do you know?

**Comment by peterrehm** [comment]
There has been quit some refactoring due to the Asset Component, so there is a new service available, `assets.packages` which provides you that functionality.

**Comment by dosten** [comment]
Yes, but `templating.helper.assets` is a public templating helper, what happens if someone wants to use `assets.packages` in a PHP template?

**Comment by peterrehm** [comment]
Good point, this must be validated, I was just following that up based on the referenced PR. It would be great if someone could provide further feedback, I was just removing the configuration, the actual service has been removed alfready before.

**Comment by dosten** [comment]
The class has been removed in #13666, the PR doesn't have any discussion, maybe it's a mistake. cc/ @fabpot

**Comment by stof** [comment]
hmm, looks like the there is templating helper based on the new component. This looks like a mistake.

**Comment by dosten** [comment]
@stof sorry, i don't understand what you're saying..

**Comment by peterrehm** [comment]
What he means is that it seems to be wrong for him, that there is no AssetsHelper based on the new component.

@fabpot The current deprecation message relates just to the new Asset Component. The Asset component however has no such helper. Do you want to have a helper again in the asset component with the same functionality? What was the intention?

The decision should be reflected in the docs.

**Comment by dosten** [comment]
@peterrehm Thanks for the explanation :) IMO we should keep the helper, see #14972.

**Comment by peterrehm** [comment]
@dosten So I would assume this PR should be fine, as this is deprecating the helper service not the Helper which will be eventually moved to another component which is however at the current moment already removed.

**Pull request closed without merging**
