### PR TITLE
Removed SecureRandom class

### PR DESCRIPTION
**Pull request by pierredup**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

Remove the `Symfony\Component\Security\Core\Util\SecureRandom` class and use the `random_bytes` function instead. Also include the `paragonie/random_compat` library for non PHP 7 installs

**Note** This PR depends on #15879 to be merged first

### CODE REVIEW

**Comment by stof** [comment]
We cannot remove it from the master branch without deprecating it first in 2.8 according to our policy. Otherwise it makes the upgrade to 3.0 painful

**Comment by pierredup** [comment]
@stof the deprecation PR is pending here #15879

**Comment by stof** [comment]
Which means this PR should not exist yet (merging the deprecation PR will make this PR unmergeable because of conflicts)

**Comment by pierredup** [comment]
I'll fix the conflicts when the deprecation PR is merged, I also updated the description to say that this is dependant on the deprecation PR to be merged first.
Having this PR open already means I can get quicker feedback and fix any issues without having to wait for the other PR's to be merged first and then only start with the removal.

**Comment by stof** [comment]
@pierredup most of the work done in this PR would become unnecessary once the deprecation PR is implemented the proper way though. The PR would just remove the class, the ``secure_random`` service and the tests for the class. So getting feedback on the current state of this PR is useless.

**Comment by pierredup** [comment]
Okay makes sense, I'll close this for now

**Pull request closed without merging**
