### PR TITLE
CS: remove unneeded parentheses around control statements

### PR DESCRIPTION
**Pull request by keradus**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by xabbuh** [comment]
some of these changes should be done in `2.3`

**Comment by keradus** [comment]
I thought that 2.3 is only for bugfixes now. OK, will send second PR ;)

**Comment by keradus** [comment]
Here you go @xabbuh https://github.com/symfony/symfony/pull/16780 ;)

**Comment by keradus** [comment]
Actually all could be fixed on 2.3 line

**Pull request closed without merging**
