### PR TITLE
[TwigBundle] do not mock the container builder or definitions

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by stof — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
more of this please :)

**Review by derrabus — APPROVED** [review]

**Comment by fancyweb** [comment]
Hey, I am the person who wrote this test yesterday.
I unfortunately don't know much about testing so I did it by looking to this other test of the TwigBundle https://github.com/symfony/symfony/blob/39e88ed3128933d7540eadd847d5650c8b52f5ba/src/Symfony/Bundle/TwigBundle/Tests/DependencyInjection/Compiler/TwigLoaderPassTest.php
For my personal knowledge, can someone explain me why is this better to not use mocking in this scenario please ? :-)

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by greg0ire** [comment]
Several reasons:

1. less code => easier to maintain
2. the test should test the outcome, not how it is achieved, it should have no knowledge of the SUT's internals
3. if what you are mocking comes from another package, you want to catch any deprecations, and you mock the internals as they are at one point in time, but they may change without it being considered a BC-reak => "don't mock what you don't own"

**Comment by xabbuh** [comment]
@fancyweb Sorry that I only created a PR after yours was merged, but I sadly didn't manage to review it before.

**Pull request merged**
