### PR TITLE
[HttpFoundation] Redis session handler

### PR DESCRIPTION
**Pull request by sgrodzicki**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | symfony/symfony-docs#5230 |

### CODE REVIEW

**Comment by cordoval** [comment]
I hope this gets in on 2.7 though it has been feature freezed :worried:

**Comment by Tobion** [comment]
I'm pretty sure there already exist redis session handler, even as PHP C extension.

**Comment by sgrodzicki** [comment]
@Tobion please have a closer look. This is just a wrapper which internally uses the C extension. You *can* set the session handler on a PHP configuration level but often it is more convenient to place it right into your app. That's why all other handlers were created in the first place.

**Comment by Tobion** [comment]
@sgrodzicki I had a close lock and I don't see the point of it.
1. it's not compatible with the core redis session handler, as it for example uses a different prefix by default. so you cannot easily exchange them
2. it has less features then the existing one
3. it doesn't seem to lazy connect to redis
4. it doesn't close the connection

So what's the advantage?

**Comment by jakzal** [comment]
> You can set the session handler on a PHP configuration level but often it is more convenient to place it right into your app

When do you think it's more convenient to use a custom handler, instead of the native one?

**Comment by sgrodzicki** [comment]
@jakzal when you don't have access to the PHP configuration file and/or you're hosting multiple Symfony projects on the same server/workers.

**Comment by Tobion** [comment]
@sgrodzicki you can set the native handler in code with ini_set. You don't need access to the config file.

**Comment by sgrodzicki** [comment]
@Tobion how is that different from Memcached/MongoDB?

**Comment by fabpot** [comment]
Closing for the reasons given by @Tobion

**Pull request closed without merging**
