### PR TITLE
CS: Use "self" keyword instead of class name if possible

### PR DESCRIPTION
**Pull request by gharlan**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

Fixes provided by new fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1116

If this pr is merged I would change the level of the fixer to `symfony`.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by Tobion** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
Thank you @gharlan.

**Comment by Tobion** [comment]
Thank you @gharlan.

**Comment by Tobion** [comment]
lol we tried to merge at the same time

**Comment by nicolas-grekas** [comment]
Looks like so, I've been a few seconds faster :)

**Pull request merged**
