### PR TITLE
[HttpFoundation] fix case sensitivity issue on IIS

### PR DESCRIPTION
**Pull request by freddy1913**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no   
| Deprecations? | no 
| Tests pass?   | yes   
| Fixed tickets | 
| License       | MIT
| Doc PR        | -

Fix problem with case sensitive ( URL REWRITE on IIS )

### CODE REVIEW

**Comment by lyrixx** [comment]
Hello @freddy1913 

Thanks for your first contribution.
Your are supposed to fill the table in the PR description. 

Then, if it's really a bug, could you please add a test for it?
And patch should be sent to the lower maintained branch (2.7 for now)

**Comment by nicolas-grekas** [comment]
Status: needs work

**Comment by nicolas-grekas** [comment]
Closing due to lack of feedback. Of course, feel free to submit another PR with more details @freddy1913.

**Comment by freddy1913** [comment]
Bonjour,

Excusez moi mais je savais pas que je devais faire quelque chose de plus qu'un commit ? Pourriez-vous m'aider svp, je ne suis pas un grand connaisseur de github. De plus cela fait pas très longtemps que je développe.  Je vous remercie d'avance !

**Comment by xabbuh** [comment]
@freddy1913 Could you please use English for the communication on the GitHub repo? :) I don't speak any French and needed Google Translate to hopefully correctly understand what you were trying to say.

As @lyrixx said if you think that this fixes a bug, we will need a test that ensures that this is not going to be introduced in the future. Can you add one?

**Comment by freddy1913** [comment]
@xabbuh Ok thank you for your answer. I will see for adding a test so.

**Comment by freddy1913** [comment]
I don't know how to pass a test. It's not really a bug.  I just use stripos instead strpos in the request.php that allow me to get url with upper and lower case mixed. it occured in the IIS and laravel environement. (not apache) sorry for my bad english

**Comment by nicolas-grekas** [comment]
Can you at least explain what's not working before, and working after?

**Comment by freddy1913** [comment]
Sure,  When I try to access app's url  http://myserver/myApp/public/  instead http://myserver/myapp/public/  I have this route error [in RouteCollection.php (line 179)]. The only way to get access back through the same url but lowercase "A" http://server/myapp. 

We have traced back the issue to vendor\symfony\http-foundation\Request.php  [strpos changing it to stripos] fixed the problem.

It occured on IIS environement only

Thank you !

**Comment by javiereguiluz** [comment]
I've looked for more information about this:

1) The hostname part of the URL is always case-insensitive (because of DNS: https://tools.ietf.org/html/rfc4343)
2) The other parts of the URL are case-sensitive ...
3) ... but Windows being (usually) a case-insensitive OS makes URLs served on IIS case-insensitive too.

So, this fix is correct, but it should only be applied on Windows ... and ideally, only on case-insensitive OS. Another solution could be to ignore this fix and apply the standards strictly and treat URLs case-sensitive, regardless of the OS.

**Comment by nicolas-grekas** [comment]
I think we don't want to handle this: as @javiereguiluz said, the path of URLs are case sensitive. If Windows doesn't follow the spec that's fine but we don't have to follow this. Why do you want to be able to use two different URLs to access the same app? This breaks the concept of URIs and e.g. forces duplicating any cache for no reason.
With this reasoning, I'm :-1: for this change. Thanks for proposing anyway!

**Pull request closed without merging**
