### PR TITLE
[Console] Add method to know parsed option

### PR DESCRIPTION
**Pull request by blanchonvincent**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #12769, #11572 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@xabbuh do you like the `hasParsedOption()` method name?

**Comment by fabpot** [comment]
I think the implementation should be actually different. There is no need to add another method with a weird name nobody will understand. I was more thinking about adding an additional argument to the existing `getOption()` method.

**Comment by bishopb** [comment]
@fabpot I think the challenge with an additional argument to `getOption` is that wouldn't address `getOptions`, which I would also expect to support tri-state optionals:

```
command.php
$this->getOptions() => [ 'foo' => 'value when not given' ]

command.php --foo
$this->getOptions() => [ 'foo' => 'value when given but blank' ]

command.php --foo=bar
$this->getOptions() => [ 'foo' => 'bar' ];
```

**Comment by tomzx** [comment]
While you guys are at it, it might also be useful to be able to determine if an argument has been set.

**Pull request closed without merging**
