### PR TITLE
[Serializer][TypeInfo] fix support for phpstan/phpdoc-parser 2

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | related to #58796
| License       | MIT

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by mtarld — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you Christian.

**Comment by derrabus** [comment]
The changes of #57618 make it a bit difficult to merge this change up. @mtarld Can you help here?

**Comment by mtarld** [comment]
Sure @derrabus I'll take care of it 🙂

**Comment by andrew-demb** [comment]
~@xabbuh can you backport these changes to 6.4 too, please?~

UPD: I found https://github.com/symfony/symfony/pull/58800, already backported. Thanks!

**Pull request merged**
