### PR TITLE
[travis] make the PHP version check for APC more robust

### PR DESCRIPTION
**Pull request by vicb**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Does this fix anything?

**Comment by WouterJ** [comment]
@nicolas-grekas the current way means APC is configured for the 7.0 builds as well IIUC

**Comment by nicolas-grekas** [comment]
@WouterJ not really because of the first `if` in the bash line

**Comment by vicb** [comment]
PHP7 was what I had in mind when submitting this PR.

Releasing good SW is also about promoting good practices and IMO checking minor version number only is not one of them. However I could understand if you prefer closing this PR & feel free to do so.

**Comment by nicolas-grekas** [comment]
Thanks @vicb see .travis.yml in #15575

**Pull request closed without merging**
