### PR TITLE
[Form] fix truncating form views in data collector

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no (fixing a non released patch)
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Fixes #27923.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@VincentChalnot can you please confirm this patch also fixes the memory issue?

**Comment by yceruto** [comment]
I can confirm, this change solve the issue as well.

**Comment by VincentChalnot** [comment]
@nicolas-grekas I confirm this patch also fix the memory issue, thanks!

**Comment by nicolas-grekas** [comment]
thank you for the confirmation!

**Pull request merged**
