### PR TITLE
typo

### PR DESCRIPTION
**Pull request by vetalt**
| Q | A |
| --- | --- |
| License | MIT |

[Validator] translation typo

### CODE REVIEW

**Comment by xabbuh** [comment]
Imho this change is not correct. There is nothing like "a user current password", but we are dealing with "the user's password".

**Comment by phansys** [comment]
I agree with @xabbuh. Also, not that you are changing the translation source, not the target.

**Comment by vetalt** [comment]
all other translations have "user current password" at this place

**Comment by phansys** [comment]
What do you mean? Check [this](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Validator/Resources/translations/validators.en.xlf#L178-L179) for instance.
The old message (the same that you are trying to reintroduce) was fixed in this commit: @d57471e.

**Comment by vetalt** [comment]
you are right.. I have old symfony

**Pull request closed without merging**
