### PR TITLE
[DI] Remove an unused property

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  |no 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]

**Review by ogizanagi — APPROVED** [review]

**Comment by ro0NL** [comment]
Could you check https://github.com/symfony/symfony/pull/22811#discussion_r118755708 it's still used :)

**Comment by nicolas-grekas** [comment]
@dunglas can you patch that line in this PR also, as spotted by @ro0NL above?

**Comment by dunglas** [comment]
@nicolas-grekas done

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request merged**
