### PR TITLE
[Yaml] [Validator] Removed conditional @deprecated tags and moved their descriptions to the method description as a note

### PR DESCRIPTION
**Pull request by gerritdrost**
[Yaml] [Validator] Removed conditional @deprecated tags and moved their descriptions to the method description as a note.

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14815 |
| License | MIT |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by jakzal** [comment]
:-1: as this is going to make that these two methods show up in IDEs as deprecated. Methods themselves are not deprecated, only some of their parameters are.

**Comment by jakzal** [comment]
Sorry, I was reading the patch in reverse :(

Obviously :+1:

**Comment by xabbuh** [comment]
:+1:

**Comment by fabpot** [comment]
This should probably be merged ealier than 2.7.

**Comment by fabpot** [comment]
Thank you @gerritdrost.

**Pull request closed without merging**
