### PR TITLE
[Console] Register signal handling only for commands implemeting SignalableCommandInterface

### LINKED ISSUE #38820: [Console] Signal does not work with Question
**Symfony version(s) affected**: 5.2.x

I broke symfony, sorry !

**Description**  

Signal handling does not work well with question! 

**How to reproduce**  

Use `bin/console make:controller` and then press <kbd>CTRL+C</kbd>
=> it does not work anymore until you press <kbd>enter</kbd>

**Possible Solution**  

Empty this list https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Console/Application.php#L94
Most of the time, we don't care about signal. It's only useful for long running process. But since we use this list **before** running the command, the "Signal To Symfony Event" feature will become hard to implement. We may register signal listener if the command implement a certain insterface.

The other solution would be to not use [`fgets`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Console/Helper/QuestionHelper.php#L517) but `stream_select()`

**Additional context**  

I created a simple reproducer:
```
<?php

pcntl_signal(SIGINT, function () {
    dump('CAUGHT');
});
pcntl_async_signals(true);


$stream = \STDIN;
$what = fgets($stream, 4096);

dump('AFTER');
```

=>

```
php test.php 
^C^C^C^C
^ "CAUGHT"
^ "CAUGHT"
^ "CAUGHT"
^ "CAUGHT"
^ "AFTER"
```

As you can see, I pressed 4 times <kbd>CTRL+C</kbd> and it did not worked until I pressed <kbd>enter</kbd>

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 5.x for features
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #38820
| License       | MIT
| Doc PR        |

---

Actually, it does not make sens to listen all signals for all commands.

This commit also add more tests for this part of code.

### CODE REVIEW

**Comment by lyrixx** [comment]
Fabbot failures are not related to my diff. Should I fix it?

**Comment by chalasr** [comment]
They are false positives to me.

**Review by chalasr — APPROVED** [review]
👍

**Review by nicolas-grekas — APPROVED** [review]

**Comment by chalasr** [comment]
Thank you @lyrixx.

**Pull request merged**
