### PR TITLE
[Messenger] log Throwable if message failed

### PR DESCRIPTION
**Pull request by amberovsky**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       |  
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by Tobion** [comment]
This error is already logged in https://github.com/symfony/symfony/blob/0ab5eeddf97d0a277c5ad956a51365aba93b27b9/src/Symfony/Component/Messenger/EventListener/SendFailedMessageForRetryListener.php#L66
Since there is no further explanation, I'm closing this PR.

**Comment by amberovsky** [comment]
Hey @Tobion ,
That is unrelated, for example `ConsumeMessagesCommand` does not use `SendFailedMessageForRetryListener` but `StopWorkerOnFailureLimitListener`

I'm not sure if the `ConsumeMessagesCommand` code is wrong but, IMHO, `StopWorkerOnFailureLimitListener` should not depend `SendFailedMessageForRetryListener` (as _it knows the error is logged there_) as that breaks SOLID.

**Comment by Tobion** [comment]
SendFailedMessageForRetryListener  is always registered using the event subscribe service tag. The other listener you mention are registere dynamically as they are only used conditionally.

**Comment by Tobion** [comment]
Logging also has nothing to do with SOLID. The error is already logged. So there is no point in logging it twice which would confuse people.

**Comment by amberovsky** [comment]
Hey @Tobion ,

> SOLID does not apply to logging

Yes indeed, in this case, you are saying that listener A should not log the message because listener B logs it and therefore you create a dependency between them, however, the listeners are unrelated to each other. **That** breaks SOLID, not **logging**. 

> So there is no point in logging it twice which would confuse people.

A _null_ can be provided as the logger instance *if* that confuses people

Anyway, even the auto-registered `SendFailedMessageForRetryListener` you mentioned has some logic that prevents the message to be logged in some cases. That is quite bad as we always need to know why a worker failed.

```php
        $shouldRetry = $retryStrategy && $this->shouldRetry($throwable, $envelope, $retryStrategy);

        if ($shouldRetry) {
        ...
            if (null !== $this->logger) {
                $this->logger->error('Error thrown while handling message {class}. Sending for retry #{retryCount} using {delay} ms delay. Error: "{error}"', $context + ['retryCount' => $retryCount, 'delay' => $delay, 'error' => $throwable->getMessage(), 'exception' => $throwable]);
            }
        ...
        }
```

**Pull request closed without merging**
