### PR TITLE
[EventDispatcher] Deprecate ContainerAwareEventDispatcher

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

These methods shouldn't be available to end users.

### CODE REVIEW

**Comment by stof** [comment]
👍

**Comment by nicolas-grekas** [comment]
PR updated to deprecate the ContainerAwareEventDispatcher class.
To be rebased on top of #20953 before merging.

**Comment by xabbuh** [comment]
The upgrade files for 3.3 and 4.0 need to be updated too.

**Comment by fabpot** [comment]
Can be rebased now

**Comment by fabpot** [comment]
You should probably update `src/Symfony/Bundle/FrameworkBundle/Resources/config/services.xml` as well to remove its usage.

**Comment by nicolas-grekas** [comment]
Rebased. About services.xml, that'd be a BC break because of the getContainer method that people may use...

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by chalasr** [comment]
> About services.xml, that'd be a BC break because of the getContainer method that people may use...

It's a bit annoying to get deprecations each time the `event_dispatcher` service is used until 4.0.
is there any alternative we can provide? Most often there is no need for container aware dispatcher, only dispatching events (3rd party bundles, functional tests in final apps..)

**Pull request merged**
