### PR TITLE
[Validator][GroupSequence] fixed GroupSequence validation ignores PropetyMetadata of parent classes

### PR DESCRIPTION
**Pull request by senaria**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #19387 |
| License | MIT |
| Doc PR | N/A |

### CODE REVIEW

**Comment by yakobe** [comment]
Can we merge this in?

**Comment by senaria** [comment]
Is there any news about this? This possible solution looks like it would really help us out. Would be great if you could have a closer look.

**Comment by fabpot** [comment]
@HeahDude Can you have a look at this one?

**Comment by HeahDude** [comment]
LGTM 👍 @senaria Thank you for submitting this patch :)

Status: reviewed

**Comment by fabpot** [comment]
Thank you @senaria.

**Comment by senaria** [comment]
Brilliant. Thank you 👍

**Comment by peterrehm** [comment]
I just proposed to revert this commit as it introduced a BC break. Please see my comment in the PR https://github.com/symfony/symfony/pull/20857, I think this might solve your issue as if the revert will happen it might break your application logic.

sorry for the additional work @yakobe! :)

**Pull request closed without merging**
