### PR TITLE
[TwigBundle] Template validator

### PR DESCRIPTION
**Pull request by GaryPEGEOT**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Add a new constraint to validate a Twig template stored in a model / entity.

### CODE REVIEW

**Comment by xabbuh** [comment]
Thanks for proposing this feature @GaryPEGEOT. However, to me this is not a really common use case and thus I would be 👎  on adding this to the core.

**Comment by fabpot** [comment]
Same for me. I don't think this belongs to the core. Ir would make for excellent blog post though.

**Comment by iltar** [comment]
I could see use for this feature, especially considering our email templates are written in twig. As this feature is restricted to the TwigBundle, I don't think there's a big problem if it's introduced. However, xabbuh is right that this is not a feature many people would want. You could always publish your own bundle for this!

**Comment by stof** [comment]
I'm also -1 about adding this to the core. This can perfectly be implemented as a third-party bundle (maintained by people needing the feature)

**Comment by xabbuh** [comment]
closing for the reasons explained

**Pull request closed without merging**
