### PR TITLE
[FrameworkBundle] fix Could not find service "test.service_container"

### LINKED ISSUE #41715: Testing standalone bundle - got 'Could not find service "test.service_container".'
I'm writing a standalone bundle and trying to test it. But got an error:

`LogicException: Could not find service "test.service_container". Try updating the "framework.test" config to "true".`

I couldn't find anything in the documentation related to this error. How can I fix that?

UPD: I tried obvious solution by creating `config/config_test.yml` and even renamed extension to `.yaml` but it didn't help, content of the file is:

```yaml
framework:
    test: true
```
The content of `phpunit.xml.dist` (renamed to `.txt` due to github limitations):
[phpunit.txt](https://github.com/symfony/symfony/files/6656035/phpunit.txt)

### PR DESCRIPTION
**Pull request by smilesrg**
| Q             | A
| ------------- | ---
| Branch?       |  5.2, needs to be ported to 5.3
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no
| Tickets       | Fix #41715
| License       | MIT

Partial backport of https://github.com/symfony/symfony/pull/41530
Related to https://github.com/symfony/symfony/issues/41715 and https://github.com/symfony/symfony/pull/41530

When launching phpunit, got an error:
`LogicException: Could not find service "test.service_container". Try updating the "framework.test" config to "true".`

```
There was 1 error:

1) App\Symfony\Bundle\Tests\Integration\IntegrationTest::testServiceWiringWithConfiguration
LogicException: Could not find service "test.service_container". Try updating the "framework.test" config to "true".

/Projects/app/vendor/symfony/framework-bundle/Test/KernelTestCase.php:109
/Projects/app/tests/integration/IntegrationTest.php:23

Caused by
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "test.service_container". Did you mean this: "service_container"?

/Projects/app/vendor/symfony/dependency-injection/Container.php:280
/Projects/app/vendor/symfony/dependency-injection/Container.php:228
/Projects/app/vendor/symfony/framework-bundle/Test/KernelTestCase.php:107
/Projects/app/tests/integration/IntegrationTest.php:23
```

/cc @xabbuh  @nicolas-grekas

### CODE REVIEW

**Comment by YaFou** [comment]
Can you implement a test please?

**Comment by smilesrg** [comment]
>Can you implement a test please?

Well... this is a backport of PR that hasn't any tests... Probably I can, but I'm not sure how to test these changes properly.

**Comment by nicolas-grekas** [comment]
Thank you @smilesrg.

**Comment by smilesrg** [comment]
@nicolas-grekas Thank you too!

**Pull request merged**
