### PR TITLE
[Process] Fix BC break: "exec" should remain an internal "detail"

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #22476
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by stof** [comment]
this still does not fix the BC break when the executed code already used `exec`

**Comment by nicolas-grekas** [comment]
accepting an array is new since 3.3, so this cannot happen

**Comment by stof** [comment]
oh, it is indeed only for arrays

**Comment by stof** [comment]
@nicolas-grekas it can happen when using ProcessBuilder, as this one uses the new API under the hood.

**Comment by nicolas-grekas** [comment]
I don't see what you mean, can you post a reproducer that fails with the current patch?

**Comment by stof** [comment]
ProcessBuilder can be used to create processes using `exec` already today.
And in 3.3, a second exec will be added on them, due to using an array.

Btw, I think you also broke the `setPrefix` feature of the ProcessBuilder, as adding it in the array will then make Process escape it

**Comment by nicolas-grekas** [comment]
I'm really sorry, but either you're wrong, or I totally miss the point.
the prefix in 2.7/3.2 *is* escaped. See
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Process/ProcessBuilder.php#L270

Please provide me some code sample to help me get your point if it's still valid...

**Comment by stof** [comment]
ah indeed, I forgot it is.

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
