### PR TITLE
[Console] Use file system completion for redirect operators

### PR DESCRIPTION
**Pull request by Chi-teck**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | yes
| Tickets       | #49761
| License       | MIT

The approach is similar to https://github.com/systemd/systemd/pull/12089. I also added input redirect operator.

### CODE REVIEW

**Comment by GromNaN** [comment]
Thanks for working on this topic. It would be nice if we can have the same feature for fish and zsh. 

I'll use a [demo app](https://github.com/GromNaN/symfony-console-demo) to test.

**Comment by Chi-teck** [comment]
@GromNaN I have no experience with ZSH or Fish. So added subtasks to the parent ticket.

**Review by GromNaN — APPROVED** [review]
It works very well. Thank you.

**Comment by fabpot** [comment]
Thank you @Chi-teck.

**Pull request merged**
