### PR TITLE
[Validator] Add Japanese translation

### PR DESCRIPTION
**Pull request by issei-m**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by issei-m** [comment]
Although I'm not sure why the AppVeyor CI has broken, guessing not related to this change.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @issei-m.

**Comment by nicolas-grekas** [comment]
@issei-m we are looking for help to translate the new Symfony 5 book written by @fabpot into Japanese. Do you know if some Japanase-native people could be interested in doing so?
See https://www.kickstarter.com/projects/fabpot/symfony-5-the-fast-track for more info :)

**Comment by issei-m** [comment]
@nicolas-grekas I’m going to look for those who would be interested in it, btw I’m one of them too. So now seeing the kick starter page you pasted :)

**Comment by fabpot** [comment]
@issei-m I've just invited you to the Japanese translation team :)

**Comment by issei-m** [comment]
@fabpot Hi, I've newly found the two persons who willing to contribute to the translation project, so I'd like to invite them to join us: @ganchiku, @kumamidori
Best regards!

**Comment by issei-m** [comment]
@fabpot I got another one: @ttskch, he's interested in the PJ too.

**Comment by fabpot** [comment]
@issei-m @ttskch @ganchiku (welcome back :)) @kumamidori You are now all part of the Japanese team. More info in the "discussions" section of the main translation team. Don't hesitate to ping me via the "discussions" section of the Github Japanese team.

**Pull request merged**
