### PR TITLE
[VarDumper] Improve microseconds support in date caster

### PR DESCRIPTION
**Pull request by maidmaid**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | /
| License       | MIT
| Doc PR        | /

This PR adds the microseconds in ``period`` virtual property and in tooltip overview.

Before:

After:

And fixes interval caster:

```php
dump((new DateTime('00:00:00'))->diff(new DateTime('00:00:00.123')));

// before
DateInterval {
  interval: + 00:00:00.0.123
}

// after
DateInterval {
  interval: + 00:00:00.123
}
```

### CODE REVIEW

**Comment by maidmaid** [comment]
Fail not related.

**Comment by nicolas-grekas** [comment]
can you add a test with non-zero ms?

**Comment by maidmaid** [comment]
Mmh, non-zero ms cases are based on the ``formatSeconds()`` method which is already tested here: https://github.com/symfony/symfony/blob/89d85f3ea15c9ec29be374d77cd3f245fb8ec75a/src/Symfony/Component/VarDumper/Tests/Caster/DateCasterTest.php#L91-L96 Is it really usefull?

**Comment by nicolas-grekas** [comment]
tests are red

**Comment by maidmaid** [comment]
Fixed.

**Comment by maidmaid** [comment]
Fixed.

**Comment by nicolas-grekas** [comment]
Thank you @maidmaid.

**Pull request merged**
