### PR TITLE
[Validator] remove partial deprecation annotation

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #14815 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by stof** [comment]
A note should be kept explaining that these arguments are deprecated though. It cannot be removed entirely

**Comment by xabbuh** [comment]
@stof The note is already there: https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Validator/ExecutionContextInterface.php#L94

**Comment by aitboudad** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
