### PR TITLE
[DependencyInjection] clarify exception when no args are configured

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #21412
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by stof** [comment]
👍

**Review by javiereguiluz — APPROVED** [review]
👍

**Comment by chalasr** [comment]
Much better than 
> [...] is not in the range [0, -1]

👍

**Comment by dunglas** [comment]
👍

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
