### PR TITLE
[DI][Serializer] Fix missing de(normalizer|coder) autoconfig

### PR DESCRIPTION
**Pull request by ogizanagi**
| Q             | A
| ------------- | ---
| Branch?       | 3.3
| Bug fix?      | yes(ish)
| New feature?  | no (at least complete the 3.3 feature)
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Just migrating an app to `3.3.0-RC1`, I get surprised it wasn't already registered :)

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Can you do the same for `DecoderInterfae`?

**Comment by ogizanagi** [comment]
Oh, indeed, good catch! Done.

**Review by nicolas-grekas — APPROVED** [review]
:+1: (failure unrelated)

**Comment by nicolas-grekas** [comment]
Thank you @ogizanagi.

**Pull request merged**
