### PR TITLE
[Serializer] Added ScalarDenormalizer for denormalize any scalar values

### LINKED ISSUE #33784: [Serializer] deserializing array of integers
**Symfony version(s) affected**: 4.3.4

**Description**  
Hello, I am trying to deserialize an array of integers but I am getting this exception: `Could not denormalize object of type int[], no supporting normalizer found.`  Previously I was using JMS serializer so it was possible to define type `array<int>` but I get the same error with symfony serializer.

**How to reproduce**  
```php
<?php
$serializer = new Serializer(
    [new GetSetMethodNormalizer(), new PropertyNormalizer(), new ObjectNormalizer(), new ArrayDenormalizer()],
    [new JsonEncoder()]
);
$numbers  = $serializer->deserialize('["15"]', 'int[]', 'json');
```

### PR DESCRIPTION
**Pull request by a-menshchikov**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #33784
| License       | MIT

Was added `ScalarDenormalizer` class that allows deserialize scalar data (single or array).

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Should target master as it's a new feature.

**Comment by a-menshchikov** [comment]
First of all this is bug fix (see #33784). Or that issue can be resolved only in master?

**Comment by dunglas** [comment]
For serialization, scalar values are handled directly in the `Serializer` class: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Serializer.php#L149

I wonder if we shouldn't add support for normalization in this new class too (while keeping the existing code in `Serializer` for performance).

It looks like a bug fix to me too.

**Comment by a-menshchikov** [comment]
#35235 is a corrected copy of this PR.

**Pull request closed without merging**
