### PR TITLE
Use the ::class constant

### PR DESCRIPTION
**Pull request by Nyholm**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | 

This PR updates all `class_exits` checks to use the `::class` constant. 

I do this to be coherent with the rest of the source code. 
My other (unrelated reason) is that Im running static analyses on the source code and classes hidden in strings like this are really hard to find.

### CODE REVIEW

**Comment by fabpot** [comment]
I'm :-1: for such changes that are only local. We should either do it everywhere (but that makes merging branches more complex) or not at all.

**Comment by Nyholm** [comment]
Thank you for the quick feedback. Are you okey with this change if it is for all our Bundles and everywhere we refer to a class?

**Comment by fabpot** [comment]
No, we decided to not do that to avoid making branch merges more painful.

**Comment by Nyholm** [comment]
Okey. Thank you for reviewing this.

**Pull request closed without merging**
