### PR TITLE
[Validators] Add new translation in Hungarian

### LINKED ISSUE #41821: Missing translations for Hungarian (hu)
Hello,

There are some missing translation for Hungarian (hu). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Validator/Resources/translations/validators.hu.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Resources/translations/validators.hu.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by danielTiringer**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41821 
| License       | MIT
| Doc PR        | N/A

This PR adds missing Hungarian translations.

### CODE REVIEW

**Comment by StaffNowa** [comment]
Hi, thanks for contributing, but I think wrong trans-unit ids small list of ids from RU and LT countries https://github.com/symfony/symfony/pull/41872/files, but not critical :)

**Comment by danielTiringer** [comment]
> Hi, thanks for contributing, but I think wrong trans-unit ids small list of ids from RU and LT countries https://github.com/symfony/symfony/pull/41872/files, but not critical :)

That is a nice catch! :)
I did double check the Hungarian ones, and thankfully it had no such issues.

**Comment by StaffNowa** [comment]
@danielTiringer thanks for checking 👍💪

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @danielTiringer.

**Pull request merged**
