### PR TITLE
[DependencyInjection] Add support for casting callables into single-method interfaces

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 6.3
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

This PR makes it possible to cast closures to single-method interfaces.

It is best reviewed [ignoring whitespaces](https://github.com/symfony/symfony/pull/49632/files?w=1).

This works at the service definition level. Here is an example that creates heterogeneous URI-template expanders and exposes them under a common interface (using real classes inspired from #49302):

```php
interface UriExpanderInterface
{
    public function expand(string $url, array $vars): string;
}
```

And then, in some service configuration using the PHP-DSL:

```php
    ->set('uri_expander.guzzle', UriExpanderInterface::class)
        ->fromCallable([\GuzzleHttp\UriTemplate\UriTemplate::class, 'expand'])

    ->set('uri_template_expander.rize', UriExpanderInterface::class)
        ->fromCallable([inline_service(\Rize\UriTemplate::class), 'expand'])

    ->alias(UriExpanderInterface::class, 'uri_template_expander.rize' or 'uri_template_expander.guzzle')
```

Internally, this creates a proxy class that will behave like this one (which could be used in a test case):

```php
$expander = new class ($closure) implements UriExpanderInterface {
    public function __construct(private \Closure $closure)
    {
    }

    public function expand(string $url, array $vars): string
    {
        return $this->closure->__invoke($url, $vars);
    }
};
```

This also adds support for YAML and XML of course:

```yaml
services:
    uri_template_expander.rize:
        class: UriExpanderInterface
        from_callable: [ !service {class: Rize\UriTemplate}, expand ]
```

```xml
<services>
  <service id="uri_template_expander.rize" class="UriExpanderInterface">
    <from-callable method="expand">
      <service class="Rize\UriTemplate"/>
    </from-callable>
  </service>
</services>
```

This also works using attributes:

```php
class MyClass
{
    public function __construct(
        #[AutowireCallable([\GuzzleHttp\UriTemplate\UriTemplate::class, 'expand'])]
        UriExpanderInterface $expander,
    )
}
```

### CODE REVIEW

**Comment by Neirda24** [comment]
Doesn't this reduce the evolutivity of the interface? If I understand this correctly then adding a second method to the interface would break your wrapping. I don't see the real benefits at the moment. Could you share real world usage cases ?

**Comment by nicolas-grekas** [comment]
@Neirda24 adding a method to an interface is a BC break so this shouldn't come unplanned. Also the segregation principle tells us that interfaces should have less methods, not more, so that the natural path for them is to shrink, not grow. Of course nothing enforces this, but this still helps answer you argument. I don't have a better real world usage than the one I posted in the description.

**Comment by Neirda24** [comment]
@nicolas-grekas : agreed on the principles. I simply fear that it adds a lot of complexity both to maintain in symfony and to read in real world apps without gaining much from it. Maybe there is something I am not seeing ATM. Using the factory we usually expect that the class or type is the one from the method itself, here it is automatically cast as what Interface was provided on the service definition. AFAIK only this factory would do this. Am I wrong ?

**Comment by nicolas-grekas** [comment]
PR updated to make it easy to configure. This should alleviate your concerns @Neirda24. About the complexity for maintainers, this was pretty straightforward to implement actually so it's not an issue to me.

**Comment by Neirda24** [comment]
Indeed easier to read. And less confusing for new developers. Gotta make sure the "cast" keyword is kept out of the documentation because even though it could be affiliated to a cast it is more a decorator to me. Thanks @nicolas-grekas !

**Comment by chalasr** [comment]
rebase needed

**Comment by nicolas-grekas** [comment]
done

**Review by chalasr — APPROVED** [review]
Cool

**Comment by nicolas-grekas** [comment]
(rebased)

**Pull request merged**
