### PR TITLE
[Console] fix restoring stty mode on CTRL+C

### LINKED ISSUE #44045: [Process] Buggy terminal after interrupting TTY Process
### Symfony version(s) affected

5.3

### Description

Interrupting a Process with TTY mode in a Command leads to broken terminal: we can't see what we're typing anymore.

It happens only for processes that require user input several times. The bug occurs if there are remaining steps to complete the operation. So if we interrupt the process at the last step, bug doesn't occur.
Typically, my use case is using Maker Bundle. So for instance, bug occurs with `make:entity`, but not with `make:controller`.

### How to reproduce

1. Make a basic command with `make:command` or manually.
2. Implement [`SignalableCommandInterface`](https://symfony.com/doc/current/components/console/events.html#the-consoleevents-signal-event) and susbcribe to SIGINT signal.
3. Run a Process that require user input multiple times with TTY mode enabled in execute command function, like this:

```php
        $process = Process::fromShellCommandline('php bin/console make:entity');
        $process->setTty(true);

        $process->run();
```

4. Run command at the project root (`php bin/console your-command`).
5. Interrupt command at the first step.
6. See that you can't see what you're typing anymore in the terminal (but you're typing!).

### Possible Solution

It should be a problem with standard input/output not given back to the parent process, but I don't have enough knowledge in systems to fix it alone...

### Additional Context

image

As you can see, you don't see the `php -v` I entered after interrupting the `Test` command that launches `make:entity` process. Only the result of it appears.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.3
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #44045
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by chalasr** [comment]
Could this be tested?

**Comment by nicolas-grekas** [comment]
Test added :hot_face:

**Comment by chalasr** [comment]
Thank you @nicolas-grekas.

**Comment by chalasr** [comment]
Screenshot 2022-01-24 at 21 00 18
😊

**Pull request merged**
