### PR TITLE
[Cache] Use binary type for ID column for PostgreSQL

### PR DESCRIPTION
**Pull request by alexndlm**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        | 

When using PostgreSQL binary part of the cache item ID loses.

Previous tries:
- https://github.com/symfony/symfony/pull/49713
- https://github.com/symfony/symfony/pull/49741

### CODE REVIEW

**Comment by alexndlm** [comment]
@nicolas-grekas, would you please take a look?

**Comment by alexndlm** [comment]
@nicolas-grekas, ping, ping.

**Comment by alexndlm** [comment]
@nicolas-grekas , any updates?

**Comment by nicolas-grekas** [comment]
On second thought, I'd prefer a more seamless approach.
I submitted #49848 for 5.4 and also #49847 for 6.3.
Thanks for  raising this issue and sending PRs!

**Pull request closed without merging**
