### PR TITLE
[Security] add subject variable to expression context

### PR DESCRIPTION
**Pull request by xabbuh**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | yes |
| Tests pass? | yes |
| Fixed tickets | #16600 |
| License | MIT |
| Doc PR | TODO |

### CODE REVIEW

**Comment by xabbuh** [comment]
If someone has an idea how we could trigger a deprecation warning when the user accesses the deprecated `object` variable, I will be happy to include such a change here too.

**Comment by fabpot** [comment]
I'm going to merge this one now before 2.8 release. For the deprecation warning, we can add it later on. @xabbuh Can you create a ticket so that we don't forget about this?

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Comment by stof** [comment]
Deprecation ``object`` would make it very hard to write expressions compatible with both 2.7 and 3.0 (or 2.8 without deprecations): the expression language does not give us enough expressiveness to handle this (allowed variables are checked at compile time)

**Comment by xabbuh** [comment]
@stof What would you suggest instead?

**Comment by fabpot** [comment]
I've merged 2.8 into master by keeping both `object` and `subject`.

**Pull request merged**
