### PR TITLE
[Process] Fix stream_select priority when writing to stdin

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by fabpot** [comment]
ping @romainneutron 
Is it possible to add some tests?

**Comment by nicolas-grekas** [comment]
@fabpot test case added. It hangs without the patch.

**Comment by romainneutron** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
