### PR TITLE
[HttpKernel] removed deprecated profiler storages

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by Tobion** [comment]
Tests are failing and you also need to remove code in https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L293

Status: Needs Work

**Comment by fabpot** [comment]
Just realized that `lifetime` should be deprecated as well. I'm going to create a PR on 2.8.

**Comment by fabpot** [comment]
See #16027

**Comment by xavierleune** [comment]
:cry:

**Pull request merged**
