### PR TITLE
[Form] Throw exception for invalid form buttons name

### PR DESCRIPTION
**Pull request by yceruto**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

See https://github.com/symfony/symfony/pull/28969

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
(note: no need to create one removal PR by deprecation - grouping a bit could be easier for everyone)

**Comment by nicolas-grekas** [comment]
(.e.g: rebase needed now :) )

**Comment by yceruto** [comment]
I guess that this way should be easier to review.

> (.e.g: rebase needed now :) )

it's not needed here :)

**Comment by nicolas-grekas** [comment]
Thank you @yceruto.

**Pull request merged**
