### PR TITLE
[DebugBundle] add dumps count in the profiler menu

### PR DESCRIPTION
**Pull request by fmata**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

When many dumps are expected, it would be convenient to have the dumps count displayed in the menu instead of going to the panel and perform a manual count.

### CODE REVIEW

**Review by ro0NL — APPROVED** [review]
usually panels only display their error count here, but here the context is different; there's only ever a total count.

edit: missed @javiereguiluz comment in between, but yeah the same issue is on my mind as well :)

**Comment by fmata** [comment]
@javiereguiluz I was not aware of this rule. It's a little patch but important DX IMHO, I need it everyday. I agree with @ro0NL and may be what is done in SwiftmailerBundle can argue to make an exception :)

https://github.com/symfony/swiftmailer-bundle/blob/3fc0cd702d46fdd67d247766b4b634946daf140e/Resources/views/Collector/swiftmailer.html.twig#L101-L105

**Comment by fabpot** [comment]
When is it useful to have the number of dumps?

**Comment by fmata** [comment]
When you dump() before and in a if statement, if the condition is true the number of dumps is 2 else 1.

It's useful too when you want debug a loop and you know the number of iterations expected, you can check with the number of dumps and go deeper in the panel when needed only.

**Comment by nicolas-grekas** [comment]
I don't know about the menu, I'll let @javiereguiluz decide.
But at least the count should be displayed in the main panel.
About the use case you describe, isn't the count already displayed in the toolbar?
Doesn't it allow spotting loop/ifs as you describe already?

**Comment by fmata** [comment]
The toolbar is not enough with AJAX calls where only profile, method, type, status, URL and time are displayed.

**Comment by fabpot** [comment]
I'm not convinced that this should be done.

**Comment by fmata** [comment]
I understand your point, I think it can be sum up as this : one more click to get the info is it worth than too much counts in profiler tabs ?

From a designer point of view I have not the answer but as a developer I know each click I can avoid is a quick win ;)

**Comment by fabpot** [comment]
The problem I see is that most of the time, the count is not relevant.

**Comment by fabpot** [comment]
Let's close, I still don't think this is useful in most of the cases.

**Pull request closed without merging**
