### PR TITLE
[2.3] * Happy New Year 2015 *

### PR DESCRIPTION
**Pull request by saro0h**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | ~ |
| License | MIT |
| Doc PR | ~ |

### CODE REVIEW

**Comment by stof** [comment]
You missed the update of the LICENSE file at the root of the repo

**Comment by saro0h** [comment]
Done!

**Comment by hhamon** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @saro0h.

**Pull request merged**
