### PR TITLE
Update FileLoader.php

### PR DESCRIPTION
**Pull request by error56**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #...   
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by fabpot** [comment]
Thanks for the PR. As a rule, we do not make "cosmetic" changes in just one file. If we decide to do such changes, we do them on the whole code base to make maintenance easier.

**Comment by error56** [comment]
Oh, ok. (I really want to help with Sf code but all my PRs are bad XD)

**Comment by fabpot** [comment]
@error56 There are not bad, don't worry. I'm just trying to explain how we are working. The biggest issue for us (the maintainers) is that we need to maintain many branches in parallel, so we have rules to make our lives a bit easier.

**Comment by error56** [comment]
Yeah, I know. I read rules at symfony.com, but I feel that I still not understand how it works :worried:

**Pull request closed without merging**
