### PR TITLE
[Lock] Fixed PdoStore::putOffExpiration(), PdoStore::getHashedKey()

### PR DESCRIPTION
**Pull request by pprishchepa**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | It seems no
| Fixed tickets |
| License       | MIT
| Doc PR        |

1. Fixed PDO Statement exception in PdoStore::putOffExpiration():

```
 An exception occurred while executing 'UPDATE lock_keys SET key_expiration = UNIX_TIMESTAMP() + 10, key_token = :token WHERE key_id = :id AND (key_token = :token OR key_expiration <= UNIX_TIMESTAMP())' with params ["dcfc5ff369bc1896563  
  325c2e90478154eb670f6b6ebad3617e946ecb1f81517", "FRJOnftxRwPIgIRVb4EpOIVFwNjTmx0fwkBSTVJdViI="]:                                                                                                                                            
                                                                                                                                                                                                                                              
  SQLSTATE[HY093]: Invalid parameter number    
```

2. Added explicit casting `Key` to `string` in getHashedKey() to avoid error with `strict_types` enabled.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
But we don't enable strict types, so this change is not necessary!

**Comment by PavelPrischepa** [comment]
@nicolas-grekas ok, but what about PdoStore::putOffExpiration() fix?

**Comment by nicolas-grekas** [comment]
I don't get them. Can't we reference the same parameter twice? Can you give a few more hints please?

**Comment by PavelPrischepa** [comment]
Yes, according to http://php.net/pdo.prepare
> You must include a unique parameter marker for each value you wish to pass in to the statement when you call PDOStatement::execute(). You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @PavelPrischepa.

**Pull request merged**
