### PR TITLE
[Yaml] removed deprecation notices on internal constant

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | antonioribeiro/tracker#56, #13306 |
| License | MIT |
| Doc PR | n/a |

Reverting the deprecated notices on `Unescaper::ENCODING` for two reasons:
- The constant is only used internally and nobody ever used it anyway;
- The deprecation notice is ALWAYS triggered when using the YAML component.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by Tobion** [comment]
Hm, I did not find where `Unescaper::ENCODING` is accessed internally?! Could you pinpoint me please?

**Comment by fabpot** [comment]
@Tobion That's the irony :) This constant is not used anymore and nobody should ever have used but still, everyone were having a deprecating notice just because the class was loaded. 

I could have removed the constant altogether, but just in case someone somewhere is using the constant for whatever reasons, I prefer to keep it until 3.0.

**Comment by Tobion** [comment]
But @nicolas-grekas introduced the constant deprecation via a new class because he said the class is only loaded when the constant is actually accessed (lazy class loading). That was the whole idea. So it doesn't actually work?

**Comment by fabpot** [comment]
Right, apparently, that does not always work. So, all the other constants that were using the same mechanism should be checked to see if that works correctly. We are already aware that some do not work, and me or @nicolas-grekas is going to fix them.

**Comment by Tobion** [comment]
Well, either we can rely on lazy constant resolution by php or not. If it only works for some and some not, it would not be deterministic and not reliable as well to work.

**Comment by stof** [comment]
I think it might depend on the optimization level of OPCache. If it is configured to optimize the access to constants, it might need to load them eagerly

**Pull request merged**
