### PR TITLE
[2.6][Validator] Fix Interface reference in docblock

### PR DESCRIPTION
**Pull request by xelaris**
| Q | A |
| --- | --- |
| Fixed tickets |  |
| License | MIT |

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by dosten** [comment]
:+1:

**Comment by aitboudad** [comment]
:+1:  good catch !

**Comment by Tobion** [comment]
:+1:

**Comment by dunglas** [comment]
:+1:

**Comment by Tobion** [comment]
Good catch, thanks @xelaris.

**Pull request merged**
