### PR TITLE
[Debug] deprecate the component in favor of ErrorCatcher

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Keeping the `Debug` and `DebugClassLoader` classes in a standalone component creates a pile of complications that don't have to be. Let's make things simple and move everything to ErrorCatcher.

Fix https://github.com/symfony/recipes/pull/619
Fix https://github.com/symfony/skeleton/pull/177

### CODE REVIEW

**Comment by stof** [comment]
is DebugClassLoader the only debug utility we need to provide ?

**Comment by nicolas-grekas** [comment]
I think so. At least we don't have any other.

**Comment by lyrixx** [comment]
I have just one concern about discoverability. Is this something we should take care of?

**Comment by fancyweb** [comment]
Aren't we regret this in the future if we create new debug utilities? 😕

Also, having the `DebugClassLoader` in a component that was created to render PHP errors / exceptions in different formats does not seem consistent.

**Comment by nicolas-grekas** [comment]
That's still the most pragmatic way to solve the issues that the linked issues describe.
And having a component with debug utilities is just normal (while having a Debug with non-debug things is not.)

**Comment by fancyweb** [comment]
But that still doesn't solve the problem for existing projects, right? 🤔 Their index.php is still referencing the `Debug` component but it's still not required anymore.

**Comment by nicolas-grekas** [comment]
As with any regular deprecations. The issue is different, see linked issues. (Sorry I can't elaborate I'm on mobile and about to be AFK)

**Comment by Tobion** [comment]
I thought the whole point of creating the ErrorCatcher component was to split the debugging part and the part that is required even without debugging turned on.
Otherwise we could have just added the new ErrorRendering inside the debug component and wouldn't have to deprecate anything.

**Comment by nicolas-grekas** [comment]
The main point was to improve and split the rendering part actually. Splitting the debug tools wouldn't be of much interest to me.
So, in the end, in think we need an ErrorHandler component, that contains the debug tools too, but NO rendering at all.
Then rendering would be split in a dedicated component, and we would deprecate Debug and drop ErrorCatcher.

**Comment by yceruto** [comment]
> But that still doesn't solve the problem for existing projects, right? thinking Their index.php is still referencing the Debug component but it's still not required anymore.

@fancyweb we could use the flex command `symfony:sync-recipes` to update the `index.php` file with the new namespace, I know, that will require an extra effort and should be informed as well.

**Pull request closed without merging**
