### PR TITLE
[EventDispatcher] collect called listeners information only once

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #31970
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I've profiled the same app again after applying this patch:

* Before: https://blackfire.io/profiles/f35213c7-d5b5-4eb4-8315-4ad3f24ac9e9/graph
* After: https://blackfire.io/profiles/0c3f3471-e073-4599-ad24-b1ea6766b2fa/graph
* Comparison: https://blackfire.io/profiles/compare/5e4b5a28-2cd7-4f4d-9c0d-cfef1d439f63/graph

Impressive 😱 

image

Thanks a lot Christian!

**Comment by derrabus** [comment]
Can't we target 4.2 with this change?

**Comment by Simperfit** [comment]
if this has been introduced in 4.2 I think this should target 4.2 as this is more than a bugfix !

**Review by Simperfit — APPROVED** [review]

**Comment by javiereguiluz** [comment]
In the past, our policy with performance improvements was:

* Never merge them in older branches. It's tempting to do ... but at the same time, it's too easy to introduce bugs.
* Only merging in "next" branch is great to promote the performance improvements of the new version (and encourage upgrading).

Things can change though if this is considered a bug fix.

**Review by fabpot — APPROVED** [review]

**Review by chalasr — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
(I'd be fine with 4.2 :) )

**Review by lyrixx — APPROVED** [review]
:+1: for 4.2 too

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request closed without merging**
