### PR TITLE
Make use of the nullsafe operator

### PR DESCRIPTION
**Pull request by derrabus**
| Q             | A
| ------------- | ---
| Branch?       | 6.1
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

PHP 8 introduced a nullsafe operator which allows us to simplify some of our code.

I have used a PhpStorm inspection to automate the change. I did some minor adjustments afterwards where the fixer left unnecessary paranthesis or local variables.

### CODE REVIEW

**Review by jderusse — COMMENTED** [review]
I think you can also look for `    $this->logger && $this->logger->`

**Comment by stof** [comment]
I think we should avoid doing that for existing code for now, to avoid merge conflicts when merging between branches.

**Comment by fabpot** [comment]
@stof I think we stopped worrying about this a while ago.
@derrabus Is there any PHP CS Fixer rule that we can enable for this (probably not easy to implement)?

**Comment by derrabus** [comment]
> I think we should avoid doing that for existing code for now, to avoid merge conflicts when merging between branches.

The thing is, since we decided not to merge this kind of change into the oldest stable brach anymore, we would basically never be able to perform this kind of modernization if we didn't do it on the feature branch. I think that the conflicts are managable in this case.

> Is there any PHP CS Fixer rule that we can enable for this (probably not easy to implement)?

Not that I'm aware of, but I could try to implement rules for the cases I've found here.

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @derrabus.

**Pull request merged**
