### PR TITLE
Code style fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | yno
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

Generated by php-cs-fixer (not all the changes it makes are relevant, so I've only committed the intended ones).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
fabbot.io is failing, but on some code that I think was intentionally formatted not to "standard".

**Comment by GrahamCampbell** [comment]
NB This code is in a different part of the file to the area my PR addresses.

**Comment by fabpot** [comment]
Thank you for the PR. The way we fix CS is by running php-cs-fixer on 3.4, then merging in 4.3, 4.3, 5.0, and master. As it is quite tedious to do it via PRs, I've done it.
Also, we cannot fix most of the things in PHPUnitBridge as we need to keep compat with older PHP versions.

**Comment by GrahamCampbell** [comment]
Ah, I see. 👍

**Pull request closed without merging**
