### PR TITLE
Split and clean up tests

### PR DESCRIPTION
**Pull request by localheinz**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

This pull request 

- [x] splits a test and removes a data provider to avoid creating test doubles in data providers

Follows #49244.

💁‍♂️ This follows a brief discussion on Twitter (see https://twitter.com/VotrubaT/status/1622995017756291074). 

I do not expect this to be merged, but in my opinion, creating 

- test doubles
- the system under test (not the case here, but I have observed it elsewhere)

in data providers are anti-patterns.

~~Other than that, I have no idea what we are testing here.~~

### CODE REVIEW

**Comment by alfredbez** [comment]
I'm pretty sure that you forgot to add the words "in dataproviders" in this paragraph:
> [...] in my opinion, creating
> * test doubles
> * the system under test (not the case here, but I have observed it elsewhere)
>
> are anti-patterns.

**Comment by localheinz** [comment]
Thank you, @alfredbez - adjusted the description!

**Review by OskarStark — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Thank you @localheinz.

**Comment by localheinz** [comment]
Thank you, @alfredbez, @nicolas-grekas, and @OskarStark!

**Pull request merged**
