### PR TITLE
typofix - https://github.com/vlajos/misspell_fixer

### PR DESCRIPTION
**Pull request by vlajos**
Fix 3 small typos. Original:  #15494

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1: @vlajos thanks for fixing these issues.

There is no need to change your pull request, but I'd like to tell you that bug fixes should be sent to "the oldest Symfon branch which is still maintained". Until May 2016 that means "Symfony 2.3" (if the error is present in that version). But don't worry, our doc managers will change the branch for you. My comment is only useful for your next contribution. Thanks!

**Comment by javiereguiluz** [comment]
@vlajos another minor comment: when the changes are small (like the three typos fixed in this pull request) there is no need to add anything special in the description of the pull request. However, when the change is large or complex, we ask contributors to add the following table with information for the doc managers:

```
| Q             | A
| ------------- | ---
| Doc fix?      | yes
| New docs?     | no
| Applies to    | all
| Fixed tickets | -
```

Since your pull request doesn't include this table, our review robot called "fabbot" says that there is an error. In any case, don't worry because the proposed changes are minor and our doc managers will understand it right.

If you want to read more about the contribution process, here it is a bried and straight to the point article: http://symfony.com/doc/current/contributing/documentation/overview.html

**Comment by jakzal** [comment]
:+1: 

Status: Reviewed

**Comment by nicolas-grekas** [comment]
Thank you @vlajos.

**Comment by jakzal** [comment]
For some reason the merge didn't trigger closing the ticket.

**Comment by nicolas-grekas** [comment]
It's because I merged on 2.3 :)

**Pull request closed without merging**
