### PR TITLE
[FrameworkBundle] Fix cache warmup in cache:clear for kernel with custom constructor

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no (todo once merged up to master)
| Tests pass?   | yes
| Fixed tickets | #22499,  #22721
| License       | MIT
| Doc PR        | n/a

Making use of the `cache_warmer` service instead of doing it manually, removing the need for wrongly instantiating the kernel by hand.
Protected `CacheClearCommand::warmup()` and `::getTempKernel()` to be deprecated/removed afterward.

Better diff https://github.com/symfony/symfony/pull/22519/files?w=1

### CODE REVIEW

**Comment by Koc** [comment]
relates to #8500

**Comment by chalasr** [comment]
ping @stof is this approach valid regarding your  https://github.com/symfony/symfony/issues/8500#issuecomment-21416489?

**Comment by chalasr** [comment]
Even worst with symfony/flex...

```
$ composer create-project symfony/skeleton:dev-master
$ bin/console cache:clear
```

> PHP Fatal error:  Class App\Kerne_ may not inherit from final class (App\Kernel) in /Users/chalasr/Workspace/tests/flex/var/cache/de_/kernel.tmp on line 4

**Comment by fabpot** [comment]
As of Symfony 3.3, you must use `bin/console cache:clear --without-warmup`

**Comment by chalasr** [comment]
Sure, but this is still broken from 2.7, and not using `--no-warmup` is still supported until 4.0.
If we don't want to fix this bug (or if this approach has drawbacks that I'm not aware of), I would still throw a clear exception saying to use `cache:warmup` separately instead of letting the command break on such an obscure error.

**Comment by ro0NL** [comment]
Seems to fix #22721 as well... probably unintended :)

**Comment by chalasr** [comment]
yes, unintended but not surprising :) the warmup part of `c:c` is full of bugs. Would be nice to know what's wrong here

**Comment by nicolas-grekas** [comment]
But this just replaces "temporary offline" warmups with "online" warmups.
It will break existing apps that do clear cache online. This code exists exaclty for that, which means its kinda supported. Doing this change in 2.7 is dangerous to me.

**Comment by chalasr** [comment]
Let's live with it then, thanks for the explanation.

**Pull request closed without merging**
