### PR TITLE
[Serializer] Support specifying format for DateTimeNormalizer::denormalize

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | symfony/symfony-docs#7063 |

### CODE REVIEW

**Comment by dunglas** [comment]
👍, can you also open a doc PR?

**Comment by teohhanhui** [comment]
I forgot to add test for invalid cases.

**Comment by teohhanhui** [comment]
> can you also open a doc PR?

Where should I add it? I see that the `DateTimeNormalizer` is mentioned in the [Normalizers](https://github.com/symfony/symfony-docs/blob/cea26fc72813c826155338f2a82a7e59af558656/components/serializer.rst#normalizers) section.

/cc @weaverryan

**Comment by xabbuh** [comment]
@teohhanhui I think your addition would fit there quite well (as long as there is no dedicated chapter about all the normalizers we have)

**Comment by teohhanhui** [comment]
Documentation added.

**Comment by teohhanhui** [comment]
Test case added for denormalize format mismatch.

**Comment by fabpot** [comment]
Thank you @teohhanhui.

**Pull request merged**
