### PR TITLE
feat: add context to guardEvent

### PR DESCRIPTION
**Pull request by dvdknaap**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | #49571
| License       | MIT

### CODE REVIEW

**Comment by 94noni** [comment]
reminds me https://github.com/symfony/symfony/issues/40742
read fastly but isnt the same thing?

(edit: also new feature must target the next branch, which now is branch 6.3)

**Comment by dvdknaap** [comment]
> reminds me #40742 read fastly but isnt the same thing?
> 
> (edit: also new feature must target the next branch, which now is branch 6.3)

Yes, that's the same thing.
I've needed it for the company i'm working working for and they are using 5.4 that's why i have added in the 5.4 branch but if needed i can create a new PR for branch 6.3.

**Comment by lyrixx** [comment]
This has already been refused because you must not decide if a transition is enabled by using the context. Context is here only to store metadata. Instead you can store what you need in your subject direclty (even if not persisted to the DB)

**Comment by lyrixx** [comment]
Thanks for your first pull request! I'm sorry that it cannot be merged.

**Pull request closed without merging**
