### PR TITLE
[VarExporter] remove Ignore attribute from setLazyObjectAsInitialized() method

### LINKED ISSUE #54477: [VarExporter] Mapping Expception - Ignore can only be added on methods beginning with "get", "is", "has" or "set".`
### Symfony version(s) affected

6.4.6

### Description

After upgrading symfony/var-exporter from 6.4.4 to 6.4.6 I get an error during my serialization process.

`Ignore on "Proxies\__CG__\App\Entity\Artist::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".`

vendor/symfony/serializer/Mapping/Loader/AttributeLoader.php:172

### How to reproduce

Use Serializer and serialize some objects with relations and setting the context.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 6.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Issues        | Fix #54477
| License       | MIT

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Review by jderusse — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
Wait, this breaks `LazyGhostTraitTest::testNormalization`. :'(

**Comment by xabbuh** [comment]
The only solution I see for now is to disallow normalizing classes using the `LazyGhostTrait` again. :(

**Comment by nicolas-grekas** [comment]
Can't we make Serializer aware of the trait so that it skips those methods?
Alternatively, we might just remove this exception `Ignore can only be added on methods beginning with "get", "is", "has" or "set".`
It's useless to me. Ignore means ignore, not yell.

**Comment by nicolas-grekas** [comment]
Replaced by #54485, thanks for chiming in!

**Pull request closed without merging**
