### PR TITLE
[VarDumper] `HtmlDumper::setDumpHeader()` accepts `null`

### LINKED ISSUE #42272: "Backport type fixes" BC break
**Symfony version(s) affected**: 5.3.4

**Description**
By type hinting a series of (before untyped) methods, this ["Backport type fixes" commit](https://github.com/symfony/symfony/commit/6f6c1a1661a3861a4f0dbd07ac03f62dcd153fba) is breaking backward compatibility to other packages.

**How to reproduce**
Breaks [DebugBar](https://github.com/barryvdh/laravel-debugbar), for example: https://github.com/maximebf/php-debugbar/issues/474

### PR DESCRIPTION
**Pull request by rrpadilla**
| Q             | A
| ------------- | ---
| Branch?       | 5.3 
| Bug fix?      | yes
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #42272 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Shouldn't maximebf/debugbar be patched instead? Can you please them a PR?

**Comment by nicolas-grekas** [comment]
> their code does check for NULL headers when printing so they are a possibility.

I read that in the issue on maximebf/debugbar, found the corresponding line in the code. This makes sense as a big fix now.

Can you please add a test case to back the behavior up?

**Comment by nicolas-grekas** [comment]
I suggested an alternate fix in https://github.com/maximebf/php-debugbar/issues/474

**Comment by barryvdh** [comment]
I fixed it for the time being now: https://github.com/maximebf/php-debugbar/pull/475

I think we needed to reset it for a reason, which isn't currently possible. We're now overriding this method which solves it, but either a nullable check or a reset method would be helpful.

**Comment by derrabus** [comment]
> I think we needed to reset it for a reason, which isn't currently possible.

Do you want to contribute the reset method as a feature for 5.4?

**Comment by nicolas-grekas** [comment]
Actually I prefer making the setter null able as a bugfix :)

**Review by derrabus — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]

**Comment by derrabus** [comment]
Good catch, thanks @rrpadilla.

**Pull request merged**
