### PR TITLE
Added progressive jpeg to mime types guesser

### PR DESCRIPTION
**Pull request by Koc**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | - |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by stof** [comment]
wouldn't it be better to update the list from the Apache list rather than adding a single element in it ?

**Comment by Koc** [comment]
pjpeg is missed in Apache list http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types

**Comment by Koc** [comment]
Closed by accident.

**Comment by fabpot** [comment]
Thank you @Koc.

**Pull request closed without merging**
