### PR TITLE
Add addAttributeValues/removeAttributeValues to EntryManagerInterface

### PR DESCRIPTION
**Pull request by grahl**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no 
| Deprecations? | no
| Tests pass?   | untested
| Fixed tickets | #29433
| License       | MIT
| Doc PR        | N/A

Fix should be self-explanatory based on details in #29433

### CODE REVIEW

**Comment by ro0NL** [comment]
This is a BC break :) https://symfony.com/doc/current/contributing/code/bc.html#changing-interfaces

I suggest to mark them using `@method`

**Comment by chalasr** [comment]
Status: needs work

**Comment by nicolas-grekas** [comment]
The proper way to do this change is to add the method as `@method` annotations on the top of the class. This will trigger a deprecation when DebugClassLoader is used and will mark the method as "should be implemented - will be enforced in 5.0".

Please update :)

**Comment by nicolas-grekas** [comment]
Continued in #30043, thanks @grahl

**Pull request closed without merging**
