### PR TITLE
[WebProfilerBundle] add a way to limit ajax request

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | yes 
| BC breaks?    | no
| Deprecations? | no 
| Tests pass?   | yes
| Fixed tickets | #22688
| License       | MIT
| Doc PR        | symfony/symfony-docs#... 

I need to add the doc entry and the reproducer to test that everything is ok.

### CODE REVIEW

**Comment by Simperfit** [comment]
Status: Needs Work

**Comment by javiereguiluz** [comment]
I don't like adding a new config option for this not-so-important feature. What if we set a common sense limit (e.g. `100` requests) and when you get MAX + 1 requests, the first one is dropped and so on.

**Comment by ostrolucky** [comment]
I like idea about cutting of oldest requests, rather than stopping flow of new ones

**Comment by Simperfit** [comment]
@javiereguiluz I guess it makes more sens.

@ostrolucky Yes, why not I didn't think of that in the first place but it could be nice too.

**Comment by Simperfit** [comment]
@javiereguiluz so even if it's not the requested feature, is it really worth it to add this non-configurable limit ? I guess we could let it configurable, it make sens to me too WDYT ?

**Comment by fabpot** [comment]
Please, don't make it configurable. It does not make sense.

**Comment by Simperfit** [comment]
So we agree for a limit like 100 request, after that we drop the olds one to have the new one ?

**Comment by fabpot** [comment]
LGTM

**Comment by Simperfit** [comment]
Status: Needs Review

**Comment by Simperfit** [comment]
@fabpot @javiereguiluz @ostrolucky could you please review this one ?

**Comment by fabpot** [comment]
It looks good to me. The current patch looks like a bug fix now. So, I would merge it into 2.7 instead of master. WDYT?

**Review by fabpot — APPROVED** [review]

**Comment by Simperfit** [comment]
I agree, let's look on what other are thinking and ill rebase it.

**Comment by fabpot** [comment]
I think you can go ahead and rebase on 2.7.

**Review by nicolas-grekas — APPROVED** [review]
for 2.7

**Comment by Simperfit** [comment]
rebased.

**Comment by fabpot** [comment]
Thank you @Simperfit.

**Comment by nicolas-grekas** [comment]
@Simperfit I did not manage to merge this change into 3.4, as the JS has changed too much, please submit another PR for 3.4. Sorry about that.

**Comment by Simperfit** [comment]
i'm doing it

2018-02-22 12:00 GMT+01:00 Nicolas Grekas <notifications@github.com>:

**Review by pmoubed — COMMENTED** [review]
This code is broken for v2.7.42

overview:1306 Uncaught TypeError: Cannot read property 'count' of undefined
    at Object.renderAjaxRequests (overview:1306)
    at Sfjs.load.maxTries (overview:1306)
    at overview:1306
    at XMLHttpRequest.xhr.onreadystatechange (overview:1306)
renderAjaxRequests @ overview:1306
Sfjs.load.maxTries @ overview:1306
(anonymous) @ overview:1306
xhr.onreadystatechange @ overview:1306
XMLHttpRequest.send (async)
request @ overview:1306
load @ overview:1306
(anonymous) @ overview:1306
(anonymous) @ overview:1306
overview:1306 Uncaught TypeError: Cannot read property 'count' of undefined
    at Object.renderAjaxRequests (overview:1306)
    at XMLHttpRequest.<anonymous> (overview:1306)

**Pull request merged**
