### PR TITLE
Add support to ValueToDuplicatesTransformer for comparing objects

### PR DESCRIPTION
**Pull request by lookbadgers**
It's possible when using the \Symfony\Component\Form\Extension\Core\Type\RepeatedType the field being duplicated contains an object.
This checks if the values being compared are both objects and compares the __toString() method of the objects, if they are not equal it throws a TransformationFailedException.

| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | 
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by xabbuh** [comment]
IMO this is not the right way to fix the issue you are experiencing. If we want to support this use case, the solution will be to allow to pass a callback that does the actual comparison logic (i.e. return `true` or `false`).

**Comment by lookbadgers** [comment]
That would work, but it would be better if when using `RepeatedType` you could specify the `ValueToDuplicatesTransformer` to use instead.  

The original solution still holds the advantage of not needing any extra configuration.

**Comment by nicolas-grekas** [comment]
:-1: as is on 2.7: that's a behavior change, and not all objects are allowed to be casted to string. @xabbuh's suggestion might be better, as a new feature on 3.4 for sure.

**Comment by HeahDude** [comment]
Already handled by https://github.com/symfony/symfony/pull/21608.

**Pull request closed without merging**
