### PR TITLE
[DX][Config] Changed return type definition for some methods of NodeDefinition

### PR DESCRIPTION
**Pull request by Strate**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #12280 |
| License | MIT |

Discussed in #12280

### CODE REVIEW

**Comment by fabpot** [comment]
Anyone with an IDE willing to validate this one? @Haehnchen @symfony/deciders

**Comment by Rvanlaak** [comment]
I thought `@return self` is preferred by IDEs above returning the object, but was unable to find back the source about that. The only thing phpDoc tells us is that `@return $this` is [typically used by fluent interfaces](http://www.phpdoc.org/docs/latest/guides/types.html#keywords).

**Comment by jakzal** [comment]
@Rvanlaak we've discussed this already, see https://github.com/symfony/symfony/issues/12280#issuecomment-72509920 to learn why we can't add it to all the methods. 

This PR alters type hints where it makes sense. 

I'll test it in the evening, unless someone does it before me.

**Comment by WouterJ** [comment]
The classname can be omitted, as `$this` is equal to it, isn't it?

**Comment by Strate** [comment]
@WouterJ The class name is fallback for IDEs, which does not recognize `$this` as return type.
@Rvanlaak `return self` is not the same thing as `return $this`. As you can see, all methods, where I have changed return type definition, actuall returning `$this`.

**Comment by stof** [comment]
This is related to https://github.com/symfony/symfony/issues/11577, with the discussion starting in https://github.com/symfony/symfony/pull/11523

Someone using Netbeans should check whether it supports these return types properly now. If it does, we should then improve the phpdoc on the whole Symfony codebase, not only on a few classes (and doing it in 2.3 to help people using the LTS too and keep the branch merging maintainable)

**Comment by jakzal** [comment]
I confirm it improves autocompletion in PhpStorm. 

Obviously it only improves it when node level is the same. For example `$arrayNode->isRequried()->add` will suggest ArraNodeDefinition methods, while it wasn't doing it before.

As soon as `end()` is used, autocompletion breaks, but as explained earlier we cannot do anything about it.

**Comment by Haehnchen** [comment]
some tricky java hacks, but i am able to overwrite the `end` phptypes in PhpStorm by the Symfony plugin. Follow external issue: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/384

**Comment by fabpot** [comment]
Thank you @Strate.

**Pull request closed without merging**
