### PR TITLE
[HttpClient] Fix collecting data non-late for the profiler

### LINKED ISSUE #49096: [http-client] No longer showing requests in the http_client profiler
### Symfony version(s) affected

6.2.5

### Description

In 6.2.2 I was getting trace information in the http_client profiler to run tests on so I could check some requests were made. In 6.2.5, the profiler no longer has this data.

### How to reproduce

Using `$collector = $this->getProfile()->getCollector('http_client')` in my test, I loop through each client. The clients have an empty array in the `trace` property now.

### Possible Solution

Investigating

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #49096
| License       | MIT
| Doc PR        | -

@silverbackdan @pforesi could you please confirm that this fixes both your use cases?

### CODE REVIEW

**Comment by silverbackdan** [comment]
Really sorry but I do have gaps in my knowledge on how I bring in this change into my application to test the fix. I'm using the latest Symfony version, would you be find enough to let me know how to bring the change into my application and I'll run my tests again.

**Comment by nicolas-grekas** [comment]
The easiest way might be to just replace the file in your vendor directory by copy/pasting the one attached to this PR.

**Comment by silverbackdan** [comment]
Thanks @nicolas-grekas but I'm afraid the problem still persists

**Comment by silverbackdan** [comment]
The problem is in that file though, as if I update to the latest version and replace that file from the version before I do not get the error

**Comment by silverbackdan** [comment]
I've done some dumping in the function and I think the issue is that with either of the new updates, the function is called twice. I can confirm that reverting just this file back to the previous version causes no issues so it is related to this change.

**Comment by silverbackdan** [comment]
`doCollect` is called twice with `reset` as `true`
It looks like it's being triggered from an event listener.

**Comment by silverbackdan** [comment]
I don't know why, but in my tests `ProfilerListener::onKernelTerminate` is being called twice in behat/behatch tests. I'm not sure where this originates from.

**Comment by silverbackdan** [comment]
Sorry for many messages and deleted ones. In the profiler listener `onKernelTerminate` there are 2 profiles on my test requests. This causes `saveProfile` to be called twice which seems to filter down and then make `doCollect` to be called twice too.

In my case I seem to have requests for these.
```
_api_/dummy_components/{id}{._format}_delete
_api_/page_data_with_components/{id}{._format}_get
```

So perhaps in my code somewhere I am performing a sub-request which means that the trace would be cleared?

**Comment by nicolas-grekas** [comment]
No worries :)
Can you try the updated patch please?

**Comment by silverbackdan** [comment]
Looks like it works :)

**Comment by silverbackdan** [comment]
Will this be in 6.2.6? I'll leave a conflict in my composer for 6.2.5 just so I don't get failing tests :)

**Comment by nicolas-grekas** [comment]
Of course :)

**Comment by silverbackdan** [comment]
Thanks as always @nicolas-grekas

**Comment by amalricBzh** [comment]
Hello,
On a SF 5.4 micro-service application, with: 
- http-client 5.4.19
- web-profiler-bundle : 5.4.19
=> Everything is ok, The profiler collect HTTP calls data.

But with http-client 5.4.20 wich include this PR => It's KO, the web profiler doesn't collect any HTTP Client calls, the "Http Client" tab is empty 😢 .

**Comment by fancyweb** [comment]
Hello, it has been fixed in https://github.com/symfony/symfony/pull/49301. The patch should be released at the end of the month.

**Pull request merged**
