### PR TITLE
[DomCrawler] improve failure messages of the CrawlerSelectorTextContains constraint

### LINKED ISSUE #33551: Could assertSelectorTextContains return current value in WebTestCase?
Right now when test fails there is information about selector and expected value, but there is no information about actual value from test. 

> Matches selector "#selector" and has a node matching selector "#selector" with content containing "expected_value"

I would like to now, what was the actual value of the test which was found in that _#selector_ to get more details why it failed.

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 5.x
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #33551, #37757
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
This will need a PR on lower branches, to relax the assertions when fwb is used with domcrawler ^5.3

**Comment by nicolas-grekas** [comment]
This will need a PR on lower branches, to relax the assertions when fwb is used with domcrawler ^5.3

**Comment by xabbuh** [comment]
That's true, the alternative would be to merge this in a lower branch. But since this is not a bugfix I think we should not do that.

**Comment by fabpot** [comment]
If that's easier for us, let's do that change in 4.4?

**Comment by xabbuh** [comment]
rebased on 4.4

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
