### PR TITLE
[Yaml] Fix error handling on ini file parsing

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Should make travis green again on master.
/cc @xabbuh

### CODE REVIEW

**Review by xabbuh — APPROVED** [review]
:+1:

**Comment by javiereguiluz** [comment]
👍

**Comment by xabbuh** [comment]
Thank you @chalasr.

**Comment by GuilhemN** [comment]
This part of the code supports things that shouldn't be. 
e.g:
```yml
"foo"
bar
```
is not valid.
```yml
bar
"foo"
```
is valid but should be parsed as `"bar\n\"foo\""` and not `"bar\nfoo`.

This could be fixed by updating some things:
- first, trim the empty lines at the beginning of the value
- if the value begins with `*`, `{`, `[`, `]` or `}`  throw an exception (correct reference and correct inline mappings/sequences are parsed earlier)
- (if the value begins with `&`, trim it? or throw an exception as it does not really make sense?)
- if the value begins with `!`, trim the tag and process the value without it
- if the value begins with `'` or `"`, pass the entire value to `Inline::parse()` but trim the last lines if they are empty.
- otherwise, if the value is not special, threat the value "manually":
```php
foreach ($lines as $line) {
    if ($this->preg_match('/[ \t]+#/', $line, $match, PREG_OFFSET_CAPTURE)) {
        $line = substr($line, 0, $match[0][1]);
    }

    if ('' === trim($line)) {
        $value .= "\n";
        $previousLineWasNewline = true;
    } elseif ($previousLineWasNewline) {
        $value .= trim($line);
        $previousLineWasNewline = false;
    } else {
        $value .= ' '.trim($line);
        $previousLineWasNewline = false;
    }
}
```

**Pull request merged**
