### PR TITLE
[HttpClient] Preserve the case of headers when sending them

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #32819
| License       | MIT
| Doc PR        | -

Some hosts are case sensitive, let's present headers in the submitted form.

### CODE REVIEW

**Comment by fabpot** [comment]
What about `ETag`?

**Comment by javiereguiluz** [comment]
@nicolas-grekas as you said here https://github.com/symfony/symfony/issues/32819#issuecomment-516562159

* In HTTP 1, headers should be lowercase _(but some APIs don't respect that)_
* In HTTP/2, headers can only be lowercase

So, could we leave headers as-is when using HTTP 1 (no strtolower, no ucwords, no changes whatsoever) and just apply `strtolower()` unconditionally when using HTTP/2? Thanks.

**Comment by nicolas-grekas** [comment]
Got it, see also comments on the linked issue.

**Comment by nicolas-grekas** [comment]
> So, could we leave headers as-is when using HTTP 1 (no strtolower, no ucwords, no changes whatsoever) and just apply strtolower() unconditionally when using HTTP/2? Thanks.

That is not possible, because the protocol can be decided automatically.
The only sensible way is to preserve the input case.
That will break normalization, but since this is internal concern, there should be ways around.

**Comment by nicolas-grekas** [comment]
PR updated, ready.

**Review by javiereguiluz — APPROVED** [review]

**Pull request merged**
