### PR TITLE
[console][ArrayInput] avoid return array value for getFirstArgument.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | #14116 |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by mpdude** [comment]
Can someone explain me why this is the right fix?

I mean, why shouldn't it return an array if the first argument *is* an array?

**Comment by aitboudad** [comment]
@mpdude https://github.com/aitboudad/symfony/blob/console_array_input/src/Symfony/Component/Console/Input/InputInterface.php#L24

**Comment by xabbuh** [comment]
@aitboudad Afaics, the first argument is not necessarily the command being executed. For example, the `CommandTester` just [appends it to the existing input parameters](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Console/Tester/CommandTester.php#L60-65) when no `command` key is given.

**Comment by xabbuh** [comment]
So, if the `filename` argument were not defined as an array (or if another non-array argument were added in the future), `getFirstArgument()` would return that argument and not the command name.

**Comment by aitboudad** [comment]
@xabbuh yes I know :) in this PR I'm not attempts to return the command name as first argument but just to make ArrayInput compatible with InputInterface.

**Comment by fabpot** [comment]
I agree with @mpdude, I don't think this is the right fix.

**Comment by fabpot** [comment]
What about @14205?

**Comment by mpdude** [comment]
Updated #14205.

**Comment by aitboudad** [comment]
what do you  think to change ```getFirstArgument``` return type to  mixed ?
```php
    /**
     * @return mixed
     */
    public function getFirstArgument();
```

**Comment by mpdude** [comment]
I think that would be honest :-)

**Comment by fabpot** [comment]
closing in favor of #14205

**Pull request closed without merging**
