### PR TITLE
[AssetMapper] fix tests on Windows

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
There is a temp file created that also needs to be removable when cleaning up in the `tearDown()` method: https://ci.appveyor.com/project/fabpot/symfony/builds/50521173#L1064

**Review by alexandre-daubois — APPROVED** [review]

**Comment by smnandre** [comment]
Thank you @xabbuh this test really broke my mind  (https://github.com/symfony/symfony/pull/58141#pullrequestreview-2274504300)

I'm not sure exacty "when" this temp file is created... my guts say there is something wrong with the /.! format that mess with the Finder list of files, and we end up trying to remove a directory before its content, but until now my guts have been wrong on this so ... 😅 

Notes i made trying to debug this:

```
1) Symfony\Component\AssetMapper\Tests\ImportMap\RemotePackageStorageTest::testSaveThrowsWhenFailing
Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "C:\Users\appveyor\AppData\Local\Temp\1/.!!8wd\assets\acme\vendor\module_specifier\modF8A2.tmp": unlink(C:\Users\appveyor\AppData\Local\Temp\1/.!!8wd\assets\acme\vendor\module_specifier\modF8A2.tmp): Permission denied
C:\projects\symfony\src\Symfony\Component\Filesystem\Filesystem.php:197
C:\projects\symfony\src\Symfony\Component\Filesystem\Filesystem.php:185
C:\projects\symfony\src\Symfony\Component\Filesystem\Filesystem.php:185
C:\projects\symfony\src\Symfony\Component\Filesystem\Filesystem.php:185
C:\projects\symfony\src\Symfony\Component\Filesystem\Filesystem.php:185
C:\projects\symfony\src\Symfony\Component\Filesystem\Filesystem.php:185
C:\projects\symfony\src\Symfony\Component\Filesystem\Filesystem.php:153
C:\projects\symfony\src\Symfony\Component\AssetMapper\Tests\ImportMap\RemotePackageStorageTest.php:35
--
```

So the exception is thrown during the test teardown (RemotePackageStorageTest.php)


https://github.com/symfony/symfony/blob/cc11de0fa7bf38a40bd0dc8f723ed561f850d186/src/Symfony/Component/AssetMapper/Tests/ImportMap/RemotePackageStorageTest.php#L33-L36

This method calls the Filesystem remove() method (with a directory path)

https://github.com/symfony/symfony/blob/cc11de0fa7bf38a40bd0dc8f723ed561f850d186/src/Symfony/Component/Filesystem/Filesystem.php#L153

The remove then call the doRemove with the directory and recursive "false" 

And after some iterations of 

https://github.com/symfony/symfony/blob/cc11de0fa7bf38a40bd0dc8f723ed561f850d186/src/Symfony/Component/Filesystem/Filesystem.php#L184-L185

We arrive at the final exception

https://github.com/symfony/symfony/blob/cc11de0fa7bf38a40bd0dc8f723ed561f850d186/src/Symfony/Component/Filesystem/Filesystem.php#L196-L198

So if you have any way to know precisely when it is created i'd be very interested to know

**Comment by xabbuh** [comment]
I just had another look and found the root issue to be located in the Filesystem component. In the `dumpFile()` method a temporary file is used which reuses the permissions of the target file leading to it not being removed on Windows filesystems afterwards if it has no write permissions: #58185

**Comment by xabbuh** [comment]
so we can revert this now: #58302

**Pull request merged**
