### PR TITLE
[HttpKernel] Do not normalize the kernel root directory path #15567

### PR DESCRIPTION
**Pull request by leofeyer**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15474 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by fabpot** [comment]
:+1: What about doing that on 2.3 as this is a bug fix? (no need to create another PR, as we can easily switch the branch when merging)

**Comment by leofeyer** [comment]
Sure. I have just realized that version 2.3 has not yet reached its end of life. My bad.

**Comment by fabpot** [comment]
ping @symfony/deciders

**Comment by Tobion** [comment]
:+1: I think the normalization should only be done internally when really necesssary to work with (e.g. in https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Filesystem/Filesystem.php#L332 ) it which does not seem to be the case here.

**Comment by fabpot** [comment]
Thank you @leofeyer.

**Pull request closed without merging**
