### PR TITLE
[Notifier] Unify composer.json

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | --
| License       | MIT

Most of the other bridges use this "syntax"

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by fabpot** [comment]
Do we have this discrepancy only on Notifier components? If not, can we fix them all here?

**Review by xabbuh — APPROVED** [review]

**Comment by OskarStark** [comment]
> Do we have this discrepancy only on Notifier components? If not, can we fix them all here?

Let me check

**Comment by OskarStark** [comment]
Only in Notifier

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @OskarStark.

**Pull request merged**
