### PR TITLE
[DI][2.7] Include dynamic services in alternatives

### PR DESCRIPTION
**Pull request by ro0NL**
| Q | A |
| --- | --- |
| Branch? | 2.7 |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any |
| License | MIT |
| Doc PR | reference to the documentation PR, if any |

### CODE REVIEW

**Comment by ogizanagi** [comment]
Status: Reviewed

**Comment by ro0NL** [comment]
This will include possible private services as well, which you are still allowed to `get`.

**Comment by ogizanagi** [comment]
> This will include possible private services as well, but those are still allowed to get.

@ro0NL : And it was already the case anyway, isn't it ?

**Comment by ro0NL** [comment]
I guess it depends.. if it was already initialized yes/no. This will include by definition, not by state.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by nicolas-grekas** [comment]
Thank you @ro0NL.

**Pull request merged**
