### PR TITLE
[Form][2.8] Upgrade Guide: Describe how to build forms after deprecations

### PR DESCRIPTION
**Pull request by sh4ka**
| Q | A |
| --- | --- |
| Branch? | 2.8 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #18662 |
| License | MIT |
| Doc PR |  |

### CODE REVIEW

**Comment by xabbuh** [comment]
Duplicate of #20204?

**Comment by sh4ka** [comment]
I thought that the deprecations were introduced in 2.8, but maybe you are right.

**Comment by fabpot** [comment]
Thanks for your contribution, but #20204 is indeed good as is as I can merge in any branch (you're right, it should be merged in 2.8).

**Comment by sh4ka** [comment]
Perfect then. Good to know. It is hard to have the full scope of the existing WIP in the project.

**Comment by fabpot** [comment]
I know, this is also very difficult for us :)

**Pull request closed without merging**
