### PR TITLE
[Workflow] do not emit not needed guard events

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #23677
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by lyrixx** [comment]
Thanks for this PR.
I like it but now the real logic (a transition is enabled if all places before it,  contain a token) exists at two different place (in `getEnabledTransitions` and `can` method).
If you find a way to share this logic without adding some complexity it will be awesome.

Anyway I'm :+1:

**Comment by fmata** [comment]
This can not be considered as a bugfix ?
Do you have an idea to avoid this current behaviour in 3.3.* ?

**Comment by lyrixx** [comment]
> This can not be considered as a bugfix ?

IMHO this is not a bug fix as the current behavior (before this PR) is not buggy. This is just a performance optimization.

> Do you have an idea to avoid this current behaviour in 3.3.* ?

it's not possible.

**Review by Simperfit — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request merged**
