### PR TITLE
[Translation][MessageCatalogue] use define whenever possible.

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets | ~ |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by stof** [comment]
why adding more method calls for the same thing ?

**Comment by aitboudad** [comment]
@stof I made this change just to avoid duplication of code

**Comment by stloyd** [comment]
:-1: as you add overhead (little by still) for no reason as those are calls to internal variable. We should avoid it same as we avoid using `sizeof()` instead of `count()`...

**Comment by aitboudad** [comment]
@stloyd agreed, so let close it :)

**Pull request closed without merging**
