### PR TITLE
[Cache] AbstractAdapter: avoid an extra call to ApcuAdapter::isSupported

### PR DESCRIPTION
**Pull request by dunglas**
| Q | A |
| --- | --- |
| Branch? | master |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
You can even go one step further & cache all `*::isSupported` calls in static props

**Comment by dunglas** [comment]
@nicolas-grekas it is usually called several times during the same request?

**Comment by nicolas-grekas** [comment]
Yes, once per namespace (ie per cache pool)

**Comment by dunglas** [comment]
@nicolas-grekas updated to use `static` properties.

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request closed without merging**
