### PR TITLE
[Console] Add a Compiler Pass to Easily Add Helpers

### PR DESCRIPTION
**Pull request by chrisguitarguy**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #15258 |
| License | MIT |
| Doc PR | - |

### CODE REVIEW

**Comment by iltar** [comment]
I find helpers extremely annoying on the console. There's virtually no way to get proper autocomplete. When people will start adding custom helpers, I fear it becomes a big mess where nobody knows what to use when and what's even available.

**Comment by Tobion** [comment]
I agree. The new console utilities like ProgressBar, ProgressIndicator and Table are not using the helper stuff anyway. So IMO we should deprecate the helper functionality in 3.1.

**Comment by ogizanagi** [comment]
Agree too. Plus you can already add helpers easily from the `Application` instance in `app/console`:

````php
$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$myHelper = ...; // Create the helper instance or get it from the Container
$application->getHelperSet()->set($myHelper);
```

The only benefit of such a compiler pass would be lazy-loading or third-party bundles being able to add helpers. 
I don't think console helpers need lazy-loading due to what they generally achieve, and third party bundles can already add helpers if it is really needed through the trick you explained in https://github.com/symfony/symfony/issues/15258#issuecomment-145248921:

```php
use Symfony\Bundle\FrameworkBundle\Console\Application as FrameworkApplication;
use Symfony\Component\Console\Application;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
    /**
     * {@inheritdoc}
     */
    public function registerCommands(Application $application)
    {
        if ($application instanceof FrameworkApplication) {
            $container  = $application->getKernel()->getContainer()
            $application->getHelperSet()->set($container->get('your_helper'));
        }

        parent::registerCommands($application);
    }
}
```

**Comment by fabpot** [comment]
Closing for the reasons explained by @iltar and @Tobion

**Pull request closed without merging**
