### PR TITLE
Added translations in validator for Serbian Cyrillic

### LINKED ISSUE #30188: [Validator] Add the missing translations for the Serbian (Cyrillic) ("sr_Cyrl") locale
If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken. Thanks!

-----

**Symfony version(s) affected**: 3.4

**Description**

The `src/Symfony/Component/Validator/Resources/translations/validators.sr_Cyrl.xlf` file is missing the following translations compared to the original English file:

```xml
<trans-unit id="78">
    <source>An empty file is not allowed.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="79">
    <source>The host could not be resolved.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="80">
    <source>This value does not match the expected {{ charset }} charset.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="81">
    <source>This is not a valid Business Identifier Code (BIC).</source>
    <target>...</target>
</trans-unit>
<trans-unit id="82">
    <source>Error</source>
    <target>...</target>
</trans-unit>
<trans-unit id="83">
    <source>This is not a valid UUID.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="84">
    <source>This value should be a multiple of {{ compared_value }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="85">
    <source>This Business Identifier Code (BIC) is not associated with IBAN {{ iban }}.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="86">
    <source>This value should be valid JSON.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="87">
    <source>This collection should contain only unique elements.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="88">
    <source>This value should be positive.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="89">
    <source>This value should be either positive or zero.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="90">
    <source>This value should be negative.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="91">
    <source>This value should be either negative or zero.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="92">
    <source>This value is not a valid timezone.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="93">
    <source>This password has been leaked in a data breach, it must not be used. Please use another password.</source>
    <target>...</target>
</trans-unit>
<trans-unit id="94">
    <source>This value should be between {{ min }} and {{ max }}.</source>
    <target>...</target>
</trans-unit>
```

**Possible Solution**

A Pull Request must be sent to Symfony's 3.4 branch adding the missing translations.

Don't forget to take a quick look at the existing translations to use the same tone and style in the new translations.

**Additional context**

You have two ways to make this contribution:

**1)** Use the GitHub web interface to edit the translation and make the pull request.

  * It's recommended if you don't have any experience using Git in the terminal.
  * To do so, [click here](https://github.com/symfony/symfony/edit/3.4/src/Symfony/Component/Validator/Resources/translations/validators.sr_Cyrl.xlf) to edit the translation file and follow the given steps to create the pull request.

**2)** Use your own editor to edit the translation file and use the Git commands in the terminal to make the pull request.

  * It's the most common way to contribute to Symfony.
  * You need to download Symfony's code to your computer and follow the steps explained [in this contribution guide](https://symfony.com/doc/current/contributing/code/patches.html)

-----

If you need any help during the contribution process, visit the `#contribs` channel on [Symfony Slack](https://symfony.com/slack) where we'll be happy to help you.

### PR DESCRIPTION
**Pull request by KristijanKanalas**
Resolves #30188

Should be able for merges in branches >3.4, not sure how to do that tho :(

### CODE REVIEW

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @KristijanKanalas.

**Comment by fabpot** [comment]
Merges onto the other branches is done by the core team, you don't need to do anything.

**Comment by KristijanKanalas** [comment]
Okay, thank you 🙂 This was my first contribution, I hope I can help in the future too.

**Comment by fabpot** [comment]
@KristijanKanalas Great first contribution! Thank you.

**Pull request merged**
