### PR TITLE
Fixed generation mistake in changelog

### PR DESCRIPTION
**Pull request by chalasr**
| Q             | A
| ------------- | ---
| Branch?       | "master"
| Fixed tickets |n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by javiereguiluz** [comment]
:+1:

**Comment by sstok** [comment]
I don't think Carson bot likes the short questioner :)

Status: reviewed

**Comment by chalasr** [comment]
@sstok The issue is that carson doesn't check if both "yes" and "no" are present in the corresponding columns, and since I wanted to submit this PR quickly, I do not took the time to cleanup the template at first :)

**Comment by fabpot** [comment]
Thank you @chalasr.

**Pull request merged**
