### PR TITLE
[Cache] document igbinary changes in the Cache component

### PR DESCRIPTION
**Pull request by xabbuh**
| Q             | A
| ------------- | ---
| Branch?       | 7.2
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Issues        | 
| License       | MIT

### CODE REVIEW

**Comment by xabbuh** [comment]
Since using the igbinary extension is no longer the default when it is installed I wonder if we need to introduce a config option in FrameworkBundle to make it possible to easily re-enable it.

**Comment by fabpot** [comment]
We used to support the YAML PECL package in addition/replacement of our pure PHP YAML package. We stopped supporting it after a few years because of the behavioral differences between the two. This sounds like the same story.

**Comment by xabbuh** [comment]
@fabpot Would you suggest deprecating the igbinary support in the `DefaultMarshaller` entirely?

**Review by nicolas-grekas — APPROVED** [review]
I would keep things as is for now (no config option, no deprecation) and see how the community moves forward on the topic (extension maintenance, etc.)

**Review by javiereguiluz — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Pull request merged**
