### PR TITLE
[Security][Validator] Check translations for Czech

### PR DESCRIPTION
**Pull request by wallach-game**
| Q             | A
| ------------- | ---
| Branch?       | 5.4
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Issues        | Fix (https://github.com/symfony/symfony/issues/54552) 
| License       | MIT

Checked the czech translation

### CODE REVIEW

**Comment by wallach-game** [comment]
@chalasr its failing because of some redis test. 

```
Time: 00:57.463, Memory: 8.00 MB
There was 1 failure:
1) Symfony\Component\Lock\Tests\Store\RedisArrayStoreTest::testBackwardCompatibility
Failed asserting that false is true.
C:\projects\symfony\src\Symfony\Component\Lock\Tests\Store\AbstractRedisStoreTestCase.php:49
FAILURES!
Tests: 178, Assertions: 201, Failures: 1, Skipped: 124.
KO src\Symfony/Component/Lock
PHPUnit 9.6.21 by Sebastian Bergmann and contributors.

```
 any idea how to fix it ?

**Comment by nicolas-grekas** [comment]
There are also translation to fix in https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Validator/Resources/translations/validators.cs.xlf, could you please have a look?

**Comment by wallach-game** [comment]
I will check the translations and i can translate other messages, but any idea how to fix the build error ?

**Comment by nicolas-grekas** [comment]
You can ignore it I think.

**Comment by nicolas-grekas** [comment]
Thank you @wallach-game.

**Pull request merged**
