### PR TITLE
Update SessionInterface.php

### PR DESCRIPTION
**Pull request by rwitchell**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | -
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

IDE is complaining the method does not exist. Added method to SessionInterface. Change can be merged up to master.

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. 
I'm afraid it is a BC break to add a method to an interface. You cannot target 2.7 branch for this PR. 

Also, this is not a bugfix, it is a new feature.

**Comment by Koc** [comment]
Duplicates #22395 and many other

**Comment by nicolas-grekas** [comment]
You can type hint `Session` instead of the interface - I doubt there is real competition for other implementation of `SessionInterface`, isn't it?

**Comment by sstok** [comment]
I think the main reason for typehinting the SessionInterface is the ability to mock or use an adapter for legacy applications.

What if we introduce an interface like `SessionWithFlashBagInterface` that extends `SessionInterface`? This would make type hinting possible for and not forcing FlashBag support upon every implementation.

**Comment by fabpot** [comment]
Closing as this has been discussed a lot already and cannot be done for BC reasons. Note that even without BC issues, this addition was rejected back then.

**Pull request closed without merging**
