### PR TITLE
Display php info for extra versions in travis

### PR DESCRIPTION
**Pull request by jderusse**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | -
| License       | MIT
| Doc PR        | -

Display the PHP info of all tested versions when the test-suite use several versions of PHP

Helps to troubleshoot  https://github.com/symfony/symfony/pull/38818#issuecomment-716575154

### CODE REVIEW

**Comment by Nyholm** [comment]
I've found info outputs like this super helpful in my CI. I do them for PHP versions and versions of static tools.

**Comment by nicolas-grekas** [comment]
Unrelated to the issue, here is the fix: https://github.com/symfony/symfony/commit/255f1e3478caf9b8e8dfb843e448074bce594949

**Comment by jderusse** [comment]
Hm I never said this PR was fixing the linked issue.

Displaying the info of PHP 7.2, when running the "5.6 + 7.0 + 7.1 + 7.2" test-suite is useless. 
The purpose of this PR was to display the PHP info of all tested versions (and not only the last version)

If we don't need this, then I suggest to remove this step.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by jderusse** [comment]
Please don't merge it before CI green. I'm not 100% confident with the syntax

**Comment by nicolas-grekas** [comment]
Thank you @jderusse.

**Pull request merged**
