### PR TITLE
[3.0][EventDispatcher][Event] removed deprecated methods

### PR DESCRIPTION
**Pull request by aitboudad**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Fixed tickets | ~ |
| Tests pass? | yes |
| License | MIT |

### CODE REVIEW

**Comment by hhamon** [comment]
Can you please also update the PR to remove the `setName` and ` getName` methods as well? I don't know if removing these two methods has lots of impact elsewhere or not.

**Comment by fabpot** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @aitboudad.

**Pull request merged**
