### PR TITLE
broken or bad merge

### PR DESCRIPTION
**Pull request by cordoval**
cc @sstok

### CODE REVIEW

**Comment by cordoval** [comment]
what is wrong with composer cc @stof ?

**Comment by sstok** [comment]
Please don't put a cc or mention in the commit message ;)

**Comment by cordoval** [comment]
closing then sorry about this

**Comment by xabbuh** [comment]
@cordoval Has this been replaced by another pull request or has it been fixed somewhere?

**Comment by cordoval** [comment]
Christian

yes i believe so, but i don't have it handy, i bet we will see it fixed eventually (I hope so)
I applaud your effort to get into core and work very hard, these days the top people are very absent and these problems are starting to happen.

**Comment by sstok** [comment]
#15271

**Pull request closed without merging**
