### PR TITLE
Refactor/use constructor promotion 6.2

### PR DESCRIPTION
**Pull request by TheKhanj**
Just a simple refactor :)

Now that we only support php8 it's nice to use constructor promotion as well.
| Q             | A
| ------------- | ---
| Branch?       | 6.2
| Bug fix?      | no
| New feature?  | no 
| Deprecations? | no 
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Review by derrabus — APPROVED** [review]
LGTM, but it's not a bugfix. We should target 6.3.

**Comment by TheKhanj** [comment]
Pardon me, I didn't know which version to target :)

**Comment by nicolas-grekas** [comment]
I'm going to be :-1: here because this is not needed and also because I suspect that there are way more classes that could be candidates for CPP. If we want to go full CPP, it should be done automatically.
(But it's not 100% sure we want to, because that might create maintenance overhead dealing with merge conflicts.)

Thanks for submitting.

**Comment by stof** [comment]
I agree with @nicolas-grekas here. It is fine to use CPP for new code in the 6.3 branch, but I don't see the benefits of migrating existing classes while I see the potential for merge conflicts during maintenance merges.

**Comment by derrabus** [comment]
We rarely introduce new constructor parameters in lower branches because such a change is usually not needed for pure bugfixes. Also, a constructor signature change has BC implications we'd want to avoid in bugfix releases.

I do see a benefit of modernizing existing code with CPP. But I see Nicolas' point that we should rather automate this kind of change.

**Comment by TheKhanj** [comment]
Thanks for your responses, I agree, it doesn't worth it😁 When it works don't change it👍:)

**Pull request closed without merging**
