### PR TITLE
[DI] Dump container with HTTPS xsd

### PR DESCRIPTION
**Pull request by ro0NL**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no     
| Deprecations? | no
| Tests pass?   | yes    
| Fixed tickets | #29775 
| License       | MIT
| Doc PR        | symfony/symfony-docs#...

### CODE REVIEW

**Comment by dunglas** [comment]
The fix looks appropriated (and using HTTPS is always better), but the tests must be updated.

**Comment by ro0NL** [comment]
right :) i dont want to add unnecessary effort for mergers. So perhaps it's better to do it globally per branch, 3.4 and up, or keep the legacy.

```
sed -i -E 's/http:\/\/symfony.com\/schema\/dic\/([^\ ]+)\.xsd/https:\/\/symfony.com\/schema\/dic\/\1.xsd/g' src/**/*.{xml,php}
```

**Comment by stof** [comment]
this should indeed be done in 3.4 and up to avoid merge conflicts in the future.

**Comment by ro0NL** [comment]
i was mainly curious if we we want to update all test fixtures and core configs as well...

if it's only for the dumped container, it also qualifies a new feature (but i should fix the tests properly, per case then)

**Comment by chalasr** [comment]
I would update core configs as well. For testing configs I think we don't really care, would be bonus :)

**Comment by nicolas-grekas** [comment]
(rebase needed)

**Comment by fabpot** [comment]
see #30434

**Pull request closed without merging**
