### PR TITLE
fixed CS

### PR DESCRIPTION
**Pull request by fabpot**
| Q | A |
| --- | --- |
| Branch? | 3.1 |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR | n/a |

I submit this one to check that everyone is ok to NOT mix short array notations with long array notations in Symfony even in 3.x. Consistency is better IMHO.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:

**Comment by xabbuh** [comment]
Does this mean that we explicitly do not allow the short array syntax even for new code introduced in 3.0 or higher?

**Comment by fabpot** [comment]
@xabbuh Yes, that's what I propose. There is no consequence is using only the long syntax and it makes code more consistent.

**Comment by xabbuh** [comment]
👍 Fine for me. But we should clarify that in the contribution docs then imo.

**Comment by fabpot** [comment]
Not sure if there is something to change in the documentation as http://symfony.com/doc/current/contributing/code/standards.html already uses `array()` everywhere

**Pull request merged**
