### PR TITLE
Add bulgarian translations

### LINKED ISSUE #41035: Missing translations for Bulgarian (bg)
Hello,

There are some missing translation for Bulgarian (bg). These should be added in branch 4.4. 
See https://github.com/symfony/symfony/issues/38710 for details and [this page](https://symfony-translations.nyholm.tech/#pr) for an example.

These are the files that should be updated: 
- [src/Symfony/Component/Security/Core/Resources/translations/security.bg.xlf](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/Resources/translations/security.bg.xlf)

NOTE: If you want to work on this issue, add a comment to assign it to yourself and let others know that this is already taken.

### PR DESCRIPTION
**Pull request by Warxcell**
| Q             | A
| ------------- | ---
| Branch?       | 4.4
| Bug fix?      | no
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #41035
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Thank you

**Comment by Nyholm** [comment]
Oh no.. I made a mistake. 

Another PR was also adding Bulgarian translations (#41231). Symfony has a rule that if two PRs are doing the same with, we will merge the first one that was opened. I did not follow that rule, Im sorry. 

@Warxcell and @I-Valchev, I see that you didn't use the same translation. Which one is better?

**Comment by I-Valchev** [comment]
Oh, I wasn't aware of that either.

To me, both are equally good, as the words "твърде" and "прекалено", which are different, are synonyms in this context.

Whichever one you use is fine by me! Would be nice to keep the other corrections from my PR, though, especially the grammar issues.

**Comment by Warxcell** [comment]
I was using same wording as other translations, in order to keep them consistent, if you look at: 
Trans unit id=17:
Too many === Твърде много
Trans unit id=19:
Too many === Прекалено много

I think it's better to keep wording consistent accross all the translations. 

Otherwise fixes that @I-Valchev did are good.

**Comment by Nyholm** [comment]
Feel free to open a PR (or update this one) to make them consistent.

**Pull request closed without merging**
