### PR TITLE
[Security] Removed unsed trait import

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Branch?       | 3.4
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by chalasr** [comment]
Seems like it's used actually.

**Comment by lyrixx** [comment]
@chalasr where ? I was not able to find usage and tests are OK

**Comment by chalasr** [comment]
@lyrixx https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Guard/Authenticator/AbstractFormLoginAuthenticator.php#L77 and https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Http/Authentication/DefaultAuthenticationSuccessHandler.php#L110
(tests aren't ok, see travis)

Seems relevant for AbstractFormLoginAuthenticator only starting from 4.1.

**Review by nicolas-grekas — APPROVED** [review]

**Comment by chalasr** [comment]
Good catch, thanks @lyrixx.

**Pull request merged**
